### ISSUE TITLE
Stack hangs on removing state when 'Import from YAML' was used

### ISSUE THREAD

**Issue by pipoe2h** [rancher/rancher#10047]
After import a wrong YAML file and the deployment fails, the stack hangs on removing state when you try to delete it.

If you use the same method but don't add a file and leave the stack empty it is removed successfully after trigger its deletion.

The following manifest is an example with a forced error (apiVersion).

```yaml
apiVersion: apps/v1beta3
kind: Deployment
metadata:
  name: mywebservice-deployment`
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: k8s-deployment-web-1-10
        image: nginx:1.10
        ports:
        - containerPort: 80
```

The attached file shows a bunch of stacks pending to be removed
![image](https://user-images.githubusercontent.com/17649319/31306800-5685e672-ab4f-11e7-8b16-4929981cd19b.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha9` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`containers.index`|
