### ISSUE TITLE
"502 Bad Gateway" response when a target that services 2 port rules is enabled for draining.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10068]
Rancher server version - v1.6-develpment

Steps to reproduce the problem:

Create a service - S1 with drain_timeout_ms set and label say test1=value1.
Create an LB service with following 2 port rules:
Service rule pointing for S1 on port 8000
Selector rule pointing for test1=value1 on port 8100

Make connection on port 8000
After abut 10 secs , make connection to port 8100

While connections are still in progress , upgrade S1.

Connection on  port 8000 succeeds as expected.
Connection on  port 8100  get "502 Bad Gateway" response as soon as the connection on  port 8000 succeeds.

Exported config of the stack for the above configuration:
```
version: '2'
services:
  hello1:
    image: prachidamle/testservice
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  lb-1:
    image: rancher/lb-service-haproxy:v0.7.12
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.create_agent: 'true'
  lb-2:
    image: rancher/lb-service-haproxy:v0.7.12
    ports:
    - 8000:8000/tcp
    - 8100:8100/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.create_agent: 'true'
  hello2:
    image: prachidamle/testservice
    environment:
      SLEEP_INTERVAL: '20000'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      test1: value1
```
rancher-compose
```
version: '2'
services:
  hello1:
    drain_timeout_ms: 25000
    scale: 1
    start_on_create: true
  lb-1:
    drain_timeout_ms: 0
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: hello1
        source_port: 8080
        target_port: 8094
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  lb-2:
    drain_timeout_ms: 0
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        selector: test1=value1
        source_port: 8000
        target_port: 8094
      - priority: 2
        protocol: http
        service: hello2
        source_port: 8100
        target_port: 8094
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  hello2:
    drain_timeout_ms: 25000
    scale: 1
    start_on_create: true
```
