### ISSUE TITLE
Service unavailable after update to rancher 1.6.10 from 1.6.7

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#10062]
I made update from 1.6.7 to 1.6.10 and also all infrastructur updates including kubernetes afterwards.
When i try to execute an easy command that always did work before the update i get the following Error.
Executing command 
```
kubectl -f production-core-pg.svc.yml apply --namespace=default --v=0 --insecure-skip-tls-verify=true
```
bash stderr: serializer for text/plain; charset=utf-8 doesn't exist
Error from server (InternalError): an error on the server ("Service unavailable") has prevented the request from succeeding

Content of production-core-pg.svc.yml
```
apiVersion: v1
kind: Service
metadata:
  name: production-core-pg
  namespace: default
  labels:
    name: production-core-pg
  annotations:
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: production-core-pg
```
If i wait a little this command does work again. The server does not have any big load but still it happens every second time. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|
