### ISSUE TITLE
links to services dont get created if referenced external link doesnt exist

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10070]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Steps to Reproduce:**
Create a stack with the following definition where the external_link isnt present in the environment
```
version: '2'
services:
  thelinker:
    image: ubuntu:14.04.3
    stdin_open: true
    external_links:
    - test/someexternalservice:external
    tty: true
    links:
    - linkedsvc:linkforsvc
    labels:
      io.rancher.container.pull_image: always
  linkedsvc:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
**Results:**

In the api response for the service where external service didnt exist, I see: `linkedServices": null`
in the api response for the service where the external service existed, we see linked services resolvable within the container and linked svc referenced: 
```"linkedServices": {

    "linkedsvc": "1s35"

},```
