### ISSUE TITLE
lb_config priority not parsed in rancher-compose.yml

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#10091]
**Rancher versions:**
rancher/server: 1.6.0 - 1.6.5
rancher/agent: 1.2.2 - 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable): na

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6 - 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.1.0 (4.9.45)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ha w external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. deploy load balancer with selector rules
2. deploy service with lb_config in either docker-compose.yml or rancher-compose.yml

rancher-compose.yml
```sh
version: '2'
services:
  webapp:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: example.com
        path: /
        target_port: 80
        priority: 20
```

**Expected Results:**
rancher-compose.yml
```sh
version: '2'
services:
  webapp:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: example.com
        path: /
        target_port: 80
        priority: 20
```

**Actual Results:**
rancher-compose.yml
```sh
version: '2'
services:
  webapp:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: example.com
        path: /
        target_port: 80
```

**Comment by yamingwa** [comment]
I got the same issue, plus, I found that internal loadbalaner is implemented with a shortest match algorithm when parsing the path attributes.  

For example, for the following `rancher-compose.yml`, both of the requests for `/app` and `/application` will be routed to web1.
```
version: '2'
services:
  web1:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - path: /app
        target_port: 80
  web2:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - path: /application
        target_port: 80
```
