### ISSUE TITLE
CATTLE_AGENT_IP settings for imported clusters

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#10119]
**Rancher versions:**
rancher/server:v2.0.0-alpha10

When importing a cluster CATTLE_AGENT_IP is
1. ) Difficult to set
2. ) Not behaving as expected.

Setup:
2 VMs for K8s worker nodes
Rancher Server running in container on dom0.

When importing the k8s cluster with the kubectl command, both hosts end up showing the docker0 bridge IP as their AgentIP addresses.

As an attempted workaround, instead of running kubectl create -f http://registrationurl.yml

I downloaded the yaml file and attempted to add:
```yaml
- name: CATTLE_AGENT_IP
  valueFrom:
     fieldRef:
       fieldPath: status.hostIP
```

then ran `kubectl create -f ./local_reg.yml`

Execing into one of the agents, I can see CATTLE_AGENT_IP is set correctly, however, the nodes still show up as docker0 bridge inside of Rancher.
