### ISSUE TITLE
When importing k8s manifests, the containers aren't associated to the stack

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10182]
**Rancher versions:** 2.0 master 10/19

**Steps to Reproduce:**
1.  Import the below info
```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 80
```

**Results:**  The Stack is created, but the php-redis containers are placed in the Default Stack.   If I delete the stack that was created (cause it looks empty) it deletes the php containers.
