### ISSUE TITLE
rancher/container-crontab doesn't work - it ignores the cron label and restarts the container every 1h15'

### ISSUE THREAD

**Issue by pgorni** [rancher/rancher#10255]
*Description*
I'm using `rancher/container-crontab:v0.2.0` from the Rancher Library. 
I have a container with `cron.schedule` label set to `0 0 17 ? * THU` so that it runs every Thursday at 17:00. The container's execution mode is set to `start-once` (not `auto restart`).

*What happens*
The container is ran every 1h15'. 
The container's log shows this:
```
02:06:12 AM | INFO | service.update (3 sec) | Updating service
(...)
03:21:14 AM | INFO | service.update (4 sec) | Updating service
(...)
04:36:16 AM | INFO | service.update (3 sec) | Updating service
```
Of course, this doesn't adhere to the cron rule - today's Tuesday, not Thursday.
I can also check the container-crontab's log, which shows the following:
```
31.10.2017 02:06:11time="2017-10-31T01:06:11Z" level=info msg="Removed: 09d7a8c3e7decc1cfafee0017c4ad663f824902f4b8571645e10d3b92e9ff045"
31.10.2017 02:06:14time="2017-10-31T01:06:14Z" level=info msg="Added: bcf1f436b143a145c06d01832b7add733001506e83677e25de0fba004b80b72f, with schedule: 0 0 17 ? * THU"
31.10.2017 03:21:13time="2017-10-31T02:21:13Z" level=info msg="Removed: bcf1f436b143a145c06d01832b7add733001506e83677e25de0fba004b80b72f"
31.10.2017 03:21:16time="2017-10-31T02:21:16Z" level=info msg="Added: 7cc7c792986a64343abe2f5dba4e986a2e727b7c1701c92577e69abd28e95d7b, with schedule: 0 0 17 ? * THU"
31.10.2017 04:36:15time="2017-10-31T03:36:15Z" level=info msg="Removed: 7cc7c792986a64343abe2f5dba4e986a2e727b7c1701c92577e69abd28e95d7b"
31.10.2017 04:36:18time="2017-10-31T03:36:18Z" level=info msg="Added: ecf4de86ae4785187c6c75ed6653a96422c037df44ec9b7113ac4bee22e5bc64, with schedule: 0 0 17 ? * THU"
```

Maybe the `docker-compose.yml` of the container will be helpful:

```
version: '2'
services:
  [snip]:
    image: [snip]
    environment:
      [snip]
    stdin_open: true
    working_dir: /app
    volumes:
    - [snip]
    tty: true
    command:
    - ./main.sh
    labels:
      io.rancher.scheduler.affinity:host_label: disk.resilio=true
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.schedule: 0 0 17 ? * THU
```

*Expected behaviour*
I expect the service to adhere to the cron rule.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`github` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|
