### ISSUE TITLE
stop_signal should not be in export/view config if it has default value

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10287]
**Rancher versions:** 2.0 master 11/7

**Steps to Reproduce:**
1.  Import below yaml
```
version: "2"
services:
  s1:
    image: nginx
```
2.  View or export config

**Results:**  stop_signal is exporting into the config even thou I didn't modify it.  Should not show/export if it's default (SIGTERM)
```
version: "2"
services:
  s1:
    image: nginx
    stop_signal: SIGTERM
```
