### ISSUE TITLE
upgrading a sidekick of a  service having "NetworkMode" set to "container" results in upgraded container have networkMode set to bridge.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10295]
Rancher server - v1.6.11-rc8

Steps to reproduce the problem:
Create a service with sidekick having "NetworkMode" set to "container" using the following yml:
```
version: '2'
services:
  tests:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
    network_mode: container:testp
  testp:
    image: prachidamle/testservice
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: tests
```

From UI, upgrade this service.
Select sidekick ("tests") service to upgrade and upgrade the service.
Upgraded sidekick container is now in "bridge" mode.

secondaryLaunchConfigs sent for upgrade action has the networkMode set to "bridge":

```
networkContainerId
:
"1i101"
networkLaunchConfig
:
"testp"
networkMode
:
"bridge"
```
