### ISSUE TITLE
haproxy stats exporter in HA 

### ISSUE THREAD

**Issue by MartinLeedotOrg** [rancher/rancher#10307]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

In accordance with the [docs](http://rancher.com/docs/rancher/v1.6/en/cattle/adding-load-balancers/) I've selected `Always run one instance of this container on every host` for the scheduling policy for my Load Balancer service.

I'd like to run the [prometheus haproxy exporter](https://github.com/prometheus/haproxy_exporter) to gather stats.

As the stats aren't aggregated, I need to target all my load balancers, by running something like:
```
haproxy-exporter1:
    image: quay.io/prometheus/haproxy-exporter
    command:
    - --haproxy.scrape-uri=http://Public-Loadbalancer-1:9805/;csv
```
But this means modifying the stack every time I add or remove a host.

Any suggestions for how to automate this?

Thoughts:
Set in haproxy:  
```stats socket /run/haproxy/admin.sock mode 660 level admin```
And mount that socket from a haproxy-exporter container

Write a service that enumerates the containers and then starts a haproxy-exporter for each one...

Any other ideas?
