### ISSUE TITLE
Regions - omitting regions in links and not setting regions in LB does not default to current region.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10343]
Rancher versions: Build from https://github.com/alena1108/cattle - "region" branch

Steps to reproduce the problem:
Set up has 3 environments - test1 , test2 , test3.
Create a cross environment service links without specifying regions.
Create Lbs with cross environment targets with portRules not having regions set (but environment set).
environments do not get linked and service and Lb is not functional.

```
root@3dcb6ae18777:/# curl http://rancher-metadata/latest/environments
root@3dcb6ae18777:/#
```

Expected behav

yml used from test1:
```
version: '2'
services:
  lb-1:
    image: kinarashah/lb:finalregions
    ports:
    - 9000:9000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  test1:
    image: sangeetha/testclient
    stdin_open: true
    external_links:
    - test3/stack2/linked1:myweb
    tty: true
    ports:
    - 9001:22/tcp
    labels:
      io.rancher.container.pull_image: always
```

```
version: '2'
services:
  lb-1:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - environment: test2
        priority: 1
        protocol: http
        selector: foo=bar
        source_port: 9000
        target_port: 80
        weight: 100
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  test1:
    scale: 1
    start_on_create: true
```
