### ISSUE TITLE
clusterrolebinding io-rancher-system created with wrong apiVersion in k8s 1.8, prevents dashboard from starting up

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#10351]
**Rancher versions:**
rancher/server: v1.6.11

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.8.3-rancher1

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes + RBAC

**Steps to Reproduce:**
1. Setup Kubernetes env template with RBAC enabled
1. Add a host

**Results:**
1. Dashboard won't come up

```panic: secrets is forbidden: User "system:serviceaccount:kube-system:io-rancher-system" cannot create secrets in the namespace "kube-system"```

We use (https://github.com/rancher/kubernetes-package/blob/v1.8.3-rancher1/package/addons-update.sh#L28):
```apiVersion: rbac.authorization.k8s.io/v1alpha1```

From https://github.com/kubernetes/dashboard/wiki/Access-control#official-release:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
