### ISSUE TITLE
Rancher 1.6.11 - Problem upgrading haproxy  to 0.7.15

### ISSUE THREAD

**Issue by pwilms** [rancher/rancher#10373]
**Rancher versions:**
rancher/server: 1.6.11

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**   Rancher OS 

**Type/provider of hosts: Bare-metal

**Setup details: (single node rancher  with  external DB)**

upgraded rancher 1.6.11. After upgrading existent rancher/lb-service-haproxy:v0.7.9 to rancher/lb-service-haproxy:v0.7.15 through webinterface lb reboots with error.  Deleting and creating new LB works. 

**Environment Template:**
Cattle

**Results:**
New labels are not set.

Logging of `rancher/server`:
```
2017-11-21 00:09:09,906 ERROR [4eb3c71c-3f96-4d66-8cc2-f02d2f5bcbf6:3652] [service:11] [service.update] [] [cutorService-57] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataChangedException: Database record has been changed
2017-11-21 00:09:10,098 ERROR [:] [] [] [] [cutorService-57] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [service.update:3652] on [11] org.jooq.exception.DataChangedException: Database record has been changed
```

**Comment by superseb** [comment]
I believe this should be tested in https://github.com/rancher/rancher/issues/10061, let me check

**Comment by superseb** [comment]
Can you share the compose files of the stack were you encountered this issue?

**Comment by pwilms** [comment]
Of course, here for example with our main loadbalancer. i've added a new one and stopped the "old" instead of migration:

docker-compose.yml 
```yml
version: '2'
services:
  nginx:
    image: nginx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      healthcheck: 'true'
  global-loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 25:25/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  GlobalLoadbalancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 25:25/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  promote-https:
    image: jamessharp/docker-nginx-https-redirect
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      web.https: promote
```
rancher-compose.yml
```yml 
version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
  global-loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs:
      - somecert
      config: |-
        defaults
        log 127.0.0.1:8514 local0 debug
      default_cert: somecert
      port_rules:
      - hostname: '*'
        priority: 1
        protocol: http
        selector: web.http=true
        source_port: 80
        target_port: 80
      - hostname: '*'
        priority: 2
        protocol: https
        selector: web.https=true
        source_port: 443
        target_port: 80
      - priority: 3
        protocol: tcp
        selector: web.smtp=true
        source_port: 25
        target_port: 25
      - hostname: rancher1
        priority: 4
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
      - hostname: rancher2
        priority: 5
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  GlobalLoadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs:
      - somecert
      config: |-
        defaults
        log 127.0.0.1:8514 local0 debug
      default_cert: somecert
      port_rules:
      - hostname: '*'
        path: ''
        priority: 2
        protocol: http
        selector: web.http=true
        source_port: 80
        target_port: 80
      - hostname: '*'
        path: ''
        priority: 3
        protocol: https
        selector: web.https=true
        source_port: 443
        target_port: 80
      - priority: 4
        protocol: tcp
        selector: web.smtp=true
        source_port: 25
        target_port: 25
      - hostname: rancher1
        path: ''
        priority: 5
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
      - hostname: rancher2
        path: ''
        priority: 6
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  promote-https:
    scale: 1
    start_on_create: true
```

**Comment by superseb** [comment]
Ok, so to reproduce I can launch these compose files without the `global-loadbalancer` definition in v1.6.10 and upgrade to v1.6.11 and see the loadbalancer fail to start, correct?

**Comment by superseb** [comment]
We tried reproducing using your stack definition, but couldn't. Did you literally update the loadbalancer and it happened? No rollbacks, restarts, other things that might interfere in the process?

**Comment by pwilms** [comment]
i can reproduce it with our production system, and i try to reproduce it on a test instance right now.

**Comment by pwilms** [comment]
@superseb  I had the chance to reproduce it on a test system.

Tested with digital ocean but behave like baremetal:

1. new instance installed Ubuntu 16.04.3 LTS (4.4.0)
2. installed docker 17.03.2-ce (from your documentation)
3. spinup ranger with external database ``` docker run -d --restart=unless-stopped -p 9999:8080 rancher/server:v1.6.10 --db-host rancher --db-user rancher --db-pass secret --db-name ranchertest```
4.added the same server as bare metal client  ```sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://*********:9999/v1/scripts/D2F61534AAAAAAF496B4:1483142400000:LeOPXYOcYymrqOUkoKntrEflAU```
5. added  a self signed test.key 
6. added the following stack

```
version: '2'
services:
  nginx:
    image: nginx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      healthcheck: 'true'
  GlobalLoadbalancer:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 25:25/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  promote-https:
    image: jamessharp/docker-nginx-https-redirect
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      web.https: promote
```

```
version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
  GlobalLoadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        defaults
        log 127.0.0.1:8514 local0 debug
      default_cert: test
      port_rules:
      - hostname: '*'
        priority: 2
        protocol: http
        selector: web.http=true
        source_port: 80
        target_port: 80
      - hostname: '*'
        priority: 3
        protocol: https
        selector: web.https=true
        source_port: 443
        target_port: 80
      - priority: 4
        protocol: tcp
        selector: web.smtp=true
        source_port: 25
        target_port: 25
      - hostname: rancher1.tovista.eu
        priority: 5
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
      - hostname: rancher2.tovista.eu
        priority: 6
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  promote-https:
    scale: 1
    start_on_create: true
```

7. waited until all is green and shiny
8. stoped rancher-server 
9. spinup new version with external database ``` docker run -d --restart=unless-stopped -p 9999:8080 rancher/server:v1.6.11 --db-host rancher --db-user rancher --db-pass secret --db-name ranchertest``` 
10. waited until all is up
11. upgraded with the little yellow arrow on the frontend. now it's in a weired state:

```
21.11.2017 00:01:41time="2017-11-20T23:01:41Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
21.11.2017 00:01:41471dc628-0d5d-4c59-96f1-a239e95aa360time="2017-11-20T23:01:41Z" level=info msg="Starting Rancher LB service"
21.11.2017 00:01:41time="2017-11-20T23:01:41Z" level=fatal msg="CATTLE_ENVIRONMENT_ADMIN_ACCESS_KEY is not set, fail to init of Rancher LB provider"
```

I'll could you provide access to the test-system if you want to!
