### ISSUE TITLE
LoadBalancer security hole with dual IPs

### ISSUE THREAD

**Issue by khauser** [rancher/rancher#10389]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.1
network-services: v0.2.6
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
one rancher host and one agent
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I have two domains with their IPs:
```
domain1.com 1.2.3.4
domain2.com 1.2.3.5
```
These two IPs point to same host where I bound one LB to each IP (currently by docker-compose, since UI isn't working rightly).
**First Stack:**
docker-compose.yml
```
image: rancher/lb-service-haproxy:v0.7.5
ports:
  1.2.3.4:80:80/tcp
```
with rancher-compose.yml
```
      port_rules:
      - hostname: domain1.com
        priority: 1
        protocol: http
        selector: tool=tool1
        source_port: 80
        target_port: 80
```
and
**Second Stack:**
docker-compose.yml
```
image: rancher/lb-service-haproxy:v0.7.5
ports:
  1.2.3.5:80:80/tcp
```
with rancher-compose.yml
```
      port_rules:
      - hostname: domain2.com
        priority: 1
        protocol: http
        selector: tool=tool2
        source_port: 80
        target_port: 80
```
**Results:**
Doing a `curl domain1.com` would lead us to tool1 and `curl domain2.com` to tool2.

**Why we do use two IPs on one host?**
We want to restrict some of our users to only some of our tools. For this we do have a firewall rule for _1.2.3.4_ where all tools behinds are allowed to be accessed. And one for _1.2.3.5_ where some client IPs are denied.

The Problem now is that one of our security guys had tried something (so bad, they always try things ;)). He added this line to the `/etc/hosts` of a client which should be denied:
`1.2.3.4 domain2.com`
When doing a curl now on this domain he does have access to tool2, but he shouldn't. Not because of the firewall, since there only IPs could be verified, but on rachner site, since I there bound tool2 to _1.2.3.5_. 

Could this be a bug or are we doing something wrong?

I hope I explained our problem well.

Best
Karsten
