### ISSUE TITLE
Rancher discards any customized labels when set compute=true?

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#10381]
**Rancher versions:** V1.6.10
Kubernetes version: v1.7.4-rancher2

Hi, all

I have my kubernetes cluster with plane enabled, for compute hosts, I labelled them with compute=true and app=tests, then defined my pods with nodeselector app=tests, but found they were not scheduled, by "kubectl edit node xxx", found there're no label app=test there? Can anyone tell me how to add customized labels to compute nodes? Thanks.

labels of compute node:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-11-21T05:23:07Z
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: rancher
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: Region1
    failure-domain.beta.kubernetes.io/zone: FailureDomain1
    kubernetes.io/hostname: ubuntu
```
