### ISSUE TITLE
[cli] Is there a list of available variables for use in the compose file? Like {{.Stack.Name}}, {{.Scale.Id}}

### ISSUE THREAD

**Issue by senica** [rancher/rancher#10430]
Is there a list of all available variables allowed?

I'm really looking for one that will let give me the scale number as I have a service that I have to define the hostname

http://rancher.com/docs/rancher/latest/en/cli/variable-interpolation/

```
neo4j:
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
    - NEO4J_dbms_connector_bolt_advertised__address=hosts-neo4j-{{.Count}}:7687
```
Doing it manually does not work well with scale at all.
