### ISSUE TITLE
Webhook upgrade is breaking nginx service (Working with rancher-compose upgrade)

### ISSUE THREAD

**Issue by nmacherey** [rancher/rancher#10468]
Hi,

It seams that rancher webhook is not properly handling service upgrades (I may be doing some wrong things...). The nginx systematically generate a 503 after upgrading the service via Webhook while doing it via the command line using rancher-compose is working like a charm...

The webhook is configured to upgrade the full stack when the "latest" tag is pushed and for services matching the label: 

wakeonweb.image-pushed: contrat-client

The docker-compose file:

```yaml
version: '2'
services:
    contrat-client-app:
        image: wakeonweb/contrat-client:latest
        volumes:
            - /var/www/project
        expose:
            - 9000
        labels:
            wakeonweb.image-pushed: contrat-client
            io.rancher.container.pull_image: always
            io.rancher.container.start_once: true

    contrat-client-nginx:
        image: wakeonweb/contrat-client-nginx:latest
        volumes_from:
            - contrat-client-app
        ports:
            - "80:80/tcp"
        expose:
            - 80
        labels:
            io.rancher.sidekicks: contrat-client-app
            wakeonweb.image-pushed: contrat-client
            io.rancher.container.pull_image: always
            io.rancher.service.external_lb.endpoint: sit
```
And the rancher-compose file

```yaml
version: '2'
services:
  contrat-client-app:
    scale: 1
    start_on_create: true
  contrat-client-nginx:
    scale: 1
    start_on_create: true
```

In addition, if I add a Global Load Balancer instead of exposing the nginx port, on any upgrade with --force-upgrade the service is down.

Here is the docker-compose file generated by the UI:

```yaml
version: '2'
services:
  load-balancer:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.service.external_lb.endpoint: sit
```
And the load balancer rancher-compose file:

```yaml
version: '2'
services:
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: contrat-client/contrat-client-nginx
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
```

Upgrade are made using the folliwing command:

rancher-compose --project-name ${COMPSE_PROJECT_NAME} --file ${COMPSE_FILE} --rancher-file ${RANCHER_COMPOSE_FILE} --url ${RANCHER_URL} --verbose up --force-upgrade --pull -d -c

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.12` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|
