### ISSUE TITLE
Service link DNS resolution takes some time to be available after containers (re)creation

### ISSUE THREAD

**Issue by eesprit** [rancher/rancher#10476]
**Rancher versions:**
rancher/server: 1.6.12
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.2.1
network-services: 0.2.7
scheduler: 0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:48 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian Stretch (9) 64 bits - Linux Kernel 4.9.0-4-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
XenServer VMs

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, external databases, 3 agent nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a "test" stack, with 2 services, the second one having the first one as a service link.
The second service is configured to ping the other service using the service link alias.

You can use the following templates to create such a test stack :

*docker-compose.yml*
```yaml
version: '2'
services:
  service2:
    image: tutum/dnsutils
    stdin_open: true
    tty: true
    links:
    - service1:target
    command:
    - ping
    - -c
    - '1000'
    - target
    labels:
      io.rancher.container.pull_image: always
  service1:
    image: tutum/dnsutils
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

* rancher-compose.yml
```yaml
version: '2'
services:
  service2:
    scale: 1
    start_on_create: true
  service1:
    scale: 1
    start_on_create: true
```

**Results:**
After the creation of the service2 container, the container fails because it can't resolve the name "target" (not all the time, but definitely more then 50%). If restarted, it works fine. If deleted and another container is re-created, it will also fail, and it will work after restart.

Changing the command to ping the FQDN of the other service seems to always work.
(you can test by updating the service2 command to : ping -c 1000 service1.test.rancher.internal)

It looks like :
- the container is created
- it obtains an IP / interface in the managed network
- the process is started inside the container
- the service links is not yet in place, so the DNS resolution fails
- the service link is in place
- if restarted, the service link is already in place, so it is OK

We never had this problem with previous Rancher versions (our environment was in 1.6.7 before upgrading to 1.6.12). We also have a 1.5.9 version wich does not have this problem.
With this version, this problems manifest almost all the time a service is created or updated (and of course if it tries to resolve another service early in its run process).

**Expcected**
Service link to be resolvable before the process is started
