### ISSUE TITLE
Services created with direct Endpoints cannt work in lb-controller

### ISSUE THREAD

**Issue by meggarr** [rancher/rancher#10497]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: 1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.02

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
I want to create a LB from Elasticsearch cluster outside of Rancher/Kubernetes. So I create an ingress, service, and endpoints, like below. My intent is to use the endpoints directly, and let LB Controller to setup backends for those endpoints. but it does not work.
```
kind: Ingress
metadata:
  namespace: cloud
  name: es
  annotations:
    http.port: "9200"
    config: "defaults\ntimeout client 10m\ntimeout server 10m\n"
    io.rancher.scheduler.affinity.host_label: "eslb=true"
spec:
  backend:
    serviceName: es
    servicePort: 9200
---
kind: Service
apiVersion: v1
metadata:
  namespace: cloud
  name: es
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: cloud
  name: es
subsets:
  - addresses:
      - ip: 10.245.247.180
    ports:
      - port: 9200
  - addresses:
      - ip: 10.245.247.204
    ports:
      - port: 9200
```

**Results:**
There's no backend in the HAProxy LB for those endpoints
