### ISSUE TITLE
Rancher Require container label on host are not taken into account

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#10490]
**Rancher versions:**
rancher/server: 1.6.11
rancher/agent: 1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.13.5
network-services: v0.7.18
scheduler: 0.8.2

When hosts have **require container label** them they are not taken into account.

I have 2 hosts:
* host 1 label: `com.appli=true`
* host 2 label: `com.monitoring=true`

I have 2 fake stacks:

1 application:
```
version: '2'
services:
  demo-app:
    image: ubuntu
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      com.appli: 'true'
```

1 monitoring:
```
version: '2'
services:
  monitor:
    image: ubuntu
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      com.monitoring: 'true'
```

It's the same with shorter labels: `com.appli`

This results in all the application scheduled on the same host, or randomly placed without using the host require container label

![capture du 2017-12-07 10-57-06](https://user-images.githubusercontent.com/1558372/33709715-8db0385e-db3e-11e7-82c2-2196e3b3c708.png)
