### ISSUE TITLE
[Vault] Containers with volumes in vault-volume-driver  are not able to migrate to a different host when host is powered down/deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10517]
Rancher versions: Build from v1.6-development

Steps to reproduce the problem:
Have a setup with 2 hosts.
Deploy "vault-volume-driver" using catalog https://github.com/cloudnautique/rancher-catalog - branch add_vault_volume_driver

Create a service using volumes in vault-volume-driver using the following yml:
```
version: '2'
volumes:
  vault-token:
    driver_opts:
      policies: mypolicy1
    driver: vault-volume-driver
    per_container: true
services:
  testing:
    image: alpine
    stdin_open: true
    volumes:
    - vault-token:/testing
    tty: true
    command:
    - sh
```

Once service container is running successfully , deactivate the host where the container is running.
Delete the container.
Not able to start the container in the other host .
Allocation fails with following error message -  ```(Failed to allocate instance [container:1i78]: Bad instance [container:1i78] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1].) ```

**Comment by cloudnautique** [comment]
falls under the #10500 umbrella

**Comment by sangeethah** [comment]
Another scenario that breaks:
Rancher versions: Build from v1.6-development

Steps to reproduce the problem:
Have a setup with 2 hosts.
Deploy "vault-volume-driver" using catalog https://github.com/cloudnautique/rancher-catalog - branch add_vault_volume_driver

Create a service using volumes in vault-volume-driver using the following yml:
```
version: '2'
volumes:
  vault-token:
    driver_opts:
      policies: mypolicy1
    driver: vault-volume-driver
    per_container: true
services:
  testing:
    image: alpine
    stdin_open: true
    volumes:
    - vault-token:/testing
    tty: true
    command:
    - sh
```
Once service container is running successfully , delete the host were the container is running.
Container is not able to migrate to another host in the environment.

Following error seen:

```Unhealthy (Failed to allocate instance [container:1i667]: Bad instance [container:1i667] in state [erroring]: Allocation failed: volume [663] must have exactly these pool(s): [12], valid host(s) [])```
