### ISSUE TITLE
Health check service instance stuck in "reinitializing" state forever when docker is rebooted on the host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10556]
Rancher server version - Build from 1.6 branch
Steps to reproduce the problem:
Had a setup with 3 hosts.
restart docker on one of the hosts.
Even after docker is restarted, Health check service instance gets stuck in "reinitializing" state forever.

Service container logs: 
```12/13/2017 1:47:13 PMtime="2017-12-13T21:47:13Z" level=error msg="Failed to read stats: dial unix /var/run/haproxy.sock: connect: connection refused"
12/13/2017 1:47:15 PMtime="2017-12-13T21:47:15Z" level=error msg="Failed to read stats: dial unix /var/run/haproxy.sock: connect: connection refused"
12/13/2017 1:47:17 PMtime="2017-12-13T21:47:17Z" level=error msg="Failed to read stats: dial unix /var/run/haproxy.sock: connect: connection refused"```
```

Health check service  does not have any initializing/reinitializing timeouts set.

**Comment by deniseschannon** [comment]
@alena1108 @kinarashah Can we add some timeouts for the service?

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher-catalog/pull/1034

**Comment by deniseschannon** [comment]
Available in the `v0.3.3-1` healthcheck template

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.6.13-rc4.

This issue is not seen anymore. health_check service instances have initializing_timeout and reinitializing_timeout set now.

```
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```
