### ISSUE TITLE
Catalog allows ability to use same sidekick for 2 different primary services, which is invalid use case. 

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10563]
**Rancher versions:**
rancher/server: 1.6.10
rancher/agent: 1.2.6

When trying to use `rancher up` to create a stack that is accepted in catalog, CLI throws errors

```
someboxR:test1176 ahmad$ rancher  up -s ahmad-8
INFO[0000] Creating stack ahmad-8
INFO[0000] Creating volume template yoyo-storage-volume
INFO[0000] [yoyo-client]: Creating
INFO[0000] [yoyo-data]: Creating
INFO[0000] [yoyo-primary]: Creating
INFO[0000] Creating service yoyo-client
INFO[0000] Creating service yoyo-primary
INFO[0000] Creating service yoyo-data
ERRO[0001] Failed Creating yoyo-data : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, baseType=error, code=NotUnique] from [https://my-server.yay/v2-beta/projects/1a5/services]
INFO[0001] [yoyo-primary]: Created
INFO[0001] [yoyo-client]: Created
INFO[0001] [yoyo-sysctl]: Creating
INFO[0001] [yoyo-storage]: Creating
INFO[0001] [yoyo-sysctl]: Created
INFO[0001] [yoyo-storage]: Created
ERRO[0001] Failed to start: yoyo-data : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, baseType=error, code=NotUnique] from [https://my-server.yay/v2-beta/projects/1a5/services]
FATA[0001] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, baseType=error, code=NotUnique] from [https://my-server.yay/v2-beta/projects/1a5/services]```

**Comment by aemneina** [comment]
I believe the real issue here is that one cant have more than one service reference the same sidekick. The stack that was attempted had this characteristic, its easy to reproduce with a basic example:

```
version: '2'
services:
  thesidekick:
    image: busybox
    stdin_open: true
    tty: true
  thesvc:
    image: busybox
    stdin_open: true
    tty: true
    labels:
      io.rancher.sidekicks: thesidekick

  somesvc:
    image: busybox
    stdin_open: true
    tty: true
    labels:
      io.rancher.sidekicks: thesidekick
```

If this isnt supported we should call out the relationship characteristics of services to a sidekick.
