### ISSUE TITLE
[Pipeline] Mixed logs information 

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10640]
**Rancher versions:**
rancher/server:v1.6.13
rancher/agent::v1.2.8

**Infrastructure Stack versions:**
pipeline:v0.1.0

**Steps to Reproduce:**
1. Create a pipeline with yml below
```yml
name: test
isActivate: false
cronTrigger:
  timezone: Asia/Hong_Kong
stages:
- name: Source Code Management
  steps:
  - type: scm
    repository: <your-repository>
    branch: master
    gitUser:  <git-user>
- name: test
  steps:
  - type: task
    image: busybox
    shellScript: ls
  - type: task
    image: busybox
    shellScript: ls -al
```
2. Run this Pipeline.

3. After Success of this pipeline, Switch logs between step 1 and 2 under stage 'test'

4. Repeat Reproducing Step 3.

**Results:**
The logs can't be changed after Step 4 .
