### ISSUE TITLE
Fail on upgradeStack step using ${CICD_GIT_COMMIT} variable as image tag

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#10695]
**Rancher versions:**
rancher/server: v1.6.13
rancher/agent: v1.2.8

**Pipeline version: v0.1.0**

**Steps to Reproduce:**
Run a pipeline with similar definition as follows:
```
name: test
isActivate: true
cronTrigger:
  timezone: Asia/Hong_Kong
stages:
- name: Source Code
  steps:
  - type: scm
    repository: http://git.example.com/test/test.git
    branch: master
    gitUser: gitlab:root
- name: package
  steps:
  - type: build
    dockerFileContent: |-
      FROM nginx
      RUN echo hi
    buildPath: .
    dockerFilePath: ./Dockerfile
    targetImage: nginx:${CICD_GIT_COMMIT}
- name: upstack
  steps:
  - type: upgradeStack
    stackName: test
    dockerCompose: |-
      services:
        ngx:
          image: nginx:${CICD_GIT_COMMIT}

```
**Results:**
Fail in upgrade stack step:
```
level=error msg="parse yaml got error:yaml: line 2: mapping values are not allowed in this context, please check file format:\nservices:\n  ngx:\n    image: nginx:\n" 
level=fatal msg="yaml: line 2: mapping values are not allowed in this context" 
Build step 'Execute shell' marked build as failure
```
