### ISSUE TITLE
ranport2.0 preview hostport does not work

### ISSUE THREAD

**Issue by Anteoy** [rancher/rancher#10691]
**Rancher versions:**
2.0 preview
in my traefik yaml:
`- image: traefik:v1.4.3
        name: traefik-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080`
and I try another images to test hostPort:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: class100-ops
  labels:
    app: busybox-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: busybox-pod
    spec:
      containers:
        - name: webapp
          image: training/webapp
          ports:
          - name: http
            containerPort: 5000
            hostPort: 65000
```
The all hostPort does not work,Is the current 2.0 preview does not support it？Or I need to  install any other plugins?
