### ISSUE TITLE
NFS - Subfolder does not get created when custom export/host driver opts are provided.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10727]
Rancher versions:
rancher/server:v1.6.12-flexvol
NFS driver Version: daishan1992/storage-nfs:dev

Steps to reproduce the problem:
Create a service with nfs volume driver providing custom export/host driver opts.
The root export path gets mounted.

Expected behavior is to have a subfolder (with volume name) created on the NFS server and this volume gets mounted

yml used:

```
version: '2'
volumes:
  yello11:
    driver_opts:
      export: /var/nfs
      host: <hostip>
      no_subfolder: 'false'
    driver: rancher-nfs
services:
  nginx1:
    image: nginx
    volumes:
    - yello11:/data1
```

The same behavior is also seen when no_subfolder option is not set.
