### ISSUE TITLE
[Pipeline] Pipeline UI is in waiting page 

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#10738]
**Rancher versions:**
rancher/server:v1.6.13
rancher/agent:v1.2.8

**Pipeline Stack versions:**
pipeline: v0.1.0

**Steps to Reproduce:**
1. Set up a new cattle environment with the only pipeline stack. and check that pipeline-ui is accessible.
2. Log into the host of the environment in step 1, then run `mkdir atest && cd atest`, here we want to ensure that name of the created stack sorted at the first position of stack list.
3. Set up any service through `docker-compose up` under dir `atest`.
For examples, you can use the `docker-compose.yml` below
```yml
version: '2'
services:
  web:
    container_name: a-test
    restart: always
    image: ghost
    ports:
      - "2368:2368"
```

4. Get into pipeline-ui again and refresh it. 

**Results:**
`pipeline-ui` shows just waiting. like
![image](https://user-images.githubusercontent.com/9334435/34561495-44245ee2-f185-11e7-844f-f59a357bace9.png)
