### ISSUE TITLE
Rancher server doesn't map ports for container with managed network

### ISSUE THREAD

**Issue by ynnt** [rancher/rancher#1084]
When I create docker container with managed network and port mapping to host ip it seems like rancher network agent does not map port for this container.
docker ps
![screen shot 2015-06-08 at 3 16 21 pm](https://cloud.githubusercontent.com/assets/12729981/8034549/64e92484-0df1-11e5-8d91-0ffd0f3a9edd.png)
Screenshot from rancher server 
![screen shot 2015-06-08 at 3 17](https://cloud.githubusercontent.com/assets/12729981/8034617/ef55a11a-0df1-11e5-8208-920f457b2beb.png)
Network agent:
```
root@d5ffcf0b421f:/# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:isakmp
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ipsec-nat-t
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
```
```
root@d5ffcf0b421f:/# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  10.42.0.1            anywhere
```

**Comment by will-chan** [comment]
Which version of rancher/server are you using? If you docker inspect your rancher/server container, it should tell you.

**Comment by anapsix** [comment]
same here.. Started a stack with `rancher-compose start`:
```
#docker-compose.yml44
haproxy:
  image: 'tutum/haproxy:0.1'
  environment:
    - BACKEND_PORT=7379
  links:
    - 'webdis'
  ports:
    - '8000:80'
    - '1936:1936'
webdis:
  image: 'anapsix/webdis'
  ports:
   - '7379:7379'
  links:
   - 'redis'
redis:
  image: 'anapsix/redis:latest'
```

No ports are mapped on `tutum/haproxy` container:
```
[rancher@nick ~]$ docker ps 
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES
6931f34ce44b        tutum/haproxy:0.1               "/run.sh"              45 seconds ago      Up 44 seconds       80/tcp, 443/tcp, 1936/tcp                      6cfcdfd1-2ba0-4aa7-97ba-d08ea660246f  
```

Yet, UI claims they are mapped.. Also, Rancher misidentifies public ip as `172.17.42.1`
![image](https://cloud.githubusercontent.com/assets/1256199/8802695/23208e5e-2f91-11e5-9828-9ede46625de0.png)
