### ISSUE TITLE
Import from YAML truncate environmental variable

### ISSUE THREAD

**Issue by lingzhang-lyon** [rancher/rancher#10920]
When we try to use Import from YAML to create stack, if the environmental variables have "=", it will be truncated. 

example of docker-compose.yml
```
version: "2"
services:
  ubuntu-test:
    environment:
    - MONGO_URL=mongodb://hello:test@host1:27017,host2:27017,host3:27017/test-db?ssl=true&authSource=admin&replicaSet=test-shard-0
    image: ubuntu:xenial
```

after import the compose.yml showing in UI would be like
```
version: "2"
services:
  ubuntu-test:
    environment:
    - MONGO_URL=mongodb://hello:test@host1:27017,host2:27017,host3:27017/test-db?ssl
    image: ubuntu:xenial
    stop_signal: SIGTERM
```
also the container keep regenerating, showing error like `Error on container (1i146): no such file or directory`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha10` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`new-stack`|
