### ISSUE TITLE
[UI] Show which machines are schedulable/un-schedulable. 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#10980]
with the newer version of rke, kubelet unschedulable will start with nodes that has only etcd roles, i think an unschedulable flag should be added to machine resources so that the UI can read it, also it should be excluded from aggregated stats calculation

**Comment by aiwantaozi** [comment]
@galal-hussein Is there any other entry user could set the unschedule, or when user select only etcd role for the node then rke will automatically set unschedule?

I  check the node with only etcd role now will have taints like below, is this what you want to add to node, and let UI show?
```
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      node-role.kubernetes.io/etcd: "true"
  spec:
    externalID: node1
    podCIDR: x.x.x.x/24
    taints:
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      timeAdded: 2018-03-21T06:51:08Z
      value: "true"
```
