### ISSUE TITLE
Tweaks to get a node on same host as management server 

### ISSUE THREAD

**Issue by brianclements** [rancher/rancher#1107]
Following the directions on the readme, I have some additional tweaks I need to do to get a node on the same host as the management server.

Using this docker-compose.yml:

```yaml
rancherData:
  image: "rancher/server"
  command: "tail -f /dev/null"
rancherServer:
  image: "rancher/server"
  volumes_from:
    - rancherData
  ports:
    - "3000:8080"
rancherClient:
  image: "rancher/agent:v0.7.9"
  command: "http://mnemosyne.bcnet:3000/v1/scripts/958BCECEB9B69C922130:1433829600000:ClhCbanDEhynfNDJfLfiLj2Os"
  privileged: true
  environment:
    CATTLE_AGENT_IP: "192.168.3.5"
  # net: "host"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
```
First what happened was that my domain name couldn't work:
```
INFO: Attempting to connect to: http://mnemosyne.bcnet:3000/v1
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
ERROR: http://mnemosyne.bcnet:3000/v1 is not accessible
```
replacing that with `localhost:3000` did the trick. Not sure why, maybe because the dns routing didn't make it's way into the container? In any case, once I do that, I get further but now whatever this is happens:

```
○ docker-compose up rancherClient
Creating level1_rancherClient_1...
Attaching to level1_rancherClient_1
rancherClient_1 | 
rancherClient_1 | INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.3.5:3000/v1
rancherClient_1 | INFO: Checking for Docker version >= 1.6.0
rancherClient_1 | INFO: Found Server version: 1.6.2
rancherClient_1 | INFO: docker version: Client version: 1.6.0
rancherClient_1 | INFO: docker version: Client API version: 1.18
rancherClient_1 | INFO: docker version: Go version (client): go1.4.2
rancherClient_1 | INFO: docker version: Git commit (client): 4749651
rancherClient_1 | INFO: docker version: OS/Arch (client): linux/amd64
rancherClient_1 | INFO: docker version: Server version: 1.6.2
rancherClient_1 | INFO: docker version: Server API version: 1.18
rancherClient_1 | INFO: docker version: Go version (server): go1.4.2
rancherClient_1 | INFO: docker version: Git commit (server): 7c8fca2
rancherClient_1 | INFO: docker version: OS/Arch (server): linux/amd64
rancherClient_1 | INFO: docker info: Containers: 3
rancherClient_1 | INFO: docker info: Images: 254
rancherClient_1 | WARNING: No swap limit support
rancherClient_1 | INFO: docker info: Storage Driver: btrfs
rancherClient_1 | INFO: docker info: Execution Driver: native-0.2
rancherClient_1 | INFO: docker info: Kernel Version: 3.13.0-53-generic
rancherClient_1 | INFO: docker info: Operating System: Ubuntu 14.04.2 LTS
rancherClient_1 | INFO: docker info: CPUs: 4
rancherClient_1 | INFO: docker info: Total Memory: 3.851 GiB
rancherClient_1 | INFO: docker info: Name: mnemosyne
rancherClient_1 | INFO: docker info: ID: S7PD:EJ3S:NDXY:3FP3:LLCX:NM3O:2YRJ:BKFJ:PCM3:CTNO:ND2P:PYUO
rancherClient_1 | INFO: Attempting to connect to: http://192.168.3.5:3000/v1
rancherClient_1 | INFO: http://192.168.3.5:3000/v1 is accessible
rancherClient_1 | INFO: Inspecting host capabilities
rancherClient_1 | INFO: System: false
rancherClient_1 | INFO: Host writable: true
rancherClient_1 | INFO: Token: xxxxxxxx
rancherClient_1 | INFO: Running registration
rancherClient_1 | Traceback (most recent call last):
rancherClient_1 |   File "./register.py", line 11, in <module>
rancherClient_1 |     secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
rancherClient_1 |     return gdapi.from_env(prefix=prefix, factory=Client, **kw)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
rancherClient_1 |     return _from_env(prefix=prefix, factory=factory, **args)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env
rancherClient_1 |     return factory(**result)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
rancherClient_1 |     super(Client, self).__init__(*args, **kw)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
rancherClient_1 |     self._load_schemas()
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_schemas
rancherClient_1 |     response = self._get_response(self._url)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 258, in _get_response
rancherClient_1 |     headers=self._headers)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
rancherClient_1 |     return self.request('GET', url, **kwargs)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
rancherClient_1 |     resp = self.send(prep, **send_kwargs)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
rancherClient_1 |     r = adapter.send(request, **kwargs)
rancherClient_1 |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
rancherClient_1 |     raise ConnectionError(err, request=request)
rancherClient_1 | requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
level1_rancherClient_1 exited with code 1
```

And lastly, to fix this, I have to run the rancher agent container with the `--net host` option and it boots up normally. Note that I haven't noticed any effect by setting or unsetting `CATTLE_AGENT_IP`. This is the working docker-compose.yml:

```yaml
rancherData:
  image: "rancher/server"
  command: "tail -f /dev/null"
rancherServer:
  image: "rancher/server"
  volumes_from:
    - rancherData
  ports:
    - "3000:8080"
rancherClient:
  image: "rancher/agent:v0.7.9"
  command: "http://localhost:3000/v1/scripts/958BCECEB9B69C922130:1433829600000:ClhCbanDEhynfNDJfLfiLj2Os"
  privileged: true
  # environment:
    # CATTLE_AGENT_IP: "192.168.3.5"
  net: "host"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
```
