### ISSUE TITLE
UI for ingress controller for RKE cluster 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11267]
Ingress controller is enabled in types and rke, we need to give user a UI option to enable/disable it, similar to networkplugin/auth.

**Comment by loganhz** [comment]
can not find the ingress controller related field in `/v3/schemas/rancherKubernetesEngineConfig` with `rancher/server:master`.  Which field should I use for the ingress controller option?

**Comment by loganhz** [comment]
@alena1108 Can I have a payload example for it?

**Comment by galal-hussein** [comment]
@loganhz ingress is enabled by default in rke, and can be customized as following:
```
ingress:
  provider: nginx
  options:
    map-hash-bucket-size: "128"
    ssl-protocols: SSLv2
```
options are described in the official [documentation](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md) of nginx ingress controller
