### ISSUE TITLE
Load balancer never initialises, hangs on "Waiting for metadata self service"

### ISSUE THREAD

**Issue by 0xdeafcafe** [rancher/rancher#11275]
**Rancher versions:**
rancher/server: `v1.6.14`
rancher/agent: `v1.2.9`

**Infrastructure Stack versions:**
healthcheck: `v0.3.3`
ipsec: `v0.13.7`
network-services: `v0.7.19`
scheduler: `v0.8.3`
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Containers: 75
 Running: 74
 Paused: 0
 Stopped: 1
Images: 46
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 518
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1020-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: dev-a2
ID: RARH:CC63:BXE4:7HES:VDPX:QTMS:YCRR:IKEG:VWDR:G6BV:YAXG:V5VZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8

```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-1020-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When we updated rancher to the latest stable build, one of our load balancers just stopped starting, and repeatedly outputs to the console `02/02/2018 11:40:15 Waiting for metadata self service`. Strangely it only does this to one of the load balancers we run.

**Results:**
I dug around and saw this code was only introduced on October 17th in this [PR](https://github.com/rancher/lb-controller/pull/103). I've posted the load balancer config files below:

docker-compose.yml
```
version: '2'
services:
  lb-external:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  lb-internal:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 81:81/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
```

rancher-compose.yml - (Each LB has about 40 services running on it, but I've trimmed them down)
```
version: '2'
services:
  lb-external:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - { protocol: http, source_port: 80, target_port: 80, hostname: service-admin.dev.ext.cuvva.co, service: dev/service-admin }
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  lb-internal:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - { protocol: http, source_port: 81, target_port: 80, hostname: service-admin.dev.int.cuvva.co, service: dev/service-admin }
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

```
