### ISSUE TITLE
Loadbalancer in stack will spawn continuously when doing rollback on services created with batch-size=1

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#11304]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: 0.2.2
network-services: v0.2.8
scheduler: v0.8.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3, `4.4.0-112-generic`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Download CLI v0.6.7
1. Use the following stack definition
`docker-compose.yml`
```
version: '2'
services:
  nginx:
    image: nginx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
```

`rancher-compose.yml`
```
version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
  lb:
    scale: 2
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
```
1. Run an upgrade on this stack using `batch-size=1`: `rancher up -d --force-upgrade --batch-size=1 --interval=2000`
1. Rollback the stack using `rancher up -d -r`

**Results:**
Service `nginx` will rollback fine, lb will continue spawning new lb's and will never finish. Problem does not occur when `batch-size=1` is omitted from the command.
