### ISSUE TITLE
Unable to create loadbalancer backend pointing to internal ip

### ISSUE THREAD

**Issue by giovannicandido** [rancher/rancher#11477]
Unable to create loadbalancer pointing to internal ip

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 
network-services:
scheduler:
kubernetes (if applicable): 1.8.5-rancher1

**Docker version: (`docker version`,`docker info` preferred)**

```

Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: k8s2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Proxmox VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

Create a service pointing to a external IP
```
kind: Service
apiVersion: v1
metadata:
  name: artifactory-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
---
kind: Endpoints
apiVersion: v1
metadata:
  name: artifactory-service
subsets:
  - addresses:
      - ip: 192.168.x.x
    ports:
      - port: 8081
```

Create a ingress load balancer

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-lb
  annotations:
    io.rancher.scheduler.affinity.host_label: "external-ip=true"
spec:
  rules:
  - host: artifactory.foo.com
    http:
      paths:
      - backend:
          serviceName: artifactory-service
          servicePort: 80
```

**Results:**

Acessing the lb host ip result in

` 
503 Service Unavailable
No server is available to handle this request. 
`

Executing a kubernetes pod and using curl to access **artifactory-service** works:

```
kubectl run --rm -it alpine --image alpine -- ash
apk --update add curl
curl artifactory-service
``` 

Returns the external service response

Reference from kubernetes:

https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by giovannicandido** [comment]
Same problem using Service type externalName:

```
kind: Service
apiVersion: v1
metadata:
  name: artifactory-named-service
spec:
  type: ExternalName
  externalName: artifactory.internal.xxx.com
```
