### ISSUE TITLE
[err-msg] Bad response statusCode ...

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#11509]
**Rancher versions:**
1.6.5+

**Symptom:**
Bad response statusCode ... It appears these errors are bubbled up from the API with no user-friendly mapping. This can happen under several different types of conditions. Our most specific example is when a `volumes_from` was used without a sidekick. However, it is not limited to this condition, we have also seen PortWrongFormat, 

**Expected behavior:**
The message should indicate exactly what went wrong. E.g. "a target of volumes_from must be configured as a sidekick"

**Comment by jambajaar** [comment]
@leodotcloud -- More details on the example provided:

My guess is that these are bubbling up from the API when ports are bound.

When searching the Rancher UI code, there are a few places `statusCode` is used:
https://github.com/rancher/ui/search?utf8=%E2%9C%93&q=statusCode&type=

Testing spinning up a container with volumes_from without using a sidekick.

Error seen is:

```
Error (Bad response statusCode [422].
Status [422 status code 422].
Body: [baseType=error, code=InvalidReference, fieldName=LaunchConfigName] 
from 
[http://localhost:8080/v2-beta/projects/1a439/services])
```
Above was triggered with YML:

```
portal:
  image: nginx 
  volumes_from:
    - portal-data
  expose:
    - "7080:7080"
portal-data:
  image: nginx
  volumes:
    - /home/packet/portal
nginx-portal:
  image: nginx
  expose:
    - "9080:80"
  links: 
    - portal
    - portal-data
  volumes_from:
    - portal-data
Portal-LB:
  restart: always
  ports:
    - "443:9080"
  image: rancher/load-balancer-service
  links:
    - nginx-portal:nginx-portal
```
