### ISSUE TITLE
Custom runtime-config arguments in kubernetes project-template

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#11587]
You can think about this request as **futureproofing kubernetes project-template by supporting custom runtime-config arguments**.

I would like to enable [admissionregistration.k8s.io/v1alpha1](https://kubernetes.io/docs/admin/extensible-admission-controllers/) for kubernetes.

This feature circumvents the need to [turn on admission controllers via kube-api arguments](https://kubernetes.io/docs/admin/admission-controllers/#how-do-i-turn-on-an-admission-controller) which is not possible in project template. And injecting configuration files into kube-api containers via rancher-compose would prove even more challenging.

That way we the users can enable alpha/beta features at our own peril.

**Rancher versions:**
rancher/server: 1.6.14

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.8.5

Like-minded forum post https://forums.rancher.com/t/how-to-enable-kubernetes-initializers-alpha-feature-in-rancer/8103

**Comment by wangshuaizs** [comment]
Has rancher supported feature-gate ?

**Comment by gretel** [comment]
this seems to be quite important to me - anything we could do to progress on this issue?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by askldjd** [comment]
In Rancher 2.x, you can edit the cluster config YAML file. Here is an example to use the `enable-admission-plugins` flag.

```yaml
services:
  kube-api: 
    extra_args: 
      enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
      runtime-config: "admissionregistration.k8s.io/v1alpha1"
```
