### ISSUE TITLE
[Windows] Sometimes can not access the service alias

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11789]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Create two services in a stack and set service links `- service1:whl3`
```
version: '2'
services:
  server1:
    image: microsoft/nanoserver
    stdin_open: true
    network_mode: transparent
    tty: true
    isolation: default
    labels:
      io.rancher.container.pull_image: always
  client1:
    image: microsoft/nanoserver
    stdin_open: true
    network_mode: transparent
    tty: true
    isolation: default
    links:
    - server1:whl3
    labels:
      io.rancher.container.pull_image: always
```
2. Waiting for client1 to start successfully
3. Log in client1 and `ping whl3`

**Results:**
Sometimes it will prompt "Ping request could not find host whl3. Please check the name and try again." Try `ping whl3` a few minutes later, and sometimes it's accessible

Here is my operation record
```

PS C:\> ping whl3
Ping request could not find host whl3. Please check the name and try again.
PS C:\> Resolve-DnsName whl3

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
whl3.u3.rancher.internal                       A      1     Answer     192.168.2.187


PS C:\> ping 192.168.2.187

Pinging 192.168.2.187 with 32 bytes of data:
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time=2ms TTL=128

Ping statistics for 192.168.2.187:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 2ms, Average = 0ms

# After a few minutes
PS C:\> ping whl3

Pinging whl3.u3.rancher.internal [192.168.2.187] with 32 bytes of data:
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
Reply from 192.168.2.187: bytes=32 time<1ms TTL=128
```

If you can not reproduce, you can try to create multiple identical stacks
