### ISSUE TITLE
HostPort port is not being set

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#11786]
When create workload with port of HostPort type, no HostPort is being opened on the backend. Need to fix the api mapper to set port.Hostport = sourcePort when kind="HostPort"

**Comment by alena1108** [comment]
@sangeethah as a part of the check, a) make sure that the HostPort was set on the workload's conatiners port b) that it is actually accessible. If a doesn't work, reopen the bug for me. if b) doesn't work, reassign to RKE team.

**Comment by moelsayed** [comment]
Confirmed working:
- HostPort configuration is applied to the workload container:
```
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    lifecycle: {}
    name: nginx-hostport
    ports:
    - containerPort: 80
      hostPort: 8888
      protocol: TCP
```
- The workload is accessible through the hostPort address.
