### ISSUE TITLE
[Load Balancer] getting HAProxy Stats exported to prometheus

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#11859]
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: latest

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.8.5-rancher4

I am trying to get statistics from Rancher-Ingress (haproxy) to prometheus running inside kubernetes.
I already have the global section configured to expose the stats endpoint like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    # Customizing HAProxy in the load balancer
    config: "listen stats\nbind :1936\nmode http\nbalance\ntimeout client 5000\ntimeout connect 4000\ntimeout server 30000\nstats enable\nstats hide-version\nstats refresh 15s\nstats show-node\nstats auth test:test\nstats uri /haproxy"
```

I know i can discover the loadbalancers via internal dns, but i would need to start a haproxy_exporter next to each one ?
