### ISSUE TITLE
[Windows] Windows environment can't access sidekicks service

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#11856]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows 
**Steps to Reproduce:**

1. I tried to create a sidekicks service, just like docker-compose below.  
```
version: '2'
services:
  test155703:
    image: kingsd/win-nginx:v0.4
    network_mode: transparent
  test389055:
    image: kingsd/windowsssh:v0.11
    stdin_open: true
    network_mode: transparent
    tty: true
    links:
    - test568785:test568785
    ports:
    - 7004:22/tcp
  test568785:
    image: kingsd/win-nginx:v0.4
    network_mode: transparent
    labels:
      io.rancher.sidekicks: test155703
```
2. Waiting for the container to be created successfully and login to the test389055 container, use the `ping test155703.test568785` to access the sidekicks service

**Results:**
Return can't access test155703.test568785. 
```
PS C:\Program Files\OpenSSH-Win64> ping test155703.test568785
Ping request could not find host test155703.test568785. Please check the name and try again.
```
