### ISSUE TITLE
Upgrade of service with sidekick does not obey pull always

### ISSUE THREAD

**Issue by chris-scentregroup** [rancher/rancher#11852]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9
rancher-compose: v0.12.5

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce

**Steps to Reproduce:**
With rancher compose action an upgrade with a command such as `rancher-compose up -d --upgrade  --confirm-upgrade --batch-size 1`.

docker-compose.yml
```
  frontend:
    image: nginx:1.13.8-alpine
    stdin_open: true
    tty: true
    entrypoint:
    - /opt/acme/docker-entrypoint-fe.sh
    command: ["nginx", "-g", "daemon off;"]
    environment:
      API_URL: '${API_URL}'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: tier=private
      io.rancher.sidekicks: data
    volumes_from:
    - 'data'
  data:
    image: ajax/acme:latest
    command:
    - 'true'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: tier=private
      io.rancher.container.start_once: 'true'
```
Noting the label to pull image always, latest tag is in use for both container services.

**Results:**
The sidekick data container (which is a started-once) is not pulled and replaced. If this is the wrong approach for this use case, please let me know and if not it looks like a bug.
