### ISSUE TITLE
A cycle in service alias definition will bring down dns and other infrastructure services 

### ISSUE THREAD

**Issue by conet** [rancher/rancher#11947]
**Rancher versions:**
rancher/server: v1.16.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3-1
ipsec: 0.2.2
network-services: v0.2.8
scheduler: v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.6.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Define a cycle in service aliases (this can happen because of human error while selecting services from a huge combobox). It's easy to define links to self when upgrading a stack that has links using a catalog item. Links to self can't be created in the UI when manually defining services but in this case a circular definition (with the same effect) can easily be setup like this:

```
version: '2'
services:
  service2:
    image: centos:7.4.1708
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  alias1:
    image: rancher/dns-service
    links:
    - alias2:alias2
  service1:
    image: centos:7.4.1708
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  alias2:
    image: rancher/dns-service
    links:
    - alias1:alias1
```

**Results:**
From this point on DNS will stop being updated, for example after a service update the name of the service will still be resolved towards the old container ip causing other services to fail without a clear cause. If one figures out that there is rancher DNS issue and tries to restart the network services hoping to fix the problem it will just make it worst by bringing down all infrastructure services which depend on a working DNS.
The `metadata` service will be blocked in a cycle eating available CPU and failing to produce a working `/etc/rancher-dns/answers.json` (the file will be empty or contain `null`). The `ipsec` stack, if restarted will fail to start because the name of the rancher server will fail to be resolved thus preventing the `ipsec-router` service to obtaint the secrets needed to start.

The fix is pretty simple but probably not obvious to everyone without knowledge of this problem, once the cycle is broken the services start working properly again. Rancher services themselves should be resilient against these kind of errors.

Please note that `rancher-dns:v0.16.4` no longer has this issue but the current stable rancher version uses `rancher/dns:v0.15.3`.

I've seen a long list of open DNS issues, some of them might have this as a cause.
