### ISSUE TITLE
[Windows] Cannot resolve hostname pointed to by external service

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#12059]
**Rancher versions:**
rancher/server: v1.6.14

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ee-6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Windows 2016
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
All
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Windows
**Steps to Reproduce:**
1. Use the following compose to add an external service and point to a hostname

docker-compose.yml
```
version: '2'
services:
  winssh:
    image: kingsd/windowsssh:v0.11
    network_mode: transparent
    tty: true
    isolation: default
    links:
    - ext-network:ext-network
    ports:
    - 3024:22/tcp
  ext-network:
    image: rancher/external-service
```
rancher-compose.yml
```
version: '2'
services:
  winssh:
    scale: 2
    start_on_create: true
  ext-network:
    hostname: baidu.com
```
2. Use the `Resolve-DnsName ext-network` command to resolve the domain 'ext-network' in the winssh container
**Results:**
Windows container returned unresolved domain 'ext-network'
```
PS C:\Program Files\OpenSSH-Win64> Resolve-DnsName ext-network
Resolve-DnsName : ext-network : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName ext-network
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ext-network:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```
