### ISSUE TITLE
[cli] rancher up --pull reports success when image pull fails

### ISSUE THREAD

**Issue by larscheidt** [rancher/rancher#12171]
**Rancher versions:**
rancher/server: v1.6.14
rancher/agent: v1.2.9
rancher/cli: v0.6.7

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Red Hat Enterprise Linux Server release 7.4 (Maipo)
3.10.0-693.21.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create the following docker-compose.yml:
```
version: '2'
services:
  top:
    image: docker.io/centos:7
    command: top
    environment:
    - TERM=xterm-256color
    labels:
      io.rancher.scheduler.global: 'true'
    network_mode: bridge
    tty: true
```

2. Start "top" service with rancher CLI:
```
rancher up --pull --force-upgrade -d top
```

3. Edit /etc/hosts on one of the nodes running the "top" service to point docker.io at 127.0.0.1.
```
127.0.0.1    docker.io
```

4. Run the rancher up command again
```
rancher up --pull --force-upgrade -d top
```

**Results:**

Rancher CLI returns 0 and reports success, even though it was unable to re-pull docker.io/centos:7 on the node with the altered /etc/hosts file.  Expected Rancher CLI to return non-zero and report failure.
