### ISSUE TITLE
Rancher kubernetes kube-apiserver flags

### ISSUE THREAD

**Issue by manokaran3529** [rancher/rancher#12184]
Hi All,

Is there a way to add additional kube-apiserver flags to the k8s environment template. Basically, we need to set kube-apiserver OIDC flags to the api-server for OIDC authentication for our K8s env. Right now we have option only for adding kubelet flags.

**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: v1.2.9

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.8.9

**Comment by manwanth** [comment]
Hi Manokaran, did you got any solution for this? I am also looking for the same.

**Comment by apoorva11029** [comment]
@superseb does rancher support modifying kube-apiserver flags currently?

**Comment by ragashreeshekar** [comment]
Facing the same issue. I want to enable etcd secrets encryption however unable to once the cluster is setup. Any leads on this please?

**Comment by jgato** [comment]
exactly the same issue here. After a cluster is created, how can I modiffy kube-apiserver to add oidc? I have read lots of regular Kubernetes docs pointing to edit the manifest in /etc/kubernetes/manifest, but Rancher does not seems to follow that approach.

**Comment by fly2tomato** [comment]
> exactly the same issue here. After a cluster is created, how can I modiffy kube-apiserver to add oidc? I have read lots of regular Kubernetes docs pointing to edit the manifest in /etc/kubernetes/manifest, but Rancher does not seems to follow that approach.

any solution？

**Comment by fly2tomato** [comment]
my workaround:
Also need to modify kube-apiserver.yaml but can't find it anywhere in the master node.
The key is the kube-apiserver.yaml does not exist in the master node, but you can modify the settings of kube-apiserver.yaml by using cluster.yaml when you use rke to build up your k8s cluster.
For example, if you want to add feature-gates=RemoveSelfLink=false into kube-apiserver.yaml，it is equal to add it into cluster.yaml:
kube-apiserver.yaml:

```
spec:
  containers:
  - command:
    - kube-apiserver
    - --feature-gates=RemoveSelfLink=false ## new feature to be added
```

cluster.yaml:
```
service:
  kube-api:
    extra_args:
      feature-gates: "RemoveSelfLink=false" ## new feature to be added
```
