### ISSUE TITLE
Catalog Apps - add enumerated list for catalog questions

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#12459]
We need to add the enum type for the catalog questions, and an example as below.

```
- variable: serviceType
  default: "NodePort"
  description: "Kubernetes Service type(options are ClusterIP, NodePort and LoadBalancer)"
  type: "enum"
  options: 
    - "ClusterIP"
    - "NodePort"
    - "LoadBalancer"
```
