### ISSUE TITLE
Data loss when health check fails and recreate stategy

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#12472]
**Rancher versions:**
rancher/server: 1.6.15
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.13.11
network-services: 0.7.20
scheduler: 0.8.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

17.12.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

CentOS 7.4 x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Create a service with a data container and a container scoped volume:

docker-compose.yml
```yaml
---
version: '2'
services:
  test:
    image: nginx:latest
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: test-data
    volumes_from:
      - test-data
  test-data:
    network_mode: none
    labels:
      io.rancher.container.start_once: true
      io.rancher.container.hostname_override: container_name
    environment:
      SERVICE_UID: 0
      SERVICE_GID: 0
      SERVICE_VOLUME: "/data"
    image: rawmind/alpine-volume:0.0.2-1
    volumes:
      - test-data:/data
volumes:
  test-data:
    driver: local
    per_container: true
```

rancher-compose.yml
```yaml
---
version: '2'
services:
  test:
    scale: 3
    health_check:
      port: 80
      request_line: GET / HTTP/1.0
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 5000
```

**Results:**

Write something under /data and then make the instance unhealthy by changing for instance the port and reloading nginx.

```shell
sed -i 's/80;/8080;/' /etc/nginx/conf.d/default.conf
nginx -s reload
```

When the health check fails, the unhealthy containers get recreated along with the their data containers resulting in data loss!
