### ISSUE TITLE
Rancher api does not recognize securityContext:drop:all

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#12619]
*Describe your issue here*

I found that the deployment created in the yaml file that defines the securityContext cannot be scaled on the rancher ui, but can be scaled by kubectl.

For example use the following yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: carts-db
    spec:
      containers:
      - name: carts-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta2` UI: `v2.0.34` |
|Access|`local` `admin`|
|Route|`workload`|
