### ISSUE TITLE
container wont move to different host

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#12637]
**Rancher versions:**
rancher/server: 1.6.16
rancher/agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: 0.3.6
ipsec: 0.13.11
network-services: 0.10.2
scheduler: 0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
17.09.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.78-rancher2
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- 2 Nodes with labels: 
```
ranch01.fra:
ck_type=internal 
ck_host=ranch01.fra
vrrp_role=master

ranch02.fra:
ck_type=internal 
ck_host=ranch02.fra
vrrp_role=backup
```

2. create following stack:
docker-compose:
```
  prometheus-rancher:
    image: registry/sys/prom/prometheus
    mem_limit: 2147483648
    cpu_shares: 1024
    extra_hosts:
      - rancher-server:10.10.0.121
    # ports:
    #   - 9090:9090
    command:
      - '--config.file=/config/prometheus-rancher.yml'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://prometheus/prometheus-rancher'
      - '--storage.tsdb.path="/prometheus'
      - '--storage.tsdb.retention=1h'
    volumes:
      - prometheus_rancherdata:/prometheus
    labels:
      io.rancher.container.pull_image: 'always'
      io.rancher.scheduler.affinity:host_label_soft: ck_type=internal

  prometheus:
    image: registry/sys/prom/prometheus
    restart: always
    mem_limit: 8388608000
    cpu_shares: 2048
    # ports:
    #   - 9091:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/config/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.external-url=https://prometheus/prometheus/'
      - '--storage.tsdb.path="/prometheus"'
      - '--storage.tsdb.retention=60d'
    labels:
      io.rancher.scheduler.affinity:host_label_soft: ck_type=internal
```
**Results:**
Initially containers are spread over 2 hosts.
But no matter what (evacuating host2, scaling prometheus-rancher) all other containers are scheduled only on host2.

regards,
Roman
