### ISSUE TITLE
Rancher report everything green even canal-node container is down: System Project is needed

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#12706]
**Rancher versions:**
rancher/server: v2.0.0-beta3

**Infrastructure Stack versions:**
healthcheck: green
ipsec: green
network-services: green
scheduler: green 
kubernetes (if applicable): green

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO + RKE 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 nodes

**Steps to Reproduce:**
1. Deploy following yaml to crash canal-node container (one of three containers the canal pod are running)
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: canal-crash
  name: canal-crash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: canal-crash
    spec:
      containers:
      - name: canal-crash
        image: nginx
        ports:
        - containerPort: 80
          name: canal-crash
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: canal-crash
  name: canal-crash-svc
spec:
  selector:
    app: canal-crash
  ports:
  - name: canal-crash
    port: 80
    targetPort: canal-crash
  type: LoadBalancer
```
2. Check `kube-system` namespace, found canal-node is down
```
$ kubelet -n kube-system get pod
NAME                                   READY     STATUS             RESTARTS   AGE
canal-6qr4t                            2/3       CrashLoopBackOff   15         1h
canal-dkctf                            2/3       Running            15         1h
canal-rr42s                            2/3       CrashLoopBackOff   14         1h
kube-dns-6f7666d48c-njr65              3/3       Running            0          1h
kube-dns-autoscaler-6bbfff8c44-87wms   1/1       Running            0          1h
```
Notice Ready is `2/3` instead of `3/3`.

**Results:**
Everything is green for Rancher UI.

**Expectation**
Rancher UI should report error since key network plugin container is down.
