### ISSUE TITLE
Deployment with InitContainer(sidecar) unable to scale

### ISSUE THREAD

**Issue by gwiersma** [rancher/rancher#12817]
Rancher versions:
rancher/server: v2.0.0-beta3
rancher/agent: agent:v2.0.0-beta3

Docker version:
Server Version: 17.03.2-ce

Operating system and kernel:
Ubuntu 16.04.4 LTS (Xenial Xerus)"
4.13.0-38-generic

Type/provider of hosts:
VMware vSphere

Setup details:
1 master
3 workers

Steps to Reproduce:
- Start deployment with kubectl create -f <file.yaml>
- Init container is started and downloads a file from een internal webserver.
- Downloaded file is saved as a .php file on a shared volume.
- When the file has been downloaded, a hello world container is started.
- The hello world container uses the same volume as the initcontainer and also uses the index.php as default webpage.
- When we try to scale the amount of replicas, we receive the following error in the Rancher2.0 Dashboard: 

```
Error updating scale
Validation failed in API: Deployment.apps "helloworld" is invalid: spec.template.spec.initContainers[0].lifecycle: Invalid value: api.Lifecycle{PostStart:(*api.Handler)(nil), PreStop:(*api.Handler)(nil)}: must not be set for init containers
```

When we use kubectl: rancher kubectl scale --replicas=<amount> -f <yamlfile>.yaml it works. 

Our Deployment file:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "helloworld"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "helloworld"

  template:
    metadata:
      labels:
        app: "helloworld"

    spec:
      volumes:
        - name: "application"
          hostPath:
            path: /var/kube/workdir/
            type: DirectoryOrCreate
      initContainers:
      - name: check-webapp-ready
        image: busybox
        command: ["wget", "-O", "/www/index.php", "http://<IP>/index.txt"]
        volumeMounts:
          - name: "application"
            mountPath: "/www"
      containers:
      - name: webserver
        image: "dockercloud/hello-world:latest"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: "application"
            mountPath: "/www"
```
