### ISSUE TITLE
Error when deploying 2.0 server in HA

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#12949]
**Rancher versions:**
rancher/server: master

**Docker version: (`docker version`,`docker info` preferred)**17.03

**Steps to Reproduce:**
1. Deploy rancher in HA using the yml file below:
```
# default k8s version: v1.8.9-rancher1-1
# default network plugin: flannel
nodes:
  - address: <IP>
    user: <USER>
    role: [controlplane,etcd,worker]
    ssh_key_path: <PEM_FILE>

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
  subjects:
  - kind: User
    name: system:serviceaccount:cattle-system:default
    apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data: 
    tls.crt: <BASE64_CRT>  # ssl cert for ingress. If selfsigned, must be signed by same CA as cattle server
    tls.key: <BASE64_KEY>  # ssl key for ingress. If selfsigned, must be signed by same CA as cattle server
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cert.pem: <BASE64_CRT>    # ssl cert for cattle server.
    key.pem: <BASE64_KEY>     # ssl key for cattle server.
    cacerts.pem: <BASE64_CA>  # CA cert used to sign cattle server cert and key
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: <FQDN>  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts: 
      - <FQDN>      # FQDN to access cattle server
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        containers:
        - image: rancher/server:master
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server

```
Deploying rancher in HA fails with the below error:
```
Exit status 1, I0420 23:34:40.611959 11005 http.go:105] HTTP2 has been explicitly disabled I0420 23:34:40.649941 11005 http.go:105] HTTP2 has been explicitly disabled W0420 23:34:40.664328 11005 factory_object_mapping.go:423] Failed to download OpenAPI (the server has asked for the client to provide credentials), falling back to swagger error: You must be logged in to the server (Unauthorized)

```
<img width="1291" alt="screen shot 2018-04-20 at 7 30 45 pm" src="https://user-images.githubusercontent.com/18536626/39079522-598ea19e-44d1-11e8-875d-fc8b378781d7.png">

**Comment by biblesyme** [comment]
**Rancher versions:** 
rancher/server: master 22/4

<img width="1312" alt="screen shot 2018-04-23 at 09 45 12" src="https://user-images.githubusercontent.com/9334435/39103269-5f7a4c18-46dc-11e8-9210-32897b33bf07.png">

Same error when I launch rancher in minikube with yaml below

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cattle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cattle
    spec:
      containers:
      - image: rancher/server:master
        imagePullPolicy: Always
        name: cattle
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cattle-globalrole-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cattle-globalrole-user
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

```
