### ISSUE TITLE
No public ingress endpoint created for workload when ingress is created natively

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#12998]
Steps to reproduce:

1) Create deployment, service and ingress having service as a target, natively, using kubectl. 
2) Go to rancher UI/API to see the workoload.

Bug: public endpoint exposed via ingress, not present on the workload.

@orangedeng we should make sure that for ingress created locally - the one that *would not* have the rancher ingress status annotation - public endpoints are being created.

Here are the yml files that can be used to reproduce the bug:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 5
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

**Comment by orangedeng** [comment]
@alena1108 As long as your ingress example is using default backend, I think the major issue is how we show default backend endpoint in workload. I tested ingress with host/path rules and it turns out alright. Here is the example ingress resource I tested ok.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: t2
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80
        path: /aoo
```

**Comment by alena1108** [comment]
@orangedeng can we run more tests to ensure that the pubic endpoints get updated on every native ingress use case. If all tests pass, please close the issue

**Comment by orangedeng** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 5
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test2
  namespace: default
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
  rules:
  - host: test.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80
        path: /doo
  - host: test2.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80
        path: /
```
@sangeethah this is an example for all kind of ingress backend. Default backend won't be set as a public endpoint. The other rules for host/path will show in workload public endpoint.

**Comment by alena1108** [comment]
@sangeethah

 as a verification, lets just make sure that we test ingress created by not using rancher API/LB UI, get public endpoints assigned. The endpoints will get created for hostname/path rules only. Keeping that in mind, we can test:

* deploying ingress using kubectl and yml file
* deploying ingress via rancher - make it point to the service - export yml -> Deploy new ingress using import yml. Make sure new ingress gets endpoints.

**Comment by sangeethah** [comment]
Tested with v2.0.0-rc1

Scenario 1:
When ingress ( and Service/Replication controller) is created using remote kubectl , When ingress gets synced to rancher-server , workload has public endpoints created as expected.

```
apiVersion: v1
kind: Service
metadata:
 name: k8test2
 labels:
   k8s-app: k8test2-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test2-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc2
spec:
 replicas: 2
 selector:
   k8s-app: k8test2-service
 template:
   metadata:
     labels:
       k8s-app: k8test2-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress2
 annotations:
   http.port: "83"
spec:
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /service3.html
       backend:
         serviceName: k8test2
         servicePort: 81                           
```
Scenario 2:

Deploy ingress via rancher UI and  make it point to the service ( by having the workload have a nodeport which results in service entry created for it).
Export this ingress.
Using remote kubectl - use  the exported ingress file to create a new ingress that points to a different service entry that was created by rancher ( service entry relating to a workload deployment with nodeport).


Scenario 3:

Deploy ingress via rancher UI and  make it point to the service ( by having the workload have a nodeport which results in service entry created for it).
Export this ingress.
Using import at namespace scope - use  the exported ingress file to create a new ingress that points to a different service entry that was created by rancher ( service entry relating to a workload deployment with nodeport).

In all the above cases , workload has public endpoints created as expected.
