### ISSUE TITLE
Testing `rancher up`

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#13034]
`rancher up` needs to be tested. User should be able to create any resource in yaml format by using `rancher up`

**Comment by StrongMonkey** [comment]
`rancher up` is mostly used to create rancher resources in yaml file format. Each resource can be defined as a yaml file, for example, a gke cluster can be defined as 
```
version: 3
clusters:
  test-cluster:
    description: "for test"
    googleKubernetesEngineConfig:
      diskSizeGb: 100
      enableAlphaFeature: false
      horizontalPodAutoscaling: false
      httpLoadBalancing: false
      kubernetesDashboard: false
      legacyAbac: false
      machineType: g1-small
      masterVersion: 1.9.6-gke.1
      networkPolicyConfig: false
      nodeCount: 3
      projectId: rancher-dev
      zone: us-central1-f
```
