### ISSUE TITLE
Ingress not functional on Azure Container service cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13088]
**Rancher versions:**
rancher/server: v2.0.0-beta4-rc3

**Steps to Reproduce:**
1. Create a Azure container service cluster 
2. Create a workload with nginx image
3. Create an ingress pointing to the workload

Accessing the ingress from any of the node IPs does not resolve to the desired targets.
The node IPs display internal address.

```
wget --header='host: foo.bar.com' http://10.240.0.6:80/name.html
--2018-04-25 12:05:03--  http://10.240.0.6/name.html
Connecting to 10.240.0.6:80... ^C
```
If the Azure container service creates its own resource for the ingress, then the right endpoint should be provided to access the ingress.

**Comment by cjellick** [comment]
TODOs:
1. investigate what is causing this. Is this our problem or the providers? Determine if it should be documented.
2. Determine if this could be solved by cluster capabilities?

**Comment by StrongMonkey** [comment]
In order to get ingress working, cluster needs to deployed a ingress controller.
By default GKE uses gce controller https://github.com/kubernetes/ingress-gce/blob/master/README.md and rke uses https://github.com/kubernetes/ingress-nginx/blob/master/README.md.
There are two ways to configure ingress for AKS:
1. Use nginx-controller by default. https://docs.microsoft.com/en-us/azure/aks/ingress.  From the docs it is only possible to install that from helm. (there is no official AKS api to support that, so it will be hard to integrate into rancher api)
2. Use AKS HTTP application routing. https://docs.microsoft.com/en-us/azure/aks/http-application-routing. This is supported by AKS api, so it is possible to integrate that into rancher api.
If we are going with approach 2, we will have to add a new flag in kontainer-enginer to flip the setting, and corresponding api to turn on ingress addon.

**Comment by cjellick** [comment]
As with https://github.com/rancher/rancher/issues/13086, we are going to note/warn about this on cluster creation.
SInce AKS does have the api for creating an ingress, in 2.2 we'll probably implement it properly

**Comment by dnauck** [comment]
Wouldn't it make sense to deploy nginx-ingress like on custom clusters?

**Comment by amarczinek** [comment]
Is there any information when/if this is been addressed?

**Comment by junkiebev** [comment]
@amarczinek - This tripped me up for a bit, but the solution is pretty easy. You just need to add the annotation
`kubernetes.io/ingress.class: addon-http-application-routing` to the ingress object so that the ingress controller knows to pick it up.

Example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  name: some-url
  namespace: some-namespace
spec:
  rules:
  - host: some.url.com
    http:
      paths:
      - backend:
          serviceName: some-url
          servicePort: 80
```
