### ISSUE TITLE
Not able to create PVC through UI on GKE cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#13180]
**Rancher versions:**
 rancher/rancher: master

**Steps to Reproduce:**
1. Create a GKE cluster
2. Create a disk of 10G or higher in GCE portal
3. Create a volume "vol1" a the cluster level
4. Create a persistent volume claim using the volume "vol1"

The volume claim is stuck in pending state. A workload cannot be created using the volume claim and it is stuck in "Updating" state.

![screen shot 2018-04-27 at 6 01 16 pm](https://user-images.githubusercontent.com/18536626/39390116-090a20da-4a45-11e8-8aef-e7e668bccfae.png)

Note: A persistent volume and persistent volume can be successfully created using the yml file below. A workload can also be created successfully.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: testgoogvol
  storageClassName: ""


```
