### ISSUE TITLE
Support insecure registry option in "publish an image" step

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#13242]
`publish an image`  step should provide option for user to specify if the chosen registry is insecure or not.

**Comment by gitlawr** [comment]
If a user want to deploy a workload using images from insecure registry, they need to properly configure docker daemon on their hosts beforehand.
Now publishing a image to an insecure registry results in a failure in auth.
The publish image step is run in `dind` way, we can add an `allow insecure registries` option in the step and pass it to that docker daemon if we want.

**Comment by KaelBaldwin** [comment]
This is causing me trouble at the moment. I've set up an insecure registries in the daemon.json on my hosts, but when it tries to do the publish an image step the authentication fails.

**Comment by KaelBaldwin** [comment]
I ended up just securing the registry

**Comment by gitlawr** [comment]
Starting from v2.1.0, UI does not expose the option, but you can set environment variable for the push image step as follows:
```
- publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xxx
      pushRemote: true
      registry: xxx
    env:
      PLUGIN_INSECURE: "true"
```
For more available environment variables please refer to the docs.
