### ISSUE TITLE
Exoscale provisioning

### ISSUE THREAD

**Issue by fretscha** [rancher/rancher#13291]
Created node template and entered Exoscale API key and secret. When I try to create a cluster on Exoscale, based on this template, I get following error:

> Error setting machine configuration from flags provided: missing an API key (--exoscale-api-key) or API secret key (--exoscale-api-secret-key); Timeout waiting for ssh key

Unsucessfully Tried multiple keypairs & multiple accounts. 

Docker-machine provisioning from command line works. Rancher UI fails.
 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by fretscha** [comment]
Problem still exists in v2.0.2

**Comment by justjulian** [comment]
Same here with v2.0.6

**Comment by greut** [comment]
Oh crickey. We made changes in the 1.6 branch which aren't as of yet been ported to the 2.x world. We'll take care of that soonish.

**Comment by greut** [comment]
As the "node provider" still uses docker-machine which is in a bugfix mode for a long time already. It's probably easier to rely on the _bring your own nodes_ cluster setup.

![screenshot from 2018-07-31 09-06-12](https://user-images.githubusercontent.com/1388/43443407-0e71bc12-94a1-11e8-8484-679cb4fff9f6.png)

A working cloud-init could be the following one.

```yaml
#cloud-config

manage_etc_hosts: true

apt_sources:
- source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
  keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true

packages:
- [ docker-ce, "17.03.2~ce-0~ubuntu-xenial" ]


runcmd:
- [ usermod, -aG, docker, ubuntu ]
```

NB: we are working to bring back the node provider as well.
