### ISSUE TITLE
Using Private registries with basic authentication 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#13339]
**Rancher versions:**
rancher/rancher:master

Currently using private registry with basic authentication will succeed for deploying k8s components but will fail for deploying the pods because kubelet has no idea what credentials are being used and it fails to pull the pause image and pods images.

**Comment by apricote** [comment]
We are also experiencing this issue. We tried this either with the beta or some RC and as far as I can remember it was working back then.

Current workaround we are using is to edit the YAML of the Deployment/Workload and add the `imagePullSecrets` manually:

```yaml
kind: Deployment
name: workload-name
spec:
  template:
    spec:
      containers:
      - image: ...
      imagePullSecrets:
      - name: registry-credentials-name
```

While this is no maintainable solution, it allows us to experiment with Rancher 2.
