### ISSUE TITLE
Not able to start services that has data volumes from other containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1334]
Server version - v0.25.0-rc2
Rancher compose version - rancher-compose-v0.1.3

Create a service that has data volumes from a container  with label con=vol.
Service has scheduling rules to start a containers on host that has containers with labels  con=vol.

I get the following error when trying to start the service:

root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.1.3# ./rancher-compose -p testvol create
INFO[0000] Creating environment testvol                 
ERRO[0000] Failed to find 736073f0-2bb3-47aa-aa7c-02a90abc806e 
INFO[0000] Creating service test41261                   
ERRO[0000] Failed to start test41261 : Bad response from [http://104.154.37.50:8080/v1/services], statusCode [422]. Status [422 status code 422]. Body: [{"id":"58318398-d51d-4fe7-b1d1-e30a565697b3","type":"error","links":{},"actions":{},"status":422,"code":"InvalidReference","message":null,"detail":null,"fieldName":"LaunchConfigName"}] 
ERRO[0000] Failed to start: test41261 : Bad response from [http://104.154.37.50:8080/v1/services], statusCode [422]. Status [422 status code 422]. Body: [{"id":"58318398-d51d-4fe7-b1d1-e30a565697b3","type":"error","links":{},"actions":{},"status":422,"code":"InvalidReference","message":null,"detail":null,"fieldName":"LaunchConfigName"}] 
FATA[0000] Bad response from [http://104.154.37.50:8080/v1/services], statusCode [422]. Status [422 status code 422]. Body: [{"id":"58318398-d51d-4fe7-b1d1-e30a565697b3","type":"error","links":{},"actions":{},"status":422,"code":"InvalidReference","message":null,"detail":null,"fieldName":"LaunchConfigName"}] 
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.1.3# 

ymls used:

docker-compose.yml 
```
test41261:
  restart: on-failure:10
  labels:
    io.rancher.scheduler.affinity:container_label: c1=vol
  dns:
  - 1.2.3.4
  cpu_shares: 400
  image: ibuildthecloud/helloworld:latest
  hostname: test
  volumes:
  - /test/container:/test/vol1:ro
  stdin_open: true
  mem_limit: 8000000
  cap_add:
  - CHOWN
  dns_search:
  - 1.2.3.4
  environment:
    TEST_FILE: /etc/testpath.conf
  domainname: rancher.io
  cap_drop:
  - KILL
  tty: true
  command:
  - sleep
  - '9000'
  privileged: true
  volumes_from:
  - 736073f0-2bb3-47aa-aa7c-02a90abc806e
  user: root
```

rancher-compose.yml
``` 
test41261:
  scale: 2
```
