### ISSUE TITLE
When cpu_sets is set for service , it does not get set for the containers in the service. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1335]
Server version - v0.25.0-rc2
Rancher compose version - rancher-compose-v0.1.3

When cpu_sets is set for service , it does not get set for the containers in the service. 
docker-compose.yml that was used:

```
test41261:
  restart: on-failure:10
  labels:
    io.rancher.scheduler.affinity:container_label: c1=vol
  dns:
  - 1.2.3.4
  cpu_shares: 400
  cpuset: 0
  image: ibuildthecloud/helloworld:latest
  hostname: test
  volumes:
  - /test/container:/test/vol1:ro
  stdin_open: true
  mem_limit: 8000000
  cap_add:
  - CHOWN
  dns_search:
  - 1.2.3.4
  environment:
    TEST_FILE: /etc/testpath.conf
  domainname: rancher.io
  cap_drop:
  - KILL
  tty: true
  command:
  - sleep
  - '9000'
  privileged: true
```

Containers in the service has "cpuSet": null.
