### ISSUE TITLE
Rancher Up - GKE Nodes not present.

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13361]
Rancher versions:
Master 5/8/2018

Steps:
Create a new cluster with Rancher up, using the below YAML File.

```
clusters:
    test:
        googleKubernetesEngineConfig:
            disableHorizontalPodAutoscaling: false
            disableHttpLoadBalancing: false
            disableNetworkPolicyConfig: false
            diskSizeGb: 100
            enableAlphaFeature: false
            enableKubernetesDashboard: false
            enableLegacyAbac: false
            nodeCount: 1
            type: googleKubernetesEngineConfig
            machineType: g1-small
            zone: us-central1-f
            clusterIpv4Cidr: null
            credential: "$pasteYourGkeCredentialInHere"
            projectId: rancher-dev
            masterVersion: 1.9.6-gke.1
```

Results:
Cluster is created, however there are no nodes present.
