### ISSUE TITLE
Having external_links does not result in container links being created for the service

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1337]
Server version - v0.25.0-rc2
Rancher compose version - rancher-compose-v0.1.3

Create a service with container link using rancher server UI.
Used the config generated for this service as input to  rancher compose. 

Service that was created does not have container links .There are no environment variables relating to links present in the containers.

Following is the docker-compose.xml that was used: 

```
test321896:
  ports:
  - 9999:22/tcp
  external_links:
  - WEB1:53f45376-7625-48b9-b31f-41a9543ad73a
  image: sangeetha/testclient:latest
```
