### ISSUE TITLE
Pass docker run arguments for a service

### ISSUE THREAD

**Issue by hadirsa** [rancher/rancher#13410]
Hi. I have an issue. I have a docker-compose file for mysql  like below. **How can i pass tmpfs in mysql service?**
 I mean running a service **without** docker-compose file

```
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - "/opt/docker/mysql.conf.d:/etc/mysql/conf.d"
    environment:
     - MYSQL_ROOT_PASSWORD=finger
    tmpfs:
     - /var/lib/mysql/:rw,noexec,nosuid,size=600m
     - /tmp/:rw,noexec,nosuid,size=50m
```
