### ISSUE TITLE
Specify custom config options to kubelet

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/rancher#13488]
**Rancher versions:** rancher/rancher:2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1-rancher2

**Docker version:** 17.03.2-ce, build f5ec1e2

**Operating system and kernel:** 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

**Type/provider of hosts: ** Bare-metal

**Setup details: ** single node rancher

**Environment Template: ** Kubernetes

I would like to pass custom config options to kubelet : https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ for example the **--max-pods** one....

How can we do that (by node) ?

**Comment by superseb** [comment]
Not yet in the UI, see https://github.com/rancher/rancher/issues/13076

**Comment by Angelinsky7** [comment]
@superseb this seems now in the ui but i cannot manage to make the change, could you give me a hint, please !!!?
I'm trying to add ADDITIONAL_KUBELET_FLAGS":"--max-pods=200"
so i thought of editing the cluster options :

```
 services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube_api: 
    pod_security_policy: false
  kubelet: 
    fail_swap_on: false
    max_pods: 200
ssh_agent_auth: false
```

but this is not working and the config rollback without any error message.

**Plus, how can i set this options ONLY for some nodes ?**

Thanks for all the support !
