### ISSUE TITLE
Add etcd backups to Rancher Server RKE template examples

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#13562]
**Rancher versions:**
rancher/rancher: 2.0.0

RKE template examples should have etcd backups enabled.  

```
services:
  etcd:
    backup: true
    creation: 15m0s
    retention: 24h
```

**Comment by deniseschannon** [comment]
@galal-hussein let's add this into the examples. what happens if you try to launch it using an older version of RKE?

**Comment by soumyalj** [comment]
Tested on a  HA setup using rke version v0.1.8-rc11.[https://raw.githubusercontent.com/rancher/rancher/e9d29b3f3b9673421961c68adf0516807d1317eb/rke-templates/3-node-certificate-recognizedca.yml]
 The yml included the services section 
```
services:
  etcd:
    backup: true
    creation: 30m0s
    retention: 15h
```
Snapshots  were taken at the correct intervals in /opt/rke/etcd-snapshots
1. Cluster1 was created . snapshot(S1) created after the cluster1 was created and stored in a different host.
2. Another cluster(C2) was created after the snapshot was saved .
3. The same snapshot(S1) was copied to all the hosts in directory /opt/rke/etcd-snapshots 
etcd snapshot-restore was performed. Also ensure that the certificate bundle exists on all the hosts in directory /opt/rke/etcd-snapshots 
4. Restore the snapshot (S1)
./rke_darwin-amd64 etcd snapshot-restore --name S1 --config cluster.yml

After restore, only cluster C1 was seen in the rancher server. C2 was not seen as expected.
