### ISSUE TITLE
Default Loadbalancer/Ingress can only reach one pod

### ISSUE THREAD

**Issue by PiiTan** [rancher/rancher#13618]
**Rancher versions:**
rancher/server or rancher/rancher: latest (2.0?) Docker Image ID: 3141e5c66ee8
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10 Rancher

**Docker version: (`docker version`,`docker info` preferred)**
Version:      17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7, 3.10.0-693.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher (server)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Install fresh CentOS 7
2. Install Docker 17.03-ce
3. Open firewall ports on K8s-Masters (3 VMs)
firewall-cmd --zone=public --add-port=2379/tcp --permanent
firewall-cmd --zone=public --add-port=2380/tcp --permanent
firewall-cmd --zone=public --add-port=6443/tcp --permanent
firewall-cmd --zone=public --add-port=10250/tcp --permanent
firewall-cmd --zone=public --add-port=80/tcp --permanent
firewall-cmd --reload
4. Run Rancher Server and Create a Custom Cluster
5. Select all node roles and run it on all master nodes
6. Deploy a simple nginx with ingress to test performance
```
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
  labels:
    app: test-app-externalip
spec:
  ports:
  - port: 90
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: test-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testapp-ingress
spec:
  rules:
  - host: k8app.random.co
    http:
      paths:
      - backend:
          serviceName: test-app-svc
          servicePort: 90
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: tutum/hello-world
        ports:
        - containerPort: 80
```

**Results:**
When replica=1 everything works
When replica=2, if loadbalancer routes to the wrong pod it times out after 5 seconds
When replica=3, if loadbalancer routes to the wrong pod it times out after 5 or 10 seconds

2018/05/21 08:09:25 [error] 25#25: *2 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.30.5.62, server: k8app.random.co, request: "GET / HTTP/1.1", upstream: "http://10.42.2.8:80/", host: "k8app.random.co"
10.30.5.62 - [10.30.5.62] - - [21/May/2018:08:09:25 +0000] "GET / HTTP/1.1" 200 482 "-" "PostmanRuntime/7.1.5" 222 5.002 [default-test-app-svc-90] 10.42.2.8:80, 10.42.1.6:80 0, 691 5.000, 0.002 504, 200
