### ISSUE TITLE
RKE templates for Rancher HA Install lack the 'cluster-admin' ClusterRole

### ISSUE THREAD

**Issue by gaui** [rancher/rancher#13631]
The RKE templates where Rancher HA install is described, are lacking a `ClusterRole`.
I applied the exact template and always got this from the cattle pod:

```
$ kubectl logs cattle-59944644bc-xl65w --namespace=cattle-system
I0521 19:02:16.149674       1 http.go:105] HTTP2 has been explicitly disabled
2018/05/21 19:02:46 [INFO] Waiting for server to become available: Get https://10.43.0.1:443/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

So I stumbled up on this: https://rancher.com/kubernetes-authentication-in-rancher-and-rbac/

Where the `cluster-admin` ClusterRole is applied, but it's nowhere seen in the template.

```
          apiVersion: rbac.authorization.k8s.io/v1beta1
          kind: ClusterRole
          metadata:
           labels:
             kubernetes.io/bootstrapping: rbac-defaults
           name: cluster-admin
          rules:
          - apiGroups:
           - '*'
           resources:
           - '*'
           verbs:
           - '*'
          - nonResourceURLs:
           - '*'
           verbs:
           - '*'
```

URL in docs: https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/#part-5-download-config-file-template

URL in repo: https://github.com/rancher/rancher/tree/master/rke-templates
