### ISSUE TITLE
Rancher 2.0 HA installation nginx ingress always redirects to default backend

### ISSUE THREAD

**Issue by vishwakhrushi** [rancher/rancher#13677]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
 17.03.2-ce, build f5ec1e2
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux release 7.3.1611 (Core)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

I installed Rancher 2.0 in HA mode using the link below
https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/
But nginx ingress controller is always redirecting the page to default backend when trying to access the UI from the browser.

The following is my rancher-cluster.yml

```
nodes:
  - address: host1 
    user: username
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa 
  - address: host2
    user: username
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: host3
    user: username
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: <encrypted cert>
    tls.key: <encrypted key>   
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: <encrypted CA key>
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: hostname
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - hostname
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
```

The rancher server is running and able to access the service when it is exposed using a nodeport.

Below are the logs from my nginx-ingress-controller

> -------------------------------------------------------------------------------
> NGINX Ingress controller
>   Release:    154a606-dirty
>   Build:      154a606
>   Repository: git@github.com:rancher/ingress-nginx.git
> -------------------------------------------------------------------------------
> 
> I0523 22:15:26.345312       6 main.go:181] Creating API client for https://10.43.0.1:443
> I0523 22:15:26.388868       6 main.go:193] Running in Kubernetes Cluster version v1.10 (v1.10.1) - git (clean) commit d4ab47518836c750f9949b9e0d387f20fb92260b - platform linux/amd64
> I0523 22:15:26.394987       6 main.go:84] validated ingress-nginx/default-http-backend as the default backend
> I0523 22:15:26.952712       6 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace  (class nginx)
> I0523 22:15:26.952750       6 stat_collector.go:78] collector extracting information from port 18080
> I0523 22:15:26.980629       6 nginx.go:244] starting Ingress controller
> I0523 22:15:28.181346       6 store.go:613] running initial sync of secrets
> I0523 22:15:28.181491       6 nginx.go:266] starting NGINX process...
> I0523 22:15:28.181724       6 leaderelection.go:174] attempting to acquire leader lease...
> W0523 22:15:28.182671       6 controller.go:334] service ingress-nginx/default-http-backend does not have any active endpoints
> I0523 22:15:28.182816       6 controller.go:171] backend reload required
> I0523 22:15:28.182841       6 stat_collector.go:34] changing prometheus collector from  to default
> I0523 22:15:28.201680       6 leaderelection.go:184] successfully acquired lease ingress-nginx/ingress-controller-leader-nginx
> I0523 22:15:28.201806       6 status.go:192] new leader elected: nginx-ingress-controller-pckcq
> I0523 22:15:28.319770       6 controller.go:180] ingress backend successfully reloaded...
> W0523 22:15:30.696962       6 controller.go:334] service ingress-nginx/default-http-backend does not have any active endpoints
> I0523 22:15:30.717644       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"cattle-ingress-http", UID:"ce020bd4-5ed6-11e8-ad51-00155d71f510", APIVersion:"extensions", ResourceVersion:"666", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress cattle-system/cattle-ingress-http
> I0523 22:15:33.621549       6 backend_ssl.go:68] adding secret cattle-system/cattle-keys-ingress to the local store
> W0523 22:15:33.621671       6 controller.go:334] service ingress-nginx/default-http-backend does not have any active endpoints
> W0523 22:15:33.621731       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> I0523 22:15:33.621853       6 controller.go:171] backend reload required
> I0523 22:15:33.737245       6 controller.go:180] ingress backend successfully reloaded...
> W0523 22:15:36.952696       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> I0523 22:15:36.952822       6 controller.go:171] backend reload required
> I0523 22:15:37.036243       6 controller.go:180] ingress backend successfully reloaded...
> W0523 22:15:40.286117       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:15:43.619434       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:15:46.952677       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:15:50.286041       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:15:53.619350       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:15:56.952741       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> W0523 22:16:00.285996       6 controller.go:739] service cattle-system/cattle-service does not have any active endpoints
> I0523 22:16:03.619465       6 controller.go:171] backend reload required
> I0523 22:16:03.701690       6 controller.go:180] ingress backend successfully reloaded...
> I0523 22:16:28.256887       6 status.go:342] updating Ingress cattle-system/cattle-ingress-http status to [{ host1} { host2} { host3}]
> I0523 22:16:28.267315       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"cattle-ingress-http", UID:"ce020bd4-5ed6-11e8-ad51-00155d71f510", APIVersion:"extensions", ResourceVersion:"1630", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress cattle-system/cattle-ingress-http
> I0523 22:16:28.284627       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"cattle-ingress-http", UID:"ce020bd4-5ed6-11e8-ad51-00155d71f510", APIVersion:"extensions", ResourceVersion:"1632", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress cattle-system/cattle-ingress-http
> I0523 22:16:28.374184       6 backend_ssl.go:174] updating local copy of ssl certificate cattle-system/cattle-keys-ingress with missing intermediate CA certs
> I0523 22:16:30.286212       6 controller.go:171] backend reload required
> I0523 22:16:30.389020       6 controller.go:180] ingress backend successfully reloaded...
> 10.7.32.94 - [10.7.32.94] - - [23/May/2018:22:19:38 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.000 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.54.197 - [10.7.54.197] - - [23/May/2018:22:20:11 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.000 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.32.94 - [10.7.32.94] - - [23/May/2018:22:26:48 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.001 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.32.94 - [10.7.32.94] - - [23/May/2018:22:31:48 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.001 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.54.197 - [10.7.54.197] - - [23/May/2018:22:35:11 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.001 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.32.94 - [10.7.32.94] - - [23/May/2018:22:36:48 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.000 [upstream-default-backend] 10.42.1.4:8080 0 - -
> 10.7.32.94 - [10.7.32.94] - - [23/May/2018:22:41:48 +0000] "GET / HTTP/1.1" 499 0 "-" "SSLClient/1.0" 86 0.001 [upstream-default-backend] 10.42.1.4:8080 0 - -
> I0523 22:44:33.730946       6 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"cattle-ingress-http", UID:"ce020bd4-5ed6-11e8-ad51-00155d71f510", APIVersion:"extensions", ResourceVersion:"6058", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress cattle-system/cattle-ingress-http

**Comment by pensiero** [comment]
+1

**Comment by wanshaoyuan** [comment]
Your ingress is not configured with FQDN

```
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: <FQDN>  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - <FQDN>      # FQDN to access cattle server
```
