### ISSUE TITLE
Pipeline does not build if new tag

### ISSUE THREAD

**Issue by jungju** [rancher/rancher#13739]
rancher/rancher:v2.0.2

my pipeline config
```
name: xxxx-tag-push
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      sourceCodeCredentialId: xxxx
      url: https://github.com/xxxx/xxxx.git
- name: publish
  steps:
  - publishImageConfig:
      buildContext: .
      dockerfilePath: ./Dockerfile
      tag: xxxx/xxxx:${CICD_GIT_TAG}
triggerCronTimezone: Asia/Irkutsk
triggerWebhookTag: true
```
Pipeline should not build automatically whenever there is a new tag.

In the list, Trigger Manually is displayed.
![image](https://user-images.githubusercontent.com/809189/40596896-e0dad13a-6278-11e8-89f9-e24ac7d22dd5.png)

**Comment by tfiduccia** [comment]
@jungju - You have triggerWebhookTag: true, this needs to be set to false.  True means to build automatically for new tag.

**Comment by jungju** [comment]
@tfiduccia I want to run it automatically when I create a tag. But no.
triggerWebhookTag: true <- It seems that it does not work properly.

**Comment by tfiduccia** [comment]
@jungju - I'm sorry I don't understand what your problem is.  Your issue says that the Pipeline "should not" build automatically.  But you are saying you want it to build to automatically.  

So is your issue that when you create a new tag, the pipeline is not running automatically?

**Comment by tfiduccia** [comment]
This is a bug - I created a pipeline that should trigger when I create a new tag.  The pipeline triggered but I got an error.  When I run same pipeline manually, it works fine.  Here is the error:
![image](https://user-images.githubusercontent.com/11514927/40800695-f1673274-64c5-11e8-8da5-7ba0c9c6119b.png)

**Comment by gitlawr** [comment]
The error above should be irrelevant to original issue(It is triggered)
For the tag event not triggering the pipeline issue, you might need to check:

**Comment by gitlawr** [comment]
The issue should be fixed in the refactoring work. Moving to QA for validation

**Comment by bmdepesa** [comment]
rancher/rancher:master 9/5

Pipeline is executing on new tag.

**Comment by socar-dorma** [comment]
I using `rancher/rancher:v2.1.6`
I have the same problem. 

My pipeline trigger setting is `tag`.
```
"triggerWebhookPr": false,
"triggerWebhookPush": false,
"triggerWebhookTag": true,
```

Creating and pushing a new tag does not start the pipeline.

**Comment by gitlawr** [comment]
@socar-dorma those configurations are deprecated in 2.1.x
To enable build trigger for tag event:
1. Expand the action button for a enabled repo, then click `setting`:
![image](https://user-images.githubusercontent.com/5697937/53713495-04e27300-3e86-11e9-8b34-911777d04070.png)
2. On the pop-up window, enable the `tag` option.(only push event is enabled by default)
![image](https://user-images.githubusercontent.com/5697937/53713542-2fccc700-3e86-11e9-97f1-712fdaf54f98.png)

**Comment by socar-dorma** [comment]
@gitlawr my configuration..
![2019-03-05 5 07 45](https://user-images.githubusercontent.com/28700428/53790096-6cbdba00-3f69-11e9-91d6-9d1656c7a5d9.png)

I copy blow configuration.. from pipelines's `View in API` page.
```
"triggerWebhookPr": false,
"triggerWebhookPush": false,
"triggerWebhookTag": true,
```

**Comment by gitlawr** [comment]
@socar-dorma Can you check:
1. Is there a `.rancher-pipeline.yaml` file in your tag branch?
2. Is there any condition configuration in the pipeline file? It would be helpful if you can share the pipeline file

**Comment by socar-dorma** [comment]
My `.rancher-pipeline.yaml`... 
```
stages:
  - name: node-build
    steps:
      - runScriptConfig:
          image: node:10
          shellScript: |-
            # init for git submodule clone.
            ... some build script ....
        envFrom:
          - sourceName: secret_source...name
            sourceKey: secret_key...name
  - name: docker-build
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: dockerhubid/myimagename:k8s-${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: index.docker.io
  - name: deploy
    steps:
      - applyYamlConfig:
          path: ./deploy/k8s/api.k8s.yml
timeout: 600
triggerWebhookTag: true
branch:
  include:
    - develop
```
