### ISSUE TITLE
allowVolumeExpansion no work

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#13744]
**Rancher versions:**
rancher/rancher:v2.0.1

I configure glusterfs storageclass and works but Claim resize no.

change de size of pvc see error:
The PersistentVolumeClaim "xxxxxx" is invalid: spec: Forbidden: field is immutable after creation.

How I can configure "ExpandPersistentVolumes=true" in cluster?

**Comment by loganhz** [comment]
Hi @Itiho , I think Rancher doesn't allow edit existing PVC from UI. 
Where did you see the error?

**Comment by Itiho** [comment]
I dont use UI for edit pvc. I use YAML and kubectl. 

Claim resize need cluster configure  with "ExpandPersistentVolumes=true" option


https://akomljen.com/easy-way-to-resize-kubernetes-persistent-volumes/

**Comment by loganhz** [comment]
1. You can use RKE or something else to start a k8s cluster with the feature gate enabled and import it.
2. In Rancher v2.0,4, rancher supports edit cluster options as yaml. You can use the following yaml to provision k8s from Rancher UI.
 
```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
ignore_docker_version: true
ingress: 
  provider: "nginx"
kubernetes_version: "v1.10.3-rancher2-1"
network: 
  plugin: "canal"
services: 
  etcd: 
    extra_args: 
      heartbeat-interval: 500
      election-timeout: 5000
    snapshot: false
  kube_controller:
    extra_args: 
      feature-gates: ExpandPersistentVolumes=true
  kube_api: 
    pod_security_policy: false
    extra_args:
      admission-control: PersistentVolumeClaimResize,Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
      feature-gates: ExpandPersistentVolumes=true
ssh_agent_auth: false
```

![image](https://user-images.githubusercontent.com/21168270/41915792-288888de-7989-11e8-98d6-1218751ca595.png)

**Comment by Itiho** [comment]
I edit in API and give this error:

[kube-apiserver] on host [10.0.152.179]: Get https://localhost:6443/healthz: dial tcp 127.0.0.1:6443: getsockopt: connection refused, log: [admission-control plugin " Initializers" is unknown, admission-control plugin " NamespaceLifecycle" is unknown, admission-control plugin " LimitRanger" is unknown, admission-control plugin " ServiceAccount" is unknown, admission-control plugin " DefaultStorageClass" is unknown, admission-control plugin " DefaultTolerationSeconds" is unknown, admission-control plugin " NodeRestriction" is unknown, admission-control plugin " ResourceQuota" is unknown]



> {
    "addonJobTimeout": 30,
    "authentication": {
        "strategy": "x509",
        "type": "/v3/schemas/authnConfig"
    },
    "authorization": {
        "type": "/v3/schemas/authzConfig"
    },
    "bastionHost": {
        "sshAgentAuth": false,
        "type": "/v3/schemas/bastionHost"
    },
    "cloudProvider": {
        "type": "/v3/schemas/cloudProvider"
    },
    "ignoreDockerVersion": true,
    "ingress": {
        "provider": "nginx",
        "type": "/v3/schemas/ingressConfig"
    },
    "kubernetesVersion": "v1.10.3-rancher2-1",
    "network": {
        "canalNetworkProvider": {
            "iface": "",
            "type": "/v3/schemas/canalNetworkProvider"
        },
        "plugin": "canal",
        "type": "/v3/schemas/networkConfig"
    },
    "services": {
        "etcd": {
            "extraArgs": {
                "election-timeout": "5000",
                "heartbeat-interval": "500"
            },
            "snapshot": false,
            "type": "/v3/schemas/etcdService"
        },
        "kubeApi": {
            "extraArgs": {
                "admission-control": "PersistentVolumeClaimResize, Initializers, NamespaceLifecycle, LimitRanger, ServiceAccount, DefaultStorageClass, DefaultTolerationSeconds, NodeRestriction, ResourceQuota",
                "feature-gates": "ExpandPersistentVolumes=true"
            },
            "podSecurityPolicy": false,
            "type": "/v3/schemas/kubeAPIService"
        },
        "kubeController": {
            "type": "/v3/schemas/kubeControllerService"
        },
        "kubelet": {
            "failSwapOn": false,
            "type": "/v3/schemas/kubeletService"
        },
        "kubeproxy": {
            "type": "/v3/schemas/kubeproxyService"
        },
        "scheduler": {
            "type": "/v3/schemas/schedulerService"
        },
        "type": "/v3/schemas/rkeConfigServices"
    },
    "sshAgentAuth": false,
    "type": "/v3/schemas/rancherKubernetesEngineConfig"
}

**Comment by loganhz** [comment]
FYI, I have created the clusters successfully with AWS node driver.

1. Added a new cluster with the yaml successfully in v2.0.4
2. Updated an existing ready cluster with the yaml successfully in v2.0.4

![image](https://user-images.githubusercontent.com/21168270/41923466-0f85d664-799a-11e8-9fa5-b9be45f865a5.png)

**Comment by loganhz** [comment]
We can config `ExpandPersistentVolumes=true` as `extra_args` in cluster yaml via UI.
Close this issue as it is for how to config `ExpandPersistentVolumes=true`. Please feel free to create another issue if you still see the problem.

![image](https://user-images.githubusercontent.com/21168270/42141234-5ef48e54-7dda-11e8-85e0-f5ba992d39da.png)

**Comment by Itiho** [comment]
Edit in api get 

This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [xxx.xxx.xxx.xxx]: Get https://localhost:6443/healthz: dial tcp [::1]:6443: getsockopt: connection refused

**Comment by loganhz** [comment]
Can you look at the container log of api server, please? Is there any clue?

**Comment by Negashev** [comment]
example of 2.1.3 version

```
services: 
  etcd: 
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: true
  kube-api: 
    extra_args: 
      enable-admission-plugins: "PersistentVolumeClaimResize,Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota"
      feature-gates: "ExpandPersistentVolumes=true"
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kube-controller: 
    extra_args: 
      feature-gates: "ExpandPersistentVolumes=true"
  kubelet: 
    extra_args: 
      volume-plugin-dir: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
    extra_binds: 
      - "/usr/libexec/kubernetes/kubelet-plugins/volume/exec:/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
    fail_swap_on: false
ssh_agent_auth: true
```
