### ISSUE TITLE
Setting boolean flag in questions.yaml, show wrong value in answers

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#13842]
**Rancher versions:** 2.0 master 6/4

**Steps to Reproduce:**
1.  Create a helm chart that has a boolean question type.
2.  make the default = true
3.  Add Helm catalog to rancher
4.  Go to catalog app
5.  Change question a to false

Results:  answers shows it as "true"
![image](https://user-images.githubusercontent.com/11514927/40951487-171b1a44-682c-11e8-914c-dd31c6965051.png)

Example of questions.yaml
```
categories:
  - things
  - stuffs
questions:
  - variable: a
    type: boolean
    description: The A"
    default: true
```

**Results:**
