### ISSUE TITLE
Can't mix volumes with rancher-nfs and null driver since 1.6.15

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#13851]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.15
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
nfs: 0.5.0

**Steps to Reproduce:**

```yaml
version: '2'
volumes:
  foo:
    external: true
    driver: rancher-nfs
  bar:
    external: true
    driver: null
services:
  foo:
    image: debian:stable
    volumes:
    - foo:/foo
    - bar:/bar
```

**Results:**

Generated yaml is:
```yaml
version: '2'
volumes:
  foo:
    external: true
    driver: rancher-nfs
  bar:
    external: true
services:
  foo:
    image: debian:stable
    volumes:
    - foo:/foo
    - bar:/bar
```
And `bar` volume points to rancher-nfs.
It used to work with rancher-nfs 0.4.0.
