### ISSUE TITLE
Nginx-ingress-controller did not remove ingress ip after node is powered down

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13862]
**Rancher versions:**
rancher/rancher:cee0b2b

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Steps to Reproduce:**
1. Add 2 worker nodes to the cluster
1. update `setting.ingress-ip-domain` to `lb.rancher.cloud`
2. Create ingress, then I can see two ingress ip
```
status:
  loadBalancer:
    ingress:
    - ip: 172.31.10.135
    - ip: 172.31.13.78
```
3. Shutdown one of the worker nodes (e.g. 172.31.13.78)
**Results:**
An hour later, I noticed that nginx-ingress-controller did not remove ingress ip 172.31.13.78
```
# kubectl get ing nginx-lb -o yaml
...
...
...
status:
  loadBalancer:
    ingress:
    - ip: 172.31.10.135
    - ip: 172.31.13.78
```

gzrancher/rancher#10761

**Comment by h-dang** [comment]
Hi, I am having same problem
Using 5 nodes, configure only 3 nodes for 1 deployment
then check the ing, its still list 5 ip of 5 nodes.

**Comment by h-dang** [comment]
Even access cluster console, using kubectl to update ing, it still the same

**Comment by kinarashah** [comment]
1) Check if the issue reproduces on the latest version 
2) Look at nginx-ingress status.go, where the ingress's LB endpoints get calculated: https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/internal/ingress/status/status.go#L197 

LOE: 2 days (investigate+implement)

**Comment by kinarashah** [comment]
@sowmyav27 New k8s versions with updated ingress images are now available in dev branches for 2.4 and 2.5. 

`dev-v2.4`
| Image | Min Rancher version 
|- | -- |
|`v1.16.15-rancher1-3` | v2.4.4 |
|`v1.17.13-rancher1-2`| v2.4.4 |
|`v1.18.10-rancher1-2`| v2.4.5  |

`dev-v2.5`
| Image | Min Rancher version 
|- | -- |
|`v1.17.13-rancher1-2` | v2.4.4 |
|`v1.18.10-rancher1-2`| v2.4.5 |
|`v1.19.3-rancher1-2`| v2.5.0  |

**Comment by sowmyav27** [comment]
**Reproduced the issue On 2.4.8**

- Bring up a custom rke cluster - 1 etcd/control and 3 worker nodes.
- Deploy a workload and an ingress.
- View/Edit in YAML of the ingress.
- 3 ingress IPs will be listed

```
status:
  loadBalancer:
    ingress:
    - ip: <worker-1>
    - ip: <worker-2>
    - ip: <worker-3>
```
- Power down w1 node.
- The ingress IPs still show 3 worker nodes' ip addresses

**On 2.4-head commit id: `6ab3cb450` , 2.5-head -commit id: `1599dc142` and master-head - commit id: `9124f6ed18`**

- 1.18.10-rancher1-2 on 2.4-head and 1.19.3-rancher1-2 on 2.5-head and master-head
- Bring up a custom rke cluster - 1 etcd/control and 3 worker nodes.
- Deploy a workload and an ingress.
- View/Edit in YAML of the ingress.
- 3 ingress IPs will be listed

```
status:
  loadBalancer:
    ingress:
    - ip: <worker-1>
    - ip: <worker-2>
    - ip: <worker-3>
```
- Power down w1 node.
- The ingress IPs show only ip addresses of w2 and w3
