### ISSUE TITLE
Restricted users should be able to exec shell into containers with CAP_ADD

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13886]
**Rancher versions:**
rancher/server: v1.6.18

**Steps to Reproduce:**

Launch stack with cap_add added in compose:

```
version: '2'
services:
  db:
    image: mariadb 
    cap_add: 
    - KILL 
```

Try to execute shell as Restricted user

**Results:**
Execute shell is not available in the menu, due to https://github.com/rancher/cattle/blob/v1.6/code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/filter/instance/InstanceOutputFilter.java#L96
