### ISSUE TITLE
Execute Shell should keep showing on first open and selected container does not have sh/bash

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#13958]
Version: master 6/12

Launch a pod with multiple containers like example below, where first does not have `/bin/sh` or `/bin/bash` (`traefik`)

```
apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  containers:
  - name: 1st
    image: traefik
  - name: 2nd
    image: debian
    volumeMounts:
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          sleep 1;
        done
```

Open `Execute Shell` on the pod

Results:
Docker error is shown `no such file or directory` and window closes before you can choose the 2nd container.

We should at least keep the window open so users can switch, even better if we warn that there is no shell in the current container.
