### ISSUE TITLE
kubectl proxy doesn't work with default ingress

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13979]
Deployment model: Rancher HA on Kubernetes

With the current Rancher centralized authentication model, the default ingress documented prevents the kubectl proxy to work correctly.

It's not possible to use `http://127.0.0.1:8001` with `kubectl proxy` using a kubeconfig pointing to the Rancher server.

It can be possible to use `http://localhost:8001`, but you must first change your ingress resource to include this host name, e.g an ingress helm template:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: cattle-system
  name: cattle-ingress-https
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
spec:
  rules:
  - host: {{ .Values.rancher.fqdn | quote }}
    http:
      paths:
      - backend:
          serviceName: cattle-service
          servicePort: 80
  - host: "localhost"
    http:
      paths:
      - backend:
          serviceName: cattle-service
          servicePort: 80
  tls:
  - secretName: cattle-keys-ingress
    hosts:
    - {{ .Values.rancher.fqdn | quote }}
```

We should document this use case.

Current doc: https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/
