### ISSUE TITLE
Mount host ssl certs to Rancher server

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13973]
There isn't any configuration to mount some additional host volumes to Rancher server when deployed on Kubernetes, nor is there any logic to mount different kind of host volumes to make the certificates in the host PKI store visible to the container.

Not having the host certificates means that Rancher cannot speak to some on-prem cloud providers, e.g openstack or vmware, if the target apis have self-signed CA certificates.

Obviously, the path for the host pki store is different from one distro to another. I'm wondering if we could make some initContainers to try different things to detect this automatically and copy the pki files over to an emptyDir folder for Rancher. Then, have this added in the official deployment manifest.

Or at the very least, document the use case and the required changes in the deployment manifest.

BTW, the manifest here seems highly dated and definitely could be improved:  https://github.com/rancher/rancher/blob/master/deploy.yml

**Comment by aemneina** [comment]
@alexandrem can you try with the following: 
Launch a rancher server container with with a couple extra parameters:
- First bind mount your cert to the rancher server container, say:/path-to-cert/cacerts.pem:/etc/cacerts/cacerts.pem
- Then add an environmental variable SSL_CERT_DIR=/etc/cacerts and your certificates should be recognized.

Let me know if that does the trick for you

**Comment by alexandrem** [comment]
I didn't know about the SSL_CERT_DIR, so that's interesting.

My current workaround at the moment is doing this for my Rancher deployment (my host is centos-7):

```yaml
      initContainers:
      - name: init-certificates
        image: alpine
        command:
        - /bin/sh
        - -exc
        - |
          cd /etc/ssl/certs
          cat ca-bundle.crt  | tee ca-certificates.crt
        volumeMounts:
        - mountPath: /etc/pki
          name: etc-pki-host
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
      containers:
      - image: "{{ .Values.rancher.image }}:{{ .Values.rancher.imageTag }}"
        imagePullPolicy: Always
        {{- if .Values.rancher.tls_ca }}
        args:
          - --no-cacerts
          #- --debug
        {{- end }}
        name: cattle-server
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/rancher/ssl
          name: cattle-keys-volume
          readOnly: true
        - mountPath: /etc/pki
          name: etc-pki-host
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
      volumes:
      - name: cattle-keys-volume
        secret:
          defaultMode: 420
          secretName: cattle-keys-server
      - name: ssl-certs-host
        hostPath:
          path: /etc/ssl/certs
      - name: etc-pki-host
        hostPath:
          # for centos-7
          path: /etc/pki
```
