### ISSUE TITLE
Rancher Up - Unable to remove node pool

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#13983]
**Rancher versions:**
rancher-v2.0.2-rc1

**Steps to Reproduce:**

Perform rancher up with a two node pool yml file. (Example attached) 

```
Version: v3
clusters:
  testingcluster:
    rancherKubernetesEngineConfig:
      addonJobTimeout: 30
      authentication:
        strategy: x509
      authorization: {}
      bastionHost: {}
      cloudProvider: {}
      ignoreDockerVersion: true
      ingress:
        provider: nginx
      kubernetesVersion: v1.10.3-rancher2-1
      network:
        plugin: canal
      services:
        etcd:
          extraArgs:
            election-timeout: "5000"
            heartbeat-interval: "500"
        kubeApi: {}
        kubeController: {}
        kubelet: {}
        kubeproxy: {}
        scheduler: {}
nodePools:
  np-x8q8f:
    clusterId: testingcluster
    hostnamePrefix: austinworker
    nodeTemplateId: defaultDO
    quantity: 2
    worker: true
  np-zm88b:
    clusterId: testingcluster
    controlPlane: true
    etcd: true
    hostnamePrefix: austinallroles
    nodeTemplateId: defaultDO
    quantity: 1
    worker: true
```

Remove worker node pool from yml file.
Perform rancher up with updated yml.

**Results:**
Removed node pool is not deleted from rancher server.
