### ISSUE TITLE
can't remove the worker role from controlplane nodes.

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rancher#14133]
rancher version 2.0.2

First I've run rke with `role: [controlplane,worker]` selected for `controlplane` nodes, then tried to isolate my workers by removing `worker` role from that list for `controlplane` nodes and then rerun the `./rke up ....` with `role: [controlplane]` without `worker` for my `controlplane` nodes but still the `worker` role present in that `controplane` nodes.
It works with `etcd` normally, i.e. if I'm adding `worker` role for `etcd` nodes it adds normaly and then if I remove from role list and rerun `rke up ....` it removes normally and correspondingly the `etcd` nodes become unschedulable but with `controlplane` it doesn't work.

seems it shows the worker role wrongly on web UI only, but with kubectl it shows that the role was removed normally from controlplane nodes as well.
see the screenshots, on web interface the worker role is still present for controlplane nodes but with kubectl it's not.
<img width="984" alt="screen shot 2018-06-21 at 10 21 07 pm" src="https://user-images.githubusercontent.com/16855630/41737876-989f676e-75a1-11e8-8e34-99a9d2bb26e4.png">
<img width="502" alt="screen shot 2018-06-21 at 10 17 26 pm" src="https://user-images.githubusercontent.com/16855630/41737888-9eaa8df0-75a1-11e8-8ee3-2ba1fb507a46.png">

config:
```
nodes:
  - address: ny-vm3-etcd1-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [etcd] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

  - address: ny-vm4-etcd2-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [etcd] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

  - address: ny-vm5-etcd3-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [etcd] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

  - address: ny-vm3-orch1-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [controlplane] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

  - address: ny-vm4-orch2-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [controlplane] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file

  - address: ny-vm4-master2-prod # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [worker] # K8s roles for node
    ssh_key_path: ~/.ssh/id_rsa # path to PEM file
............ ............. ...................
............ ............. ...................
```
