### ISSUE TITLE
Scaling up a workload creates new pods as part of scale up on a fresh install

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#14171]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.3-rc4

**Steps to Reproduce:**
1. Create a cluster in v2.0.3.
2. Create workload wk1 with scale 2
3. Scale up the workload from 2 to 3

Three new pods are created and the original two are removed.
New pods are created and the old ones are deleted.
<img width="1165" alt="screen shot 2018-06-22 at 2 07 32 pm" src="https://user-images.githubusercontent.com/18536626/41799255-a3737520-7625-11e8-8d0d-2b059e7e1bac.png">

**Comment by alena1108** [comment]
Happens because on some updates Rancher inserts empty `Capabilities` parameter into a security context, and in some cases the parameter is dropped:

```
securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
```

vs

```
securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
```


That results in updating pod spec, and that in turns triggers pods recreate. Doesn't happen always, just time to time.
Looks like this bug existed since 2.0.2 (may be even earlier).
