### ISSUE TITLE
Problem regarding the OpenStack cloud-config

### ISSUE THREAD

**Issue by dabeck** [rancher/rancher#14197]
**Rancher versions:**
rancher/rancher:v2.0.3

**Type/provider of hosts:**
custom OpenStack provider

**Steps to Reproduce:**
Create a new Cluster within rancher 2.0.3 with a custom cloud-config and a OpenStack cloud-provider config:

```
...
cloud_provider:
  name: openstack
  openstackCloudProvider:
    global:
      auth-url: "https://example.../v3"
      domain-name: "domain"
      password: "password"
      region: "eu-de"
      tenant-id:  "id"
      username: "user"    
    load_balancer:
      subnet-id: "4ba20e2c-bb89-468f-81c6-2c67a4bac419"
      floating-network-id: "0a2228f2-7f8a-45f1-8e09-9039e1d09975"
```

**Results:**
The generated cloud-config is corrupted:
```
$ cat /etc/kubernetes/cloud-config 
[Global,omitempty]
auth-url,omitempty = https://example.../v3
username,omitempty = user
user-id,omitempty = 
password,omitempty = password
tenant-id,omitempty = id
tenant-name,omitempty = 
trust-id,omitempty = 
domain-id,omitempty = 
domain-name,omitempty = domain
region,omitempty = eu-de
ca-file,omitempty = 

[LoadBalancer,omitempty]
lb-version,omitempty = 
use-octavia,omitempty = false
subnet-id,omitempty = 4ba20e2c-bb89-468f-81c6-2c67a4bac419
floating-network-id,omitempty = 0a2228f2-7f8a-45f1-8e09-9039e1d09975
lb-method,omitempty = 
lb-provider,omitempty = 
create-monitor,omitempty = false
monitor-delay,omitempty = 0
monitor-timeout,omitempty = 0
monitor-max-retries,omitempty = 0
manage-security-groups,omitempty = false

[BlockStorage,omitempty]
bs-version,omitempty = 
trust-device-path,omitempty = false
ignore-volume-az,omitempty = false

[Route,omitempty]
router-id,omitempty = 

[Metadata,omitempty]
search-order,omitempty = 
request-timeout,omitempty = 0
```

See [comment](https://github.com/rancher/rke/pull/667#issuecomment-398708511)
