### ISSUE TITLE
rke deployment failed

### ISSUE THREAD

**Issue by coyoty** [rancher/rancher#14253]
RKE version:
v0.1.8-rc7
Docker version: (docker version,docker info preferred)
17.03.2-ce
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Ubuntu 16.04.4 LTS : 4.4.0-128-generic
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS 
cluster.yml file:

```
nodes:
  - address: xxx.xxx.xxx.xxx # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: id_rsa.pem # path to PEM file
  - address: xxx.xxx.xxx.xxx
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: id_rsa.pem
  - address: xxx.xxx.xxx.xxx
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: id_rsa.pem

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: xxx
    tls.key: xxx
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      spec:
    rules:
    - host: rancher.xx.xx 
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - rancher.xx.xx
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP

```
Steps to Reproduce: 
Run
`./rke_linux-amd64 up --config rancher-cluster.yml`

Get:
```
INFO[0170] [addons] Executing deploy job..
ERRO[0200] Failed to get job complete status: <nil>
WARN[0200] Failed to deploy addon execute job [rke-user-includes-addons]: Failed to get job complete status: <nil>
INFO[0200] Finished building Kubernetes cluster successfully
```

Run 
`kubectl --kubeconfig kube.yml logs -l job-name=rke-user-addon-deploy-job -n kube-system`

Get:
```
namespace "cattle-system" configured
serviceaccount "cattle-admin" unchanged
clusterrolebinding.rbac.authorization.k8s.io "cattle-crb" configured
secret "cattle-keys-ingress" unchanged
service "cattle-service" unchanged
error: error validating "/etc/config/rke-user-addon.yaml": error validating data: [unknown object type "nil" in Ingress.metadata.annotations.spec, ValidationError(Ingress.metadata): unknown field "rules" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(Ingress.metadata): unknown field "tls" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]; if you choose to ignore these errors, turn validation off with --validate=false
```
