### ISSUE TITLE
Rancher 2 HA setup Error connecting to WebSocket

### ISSUE THREAD

**Issue by damcar** [rancher/rancher#14264]
Rancher versions: 2.0.2

I followed the [official guide](https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install/) to install rancher in HA (3 hosts) setup but I have this alert regularly :

![rancher](https://user-images.githubusercontent.com/15870832/41998702-aa740850-7a5b-11e8-8fe4-c2dde05be6eb.png)

Whats is the reason for this alert ?

**Comment by alexandrem** [comment]
I suppose you have more than 1 replica for your rancher deployment.

Try adding this to your ingress resource annotations (assuming you have nginx):

```yaml
nginx.ingress.kubernetes.io/affinity: "cookie"
nginx.ingress.kubernetes.io/session-cookie-name: "route"
nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
```
