### ISSUE TITLE
Add tolerations to cattle-node-agent DaemonSet

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#14296]
With etcd and controlplane being tainted, it needs tolerations to be scheduled.

Workaround: https://gist.github.com/superseb/257549cc2eeea197bae0667ac41abefa

**Comment by Itiho** [comment]
Apply the same solution to in nginx-ingress-controller

`kubectl patch daemonset nginx-ingress-controller -n ingress-nginx --patch "$(curl -sL https://gist.githubusercontent.com/superseb/257549cc2eeea197bae0667ac41abefa/raw/ad01acda10e21ae6eebd7e65f55b9bf4b66176bc/ds-cattle-node-agent-tolerations-patch.yml)`

**Comment by alena1108** [comment]
@Itiho could you file a separate issue for ingress controller

**Comment by Itiho** [comment]
@alena1108 I dont find ingress-controller template.

**Comment by bmdepesa** [comment]
rancher/rancher:master 6/29

Tolerations are added correctly to the daemonset, and cattle-node-agent is running on each plane correctly.

**Comment by travisghansen** [comment]
Is there any reason this isn't ignoring all taints?  As is I'm unable (without making below modifications) to use taints outside of the ones applied by default.  This is what I've seen CNI drivers do for example...

```
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
```
