### ISSUE TITLE
With  EBS volume driver, add capability to specify ebs snapshot by tag key and value pair

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14315]
snapshotTag: driver option to specify tag value
snapshotTagName: driver option to specify tag key (defaults to "Name")

**Comment by deniseschannon** [comment]
```
version: '2'
services:
  foo1:
    image: busybox
    stdin_open: true
    volumes:
    - bar:/var/lib/storage
  foo2: 
    image: busybox
    volumes:
    - bar:/var/lib/storage

volumes:
  bar:
    driver: rancher-ebs
    driver_opts:
      snapshotTagName:  <TAG_KEY>
      snapshotTag: <TAG_VALUE>```

**Comment by soumyalj** [comment]
Tested with v1.6.19-rc4 using EBS v0.6.0
1. Created a snapshot of an already existing EBS volume with data . Used the snapshotTagName, snapshotTag in driver options as below:
```
version: '2'
services:
  foo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - mytestvol1:/mydata
volumes:
  mytestvol1:
    driver: rancher-ebs
    driver_opts:
      size: '5'
      snapshotTagName: testsnapshot
      snapshotTag: testsnapshotvalue
```
The stack was created successfully and the data was available in the volume. Data write to the volume was fucntional

2. Created a new volume in EBS, attached volume to an ec2 instance and performed "mkfs"
Created snapshot of the volume and used snapshotTagName, snapshotTag in driver options as above. The stack was created successfully and data write to the volume was functional.
