### ISSUE TITLE
Enable cfgparam disk.enableUUID=1 by default when using the vSphere node driver

### ISSUE THREAD

**Issue by LinAnt** [rancher/rancher#14334]
**Rancher versions:**
rancher/rancher: v2.0.3
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services: flannel
scheduler:
kubernetes (if applicable): 1.10.3

**Docker version: (`docker version`,`docker info` preferred)**

```
[docker@dev-us-2-etcd2 ~]$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.4-vmware

```
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

`4.14.32-rancher2`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere 6.5
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher

**Steps to Reproduce:**

Provision a cluster
Specify image, I used rancherOS 1.4-vmware
When cluster is up, deploy a workload with a PVC volume

**Results:**
Volume will get attached to the correct VM then it bugs out.
The reason behind this is that the VMWare VCP requires `disk.EnableUUID` to be set to true for all VMs in order to be successful in mounting the persistent disks.

How to fix temporarily:

1. Install govc
2. locate all the VMs in your cluster and the correct path to them inside vSphere
3. Run this script to turn set the flag:
```
#! /bin/sh
GOVC_INSECURE=1 # or 0
GOVC_URL=<vcenterIP>
GOVC_USERNAME=<vsphere-username>
GOVC_PASSWORD=password123

VMFOLDER="/<cluster>/vm/<vm-folder>/" # can be obtained through govc ls and then you just iterate untill you locate your VMs
for vm in vm1 vm2 vm3
do
    govc vm.change -e="disk.enableUUID=1" -vm="$VMFOLDER$vm"
done
```

The cloud-provider section of the cluster config:

```yaml
cloud_provider: 
  name: "vsphere"
  vsphere_cloud_provider: 
    disk: 
      scsicontrollertype: "pvscsi"
    global: 
      insecure-flag: false
      password: "password123"
      port: "443"
      soap-roundtrip-count: 0
      user: "<vsphere-user>"
    virtual_center: 
      <vpshere-IP>: 
        password: "password123"
        soap-roundtrip-count: 0
        user: "<vsphere-user>"
    workspace: 
      datacenter: "<datacenter>"
      default-datastore: "vsanDatastore"
      folder: "<vmfolder>"
      resourcepool-path: "<resourcepool path>"
      server: "<vsphere-ip>"
```

**Comment by superseb** [comment]
According to https://www.veritas.com/support/en_US/doc/129690088-129690091-0/uxrt-731_v85424878-129690091, this can be set using cfgparam which is exposed in the UI when creating a node pool. If that works, we can build in logic to automatically enable this if the cloud provider is configured.

**Comment by spawnia** [comment]
This can be added in the Node Template under "Configuration Parameters used for guestinfo"

I added it as "disk.enableUUID=TRUE", it works fine.

**Comment by LinAnt** [comment]
@spawnia Do you provision your storage classes through the UI as well? I can't seem to get them to work. Through the kubectl CLI it works fine. I have done extensive testing yet.

**Comment by spawnia** [comment]
This is caused by a type in the UI, see #14333

I created a PR to the UI, in the meantime, you can just use this:

```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: thin
```
