### ISSUE TITLE
Existing pods deleted on scale up with ingress. 

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#14352]
**Rancher versions:**
V2.0.5-rc2

Steps to Reproduce:
Create a new deployment workload
Create Ingress, target created workload.
Scale up workload.

Results:
Existing pods are re-created when scale up finishes. We only need to add one pod and keep existing pods.

**Note** This does not occur every time. I was not able to reproduce unless ingress was added to  workload.

**Comment by alena1108** [comment]
I don't think it has anything to do with ingress, as we don't put any reference to it on the workload. The issue is most likely to do with this fix:

https://github.com/rancher/types/pull/483

Before the fix, the way we do workload updates were inconsistent, and capabilities field representation in the pod spec on the underlying deployment could take one of two different representations, and the diff could cause pod recreate. @StrongMonkey fixed it so it is always representation 1. But workloads that are created prior to 2.0.4 could still have pods recreated when the update runs for them on 2.0.5, and it is something we have to document.

@StrongMonkey can you make sure that the above is the cause for the behavior @adingilloRancher is seeing, by comparing the yml spec before and after update.

**Comment by StrongMonkey** [comment]
I can confirm that this is due to the change we introduced in rancher/types#483. This will only happens before and after upgrade, which before upgrade we add an empty "capability: {}` to it and it will get removed if you edit it after upgrade. This should not happen in a fresh setup.
@austin Can you confirm that it will only happen when you do upgrade testing?  
@alena Yes we should document it.

**Comment by alena1108** [comment]
@StrongMonkey can we check that it doesn't happen on fresh V2.0.5-rc2. Double check with @adingilloRancher on user cluster specifics - provider, k8s version (wonder if that could cause differences in behavior)

**Comment by StrongMonkey** [comment]
@adingilloRancher We have to collect the yaml output of the workload to identify which part has changed to cause pod recreation. Normally if you create a workload without specifying anything, the pod template looks like
```
template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-test
    spec:
      affinity: {}
      containers:
      - image: sangeetha/testnewhostrouting
        imagePullPolicy: Always
        name: test
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30reproduciable
```
If the pod get recreated after scaling up, then something must changed in the pod template. We should be able to identify the change and root cause the issue according to what's changed in the yaml.(since it is not always reproducible).
