### ISSUE TITLE
Clusterwide DNS failure after editing existing cluster and add cloud provider configuration

### ISSUE THREAD

**Issue by jepp2078** [rancher/rancher#14385]
**Rancher versions:**
rancher/rancher: v2.0.3
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 1.10.3-rancher2-1

**Docker version: (`docker version`,`docker info` preferred)**
```
[docker@integration-test-worker1 ~]$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.2
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:03 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
[docker@integration-test-worker1 ~]$ cat /etc/os-release
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
```
4.14.32-rancher2
``` 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere 6.5

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Steps to Reproduce:**
Create a 1.10.3-rancher2-1 cluster with Canal network provider.

1x etcd+control node
3x worker nodes

Let it finish creating.

Create a busybox:latest container and do a:

```
nslookup google.com
```

Confirm it can resolve the DNS as per:

```
nslookup google.com
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2a00:1450:400f:808::200e arn09s10-in-x0e.1e100.net
Address 2: 216.58.211.142 arn09s10-in-f14.1e100.net
```

Apply the following cloud provider:

```
cloud_provider: 
  name: "vsphere"
  vsphere_cloud_provider: 
    disk: 
      scsicontrollertype: "pvscsi"
    global: 
      insecure-flag: true
      password: <redacted>
      port: "443"
      soap-roundtrip-count: 0
      user: <redacted>
    virtual_center: 
      <redacted>: 
        password: <redacted>
        soap-roundtrip-count: 0
        user: <redacted>
    workspace: 
      datacenter: <redacted>
      default-datastore: <redacted>
      folder: <redacted>
      server: <redacted>
```

Wait 10minutes.

Open a shell to the same busybox container as before.

Do nslookup again, the output should be:

```
nslookup google.com
Server:    10.43.0.10
Address 1: 10.43.0.10

nslookup: can't resolve 'google.com'
```

**Results:**
Pods can't communicate with the internal kube-dns.

**kubectl output**
```
kubectl get nodes
NAME       STATUS    ROLES               AGE       VERSION
control1   Ready     controlplane,etcd   5m        v1.10.3
worker1    Ready     worker              3m        v1.10.3
worker2    Ready     worker              3m        v1.10.3
worker3    Ready     worker              3m        v1.10.3
```
```
kubectl get pods --all-namespaces
NAMESPACE       NAME                                    READY     STATUS    RESTARTS   AGE
cattle-system   cattle-cluster-agent-c9d7b9d89-s9bzj    1/1       Running   2          13m
cattle-system   cattle-node-agent-28j6n                 1/1       Running   0          13m
cattle-system   cattle-node-agent-7jp5h                 1/1       Running   0          13m
cattle-system   cattle-node-agent-fh9c8                 1/1       Running   0          13m
default         test-7f58ddc49b-ntmbw                   1/1       Running   0          11m
ingress-nginx   default-http-backend-564b9b6c5b-hvncz   1/1       Running   0          13m
ingress-nginx   nginx-ingress-controller-2q8n9          1/1       Running   0          13m
ingress-nginx   nginx-ingress-controller-96cqv          1/1       Running   0          13m
ingress-nginx   nginx-ingress-controller-vzkxd          1/1       Running   0          13m
kube-system     canal-4mtcx                             3/3       Running   0          13m
kube-system     canal-jk99z                             3/3       Running   0          13m
kube-system     canal-tnf4p                             3/3       Running   0          13m
kube-system     canal-x2qhp                             3/3       Running   0          13m
kube-system     kube-dns-5ccb66df65-66rxf               3/3       Running   0          13m
kube-system     kube-dns-autoscaler-6c4b786f5-qwlrq     1/1       Running   0          13m
```

**Additional info**
@LinAnt has reproduced on his similar vSphere setup.

Also tested with Calico and Flannel. Same issue.
