### ISSUE TITLE
Add support for turning off network policies for Canal for  k8s clusters that are launched by Rancher (custom cluster or node pools)

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#14462]
We should add support for:

* Canal having network policies OFF
* Switching from Canal having network policies ON to OFF

**Comment by alwinmarkcf** [comment]
And I got the next Problem cattle is doing bad magic which does not work and is broken by design. I wanted to expose a pod threw an ingress. After my Problems with #14085 I removed all Namespaces from any Project in Rancher 2.0

Unfortunately Cattle does not care at all and applied a random network-policy only allowing the pod itself to connect to the ports.

```
- apiVersion: extensions/v1beta1                                                                                                                                                                                                              
  kind: NetworkPolicy                                              
  metadata:                                                                 
    creationTimestamp: 2018-07-12T11:49:54Z                                                 
    generation: 1                                                             
    name: hp-icinga-0                                                                                                                                                       
    namespace: cf-system                                                                                                                                                                                                                       
    ownerReferences:                                                                                                                                                                                                                          
    - apiVersion: v1
      kind: Pod
      name: icinga-0
      uid: b192c914-85c9-11e8-bf76-001b21bca8d2
    resourceVersion: "3633886"
    selfLink: /apis/extensions/v1beta1/namespaces/cf-system/networkpolicies/hp-icinga-0
    uid: b19621f1-85c9-11e8-a3a9-001b21bca8b8
  spec:
    ingress:
    - ports:
      - port: 5665
        protocol: TCP
    podSelector:
      matchLabels:
        field.cattle.io/podName: icinga-0
    policyTypes:
    - Ingress
```

This is not only problematic because of this single container, but this was the only policy as this namespace shouldn't be managed at all, so the policies made in #14085 were not applied (not even tried because this would break another thing). 

Great job again! So there is now way someone is able to run Rancher 2.0 in production.

So Rancher only had one usecase where we had to debug and tweak rancher itself because it is using an ancient API. Feedback to our foundings... No, except that the documentation becomes updated... which it didn't.

**Comment by vincent99** [comment]
@alwinmarkcf this issue is specifically to turn off all management of network policies by rancher, which is what you wanted in the first place.

I'm going to tell you this one time: your tone  in these issues is condescending, rude, and  not welcome here. If you cannot conduct yourself in a professional manner, you are going to be banned the next time I see it.

**Comment by alwinmarkcf** [comment]
@vincent99 so what do i have to change with my **tone** (or better style of writing)?

Just the facts:
In rancher 1.6 rancher enforces to be on first place in iptables which leads to exposing all services which were before protected by the only working workarround many have used.

By doing so, now tons of rancher clusters are insecure now. If you don't believe me just do portscans on Rancher or Docker Community Users, which are using rancher on similar hosters like Hetzner.

I politly opened a non intrusive PR which is still open where sb. politly thanked for contribution but rudely ignored it.

Then with rancher 2.0 the same thing happens again. Instead of fixing the issue you are arguing about "tones" even though the problem is already quite clear.

So these are just the facts and don't kill the messenger. If you think this is the wrong tone, you may have a problem with the reality you've created.

So simply ask yourself, would you recommend someone contributing to an OSS Project where your contributions are ignored? (Don't believe me, than just takr a look on the contributers and open or closed PRs)

Next Question: would you recommend using an OSS Project  with these kind of security wholes not patched in several months? Even worse, not stating officially that these issues exist (e.g. in Rancher 2.0 or rke while trying to use calico)?

And finally, wouldn't you say ignoring and holding people out is rude as well?

**Comment by alwinmarkcf** [comment]
@mychalsexton this is  not working with calico as Calico create a NP and opens it for everything as it can't determine node ip https://github.com/rancher/rancher/issues/14085

Then you only can blacklist services, while i prefer whitelisting as it is more secure as you can't oversee securitywholes as easy.

**Comment by vincent99** [comment]
And we're done here.

**Comment by sangeethah** [comment]
@kinarashah As part of this issue , will we handle the following use cases?
1. Network policies will not be programed for RKE clusters which uses calico/flannel networking.
2. Network policies will not be programed for clusters other than RKE clusters , like GCE. EKS and AKS.
3. If an imported cluster is RKE and and has canal networking with network policy turned on , will we program Network policies in this case ?

**Comment by deniseschannon** [comment]
spoke with @kinarashaha about this:

> 1. Network policies will not be programed for RKE clusters which uses calico/flannel networking.
There will be flag set on the cluster level for "enableNetworkPolicy". Network policies should only be created when the flag is set to true AND canal is selected. We shouldn't be creating network policies for other networking providers that don't support network policies. 

> 2. Network policies will not be programed for clusters other than RKE clusters , like GCE. EKS and AKS.
Correct, no network policies should be programmed for other clusters

> 3. If an imported cluster is RKE and and has canal networking with network policy turned on , will we program Network policies in this case ?

We never manage networking for imported clusters. The concept of a imported cluster is that outside of Rancher, you are managing the k8s components and networking. If you want to take advantage of network policies, you must use either a custom cluster or use a node pool to have Rancher launch and manage k8s on the cluster.

Some upgrade scenarios: 
1. For upgrades, any clusters that have existing network policies (RKE with calico/flannel, GKE/EKS/AKS) will not be cleaned up unless the cluster is changed.  We will not be cleaning up these network policies on solely a Rancher upgrade, but if the cluster is changed, then we should clean them up.
2. For  any cluster that is from a previous release that uses RKE with canal should have the flag enabled by default. All other clusters should have the flag disabled.

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

Covered all test cases in test plan. 

Confirmed that we will not remove existing network policies after upgrade, until cluster is edited.
Confirmed that we will not see Project Network Isolation flag enabled automatically after upgrade, for clusters w/ network set to Canal prior to upgrade.

**Comment by kinarashah** [comment]
I've updated code to reflect that upgraded canal clusters will have the project network isolation flag enabled automatically after upgrade.

**Comment by adingilloRancher** [comment]
v2.0.7-rc3

Upgrade canal cluster behave as expected.

**Comment by christianmue1980a** [comment]
I have a RKE cluster upgraded through earlier versions, now running RKE v0.1.9 and Rancher 2.0.8.
The "np-default" policies are still automatically created.

How can I change this behavior? Simply running "rke up" did not change this behavior.

**Comment by christianmue1980a** [comment]
Adding "enableNetworkPolicy: false" to ne cluster.yaml and running "rke up" again did not change the behavior, "np-default" policies are still being created

**Comment by bmdepesa** [comment]
@christianmue1980a

You mentioned this is an upgraded cluster. Have you edited the cluster after the upgrade? If the policies were present prior to the upgrade, they will not be automatically removed. You must make some change to the cluster for the update to remove the policies.

**Comment by christianmue1980a** [comment]
@bmdepesa , thanks for your answer.
The cluster was initially created with a cluster.yaml which did not contain the "enableNetworkPolicy" flag. It was also upgraded without this flag. 

While I was looking for a solution to get rid of the network policies, I tried to add enableNetworkPolicy=false and run "rke up" again, but without success.

>  You must make some change to the cluster for the update to remove the policies.

What changes do I need to do in order to deactivate the automatic creation of the network policies in future?

**Comment by bmdepesa** [comment]
@christianmue1980a  Can you please post your cluster.yaml w/ any sensitive info removed? I will try to reproduce what you are seeing.

**Comment by sebastiansirch** [comment]
Hi @bmdepesa ,

we are seeing exactly the same issue as described - NodePort services stop working after the network policy is created automatically and we did not find a way yet to get rid of the mechanism which creates the network policies automatically.

Here is our cluster.yaml; I think we started with Rancher 2.0.4 oder 2.0.5... for RKE, I cannot really think of the version we started with... guess it was 0.1.7 or 0.1.8

Thanks for your support!

```
nodes:
  - address: node1
    user: admin
    ssh_key_path: /home/admin/.ssh/id_rsa
    role:
    - worker
    - controlplane
    - etcd
  - address: node2
    user: admin
    ssh_key_path: /home/admin/.ssh/id_rsa
    role:
    - worker
    - controlplane
    - etcd
  - address: node3
    user: admin
    ssh_key_path: /home/admin/.ssh/id_rsa
    role:
    - worker
    - controlplane
    - etcd

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 24h # time increment between snapshots
    retention: 10d # time increment before snapshot purge
  kube-api:
    extra_args:
      v: 4
      feature-gates: "MountPropagation=true"
  kube-controller:
  scheduler:
  kubelet:
    extra_binds:
      - "/dev:/dev"
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
      - "/var/lib/storageos:/var/lib/storageos:rshared"
    extra_args:
      feature-gates: "MountPropagation=true"
      read-only-port: 10255
  kubeproxy:

ingress:
  provider: none

addon_job_timeout: 600
addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: <removed>
    tls.key: <removed>
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: <removed>
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: cluster.domain.de  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - cluster.domain.de      # FQDN to access cattle server
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:stable
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server

```
