### ISSUE TITLE
Edit cluster yaml sometimes removes custom configuration when saving

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14471]
**Rancher versions:**
rancher/rancher:master 7/9

Sometimes when editing cluster yaml through the UI, the previous changes are removed.

I went through the following steps sequentially on the same cluster and saw this behavior, the snippets listed are how the YAML was edited in each step (not the resulting output after saving).

Created custom cluster (DO hosts, 3 nodes, one role per node)

Through UI:
Edit yaml to have extra_env - settings were saved in YAML and the env vars were present.
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
```

Edit yaml to have extra_env & extra_bind - extra_env section is removed from YAML, and extra_bind section was present with the inputted config and mounted properly on the container.
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
    extra_binds:
      - "/root/testvol:/etc/testvol"
```

Edit yaml to have 2 extra_bind args - extra_bind section is completely removed, no binds present in worker node. YAML was back to being defaulted to what is seen when editing a new cluster with no custom config
```
services:
  kubelet:
    extra_binds:
      - "/root/testvol:/etc/testvol"
      - "/root/testvol2:/etc/testvol2"
```

Edit yaml to have 2 extra_env - works, both env vars available on the container
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
      - "TEST=value"
```

Edit yaml to have add another extra_env - extra_env section removed, YAML is again back to default configuration
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
      - "TEST=value"
      - "ANOTHER_VAR=another_value"
```

**Comment by loganhz** [comment]
I can reproduce this issue and I think we should fix it in backend.

1.  Create a custom cluster with the `extra_env` for kubelet in YAML.
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
```

2. Edit the cluster in YAML to add `extra_binds` and remove `extra_env`.

```
services:
  kubelet:
    extra_binds:
      - "/root/testvol:/etc/testvol"
      - "/root/testvol2:/etc/testvol2"
```

3. UI sends the correct payload to backend. You can see the extra_env has been removed in payload and extra_binds has been added.

![image](https://user-images.githubusercontent.com/21168270/42547961-40f6a602-84f7-11e8-9ea4-9a6cc9c40a68.png)

4. But server doesn't remove extra_env fields. Both `extra_env` and `extra_binds` are in the API now. This is wrong as UI doesn't pass the `extra_env` to backend.

![image](https://user-images.githubusercontent.com/21168270/42548046-b0135cec-84f7-11e8-9907-f79949eff927.png)

**Comment by galal-hussein** [comment]
@loganhz i tested with the latest master, i think the main reason these changed not recorded in the API object is that extra env and extra binds are saved as dictionary and not a list, to reproduce:
- edit the cluster yaml and add:
```
services:
  kubelet:
    extra_binds:
      - "/tmp:/tmp"
```
- save the cluster configuration
- edit the cluster yaml again

You will see the extra binds changed from dictionary and not a list:
```
kubelet: 
    extra_binds: 
      0: "/tmp:/tmp"
```

on the second attempt to edit the cluster yaml, it will be something like that:
```
kubelet:
    extra_env:
      - "foo=bar" 
    extra_binds: 
      0: "/tmp:/tmp"
```
on saving the previous configuration the `0: "/tmp:/tmp"` will not get saved properly in the cluster configuration since its not a list.

**Comment by galal-hussein** [comment]
@loganhz @moelsayed RKE is only comparing rke env:
```
func getRKEEnvVars(env []string) []string {
	tmp := []string{}
	for _, e := range env {
		if strings.HasPrefix(e, "RKE_") {
			tmp = append(tmp, e)
		}
	}
	return tmp
}
```

This means that any new env will not trigger an update, i will try to fix to make this much like what Rancher does for worker nodes.

**Comment by janeczku** [comment]
@loganhz Here is another releated issue that should be fixed in the UI.
1. The cluster YAML editor does not render empty dicts resulting in invalid configuration when users were to copy paste the content. It seems to just be a rendering issue as it gets correctly created in the API.

Steps to reproduce:
1. Create cluster -> Cluster Options -> Read from file...
2. Use this file:
```

**Comment by janeczku** [comment]
1. The cluster YAML editor does not render empty dicts resulting in invalid configuration when users were to copy paste the content. 
2. The editor also unwarrantedly transforms camel case key names to snake case. Which does not break functionality but is very confusing since the name does no longer match the documented key name.

Steps to reproduce:
1. Create cluster -> Cluster Options -> Read from file...
2. Use this file content:
```
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      user: some
      password: secret
      datacenters: ha-datacenter
    virtual_center:
      esxi-1.home: {}
    workspace:
      server: somewhere
      folder: dummy
      default-datastore: ds1
      datacenter: ha-datacenter
```
Note the empty dict `esxi-1.home.meta.cx: {}` which is valid yaml and removing it renders the cloud config configuration block defunct.

3. Click Edit As YAML
4. Note that the content has been transformed such as the top-level dictionary `virtual_center`and its child  have been removed and the name of the `vsphereCloudProvider` key has been changed to `vsphere_cloud_provider`.

![screen shot 2018-07-25 at 18 02 35](https://user-images.githubusercontent.com/3813921/43212727-12e0a4e0-9035-11e8-824c-62933ba89a4b.png)

**Comment by bmdepesa** [comment]
rancher/rancher:master 8/6

I see new env/binds getting added correctly, but when updated to remove a section, that section is not removed. 

For example, first edit YAML with:
```
services:
  kubelet:
    extra_env:
      - "FOO=bar"
    extra_binds:
      - "/root/testvol:/etc/testvol"
```

Then edit with:
```
services:
  kubelet:
    extra_binds:
      - "/root/testvol:/etc/testvol"
      - "/root/testvol2:/etc/testvol2"
```

After save, user is presented with:
```
services:
  kubelet: 
    extra_binds: 
      - "/root/testvol:/etc/testvol"
      - "/root/testvol2:/etc/testvol2"
    extra_env: 
      - "FOO=bar"
```

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/43813470-6ef679ee-9af8-11e8-9deb-f0193e357160.png)

I think UI sends the correct payload to backend. We need to fix it in backend.

**Comment by StrongMonkey** [comment]
By default we use strategic-merge-patch to update all resources. This means that if we want to remove a key, we have to specifically set it to empty. 
For example: 
```
services:
  kubelet: 
    extra_binds: 
      - "/root/testvol:/etc/testvol"
      - "/root/testvol2:/etc/testvol2"
    extra_env: {}
```
The solution is to send the payload like this or change the strategic we use for update.
