### ISSUE TITLE
Kubelet container is removed from worker node when duplicate binds are added to cluster config yaml

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#14470]
**Rancher versions:**
rancher/rancher:master 7/9

**Steps to Reproduce:**
Create a custom cluster, 3 nodes, one of each role
Edit cluster yaml to include a duplicate bind:

```
services:
  kubelet:
    extra_binds:
      - "/host/dev:/dev/"
      - "/host/dev:/dev/"
```

Save the cluster config, it should be successful. 

After ~2 minutes, the `kubelet` container is removed from worker node and is not restarted (ssh into worker node and check `docker ps | grep kubelet` periodically after saving config).
