### ISSUE TITLE
Rancher2 deployements using kubectl can't use L4 LoadBalancer from Rancher UI

### ISSUE THREAD

**Issue by Treenity** [rancher/rancher#14513]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6

**Infrastructure Stack versions:**
kubernetes: 1.10.5

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1062-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher on EC2, AWS Cluster 3 nodes (1etcd, 1 controler, 1 worker)
Rancher, controler and worker are in a public VPC, etcd in private VPC.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Create a AWS Cluster with Amazon Cloud provider setting in Rancher Cluster
Use kubectl to provision a deployement
Edit deployement in rancher to use L4 LoadBalancer
ports 80
type L4 Load balancer
Listen 80

**Results:**
Nothing ;o)
No service created, so no AWS ELB created, UI dont show any opened ports under deployement name.

**Expected Result:**
Exposing my deployement to AWS ELB

**Details:**
I've created a simple deployement to test it : 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-from-kubectl
  name: nginx-from-kubectl
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: nginx-from-kubectl
    spec:
      containers:
        - image: nginx
          name: nginx-from-kubectl
```
then use
`kubectl create -f test.yaml`
Deployement is created, then i edit the deployement in rancher to set the ports to be exposed through a L4 LoadBalancer Type. Deployement is updated, but no service is created.
If i use kubectl expose, kubernetes created the service, and the AWS ELB is created without any problem.
