### ISSUE TITLE
OpenStack Provider lbaas monitor parameter type error

### ISSUE THREAD

**Issue by dommgifer** [rancher/rancher#14577]
**Rancher versions:**
rancher/rancher: v2.0.6

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node ranche
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. create cluster
2. use OpenStack provider
3. Edit yaml add "cloudProvider"
cloud_provider: 
  name: "openstack"
  openstack_cloud_provider: 
    block_storage: 
      bs-version: "v2"
      ignore-volume-az: false
      trust-device-path: false
    global: 
      auth-url: "http://XXXXXX:5001/v3"
      domain-name: "default"
      password: "XXXXX!"
      tenant-id: "885c63821c3a43a78da157958eca3a99"
      username: "XXXXX"
    load_balancer: 
      create-monitor: true
      floating-network-id: "d0456ee8-c9a9-4e0c-8be1-0974f1d13ac0"
      lb-method: "ROUND_ROBIN"
      lb-provider: "haproxy"
      manage-security-groups: false
      monitor-delay: 60
      monitor-max-retries: 3
      monitor-timeout: 30
      subnet-id: "12c1529a-2f54-43be-8f04-f766369c2b1d"
      use-octavia: false
4. add nodepool and save to create cluster

**Results:**
The cluster return Error message:
`[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host`

I login to master and check kubelet log, got error message:
`failed to run Kubelet: could not init cloud provider "openstack": time: missing unit in duration 60`

And then, modified section [LoadBalancer] in /etc/kubernetes/cloud_config,
Changed "monitor-delay=60" to "monitor-delay=1m" and "monitor-timeout=30" to "monitor-timeout=30s".

Save file , kubelet was successfully running.

I found the Rancher doc about OpenStack cloud provider : 
https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/#load-balancer

The configuration options of type:

- monitor-delay  : int

- monitor-timeout : int

Kubernetes offical doc of OpenStack cloud provider:
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#openstack

The  configuration options of "monitor-delay" and "monitor-timeout" without specific type, only 
describe "second".

So,  in view of above mentioned problem, I think parameter "monitor-delay" and "monitor-timeout" type were "string" not "int".

**Comment by stieler-it** [comment]
Even worse: The OpenStack Kubernetes cloud provider seems to add **all** nodes to the pool, including master nodes tagged as Unschedulable. Configuring monitors would be a workaround to take those nodes out of service. However I also wasn't able to save a working cloud config with monitor.

**Comment by leafty** [comment]
:+1: Do not validate monitor delays an `Int` as the doc falsely says the time is in seconds.
The duration are parsed with the `time` go package, see: https://github.com/kubernetes/cloud-provider-openstack/blob/1.12.0/pkg/cloudprovider/providers/openstack/openstack.go#L109-L110

Editing manually `/etc/kubernetes/cloud-config` to add `s` lets `kubelet` start but is not a viable solution.

**Comment by alexandrem** [comment]
Can I know in what Rancher release this will land?

This prevents to have proper LB backend member health checks.

**Comment by stieler-it** [comment]
[Kubernetes documentation](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancer) is now pretty clear about these properties: Units are mandatory.
However, Rancher's validation only accepts integer values which will prevent kubelet from running.

This is accepted by Rancher, does not work with kubelet:
```
    load_balancer: 
      create-monitor: true
      monitor-delay: 5
      monitor-max-retries: 3
      monitor-timeout: 5
```

This should be a correct example but is not accepted by Rancher:
```
    load_balancer: 
      create-monitor: true
      monitor-delay: "5s"
      monitor-max-retries: 3
      monitor-timeout: "5s"
```

**Comment by wowsel** [comment]
Dear developers, is there any news?

**Comment by mjpitz** [comment]
Interesting. All of these corresponding classes are generated from something, which is suggesting the int instead of a string with units.

https://github.com/rancher/types/blob/6c35a3b3e51fa5014a5f788e41b773d2469980e4/client/management/v3/zz_generated_openstack_cloud_provider.go

It's not clear where that file is being generated from. Maybe someone from the team can offer some direction on how to go about getting the types repo updated with the proper data types?

**Comment by rawmind0** [comment]
https://github.com/terraform-providers/terraform-provider-rancher2/pull/21

**Comment by soumyalj** [comment]
Tested with master from June 11. 
Create openstack node driver cluster
Edit the yaml and provide cloudprovider section as below:
```
cloud_provider:
  name: "openstack"
  openstack_cloud_provider:
     load_balancer:
        create-monitor: true
        floating-network-id: "123"
        lb-method: "ROUND_ROBIN"
        lb-provider: "haproxy"
        manage-security-groups: false
        monitor-delay: 60s
        monitor-max-retries: 3
        monitor-timeout: 30s
        subnet-id: "34556"
        use-octavia: false
```
monitor-delay and monitor-timeout have seconds and units 
Values get stored in as string in cluster Api as expected:
```
"cloudProvider": {

    "name": "openstack",
    "openstackCloudProvider": {
        "loadBalancer": {
            "create-monitor": true,
            "floating-network-id": "123",
            "lb-method": "ROUND_ROBIN",
            "lb-provider": "haproxy",
            "manage-security-groups": false,
            "monitor-delay": "60s",
            "monitor-max-retries": 3,
            "monitor-timeout": "30s",
            "subnet-id": "34556",
            "type": "/v3/schemas/loadBalancerOpenstackOpts",
            "use-octavia": false
        },
        "type": "/v3/schemas/openstackCloudProvider"
    },
    "type": "/v3/schemas/cloudProvider"
},
```
The schema shows that type is string : https://a.b.c.d/v3/schemas/loadBalancerOpenstackOpts

```
"monitor-delay": {

    "create": true,
    "nullable": true,
    "type": "string",
    "update": true

},
"monitor-timeout": {

    "create": true,
    "nullable": true,
    "type": "string",
    "update": true

},

```
