### ISSUE TITLE
Ingress with SSL certificate gives Kubernetes Ingress Controller Fake Certificate Organisation

### ISSUE THREAD

**Issue by AmitDJagtap** [rancher/rancher#14580]
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
network-services: Canal
Kubernetes Version : v 1.10.1-rancher1

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Cloud VM ( biznet )

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Step 1: Installed certmanger using catalog app in Rancher2.0
Step 2: Added issuer via kubectl command line

```
kubectl create -f - <<END
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: lending-300
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sample@mail.com
    privateKeySecretRef:
      name: letsencrypt
    dns01: 
       providers:
        - name: route53-dns
          route53:
             accessKeyID: xxxxxx
             secretAccessKeySecretRef:
                name: aws-dns
                key: api-key
             region: us-east-1
END
```

Step 3: Added certificate via  kubectl command line

```
kubectl create -f - <<END
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-id
  namespace: lending-300
spec:
  secretName: example-id-tls
  issuerRef:
    name: letsencrypt
  commonName: example.id
  acme:
    config:
    - dns01:
        provider : route53-dns
      domains:
        - example.id
END
```

Step 4: Certificate gets created successfully

![rancher 1](https://user-images.githubusercontent.com/9251806/42812306-df4cb82c-89da-11e8-8cf9-8859e1d18749.png)

```
> kubectl -n lending-300 describe certificate example-id
Name:         example-id
Namespace:    ns-300
Labels:       <none>
Annotations:  <none>
API Version:  certmanager.k8s.io/v1alpha1
Kind:         Certificate
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-07-17T09:47:55Z
  Generation:          1
  Resource Version:    792347
  Self Link:           /apis/certmanager.k8s.io/v1alpha1/namespaces/lending-300/certificates/example-id
  UID:                 7b37de9b-89a6-11e8-8419-02005af20004
Spec:
  Acme:
    Config:
      Dns 01:
        Provider:  route53-dns
      Domains:
        example.id
  Common Name:  example.id
  Dns Names:    <nil>
  Issuer Ref:
    Name:       letsencrypt
  Secret Name:  example-id-tls
Status:
  Acme:
    Order:
      URL:  https://acme-v02.api.letsencrypt.org/acme/order/38468058/18059394
  Conditions:
    Last Transition Time:  2018-07-17T09:51:05Z
    Message:               Certificate issued successfully
    Reason:                CertIssued
    Status:                True
    Type:                  Ready
    Last Transition Time:  <nil>
    Message:               Order validated
    Reason:                OrderValidated
    Status:                False
    Type:                  ValidateFailed
Events:
  Type    Reason          Age   From          Message
  ----    ------          ----  ----          -------
  Normal  CreateOrder     33m   cert-manager  Created new ACME order, attempting validation...
  Normal  DomainVerified  31m   cert-manager  Domain "example.id" verified with "dns-01" validation
  Normal  IssueCert       30m   cert-manager  Issuing certificate...
  Normal  CertObtained    30m   cert-manager  Obtained the certificate from ACME server
  Normal  CertIssued      30m   cert-manager  Certificate issued successfully

```
Step 5: Add certificate to ingress
```
  > kubectl -n mynamespace describe ingress myapp
Name:             myapp
Namespace:        mynamespace
Address:          172.16.0.100
Default backend:  myappwebsite:8686 (10.42.0.168:8686)
TLS:
  example-id-tls terminates exmaple.id
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     myappwebsite:8686 (10.42.0.168:8686)
Annotations:
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  CREATE  36m                nginx-ingress-controller  Ingress mynamespace/myapp
  Normal  UPDATE  34m (x2 over 35m)  nginx-ingress-controller  Ingress mynamespace/myapp
```
**Results:**
I still get the default kubernetes SSL certificate.

![desktop screenshot 1](https://user-images.githubusercontent.com/9251806/42812433-400399c4-89db-11e8-8770-b458dea1f1f4.png)

**Comment by quangnhut123** [comment]
Me too not work with ingress dont know why !

**Comment by AmitDJagtap** [comment]
I ended up using this **valian/docker-nginx-auto-ssl**.  Created a deployment for this image and pointed my domain A rec to this pods IP  More info about configuring on docker hub page for  **valian/docker-nginx-auto-ssl**.

**Comment by pmcanseco** [comment]
I am having the same issue. I even added 
```
ingress: 
  provider: "nginx"
  extra_args:
    enable-ssl-passthrough: ""
```
to my cluster yaml, as well as the annotation `nginx.ingress.kubernetes.io/ssl-passthrough=true` in my ingress. Despite that, I get the same symptom OP shows.
