### ISSUE TITLE
kube-controller-manager is not setup correctly - No Certificate Signer

### ISSUE THREAD

**Issue by cgebe** [rancher/rancher#14674]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.6

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03.02

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node ACME Installation

**Steps to Reproduce:**
1. Setup a new cluster
2. Create a [CertificateSigningRequest](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request)
3. Inspect the CSR

**Results:**
When approving the CSR no certificate is issued, because the certificate signer is not setup with a CA during the initial creation of the cluster. 

https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators
https://kubernetes.io/cn/docs/admin/kubelet-tls-bootstrapping/#kube-controller-manager-configuration

**Comment by kamushadenes** [comment]
Can confirm.

I tried adding 

```
 kube-controller:
   extra_args:
     cluster-signing-cert-file: /etc/kubernetes/ca.crt
     cluster-signing-key-file: /etc/kubernetes/ca.key
```

But it didn't work.

**Comment by deniseschannon** [comment]
In Rancher 2.2 and RKE 0.2.0, we've only added the ability to bring your own certs to clusters created with the RKE CLI.

https://rancher.com/docs/rke/latest/en/installation/certs/#generating-certificate-signing-requests-csrs-and-keys

This is not available directly through the Rancher UI.

**Comment by gehring** [comment]
@deniseschannon Is it possible to have RKE set up the kube controller manager with a signing cert and key when generating the initial certificates in order to allow the cluster to issue certificates without having to setup our own custom certificates? I'm not all that familiar with how CSRs and CAs are handled so hopefully my question isn't silly!

**Comment by dnoland1** [comment]
Got this working using:
```yaml
    kube-controller:
      extra_args:
        cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
        cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
```
This is required for setting up Windows GMSA if you want to use the webhook install script referenced here - https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/#install-webhooks-to-validate-gmsa-users
