### ISSUE TITLE
LoadBalancer information is not shown in UI when Cloud Provider is enabled

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#14680]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6

Steps to repro:
- Create a node template with IAM profile prerequisites to use Cloud Provider (AWS)
- Create an AWS cluster with Cloud Provider enabled
- Create the following Workload and Service/LB

```
apiVersion: v1
kind: Service
metadata:
  name: test-leo-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: test-leo
---
apiVersion: v1
kind: Pod
metadata:
  name: test-leo
  labels:
    name: test-leo
spec:
  containers:
    - name: test-leo
      image: leodotcloud/swiss-army-knife
      ports:
        - containerPort: 80
```

Wait for few min for the load balancer to be created.

```
> kubectl get svc test-leo-lb -o wide
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP                                                              PORT(S)        AGE       SELECTOR
test-leo-lb   LoadBalancer   10.43.154.211   example1e8b2c812c05e407a9-405633674.us-east-1.elb.amazonaws.com   80:30675/TCP   33m       name=test-leo
>
```

This above Load Balancer information is not available anywhere in the UI:

<img width="1302" alt="screen shot 2018-07-21 at 11 27 45 pm" src="https://user-images.githubusercontent.com/19392926/43042967-d3b405ae-8d3d-11e8-9119-1d3f29679255.png">
<img width="1298" alt="screen shot 2018-07-21 at 11 27 53 pm" src="https://user-images.githubusercontent.com/19392926/43042968-d3ca5548-8d3d-11e8-971d-fcc2086f0921.png">
<img width="1298" alt="screen shot 2018-07-21 at 11 28 01 pm" src="https://user-images.githubusercontent.com/19392926/43042969-d3dffbf0-8d3d-11e8-9350-4e54ce811b06.png">

Expected:
It would be nice to see the LB information in the UI instead of going through `kubectl`
