### ISSUE TITLE
Scaling up a workload with 2 env vars creates new pods as part of scale up on a fresh install

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#14713]
**Rancher versions:**
rancher/rancher: v2.0.5 ， v2.0.6
rancher/rancher-agent: v2.0.5， v2.0.6

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS 4.4.0-116-generic #140-Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware virtual machine

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
1. Create a workload，Configuring multiple environment variables (More than 1);
2. Scale up the workload ;

**Results:**
In the case of configuring multiple environment variables, the old pod reconstruction will occur in the scaling workload.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/20707603/43116764-ec7bb00a-8f3b-11e8-8276-9dfe97dc57cf.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/20707603/43116873-7bed2750-8f3c-11e8-8316-6891332df435.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/20707603/43116929-c0ab9d9a-8f3c-11e8-98e7-dbc7c988aa4a.png">

**Comment by xiaoluhong** [comment]
@superseb

**Comment by wanshaoyuan** [comment]
@alena1108 Is there a good solution?

**Comment by StrongMonkey** [comment]
@soumyalj try to create a workload with 4 or more environment variables set. That should reproduce it easily.

**Comment by soumyalj** [comment]
Reproduced the issue with v2.0.6
Tested with master build from August 6th.
Created a workload with two or more environment variables.
Incremented the scale and old pods were not created as part of the scale up
<img width="1532" alt="screen shot 2018-08-06 at 4 46 12 pm" src="https://user-images.githubusercontent.com/18536626/43746373-c96f1b94-9998-11e8-88ea-ffe20634a8bc.png">
The env variables are sorted in alphabetical order when the workload  yml is observed
```
  spec:
      affinity: {}
      containers:
      - env:
        - name: key
          value: value
        - name: key1
          value: valu2
        - name: test
          value: value
        - name: test5
          value: myvalue5
        - name: test6
          value: myvalue6


```
