### ISSUE TITLE
Add UDP and TCP support to Rancher ingress

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#14744]
Allow for exposing of UCP and TCP services via the Rancher ingress controller

<a>https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md</a>

Nginx support this so we should give the user options to select tcp and udp and associate them with a config map.

**Comment by guangbochen** [comment]
the latest version of rancher v2.0.8 now supports TCP and UDP service through configmap.
![image](https://user-images.githubusercontent.com/4569037/44834847-ded4df80-ac64-11e8-80aa-b2872e23814b.png)

@loganhz @vincent99 wondering if we need to add them in the UI configuration of ingress.

**Comment by vincent99** [comment]
Not without capabilities/a way to know that it's the nginx ingress that's enabled.

**Comment by chrisurwin** [comment]
@vincent99 can we not get that from the cluster config as we have a radio button to state is nginx ingress is enabled or not?

**Comment by vincent99** [comment]
Not arguing against the feature, but you need to show it based in the correct info.

That's a rke config field, which doesn't exist on imported or kontainer-engine clusters.

**Comment by dusterio** [comment]
@guangbochen can we have an example of the configmap please?

**Comment by imwower** [comment]
> the ingress-nginx has an example for that https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md.

but the UDP services do not work, as the TCP ones work well,

I create a configMap used TCP rules, and it works well, here is an example:
  create a yaml file, named nginx.yaml, then execute:
  `kubectl apply -f nginx.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  88: "base/nginx:80"
```

but when use UDP rules, it does not work, here is UDP example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  27017: "base/mongo:27017"
```

I can't access mongo service via <host_ip>:27017, but can access nginx <host_ip>:88

**Comment by jmwilkinson** [comment]
@imwower Did you do anything different for mongo? I cannot seem to get that one to work.

**Comment by superseb** [comment]
This is going to be removed from NGINX ingress as seen here https://github.com/kubernetes/ingress-nginx/pull/3197

**Comment by jmwilkinson** [comment]
@superseb Oh no.

**Comment by imwower** [comment]
the ingress-nginx is used for back-end load balance, so we should not use it to expose tcp/udp port;
and the front-end load balance should be another project, or another service

**Comment by vincent99** [comment]
I think we can safely close this, there's no point in implementing it with this being removed from upstream soon.

**Comment by alvistar** [comment]
Hi, just want to point that they are not going to remove this feature anymore.

https://github.com/kubernetes/ingress-nginx/pull/3197

**Comment by tegk** [comment]
Should be integrated into the UI for sure :-)

**Comment by davidwindell** [comment]
Agreed, @vincent99 can you re-open this?

**Comment by vincent99** [comment]
We have no plans of implementing a special UI for this.  It is a niche use case for a non-standard behavior supported by one out of the many ingress controllers available.

Other than autocompleting the service names, it would probably look pretty much like the ConfigMap editor that you can use today.

**Comment by davidwindell** [comment]
Understood, in our case we were looking for an easy way to allow users to expose SSH in their pods (for unison sync, can't be done with kubectl).

**Comment by jmwilkinson** [comment]
It looks like newly deployed Rancher clusters will no longer support tcp/udp services via nginx ingress, as the config map is not generated, and the immutable property `hostNetwork` is now false, so even if the config maps were added nginx cannot actually route traffic.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/17836030/142248373-e94c00b1-dc91-49b6-b6a8-81a44f2f3b32.png">

An official alternative would be nice.

**Comment by d3473r** [comment]
Any news on this issue?
I've just update our rancher cluster and now a rabbitmq deployment is not reachable as a tcp-service anymore :(

**Comment by tacerus** [comment]
Any news on this? Is there an official way to expose generic TCP and UDP services using Rancher?

**Comment by mxm-tr** [comment]
I've been able to make it work using the following steps. In this example a gitlab ssh service is exposed on port 2222.

1. Edit the tcp-services ConfigMap to configure the ingress controller:

```
kubectl -n ingress-nginx edit cm tcp-services
```

Example to expose the `mygitlab-gitlab-shell` Service in the `gitlab` namespace
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-configmap-example
data:
  2222: "gitlab/mygitlab-gitlab-shell:2222"
```

2. Edit the ingress controller DaemonSet configuration to expose the requested port:
```
kubectl -n ingress-nginx edit daemonsets.apps nginx-ingress-controller
```
Add the requested port in the `spec.containers[0].ports` section. For this example:

```yaml
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 2222
          hostPort: 2222
          name: ssh-gitlab
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 8443
          name: webhook
          protocol: TCP

```

3. Edit the ingress controller's Service to forward traffic to the containers:

```
kubectl -n ingress-nginx edit service ingress-nginx-controller-admission
```

For this example, the `spec.ports` section looks like this:

```
  ports:
  - appProtocol: ssh
    name: ssh-gitlab
    port: 2222
    protocol: TCP
    targetPort: ssh-gitlab
  - appProtocol: https
    name: https-webhook
    port: 443
    protocol: TCP
    targetPort: webhook

```
