### ISSUE TITLE
Add pod affinity/anti-affinity 

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#14752]

**Comment by cjellick** [comment]
@StrongMonkey I need more details!

**Comment by cjellick** [comment]
@aemneina need more details

**Comment by StrongMonkey** [comment]
@cjellick this is adding corresponding rancher api to map pod affinity/anti-affinity

**Comment by watermeion** [comment]
+1

**Comment by ItsReddi** [comment]
Took me ages to find out that this is not supported via UI right now until i found that issue.
Since: https://rancher.com/docs/rancher/v2.x/en/v1.6-migration/schedule-workloads/#label-affinity-antiaffinity
does not mention that this is not possible anymore and we understood that pod affinity / antiaffinity is supported like in 1.x

**Comment by admun** [comment]
how pod affinity/antiaffinity using label works now?

I've trying to do it by no luck so far.

**Comment by admun** [comment]
I used the rancher UI to add anti affinity rules, but pods still schedule on the same node

```
...
...
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-05-22T03:46:45Z"
        field.cattle.io/ports: '[[{"containerPort":31416,"dnsName":"boinc-client","hostPort":0,"kind":"ClusterIP","name":"tcp31416","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app: boinc-client
        workload.user.cattle.io/workloadselector: statefulSet-boinc-boinc-client
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: NotIn
                values:
                - boinc-client
...
...
```
