### ISSUE TITLE
UI cluster yaml editor truncates empty dicts and modifies key names

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#14750]
**Rancher versions:**
v2.0.6

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere node driver

The cluster YAML editor does not render empty dicts resulting in invalid configuration when users were to copy paste the content. 
The editor also unwarrantedly transforms camel case key names to snake case. Which does not break functionality but is very confusing to users since the name does no longer match the documented key name.

**Steps to Reproduce:**
1. Create cluster (vSphere) -> Cluster Options -> Read from file...
2. Use this file content:
```
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      user: some
      password: secret
      datacenters: ha-datacenter
    virtual_center:
      esxi-1.home: {}
    workspace:
      server: somewhere
      folder: dummy
      default-datastore: ds1
      datacenter: ha-datacenter
```
Note the empty dict `esxi-1.home: {}` which is valid yaml and this entry is required by the cloud provider.

3. Click Edit As YAML
4. Note that the content has been changed such as the top-level dictionary `virtual_center`and its child  have been removed and the name of the `vsphereCloudProvider` key has been changed to `vsphere_cloud_provider`.

This appears to be a UI rendering issue, as the cluster is created in API with the correct config.

![screen shot 2018-07-25 at 18 02 35](https://user-images.githubusercontent.com/3813921/43212727-12e0a4e0-9035-11e8-824c-62933ba89a4b.png)
