### ISSUE TITLE
volume hostpath with subpath 

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#14836]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

**Infrastructure Stack versions:**
kubernetes (if applicable):  v.1.10.5

Create a volume in a pod
![image](https://user-images.githubusercontent.com/15118220/43363726-59aeb490-934e-11e8-97ac-30a3986b5cda.png)

According to document, https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath

a Pod uses subPath to create a directory pod1 within the hostPath volume /var/log/pods, using the pod name from the Downward API. The host directory /var/log/pods/pod1 is mounted at /logs in the container.

Expecting directory /iag/unix create in node host and mount to pod as /unix

But got 
![image](https://user-images.githubusercontent.com/15118220/43363738-adbe174c-934e-11e8-8a1f-79b79afeb19b.png)

view yaml
![image](https://user-images.githubusercontent.com/15118220/43363772-88a542ae-934f-11e8-94e2-04c6d8ad10c1.png)

Not sure what I missed. No directory created in node host.

**Comment by loganhz** [comment]
It's a known k8s issue. It will work if you leave subpath empty 
Please check https://github.com/kubernetes/kubernetes/issues/61456

**Comment by janeczku** [comment]
This is still an issue with Rancher installed K8s 1.11 and 1.12.
The issue for hostPath+subPath with containerized Kubelet has been fixed upstream since v1.11: https://github.com/kubernetes/kubernetes/pull/63143 first shipped in K8s v1.11.0.

It looks like there is some work todo on RKE side (like mounting the host rootfs to kubelet /rootfs mountpoint).

**Comment by janeczku** [comment]
Steps to reproduce:

1. Create a cluster in Rancher using K8s v1.12.x
2. Deploy a workload that mounts a hostPath volume using a subPath (see manifest below)
3. Exec to the pod and create a new file under the mount point (e.g. `uniquefile`)
4. SSH to the host where the Pod is running.
5. Verify that the file was created under the expected hostPath/subPath in the rootfs

Result:
```
worker1:/# stat /site-data/nginx
stat: cannot stat '/site-data/nginx': No such file or directory
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /volume/nginx
          name: site-data
          subPath: nginx
      volumes:
      - name: site-data
        hostPath:
          path: /site-data
          type: DirectoryOrCreate
```

**Comment by JorinL** [comment]
Ran into that problem today and can also reproduce it with mosquitto and a sub path in the claimed volume.  Using v1.13.4-rancher1-1 and rancher-agent:v2.1.7

**Comment by loganhz** [comment]
Added into 2.3

https://github.com/kubernetes/kubernetes/pull/63143#issuecomment-401887153

**Comment by gitlawr** [comment]
Here's the workaround:
1. Edit cluster, Edit as YAML
2. Add the following flags for kubelet:
```
services:
  kubelet:
    extra_args:
      containerized: "true"
    extra_binds: 
      - "/:/rootfs:rshared"
```
3. Click save and wait till the cluster is updated.

Notes:
The community is planning to deprecate the "--containerized" for kubelet(https://github.com/kubernetes/kubernetes/issues/74148).
But the flag is essential for the capability as there is no alternative at the moment.

**Comment by mrtndwrd** [comment]
@gitlawr does that mean you're mount-binding the whole root system of your Kubernetes host to the kubelet container? That can't be good for security, right?

**Comment by cjellick** [comment]
Looks like an rke fix?

**Comment by cjellick** [comment]
I realize @galal-hussein is out this week, but assigning to him at least temporarily

**Comment by varac** [comment]
From https://github.com/rancher/rancher/issues/14836#issuecomment-491152114: 

> The community is planning to deprecate the "--containerized" for kubelet(kubernetes/kubernetes#74148).

This already got merged, so a containerized kubelet *is* already deprecated.

> But the flag is essential for the capability as there is no alternative at the moment.

What's the plan for rancher/rke regarding hyperkube ? When does the containerized kubelet gets replaced ? This issue is really annoying because a lot of upstream charts break on a hostpath provider due to their use of `subpath`.

**Comment by Leen15** [comment]
Any news here?

**Comment by varac** [comment]
I created a [feature request to deprecate the containerized kubelet](#22882).   
Meanwhile I have two questions, maybe somebody from rancher could comment on:

- What's the recommended workaround for this issue ? Is it bind-mounting the whole host rootdir into the kubelet container like suggested by @gitlawr  in [above comment](https://github.com/rancher/rancher/issues/14836#issuecomment-491152114) ?
- If so, are there any security implications with this, or anything that could reduce potential risks ?

**Comment by varac** [comment]
> Is it bind-mounting the whole host rootdir into the kubelet container like suggested by @gitlawr in above comment ?

To be more precise, which host directories need to get additionally bind-mounted into the pod in order to make `subpath` work ?

**Comment by bruno-lopes** [comment]
Any news on this??? The ability to mount an specific file is very important to us.

**Comment by sriraj7** [comment]
any update on this , i have created a pv before i claim it using the volume claim template in values.yaml file for prometheus helm chart. 
1) my goal is to take the tsdb snapshot and store the snapshot in host path 
2) i am ablet create the snapshot, bound the pv but prometheus server pod is breaking with crate config error with error stating /data/prometheus: no such file or directory.

if i could attach the pv. i will use the snapshot path not to loose the metrics during upgrade

could some one help me with a work around to achieve my goals

**Comment by BarthV** [comment]
Workaround provided by @gitlawr is not working anymore on kube 1.17.4 since https://github.com/kubernetes/kubernetes/issues/74148 .

Now I'm seeing this message :
```
FATA[0339] [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [cpu3.store.local]
[server.go:156] unknown flag: --containerized
```

I'm afraid it will not be anymore enough to fix this.
AFAIK, the only other way to fix it is to apply some kubectl patch as told in https://github.com/rancher/local-path-provisioner/issues/4#issuecomment-578620842

Please make something fast :'(

**Comment by ryansann** [comment]
I've done some further investigation on this issue and will summarize my findings below.

## Problem

When using a hostPath volume with a subPath, the containerized kubelet is not able to create a mount back to the host filesystem.

## Validate hostPath volume

In a cluster running a containerized kubelet you can perform the following steps to check that hostPath volumes work.

Create a deployment with a `hostPath` volume that has no `subPath`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /volume/nginx
          name: site-data
      volumes:
      - name: site-data
        hostPath:
          path: /site-data
          type: DirectoryOrCreate
```

SSH into the worker node where the pod was scheduled and inspect the corresponding docker container to see bind mounts:
```json
{
    "HostConfig": {
        "Binds": [
            "/site-data:/volume/nginx"
        ]
    }
}
```
This looks good and the `/site-data` directory is created on the host

## Reproduce subPath issue with hostPath volume

Create a deployment with a `hostPath` volume that has a `subPath`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /volume/nginx
          name: site-data
          subPath: nginx
      volumes:
      - name: site-data
        hostPath:
          path: /site-data
          type: DirectoryOrCreate
```

SSH into the worker node where the pod was scheduled and inspect the corresponding docker container to see bind mounts:
```json
{
    "HostConfig": {
        "Binds": [
            "/var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0:/volume/nginx"
        ]
    }
}
```

Check the mounts on the host with `findmnt /var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0` this will return:
```
TARGET                                                                                       SOURCE                 FSTYPE OPTIONS
/var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0 none[/site-data/nginx] aufs   rw,relatime,si=2fb3ccf5b8b9c475,dio,dirperm1
```

From this we can see the `SOURCE` has the correct `<hostPath>/<subPath>` but if we check the node for this path with: `stat /site-data/nginx` we get `no such file or direcotry`. So what's happening? If we exec into the kubelet we can get more information. Do the following:

1. `docker exec -it $(docker ps -aq --filter "name=kubelet") /bin/sh`
2. Once inside the kubelet, run: `stat /site-data/nginx`

We can see from the output that `/site-data/nginx` actually does exist in the kubelet, however, since the kubelet is containerized and does not share a filesystem with the node, `/site-data/nginx` does not exist on the node, where it should. 

This gives us more information on the previous `findmnt` output. It tells us that a filesystem that lives in the kubelet at `/site-data/nginx` is being mounted to `/var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0` on the kubernetes node. It is able to be mounted to this path on the node because there is a bind mount from the node's `/var/run/kubelet` directory to the container's `/var/run/kubelet` directory, as can be seen from the kubelet container's binds:
```
{
    "HostConfig": {
        "Binds": [
            ...
            "/var/lib/kubelet:/var/lib/kubelet:shared,z",
            ...
        ]
}
```

This is not the desired functionality as there no presence of `/<hostPath>/<subPath>` on the host, only in the containerized kubelet.

If we wanted to confirm the above we could take some manual steps to make this work, i.e. get `/site-data/nginx` to be populated on the host. Here's what we can do:

1. Create the target directory on the host with: `mkdir -p /site-data/nginx`
2. Create a bindmount with: `mount --bind /var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0 /site-data/nginx`

With these steps taken, we have the following:
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtcIi92b2x1bWUvbmdpbnhcIl1cbiAgQltcIi9zaXRlLWRhdGEvbmdpbnhcIl1cbiAgQ1tcIi92YXIvbGliL2t1YmVsZXQvcG9kcy9kMGI3OWE0MC02YTY5LTQ3ZDktYTdlNC1lZjM2MzMxNzMyZTIvdm9sdW1lLXN1YnBhdGhzL3NpdGUtZGF0YS9uZ2lueC8wXCJdXG4gIERbXCIvdmFyL2xpYi9rdWJlbGV0L3BvZHMvZDBiNzlhNDAtNmE2OS00N2Q5LWE3ZTQtZWYzNjMzMTczMmUyL3ZvbHVtZS1zdWJwYXRocy9zaXRlLWRhdGEvbmdpbngvMFwiXVxuICBFW1wiL3NpdGUtZGF0YS9uZ2lueFwiXVxuXG4gIHN1YmdyYXBoIEt1YmVsZXRcbiAgICBCIC0tPnxtb3VudHwgQ1xuICBlbmRcbiAgc3ViZ3JhcGggTmdpbnggUG9kXG4gICAgQSAtLT58ZG9ja2VyIHZvbHVtZXwgQlxuICBlbmRcbiAgc3ViZ3JhcGggS3ViZXJuZXRzIE5vZGVcbiAgICBDIC0tPnxkb2NrZXIgdm9sdW1lfCBEXG4gICAgRCAtLT58bW91bnQqfCBFXG4gIGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtcIi92b2x1bWUvbmdpbnhcIl1cbiAgQltcIi9zaXRlLWRhdGEvbmdpbnhcIl1cbiAgQ1tcIi92YXIvbGliL2t1YmVsZXQvcG9kcy9kMGI3OWE0MC02YTY5LTQ3ZDktYTdlNC1lZjM2MzMxNzMyZTIvdm9sdW1lLXN1YnBhdGhzL3NpdGUtZGF0YS9uZ2lueC8wXCJdXG4gIERbXCIvdmFyL2xpYi9rdWJlbGV0L3BvZHMvZDBiNzlhNDAtNmE2OS00N2Q5LWE3ZTQtZWYzNjMzMTczMmUyL3ZvbHVtZS1zdWJwYXRocy9zaXRlLWRhdGEvbmdpbngvMFwiXVxuICBFW1wiL3NpdGUtZGF0YS9uZ2lueFwiXVxuXG4gIHN1YmdyYXBoIEt1YmVsZXRcbiAgICBCIC0tPnxtb3VudHwgQ1xuICBlbmRcbiAgc3ViZ3JhcGggTmdpbnggUG9kXG4gICAgQSAtLT58ZG9ja2VyIHZvbHVtZXwgQlxuICBlbmRcbiAgc3ViZ3JhcGggS3ViZXJuZXRzIE5vZGVcbiAgICBDIC0tPnxkb2NrZXIgdm9sdW1lfCBEXG4gICAgRCAtLT58bW91bnQqfCBFXG4gIGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Now, if we add to the hostPath/subPath volume in the nginx pod, we should actually see the files in the kubelet and on the host. 

3. Exec into the nginx pod's corresponding docker container with: `docker exec -it $(docker ps -aq --filter "label=io.kubernetes.container.name=nginx") /bin/sh`
4. Create a file in the container at the mount point with: `echo "hello" > /volume/nginx/f.txt`
5. Exit container and check file on host with: `cat /site-data/nginx/f.txt` (this should output `hello`)
6. Exec into the kubelet with: `docker exec -it $(docker ps -aq --filter "name=kubelet") /bin/sh`
7. Validate in the kubelet container with: `cat /site-data/nginx/f.txt` (this should output `hello`)

Taking this one step further, we can setup a k8s cluster that does not use a containerized kubelet. This can be accomplished most easily with k3d or minikube. The output from the `findmnt /var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0` command here will look something like:
```
TARGET                                                                                       SOURCE                  FSTYPE OPTIONS
/var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0 ext4[/site-data/nginx] ext4  rw,relatime,size=3543256k
```

We can see that a filesystem was created at `/site-data/nginx` and mounted to `/var/lib/kubelet/pods/d0b79a40-6a69-47d9-a7e4-ef36331732e2/volume-subpaths/site-data/nginx/0`, which in turn is mounted as a volume to the corresponding container. The difference here is that, since the kubelet is running directly on the kubernetes node, the mount's source (`ext4[/site-data/nginx]`) actually lives on the host and not inside of a container. This allows for files written to `/volume/nginx` inside the container to be persisted back to the host filesystem.  

Other k8s clusters which use a containerized kubelet will run into this same issue with `hostPath` volumes using `subPath`. I confirmed this by creating a Digital Ocean managed cluster and deploying the above nginx deployment which uses a `subPath`. Any files added to `/volume/nginx` in the pod's corresponding container were not populated on the host at `/site-data/nginx`.

## Alternatives

Instead of using a `hostPath` volume with a `subPath`, multiple `hostPath` volumes without a `subPath` could be used.

## Additional information

There was previously a workaround where the kubelet's container could be run with a volume `-v /:/rootfs:rshared` mounting the host's root filesystem inside the container at `/rootfs`, along with the kubelet process being given the `--containerized` flag which makes the kubelet aware of `/rootfs`. This allowed for `hostPath` volumes using a `subPath` to work as expected, but due to maintenance efforts by the upstream, this flag was deprecated in kubernetes version `1.14` and removed in version `1.16`. As such, it is no longer an option.
