### ISSUE TITLE
vSphere Cloud Provider not working

### ISSUE THREAD

**Issue by MaxDiOrio** [rancher/rancher#14889]
**Rancher versions:**
rancher/server or rancher/rancher:  v2.0.6

**Docker version: (`docker version`,`docker info` preferred)**  Docker version 1.12.6, build 3e8e77d/1.12.6 

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**.   RHEL 7.5 3.10.0-862.9.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**. VMWare vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**. Single Node

So I'm trying to deploy clusters with vSphere Cloud Provider so that I can create persistent volumes.

When I bring up the cluster after editing the yaml, all machines are stuck Registering - Waiting to register with Kubernetes

I see the following in the Rancher logs.  The really strange one is why is it looking for the datacenter as a uint?  

2018/08/01 19:32:33 [ERROR] cluster [c-hlnt5] provisioning: [workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.85.175.34]: Get https://localhost:10250/healthz: dial tcp [::1]:10250: getsockopt: connection refused, log: F0801 19:32:20.783951    7019 server.go:233] failed to run Kubelet: could not init cloud provider "vsphere": failed to parse "Latham-Colo-DC" as uint: expected integer

[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.85.175.34]: Get https://localhost:10250/healthz: dial tcp [::1]:10250: getsockopt: connection refused, log: + umount /var/lib/docker/overlay/92e64d20058ccfab51ab2f4e374b797e330d9c5b09761f33a7b4b51e849864e3/merged/opt/rke/var/lib/kubelet

Failed to create Certificates deployer container on host [10.85.175.36]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I'm using the following Cloud Provider yaml:

```
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
      global: 
        insecure-flag: 1
        user: svcaccount
        password: password
        port: 443
      virtual_center:
        10.85.128.181:
            datacenters: Latham-Colo-DC
      workspace:
        server: 10.85.128.181
        datacenter: Latham-Colo-DC
        folder: pvols
        default-datastore: /Latham-Colo-DC/datastore/vmware_kube1
        resourcepool-path: /Latham-Colo-DC/host/Production-Cluster
      disk:
        scsicontrollertype: pvscsi
```

Any ideas?  Thanks!
