### ISSUE TITLE
Rancher Displays Certificate Improperly When It is Added via k8s

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14921]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

**Steps to Reproduce:**
Configure cert-manager to successfully issue a certificate and then try and view it in the Rancher Interface.

**Results:**
The Rancher UI does not display the information correctly. On the certificate list, it shows no domains and an invalid date for expiration. On the certificate details, it shows the current time for Beginning and End dates, and shows no other information.

![screen shot 2018-08-02 at 3 54 33 pm](https://user-images.githubusercontent.com/48329/43613373-636b6ade-966c-11e8-93db-4b3973c4590a.png)

**Expected Behavior:** One would expect that if the certificate is shown that it render the correct and complete information.

**Comment by ekristen** [comment]
This is still an issue. Certs that are being added with cert-manager for example is the easiest way to introduce this.

**Comment by vincent99** [comment]
That info is parsed out during upload so the UI doesn't need to have a giant X.509/ASN.1 parser library, but does not get populated if a cert is created directly through the k8s API.

**Comment by ekristen** [comment]
It’s a pretty common use casenow, any way to have the rancher server monitor and parse after the fact to keep the UI minimal?

**Comment by cjellick** [comment]
Sounds like a good idea. I assume @vincent99 agrees since he assigned to me

**Comment by sowmyav27** [comment]
### reproduced the issue with rancher:v2.2.6-rc3
**Steps:**

1. Deploy Cert Manager on a cluster - project on Rancher UI
2. Deploy a certificate from kubectl into a namespace

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  commonName: example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
```
3. Go to the namespace --> Certificates --> Select your certificate. Details of the certificate are not available on the UI.
<img width="1337" alt="Screen Shot 2019-07-23 at 11 40 59 AM" src="https://user-images.githubusercontent.com/26032343/61738838-02eb5480-ad40-11e9-8b2a-d7f475b3aa02.png">


Verified on master-head (latest - 07/23/2019)
**Steps:**

1. Deploy Cert Manager on a cluster - project on Rancher UI
2. Deploy a certificate from kubectl into a namespace - as mentioned above.
3. Go to the namespace --> Certificates --> Select your certificate. Details of the certificate are available on the UI.
