### ISSUE TITLE
1.6.20 / k8s-1.11.1 - unable to get etcd-metrics

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#14932]
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.20

**Infrastructure Stack versions:**
healthcheck:v0.3.8
ipsec:0.13.17
network-services: v0.10.4
scheduler:
kubernetes (if applicable): 1.11.1

**Docker version: (`docker version`,`docker info` preferred)** 17.09.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 4.9.80-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** singel-node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:** upgrade kubernetes to 1.11.1

**Results:**
Can't scrape etcd-metrics anymore from within kubernetes. The following prometheus-config worked before:
```
scrape_configs:
  - job_name: etcd
    metrics_path: /metrics
    dns_sd_configs:
    - names:
      - etcd.kubernetes
      port: 2379
      type: A
    relabel_configs:
    - replacement: sys
      target_label: team
```

Executing the following from within a etcd-container:
```
root@2bc9fa81861e:/opt/rancher# curl -v  127.0.0.1:2379/metrics
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /metrics HTTP/1.1
> Host: 127.0.0.1:2379
> User-Agent: curl/7.47.0
> Accept: */*
>

* Connection #0 to host 127.0.0.1 left intact
root@2bc9fa81861e:/opt/rancher#
```

regards,
Roman
