### ISSUE TITLE
how to modify "kube-apiserver" values in Rancher Kubernetes

### ISSUE THREAD

**Issue by manwanth** [rancher/rancher#14992]
**Rancher versions:** 
rancher/server or rancher/rancher: v.1.6.18
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:** 
healthcheck: v.0.3.6
ipsec: v.0.2.4
network-services: v.0.2.9
scheduler: 
kubernetes (if applicable): v.1.10.3-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**  17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 3.10.0-862.9.1.el7.x86_64

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
I would like to update "kube-apiserve" values to hardening Kuberneties, but I am not able to find /etc/kubernetes/manifests/kube-apiserver.yaml file under kublet. Where can I find kube-apiserver.yam file?

**Results:**

**Comment by superseb** [comment]
Duplicate of https://github.com/rancher/rancher/issues/12184

**Comment by manwanth** [comment]
I know Its duplicate of #12184, but I still waiting for solution. I did not see any response on this.

**Comment by fly2tomato** [comment]
Also need to modify kube-apiserver.yaml but can't find it anywhere in the master node.
The key is  the kube-apiserver.yaml  does not exist in the master node, but you can modify the settings of kube-apiserver.yaml by using cluster.yaml when you use rke to build up your k8s cluster.
For example, if you want to add **feature-gates=RemoveSelfLink=false** into kube-apiserver.yaml，it is equal to add it into cluster.yaml:
kube-apiserver.yaml:
```
spec:
  containers:
  - command:
    - kube-apiserver
    - --feature-gates=RemoveSelfLink=false ## new feature to be added
```
cluster.yaml:
```
service:
  kube-api:
    extra_args:
      feature-gates: "RemoveSelfLink=false" ## new feature to be added
```
