### ISSUE TITLE
vSphere cluster provisioning fails when Docker version is specified in cloud-config

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#15019]
**Rancher versions:**
rancher/server v2.06

**Steps to Reproduce:**
1. Create a cloud-config having at least the following content:
```
#cloud-config
rancher:
  docker:
    engine: docker-17.03.2-ce
```
2. Create vSphere node template with the following guestinfo configuration parameters:
- `guestinfo.cloud-init.config.data`: `<base64 encoded cloud-config>`
- `guestinfo.cloud-init.data.encoding`: `base64`
3. Create a vSphere cluster using that template

**Results:**
vSphere cluster creation fails

```
