### ISSUE TITLE
option "proxy-read-timeout" of rancher's nginx ingress is defined differently from kubernetes/ingress-nginx

### ISSUE THREAD

**Issue by DoubleFaults** [rancher/rancher#15044]
**Rancher versions:** rancher/rancher:v2.0.6

**Steps to Reproduce:**

1. Edit cluster -> Cluster Options -> Edit as yaml
2. add `ingress` part:

```yaml
ingress: 
  options: 
    proxy-body-size: "128G"
    proxy-read-timeout: 600 # add this item
```

> I used "600", because [ingress nginx documentation](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md) says that this option takes a integer as value.But why did I quote it? I met `strconv.ParseInt failed` in the logs of `nginx-ingress-controller" pod when I used "600s".

3. after cluster updated, check `ingress-nginx` yaml(route: Projects/Namespaces -> Not in a project -> ingress-nginx -> Menu:View/Edit YAML)

**Results:**

`proxy-read-timeout` does not show up there. 

It is similar to `proxy-connect-timeout` and `proxy-send-timeout`.

---

When I added as `proxy-read-timeout: "600s"`, it would be added to ingress-nginx's configmap.

**But** it caused a `strconv.ParseInt: parsing "600s": invalid syntax` when I restarted `nginx-ingress-controller-xxxxx` pods and checked its logs.

**Comment by sangeethah** [comment]
Tested with latest build from master:

1. Create cluster with version -  v1.11.2 
2. Edit cluster -> Cluster Options -> Edit as yaml
add ingress part:
ingress: 
  options: 
    proxy-body-size: "128G"
    proxy-read-timeout: 600 # add this item

3. After cluster gets updated, check ingress-nginx yaml 

  proxy-read-timeout parameter is present:

```
  data:
    proxy-body-size: 128G
    proxy-read-timeout: "600"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"proxy-body-size":"128G","proxy-read-timeout":"600"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"ingress-nginx"},"name":"nginx-configuration","namespace":"ingress-nginx"}}
```
