### ISSUE TITLE
Rancher v2.0.7 upgrade re-adds cluster nodes by hostname 

### ISSUE THREAD

**Issue by frenchtoasters** [rancher/rancher#15093]
It would seem that after the v2.0.7 upgrade my cluster was reconfigured and the nodes were readded by hostname instead of IP like they were previously. 

**Rancher versions:**
rancher/rancher v2.0.7

**Docker version: (`docker version`,`docker info` preferred)**
17.03-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release`
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

`uname -r`
4.4.0-116-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher-ha deployed with RKE

**Steps to Reproduce:**
Deploy v2.0.5/6 cluster and define the nodes in the cluster.yml with just the IP addresses, the cluster will then be created with all nodes having the name being their IP addresses. After the upgrade to v2.0.7 my cluster now shows 6 nodes instead of 3, with 3 of them `Unavailable` with a `Kubelet stopped posting node status.` message all of these are the nodes that were deployed originally and added to the cluster with their IP addresses as the name. The other 3 nodes are the same nodes however they were added to the cluster with their hostnames instead of IP addressses. 

**Results:**
3 `Unavailable` nodes that are the same as the available nodes added to the cluster. The extra nodes that were added only show that they have a role of `Worker` and the other `Unavialble` nodes show they have a role of `All`

Here is the kubectl output:
```
> kubectl get nodes --kubeconfig kube_config_cluster.yml 
NAME            STATUS     ROLES                      AGE       VERSION
172.21.35.204   NotReady   controlplane,etcd,worker   23d       v1.10.5
172.21.35.206   NotReady   controlplane,etcd,worker   23d       v1.10.5
172.21.35.209   NotReady   controlplane,etcd,worker   9d        v1.10.5
rancher-ha1     Ready      <none>                     19h       v1.10.5
rancher-ha2     Ready      <none>                     19h       v1.10.5
rancher-ha4     Ready      <none>                     19h       v1.10.5
```

Also it seems that now the cluster is being reported as an imported cluster in the Rancher GUI

**Comment by galal-hussein** [comment]
@frenchtoasters i wasn't able to reproduce the problem, i can see the node still registered with the IP even after the upgrade to v2.0.7, i think what might happened is that you configured the hostname_override in the cluster.yml and upgraded, this will cause the kubelet to restart and re-register with the hostname instead, can you show us the cluster.yml before and after upgrade?

**Comment by frenchtoasters** [comment]
The only difference from before and after was that i added a cloud provider after the upgrade and before i noticed the issue above. 

Before
```
nodes:
  - address: 172.21.35.204 # hostname or IP to access nodes
    user: ubuntu # root user (usually 'root')
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/rancher # path to PEM file
  - address: 172.21.35.206
    user: ubuntu
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/rancher
  - address: 172.21.35.209
    user: ubuntu
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/rancher

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: 
    tls.key: 
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: 
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: rancher-ha.lab  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - rancher-ha.lab     # FQDN to access cattle server
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
            
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```

After:
```
nodes:
  - address: 172.21.35.204 # hostname or IP to access nodes
    user: ubuntu # root user (usually 'root')
    role: [controlplane,etcd,worker] # K8s roles for node
    ssh_key_path: ~/.ssh/rancher # path to PEM file
  - address: 172.21.35.206
    user: ubuntu
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/rancher
  - address: 172.21.35.209
    user: ubuntu
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/rancher

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: 
    tls.key: 
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: 
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: rancher-ha.tom.future.lab  # FQDN to access cattle server
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - rancher-ha.tom.future.lab     # FQDN to access cattle server
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
            
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge

cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      insecure-flag: true
      user: administrator@vsphere.local
      password: 
      datacenter: MGMT
      working-dir: kubernetes
      server: 172.21.35.10
  virtual_center:
    172.21.35.10: {}
  worksapce:
    server: 172.21.35.10
    datacenter: MGMT
    folder: kubernetes
    default-datastore: mgmt-vms/mgmt-vms1
```
