### ISSUE TITLE
Rancher [2.0.7] Rancher CLI Create cluster rke config cloud config not applied 

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15098]
**Rancher versions:**
rancher/server 2.0.7

Using Rancher CLI and passing RKE config to create cluster. In the rke config I am passing cloud config but that is not being set.

```
cloud_provider:
  name: openstack
  openstackCloudProvider:
    global:
      username: test
      password: test
      auth-url: test
      tenant-id: test
      domain-id: test
    block_storage:
      ignore-volume-az: false
```

```
rancher cluster create --rke-config ~/Downloads/rke.yml mitch --k8s-version v1.10.5-rancher1-2 
```

Then when I look in Rancher the cloud config is not set at all.

**Comment by jamiebuxxx** [comment]
I'm experiencing the same issue. After the cluster comes online, I'm able to set the cloud config in the GUI. It would be ideal to have the cloud config be set from the rke config for automation purposes.

**Comment by leodotcloud** [comment]
@mitchellmaler I am really not sure what part of the yaml file is not working for you. Is it a particular setting? I don't see any cloud config specified in the yaml snippet above. Can you please elaborate on the problem that you are facing? 

BTW, cloud provider and cloud config are two different things. Cloud Provider is more of a cluster level thing and also it's a kubernetes concept. Cloud Config is more about what happens with a particular machine after boot up. It's more at the VM/Machine level.

**Comment by alena1108** [comment]
@leodotcloud openstackCloudProvider gets translated to the cloud config on the backend. We just need to check why values passed by CLI, are not being set on the cluster.RancherKubernetesConfig API. Based on what @mitchellmaler and @jamiebuxxx observe, only UI-API works, but not CLI-API

**Comment by jamiebuxxx** [comment]
I believe is this related to the following bug: https://github.com/rancher/rancher/issues/19095. I can confirm that when using the JSON format as mentioned in the the issue, everything works as expected. Certain things don't appear to work when using the YAML format.

**Comment by alena1108** [comment]
@mitchellmaler can you share your entire rke.yaml? sensitive data like password can be omitted.

**Comment by leodotcloud** [comment]
Root cause:

When using the Rancher CLI, the yaml file is being unmarshalled here: https://github.com/rancher/cli/blob/master/cmd/cluster.go#L768 with the struct from the generated file. 

Whereas RKE binary does not use the generated one: https://github.com/rancher/rke/blob/master/cmd/common.go#L48

Hence, the yaml from the docs (https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/) works for RKE binary and not for rancher CLI.

A temporary work around is to change `cloud_provider` to `cloudProvider` but once the fix is available, this will not work anymore.

**Comment by sowmyav27** [comment]
Reproduced the issue on `v2.2.6`

**Steps:**
Using Rancher CLI and passing RKE config to create cluster. In the rke config pass, cloud config
```
cloud_provider:
  name: openstack
  openstackCloudProvider:
    global:
      username: test
      password: test
      auth-url: test
      tenant-id: test
      domain-id: test
    block_storage:
      ignore-volume-az: false
```
```
./rancher cluster create --rke-config rancher-cluster.yml test2 --k8s-version v1.15.0-rancher1-1
```

**Result:**
Cloud config is not set. Verify in `View in API` of the cluster

Verified the fix in rancher:master-head
**Steps:**
Using Rancher CLI and passing RKE config to create cluster. In the rke config pass, cloud config
```
cloud_provider:
  name: openstack
  openstackCloudProvider:
    global:
      username: test
      password: test
      auth-url: test
      tenant-id: test
      domain-id: test
    block_storage:
      ignore-volume-az: false
```
```
./rancher cluster create --rke-config rancher-cluster.yml test2 --k8s-version v1.15.0-rancher1-1
```

**Result:**
Cloud config i set. Verify in `View in API` of the cluster
```
"cloudProvider": {
"name": "openstack",
"openstackCloudProvider": {
"blockStorage": {
"bs-version": "",
"ignore-volume-az": false,
"trust-device-path": false,
"type": "/v3/schemas/blockStorageOpenstackOpts"
},
"global": {
"auth-url": "https://1.2.3.4/identity/v3",
"ca-file": "",
"domain-id": "xxxxxxxxxxxxxx",
"domain-name": "",
"region": "",
"tenant-id": "xxxxxxxxxxxxxx",
"tenant-name": "",
"trust-id": "",
"type": "/v3/schemas/globalOpenstackOpts",
"user-id": "",
"username": "xxxxxxxxxxxxxx"
},
```
