### ISSUE TITLE
rancher-compose/cli doesn't apply lb_config to an existing service

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#15132]
**Rancher versions:**
Rancher | v1.6.20
Cattle | v0.183.60
User Interface | v1.6.45
Rancher CLI | v0.6.11
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.8
ipsec: rancher/net:v0.13.17
network-services: rancher/network-manager:v0.7.22
scheduler: rancher/scheduler:v0.8.5

**Docker version: (`docker version`,`docker info` preferred)**
Docker: 17.12.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Kernel: 4.4.0
OS: Ubuntu 16.04.3 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher / external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create a service without lb_config first:
```
version: '2'
services:
  web:
    image: nginx
```

2. Add lb_config to rancher-compose.yml and run an upgrade (`rancher-compose up -d -u -c`):
```
version: '2'
services:
  web:
    lb_config:
      - port_rules:
          target_port: 80
          hostname: nginx.lb
```

**Results:**

`lb_config` section doesn't get applied to an existing service and it cannot be picked up (selected) by a load balancer; the only way to make it work is to completely re-create a service from scratch, which also means any existing external links that point to such service will be gone (very BAD side-effect - another issue that need to be tacked separately)

any further changes to `lb_config` also have no effect until service is re-created
