### ISSUE TITLE
Rancher load balancer sends traffic to upgraded containers before healthcheck passes

### ISSUE THREAD

**Issue by bghinkle** [rancher/rancher#15189]
**Rancher versions:**
rancher/server: 1.6.20
rancher/agent: 1.2.11

**Infrastructure Stack versions:**
healthcheck: 0.3.8
ipsec: 0.2.5
network-services: 0.2.10
scheduler: 0.8.5
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS (Xenial Xerus), Kernel 4.4.0-1061-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single-node Rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy a stack from the catalog with an Rancher HAProxy load balancer sending traffic to a service with multiple containers with an upgrade strategy of `start_first: true` and an HTTP health check defined. See the following rancher-compose.yml (skipping .catalog section) as an example:

```
version: '2'
services:
  test-service:
    scale: 3
    drain_timeout_ms: 10000
    upgrade_strategy:
      start_first: true
    health_check:
      port: 33380
      request_line: GET /health HTTP/1.0
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 2
      strategy: recreate
      healthy_threshold: 2
      response_timeout:

  test-lb:
    scale: 2
    upgrade_strategy:
      start_first: true
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /api
        priority: 1
        protocol: http
        service: test
        source_port: 36784
        target_port: 33380
```
After the stack is green, deploy an updated version of the stack with newer container images.

**Results:**
Logs from the newer container show that application traffic is sent to it through the Rancher LB, *before* any health check traffic arrives at the container. This causes failures to callers of the service if the new container is unhealthy before it's marked down by the healthcheck process.

The expected result should be that the load balancer does **not** send traffic to a container until it has passed its healthcheck.
