### ISSUE TITLE
istio automatic injection  not working in rancher/rancher 2.0

### ISSUE THREAD

**Issue by damozhiying** [rancher/rancher#15182]
Custom runtime-config arguments in kubernetes project-template,
admission controllers via kube-api arguments

**Comment by david-maumenee** [comment]
Hi,

You can check kube-api config by running this command one the control plane node :
```
docker inspect kube-apiserver | grep admission-control
```

For me it's ok with both K8s 1.10 and 1.11 with a custom K8s config (via "Edit Yaml")
```yaml
services:
   kube-api:
     ...
     extra_args:
       admission-control: ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,DefaultTolerationSeconds
```
see https://github.com/rancher/rancher/issues/14032#issuecomment-398006866

Then check if istio-injection is enabled in your namespace with ```kubectl get namespace -L istio-injection```
if not already ```kubectl label namespace my-name-space istio-injection=enabled```
