### ISSUE TITLE
Restore deleted built-in node driver

### ISSUE THREAD

**Issue by jinhong-** [rancher/rancher#15267]
I am on rancher 2.0.8. I deleted the built in openstack node driver. Is there any way i can restore it?

**Comment by guangbochen** [comment]
you can eitther reinstall your rancher server or run `kubectl apply` to get the nodedriver back.  
1. login to your rancher host and exec into the rancher docker container,
2. and run `kubectl apply -f osnode.yaml` will create one for you.

osnode.yaml:
```
apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  annotations:
    lifecycle.cattle.io/create.node-driver-controller: "true"
  clusterName: ""
  finalizers:
  - controller.cattle.io/node-driver-controller
  generation: 1
  name: openstack
  namespace: ""
  selfLink: /apis/management.cattle.io/v3/nodedrivers/openstack
spec:
  active: false
  builtin: true
  checksum: ""
  description: ""
  displayName: openstack
  externalId: ""
  uiUrl: ""
  url: local://
```
