### ISSUE TITLE
Anti-affinity rule specified with label io.rancher.stack_service.name=env_name/service_name breaks sidekick placements.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1530]
Server version - V0.27.0-rc4
Steps to reproduce the problem:

Create service with sidekick such that primary launch config has anti-affinity rule to itself using the following configuration:

    launch_config_service = {
        "imageUuid": SSH_IMAGE_UUID,
        "labels": {
            'io.rancher.scheduler.affinity:container_label_ne':
                "io.rancher.stack_service.name" +
                "=" + env_name + "/" + service_name
        }
    }

    launch_config_consumed_service = {
        "imageUuid": WEB_IMAGE_UUID}
  
Service is created with following configurations:

     name=service_name, environmentId=env.id,
        launchConfig=launch_config_service, scale=service_scale,
        secondaryLaunchConfigs=[launch_config_consumed_service])

When service is activated ,  the primary launch config containers get deployed in different hosts with anti-affinity scheduling as expected.

But the sidekick containers are not placed in the same host as the primary containers as per the deployment units.

**Comment by sangeethah** [comment]
Tested with build from master:
Anti-affinity rule specified with label io.rancher.stack_service.name=env_name/service_name works.
We are

Following are the docker-compose.yml files used for sidekick with anti-affinity and both of them work as expected:

with environment name:

```
test:
  tty: true
  image: sangeetha/testclient
  stdin_open: true
  labels:
    io.rancher.sidekicks: w1,w2
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=sk9/test
w1:
  tty: true
  image: sangeetha/testhostrouting
  stdin_open: true
w2:
  tty: true
  image: sangeetha/testhostrouting
  stdin_open: true
```
without environment name:

```
test:
  tty: true
  image: sangeetha/testclient
  stdin_open: true
  labels:
    io.rancher.sidekicks: w1,w2
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=test
w1:
  tty: true
  image: sangeetha/testhostrouting
  stdin_open: true
w2:
  tty: true
  image: sangeetha/testhostrouting
  stdin_open: true
```
