### ISSUE TITLE
[rancher-dns] How to make a rancher service use consul DNS

### ISSUE THREAD

**Issue by edwinallenz** [rancher/rancher#15304]
I'm trying to make a service use consul to query DNS entries, with a new global recurse for rancher-dns service or disable rancher dns for a specific service and only use consul DNS.

This is the compose file where I'm trying to make a service query consul DNS entries.
```
version: '2'
services:
  busy:
    image: tutum/dnsutils
    stdin_open: true
    external_links:
    - consul/consul:consul
    dns_search:
    - 10.42.173.171
    dns:
    - 10.42.173.171
    tty: true
    labels:
      io.rancher.container.dns.priority: service_last
      io.rancher.container.pull_image: always
      io.rancher.service.external_dns: 'false'
      rancher.container.dns: 'false'
      io.rancher.container.network: 'false'
```
The DNS entry is added to the `resolv.conf` file but it's overrided by rancher.
```
/# cat /etc/resolv.conf
search 10.42.173.171 dns.rancher.internal busy.dns.rancher.internal rancher.internal
# nameserver 10.42.173.171
nameserver 169.254.169.250
```

Thanks in advance.
**Rancher versions:**
rancher/server or rancher/rancher: 1.6.15
Rancher DNS
dns:v0.17.3

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
