### ISSUE TITLE
Ingress cannot configure multiple backends on one frontend

### ISSUE THREAD

**Issue by xiaoluhong** [rancher/rancher#15312]
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7  v2.0.8
rancher/agent or rancher/rancher-agent: v2.0.7  v2.0.8

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
wmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Steps to Reproduce:**
1、Create two new workloads, demo1 is nginx(80) and demo2 is tomcat(8080) (Under normal circumstances, the page will be displayed in rotation.)
2、Add inress, configuration as shown below:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/20707603/44846841-33d41e00-ac84-11e8-8e61-cef6de19efb5.png">
3、Save ingress and re-edit inress，The result is as follows：

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/20707603/44846953-857ca880-ac84-11e8-902a-67d8143f8e23.png">

4、View YAML configuration
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/20707603/44847104-ef954d80-ac84-11e8-8a3e-0c7379322d2a.png">

**Results:**

Tested after multiple replacement configurations， if there are multiple backends，If there are multiple backends, the last backend port will replace all previous backend ports. And, only one backend will be displayed in the YAML configuration.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/45009411-9e95a880-b03a-11e8-81c4-d2a54f6a8268.png)

Backend doesn't support different target ports of workloads. Given the same `path`, even user can select different workloads but user can not specify different ports for each workload.

I guess we need to change the schema and update the UI as well.

**Comment by orangedeng** [comment]
@loganhz @xiaoluhong I don't think this is a decent use case for kubernetes ingress and service. Paths need to be unique in a host rule. Load balancing workload is the job for service, not ingress.

**Comment by alena1108** [comment]
In native k8s ingress, you can't define the multiple backends for the same paths. Here is native ingress example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
```

Same for the rule w/o the path - for a single hostname, only one backend is allowed:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: testsvc
    servicePort: 80
```

Also if you look at k8s service definition, you could see that the same source port can't be directed to different backend ports:

```
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9377
```

That should explain why you a) can only direct the traffic for path/hostname to a service's single port and why b) single service port can only direct the traffic to the single target port.
