### ISSUE TITLE
Rancher healthchecks cause high network load / container restarts

### ISSUE THREAD

**Issue by patrickkeller** [rancher/rancher#15373]
We have a 3 node environment (identical hardware, see docker info below) with ~100 stacks. The healthchecks (see config below) cause high network load/container restarts because of the high load. When we stop the healthcheck-stack the env gets fast again. We tried already to recreate healtcheck-, ipsec-, network-services. 

**Healthcheck config that causes the problem:**
```
services:
  server:
    scale: ${NODE_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      request_line: '/planer/ui'
      interval: 15000
      healthy_threshold: 2
      initializing_timeout: 600000
      reinitializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate

  customer-ui:
    scale: ${NODE_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      request_line: ''
      interval: 15000
      healthy_threshold: 2
      initializing_timeout: 600000
      reinitializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate

  admin-ui:
    scale: ${NODE_SCALE}
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      request_line: ''
      interval: 15000
      healthy_threshold: 2
      initializing_timeout: 600000
      reinitializing_timeout: 600000
      unhealthy_threshold: 3
      strategy: recreate

  redis:
    scale: 1
    health_check:
      port: 6379
      request_line: ''
      interval: 15000
      healthy_threshold: 2
      unhealthy_threshold: 3
      strategy: recreate
```

**Rancher versions:**
```
rancher/server v1.6.21
rancher/agent v1.2.11
```

**Infrastructure Stack versions:**
```
healthcheck: v0.3.8
ipsec: v0.13.17
network-services: v0.10.4
scheduler: v0.8.5
```

**Docker version: (`docker version`,`docker info` preferred)**
(One host)
```
Containers: 160
 Running: 156
 Paused: 0
 Stopped: 4
Images: 77
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: v0.13.2 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.14.59-coreos-r2
Operating System: Container Linux by CoreOS 1800.6.0 (Rhyolite)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 47.17GiB
Name: sopl01
ID: 3G4Z:AGNE:SCYG:O7SH:FBMU:EWMW:BQ2Y:ZYOZ:WAT2:WI7L:XOXJ:MYZZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`Container Linux by CoreOS stable (1800.6.0)`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`KVM`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 identical hosts

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Don't know. Deploy a large amount of stacks?

**Results:**
Healtchecks should not cause high network load and containers
