### ISSUE TITLE
automatically created network policy "np-default" for services of type NodePort does not work

### ISSUE THREAD

**Issue by sebastiansirch** [rancher/rancher#15372]
When a service of type NodePort is created, accessing the pod via the generated port works fine for less than 60 minutes. at some point in time, a network policy is created which blocks any access from outside.

Despite the fact that the generated policy does not work - "enableNetworkPolicy: false" does not prevent rancher from creating the policy at all.

Generated policy
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: 2018-09-01T21:21:31Z
    generation: 1
    labels:
      field.cattle.io/projectId: p-pmtbj
    name: np-default
    namespace: demo
    resourceVersion: "34490822"
    selfLink: /apis/extensions/v1beta1/namespaces/demo/networkpolicies/np-default
    uid: ff23e1a6-ae2c-11e8-abc4-005056b0e5cb
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            field.cattle.io/projectId: p-pmtbj
      - namespaceSelector:
          matchLabels:
            field.cattle.io/projectId: p-tltfn
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Rancher versions:**
2.0.8

**Infrastructure Stack versions:**

RKE cluster with the following cluster.yaml

```
nodes: # skipped here...

enableNetworkPolicy: false

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 24h # time increment between snapshots
    retention: 10d # time increment before snapshot purge
  kube-api:
    extra_args:
      v: 4
      feature-gates: "MountPropagation=true"
  kube-controller:
  scheduler:
  kubelet:
    extra_binds:
      - "/dev:/dev"
      - "/usr/libexec/kubernetes/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins"
      - "/var/lib/storageos:/var/lib/storageos:rshared"
    extra_args:
      feature-gates: "MountPropagation=true"
      read-only-port: 10255
  kubeproxy:

ingress:
  provider: none

network:
  plugin: "canal"

```

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

vmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

cluster created with RKE, afterwards imported into rancher HA (running on the same cluster)
cluster was initially setup with rancher 2.0.0 and updated step-wise to 2.0.8 and latest RKE version

**Steps to Reproduce:**

create a pod and service of type node port
wait for ~60 minutes and check the network policy which has been created automatically

**Results:**

the network policy should not block the configured nodeport access.
