### ISSUE TITLE
add rancher server magic proxy as addtional access service type in the catalog UI

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#15375]
Rancher versions: 2.0 master 09/03

Using [k8s api server proxy](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls) of rancher server as an additional service type in the catalog UI, the endpoint of rancher's magic proxy will be secured by the rancher server's auth.

services using the api-server proxy is requried to add metadata label `kubernetes.io/cluster-service: "true"` as below.
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes-dashboard.fullname" . }}
  labels:
    kubernetes.io/cluster-service: "true" # cluster-service is required
```

Results: User will be able to select `rancher-proxy` as a service type of accessing it's server.
![image](https://user-images.githubusercontent.com/4569037/44970118-b4479700-af82-11e8-8dee-83b987b02e43.png)
