### ISSUE TITLE
Not able to access LB rules due to incorrect programming on haproxy.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1550]
Server version - V0.28.0-rc1

Rancher compose version- V0.2.0

Steps to reproduce the problem:

Create LB service using the files:
```
root@45b656f59e5b:~/rancher-compose-v0.2.0# cat lb_service-rancher-compose.yml
LB-test408449:
  scale: 1
test129207:
  scale: 2
test-763295:
  scale: 2

root@45b656f59e5b:~/rancher-compose-v0.2.0# cat  lb_service-docker-compose.yml
LB-test408449:
  ports:
  - 7900:80
  image: rancher/load-balancer-service
  links:
  - test129207:test129207
  - test-763295:test-763295
test129207:
  image: sangeetha/testlbsd:latest
test-763295:
  image: sangeetha/testlbsd:latest

root@45b656f59e5b:~/rancher-compose-v0.2.0# 
```

LB service gets created but not able to access LB rules due to incorrect programming on haproxy.

<img width="753" alt="screen shot 2015-07-15 at 4 14 22 pm" src="https://cloud.githubusercontent.com/assets/4266958/8712057/9416198c-2b0c-11e5-92e9-3b9f2b0b96de.png">
