### ISSUE TITLE
open the UDP protocol 5000-6000 continuous 1000 ports

### ISSUE THREAD

**Issue by kys1230** [rancher/rancher#15511]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.20` Cattle: `v0.183.60` UI: `v1.6.45` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.code`|

I need to open the UDP protocol 5000-6000 continuous 1000 ports, but the answer is format error.

my docker-compose.yml
```yaml
version: 2
services:
  test:
    image: alpine:latest
    ports:
      - 5000-6000:5000-6000/udp
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
```
my rancher-compose.yml
```yaml
version: '2'
services:
  test:
    scale: 1
    retain_ip: true
```

error message:
```text
Error (Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, message=the specified port spec format is wrong, code=PortWrongFormat] from [http://localhost:8080/v2-beta/projects/1a5/services])
```
