### ISSUE TITLE
Need a way to pass credentials for system-default-registry

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15554]
**Rancher versions:** Build from master

**Steps to Reproduce:**

There is no way to pass credentials for system-default-registry from rancher-server for creating RKE clusters.

**Comment by alena1108** [comment]
@westlywright the api support is already in - the parameter is called privateRegistries on the config - so we have to add support in the UI for that.

**Comment by bmdepesa** [comment]
From https://github.com/rancher/rke/issues/588 - 

When creating a cluster, we are able to edit cluster yaml before creation, and add credentials for private registry: 
```
private_registries:
- url: <registry url>
  user: <password>
  password: <password>
  is_default: true
```
