### ISSUE TITLE
[rancher-compose] docker-compose extends behaviour

### ISSUE THREAD

**Issue by VogonogoV** [rancher/rancher#1556]
rancher-server: v0.28-rc1
rancher-compose: v0.2.1
docker-compose: 1.3.2

The compose feature of docker supports [extending](https://docs.docker.com/compose/extends/) of docker files. At the section about [overriding configuration](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration) it states: 
> Compose copies configurations from the original service over to the local one, except for `links` and `volumes_from`.

## Example 1
common.yml:
```
web:
  image: ubuntu:14:04

db:
  image: ubuntu:14:04
```
docker-compose.yml:
```
web:
  extends:
    file: common.yml
    service: web

db:
  extends:
    file: common.yml
    service: db
  links:
    - web:web
```
Command
```
rancher-compose create
```
I expected to see the link from db to web. However, there are no links at all.

## Example 2
When adding the link to the `common.yml` file and removing it from the `docker-compose.yml`:
```
web:
  image: ubuntu:14:04

db:
  image: ubuntu:14:04
  links:
    - web:web
```
docker-compose.yml:
```
web:
  extends:
    file: common.yml
    service: web

db:
  extends:
    file: common.yml
    service: db
```
I expect to see no link. However, there is a link between `db` and `web` now. docker-compose even says the second example is invalid.
```
$ docker-compose up
Cannot extend service 'db' in <path>/common.yml: services with 'links' cannot be extended
```
