### ISSUE TITLE
Be able to send notifications to notifiers when pipelines are finished

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#15665]
When a pipeline execution finishes, it would be useful if we can send notifications to existing notifiers.
The yaml config would be
```
notification:
  notifiers: ["notifier-a","notifier-b"]# existing notifiers' Id/name, string or array.
  condition: "Failed"# send notifications when execution result is "Failed", options including `Failed/Success/Changed`
  message: "xxx" # Optional, we have default messages but users can overwrite it.
```
Edit: the following format would be better to support multiple recipients and to keep consistent with how alerts use notifiers.
```
notification:
  recipients:
    - notifier: notifier-a
      recipient: "#channel-abc"
    - notifier: notifier-a
      recipient: "@somebody"
    - notifier: notifier-b #using default recipient of the notifier
  condition: Failed
  message: "xxx"
```

When users edit pipeline via UI, In advanced configurations there's a notification section.
Users can choose one or multiple notifiers from the notifiers list of the cluster.
Users can choose trigger conditions, e.g., notify when the result is "Failed", "Success" or "Changed"
Users can set notification messages. Pipeline variables are available.
