### ISSUE TITLE
[2.0.8] Statefulset Workloads and Pods Volumes in the UI are blank

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15771]
**Rancher versions:** 
rancher/rancher: 2.0.8

Volumes are not visible for Statefulset workloads and pods in the UI with volume claim template which creates persistent volumes. 

**Steps to Reproduce:**
Deploy statefulset workload with volume claim template. Navigate to the workload in the UI and expand the volumes section and it is blank. Navigate down to the specific pod and the volumes section is blank as well.

![screen shot 2018-09-21 at 2 29 58 pm](https://user-images.githubusercontent.com/4107699/45902053-daef3580-bdaa-11e8-8385-c416efe1442f.png)

**Comment by mitchellmaler** [comment]
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio-prod
spec:
  serviceName: minio-internal
  replicas: 6
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        envFrom:
        - secretRef:
            name: minio-secret
        image: minio/minio:RELEASE.2018-09-12T18-49-56Z
        args:
        - server
        - http://minio-0.minio-internal.minio-prod.svc.cluster.local/data/
        - http://minio-1.minio-internal.minio-prod.svc.cluster.local/data/
        - http://minio-2.minio-internal.minio-prod.svc.cluster.local/data/
        - http://minio-3.minio-internal.minio-prod.svc.cluster.local/data/
        - http://minio-4.minio-internal.minio-prod.svc.cluster.local/data/
        - http://minio-5.minio-internal.minio-prod.svc.cluster.local/data/
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100GB
      storageClassName: default
```
