### ISSUE TITLE
After host reboot dependent services are not started in the correct order

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#15799]
**Rancher versions:**
v1.6.21
**rancher/agent or rancher/rancher-agent:**
rancher/agent:v1.2.11

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.5 LTS  4.4.0-134-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create a new Cattle environment with a single node
2. Create a user stack from the following docker-compose file:
```yaml
version: '2'
services:
  main-app:
    image: nginx
    links:
    - dependency-1
    - dependency-2
    - dependency-3
   dependency-1:
    image: redis
    links:
    - dependency-2
    - dependency-3
  dependency-2:
    image: redis
  dependency-3:
    image: redis
```
3. Restart the environment node, ie. `sudo shutdown -r now`
4. Check the timestamp for when each container was started after the reboot, e.g.:
`$ docker inspect -f '{{.Name}} {{.State.StartedAt}}' $(docker ps -q)`

**Expected Results:**

When the host is restarted, the services should be (re-) started in the following order (as imposed by links):

1. dependency-2 / dependency-3
2. dependency-1
3. main-app

**Actual Results:**
Only during initial deployment the services are started according to links dependencies.
But on host reboot, the services were (re-) started in "random" order:

1. dependency-1
2. dependency-2 / dependency-3
3. main-app
