### ISSUE TITLE
Workload update: send empty map on update only when the field is set on existing resource

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15863]
UI currently sends capAdd/capDrop[] as empty arrays on workload update, no matter whether the field is set on the existing object. It results in buggy behavior when resource is created via api/cli, and these fields are not set on creation. Then when on the update they are passed in, it results in pod spec modification and all workload's pods recreation.

it can be done as a generic UI fix for all updates/resources, or we can scope it to capAdd/capDrop for now, and revise the rest later.

More context can be found here: https://github.com/rancher/rancher/issues/15844

**Comment by alena1108** [comment]
Steps to reproduce:

* create workload using kubectl 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
```
* in the UI, scale i up using +. The containers get recreated
