### ISSUE TITLE
run Hadoop need  build pvc ？

### ISSUE THREAD

**Issue by jingslunt** [rancher/rancher#15874]
```
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: hadoop-vcthb-hadoop-hdfs-dn
      namespace: hadoop-vcthb
    spec:
      storageClassName: "nfs"
      accessModes:
        - ReadWriteOnce
        - ReadWriteMany
        - ReadOnlyMany
      resources:
        requests:
          storage: 500Mi
```
