### ISSUE TITLE
k8s 1.12 support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15872]
Add k8s 1.12 as support k8s version for RKE. Evaluate that:

* k8s cluster gets launched w/o errors
* existing system services working with newer version of k8s. Figure out what needs to be upgraded
* upgrade from previous version to k8s 1.12 works

Can be first tested on rke standalone, and then full rancher-to-rke path

**Comment by maxkorp** [comment]
By my testing, this is working

To provision a kubernetes 1.12 cluster, I used the following config

```
nodes:
    - address: xxx.xxx.xxx.xxx
      internal_address: xxx.xxx.xxx.xxx
      user: ubuntu
      role:
        - controlplane
        - etcd
      ssh_key_path: /Users/maxkorp/.ssh/x2.pem
    - address: xxx.xxx.xxx.xxx
      internal_address: xxx.xxx.xxx.xxx
      user: ubuntu
      role:
        - worker
      ssh_key_path: /Users/maxkorp/.ssh/x.pem
    - address: xxx.xxx.xxx.xxx
      internal_address: xxx.xxx.xxx.xxx
      user: ubuntu
      role:
        - worker
      ssh_key_path: /Users/maxkorp/.ssh/x.pem
kubernetes_version: "v1.12.0-rancher1-1"
ignore_docker_version: true
```

To test upgrading, I removed `kubernetes_version`, deployed a new cluster and workloads, and then re-added `kubernetes_version` and reupped. 

In the UI I simply selected the appropriate version under cluster options.
