### ISSUE TITLE
Link not established with sidekicked container

### ISSUE THREAD

**Issue by EliSnow** [rancher/rancher#1589]
Rancher: v0.28.0
Cattle: v0.64.0
Rancher-compose: v0.22.0

With the following `docker-compose.yml`:

```yml
test-apache:
  ports:
  - 80:80/tcp
  restart: on-failure:5
  tty: true
  image: debian:jessie
  links:
  - test-node:node
  stdin_open: true
test-node:
  restart: on-failure:5
  tty: true
  image: debian:jessie
  stdin_open: true
  labels:
    io.rancher.sidekicks: test-apache
```
Container `test-apache` is not getting a link to `test-node`.
