### ISSUE TITLE
Container with port 22 open publicly and port 22 internally cause's ssh no longer to work for the host it on

### ISSUE THREAD

**Issue by chris-hill1990** [rancher/rancher#15890]
**Rancher versions:**
rancher/server or rancher/rancher: v1.6.15
rancher/agent or rancher/rancher-agent: rancher/agent:v1.2.10 

**Infrastructure Stack versions:**
healthcheck:
rancher/healthcheck:v0.3.6
ipsec:
rancher/net:holder
rancher/net:v0.13.11
network-services:
rancher/network-manager:v0.7.20
rancher/metadata:v0.10.2
scheduler:
rancher/scheduler:v0.8.3
kubernetes (if applicable):

**Docker version: (`docker version 2 `,`docker info` preferred)**
version: '2' (docker)
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.2.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.2.0
PRETTY_NAME="RancherOS v1.2.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
docker compose file 
```
version: '2'
services:
  worker:
    image: **Image that has ssh open and running diffrent key than the host**
    stdin_open: true
    tty: true
    ports:
    - 22:22/tcp
```

This configuration appears to take port 22 from the host and stoped the admin from ssh'ing in to the host . 
**Results:**
