### ISSUE TITLE
UI - Not able to show the mounted volumes from other containers

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1595]
Build from master:
I used the following rancher compose to create services with data volumes:

```
root@sangee01:/home/sangeethahariharan1/test1/rancher-compose-v0.2.1# cat docker-compose-dv.yml 
client:
  labels:
    io.rancher.sidekicks: vol
  image: sangeetha/testclient:latest
  volumes_from:
  - vol
vol:
  image: sangeetha/testlbsd:latest
root@sangee01:/home/sangeethahariharan1/test1/rancher-compose-v0.2.1# cat rancher-compose-dv.yml
client:
  scale: 2
vol:
  scale: 2
root@sangee01:/home/sangeethahariharan1/test1/rancher-compose-v0.2.1# 
```
Containers of "client" service gets created with data Volumes mounted from  containers from "vol" service. Detailed view of the container does not show the volumes mounted.

API shows - "dataVolumesFrom": [
"1i164",
],

<img width="1105" alt="screen shot 2015-07-20 at 6 17 24 pm" src="https://cloud.githubusercontent.com/assets/4266958/8791141/b2d7d27c-2f0b-11e5-916a-773a4079e13c.png">
