### ISSUE TITLE
k8s 1.12 doesn't work with flannel

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#15955]
Flannel network doesn't work on RKE provisioned clusters having k8s 1.12

https://github.com/rancher/rke/issues/936
kubernetes/kubernetes#69220
coreos/flannel#1044

**Comment by ReSearchITEng** [comment]
For anyone willing to test the flannel fix for 1.12 , 
`kubeadm -n kube-system apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml`

**Comment by bootc** [comment]
I applied the change manually, replacing the `spec.template.spec.tolerations` in the `kube-flannel` DaemonSet with:

```
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        operator: Exists
```

This made my new node spring to life.
