### ISSUE TITLE
Problems with data container re-use

### ISSUE THREAD

**Issue by dennybritz** [rancher/rancher#1596]
I have a service defined as follows:

```yaml
wordpress:
  stdin_open: true
  tty: true
  image: wordpress
  links:
    - db:mysql
  labels:
    io.rancher.sidekicks: datawp
  volumes_from:
    - datawp

datawp:
  image: wordpress
  stdin_open: true
  command: cat
  volumes:
    - /var/www/html
```

When the wordpress container crashes (SIGKILL) the data container crashes with it. When the service is restarted the data container is created again, not re-using the previous volume and thus losing the data. It works fine if I restart the service manually, then the same data container is re-used.

Is this perhaps related to the fact that data containers must be running when being part of a service? If the data container is allowed to be in a stopped state then it can't crash.
