### ISSUE TITLE
Elasticsearch index created by logging is lowercased

### ISSUE THREAD

**Issue by naisanza** [rancher/rancher#16009]
**Rancher versions:**
```
Rancher | v2.1.0
User Interface | v2.0.77
Helm | v2.10.0-rancher4
Machine | v0.15.0-rancher1-1
```

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 91
 Running: 75
 Paused: 0
 Stopped: 16
Images: 32
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 392
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 17.63GiB
Name: bigma
ID: UWKU:2Q36:44LW:HH6M:5DI3:YERH:WHCZ:YT5X:LDP2:QP4F:7Y4W:BHS2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.15.0-36-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
baremetal
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
single node rancher
internal DB
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.11.3-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  options: 
    flannel_backend_type: "vxlan"
  plugin: "canal"
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet: 
    extra_args: 
      max-pods: "512"
    fail_swap_on: false
ssh_agent_auth: false
```

**Steps to Reproduce:**
1. Deploy elasticsearch
2. Copy container IP (because internal-cluster-dns doesn't work with vanilla Rancher 2.x)
3. Enable elasticsearch logging
4. Paste elasticsearch container IP
5. View elasticsearch indexes

**Results:**

When setting up Rancher logging to Elasticsearch, it says the generated index will be `innovations_Default-2018-10-02`, however, the actual index created in elasticsearch is `innovations_default-2018-10-02`

The index is all lower-cased
