### ISSUE TITLE
Wrong octal values in secret defaultMode in Helm chart

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16023]
```
Error: release rancher failed: Deployment.apps "rancher" is invalid: [spec.template.spec.volumes[0].secret.defaultMode: Invalid value: 750: must be a number between 0 and 0777 (octal), both inclusive, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "tls-ca-volume"]
```

Must be 0750 but can be changed to 0400 for both as we only need to read from it.

**Comment by terribleplan** [comment]
This is urgent and is preventing us (and anyone using `privateCA`) from deploying rancher. Can we get this merged ASAP?

**Comment by jepp2078** [comment]
You can use kubectl to edit the rancher deployment yourself.

Run the helm chart without --privateCA, then manually edit the deployment and add the following:

```
      containers:
        volumeMounts:
        - mountPath: /etc/rancher/ssl
          name: tls-ca-volume
          readOnly: true
```

```      
    spec:
      volumes:
      - name: tls-ca-volume
        secret:
          defaultMode: 450
          secretName: tls-ca
```
