### ISSUE TITLE
Catalog integration in Pipeline

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16026]
- [ ] Publish Catalog Template Step: 
  - users select a catalog,
  - users put a chart directory in the source code repository,
  - variable substituion available in the chart files,
  - users provide git deploy key via secrets,
  - as the result, a new version of the catalog template will be added in catalog repository.
  - example yaml would be:
    ```
    steps:
    - publishCatalogConfig:
        path: <path-to-chart-directory>
        catalog: <catalog name/id>
        version: <version-to-publish>
      envFrom:
        sourceName: my-secret
        sourceKey: deploy-key
        targetKey: ALIAS_ENV
    ```
- [ ] Apply Catalog App Step:
  - users select a catalog,
  - users fill in answers, like how they do deploying an app,
  - variable substitution available in the answers,
  - example yaml would be:
    ```
    steps:
    - applyCatalogConfig:
        catalog: <catalog name/id>
        version: <version-to-publish>
        name: <name>
        targetNamespace: <ns>
    ```

**Comment by gitlawr** [comment]
- [ ] Publish Catalog Template Step: 
  - users provide git deploy key via secrets,
  - users put a chart directory in the source code repository,
  - variable substituion available in the chart files.
  - example yaml would be:
    ```
    steps:
    - publishCatalogConfig:
        path: <path-to-chart-directory>
        catalog: <catalog name/id>
        version: <version-to-publish>
      envFrom:
        sourceName: my-secret
        sourceKey: deploy-key
        targetKey: DEPLOY_KEY
    ```
  - as the result, a new version of the catalog template will be added in catalog repository.
- [ ] Apply Catalog App Step:
  - users select catalog
  - users fill in answers, like how they do deploying an app.
  - variable substitution available in the answers.
  - example yaml would be:
    ```
    steps:
    - applyCatalogConfig:
        catalog: <catalog name/id>
        version: <version-to-publish>
        name: <name>
        targetNamespace: <ns>
    ```
