### ISSUE TITLE
Rancher brokened after upgrade the autosacler 

### ISSUE THREAD

**Issue by hanyan007** [rancher/rancher#16072]
rancher version :2.0.8 
5 nodes(3 all, 2 workser Role)
Docker version 1.13.1

Dear Rancher，
I configure the autosacler follow the website： “https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/"

Then my cluster of custom kubernetes was broken.
like this：

**This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.
 [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [192.168.10.15]: Get https://localhost:6443/healthz: dial tcp [::1]:6443: connect: connection refused, log:**

**the host 192.168.10.15：
fb72e43eb680        rancher/hyperkube:v1.11.3-rancher1                                                                         "/opt/rke-tools/en..."   15 hours ago        Restarting (1) About a minute ago                       kube-apiserver**

other nodes's  kube-apiserver are “Restarting”  of status too.

I try to recover it , but failed. some services are brokened too. 
so i delete all the nodes,  and upgrade the rancher to **v2.1.0,** then try configure autosacler,upgrade again
but the problem still happened.

the default configuration：
```
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet: 
    fail_swap_on: false
ssh_agent_auth: false
```

I upgrade like this：
```
services: 
  etcd: 
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    snapshot: false
  kube-api: 
    extra_args: 
      pod_security_policy: "false"
      requestheader-client-ca-file: "/etc/kubernetes/ssl/kube-ca.pem"
      service_node_port_range: "30000-32767"
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kube-controller: 
    extra_args: 
      horizontal-pod-autoscaler-downscale-delay: "5m0s"
      horizontal-pod-autoscaler-sync-period: "30s"
      horizontal-pod-autoscaler-upscale-delay: "1m0s"
  kubelet: 
    extra_args: 
      read-only-port: "10255"
    fail_swap_on: false
ssh_agent_auth: false

```
Now i have no idea.
Please give me some advice.
Thanks & Regards
