### ISSUE TITLE
Linked containers running on different hosts cannot ping

### ISSUE THREAD

**Issue by anapsix** [rancher/rancher#1608]
> TLDR;
cross-host network is not working

I've got a simple 2-3 component service, consisting of redis instance, webdis instance and an optional load balancer.

Here is my `docker-compose.yml`:
```
haproxy:
  image: 'tutum/haproxy:0.1'
  environment:
    - BACKEND_PORT=7379
  links:
    - 'webdis'
  ports:
    - '8000:80'
    - '1936:1936'
webdis:
  image: 'anapsix/webdis'
  ports:
   - '7379:7379'
  links:
   - 'redis'
redis:
  image: 'anapsix/redis:latest'
```
I start service up with `rancher-compose up`, which is reflected in Rancher Web-UI.
![image](https://cloud.githubusercontent.com/assets/1256199/8827188/1f293954-3059-11e5-95ca-4f221622bd92.png)
However, it appears that `webdis` instance cannot talk to `redis` instance (and `haproxy` cannot connect to `webdis` as well) even though the containers are linked.  
Hostname `redis` is properly resolvable from withing `webdis`, but pings fail.
```
### webdis container
/ # ip a s eth0                                                                 
23: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:96:4a:73:08:55 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.7/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.42.14.165/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::96:4aff:fe73:855/64 scope link
       valid_lft forever preferred_lft forever

/ # ping -c 4 redis
PING redis (10.42.247.116): 56 data bytes
--- redis ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```
Yet `haproxy` container, that runs on the same host can ping `redis`, though I have to use the IP, since `redis` is not linked to `haproxy`.
```
### haproxy container                                                          
/ # ip a s eth0                                                
23: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:96:4a:19:f2:2f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.7/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.42.168.239/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::96:4aff:fe19:f22f/64 scope link
       valid_lft forever preferred_lft forever

/ # ping -c 4 10.42.247.116
PING 10.42.247.116 (10.42.247.116) 56(84) bytes of data.
64 bytes from 10.42.247.116: icmp_seq=1 ttl=64 time=0.106 ms
64 bytes from 10.42.247.116: icmp_seq=2 ttl=64 time=0.074 ms
64 bytes from 10.42.247.116: icmp_seq=3 ttl=64 time=0.079 ms
64 bytes from 10.42.247.116: icmp_seq=4 ttl=64 time=0.054 ms
--- 10.42.247.116 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2999ms
```

## environment
Rancher and RancherOS on bare metal
```
RancherOS v0.3.3
rancher/agent-instance:v0.3.1
rancher/agent:v0.7.9
CATTLE_RANCHER_SERVER_IMAGE=v0.25.0
CATTLE_CATTLE_VERSION=v0.58.0
```

**Comment by Kelindar** [comment]
I have the same issue across cloud providers on VMs (GCE & AWS) while IPSEC UDP ports ```500``` and  ```4500``` are allowed to  ```0.0.0.0/0```, but haven't had time to investigate further yet. Funny enough, it seems to work inside 3 hosts in GCE but doesn't reach AWS.

**Comment by anapsix** [comment]
@Kelindar I'm running it on two physical hosts in a rack next to each other.. No extra firewall rules.. So, not really sure what's up

**Comment by Kelindar** [comment]
Just got the same issue again with 3 hosts on GCE, running ```rancher v0.30.0-rc2```

```
Messaging:
  ports:
  - 4000:4000/tcp
  - 4001:4001/tcp
  - 8082:8082/tcp
  restart: always
  environment:
    GNATS_LOG: 'true'
  domainname: ''
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  hostname: messaging
  image: emitter/bus
  privileged: true
  stdin_open: true
```
