### ISSUE TITLE
Rancher V2 HA Restoration Guide

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#16104]
I had the dubious pleasure of having to change away from the rke addons system to the helm based distro to ensure we can upgrade later on. During which I thought now would be a good idea to see how hard it would be to pop-up a new cluster and test disaster recovery.

Which is where I come to a sticky end; either the guide's out of sync or I've somehow, between flipping between sections, lost my place.

(for reference) https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/

So I start off on this restoration adventure by (as the first step states) creating a fresh cluster following the normal instructions.

So download RKE; and create a rancher-cluster.yml file ala
```
nodes:
  - address: 172.11.11.207 # hostname or IP to access nodes
    user: user
    role: [controlplane, worker, etcd] # K8s roles for node
    ssh_key_path: ./rk8_rsa # path to PEM file
  - address: 172.11.11.206
    user: user
    role: [controlplane, worker, etcd]
    ssh_key_path: ./rk8_rsa
  - address: 172.11.11.205
    user: user
    role: [controlplane, worker, etcd]
    ssh_key_path: ./rk8_rsa

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```

Which is similar to the old one minus the addons section which is gone after 2.0.8.

Run `rke up --config ./rancher-cluster.yml`, logs fly up the screen everything says healthy etc.

Run all the helm commands

```
kubectl --kubeconfig=kube_config_cluster.yml -n kube-system create serviceaccount tiller
kubectl --kubeconfig=kube_config_cluster.yml create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm --kubeconfig=kube_config_cluster.yml init --service-account tiller

helm --kubeconfig=kube_config_cluster.yml repo add rancher-stable https://releases.rancher.com/server-charts/stable

helm --kubeconfig=kube_config_cluster.yml install stable/cert-manager --name cert-manager --namespace kube-system
helm --kubeconfig=kube_config_cluster.yml install rancher-stable/rancher --name rancher  --namespace cattle-system --set hostname=pointlessdomain.com
```

Quick check
```
λ kubectl --kubeconfig=kube_config_cluster.yml get nodes
NAME            STATUS    ROLES                      AGE       VERSION
172.11.11.205   Ready     controlplane,etcd,worker   3m        v1.11.3
172.11.11.206   Ready     controlplane,etcd,worker   3m        v1.11.3
172.11.11.207   Ready     controlplane,etcd,worker   2h        v1.11.3

λ kubectl --kubeconfig=kube_config_cluster.yml get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
cattle-system   rancher-7bf74f957b-5kl8p                  1/1       Running     1          1m
cattle-system   rancher-7bf74f957b-bmhgc                  1/1       Running     1          1m
cattle-system   rancher-7bf74f957b-vxtb9                  1/1       Running     1          1m
ingress-nginx   default-http-backend-797c5bc547-782br     1/1       Running     0          4m
ingress-nginx   nginx-ingress-controller-7jpn7            1/1       Running     0          4m
ingress-nginx   nginx-ingress-controller-9zglh            1/1       Running     0          4m
ingress-nginx   nginx-ingress-controller-gg2rr            1/1       Running     0          4m
kube-system     canal-8sr67                               3/3       Running     0          4m
kube-system     canal-fljs4                               3/3       Running     0          4m
kube-system     canal-r4fll                               3/3       Running     0          4m
kube-system     cert-manager-74557675cb-rjgml             1/1       Running     0          1m
kube-system     kube-dns-7588d5b5f5-9pmkr                 3/3       Running     0          4m
kube-system     kube-dns-autoscaler-5db9bbb766-sjdgm      1/1       Running     0          4m
kube-system     metrics-server-97bc649d5-cjnv4            1/1       Running     0          4m
kube-system     rke-ingress-controller-deploy-job-xtxzq   0/1       Completed   0          4m
kube-system     rke-kubedns-addon-deploy-job-xtqr8        0/1       Completed   0          4m
kube-system     rke-metrics-addon-deploy-job-b4tlh        0/1       Completed   0          4m
kube-system     rke-network-plugin-deploy-job-kms2w       0/1       Completed   0          4m
kube-system     tiller-deploy-57f988f854-7s66n            1/1       Running     0          1m
```

(I was happy without an ingress on the rancher cluster; we run external lbs/frontend servers, this stuffs just in the way, but seems the only choice now and extra faf around tls which i'd normally terminate at the edge so IDS can do its job)

Now in the docs it says comment out all but 1 node. 

```
nodes:
  - address: 172.11.11.207 # hostname or IP to access nodes
    user: user
    role: [controlplane, worker, etcd] # K8s roles for node
    ssh_key_path: ./rk8_rsa # path to PEM file

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge
```

Then shove the etcd backup up and cluster certs gz file.
Then...
`rke etcd snapshot-restore --name snapshot.db --config ./kube_config_cluster.yml`
(yes i called the backup file snapshot.db so all the files exist appropriately) 
Here we fail

```
λ rke etcd snapshot-restore --name snapshot.db --config ./kube_config_cluster.yml
INFO[0000] Starting restoring snapshot on etcd hosts
FATA[0000] Failed to validate cluster: Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config
```

If I don't run the helm steps and restore etcd, that works as far as restoring etcd via rke goes but then there were other issues. I'm assuming that the documents either miss out an instruction (like step 1, install your cluster using RKE but skip the helm step) or there's something I'm missing.
