### ISSUE TITLE
Ingress doesn't launch when using restricted PSP as cluster default

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#16119]
**Rancher versions:**
rancher/rancher: **v2.1.0**

Steps to Reproduce:
1. Deploy a custom cluster from UI
2. Specify Pod Security Policy > restricted

**Results:**
The nginx ingress controller pods are not created due to the restriction of the pod security policy. My concern is that the default restricted pod security policy should probably allow all of the rancher components to work by default.

```
FailedCreate | Error creating: pods "nginx-ingress-controller-" is forbidden: 
unable to validate against any pod security policy: [spec.securityContext.hostNetwork: 

Invalid value: true: Host network is not allowed to be used 
capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added

spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 80: 

Host port 80 is not allowed to be used. Allowed ports: []
spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 443: 

Host port 443 is not allowed to be used. Allowed ports: []]
```

Workaround add new pod security policy or modify the restricted one to allow the following:
```
Host Network: Yes: The use of host networking
Allowed Capabilities: NET_BIND_SERVICE
Host Ports Policy: range 80 - 80, 443 - 443
```

**Comment by RonWilliams** [comment]
@massimo-cannavo I tested this issue by deleting the worker node (removing the entire VM) and rebuilding. While using the pod security policy "unrestricted", the ingress container fails to start. I assume that the unrestricted security policy includes NET_BIND_SERVICE.

**Comment by massimo-cannavo** [comment]
https://github.com/kubernetes/ingress-nginx/issues/2783

**Comment by massimo-cannavo** [comment]
https://github.com/rancher/rancher/issues/15163

**Comment by massimo-cannavo** [comment]
https://github.com/kubernetes/ingress-nginx/issues/2855#issuecomment-413887032

```
Host Network: Yes: The use of host networking
Allowed Capabilities: NET_BIND_SERVICE
Host Ports Policy: range 8080 - 8080, 8443 - 8443
```

```
containers:
   - args:
      - /nginx-ingress-controller
      - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
      - --configmap=$(POD_NAMESPACE)/nginx-configuration
      - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
      - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
      - --annotations-prefix=nginx.ingress.kubernetes.io
      - --http-port=8080
      - --https-port=8443
```

```
ports:
  - containerPort: 8080
     hostPort: 8080
     name: http
     protocol: TCP
  - containerPort: 8443
     hostPort: 8443
     name: https
     protocol: TCP
```

**Comment by massimo-cannavo** [comment]
Refer to https://github.com/rancher/rancher/issues/16215

**Comment by jgreat** [comment]
I can confirm this is still an issue as of v2.1.5.

`ingress-controller` pods are unable to launch if you apply the `restricted` PSP as cluster default. Looks like the `unrestricted` PSP is not applied to the entire `System` project.

**Expected behavior:**
When enabling PSP for a cluster, all namespaces in System project should get the `unrestricted` PSP role bound to the default service account.

**Steps to reproduce (least amount of steps as possible):**

1. When creating a cluster, in advanced options turn on PSP and set the default policy to `restricted`.
1. Cluster will create, but pods in the `ingress-nginx` namespace under the `System` project will never schedule.

**Result:**
Ingress controller never starts.

**Other details that may be helpful:**
Work around: Edit System project, change PSP from None to unrestricted, redeploy `nginx-ingress-controller` deployment.

**Comment by spaelling** [comment]
Added this just before the `deployment`

```yaml
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-nginx.psp-role
  namespace: ingress-nginx  
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ingress-nginx.psp-rolebinding
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx.psp-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: nginx-ingress-serviceaccount
  namespace: ingress-nginx

---
```

Then it works. Not the prettiest, but I gave up customizing a PSP that works specifically for the ingress controller. Still a K8S n00b.

**Comment by cjreyn** [comment]
+1 for fix on this!

**Comment by dehotot** [comment]
+1 for a fix on this too; it's blocking our deployment of RBAC'ed user clusters.

**Comment by dehotot** [comment]
+1 on this; perhaps it's linked to https://github.com/rancher/rke/issues/1474 ?

**Comment by piwi91** [comment]
The default PSP created by RKE is:
```
kubectl -n ingress-nginx apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-psp-role
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
EOF

kubectl -n ingress-nginx apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-psp-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
EOF
```

You practically disable PSP when you add this binding ;)
