### ISSUE TITLE
websocket loadbalancer in rancher 2

### ISSUE THREAD

**Issue by phynias** [rancher/rancher#16120]
*Describe your issue here*
trying to setup a loadbalancer that handles websocket connections.
i found this here https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket that says i need to add the nginx.org/websocket-services

i have this

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-bx6l7
    nginx.org/websocket-services: "ingress-c23208ea53658536dee0635661bb5c70"
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: api-lb
  selfLink: /apis/extensions/v1beta1/namespaces/api-prod/ingresses/api-lb
spec:
  rules:
  - host: api.ex.com
    http:
      paths:
      - backend:
          serviceName: ingress-29912bbd006fbb007344881760703048
          servicePort: 8080
  - host: io.ex.com
    http:
      paths:
      - backend:
          serviceName: ingress-2f89ea549e2a6098baafdd95f4f714b8
          servicePort: 4747
  - host: mqtt.ex.com
    http:
      paths:
      - backend:
          serviceName: ingress-c23208ea53658536dee0635661bb5c70
          servicePort: 3738
status:
  loadBalancer: {}

```

i have also tried "api-prod:ingress-c23208ea53658536dee0635661bb5c70" for nginx.org/websocket-services. neither seems to work. has anyone else gotten websockets to work in the rancher2 lb?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.0` UI: `v2.0.77` |
|Route|`ingresses.index`|
