### ISSUE TITLE
Container name have been changed to service name when upgrade

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#16143]
**Rancher versions:**
rancher/server or rancher/rancher: master 10/15
rancher/agent or rancher/rancher-agent: master 10/15

**Steps to Reproduce:**
1. Import a yaml which container name is different from service name.
2. Edit this workload and click upgrade.

Here is a example yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingress-test
    spec:
      containers:
      - image: nginx  
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-test
  name: ingress-test
spec:
  ports:
  - name: service0
    port: 8080             
    protocol: TCP
    targetPort: 8080     
  - name: service1
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ingress-test
  type:  NodePort
```

**Results:**
Container name has been changed to the service name.
