### ISSUE TITLE
There is no indication at the cluster level when add_on jobs fail to deploy.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16164]
**Rancher versions:** v2.1.1-rc4
**Steps to Reproduce:**
Create a RKE cluster with  following configurations for ingress .
```
ingress: 
  extra_args: 
    default-backend-service: "ingress-nginx/pretty-error"
  options: 
    custom-http-errors: "404"
  provider: "nginx"
```
rke-ingress-controller addons not being able to start successfully because of issue - https://github.com/rancher/rke/issues/962

In this case cluster gets to "Active" state and there is no indication that Ingress add on failed to start successfully.

The only place where this error is presented is in the "Workloads" view in "System" project.

It would be good to show some indication at the cluster level when add_on jobs fail to deploy.
