### ISSUE TITLE
Ability to create global roles and setting them as a default

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#16216]
We are trying to setup the global user role so that user cannot create a cluster. I tried setting the default user to User Base just so they can log in and it seemed to work. The issue is now if this AD user tries to add a new Member to a project (cause they were added as a Project Owner) they cannot list any users and each AD user already added has an error. 

My goal is to give the user as minimum of access when the log in the first time but then can request access from either an Admin or Project/Cluster Owner to be added.

![2018-10-19 22_31_48-rancher](https://user-images.githubusercontent.com/4107699/47250849-e9069500-d3ee-11e8-9894-83507c073e45.png)

**Comment by mitchellmaler** [comment]
The main issue is I cannot customize or create any new global roles.

**Comment by loganhz** [comment]
I can reproduce this issue in master

Steps to reproduce:

1. Go to global role page and make `User Base` role as default role. And make the `User` role to non-default role.
2. Create two users `user1` and `user2` with custom global permission `Login` only.
3. Assign `user1` to `Default` project with `Project owner` role.
4. Login as `user1` and try to add `user2` as a `Project Member`

Results:

`user1` can not find `user2` when try to search and find it.
Also it shows an error for fetching the the default admin user info in project member page.

![image](https://user-images.githubusercontent.com/21168270/47263166-bf548780-d52e-11e8-92eb-784a6f7a3a35.png)

Expected:

`user1` should be able to add `user2` as a `Project Member` as `user1` is a `Project Owner`
Also, `user1` should be able to see the user info for all users in the project instead of seeing an error with `Unable to fetch user info`

**Comment by cjellick** [comment]
@loganhz the Login role (aka User Base) behaving as expected. It is extremely limited permissions and we intend for someone with only that role to not be able to see/search other users.

@mitchellmaler to accomplish what you want, you basically need the ability to create a new global role. We don't let you edit the built-in ones because we need to keep those in-sync and in-line with what Rancher expects.
When we originally design this Global Roles feature, we intentionally locked them down to prevent admins from creating new ones. Our thinking/motivation was to prevent users from shooting themselves in the foot and that there should be no need to customize them.
I think this was wrong and I think we should/will open it up so that you can create new global roles. We will probably give you the ability to clone an existing one, so that you can basically clone the User role and remove whatever permissions you don't want in it.

But, no one is actively working on this feature yet.  To work around it, you can use kubectl pointed at the kubernetes where rancher server is running to directly create a new global role. Meaning, you can basically do the clone yourself following these steps:
```
# First, get the yaml for the existing user role
kubectl get globalroles user -o yaml >custom-user.yaml

# Make modifications. Clear out all but the "name" field from the metadata section, change the name and adjust the rules as you see fit (in your case, delete the rule for cluster creation*
vim custom-user.yaml

# Create the new role
kubectl create -f custom-user.yaml

# Make sure you disable the built-in user role from being a "New User Default"
```

 * Here's a yaml file that defines a role called new-user that is the same as the user role but without the rule for creating clusters. So you could just copy this down and use `kubectl create -f`
```
apiVersion: management.cattle.io/v3
description: ""
displayName: Custom User
kind: GlobalRole
metadata:
  name: custom-user
newUserDefault: true
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - principals
  - roletemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - preferences
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - templates
  - templateversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - nodedrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - podsecuritypolicytemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - nodetemplates
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - sourcecodecredentials
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - sourcecoderepositories
  verbs:
  - '*'
```
