### ISSUE TITLE
[server-chart] Custom annotations for ingress. 

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#16278]
rancher/server-chart#43 covers the changes for this enhancement.

Ability to add arbitrary annotations to customize the ingress. 

Some ways this could be used:

* Customize cert-manager actions (use a `cluster-issuer` or custom `issuer`)
* Support other ingress controllers beside nginx.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.1.1
- Installation option (single install/HA): HA server-chart

**Comment by bmdepesa** [comment]
rancher/server-chart:master

Deployed Rancher in HA w/ additional set option: 
```
--set 'ingress.extraAnnotations.nginx\.ingress\.kubernetes\.io/limit-connections=5'
```

Checked the ingress: `kubectl get ingress rancher -n cattle-system -o yaml`
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: rancher
    field.cattle.io/publicEndpoints: '[{"addresses":["13.57.215.250","13.57.42.103","54.193.41.180"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"brandonha.qa.rancher.space","allNodes":false}]'
    nginx.ingress.kubernetes.io/limit-connections: "5"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
```
