### ISSUE TITLE
Flannel uses internal IP for VXLAN where external IP should be used

### ISSUE THREAD

**Issue by blattersturm** [rancher/rancher#16295]
I've set up a cluster using Flannel as network backend on Scaleway. As the eth0 interface of each VM on Scaleway uses an internal IP, I configured the external IP manually.

However, checking `tcpdump -i eth0 port 8472`, I see that nodes are trying to talk to one another using their internal IPs, which, for the lack of routing tables, leads to nowhere. I've not entered any custom internal IP at all; only an external IP, which shows properly, and all nodes seemingly registered correctly as well.

How can I manage to use the external IP for the VXLAN traffic, instead of using the (unreachable) internal IP?

**Comment by blattersturm** [comment]
It seems that `flannel.alpha.coreos.com/public-ip` annotation is set to internal IP. How can this be different?

**Comment by blattersturm** [comment]
Also, it seems kube-apiserver is advertising itself as a service using the internal IP, leading to timeouts when random routing routes 10.43.0.1 to an external kube-apiserver instance, and not the local one. 😕

**Comment by loganhz** [comment]
@blattersturm By setting the `flannel_iface`, you can configure the interface to use for inter-host communication.

https://rancher.com/docs/rke/v0.1.x/en/config-options/add-ons/network-plugins/#flannel-network-plug-in-options

**Comment by micw** [comment]
@loganhz actually this is not working on rancher. you need to set network.flanel_cloud_provider.iface to the interface instead. I found this in some issues but in no official documentation.
At least it's documented on the yaml if you create a new cluster in rancher and click "edit as yaml".

**Comment by bithavoc** [comment]
@micw where do you set that?

like this?
```
network: 
  options: 
    flannel_backend_type: "vxlan"
    flannel_iface: "enp0s8"
  flanel_cloud_provider:
    iface: "enp0s8"
  plugin: "canal"
```

is not working :/

**Comment by bithavoc** [comment]
This doesn't work either:
```
network: 
  options: 
    canal_flannel_backend_type: "vxlan"
    canal_iface: "enp0s8"
  plugin: "canal"
```

```
flannel.alpha.coreos.com/public-ip | 10.0.2.15
rke.cattle.io/external-ip | 172.28.128.11
rke.cattle.io/internal-ip | 172.28.128.11
```

When running `Custom` and I use `--address enp0s8 --internal-address enp0s8`, it should pick the same interface for Canal/Flannel.

This is specially frustrating in Vagrant where is impossible to disable nat and the first interface is a NAT with host only(`10.0.2.15`) and the second is the private network which can actually communicates between nodes `172.28.128.11` but ranches doesn't pass the configuration to the CNI config.

**Comment by micw** [comment]
Actually I use:
```
network: 
  plugin: "canal"
  options: 
    flannel_backend_type: "vxlan"
  canal_network_provider: 
    iface: "wg0"
```

That works (canal traffic runs on wg0 which is my internal network).

**Comment by bithavoc** [comment]
@micw that worked in Vagrant, thanks 💪 

```
network: 
  options: 
    flannel_backend_type: "vxlan"
  canal_network_provider:
    iface: "enp0s8"
  plugin: "canal"
```
