### ISSUE TITLE
could not init cloud provider "vsphere": unknown escape sequence

### ISSUE THREAD

**Issue by codekoala** [rancher/rancher#16371]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Begin creating a vSphere new cluster
* Edit YAML to include configuration for vSphere provider that uses a backslash in the username:
```yaml
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      insecure-flag: true
    virtual_center:
      vcenter.tld.com:
        user: "DOMAIN\\user"
        password: "password"
        datacenters: "DC1"
```
* Create the cluster

**Result:**
![image](https://user-images.githubusercontent.com/48698/47736126-5c58a400-dc44-11e8-965e-5d4c64c733c7.png)

`...failed to run Kubelet: could not init cloud provider "vsphere": 10:21 unknown escape sequence`

**Other details that may be helpful:**
* I did try several values for the username, such as `"DOMAIN\user"`. `"DOMAIN\\user"`, `"DOMAIN\\\\user"`, `"DOMAIN/user"`.
* We were able to use `user@domain.site.local` rather than `DOMAIN\user` to get past this error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.0
- RancherOS version: v1.4.2
- Installation option (single install/HA): HA
