### ISSUE TITLE
extends doesn't work with image in the extended file.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1641]
Use this example for `rancher-compose up` and containers never get started.

## Example 1
common.yml:
```
web:
  image: ubuntu:14:04

db:
  image: ubuntu:14:04
```
docker-compose.yml:
```
web:
  extends:
    file: common.yml
    service: web

db:
  extends:
    file: common.yml
    service: db
  links:
    - web:web
```

Containers error and never get started so service is stuck in activating state.

```
0835f712-f62d-41d4-9762-4163c9c58f1d : 'dict' object has no attribute 'dockerImage'
```
