### ISSUE TITLE
Rancher 2.0 Ingress session affinity doesn't work

### ISSUE THREAD

**Issue by maheshacharya** [rancher/rancher#16446]
I can't seem to get Session Affinity to work with Ingress in Rancher. My ingress config is below.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-hash: sha1
    ingress.kubernetes.io/session-cookie-name: route
    kubernetes.io/ingress.class: nginx
  labels:
  name: cms
spec:
  rules:
  - host: rancher-cms.cloud-hub.co
    http:
      paths:/
      - backend:
          serviceName: hippo
          servicePort: 80
```
I expect the Ingress to send the request to the same Pod for a given session, however, it is being sent to any Pod, as a result, JSESSIONID is constantly changing, causing too many Redirects. Without Session Affinity, I won't be able to use Rancher for my deployments -- please help. Thanks in advance.

Versions /Specs of my deployment.
```

Rancher | v2.1.1
User Interface | v2.1.4
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1

```
Ingress details
```
> kubectl describe ingress -n hippo
Name:             cms
Namespace:        hippo
Address:          <IP ADDRESS>,<IP ADDRESS>,<IP ADDRESS>
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                      Path  Backends
  ----                      ----  --------
  rancher-cms.cloud-hub.co
                               hippo:80 (<none>)
Annotations:
  field.cattle.io/publicEndpoints:            [{"addresses":["<IP ADDRESS>"],"port":80,"protocol":"HTTP","serviceName":"hippo:hippo","ingressName":"hippo:cms","hostname":"rancher-cms.cloud-hub.co","allNodes":true}]
  ingress.kubernetes.io/affinity:             cookie
  ingress.kubernetes.io/session-cookie-hash:  sha1
  ingress.kubernetes.io/session-cookie-name:  route
  kubernetes.io/ingress.class:                nginx
  field.cattle.io/ingressState:               {"Y21zL2hpcHBvL3JhbmNoZXItY21zLmNsb3VkLWh1Yi5jby8vODA=":""}
Events:                                       <none>
```
