### ISSUE TITLE
Rancher log shows running in single-server mode when clustered

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#16475]
rancher/rancher:v2.1.2-rc7

Rancher logs are showing that it is running in single server mode, even when it is actually running clustered (HA).

To reproduce: 
* Deploy Rancher via helm with replicas > 1
* Check logs, at beginning of logs `[INFO] Running in single server mode, will not peer connections` is displayed.

Expected:
```
[INFO] Running in clustered mode with ID x.x.x.x, monitoring endpoint cattle-system/rancher
```

Additional information: 
Performed HA tests (leader migration on pod/node deletion) to ensure Rancher was running as a cluster.

Rancher deployment `kubectl get deployment rancher -o wide -n cattle-system` shows `CATTLE_NAMESPACE` and `CATTLE_PEER_SERVICE` are set correctly:
```
    env:
        - name: CATTLE_NAMESPACE
          value: cattle-system
        - name: CATTLE_PEER_SERVICE
          value: rancher
```
