### ISSUE TITLE
Question about cloneStage of Pipeline

### ISSUE THREAD

**Issue by chux0519** [rancher/rancher#16504]
It seems cloneStage is unconfigurable.

Is it possible to use `ssh` instead of `user + token`?

ps: I'm using a private gitlab server, and admin only allow git clone via ssh

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/16136

**Comment by chux0519** [comment]
@loganhz Thank you for your reply, I left a comment under 16136.

Maybe this issue can be closed.

**Comment by gitlawr** [comment]
Let's track it here as the linked issue aims at self-signed-certificate git service integration.

**Comment by gitlawr** [comment]
We are not managing deploy keys for users, so the default clone stage does not clone via ssh.
You can skip the default clone stage and do clone in your own way(inject your deploy key via secrets, and do the clone in an image with git utils)
At the moment, this can be done by claiming and skipping the clone stage explicitly:
```
stages:
- name: clone
  steps:
  - sourceCodeConfig: {}
  when:
    branch: nonexistone
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
timeout: 60
```
This looks hacky though, we would probably provide a `skipClone` option for the purpose.
