### ISSUE TITLE
Ingress controller backend-protocol annotation being ignored

### ISSUE THREAD

**Issue by joraff** [rancher/rancher#16514]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Create ingress object with backend-protocol annotation, such as:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
  - host: my_host
    http:
      paths:
      - backend:
          serviceName: my_service
          servicePort: 443
  tls:
  - hosts:
    - my_host
...
```

**Result:**

nginx.conf file continues to use http as backend protocol despite specifying HTTPS in annotation:
`proxy_pass http://backend_service_upstream`

Expect:
`proxy_pass https://backend_service_upstream`

Ingress controller annotation docs: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/

**Other details that may be helpful:**

**Environment information**
- Rancher 2.1.1, HA, Ingress pods are `rancher/nginx-ingress-controller:0.16.2-rancher1` in a daemonset

I don't have a non-rancher kubernetes cluster using unmodified k8s ingress images, so I can't say that this isn't related to something specifically in the rancher ingress controller fork. Hopefully someone can verify if this also happens in upstream, in which case I'll re-submit to the kubernetes or nginx teams.

Thanks!
