### ISSUE TITLE
Exposed ports are not set when  creating internal LB.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1652]
rancher-server version - v0.30.0-rc2
rancher-compose version v0.2.3-rc1

Exposed ports are not set when  creating internal LB.
Used the following files to create Internal LB:

```
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# cat docker-compose-lb-internal.yml 
lbinternal:
  links:
  - test2:test2
  - test1:test1
  expose:
  - 3430:80
  - 3431:81
  labels:
    io.rancher.loadbalancer.target.test2: def/service3
    io.rancher.loadbalancer.target.test1: abc/service1
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
test1:
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
test2:
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true

# cat rancher-compose-lb-internal.yml 
test1:
  scale: 1
test2:
  scale: 1
lbinternal:
  scale: 1
  load_balancer_config:
    description: testfromrancher
    name: lbinternal config
root@sangee01:/home/sangeethahariharan1/v23/rancher-compose-v0.2.3-rc1# 
```

                                                                                                                                                               |            116 |
| 315 | lbinternal    |          5 | loadBalancerService | 7620eb1f-3846-4796-a5e9-aa9c375ee3f2 | NULL                   | active   | 2015-07-25 00:20:57 | NULL                | NULL                | {"fields":{"scale":1,"launchConfig":{"labels":{"io.rancher.loadbalancer.target.test1":"abc/service1","io.rancher.loadbalancer.target.test2":"def/service3"},"logConfig":{},"networkMode":"managed","stdinOpen":true,"tty":true,"privileged":false,"publishAllPorts":false,"readOnly":false,"startOnCreate":true},"loadBalancerConfig":{"description":"testfromrancher","name":"lbinternal config"}}}                                                                                                                                                                                                                                                                                                                                                       |            116 |
+-----+---------------+------------+---------------------+--------------------------------------+------------------------+----------+---------------------+---------------------+---------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+
