### ISSUE TITLE
Cannot publish 2 images with rancher-pipeline

### ISSUE THREAD

**Issue by AdamRazniewskiISO** [rancher/rancher#16624]
**What kind of request is this :**
Bug

**Steps to reproduce (least amount of steps as possible):**
Make a pipeline with 2 publishimagesteps

```
stages:
- name: test1
  steps:
  - publishImageConfig:
      dockerfilePath: ./server/Dockerfile
      buildContext: ./server
      tag: test/test:1.0
- name: test2
  steps:
  - publishImageConfig:
      dockerfilePath: ./test/Dockerfile
      buildContext: ./test
      tag: test2/test2:1.0
```

**Result:**
Second publish image will have status:
```
11:32:11 [pipeline_p-7pc6h-5] Running shell script
11:32:13 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
11:32:13 + /usr/local/bin/dockerd -g /var/lib/docker
11:33:09 EXITCODE   0time="2018-11-16T11:33:02Z" level=fatal msg="Error authenticating: exit status 1"
```

It's impossible to build 2 images with one pipeline now

**Environment information**
- Rancher version: v2.1.2-rc12
- Installation option (single install/HA): single install

**Comment by gitlawr** [comment]
The cause is that currently the docker daemon storage path is sharing among containers in the build pod, but in docker's design `/var/lib/docker` is intended to be managed by a single daemon.
For muliple publish steps, we can:
1. have multiple independent docker daemon
2. set up dockerd in the first step and share it with the rest publish steps.

We are also investigating having a centralized dockerd in a project for caching purpose.

Workaround in v2.1.1:
You can try the following to bypass the conflict:
```
stages:
- name: test1
  steps:
  - publishImageConfig:
      dockerfilePath: ./server/Dockerfile
      buildContext: ./server
      tag: test/test:1.0
- name: test2
  steps:
  - publishImageConfig:
      dockerfilePath: ./test/Dockerfile
      buildContext: ./test
      tag: test2/test2:1.0
    env:
      PLUGIN_STORAGE_PATH: /var/lib/docker2
```
