### ISSUE TITLE
Host Rancher Charts in repo format

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16672]
We should host the charts of rancher in repo format
Just like we do for HA server-chart `https://releases.rancher.com/server-charts/latest/index.yaml`

We need the same for `github.com/rancher/charts`

As a developer, I am packaging my application using helm and I want to use Rancher's mysql chart.
In `requirements.yaml`, I can't specify repository

```
dependencies:
- name: mysql
  version: 0.3.7
  repository: "https://github.com/rancher/charts"
```
This doesn't work
