### ISSUE TITLE
Service discovery alias targets wrong IP

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#16691]
Running Rancher 2.1.1.

Steps to reproduce the issue:

1) create a service which has a cluster ip

```
apiVersion: v1
kind: Service
metadata:
  name: es-coordinator
  namespace: monitoring
  labels:
    app: es-coordinator
spec:
  ports:
  - port: 9200
    name: http
  selector:
    app: es-coordinator
```

2) create an alias to that service

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetDnsRecordIds: '["monitoring:es-coordinator"]'
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

3) the newly-created alias doesn't resolve to the es-coordinator's cluster ip but to the pods ips..

```bash
# host es-coordinator
es-coordinator.monitoring.svc.cluster.local has address 10.43.46.2
# host elasticsearch
elasticsearch.monitoring.svc.cluster.local has address 10.42.4.21
elasticsearch.monitoring.svc.cluster.local has address 10.42.5.21
```

**Comment by Hitesh-Agrawal** [comment]
The 2 above (create an alias to that service) correct .yml definition is below, which was missing name and namespace

```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
  annotations:
    field.cattle.io/targetDnsRecordIds: '["monitoring:es-coordinator"]'
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
