### ISSUE TITLE
Rancher catalog multiline variable feature[2.0]

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#16728]
I create a chart that is defined as multiline in questions.yml, but the deployment will report an error when passing multiple rows of values ​​on the UI.

Use the following yaml file
questions.yml   
```
questions:
- variable: masterConfig
  description: "masterConfig"
  type: multiline
  label: config
```
redis-configmap.yaml  
``` 
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
data:
    master.conf: |
      {{ .Values.masterConfig | indent 4 }}
```
Deployment is normal when incoming with a single row value  
![](https://training-1251900790.cos.ap-guangzhou.myqcloud.com/image/1.png)

An error occurred when using a multi-line deployment
![](https://training-1251900790.cos.ap-guangzhou.myqcloud.com/image/2.png)

![](https://training-1251900790.cos.ap-guangzhou.myqcloud.com/image/3.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`catalog-tab.launch`|
