### ISSUE TITLE
Feature Request - EKS - Allow passing custom ManagedPolicyArns to the NodeInstanceRole

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#16730]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Request Details:**
Requesting the ability to add custom Policy ARN to the node instance profile. In order to use the cluster-autoscaler for EKS (https://github.com/helm/charts/tree/master/stable/cluster-autoscaler) the Role needs the correct policy to allow for autoscaling. I believe it would be best for the users to first create their policy in AWS and then to allow the users to specify that policies in Rancher and have it created with the Cloudformation stack. Would make the most sense to accept an array of policy arn's

**Result:**
```
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - !Ref CustomNodeInstanceRoleARN
```
Something like the above.

**Environment information**
- Rancher version: 2.1.1
