### ISSUE TITLE
Named service port in Ingress doesn't work

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#16740]
rancher/rancher:v2.1.1

Offending line: `servicePort: http`

Problematic config:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc-leo-test
  name: svc-leo-test
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: leo-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-leo-test
spec:
  rules:
  - host: leo-test.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-leo-test
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leo-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: leo-test
    spec:
      containers:
      - name: leo-test
        image: leodotcloud/swiss-army-knife
        ports:
        - containerPort: 80
```

Working config:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc-leo-test
  name: svc-leo-test
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: leo-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-leo-test
spec:
  rules:
  - host: leo-test.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-leo-test
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leo-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: leo-test
    spec:
      containers:
      - name: leo-test
        image: leodotcloud/swiss-army-knife
        ports:
        - containerPort: 80
```

**Comment by leodotcloud** [comment]
This issue can become quite annoying while authoring helm charts as the default template generators use named ports. Also, quite a few of the upstream charts use this format.

**Comment by sharedprophet** [comment]
The problematic config doesn't have any port specs with the name "http"...?

**Comment by loganhz** [comment]
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: svc-leo-test
  name: svc-leo-test
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    name: leo-test
```

I guess add this line `name: http` could fix this issue
