### ISSUE TITLE
Nginx ingress uses public ip while communicating with service

### ISSUE THREAD

**Issue by gadelkareem** [rancher/rancher#16764]
*Describe your issue here*
The Nginx ingress does not have a private IP from canal. And when it communicates with services, it uses the instance public IP instead of using the internal network for some reason.
```
kubectl get ingress
NAME           HOSTS             ADDRESS   PORTS   AGE
example-ingress   example.com             80      5m
```
I need to detect the nginx ingress range to whitelist it as a proxy for my webserver, so I can get the real remote IP.

I tried both the nginx ingress that comes with Rancher and with helm to enable `--report-node-internal-ip-address=true`:
```
helm upgrade --install ingress --namespace=ingress --set rbac.create=true,controller.kind=DaemonSet,controller.service.type=ClusterIP,controller.hostNetwork=true,controller.extraArgs.report-node-internal-ip-address=true stable/nginx-ingress
```

Service and ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.class: nginx
  name: app-ingress
  namespace: app
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
    app: app
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
```

The exact same setup works fine on a kubeadm setup.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.1` UI: `v2.1.4` |
|Route|`ingresses.index`|
