### ISSUE TITLE
Clusters created from rke are getting stuck in "waiting for server-url setting to be set"

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#16840]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
cluster.yaml should look like...

```
ignore_docker_version: true
kubernetes_version: v1.12.1-rancher1-1

nodes:
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
  - address: 10.x.x.x
    user: rancher
    role: [controlplane,worker,etcd]
    ssh_key_path: ./rancher.rsa
```

Then do the normal `rke up --config cluster.yaml` Install helm and tiller if needed and then.... sit.

```
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller --tiller-connection-timeout 100

helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm upgrade --install cert-manager stable/cert-manager --namespace kube-system --tiller-connection-timeout 100
helm upgrade --install rancher rancher-stable/rancher --namespace cattle-system --set hostname=$RANCHER_FQDN --tiller-connection-timeout 100
```

**Result:**
It looks like it's working, two of the rancher pods aren't complaining but then one of them starts spamming:
```
2018/12/04 13:58:48 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/12/04 14:03:04 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
```

`curl`ing the pod like so: `curl -s -k https://10.x.x.x/login --header 'Host: myhost.com'` results in a 404. It's like the cluster is never coming up to ready, so how do we do an HA install? :(

**Other details that may be helpful:**

Tried with both docker 17 and 18, centos 7.5 and rancheros. Originally filed as an `rke` problem over here: https://github.com/rancher/rke/issues/1052

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): No UI. :)
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): KVM on Bare metal
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 CPU 16 GB
- Kubernetes version (use `kubectl version`): 

```
cluster doesn't come up
```

- Docker (use `docker info`): 

Tried with both docker 17 and Docker 18.
