### ISSUE TITLE
Can not set flannel interface follow RKE doc in Rancher UI

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#16903]
rancher/rancher:v2.1.3

RKE document says, we can set it with the following config.

```
network:
    plugin: flannel
    options:
      flannel_iface: eth1
```

But when we do it in UI, it seems it doesn't work. 

The correct option is:

```
network:
    plugin: flannel
    flannel_cloud_provider:
      iface: eth1
```

The thing is we have a `flannelNetworkProvider` filed in `/v3/schemas/networkConfig`. But it is very confusing as user doesn't know it from the RKE doc.I guess Canal/Weave has similar issues

![image](https://user-images.githubusercontent.com/21168270/49562215-79744700-f955-11e8-9f58-af9ecaea7130.png)

Solution:

1. Maybe we should make the config under `options` work as well via Rancher API
2. Or put the interface input back instead of ask user to config it in YAML via Rancher UI

**Comment by loganhz** [comment]
@galal-hussein any idea about this issue?

**Comment by leodotcloud** [comment]
Built a dev image using v2.2.4 tag and updated the setting for agent image to match the same. Created a cluster with `flannel_iface: eth1` and it got created successfully. 

For some reason, the same doesn't work with v2.2.4. Tried the same with a new install of v2.2.7 and it didn't work too.

**Comment by leodotcloud** [comment]
Using `rancher/rancher:master`, the flannel setting seems to be working.

<img width="518" alt="Screen Shot 2019-08-20 at 7 30 20 AM" src="https://user-images.githubusercontent.com/19392926/63356305-673c0c80-c31c-11e9-9a67-88d8c73db7d9.png">

**Comment by alena1108** [comment]
@sangeethah can be tested on the latest master

**Comment by sangeethah** [comment]
@leodotcloud @loganhz 

1. Created  a DO cluster with following:
```
 network:
    options:
      flannel_iface: eth1
    plugin: flannel
```

I see cluster get to"Active" state but kube-flannel fails to get started which is as expected since DO machines does not have `eth1` interface.

```
I0829 00:31:07.116058 1 main.go:210] Could not find valid interface matching eth1: error looking up interface eth1: route ip+net: no such network interface
E0829 00:31:07.116157 1 main.go:234] Failed to find interface to use that matches the interfaces and/or regexes provided
```
"Edit as Yaml" for kube-flannel indicates that iface is set as expected:

```
network:
    plugin: flannel
    flannel_cloud_provider:
      iface: eth1
      containers:
      - args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=eth1
```
This seems to work as expected. Please confirm.

1. Created  a DO cluster with following:
```
network:
    plugin: flannel
    flannel_cloud_provider:
      iface: eth1
```

I see cluster get to"Active" state and kube-flannel also get started successfully with default interface which is incorrect:

```
I0829 00:19:32.434266 1 main.go:514] Determining IP address of default interface
I0829 00:19:32.434538 1 main.go:527] Using interface with name eth0 and address 159.65.183.188
```
