### ISSUE TITLE
Rancher-Compose: Cross Stack target services in Load Balancers should look at link alias instead of service name.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1691]
The labels used for target services relies on the service name instead of link alias. 

```
lb: 
  ports: 
  - 80
  links: 
  - web1:web1a
  external_links:
  - stackb/web2: web2a
  labels: 
    io.rancher.loadbalancer.target.web1: '91'
    io.rancher.loadbalancer.target.web2: '90'
```

We should change to Link Alias.

```
lb: 
  ports: 
  - 80
  links: 
  - web1:web1a
  external_links:
  - stackb/web2: web2a
  labels: 
    io.rancher.loadbalancer.target.web1a: '91'
    io.rancher.loadbalancer.target.web2a: '90'
```

If we make this change, we should add the ability to create aliases in the UI so the generated `docker-compose.yml` would be correlated. It also allows the services of the same name to be used but with different aliases.
