### ISSUE TITLE
Rancher-Compose: Labels need to allow stackname/servicename as the label for target services in a different stack.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1693]
Since we allow cross stack linking, we run into issues when we have services with the same name using rancher-compose. Rancher-Compose needs to support label key in this syntax:

```
 io.rancher.loadbalancer.target.ENVIRONMENT_NAME/SERVICE_NAME
```

Rancher-Compose v0.2.5
Currently, we're only able to creating the same routing rules for the service names that are the same across stacks. 
```
lb:
  image: rancher/load-balancer-service
  ports:
  - 80
  links: 
  - web1:web1
   external_links:
  - differentstack/web1:web1
  labels:
    io.rancher.loadbalancer.target.web1: app.example.com:80/foo=8000
```

We want to be able to support this rancher-compose for cross-stack services of the same name.
```
lb:
  image: rancher/load-balancer-service
  ports:
  - 80
  links: 
  - web1:web1
   external_links:
  - differentstack/web1:web1
  labels:
    io.rancher.loadbalancer.target.web1: app.example.com:80/foo=8000
   # Add support for `otherstack/servicename` in the key 
    io.rancher.loadbalancer.target.differentstack/web1: '90'
```

The fix in Rancher-Compose needs to be released with the fix in Rancher, where Rancher will generate the `docker-compose.yml` file with the same key.
