### ISSUE TITLE
Rancher Helm questions.yml 

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#16930]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

Rancher | v2.0.7
-- | --
User Interface | v2.0.67
Helm | v2.9.1-rancher1
Machine | v0.15.0-rancher1-1

Questions:
How can I get a list of files in the options element of the questions.yml file ?

**Comment by guangbochen** [comment]
you can only specify string options of `enum` type in the questions.yml, e.g,
```
- variable: service.type
  default: "ClusterIP"
  description: "Service type"
  type: enum
  options:
    - "ClusterIP"
    - "NodePort"
  required: true
  label: Service Type
```
