### ISSUE TITLE
Rancher needs to generate Rancher-Compose that shows environment_name/stackname in labels for routing rules

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#1694]
With #1693, Rancher needs to generate different rancher-compose syntax for services linked from a different stack. 

Current syntax only allows 1 key even if I created 2 routing rules, but had 2 services with the same name (but in different stacks). 

Current Syntax:
```
lb:
  image: rancher/load-balancer-service
  ports:
  - 80
  links: 
  - web1:web1
   external_links:
  - differentstack/web1:web1
  labels:
    # No ability to differentiate between the 2 web1 services
    io.rancher.loadbalancer.target.web1: app.example.com:80/foo=8000
```

New syntax
```
lb:
  image: rancher/load-balancer-service
  ports:
  - 80
  links: 
  - web1:web1
   external_links:
  - differentstack/web1:web1
  labels:
    io.rancher.loadbalancer.target.web1: app.example.com:80/foo=8000
   # Add support for `otherstack/servicename` in the key 
    io.rancher.loadbalancer.target.differentstack/web1: '90'
```

**Comment by alena1108** [comment]
Even with no duplicated services names cross environments, "label" directives for hostname routing rules are not being set. I've just tested couple of scenarios:

Doesn't work:
```
external_links:
  - env1/svc1
  labels:
    io.rancher.loadbalancer.target.svc1: example.com=10001
```

Works:
```
external_links:
  - env1/svc1
  labels:
    io.rancher.loadbalancer.target.env1/svc1: example.com=10001
```

We have to fix the config export on the rancher side to include the environment name. No need for the fix on the rancher-compose side as it already respects an environment name in the "io.rancher.loadbalancer.target" label

**Comment by alena1108** [comment]
@sangeethah

**Comment by sangeethah** [comment]
Tested with build from master:

Configs generated for stacks that have lb-services linked to targets from other stacks  includes stack name/service name in the target labels:

```
lb-cross:
  ports:
  - 220:80
  - 221:81
  restart: always
  external_links:
  - Default/sanweb2:sanweb2
  - Default/sanweb1:sanweb1
  - rancher-san/web4:web4
  labels:
    io.rancher.loadbalancer.target.web3: 440/service2.html
    io.rancher.loadbalancer.target.Default/sanweb1: www.abc.com
    io.rancher.loadbalancer.target.Default/sanweb2: www.def.com/service1.html=80,www.def.com/service3.html=81
    io.rancher.loadbalancer.target.rancher-san/web4: /name.html
  tty: true
  image: rancher/load-balancer-service
  links:
  - web3:web3
  stdin_open: true
web3:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
```
