### ISSUE TITLE
Catalog - show_if condition didn't work for array of variable like `xip.io`

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#16982]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. having a questions.yml with following variables:
```
- variable: ingress.enabled
  default: false
  description: "Expose app using Layer 7 Load Balancer - ingress"
  type: boolean
  label: Expose app using Layer 7 Load Balancer
  show_subquestion_if: true
  group: "Services and Load Balancing"
  subquestions:
  - variable: ingress.hosts[0].name
    default: "xip.io"
    description: "Hostname to your Fluentd installation"
    type: hostname
    required: true
    label: Hostname
- variable: test
  default: "test"
  description: "test"
  type: string
  show_if: "ingress.hosts[0].name=!xip.io"
  label: Test
  group: "Fluentd Settings"
```
2. show_if condition didn't work for `test` parameter even if user changes the host[0].name to any other pararmeters.

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single
