### ISSUE TITLE
Rancher virtual host settings from UI

### ISSUE THREAD

**Issue by portokallidis** [rancher/rancher#1698]
Is there any way that i can set VIRTUAL_HOST like nginx-proxy image or like in tutum?
Perhaps an easy example should be extremely helpful! :)

**Comment by vincent99** [comment]
The built-in load balancing service supports routing based on the host header, among other things, in the latest release:  http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-balancers/#advanced-routing-options

**Comment by deniseschannon** [comment]
@portokallidis Please let me know if the examples in the docs are not enough or if you have more questions.

**Comment by portokallidis** [comment]
Sorry for the late response, but i 've yet to figure it out
I want to setup the simple wordpress stack as an example 
wordpress stack
======
The docker-compose.yml :
````yaml
mywordpress:
  tty: true
  image: wordpress
  links:
    - database:mysql
  stdin_open: true
wplb:
  labels:
    - io.rancher.loadbalancer.target.mywordpress: '80'
  tty: true
  image: rancher/load-balancer-service
  links:
    - mywordpress:mywordpress
  stdin_open: true
database:
  environment:
    - MYSQL_ROOT_PASSWORD: pass1
  tty: true
  image: mysql
  stdin_open: true
````

The rancher-compose.yml : 
````yaml
mywordpress:
  scale: 1
wplb:
  scale: 1
  load_balancer_config:
    name: wplb config
    app_cookie_stickiness_policy:
      cookie: lb_wordpress_sticky
      max_length: 1024
      prefix: false
      request_learn: true
      timeout: 3600000
      mode: path_parameters
database:
  scale: 1
````
I also need a load balancer outside the stack (like this for example)
````yaml
AthinaRouter:
  ports:
  - 80:80
  external_links:
  - wordpress-rancher/pma:pma
  - wordpress-rancher/elgg:elgg
  - wordpress-rancher/wplb:wplb
  labels:
    io.rancher.loadbalancer.target.wplb: wp.nporto.eu:80=80
    io.rancher.loadbalancer.target.pma: pma.wp.nporto.eu:80=80
    io.rancher.loadbalancer.target.elgg: eclinpro.nporto.eu:80=80
    io.rancher.scheduler.affinity:host_label: host_location=duth
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
````

**Comment by portokallidis** [comment]
When i assign The router to from wp.nporto.eu-> single container wordpress it works
but when i assign it to wplb (the wordpress loadbalancer container) doesnt work.

**Comment by deniseschannon** [comment]
It doesn't look like you added any listening ports to `wplb`. 

```
ports:
# There must be a listener port for the LB to work.
  - 80:80
```
inside of 
```
wplb:
  labels:
    - io.rancher.loadbalancer.target.mywordpress: '80'
  tty: true
  image: rancher/load-balancer-service
  links:
    - mywordpress:mywordpress
  stdin_open: true
```

Since you have a load balancer on top of a load balancer, you could make the listening be internal (only available inside the host), which would have the listener ports in this format. 
```
expose:
  - 80:80
```

And you'd need to  make sure your `AthinaRouter` is on the same host as the `wplb`. In your `AthinaRouter`, the other services don't seem to be linked in either `links` or `external_links`. Specifically, `other1lb`, `other1lb`, `other3lb` don't seem to be linked anywhere.
