### ISSUE TITLE
Deleting a namespace with audit logging enabled hangs

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#17027]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I was not able to reproduce this myself, I tried with a single node installation as well as an HA installation.
1) Install Rancher in an HA installation with RKE and enable audit log.
2) Create a namespace from CLI: kubectl create ns tempas
3) Delete the namespace from CLI: kubectl delete ns tempas

**Result:**
Namespace deletion will hang

**Other details that may be helpful:**
Ping me for logs.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.3
- Installation option (single install/HA): HA RKE w/ helm chart

**Comment by galal-hussein** [comment]
Rancher version: master
single node
Steps:

- Run rancher server as a single node installation
- start a custom cluster with 1 node (ALL roles) and 2 worker nodes
- edit the cluster config to add the following extra args:
```
kube-api: 
    always_pull_images: false
    extra_args: 
      audit-log-maxage: "30"
      audit-log-maxbackup: "10"
      audit-log-path: "-"
      v: "3"
```
- create a namespace on this cluster and try to remove it

I wasn't able to reproduce the issue and the namespace got deleted normally
