### ISSUE TITLE
min_length, max_length, valid_chars not considered when generating a password

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#17055]
v2.1.1

```
- group: "App Settings"
  variable: app.session.secret
  default: ""
  description: "secret will be auto-generated if not specified"
  min_length: 64
  max_length: 64
  valid_chars: "[a-z,A-Z,0-9]"
  type: password
  label: Session Secret
```

When I use the above question, clicking the "Generate" button in UI doesn't consider the constraints when generating the string.

**Comment by loganhz** [comment]
> While it's not particularly well documented, that is not the [intended format](https://github.com/rancher/api-spec/blob/master/specification.md#character-ranges) for `validChars`, you'd just say `a-zA-z0-9`.

Please use `valid_chars: "[a-zA-Z0-9"` instead of `valid_chars: "[a-z,A-Z,0-9]"`

**Comment by davidnuzik** [comment]
Version: master 2.2 (12/21/18)
Fixes were put in to support min_length and max_length for the password, valid_chars improvement(s), and misc. See the PR. I validated that this is working and that we can now consider the constraints provided based on the example given in the issue description. This worked successfully when I specified my valid_chars: "a-zA-Z0-9" and every time the randomly generated password length was indeed 64 per the questions.yaml specifications.
```
categories:
  - davidnuzik
questions:
- group: "App Settings"
  variable: app.session.secret
  default: ""
  description: "secret will be auto-generated if not specified"
  min_length: 64
  max_length: 64
  valid_chars: "a-zA-Z0-9"
  type: password
  label: Session Secret
```
