### ISSUE TITLE
[RFE] Rancher 2 Catalog Value Substitution

### ISSUE THREAD

**Issue by mak3r** [rancher/rancher#17096]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Background**
Our use case starts with catalogs and how we us Rancher to provide services for our customers (developers, analysts, release managers, etc). When we create our own catalog apps, we have added a section in the questions.yml to capture the users initials. In our deployments, we use the `initials` value to programmatically provision an NFS share. If it exists we use the existing directory. If it doesn't exist, we create it. 

**Problem**
The fundamental problem with this approach is one of both security and order. Users may, intentionally or accidentally use incorrect initials. 

**Feature Request**
This is suggestion for a 2 part solution which will solve both the issues of security (from our use case) as well as providing a contextual value resolution. The contextual value resolution  would assist in maintaining order (from our use case). In the examples below, the idea is to make contextual substitute for the value string which begins with `${` and ends with `}` 

***Maintaining Order***
Ideally, our admins who create the charts could set a sequence of characters as the default value for the `nfsDirName` variable so that it is always tied to the logged in user at deployment. 
`questions.yml:`
```
questions:
- variable: nfsDirName
  default: "${rancher_user_id}"
  description: "user specific nfs directory"
  type: string
  required: true
  label: NFS Directory Name
  group: "NFS Settings"
```

***Resolving the Security Issue***
In order to have this type of value substitution, we will not know what the default value for the `nfsDirName` variable will be until the user context is known. If this is an editable parameter, then we still have a security issue given a malicious user. A new parameter for the questions format could solve this. For example if we could set an `editable` key to false and also set the `show_if` value to false then the user would not see or be permitted to modify the final value. It might look like this:
`questions.yml:`
```
questions:
- variable: nfsDirName
  default: "${rancher_user_id}"
  description: "user specific nfs directory"
  type: string
  required: true
  label: NFS Directory Name
  group: "NFS Settings"
  show_if: false
  editable: false
```

**Additional details**
This is a generic feature request that would be valuable as a general feature. Suggestions for other substitutions would include: 
- Project name
- Cluster name
- Application name
- Namespace
- etc...

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Request for Rancher >= 2.x
- Installation option (single install/HA):
N/A
