### ISSUE TITLE
helm annotations error

### ISSUE THREAD

**Issue by lanmingle** [rancher/rancher#17128]
The parse failed, but the official one did not。

xxx-values.yaml
``` yaml

  service:
    type: ClusterIP
    ## Use serviceLoadBalancerIP to request a specific static IP,
    ## otherwise leave blank
    # loadBalancerIP:
    annotations:
       prometheus.io/scrape: "true"
       prometheus.io/port: "9121"

```

Rancher | v2.1.3
-- | --
用户界面 | v2.1.17
Helm | v2.10.0-rancher5
主机 | v0.15.0-rancher1-1
