### ISSUE TITLE
Workload annotations for monitoring do not wireup collection

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#17145]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a deployment workload with the annotation set via `kubectl`
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
      annotations:
        field.cattle.io/workloadMetrics: '[{"path":"/minio/prometheus/metrics","port":9000,"schema":"HTTP"}]'
    spec:
        containers:
....
```

**Result:**

No monitoring service or ServiceMonitor object are created, and therefore not scraped for metrics.

If I manually create the missing resources, it seems to work. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher/rancher:master - 12/17 AM MST
Stand alone container

1x imported single node RKE cluster.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker (use `docker info`):

```
(paste the output here)
```
