### ISSUE TITLE
Pipeline applyApp step does not work properly

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17225]
**Steps to reproduce:**
1. add a project catalog, e.g. https://github.com/gitlawr/charts.git, lawrtest branch.
2. run a pipeline with apply app step, e.g.:
```
stages:
- name: deploy app
  steps:
  - applyAppConfig:
      catalog: c-lhr4b-p-5n7wz-p-lawrtest-mysql
      version: 0.3.7
      answers:
        persistence.enabled: "false"
      name: myapp
      targetNamespace: myapp
```
3. run the pipeline

**Result:**
It prints errors in loop.
![image](https://user-images.githubusercontent.com/5697937/50411071-17ae4b00-0838-11e9-8f84-006b6ba09550.png)
