### ISSUE TITLE
Unnecessary backends if multiple source ports are specified in config

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#1722]
I am running two lb'd containers with ports 80 and 443 forwarded. The port 80 is ACL'd on the host header, but port 443 is not because it is the only HTTPS service on the LB. The 443 HAProxy config is shown below.

```
frontend 00269251-55e9-4271-88fb-e4189c935bba_frontend
        bind 10.42.3.46:443
        mode tcp
        # This backend is the only backend that I need
    	default_backend 00269251-55e9-4271-88fb-e4189c935bba_5_backend
        # This backend is superfluous, and these containers don't respond to 443
    	default_backend 00269251-55e9-4271-88fb-e4189c935bba_2_backend

backend 00269251-55e9-4271-88fb-e4189c935bba_5_backend
        mode tcp
        balance roundrobin
        timeout check 2000
        option httpchk GET / HTTP/1.0
        server 839847d0-6308-489a-b78c-82017502bbd0 10.42.178.183:443 check port 80 inter 2000 rise 2 fall 4
        server ff7cc32d-4ab6-46c1-a38a-57eccfa97b6c 10.42.241.178:443 check port 80 inter 2000 rise 2 fall 4
backend 00269251-55e9-4271-88fb-e4189c935bba_2_backend
        mode tcp
        balance roundrobin
        timeout check 10000
        option httpchk GET / HTTP/1.0
        server 62c78f6f-cdfa-401a-b66c-33b73841d372 10.42.253.149:443
        server 282e6900-2794-4f47-afa2-edf81edbcca1 10.42.78.110:443 check port 80 inter 5000 rise 2 fall 3
        server 9cfe16d6-2650-41cc-85e0-bd692f5b6394 10.42.236.207:443
        server 56ae31ca-1386-4808-a775-c3f40e9174f8 10.42.77.185:443
        server 451df345-60ad-4b60-bd13-2d5a80ab84df 10.42.161.91:443
        server 83cf80c1-ecc3-42f3-b073-103ea6e432f7 10.42.254.210:443
        server 0ac3e48e-7c07-4f39-b5a2-d480383ef61b 10.42.41.78:443 check port 80 inter 5000 rise 2 fall 5
        server cd9da632-0bdf-42e6-b3ef-01b9d78d3ad9 10.42.93.196:443 check port 80 inter 5000 rise 2 fall 5
        server 31405d23-c854-46ce-92b9-db5f87b3deaa 10.42.71.21:443 check port 80 inter 5000 rise 2 fall 5
        server 727ecffc-d6fc-4ced-8cc3-5ed0b4e429eb 10.42.138.91:443 check port 80 inter 5000 rise 2 fall 5
        server e8de5d88-2f50-4a2a-a819-78017027662c 10.42.142.216:443
```

Why are there 2 default_backends? If the hosts that are supposed to respond on port 443 don't, I would want the connection to drop or return 503.

With this setup about 50% of the time:

```
$ curl https://example.com
curl: (35) Server aborted the SSL handshake
```

Both containers are verified working.

**Comment by alena1108** [comment]
@willseward could you share the output of exported .yml file of your stack? 2 default backends should have never been assigned to one front end unless 2 target ports - 80 and 443 - were deliberately assigned to listening port 443 under Advanced options.

Also what Rancher version is it? And is it a fresh install, or upgraded setup?

**Comment by alena1108** [comment]
![hostnamerouting](https://cloud.githubusercontent.com/assets/1562176/9048950/02c49c34-39f2-11e5-8a29-8ba0578615d7.png)

I've just setup an LB for application listening on 2 ports - 80 and 443 - similar to your use case, and linked a service to it. it resulted in 1 default backend per each listening port on haproxy

**Comment by willseward** [comment]
Rancher	v0.31.0
Cattle	v0.73.0
User Interface	v0.39.0
Rancher Compose	beta/latest
It's been upgraded continuously since v0.28.0

Here are obfuscated versions of my yml files.
``` yaml
lb-b:
  ports:
  - 443:443/tcp
  - 80:80
  external_links:
  - stack1/web:stack1-web
  - stack2/web:stack2-web
  - stack2/apiv3:apiv3
  - stack3/web:stack3-web
  - stack4/web:stack4-web
  - stack5/web:stack5-web
  labels:
    io.rancher.loadbalancer.target.stack5-web: example.com:80,example.com:443=443
    io.rancher.loadbalancer.target.stack3-web: example2.com:80
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.web-1: frogsaver.com:80,portal.frogsaver.com:80,www.frogsaver.com:80
    io.rancher.loadbalancer.target.wordpress: babylondevelopment.us:80
    io.rancher.loadbalancer.target.api-v4-b: v4.api.frogsaver.com:80
    io.rancher.loadbalancer.target.api-v1-3-a: api.frogsaver.com:80
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```

**Comment by willseward** [comment]
Rancher	v0.31.0
Cattle	v0.73.0
User Interface	v0.39.0
Rancher Compose	beta/latest
It's been upgraded continuously since v0.28.0

Here are obfuscated versions of my yml files.
``` yaml
lb-b:
  ports:
  - 443:443/tcp
  - 80:80
  external_links:
  - stack1/web:stack1-web
  - stack2/web:stack2-web
  - stack3/web:stack3-web
  - stack4/web:stack4-web
  - stack5/web:stack5-web
  labels:
    io.rancher.loadbalancer.target.stack1-web: example.com:80,example.com:443=443
    io.rancher.loadbalancer.target.stack2-web: example2.com:80
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.stack3-web: example3.com:80,www.example3.com:80,www2.example3.com:80
    io.rancher.loadbalancer.target.stack4-web: example4.com:80
    io.rancher.loadbalancer.target.stack5-web: example5.com:80
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```
