### ISSUE TITLE
Mount failed for local storage volume

### ISSUE THREAD

**Issue by zidex** [rancher/rancher#17264]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

sc.yml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
pv.yml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-test
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - test1604
```
pvc.yml
```
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
```
test.yml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-reader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-reader
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: reader
        image: gcr.io/google_containers/busybox:1.24
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "tail -f /usr/test-pod/test_file"
        volumeMounts:
        - name: test-vol
          mountPath: /usr/test-pod
      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: "pvc-test"
```

**Result:**

Warning | FailedMount | Unable to mount volumes for pod  "test-reader-574bb8d5dd-t284t_default(b51252f3-0b48-11e9-bd5e-0800271af56c)":  timeout expired waiting for volumes to attach or mount for pod  "default"/"test-reader-574bb8d5dd-t284t". list of unmounted  volumes=[test-vol]. list of unattached volumes=[test-vol  default-token-6tjxd] | 2 minutes ago
-- | -- | -- | --
Warning | FailedMount | MountVolume.SetUp failed for volume "local-pv-test" : mount  failed: exit status 32 Mounting command: mount Mounting arguments: -o bind /mnt/disks/test  /var/lib/kubelet/pods/b51252f3-0b48-11e9-bd5e-0800271af56c/volumes/kubernetes.io~local-volume/local-pv-test Output: mount: special device /mnt/disks/test does not exist | 2 minutes ago

**Other details that may be helpful:**

> kubectl get nodes
> NAME       STATUS   ROLES                      AGE   VERSION
> test1604   Ready    controlplane,etcd,worker   1h    v1.11.5

> ls -l /mnt/disks/
> total 4
> drwxrwxrwx 2 root root 4096 Dec 29 12:02 test

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.1.4
- Installation option (single install/HA):
Single
Host system: Ubuntu 16.04
Docker: 17.03.3
