### ISSUE TITLE
[Pipeline] Second build in a pipeline always fails

### ISSUE THREAD

**Issue by pensiero** [rancher/rancher#17269]
**Steps to reproduce (least amount of steps as possible):**
I'm able to successfully build&publish the first image of my pipeline, however if I add a second build step, it fails.
I also tried moving the step into a new stage, and I also tried to change the order of the builds: it always fails the second build, not matter what image is.

This is the error:

```
13:00:39 [pipeline_p-bcrkx-17] Running shell script
13:00:40 + /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker
13:00:40 + /usr/local/bin/dockerd -g /var/lib/docker
13:01:36 EXITCODE   0time="2018-12-30T13:01:29Z" level=fatal msg="Error authenticating: exit status 1"
```

This is my `.rancher-pipeline.yaml`
```
stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./config/docker/nginx/Dockerfile
      buildContext: .
      tag: xxx-nginx:${CICD_EXECUTION_SEQUENCE}
  - publishImageConfig:
      dockerfilePath: ./config/docker/web/prod/Dockerfile
      buildContext: .
      tag: xxx-web:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./config/docker/nginx/deployment.yaml
  - applyYamlConfig:
      path: ./config/docker/web/deployment.yaml
timeout: 60
branch: {}
```

<img width="1269" alt="screenshot 2018-12-30 at 14 07 14" src="https://user-images.githubusercontent.com/2010696/50547565-3cd9f980-0c3c-11e9-8598-0ddd8251a887.png">

**Environment information**
- Rancher version: `2.1.4`
- Installation option: `single`
