### ISSUE TITLE
volume error: stat /path no such file or directory

### ISSUE THREAD

**Issue by altairo2087** [rancher/rancher#17297]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug
**Steps to reproduce (least amount of steps as possible):**
1. create pv and pvc
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/grafana"
  claimRef:
    namespace: monitoring
    name: grafana-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - infra
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
```
2. install helm/stable/grafana with persistence
```
persistence:
  enabled: true
  existingClaim: grafana-pvc
  subPath: "var/lib/grafana"
```
**Result:**
POD error event
Error: stat /volumes/grafana: no such file or directory
![image](https://user-images.githubusercontent.com/7862433/50634986-76bf3e80-0f61-11e9-8145-ba47bfc41d1f.png)

**Other details that may be helpful:**
I'm trying create pv from rancher ui and install grafana from catalog->grafana(helm).
But this works when i install kubernetes without rancher.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.14
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM CentOS Linux release 7.6.1810 (Core) 8CPU/6GB
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 33
 Running: 32
 Paused: 0
 Stopped: 1
Images: 18
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 5.658GiB
Name: infra
ID: ZJ2D:BS42:FG3C:GWBM:Q5RF:SOQ2:ASDH:ZKF7:A42V:FWPB:4V2E:YJZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```
