### ISSUE TITLE
Rancher Compose fails to start a container with volumes or ports especifications

### ISSUE THREAD

**Issue by alculquicondor** [rancher/rancher#1729]
I set up this `docker-compose.yml`:

```yaml
rabbitmq:
    image: rabbitmq
    volumes:
        - "/var/lib/rabbitmq"
    ports:
        - "127.0.0.1:15672:15672"
    expose:
        - "5672"
    hostname: rabbitmq
    restart: "always"
```

And I get messages like this:

```
rabbitmq_1 | 2015-08-03T23:04:13.122494920Z no such file or directory
rabbitmq_1 | 2015-08-03T23:04:15.719045483Z no such file or directory
rabbitmq_1 | 2015-08-03T23:04:17.249947070Z no such file or directory
```
When using rancher-compose. It works if there are not volumes nor ports especifications. I've tried with other images too.

I'm running rancher in a vagrant cluster (using rancherOS) with latest tags.

Is there anything you recommend me to try to trace this down?

**Comment by deniseschannon** [comment]
The ports issue is due to Rancher not supporting binding to a specific IP. https://github.com/rancher/rancher/issues/53

As for the volumes, I'm not having issues with it. I try to run your file in rancher-compose and get this error, which I'm thinking is related to the port mapping issue.

```
ERRO[0023] Failed to get logs for rabbittest1_rabbitmq_1: websocket: bad handshake 
```

What version of Rancher (click on cow in left corner) and rancher-compose are you running? To find the version in rancher-compose, please use `rancher-compose -v`. The versions need to be compatible with each other.

**Comment by martijngastkemper** [comment]
I got the same problem with volumes. I tried to use ``volumes``, ``volumes_from`` and via the UI, but all three method didn't work. This is one of the use cases I tested:
``` yml
# docker-compose.yml
test:
  image: ubuntu
  volumes_from:
    - testdata
testdata:
  image: ubuntu
  command:
  volumes:
    - /var/lib/mysql
  tty: true
  stdin_open: true
```

Version information:
Rancher	v0.31.0
Cattle	v0.73.0
User Interface	v0.39.0
Rancher Compose	beta/latest
