### ISSUE TITLE
TransitioningMessage and transitioning state are not reflected correctly for the cluster that got to "Active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17304]
Rancher server version - 2.1.5-rc4
K8s version - 1.11.6 ( host os - rhel75)

Steps to reproduce the issue:
Created a custom cluster with following configuration:
1 control node
4 etcd node
2 worker node

Cluster gets to "Active" state.
Removed 1 of the etcd node from rancher server and then deleted it from AWS console.
Added 1 more worker node.

Cluster state is now in "Active" state and is fully functional.
But transition error message is seen for the cluster and it never gets cleared

```
"state": "active",
"transitioning": "error",
"transitioningMessage": "[etcd] Failed to bring up Etcd Plane: Failed to inspect [etcd-rolling-snapshots] container on host [18.216.99.16]: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/etcd-rolling-snapshots/json: failed to find session for client c-cp9qw:m-7f1cccc107f8",
```

<img width="1405" alt="screen shot 2019-01-03 at 9 29 26 am" src="https://user-images.githubusercontent.com/4266958/50652090-34363b80-0f3a-11e9-9b30-883fbe6c1bc7.png">

**Comment by alena1108** [comment]
@sangeethah if you hit this issue again, could you include the viewInApi output?

**Comment by Krailon** [comment]
It seems I've run into this issue as well. Cluster state is active but red. Nodes and pods are all green. Everything seems to be working but "Transitioning" value is "error". In my case I think this likely happened because I created a cluster with only master nodes without removing their taints. There was a delay between cluster creation and the first worker node joining during which several core components repeatedly failed to deploy. Here's my viewInAPI output:

```YAML
{
"actions": {
"exportYaml": "…/v3/clusters/c-t2xvp?action=exportYaml",
"generateKubeconfig": "…/v3/clusters/c-t2xvp?action=generateKubeconfig",
"importYaml": "…/v3/clusters/c-t2xvp?action=importYaml"
},
"agentImage": "rancher/rancher-agent:v2.1.5",
"allocatable": {
"cpu": "4",
"memory": "16329956Ki",
"pods": "110"
},
"annotations": {
"authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
"lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
"lifecycle.cattle.io/create.cluster-provisioner-controller": "true",
"lifecycle.cattle.io/create.cluster-scoped-gc": "true",
"lifecycle.cattle.io/create.mgmt-cluster-rbac-remove": "true"
},
"apiEndpoint": "REDACTED",
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"displayName": "ml-prod",
"dockerRootDir": "/var/lib/docker",
"enableNetworkPolicy": false,
"internal": false,
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.11.6-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannel_backend_type": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"nodes": [
{
"address": "REDACTED",
"hostnameOverride": "vmmllabprodproj01",
"nodeId": "c-t2xvp:m-142c085b6eff",
"port": "22",
"role": [
"worker"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "192.168.77.57",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-14b3099fd051",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-631670557442",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-63ebc7d3f2f2",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-cadffa096093",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-f4c8aa62c3fe",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
}
],
"services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"type": "/v3/schemas/clusterSpec"
},
"baseType": "cluster",
"caCert": "REDACTED",
"capacity": {
"cpu": "4",
"memory": "16432356Ki",
"pods": "110"
},
"componentStatuses": [
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "controller-manager",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-1",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-2",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-3",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-4",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "scheduler",
"type": "/v3/schemas/clusterComponentStatus"
}
],
"conditions": [
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "BackingNamespaceCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "DefaultProjectCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "SystemProjectCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "InitialRolesPopulated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "Pending"
},
{
"lastUpdateTime": "2019-01-19T00:03:26Z",
"message": "[etcd] Failed to bring up Etcd Plane: Failed to create [rke-bundle-cert] container on host [REDACTED]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
"reason": "Error",
"status": "True",
"type": "Provisioned"
},
{
"lastUpdateTime": "2019-01-18T23:53:39Z",
"status": "True",
"type": "Waiting"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "CreatorMadeOwner"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "NoDiskPressure"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "NoMemoryPressure"
},
{
"lastUpdateTime": "2019-01-23T02:16:48Z",
"status": "True",
"type": "Ready"
},
{
"lastUpdateTime": "2019-01-19T00:03:26Z",
"status": "True",
"type": "Updated"
},
{
"lastUpdateTime": "2019-01-18T23:52:58Z",
"status": "True",
"type": "GlobalAdminsSynced"
},
{
"lastUpdateTime": "2019-01-19T00:03:28Z",
"status": "True",
"type": "SystemAccountCreated"
},
{
"lastUpdateTime": "2019-01-19T00:03:29Z",
"status": "True",
"type": "AgentDeployed"
}
],
"created": "2019-01-18T23:33:36Z",
"createdTS": 1547854416000,
"creatorId": "user-brpvt",
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": null,
"desiredAgentImage": null,
"dockerRootDir": "/var/lib/docker",
"driver": "rancherKubernetesEngine",
"enableNetworkPolicy": false,
"id": "c-t2xvp",
"internal": false,
"labels": {
"cattle.io/creator": "norman"
},
"limits": {
"cpu": "10m",
"memory": "360Mi",
"pods": "0"
},
"links": {
"clusterAlerts": "…/v3/clusters/c-t2xvp/clusteralerts",
"clusterEvents": "…/v3/clusters/c-t2xvp/clusterevents",
"clusterLoggings": "…/v3/clusters/c-t2xvp/clusterloggings",
"clusterRegistrationTokens": "…/v3/clusters/c-t2xvp/clusterregistrationtokens",
"clusterRoleTemplateBindings": "…/v3/clusters/c-t2xvp/clusterroletemplatebindings",
"namespaces": "…/v3/clusters/c-t2xvp/namespaces",
"nodePools": "…/v3/clusters/c-t2xvp/nodepools",
"nodes": "…/v3/clusters/c-t2xvp/nodes",
"notifiers": "…/v3/clusters/c-t2xvp/notifiers",
"persistentVolumes": "…/v3/clusters/c-t2xvp/persistentvolumes",
"projects": "…/v3/clusters/c-t2xvp/projects",
"remove": "…/v3/clusters/c-t2xvp",
"self": "…/v3/clusters/c-t2xvp",
"shell": "wss://rancher.itel.com/v3/clusters/c-t2xvp?shell=true",
"storageClasses": "…/v3/clusters/c-t2xvp/storageclasses",
"subscribe": "…/v3/clusters/c-t2xvp/subscribe",
"update": "…/v3/clusters/c-t2xvp"
},
"name": "ml-prod",
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.11.6-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannel_backend_type": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"requested": {
"cpu": "800m",
"memory": "250Mi",
"pods": "9"
},
"state": "active",
"transitioning": "error",
"transitioningMessage": "[etcd] Failed to bring up Etcd Plane: Failed to create [rke-bundle-cert] container on host [REDACTED]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
"type": "cluster",
"uuid": "7a1b13ae-1b79-11e9-9e56-00505698f4c7",
"version": {
"buildDate": "2018-12-16T04:30:10Z",
"compiler": "gc",
"gitCommit": "b1d75deca493a24a2f87eb1efde1a569e52fc8d9",
"gitTreeState": "clean",
"gitVersion": "v1.11.6",
"goVersion": "go1.10.3",
"major": "1",
"minor": "11",
"platform": "linux/amd64",
"type": "/v3/schemas/info"
}
}
```

**Comment by Krailon** [comment]
It seems I've run into this issue as well. Cluster state is active but red. Nodes and pods are all green. Everything seems to be working but "Transitioning" value is "error". In my case I think this likely happened because I created a cluster with only master nodes without removing their taints. There was a delay between cluster creation and the first worker node joining during which several core components repeatedly failed to deploy. Here's my viewInAPI output:

```YAML
{
"actions": {
"exportYaml": "…/v3/clusters/c-t2xvp?action=exportYaml",
"generateKubeconfig": "…/v3/clusters/c-t2xvp?action=generateKubeconfig",
"importYaml": "…/v3/clusters/c-t2xvp?action=importYaml"
},
"agentImage": "rancher/rancher-agent:v2.1.5",
"allocatable": {
"cpu": "4",
"memory": "16329956Ki",
"pods": "110"
},
"annotations": {
"authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
"lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
"lifecycle.cattle.io/create.cluster-provisioner-controller": "true",
"lifecycle.cattle.io/create.cluster-scoped-gc": "true",
"lifecycle.cattle.io/create.mgmt-cluster-rbac-remove": "true"
},
"apiEndpoint": "REDACTED",
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"displayName": "ml-prod",
"dockerRootDir": "/var/lib/docker",
"enableNetworkPolicy": false,
"internal": false,
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.11.6-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannel_backend_type": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"nodes": [
{
"address": "REDACTED",
"hostnameOverride": "vmmllabprodproj01",
"nodeId": "c-t2xvp:m-142c085b6eff",
"port": "22",
"role": [
"worker"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-14b3099fd051",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-631670557442",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-63ebc7d3f2f2",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-cadffa096093",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "REDACTED",
"hostnameOverride": "REDACTED",
"nodeId": "c-t2xvp:m-f4c8aa62c3fe",
"port": "22",
"role": [
"etcd",
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
}
],
"services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"type": "/v3/schemas/clusterSpec"
},
"baseType": "cluster",
"caCert": "REDACTED",
"capacity": {
"cpu": "4",
"memory": "16432356Ki",
"pods": "110"
},
"componentStatuses": [
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "controller-manager",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-1",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-2",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-3",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-4",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "scheduler",
"type": "/v3/schemas/clusterComponentStatus"
}
],
"conditions": [
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "BackingNamespaceCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "DefaultProjectCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "SystemProjectCreated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "InitialRolesPopulated"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "Pending"
},
{
"lastUpdateTime": "2019-01-19T00:03:26Z",
"message": "[etcd] Failed to bring up Etcd Plane: Failed to create [rke-bundle-cert] container on host [REDACTED]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
"reason": "Error",
"status": "True",
"type": "Provisioned"
},
{
"lastUpdateTime": "2019-01-18T23:53:39Z",
"status": "True",
"type": "Waiting"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "CreatorMadeOwner"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "NoDiskPressure"
},
{
"lastUpdateTime": "2019-01-18T23:33:36Z",
"status": "True",
"type": "NoMemoryPressure"
},
{
"lastUpdateTime": "2019-01-23T02:16:48Z",
"status": "True",
"type": "Ready"
},
{
"lastUpdateTime": "2019-01-19T00:03:26Z",
"status": "True",
"type": "Updated"
},
{
"lastUpdateTime": "2019-01-18T23:52:58Z",
"status": "True",
"type": "GlobalAdminsSynced"
},
{
"lastUpdateTime": "2019-01-19T00:03:28Z",
"status": "True",
"type": "SystemAccountCreated"
},
{
"lastUpdateTime": "2019-01-19T00:03:29Z",
"status": "True",
"type": "AgentDeployed"
}
],
"created": "2019-01-18T23:33:36Z",
"createdTS": 1547854416000,
"creatorId": "user-brpvt",
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": null,
"desiredAgentImage": null,
"dockerRootDir": "/var/lib/docker",
"driver": "rancherKubernetesEngine",
"enableNetworkPolicy": false,
"id": "c-t2xvp",
"internal": false,
"labels": {
"cattle.io/creator": "norman"
},
"limits": {
"cpu": "10m",
"memory": "360Mi",
"pods": "0"
},
"links": {
"clusterAlerts": "…/v3/clusters/c-t2xvp/clusteralerts",
"clusterEvents": "…/v3/clusters/c-t2xvp/clusterevents",
"clusterLoggings": "…/v3/clusters/c-t2xvp/clusterloggings",
"clusterRegistrationTokens": "…/v3/clusters/c-t2xvp/clusterregistrationtokens",
"clusterRoleTemplateBindings": "…/v3/clusters/c-t2xvp/clusterroletemplatebindings",
"namespaces": "…/v3/clusters/c-t2xvp/namespaces",
"nodePools": "…/v3/clusters/c-t2xvp/nodepools",
"nodes": "…/v3/clusters/c-t2xvp/nodes",
"notifiers": "…/v3/clusters/c-t2xvp/notifiers",
"persistentVolumes": "…/v3/clusters/c-t2xvp/persistentvolumes",
"projects": "…/v3/clusters/c-t2xvp/projects",
"remove": "…/v3/clusters/c-t2xvp",
"self": "…/v3/clusters/c-t2xvp",
"shell": "wss://rancher.itel.com/v3/clusters/c-t2xvp?shell=true",
"storageClasses": "…/v3/clusters/c-t2xvp/storageclasses",
"subscribe": "…/v3/clusters/c-t2xvp/subscribe",
"update": "…/v3/clusters/c-t2xvp"
},
"name": "ml-prod",
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.11.6-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannel_backend_type": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"services": {
"etcd": {
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": true,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"requested": {
"cpu": "800m",
"memory": "250Mi",
"pods": "9"
},
"state": "active",
"transitioning": "error",
"transitioningMessage": "[etcd] Failed to bring up Etcd Plane: Failed to create [rke-bundle-cert] container on host [REDACTED]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?",
"type": "cluster",
"uuid": "7a1b13ae-1b79-11e9-9e56-00505698f4c7",
"version": {
"buildDate": "2018-12-16T04:30:10Z",
"compiler": "gc",
"gitCommit": "b1d75deca493a24a2f87eb1efde1a569e52fc8d9",
"gitTreeState": "clean",
"gitVersion": "v1.11.6",
"goVersion": "go1.10.3",
"major": "1",
"minor": "11",
"platform": "linux/amd64",
"type": "/v3/schemas/info"
}
}
```
