### ISSUE TITLE
Cannot set `true` via yaml or key-value editor for catalog apps. 

### ISSUE THREAD

**Issue by materemias** [rancher/rancher#17346]
I failed to set any of my Catalog deployment’s affinity via yaml…
If I use
```
  affinity: 
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
          - 
            matchExpressions: 
              - 
                key: "cloud.google.com/gke-preemptible"
                operator: "NotIn"
                values: 
                  - "true"
```
I always get
```
Failed to install app whatever. Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to apps/v1, Kind=Deployment: unrecognized type: string
```

The issue is with the `true` statement in values, but I cannot get how to provide it correctly so that it gets accepted.
I am aware rancher uses `--set` to assign helm values.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug (or lack of information)

**Steps to reproduce (least amount of steps as possible):**
deploy anything from catalog and set affinity from yaml

**Result:**
```
Failed to install app whatever. Error: UPGRADE FAILED: failed to create patch: failed to get versionedObject: unable to convert unstructured object to apps/v1, Kind=Deployment: unrecognized type: string
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.1.5
- Installation option: single install
