### ISSUE TITLE
Setting network config with cloudinit has no effect on vSphere Node Template

### ISSUE THREAD

**Issue by mr-rodgers** [rancher/rancher#17360]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug / Question

**Steps to reproduce (least amount of steps as possible):**
1. Using the vSphere node template, supply a cloudconfig that's similar:
```
rancher:
  network:
    interfaces:
      eth0:
        address: 172.16.0.163/22
        gateway: 172.16.0.1
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
      - 172.16.0.1
      - 8.8.8.8
```

**Result:**
According to the docs here, this should work: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/#instance-options

Instead, the cloudconfig is ignored and the node just uses DHCP to get its IP address.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 8vCPU/16GB RAM
- Kubernetes version (use `kubectl version`): v1.11.5

**Comment by mr-rodgers** [comment]
I was missing this `#cloud-config` at the start of the file.  It should look like this:

```
#cloud-config
rancher:
  network:
    interfaces:
      eth0:
        address: 172.16.0.163/22
        gateway: 172.16.0.1
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
      - 172.16.0.1
      - 8.8.8.8
```
