### ISSUE TITLE
format annotations Error when using helm.

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#17440]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create an app like stable/rabbitmq-ha
- The answer file
```yaml
---
  busyboxImage: 
    pullPolicy: "Always"
    repository: "busybox"
    tag: "latest"
  definitionsSource: "definitions.json"
  existingConfigMap: "false"
  existingSecret: "false"
  image: 
    pullPolicy: "IfNotPresent"
    repository: "rabbitmq"
    tag: "3.7.5-management-alpine"
  ingress: 
    enabled: "true"
    hostName: "rabbitmq.net"
  managementPassword: ""
  managementUsername: ""
  persistentVolume: 
    accessModes: 
      - "ReadWriteOnce"
    enabled: "true"
    name: "data"
    size: "8Gi"
    storageClass: "alicloud-nas-ssd"
  podManagementPolicy: "OrderedReady"
  rabbitmqClusterPartitionHandling: "autoheal"
  rabbitmqEpmdPort: "4369"
  rabbitmqHipeCompile: "false"
  rabbitmqManagerPort: "15672"
  rabbitmqMemoryHighWatermark: "400MB"
  rabbitmqMemoryHighWatermarkType: "absolute"
  rabbitmqNodePort: "5672"
  rabbitmqPassword: ""
  rabbitmqUsername: ""
  rbac: 
    create: "true"
  replicaCount: "2"
  resources: 
    limits: 
      cpu: "100m"
      memory: "500Mi"
    requests: 
      cpu: "100m"
      memory: "500Mi"
  service: 
    clusterIP: "172.31.14.241"
    type: "LoadBalancer"
    annotations:
      service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
      service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: "true"
      service.beta.kubernetes.io/alicloud-loadbalancer-slb-network-type: vpc
  serviceAccount: 
    create: "true"
  updateStrategy: "OnDelete"
```
- The error details.
```text
Installing
Failed to install app rabbitmq-ha-yszwz. Error: YAML parse error on rabbitmq-ha/templates/service.yaml: error unmarshaling JSON: json: cannot unmarshal object into Go struct field .annotations of type string
```

**Result:**
The annotations turned to this.
```
  service: 
    annotations: 
      service: 
        beta: 
          kubernetes: 
            io/alicloud-loadbalancer-address-type: "intranet"
            io/alicloud-loadbalancer-force-override-listeners: "true"
            io/alicloud-loadbalancer-slb-network-type: "vpc"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): alibaba cloud 8Core/16Gib
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
Containers: 89
 Running: 73
 Paused: 0
 Stopped: 16
Images: 61
Server Version: 17.06.2-ce-3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 462c82662200a17ee39e74692f536067a3576a50
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: k8s-worker002
ID: XGXJ:GWMJ:5LIB:CFEY:KMIV:C6MS:SZPT:YJYY:4J53:ZGLM:3ESD:ZN4H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://pqbap4ya.mirror.aliyuncs.com/
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```
