### ISSUE TITLE
rancher-compose fails to correctly setup L7 load balancer

### ISSUE THREAD

**Issue by sf-devops** [rancher/rancher#1746]
When using rancher-compose to recreate a load balancer, the L7 vhost/request-host definition is not correctly setup per the labels in the docker-compose.yml file.  

rancher-compose:  v0.2.5
rancher/server: v0.31.0

Working config for haproxy as reported by rancher/server export config:
```
$ cat docker-compose.yml
haproxy-stage:
  ports:
  - '80'
  external_links:
  - docker-test-stage/docker-test-stage:dts
  labels:
    io.rancher.scheduler.affinity:host_label: sf_env=stage
    io.rancher.loadbalancer.target.dts: docker-test.example.com=10001
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true

$ cat rancher-compose.yml
haproxy-stage:
  scale: 2
  load_balancer_config:
    name: haproxy-stage config
docker-test-stage:
  scale: 2
```

```
$ rancher-compose --access-key=xxx --secret-key=yyy --url=http://54.210.xxx.xxx:8080/v1 create
INFO[0000] Creating environment haproxy-stage
INFO[0000] Creating service haproxy-stage

$ rancher-compose --access-key=xxx --secret-key=yyy --url=http://54.210.xxx.xxx:8080/v1 start
INFO[0000] Project [haproxy-stage]: Starting project
INFO[0000] [0/1] [haproxy-stage]: Starting
INFO[0009] [1/1] [haproxy-stage]: Started
```
The vhost link of docker-test.example.com port 10001 is what is being problematic.  The link is created but the target port and request host fields are not populated.  

If I manually put docker-test.example.com in the request host and target port 10001 ... everything works fine again.  

Here's the L7 routing for haproxy-stage after i've run rancher-compose ... notice that the request_host and target_port are left blank:

![image](https://cloud.githubusercontent.com/assets/11682050/9102889/a5b7be90-3bbd-11e5-890d-ddb41268515c.png)

Here's the L7 routing for haproxy-stage after I've manually added the request_host and the target_port:

![image](https://cloud.githubusercontent.com/assets/11682050/9102864/80d1f758-3bbd-11e5-8a29-17c26a0cdf79.png)

After I manually re-add those two bits of info, the load balancer functions fine.    I consulted the label syntax for the vhost as described on this page:  http://docs.rancher.com/rancher/rancher-compose/rancher-services/  ... and it seems to be correct.  Plus, its what rancher/server exports after I've manually fixed it.  

```
# curl --header 'Host: docker-test.example.com' http://54.210.xxx.xxx
<h1>Hello World!</h1><p>
Host: 6b1fbf51f3d6<p>
User ip:10.42.42.156
# curl --header 'Host: docker-test.example.com' http://54.210.xxx.xxx
<h1>Hello World!</h1><p>
Host: 860da075d21f<p>
User ip:10.42.42.156
```

**Comment by alena1108** [comment]
@sf-devops the culprit is the named external link - "dts", or rather the fact that the name of the link is different from the service name. During the "io.rancher.loadbalancer.target.*" label generation when export .yml, instead of reading from the service.name, we read from the service link name - a Rancher server bug. Because rancher-compose looks up for the target service by name, not link alias, when propagate host name routing rules to rancher. 

To workaround the problem for now, just remove ":dts" portion from the yml file, so it looks like:
```
external_links:
  - docker-test-stage/docker-test-stage
```
and omit the link alias for all new links you register for Rancher LB service. Let us know how it works for you.

We will be working on the actual fix, thanks for reporting the issue

**Comment by sf-devops** [comment]
@alena1108 I had previously tried it without an alias -- and had this:

```
  external_links:
  - docker-test-stage/docker-test-stage:docker-test-stage
  labels:
    io.rancher.scheduler.affinity:host_label: sf_env=stage
    io.rancher.loadbalancer.target.docker-test-stage: docker-test.example.com=10001
```
I just reverted back to that config and it still fails to set the request_host and target_port.   I had set it to an alias because the docs seemed to indicate that it was required.  

I also tried without an alias at all:
```
  external_links:
  - docker-test-stage/docker-test-stage
  labels:
    io.rancher.scheduler.affinity:host_label: sf_env=stage
    io.rancher.loadbalancer.target.docker-test-stage: docker-test.example.com=10001
```

And it still fails to set those 2 bits.
