### ISSUE TITLE
LB source port not set in HAProxy config

### ISSUE THREAD

**Issue by SeerUK** [rancher/rancher#1747]
Hi there,

I'm currently attempting to set up a load balancer. I've attempted to make this LB only respond with a given host and port. Unfortunately, the source port entered does not make it's way into the HAProxy config.

This is as close it comes to getting it right:
https://github.com/rancher/cattle/blob/master/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl#L41

If a port is specified it should be included in that host header, otherwise HAProxy simply responds with a 503, as no backend will match.

As a result, it appears that this will only ever work if your source port is 80 currently, unless I'm doing something wrong.

Rancher v0.31.0
Cattle v0.73.0
User Interface v0.39.0
Rancher Compose beta/latest
Docker version 1.7.1, build 786b29d
Ubuntu 14.04 x64

If I have some time soon enough then I'll submit a PR for this issue.

**Comment by haswalt** [comment]
I had the same issue. In my cas I was trying to send to different containers based of path.

**Comment by deniseschannon** [comment]
@SeerUK Can you share your docker-compose.yml? This can be exported from the Rancher UI on the stack if you click on this button in the stack view. 

![screen shot 2015-08-03 at 10 16 35 am](https://cloud.githubusercontent.com/assets/11410997/9116613/2494191e-3c1a-11e5-9d11-5467f0d6aade.png)

Did you make sure to also include your source port in the listening ports section of the LB? It must be in the listening port and not only the advanced routing rules section.

**Comment by SeerUK** [comment]
Here's how I configured it: https://www.dropbox.com/s/2kppe7kavfnliak/Screenshot%202015-08-06%2017.27.34.png?dl=0

Here's my docker-compose.yml:

```
jenkins:
  ports:
  - 13001:8080/tcp
  restart: 'no'
  tty: true
  image: jenkins:1.609.2
  stdin_open: true
jenkins-lb:
  ports:
  - 13101:8080
  labels:
    io.rancher.loadbalancer.target.jenkins: strident.jenkins.io:13101
  tty: true
  image: rancher/load-balancer-service
  links:
  - jenkins:jenkins
  stdin_open: true
```

I have manually entered the LB container and edited the HAProxy config to include the port in the host header, and it works instantly after restarting HAProxy then. The issue seems to be that the port is not included in the config file when it's made, and from looking at the template, it doesn't look like it can be currently.
