### ISSUE TITLE
Cluster level alert for a normal pod event does not get sent out 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17472]
Version: Master

**Cluster information**
Single node

Steps:
1. Create a DO cluster
2. Set up a notifier using slack
3. Create an alert at the cluster level for a normal pod event. Set the alert to send critical event.
4. Create a pod "test1" in the default project, alert gets sent as expected.
5. Create a new project and create a pod "testnew" in the new project.

Alert does not get sent for the new pod . The alert manager receives the alert event, but the alert does not get sent out.

<img width="995" alt="screen shot 2019-01-17 at 1 48 28 pm" src="https://user-images.githubusercontent.com/18536626/51351026-93c63800-1a5e-11e9-8cd1-feadcf619578.png">

Alert manager config
```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  slack_api_url: <secret>
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: rancherlabs
  routes:
  - receiver: c-cckdn:event-alert
    match:
      group_id: c-cckdn:event-alert
    routes:
    - match:
        alert_type: event
        rule_id: c-cckdn:event-alert_deployment-event-alert
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 1h
    - match:
        alert_type: event
        rule_id: c-cckdn:event-alert_car-59c6s
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 1h
    group_wait: 3m
    group_interval: 3m
    repeat_interval: 1h
  group_wait: 1m
  group_interval: 10s
  repeat_interval: 1h
receivers:
- name: rancherlabs
  slack_configs:
  - send_resolved: false
    http_config: {}
    api_url: <secret>
    channel: '#alert'
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title: '{{ template "slack.default.title" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "slack.default.text" . }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
- name: c-cckdn:event-alert
  slack_configs:
  - send_resolved: false
    http_config: {}
    api_url: <secret>
    channel: '@soumya'
    username: '{{ template "slack.default.username" . }}'
    color: '{{ if eq (index .Alerts 0).Labels.severity "critical" }}danger{{ else
      if eq (index .Alerts 0).Labels.severity "warning" }}warning{{ else }}good{{
      end }}'
    title: '{{ template "rancher.title" . }}'
    pretext: '{{ template "slack.default.pretext" . }}'
    text: '{{ template "slack.text" . }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: '{{ template "slack.default.iconemoji" . }}'
    icon_url: '{{ template "slack.default.iconurl" . }}'
templates:
- /etc/alertmanager/config/notification.tmpl





```
