### ISSUE TITLE
etcd restore from S3 backup fails for a broken cluster and healthy cluster

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17503]
Version: Master
K8s version: 1.11.6

**Steps to reproduce (least amount of steps as possible):**
1. Create a DO cluster with 3 nodes having all roles in each
2. Create workloads/ingress
3. Edit the cluster and provide S3 backup config as below:
```
backup_config:
      interval_hours: 1
      retention: 3
      s3_backup_config:
        access_key: abcdef
        secret_key: KEY
        bucket_name: rkebackuptest
        endpoint: s3.amazonaws.com

```
4. Wait for cluster update to complete and allow backup to be created in S3
5. Break the cluster by deleting the etcd containers in two hosts
6. Restore the cluster by performing `restoreFromEtcdBackup` action. Choose the backup to restore from.
7. Cluster goes to updating state, but restore fails to complete. Cluster is stuck in "Updating" state with error 
![screen shot 2019-01-21 at 4 22 11 pm](https://user-images.githubusercontent.com/18536626/51504949-b75bec00-1d98-11e9-96b4-ca0640846dff.png)

API info below:
```
"state": "updating",
"transitioning": "error",
"transitioningMessage": "etcd snapshots are not consistent",
"type": "cluster",
"uuid": "7d07bdb2-1dce-11e9-be33-dfdfdfdfd",
```
