### ISSUE TITLE
Pipeline applyApp step to upgrade cluster and project level catalog app failed

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#17511]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Add cluster and project level catalog
2. Edit Pipeline Configuration
3. Select the cluster and project level catalog in the pipeline applyApp step
4. Run the pipeline and run successfully
5. Run the pipeline again and it will perform the upgrade

```
 .rancher-pipeline.yml

stages:
- name: project-level
  steps:
  - applyAppConfig:
      catalogTemplate: p-jnrpd:test-fluentd
      version: 1.0.0
      name: fluent-test
      targetNamespace: default
    when:
      branch: {}
- name: cluster-level
  steps:
  - applyAppConfig:
      catalogTemplate: c-8pfgw:test-cluster-mongodb
      version: 4.8.4
      name: mogodb-test
      targetNamespace: default
    when:
      branch: {}
- name: global-level
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:test-global-mysql
      version: 0.10.2
      name: mysql-test
      targetNamespace: default
timeout: 60
notification: {}
```

**Result:**

1. CatalogTemplate should not use a colon connection
2. Cluster and project level catalog app upgrade error

```
09:00:55 [pipeline_p-tdrqz-6] Running shell script
09:00:58 + apply-app
09:00:58 [INFO]check done...
09:00:58 [INFO]prepare config done...
09:00:58 time="2019-01-22T09:00:58Z" level=info msg="Saving config to /root/.rancher/cli2.json"
09:00:58 [INFO]refreshing catalog
09:01:10 EXITCODE   0[INFO]upgrading the "fluent-test" app
09:01:10 time="2019-01-22T09:01:08Z" level=fatal msg="version 1.0.0 not valid for app"
```

**Other details that may be helpful:**

Global level catalog app can be upgraded successfully.
