### ISSUE TITLE
Global DNS UI: Add option for cloudflare provider in UI

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#17551]
Version: 2.2 master (1/23/19) HA setup

The Cloudflare provider support for global dns is merged in the backend and can be added now to the UI, the cloudflare global dns object will look like that:

```
apiVersion: management.cattle.io/v3
kind: GlobalDnsProvider
metadata:
  name: <deployment-name>
spec:
  cloudflareProviderConfig:
    apiEmail: xxxx@xxxx
    rootDomain: xxxxxxxxxx
    apiKey: xxxxxxxxxxxxxxx
```
https://github.com/rancher/rancher/pull/17525
