### ISSUE TITLE
kubeadm 1.13.2 & helm 1.12.2 install rancher v2.1.5 loop 308

### ISSUE THREAD

**Issue by lanmingle** [rancher/rancher#17574]
kubeadm-config.yaml
``` yaml

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  scheduler: wrr

---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
clusterName: tencent
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
    - apiserver.vip
controlPlaneEndpoint: apiserver.vip:6443

```

ipvs
``` bash

rm -rf /etc/sysconfig/modules/ipvs.modules

cat > /etc/sysconfig/modules/ipvs.modules <<EOF
#!/bin/bash
ipvs_modules="ip_vs ip_vs_lc ip_vs_wlc ip_vs_rr ip_vs_wrr ip_vs_lblc ip_vs_lblcr ip_vs_dh ip_vs_sh ip_vs_fo ip_vs_nq ip_vs_sed ip_vs_ftp nf_conntrack"
for kernel_module in \${ipvs_modules}; do
  /sbin/modinfo -F filename \${kernel_module} > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    /sbin/modprobe \${kernel_module}
  fi
done
EOF

chmod 755 /etc/sysconfig/modules/ipvs.modules && bash /etc/sysconfig/modules/ipvs.modules && lsmod | grep ip_vs

```

kube

``` bash

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

NAME      STATUS   ROLES    AGE     VERSION
prod244   Ready    <none>   6h8m    v1.13.2
prod245   Ready    <none>   6h8m    v1.13.2
prod246   Ready    <none>   6h8m    v1.13.2
prod247   Ready    master   6h9m    v1.13.2
prod248   Ready    master   6h10m   v1.13.2
prod249   Ready    master   6h12m   v1.13.2

```

cert-manager

``` yaml
# https://github.com/helm/charts/blob/master/stable/cert-manager

# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  # repository: quay.io/jetstack/cert-manager-controller
  # tag: v0.5.2
  pullPolicy: IfNotPresent

createCustomResource: true

# Override the namespace used to store DNS provider credentials etc. for ClusterIssuer
# resources. By default, the same namespace as cert-manager is deployed within is
# used. This namespace will not be automatically created by the Helm chart.
# clusterResourceNamespace: "kube-system"

# leaderElection:
  # Override the namespace used to store the ConfigMap for leader election
  # namespace: "kube-system"

# certificateResourceShortNames: ["cert", "certs"]

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # name:

# Optional additional arguments
# extraArgs: []
  # Use this flag to set a namespace that cert-manager will use to store
  # supporting resources required for each ClusterIssuer (default is kube-system)
  # - --cluster-resource-namespace=kube-system

# extraEnv: []
# - name: SOME_VAR
#   value: 'some value'

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 75m
    memory: 128Mi

# podAnnotations: {}

# podLabels: {}
# Optional DNS settings, useful if you have a public and private DNS zone for
# the same domain on Route 53. What follows is an example of ensuring
# cert-manager can access an ingress or DNS TXT records at all times.
# NOTE: This requires Kubernetes 1.10 or `CustomPodDNS` feature gate enabled for
# the cluster to work.
# podDnsPolicy: "None"
# podDnsConfig:
#   nameservers:
#     - "1.1.1.1"
#     - "8.8.8.8"

# nodeSelector: {}

ingressShim:
  defaultIssuerName: "letsencrypt-staging"
  defaultIssuerKind: "ClusterIssuer"
  defaultACMEChallengeType: "http01"
  # defaultACMEDNS01ChallengeProvider: ""

webhook:
  enabled: false

# This is used by the static manifest generator in order to create a static
# namespace manifest for the namespace that cert-manager is being installed
# within. It should **not** be used if you are using Helm for deployment.
createNamespaceResource: false

# Use these variables to configure the HTTP_PROXY environment variables
# http_proxy: "http://proxy:8080"
# http_proxy: "http://proxy:8080"
# no_proxy: 127.0.0.1,localhost

# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
# for example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
# affinity: {}

# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#toleration-v1-core
# for example:
#   tolerations:
#   - key: foo.bar.com/role
#     operator: Equal
#     value: master
#     effect: NoSchedule
# tolerations: []

```

``` bash

helm install stable/cert-manager \
--name="cert-manager" \
--namespace="kube-system" \
-f ./values.yaml

```

rancher

``` yaml
# https://github.com/rancher/server-chart/blob/master/rancher

# Additional Trusted CAs.
# Enable this flag and add your CA certs as a secret named tls-ca-additional in the namespace.
# See README.md for details.
# additionalTrustedCAs: false

# antiAffinity: preferred

# Audit Logs https://rancher.com/docs/rancher/v2.x/en/installation/api-auditing/
# The audit log is piped to the console of the rancher-audit-log container in the rancher pod.
# https://rancher.com/docs/rancher/v2.x/en/installation/api-auditing/
# destination stream to sidecar container console or hostPath volume
# level: Verbosity of logs, 0 to 3. 0 is off 3 is a lot.
# auditLog:
#   destination: sidecar
#   hostPath: /var/log/rancher/audit/
#   level: 0
#   maxAge: 1
#   maxBackup: 1
#   maxSize: 100

# Have Rancher detect and import the "local" Rancher server cluster
# Adding the "local" cluster available in the GUI can be convenient, but any user with access to this cluster has "root" on any of the clusters that Rancher manages.
# options; "auto", "false". (auto pretty much means true)
addLocal: "false"
# Add debug flag to Rancher server
# debug: false

# Fully qualified name to reach your Rancher server
hostname: rancher.lmlily.com

## Optional array of imagePullSecrets containing private registry credentials
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# imagePullSecrets: []
# - name: secretName

### ingress ###
# Readme for details and instruction on adding tls secrets.
ingress:
  extraAnnotations:
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  tls:
    # rancher, letsEncrypt, secrets
    source: rancher

### LetsEncrypt config ###
# ProTip: The production environment only allows you to register a name 5 times a week.
#         Use staging until you have your config right.
# letsEncrypt:
#   email: lanmingle@qq.com
#   environment: production

# If you are using certs signed by a private CA set to 'true' and set the 'tls-ca'
# in the 'rancher-system' namespace. See the README.md for details
# privateCA: false

# http[s] proxy server passed into rancher server.
# proxy: http://<username>@<password>:<url>:<port>

# comma separated list of domains or ip addresses that will not use the proxy 
# noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 

# Override rancher image location for Air Gap installs
# rancherImage: rancher/rancher
# rancher/rancher image tag. https://hub.docker.com/r/rancher/rancher/tags/
# Defaults to .Chart.appVersion
# rancherImageTag: v2.1.5

# Number of Rancher server replicas.
replicas: 2

# Set pod resource requests/limits for Rancher.

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 75m
    memory: 128Mi

# tls
#   Where to offload the TLS/SSL encryption
# - ingress (default)
# - external
# tls: ingress

```

``` bash
#!/bin/bash

helm install rancher-stable/rancher \
--name="rancher" \
--namespace="cattle-system" \
-f ./values.yaml

```
