### ISSUE TITLE
[rancher-dns] [rancher-compose] Support reverse dot notation for links to service in a different stack

### ISSUE THREAD

**Issue by phallguy** [rancher/rancher#1758]
From rancher compose docs, the following creates an external link to db1 in the alldbs stack with the name mysql inside the wordpress container.

```
wordpress:
  image: wordpress
  external_links:
    - alldbs/db1:mysql
```

I propose that an external link to a different stack, that has not been given a custom name, use reverse dot notation for it's dns name within the container. For example

```
wordpress:
  image: wordpress
  external_links:
    - etcd/console
```

Should create a dns entry `console.etcd` within the wordpress container. If you forget to provide a custom name, it simply maps the external link name as is which is not a valid DNS name:

```
ETCD_CONSOLE_1_PORT=tcp://etcd/console:8080
ETCD_CONSOLE_1_PORT_8080_TCP_ADDR
```
