### ISSUE TITLE
Healthchecks for external services

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#1773]
As external service can act as a LB service target, we should support healtchecks for this type of service too. Otherwise any external ip/port that can't be reached, won't be excluded from the list of healthy Lb targets.

@will-chan @ibuildthecloud

**Comment by alena1108** [comment]
Rancher-compose changes are needed

**Comment by sangeethah** [comment]
Tested with build from master - Sep 15

Enabled health check for  external service using the following rancher-compose.yml.

```
test1:
  external_ips:
  - 10.42.52.21
  - 10.42.243.225
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /name.html HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
```
I see that health_check parameters being set for the external service.

Scenario1:

Created a service - "testc" which links to external service with linkname - "testlinkme".

When I did - dig on testc it returns both ip addresses - 10.42.52.21 and 10.42.243.225.

Stopped container  with ip address 10.42.243.225 , so that it is not reachable.

When I did - dig on testc it still returns both ip addresses - 10.42.52.21 and 10.42.243.225.

Expected behavior here is for dig to return only 10.42.52.21.

Scenario 2:

When I used this external service as target for LB service , I see health checks being configured in LB for this target:

```
        option httpchk GET /name.html HTTP/1.0                                  
        server 7a0f80dc-11df-42be-8347-8e9b43098971 10.42.243.225:80 check port 
80 inter 2000 rise 2 fall 3                                                     
        server 79515a0e-f0b0-486e-a3da-363cf5b9c874 10.42.52.21:80 check port 80
 inter 2000 rise 2 fall 3                                                       
```

This works as expected.

Reopened this issue to handle health check for external services when they are linked services.
