### ISSUE TITLE
Envvar substitution in pipeline configs is broken

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#17757]
**Rancher Version**
master 1/30

**Steps to reproduce (least amount of steps as possible):**
1. Add the following pipeline:
```
stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo $FOO
    env:
      FOO: ${CICD_GIT_BRANCH}
```

**Result:**
```
14:50:31 [pipeline_p-wlmkp-2] Running shell script
14:50:33 + echo '${CICD_GIT_BRANCH}'
14:50:33 ${CICD_GIT_BRANCH}
```
**Expected Result**
`${CICD_GIT_BRANCH}` is substituted to specific branch name.

**Comment by loganhz** [comment]
I will validate this issue

**Comment by cjellick** [comment]
@loganhz to validate

**Comment by loganhz** [comment]
Validated on rancher/rancher:master 02/21

Steps to validate:

1. Add the following pipeline:
```
stages:
- name: Build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo $FOO
    env:
      FOO: ${CICD_GIT_BRANCH}
```

**Result:**
It prints the branch name
