### ISSUE TITLE
Assigning jobs to pipeline engine; buildinfo result failure

### ISSUE THREAD

**Issue by arbermarleku** [rancher/rancher#17858]
In  my YAML scritp i dont have the {} like like users had in this url :
https://github.com/rancher/rancher/issues/17120

My Yml is down bellow
Can you give me a hint what i am doing wrong

```
stages:
- name: Build Backend
  steps:
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :api:shadowJar
    when:
      branch:
        include:
        - api*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :collector:shadowJar
    when:
      branch:
        include:
        - collector*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :consumer:shadowJar
    when:
      branch:
        include:
        - consumer*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :sync:shadowJar
    when:
      branch:
        include:
        - sync*
      event:
        include:
        - tag
- name: Publish to QA
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/qa/Dockerfile
      buildContext: .
      tag: myproject-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/qa/Dockerfile
      buildContext: .
      tag: myproject-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/qa/Dockerfile
      buildContext: .
      tag: myproject-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-qa*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/qa/Dockerfile
      buildContext: .
      tag: myproject-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-qa*
      event:
        include:
        - tag
- name: Publish to Staging
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/stagign/Dockerfile
      buildContext: .
      tag: myproject-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/stagign/Dockerfile
      buildContext: .
      tag: myproject-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/stagign/Dockerfile
      buildContext: .
      tag: myproject-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-staging*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/stagign/Dockerfile
      buildContext: .
      tag: myproject-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-staging*
      event:
        include:
        - tag
- name: Publish to Production
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/prod/Dockerfile
      buildContext: .
      tag: myproject-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - api-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/prod/Dockerfile
      buildContext: .
      tag: myproject-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - collector-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/prod/Dockerfile
      buildContext: .
      tag: myproject-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - consumer-production*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/prod/Dockerfile
      buildContext: .
      tag: myproject-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.docker.com
    when:
      branch:
        include:
        - sync-production*
      event:
        include:
        - tag
- name: Deploy to QA
  steps:
  - applyYamlConfig:
      path: .k8s/api/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - api-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/collector/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - collector-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/consumer/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - consumer-qa*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/sync/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - sync-qa*
      event:
        include:
        - tag
- name: Deploy to Staging
  steps:
  - applyYamlConfig:
      path: .k8s/api/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - api-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/collector/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - collector-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/consumer/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - consumer-staging*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: .k8s/sync/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - sync-staging*
      event:
        include:
        - tag
- name: Deploy to Production
  steps:
  - applyYamlConfig:
      path: k8s/api/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - api-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/collector/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - collector-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/consumer/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - consumer-production*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/sync/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - sync-production*
      event:
        include:
        - tag

```

_Originally posted by @arbermarleku in https://github.com/rancher/rancher/issues/17120#issuecomment-459767858_
