### ISSUE TITLE
Rancher 2.2.0-alpha6 cannot deploy workload

### ISSUE THREAD

**Issue by gioppoluca** [rancher/rancher#17877]
**bug:**

**Steps to reproduce:**
Scratch new installation, created a cluster (single node to be fast).
Activate monitoring to try it out (just activated and saved, do not know if is the right way, appeared the option to go to configure, but getting FAULT since it appears not to be able to load resources).
I reload the page and try to go to cluster and deploy anyway a workload.
Click on workload and BOOM:
Loading chunk 10 failed. (missing: https://rancher.sdp.csi.it/p/c-2qnhs:p-b6vfv/chunk.b91cb99f7120f4ec08ad.js)

**Result:**
Cannot deploy

**Other details that may be helpful:**
I'm behind corporate proxy so I have HTTP_PROXY set in various docker files

The cluster page also says:

Monitoring API is not ready

**Environment information**
- Rancher version : 2.2.0-alpha6
- Installation option (single install):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
addon_job_timeout: 30
authentication: 
  strategy: "x509|webhook"
bastion_host: 
  ssh_agent_auth: false
dns: 
  provider: "kube-dns"
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.13.1-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  options: 
    flannel_backend_type: "vxlan"
  plugin: "canal"
restore: 
  restore: false
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    backup_config: 
      interval_hours: 12
      retention: 6
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: false
  kube-api: 
    always_pull_images: false
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet: 
    cluster_domain: "sdp.csi.it"
    fail_swap_on: false
ssh_agent_auth: false
agent_image: "rancher/rancher-agent:v2.2.0-alpha6"
allocatable: 
  cpu: "4"
  memory: "3778564Ki"
  pods: "110"
annotations: 
  authz.management.cattle.io/creator-role-bindings: "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}"
  field.cattle.io/overwrite_monitoring_app_answers: "{\"answers\":{\"_key-Data_Retention\":\"prometheus.retention\",\"_key-Node_Exporter_Host_Port\":\"exporter-node.ports.metrics.port\",\"_key-Grafana_Storage_Enabled\":\"grafana.persistence.enabled\",\"_key-Grafana_Storage_Size\":\"grafana.persistence.size\",\"_key-Grafana_Storage_Class\":\"grafana.persistence.storageClass\",\"_key-Prometheus_Storage_Enabled\":\"prometheus.persistence.enabled\",\"_key-Prometheus_Storage_Size\":\"prometheus.persistence.size\",\"_key-Prometheus_Storage_Class\":\"prometheus.persistence.storageClass\",\"_tpl-Node_Selector\":\"nodeSelector#(prometheus,grafana,exporter-kube-state)\",\"prometheus.retention\":\"360h\",\"exporter-node.ports.metrics.port\":\"9100\",\"grafana.persistence.enabled\":\"false\",\"prometheus.persistence.enabled\":\"false\",\"prometheus.persistence.storageClass\":\"default\",\"grafana.persistence.storageClass\":\"default\",\"grafana.persistence.size\":\"10Gi\",\"prometheus.persistence.size\":\"50Gi\"}}"
  lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
  lifecycle.cattle.io/create.cluster-provisioner-controller: "true"
  lifecycle.cattle.io/create.cluster-scoped-gc: "true"
  lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
  networking.management.cattle.io/enable-network-policy: "true"
api_endpoint: "https://10.102.67.67:6443"
applied_enable_network_policy: true
applied_spec: 
  display_name: "sdptools"
# 
#   # Rancher Config
# 
  docker_root_dir: "/var/lib/docker"
  enable_cluster_alerting: false
  enable_cluster_monitoring: false
  enable_network_policy: true
  internal: false
  local_cluster_auth_endpoint: 
    enabled: true
  rancher_kubernetes_engine_config: 
    addon_job_timeout: 30
    authentication: 
      strategy: "x509|webhook"
    bastion_host: 
      ssh_agent_auth: false
    dns: 
      provider: "kube-dns"
    ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
    ingress: 
      provider: "nginx"
    kubernetes_version: "v1.13.1-rancher1-1"
    monitoring: 
      provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
    network: 
      options: 
        flannel_backend_type: "vxlan"
      plugin: "canal"
    nodes: 
      - 
        address: "10.102.67.67"
        hostname_override: "kubenode1"
        labels: null
        node_id: "c-2qnhs:m-323a0c836708"
        port: "22"
        role: 
          - "etcd"
          - "controlplane"
          - "worker"
        ssh_agent_auth: false
        user: "root"
    restore: 
      restore: false
# 
#      services:
#        kube_api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube_controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
    services: 
      etcd: 
        backup_config: 
          interval_hours: 12
          retention: 6
        creation: "12h"
        extra_args: 
          election-timeout: "5000"
          heartbeat-interval: "500"
        retention: "72h"
        snapshot: false
      kube-api: 
        always_pull_images: false
        pod_security_policy: false
        service_node_port_range: "30000-32767"
      kubelet: 
        cluster_domain: "sdp.csi.it"
        fail_swap_on: false
    ssh_agent_auth: false
auth_image: "erikwilson/kube-api-auth:latest"
ca_cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKTFdOaE1CNFhEVEU1TURJd05qQTROREl5TTFvWERUSTVNREl3TXpBNE5ESXlNMW93RWpFUU1BNEdBMVVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU0zQXV6RGZ3T09lClg2ZDU5WWRWVGtsQ3UyaHVySElCV3RIc3F1bXJNU25WZEFKKzJZSHZxV0tRWU1iQU1leGN1ZkYxRXpOSjJRMlMKQitxMEVKblRNbUM3a1Z6aSt1cmpJMlFRNkgvbXUrNDhiQ2NOMEQ2MEMxNk01VExSV1E4bzBxUEc3eFVuUUU3Nwp3cWFHazRMMS9RQU5McklCaThSbGI2OU9TYlRVVmNnMDd5Q256N3hWMHFzZE0yNnovSS8zTGtFcXJjMzU2dlJUCjFabUJHS0k4djVLUHBnbGRodmlBQ1JoS2haazRMN0pvdEE5RXVFaHYxaER5WkRuOG92blNGZ2FUMGRnTFhZVmIKZ29pRTZ2WjBaUHNCVFFVREhkRy80cE5yb2Z0WTlVNlR3U2lTSkxYeGFzU2dYZXFBNTIxNGhIMXlkQndSL29pdApHc3RINzJjUXJWc0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQWVSUTh6bnNRWGFzbmREc1RZT1ZtczV4SW5xU3Uwa1J2Q2kKd1JBUzU4a0VxOC93VHQ4K2RNQnhzcjVmU1VLL1hodWRTSlBFeFZXK3dEbFdzejVlbW0wY25lN1BoSGlUdlNHRQo0MGFsU3VCMGt5UE1Hc1M2ek4zVC9YT3B4WjcxcEZwOGdvZTRtSGQ4U2g5UWJRbFIvYWgwaVFvM2t5MEUwbWNWClhuMkFrTTNkM0xRaklodk14aHB6L3I0dHNNRXlRcFdYOXh2Y1B4dWQ4ZXFXQ3FyTHljSFVuTXR2bHo2bEdxZG4KZFF0QVR3anVIank4bjRqODBmUmZUTkVuUjBrWkFtL0MrOGtva1FKSkxGbnA4V2RZeitSbkdXT2dMODlhTWZzQQoyckpaZTd4ckFXQng0ei9udXExZnp5MEdCTjRwOWNsOHM0RXhqcmJtOFVXNER5eDJONjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
capabilities: 
  ingress_capabilities: 
    - 
      custom_default_backend: false
      ingress_provider: "Nginx"
  load_balancer_capabilities: 
    enabled: false
    health_check_supported: false
  node_pool_scaling_supported: false
  node_port_range: "30000-32767"
capacity: 
  cpu: "4"
  memory: "3880964Ki"
  pods: "110"
component_statuses: 
  - 
    conditions: 
      - 
        message: "ok"
        status: "True"
        type: "Healthy"
    name: "controller-manager"
  - 
    conditions: 
      - 
        message: "{\"health\": \"true\"}"
        status: "True"
        type: "Healthy"
    name: "etcd-0"
  - 
    conditions: 
      - 
        message: "ok"
        status: "True"
        type: "Healthy"
    name: "scheduler"
conditions: 
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "BackingNamespaceCreated"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "DefaultProjectCreated"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "SystemProjectCreated"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "InitialRolesPopulated"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "CreatorMadeOwner"
  - 
    last_update_time: "2019-02-06T08:42:17Z"
    status: "True"
    type: "Pending"
  - 
    last_update_time: "2019-02-06T08:44:36Z"
    status: "True"
    type: "Provisioned"
  - 
    last_update_time: "2019-02-06T08:44:52Z"
    status: "True"
    type: "Waiting"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "NoDiskPressure"
  - 
    last_update_time: "2019-02-06T08:39:13Z"
    status: "True"
    type: "NoMemoryPressure"
  - 
    last_update_time: "2019-02-06T08:44:40Z"
    status: "True"
    type: "GlobalAdminsSynced"
  - 
    last_update_time: "2019-02-06T08:46:59Z"
    status: "True"
    type: "PrometheusOperatorDeployed"
  - 
    last_update_time: "2019-02-06T08:44:48Z"
    status: "True"
    type: "SystemAccountCreated"
  - 
    last_update_time: "2019-02-06T08:44:49Z"
    status: "True"
    type: "AgentDeployed"
  - 
    last_update_time: "2019-02-06T08:44:52Z"
    status: "True"
    type: "Ready"
  - 
    last_update_time: "2019-02-06T08:45:44Z"
    status: "True"
    type: "Updated"
  - 
    last_update_time: "2019-02-06T08:45:03Z"
    status: "True"
    type: "ServiceAccountMigrated"
  - 
    last_update_time: "2019-02-06T08:49:22Z"
    message: "[Grafana Deployment isn't deployed, Kube State Exporter Deployment isn't deployed, Prometheus StatefulSet isn't deployed, Node Exporter DaemonSet isn't deployed]"
    status: "Unknown"
    type: "MonitoringEnabled"
created: "2019-02-06T08:39:13Z"
creator_id: "user-4kdvr"
# 
#   # Rancher Config
# 
docker_root_dir: "/var/lib/docker"
driver: "rancherKubernetesEngine"
enable_cluster_alerting: false
enable_cluster_monitoring: true
enable_network_policy: true
id: "c-2qnhs"
internal: false
labels: 
  cattle.io/creator: "norman"
limits: 
  cpu: "10m"
  memory: "190Mi"
  pods: "0"
local_cluster_auth_endpoint: 
  enabled: true
monitoring_status: 
  conditions: 
    - 
      last_update_time: "2019-02-06T08:47:04Z"
      message: "Grafana Deployment isn't deployed"
      reason: "Error"
      status: "False"
      type: "GrafanaDeployed"
    - 
      last_update_time: "2019-02-06T08:47:04Z"
      message: "Node Exporter DaemonSet isn't deployed"
      reason: "Error"
      status: "False"
      type: "NodeExporterDeployed"
    - 
      last_update_time: "2019-02-06T08:47:04Z"
      message: "Kube State Exporter Deployment isn't deployed"
      reason: "Error"
      status: "False"
      type: "KubeStateExporterDeployed"
    - 
      last_update_time: "2019-02-06T08:47:04Z"
      message: "Prometheus StatefulSet isn't deployed"
      reason: "Error"
      status: "False"
      type: "PrometheusDeployed"
    - 
      last_update_time: "2019-02-06T08:47:06Z"
      status: "True"
      type: "MetricExpressionDeployed"
name: "sdptools"
requested: 
  cpu: "540m"
  memory: "140Mi"
  pods: "9"
state: "active"
transitioning: "no"
uuid: "ae4c3813-29ea-11e9-80c8-0242ac110002"
version: 
  build_date: "2018-12-13T10:31:33Z"
  compiler: "gc"
  git_commit: "eec55b9ba98609a46fee712359c7b5b365bdd920"
  git_tree_state: "clean"
  git_version: "v1.13.1"
  go_version: "go1.11.2"
  major: "1"
  minor: "13"
  platform: "linux/amd64"

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
