### ISSUE TITLE
hostPort settings get lost when using "Redeploy" on a workload

### ISSUE THREAD

**Issue by micw** [rancher/rancher#17878]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Create the following deployment :
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: test
  name: test
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
        name: test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8123
          name: http
          protocol: TCP
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
Klick "redeploy" on the test workload in the rancher UI 

**Result:**
The setting "hostPort: 8123" is missing after redeploy. The container is not listening anymore on this host port.

**Other details that may be helpful:**

**Environment information**

Rancher | v2.1.3
User Interface | v2.1.17
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1
(Single-Node Rancher)

**Cluster information**
- Cluster type Custom
- Machine type metal
- Kubernetes version (use `kubectl version`): v1.12.3

**Comment by talisto** [comment]
I've noticed this also happens when upgrading a container via Workloads > Edit > Upgrade.

**Comment by talisto** [comment]
I just figured out that a workaround is to include the `field.cattle.io/ports` annotation.  So in your example it would be:

```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: test
  name: test
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"hostPort":8123,"kind":"HostPort","name":"http","protocol":"TCP","sourcePort":8123}]]'
      labels:
        app: test
        name: test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8123
          name: http
          protocol: TCP
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

That appears to survive upgrades and redeploys.
