### ISSUE TITLE
[server-chart] use http /healthz for pod health.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17948]
Change pod health checks from basic tcp to the http `/healthz` endpoint. Monitoring the http endpoint is a little bit better for determining when rancher is up and ready for requests.  

rancher/server-chart#74 for server-chart

**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Comment by jgreat** [comment]
#17950 for rancher/rancher

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/14
server chart: rancher-0.0.0-1550095146.master.8f361af9

* Install Rancher via Helm
* Check Rancher deployment: `kubectl get deployment rancher -o yaml -n cattle-system`
```
...

readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP

...

livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP

...
```
