### ISSUE TITLE
[server-chart] Make busybox image location configurable

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#17946]
Air Gap installs that want to configure the rancher audit log may need to configure the image repo for busybox container used to capture the logs for shipping.

https://github.com/rancher/server-chart/pull/78 addresses this for server-chart.
#17945 for rancher

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Comment by bmdepesa** [comment]
rancher/rancher:master 2/14
server chart: rancher-0.0.0-1550095146.master.8f361af9

* Installed Rancher via helm with:
```
helm install ./ --name rancher \
  --namespace cattle-system \
  --set hostname=brandonha.qa.rancher.space \
  --set rancherImageTag=master \
  --set busyboxImage=prom/busybox:latest \
  --set auditLog.level=1
```

* Check rancher deployment: `kubectl get deployment rancher -o yaml -n cattle-system`
```
...
- args:
        - -F
        - /var/log/auditlog/rancher-api-audit.log
        command:
        - tail
        image: prom/busybox:latest
        imagePullPolicy: Always
...
```
