### ISSUE TITLE
Change Rancher Persistent Volume Longhorn to use CSI driver instead of Flexvolume driver

### ISSUE THREAD

**Issue by yasker** [rancher/rancher#17972]
CSI is the default driver for Kubernetes 1.10+.

The yaml spec for CSI looks like this:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-vol-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeAttributes:
      fromBackup: ""
      numberOfReplicas: '3'
      staleReplicaTimeout: '30'
    volumeHandle: <existing-longhorn-volume-name>
```

If a PV is manually created, it must have `volumeHandle` pointed to an **existing** Longhorn volume. It's the limitation of CSI at the moment. So the user must provide input to `volumeHandle` field.

**Comment by yasker** [comment]
This will help https://github.com/rancher/longhorn/issues/388

**Comment by alena1108** [comment]
As a part of the fix, we have to:

* figure out the configurable way of enabling csi support for specific storage drivers only (like honghorn)
* see if API support is enabled for csi field
* address the UI for csi configuration

**Comment by alena1108** [comment]
Moving out of 2.2 milestone as we don't have enough time to implement conditional csi/flex logic by the 2.2 code freeze. Should consider making a feature a part of 2.2.1 release. Till then, the workaround would be to configure pv using kubectl

**Comment by bkalai321** [comment]
If a PV is manually created, it must have volumeHandle pointed to an existing Longhorn volume. It's the limitation of CSI at the moment.
how to do this from cli

**Comment by yasker** [comment]
Updated CSI example

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-vol-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: <existing-longhorn-volume>
```

`volumeHandle` input from user is required.
