### ISSUE TITLE
CLI: Parsing errors for ` rancher cluster ls `command

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18128]
Rancher CLI version:  v2.2.0-rc7 /v2.2.0-rc8
Rancher version used: Master

Steps:
1. Create a rancher setup with master and have multiple DO clusters in it. 
2. Perform export of one of the existing clusters using cli and save the yml in cluster.yml 
Example cluster.yml file:
```
Version: v3
clusters:
  test-532531:
    dockerRootDir: /var/lib/docker
    enableNetworkPolicy: false
    localClusterAuthEndpoint: {}
    rancherKubernetesEngineConfig:
      addonJobTimeout: 30
      authentication:
        strategy: x509
      authorization: {}
      bastionHost: {}
      cloudProvider: {}
      dns: {}
      ignoreDockerVersion: true
      ingress:
        provider: nginx
      kubernetesVersion: v1.13.1-rancher1-1
      monitoring:
        provider: metrics-server
      network:
        plugin: canal
      restore: {}
      services:
        etcd:
          backupConfig:
            intervalHours: 12
            retention: 6
          creation: 12h
          extraArgs:
            election-timeout: "5000"
            heartbeat-interval: "500"
          retention: 72h
          snapshot: false
        kubeApi:
          serviceNodePortRange: 30000-32767
        kubeController: {}
        kubelet: {}
        kubeproxy: {}
        scheduler: {}
nodePools:
  np-gbpb41:
    clusterId: test-532531
    controlPlane: true
    etcd: true
    hostnamePrefix: testauto-417921
    nodeTemplateId: test-73882
    quantity: 1
    worker: true
```
3. Create a cluster using CLI with `rancher up` command 
```
./rancher up --file cluster.yml
```
2. After creating a cluster, do an ls as  `./rancher cluster ls`  command
It displays parsing errors as below:

```
rancher-v2.2.0-rc8 soumya$ ./rancher cluster ls
strconv.ParseFloat: parsing "5700Mi": invalid syntax
strconv.ParseFloat: parsing "1329952Ki": invalid syntax
strconv.ParseFloat: parsing "1900Mi": invalid syntax
CURRENT   ID        STATE          NAME                   PROVIDER                    NODES     CPU          RAM            PODS
          c-cckbs   active         dosinganodeaaa         Rancher Kubernetes Engine   1         0.54/2       0.14/3.76 GB   9/110
          c-hhpmx   active         dosingnodenew1         Rancher Kubernetes Engine   1         0.54/2       0.14/3.76 GB   9/110
          c-hvtt9   provisioning   test-532531            Rancher Kubernetes Engine   1         0.00/0       0.00/0.00 GB   0/0
          c-j8fvh   active         dosingnodenew101       Rancher Kubernetes Engine   1         0.54/2       0.14/3.76 GB   9/110
          c-ltllp   active         test-54701             Rancher Kubernetes Engine   8         1.30/6       0.24/0.00 GB   15/330
*         c-nbgs8   active         dosingnode             Rancher Kubernetes Engine   1         0.54/2       0.14/3.76 GB   10/110
          c-qgjzb   active         soumyaexamplecluster   Google Kubernetes Engine    3         1.34/2820m   0.00/3.38 GB   18/330
          c-tzmfv   active         dosingnodenew100       Rancher Kubernetes Engine   1         0.54/2       0.14/3.76 GB   9/110
          c-xrdvt   active         test-62917             Rancher Kubernetes Engine   1         0.54/2       0.14/0.00 GB   9/110
rancher-v2.2.0-rc8 soumya$ 


```
