### ISSUE TITLE
Hostname generation possible outside of the UI?

### ISSUE THREAD

**Issue by rahmnathan** [rancher/rancher#18124]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

I'm trying to automate my deployments to Kubernetes(Rancher) using Helm. Currently, we're taking advantage of the automated hostname generation for Ingress' through the UI (which works very nicely). I was wondering if there is a way to do this via a plain Kubernetes Ingress yaml file. We'd like to be able to package our Ingress definitions in our Helm charts, but this is currently not possible when relying on these hostnames. Maybe there's a label or annotation that would trigger this? I haven't been able to find any information yet.

Thanks

**Comment by loganhz** [comment]
There is a host field in ingress yaml. The auto-generation will work without any rancher related labels or annotations

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: wordpress-wordpress
    chart: wordpress-2.1.10
    heritage: Tiller
    release: wordpress
  name: xip.io-wordpress
  namespace: wordpress
spec:
  rules:
  - host: xip.io
    http:
      paths:
      - backend:
          serviceName: wordpress-wordpress
          servicePort: 80
```
