### ISSUE TITLE
Support Opsgenie as a notifier

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#18164]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Add Opsgenie as a supported notifier

gz#5093
gz#5198
gz#10165

**Comment by helhindi** [comment]
+1 for the above request. We would benefit from the addition o opsgenie as a notifier

**Comment by ketanp2000** [comment]
this would be nice to have.... #18164

**Comment by chipm73** [comment]
+1 for this as well.

**Comment by mrunalhtrivedi** [comment]
+1 that's definitely needed.

**Comment by sirrapa** [comment]
Same here

**Comment by vsabella** [comment]
👍

**Comment by basroovers** [comment]
OpsGenie support would be very much appreciated.

**Comment by cmer81** [comment]
+1 same here.

**Comment by lalinsky** [comment]
Can this be implemented, please? It's rather easy, since alertmanager already supports opsgenie.

**Comment by mitchellmaler** [comment]
@superseb We just ran into this as well. We want to switch to using the built in Rancher monitoring but we currently only use Opsgenie for notifications and I know it's an alert manager supported notifier. I can see @wtschreiter has opened up a few PRs #21961 and  https://github.com/rancher/types/pull/931 that would solve this.

**Comment by wtschreiter** [comment]
Any hint about what I can do to support this is welcome

**Comment by mitchellmaler** [comment]
@superseb @loganhz Can the related PR be added for 4.5?

**Comment by aiyengar2** [comment]
This should be supported by Alerting V2, which will allow users to directly modify the AlertManager Config and supply the [ops_genie notifier configuration](https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config).

Issue: https://github.com/rancher/rancher/issues/28348

**Comment by wjimenez5271** [comment]
Validate this is working by using the following config for the secret object `alertmanager-rancher-monitoring-alertmanager`, setting the key `alertmanager.yaml` to:

```
global:
  resolve_timeout: 5m
  opsgenie_api_key: [Opsgenie integration API key]
receivers:
- name: 'rancher-opsgenie'
  opsgenie_configs:
  - api_key: [Opsgenie integration API key]
  - message: "alert!"
route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 30s
  receiver: "rancher-opsgenie"
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: "rancher-opsgenie"
templates:
- /etc/alertmanager/config/*.tmpl
```

This produced an alert in Opsgenie: 

<img width="884" alt="Screen Shot 2020-09-18 at 4 23 04 PM" src="https://user-images.githubusercontent.com/322834/93652832-49cbed00-f9cb-11ea-9e53-e2170c438871.png">


Additional fields and parameters in the alert can be set by defining in the above secret object according to: https://prometheus.io/docs/alerting/latest/configuration/#opsgenie_config
