### ISSUE TITLE
ingress remains intializing after upgraded to 2.1.6

### ISSUE THREAD

**Issue by Ryanbeta** [rancher/rancher#18265]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
1. create a cluster in rancher 2.0.6 ,update the cluster to 2.1.6, updates kubenetes from 1.10 to 1.11
2. define deployment.yaml & service.yaml in my private catalog and deploy this app through UI
3. add an ingress in UI and refer a url to the service, and the ingress stays intializing

**Result:**
1. the ui says the ingress is initializing
2. metadata.annotations does not have field.cattle.io/publicEndpoints field, and ingressState is incomplete:
```
metadata:
  annotations:
    field.cattle.io/creatorId: user-64dpp
    field.cattle.io/ingressState:'{"bWFjcm9zcGlkZXItc2VydmljZS1pbmdyZXNzL21hY3Jvc3BpZGVyLXNlcnZpY2UvbWFjcm9zcGlkZXItc2VydmljZS16dXVsLnJlc3Bvb2wyLndtY2xvdWQtcWEuY29tLy84MDg1":""}'
  creationTimestamp: 2019-02-20T09:46:22Z
```
3. the ingress.yaml has empth status.loadBalancer, usually I can find lb ip here:
```
status:
  loadBalancer: {}
```
4. the url itself works properly. I can access back-end service through designated rules[0].host

**Other details that may be helpful:**
This procedure works fine in 2.0.6

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.6
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8C32G
- Kubernetes version (use `kubectl version`): 

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
# docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:50 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
