### ISSUE TITLE
Layer 4 Load Balancing Disabled With MetalLB Configured

### ISSUE THREAD

**Issue by DarkRider1768** [rancher/rancher#18275]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Run Rancher 2.2.0-Alpha6, install and configure MetalLB (BGP), attempt to deploy a pod with Layer 4 load balancing.

**Result:**
Cannot select Layer 4 load balancing from the drop down as it's set to disabled.

**Other details that may be helpful:**
This was working in version 2.1.6, prior to updating the rancher deployment.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher 2.2.0-Alpha6
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal; 96 Cores, 251GiB Ram across 4 nodes
- Kubernetes version (use `kubectl version`): 1.12.4

```yaml
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```yaml
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
