### ISSUE TITLE
Cloud credentials support for custom node driver

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#18307]
This issue is to validate the cloud credential support for custom node drivers

**Comment by kinarashah** [comment]
Works in rancher/master: 2/20 

Steps - 
1) Figure out which fields need to be included in the cloud credential. For example, for Packet node driver, I want `projectId` and `plan` to be included in the credential, where I want `plan` to be of type password. 
Difference: All fields in credential are stored in kubernetes secret, but when you mark a field of type password, API won't show its value. Here, `projectId` and `plan` would be a part of `packetCredentialConfig` but once you create a cloud credential, API would show only `projectId`. 
Note: Following fields are already hardcoded for type password  https://github.com/rancher/rancher/blob/master/pkg/controllers/management/drivers/nodedriver/utils.go#L19

2) Edit node driver in API, add annotation `cred` : `field1, field2,..` and `password`: `field1, field2, ..` as required. In our current example, I edited node packet driver to `cred`: `projectId` and `password`:`plan`. 

3) Activate node driver. 

Now, either check `v3/schemas/cloudcredential` or go to `v3/cloudcredentials` and create a new one. A new driverName+`credentialconfig` would have been created, confirm the fields passed have been created. In our example, I see `packetcredentialconfig` got created.

**Comment by kinarashah** [comment]
We do require UI support for this, since above was tested through API. 

UI just needs to allow editing annotations on node driver, and also show that while creating a new one. 
Can also display `cred` and `password` keys so user can just give values accordingly.

**Comment by displague** [comment]
I'm interested in how this will work too (for the Linode node driver).

I currently ask users to use the `Custom YAML` field in the UI to include an add-on URI which expects a secrets to exist with a specific name:

```yaml
addons_include:
  - https://linode.github.io/rancher-ui-driver-linode/releases/v0.2.0/linode-addons.yml
addons: |-
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: linode
    namespace: kube-system
  stringData:
    token: "..."
    region: "..."
  ---
```

The process is described here: https://www.linode.com/docs/applications/containers/how-to-deploy-kubernetes-on-linode-with-rancher-2-2/#provision-a-cluster
