### ISSUE TITLE
Rancher server + agent on same machine

### ISSUE THREAD

**Issue by rcdailey** [rancher/rancher#18360]
I am trying to run Rancher on 1 physical machine (my home lab) to manage my containers instead of using docker compose. I use this:

```
version: '3.7'

services:
  app:
    image: rancher/rancher
    container_name: rancher
    restart: unless-stopped
    networks:
      - reverse_proxy
      - agent_network
    volumes:
    - ./data:/var/lib/rancher

  agent:
    image: rancher/rancher-agent:v2.1.6
    container_name: rancher-agent
    privileged: true
    networks:
    - agent_network
    volumes:
    - /etc/kubernetes:/etc/kubernetes
    - /var/run:/var/run
    environment:
    - CATTLE_SERVER=http://rancher
    - CATTLE_TOKEN=<snip>
    - CATTLE_CA_CHECKSUM=<snip>
    - ALL=true

networks:
  reverse_proxy:
    external: 'true'
    name: reverse_proxy
  agent_network:
```

This doesn't seem to work. Even though my node shows up in the Web UI, it doesn't look like it is fully registered. The agent logs show:

```
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Rancher agent version v2.1.6 is starting"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Option etcd=true"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Option controlPlane=true"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Option worker=true"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Option requestedHostname=e3d17513ba69"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Option customConfig=map[address:172.21.0.2 internalAddress: roles:[etcd worker controlplane] label:map[]]"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Listening on /tmp/log.sock"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Connecting to wss://rancher/v3/connect/register with token wz4xqr85566srrbbp87rcsrbjrqlnhc84tmv2bmzt4jgpqspb7958h"
rancher-agent | time="2019-02-25T01:42:00Z" level=info msg="Connecting to proxy" url="wss://rancher/v3/connect/register"
rancher-agent | time="2019-02-25T01:42:00Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
rancher-agent | time="2019-02-25T01:42:00Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
rancher-agent | time="2019-02-25T01:42:10Z" level=info msg="Connecting to wss://rancher/v3/connect/register with token wz4xqr85566srrbbp87rcsrbjrqlnhc84tmv2bmzt4jgpqspb7958h"
rancher-agent | time="2019-02-25T01:42:10Z" level=info msg="Connecting to proxy" url="wss://rancher/v3/connect/register"
rancher-agent | time="2019-02-25T01:42:10Z" level=info msg="Starting plan monitor"
```

So it looks like it worked half way or something. What am I doing wrong in my configuration of the agent? I wanted the server and the agent to talk to each other directly over the 172.21.0.0/16 subnet if possible. There's no reason for them to need host networking, or connect through the WAN, as far as I know. 

Thanks in advance for any help.
