### ISSUE TITLE
[QUESTION] How to use weave with encryption

### ISSUE THREAD

**Issue by vistalba** [rancher/rancher#18370]
Hi

I'm running rancher v2.2.0-rc2 to create a new cluster with weave as cni.

As described here, rancher sets a auto-generated password:
https://github.com/rancher/rke/pull/781

If I set Network-Plugin to weave in the UI and look at the YAML it look like this:

```
network: 
  options: 
    flannel_backend_type: "vxlan"
  plugin: "weave"
  weave_network_provider: 
    password: "Q]SZOQ5wp@n$oijz"
```
Password value is generated random.

If I create the cluster now, weave starts unencrypted.
Is there something wrong with the syntax? In the link above it looks little different from here.
