### ISSUE TITLE
Airgap HA - TransitioningMessage and transitioning state do not reflect correct status

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#18417]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run rancher 2.2.0-rc1  in the airgap HA mode
- add an EC2 cluster
- enable cluster-level monitoring
- disable cluster-level monitoring after there is error message showing for the cluster
- check the catalog apps and workloads for monitoring are fully removed

**Result:**
The cluster state is in "Active" state and is fully functional, but the transition error message is seen for the cluster and it never gets cleared.
<img width="1394" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/53449037-2f3fb680-39d6-11e9-8ddd-379ca9ec9f43.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.0-rc1
- Installation option (single install/HA):
airgap HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by sangeethah** [comment]
This is similar to https://github.com/rancher/rancher/issues/17304

**Comment by jiaqiluo** [comment]
View the cluster in  API
```yaml
{
"actions": {
"backupEtcd": "…/v3/clusters/c-bmngj?action=backupEtcd",
"enableMonitoring": "…/v3/clusters/c-bmngj?action=enableMonitoring",
"exportYaml": "…/v3/clusters/c-bmngj?action=exportYaml",
"generateKubeconfig": "…/v3/clusters/c-bmngj?action=generateKubeconfig",
"importYaml": "…/v3/clusters/c-bmngj?action=importYaml",
"restoreFromEtcdBackup": "…/v3/clusters/c-bmngj?action=restoreFromEtcdBackup",
"rotateCertificates": "…/v3/clusters/c-bmngj?action=rotateCertificates"
},
"agentImage": "ec2-13-57-242-254.us-west-1.compute.amazonaws.com:443/rancher/rancher-agent:v2.2.0-rc1",
"allocatable": {
"cpu": "4",
"memory": "16328960Ki",
"pods": "110"
},
"annotations": {
"authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
"field.cattle.io/overwriteAppAnswers": "{\"answers\":{\"exporter-node.enabled\":\"true\",\"exporter-node.ports.metrics.port\":\"9796\",\"exporter-kubelets.https\":\"true\",\"prometheus.retention\":\"360h\",\"grafana.persistence.enabled\":\"false\",\"prometheus.persistence.enabled\":\"false\",\"prometheus.persistence.storageClass\":\"default\",\"grafana.persistence.storageClass\":\"default\",\"grafana.persistence.size\":\"10Gi\",\"prometheus.persistence.size\":\"50Gi\"}}",
"lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
"lifecycle.cattle.io/create.cluster-provisioner-controller": "true",
"lifecycle.cattle.io/create.cluster-scoped-gc": "true",
"lifecycle.cattle.io/create.mgmt-cluster-rbac-remove": "true"
},
"apiEndpoint": "https://172.31.29.78:6443",
"appliedEnableNetworkPolicy": false,
"appliedPodSecurityPolicyTemplateId": "",
"appliedSpec": {
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"desiredAuthImage": "",
"displayName": "custom3",
"dockerRootDir": "/var/lib/docker",
"enableClusterAlerting": false,
"enableClusterMonitoring": false,
"enableNetworkPolicy": false,
"internal": false,
"localClusterAuthEndpoint": {
"enabled": true,
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509|webhook",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"dns": {
"provider": "kube-dns",
"type": "/v3/schemas/dnsConfig"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.13.1-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannelBackendType": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"nodes": [ 3 items
{
"address": "172.31.18.88",
"hostnameOverride": "ip-172-31-18-88",
"internalAddress": "172.31.18.88",
"nodeId": "c-bmngj:m-00366f46332b",
"port": "22",
"role": [
"etcd"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "172.31.17.185",
"hostnameOverride": "ip-172-31-17-185",
"internalAddress": "172.31.17.185",
"nodeId": "c-bmngj:m-62e6a1e95c6b",
"port": "22",
"role": [
"worker"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
},
{
"address": "172.31.29.78",
"hostnameOverride": "ip-172-31-29-78",
"internalAddress": "172.31.29.78",
"nodeId": "c-bmngj:m-813679dfb616",
"port": "22",
"role": [
"controlplane"
],
"sshAgentAuth": false,
"type": "/v3/schemas/rkeConfigNode",
"user": "root"
}
],
"privateRegistries": [
{
"isDefault": true,
"type": "/v3/schemas/privateRegistry",
"url": "ec2-13-57-242-254.us-west-1.compute.amazonaws.com:443",
"user": "jiaqi"
}
],
"restore": {
"restore": false,
"type": "/v3/schemas/restoreConfig"
},
"services": {
"etcd": {
"backupConfig": {
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": null,
"type": "/v3/schemas/backupConfig"
},
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"alwaysPullImages": false,
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"type": "/v3/schemas/clusterSpec"
},
"authImage": "ec2-13-57-242-254.us-west-1.compute.amazonaws.com:443/rancher/kube-api-auth:v0.1.1",
"baseType": "cluster",
"caCert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKTFdOaE1CNFhEVEU1TURJeU5URTNNVEV5TlZvWERUSTVNREl5TWpFM01URXlOVm93RWpFUU1BNEdBMVVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1LU2VHSXFaZTFwCmFnMHM1QTI0MUV3cFBkVmpWeUZDdFJxanRYYjBKWVRIbFlDbmxhcXhPNXg3MFF2cEwxWDAyMG9HV1g1NnYwN2oKTHFVRE1KU3hHYmcybjZ3c002aklOT1UyVkVVL3ZXUzl5N2VJc09iSVRwcURoaUdHcGp5dkpOdjFKZ0t1THNHVQo1Wi9pQk9ZNGE5Tk1TdFdvK2ZDUEtFcGdOWTNYaXM1bjRXVTMxeGNlcE9JRDBHaEx5aEFScSsvZktESndLbVdnCnNhaUl5YUdYZHFuTDhNTmtSbWtvRWJhZHRzRTRpTklEeUlMbGF4SENDU3U0U3loZGk3ZUYzMGJOOTVNd1krNkQKYnJ6WXZ3amkzWjhqcnk4eC9SMldYeGw3OXJEY25xdkxzcVBEYURrOGJyNUZaNzZzUlFTNFN0NU9PTWVDRVpEZgpsRUpzTWpSMEdIOENBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSythRFdyK3Y2dDd0cm50RUJUb3RmYVRrZnJnZFBBbU5VT2QKZ0xZUDQxT2h2S2NodzRLckJja2dEWmZzZE9DSTdwOElLNjB4NkhXcUt2NHBWYUxHWlVERlBvSFZCclE4TXN6OAprL0lqV0RQZUVSTXA4OFRjYUV4WUlIV25TWmhKZnN3UWJITUF5MkthOEVEVys2bVlaaENyYUo5L2RrRWJDQ3BZCjNxOXhoRTFHcGpIUVI0b3VCSDdOYkZKN2R4OWVqUVNHbDhqaGpVZHA0YjJTd3ltUy9ZTXk3UHFsMzN0SlBvY08KUTdPTzMyUnhKamlXNDNsQjZuN3o5ZkNxUVhhRjByMDJrWkdhWmUwWnU5YnNmcjhTa3A3RmF5YTRVYm5uQnk1UAplUExPVWVBWDg0NitRVm00TktacTJGZ2kzS0xLcVBKakZLYjlIMEx0QkFjbnpLTFdwQ289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
"capabilities": {
"ingressCapabilities": [
{
"customDefaultBackend": false,
"ingressProvider": "Nginx",
"type": "/v3/schemas/ingressCapabilities"
}
],
"loadBalancerCapabilities": {
"enabled": false,
"healthCheckSupported": false,
"type": "/v3/schemas/loadBalancerCapabilities"
},
"nodePoolScalingSupported": false,
"nodePortRange": "30000-32767",
"type": "/v3/schemas/capabilities"
},
"capacity": {
"cpu": "4",
"memory": "16431360Ki",
"pods": "110"
},
"componentStatuses": [ 3 items
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "controller-manager",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "{\"health\": \"true\"}",
"status": "True",
"type": "Healthy"
}
],
"name": "etcd-0",
"type": "/v3/schemas/clusterComponentStatus"
},
{
"conditions": [
{
"message": "ok",
"status": "True",
"type": "Healthy"
}
],
"name": "scheduler",
"type": "/v3/schemas/clusterComponentStatus"
}
],
"conditions": [ 18 items
{
"status": "True",
"type": "Pending"
},
{
"lastUpdateTime": "2019-02-25T17:13:10Z",
"status": "True",
"type": "Provisioned"
},
{
"lastUpdateTime": "2019-02-25T17:13:25Z",
"status": "True",
"type": "Waiting"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "BackingNamespaceCreated"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "DefaultProjectCreated"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "SystemProjectCreated"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "InitialRolesPopulated"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "CreatorMadeOwner"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "NoDiskPressure"
},
{
"lastUpdateTime": "2019-02-25T17:09:22Z",
"status": "True",
"type": "NoMemoryPressure"
},
{
"lastUpdateTime": "2019-02-25T17:13:10Z",
"status": "True",
"type": "GlobalAdminsSynced"
},
{
"lastUpdateTime": "2019-02-26T19:29:47Z",
"message": "failed to ensure catalog \"catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2\": failed to find catalog by ID \"catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2\": catalogtemplateversions.management.cattle.io \"system-library-rancher-monitoring-0.0.2\" not found",
"reason": "Error",
"status": "False",
"type": "PrometheusOperatorDeployed"
},
{
"lastUpdateTime": "2019-02-25T17:13:16Z",
"status": "True",
"type": "SystemAccountCreated"
},
{
"lastUpdateTime": "2019-02-25T17:13:17Z",
"status": "True",
"type": "AgentDeployed"
},
{
"lastUpdateTime": "2019-02-25T17:13:25Z",
"status": "True",
"type": "Ready"
},
{
"lastUpdateTime": "2019-02-25T17:13:38Z",
"status": "True",
"type": "Updated"
},
{
"lastUpdateTime": "2019-02-25T17:13:33Z",
"status": "True",
"type": "ServiceAccountMigrated"
},
{
"lastUpdateTime": "2019-02-26T20:26:06Z",
"status": "False",
"type": "MonitoringEnabled"
}
],
"created": "2019-02-25T17:09:22Z",
"createdTS": 1551114562000,
"creatorId": "user-bw5kj",
"defaultClusterRoleForProjectMembers": null,
"defaultPodSecurityPolicyTemplateId": null,
"description": "",
"desiredAgentImage": "",
"desiredAuthImage": "",
"dockerRootDir": "/var/lib/docker",
"driver": "rancherKubernetesEngine",
"enableClusterAlerting": false,
"enableClusterMonitoring": false,
"enableNetworkPolicy": false,
"id": "c-bmngj",
"internal": false,
"labels": {
"cattle.io/creator": "norman"
},
"limits": {
"cpu": "10m",
"memory": "190Mi",
"pods": "0"
},
"links": {
"clusterAlertGroups": "…/v3/clusters/c-bmngj/clusteralertgroups",
"clusterAlertRules": "…/v3/clusters/c-bmngj/clusteralertrules",
"clusterAlerts": "…/v3/clusters/c-bmngj/clusteralerts",
"clusterCatalogs": "…/v3/clusters/c-bmngj/clustercatalogs",
"clusterLoggings": "…/v3/clusters/c-bmngj/clusterloggings",
"clusterMonitorGraphs": "…/v3/clusters/c-bmngj/clustermonitorgraphs",
"clusterRegistrationTokens": "…/v3/clusters/c-bmngj/clusterregistrationtokens",
"clusterRoleTemplateBindings": "…/v3/clusters/c-bmngj/clusterroletemplatebindings",
"etcdBackups": "…/v3/clusters/c-bmngj/etcdbackups",
"namespaces": "…/v3/clusters/c-bmngj/namespaces",
"nodePools": "…/v3/clusters/c-bmngj/nodepools",
"nodes": "…/v3/clusters/c-bmngj/nodes",
"notifiers": "…/v3/clusters/c-bmngj/notifiers",
"persistentVolumes": "…/v3/clusters/c-bmngj/persistentvolumes",
"projects": "…/v3/clusters/c-bmngj/projects",
"remove": "…/v3/clusters/c-bmngj",
"self": "…/v3/clusters/c-bmngj",
"shell": "wss://jiaqi-ag-lb-e4f7e0724eaa18d0.elb.us-west-1.amazonaws.com/v3/clusters/c-bmngj?shell=true",
"storageClasses": "…/v3/clusters/c-bmngj/storageclasses",
"subscribe": "…/v3/clusters/c-bmngj/subscribe",
"templates": "…/v3/clusters/c-bmngj/templates",
"tokens": "…/v3/clusters/c-bmngj/tokens",
"update": "…/v3/clusters/c-bmngj"
},
"localClusterAuthEndpoint": {
"enabled": true,
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"monitoringStatus": {
"conditions": [ 5 items
{
"lastUpdateTime": "2019-02-26T19:29:47Z",
"message": "Grafana Deployment isn't deployed",
"reason": "Error",
"status": "False",
"type": "GrafanaDeployed"
},
{
"lastUpdateTime": "2019-02-26T19:29:47Z",
"message": "Node Exporter DaemonSet isn't deployed",
"reason": "Error",
"status": "False",
"type": "NodeExporterDeployed"
},
{
"lastUpdateTime": "2019-02-26T19:29:47Z",
"message": "Kube State Exporter Deployment isn't deployed",
"reason": "Error",
"status": "False",
"type": "KubeStateExporterDeployed"
},
{
"lastUpdateTime": "2019-02-26T19:29:47Z",
"message": "Prometheus StatefulSet isn't deployed",
"reason": "Error",
"status": "False",
"type": "PrometheusDeployed"
},
{
"lastUpdateTime": "2019-02-26T20:26:06Z",
"status": "False",
"type": "MetricExpressionDeployed"
}
],
"type": "/v3/schemas/monitoringStatus"
},
"name": "custom3",
"rancherKubernetesEngineConfig": {
"addonJobTimeout": 30,
"authentication": {
"strategy": "x509|webhook",
"type": "/v3/schemas/authnConfig"
},
"authorization": {
"type": "/v3/schemas/authzConfig"
},
"bastionHost": {
"sshAgentAuth": false,
"type": "/v3/schemas/bastionHost"
},
"cloudProvider": {
"type": "/v3/schemas/cloudProvider"
},
"dns": {
"provider": "kube-dns",
"type": "/v3/schemas/dnsConfig"
},
"ignoreDockerVersion": true,
"ingress": {
"provider": "nginx",
"type": "/v3/schemas/ingressConfig"
},
"kubernetesVersion": "v1.13.1-rancher1-1",
"monitoring": {
"provider": "metrics-server",
"type": "/v3/schemas/monitoringConfig"
},
"network": {
"options": {
"flannelBackendType": "vxlan"
},
"plugin": "canal",
"type": "/v3/schemas/networkConfig"
},
"privateRegistries": [
{
"isDefault": true,
"type": "/v3/schemas/privateRegistry",
"url": "ec2-13-57-242-254.us-west-1.compute.amazonaws.com:443",
"user": "jiaqi"
}
],
"restore": {
"restore": false,
"type": "/v3/schemas/restoreConfig"
},
"services": {
"etcd": {
"backupConfig": {
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": null,
"type": "/v3/schemas/backupConfig"
},
"creation": "12h",
"extraArgs": {
"election-timeout": "5000",
"heartbeat-interval": "500"
},
"retention": "72h",
"snapshot": false,
"type": "/v3/schemas/etcdService"
},
"kubeApi": {
"alwaysPullImages": false,
"podSecurityPolicy": false,
"serviceNodePortRange": "30000-32767",
"type": "/v3/schemas/kubeAPIService"
},
"kubeController": {
"type": "/v3/schemas/kubeControllerService"
},
"kubelet": {
"failSwapOn": false,
"type": "/v3/schemas/kubeletService"
},
"kubeproxy": {
"type": "/v3/schemas/kubeproxyService"
},
"scheduler": {
"type": "/v3/schemas/schedulerService"
},
"type": "/v3/schemas/rkeConfigServices"
},
"sshAgentAuth": false,
"type": "/v3/schemas/rancherKubernetesEngineConfig"
},
"requested": {
"cpu": "540m",
"memory": "140Mi",
"pods": "9"
},
"state": "active",
"transitioning": "error",
"transitioningMessage": "failed to ensure catalog \"catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2\": failed to find catalog by ID \"catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2\": catalogtemplateversions.management.cattle.io \"system-library-rancher-monitoring-0.0.2\" not found",
"type": "cluster",
"uuid": "18420175-3920-11e9-af88-0262c4f87d22",
"version": {
"buildDate": "2018-12-13T10:31:33Z",
"compiler": "gc",
"gitCommit": "eec55b9ba98609a46fee712359c7b5b365bdd920",
"gitTreeState": "clean",
"gitVersion": "v1.13.1",
"goVersion": "go1.11.2",
"major": "1",
"minor": "13",
"platform": "linux/amd64",
"type": "/v3/schemas/info"
}
}
```
