### ISSUE TITLE
rancher-compose.yml not being correctly generated with scaling configuration. 

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#1842]
```
Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest
```

<h1>Summary</h1>
This could be wider reaching but in this instance we have come across it under the conditions described below. When creating loadbalancer services through the GUI, when you view or export the config, the scaling configuration doesn't reflect the configuration specified when creating the service.

<h1>Steps to replicate</h1>
1. Create new loadbalancer service, supply port/destination service as required. Now, for 'Scale' choose 'Always run one instance of this container on every host.' 
2. Once created, view the config in the GUI, you will see scale defined as so `  scale: 1` without any further configuration.
3. Repeat the steps but for scaling, select a number of containers. The generated config from both these services will be identical in docker-compose.yml and rancher-compose.yml. 

<h1>Outcome</h1>
A result of the above means we can't reliably build out a service that uses the config, it's also tripping up rancher-compose but i'll raise that separately if required.

**Comment by deniseschannon** [comment]
Thanks for the detailed issue. 

When you select "Always run one instance of this container on every host", the scale in the rancher-compose doesn't matter. There is a label in the docker compose called "io.rancher.scheduler.global: true", which is setting a global scale for the load balancer. You can read more about it here: 
http://docs.rancher.com/rancher/rancher-compose/scheduling/#global-service

In v0.32.0, if I select a load balancer with scale 2, I see in my rancher-compose that the scale is 2.

Example in Rancher-compose.yml
```
lbtestscale:
  scale: 2
  load_balancer_config:
    name: lbtestscale config
```

Finally, what's the issue that you are having with rancher-compose?

**Comment by Rucknar** [comment]
You are indeed correct! Hadn't spotted that, my mistake. I'll update the ticket in around an hour(travelling)  with details of the compose issue we hit (which led us to the above incorrect conclusion!).

**Comment by Rucknar** [comment]
Right...

Docker server running on host1, and two managed rancher nodes running (host2/host3)

we are using the rancher-compose cli tool to populate services using the below rancher-compose and docker-compose config files. The services create as we would expect through the CLI.
When issuing the `up` command to rancher it also correctly starts them.

The issue is that the cli never returns yet the services do start properly, it posts `INFO[0050] Project [helloworld]: Project started` but i don't get returned to the command line. We've verified this on linux and on Mac OS X. The services start as i'd expect.

docker-compose.yml
```
WebsiteLB:
  ports:
  - 80:80
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - WebServiceV1:WebServiceV1
  stdin_open: true
WebServiceV1:
  restart: always
  tty: true
  image: tutum/hello-world
  stdin_open: true
```
rancher-compose.yml
```
WebsiteLB:
  scale: 1
  load_balancer_config:
    description: Loadbalancer for website testing.
    name: WebsiteLB config
WebServiceV1:
  scale: 6
```
