### ISSUE TITLE
Enable recurring backup, the value of the snapshot is false

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#18429]
**Rancher version**
rancher/rancher:master 02/27

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Create a cluster and enable backup for the cluster 
* Configure the correct `s3_backup_config`

**Result:**
The value of the snapshot is false, the backup does not work.
```
services: 
  etcd: 
    backup_config: 
      interval_hours: 12
      retention: 6
      s3_backup_config: 
        access_key: "xxxx"
        bucket_name: "test-bucket"
        endpoint: "oss-cn-shenzhen.aliyuncs.com"
        region: "cn-shenzhen"
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: false
```
