### ISSUE TITLE
Rancher-created GKEs are missing essential scopes in default node-pool for GCR access

### ISSUE THREAD

**Issue by McSlow** [rancher/rancher#18440]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
install rancher, spin up gke cluster, pull docker image from gcr (docker image is in the same gcloud project as the gke cluster)

**Result:**
access denied.

**Environment information**
- Rancher version : 2.1.6
- Installation option :single

Hi, seems that rancher-created gke clusters are missing some essential default node-pool scopes to run smoothly.
i.e. the "https://www.googleapis.com/auth/devstorage.read_only" is missing (it's there when you spin up a gke from the google cloud console) - resulting in the inability to pull docker images from the project's gcr container registry - usually this works without any authentication when gke and gcr is within the same project.

the old-fashioned way ( creating a service account and creating pull credentials which have to placed in the docker config json) still works.

For reference, here are the scopes from a rancher-create gke:

```
gcloud container node-pools describe default-pool --region europe-west1-d --cluster c-redacted
config:
  diskSizeGb: 20
  diskType: pd-standard
  imageType: COS
  machineType: n1-standard-2
  oauthScopes:
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  serviceAccount: default
initialNodeCount: 2
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/it-test-216114/zones/europe-west1-d/instanceGroupManagers/gke-c-redacted-default-pool-987e582b-grp
management: {}
name: default-pool
selfLink: https://container.googleapis.com/v1/projects/it-redacted/zones/europe-west1-d/clusters/c-redacted/nodePools/default-pool
status: RUNNING
version: 1.11.7-gke.6
```
gitlab-created gke's seem to have the same problem:
https://stackoverflow.com/questions/54043495/gke-cluster-cant-pull-errimagepull-from-gcr-registry-in-same-project-gitlab
