### ISSUE TITLE
alertmanager can't start

### ISSUE THREAD

**Issue by jasonsoft** [rancher/rancher#18493]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
1. add slack notifier
2. enable "alerts" feature in cluster-level

**Result:**
alertmanager-cluster-alerting pod can't start due to the following error log

```
level=info ts=2019-03-01T05:01:52.138592557Z caller=main.go:177 msg="Starting Alertmanager" version="(version=0.16.1, branch=HEAD, revision=571caec278be1f0dbadfdf5effd0bbea16562cfc)"
level=info ts=2019-03-01T05:01:52.138654658Z caller=main.go:178 build_context="(go=go1.11.5, user=root@3000aa3a06c5, date=20190131-15:05:40)"
level=warn ts=2019-03-01T05:01:54.168738877Z caller=cluster.go:226 component=cluster msg="failed to join cluster" err="1 error occurred:\n\n* Failed to resolve alertmanager-cluster-alerting-0.alertmanager-operated.cattle-prometheus.svc:6783: lookup alertmanager-cluster-alerting-0.alertmanager-operated.cattle-prometheus.svc on 10.96.0.10:53: no such host"
level=info ts=2019-03-01T05:01:54.168814478Z caller=cluster.go:228 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2019-03-01T05:01:54.168857278Z caller=main.go:268 msg="unable to join gossip mesh" err="1 error occurred:\n\n* Failed to resolve alertmanager-cluster-alerting-0.alertmanager-operated.cattle-prometheus.svc:6783: lookup alertmanager-cluster-alerting-0.alertmanager-operated.cattle-prometheus.svc on 10.96.0.10:53: no such host"
level=info ts=2019-03-01T05:01:54.170650098Z caller=cluster.go:632 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-03-01T05:01:54.196098986Z caller=main.go:334 msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2019-03-01T05:01:54.196414989Z caller=main.go:337 msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="unsupported scheme \"\" for URL"
level=info ts=2019-03-01T05:01:54.19651759Z caller=cluster.go:641 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=25.783691ms
```

**Other details that may be helpful:**
use default setting.  haven't use custom alertmanager config yet.

alertmanager.yaml

```
apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX3JlcXVpcmVfdGxzOiBmYWxzZQogIHNsYWNrX2FwaV91cmw6IHNsYWNrX2FwaV91cmwKICBwYWdlcmR1dHlfdXJsOiBodHRwczovL2V2ZW50cy5wYWdlcmR1dHkuY29tL3YyL2VucXVldWUKcm91dGU6CiAgcmVjZWl2ZXI6IHJhbmNoZXJsYWJzCiAgcm91dGVzOgogIC0gcmVjZWl2ZXI6IGMtZGJieno6bm9kZS1hbGVydAogICAgZ3JvdXBfYnk6CiAgICAtIGdyb3VwX2lkCiAgICBtYXRjaDoKICAgICAgZ3JvdXBfaWQ6IGMtZGJieno6bm9kZS1hbGVydAogICAgY29udGludWU6IHRydWUKICAgIHJvdXRlczoKICAgIC0gZ3JvdXBfYnk6CiAgICAgIC0gcnVsZV9pZAogICAgICBtYXRjaDoKICAgICAgICBydWxlX2lkOiBjLWRiYnp6Om5vZGUtYWxlcnRfaGlnaC1jcHUtbG9hZAogICAgICBjb250aW51ZTogdHJ1ZQogICAgICBncm91cF93YWl0OiAzbQogICAgICBncm91cF9pbnRlcnZhbDogM20KICAgICAgcmVwZWF0X2ludGVydmFsOiAxaAogICAgLSBncm91cF9ieToKICAgICAgLSBydWxlX2lkCiAgICAgIG1hdGNoOgogICAgICAgIHJ1bGVfaWQ6IGMtZGJieno6bm9kZS1hbGVydF9ub2RlLWRpc2stcnVubmluZy1mdWxsCiAgICAgIGNvbnRpbnVlOiB0cnVlCiAgICAgIGdyb3VwX3dhaXQ6IDNtCiAgICAgIGdyb3VwX2ludGVydmFsOiAzbQogICAgICByZXBlYXRfaW50ZXJ2YWw6IDFoCiAgICAtIGdyb3VwX2J5OgogICAgICAtIHJ1bGVfaWQKICAgICAgbWF0Y2g6CiAgICAgICAgcnVsZV9pZDogYy1kYmJ6ejpub2RlLWFsZXJ0X2hpZ2gtbWVtbW9yeQogICAgICBjb250aW51ZTogdHJ1ZQogICAgICBncm91cF93YWl0OiAzbQogICAgICBncm91cF9pbnRlcnZhbDogM20KICAgICAgcmVwZWF0X2ludGVydmFsOiAxaAogICAgZ3JvdXBfd2FpdDogM20KICAgIGdyb3VwX2ludGVydmFsOiAzbQogICAgcmVwZWF0X2ludGVydmFsOiAxaAogIGdyb3VwX3dhaXQ6IDFtCiAgZ3JvdXBfaW50ZXJ2YWw6IDEwcwogIHJlcGVhdF9pbnRlcnZhbDogMWgKcmVjZWl2ZXJzOgotIG5hbWU6IHJhbmNoZXJsYWJzCiAgc2xhY2tfY29uZmlnczoKICAtIHNlbmRfcmVzb2x2ZWQ6IGZhbHNlCiAgICBjaGFubmVsOiAnI2FsZXJ0JwogICAgdGl0bGVfbGluazogIiIKLSBuYW1lOiBjLWRiYnp6Om5vZGUtYWxlcnQKICBzbGFja19jb25maWdzOgogIC0gc2VuZF9yZXNvbHZlZDogZmFsc2UKICAgIGFwaV91cmw6IGh0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzL1RHSzdVUFpLTS9CR0xROTBUQlEvcU9hR0pCM3hRSGd0dlpqYjEySHV0V0JNCiAgICBjaGFubmVsOiAnI21vbml0b3JfcHJvZCcKICAgIGNvbG9yOiAne3sgaWYgZXEgKGluZGV4IC5BbGVydHMgMCkuTGFiZWxzLnNldmVyaXR5ICJjcml0aWNhbCIgfX1kYW5nZXJ7eyBlbHNlCiAgICAgIGlmIGVxIChpbmRleCAuQWxlcnRzIDApLkxhYmVscy5zZXZlcml0eSAid2FybmluZyIgfX13YXJuaW5ne3sgZWxzZSB9fWdvb2R7ewogICAgICBlbmQgfX0nCiAgICB0aXRsZTogJ3t7IHRlbXBsYXRlICJyYW5jaGVyLnRpdGxlIiAuIH19JwogICAgdGl0bGVfbGluazogIiIKICAgIHRleHQ6ICd7eyB0ZW1wbGF0ZSAic2xhY2sudGV4dCIgLiB9fScKdGVtcGxhdGVzOgotIC9ldGMvYWxlcnRtYW5hZ2VyL2NvbmZpZy9ub3RpZmljYXRpb24udG1wbAo=
  notification.tmpl: Cnt7LSBkZWZpbmUgInJhbmNoZXIudGl0bGUiIC19fQp7ey0gaWYgZXEgLkNvbW1vbkxhYmVscy5hbGVydF90eXBlICJldmVudCIgfX0Ke3sgLkNvbW1vbkxhYmVscy5ldmVudF90eXBlfX0gZXZlbnQgb2Yge3suR3JvdXBMYWJlbHMucmVzb3VyY2Vfa2luZH19IG9jY3VycmVkCgp7ey0gZWxzZSBpZiBlcSAuQ29tbW9uTGFiZWxzLmFsZXJ0X3R5cGUgInN5c3RlbVNlcnZpY2UiIH19ClRoZSBzeXN0ZW0gY29tcG9uZW50IHt7IC5Hcm91cExhYmVscy5jb21wb25lbnRfbmFtZX19IGlzIG5vdCBydW5uaW5nCgp7ey0gZWxzZSBpZiBlcSAuQ29tbW9uTGFiZWxzLmFsZXJ0X3R5cGUgIm5vZGVIZWFsdGh5IiB9fQpUaGUga3ViZWxldCBvbiB0aGUgbm9kZSB7eyAuR3JvdXBMYWJlbHMubm9kZV9uYW1lfX0gaXMgbm90IGhlYWx0aHkKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAibm9kZUNQVSIgfX0KVGhlIENQVSB1c2FnZSBvbiB0aGUgbm9kZSB7eyAuR3JvdXBMYWJlbHMubm9kZV9uYW1lfX0gaXMgb3ZlciB7eyAuQ29tbW9uTGFiZWxzLmNwdV90aHJlc2hvbGR9fSUKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAibm9kZU1lbW9yeSIgfX0KVGhlIG1lbW9yeSB1c2FnZSBvbiB0aGUgbm9kZSB7eyAuR3JvdXBMYWJlbHMubm9kZV9uYW1lfX0gaXMgb3ZlciB7eyAuQ29tbW9uTGFiZWxzLm1lbV90aHJlc2hvbGR9fSUKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAicG9kTm90U2NoZWR1bGVkIiB9fQpUaGUgUG9kIHt7IGlmIC5Hcm91cExhYmVscy5uYW1lc3BhY2V9fXt7Lkdyb3VwTGFiZWxzLm5hbWVzcGFjZX19Ont7ZW5kfX17ey5Hcm91cExhYmVscy5wb2RfbmFtZX19IGlzIG5vdCBzY2hlZHVsZWQKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAicG9kTm90UnVubmluZyIgfX0KVGhlIFBvZCB7eyBpZiAuR3JvdXBMYWJlbHMubmFtZXNwYWNlfX17ey5Hcm91cExhYmVscy5uYW1lc3BhY2V9fTp7e2VuZH19e3suR3JvdXBMYWJlbHMucG9kX25hbWV9fSBpcyBub3QgcnVubmluZwoKe3stIGVsc2UgaWYgZXEgLkNvbW1vbkxhYmVscy5hbGVydF90eXBlICJwb2RSZXN0YXJ0cyIgfX0KVGhlIFBvZCB7eyBpZiAuR3JvdXBMYWJlbHMubmFtZXNwYWNlfX17ey5Hcm91cExhYmVscy5uYW1lc3BhY2V9fTp7e2VuZH19e3suR3JvdXBMYWJlbHMucG9kX25hbWV9fSByZXN0YXJ0cyB7eyAuQ29tbW9uTGFiZWxzLnJlc3RhcnRfdGltZXN9fSB0aW1lcyBpbiB7eyAuQ29tbW9uTGFiZWxzLnJlc3RhcnRfaW50ZXJ2YWx9fSBzZWMKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAid29ya2xvYWQiIH19ClRoZSB3b3JrbG9hZCB7eyBpZiAuR3JvdXBMYWJlbHMud29ya2xvYWRfbmFtZXNwYWNlfX17ey5Hcm91cExhYmVscy53b3JrbG9hZF9uYW1lc3BhY2V9fTp7e2VuZH19e3suR3JvdXBMYWJlbHMud29ya2xvYWRfbmFtZX19IGhhcyBhdmFpbGFibGUgcmVwbGljYXMgbGVzcyB0aGFuIHt7IC5Db21tb25MYWJlbHMuYXZhaWxhYmxlX3BlcmNlbnRhZ2V9fSUKCnt7LSBlbHNlIGlmIGVxIC5Db21tb25MYWJlbHMuYWxlcnRfdHlwZSAibWV0cmljIiB9fQpUaGUgbWV0cmljIHt7IC5Db21tb25MYWJlbHMuYWxlcnRfbmFtZX19IGNyb3NzZWQgdGhlIHRocmVzaG9sZCAKe3sgZW5kIC19fQp7eyBlbmQgLX19Cgp7ey0gZGVmaW5lICJ3ZWNoYXQudGV4dCIgLX19Cnt7IHRlbXBsYXRlICJfX3dlY2hhdF90ZXh0X2xpc3QiIC4gfX0Ke3sgZW5kIC19fQoKe3stIGRlZmluZSAiX193ZWNoYXRfdGV4dF9saXN0IiAtfX0Ke3sgdGVtcGxhdGUgInJhbmNoZXIudGl0bGUiIC4gfX0Ke3sgdGVtcGxhdGUgIl9fdGV4dF9saXN0IiAuIH19Cnt7IGVuZCAtfX0KCnt7LSBkZWZpbmUgInNsYWNrLnRleHQiIC19fQp7eyB0ZW1wbGF0ZSAiX190ZXh0X2xpc3QiIC4gfX0Ke3sgZW5kIC19fQoKe3stIGRlZmluZSAiX190ZXh0X2xpc3QiIC19fQp7eyByYW5nZSAuQWxlcnRzLkZpcmluZyB9fQp7eyB0ZW1wbGF0ZSAiX190ZXh0X3NpbmdsZSIgLiB9fQp7eyBlbmQgLX19Cnt7IGVuZCAtfX0KCnt7LSBkZWZpbmUgIl9fdGV4dF9zaW5nbGUiIC19fQpBbGVydCBOYW1lOiB7eyAuTGFiZWxzLmFsZXJ0X25hbWV9fQpTZXZlcml0eToge3sgLkxhYmVscy5zZXZlcml0eX19CkNsdXN0ZXIgTmFtZToge3suTGFiZWxzLmNsdXN0ZXJfbmFtZX19Cnt7LSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgImV2ZW50IiB9fQp7ey0gaWYgLkxhYmVscy53b3JrbG9hZF9uYW1lIH19Cldvcmtsb2FkIE5hbWU6IHt7LkxhYmVscy53b3JrbG9hZF9uYW1lfX0Ke3tlbmQgLX19ClRhcmdldDoge3sgaWYgLkxhYmVscy50YXJnZXRfbmFtZXNwYWNlIC19fXt7LkxhYmVscy50YXJnZXRfbmFtZXNwYWNlfX06e3sgZW5kIC19fXt7LkxhYmVscy50YXJnZXRfbmFtZX19CkNvdW50OiB7eyAuTGFiZWxzLmV2ZW50X2NvdW50fX0KRXZlbnQgTWVzc2FnZToge3sgLkxhYmVscy5ldmVudF9tZXNzYWdlfX0KRmlyc3QgU2Vlbjoge3sgLkxhYmVscy5ldmVudF9maXJzdHNlZW59fQpMYXN0IFNlZW46IHt7IC5MYWJlbHMuZXZlbnRfbGFzdHNlZW59fQp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgIm5vZGVDUFUiIH19ClVzZWQgQ1BVOiB7eyAuTGFiZWxzLnVzZWRfY3B1fX0gbQpUb3RhbCBDUFU6IHt7IC5MYWJlbHMudG90YWxfY3B1fX0gbQp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgIm5vZGVNZW1vcnkiIH19ClVzZWQgTWVtb3J5OiB7eyAuTGFiZWxzLnVzZWRfbWVtfX0KVG90YWwgTWVtb3J5OiB7eyAuTGFiZWxzLnRvdGFsX21lbX19Cnt7LSBlbHNlIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAicG9kUmVzdGFydHMiIH19ClByb2plY3QgTmFtZToge3sgLkxhYmVscy5wcm9qZWN0X25hbWV9fQpOYW1lc3BhY2U6IHt7IC5MYWJlbHMubmFtZXNwYWNlfX0Ke3stIGlmIC5MYWJlbHMud29ya2xvYWRfbmFtZSB9fQpXb3JrbG9hZCBOYW1lOiB7ey5MYWJlbHMud29ya2xvYWRfbmFtZX19Cnt7IGVuZCAtfX0KQ29udGFpbmVyIE5hbWU6IHt7IC5MYWJlbHMuY29udGFpbmVyX25hbWV9fQp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgInBvZE5vdFJ1bm5pbmciIH19ClByb2plY3QgTmFtZToge3sgLkxhYmVscy5wcm9qZWN0X25hbWV9fQpOYW1lc3BhY2U6IHt7IC5MYWJlbHMubmFtZXNwYWNlfX0Ke3stIGlmIC5MYWJlbHMud29ya2xvYWRfbmFtZSB9fQpXb3JrbG9hZCBOYW1lOiB7ey5MYWJlbHMud29ya2xvYWRfbmFtZX19Cnt7IGVuZCAtfX0KQ29udGFpbmVyIE5hbWU6IHt7IC5MYWJlbHMuY29udGFpbmVyX25hbWV9fQp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgInBvZE5vdFNjaGVkdWxlZCIgfX0KUHJvamVjdCBOYW1lOiB7eyAuTGFiZWxzLnByb2plY3RfbmFtZX19Ck5hbWVzcGFjZToge3sgLkxhYmVscy5uYW1lc3BhY2V9fQpQb2QgTmFtZToge3sgLkxhYmVscy5wb2RfbmFtZX19Cnt7LSBpZiAuTGFiZWxzLndvcmtsb2FkX25hbWUgfX0KV29ya2xvYWQgTmFtZToge3suTGFiZWxzLndvcmtsb2FkX25hbWV9fQp7eyBlbmQgLX19Cnt7LSBlbHNlIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAid29ya2xvYWQiIH19ClByb2plY3QgTmFtZToge3sgLkxhYmVscy5wcm9qZWN0X25hbWV9fQpBdmFpbGFibGUgUmVwbGljYXM6IHt7IC5MYWJlbHMuYXZhaWxhYmxlX3JlcGxpY2FzfX0KRGVzaXJlZCBSZXBsaWNhczoge3sgLkxhYmVscy5kZXNpcmVkX3JlcGxpY2FzfX0Ke3stIGVsc2UgaWYgZXEgLkxhYmVscy5hbGVydF90eXBlICJtZXRyaWMiIH19Cnt7LSBpZiAuTGFiZWxzLm5hbWVzcGFjZSB9fQpOYW1lc3BhY2U6IHt7IC5MYWJlbHMubmFtZXNwYWNlfX17eyBlbmQgfX0Ke3stIGlmIC5MYWJlbHMucHJvamVjdF9uYW1lIH19ClByb2plY3QgTmFtZToge3sgLkxhYmVscy5wcm9qZWN0X25hbWV9fXt7IGVuZCB9fQp7ey0gaWYgLkxhYmVscy5wb2RfbmFtZSB9fQpQb2QgTmFtZToge3sgLkxhYmVscy5wb2RfbmFtZX19e3sgZWxzZSBpZiAuTGFiZWxzLnBvZCAtfX1Qb2QgTmFtZToge3sgLkxhYmVscy5wb2R9fXt7IGVuZCB9fQpFeHByZXNzaW9uOiB7eyAuTGFiZWxzLmV4cHJlc3Npb259fQpEZXNjcmlwdGlvbjogVGhyZXNob2xkIENyb3NzZWQ6IGRhdGFwb2ludCB2YWx1ZSB7eyAuQW5ub3RhdGlvbnMuY3VycmVudF92YWx1ZX19IHdhcyB7eyAuTGFiZWxzLmNvbXBhcmlzb259fSB0byB0aGUgdGhyZXNob2xkICh7eyAuTGFiZWxzLnRocmVzaG9sZF92YWx1ZX19KSBmb3IgKHt7IC5MYWJlbHMuZHVyYXRpb259fSkKe3sgZW5kIC19fQp7ey0gaWYgLkxhYmVscy5sb2dzIH19CkxvZ3M6IHt7IC5MYWJlbHMubG9nc319Cnt7IGVuZCAtfX0Ke3sgZW5kIC19fQoKe3stIGRlZmluZSAiZW1haWwudGV4dCIgLX19Cnt7IHRlbXBsYXRlICJfX2VtYWlsX3RleHRfbGlzdCIgLiB9fQp7eyBlbmQgLX19Cgp7ey0gZGVmaW5lICJfX2VtYWlsX3RleHRfbGlzdCIgLX19Cnt7IHJhbmdlIC5BbGVydHMuRmlyaW5nIH19Cnt7IHRlbXBsYXRlICJfX2VtYWlsX3RleHRfc2luZ2xlIiAuIH19Cnt7IGVuZCAtfX0Ke3sgZW5kIC19fQoKe3stIGRlZmluZSAiX19lbWFpbF90ZXh0X3NpbmdsZSIgLX19CkFsZXJ0IE5hbWU6IHt7IC5MYWJlbHMuYWxlcnRfbmFtZX19PGJyPgpTZXZlcml0eToge3sgLkxhYmVscy5zZXZlcml0eX19PGJyPgpDbHVzdGVyIE5hbWU6IHt7LkxhYmVscy5jbHVzdGVyX25hbWV9fTxicj4Ke3stIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAiZXZlbnQiIH19Cnt7LSBpZiAuTGFiZWxzLndvcmtsb2FkX25hbWUgfX0KV29ya2xvYWQgTmFtZToge3suTGFiZWxzLndvcmtsb2FkX25hbWV9fTxicj4Ke3sgZW5kIC19fQpUYXJnZXQ6IHt7IGlmIC5MYWJlbHMudGFyZ2V0X25hbWVzcGFjZSAtfX17ey5MYWJlbHMudGFyZ2V0X25hbWVzcGFjZX19Ont7ZW5kIC19fXt7IC5MYWJlbHMudGFyZ2V0X25hbWV9fTxicj4KQ291bnQ6IHt7IC5MYWJlbHMuZXZlbnRfY291bnR9fTxicj4KRXZlbnQgTWVzc2FnZToge3sgLkxhYmVscy5ldmVudF9tZXNzYWdlfX08YnI+CkZpcnN0IFNlZW46IHt7IC5MYWJlbHMuZXZlbnRfZmlyc3RzZWVufX08YnI+Ckxhc3QgU2Vlbjoge3sgLkxhYmVscy5ldmVudF9sYXN0c2Vlbn19PGJyPgp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgIm5vZGVDUFUiIH19ClVzZWQgQ1BVOiB7eyAuTGFiZWxzLnVzZWRfY3B1fX0gbTxicj4KVG90YWwgQ1BVOiB7eyAuTGFiZWxzLnRvdGFsX2NwdX19IG08YnI+Cnt7LSBlbHNlIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAibm9kZU1lbW9yeSIgfX0KVXNlZCBNZW1vcnk6IHt7IC5MYWJlbHMudXNlZF9tZW19fTxicj4KVG90YWwgTWVtb3J5OiB7eyAuTGFiZWxzLnRvdGFsX21lbX19PGJyPgp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgInBvZFJlc3RhcnRzIiB9fQpQcm9qZWN0IE5hbWU6IHt7LkxhYmVscy5wcm9qZWN0X25hbWV9fTxicj4KTmFtZXNwYWNlOiB7eyAuTGFiZWxzLm5hbWVzcGFjZX19PGJyPgp7ey0gaWYgLkxhYmVscy53b3JrbG9hZF9uYW1lIH19Cldvcmtsb2FkIE5hbWU6IHt7LkxhYmVscy53b3JrbG9hZF9uYW1lfX08YnI+Cnt7IGVuZCAtfX0KQ29udGFpbmVyIE5hbWU6IHt7LkxhYmVscy5jb250YWluZXJfbmFtZX19PGJyPgp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgInBvZE5vdFJ1bm5pbmciIH19ClByb2plY3QgTmFtZToge3suTGFiZWxzLnByb2plY3RfbmFtZX19PGJyPgpOYW1lc3BhY2U6IHt7IC5MYWJlbHMubmFtZXNwYWNlfX08YnI+Cnt7LSBpZiAuTGFiZWxzLndvcmtsb2FkX25hbWUgfX0KV29ya2xvYWQgTmFtZToge3suTGFiZWxzLndvcmtsb2FkX25hbWV9fTxicj4Ke3sgZW5kIC19fQpDb250YWluZXIgTmFtZToge3sgLkxhYmVscy5jb250YWluZXJfbmFtZX19PGJyPgp7ey0gZWxzZSBpZiBlcSAuTGFiZWxzLmFsZXJ0X3R5cGUgInBvZE5vdFNjaGVkdWxlZCIgfX0KUHJvamVjdCBOYW1lOiB7ey5MYWJlbHMucHJvamVjdF9uYW1lfX08YnI+Ck5hbWVzcGFjZToge3sgLkxhYmVscy5uYW1lc3BhY2V9fTxicj4Ke3stIGlmIC5MYWJlbHMud29ya2xvYWRfbmFtZSB9fQpXb3JrbG9hZCBOYW1lOiB7ey5MYWJlbHMud29ya2xvYWRfbmFtZX19PGJyPgp7eyBlbmQgLX19ClBvZCBOYW1lOiB7eyAuTGFiZWxzLnBvZF9uYW1lfX08YnI+Cnt7LSBlbHNlIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAid29ya2xvYWQifX0KUHJvamVjdCBOYW1lOiB7ey5MYWJlbHMucHJvamVjdF9uYW1lfX08YnI+CkF2YWlsYWJsZSBSZXBsaWNhczoge3sgLkxhYmVscy5hdmFpbGFibGVfcmVwbGljYXN9fTxicj4KRGVzaXJlZCBSZXBsaWNhczoge3sgLkxhYmVscy5kZXNpcmVkX3JlcGxpY2FzfX08YnI+Cnt7LSBlbHNlIGlmIGVxIC5MYWJlbHMuYWxlcnRfdHlwZSAibWV0cmljIiB9fQp7ey0gaWYgLkxhYmVscy5wcm9qZWN0X25hbWUgfX0KUHJvamVjdCBOYW1lOiB7ey5MYWJlbHMucHJvamVjdF9uYW1lfX08YnI+Cnt7IGVuZCAtfX0Ke3stIGlmIC5MYWJlbHMucG9kX25hbWUgfX0KUG9kIE5hbWU6IHt7LkxhYmVscy5wb2RfbmFtZX19e3sgZWxzZSBpZiAuTGFiZWxzLnBvZCAtfX1Qb2QgTmFtZToge3suTGFiZWxzLnBvZH19PGJyPgp7eyBlbmQgLX19Cnt7LSBpZiAuTGFiZWxzLm5hbWVzcGFjZSB9fQpOYW1lc3BhY2U6IHt7LkxhYmVscy5uYW1lc3BhY2V9fTxicj4Ke3sgZW5kIC19fQpFeHByZXNzaW9uOiB7ey5MYWJlbHMuZXhwcmVzc2lvbn19PGJyPgpEZXNjcmlwdGlvbjogVGhyZXNob2xkIENyb3NzZWQ6IGRhdGFwb2ludCB2YWx1ZSB7eyAuQW5ub3RhdGlvbnMuY3VycmVudF92YWx1ZX19IHdhcyB7eyAuTGFiZWxzLmNvbXBhcmlzb259fSB0byB0aGUgdGhyZXNob2xkICh7eyAuTGFiZWxzLnRocmVzaG9sZF92YWx1ZX19KSBmb3IgKHt7IC5MYWJlbHMuZHVyYXRpb259fSk8YnI+Cnt7IGVuZCAtfX0Ke3stIGlmIC5MYWJlbHMubG9ncyB9fQpMb2dzOiB7eyAuTGFiZWxzLmxvZ3N9fQp7eyBlbmQgLX19Cjxicj4Ke3sgZW5kIC19fQo=
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

rancher/rancher:v2.2.0-rc2
rancher/prom-alertmanager:v0.16.1

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

Cluster type: imported ( created by kubeadm)

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:24:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
