### ISSUE TITLE
Rancher does not create new namespace when importing YAML through UI

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#18498]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Import YAML that references a nonexistent namespace:

```
apiVersion: v1
kind: Pod
metadata:
  namespace: idonotexist
  name: test-pod
  labels:
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:1.15-alpine
```

**Result:**

The UI reports that the Namespace `idonotexist` cannot be found.

**Other details that may be helpful:**

At the bottom of the Import YAML screen is a note that says, "If a resource specifies a namespace that doesn't exist, it will be created and added to this project."

**Environment information**
- 2.1.6
- single

- Docker version (use `docker version`):

```
18.09.2
```

![screen shot 2019-03-01 at 08 01 29](https://user-images.githubusercontent.com/171292/53634178-4362fe00-3bf8-11e9-94c2-a5d7b38bb31f.png)
