### ISSUE TITLE
Create doesn't create all circular links so starting in UI will not work, but starting in CLI does work

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1851]
Given this [docker-compose.yml](https://gist.github.com/vincent99/c4a4a74bdf0ae91bcb20), `rancher-compose up` will create all the links correctly:

![image](https://cloud.githubusercontent.com/assets/753917/9415513/c2643274-47f4-11e5-989f-ff4aa85ece9f.png)

Whilst `rancher-compose create` (+ optionally `start`) will not:

![image](https://cloud.githubusercontent.com/assets/753917/9415501/b7addb3c-47f4-11e5-9f04-0041b5edb046.png)

**Comment by JamesBarwell** [comment]
Just a note to say that I am also losing circular linking when using ```rancher-compose upgrade```. So in the example below I can build my V2 services with circular links using ```up```. But then when I upgrade, if foo is upgraded first, it will not be linked to bar - but bar will be linked to foo.

```
fooV2:
  image: tutum/hello-world
  links:
    - barV2:bar

barV2:
  image: tutum/hello-world
  links:
    - fooV2:foo

fooV3:
  image: tutum/hello-world
  stdin_open: true
  links:
    - barV3:bar

barV3:
  restart: always
  tty: true
  image: tutum/hello-world
  links:
    - fooV3:foo
```
