### ISSUE TITLE
Spin up with docker and nginx not working

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#18607]
Hi there, can someone help me?

I try to start a Rancher 2 server with SSL by using this docker-compose.yml
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:ro'
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes_from:
      - nginx-proxy
    volumes:
      - '/home/docker/nginx-proxy/ssl:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  rancher-server:
    image: rancher/rancher:stable
    restart: always
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=MY_HOST_COM
      - LETSENCRYPT_TEST=false
      - LETSENCRYPT_HOST=MY_HOST_COM
      - LETSENCRYPT_EMAIL=mail@MY_HOST_COM
      - CATTLE_DB_CATTLE_MYSQL_HOST=MY_IP_ADDRESS
      - CATTLE_DB_CATTLE_MYSQL_PORT=3306
      - CATTLE_DB_CATTLE_MYSQL_NAME=rancher_server
      - CATTLE_DB_CATTLE_USERNAME=rancher_server
      - CATTLE_DB_CATTLE_PASSWORD=MY_MYSQL_PW

```
but at the end of the spin-up process, it hangs there:

```
rancher-server_1                     | 2019/03/05 23:44:45 [INFO] uploading azureConfig to node schema
rancher-server_1                     | 2019/03/05 23:44:45 [INFO] uploading azureConfig to node schema
rancher-server_1                     | 2019/03/05 23:44:45 [INFO] uploading amazonec2Config to node schema
rancher-server_1                     | 2019/03/05 23:44:45 [INFO] uploading amazonec2Config to node schema
nginx-proxy_1                        | 2019/03/05 23:44:48 [notice] 90#90: signal process started
nginx-proxy_1                        | Generating DH parameters, 2048 bit long safe prime, generator 2
nginx-proxy_1                        | This is going to take a long time
nginx-proxy_1                        | dhparam generation complete, reloading nginx
rancher-server_1                     | 2019/03/05 23:44:48 [INFO] Updating catalog library
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:44:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
rancher-server_1                     | E0305 23:44:54.169574       6 clusterroleaggregation_controller.go:180] admin failed with : Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io "admin": the object has been modified; please apply your changes to the latest version and try again
rancher-server_1                     | 2019/03/05 23:44:59 [INFO] Catalog sync done. 30 templates created, 0 templates updated, 0 templates deleted
rancher-server_1                     | 2019/03/05 23:44:59 [ERROR] CatalogController library [catalog] failed with : failed to sync templates. Resetting commit. Multiple error occurred: [Error in HTTP GET of [file://../logo.png], error: Get file://../logo.png: unsupported protocol scheme "file"]
rancher-server_1                     | 2019/03/05 23:45:01 [INFO] Updating catalog library
rancher-server_1                     | 2019/03/05 23:45:02 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:45:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1

```

When I call my page shows `502 Bad Gateway
nginx/1.14.1` and the console ends up with this:

```
                       | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:54:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
rancher-server_1                     | 2019-03-05 23:54:29.345562 I | mvcc: store.index: compact 2221
rancher-server_1                     | 2019-03-05 23:54:29.354758 I | mvcc: finished scheduled compaction at 2221 (took 4.150322ms)
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:54:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:54:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:55:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:55:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:55:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:55:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:56:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_HOST_COM 84.113.179.246 - - [05/Mar/2019:23:56:16 +0000] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
nginx-proxy_1                        | nginx.1    | 2019/03/05 23:56:17 [error] 92#92: *49 no live upstreams while connecting to upstream, client: 84.113.179.246, server: MY_HOST_COM, request: "GET / HTTP/2.0", upstream: "http://MY_HOST_COM/", host: "MY_HOST_COM"
nginx-proxy_1                        | nginx.1    | MY_HOST_COM 84.113.179.246 - - [05/Mar/2019:23:56:17 +0000] "GET / HTTP/2.0" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
nginx-proxy_1                        | nginx.1    | 2019/03/05 23:56:18 [error] 92#92: *49 no live upstreams while connecting to upstream, client: 84.113.179.246, server: MY_HOST_COM, request: "GET /favicon.ico HTTP/2.0", upstream: "http://MY_HOST_COM/favicon.ico", host: "MY_HOST_COM", referrer: "https://MY_HOST_COM/"
nginx-proxy_1                        | nginx.1    | MY_HOST_COM 84.113.179.246 - - [05/Mar/2019:23:56:18 +0000] "GET /favicon.ico HTTP/2.0" 502 575 "https://MY_HOST_COM/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:56:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:56:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:56:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:57:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:57:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:57:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:57:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:58:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:58:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
rancher-server_1                     | E0305 23:58:31.879495       6 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:58:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:58:53 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:59:08 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:59:23 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
rancher-server_1                     | 2019-03-05 23:59:29.354256 I | mvcc: store.index: compact 2551
rancher-server_1                     | 2019-03-05 23:59:29.365476 I | mvcc: finished scheduled compaction at 2551 (took 3.431346ms)
nginx-proxy_1                        | nginx.1    | MY_IP_ADDRESS 138.201.187.48 - cloud66 [05/Mar/2019:23:59:38 +0000] "GET /haproxy?stats/;csv;norefresh HTTP/1.1" 503 213 "-" "Datadog Agent/6.8.3"
nginx-proxy_1
```

Any suggestion for the right direction would be a charm. Thank you
