### ISSUE TITLE
Tolerations loaded from catalog show up incorrect in user interface

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#18605]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) deploy datadog from catalog library item
2) Open workload
3) look at node scheduling> tolerations

**Result:**
Note that the user interface is display the tolerations incorrectly

**Other details that may be helpful:**
Tolerations seem to actually exist and work correctly until you make changes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.6
- Installation option (single install/HA): Single

**Comment by patrick0057** [comment]
Related to https://github.com/rancher/rancher/issues/18550

**Comment by westlywright** [comment]
This is available in the `latest-2.3`. QA can test with a 2.3 release or 2.3-master by replacing ui-index with `https://releases.rancher.com/ui/latest-2.3/index.html`

**Comment by sowmyav27** [comment]
**Reproduced the issue on `2.3.0` - `ui-index: local`**

**Steps:**

- deploy datadog from catalog library in Apps in an rke cluster
- Go to Workloads --> Datadog --> Node Scehduling --> Tolerations:

<img width="1438" alt="Screen Shot 2019-10-15 at 3 58 22 PM" src="https://user-images.githubusercontent.com/26032343/66876195-bc378000-ef65-11e9-9630-fabc584744b7.png">

- Workload --> view Edit YAML shows

```
tolerations:
      - key: node-role.kubernetes.io/etcd
        value: "true"
      - key: node-role.kubernetes.io/controlplane
        value: "true"
```

**Changed the UI tag to : `https://releases.rancher.com/ui/latest-2.3/index.html`**

**Steps:**

- On the existing Datadog workload --> Node Scheduling --> Tolerations:

<img width="1419" alt="Screen Shot 2019-10-15 at 3 59 03 PM" src="https://user-images.githubusercontent.com/26032343/66876282-19333600-ef66-11e9-91e9-491983df4579.png">

- View and edit YAML shows

```
tolerations:
      - key: node-role.kubernetes.io/etcd
        value: "true"
      - key: node-role.kubernetes.io/controlplane
        value: "true"
```
- Deploy a new Data dog app
- Go to Workloads --> Datadog --> Node Scehduling --> Tolerations:
- The tolerations are shown as expected.
- View and edit YAML shows tolerations as expected.
