### ISSUE TITLE
[rancher-compose] Failed to create circular links in services

### ISSUE THREAD

**Issue by JamesBarwell** [rancher/rancher#1863]
RancherOS: v0.4.0-rc2
Rancher: v0.32.0
Cattle: v0.75.0
User Interface: v0.40.0
Rancher Compose: v0.2.5

## Description
I have two services that link to each other, described in the docker-compose.yml. I build them using rancher-compose.

## Expected
Two services are created with links to each other.

## Actual
Only one of the services links to the other, and I receive a warn in the rancher-compose output.

## Details

Two services defined:
```
foo:
  restart: always
  tty: true
  image: tutum/hello-world
  stdin_open: true
  links:
    - bar:bar

bar:
  restart: always
  tty: true
  image: tutum/hello-world
  stdin_open: true
  links:
    - foo:foo
```
```
foo:
  scale: 1

bar:
  scale: 1
```
and I build them: 
```
rancher-compose -f test/docker-compose.yml -r test/rancher-compose.yml create
INFO[0000] Creating environment test
INFO[0000] Creating service foo
WARN[0000] Failed to find service bar to link to
INFO[0000] Creating service bar
```

The services show up in the GUI with only bar linking to foo, and foo having no links. But the order seems to be random and quite often I see bar linking to foo, and foo linking to nothing. If I add the missing link using the GUI, it does appear successfully.

Is this functionality supported? Cheers.
