### ISSUE TITLE
Pipeline build exceeding default memory limit gets OOM killed

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#18716]
**Rancher Version:**
master 3/8

**Steps to reproduce (least amount of steps as possible):**
1. Run the following pipeline:
```
stages:
- name: build
  steps:
  - runScriptConfig:
      image: polinux/stress
      shellScript: stress -m 1 --vm-bytes 2G --vm-keep --timeout 10s
```

**Result:**
![image](https://user-images.githubusercontent.com/5697937/54018336-56ab3600-41c3-11e9-9b26-3481036fc130.png)

**Other details that may be helpful:**
It succeeds if the configuration goes:
```
stages:
- name: build
  steps:
  - runScriptConfig:
      image: polinux/stress
      shellScript: stress -m 1 --vm-bytes 2G --vm-keep --timeout 10s
    memoryLimit: 3Gi
```

This can break pipelines from previous versions. There is probably no reasonable default limits for containers of `build image` and `run script` step, since they executes user-defined content.
