### ISSUE TITLE
Random notifier will be picked in Pipeline if we use notifier name as the target

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18726]
rancher/rancher:v2.2.0-rc2

Steps:

1. Create 2 notifiers with the same name
2. In pipeline yaml, use the name as the notifier `field` of recipients.
```yaml
stages:
  - name: Build something
    steps:
    - runScriptConfig:
        image: busybox
        shellScript: ls
notification:
  recipients:
  - # Recipient
    recipient: "#mychannel"
    # ID of Notifier
    notifier: "myslack"
``` 

Results:

One of the notifiers will be picked if pipeline sends out the message.

Expected:

We should send out the message to all of the notifiers with the same name. Or we should not support name at all.
