### ISSUE TITLE
Pipeline app docker registry authentication error

### ISSUE THREAD

**Issue by steebchen** [rancher/rancher#18753]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

Error: 
`Failed to pull image "127.0.0.1:34987/api:1": rpc error: code = Unknown desc = Error response from daemon: unauthorized: authentication required`

**Steps to reproduce (least amount of steps as possible):**

```
# .rancher-pipeline.yml
stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
```

**Other details that may be helpful:**
Everything in the pipeline works fine, just the final pod can't launch:

![Selection_999(1107)](https://user-images.githubusercontent.com/5013932/54063848-a6175380-420f-11e9-85e9-19e980ab1a25.jpg)

![Selection_999(1108)](https://user-images.githubusercontent.com/5013932/54063920-2a69d680-4210-11e9-8b2f-d5b70bfbfd0d.jpg)

**Somehow, the automatically created secret has null-values for both the username and password, which is probably why it fails.**
Shouldn't it be set automatically, though?

Also, it would be great if the pipeline namespace (i.e. for jenkins, registry etc.) could be edited.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.0-rc2
- Installation option (single install/HA): single install

**Comment by gitlawr** [comment]
To deploy workloads from private registries by yaml file, you need to configure imagepullsecrets in the yaml spec. If you are using the internal registry, use the name `pipeline-docker-registry`, take a look at the example here: https://github.com/rancher/pipeline-example-go/blob/master/deployment.yaml#L30

**Comment by steebchen** [comment]
I have specified the pipeline-docker-registry secret in my deployment.yaml from the start: 

```yaml
kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: api
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
```
