### ISSUE TITLE
Question file does not update if dropdown changed

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#18782]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- load an catalog app with a dropdown
- change dropdown values

**Result:**
It should change fields, but it doesn't

**Other details that may be helpful:**
questions.yml
```

questions:
  # Database settings
  - variable: env.open.DATABASE
    description: "Select prefered Database"
    label: "Database"
    required: true
    type: enum
    group: "Database"
    options:
      - "InfluxDB"
      - "POSTGRES"
  - variable: usersDb.env.INFLUX_USER
    label: "InfluxDB Admin Username"
    show_if: "env.open.DATABASE=InfluxDB"
    default: "admin"
    description: "Username for InfluxDB"
    type: string
  - variable: usersDb.env.INFLUX_PASSWORD
    label: "InfluxDB Admin password"
    show_if: "env.open.DATABASE=InfluxDB"
    default: "admin"
    description: "Password for InfluxDB"
    type: string
  - variable: usersDb.env.POSTGRES_USER
    label: "POSTGRES Admin Username"
    show_if: "env.open.DATABASE=POSTGRES"
    default: "admin"
    description: "Username for POSTGRES"
    type: string
  - variable: usersDb.env.POSTGRES_PASSWORD
    label: "POSTGRES Admin password"
    show_if: "env.open.DATABASE=POSTGRES"
    default: "admin"
    description: "Password for POSTGRES"
    type: string

```

![2019-03-11 12 35 44](https://user-images.githubusercontent.com/1597621/54121564-17ffc080-43fb-11e9-87d1-1f64bafe305e.gif)

**Environment information**
- Rancher version (`rancher/rancher 2.1.7`)
- Installation option (single install/HA): single installation

**Cluster information**
- Cluster type (Custom):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```yaml
> docker version
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
