### ISSUE TITLE
APi-server consume all Host RAM after update from 1.11.6 to 1.13.4 with rke 0.1.17

### ISSUE THREAD

**Issue by reymonlu** [rancher/rancher#18826]
**What kind of request is this (question/bug/enhancement/feature request):**
After the try to upgrading the Kubernetes version from 1.11.6 to 1.13.4 with rke 0.1.17, the component kube-apiserver grow in memory to overload the RAM amount of the host. After some hours of unsuccessful try to repair this kube-apiserver, i decided to delete my cluster by cleaning up all the nodes with this method https://rancher.com/docs/rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes/. And start the restore process of restoring.
My cluster.yml file
```yaml
nodes:
- address: xxxxx
  port: "22"
  internal_address: xxxxxxxx
  role:
  - controlplane
  - etcd
  hostname_override: docker-master-test-1
  user: docker
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  labels: {}
  #- address: xxxxxxx
  #  port: "22"
  #  internal_address: xxxxxxx
  #  role:
  #  - worker
  #  hostname_override: docker-worker-test-1
  #  user: docker
  #  docker_socket: /var/run/docker.sock
  #  ssh_key: ""
  #  ssh_key_path: ~/.ssh/id_rsa
  #  labels: {}
  #- address: xxxxxxx
  #  port: "22"
  #  internal_address: xxxxx
  #  role:
  #  - worker
  #  hostname_override: docker-worker-test-2
  #  user: docker
  #  docker_socket: /var/run/docker.sock
  #  ssh_key: ""
  #  ssh_key_path: ~/.ssh/id_rsa
  #  labels: {}
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    snapshot: true
    retention: 32h
    creation: 6h
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
  kube-controller:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
authentication:
  strategy: x509
  options: {}
  sans: []
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.2.18
  alpine: rancher/rke-tools:v0.1.15
  nginx_proxy: rancher/rke-tools:v0.1.15
  cert_downloader: rancher/rke-tools:v0.1.15
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.15
  kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
  kubedns_sidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
  
  # kubernetes: rancher/hyperkube:v1.11.3-rancher1
  flannel: rancher/coreos-flannel:v0.10.0
  flannel_cni: rancher/coreos-flannel-cni:v0.3.0
  calico_node: rancher/calico-node:v3.1.3
  calico_cni: rancher/calico-cni:v3.1.3
  calico_controllers: ""
  calico_ctl: rancher/calico-ctl:v2.0.0
  canal_node: rancher/calico-node:v3.1.3
  canal_cni: rancher/calico-cni:v3.1.3
  canal_flannel: rancher/coreos-flannel:v0.10.0
  wave_node: weaveworks/weave-kube:2.1.2
  weave_cni: weaveworks/weave-npc:2.1.2
  pod_infra_container: rancher/pause-amd64:3.1
  ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.4
  metrics_server: rancher/metrics-server-amd64:v0.2.1
ssh_key_path: ~/.ssh/id_rsa
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
# kubernetes_version permet de définir la version que l'on souhaite appliqué au cluster
kubernetes_version: "v1.11.6-rancher1-1"
private_registries: []
ingress:
  provider: none
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
monitoring:
  provider: ""
  options: {}
```

but it shows me the next error with the commande  : 
```
$ rke-0.1.16 up --config cluster.yml 
INFO[0000] Building Kubernetes cluster
INFO[0000] [dialer] Setup tunnel for host [129.88.176.130]
INFO[0000] [state] Found local kube config file, trying to get state from cluster
INFO[0000] [reconcile] Local config is not valid, rebuilding admin config
INFO[0000] [reconcile] Rebuilding and updating local kube config
INFO[0000] Successfully Deployed local admin kubeconfig at [./kube_config_cluster.yml]
INFO[0000] [state] Fetching cluster state from Kubernetes
INFO[0030] Timed out waiting for kubernetes cluster to get state
INFO[0030] [state] Fetching cluster state from Nodes
INFO[0030] [state] Successfully fetched cluster state from Nodes
INFO[0030] [certificates] Getting Cluster certificates from Kubernetes
INFO[0030] [certificates] Successfully started [cert-fetcher] container on host [129.88.176.130]
INFO[0034] [certificates] Certificate backup found on backup hosts
INFO[0034] [network] No hosts added existing cluster, skipping port check
INFO[0034] [reconcile] Reconciling cluster state
INFO[0034] [reconcile] Check etcd hosts to be deleted
INFO[0034] [reconcile] Check etcd hosts to be added
INFO[0034] [hosts] Cordoning host [129.88.176.131]
FATA[0034] Failed to delete worker node [129.88.176.131] from cluster: Get https://129.88.176.130:6443/api/v1/nodes?timeout=30s: dial tcp 129.88.176.130:6443: getsockopt: connection refused
```

If I understand, there is a problem with the api connection but it is not yet starting... The port 6443 can be accessible, i verify it with netcat.

**Steps to reproduce (least amount of steps as possible):**

**Result:**
Cluster working again.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
 not installed
- Installation option (single install/HA):
HA 1 nodes [etcd,control] 3 nodes [worker]

**Cluster information**
- Cluster type :  Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
