### ISSUE TITLE
vSphere Cloud Provider is unable to detect VMs that are not on the root level of a DC

### ISSUE THREAD

**Issue by ThunderRush** [rancher/rancher#18949]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Set up Rancher 2.1.7 on a HA Cluster
Create a new Cluster via vSphere driver on a folder that isn't the root of the DC (In this example, the machines are in Productive/DHQ/Non-Prod
Use a custom cloud prrovider, and edit the cluster YAML:

```cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      insecure-flag: true
    virtual_center:
      xxx:
        user: xxx
        password: xxx
        datacenters: DC1
    workspace:
      server: xxx
      datacenter: DC1
      default-datastore: ATDC1-SAN03_TPP01_0_Vol01_TFO0
      folder: rancher-disks
    disk:
      scsicontrollertype: pvscsi
    network:
      public-network: DHQ-1147-it_test
```

Create a new Storage Class in the Cluster. Leave all settings as default.
Create a new volume in a namespace, select the created Storage Class.

**Result:**
Volume is stuck in "Pending",
kube-controller-manager reports:
`I0315 09:29:20.465962       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"testvv", UID:"4ab81468-4704-11e9-b23d-0050568c8608", APIVersion:"v1", ResourceVersion:"3585", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' Failed to provision volume with StorageClass "default": No VM found`

**Other details that may be helpful:**
If you do not specifiy a folder in your node template, and then repeat the steps, creating a new volume works without a problem.

**Environment information**
- Rancher version: 2.17
- Installation option: HA

**Cluster information**
- Cluster type: Infrastructure Provider
- Machine type: VM 2 CPUs/ 4GB
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ThunderRush** [comment]
Update. I was wrong when it comes to the actual cause of this issue.
Using vSphere as a Storage Class provider works correctly, and it can detect machines that are nested in folders.

However. The documentation (https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/vsphere/) on this topic is wrong/misleading. The description of Workspace -> Folder reads as:

`folder | string | * | Path of folder in which to create dummy VMs used for volume provisioning (relative from the root of the datastore), e.g. “kubernetes”.`

This is wrong, however. folder needs to be the absolute path of the machines that want to use a vSphere volume. i.e: "vm/Productive/Company/Non-Prod"

This is also reflected in the offical VMWare Topic (https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html) on this issue:

`folder is the virtual center VM folder path under the datacenter`

**Comment by Busch** [comment]
I got the same issue:
`Failed to provision volume with StorageClass "vsphere": No VM found`

In vCenter, if I go to "VMs and Templates" I see the following hierarchy:
```
vCenterServerName
     ClusterName
          FolderName
```

ClusterName is LAB
FolderName is MIW

My CloudProvider configuration:

```
cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
    disk: 
      scsicontrollertype: "pvscsi"
    global: 
      insecure-flag: true
      port: "443"
      soap-roundtrip-count: 0
    virtual_center: 
      10.19.0.56: 
        datacenters: "LAB"
        soap-roundtrip-count: 0
        user: "rancher@vsphere.local"
    workspace: 
      datacenter: "LAB"
      default-datastore: "EF550"
      folder: "/vm/MIW"
      server: "10.19.0.56"

```
What am I getting wrong?

**Comment by mickpik** [comment]
@Busch Have you been able to get this working in the meanwhile? I am running into the same issue

**Comment by cdivitotawela** [comment]
Sometime back I got this issue fixed apparently referring the same thread. However I don't remember exactly what I did. I will suggest couple of things to try.

Try updating provider ids as per https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#update-all-node-providerid-fields

Try this as well. 
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/faqs.html#how-can-diskenableuuid-enabled-on-node-vms

**Comment by PhilipSchmid** [comment]
@cdivitotawela Thanks for the hint! The process from https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#update-all-node-providerid-fields fixed it for me.

Before:
```bash
kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'
[
  "testing-master-1",
  null,
  "420B82EB-5654-3921-83E2-C6C9A1D9E3AF"
]
[
  "testing-master-2",
  null,
  "420B52C4-1C35-7B60-428F-92E9F31E05AD"
]
[
  "testing-master-3",
  null,
  "420BBCEF-3F73-7920-12F8-A6AE99744D07"
]
[
  "testing-worker-1",
  null,
  "420BD331-198A-5DF0-1144-A15DAAC386D0"
]
[
  "testing-worker-2",
  null,
  "420B4951-B3F1-B60B-3A75-00C82DF17CED"
]
[
  "testing-worker-3",
  null,
  "420B47B2-B3D2-9A58-7168-0461CAADDE88"
]
```

Fix: 
```bash
kubectl patch node testing-master-1 -p "{\"spec\":{\"providerID\":\"vsphere://420b82eb-5654-3921-83e2-c6c9a1d9e3af\"}}"
kubectl patch node testing-master-2 -p "{\"spec\":{\"providerID\":\"vsphere://420b52c4-1c35-7b60-428f-92e9f31e05ad\"}}"
kubectl patch node testing-master-3 -p "{\"spec\":{\"providerID\":\"vsphere://420bbcef-3f73-7920-12f8-a6ae99744d07\"}}"
kubectl patch node testing-worker-1 -p "{\"spec\":{\"providerID\":\"vsphere://420bd331-198a-5df0-1144-a15daac386d0\"}}"
kubectl patch node testing-worker-2 -p "{\"spec\":{\"providerID\":\"vsphere://420b4951-b3f1-b60b-3a75-00c82df17ced\"}}"
kubectl patch node testing-worker-3 -p "{\"spec\":{\"providerID\":\"vsphere://420b47b2-b3d2-9a58-7168-0461caadde88\"}}"
```

After:
```bash
kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]'
[
  "testing-master-1",
  "vsphere://420b82eb-5654-3921-83e2-c6c9a1d9e3af",
  "420B82EB-5654-3921-83E2-C6C9A1D9E3AF"
]
[
  "testing-master-2",
  "vsphere://420b52c4-1c35-7b60-428f-92e9f31e05ad",
  "420B52C4-1C35-7B60-428F-92E9F31E05AD"
]
[
  "testing-master-3",
  "vsphere://420bbcef-3f73-7920-12f8-a6ae99744d07",
  "420BBCEF-3F73-7920-12F8-A6AE99744D07"
]
[
  "testing-worker-1",
  "vsphere://420bd331-198a-5df0-1144-a15daac386d0",
  "420BD331-198A-5DF0-1144-A15DAAC386D0"
]
[
  "testing-worker-2",
  "vsphere://420b4951-b3f1-b60b-3a75-00c82df17ced",
  "420B4951-B3F1-B60B-3A75-00C82DF17CED"
]
[
  "testing-worker-3",
  "vsphere://420b47b2-b3d2-9a58-7168-0461caadde88",
  "420B47B2-B3D2-9A58-7168-0461CAADDE88"
]
```

Finally I needed to reboot all nodes in order to restart the kublets, kube-apiserver etc.. Now it works perfect again.

Regards,
Philip

**Comment by ngealy** [comment]
I was getting the same error: "No VM found"

Following this https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/troubleshooting/ to look at the logs, I found that my control plan node did not have the providerID set and that was causing the problem.  It seems like if you don't have the cloud_provider setup when you initially launch the cluster using Rancher, then the providerID is not set properly. 

In my case, to fix it, I deleted the cluster and recreated it while providing the correct cloud_provider config as yaml.

```yaml
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk:
        scsicontrollertype: pvscsi
      global:
        insecure-flag: true
      network: {}
      virtual_center:
        vcenter.company.com:
          datacenters: mydatacenter
          port: '443'
          user: admin@vsphere.local
          password: SuperSecret
      workspace:
        datacenter: mydatacenter
        default-datastore: Local#SSD#1
        folder: vm/dev
        server: vcenter.company.com
```
