### ISSUE TITLE
[Question] Why pipeline network is too slow

### ISSUE THREAD

**Issue by LucasHCruz** [rancher/rancher#18944]
**Steps to reproduce (least amount of steps as possible):**
1 - I've created a cluster for CI/CD and I've installed a Sonatype Nexus from helm to manage my artifacts.
2 - I'm using maven to manage my project dependencies.
3 - I configured a pipeline in another cluster with a step to build my artifact and generate the Docker image.
4 - My script does a "mvn clean install" command.

When the pipeline is running, the artifact download gets stuck in a random artifact.
```
Progress (3): 1.0/3.4 MB | 0.4/1.9 MB | 72 kB
Progress (3): 1.0/3.4 MB | 0.4/1.9 MB | 72 kB
Progress (3): 1.0/3.4 MB | 0.4/1.9 MB | 72 kB
                                             
Downloaded from Nexus: http://my-nexus/repository/b2b-group/org/springframework/security/spring-security-crypto/5.0.11.RELEASE/spring-security-crypto-5.0.11.RELEASE.jar (72 kB at 619 kB/s)
02:10:13 Progress (2): 1.0/3.4 MB | 0.4/1.9 MB
                                     
Downloading from Nexus: http://my-nexus/repository/b2b-group/io/github/openfeign/feign-slf4j/9.5.1/feign-slf4j-9.5.1.jar
```
Obs.: **The artifact download only gets stuck inside the pipeline.**

If I execute the same command inside an arbitrary  POD, all the downloads work fine.

My question is:

**How can I troubleshoot this issue**?  I do not even wonder where to start.

Additional informations:

My pipeline yaml:
```
stages:
- name: Create the artifact
  steps:
  - runScriptConfig:
      image: maven:3.5.2-jdk-8
      shellScript: mvn -T 1C clean install -DskipUTs -DskipITs
- name: Build and publish the image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: account/app:${CICD_GIT_TAG}
      pushRemote: true
      registry: index.docker.io
- name: Deploy to environment
  steps:
  - applyYamlConfig:
      path: ./k8s.yaml
timeout: 60
```

The runScript stuck:
![image](https://user-images.githubusercontent.com/4612865/54405853-976ce880-46b6-11e9-874e-e1b09daa49ac.png)
