### ISSUE TITLE
Kubernetes Version is empty when editing cluster v2.2.0-rc6

### ISSUE THREAD

**Issue by Troyhy** [rancher/rancher#18985]
*Kubernetes version dropdown is empry*

![image](https://user-images.githubusercontent.com/587882/54513671-bee6de00-4960-11e9-88be-cec256b2aeb7.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc6` UI: `v2.2.9` |
|Route|`authenticated.cluster.edit`|

**Comment by davidnuzik** [comment]
Assigned to me to test this and try to reproduce/gather details

**Comment by davidnuzik** [comment]
I am having a hard time reproducing this in v2.2.0-rc6 and latest master. I tried various RKE providers: DigitalOcean, Azure, EC2 and could not reproduce with any of those. I used Flannel networking as pictured.

**Comment by Troyhy** [comment]
Cluster is using Hetzner driver https://github.com/JonasProgrammer/docker-machine-driver-hetzner
and is updated from earlier RC releases.

I tested same setup from fresh install of RC6 and it works as it should.

**Comment by Troyhy** [comment]
Is there any log or other info that might help you or at least me to fix the issue in this cluster?

**Comment by GregorPirolt** [comment]
@Troyhy I got the same problem. I also got the empty fields when creating a new cluster from the same rancher instance. I tried to export the cluster with the rancher cli and the use rancher up with the output. No success. Seems like the process of upgrading from 2.1.6 to alpha-3 and then all rc releases up to 8 messed up the etcd somehow... I also compacted and defraged the etcd inside rancher with no success.

**Comment by Troyhy** [comment]
@GregorPirolt How did you manage interact with etcd of Rancher install? I have single node install...

**Comment by Troyhy** [comment]
In my case deploying fresh cluster does not solve issue, there is something wrong in rancher's own data structures. All new clusters provisioned will suffer of this same issue. in addition whole setting yaml of cluster is uneditable and missin lot of stuff...
Here is the whole settings.yaml, It always remains this if I try to edit it.
```yaml
driver_name: "rancherkubernetesengine"
# 
#   # Rancher Config
# 
docker_root_dir: "/var/lib/docker"
enable_cluster_alerting: false
enable_cluster_monitoring: true
enable_network_policy: false
local_cluster_auth_endpoint: 
  enabled: true
name: "sandbox"
```
