### ISSUE TITLE
Cannot provision rancher cluster in HA mode - Kube apiserver fails

### ISSUE THREAD

**Issue by DanCharousek** [rancher/rancher#19069]
**What kind of request is this: bug**

**Steps to reproduce:**
1. Setup 3 Digital Ocean droplets (docker-s-1vcpu-2gb-fra1-01/02/03)
2. Configure rancher-cluster.yml

```
nodes:
  - address: XXX.XXX.XXX.XXX
    internal_address: 10.XXX.XXX.XX
    user: root
    role: [controlplane,worker,etcd]
  - address: XXX.XXX.XXX.XXX
    internal_address: 10.XXX.XXX.XX
    user: root
    role: [controlplane,worker,etcd]
  - address: XXX.XXX.XXX.XXX
    internal_address: 10.XXX.XXX.XX
    user: root
    role: [controlplane,worker,etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
```

3. Startup cluster provisioning `rke up --ssh-agent-auth --config rancher-cluster.yml`

**Result:**

```
FATA[0264] [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [XXX.XXX.XXX.XXX]: Get https://localhost:6443/healthz: EOF, log: I0321 20:47:24.458670       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.
```

**Other details that may be helpful:**
I SSHed into the nodes and found out that the healthchecks issues are caused by `kube-apiserver` container that would not start up. This is the error message that `docker logs kube-apiserver` returns:

```
F0321 20:44:36.007795       1 storage_decorator.go:57] Unable to create storage backend: config (&{etcd3 /registry [https://10.XXX.XXX.XXX:2379 https://10.XXX.XXX.XXX:2379 https://10.XXX.XXX.XXX:2379] /etc/kubernetes/ssl/kube-node-key.pem /etc/kubernetes/ssl/kube-node.pem /etc/kubernetes/ssl/kube-ca.pem true 0xc00066fef0 <nil> 5m0s 1m0s}), err (context deadline exceeded)
```

I think this error is key to the problem, but unfortunately I'm not able to read it from it.

**Environment information**
- Rancher version:
  - rancher/hyperkube:v1.13.4-rancher1
  - rancher/rke-tools:v0.1.16
  - rancher/coreos-etcd:v3.2.24
- Installation option: HA
- Docker version on nodes (droplets): Docker version 18.09.2, build 6247962
- Rke version on my host: rke version v0.1.17
- Kubectl version on my host: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Docker version (use `docker version`):

```
Docker version 18.09.2, build 6247962
```

Thank you for any help and suggestions.
