### ISSUE TITLE
Configs generated for LB with ssl enabled listeners does not have any information about certs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1909]
Server version - Build from master - Aug 26

Create LB service with ssl enabled listeners and few certificates.
YML Configs generated for LB service with ssl enabled listeners does not have any information about certs.

**Comment by sangeethah** [comment]
Tested with server build from master - Sep 4

ssl ports are indicated using labels:

io.rancher.loadbalancer.ssl.ports: '400'

Certs are present in rancher-compose.yml in LB service section:

```
LB-test721471:
  scale: 2
  certs:
  - test-919305
  - test-388082
  default_cert: test-639611
```
