### ISSUE TITLE
Feature request - Grafana loki support (log aggregation)

### ISSUE THREAD

**Issue by riaan53** [rancher/rancher#19125]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
With the v6 release of Grafana they added Loki support https://github.com/grafana/loki and will be awesome if Rancher can make it an option to enable for logs.

Looks like they have a fluentd plugin: https://github.com/grafana/loki/tree/master/fluentd/fluent-plugin-loki

**Comment by LinAnt** [comment]
I tested loki with loki promtail on rancher. It works really well. Getting it integrated into the existing grafana would be awesome.

**Comment by gabrielcalderon** [comment]
This would be awesome! 😁

**Comment by RRadziejewski** [comment]
+1

**Comment by Razikus** [comment]
+1

**Comment by PKuebler** [comment]
i love loki =) its so easy to use.

**Comment by nickvth** [comment]
+ 1

**Comment by nickvth** [comment]
This would be awesome indeed!

**Comment by LinAnt** [comment]
Okay, so I bumped the image to 6.1.6 and added loki as a datasource in the config map. Everything is working as expected so far :)

**Comment by khauser** [comment]
@LinAnt Great 😃! Did you add Loki to your cluster? How? And then, what did you add in the configmap?

**Comment by LinAnt** [comment]
Datasources.yaml
```yaml
apiVersion: 1

datasources:
- name: RANCHER_MONITORING
  type: prometheus
  access: proxy
  basicAuth: false
  editable: false
  isDefault: true
  url: http://prometheus-operated:9090
- name: pg-loki
  type: loki
  access: proxy
  url: http://loki.loki.svc.cluster.local:3100
  editable: false
```

I installed loki using Helm template. They recommend using regular helm install, but we don't want tiller in any of our clusters, hence I opted for using template.

We use promtail for shipping logs, but ranchers fluentd can possibly work just as well.
