### ISSUE TITLE
rancher ingress Initializing

### ISSUE THREAD

**Issue by zhuer0632** [rancher/rancher#19135]
**What kind of request is this (question/bug/enhancement/feature request):**

bug 

**Steps to reproduce (least amount of steps as possible):**

rancher ingress Initializing 

**Other details that may be helpful:**

rancher  2.2.0 rc13
k3s      0.3.0-rc1

Although the state of the ingress is inilization, the domain name is accessible after being resolved to the node.

![bug](https://user-images.githubusercontent.com/1808782/54899231-1d383180-4f0a-11e9-8904-cdfc4c6994ae.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
root@ubuntu-s-rks-master:~# k3s kubectl  version 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4-k3s.1", GitCommit:"7f72ee72d6dce73e2d36dbd3402413d146fad01e", GitTreeState:"clean", BuildDate:"2019-03-04T01:05+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4-k3s.1", GitCommit:"7f72ee72d6dce73e2d36dbd3402413d146fad01e", GitTreeState:"clean", BuildDate:"2019-03-04T01:05+00:00Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by vkukk** [comment]
I'm having indentical issue with Gitlab installation running on OVH public cloud (Openstack, does not have any loadbalancer). Following nginx-ingress config is in use:
```yaml
nginx-ingress:
  enabled: true
  controller:
    hostNetwork: true
    kind: DaemonSet
    service:
      type: ClusterIP
      externalTrafficPolicy: false

**Comment by vkukk** [comment]
For me, setting kind to nodePort and specifying externalIPs for service, solved issue.

**Comment by jhughes2112** [comment]
Here's how I solved it correctly for my setup.  When I went to the node that is running the controller and checked the logs on it, like so:
```
docker logs -f k8s_nginx-ingress-controller_nginx-ingress-controller-etcetcetc
```
A new log line popped up every 30 seconds or so that looks like this:
```
W0120 03:42:59.332901       6 status.go:278] error updating ingress rule: ingresses.networking.k8s.io "rancher-demo" is forbidden: User "system:serviceaccount:ingress-nginx:nginx-ingress-serviceaccount" cannot update resource "ingresses/status" in API group "networking.k8s.io" in the namespace "default"
```
I had an issue where the nginx ingress ClusterRole was incorrectly configured to have less permissions than it needs to update the `ingress/status` field with the IP address it got from the LoadBalancer, which is why Rancher UI shows it not being initialized.  I had to edit the ClusterRole for my ingress-nginx controller and make sure the part that gives permissions to the ingresses/status looks like this:
```
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses/status
  verbs:
  - update
```
It's worth noting that my ingress-nginx is in a different namespace than my deployments, so I think other people may not have exactly the same problems, but it's worth checking.

Good luck!

**Comment by ChrisMcKee** [comment]
Thought the permission change would fix this but (in the case of haproxy) the config update verb already exists under extensions
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-ingress
    meta.helm.sh/release-namespace: haproxy-ingress
  creationTimestamp: "2020-06-25T14:00:40Z"
  labels:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.4.5
    helm.sh/chart: kubernetes-ingress-1.3.2
    io.cattle.field/appId: haproxy-ingress
  name: haproxy-ingress-kubernetes-ingress
  resourceVersion: "20346"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/haproxy-ingress-kubernetes-ingress
  uid: 2012446d-41b3-4b0a-8479-1de52590a592
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - services
  - namespaces
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - networking.k8s.io/v1beta1
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io/v1beta1
  resources:
  - ingresses/status
  verbs:
  - get
  - list
  - watch
  - update
```

regardless adding it doesnt seem to fix anything 🤷  and there are no errors on the ingress backend.

**Comment by ChrisMcKee** [comment]
In comparison
```
helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
helm repo update
kubectl create namespace ingress-haproxy
helm install haproxy-ingress incubator/haproxy-ingress --namespace ingress-haproxy --set rbac.create=true --set controller.kind=DaemonSet --set controller.hostNetwork=true --set controller.dnsPolicy=ClusterFirst --set controller.logs.enabled=true 
```
works fine 
![image](https://user-images.githubusercontent.com/83597/85751451-80fb6c80-b702-11ea-92eb-eb8381274e28.png)

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-ingress
    meta.helm.sh/release-namespace: ingress-haproxy
  creationTimestamp: "2020-06-25T15:36:59Z"
  labels:
    app: haproxy-ingress
    app.kubernetes.io/managed-by: Helm
    chart: haproxy-ingress-0.0.26
    heritage: Helm
    release: haproxy-ingress
  name: haproxy-ingress
  resourceVersion: "23111"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/haproxy-ingress
  uid: 238b3406-c7ee-4802-a661-28d16dd39bfe
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
``

**Comment by ChrisMcKee** [comment]
Had a similar issue with the Haproxy helm chart (official one not the default one in the library which didnt work) 
using the manually added catalogue and the following values worked fine
```
controller:
  containerPort:
    http: 80
    https: 443
    stat: 1024
  daemonset:
    hostPorts:
      http: 80
      https: 443
      stat: 1024
    useHostPort: true
  defaultTLSSecret:
    enabled: true
    secret: null
  ingressClass: null
  kind: DaemonSet
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    path: /healthz
    periodSeconds: 10
    port: 1042
    scheme: HTTP
    successThreshold: 1
    timeoutSeconds: 1
  logging:
    level: info
  name: haproxycontroller
  publishService:
    enabled: true
    pathOverride: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 0
    path: /healthz
    periodSeconds: 10
    port: 1042
    scheme: HTTP
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
      
  ## Controller Service configuration
  service:
    annotations: {}
    enablePorts:
      http: true
      https: false
      stat: true
    ports:
      http: 80
      https: 443
      stat: 1024
    targetPorts:
      http: http
      https: https
      stat: stat
    type: NodePort

podSecurityPolicy:
  annotations: {}
  enabled: false
rbac:
  create: true
serviceAccount:
  create: true
  
defaultBackend:
  containerPort: 8080
  image:
    pullPolicy: IfNotPresent
    repository: k8s.gcr.io/defaultbackend-amd64
    runAsUser: 65534
    tag: 1.5
  name: default-backend
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
  service:
    port: 8080
  serviceAccount:
    create: true
```

Turning off publish service stopped the load balancing state updating; but routing still worked fine.
