### ISSUE TITLE
Unable to provision Azure Disk with Azure node driver and azure cloud provider

### ISSUE THREAD

**Issue by fwiedmann** [rancher/rancher#19216]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Create a pvc with azure disk storage class set.
pvc deplyoment:
```yaml
kind: PersistentVolumeClaim

apiVersion: v1

metadata:

  name: pvc-test

  namespace: test

  labels:

    app: test

spec:

  accessModes:

    - "ReadWriteOnce"

  resources:

    requests:

      storage: "100Gi"
```

**Result:**
kubectl get pvc:
NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS         AGE
pvc-test            Pending                                      azure-disk-storage   31m

kubectl describe pvc test:
 Warning    ProvisioningFailed  59s (x32 over 31m)  persistentvolume-controller  Error creating provisioned PV object for claim pvc-test: persistentvolumes "pvc-ad62bf5a-508f-11e9-ae0a-000d3a2fcc18" is forbidden: error querying AzureDisk volume kubernetes-dynamic-pvc-XXXXXXXXXXXXXX: invalid disk URI: https://XXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-XXXXXXXXXXXXXXXX.vhd. Deleting the volume.

**Other details that may be helpful:**
- The pv gets created in the storage-group for dynamic pv of the cluster. 
- Works perfectly in rancher 2.1.7
- 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.2
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
18.09
```
(paste the output here)
```

**Comment by bmdepesa** [comment]
I am unable to reproduce. 

* Deploy rancher server v2.1.7
* Create Azure cluster w/ cloud provider
* Attach Azure data disk to worker node
* Create PV
* Create workload in project with PVC
* *Upgrade to v2.2*
* Create workload in project
  * Added a new volume from new PVC
  * Added a new volume from existing PVC
* Edited existing workload
  * Added a new volume from new PVC
  * Added a new volume from existing PVC

PVCs get created successfully and workloads are functional.

@fwiedmann are there any steps I missed in trying to reproduce?

**Comment by alena1108** [comment]
@fwiedmann is your cluster an AKS cluster (Hosted Kubernetes provider), or do you just use Azure driver to provision the nodes?

**Comment by fwiedmann** [comment]
@bmdepesa No you didnt miss any steps. We had the same setup.

**Comment by fwiedmann** [comment]
> @fwiedmann is your cluster an AKS cluster (Hosted Kubernetes provider), or do you just use Azure driver to provision the nodes?
@alena1108 We provision our k8s-clusters with the Azure driver.

**Comment by sirrapa** [comment]
Any update on this issue?
We also noticed that the nodes created by the Azure Driver does not use managed disks.

**Comment by cjellick** [comment]
No update. We cannot reproduce. If you can review @bmdepesa's steps and try to find any gaps in reproducing, that would be helpful.

**Comment by bmdepesa** [comment]
@sirrapa @fwiedmann 

Are you using the Azure cloud provider with the Azure node driver?

**Comment by sirrapa** [comment]
@bmdepesa yes we are using Azure cloud provider with the Azure node driver.

**Comment by bmdepesa** [comment]
@sirrapa My original steps to reproduce did not use the cloud provider. I will attempt to reproduce this again.

**Comment by fwiedmann** [comment]
We're using the version 2.2.0 with the new Cloud-Credential feature and using the azure cloudprovider. Set only the following to the cloudprovider: clientid, clientsecret, subscriptionid and tenantid (in v2.17.0 & v2.2.0)
This is our storageclass configuration:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  name: azure-disk-storage
parameters:
  kind: dedicated
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
