### ISSUE TITLE
[Pipeline] Publishing catalog template fails with certificate error

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#19220]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Set up a self-signed cert Git service(gitlab/github/bitbucket server)
2. Add the git server CA root certificate to Rancher server container, following the docs for additional CA.
3. Configure the Git service under  Tools > Pipelines 
4. Configure the CA root certificate under Tools > Pipelines > Custom CA
5. Configure and run a pipeline that includes a Publish stage with a `publishCatalogConfig` step where the catalog is pushed to that same Git service which uses the self-signed cert, e.g.:
```
(....)
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-app:${CICD_GIT_TAG}
  - publishCatalogConfig:
      path: ./charts/template
      catalogTemplate: wordpress
      version: ${CICD_GIT_TAG}
      gitUrl: https://gitlab.example.com/me/mycharts.git
      gitBranch: master
      gitAuthor: admin
      gitEmail: admin@user.com
    envFrom:
    - sourceName: pipeline-auth
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: pipeline-auth
      sourceKey: PASSWORD
      targetKey: PASSWORD
(....)
```

**Result:**
Pipeline build fails with following error:

```
15:57:01 [pipeline_p-5g2j8-1] Running shell script
15:57:02 + publish-catalog
15:57:02 [INFO]check done...
15:57:02 [INFO]prepare config done...
15:57:02 [INFO]publishing to https://gitlab.example.com/me/mycharts.git
15:57:02 Cloning into '/tmp/repo'...
15:57:02 fatal: unable to access 'https://gitlab.example.com/me/mycharts.git/': SSL certificate problem: unable to get local issuer certificate
```

Support for Git with self-signed certificate was previously added here: https://github.com/rancher/rancher/pull/16686
It seems it only works for cloning the application source code repository but not the catalog template repository.

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.2.0
