### ISSUE TITLE
Rancher 2.2 - Gitlab integration - Not working

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19272]
https://forums.rancher.com/t/rancher-2-2-gitlab-integration-not-working/13769/2

**Comment by cjellick** [comment]
also https://forums.rancher.com/t/using-gitlabs-generic-k8s-connection-until-gitlab-is-added-to-v2-x-pipeline/10262/6

**Comment by cjellick** [comment]
@loganhz can you have your team regression test gitlab integration

**Comment by rootwuj** [comment]
@cjellick @loganhz 

Tested with Rancher v2.2.0 and gitlab-ee 11.9.1-ee.0 
Step:
Fresh install of rancher server version - 2.2.0
Configuring pipeline with private gitlab.
Enable repo and edit a simple config.
Run the pipeline.

The pipeline runs successfully.

**Comment by alena1108** [comment]
@loganhz can you follow up with users on the rancher forums (linked in the first comment) to get the steps to reproduce?

**Comment by gitlawr** [comment]
I think the original threads are talking about [kubernetes integration in Gitlab](https://docs.gitlab.com/ee/user/project/clusters/index.html#adding-an-existing-kubernetes-cluster), not Rancher pipeline integrating with Gitlab. We should validate if there is any blocker issue for that.

**Comment by gitlawr** [comment]
Validated in v2.2.1, I can configure Gitlab's kubernetes integration to Rancher managed clusters successfully.
If you are following this blog: https://rancher.com/blog/2018/2018-08-07-cicd-pipeline-k8s-autodevops-rancher-and-gitlab/, The overall workflow still works but a few tweaks are needed.
Takeaway notes are listed as follows:
1. To get K8S API endpoint, the `get_kubeconfig_custom_cluster_rancher2.sh` script by superseb is still valid, and if you enable `Authorized Cluster Endpoint` for RKE clusters now, you can fetch that from kubeconfig file provided in Rancher UI.
2. The `gitlab-managed-apps` seems to be a preserved namespace by Gitlab now, use other namespaces.
3. The service account RBAC roles provided in the blog may not be sufficient. For example, `apps` API group is required as deployment resource is moved in newer K8S version. You should get a token with necessary permissions per your requirements.
4. The default Ruby on Rails template does not work out of the box. Update the command in the Dockerfile of the project to `CMD ["sh", "-c", "bundle exec rails server -b 0.0.0.0 -p ${PORT}"]` so that the application is accessible via the ingress.
These are basically configurations for Gitlab CI/Kubernetes and no blocker issue on Rancher side is found.

**Comment by deniseschannon** [comment]
Based on the content in the forums, it seems that this is resolved.

**Comment by qubusp** [comment]
Please reopen and edit the post from your blog. This is taking more than an hour to be integrated by looking trough gtilab issues. The propper role binding as follows:

```
apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: gitlab 
  namespace: default 
--- 
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: gitlab-admin 
  namespace: default 
subjects: 
  - kind: ServiceAccount 
    name: gitlab 
    namespace: default 
roleRef: 
  kind: ClusterRole 
  name: cluster-admin 
  apiGroup: rbac.authorization.k8s.io 
--- 
apiVersion: v1 
kind: Secret 
metadata: 
  name: gitlab-token 
  namespace: default 
  annotations: 
    kubernetes.io/service-account.name: gitlab 
type: kubernetes.io/service-account-token
```
and then you get the token by doing:

`kubectl describe gitlab-token | grep token: `
