### ISSUE TITLE
Workloads UI shows nodeport link ONLY with services bearing 1 label selector

### ISSUE THREAD

**Issue by spirilis** [rancher/rancher#19283]
Upon creating a deployment, Rancher UI will show an associated nodeport under the pod name (e.g. 30880/tcp) as a link to access the service.  This is fine but, it only works if the nodeport service's selector includes 1 label.  If the nodeport selector includes 2 labels, Rancher UI fails to print the "30880/tcp" under the deployment name in the "Workloads > Workloads" UI view.

E.g., for my "websingleton" service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: websingleton
  namespace: ebrtest
  labels:
    svc: websingleton
    app: nginx
spec:
  type: NodePort
  selector:
    website: websingleton
  ports:
  - name: http
    protocol: TCP
    nodePort: 30880
    port: 80
    targetPort: 80
```

... app:
```yaml
apiVersion: apps/v1beta2
kind: Deployment
...
spec:
  template:
    metadata:
      labels:
        app: nginx
        run: nginx
        website: websingleton
...
```

If I modify the service to select on 2 labels, it works fine but the "30880/tcp" link no longer shows up:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: websingleton
  namespace: ebrtest
  labels:
    svc: websingleton
    app: nginx
spec:
  type: NodePort
  selector:
    run: nginx
    website: websingleton
  ports:
  - name: http
    protocol: TCP
    nodePort: 30880
    port: 80
    targetPort: 80
```

Granted, Rancher-deployed instances don't have this problem since Rancher constructs a service selected on 1 label, but should this work for k8s-native yml defined services?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.1.7` UI: `v2.1.21` |
|Route|`containers.index`|
