### ISSUE TITLE
support for creating Load Balancer with ssl enabled listeners.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1929]
Server Version - V0.35.0-rc5

Once https://github.com/rancher/rancher/issues/1909  is resolved , we should support for creating Load Balancer with ssl enabled listeners using rancher-compose.

**Comment by sangeethah** [comment]
Tested with rancher-compose version - v0.3.0-rc1

SSL enabled listeners can be created from rancher-compose using -  labels io.rancher.loadbalancer.ssl.ports and providing default_cert and certs

```
rancher-compose.yml

lb-1:
  scale: 1
  certs:
  - test3
  load_balancer_config:
    description: lb-1
    name: lb-1 config
  default_cert: test1
web1:
  scale: 2
web2:
  scale: 2

docker-compose.yml

lb-1:
  ports:
  - 9098:80
  - 9097:81
  restart: always
  labels:
    io.rancher.loadbalancer.ssl.ports: '9097'
    io.rancher.loadbalancer.target.web2: def
    io.rancher.loadbalancer.target.web1: abc
  tty: true
  image: rancher/load-balancer-service
  links:
  - web1:web1
  - web2:web2
  stdin_open: true
web1:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
web2:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.3.0-rc1# 
```
