### ISSUE TITLE
EtcdBackup.management.cattle.io "------" not found

### ISSUE THREAD

**Issue by aleksey005** [rancher/rancher#19296]
Rancher 2.2.1 
4 node baremetall

Error after restore snapshot
EtcdBackup.management.cattle.io "c-25d48/c-25d48-rs-x5mhc" not found

![image](https://user-images.githubusercontent.com/6145279/55348284-8cd88e80-54bf-11e9-8819-baaa7d89dd17.png)
Cluster is now in update status all the time.

Edit and Save cluster not work
![image](https://user-images.githubusercontent.com/6145279/55348451-e5a82700-54bf-11e9-9638-79d3be451b4f.png)

**Comment by alena1108** [comment]
@aleksey005 is it 2.2.1 fresh install, or an upgraded setup? If upgraded, what version of Rancher have you upgraded from? 

Can you also provide a Rancher log taken after you hit "Edit and Save" resulting in "Cluster spec conversion error"

**Comment by aleksey005** [comment]
@alena1108  upgrade from version 2.1.7 (all new release i upgrade correctly)

I am surprised and most likely I looked badly in the documentation, but did not find how to see the logs. Please tell me how to do it?

**Comment by aleksey005** [comment]
This file does not exist, because I have already deleted it from the S3 cloud, but the rancher still tries to download it. How to make him change his mind?

#docker logs --tail 100 kind_kirch
...
2019/04/03 07:23:59 [INFO] Provisioning cluster [c-25d48]
2019/04/03 07:23:59 [INFO] Restoring cluster [c-25d48] from backup
2019/04/03 07:23:59 [ERROR] ClusterController c-25d48 [cluster-provisioner-controller] failed with : etcdBackup.management.cattle.io "c-25d48/c-25d48-rs-x5mhc" not found
2019/04/03 07:24:02 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:45094: i/o timeout
2019/04/03 07:24:17 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:24:27 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:46112: i/o timeout
2019/04/03 07:24:43 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:24:53 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:47062: i/o timeout
2019/04/03 07:25:09 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:25:19 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:47996: i/o timeout
2019/04/03 07:25:35 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:25:45 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:48948: i/o timeout
2019/04/03 07:26:00 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:26:10 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:49884: i/o timeout
2019-04-03 07:26:24.906457 I | mvcc: store.index: compact 12996022
2019-04-03 07:26:25.026314 I | mvcc: finished scheduled compaction at 12996022 (took 112.37078ms)
2019/04/03 07:26:26 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:26:36 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:50828: i/o timeout
2019/04/03 07:26:52 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:27:02 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:51778: i/o timeout
2019/04/03 07:27:14 [ERROR] API error response 422 for PUT /v3/clusters/c-25d48?_replace=true. Cause: json: cannot unmarshal string into Go struct field RotateCertificates.services of type []string
2019/04/03 07:27:17 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:27:27 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:52722: i/o timeout
2019/04/03 07:27:43 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:27:53 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:53674: i/o timeout
2019/04/03 07:28:09 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:28:19 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:54620: i/o timeout
2019/04/03 07:28:34 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:28:44 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:55560: i/o timeout
2019/04/03 07:29:00 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:29:10 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:56506: i/o timeout
2019/04/03 07:29:26 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:29:36 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:57448: i/o timeout
2019/04/03 07:29:52 [INFO] Handling backend connection request [c-25d48:m-37b0224f2574]
2019/04/03 07:29:57 [ERROR] API error response 422 for PUT /v3/clusters/c-25d48?_replace=true. Cause: json: cannot unmarshal string into Go struct field RotateCertificates.services of type []string
2019/04/03 07:30:02 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->10.1.100.57:58390: i/o timeout

**Comment by aleksey005** [comment]
Can anyone suggest that this is an intractable problem and I should reinstall Rancher? Now I can’t manage the cluster at all. It is still in an update state.

**Comment by alena1108** [comment]
@aleksey005 

> This file does not exist, because I have already deleted it from the S3 cloud, but the rancher still tries to download it

Rancher operates with an assumption that the snapshot created by rancher, should be managed by rancher only. To restore, can you try:

- remove corresponding snapshot record from rancher (either via UI or api)
- try restoring to the snapshot that does exist on s3

**Comment by aleksey005** [comment]
@alena1108 There are no local snapshots. I deleted them, as well as those that were on S3 (10 GB in total), because I thought that they were not substantial. In fact, I came to the conclusion that the goal of deployment should be quickly repeated and, accordingly, the cluster should be developed for each microservice of its own. Rancher does not fail and continues to work, well, what I did for all management services with a web interface is domain names. I'll try rancher to update in this state.

**Comment by aleksey005** [comment]
After update 2.2.2 - no result

![1](https://user-images.githubusercontent.com/6145279/56283449-7450b100-611a-11e9-9fb8-a8f4ffbf2454.PNG)

After clik Save - Error 
![2](https://user-images.githubusercontent.com/6145279/56283456-77e43800-611a-11e9-8af0-21344b79d2ab.PNG)

![3](https://user-images.githubusercontent.com/6145279/56283460-7adf2880-611a-11e9-8489-e7e572536836.PNG)

**Comment by alena1108** [comment]
@aleksey005 can you share the output of "View as yaml" for your cluster?

**Comment by aleksey005** [comment]
@alena1108 If you need access, I can provide it on request.
```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
bastion_host: 
  ssh_agent_auth: false
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.13.5-rancher1-2"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  options: 
    flannel_backend_type: "host-gw"
  plugin: "flannel"
restore: 
  restore: false
  snapshot_name: "c-25d48:c-25d48-rs-zb8pv"
rotate_certificates: 
  ca_certificates: false
# 
#      services:
#        kube-api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube-controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    backup_config: 
      enabled: true
      interval_hours: 12
      retention: 6
      s3_backup_config: 
        access_key: "-----------"
        bucket_name: "-----------"
        endpoint: "-----------"
        region: "-----------"
        secret_key: "-----------"
    creation: "12h"
    extra_args: 
      election-timeout: "5000"
      heartbeat-interval: "500"
    retention: "72h"
    snapshot: false
  kube-api: 
    always_pull_images: false
    pod_security_policy: false
    service_node_port_range: "30000-32767"
  kubelet: 
    fail_swap_on: false
ssh_agent_auth: false
# 
#   # Rancher Config
# 
docker_root_dir: "/var/lib/docker"
enable_cluster_alerting: true
enable_cluster_monitoring: true
enable_network_policy: false
local_cluster_auth_endpoint: 
  enabled: false
name: "-----------"
```
