### ISSUE TITLE
Running behind Traefik reverse proxy - Failed to connect to proxy error: websocket: bad handshake 

### ISSUE THREAD

**Issue by dschuldt** [rancher/rancher#19323]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
I'm not sure if this is a problem with Rancher, Traefik or any other network component within our company infrastructure (proxy, etc.). Any help is appreciated; thanks a lot in advance.

Importing an existing cluster into Rancher 2.2 running behind Traefik v1.7.9 results in the following error messages:

**Result:**

_Cattle-Node-Agent_ 

time="2019-04-01T16:22:30Z" level=info msg="Connecting to wss://********/v3/connect with token
ww88vvxbv78dlhjzv9vmhf9fw6xvw8gwhxnrjdldd48kdcdftkdlm7"
time="2019-04-01T16:22:30Z" level=info msg="Connecting to proxy" url="wss://********/v3/connect"
time="2019-04-01T16:22:30Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"

_Traefik_

time="2019-04-01T16:15:58Z" level=error msg="vulcand/oxy/forward/websocket: Error dialing \"********\": websocket: bad handshake with
resp: 200 200 OK"

**Other details that may be helpful:**
- Rancher 1.6 works without problems behind Traefik

**Environment information**
- Rancher/Rancher:2.2.1
- Single install deployed with Rancher 1.6
- Traefik 1.7.9 (1.7.10) deployed with Rancher 1.6
- Self Signed SSL Cert

**Cluster information**
- Existing cluster is a kubeadm created cluster in version v1.13.3 running on vmware 
- Docker 18.03.1-ce on CentOS 7.6.1810 (Kernel 3.10.0-957.5.1.el7.x86_64)

**Configuration**

_Rancher_

version: "2"

```yaml
services:
  rancher2:
    image: rancher/rancher:latest
    container_name: rancher2
    restart: unless-stopped
    environment:
      HTTP_PROXY: http://******:8080
      HTTPS_PROXY: http://******:8080
      NO_PROXY: 127.0.0.1,localhost,******
    volumes:
    - rancher2:/var/lib/rancher
    - /var/lib/docker/volumes/rancher2/_data/******/certbundle.crt:/etc/rancher/ssl/cacerts.pem
    labels:
      io.rancher.scheduler.affinity:host_label: rancher2=true
      traefik.enable: true
      traefik.frontend.entryPoints: http,https
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.redirect.permanent: 'true'
      traefik.frontend.rule: Host:******
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.headers.customRequestHeaders: Host:*||X-Forwarded-Proto:https||X-Forwarded-Port:443||X-Forwarded-Host:******
      traefik.protocol: http
      traefik.port: 80
      traefik.backend: rancher2
```

_Traefik_ (traefik.toml)

```toml
logLevel = "ERROR"
[api]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        certFile = "/******/traefik/certbundle.crt"
        keyFile  = "/******/traefik/******.key"
  [entryPoints.ping]
    address = ":8082"

[metrics]
  [metrics.prometheus]

[ping]
  entryPoint = "ping"

[rancher]
  watch = true
  refreshSeconds = 10
  exposedByDefault = false
  enableServiceHealthFilter = true
```
