### ISSUE TITLE
User objects in kubeconfig are not per cluster friendly

### ISSUE THREAD

**Issue by Joeskyyy** [rancher/rancher#19342]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Sign in as user
* Create multiple clusters
* Generate kubeconfig for at least two clusters

**Result:**

* User object will have the same `name` field, but different `token` fields. Ideally this would be something like `user-ab11z.$clusterID` if the tokens are now generated per cluster.

**Other details that may be helpful:**
This is a change it seems in 2.2.0 after talking with some folks at rancher in how the token field is generated.

e.g.

Pre 2.2.0
```
kubeconfig-user-ab11z:YAYATOKEN
```

vs

2.2.0
```
kubeconfig-user-ab11z.c-a123b:YAYATOKEN
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):AWS, m5.xlarge
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by erikwilson** [comment]
Is this actually a bug or an enhancement? If I create two clusters I see different usernames in the token entries:
<img width="414" alt="Screen Shot 2019-07-19 at 4 04 16 PM" src="https://user-images.githubusercontent.com/1999874/61570112-899dea00-aa3f-11e9-962b-b7ef5116ae3a.png">
<img width="414" alt="Screen Shot 2019-07-19 at 4 04 57 PM" src="https://user-images.githubusercontent.com/1999874/61570113-8b67ad80-aa3f-11e9-952f-19da186b445b.png">

I am for changing the users.name entry to match what is in the token if it makes it easier to copy & paste those entries to another kubeconfig, but the kubeconfig should work as is without issue. I think this request should be changed to an enhancement unless you have more info to show an issue. FWIW in the docs we say: `This kubeconfig file and its contents are specific to the cluster you are viewing. You will need a separate kubeconfig file for each cluster that you have access to in Rancher.`

**Comment by Joeskyyy** [comment]
@erikwilson because the `user.name` field is the same across all clusters a given user has access to, it makes it annoying to configure multiple clusters in one kubeconfig file. Yes, users could use multiple kube config files, but then it becomes cumbersome to remember to use `--kube-config` vs `--context`.

Switching how the `user.name` field behaves enables people to use either workflow that works best for them, instead of being forced into one or have to input manual work when copy/pasting from rancher.

Additionally, this satisfies the request in #13853 to be able to generate one big kube config file :D

**Comment by vincent99** [comment]
It is definitely an enhancement, as in it works as designed but you don't like how it's designed.  Seems reasonable to do something about though.

Another option is to just call the user the same as the cluster & context, calling it the random string user ID doesn't actually add any real value (and if you want to know it it's inside the token value).  I think thats what the UI did before it was switched to the server generating the config file...

**Comment by erikwilson** [comment]
Yah, annoying or ideally != bug if the generated kubeconfig works the way it is intended. #13853 is a feature request. I think this is a good idea and we should do it, but not a bug.

**Comment by Joeskyyy** [comment]
Arguably it could be classified as a UX bug (Pedantic on my part, I know :P). As a consumer (Let's say I'm newer to k8s and rely on rancher to help me out), the instructions tell me to place the contents to `~/.kube/config`. I'm happy and hacking along, and now I need to do some stuff against another cluster, the rancher instructions now tell me to place the config in the same file. The rancher process flow has now caused me to no longer have a configuration for my previous cluster.

The docs are a lot more clear about using multiple files and the problem presented, but from the UI, it's not evident: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/kubeconfig/

Triage the problem as you will, just know it's a major thorn for us and our internal customers who use rancher.

**Comment by sumanthkumarc** [comment]
Facing same issue and agree that this is a bad user experience.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head  b8a4b64c 

The newly generated kubeconfig file has the username equivalent to the cluster name, but when the local auth endpoint is enabled, there is no associated user for that context, and attempting to use that context fails with an authentication error.

```
apiVersion: v1
kind: Config
clusters:
- name: "ec2"
  cluster:
    server: "https://<rancher_host>/k8s/clusters/c-7th98"
    certificate-authority-data: cadata
- name: "ec2-brandon-ec2-ecw1"
  cluster:
    server: "https://<cluster_host>:6443"
    certificate-authority-data: cadata
    
users:
- name: "ec2"
  user:
    token: token

contexts:
- name: "ec2"
  context:
    user: "ec2"
    cluster: "ec2"
- name: "ec2-brandon-ec2-ecw1"
  context:
    user: "ec2-brandon-ec2-ecw1"
    cluster: "ec2-brandon-ec2-ecw1"

current-context: "ec2"
```

```
$> kubectl config use-context ec2-brandon-ec2-ecw1
Switched to context "ec2-brandon-ec2-ecw1"
$> kubectl api-resources
error: You must be logged in to the server (Unauthorized)
```

**Comment by vincent99** [comment]
Changed to use the same user (named the base cluster name) for all the contexts.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ca39b717

* Deploy Rancher
* Create Cluster w/ local auth endpoint enabled
* Generate kubeconfig
* Kubeconfig contains one user, with name equivalent to base cluster name
* Each context uses the correct user
* kubectl is functional for both contexts

**Comment by andrii-litvinov** [comment]
Until this new feature is released or for those who use older version of Rancher, the solution is to manually prefix usernames from different clusters with cluster name or any arbitrary string. E.g.:

```yaml
contexts:
- context:
    cluster: sandbox
    user: user-6bqmf
  name: sandbox
users:
- name: user-6bqmf
  user:
    token: kubeconfig-user-6bqmf.c-ltt4h:...
```
becomes
```yaml
contexts:
- context:
    cluster: sandbox
    user: sandbox-user-6bqmf
  name: sandbox
users:
- name: sandbox-user-6bqmf
  user:
    token: kubeconfig-user-6bqmf.c-ltt4h:...
```
For `sandbox` cluster.
