### ISSUE TITLE
Backport: Panic when attempting to view metrics for workload.

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19371]
Backport https://github.com/rancher/rancher/issues/19358

**Comment by loganhz** [comment]
Steps to reproduce

1. Import a standalone  Pod by `Import YAML`.
2. Import a deployment.
3. View metrics of the deployment in Rancher UI

Results: 

You will see a red error popup

```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: busybox
      image: busybox:1.25
      volumeMounts:
        - name: quobytevolume
          mountPath: /persistent
      command:
        - /bin/sh
        - -ec
        - |
          if [ -f /persistent/log ]; then
            echo -n "Found old state starting at "; head -n1 /persistent/log
          else
            echo -n "Starting with a fresh state"
          fi
          while sleep 5; do date | tee -a /persistent/log; done
  volumes:
  - name: quobytevolume
    quobyte:
      registry: ignored:7861
      volume: testVolume
      readOnly: false
      user: root
      group: root
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

```
