### ISSUE TITLE
Rancher v2 Hardening Guide Breaks UI-Kube Terminal

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#19439]
RKE Setup
```
kubernetes_version: v1.13.5-rancher1-2
cluster_name: rancher-k8

bastion_host:
    address: ${bastion_host}
    user: ${bastion_user}
    port: 22
    ssh_key_path: ${bastion_filepath}

nodes:
  - address: ${node_one_ip}
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./sshkey
  - address: ${node_two_ip}
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./sshkey
  - address: ${node_three_ip}
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./sshkey

ignore_docker_version: true

cloud_provider:
    name: aws

network:
    plugin: canal

ingress:
    provider: nginx

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 168h # time increment before snapshot purge
  kubelet:
    extra_args:
      streaming-connection-idle-timeout: "1800s"
      protect-kernel-defaults: "true"
      make-iptables-util-chains: "true"
      event-qps: "0"
  kube-api:
    pod_security_policy: true
    extra_args:
      anonymous-auth: "false"
      profiling: "false"
      repair-malformed-updates: "false"
      service-account-lookup: "true"
      enable-admission-plugins: "ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,DenyEscalatingExec,NodeRestriction,EventRateLimit,PodSecurityPolicy"
      admission-control-config-file: "/etc/kubernetes/admission.yaml"
      encryption-provider-config: /etc/kubernetes/encryption.yaml
      audit-log-path: "/var/log/kube-audit/audit-log.json"
      audit-log-maxage: "5"
      audit-log-maxbackup: "5"
      audit-log-maxsize: "100"
      audit-log-format: "json"
      audit-policy-file: /etc/kubernetes/audit.yaml
    extra_binds:
      - "/var/log/kube-audit:/var/log/kube-audit"
  scheduler:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
  kube-controller:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
      terminated-pod-gc-threshold: "1000"

addons: |
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-psp-role
    namespace: ingress-nginx
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - default-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-psp-rolebinding
    namespace: ingress-nginx
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: default-psp-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: cattle-system
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-psp-role
    namespace: cattle-system
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - default-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-psp-rolebinding
    namespace: cattle-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: default-psp-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: extensions/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: restricted
  spec:
    requiredDropCapabilities:
    - NET_RAW
    privileged: false
    allowPrivilegeEscalation: false
    defaultAllowPrivilegeEscalation: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: MustRunAsNonRoot
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - emptyDir
    - secret
    - persistentVolumeClaim
    - downwardAPI
    - configMap
    - projected
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
```

This is the RKE setup required by the CIS benchmark based hardening guide. 
https://releases.rancher.com/documents/security/latest/Rancher_Hardening_Guide.pdf

Launching a cluster using this; then the usual helm steps, results in a working rancher installation. (obviously you need to have the encryption file and audit files as per the doc)

Clicking the launch ctl button results in a websockets error (403 Forbidden) from the system.
![image](https://user-images.githubusercontent.com/83597/55722535-7c17a380-59fe-11e9-9d17-da5328c905fc.png)

```
0:190838 WebSocket connection to 'wss://rancher-de.xxxx.xx/v3/clusters/local?shell=true' failed: Error during WebSocket handshake: Unexpected response code: 403
```

I 'expect' this is intended (in that the ability to run within the web-terminal bypassing other restrictions that may be in place may be deemed a negative resource to give a user in a hardened environment) but currently the UI fails to allow for this.
If this is intentional, it may be best to have a flag on installing rancher via helm to remove this button from the UI, and add to the docs for hardening.

gz#7489
