### ISSUE TITLE
Custom CAs no-longer work with git-based custom catalogs in Rancher v2.2

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#19473]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Configure a Gitlab server with a certificate signed by a self-generated CA
2. Install Rancher via Helm and configure the custom CA per https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#additional-trusted-cas
3. Attempt to add a custom git-based catalog from the gitlab server, and note the `Unexpected HTTP status code 400`

**Result:**

`Unexpected HTTP status code 400` error attempting to add git-based custom catalog from gitlab server with custom CA certificate.

Performing `git ls-remote <gitlab_url>` (https://github.com/rancher/rancher/blob/v2.2.1/pkg/catalog/git/git.go#L41) directly in a rancher v2.2.1 container reveals failure with `fatal: unable to access '<git_url>': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`

The git-based custom catalog with custom CA can be successfully added and the `git ls-remote` test succeeds in a Rancher v2.1.8 environment.

The difference in behaviour is the result of a change in the rancher deployment object in the helm chart in v2.2 vs 2.1, in which the custom CA file `ca-additional.pem` is now mounted at `/etc/rancher/ssl/ca-additional.pem` vs `/etc/ssl/certs/ca-additional.pem` (https://github.com/rancher/server-chart/commit/7920ce483a9c46d681dd131196c8322713df62da#diff-e3ed5b4174b5e628950137770a3e94d0). This change was made to rationalise certificate location into a single, non-OS dependent directory. However, pending updates to the git-based catalog design (https://github.com/rancher/rancher/issues/15330) this breaks git-based custom catalogs from git servers presenting a cert signed with a custom CA.

The workaround is to update the rancher deployment post-installation, to mount `ca-additional.pem` in both locations as follows:
```
...
volumeMounts:
- mountPath: /etc/ssl/certs/ca-additional.pem
  name: tls-ca-additional-volume
  readOnly: true
  subPath: ca-additional.pem
- mountPath: /etc/rancher/ssl/ca-additional.pem
  name: tls-ca-additional-volume
  readOnly: true
  subPath: ca-additional.pem
...
```

Pending changes to the catalog design, could this workaround be added to the helm chart, to ensure custom CA certificates work with git-based custom catalogs? The current behaviour in v2.2 is a regression from v2.1 where this was working, so I have labelled this as a bug.

**Environment information**

- Rancher v2.2.1
- HA Installation
