### ISSUE TITLE
Unable to launch catalog app by providing answers in yaml

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#19511]
v2.2.1

Catalog used: 
URL: https://github.com/leodotcloud/rancher-charts.git
Branch: authelia
App used: Authelia

Answers:
```
authelia:
  enableHealtcheck: false
  config:
    domain: "example.com"
    logsLevel: "debug"
    session:
      secret: "changeme"
    authentication_backend: "ldap"
    ldap:
      url: "ldap://ldap.example.com"
      user: "cn=admin,dc=example,dc=com"
      password: "admin"
      base_dn: "dc=example,dc=com"
      additional_users_dn: ""
      users_filter: "cn={0}"
      additional_groups_dn: ""
      groups_filter: "(&(member={dn})(objectclass=group))"
      group_name_attribute: "cn"
      mail_attribute: "mail"
  ingress:
    enabled: true
    hosts:
      - "login.example.com"
```

Providing the above answers in "Edit as Yaml" editor and clicking Launch doesn't work.

**Comment by davidnuzik** [comment]
Issue appears to be that in the UI we have mandatory required fields set and are still checking for them when in "Edit as YAML" mode.
![image](https://user-images.githubusercontent.com/45179589/55906275-b90fa180-5b88-11e9-8c15-2ea811e46efa.png)

**Comment by davidnuzik** [comment]
Related: #19060

**Comment by loganhz** [comment]
Created a PR to let users create apps even without required answers when they are using `Edit as YAML`.

**Comment by loganhz** [comment]
@alena1108 

Given an app with some required answers

With this PR, 

When using `Edit as YAML`, it will always let users to create it no matter if they have input the required answers.

Without this PR, 

When using `Edit as YAML`, users will always not be able to create the app no matter if they have input the required answers.

For `Edit as Form`, they are the same. UI will show the error when required answers missing.

**Comment by leodotcloud** [comment]
@loganhz I was providing answers for all the required questions. Still, the app was not getting launched. I am confused by your comments. We should still not let the app get created if the required answers are missing.

**Comment by davidnuzik** [comment]
Version: v2.2.2-rc10

Scenario A:
Confirmed that when I try to submit as form the UI will still prevent launching of the Authelia app since required fields are not filled out.

Scenario B:
Confirmed that I can now launch the app with the provided YAML (includes required LDAP Server URL, Base DN, Admin user, Admin user password)
Before UI was blocking due to it claiming that "LDAP Server URL" and "Base DN" were not provided even though they were.
```
authelia:
  enableHealtcheck: false
  config:
    domain: "example.com"
    logsLevel: "debug"
    session:
      secret: "changeme"
    authentication_backend: "ldap"
    ldap:
      url: "ldap://ldap.example.com"
      user: "cn=admin,dc=example,dc=com"
      password: "admin"
      base_dn: "dc=example,dc=com"
      additional_users_dn: ""
      users_filter: "cn={0}"
      additional_groups_dn: ""
      groups_filter: "(&(member={dn})(objectclass=group))"
      group_name_attribute: "cn"
      mail_attribute: "mail"
  ingress:
    enabled: true
    hosts:
      - "login.example.com"
```

Scenario C:
When I try to launch with YAML but do NOT provide required answers such as "LDAP Server URL" and "Base DN"  (null string provided) I can still launch the app - I should not be allowed to.
Expected behavior @loganhz ? (leodotcloud mentioned it)
```
authelia:
  enableHealtcheck: false
  config:
    domain: "example.com"
    logsLevel: "debug"
    session:
      secret: "changeme"
    authentication_backend: "ldap"
    ldap:
      url: ""
      user: "cn=admin,dc=example,dc=com"
      password: "admin"
      base_dn: ""
      additional_users_dn: ""
      users_filter: "cn={0}"
      additional_groups_dn: ""
      groups_filter: "(&(member={dn})(objectclass=group))"
      group_name_attribute: "cn"
      mail_attribute: "mail"
  ingress:
    enabled: true
    hosts:
      - "login.example.com"
```

Scenario D:
When I try to launch with YAML but do NOT provide the ldap url and base_dn at all. I can still launch the app - I should not be allowed to. Expected behavior here as well @loganhz ? (similar to Scenario C and what leodotcloud mentioned)
```
authelia:
  enableHealtcheck: false
  config:
    domain: "example.com"
    logsLevel: "debug"
    session:
      secret: "changeme"
    authentication_backend: "ldap"
    ldap:
      user: "cn=admin,dc=example,dc=com"
      password: "admin"
      additional_users_dn: ""
      users_filter: "cn={0}"
      additional_groups_dn: ""
      groups_filter: "(&(member={dn})(objectclass=group))"
      group_name_attribute: "cn"
      mail_attribute: "mail"
  ingress:
    enabled: true
    hosts:
      - "login.example.com"
```
^^^ ldap url / base_dn missing

**Comment by davidnuzik** [comment]
Note: Tested in v2.2.2-rc10 here: https://github.com/rancher/rancher/issues/19542#issuecomment-482233671
I also noticed that I can launch the app when missing required answers in YAML.

(This will also be tested again later in master for v2.3)

**Comment by westlywright** [comment]
This was resolved by https://github.com/rancher/ui/pull/2897

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/8/19)

This is now working correctly. As mentioned previously we no longer do required form checks (see my prior comment with screenshot) and we can now launch the catalog app without any issues by just providing the YAML. I tested again with the following and confirmed that the UI, HTTP, API looks good. The app deployed (just doesn't work since this is faux data).

Catalog used: 
URL: https://github.com/leodotcloud/rancher-charts.git
Branch: authelia
App used: Authelia

Answers:
```
authelia:
  enableHealtcheck: false
  config:
    domain: "example.com"
    logsLevel: "debug"
    session:
      secret: "changeme"
    authentication_backend: "ldap"
    ldap:
      url: "ldap://ldap.example.com"
      user: "cn=admin,dc=example,dc=com"
      password: "admin"
      base_dn: "dc=example,dc=com"
      additional_users_dn: ""
      users_filter: "cn={0}"
      additional_groups_dn: ""
      groups_filter: "(&(member={dn})(objectclass=group))"
      group_name_attribute: "cn"
      mail_attribute: "mail"
  ingress:
    enabled: true
    hosts:
      - "login.example.com"
```

Providing the above answers in "Edit as Yaml" editor and clicking Launch now works correctly. valuesYAML in HTTP/API looks correct and UI no longer blocks us from submitting (Launching).

Further, I made sure I can upgrade (edit) the app and change YAML values and that they take and update correctly.
