### ISSUE TITLE
[rancher-compose] public ports are not bound to 0.0.0.0

### ISSUE THREAD

**Issue by bymodude** [rancher/rancher#1956]
deploying a service with rancher-compose, public ports are shown in UI but upon "docker ps" its clear they are not bound to 0.0.0.0. Default behavior of docker with the same docker-compose.yml is to bind the ports to 0.0.0.0, so this is both confusing and also sadly makes rancher unusable for my purposes. 

I would have thought this is a most basic scenario?

docker-compose.yml
```
salt-master-data:
  labels:
    io.rancher.scheduler.affinity:host_label: name=rancher1
  tty: true
  image: busybox
  volumes:
  - /etc/salt/pki
  - /srv/salt
  - /var/logs/salt
  - /var/salt/cache
  stdin_open: true
salt-master:
  restart: always
  ports:
  - 4505:4505/tcp
  - 4506:4506/tcp
  - 4506:4506/udp
  - 5050:5000/tcp
  - 8000:8000/tcp
  labels:
    io.rancher.sidekicks: salt-master-data
    io.rancher.scheduler.affinity:host_label: name=rancher1
  image: salt-master
  volumes_from:
  - salt-master-data
```

rancher-compose.yml
```
salt-master-data:
  scale: 1
salt-master:
  scale: 1
```

docker ps (first line is the container defined above but compared to the other container its ports are not mapped to 0.0.0.0)
```
root@rancher1:~# docker ps
CONTAINER ID        IMAGE                                 COMMAND                   CREATED             STATUS              PORTS                                          NAMES
53c49a44c6f0        salt-master:latest                    "/bin/sh -c \"/usr/loc"   2 hours ago         Up 3 seconds        4505-4506/tcp, 5000/tcp, 8000/tcp, 4506/udp    465f0c92-5778-432c-9598-3e73c022a81b
2d47992fb0d5        busybox:latest                        "/bin/sh"                 2 hours ago         Up 2 hours                                                         0a7298cc-a0cb-4ba4-b85b-a9eece265271
9ef714a0db80        gliderlabs/logspout:master            "/bin/logspout syslog"    24 hours ago        Up 24 hours         8000/tcp                                       144bf3db-2daf-4b43-82de-d0b248726897
d27fecbe1618        rancher/agent-instance:v0.4.0         "/etc/init.d/agent-in"    24 hours ago        Up 24 hours         0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   9df86c00-5712-4e5a-bc5c-5c4bb3996d02
db3923ea65a7        rancher/agent:v0.8.1                  "/run.sh run"             24 hours ago        Up 24 hours                                                        rancher-agent
e5ec04b923d9        rancher/server                        "/usr/bin/s6-svscan /"    26 hours ago        Up 26 hours         3306/tcp, 0.0.0.0:8080->8080/tcp               rancher-server
7d0b1eda526e        dockerregistry_nginx                  "nginx -g 'daemon off"    3 days ago          Up 26 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp       nginx
d20be6cca7d6        registry:2                            "/bin/registry /etc/d"    3 days ago          Up 26 hours         0.0.0.0:5000->5000/tcp                         registry
```
