### ISSUE TITLE
[rancher-compose] can not specify networkMode or how to use sidekick without using managed network mode

### ISSUE THREAD

**Issue by bymodude** [rancher/rancher#1957]
I want to use a simple 2 container setup, one being primary and one container simply being a data volume container. When I setup sidekick relationship with rancher-compose it seems to automatically enable rancher managed network which leads to networking problems with salt (saltstack master), i dont plan to use rancher dns or lb for this stack, so I would like to use default docker bridge networking only. 

However even if I remove the sidekick label from the following config it still sets up managed networking (container get ip in 10.42 range), is it because volume_from? but I cannot remove that.

How can the following config be used without using rancher managed networking?

docker-compose.yml
```
salt-master-data:
  labels:
    io.rancher.scheduler.affinity:host_label: name=rancher1
  tty: true
  image: busybox
  volumes:
  - /etc/salt/pki
  - /srv/salt
  - /var/logs/salt
  - /var/salt/cache
  stdin_open: true
salt-master:
  restart: always
  ports:
  - 4505:4505/tcp
  - 4506:4506/tcp
  - 4506:4506/udp
  - 5050:5000/tcp
  - 8000:8000/tcp
  labels:
    io.rancher.sidekicks: salt-master-data
    io.rancher.scheduler.affinity:host_label: name=rancher1
  image: salt-master
  volumes_from:
  - salt-master-data
```

rancher-compose.yml
```
salt-master-data:
  scale: 1
salt-master:
  scale: 1
```
