### ISSUE TITLE
Creation of K8s "dummy" Node for BIG-IP Gateway keeps getting removed

### ISSUE THREAD

**Issue by zbialik** [rancher/rancher#19617]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**

1. Bootstrap a k8s cluster that is managed by Rancher, with the following configurations:

- custom cluster (3 nodes, each have all roles)
- amazon provider
- flannel (or canal) as network provider (although I think problem likely persists with Calico, too)

2. Create a yaml config for "dummy" node that will act as a gateway to BIG-IP device. Instructions found [here](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html).
3. Create the node using the yaml template.

**Result:**
Node goes from Status: Unknown, to Status: NotReady, and then is automatically removed.

Is there a way to ensure that the node is not automatically removed after going to the NotReady state?

**Other details that may be helpful:**
I am following the install docs for integrating f5-bigip-ctlr with kubernetes cluster ([f5-bigip-ctlr install docs](https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html)).

My yaml config for the node template is :

```
apiVersion: v1
kind: Node
metadata:
  name: bigip
  annotations:
    # Provide the MAC address of the BIG-IP VXLAN tunnel
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"<BIG-IP_mac-address>"}'
    flannel.alpha.coreos.com/backend-type: "vxlan"
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    # Provide the IP address you assigned as the BIG-IP VTEP
    flannel.alpha.coreos.com/public-ip: <IP address assigned as the BIG-IP VTEP>
spec:
  # Define the flannel subnet you want to assign to the BIG-IP device.
  # Be sure this subnet does not collide with any other Nodes' subnets.
  podCIDR: 10.42.20.0/24
```

If I try and create the "dummy" node in the local rancher cluster, the node succesfully remains in the cluster with Status: NotReady. This is what I want to happen in a k8s cluster that is managed by Rancher (i.e. not the local cluster). I am not sure why this behavior is seen for the local cluster, not seen in a k8s bootstrapped cluster. 

Perhaps there is some taint/toleration that I can apply to ensure the node doesn't get deleted?

**Environment information**
- Rancher version: `v2.1.7`
- Installation option (single install/HA): `HA`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2, t2.large
- Kubernetes version (use `kubectl version`): `v1.11.8`
- Docker version (use `docker version`): `1.12.6`
