### ISSUE TITLE
Running rancher with compose: "usermod: UID '0' already exists"

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher#1972]
I am using docker-compose to launch rancher and a data only container for persisting data and to make upgrades easier. I have managed to run rancher server successfully many times but today is randomly not working. Even if I run without the data only container, I get the same error. I am missing something?

# docker-compose.yml
```yml
rancher_data:
  container_name: rancher_data
  image: ubuntu
  volumes:
    - /var/lib/mysql

rancher:
  container_name: rancher_server
  image: rancher/server
  ports:
    - "8080:8080"
  volumes_from:
    - rancher_data
  restart: always
```
# error
      docker-compose up

```bash
Creating rancher_data...
Creating rancher_server...
Attaching to rancher_data, rancher_server
rancher_1      | Running in VBox change mysql UID
rancher_1      | usermod: UID '0' already exists
rancher_server exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping rancher_server... done
```

**Comment by cloudnautique** [comment]
Sorry, this is a bug. We need to add an additional check in there to not switch over to UID 0. 

When we added bind mounting for the MySQL directory we needed to handle mounts from VBox where the userid is set in the mount. It looks like if you are not using a bind mount from the Mac it is still trying to set it to the Userid, and failing. 

As a workaround, instead of using Ubuntu use the rancher/server container. It already exports the /var/lib/mysql directory with the correct userid. So something like:

```
rancher_data:
  container_name: rancher_data
  image: rancher/server:v0.35.0
...
```
