### ISSUE TITLE
Openstack Cinder volume storageClass fails

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#19777]
Possibly related:
https://github.com/rancher/rancher/issues/19237
https://github.com/rancher/rancher/issues/14461
https://bugs.launchpad.net/cinder/+bug/1798798 
Per the above, we're running 13.0.0, I'm going to see if I can get it upgraded.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create an openstack cluster, edit the yaml to include the following:
```
cloud_provider: 
  name: "openstack"
  openstackCloudProvider: 
    block_storage: 
      bs-version: "v3"
      ignore-volume-az: true
      trust-device-path: false
    global: 
      auth-url: "<SNIP>:5000/v3"
      domain-name: "<SNIP>"
      password: "<SNIP>"
      tenant-id: "<SNIP>"
      username: "<SNIP>"
    load_balancer: 
      create-monitor: false
      manage-security-groups: false
      monitor-delay: 0
      monitor-max-retries: 0
      monitor-timeout: 0
      subnet-id: "<SNIP>"
      use-octavia: true
    metadata: 
      request-timeout: 0
```
Note that I've tried this with omitting `bs-version`, and setting it to v1, v2, v3. All produce the same results. 

Create a storageClass of whatever your ceph-rbd volume type is, set it as the default. No customizations through the UI. I named it `v3cinder` for this test.

Now do something like install the wordpress helm chart for a demo.

**Result:**

> Failed to provision volume with StorageClass "v3cinder": failed to create a 8 GB volume: 
> Invalid request due to incorrect syntax or missing required parameters.

--

**Other details that may be helpful:**

Cinder is setup correctly. Openstack is working fine.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Self hosted openstack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vcpu 16GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 18.6.1
- RancherOS version: 1.5.1
