### ISSUE TITLE
openstack cloud provider monitor-delay and monitor-timeout are broken

### ISSUE THREAD

**Issue by tibers** [rancher/rancher#20074]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
Edit a cloud yaml for an openstack provisioned cluster and do this:
```
cloud_provider: 
  name: "openstack"
  openstackCloudProvider: 
    block_storage: 
      ignore-volume-az: false
      trust-device-path: false
    global: 
      auth-url: "NOPE"
      domain-name: "NOPE"
      password: "NOPE"
      tenant-id: "NOPE"
      username: "NOPE"
    load_balancer: 
      create-monitor: false
      manage-security-groups: false
      monitor-delay: "10s"
      monitor-max-retries: 2
      monitor-timeout: "30s"
      subnet-id: "NOPE"
      use-octavia: true
    metadata: 
      request-timeout: 0
```

**Result:**
The UI barfs the following error:
```
Validation failed in API: rancherKubernetesEngineConfig cloudProvider=InvalidFormat 422: openstackCloudProvider=InvalidFormat 422: loadBalancer=InvalidFormat 422: monitor-delay=InvalidFormat 422: strconv.ParseInt: parsing "10s": invalid **syntax**
```

**Other details that may be helpful:**
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancer

https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/provider-configuration.md#load-balancer-optional-parameters

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
