### ISSUE TITLE
Missing rbac resources while creating an Azure cluster with cloud provider set

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#20124]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster with Azure cloud provider set. (1 etcd, control plane linux node, 1 linux worker node, 2 windows worker nodes)
2. On execution of these commands on kubectl for the cluster - the rolebindings related to -system:azure-cloud-provider are not available
```
> k get sa persistent-volume-binder -n kube-system
> k get clusterrole system:azure-cloud-provider -n kube-system
> k get clusterrolebinding system:azure-cloud-provider -n kube-system
```

On creation of a `Volume`, it fails and the `Volume` is still stuck in `Pending` state.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher:master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`):

```
1.14.1
```

**Comment by alena1108** [comment]
@sowmyav27 : @sangeethah said that there are steps to workaround. Can you please add them as a comment to the issue?

**Comment by sowmyav27** [comment]
Workaround for the issue -- 

1. Import YAML from Workloads page of System project:
2. choose Cluster as Import Mode
3. import as below:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
```
