### ISSUE TITLE
[Windows] Cannot fetch metadata when using GCE cloud provider

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#20156]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Prepare 1 Linux Ubuntu 18.04 and 1 Windows 2019
1. Set up a cluster with GCE cloud provider:
    ```yaml
    cloud_provider:
      name: gce
      customCloudProvider: |-
        [Global]
        project-id=<your projcet ID, optional>
        network-name=<your network, optional if using default network>
        subnetwork-name=<your subnetwork of the above network, optional if using default network>
        node-instance-prefix=<your instance group name/your instance name specific prefix>
        node-tags=<your network tags, optional if not patching any tags>
    services:
      kube-controller:
        extra_args:
          configure-cloud-routes: true
    ```
1. Add a Linux control plane + etcd + worker node
1. Add a Windows node
1. Log in Windows node, exec `powershell`:
  ```powershell
  > cd c:\var\log
  > get-content kubelet.log -tail 2 -wait
  ```

**Result:**
So many repeated errors as below:
![image](https://user-images.githubusercontent.com/3394724/57529087-9a0e5600-7366-11e9-908b-8083ad2946a7.png)

**Other details that may be helpful:**
After patching `169.254.169.254/32` route back, the error logs gone.
![image](https://user-images.githubusercontent.com/3394724/57529271-186af800-7367-11e9-989b-598fed1594c1.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 
- Kubernetes version (use `kubectl version`): 1.14.1

**Comment by sowmyav27** [comment]
Verified on `rancher:2.3.0-alpha3`
1. Set up a GCE cloud provider cluster with: 
```
cloud_provider:
  name: gce
services:
  kube-controller:
    extra_args:
      configure-cloud-routes: true
```
2. Register a linux node - all roles -Ubuntu 18.04. 
3. The cluster comes up active but the node is seen in `Active` state with error `Node created without a route`
4. Register a Windows 2019 node - worker.
5. The node gets registered successfully.

**Comment by thxCode** [comment]
Please follow this pattern:
``` yaml
cloud_provider:
  name: gce
  customCloudProvider: |-
    [Global]
    project-id=<your projcet ID, optional>
    network-name=<your network, optional if using default network>
    subnetwork-name=<your subnetwork of the above network, optional if using default network>
    node-instance-prefix=<your instance group name/your instance name specific prefix>
    node-tags=<your network tags, optional if not patching any tags>
services:
  kube-controller:
    extra_args:
      configure-cloud-routes: true
```

Only `node-instance-prefix` is required. However, if you configure a specifical VPC, you have better to specify it in `network-name`. The `node-tags` allows you to separate different clusters in one VPC.
