### ISSUE TITLE
[Windows] Could not use GCEPersistentDisk as Volume on Windows worker

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#20180]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Prepare 1 Linux Ubuntu 18.04 and 1 Windows 2019
1. Set up a cluster with GCE cloud provider:
    ```yaml
    cloud_provider:
      name: gce
      customCloudProvider: |-
        [Global]
        project-id=<your projcet ID, optional>
        network-name=<your network, optional if using default network>
        subnetwork-name=<your subnetwork of the above network, optional if using default network>
        node-instance-prefix=<your instance group name/your instance name specific prefix>
        node-tags=<your network tags, optional if not patching any tags>
    services:
      kube-controller:
        extra_args:
          configure-cloud-routes: true
    ```
1. Add a Linux control plane + etcd + worker node
1. Add a Windows node
1. Deploy a Windows workload with an existing GCEPersistentDisk, following https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk

**Result:**
-. Workload event:
![image](https://user-images.githubusercontent.com/3394724/57578421-b4f3de00-74be-11e9-8bec-0f8a8a921744.png)

- kubelet logs from Windows:
![image](https://user-images.githubusercontent.com/3394724/57578422-c1783680-74be-11e9-8b8f-eaa0517a1be1.png)

**Other details that may be helpful:**
A related issue from Kubernetes: https://github.com/kubernetes/kubernetes/issues/74674

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): 1.14.1
