### ISSUE TITLE
[Windows] iSCSI workflow failed to start

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#20192]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a Rancher v2.3.0-alpha1 cluster and add a child cluster with a windows node(The firewall is off) in it.
2. Deploy iSCSI workflow using yaml below
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: windows-iscsi-test
  name: windows-iscsi-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: windows-iscsi-test
      name: windows-iscsi-test
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - windows-iscsi-test
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: windowsiscsitest
        image: mcr.microsoft.com/powershell:nanoserver-1809
        command:
        - pwsh.exe
        args:
        - -NoLogo
        - -NonInteractive
        - -Command
        - '&{$hs=hostname; echo $hs >> c:/mnt/hosts; do { echo "==========="; cat c:/mnt/hosts; echo "==========="; echo ""; start-sleep -s 10; } while($True)}'
        volumeMounts:
        - name: iscsi-volume
          mountPath: c:/mnt
      volumes:
      - name: iscsi-volume
        flexVolume:
          driver: "microsoft.com/iscsi.cmd"
          fsType: "NTFS"
          secretRef:
            name: "iscsi-secret"
          readOnly: false
          options:
            chapAuthDiscovery:  "false"
            chapAuthSession:  "true"
            targetPortal:  "172.31.12.208"
            iqn:  "iqn.2018-08.com.example.storagesrv01.target01"
            lun:  "0"
            authType:  "ONEWAYCHAP"
```
3. Waiting for the workflow to start

**Result:**
Pod failed to start:
```
Events:
  Type     Reason       Age    From                      Message
  ----     ------       ----   ----                      -------
  Normal   Scheduled    3m27s  default-scheduler         Successfully assigned default/iscsi to ec2amaz-3a24kcc
  Warning  FailedMount  84s    kubelet, ec2amaz-3a24kcc  Unable to mount volumes for pod "iscsi_default(f28b1a9e-754d-11e9-84c1-06876d1107e6)": timeout expired waiting for volumes to attach or mount for pod "default"/"iscsi". list of unmounted volumes=[iscsi-volume]. list of unattached volumes=[iscsi-volume default-token-62nnl]
```
At this point, I log in to the windows node and restart the rancher-agent service. Then recreate the iscsi workflow and the pod will start successfully.

I suspect the reason for the `msiscsi` service of the windows node, so I did the following test.
1. Start the `msiscsi` service before adding the windows node to the cluster.
2. Add this windows node to the cluster
3. Deploy the iSCSI workflow mentioned above

If I do this, the iSCSI workflow can start successfully.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.3.0-alpha1
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS
- Kubernetes version (use `kubectl version`):
1.14.1 & host-gw
