### ISSUE TITLE
LB stuck in Waiting in Rancher 1.6.26

### ISSUE THREAD

**Issue by rtau-t24** [rancher/rancher#20222]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a stack consist of two load balancers, let's call them lb-a and lb-b
2. Create a link from lb-a to lb-b and another link from lb-b to lb-a
3. Stop the whole stack
4. Start the stack

**Result:**
The stack would not be able to start, both LB stuck in state "Waiting: xxxxx [lloadBalancerService:xxxx]"

**Other details that may be helpful:**
We start to experience this issue since we upgrade from v1.6.22
Service log from both LB:

***lb-a***
```
12:16:17 PM | INFO | service.activate (Running) | Activating service |  
-- | -- | -- | -- | --
12:16:03 PM | INFO | service.activate.exception | Waiting: state to equal active [loadBalancerService:1s4024] |  
12:15:17 PM | INFO | service.activate (46 sec) | Activating service |  
-- | -- | -- | -- | --
12:15:02 PM | INFO | service.activate.exception | Waiting: state to equal active [loadBalancerService:1s4024] |  
```

***lb-b***
```
12:16:17 PM | INFO | service.activate (Running) | Activating service |  
-- | -- | -- | -- | --
12:16:03 PM | INFO | service.activate.exception | Waiting: loadBalancerService activating [loadBalancerService:1s4018] |  
12:15:17 PM | INFO | service.activate (46 sec) | Activating service |  
12:15:02 PM | INFO | service.activate.exception | Waiting: loadBalancerService activating [loadBalancerService:1s4018] |  
```

***compose files of the stack:***
****docker-compose.yml****
``` yaml
version: '2'
services:
  lb-a:
    image: rancher/lb-service-haproxy:v0.9.6
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  lb-b:
    image: rancher/lb-service-haproxy:v0.9.6
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
```

****rancher-compose.yml****
``` yaml
version: '2'
services:
  lb-a:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: lb-b
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  lb-b:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: lb-a
        source_port: 80
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v1.6.26
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): N/A, we are using Cattle

- Docker version (use `docker version`):

```
17.06.2-ce
```
