### ISSUE TITLE
Deploying a helm chart with list of 30 keys times out

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20310]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
0. Make sure you have a cluster added to your environment.
1. Add the custom catalog: https://github.com/sishihara/cases.git (branch master, type helm)
2. Create override_values.yml with content:
```
list_of_map:
  - foo: foo1
    bar: bar1
  - foo: foo2
    bar: bar2
  - foo: foo3
    bar: bar3
  - foo: foo4
    bar: bar4
  - foo: foo5
    bar: bar5
  - foo: foo6
    bar: bar6
  - foo: foo7
    bar: bar7
  - foo: foo8
    bar: bar8
  - foo: foo9
    bar: bar9
  - foo: foo10
    bar: bar10
  - foo: foo11
    bar: bar11
  - foo: foo12
    bar: bar12
  - foo: foo13
    bar: bar13
  - foo: foo14
    bar: bar14
  - foo: foo15
    bar: bar15
  - foo: foo16
    bar: bar16
  - foo: foo17
    bar: bar17
  - foo: foo18
    bar: bar18
  - foo: foo19
    bar: bar19
  - foo: foo20
    bar: bar20
  - foo: foo21
    bar: bar21
  - foo: foo22
    bar: bar22
  - foo: foo23
    bar: bar23
  - foo: foo24
    bar: bar24
  - foo: foo25
    bar: bar25
  - foo: foo26
    bar: bar26
  - foo: foo27
    bar: bar27
  - foo: foo28
    bar: bar28
  - foo: foo29
    bar: bar29
  - foo: foo30
    bar: bar30
```
3. using rancher CLI, login, then run: `rancher apps install --values override-values.yml sample sample`

**Result:**
CLI get error:
```
FATA[0373] timed out waiting for app to install. Run 'rancher apps' to verify status
```
server repeated shows these errors:
```
2019/05/17 21:46:29 [ERROR] AppController p-74r47/sample [helm-controller] failed with : helm template failed. panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).listItem(0xc42082b480, 0xc4200a0b40, 0x1d, 0x1d, 0x4, 0x1, 0x5b, 0x0, 0x0, 0x0)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/pkg/strvals/parser.go:291 +0x1078
k8s.io/helm/pkg/strvals.(*parser).key(0xc42082b480, 0xc420744210, 0x0, 0x0)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/pkg/strvals/parser.go:177 +0xcaa
k8s.io/helm/pkg/strvals.(*parser).parse(0xc42082b480, 0xc420744210, 0x600)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7ffd08f6941f, 0x673, 0xc420744210, 0x0, 0xc420744210)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf
main.vals(0x0, 0x0, 0x0, 0xc4205a7180, 0x1, 0x1, 0x22b9790, 0x0, 0x0, 0x22b9790, ...)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/cmd/helm/install.go:382 +0x4e5
main.(*templateCmd).run(0xc42089e200, 0xc420743b00, 0xc42022dea0, 0x1, 0x7, 0x0, 0x0)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/cmd/helm/template.go:137 +0x24b
main.(*templateCmd).(main.run)-fm(0xc420743b00, 0xc42022dea0, 0x1, 0x7, 0x0, 0x0)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/cmd/helm/template.go:92 +0x52
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc420743b00, 0xc42022dce0, 0x7, 0x7, 0xc420743b00, 0xc42022dce0)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4207b2000, 0xc420743b00, 0xc420736900, 0xc420737440)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4207b2000, 0x8, 0x8)
	/home/cjellick/gprojects/helm/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/cjellick/gprojects/helm/src/k8s.io/helm/cmd/helm/helm.go:161 +0x79
: exit status 2
```

**Other details that may be helpful:**
See also https://github.com/sishihara/cases/blob/master/helm-values-parsing-failure/README-en.md

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
rancher single install v2.1.8
rancher cli 2.2.0 for Mac.

**Comment by dnoland1** [comment]
Might be related to https://github.com/rancher/rancher/issues/20189

**Comment by daxmc99** [comment]
This is due to the way the UI and CLI handle yaml files. 
I was able to determine there are likely two errors here:

- The CLI outputs the above yaml file as 
```
        "list_of_map[0].bar": "bar1",
        "list_of_map[0].foo": "foo1",
        "list_of_map[10].bar": "bar11",
        "list_of_map[10].foo": "foo11",
        "list_of_map[11].bar": "bar12",
        "list_of_map[11].foo": "foo12",
        "list_of_map[12].bar": "bar13",
        "list_of_map[12].foo": "foo13",
        "list_of_map[13].bar": "bar14",
        "list_of_map[13].foo": "foo14",
        "list_of_map[14].bar": "bar15",
        "list_of_map[14].foo": "foo15",
        "list_of_map[15].bar": "bar16",
        "list_of_map[15].foo": "foo16",
        "list_of_map[16].bar": "bar17",
        "list_of_map[16].foo": "foo17",
        "list_of_map[17].bar": "bar18",
        "list_of_map[17].foo": "foo18",
        "list_of_map[18].bar": "bar19",
        "list_of_map[18].foo": "foo19",
        "list_of_map[19].bar": "bar20",
        "list_of_map[19].foo": "foo20",
        "list_of_map[1].bar": "bar2",
        "list_of_map[1].foo": "foo2",
        "list_of_map[20].bar": "bar21",
       ... etc
```
A valid JSON representation should be more like:
``` 
"list_of_map": [
            {
                "foo": "foo1",
                "bar": "bar1"
            },
            {
                "foo": "foo2",
                "bar": "bar2"
            },
            {
                "foo": "foo3",
                "bar": "bar3"
            }
]
```

- Even when rancher is passed a more valid JSON it is transformed internally to
```
map[foo:1 bar:1] 
```

In summary, there is likley a cli fix and a Rancher/Norman fix needed here.

**Comment by terrada3** [comment]
Hi, 
Same trouble has occurred in Rancher UI.  

![image](https://user-images.githubusercontent.com/4397382/58084567-1706be80-7bf6-11e9-9ede-9b0039da47b4.png)


![image](https://user-images.githubusercontent.com/4397382/58084529-06eedf00-7bf6-11e9-9709-ea6ede4abcb2.png)

I set answes.yaml below.
```
list_of_map:
  - foo: foo1
    bar: bar1
  - foo: foo2
    bar: bar2
  - foo: foo3
    bar: bar3
  - foo: foo4
    bar: bar4
  - foo: foo5
    bar: bar5
  - foo: foo6
    bar: bar6
  - foo: foo7
    bar: bar7
  - foo: foo8
    bar: bar8
  - foo: foo9
    bar: bar9
  - foo: foo10
    bar: bar10
  - foo: foo11
    bar: bar11
  - foo: foo12
    bar: bar12
  - foo: foo13
    bar: bar13
  - foo: foo14
    bar: bar14
  - foo: foo15
    bar: bar15
  - foo: foo16
    bar: bar16
  - foo: foo17
    bar: bar17
  - foo: foo18
    bar: bar18
  - foo: foo19
    bar: bar19
  - foo: foo20
    bar: bar20
  - foo: foo21
    bar: bar21
  - foo: foo22
    bar: bar22
  - foo: foo23
    bar: bar23
  - foo: foo24
    bar: bar24
  - foo: foo25
    bar: bar25
  - foo: foo26
    bar: bar26
  - foo: foo27
    bar: bar27
  - foo: foo28
    bar: bar28
  - foo: foo29
    bar: bar29
  - foo: foo30
    bar: bar30
```
Result
![image](https://user-images.githubusercontent.com/4397382/58085012-e2dfcd80-7bf6-11e9-85fb-4c4258e91ba4.png)
