### ISSUE TITLE
rancher ingress yaml export does not include namespace

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#20318]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Run ansible playbook https://github.com/TheShellLand/antsable/blob/master/playbooks/rancher2.yml

**Result:**
When importing the ingress yaml, it imports into `default` namespace instead of `backend`

`rancher kubectl create -f ingress/elasticsearch.yaml`

_note: importing namespace yaml files works as expected_

elasticserach.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-jl62s
    field.cattle.io/ingressState: '{"ZWxhc3RpY3NlYXJjaC9iYWNrZW5kL3hpcC5pby8vOTIwMA==":"deployment:backend:elasticsearch"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.86.10"],"port":443,"protocol":"HTTPS","serviceName":"backend:ingress-d9e8fbc38c4404d8136ca5897c80b473","ingressName":"backend:elasticsearch","hostname":"elasticsearch.backend.192.168.86.10.xip.io","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
  name: elasticsearch
  selfLink: /apis/extensions/v1beta1/namespaces/backend/ingresses/elasticsearch
spec:
  rules:
  - host: elasticsearch.backend.192.168.86.10.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-d9e8fbc38c4404d8136ca5897c80b473
          servicePort: 9200
  tls:
  - hosts:
    - elasticsearch.backend.192.168.86.10.xip.io
status:
  loadBalancer: {}
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.3`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `metal`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
sudo docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
