### ISSUE TITLE
Using a link along with a sidekick results in indefinite "Networking" state

### ISSUE THREAD

**Issue by tsilenzio** [rancher/rancher#2040]
Whenever I use a sidekick along with a link, the PostgreSQL container will always be in an indefinite "Networking" state.

```
data:
    image: tsilenzio/base
    stdin_open: true
    tty: true
    command:
        - cat

postgresql:
    image: tsilenzio/postgresql

phpfpm:
    image: tsilenzio/phpfpm
    labels:
        io.rancher.sidekicks: data
    links:
        - postgresql
```

If I remove the ```postgresql``` link or the ```data``` sidekick label, then it will work as expected

Rancher Server: v0.37.0
Rancher Agent: v0.8.2
Rancher Agent Instance: v0.4.1
Rancher Compose: v0.2.6
