### ISSUE TITLE
Allowed to add certificates with same names which is not supported by rancher compose

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2042]
Server version - Build from master - sep 15

We are allowed to add certificates with same names.
```
mysql> select id,name,state from certificate;
+----+-------+--------+
| id | name  | state  |
+----+-------+--------+
|  1 | test1 | active |
|  2 | test2 | active |
|  3 | test3 | active |
|  4 | test1 | active |
+----+-------+--------+
4 rows in set (0.01 sec)
```

In rancher-compose , we are allowed to specify name of the cert which cannot reliably be tied to a cert.

When using the following rancher-conpose yml , test1 in both certs and default_cert gets cert with id=1

```
lb-1:
  scale: 1
  certs:
  - test2
  - test3
  - test1
  load_balancer_config:
    description: lb-1
    name: lb-1
  default_cert: test1
```

We should not allow for adding certificates with duplicate names to be added .
