### ISSUE TITLE
Load balancers and alias doesn't work

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher#2047]
If you have a LB -> Service A Alias -> Service A, the load balancer can't ping service A and therefore doesn't work.

**Comment by deniseschannon** [comment]
I have confirmed that this doesn't work if I try the following docker-compose.yml. I am unable to see my `ghost` application through my load balancer.

```
testlb:
  ports:
  - 2368:2368
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - testalias:testalias
  stdin_open: true
testalias:
  image: rancher/dns-service
  links:
  - ghost:ghost
ghost:
  restart: always
  tty: true
  image: ghost
  stdin_open: true
```

@andrefreitas Could you share your docker-compose file from your stack? In the stack view, click on the little icon to see it. 
 
![vvvvvvv](https://cloud.githubusercontent.com/assets/11410997/9913083/c0e249c0-5c5f-11e5-87a7-036539db5047.png)

**Comment by andrefreitas** [comment]
@deniseschannon I have removed alias so I don't have the config anymore. Anyway, the config was trivial as yours, but instead of a ghost I had a Python Web Application running:
```yml
counter:
  ports:
  - 4016/tcp
  environment:
    CONFIG_AUTH_TOKEN: {sanitized}
    CONFIG_URL: {sanitized}
  external_links:
  - 'databases/counterdb:'
  - 'devops/etcetera:'
  - balancers/auth-balancer:auth
  labels:
    io.rancher.scheduler.affinity:host_label: com.ndrive.services.${service_name}=true
    io.rancher.container.network: 'true'
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=${stack_name}/${service_name}
  image: docker.ndrive.com/counter
```

I was using the Alias, Balancer and the Microservice (Counter) in different stacks, if that information helps. But I don't think that is the problem, since cross-stack communication works well.
