### ISSUE TITLE
Rancher HA: Failed to connect to peer

### ISSUE THREAD

**Issue by trondhindenes** [rancher/rancher#20499]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher HA installed in separate management cluster into namespace `rancher`.

Relevant block from deployment:
```
      - image: rancher/rancher
        name: rancher
        ports:
        - containerPort: 80
          protocol: TCP
        args:
        - "--http-listen-port=80"
        env:
        - name: CATTLE_NAMESPACE
          value: rancher
        - name: CATTLE_PEER_SERVICE
          value: rancher
```

We use Traefik ingress controllers behind AWS ALBs (alb is where ssl termination happens).
ALBs pass the `X-Forwarded-Proto`so we can determine if a request is ssl-ed or not.

**Result:**
Logged in the rancher pods:
`Failed to connect to peer wss://100.108.0.3/v3/connect [local ID=100.100.0.2]: websocket: bad handshake`

As far as I understand, this happens because the rancher pods try and communicate with each other using `wss://` (secured) when there is no cert available to do so. Is there a way to configure the pods to communicate using `ws://` instead?

**Other details that may be helpful:**

**Environment information**
- Rancher version `v2.2.2`
- Custom HA install, but based on official Helm chart.
