### ISSUE TITLE
Volumes_from data are different in the containers

### ISSUE THREAD

**Issue by canonale** [rancher/rancher#2049]
I want to create a stack with Taiga.io I followed the instructions of https://hub.docker.com/r/htdvisser/taiga-back/ in docker hub. The stack, have 4 containers:

- Taiga Back, is the backoffice of the app. Wrote in Python.
- Taiga Front, the angular app to show the app
- Postgres, the database.
- Data, a simple container with a filesystem to share static files and user's files.   

I wrote the docker-compose.yml and I ran the stack in my PC.

**docker-compose.yml**

````yaml
data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
    - /usr/local/taiga/media
    - /usr/local/taiga/static
    - /usr/local/taiga/logs
db:
  image: postgres
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
taigaback:
  image: htdvisser/taiga-back:stable
  hostname: dev.example.com
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: True
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: youremail@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
  links:
    - db:postgres
  volumes_from:
    - data
taigafront:
  image: htdvisser/taiga-front-dist:stable
  hostname: dev.example.com
  links:
    - taigaback
  volumes_from:
    - data
  ports:
    - 0.0.0.0:80:80
````

I checked that run all containers and I created a example project. Is all ok.
I created the rancher-compose file to upload my app. The process was well, but Rancher has created a data container for the other three but the containers did not have the same content

**docker-compose.yml**

````yaml
postgres:
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: taiga
  labels:
    io.rancher.sidekicks: data
  image: postgres
  volumes_from:
  - data
data:
  tty: true
  image: busybox:latest
  volumes:
  - /usr/local/taiga/logs
  - /usr/local/taiga/media
  - /usr/local/taiga/static
  - /var/lib/postgresql/data
taigafront:
  ports:
  - 85:80/tcp
  domainname: deploymentbox.com:85
  hostname: canonale
  image: htdvisser/taiga-front-dist:stable
  links:
  - taigaback:taigaback
  volumes_from:
  - data
  labels:
    io.rancher.sidekicks: data
taigaback:
  environment:
    EMAIL_HOST: mail.gmail.com
    EMAIL_HOST_PASSWORD: passw
    EMAIL_HOST_USER: dbic@gmail.com
    EMAIL_PORT: '587'
    EMAIL_USE_TLS: 'True'
    SECRET_KEY: wonyu9ketZab
  domainname: deploymentbox.com:85
  labels:
    io.rancher.sidekicks: data
  hostname: canonale
  image: htdvisser/taiga-back:stable
  links:
  - postgres
  volumes_from:
  - data
````

**rancher-compose**

````yaml
postgres:
  scale: 1
data:
  scale: 1
taigafront:
  scale: 1
taigaback:
  scale: 1
````

I tried to change the io.rancher.sidekicks labels and to join it all in one but  not ran

**Comment by ebuildy** [comment]
Can you post a screenshot of the running containers? (Or **docker ps** results)

**Comment by deniseschannon** [comment]
By adding a sidekick label, you're essentially asking the service with a label to become a primary service and all sidekicks are secondary services. They are launched together and independently.

In your case to link everything to the single data container, the easiest solution is to make the container the primary service and the services as sidekicks.

The sidekick label asks Rancher to launch all containers together so if you want to share the data container, this will need to be the primary service. This is a great use case and I will add it to the documentation.

Also, please note that there was an issue with linking containers with sidekicks that was fixed in v0.37.1. I'd recommend upgrading your setup to that version.


```
postgres:
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: taiga
  image: postgres
  volumes_from:
  - data
data:
  tty: true
  image: busybox:latest
  labels:
    io.rancher.sidekicks: postgres, taigafront, taigaback
  volumes:
  - /usr/local/taiga/logs
  - /usr/local/taiga/media
  - /usr/local/taiga/static
  - /var/lib/postgresql/data
taigafront:
  ports:
  - 85:80/tcp
  domainname: deploymentbox.com:85
  hostname: canonale
  image: htdvisser/taiga-front-dist:stable
  links:
  - taigaback:taigaback
  volumes_from:
  - data
taigaback:
  environment:
    EMAIL_HOST: mail.gmail.com
    EMAIL_HOST_PASSWORD: passw
    EMAIL_HOST_USER: dbic@gmail.com
    EMAIL_PORT: '587'
    EMAIL_USE_TLS: 'True'
    SECRET_KEY: wonyu9ketZab
  domainname: deploymentbox.com:85
  hostname: canonale
  image: htdvisser/taiga-back:stable
  links:
  - postgres
  volumes_from:
  - data
```

**Comment by pwFoo** [comment]
@deniseschannon
Same use case in #2032. I think make data only container the primary service wouldn't work with loadbalancers? 
In this example taigafront should be added to LB, but it's not a primary service.

**Comment by deniseschannon** [comment]
@pwFoo I believe you just need to make one of the services the primary config. For example, if taigafront needs to be added to a LB, then it should be the container that has all the sidekick labels. Note: I haven't tested using a sidekicked service as a target service, so just going off of what makes sense.

The sidekick label is just telling Rancher that all these services need to be deployed together on 1 host and as 1 unit, so if you scale up the service, then all of the services would be scaled together.

**Comment by pwFoo** [comment]
But I will have two primary services :)

> When using load balancers with services that have sidekicks, you need to use the primary service as 
> the target of the load balancer. A sidekick can not be the target.

For example:
**Service 1: Apache (80/tcp)**  <- needs to be primary because of LB
**Service 2: SSH (22/tcp)**  <- needs to be primary because of LB
**Service 3: Storage** (data only container, shared by Apache & SSH)

**Comment by canonale** [comment]
I updated rancher to 0.37.1 version (CATTLE_RANCHER_SERVER_IMAGE=v0.37.1) and I regenerated the container.
I tried to load this **docker-compose.yml**
````yaml
postgres:
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: taiga
  image: postgres
  volumes_from:
  - data
data:
  tty: true
  image: busybox:latest
  labels:
    io.rancher.sidekicks: postgres, taigafront, taigaback
  volumes:
  - /usr/local/taiga/logs
  - /usr/local/taiga/media
  - /usr/local/taiga/static
  - /var/lib/postgresql/data
taigafront:
  ports:
  - 85:80/tcp
  domainname: deploymentbox.com:85
  hostname: canonale
  image: htdvisser/taiga-front-dist:stable
  links:
  - taigaback:taigaback
  volumes_from:
  - data
taigaback:
  environment:
    EMAIL_HOST: mail.gmail.com
    EMAIL_HOST_PASSWORD: passw
    EMAIL_HOST_USER: dbic@gmail.com
    EMAIL_PORT: '587'
    EMAIL_USE_TLS: 'True'
    SECRET_KEY: wonyu9ketZab
  domainname: deploymentbox.com:85
  hostname: canonale
  image: htdvisser/taiga-back:stable
  links:
  - postgres
  volumes_from:
  - data
````

The system not run. **Taigafront** container attempts to boot, 15 or 20 minutes after, the container is green. It is like all is ok but the app not run. This is the log

![rancher-ok](https://cloud.githubusercontent.com/assets/2377560/9940503/8a3da1f0-5d70-11e5-94e0-89845c132af4.png)


````apache
17/9/2015 8:55:392015/09/17 16:55:39 [emerg] 12#0: no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:55:39nginx: [emerg] no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:55:472015/09/17 16:55:47 [emerg] 13#0: no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:55:47nginx: [emerg] no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:032015/09/17 16:56:03 [emerg] 10#0: no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:03nginx: [emerg] no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:072015/09/17 16:56:07 [emerg] 10#0: no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:07nginx: [emerg] no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:232015/09/17 16:56:23 [emerg] 17#0: no host in upstream ":8000" in /etc/nginx/upstream.conf:3
17/9/2015 8:56:23nginx: [emerg] no host in upstream ":8000" in /etc/nginx/upstream.conf:3
````

In a few minutes, **taigafront** container is red one more time

![taiga-front](https://cloud.githubusercontent.com/assets/2377560/9940508/92926e26-5d70-11e5-9271-caaf84c1d25b.png)

**Comment by pwFoo** [comment]
Hi @canonale 
I think your image `image: tianon/true` will be exiting because of a command `true`?
Docker data only container shouldn't run. So it should be fine with a stopped data container?

Example from docker docs:

    docker create -v /dbdata --name dbdata training/postgres /bin/true

After executed / created it will be in stopped state and used via `volumes-from`.

**Comment by canonale** [comment]
Hello @pwFoo.

I tried it with *tianon/true* but is not correct. I replaced it for *busybox:latest*
With **docker-compose** the stack is run

**Comment by deniseschannon** [comment]
@canonale I'm not exactly sure how your service is supposed to be configured, but the logs indicate it's something wrong in the stack configuration.

Maybe some port needs to be exposed between the images?

**Comment by deniseschannon** [comment]
One thing to note, is that you can re-use the same data container by making the service 1 the primary container (with the labels for sidekicks) and the data container and service 2 sidekicks. This is instead of making the data container the primary one. 

Example:
```
test-data:
  tty: true
  command:
  - cat
  image: ubuntu:14.04.2
  stdin_open: true
test1:
  tty: true
  image: ubuntu:14.04.2
  stdin_open: true
  labels:
    io.rancher.sidekicks: test-data, test2
  volumes_from:
  - test-data
test2:
  tty: true
  image: ubuntu:14.04.2
  stdin_open: true
  volumes_from:
  - test-data
```

But based on this issue, it sounds like it's a stack configuration issue and not a Rancher issue so I'm going to close it.
