### ISSUE TITLE
Sometimes LB rules are not accessible for more than 30 secs after the LB service has been activated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2053]
Server version - Build from master

Created LB service with the following configs:

```
rancher-compose.yml

LB-test215566:
  ports:
  - 7906:80
  - 7907:81
  labels:
    io.rancher.loadbalancer.target.test716502: /service1.html=80,/service3.html=81
    io.rancher.loadbalancer.target.test64975: www.abc1.com
    io.rancher.loadbalancer.target.test985356: www.abc1.com:7906/service1.html,www.abc1.com:7907/service3.html
  image: rancher/load-balancer-service
  links:
  - test985356:test985356
  - test64975:test64975
  - test716502:test716502
  - test556635:test556635
test64975:
  image: sangeetha/testnewhostrouting:latest
test556635:
  image: sangeetha/testnewhostrouting:latest
test985356:
  image: sangeetha/testnewhostrouting:latest
test716502:
  image: sangeetha/testnewhostrouting:latest

docker-compose.yml
  scale: 1
test64975:
  scale: 2
test556635:
  scale: 2
test985356:
  scale: 2
test716502:
  scale: 2
```

Waited for LB service to be active and all host map and target maps to be created.
I also see the hap proxy being programmed for both the 7906 and 7907 ports.

```
global
    log 127.0.0.1 local0
        log 127.0.0.1 local1 notice
        maxconn 4096
        maxpipes 1024
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    tcp
    option  tcplog
        option  dontlognull
        option  redispatch
        option forwardfor
        option httpclose
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend f1be008a-9fe1-4b5d-9a0f-9ec617299992_frontend
        bind 10.42.233.184:7906
        mode http

        acl 7_host hdr(host) -i www.abc1.com
        acl 7_host hdr(host) -i www.abc1.com:7906
        acl 7_path path_beg -i /service1.html
        use_backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_7_backend if 7_host 7_path
        acl 1_host hdr(host) -i www.abc1.com
        acl 1_host hdr(host) -i www.abc1.com:7906
        use_backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_1_backend if 1_host 
        acl 9_path path_beg -i /service1.html
        use_backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_9_backend if  9_path
        acl 8_path path_beg -i /service3.html
        use_backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_8_backend if  8_path
        default_backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_4_backend

backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_7_backend
        mode http
        balance roundrobin
        server b1789804-24af-4e4f-a407-f8df434eff79 10.42.160.162:80
        server 7ab8682b-2fc1-4b95-9ddb-8cfa2b0b8758 10.42.160.20:80

backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_1_backend
        mode http
        balance roundrobin
        server 886b234a-b88c-4d93-827e-68689bf85d12 10.42.254.204:80
        server bd9816dd-5b54-420a-9b44-0b564e3edff4 10.42.15.199:80

backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_9_backend
        mode http
        balance roundrobin
        server 231d5f16-4f31-43c0-920c-2076095550f6 10.42.155.119:80
        server 3ca56a0b-47d9-44b8-9be1-ec4de084d48c 10.42.102.56:80

backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_8_backend
        mode http
        balance roundrobin
        server 231d5f16-4f31-43c0-920c-2076095550f6 10.42.155.119:81
        server 3ca56a0b-47d9-44b8-9be1-ec4de084d48c 10.42.102.56:81

backend f1be008a-9fe1-4b5d-9a0f-9ec617299992_4_backend
        mode http
        balance roundrobin
        server 60eda58b-eb48-4a51-b63c-e1b59fc34806 10.42.104.23:80
        server fe60fb82-3a84-45cf-8d4c-90afe988f709 10.42.223.45:80

frontend 41b7fcde-dca3-4a41-aee4-08edd3225423_frontend
        bind 10.42.233.184:7907
        mode http

        acl 5_host hdr(host) -i www.abc1.com
        acl 5_host hdr(host) -i www.abc1.com:7907
        acl 5_path path_beg -i /service3.html
        use_backend 41b7fcde-dca3-4a41-aee4-08edd3225423_5_backend if 5_host 5_path
        acl 3_host hdr(host) -i www.abc1.com
        acl 3_host hdr(host) -i www.abc1.com:7907
        use_backend 41b7fcde-dca3-4a41-aee4-08edd3225423_3_backend if 3_host 
        acl 6_path path_beg -i /service1.html
        use_backend 41b7fcde-dca3-4a41-aee4-08edd3225423_6_backend if  6_path
        acl 2_path path_beg -i /service3.html
        use_backend 41b7fcde-dca3-4a41-aee4-08edd3225423_2_backend if  2_path
        default_backend 41b7fcde-dca3-4a41-aee4-08edd3225423_0_backend

backend 41b7fcde-dca3-4a41-aee4-08edd3225423_5_backend
        mode http
        balance roundrobin
        server b1789804-24af-4e4f-a407-f8df434eff79 10.42.160.162:81
        server 7ab8682b-2fc1-4b95-9ddb-8cfa2b0b8758 10.42.160.20:81

backend 41b7fcde-dca3-4a41-aee4-08edd3225423_3_backend
        mode http
        balance roundrobin
        server 886b234a-b88c-4d93-827e-68689bf85d12 10.42.254.204:81
        server bd9816dd-5b54-420a-9b44-0b564e3edff4 10.42.15.199:81

backend 41b7fcde-dca3-4a41-aee4-08edd3225423_6_backend
        mode http
        balance roundrobin
        server 231d5f16-4f31-43c0-920c-2076095550f6 10.42.155.119:80
        server 3ca56a0b-47d9-44b8-9be1-ec4de084d48c 10.42.102.56:80

backend 41b7fcde-dca3-4a41-aee4-08edd3225423_2_backend
        mode http
        balance roundrobin
        server 231d5f16-4f31-43c0-920c-2076095550f6 10.42.155.119:81
        server 3ca56a0b-47d9-44b8-9be1-ec4de084d48c 10.42.102.56:81

backend 41b7fcde-dca3-4a41-aee4-08edd3225423_0_backend
        mode http
        balance roundrobin
        server 60eda58b-eb48-4a51-b63c-e1b59fc34806 10.42.104.23:81
        server fe60fb82-3a84-45cf-8d4c-90afe988f709 10.42.223.45:81
```

When trying to access  - http://<host-ipaddress>:7907/name.html , we get connection error for 30 secs.

After a while , LB rules are accessible.

In this case , LB rules for 7906 was still accessible when connection errors was seen for port 7907.
