### ISSUE TITLE
Helm Chart: `--set tls=external` is using Self Signed certificates instead of External

### ISSUE THREAD

**Issue by caleblloyd** [rancher/rancher#20573]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

Helm chart `--set tls=external` is using Self Signed certificates instead of External

**Steps to reproduce (least amount of steps as possible):**

Unpack the latest helm chart to a directory called `rancher`

```
helm template \
    --name rancher \
    --namespace cattle-system \
    --set hostname=rancher.example.com \
    --set tls=external \
    rancher
```

**Result:**

The deployment is using self-signed certs, even though the Ingress is not managing certs:

```
      containers:
      - image: rancher/rancher:v2.2.3
        name: rancher
        ports:
        - containerPort: 80
          protocol: TCP
        args:
        # Rancher self-signed - don't clear ca certs
        - "--http-listen-port=80"
        - "--https-listen-port=443"
        - "--add-local=auto"
```

It should be using Public Trust CA by default:

```
      containers:
      - image: rancher/rancher:v2.2.3
        name: rancher
        ports:
        - containerPort: 80
          protocol: TCP
        args:
        # Public trusted CA - clear ca certs
        - "--no-cacerts"
        - "--http-listen-port=80"
        - "--https-listen-port=443"
        - "--add-local=auto"
```

**Environment information**
- Rancher version: 2.2.3
