### ISSUE TITLE
Can't create new node with cloud-init script in template

### ISSUE THREAD

**Issue by vistalba** [rancher/rancher#20571]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a new node (hetzner cx11 with the driver) from template with a cloud-init script.

**Result:**
Error: `Error creating machine: Error running provisioning: Error running "sudo apt-get update": ssh command error:`
After that error rancher deletes the node and tries to spin up a new one and end with the same error. So there is a loop.

**Other details that may be helpful:**

cloud-init script used:
```
#cloud-config
locale: de_DE.UTF-8
timezone: Europe/Berlin
package_upgrade: true
packages:
 - tree
 - screen
 - apt-transport-https
 - ca-certificates
 - curl
 - software-properties-common
 - nload
 - htop
 - jq
package_reboot_if_required: true
users:
# Create new user `user1`
  - name: user1
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    passwd: $6$w....
    ssh-authorized-keys:
      - ssh-rsa A...x
  - name: root
    ssh-authorized-keys:
      - ssh-rsa A...x
# Configure SSH
runcmd:
  - sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - sed -i 's/#Banner \/etc\/issue.net/Banner \/etc\/issue.net/g' /etc/ssh/sshd_config
  - /etc/init.d/ssh restart
# Write some Files
write_files:
-   encoding: b64
    content: K...x
    owner: root:root
    path: /etc/issue.net
    permissions: '0644'
```
Nothing special I think... ssh is working well when I log in from a other linux server.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.3` UI: `v2.2.41` |
|Route|`authenticated.cluster.nodes.index`|
