### ISSUE TITLE
Cloning of a Load Balancer fails

### ISSUE THREAD

**Issue by andrefreitas** [rancher/rancher#2059]
When cloning a Load Balancer, I get an error message. In the previous version of Rancher I had cloned it successfully without errors. I don't know if this is something related with launching Balancers through UI or Rancher-Compose. Wondering if it is related with the SSL Load Balancer clonning Issue in #1973

Update: Clone is ok if the balancer is created through UI.

# Versions
Rancher	v0.37.0
Cattle	v0.91.0
User Interface	v0.47.0
Rancher Compose	beta/latest

#  Balancer
```yml
fetcher-balancer:
  restart: always
  ports:
  - 4007:4007
  external_links:
  - microservices/fetcher:fetcher
  labels:
    io.rancher.scheduler.affinity:host_label: com.ndrive.stack.balancers=true
    io.rancher.container.network: 'true'
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```
# Screenshots
![step1](https://cloud.githubusercontent.com/assets/1192089/9932149/79ea3458-5d39-11e5-935b-e5376b1e55c6.png)
![step2](https://cloud.githubusercontent.com/assets/1192089/9932150/79ea39da-5d39-11e5-9b6f-d8675c03a415.png)

# Rancher logs
```
==> cattle-debug.log <==
2015-09-17 11:28:51,758 DEBUG [:] [] [] [] [p995425658-3409] [i.c.p.a.p.s.j.WebSocketMessageWriter] Websocket connection closed. Code: [1005], message: [null].
2015-09-17 11:28:55,720 DEBUG [:] [] [] [] [torService-1753] [a.p.s.NonBlockingSubscriptionHandler] Got exception on write, disconnecting : class java.io.EOFException [WebSocket is closed.]
```
