### ISSUE TITLE
Remove default port from service discovery

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#20656]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Desired Result:**
The current functionality when creating a workload without specifying a port is to create a service that uses port 42. This is so that service discovery works:

https://rancher.com/blog/2018/2018-09-04-service_discovery_2dot0/

The customer would like to forgo this default port due to it causing confusion on their end. Perhaps something like this will work:

```
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
```
