### ISSUE TITLE
Network isolation and external IPs

### ISSUE THREAD

**Issue by ravenpride** [rancher/rancher#20711]
Hello,

I've tried to publish a port of a pod under a specific IP address. Therefore I've used a service with a cluster ip and the desired external ip.

The (pruned) manifest looks like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: zimbra-public
spec:
  ports:
    - name: smtp
      port: 25
      protocol: TCP
  externalIPs:
  - 1.2.3.4
```

It worked as intended without project isolation, but stopped working after enabling the isolation. As I understand the project isolation, it should block communication between pods belonging to different projects, not between pods/services and the node. Using a node port service works, but exposes the ports on all nodes in addition to the desired ip address.

Any help is appreciated :-)

Thank you in advance.
