### ISSUE TITLE
Accentuation and misspelling pt-br 

### ISSUE THREAD

**Issue by arthurbdiniz** [rancher/rancher#20782]
**What kind of request is this (question/bug/enhancement/feature request):**
This is an enhancement request of pt-br translations. I saw some accentuation and misspelling.

**Result:**
```yml
enterpriseHostName: "Dominio da empresa:"
text: 'Para GitHub padrão, <a href="https://github.com/settings/developers" target="_blank">clique aqui</a> para ir as configurações de aplicativos em uma nova janela.'
noMatch: Nenhum balanciador corresponde à pesquisa atual
placeholder: p.ex. usuario
subtext1: "Digite o endereço, porta e protocolo para conectar ao seu servidor {providerName}.  <code>389</code> ié a porta padrão para inseguro, <code>636</code> para TLS."
```

**Other details that may be helpful:**

path to translations: `translations/pt-br.yaml`
