### ISSUE TITLE
Failure to create/edit an Ingress object, with a name containing a period '.', via Rancher: `"Name" contains an invalid character: .`

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#20809]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy the following ingress resource into a Rancher launched cluster via kubectl:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test.example.com
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
- Attempt to edit the resource via the Rancher UI, to change the path for example, click 'Save'

**Result:**

- Observe error of the format `"Name" contains an invalid character: .`

**Environment information**
Rancher v2.2.4

**Comment by davidnuzik** [comment]
I was able to replicate this on v2.2.4 and master (6/11/19).
You can also import via YAML without the UI/API complaining (until you edit and try to save changes)

I think the problem is that the schema has name field of type "dnsLabel" which if I recall correctly does not like periods in the string. For some reason only when we edit and try to save do we seem to be enforcing the schema.
There must be a reason but I was expecting when we at least import YAML we enforce schema (we can't do anything about kubectl, but we can probably change the type to support this).

**Comment by bmdepesa** [comment]
rancher/rancher:master-head 7e82f85f

* Import yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test.example.com
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
* Ingress is created
* Edit the ingress
* Save is successful
