### ISSUE TITLE
Feature Request: Conditions for Rancher 2 Pipeline 

### ISSUE THREAD

**Issue by herrphon** [rancher/rancher#20813]
The old pipeline from rancher 1 had the following options in the syntax:

```
stages: #array
  - Name: <string>
    needApprove: <bool>
    parallel: <bool>
    approvers: ["id1","id2"] #<sting[]> for user ids
    # either all or any is used, each condition should be in `ENVVAR=VAL` or `ENVVAR!=VAL` format.
    conditions:
      all: <[]string>
        - "CICD_GIT_BRANCH=master"
        - "CICD_GIT_BRANCH!=master"
      any: <[]string>
        steps: [<step_spec>]
```

This allowed for a variety of possibilities. 

The current syntax only supports branches and events:

```
    # Conditions for stages
    when:
      branch: master
      event: [ push, pull_request ]
```

It would be nice to be able to have more conditions.

In our case, we have different k8s clusters for test and prod... but we use the same code and would like to deploy conditionally depending on the cluster-id or similar.

Of cause it is possible to work around by doing some custom script with a container that has kubectl installed - but that's not very convenient.

Current workaround
```
steps:
  - runScriptConfig:
      image: some-k8s-image-with-kubectl
      shellScript: |-
        if [ "${CICD_CLUSTER_ID" == "c-cafe" ]; then
          kubectl apply -f deployment.yml
        fi
```
