### ISSUE TITLE
[Image pull] Sometimes Multiple versions of image are present after image is pulled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2081]
Server version - Build from master - sep 18
Rancher compose version - rancher-compose-v0.4.0-rc
Used rancher-compose to pull image using following command when there were 3 hosts in the setup:

./rancher-compose -f dc2.yml pull
```
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.4.0-rc1# cat  dc2.yml 
web1:
  restart: always
  tty: true
  image: sangeetha/testclient
  stdin_open: true
web2:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
root@sangee01:/home/sangeethahariharan1/rancher-compose-v0.4.0-rc1# 
```

Both images sangeetha/testclient and sangeetha/testnewhostrouting got pulled in all 3 hosts.

But in 1 of the hosts , I see an aditional image for "sangeetha/testclient " tagged as "latestpull-74" present.

```
root@sangeemaster-10acre-2:/home/sangeethahariharan1# docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
redis                          latest              2f2578ff984f        8 days ago          109.2 MB
nginx                          latest              0b354d33906d        8 days ago          132.9 MB
rancher/agent                  v0.8.2              11539df40565        2 weeks ago         365.1 MB
sangeetha/testnewhostrouting   latest              8dc7c560556e        8 weeks ago         93.44 MB
sangeetha/testclient           latest              9ac374da8c7e        4 months ago        261.3 MB
sangeetha/testclient           latestpull-74       9ac374da8c7e        4 months ago        261.3 MB
root@sangeemaster-10acre-2:/home/sangeethahariharan1# 
```
