### ISSUE TITLE
Hostname matching does not work with NodePort ingress gateway

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20833]
rancher/rancher:master 7a23ff88

Hostname matching is not working as expected with NodePort ingress gateway in Istio

* Create cluster
* Enable istio with ingress gateway of type NodePort
* Enable auto-injection on a namespace
* Import a service
* Create a gateway and virtualservice which matches on a hostname to do some routing:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
    - "some-test-route-url"
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            exact: /productpage
        - uri:
            exact: /login
        - uri:
            exact: /logout
        - uri:
            prefix: /api/v1/products
      route:
        - destination:
            host: productpage
            port:
              number: 9080
```

Access the service through the nodeport and a 404 error is returned. 

Enabling some additional logging in `istio-telemetry` I can see that the hostname is being recorded as:
```
"destination":"productpage","host":"some-test-route-url:31380","
```
Where 31380 is the http port for ingress gateway.

This is a known issue for istio/envoy:
https://github.com/istio/istio/issues/8807
https://github.com/istio/istio/issues/6469
