### ISSUE TITLE
[Image pull]  - Image is not pulled before starting a container when using io.rancher.container.pull_image=always

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2083]
Server version - Build from master - Sep 18
Rancher-compose version - v0-4-0-rc1

Had 3 hosts in the setup , 2 of the hosts had older version of image - " sangeetha/testupgrade:latest" and 1 host had the latest version of image - "sangeetha/testupgrade:latest".

Created service using rancher-compose up using the following docker compose yml
```
webnew1:
  restart: always
  tty: true
  image: sangeetha/testupgrade:latest
  labels:
     io.rancher.container.pull_image: always
  stdin_open: true
```

This does not result in the latest version of the image being pulled to the hosts (that did not have the latest version of the image) before containers for the services are deployed.
