### ISSUE TITLE
[Image pull] - When soft host affinity/anti-affinity rules are used , image should be pulled to all hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2088]
Server version - V0.38.0-rc2
Rancher compose version - rancher-compose-v0.4.0-rc3

When soft host affinity/anti-affinity rules are used  when pulling images , the hosts qualified for pulling images are the ones that strictly qualify for the host affinity/anti-affinity rules. 

Expected Behavior should be for the images to be pulled to all the hosts in the setup.

Following is the example of docker-compose.yml that was used:
 
```
webnew1:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  labels:
    io.rancher.scheduler.affinity:host_label_soft: test1=value1
  stdin_open: true
webnew2:
  restart: always
  tty: true
  image: sangeetha/testclient
  labels:
    io.rancher.scheduler.affinity:host_label_soft_ne: test1=value1
  stdin_open: true
```
