### ISSUE TITLE
Cannot clone a service that has a sidekick

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2094]
v0.37.1

Steps to Reproduce:

1. Add a sidekicked service into rancher using rancher-compose
```
test:
  tty: true
  image: ubuntu:14.04.2
  stdin_open: true
  volumes_from:
  - test-data
  labels:
    io.rancher.sidekicks: test-data
test-data:
  tty: true
  command:
  - cat
  image: ubuntu:14.04.2
  stdin_open: true
```
2. Click on clone in UI

Result: 

```
Validation failed in API: LaunchConfigName
```

Expected Result: We shouldn't be able clone services that have sidekicks. So either hide the clone option or provide a better error message.
