### ISSUE TITLE
UI timing out and errors when make first workload

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20988]
Version: Master (v2.3) (6/19/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Reference: https://github.com/rancher/rancher/issues/20079
- Create a new cluster
- Watch browser dev console network traffic
- Create a new workload (first one ever on this new cluster)

**Result:**
Some of the time, namespace is stuck in "Activating" state according to the UI even though this in not the case when inspect API. I cannot always reproduce the issue.
We see we have a websocket open when we view the Namespaces page (and stuck in "Activating" state.
(Screenshot below is shown after stuck in Activating state in UI for about 5 mins)
![image](https://user-images.githubusercontent.com/45179589/59792522-3b06ff80-9289-11e9-8331-72897a44a002.png)
![image](https://user-images.githubusercontent.com/45179589/59792557-44906780-9289-11e9-8d70-29e7985491ae.png)
![image](https://user-images.githubusercontent.com/45179589/59792577-53771a00-9289-11e9-955d-aa1f4e0c1dc4.png)

I believe this is a websocket issue.

**Additional Info:**
Chrome Version 75.0.3770.90 (Official Build) (64-bit) for Desktop on macOS Mojave

I can't always replicate the issue. If it's a fresh single-node rancher install, I create my first cluster on it, and create a project and then a workload with new namespace I sometimes see the issue. Sometimes can happen when create an app as well. As I create more clusters and try to test again on same rancher install I seem to be less likely to run into the issue. I see many websockets though (not sure if this is expected):
![image](https://user-images.githubusercontent.com/45179589/59793076-82da5680-928a-11e9-98a9-34730019c317.png)

**Comment by davidnuzik** [comment]
This may be easier to reproduce by importing YAML to create a deployment.
for example. With a fresh cluster, create a project and try to import this YAML:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
Import mode "Project" and you should be making a NEW namespace (no other namespaces should exist in this project).

You will probably see the UI stuck "Saving..." when you click on import. The namespace is basically taking too long in the "Activating" statue but when you look at the API it's already active.

When this fails to work correctly you see a blank error like this in the UI:
![image](https://user-images.githubusercontent.com/45179589/59794169-347a8700-928d-11e9-8509-3320b1b9e15a.png)

And when try to import again nothing happens.
Now go to the "Namespaces" page and you'll see test is in "Activating" state
![image](https://user-images.githubusercontent.com/45179589/59794202-49efb100-928d-11e9-8b38-77af2bd4a709.png)

View in API and it is not. It is Active.
