### ISSUE TITLE
Networkpolicy sometimes not working

### ISSUE THREAD

**Issue by vistalba** [rancher/rancher#21046]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
deploy networkpolicy for a service

**Result:**
sometimes the networkpolicy not work at all... sometimes all traffic is blocked, sometimes all traffic is allowed.. somtimes it works normal,

**Other details that may be helpful:**
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
    matchLabels:
      app: someappname
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: someappname
spec:
  podSelector:
    matchLabels:
      app: someappname
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 178.0.0.0/17
    - ipBlock:
        cidr: 60.0.0.0/15
    - ipBlock:
        cidr: 80.0.0.0/15
    ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector:
    matchLabels:
      app: someappname
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.32.0.0/16
        - 10.42.0.0/16
        - 10.43.0.0/16
  policyTypes:
  - Egress
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.24
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted vm
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vcpu/16GB
- Kubernetes version (use `kubectl version`): 1.13.5

Is this normal? How can I use networkpolicy for a service inside rancher? Is there another way to restrict access to one of my servcies?
