### ISSUE TITLE
[rancher-compose] Error when building image from URL on RancherOS hosts

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2118]
@djiit filed in the rancher-compose repo: 

I don't know if it's related to rancher or rancherOS... Sorry if I'm in the wrong repo.

I tried to use *rancher-compose* with a `build:` instruction set to a HTTP URL (ending with .git).

My only declared host is running *RancherOS* and I got this error when using `rancher-compose up`:

    66a33137-c63a-4931-b839-c7a1ab46ee3e : 404 Client Error: Not Found ("Error trying to use git: exec: "git": executable file not found in $PATH ()")

Did I miss something ? Should I install *git* in RancherOS ?

**Comment by deniseschannon** [comment]
@ibuildthecloud commented that 

Unfortunately git based builds don't work on Rancher v0.3.x. This will be addressed in RancherOS v0.4, but we have yet to release v0.4.

**Comment by deniseschannon** [comment]
Verified in v0.47.0 of Rancher using v0.4.1 of RancherOS that this is no longer an issue.

**Comment by elct9620** [comment]
I have same problem using Rancher v0.51.0 and RancherOS v0.4.2, is this problem still not fix?

**Comment by deniseschannon** [comment]
Yes, I verified it in v0.47.0 and RancherOS v0.4.2. This has been fixed. What error are you getting?

Can you provide your git URL? Are you sure it's a proper dockerfile?

This is the URL that I used and my docker-compose.yml file.

```
testurl:
  build: https://gist.githubusercontent.com/deniseschannon/3276610b006382da655b/raw/11690eefe15de38e82d40d559f0db641722afb6c/buildtest
```

In the URL, this is what it shows
```
FROM nginx

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by elct9620** [comment]
I test this feature using my customize nginx, 'git@github.com:elct9620/nginx-pagespeed.git'

I am sure when I using ubuntu as host and install fit on host, it can build correctly. But if I using rancheros, I got this error.

**Comment by deniseschannon** [comment]
I think you need to point it directly to the Dockerfile so the build would need to be pointing at 
https://github.com/elct9620/nginx-pagespeed/blob/master/Dockerfile

**Comment by elct9620** [comment]
Direct point Docket can work, but if I specify some repo need add some file from filesystem, I need to point fit repo and let rancher clone it to build correctly image. This is my expected feature when I reading document says " support fit repo"

**Comment by deniseschannon** [comment]
Per the docs, your URL needs to be to a git that is compatible with the Docker Remote API. Have you tried doing a build pointing to your git for docker-compose? If it works in docker-compose, it will work to build for rancher-compose/ 

http://docs.rancher.com/rancher/rancher-compose/build/

**Comment by elct9620** [comment]
I didn't tested on docker-compose, but if I using Ubuntu instead RancherOS, it is working.
I will test it using docker-compose when I can use my computer, and report it worked or not.

**Comment by someone1** [comment]
This is broken on rancheros v1.1.0:

> $ git
> -bash: git: command not found

and in Rancher:

> (Expected state running but got error: Error response from daemon: failed to init repo at /var/lib/docker/tmp/docker-build-git508179416: : exec: "git": executable file not found in $PATH)

docker-compose file for reference:

```
version: '2'
services:
  kibana-wazuh:
    build: https://github.com/someone1/kibana-wazuh-xpack.git
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      TZ: America/New_York
    external_links:
    - ESCluster/es-tribe:elasticsearch
    ports:
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
```
