### ISSUE TITLE
Pipeline applyAppConfig step fails when attempting to upgrade app deployed from project scoped catalog

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#21282]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Spin up simple single-node Rancher v2.2.4 instance:
1. Add a catalog at both the default project and global level
2. Add a pipeline with a simple `.rancher-pipeline.yml` per below to deploy application from the catalog
3. Run the pipeline and observe global level catalog and project level catalog apps both deployed successfully
4. Run the pipeline and observe global level catalog upgraded successfully, but project level catalog app fails with `13:03:53 time="2019-07-02T13:03:52Z" level=fatal msg="version 0.0.3 is not valid"`

```
stages:
- name: Global Level
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:test-test
      version: 0.0.3
      name: global
      targetNamespace: global
- name: Project Level
  steps:
  - applyAppConfig:
      catalogTemplate: p-dkq27:test-test
      version: 0.0.3
      name: project
      targetNamespace: project
branch:
  include:
  - pipeline
  exclude:
  - master
```

**Result:**

Global level catalog app upgrades successfully, project level catalog app fails to upgrade with following output:
```
13:03:39 [pipeline_p-xvq49-8] Running shell script
13:03:41 + apply-app
13:03:41 [INFO]check done...
13:03:41 [INFO]prepare config done...
13:03:42 time="2019-07-02T13:03:42Z" level=info msg="Saving config to /root/.rancher/cli2.json"
13:03:42 [INFO]refreshing catalog
13:03:52 [INFO]upgrading the "project" app
13:03:53 time="2019-07-02T13:03:52Z" level=fatal msg="version 0.0.3 is not valid"

```

**Other details that may be helpful:**

Similar behaviour previously reported and a CLI patch made re. https://github.com/rancher/rancher/issues/17511

**Environment information**
Rancher v2.2.4
