### ISSUE TITLE
v2.2.4 Non-master branch not detecting .rancher-pipeline.yml 

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#21336]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Push .rancher-pipeline.yml to branch 

**Result:**

![image](https://user-images.githubusercontent.com/28725423/60707749-708f2800-9eda-11e9-995b-255beef5769c.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.2.4`
- Installation option (single install/HA): `single`

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): `custom`
- Machine type (cloud/VM/metal) and specifications (CPU/memory): `metal`
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by gitlawr** [comment]
Can you elaborate the source code provider and its version you are using?
Do you find the pipeline file commit(create/update) in the commit history of the v0.2 branch?
Can you share the pipeline file stored in the v0.2 branch if feasible?

**Comment by ainiml** [comment]
@gitlawr both master and v0.2 branch are identical

It shows the `.rancher-pipeline.yml` for the master branch, but not for the `v0.2` branch 

```
stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry/ui:v2.0.22
      pushRemote: true
      registry: registry.world0:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch: {}
notification: {}
```
