### ISSUE TITLE
Binary ConfigMap referenced by workload - Javascript Error in Rancher UI 

### ISSUE THREAD

**Issue by kengibous** [rancher/rancher#21349]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Create a configMap with binary data - I am using this configMap to write a certificate to a pod's filesystem

Example -
```
apiVersion: v1
binaryData:
  lower.data.protection.pfx: <base64encode cert data here>
kind: ConfigMap
```

Then create a workload that references the configMap. 

Example -
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  ...
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: lower.data.protection.pfx
            path: dp.pfx
          name: lowerdataprotectioncert-config
        name: dataprotection
```

Then in the rancher user interface if you click the workload, a javascript error occurs and the page is stuck with a loading icon.

**Result:**

![image](https://user-images.githubusercontent.com/6308070/60731497-4b67dd00-9f0d-11e9-94b2-499483abc6d7.png)

Java script error - 

component.js:144 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.updateConfigMapKeys (component.js:144)
    at n.init (component.js:44)
    at n [as init] (0:58190)
    at n.e (0:57415)
    at n (0:57475)
    at n (0:57475)
    at n (0:57475)
    at new n (0:57475)
    at Function.e.create (0:57488)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA): single install
