### ISSUE TITLE
Feature request: ability to disable BIRD readiness check in Calico

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#21476]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description**
Currently it appears that there is no way to disable the BIRD readiness check in Calico using the Rancher interface or in the cluster.yaml file.  This is a feature request to have the ability disable BIRD readiness so that if a non-mesh node goes down, it will not make the CNI unavailable.  More information on this at the bottom of the following link.
https://docs.projectcalico.org/v3.5/getting-started/kubernetes/troubleshooting

**Comment by leodotcloud** [comment]
@patrick0057 
Navigating to Cluster > System > calico-node (kube-system namespace) one can click on View/Edit Yaml to make modifications to the existing DaemonSet manifest.

Getting rid of the following lines would disable the readiness check:
```
        readinessProbe:
          exec:
            command:
            - /bin/calico-node
            - -bird-ready
            - -felix-ready
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
