### ISSUE TITLE
Workload name validation does not match kubernetes naming convention

### ISSUE THREAD

**Issue by erSitzt** [rancher/rancher#21495]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Create a workload with the name "test-v1.1" using any docker image, 

**Result:**

Rancher rejects this as am invalid name.
`	
"Name" contains an invalid character: .`

**Other details that may be helpful:**

Create a deployment by importing the yaml works
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-v1.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes-v1.1
  template:
    metadata:
      labels:
        app: hello-kubernetes-v1.1
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```
This only produces an error when the container name does not match the DNS-1123 regex

Editing the workload afterwards works too, but the name is not displayed in correctly in all dialogs

**Workload list:**
![image](https://user-images.githubusercontent.com/1625376/61122383-f7776e00-a4a1-11e9-8157-4a3cb3ddcbcc.png)

**Workload edit:**
![image](https://user-images.githubusercontent.com/1625376/61122420-0a8a3e00-a4a2-11e9-9b84-9406615e8d7e.png)

**View workload**
![image](https://user-images.githubusercontent.com/1625376/61122446-1544d300-a4a2-11e9-8ade-d93c0006b9fe.png)

**Environment information**
- Rancher version : v2.2.4
- single install

**Cluster information**
Custom
v1.13.5
