### ISSUE TITLE
Rancher import resource nonconformant

### ISSUE THREAD

**Issue by jeffb4** [rancher/rancher#21599]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Launch Rancher 2.2.4
Create a cluster from import
Download and analyze YAML

**Result:**

There is a CRB with a namespace specified
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cattle-admin-binding
  namespace: cattle-system
  labels:
    cattle.io/creator: "norman"
subjects:
- kind: ServiceAccount
  name: cattle
  namespace: cattle-system
roleRef:
  kind: ClusterRole
  name: cattle-admin
  apiGroup: rbac.authorization.k8s.io
```

Because CRBs are cluster-wide, they properly should not have a namespace in their metadata (line 5 above)

**Other details that may be helpful:**

Source of template is https://github.com/rancher/rancher/blob/master/pkg/systemtemplate/template.go#L25

**Environment information**

Rancher 2.2.4 in HA
