### ISSUE TITLE
Communication between containers on different hosts not working

### ISSUE THREAD

**Issue by ccirello** [rancher/rancher#2164]
Rancher Version: Click on the cow icon in the upper left corner to provide us the info.
```
Rancher	v0.39.0
Cattle	v0.95.0
User Interface	v0.52.0
Rancher Compose	beta/latest
```

Rancher Setup: What is your setup of Rancher?
```
On a OS X 10.10.5, with VirtualBox 5.0

docker-machine create rancher-master --driver=Virtualbox
on master:
docker run -d --restart=always -p 8080:8080 rancher/server

on the others hosts, manual host addition with
docker-machine create rancher-minion-1 --driver=Virtualbox
docker-machine create rancher-minion-2 --driver=Virtualbox
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.8.2 http://...redacted...

```

Internal Rancher server DB, external DB? bind mount MySQL volume? - Internal DB
Authentication? GitHub, LDAP (With or without TLS), Local - Tried both with GH and no Auth

Rancher Hosts:
Is Rancher server on the same host as Rancher agent? If so, please make sure that the IP of the shared host has the server IP displayed in the UI. If not, please read more about how to correct.
No, they are different VMs

If you’ve used Rancher’s managed network, can containers in host A ping containers in host B? You can check by exec into a container on Host A and ping the IP of a container on the Host B.
It can't ping using the 10.* IPs

If you see a host on the UI with IP (172.17.42.1) or starting with 172.17.x.x, then please double check to see if the IP is the actual IP of the host. These IPs tend to be the docker internal IP and will not work. You will need to re-register your host with the correct IP.
I don't see such IP

Service/Load Balancer Issues:
Provide your docker-compose.yml file for your stack by clicking on the paper icon in the detailed Stack View.

docker-composer.yml:
```
lb-hw:
  ports:
  - 9080:8080
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
  - go-hw-debug:go-hw-debug
  stdin_open: true
go-hw-debug:
  ports:
  - 8080:8080/tcp
  restart: always
  tty: true
  image: ccirello/helloworld
  stdin_open: true
```
rancher-composer.yml:
```
lb-hw:
  scale: 1
  load_balancer_config:
    name: lb-hw config
go-hw-debug:
  scale: 1
```
