### ISSUE TITLE
`rancher-compose pull` Unknown schema type [pullTask] error

### ISSUE THREAD

**Issue by summerQLin** [rancher/rancher#2173]
I use rancher-compose up to deploy containers. There is 'cache' service in the docker-compose.yml,
```
...
cache:
  restart: always
  tty: true
  image: redis
  stdin_open: true
...
```
In case there is update for image redis:latest, I wanna pull that image and don't need to go through process of upgrade, like what command line `rancher-compose upgrade` does. 
I tried to use `rancher-compose pull cache`, but get error
```
Unknown schema type [pullTask] error
``` 
Check source code, it uses docker libcompose pull, does that mean it actually uses docker-compose to pull? While I tested `docker-compose pull`, it works perfect. 

rancher-compose version version v0.4.0
