### ISSUE TITLE
Project member cannot install catalog app that creates role/role binding

### ISSUE THREAD

**Issue by olivier-mauras** [rancher/rancher#21743]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
User is given the project member role. He tries to install a simple custom helm app from custom catalog.
App is setting up a service account and its binding in the namespace.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-integrator
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ci-integrator-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-integrator-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: ci-integrator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-integrator-manager
```

**Result:**
Failed to install app ci-integrator-sta. Error: release ci-integrator-sta failed: roles.rbac.authorization.k8s.io is forbidden: User "u-xxxx" cannot create roles.rbac.authorization.k8s.io in the namespace "xxx-sta"

What are the required permissions that I should add to the Project Member role to be able to do this? 

**Environment information**
- Rancher version: 2.2.5
