### ISSUE TITLE
Refactor Load Balancer code

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2179]
This ticket is to keep track of LB refactoring work that needs to be done.
- [x] Get rid of standalone Load Balancer code. Everything should be done from services perspective. 
- [x]  Implement a way of uploading custom haproxy config defined by the user (https://github.com/rancher/rancher/issues/2171, https://github.com/rancher/rancher/issues/1871)
- [x]  Change the way of compose representation for the LB service
- [x] Ability to add a selector with hostname routing rules for LB (https://github.com/rancher/rancher/issues/2288)
- [x] Allow to define custom parameters for haproxy backends
- [x] Move LB programming code from Cattle to its own microservice
- [x] SNI Routing support

@ibuildthecloud @will-chan

**Comment by ibuildthecloud** [comment]
+1

**Comment by silviupanaite** [comment]
+1

**Comment by cicerocomp** [comment]
[vulcand](http://vulcand.io/) in replacement to haproxy? :+1:

**Comment by kaos** [comment]
@alena1108 will you also upgrade HAproxy to :package: 1.6.x? (with [Lua support](http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/) built in?).

I don't have a use case right now, but it would be super cool if the load balancer could be scriptable, and with #2171 to also register/add lua scripts, sky's the limit as to what we could do.. :D

**Comment by alena1108** [comment]
@kaos sure, I don't see why not

**Comment by blaggacao** [comment]
I'd think of a UI DDOS protection:

  # DDOS protection
  # Use General Purpose Couter (gpc) 0 in SC1 as a global abuse counter
  # Monitors the number of request sent by an IP over a period of 10 seconds
  stick-table type ip size 1m expire 1m store gpc0,http_req_rate(10s),http_err_rate(10s)
  tcp-request connection track-sc1 src
  tcp-request connection reject if { sc1_get_gpc0 gt 0 }
  # Abuser means more than 100reqs/10s
  acl abuse sc1_http_req_rate(ft_web) ge 100
  acl flag_abuser sc1_inc_gpc0(ft_web)
  tcp-request content reject if abuse flag_abuser
stolen from: http://blog.haproxy.com/2012/10/12/scalable-waf-protection-with-haproxy-and-apache-with-modsecurity/

Would this be eligible for UI inclusion?

**Comment by cusspvz** [comment]
+1 for DDoS Protection (haproxy rate limit feature)

**Comment by alena1108** [comment]
For items 3-5 we would have to do refactor that would change the API/compose representation for LB and target services. @ibuildthecloud @vincent99 please point out if I've missed anything we've discussed.

Here is the example of old and new way of representing it (old way is still supported for backwards compatibility):

Old way:

```
lb:
  image: rancher/load-balancer-service
  # 1) listening rules are defined in "ports" section
  ports:
  - 80
  - 82:81
  - 9999/tcp
  links: 
  - web1:web1
  - web2:web2
  # 2) host name routing rules are defined as labels
  labels:
    io.rancher.loadbalancer.target.web1: app.example.com:80/foo=8000
    io.rancher.loadbalancer.target.web2: app.example.com/foo=8000,app.example.com/foo/bar=8001
    io.rancher.loadbalancer.target.web3: 82=8000
  # 3) certificates are global per load balancer, not per each listening port
certs:
    - foo
    - bar
    default_cert: foo
```

New way:

```
lb:
  image: rancher/load-balancer-service
  # 1) listening rules are defined in "listen_port" section and represented as objects
  listen_ports:
    - port: 80
      protocol:tcp (tls, http, https) - more protocols support, no defaulting
      # 1.1 certs can be defines on per listener now
      certs:
       - foo
      default_cert: foo
      # 1.2 you can define a custom parameters for this particular listening port
      haproxy_config: {}

  # 2) host name routing rules are defined as list of objects instead of being put to the labels
  routing_rules:
    - service_name: foo - the rule will apply to service foo 
      listen_port: 80 - the rule will get tied to listen_port 80
      target_port: 8080 - traffic for service foo will be forwarded to port 8080 of foo containers
      host_name: app.example.com - traffic coming to host app.example.com, will be forwarded to service foo
      path: /foo/bar - traffic coming to path /foo/bar, will be forwarded to service foo
   SNI: true/false - whether to use SNI routing # new feautre, more to research, most likely won't make it to v1 refactoring
      priority: 42 - rule order. Today Rancher determines the order based on hostname/path length, need to let user define it
      haproxy_config: {} custom config parameters for a backend
      app_cookie: cookie stickiness rules are defined on per target service basis, not globally
      lb_cookie: cookie stickiness rules are defined on per target service basis, not globally
```


I'm going to give a couple of examples here based on 2 major use cases.


Use case 1 - links from lb to target service are explicitly defined on lb service in docker compose. Every time you need to add an extra target to lb service, you would have to modify the lb service itself. Common use case when the same person manages lb and target services docker-compose.yml files.

docker-compose.yml

```
lb:
  image: rancher/load-balancer-service
  listen_ports:
    - port: 80
      protocol:http
  links: 
  - web1:web1
  - web2:web2
  routing_rules:
    - service_name: web1
      listen_port: 80
      target_port: 8080
      host_name: web1.example.com
    - service_name: web2
      listen_port: 80
      target_port: 8080
      host_name: web2.example.com

web1:
  image: nginx:latest
web2:
  image: nginx:latest
```

Use case 2 - services are joining lb using selectors. Person managing target service .yml, doesn't have access to lb service .yml. LB service .yml is managed by network administrator. The only thing user needs to know is - listener port of the LB he wants to join.


docker-compose.yml for lb service

```
lb:
  image: rancher/load-balancer-service
  listen_ports:
    - port: 80
      protocol:http
  selector: foo=bar
```

docker-compose.yml for web1 service
```
web1:
  image: nginx:latest
  routing_rules:
    - service_name: web1
      listen_port: 80 # listen port of the load balancer this service will be joining
      target_port: 8080
      host_name: web1.example.com
 labels:
    foo:bar # label matching lb service selector
```

docker-compose.yml for web2 service
```
web2:
  image: nginx:latest
  routing_rules:
    - service_name: web1
      listen_port: 80 # listen port of the load balancer this service will be joining
      target_port: 8080
      host_name: web2.example.com
 labels:
    foo:bar # label matching lb service selector
```

**Comment by kaos** [comment]
Nice @alena1108 ! :+1: 

A question though, shouldn't the `routing_rules`, and `listen_ports` go into the `rancher-compose` file?

I was under the impression that anything that doesn't work with `docker-compose` should go into `rancher-compose`.. ? (like `scale` does, for instance..)

**Comment by vincent99** [comment]
@kaos you can do that if you want to maintain a (somewhat) compatible docker-compose.yml.  But internally we just combine them together, so if you don't care it can all go in one file.

@alena1108 I don't remember talking about Certs per listener, and I'm not sure I really get the point.. With SNI the cert that matches the request will be picked anyway so it doesn't matter if you have just one array for the whole balancer.   Without it there can only really be one cert per listening IP+port, so maybe just the default_cert moves to the listener level?

**Comment by schuylr** [comment]
Thanks for following through, @alena1108 

How would we discern custom backend haproxyConfig from the server lines? For example, this is a feasible scenario:

```
backend xxx
    <haproxyConfig>
    server foo1 <inserted defaults> <haproxyConfig>
    server foo2 <inserted defaults> <haproxyConfig>
    server foo3 <inserted defaults> <haproxyConfig>
```

To be more specific, I need to add a `send-proxy` directive after each `server` line.

Would this be expanded in the custom parameters, like such?

```
routing_rules:
    - service_name: foo - the rule will apply to service foo 
      listen_port: 80 - the rule will get tied to listen_port 80
      target_port: 8080 - traffic for service foo will be forwarded to port 8080 of foo containers
      host_name: app.example.com - traffic coming to host app.example.com, will be forwarded to service foo
      path: /foo/bar - traffic coming to path /foo/bar, will be forwarded to service foo
   SNI: true/false - whether to use SNI routing # new feautre, more to research, most likely won't make it to v1 refactoring
      priority: 42 - rule order. Today Rancher determines the order based on hostname/path length, need to let user define it
      haproxy_config: {
        'server': 'send-proxy' # This would be auto-appended to every server line
      } custom config parameters for a backend
      app_cookie: cookie stickiness rules are defined on per target service basis, not globally
      lb_cookie: cookie stickiness rules are defined on per target service basis, not globally

**Comment by alena1108** [comment]
@vincent99 I do remember we were debating where to put the certificates...Lets leave this open to discussion as I will get more clear picture once I start working on SNI routing (which we didn't support before)


@schuylr parameters from custom haproxy config for the backend will be placed to the appropriate section of the backend: either as default for the entire backend (if supported), or to the server line. So yes, we would support your scenario.

**Comment by kaos** [comment]
@vincent99 thanks for that tidbit of info. :)

**Comment by DanielDent** [comment]
Some thoughts on re-factoring load balancing:

There are many cases where it would be nice to have services specify the load balancers they wish to be registered in, rather than the other way around.

Load balancer containers could be given tags. A service could specify which load balancing rules along with the tag(s) to which those rules could be added. External load balancers are often shared amongst many services, and updating the load balancer after creating a service is an unnecessary operational burden. Additionally, it creates issues like needing to re-configure the load balancer if a service is not currently running (external_links end up pointing to a service that doesn't exist, and as such the load balancer won't start).

I note is that right now it doesn't look like rancher has an elegant approach to having a new load balancer start before the old load balancer is removed. I get errors in the rancher UI about the port already being used if I add directives to my rancher-compose to start the new service before stopping the old one.

Another thing - it would be nice to be able to put services into a "draining" state. Currently there is "initializing, running, stopped" and a number of other states. I think that "draining" would be another state for a service to be in. In this state, no new requests would be sent to the service, it would be removed from service discovery/DNS, but it would remain available until stopped. Haproxy also has functionality which supports draining.

**Comment by blaggacao** [comment]
+1 for a better external entrypoint solution, as @DanielDent laid out.

**Comment by fernandoneto** [comment]
this could be interesting for this propose
https://github.com/kobolog/gorb

**Comment by blaggacao** [comment]
Indeed, here is the direkt link to the author's talk and his stance about IPVS: https://www.youtube.com/watch?v=oFsJVV1btDU&feature=youtu.be&list=PLkA60AVN3hh87OoVra6MHf2L4UR9xwJkv

At the end of the talk he mentiones his formula (https://youtu.be/oFsJVV1btDU?t=47m):
 - Overlay Network for internal communication
 - MacVLAN Network + IPVS Direct Routing (fastest) for exposing/load balancing services to the outer world.

I think those are the key points to possibly catch your interest.

**Comment by DanielDent** [comment]
IPVS would be a huge win. I'd actually been looking at implementing it ourselves outside of Rancher as a workaround to Rancher's current limitations - having it built into Rancher would be even better.

Haproxy just doesn't work for some of our use cases. For example, we have machines which have multiple IP addresses and run different DNS daemons on different IP addresses.

Haproxy can't load balance UDP/53. And rancher ends up wanting to bind all of the machine's IP addresses. Right now huge kludges are required.

An IPVS approach - especially if there was some flexibility in choosing which IP addresses get selected (allowing operators to specify usable CIDR ranges would be a very interesting approach - it would also avoid the need for system-specific host labels in some cases) would be a huge win.

**Comment by raphink** [comment]
Does the new syntax cover passing frontend/backend config? I'd need backend config for basic auth support, and frontend config for http->https redirect? None of these can be done in defaults or globals.

**Comment by sshipway** [comment]
+1 for custom frontend/backend config, as this would allow us to add ACLs for IP restrictions and basic authentication, something our users need

**Comment by gjongenelen** [comment]
I'm also looking for a solution like @schuylr. Would be great to define a custom server configuration in the backend. (In my case also 'send-proxy') 
So: +1

**Comment by Rucknar** [comment]
@vincent99 SNI isn't supported by a lot of java deployments on user machines. We run a few web services with clients that don't support SNI. Separate end-points would help this.

**Comment by vincent99** [comment]
@Rucknar you'd need a separate public IP for every service then, which is more than just being able to add text to the config.  For example 2 internal listeners would need the containers to have 2 10.42 IPs.

I know everyone seems to like one-balancer-to-rule-them-all but this is really much less confusing as separate balancers listening on separate IPs (which still requires #53).

**Comment by Rucknar** [comment]
Fair point!

**Comment by bkuhl** [comment]
:+1: for frontend for the purpose of forcing https

**Comment by taketnoi** [comment]
+1

**Comment by cusspvz** [comment]
@taketnoi Github has now reactions on comments to avoid `+1` kind of comments, please rate the comment/original post you're manifesting interest in.

**Comment by taketnoi** [comment]
@cusspvz I have reacted on original post. Thanks you

**Comment by yobasystems** [comment]
Config options for getting A+ on [Qualys SSL test](https://www.ssllabs.com/ssltest/)

The key things are;
- Strict-Transport-Security 
- Content-Security-Policy
- Public-Key-Pins
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options

Another useful website [securityheaders.io](https://securityheaders.io)

**Comment by rogerwelin** [comment]
+1. This would be a killer feature

**Comment by schuylr** [comment]
Just commenting since I haven't had time to see if I can do all this stuff myself, but this is the *only* thing that's preventing us from switching entirely to Rancher. Our web apps need proxy protocol and without the custom haproxy config it's a no-go for us. Amazon ECS is getting increasingly buggy so the sooner this happens the better!

**Comment by hwinkel** [comment]
+1

**Comment by hwinkel** [comment]
is there any idea to expand loadbalancing/routing capabilities to UDP protocols? Or have custom router acting in the role of a rancher loadbalancer. I.e. we use nginx to route different requests to different services based on special rules. Or use latests nginx acting as UDP balancer.

**Comment by AnalogJ** [comment]
Is there an eta on when items 3-5 will be implemented? 
I'm specifically looking for item 3: Ability to add a selector with hostname routing rules for LB (#2288) 
which I noticed was closed and referenced here. 

The lack of L7 dynamic LB routing based on a selector is an issue for us.

**Comment by weitzj** [comment]
This is also holding me back, since I need level 4 load balancing using SNI.
Is there any workaround right now to manually edit the haproxy.cfg?

**Comment by Dids** [comment]
So does this (or doesn't this) support the stats page?

**Comment by weitzj** [comment]
Right now it does not because you can only override the `default` and `global` but not add the `stats` frontend

**Comment by jbrockett** [comment]
If you want a  front-end you could try traefik.  It doesn't support ssl yet though. http://rancher.com/traefik-active-load-balancer-on-rancher/

**Comment by weitzj** [comment]
But traefic only does HTTP. So the current Haproxy is fine for HTTP.
I need TCP.

But the traefic Docker files look interesting and show building blocks how one could implement the same using Haproxy or nginx

**Comment by wzrdtales** [comment]
Also interested in item 3 to 5, as currently http/2 support is not really possible with haproxy.

Are there plans to support for example also nginx, traefik and others beside of haproxy? Or is there at least a way planned that allows reconfiguring an nginx container without actually restarting the whole container but making use of nginx ability to reload the config without a downtime?

**Comment by alena1108** [comment]
@wzrdtales 

> Are there plans to support for example also nginx, traefik and others beside of haproxy? 

I am going to work on moving out LB specific code to its own microservice (most likely to this repo https://github.com/rancher/ingress-controller). The repo will get renamed to lb-controller, and will provide a common interface for configuring the lb provider of your choice, as well as an lb controller. 
Today's defaults are controller=kubernetes provider=Rancher - to provide rancher support for k8s ingress. I am going to extend it by adding support for controller=Rancher and provider=haproxy. The controller=Rancher will read from rancher metadata, form the lb config, and pass it down to provider=haproxy. The providers list can be extended to nginx/traefik in the future.

**Comment by mrproper** [comment]
Im a little late to the party on this one but i've started a dynamic backend haproxy load balancer image which uses the rancher-metadata to dynamically route http host headers to a stack name, eg. $stack_name.$domain -> $stack_name/app
Its obviously still in development but is working: https://hub.docker.com/r/nodeintegration/rancher-haproxy/

**Comment by raphink** [comment]
@mrproper Nice. Can it access certificates though?

**Comment by mrproper** [comment]
@raphink Could easily just add certificates via metadata or volume mounted. But im trying to work out how the rancher lb gets certs and replicate it that way

**Comment by raphink** [comment]
@mrproper I don't think that's currently possible, that's the problem.

**Comment by mrproper** [comment]
@raphink cert support has been added now via metadata

**Comment by raphink** [comment]
Ah cool. In which version of Rancher?

**Comment by raphink** [comment]
@mrproper Btw, your haproxy project looks interesting, but have you considered using confd for it?

**Comment by mrproper** [comment]
@raphink i've cleaned up the tags, use 0.3/latest
Yep i have considered confd/consul, i thought with this current method it has no extra dependencies other than rancher. I might look at a confd/consul alternate backend which then doesnt require the metadata service

**Comment by raphink** [comment]
confd can make use of rancher's metadata service

**Comment by blaggacao** [comment]
@raphink @mrproper have you thought in joining @alena1108 in some way? She states:
> I am going to extend it by adding support for controller=Rancher and provider=haproxy. The controller=Rancher will read from rancher metadata, form the lb config, and pass it down to provider=haproxy. The providers list can be extended to nginx/traefik in the future.

See also the commits on: https://github.com/rancher/lb-controller/pull/15

**Comment by mrproper** [comment]
@blaggacao happy to help working out the provider side of things with @alena1108.
It would be handy to get a POC to play with.

**Comment by johnculviner** [comment]
Not sure if this is included but I'd think it might be cool to expose the template (not a static custom config as is currently implemented) to "us" if we want to do some things manually. In that way we could loop over "hard stuff" (aka the rancher managed network IPs for containers etc.) and effectively would allow people to very easily do completely custom haproxy configurations.

Overall something like that would probably reduce the work you guys have to do to support "every last wacky situation" people want to come up with and also make everyone happy in the process cause they can do whatever they want.

**Comment by vincent99** [comment]
@johnculviner We're taking the approach of merging a complete config file you provide with the templatized default config that we manage.  You will be able to override anything, but going the other way and you providing a templatized config leaves us no way for us to make changes to it on existing balancers between versions.

**Comment by johnculviner** [comment]
That makes sense. It might not be a bad idea to expose the full template as well for the advanced scenario to allow full customization (but ability to use the special sauce: the rancher managed variables) but you maybe click a check box that says:

[X] I realize rancher might make API changes to the template model and stuff might break if I upgrade

Thanks for the info!

**Comment by blaggacao** [comment]
>You will be able to override anything
@johnculviner I think you missunderstood @vincent99 's answer.

**Comment by johnculviner** [comment]
Ahh, perfect. Music to my ears!

**Comment by alena1108** [comment]
Update on the refactoring work. I've covered the first round which includes:

* moving lb code to the microservice
* defined new APIs
* made all existing functionality works using new APIs
* custom config support for frontends/backends


What is left to be covered:

* target services joining LB service via selectors
* SNI routing 
* haproxy audit logs exposure
* haproxy stats support


New APIs (docker-compose/rancher-compose representation):

```
lb_svc:
   image: rancher/lb-controller-haproxy:v0.1.0 // defined in docker-compose, lb controller image
   ports: // defined in docker-compose, ports that are going to be published to the host
    - 80
    - 443
   certs: ['foo', 'bar'] // this param and the params below are defined in rancher-compose
   default_cert: 'baz'
   config: "<custom config data>"
   stickiness_policy: <sticky policy> // this would be a generic policy applied to every http backend. If custom policy is needed per backend, it can be specified via custom config
   port_rules:
      - hostname: foo
        path: /bar
        sourcePort: 80
        priority: 0
        protocol: https
        service: mystack/foo // service is declared explicitly
        target_port: 80
        backend_name: foo

      - hostname: foo
        sourcePort: 443
        priority: 2
        protocol: sni // sni based rouing will be enabled
        service: mystack/foo
        target_port: 443

     -  hostname: foo1
        sourcePort: 443
        priority: 3
        protocol: https // ssl offload will be enabled
        service: mystack/foo
        target_port: 80

    -   sourcePort 90
        protocol: http
        targetPort: 80
        service: default/foo // no hostname routing rules, meaning that the default/foo backend will be the default one

      - sourcePort: 80
        protocol: http
        selector: web=true // services having label satisfying the selector, will join this port rule
```

Below is the example of the service that would join the LB via selector; the service will carry target port / host name routing rules information
 
```
baz:
    labels: // docker-compose
        web: true
    image: nginx // docker-compose
    port_rules: // rancher-compose
        hostname: baz.com
        target_port: 80
        path: /baz
                .....
```



Haproxy custom config. Defined on per LB basis in a format like:

```
global  // global section
        maxconn 4096 // defaults custom params
        maxpipes 1024

defaults // defaults section
    log global // defaults custom params
    mode    tcp
    option  tcplog


frontend 80 // frontend's name 80= sourcePort of portRule
    balance leastconn // frontend custom params

frontend 90 // frontend's name 90 = sourcePort of portRule
    balance roundrobin // frontend custom params

backend my_backend // backend's name my_backend = backendName of portRule
    cookie my_cookie insert indirect nocache postonly // backend custom params
    server $ip <params> // server section custom params, defined in one line with "server $ip" = server custom params directive

```

All the custom parameters will be merged with the default/service generated parameters of haproxy. All custom params appear BEFORE default/service generated parameters in the config. Example of the frontend section:

```
frontend 100
balance leastconn // custom params
bind *:100 // service's generated params - this line and below
mode http
acl 100_foo_com_bar_host hdr(host) -i foo.com
acl 100_foo_com_bar_host hdr(host) -i foo.com:100
acl 100_foo_com_bar_path path_beg -i /bar
use_backend my_backend if 100_foo_com_bar_host 100_foo_com_bar_path
```
