### ISSUE TITLE
Service HA not working as expected

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2194]
Following on from #1877 we've agreed to split this out into a separate ticket.

I'm currently exploring non functional testing on a POC environment we have stood up using rancher.
We have two physical hosts running rancheros and were running rancher on a seperate third VM running on another host with full network connectivity between the two.

I've done a simple test to force power off one of the hosts rancher is managing, this however has highlighted a few issues. I've had a search on the issues list but couldn't find much covering them.

***Expected Outcome:***
I expected the host to be marked offline and i expected the services to maintain their scale by spinning up containers on other available hosts.

***Actual Outcome:***
Rancher detected the failure very quickly and marked the host in red with a message of 'reconnecting'.
However:

Services didn't attempt to maintain scale across other hosts, no new containers were spun up.
Applications view and infrastructure view still view the containers with a hollow green circle suggesting they are running fine.

I've been told that we should actually be seeing containers restart on other hosts, i'm wondering if there is something wrong with our configuration. All of our containers have health checks on the container and at the loadbalancer level. Example below, some config

docker compose
```
Audit:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
  tty: true
  image: registry:5000/aud:65
  stdin_open: true
  volumes:
    - /home/rancher/env_config/rt/tomcat/catalina.sh:/usr/share/secure_tomcat/bin/catalina.sh
    - /home/rancher/gluster:/mnt/gluster
    - /home/rancher/env_config/rt:/home/***_user/***
  links:
    - IAM-Database:***
    - LB-***:LB-***
    - LB-***:LB-***
```
rancher compose
```
Audit:
  scale: 2
  health_check:
    port: 8080
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /auditloggerws/?lbchk=1 HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
```

Following on from the initial test, i've done the same but on a simple reproducible stack.

I've done a re-test with a simple web app & loadbalancer running across two physical hosts. I've terminated one physical host (hard power off) and the application hasn't responded to restore scale.

docker-config.yml
```
WebsiteLB:
  restart: always
  ports:
  - 80:80
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - WebServiceV1:WebServiceV1
  stdin_open: true
WebServiceV1:
  restart: always
  labels:
    io.rancher.container.hostname_override: container_name
  tty: true
  image: tutum/hello-world
  stdin_open: true
```
rancher-config.yaml
```
WebsiteLB:
  scale: 1
  load_balancer_config:
    description: Loadbalancer for website testing.
    name: WebsiteLB config
WebServiceV1:
  scale: 12
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
```
Here is the host showing as offline.
<img width="327" alt="78c6e18c-629f-11e5-81ea-3bafb452b6b3" src="https://cloud.githubusercontent.com/assets/5539660/10202097/2490dba6-67a7-11e5-8459-a96dae0af136.png">

Here is the app, impossible to tell anything is wrong and it hasn't restored the services elsewhere.
<img width="844" alt="7f9c36ec-629f-11e5-8fa8-6b7d67c2ded4" src="https://cloud.githubusercontent.com/assets/5539660/10202108/2d71e40e-67a7-11e5-8649-f136dc23a2a5.png">

What process health checks these containers? Is it on the host they run on? If so, i fail to see how they would spot a host being forced off? What can i do next to trouble shoot this issue?

Of note, i've tested breaking one of the containers by removing it's war file, rancher detected this, killed the container and started another so i know health checking is working fine.
