### ISSUE TITLE
Exporting/viewing stack configuration replaces "expose" with "ports"

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#2198]
```
Rancher	v0.39.0
Cattle	v0.95.0
User Interface	v0.52.0
Rancher Compose	beta/latest
```

Here is the YAML file I'm using to create a stack:

```
test:
  restart: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
  expose:
  - 3000/tcp
```

And here is the YAML file I'm getting when I'm trying to export/view stack:

```
test:
  restart: always
  ports:
  - 3000/tcp
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```

As you can see, "expose" part has been replaced with "ports", which is a huge deal as importing/creating a stack 2nd time might lead to port conflicts and difficult to debug issue i.e. load balancer not being created and staying in "activating" mode forever, etc.

**Comment by alena1108** [comment]
Looks like a rancher-compose issue - "ports" is being sent in the request instead of "expose":

```
{
    "scale": 1,
    "launchConfig": {
        "imageUuid": "docker:ubuntu:14.04.3",
        "logConfig": {},
        "networkMode": "managed",
        "ports": [
            "3000/tcp"
        ],
        "restartPolicy": {
            "name": "always"
        },
        "stdinOpen": true,
        "tty": true,
        "privileged": false,
        "publishAllPorts": false,
        "readOnly": false,
        "startOnCreate": true
    }
}
```

**Comment by ibuildthecloud** [comment]
@alena1108 @xaka I'm fixing this now in rancher-compose but just want to point out that we don't actually support expose.  So passing anything in the `expose` field is basically ignored by Rancher.

**Comment by sangeethah** [comment]
Tested with rancher-compose version - rancher-compose-v0.4.1-rc2 and rancher-server built from master on oct 8.

When expose is used in docker-compose.yml  , rancher-compose will ignore this. 

docker-compose.yml  used to create the service:
```
testexpose:
  restart: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
  expose:
  - 3000/tcp
```
expose gets ignored now and no ports will be exposed.

generated config ( from rancher-server)

```
testexpose:
  restart: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```

To expose ports from rancher-compose , we should use  ports , example:
ports:
  - 8999:80/tcp
