### ISSUE TITLE
[cli] `--values` flag failing with object keys containing dots

### ISSUE THREAD

**Issue by dreglad** [rancher/rancher#22027]
Rancher CLI `app` command fails installing or upgrading a release if passing a `values.yml` or `answers.yml` file containing dots in object key names (i.e. Ingress annotations)

I'd expect that any `values.yml` that is valid for a helm chart is also valid for the `--values` CLI's flag

This is similar to  https://github.com/rancher/rancher/issues/19042 but from the CLI instead of within the Rancher UI

**What kind of request is this**

Bug

**Steps to reproduce**

```yaml
# values.yml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
```

Install with Rancher CLI:
`rancher app install --values values.yml my_template`

**Result:**

Gets the following values:

```yaml
ingress: 
    annotations: 
      kubernetes: 
        io/ingress: 
          class: "nginx"
        io/tls-acme: "true"
```

**Environment information**
- Tested with Rancher CLI  v2.2.0  / v2.3.0-rc2  / master
