### ISSUE TITLE
Rancher Not Support local volume 

### ISSUE THREAD

**Issue by liyongxian** [rancher/rancher#22061]
**What kind of request is this (question/bug/enhancement/feature request):**
**Rancher does not support local volume.** 

**Steps to reproduce (least amount of steps as possible):**
In Kubernetes 1.14,local volume is GA.When I test the local volume in k8s managed by rancher(v2.2.7),It is wrong.

**Result:**
The Pod status:
example-pod   0/1     ContainerCreating   0          17m
The Pod Description info:
![volume](https://user-images.githubusercontent.com/18571576/62687866-2f6ac600-b9fa-11e9-9c28-f92a0ccf3f77.jpg)

**path "/data/local/vol1" does not exist**,but the path exists.
![2222](https://user-images.githubusercontent.com/18571576/62688006-7eb0f680-b9fa-11e9-8af7-c5924708215c.jpg)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
(paste the output here)
```
**single install**
**manager-1   Ready    controlplane,etcd   72m   v1.15.2**

- Docker version (use `docker version`):
Docker info:
Containers: 37
 Running: 24
 Paused: 0
 Stopped: 13
Images: 20
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 178
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-151-generic
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: manager-1
ID: VHWJ:OLRB:FF4W:Y2X4:4AIY:EN4N:U6UA:KYN3:E5C2:CGJM:G4KU:4QLX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://****.mirror.aliyuncs.com
Live Restore Enabled: false

```
(paste the output here)
```
Thanks.

**Comment by loganhz** [comment]
Please provide the yaml you used for creating the PV

**Comment by MingJunDuan** [comment]
I have the problem, rancher version is 2.2.8, k8s version is 1.14.6.

**Comment by yasker** [comment]
RKE doesn't support directory on the node to be used as a local volume. The reason seems due to it's containerized.

Reproduce steps:
1. Create directory `/opt/testlocalpv` on one of your RKE nodes, e.g. `node-1`
2. Use the following yaml to test the local volume (make sure to change the node affinity for the pv to mapping to your node):

Example yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rke-localpv-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-pv
  local:
    path: /opt/testlocalpv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rke-localpv-pvc
  namespace: default
spec:
  storageClassName: local-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: rke-localpv-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: test-localpv-pod
  namespace: default
spec:
  containers:
  - name: test-localpv
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: rke-localpv-pvc
```

Result:
1. The pod cannot be started with RKE
2. The same yaml and configuration works with K3s.

**Comment by damoon** [comment]
is someone working on this?

**Comment by varac** [comment]
Any updates ? Looking forward to use local volumes for velero (https://github.com/rancher/local-path-provisioner/issues/85).

**Comment by benosman** [comment]
> RKE doesn't support directory on the node to be used as a local volume. The reason seems due to it's containerized.
> 

I also found my way here as I want to use local-path with velero backups.

I have got the local volumes working in rancher / rke as per the manifest posted by @yasker, but I did have to create extra_binds in the cluster config yaml. 

https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-binds

```yaml
services:
  kubelet:
    extra_binds:
     - "/opt/testlocalpv:/opt/testlocalpv"
```

It would be helpful if the extra bind mounts could be set via the cluster form as well as the yaml, perhaps as local-path-provisioner is also a rancher product, there could be a specific option for the default path.
