### ISSUE TITLE
S3 backup config dict name in Rancher does not match the RKE docs

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#22073]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Right now, when configuring s3 backups on custom clusters in Rancher the dictionary name is `s3_backup_config`. However, in the RKE docs it's `s3backupconfig`.

This causes confusion when trying to configure S3 backups via yaml in the Rancher UI. The one in the Rancher should be changed to match RKE (`s3backupconfig`).

In Rancher:

```
      s3_backup_config: 
        access_key: "test"
        bucket_name: "test"
        endpoint: "test.com"
```

In cluster.yml for RKE cli:

```
      s3backupconfig: 
        access_key: "test"
        bucket_name: "test"
        endpoint: "test.com"
```
