### ISSUE TITLE
Ability to specify custom ServiceAccount for Pipeline run

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#22123]
**What kind of request is this (question/bug/enhancement/feature request):**

Feature request

**Steps to reproduce (least amount of steps as possible):**

The user would like the ability to create cluster level resources in the Deploy Catalog App step of a Rancher Pipeline, i.e. to create a ServiceAccount, RoleBindings and ClusterRoleBindings where these are required for an application.

As the ServiceAccount used by the Pipeline is restricted, to be Project scoped, this is not possible to create RoleBindings and ClusterRoleBindings for example.

User would therefore like ability to specify a custom ServiceAccount to be used by Pipeline run so they can customize the RBAC permissions.

User would need to acknowledge this comes with a risk that they create a Pipeline to use a ServiceAccount with admin level permissions, another user who can commit to the source repo and trigger a Pipeline run, could then make non-Project scoped changes, i.e. grant themselves admin ClusterRoleBinding.

**Environment information**
- Rancher v2.2.6

**Comment by gitlawr** [comment]
Under the hood, the deploy app step is done by cli talking to Rancher server using a project scope system account. It can be overriden if users want to grant more permissions for deploying the app.

To do that in short, generate an API key with desired permissions and pass it as the `API_TOKEN` env to the deploy-app container.

1. API keys are bound to users(Click user icon and go to the `API & Key` page to manage them). You may want to have the key from a dedicated user account for CI automation.
2. Use secrets to Inject the key. For example, create a secret in pipeline dedicated namespace, and reference it in the pipeline file:
```
stages:
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-grafana
      version: 0.0.31
      name: graf
      targetNamespace: default
    envFrom:
    - sourceName: some-secret-name
      sourceKey: some-key-name
      targetKey: API_TOKEN
```
3. Note that the API key will be accessible by every member of the project that can read secrets.

**Comment by stekole** [comment]
This is just what I wanted thank you very much for the quick and accurate response @gitlawr 

Is this documented anywhere? I keep seeing a lot of neat secret bits within the pipeline, but I do not see documentation on all the extra env vars which you can put in the different stages. 

Thanks again

**Comment by Raboo** [comment]
Hi,

I tried this with a YAML deployment. It didn't work, perhaps it only works for Catalog Apps?
I'm trying to allow the deployment/pipeline to create a namespace.

```
stages:
- name: Deploy Cert Manager
  steps:
  - applyYamlConfig:
      path: deployments/cert-manager.yml
    envFrom:
    - sourceName: elevated-pipeline-api-key
      sourceKey: API_TOKEN
      targetKey: API_TOKEN
timeout: 60
notification: {}
```

the API_TOKEN is in the format `token-xxx:yyy`

I'm trying to create namespace using YAML like this:
```
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    field.cattle.io/projectId: c-gv2bl:p-5dzht
```

Any ideas?
