### ISSUE TITLE
Azure LoadBalancer not working when using more than 1 node cluster

### ISSUE THREAD

**Issue by ajfriesen** [rancher/rancher#22147]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Deploy new cluster on azure via azure vms and deploy this deamonset to the cluster:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: deamon-set-lb
spec:
  template:
    metadata:
      labels:
        app: deamon-set-lb
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: deamon-set-lb
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deamon-set-lb
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: deamon-set-lb
  type: LoadBalancer
```

**Result:**

Depending on how many nodes you have traffic will be served or not.
When we only have 1 node cluster we always can connect via telnet and see the default nginx site.

When we have more than one node it will fail sometimes.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.5

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS VM
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Standard D4s v3 (4 vcpus, 16 GiB memory)
- Kubernetes version (use `kubectl version`): 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
sudo docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:21:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd
  Built:            Wed Jul 17 17:07:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

The loadbalancer gets created sucessfully in azure. It also get a public IP.
Security groups and networking is working since when we have 1 node only it will work properly.

My understanding is that the loadbalancer will forward the traffic to all healthy targets in the backend pool.
The backend pool consists of all kubernetes nodes.
You also can see that all nodes listen on the particular nodeport.
For example:

```
sudo lsof | grep 30823
kube-prox  7902                   root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7940             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7941             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7942             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7943             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7944             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7945             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7946             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7947             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7951             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7965             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  7975             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)
kube-prox  7902  8197             root    8u     IPv6              67653       0t0        TCP *:30823 (LISTEN)

```

As soon we add another node it will not work anymore, even if the node is listening on that port as well.

Did I forget to configure something in kube proxy?
In AWS we do not have any problem with that cluster setup, only with azure.
