### ISSUE TITLE
Nexus not accessible through published port

### ISSUE THREAD

**Issue by fabienfleureau** [rancher/rancher#2216]
Hi,
I created a stack with the following configuration: (yml)
```
nexus:
  image: sonatype/nexus
  ports:
    - "9090:8081"
  environment:
    - MAX_HEAP=768m
  volumes:
    - /data/docker/volumes/nexus:/sonatype-work
```
I can't access the service through http://host_ip:9090/ but it is accessible through http://container_ip:8081/
Also, this yml configuration is ok with docker-compose.
