### ISSUE TITLE
Changing Node Scheduling breaks if nodeSelector already exists

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#22207]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Spin up two node v1.14.5 cluster with cp/worker/etcd roles. Label one node with "foxtrot=true" and the other node with "whiskey=true"
2. Use Import YAML to launch a daemonset:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: mydstest
  namespace: default
  labels:
    k8s-app: mydstest
spec:
  selector:
    matchLabels:
      app: mydstest
  template:
    metadata:
      labels:
        app: mydstest
    spec:
      nodeSelector:
        foxtrot: "true"
      containers:
      - image: ubuntu:xenial
        imagePullPolicy: Always
        name: mydstest
        stdin: true
        tty: true
```
Note, pod launches on the node that was labelled foxtrot=true
3. Edit the daemonset, expand the Node Scheduling section. Under "Require ALL of", change foxtrot=true to whiskey=true, click Upgrade.

**Result:**
After step 3, expectation is the pod would be removed from the node labeled foxtrot=true and scheduled to node labeled whiskey=true. However, no pods are running. If you view the YAML for the daemonset, you can see both the old nodeSelector and new affininity rules are present:
```yaml
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"mydstest"},"name":"mydstest","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"mydstest"}},"template":{"metadata":{"labels":{"app":"mydstest"}},"spec":{"containers":[{"image":"ubuntu:xenial","imagePullPolicy":"Always","name":"mydstest","stdin":true,"tty":true}],"nodeSelector":{"foxtrot":"true"}}}}}'
  creationTimestamp: "2019-08-15T20:33:12Z"
  generation: 2
  labels:
    k8s-app: mydstest
  name: mydstest
  namespace: default
  resourceVersion: "4976"
  selfLink: /apis/apps/v1beta2/namespaces/default/daemonsets/mydstest
  uid: e6e33173-bf9b-11e9-8b72-0a1204fabfce
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mydstest
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-08-15T20:35:44Z"
      creationTimestamp: null
      labels:
        app: mydstest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: whiskey
                operator: In
                values:
                - "true"
      containers:
      - image: ubuntu:xenial
        imagePullPolicy: Always
        name: mydstest
        resources: {}
        securityContext:
          capabilities: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        foxtrot: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 2
```
The nodeSelector should have been removed. If removed manually, then daemonset works correctly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.7
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3a.medium in AWS EC2
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        0dd43dd87f
 Built:             Wed Jul 17 17:38:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       0dd43dd87f
  Built:            Wed Jul 17 17:48:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by tfiduccia** [comment]
@dnoland1 - The UI doesn't recognize nodeSelector as that is being deprecated and node affinity can express everything.  You can Edit the yaml of your daemon set and remove the nodeSelector section and a new pod will be created.  In future please use:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foxtrot
                operator: In
                values:
                - "true"
```

**Comment by vincent99** [comment]
If the UI is going to convert from nodeSelector -> nodeAffinity then it should cleanup the nodeSelector when it's doing it.

**Comment by codyrancher** [comment]
@vincent99 would you mind pointing me in a general direction for this one? The only mapping I found for affinity was related to persistent volumes.

**Comment by vincent99** [comment]
Kubernetes has 2 different ways to declare which nodes you want the pod to be scheduled to.  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core

pod spec -> `nodeSelector` is the older way and is a map of label key/values and only the nodes that match those labels are eligible to run this workload.

pod spec -> `affinity` -> `nodeAffinity` is a newer and more powerful way that can express more complicated conditions (plus what you could do before with `nodeSelector`).

So the UI only supports editing the newer `nodeAffinity`, but it does read the older `nodeSelector` and convert that into `nodeAffinity` rules.  The problem is that it doesn't delete the old `nodeSelector` after doing that, so you end up with BOTH sets of rules which must both be satisfied, and there might not be any nodes that satisfy both so the pod can't run anywhere.  

So the UI needs to delete the old field after converting (by setting it to null in the model so it gets posted back)

**Comment by codyrancher** [comment]
@vincent99 I'm having a heck of a time finding where the conversion occurs. I'm actually beginning to think that this is a backend issue. If you know where it's happening on the UI can you point me to where?

I don't think it's happening when it gets imported because we send the backend verbatim what was entered.

When we save changes to the daemonset there's no reference to affinity there's just a section under scheduling that looks like:
`    
"scheduling": {
        "node": {
            "nodeId": null,
            "requireAll": [
                "whiskey = true"
            ]
        },
        "scheduler": "default-scheduler"
    },
`

That's the only reference to my 'whiskey' change and the only reference to 'foxtrot' is under workloadAnnotations."kubectl.kubernetes.io/last-applied-configuration" 
`
"workloadAnnotations": {
        "deprecated.daemonset.template.generation": "1",
        "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"DaemonSet\",\"metadata\":{\"annotations\":{},\"labels\":{\"k8s-app\":\"mydstest\"},\"name\":\"mydstest\",\"namespace\":\"default\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"mydstest\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"mydstest\"}},\"spec\":{\"containers\":[{\"image\":\"ubuntu:xenial\",\"imagePullPolicy\":\"Always\",\"name\":\"mydstest\",\"stdin\":true,\"tty\":true}],\"nodeSelector\":{\"foxtrot\":\"true\"}}}}}\n"
    },
`
which appears to be the original yaml import.

**Comment by vincent99** [comment]
You are correct @codyrancher, apologies for the wild goose chase.

https://github.com/rancher/types/blob/5c4cd002e862b48c814b81acb55adaaac0c3c001/mapper/scheduling.go#L23-L55

The API reads both native k8s fields and produces a unified `scheduling` field in the output JSON, which is what the UI actually manipulates.  On edit the UI is sending back the desired scheduling object:

```json
"scheduling":{
  "node":{
    "nodeId":null,
    "requireAll":[
      "foxtrot = true",
      "whiskey = true"
    ]
  },
```

And that gets mapped back to the correct nodeAffinity spec:

```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foxtrot
                operator: In
                values:
                - "true"
              - key: whiskey
                operator: In
                values:
                - "true"
```

But fails to clear out the old

```yaml
      nodeSelector:
        foxtrot: "true"
```
