### ISSUE TITLE
Rancher generated kubeconfig has same user id but different token

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#22579]
Currently running Rancher 2.2.8 and using the kubeconfig generated by it, I am able to individually authenticate to the respective clusters via kubectl. However, I want to merge the kubeconfig so I can use `kubectl config use-context`. In attempt to merge the kubeconfig, I encountered issue where the latter clusters could not be authenticated into.

```
> kubectl get nodes
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

Looking deeper into the merged kubeconfig, the problem appears to be that the user id used is shared for all clusters, however the authentication token is different for each. The resultant kubeconfig only keeps the token of the user for the first cluster, since it's all the same id.

```
...
current-context: my-cluster1
kind: Config
preferences: {}
users:
- name: user-d5dvk
  user:
    token: kubeconfig-user-d5dvk.c-6x2sn:sfs7fkdj5d89gbx8p9jsnf8jxlx8ljwdw8r2rwmsp444hq7qx7dsv8
```
