### ISSUE TITLE
On rancher upgrade from 2.2.8 to master-head, the ingress controller pods are deployed on etcd and control plane nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22570]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On rancher v 2.2.8, deploy a cluster - 3 worker, 1 control plane, 1 etcd node - linux nodes.
- Upgrade rancher to master-head - latest
- Edit node template, add a taint - NoExecute
- Scale up the worker node.
- `"taintSupport": true` will be seen on cluster --> View in API

**Expected Result:**
Ingress Controller should be deployed on the worker node only.

**Actual Result**
Ingress Controller pods are deployed on all nodes including control plane and etcd nodes.
The bellow Affinity is missing on the workload.
```
map[key:node-role.kubernetes.io/worker operator:Exists]
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8 to master-head
- Installation option (single install/HA): single

**Comment by sowmyav27** [comment]
Verified on an upgrade from v2.2.8 to master-head latest..
**Steps:**
On rancher v 2.2.8, deploy a cluster - 1 worker, 1 control plane, 1 etcd node - linux nodes.
Upgrade rancher to master-head - latest
Scale up the worker node.

**result:**
Ingress Controller pods are deployed on worker nodes. But the bellow Affinity is missing on the workload.
```
map[key:node-role.kubernetes.io/worker operator:Exists]
```
Hence reopening the issue.

**Comment by sowmyav27** [comment]
The ingress controller is scheduling on worker nodes because it is missing Tolerations
```
- Tolerations: [map[effect:NoExecute operator:Exists] map[effect:NoSchedule operator:Exists]]
```

**Comment by sowmyav27** [comment]
Verified on an upgrade from v2.2.8 to master-head latest.
**Steps:**

- On rancher v 2.2.8, deploy a cluster - 1 worker, 1 control plane, 1 etcd node - linux nodes.
- Upgrade rancher to master-head - latest
- Edit cluster, change the k8s version. Save.
- Go to System-->Ingress controller --> Edit yaml.

**Tolerations:**
```
"tolerations":[{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}]}}}}
```

**Affinity:**
```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: NotIn
                values:
                - windows
              - key: node-role.kubernetes.io/worker
                operator: Exists
```
