### ISSUE TITLE
Rancher UI failing to provision Authorized Cluster Endpoint on RKE created cluster.

### ISSUE THREAD

**Issue by skektek** [rancher/rancher#22604]
On an RKE created cluster (HA or otherwise) the Rancher UI is not picking up even basic provisioning information such as cluster_name and etcd snapshot settings. Additionally the Authorized Cluster Endpoint is not enabled.

---
| Useful | Info |
| :-- | :-- |
|RKE|`0.2.8`|
|Certificate Manager|`0.5.2`|
|Kubectl|`1.15.3`|
|Helm|`2.14.3`|
|Docker|`docker-ce-18.09.8-3.el7`|
|Rancher|`v2.2.8`| 
|User Interface|`v2.2.94`|
|Helm|`v2.10.0-rancher11`|
|Machine|`v0.15.0-rancher8-1`|

**Comment by tfiduccia** [comment]
@skektek - I cannot reproduce your issue on 2.2.8.  Where is your rancher cluster & what type of RKE cluster are you trying to create.

**Comment by skektek** [comment]
Hello @tfiduccia 
Thanks for your response.

My Rancher cluster nodes are VMs (CentOS 7.6.1810) on vSphere. I am building a HA RKE cluster.

rancher-cluster.yml
```
nodes:
  - address: XXX.XXX.XXX.1
    user: dockeruser
    role: [controlplane,worker,etcd]
  - address: XXX.XXX.XXX.2
    user: dockeruser
    role: [controlplane,worker,etcd]
  - address: XXX.XXX.XXX.3
    user: dockeruser
    role: [controlplane,worker,etcd]
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
cluster_name: testcluster
```

1. Setup Docker repo.
2. **root# yum install docker docker-ce-18.09.8-3.el7**
3. **root# groupadd docker**
4. **root# useradd dockeruser**
5. **root# usermod -aG docker dockeruser** (I've also tried the CentOS packaged Docker 1.13 with dockerroot. It did not make any difference with this issue.)
7. Setup Kubernetes repo.
8. **root# yum install kubectl**
9. Install RKE (and setup kube config environment for kube_config_rancher-cluster.yml )
10. Setup SSH stuff (keys, forwarding, etc)
11. **dockeruser# rke up --config /home/dockeruser/rancher-cluster.yml**
12. **dockeruser# kubectl -n kube-system create serviceaccount tiller**
13. **dockeruser# kubectl create clusterrolebinding tiller --clusterrole=cluster-admin --serviceaccount=kube-system:tiller**
14. **dockeruser# helm init --service-account tiller**
15. **dockeruser# helm add rancher-stable https://releases.rancher.com/server-charts/stable**
16. **dockeruser# helm install stable/cert-manager --name cert-manager --namespace kube-system --version v0.5.2**
17. **dockeruser# helm install rancher-stable/rancher --name rancher --namespace cattle-system  --set hostname=testcluster.com** (I've tried this step both with and without "--set ingress.tls.source=rancher --set addLocal=true" even though they are defaults).

**Comment by superseb** [comment]
There is currently no difference in importing any K8s cluster or an RKE cluster. Any imported cluster has to be managed using the tool it was created with. The name `local` is always used when the cluster is imported where Rancher is running on. Regarding etcd snapshots, that is in case handled by RKE and not Rancher, there is currently no logic to handle that. If this is not what you are after, let me know, also, other functionality you are looking for.

**Comment by skektek** [comment]
Hello @superseb 

The cluster name and snapshots are incidental details. What I am really missing is the Authorized Cluster Endpoint which is `enabled: false` in the Rancher UI.

**Comment by skektek** [comment]
I've been building (and rebuilding) this RKE HA cluster in our vSphere environment. To reproduce this issue I built another RKE HA cluster in Virtual Box to the same end.  

**This issue is definitely reproducible**. 

According to this document:

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint

You can manually enable the authorized cluster endpoint.

```
local_cluster_auth_endpoint:
  enabled: true
  fqdn: "FQDN"
  ca_certs: "BASE64_CACERT"
```
I tried this as well. The outcome is still the same; the authorized cluster endpoint is not enabled in Rancher.

```
"localClusterAuthEndpoint": {
"enabled": false,
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"type": "/v3/schemas/clusterSpec"
```
