### ISSUE TITLE
kubectl logs --follow keeps blocking after pod succeeded

### ISSUE THREAD

**Issue by daddz** [rancher/rancher#22602]
**What kind of request is this:** Bug

**Steps to reproduce:**
* `kubectl apply -f one-shot.yaml` (see contents below)
* `kubectl logs -f one-shot-log -c one-shot-log` 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: one-shot-log
spec:
  restartPolicy: Never
  containers:
  - name: one-shot-log
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "echo 'starting' && sleep 20 && echo 'stopping'"]
```

**Result:**
The `kubectl logs -f` command blocks for around ~30 minutes each time even though the pod succeeds and terminates after 20 seconds.

**Other details that may be helpful:**
This does not happen in non-rancher k8s deployments.
I tried with k8s (deployed via rancher) versions: 1.12.3, 1.13.4 and 1.15.2

**Environment information**
- Rancher version: v2.2.7
- Installation option: HA
