### ISSUE TITLE
Creating ingress with proxy-ssl-verify=off erases all other annotations

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#22730]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Import the following yaml into a cluster:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-ssl-verify: off
  name: productpage
spec:
  tls:
  - hosts:
    - productpage.com
    secretName: ecp-apps-inte
  rules:
  - host: productpage.com
    http:
      paths:
      - path: /productpage
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /static
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /login
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /logout
        backend:
          serviceName: productpage
          servicePort: 9080
      - path: /api/v1/products
        backend:
          serviceName: productpage
          servicePort: 9080
```

**Result:**
Annotations are not respected

**Other details that may be helpful:**
If you put ```off``` in quotes so line 6 reads as follows, Rancher creates with 3 annotations: ```    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"```

If you edit an ingress by replacing its yaml with one where ```"off"``` is changed to ```off``` the annotations are retained/not removed.
If you edit an ingress by replacing its yaml with one where ```off```  is changed to ```"off"``` the annotations are added, so you can fix it if it's broken but you cant break it if it's working.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher  v2.2.7
User Interface  v2.2.93
Helm  v2.10.0-rancher11
Machine  v0.15.0-rancher8-1

- Installation option (single install/HA):
single and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
reproduced on cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
