### ISSUE TITLE
[Weave] Weave encryption disabled at cluster creation

### ISSUE THREAD

**Issue by tibodf** [rancher/rancher#22751]
** Bug**

**Steps to reproduce :**
- Install Rancher server 2.2.8
- Deploy a cluster with kubernetes 1.14.6 and with Weave network provider

**Result:**
Weave encryption is disabled:
`kubectl exec -n kube-system weave-net-66fbz -c weave -- /home/weave/weave --local status`
```
Version: 2.5.0 (version 2.5.2 available - please upgrade!)
        Service: router
       Protocol: weave 1..2
           Name: 22:09:43:cf:b2:14(preprod5)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 6
    Connections: 6 (5 established, 1 failed)
          Peers: 6 (with 30 established connections)
 TrustedSubnets: none
        Service: ipam
         Status: ready
          Range: 10.42.0.0/16
  DefaultSubnet: 10.42.0.0/16
```

I can't find WEAVE_PASSWORD in the daemonset
`kubectl get daemonset weave-net -n kube-system -o json`
```
"containers": [
                    {
                        "command": [
                            "/home/weave/launch.sh"
                        ],
                        "env": [
                            {
                                "name": "HOSTNAME",
                                "valueFrom": {
                                    "fieldRef": {
                                        "apiVersion": "v1",
                                        "fieldPath": "spec.nodeName"
                                    }
                                }
                            },
                            {
                                "name": "IPALLOC_RANGE",
                                "value": "10.42.0.0/16"
                            }
                        ],
                        "image": "weaveworks/weave-kube:2.5.0",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "weave",
                        "readinessProbe": {
                            "failureThreshold": 3,
                            "httpGet": {
                                "host": "127.0.0.1",
                                "path": "/status",
                                "port": 6784,
                                "scheme": "HTTP"
                            },
                            "initialDelaySeconds": 30,
                            "periodSeconds": 10,
                            "successThreshold": 1,
                            "timeoutSeconds": 1
                        },
```

**Environment information**
- Rancher version : Rancher 2.2.8
- Installation option : Single server rancher

**Cluster information**
- Cluster type : Custom ( 3 master etcd/controlplane + 3 workers)
- Machine type : VM
- Kubernetes version (use `kubectl version`): V1.14.6
- Docker version (use `docker version`): 18.09

**Why the encryption is not enabled by default?**

 Is it possible to enable encryption without redeploy the cluster?

**Comment by superseb** [comment]
How did you create the cluster? When using the UI to create a cluster, when you select Weave in the dropdown and hit Next, it will automatically generate a password. I just verified this works in v2.2.8. Please provide more steps how you created the cluster.

**Comment by tibodf** [comment]
Hi, I created the cluster with the UI :
- Add cluster
- Select Custom
- Select kubernetes versions: Kubernetes version 1.14.6-rancher1-1
- Select Network provider : Weave
- Press NEXT

If i check 'Edit as YAML' before press next, i can see the weave password :
```
addon_job_timeout: 30
authentication: 
  strategy: "x509"
ignore_docker_version: true
# 
#   # Currently only nginx ingress provider is supported.
#   # To disable ingress controller, set `provider: none`
#   # To enable ingress on specific nodes, use the node_selector, eg:
#      provider: nginx
#      node_selector:
#        app: ingress
# 
ingress: 
  provider: "nginx"
kubernetes_version: "v1.14.6-rancher1-1"
monitoring: 
  provider: "metrics-server"
# 
#   # If you are using calico on AWS
# 
#      network:
#        plugin: calico
#        calico_network_provider:
#          cloud_provider: aws
# 
#   # To specify flannel interface
# 
#      network:
#        plugin: flannel
#        flannel_network_provider:
#          iface: eth1
# 
#   # To specify flannel interface for canal plugin
# 
#      network:
#        plugin: canal
#        canal_network_provider:
#          iface: eth1
# 
network: 
  options: 
    flannel_backend_type: "vxlan"
  plugin: "weave"
  weave_network_provider: 
    password: "5CPIlE2REYIDI?Hi"
# 
#      services:
#        kube-api:
#          service_cluster_ip_range: 10.43.0.0/16
#        kube-controller:
#          cluster_cidr: 10.42.0.0/16
#          service_cluster_ip_range: 10.43.0.0/16
#        kubelet:
#          cluster_domain: cluster.local
#          cluster_dns_server: 10.43.0.10
# 
services: 
  etcd: 
    backup_config: 
      enabled: true
      interval_hours: 12
      retention: 6
    creation: "12h"
    extra_args: 
      heartbeat-interval: 500
      election-timeout: 5000
    retention: "72h"
    snapshot: false
  kube-api: 
    always_pull_images: false
    pod_security_policy: false
    service_node_port_range: "30000-32767"
ssh_agent_auth: false
# 
#   # Rancher Config
# 
docker_root_dir: "/var/lib/docker"
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint: 
  enabled: true
name: "test"
```

but when it's deployed, it's not encrypted.
