### ISSUE TITLE
Ability to restrict user to deploy only from catalog

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#22790]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

There are use cases that involve having Rancher manage Kubernetes clusters that are exlusively used to host applications deployed by *project users* from catalogs managed and provided by the *global admin team*.

This involves the requirement to limit *project users* to only be able to deploy and manage resources that are part of a catalog provided by the *global admin team* while not being able to create any project/workload resources on their own.

The required behavior of Rancher App deployment would more closely mirror the behavior of vanilla helm/tiller, where user needs permissions to deploy the chart (via tiller) but the permissions to create the deployed Kubernetes resources are derived from the role assigned to tiller itself. Similary in Rancher a user could have only permissions to deploy apps from a catalog, while Rancher ensures that all resources are created within the current project, thus maintaining tenancy.

**Comment by maggieliu** [comment]
Code for this is merged. However, we don't have enough time to validate this to ensure it's bug free. The testing/validation/bug fixing for this will be done in 2.5.1

**Comment by cloudnautique** [comment]
To test this functionality the high-level steps are:

1. create a service account and bind it to a cluster-admin role. 
2. Create a repository from YAML in the apps and marketplace.
  - Add the `serviceAccount` and `serviceAccountNamespace` to the spec.
3. log in as a read-only user.
4. Deploy an application from the repository added with a service account.

Result: 
1. The application should deploy without errors even though the logged-in user has no permissions to create resources.

For the repository service account, it would be good to test non-cluster admin-level permissions as well. The permission for the service account would need to be able to deploy the application.

The logged-in read-only user should not be able to install apps from system or library charts.

**Comment by sowmyav27** [comment]
On 2.5.0 - 

- create a service account and bind it to a cluster-admin role n a downstream cluster.
```
kubectl create sa sa-1
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount sa-1:default
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- The helm operation pod is in Reconciling state. and Logs of it show: 
```
Waiting for Kubernetes API to be available
Waiting for Kubernetes API to be available
Waiting for Kubernetes API to be available
```
- User is NOT able to deploy apps.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `56bf444`**

- create a service account and bind it to a cluster-admin role n a downstream cluster.
```
kubectl create sa sa-1
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount sa-1:default
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- The helm operation pod is in Reconciling state. and Logs of it show: 
```
Waiting for Kubernetes API to be available
Waiting for Kubernetes API to be available
Waiting for Kubernetes API to be available
```
- User is NOT able to deploy apps.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `d87f58ac` and master-head commit id: `d87f58ac`**

- create a service account and bind it to a cluster-admin role n a downstream cluster.
```
kubectl create sa sa-1
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount sa-1:default
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- Error seen in logs:
```
helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-wordpress-9.0.3.yaml --version=9.0.3 --wait=true test /home/shell/helm/wordpress-9.0.3.tgz
--
Thu, Oct 22 2020 9:07:33 pm | Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: secrets "test-mariadb" is forbidden: User "system:serviceaccount:default:sa-1" cannot get resource "secrets" in API group "" in the namespace "default"
```

**Comment by ibuildthecloud** [comment]
@sowmyav27 The namespace and name are backwards in your command.  I'm not sure how you even got this far, it should have failed the same way as before:
```
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount default:sa-1
```

**Comment by ibuildthecloud** [comment]
@sowmyav27 The error you are getting is a generic helm issue. The secret "test-mariadb" already exists so helm won't overwrite it. That is just a user issue, not a bug.  The fact it could even see the resources to determine that means it has privileges.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `d87f58ac`**

- create a service account and bind it to a cluster-admin role n a downstream cluster.
```
kubectl create sa sa-1
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount default:sa-1
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- Application - grafana deploys successfully.
- Where as deploying an application from a repo without this service account added, read-only user gets an error - `User "u-82n8r" cannot get resource "podsecuritypolicies" in API group "policy" at the cluster scope`

**Comment by ibuildthecloud** [comment]
> Where as deploying an application from a repo without this service account added, read-only user gets an error - User "u-82n8r" cannot get resource "podsecuritypolicies" in API group "policy" at the cluster scope

@sowmyav27 Isn't that expected behavior? The read-only user should fail.

**Comment by sowmyav27** [comment]
@ibuildthecloud yes that is the expected behavior. I have to validate this on master before I close it.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `a3a4c874`**

- create a service account and bind it to a cluster-admin role n a downstream cluster.
```
kubectl create sa sa-1
kubectl create clusterrolebinding test-clusterrole-1 --clusterrole cluster-admin --serviceaccount default:sa-1
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- Application - grafana deploys successfully.
- Where as deploying an application from a repo without this service account added, read-only user gets an error - `User "u-82n8r" cannot get resource "podsecuritypolicies" in API group "policy" at the cluster scope`

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bebfe0d`**

- create a service account and bind it to a project-member role n a downstream cluster.
```
kubectl create sa sa-2
kubectl create clusterrolebinding test-clusterrole-2 --clusterrole project-member --serviceaccount default:sa-2
```
- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application - wordpress from the repository added with a service account.
- Error is seen while deploying the app
```
helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-wordpress-9.0.3.yaml --version=9.0.3 --wait=true word-user1 /home/shell/helm/wordpress-9.0.3.tgz
--
Tue, Oct 27 2020 12:10:39 pm | Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: secrets "word-user1-mariadb" is forbidden: User "system:serviceaccount:default:sa-1" cannot get resource "secrets" in API group "" in the namespace "default"


```

**Comment by StrongMonkey** [comment]
@sowmyav27 Using project-member is a bad test because it doesn't contain the real permission to access `secrets`. You can verify that using `kubectl get clusterrole project-member -o yaml`. It is not saying that project-member doesn't have access to secrets, because when you create project-member in rancher it will guarantee the access.

At the same time I found that uninstall doesn't work so I will fix that.

**Comment by StrongMonkey** [comment]
To mirror the same permission as project-member in its own namespace, you have to do
1. Create rolebinding for project-member roles
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:
  namespace:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-member
subjects:
- apiGroup: core
  kind: ServiceAccount
  name: name
```
2. create rolebinding for edit roles
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:
  namespace:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: core
  kind: ServiceAccount
  name: name
```

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `a90aa3ca`**

- create a service account and bind it to a project-member role n a downstream cluster.
`kubectl create sa sa-1`
- Create rolebinding for project-member roles
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-1
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-member
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: sa-1
```
- create rolebinding for edit roles
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-2
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: sa-1
```
- create clusterolebinding for project-member-promote
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-member-promoted
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: sa-1
  namespace: default
```

- Create a repository from YAML in the apps and marketplace. Add the serviceAccount and serviceAccountNamespace to the spec.
- log in as a read-only user.
- Deploy an application from the repository added with a service account.
- Wordpress is seen deploying successfully
```
helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-wordpress-9.0.3.yaml --version=9.0.3 --wait=true admin /home/shell/helm/wordpress-9.0.3.tgz
--
Wed, Oct 28 2020 4:22:29 pm | creating 9 resource(s)
Wed, Oct 28 2020 4:22:29 pm | beginning wait for 9 resources with timeout of 10m0s
Wed, Oct 28 2020 4:22:31 pm | PersistentVolumeClaim is not bound: default/admin-wordpress
```
