### ISSUE TITLE
Pipelining does not work in a cluster with restricted PSP 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#22844]
Version: Master

Steps:

1. Create a cluster with PSP restricted and also hardening steps as in the guide
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.2/

2. Setup pipelining in the cluster . 
docker-registry and jenkins containers related to pipelining do not come up successfully. 

<img width="1281" alt="Screen Shot 2019-09-12 at 8 45 43 PM" src="https://user-images.githubusercontent.com/18536626/64836343-5048ad00-d59e-11e9-85c1-b6cb5a524fe2.png">

**Comment by jiaqiluo** [comment]
see the same bug in Rancher:v2.3.0-rc3 single install,  the user cluster is a custom cluster prepared following the hardening guide

<img width="1604" alt="Screen Shot 2019-09-16 at 5 23 01 PM" src="https://user-images.githubusercontent.com/6218999/65002040-e46c8a00-d8a6-11e9-9998-12fd3713102d.png">
<img width="1579" alt="Screen Shot 2019-09-16 at 5 23 11 PM" src="https://user-images.githubusercontent.com/6218999/65002041-e46c8a00-d8a6-11e9-9ba5-f1a2f949842c.png">
<img width="1603" alt="Screen Shot 2019-09-16 at 5 23 24 PM" src="https://user-images.githubusercontent.com/6218999/65002043-e46c8a00-d8a6-11e9-9ec3-f89e79b654f7.png">
<img width="1600" alt="Screen Shot 2019-09-16 at 5 23 49 PM" src="https://user-images.githubusercontent.com/6218999/65002044-e46c8a00-d8a6-11e9-83d1-2d336c06940e.png">

**Comment by gitlawr** [comment]
1. In PSP restricted clusters pipeline does not work by default. The build image step uses dind and requires privileged permissions. Pipeline is managed in project scope, so the permissions should be granted explicitly by cluster managers. If we grant that permission by default, it means that every project member can have serviceaccounts with privileged permissions in their projects by running pipelines.
2. To make pipeline works in PSP restricted projects:
Apply the following r/rb to the pipeline namespace
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-psp-role
  namespace: <p-id>-pipeline
rules:
- apiGroups:
  - policy
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-psp-rolebinding
  namespace: <p-id>-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-psp-role
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: <p-id>-pipeline
```
Edit the registry workload(It runs as root) by yaml and add the following to the manifest.
```
# other spec
template:
  spec:
    serviceAccountName: jenkins
```
3. For clusters configured following the hardening guide, the `DenyEscalatingExec` admission controller is enabled. This will block Jenkins Kubernetes plugin to exec into a privileged container and run build image commands. So pipeline does not work in this case. In general, pipeline is not needed in a production cluster, so we would want a feature toggle to disable the whole pipeline function in certain cases.
