### ISSUE TITLE
calico-node health checks break after editing in the UI

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#22848]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

create cluster using canal
add an environment variable to the calico-node deployment via the UI and hit save

**Result:**

The host field for the liveness/readiness checks for the calico-node containers will disappear to look like this:

```
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /liveness
            port: 9099
            scheme: HTTP
```

This causes the checks to go to the nodes IP address over port 9099, which does not work, causing the pod to crashloop. Host was originally set to localhost.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.6

- Installation option (single install/HA):
either

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): 1.14.3
