### ISSUE TITLE
Not able to use rancher-compose.yml generated for service with metadata.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2298]
Rancher server version - v0.41.0-rc1
Rancher compose version - rancher-compose-v0.4.1-rc2

Following is the  rancher-compose.yml generated for service that was created with metadata - 
{"test1": {"name": "t1name", "value": "t1value"}, "test2": {"name": "begin[1,2,3,4]end"}}

```
WEB1:
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
ext1:
  external_ips:
  - 1.1.1.1
  - 2.2.2.2
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
lb-1:
  scale: 1
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
test932494:
  scale: 2
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
```
When using this with rancher-compose , service fails to get created with the following error message:

ERRO[0001] Failed Creating test : json: unsupported type: map[interface {}]interface {} 
ERRO[0001] Failed to start: test : json: unsupported type: map[interface {}]interface {} 
FATA[0001] json: unsupported type: map[interface {}]interface {}

**Comment by alena1108** [comment]
Happens because yml parser just marshals json object, and replicates its json structure in the compose file

@ibuildthecloud @cloudnautique need your help to figure out correct rancher-compose format for representing this data.

On Rancher API service.metadata accepts map[string]json objects:

key1:json1
key2:json2

where json can have multiple fields and nested nodes. Should I just convert json1 and json2 to strings? 

```
serviceA:
metadata:
key1: 'json1_as_a_string'
key2: 'json2_as_a_string'
```

or is there some other format?

**Comment by vincent99** [comment]
The way sangeetha put it seems like how it should be in the yaml... The metadata field's type is `map[json]` because we don't want the top level to be a string or array of other things, just a map.

**Comment by alena1108** [comment]
@vincent99 Sangeetha's file is the one generated by Rancher, but apparently ranhcer-compose doesn't like this format

**Comment by vincent99** [comment]
Right, so we should fix compose :-)

**Comment by alena1108** [comment]
Ok, reassigning to rancher-compose for now

**Comment by sangeethah** [comment]
Tested with:
rancher-server version - v0.41.0-rc2
rancher-compose version - rancher-compose-v0.4.2-rc1

We are able to create a service from rancher-compose command line using the rancher-compose.yml generated for service that was created with metadata.

Was able to start a service successfully using the following docker-compose and  rancher-compose yml and metadata gets set on the service as expected.

We are also able to fetch the metadata for service using http://rancher-metadata/latest/services/<service-name>metadata
 

```
test:
  scale: 2
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
```
