### ISSUE TITLE
Two cluster names showing in kubeconfig for single node install

### ISSUE THREAD

**Issue by GarbageYard** [rancher/rancher#22996]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1) Install Rancher server
2) Create user
3) Create AWS EC2 node. Select `Add Cluster` > `Custom`
4) Assign user (created in step 2) a role of `Cluster Owner` in `Member Roles` section
5) Run generated command on EC2 node created in step 3 

**Result:**
Checking the `Kubeconfig File` present in the cluster dashboard shows two cluster names (`dev` and `dev-ip-172-31-32-121`) _instead of just one_ (`dev`) as shown below:

```
# Kubeconfig File for dev cluster
 
apiVersion: v1
kind: Config
clusters:
- name: "dev"
  cluster:
    server: "https://x.yz.ab.cde:8443/k8s/clusters/c-728wl"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQ\
     WRhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFvTVJJd0VBWURWUVFLRXdsMGFHVXQKY\
     VJUSUZJQ0FURS0tLS0t"
- name: "dev-ip-172-31-32-121"
  cluster:
    server: "https://172.31.32.121:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
     WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
     klDQVRFLS0tLS0K"
 
users:
- name: "user-fbkjc"
  user:
    token: "kubeconfig-user-fbkjc.c-728wl:2z8ngflscgjdxhq4jkmmct492dc7snrg2n4c9plqkhvs96pfzn7x6x"
 
contexts:
- name: "dev"
  context:
    user: "user-fbkjc"
    cluster: "dev"
- name: "dev-ip-172-31-32-121"
  context:
    user: "user-fbkjc"
    cluster: "dev-ip-172-31-32-121"
 
current-context: "dev"
```

Another issue is that the user id `user-fbkjc` is of `Default Admin`. Shouldn't it be that of the user which i created in step 2 above? Also, if i create another cluster and assign a different user, still the `kubeconfig` shows the user id of `Default Admin` for it.

**Other details that may be helpful:**
When i have to test the set up, i start the cluster and clean up the node instance by running these commands and then run the agent command (that i copy from the Custom Node UI section)

	docker stop $(docker ps -qa)
	docker rm -f $(docker ps -qa)
	docker rmi -f $(docker images -q)
	docker volume rm $(docker volume ls -q)

		
	rm -rf /etc/ceph        /etc/cni        /etc/kubernetes        /opt/cni        /opt/rke        /run/secrets/kubernetes.io        /run/calico        /run/flannel        /var/lib/calico        /var/lib/etcd        /var/lib/cni        /var/lib/kubelet        /var/lib/rancher/rke/log        /var/log/containers        /var/log/pods \
	   
	sudo reboot

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher version: `v2.2.8`

- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS EC2 t2.medium (ami-0020c9e628f25ae5a)
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
[centos@ip-172-31-32-121 ~]$ docker version
Client: Docker Engine - Community
 Version:           19.03.0
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        aeac9490dc
 Built:             Wed Jul 17 18:15:40 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       aeac9490dc
  Built:            Wed Jul 17 18:14:16 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
