### ISSUE TITLE
Not able to add metadata field to LB/DNS/External service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2299]
Rancher server version - v0.41.0-rc1
Rancher compose version - rancher-compose-v0.4.1-rc2

Metadata field does not get set for LB/DNS/External service when metadata field is set in rancher-compose.yml

Following is the compose files used:
 
```
sangeethahariharan1@sangee01:~/rancher-compose-v0.4.1-rc2$ cat rc-metadata.yml 
WEB1:
  metadata:
    test1:
      - t1name
      - t1value
ext1:
  external_ips:
  - 1.1.1.1
  - 2.2.2.2
  metadata:
    test1:
      - name
      - value
lb-1:
  scale: 1
  metadata:
    test1:
      - t1name
      - t1value
test:
  scale: 2
  metadata:
    test1:
      - name
      - value
sangeethahariharan1@sangee01:~/rancher-compose-v0.4.1-rc2$ cat dc-metadata.yml 
WEB1:
  image: rancher/dns-service
ext1:
  image: rancher/external-service
lb-1:
  ports:
  - 9000:80
  image: rancher/load-balancer-service
test:
  image: sangeetha/testclient:latest
sangeethahariharan1@sangee01:~/rancher-compose-v0.4.1-rc2$ ./rancher-compose -p testyo1 -f dc-metadata.yml -r rc-metadata.yml create
```
