### ISSUE TITLE
Not able to create services with metadata form rancher-compose.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2301]
Rancher server version - v0.41.0-rc1
Rancher compose version - rancher-compose-v0.4.1-rc2

Tried to  create a service by providing metada field in rancher-compose.yml as follows:

```
test:
  scale: 2
  metadata:
    test1:
      - name: n1
      - value: v1
```

Following exception seen when trying to create a service using rancher-compose:

ERRO[0001] Failed Creating test : json: unsupported type: map[interface {}]interface {} 
ERRO[0001] Failed to start: test : json: unsupported type: map[interface {}]interface {}

This metadata format worked.
```
test:
 scale: 2
 metadata:
   test1:
     - name
     - value
```

But need to know how to provide more complex json objects for metadata field.

**Comment by sangeethah** [comment]
Tested with:
rancher-server version - v0.41.0-rc2
rancher-compose version - rancher-compose-v0.4.2-rc1

We are able to create a service from rancher-compose command line using the rancher-compose.yml generated for service that was created with metadata.

Was able to start a service successfully using the following docker-compose and rancher-compose yml and metadata gets set on the service as expected.

We are also able to fetch the metadata for service using http://rancher-metadata/latest/services/metadata
```
test:
  scale: 2
  metadata:
    test1:
      name: t1name
      value: t1value
    test2:
      name: begin[1,2,3,4]end
```
