### ISSUE TITLE
Centralized Monitoring

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#23057]
**What kind of request is this (question/bug/enhancement/feature request):** Feature Request

It would be great to help enhance the Rancher "Single Pane of Glass" capabilities by providing the ability to deploy a centralized prometheus instance that either is able of scraping metrics in every cluster or scraping metrics from a per-cluster Prometheus.

This can be especially useful for organizations with many Kubernetes clusters.

gz#8139

**Comment by superseb** [comment]
Sounds like https://github.com/rancher/rancher/issues/20891

**Comment by Tejeev** [comment]
I'd like to bump this as it's a popular request.  If we can't have some easy tooling built in, can we get a doc on a tested method of deploying this using the functionality of Monitoring v2?

**Comment by empinator** [comment]
we leveraged this task by having https://thanos.io/ installed on our "central" cluster.
thanos exposes the "thanos-receive" service.
on the cluster we installed a standard prometheus, not rancher monitoring:

prometheus-cluster.yaml:
```
prometheus:
  remoteWrite:
    - url: https://thanos-receive.central-cluster.com/api/v1/receive
      name: my-remote-cluster1
  externalLabels:
    origin_prometheus: my-remote-cluster1
```
```
$ helm install kube-prometheus \
    -f prometheus-cluster.yaml \
    --namespace monitoring \
    bitnami/kube-prometheus
```

the remote cluster stores its prometheus data within the local database as well sends it to central with a "label" so you can distinguish where your data came from
