### ISSUE TITLE
[rancher-compose] Build parameter is not working

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2305]
Build image from relative/absolute directory is not working, but works with `docker-compose`
```
rancher-compose -p registry up
.
docker-compose.yml
  |-containers
  |  |-htpasswd
  |  |-nginx-conf
  |  |  |-conf.d
  |  |  |-templates
  |  |  |-Dockerfile <<< here
  |  |-registry-conf
  |  |  |-conf.d
  |  |  |-templates
  |  |  |-Dockerfile <<< here
```
Error:
```
Failed Starting nginx : Cannot locate Dockerfile: Dockerfile 
```
```yml
nginx-conf:
  build: ./containers/nginx-conf
  command: -backend=redis -node=redis:6379 -interval=5
  external_links:
    - conf/redis:redis
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: 'true'
```
Rancher server: latest
Rancher compose: 0.4.0
