### ISSUE TITLE
Create svc causing Deployment spec lost if the spec is not supported in Rancher API

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#23071]
v2.3.0-rc8

Steps:

1. Create a deployment with `windowsOptions` fields via YAML
2. Deployment up and working as expected
3. Create a node port svc with label selector

Results:

Deployment will be updated and new pods will be created.
And the `windowsOptions` fields lost in the spec.  

Not sure if the fields lost when Rancher update the annotations for the deployment

In k8s 1.15, `windowsOptions` fields are introduced. They are very important fields for Windows container. However, they are not supported in Rancher API.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#windowssecuritycontextoptions-v1-core

**Comment by gitlawr** [comment]
Types vendor uses kubernetes 1.14.5 so these fields are not available in Rancher API at the moment.

**Comment by sangeethah** [comment]
@loganhz Could you please provide the yml used for getting a deployment with windowsOptions fields  ?

**Comment by sowmyav27** [comment]
Reproduced the issue on `rancher:2.3.0-rc8` (single node install)

**Steps:**
- Create a custom windows cluster with these args in the edit as yaml file
```
    kube-api:
      extra_args:
        feature-gates: WindowsRunAsUserName=true
```

- Cluster spec: 1 linux all roles, 1 windows worker node - AWS nodes, k8s1.16
- Import a workload using the yaml file with field `windowsOptions`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    test: three
  name: wk02
  namespace: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      test: three
  template:
    metadata:
      labels:
        test: three
    spec:
      securityContext:
        windowsOptions:
          runAsUserName: "ContainerUser"
      containers:
      - image: maiwj/testcontainer:windows-1903
        name: test-image
        command: ["ping", "-t", "localhost"]
        ports: 
        - containerPort: 80
          protocol: TCP
```
- The workload should get deployed successfully.
- Do a kubectl get deployment <wk-name> -n <namespace> -o json
- Field `windowsOptions` is available in the spec
```
"securityContext": {
                    "windowsOptions": {
                        "runAsUserName": "ContainerUser"
                    }
                },
```
- Create a service discovery entry with selector labels (test: three), and a node port service.
- You will see the node port is exposed on the Workload.
- Do a kubectl get deployment <wk-name> -n <namespace> -o json
- The field `windowsOptions` is not available anymore in the spec
```
"securityContext": {}
```

Verified this issue on master-head - commit id: `de4448e87` and see that the fields on workload update, do NOT go missing

**Steps:**

- Create a custom windows cluster with these args in the edit as yaml file
```
    kube-api:
      extra_args:
        feature-gates: WindowsRunAsUserName=true
```

- Cluster spec: 1 linux all roles, 1 windows worker node - AWS nodes, k8s1.16
- Import a workload using the yaml file with field `windowsOptions` (same as given above)
- The workload should get deployed successfully.
- Do a kubectl get deployment <wk-name> -n <namespace> -o json
- Field `windowsOptions` is available in the spec
```
"securityContext": {
                    "windowsOptions": {
                        "runAsUserName": "ContainerUser"
                    }
                },
```
- Create a service discovery entry with selector labels (test: three), and a node port service.
- You will see the node port is exposed on the Workload.
- Do a kubectl get deployment <wk-name> -n <namespace> -o json
- The field `windowsOptions` is available in the spec
```
"securityContext": {
                    "windowsOptions": {
                        "runAsUserName": "ContainerUser"
                    }
                },
```
