### ISSUE TITLE
Pods "xy" is forbidden: unable to validate against any pod security policy: [];

### ISSUE THREAD

**Issue by murech** [rancher/rancher#23077]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create new pod security policy (psp) in Rancher under Security > Pod Security Policy with the same privileges as unrestricted policy (default, created by rancher)
2. assign pod security policy to project
3. delete pod and see if pod is running with applied psp

**Result:**
Error message: Pods "xy" is forbidden: unable to validate against any pod security policy: []; Deployment does not have minimum availability.

**Other details that may be helpful:**
Created pod security policy:

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    serviceaccount.cluster.cattle.io/pod-security: policy-demo
    serviceaccount.cluster.cattle.io/pod-security-version: "258848977"
  creationTimestamp: 2019-09-24T13:55:41Z
  labels:
    cattle.io/creator: norman
  name: policy-demo-psp
  resourceVersion: "258848978"
  selfLink: /apis/extensions/v1beta1/podsecuritypolicies/policy-demo-psp
  uid: ff51a0ae-ded2-11e9-a0b9-0050568d10c6
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'

Comparing yaml output of the created policy against the unrestricted policy (default, created by rancher) shows one difference: `defaultAllowPrivilegeEscalation: false` is not shown in the unrestricted policy (default, created by rancher)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher: v2.2.8 / User Interface: v2.2.94 / Helm: v2.10.0-rancher11 / Machine: v015.0-rancher8-1
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.14.6
- Docker version (use `docker version`): 19.3.1

**Comment by MSandro** [comment]
I ran into an simular situation. I used RKE to create my Kubernetes Cluster. Now I added pod_security_policy: true to my cluster.yml. Now I am unable to deploy workloads, I have the same error message

**Comment by kursattokpinar** [comment]
Have you managed to handle this? I have same problem too.

**Comment by DoumLaberge** [comment]
Same problem here

**Comment by donnydavis** [comment]
This answer will help some like myself who don't want to always be buried in the command line. In my case, I used RKE to bring the cluster up, but I wanted the rancher dashboard for other things. 
When a cluster is imported, rancher cannot do much with it. However you can make it editable by adding in your RKE config to the imported cluster. 

1. Start by heading over to the Rancher UI API ex: https://$YourRancher/v3/clusters/local
2. Grab the RKE config, dump that into a json converter - https://www.convertjson.com/yaml-to-json.htm
3. Click edit and look for this value - rancherKubernetesEngineConfig - Your RKE config that you just converted to JSON goes here. Click "Show Request" and then Click "Send Request"
4. Go to the Cluster and click the : edit button and now you can edit your RKE deployed cluster from the UI (which helps in step 6)
5. Enable the pod security policy and select your desired default.  (mine is restricted)
6. Click on Projects/ Namespaces and then edit next to the system project. Make sure the Pod Security Policy is None (or whatever you wanted for the system project).

Reason for all of this is because Rancher does not know about the pod_security_policy value until you tell it that it should be enabled. This fixed my cluster - hopefully it will help someone else.

**Comment by atsai1220** [comment]
> This answer will help some like myself who don't want to always be buried in the command line. In my case, I used RKE to bring the cluster up, but I wanted the rancher dashboard for other things.
> When a cluster is imported, rancher cannot do much with it. However you can make it editable by adding in your RKE config to the imported cluster.
> 
>     1. Start by heading over to the Rancher UI API ex: https://$YourRancher/v3/clusters/local
> 
>     2. Take the RKE config used to provision the cluster and dump that into a json converter - https://www.convertjson.com/yaml-to-json.htm
> 
>     3. Click edit and look for this value - rancherKubernetesEngineConfig - Your RKE config that you just converted to JSON goes here. Click "Show Request" and then Click "Send Request"
> 
>     4. Back in the UI, go to Cluster and click the : edit button and now you can edit your RKE deployed cluster from the UI (which helps in step 6)
> 
>     5. Enable the pod security policy and select your desired default.  (mine is restricted)
> 
>     6. Click on Projects/ Namespaces and then edit next to the system project. Make sure the Pod Security Policy is Unrestricted (or whatever you wanted for the system project).
> 
> 
> Reason for all of this is because Rancher does not know about the pod_security_policy value until you tell it that it should be enabled. This fixed my cluster - hopefully it will help someone else.

Running into similar issue with our `local` Rancher cluster. We had to add RBAC and restart any workloads for monitoring and such in order for them to start. This is cumbersome and I'm wondering I'm doing something wrong here... I suppose I could apply all these as part of user-addons but I am expecting these policies to be there with a fresh installation.

First had to create my own unrestricted-psp
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: unrestricted-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'

Then create a Cluster Role that uses this new PSP
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unrestricted-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - unrestricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

Then in each namespace in System project that has issues with workloads I create a RoleBinding for all service accounts in that namespace

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: rancher-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-operator-system-unrestricted
  namespace: rancher-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unrestricted-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
```
