### ISSUE TITLE
Cluster unavailable when I shutdown one of controlplane nodes

### ISSUE THREAD

**Issue by Leen15** [rancher/rancher#23087]
Hi, I have a very strange situation with a production cluster.
13 bare metal servers
6 servers have "controlplane,worker,etcd" roles
7 servers have only worker role

I created the cluster with RKE, with the following conf:
```
nodes:
    .......

kubernetes_version: "v1.14.6-rancher1-1"

services:
  kubelet:
    extra_args:
      max-pods: 800
      node-status-update-frequency: "4s"
  kube-api:
    extra_args:
      default-not-ready-toleration-seconds: "10"
      default-unreachable-toleration-seconds: "10"
  kube-controller:
    extra_args:
      node-monitor-grace-period: "16s"
      node-monitor-period: "2s"

```

The cattle-cluster-agent is running on one of master nodes.
If I shutdown this node, all cluster is `unavailable` in rancher.
I can access with kubectl, and if I check on nodes I see the powered off node as "NotReady".
If I check the `cattle-system` namespace the pod cattle-cluster-agent is "Running". 
If I try to kill the pod manually from kubectl, I see the pod status a "Terminating" and a new  pod as "Pending".
Inside that pod, I see:
```
Normal  Scheduled  3m    default-scheduler  Successfully assigned cattle-system/cattle-cluster-agent-77f8b7456c-c24dq to X.X.X.X
```
The scheduler assigned the pod to the NotReady node!

I tried with another cluster on AWS and I don't have this situation:
I see the cattle-cluster-agent with state "unknown" but the cluster is still visible on Rancher

So, I have 3 questions:
- Why If a single node goes down I have the cluster "unavailable" on Rancher?
- Why the cattle-cluster-agent workload doesn't have default tolerations?
- Why it continues to schedule the pod to the NotReady node?

Can you help me debugging this situation?

Thanks
