### ISSUE TITLE
Path-based  Ingress routing not work

### ISSUE THREAD

**Issue by lerit** [rancher/rancher#23141]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
I am running a Kubernetes cluster (which has the default rancher-ingress-controller) and trying to use an ingress with path-based routing. I   run some service/deployment (i.e. nginx-front-web,nginx-admin-web) and then create an ingress as follows:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress-1
spec:
  rules:
  - host: www.abc.com
    http:
      paths:
      - backend:
          serviceName: nginx-front-web
          servicePort: 80
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress-2
spec:
  rules:
    http:
      paths:
      - backend:
          serviceName: nginx-admin-web
          servicePort: 80
        path: /admin
```
**Expect:**
request www.abc.com and get nginx-front-web
request www.abc.com/admin and get nginx-admin-web
**Result:**
Then I make a request with a path:
curl -i http://www.abc.com/admin
    it redirect to www.abc.com
i find nginx log in service 'nginx-admin-web',with path endwith '/admin'
but i do not know why it redirect to first service 'nginx-front-web' later
curl -i http://www.abc.com
  it work fine
if i remove first ingress,and curl -i http://www.abc.com/admin
a page with text:
'404 - default backend'

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.8
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
```
v19.03.2
```

i seach issue relate:
  #8125
i try to set second ingress:
nginx.ingress.kubernetes.io.rewrite-target=/
but rancher ui throw error:
![选区_143](https://user-images.githubusercontent.com/4743467/65828061-3eb71300-e2c9-11e9-990c-3aadb6f6b75b.png)
