### ISSUE TITLE
flannel --iface is broken on k8s 1.16

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23180]
due to tabs being at:

https://github.com/rancher/kontainer-driver-metadata/blob/e6d8f524e4456635d1d37a05f2e454a468ed11b6/rke/templates/flannel.go#L642-L644

the `flannel_iface` configuration and flannel is broken when the rke cluster.yaml is:

```yaml
cluster_name: example
kubernetes_version: v1.16.0-beta.1-rancher2-1
network:
  plugin: flannel
  options:
    flannel_iface: eth1
```

the bug was introduced at https://github.com/rancher/kontainer-driver-metadata/commit/10592a4f69a2c3b30855e8e0cf5f4a6ceefeba96.

**Comment by alena1108** [comment]
@rgl thanks for providing the fix! We've run the validation on our end, but can you double check if the issue is no longer happening for you?

**Comment by jiaqiluo** [comment]
The bug is reproduced in master-head with old metadata
- add an EC2 cluster with k8s 1.16 and the following setting
```
  network:
    options:
      flannel_iface: eth1
    plugin: flannel
```
result:
-  the cluster is failed to be provisioned
```
2019/10/03 00:03:18 [ERROR] Cluster c-5wccn previously failed to create
2019/10/03 00:04:15 [ERROR] ClusterController c-5wccn [cluster-provisioner-controller] failed with : Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```
<img width="1466" alt="Screen Shot 2019-10-02 at 5 14 05 PM" src="https://user-images.githubusercontent.com/6218999/66090385-141ec180-e538-11e9-879c-8b60648bb7b1.png">

**Comment by jiaqiluo** [comment]
Here is what we see in `master-head`  with the fix.

Steps:
- add an EC2 cluster with k8s `v1.16` and the following settings in yaml
```
 network:
    options:
      flannel_iface: eth1
    plugin: flannel
```

Results:
- the cluster is active
- but some workloads are not deployed correctly 
<img width="1456" alt="Screen Shot 2019-10-02 at 5 21 56 PM" src="https://user-images.githubusercontent.com/6218999/66090633-277e5c80-e539-11e9-8a3a-d19d2eeb8703.png">

- check the workload `kube-flannel` -> edit as YAML, we see the option is applied 
```
 - args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface=eth1
        command:
```
- check the log of any pod inside  `kube-flannel`
```
I1003 00:19:02.654167 1 main.go:210] Could not find valid interface matching eth1: error looking up interface eth1: route ip+net: no such network interface
E1003 00:19:02.654436 1 main.go:234] Failed to find interface to use that matches the interfaces and/or regexes provided
```
