### ISSUE TITLE
Cannot upgrade service...

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2319]
Following documentation step by step I tried to upgrade service1 to service2 with no success - `Failed to find a placement`
```
rancher-compose -p conf upgrade conf-app conf-app2
```
```yml
redis-conf:
  image: odise/busybox-curl
  command: curl -s -o redis.conf https://gist.githubusercontent.com/ndelitski/ea963c2c1dabcde54637/raw/faba0e50be1e765aef9b246677f22a123d16648d/synccloud.conf.redis.conf
  workdir: /etc/redis
  volumes:
    - /etc/redis/redis.conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: 'true'
redis:
  image: redis
  ports:
  - 6379:6379
  volumes:
    - vol-conf-redis:/data
  volume_driver: convoy
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: redis-conf
    io.rancher.scheduler.affinity:host_label_soft: core=1
conf-app:
conf-app2:
  image: some-webapp-image
  ports:
  - 8082:80
  links:
  - redis:redis
  environment:
    REDIS_HOST: redis
    PORT: 80
    NODE_ENV: production
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: core=1
```

[Screenshot](https://photos-5.dropbox.com/t/2/AAAoEGMgAataLyHi2dVU2lxE4R_rgvM0m1rj3149OSEIPw/12/13342065/png/32x32/1/_/1/2/Screenshot%202015-10-12%2019.22.28.png/EP_S9AkYyeICIAEgAigC/-9SFom8_hppTpCvdc4o83UeZuIaxi8jTe9PBH9Iero4?size=1280x960&size_mode=2)
[Screenshot 2](https://photos-6.dropbox.com/t/2/AADbr1f8ulZ2I94iCb00bzt05GKPlno-B1RU13Sdy2FpYQ/12/13342065/png/32x32/1/_/1/2/Screenshot%202015-10-12%2019.34.07.png/EP_S9AkYy-ICIAEgAigC/gdN1Whz6yqVn1nZDQDDgvEguF5ChsnPPz1Rkguh1iow?size=1280x960&size_mode=2)
[Logs](https://gist.github.com/ndelitski/40f82d6b8fdadba25803)

Set and unset scheduler labels, nothing helps, what am i doing wrong?
Rancher server 0.4.0(Same with 0.4.1-rc1)
