### ISSUE TITLE
Selectors - io.rancher.service.selector.container and  io.rancher.service.selector.link labels should not be set for the service created from rancher-compose.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2328]
Rancher server version - v0.41.0-rc2
Rancher compose version - rancher-compose-v0.4.1-rc2

When using the following docker-compose file to create service with   selectorContainer/selectorLink ,
in addition to selectorContainer and selectorLink being set , io.rancher.service.selector.container and  io.rancher.service.selector.link labels are getting set.

```
ctestmultiple1:
  labels:
    io.rancher.service.selector.container: foo=bar1
  image: sangeetha/testclient:latest
testmultiple1:
  labels:
    io.rancher.service.selector.link: foo=bar1
  image: sangeetha/testclient:latest
```

io.rancher.service.selector.container and  io.rancher.service.selector.link labels should not be set for the service created from rancher-compose . Only selectorContainer and selectorLink needs to be set for the service.
