### ISSUE TITLE
[Forwardport] Tolerations loaded from catalog show up incorrect in user interface

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23353]
Forwardport rancher/rancher#18605

**Comment by westlywright** [comment]
Available in master.

**Comment by sowmyav27** [comment]
**verified on master-head - commit id `8d57a1cfb`**
ui tag: `latest2`

**Steps:**
- deploy datadog from catalog library in Apps in an rke cluster
- Go to Workloads --> Datadog --> Node Scehduling --> Tolerations:
<img width="1262" alt="Screen Shot 2019-10-22 at 1 13 07 AM" src="https://user-images.githubusercontent.com/26032343/67237549-23bf6500-f469-11e9-90b9-163546ee4e09.png">

- Workload --> view Edit YAML shows
```
      tolerations:
      - key: node-role.kubernetes.io/etcd
        value: "true"
      - key: node-role.kubernetes.io/controlplane
        value: "true"
```
