### ISSUE TITLE
Rancher adds additional annotation to each ingress

### ISSUE THREAD

**Issue by lverba** [rancher/rancher#23378]
Hi, Rancher adds additional annotation field to every ingress in cluster, example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"namespace:some-service","ingressName":"namespace:some-ingress","hostname":"fqdn","allNodes":false}]'
```
We have our own pod that creates ingresses and then rancher add these additional field our pod recreates this ingress. So, my question is: can we disable this rancher behavior somehow or should we change something inside our app? Thank you.
