### ISSUE TITLE
hostPort defined on workload via YAML lost after editing workload via the UI

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23375]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Spin up a default custom cluster with Rancher v2.2.8 or v2.3.0
2. Deploy the following simple nginx Deployment exposing a hostPort:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
```
3. Observe nginx reachable via hostPort
4. Open Edit form for the Deployment in Rancher UI and observe port incorrectly shown as NodePort 0:
<img width="1374" alt="Screenshot 2019-10-11 at 10 48 31" src="https://user-images.githubusercontent.com/9771530/66639973-42775d80-ec18-11e9-9988-d74198a231aa.png">
5. Click upgrade in the Edit UI and observe the hostPort is removed from the Deployment.

**Environment information**
- Tested on Rancher v2.2.8 and v2.3.0
