### ISSUE TITLE
NodeAffinity support for RKE system addons

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23388]
Starting v2.3, we let user configure node selector for every system addon launched in rke cluster (cni, ingress, coredns): https://github.com/rancher/kontainer-driver-metadata/pull/40. But you can only pass key/value pairs, and it essentially translates to nodeSelector option:

```
nodeSelector:
    disktype: ssd
```

We have to improve the feature by letting user configure NodeAffinity rules for system addons, with an ability to pass an operator:
```
 affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
```

cc @cloudnautique
