### ISSUE TITLE
Where is RBD in the v2.3.0?

### ISSUE THREAD

**Issue by phobos-dthorga** [rancher/rancher#23421]
Hello everyone! First of all, I apologize if this is the wrong section to post such a question. To begin with, the version information of our deployments across all nodes is just below:

```bash
phobosdthorga@rancher:~/Kubernetes/storage$ docker version
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:57:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

And for Kubernetes itself:

```bash
phobosdthorga@rancher:~/Kubernetes/storage$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

We upgraded to the latest version of Rancher recently, `v2.3.0`, by doing a clean install for reasons that are not of a concern to this Issue, and we noticed that the Ceph/RBD storage plugin is no longer present. We've tried the following below but PVCs are still being met with errors.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gk-ceph-ha
provisioner: kubernetes.io/rbd
parameters:
  monitors: 51.68.218.40:6789,164.132.173.10:6789,5.196.75.152:6789,5.135.156.174:6789
  adminId: admin
  adminSecretName: ceph-secret-ha
  adminSecretNamespace: kube-system
  pool: kubernetes-ha
  userId: kubernetes
  userSecretName: ceph-secret-user-ha
  userSecretNamespace: default
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
```

Apologies if this sounds stupid of us, but how do we enable the RBD plugin once again? We've tried searching and searching all over Google, but cannot find a way. Any and all help will be sincerely appreciated, thank you.
