### ISSUE TITLE
Linode cloud provider yaml is missing a key value pair preventing the deployment of linode services in Rancher 2.3

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#23446]
**What kind of request is this (question/bug/enhancement/feature request):**

The Linode Rancher 2.3 guide has instructions to use a yaml file in `addons_include` when deploying a custom cloud provider.

Step 10 in the [Provision a Cluster](https://www.linode.com/docs/applications/containers/kubernetes/how-to-deploy-kubernetes-on-linode-with-rancher-2-x/#provision-a-cluster) section. [Yaml](https://linode.github.io/rancher-ui-driver-linode/releases/v0.3.0/linode-addons.yml).

But the Cluster ends with taints that prevents the linode system services to deploy.

**Steps to reproduce (least amount of steps as possible):**

1. Follow the guide above it's not mandatory to setup the cluster nodes as the guide I used 1 etcd, 1 Control Plane, 3 workers

**Result:**

Worker nodes have the following taint:

`node.cloudprovider.kubernetes.io/uninitialized    true    NoSchedule`

Symptoms were nodes were showing as uninitialized (via taint), and all linode-ccm workloads were failing to schedule

**Other details that may be helpful:**

@bmdepesa helped me investigating the issue and he found the following:

The tolerations weren’t set correctly:
in spec.template.spec.tolerations for ccm-linode DS

The CCM can run on Nodes tainted as masters
```yaml
        - key: "node-role.kubernetes.io/controlplane"
          effect: "NoSchedule"
```
should be:

The CCM can run on Nodes tainted as masters
```yaml
        - key: "node-role.kubernetes.io/controlplane"
          effect: "NoSchedule"
          value: "true"
```
Once we made this change, we saw the CCM being deployed, and all nodes became initialized, and linode-controller workloads were able to be scheduled.

**Environment information**
- Rancher version : 2.3
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Cloud Provider Linode
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud

**Comment by Charliekenney23** [comment]
I was able to reproduce this with [this version](https://raw.githubusercontent.com/linode/rancher-ui-driver-linode/592298bf5b88cbd87e487ddc93067376c20f87c8/releases/v0.3.0/linode-addons.yml) of `linode_addons.yaml`. The fix was actually in linode/rancher-ui-driver-linode#12!

**Comment by izaac** [comment]
@Charliekenney23 I've used the [raw file](https://raw.githubusercontent.com/phillc/rancher-ui-driver-linode/e210a4becc4e6524ccc36fd4421a1ad30604cb8f/releases/v0.3.0/linode-addons.yml) YAML from https://github.com/linode/rancher-ui-driver-linode/pull/12 

But I'm still getting the worker nodes tainted after provisioning:

<img width="1243" alt="Screen Shot 2020-02-12 at 5 58 22 PM" src="https://user-images.githubusercontent.com/27659/74391402-62cf4880-4dc1-11ea-982b-c13cb38aecd4.png">

**Comment by Charliekenney23** [comment]
@izaac Hmm. Can you paste your cluster's config here, excluding your Linode API Token in the addon config?

**Comment by izaac** [comment]
@Charliekenney23  sure here it is:

```yaml
# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: linodetest
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addons_include:
    - https://raw.githubusercontent.com/phillc/rancher-ui-driver-linode/e210a4becc4e6524ccc36fd4421a1ad30604cb8f/releases/v0.3.0/linode-addons.yml
  addons: |-
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: linode
      namespace: kube-system
    stringData:
      token: "..."
      region: "us-west"
    ---
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.16.6-rancher1-2
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: "30000-32767"
    kubelet:
      fail_swap_on: false
      extra_args:
        cloud-provider: "external"
    kube-controller:
      extra_args:
        cloud-provider: "external"
  ssh_agent_auth: false
windows_prefered_cluster: false

```
