### ISSUE TITLE
Possible incorrect processing order for Config Map and Environment Vars

### ISSUE THREAD

**Issue by ecarlotti** [rancher/rancher#23454]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement Request

**Steps to reproduce (least amount of steps as possible):**
1. Create a Config Map with two or more variables, ex: HELLO=Hello, WORLD=World
2. Create a new workload that consumes the Config Map;
3. Define a Environment Var using both Config Map values, ex: HELLO_WORLD=$(HELLO) $(WORLD)

**Result:**
As is, the result for the steps listed above will simply be a variable with the value "$(HELLO) $(WORLD)", while the expected result would be an environment variable with the value "Hello World".

**Other details that may be helpful:**
This is happening exclusively because Rancher defines Environment Variables BEFORE it defines variables coming from Config Maps in the way it builds the workload yaml file:
```
      - env:
        - name: HELLO_WORLD
          value: $(HELLO) $(WORLD)
        - name: HELLO
         valueFrom:
            configMapKeyRef:
              key: HELLO
              name: helloworld-vars
              optional: false
        - name: WORLD
          valueFrom:
            configMapKeyRef:
              key: WORLD
              name: helloworld-vars
              optional: false
 ```

The only change I have to do to make the test case above works as expected, is to manually edit the yaml file and reverse the declaration order of Config Maps and Environment Variables:
```
      - env:
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              key: HELLO
              name: helloworld-vars
              optional: false
        - name: WORLD
          valueFrom:
            configMapKeyRef:
              key: WORLD
              name: helloworld-vars
              optional: false
        - name: HELLO_WORLD
          value: $(HELLO) $(WORLD)
```
This simple change would make the usage of Config Maps much more versatile. As of now, I have to manually edit all workloads where I need to use Config Maps to keep all my settings in a central location. This is **not possible by using only the Rancher UI**.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8 Cores, 24Gb RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-102.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Mon Aug  5 15:09:42 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-102.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Mon Aug  5 15:09:42 2019
 OS/Arch:         linux/amd64
 Experimental:    false

```
Thanks in advance for taking a look at this.
