### ISSUE TITLE
editing ingress with cert presents choose a cert dialog not cert assigned to ingress

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#23473]
**What kind of request is this (question/bug/enhancement/feature request):**
bug, maybe a feature

**Steps to reproduce (least amount of steps as possible):**
1. create secrets for ingress to use as certificates
2. create ingress using kubectl
3. edit ingress

**Result:**
presented with 'Use default ingress controller certificate' dialog selected by default and not the cert that the ingress was created with.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
I've attempted to reproduce this with the following steps.

Launch an RKE based cluster through UI (DO in my case).

After cluster is finished provisioning launch `kubectl` for the cluster.

Create a new self signed cert on the cluster with: 
  `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert-key -out cert-file -subj "/CN=foo.com/O=foo.com"`

Create secret with kubectl with:
  `kubectl create secret tls selfsinged-cert --key cert-key --cert cert-file`

Create example ingress local to cluster with the following config:
```
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: tls-example-ingress
  spec:
    tls:
    - hosts:
      - sslexample.foo.com
      secretName: selfsinged-cert
    rules:
      - host: sslexample.foo.com
        http:
          paths:
          - path: /
            backend:
              serviceName: service1
              servicePort: 80
```

Launch ingress example with:
  `kubectl apply -f ingress-example.yaml`

From the UI, edit the ingress that was launched in the default namespace for the cluster. View the ingress SSL/TLS certs section and verify the following options are set:
  `Choose a certificate` Radio button is selected
  `selfsigned-cert (foo.com)` is selected in the `Certificate` dropdown.


Can the QA team validate this? If the issue is still reproducible can you place your steps in here because I may be missing some nuance in the steps of the main issue that were not properly articulated. 

I've tested this on both `master-head` and `2.3-head` branches with the same result.
