### ISSUE TITLE
When "$$" value is used in metadata field, one of the "$" value is lost when metadata is stored for the service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2351]
Server version - Build from master oct 15

When using the following rancher-compose file  create a service with metadata , we loose one of the "$" when the metadata gets stored in the DB for the service.

Rancher-compose used for creating service:

```
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "${cluster_name}"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
```
Metadata stored for the service:

```
"metadata": {
"elasticsearch": {
"yml": {
"cluster.name": "",
"node.data": "false",
"node.master": "false",
"node.name": "${HOSTNAME}",
},
},
},
```

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc1

I am still seeing this issue:

Rancher-compose template used to create the service:

```
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "${cluster_name}"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
```


Metadata gets saved with only 1 "$"
```
"metadata": {
"elasticsearch": {
"yml": {
"cluster.name": "es",
"node.data": "false",
"node.master": "false",
"node.name": "${HOSTNAME}",
},
},
},
```
