### ISSUE TITLE
Pipeline service account is not retrievable/ fails on CRDS

### ISSUE THREAD

**Issue by stekole** [rancher/rancher#23568]
**What kind of request is this (question/bug/enhancement/feature request):**
- question
- feature request

**Steps to reproduce (least amount of steps as possible):**

- Install an app with a custom CRDs via pipeline (sealed-secrets for example)

- When you deploy anything via the pipeline it runs as a "System Account for $project-id" however you cannot find this account anywhere in the API (not that I can find)

**Result:**
Result will fail on the CRD. 
`Upgrade --force successfully deleted the previous release, but encountered 1 error(s) and cannot continue: sealedsecrets.bitnami.com "mysecret" is forbidden: User "u-xxxxxxxx" cannot delete resource "sealedsecrets" in API group "bitnami.com" in the namespace "test"`

**Other details that may be helpful:**

- If I manually gather this ID from the failed output of the pipeline and create an rbac policy, everything works after a redeploy

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-test
subjects:
- kind: User
  name: u-xxxxxxxx
  namespace: test
```

**Environment information**
- Rancher version: 2.2.8
- Installation option (single install/HA): HA

**Request:** Can we get this account ID somehow to easily add rbac rules to this pipeline user? Or are we able to set a custom user that will run the deploys/pipeline?
