### ISSUE TITLE
Unable to view project containing ecdsa certificate

### ISSUE THREAD

**Issue by mikenorgate** [rancher/rancher#23562]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Using cert managed I create a certificate resource with a key algorithm of ECDSA.

**Result:**
Attempting to navigate to the project gives an error on the `namespacedsecrets` request

The error is:
```
{
    "baseType": "error",
    "code": "InvalidBodyContent",
    "fieldName": "certs",
    "message": "failed to parse key: key must be PEM encoded PKCS1 or PKCS8: asn1: structure error: tags don't match (16 vs {class:0 tag:4 length:48 isCompound:false}) {optional:false explicit:false application:false private:false defaultValue:\u003cnil\u003e tag:\u003cnil\u003e stringType:0 timeType:0 set:false omitEmpty:false} AlgorithmIdentifier @5",
    "status": 422,
    "type": "error"
}
```

**Other details that may be helpful:**
This only started happening after an updated from 2.2.9 -> 2.3.1

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1
- Installation option (single install/HA): HA

**Comment by mrajashree** [comment]
Same as https://github.com/rancher/rancher/issues/23285

**Comment by mrajashree** [comment]
@mikenorgate were these certs created through rancher ui?

**Comment by colinwilson** [comment]
I'm still experiencing this (Rancher 2.3.5) with ECDSA certs created by cert-manager (v0.14):

_cert manifest_
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mycert.example.com
  namespace: api
spec:
  secretName: mycert.example.com
  commonName: mycert.example.com
  keySize: 256
  keyAlgorithm: ecdsa
  keyEncoding: pkcs8
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "mycert.example.com"
  dnsNames:
  - mycert.example.com
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - "mycert.example.com"
```

_describe cert_
```
> kubectl -n=test describe cert mycert-example-com
Name:         mycert-example-com
Namespace:    test
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"cert-manager.io/v1alpha2","kind":"Certificate","metadata":{"annotations":{},"name":"mycert-example-com","namespace":"test"},"sp...
API Version:  cert-manager.io/v1alpha3
Kind:         Certificate
Metadata:
  Creation Timestamp:  2020-03-21T15:36:39Z
  Generation:          1
  Resource Version:    1180390
  Self Link:           /apis/cert-manager.io/v1alpha3/namespaces/api/certificates/mycert-example-com
  UID:                 0e8d5ea8-c72a-4f41-bcf0-b30cbc353cdc
Spec:
  Common Name:  mycert.example.com
  Dns Names:
    mycert.example.com
  Issuer Ref:
    Kind:         ClusterIssuer
    Name:         letsencrypt-prod
  Key Algorithm:  ecdsa
  Key Size:       256
  Secret Name:    mycert-example-com
Status:
  Conditions:
    Last Transition Time:  2020-03-21T15:36:44Z
    Message:               Certificate is up to date and has not expired
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2020-06-19T14:36:43Z
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  20s   cert-manager  Generated a new private key
  Normal  Requested     20s   cert-manager  Created new CertificateRequest resource "mycert-example-com-2111872077"
  Normal  Issued        15s   cert-manager  Certificate issued successfully
```

_Error_: Before I configured PKCS8 encoding
```
[ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert mycert-example-com. Will not display correctly in UI
```
After encoding the cert with PKCS8
```
[ERROR] Error certs=InvalidBodyContent 422: failed to find cert that matched private key parsing cert mycert-example-com. Will not display correctly in UI
```
