### ISSUE TITLE
Is the extends keyword supported in rancher-compose.yml?

### ISSUE THREAD

**Issue by alejom99** [rancher/rancher#2359]
As you know, docker-compose has the ability to [extend](https://docs.docker.com/compose/yml/#extends) a service in one docker-compose.yml file with the service from another file. I was wondering if the same could be done within a rancher-compose.yml, for example:

common-rancher-compose.yml

```
web:
  metadata:
    config:
      param1: val1
      param2: val2
```

rancher-compose.yaml

```
web:
  extends:
    file: common-rancher-compose.yml
    service: web
  metadata:
    config:
      param1: new_val1
```

If this were to work, my expectation would be that in the second rancher-compose.yml file, we would override the param1 value under metadata, but param2 would remain the same.

Thanks
