### ISSUE TITLE
Allow cloning when adding a persistent volume claim

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#23618]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description**
Recently a new feature was added to Kubernetes to allow you to create a new persistent volume claim (PVC), by cloning an existing PVC. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-cloning . This feature is alpha in v1.15 and beta in v1.16.

Example YAML:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-new-pvc
spec:
  storageClassName: my-csi-plugin
  dataSource:
    name: an-existing-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
Feature should be available in Rancher UI when creating a new PVC. Older clusters pre-v1.15 should hide this in the UI. May also need to ensure the CSI driver supports cloning.

See also - https://kubernetes.io/blog/2019/06/21/introducing-volume-cloning-alpha-for-kubernetes/
