### ISSUE TITLE
Abstration over compose templates, add rancher-compose ability to read config from pipe

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2368]
I'll share my experience in my struggle with duplication in templates... 
In our product we have a lot of similar(in terms of deploy) microservices and have to duplicate over and over same settings in docker-compose files. Lets take a look at mail services, we have about 10 services responsible for handling emails, every service in rancher consists of configuration and app containers. Configuration one subscribe to app settings changes, update files and gracefully restart app container. App and configuration templates are only slightly differs across 10 services, but i have to produce 20 similar templates and when i change something i have to replicate it in 20 places...
Then i come up with service definitions and my compose-templates now look like this:
mail:

``` yml
mail-config:
  @conf: /etc/service.mail #volume to store config files
event-sink:
  @mail-service:
     version: 0.0.3
  # overrides may be here
event-completioner:
 @mail-service:
   version: 0.0.2
letter-composer:
  @mail-service:
    version: 0.0.3
letter-sender:
  @mail-service:
    version: 0.0.3
...
```

frontend:

``` yml
frontend-conf:
  @conf: /etc/frontend
frontend:
 volumes_from: - frontend-conf
```

service definitions:
conf:

``` yml
image: ndelitski/confd-entry:0.1.0
command: -backend=redis -node=redis:6379 -interval=5
volumes:
  - ${args}
  - /var/run/docker.sock:/var/run/docker.sock:ro
external_links:
  - conf/redis:redis
restart: always
tty: true
stdin_open: true
labels:
  io.rancher.container.hostname_override: container_name
```

mail-service:

``` yml
image: ndelitski/mail.${service_name}:${args.version}
external_links:
  - conf/redis:redis
volumes_from:
  - mail-config
environment:
  CONFIGURATION_FILE: /etc/service.mail/config.${service_name}.json
restart: always
tty: true
stdin_open: true
labels:
  io.rancher.container.hostname_override: container_name
  io.rancher.sidekicks: mail-config
  io.rancher.scheduler.affinity:host_label_soft: mail=1
```

In bash script i substitute origin compose file with tranformed and feed it to `rancher-compose -f`. Would be nice if i can do it through piping. `process_template compose@production.yml | rancher-compose up`
