### ISSUE TITLE
Launch EKS with EKS-Optimized AMIs retrieved from SSM

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#23700]
**What kind of request is this (question/bug/enhancement/feature request):** enhancement

**Steps to reproduce (least amount of steps as possible):** Currently AMIs are stored in `drivers/eks/eks_driver.go`

**Result:** Manual refresh is required 

**Other details that may be helpful:**

SSM GetParameter can be used to retrieve these programatically.

  * https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.GetParameter
  * https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html

**Comment by dkeightley** [comment]
[Example](https://github.com/weaveworks/eksctl/blob/bc389872188a28a4ece45fdf069ec03c0c691ee1/pkg/ami/ssm_resolver.go#L23) of GetParameter for EKS AMI retrieval

**Comment by dkeightley** [comment]
Or, as CloudFormation is used, using the built-in parameter type at creation of the stack, replacing 1.14 with the version of k8s.

```yaml
  NodeImageIdSSMParam:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/eks/optimized-ami/1.14/amazon-linux-2/recommended/image_id
    Description: AWS Systems Manager Parameter Store parameter of the AMI ID for the worker node instances.
```
And a condition if `NodeImageId` is provided (override).

```yaml
Conditions:
  HasNodeImageId: !Not
    - "Fn::Equals":
        - Ref: NodeImageId
        - ""
```
Build the launch configuration using the AMI:
```yaml
  NodeLaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
[...]
      ImageId: !If
        - HasNodeImageId
        - Ref: NodeImageId
        - Ref: NodeImageIdSSMParam
```
