### ISSUE TITLE
[forwardport] kube-proxy cannot support IPVS with default RKE configuration

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#23756]
[forwardport]https://github.com/rancher/rancher/issues/13769

**Comment by prachidamle** [comment]
Reopening this issue to forward-port the additional fix added to revert this change for Windows.

**Comment by deniseschannon** [comment]
Available in RKE v1.1.0-rc1

**Comment by soumyalj** [comment]
Tested with master-head branch(3e70a280cfce)
Creted DO RKE cluster with cluster.yml
```
services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy:
      extra_args:
        proxy-mode: ipvs

```
The cluster creation succeeded and cluster was functional.
Docker inspect on the kubeproxy container on each of the hosts indicated the proxy-mode:ipvs as below

```
     "Config": {
            "Hostname": "soumyadotestipvs1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "rancher/hyperkube:v1.16.3-rancher1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/opt/rke-tools/entrypoint.sh",
                "kube-proxy",
                "--cluster-cidr=10.42.0.0/16",
                "--hostname-override=soumyadotestipvs1",
                "--kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml",
                "--v=2",
                "--healthz-bind-address=127.0.0.1",
                "--proxy-mode=ipvs"
            ],
            "OnBuild": null,
            "Labels": {
                "io.rancher.rke.container.name": "kube-proxy",
                "org.label-schema.build-date": "2019-11-15T19:01:44Z",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "5ebfef51ddeea5d6b0b2da6e677eda7b1971dbc4",
                "org.label-schema.vcs-url": "https://github.com/rancher/hyperkube.git"
            }
        },

```
Cluster was functional. Ping from each of the pods to other pods on different hosts was also successful.
