### ISSUE TITLE
Permanent container ip is not working

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2375]
Using label `io.rancher.container.requested_ip` to set container ip, doesn't work... Started wit new ip address every time. My use case: stack with webapp and nginx, in-service upgrade shouldn't change ip address of webapp because nginx resolves it service link to ip at first start...
```yml
nginx-conf:
  ...
nginx:
  image: rancher/nginx:1.9.4-2
  expose:
    - 80
  external_links:
    - conf/redis:redis
    - aws-externals/backend-mails:backend
  links:
    - frontend:frontend
  volumes_from:
    - nginx-conf
  restart: always
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: nginx-conf
frontend-conf:
  ...
frontend:
  image: frontend-image
  expose:
    - 8081
  external_links:
    - conf/redis:redis
    - aws-externals/backend-mails:backend
  volumes_from:
    - frontend-conf
  environment:
    NODE_ENV: production
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: frontend-conf
    io.rancher.container.requested_ip: 10.42.187.244

```
