### ISSUE TITLE
Data-only container constantly restarting

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#2376]
I set up some data only containers as sidekicks, and for some reason they continually restart. The app still works, so it's not too concerning, but I do wonder why it's happening. Here's what it looks like in docker-compose.yml:
````sh
ps-mongo-data:
  image: busybox
  volumes:
    - /data/db
ps-mongo:
  image: mongo
  labels:
    io.rancher.sidekicks: ps-mongo-data
  volumes_from:
    - ps-mongo-data
  ports:
    - "3001:27017"
# more stuff that's not relevant continues...
````

**Comment by deniseschannon** [comment]
You need to add in `tty: true` to your busybox container. 

```
ps-mongo-data:
  image: busybox
  volumes: 
     - /data/db
   tty: true
```

**Comment by deniseschannon** [comment]
@alena1108 pointed out that since it's a data container, you can add this label to cause the container to only start once and stay stopped.

```
ps-mongo-data:
  image: busybox
  volumes: 
     - /data/db
  labels:
    io.rancher.container.start_once: true
```
