### ISSUE TITLE
Allow wildcard domain in Global DNS

### ISSUE THREAD

**Issue by daanemanz** [rancher/rancher#23779]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
* Create new Global DNS entry
* Enter FQDN with asterisk (*) to indicate a wildcard domain
* Click `Create` to save the entry

**Result:**
The UI complains that the FQDN contains an invalid character:
![image](https://user-images.githubusercontent.com/1002090/67901578-84236600-fb3d-11e9-8e87-6fb32914ebb6.png)

No record is created.

**Other details that may be helpful:**
Wildcard domains are valid DNS entries, so those should be allowed in Global DNS.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.1
- Installation option (single install/HA): HA

**Comment by spencergilbert** [comment]
This appears to be supported by external-dns, so it would be great to understand why we don't have it supported via Rancher

**Comment by vincent99** [comment]
The immediate problem is going to be that the schema for the field says it's of type `hostname`;   `*` is not a valid character in a DNS label (or any _real_ DNS entry, wildcards are fake virtual records), so the UI is correctly validating it given what it's told.

**Comment by daanemanz** [comment]
Update: I was able to create a new `GlobalDns` resource by applying this resource directly, thus circumventing the hostname validation:
```
apiVersion: management.cattle.io/v3
kind: GlobalDns
metadata:
  name: wildcard-example-com
  namespace: cattle-global-data
spec:
  fqdn: '*.example.com'
  projectNames:
  - c-xxxxx:p-xxxxx
  providerName: cattle-global-data:example-com
  ttl: 300
status:
  clusterEndpoints:
    c-xxxxx: []
```

External DNS ate it up and created a wildcard record as expected.
