### ISSUE TITLE
values.yaml in Helm Chart not updating 

### ISSUE THREAD

**Issue by ilhaan** [rancher/rancher#23794]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 
1. In a helm chart for my application, I add the following values for `ingress` in `values.yaml`: 
```
ingress:
  enabled: true
  annotations:
    rancher.io/globalDNS.hostname: <cooldnshostname>
  hosts:
    - host: <cooldnshostname>
      paths: []
```
2. I update my helm repo and then try to launch this app on Rancher via the UI. Under the "Global" menu, I navigate to Apps -> Launch -> Select my custom catalog -> Click "View Details" for my app -> scroll down and click "PREVIEW". This shows me the `values.yaml` that Rancher has imported and it includes the following for `ingress`: 
```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
```

**Result:**
These are not the values that I defined in my helm chart (shown in step 1 above) and these seem to be the default values that are generated when you run `helm create <chart-name>`. 

**Other details that may be helpful:**
In order to make sure that an old version of my chart wasn't being cached somewhere, I updated the `description` in `Chart.yaml` and pushed that to my helm chart repo and that showed up on Rancher, so some sort of caching error can be ruled out. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): HA

**Questions**: 
* Does Rancher not support `ingress` values from helm charts? I am trying to define these for applications that I want to deploy in multiple clusters. 
* If this is not supported, is there some workaround that I can use to overcome this issue?
