### ISSUE TITLE
secrets_encryption_config  - Disabling custom config results in error in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#23835]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Enable custom config in an exiting rke cluster.
- Edit cluster, Add this in the YAML file

```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: RTczRjFDODMwQzAyMDVBREU4NDJ<....>
          - identity: {}
```

- On clicking Save, cluster is provisioned again, goes into Updating state and comes up Active.
- The secrets are seen encrypted on the etcd

```
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 0a 6b  |s/default/test.k|
00000020  38 73 3a 65 6e 63 3a 61  65 73 63 62 63 3a 76 31  |8s:enc:aescbc:v1|
00000030  3a 6b 2d 66 77 35 68 6e  3a b0 9f 5e 03 cb c6 0e  |:k-fw5hn:..^....|
00000040  d7 f8 34 a3 0a 98 47 25  a0 64 2f c5 45 9f 77 0c  |..4...G%.d/.E.w.|
00000050  d8 52 9f bc 2e 48 7f e1  4f b1 bf f2 bd 73 31 51  |.R...H..O....s1Q|
00000060  f2 3d 8d 00 0a 2b 44 79  b2 ee ec 04 2f 01 f9 a5  |.=...+Dy..../...|
00000070  20 00 e2 bb 4e 24 a0 c5  fe 2b ca bc 48 b8 d5 00  | ...N$...+..H...|
00000080  7b 17 00 a9 7d b0 a1 df  30 f1 9b bb 3f 5d 00 c3  |{...}...0...?]..|
00000090  cb 1a 6a 3a 55 7c cc b8  c7 41 76 7a c6 c0 48 e4  |..j:U|...Avz..H.|
000000a0  05 9e 5c d7 27 5e 98 75  a7 de 26 65 91 03 69 e7  |..\.'^.u..&e..i.|
000000b0  2e ea f0 9f 7c 54 7e 2f  b6 a1 4b 78 f6 9e 40 e3  |....|T~/..Kx..@.|
000000c0  c0 9e 9b 09 d4 eb bd 9b  3c 43 7a 2b ea 71 51 6f  |........<Cz+.qQo|
000000d0  81 ec 0e c0 a4 94 d5 94  a0 05 3e 5d 5b d6 e1 bc  |..........>][...|
000000e0  c1 74 60 cc 82 fd 1e 4f  e3 a7 d3 7d 8f c1 42 1a  |.t`....O...}..B.|
000000f0  0e f8 cc 24 fa 6b 19 fb  97 5d f2 df a7 d3 64 a3  |...$.k...]....d.|
00000100  dd 80 df 83 f2 e0 8f 86  3a e0 4d 4b 35 f6 5c 2b  |........:.MK5.\+|
00000110  12 01 93 be f5 3d 11 54  32 f7 c8 22 dc 12 2c 45  |.....=.T2.."..,E|
00000120  ca e2 e0 8b 69 6d ea fa  17 1d 79 1c 67 65 17 4d  |....im....y.ge.M|
00000130  95 27 30 1f d4 b2 cf 28  52 9b c5 bb af 76 15 d1  |.'0....(R....v..|
00000140  e8 f4 a8 16 06 fc bc 18  0e 9c 4e 5f 26 49 a9 9e  |..........N_&I..|
00000150  7f 22 85 f6 28 5c 6f 76  85 a5 fb 4e f9 8d f3 60  |."..(\ov...N...`|
00000160  09 0d e9 9e 29 d0 09 9c  37 95 23 99 e2 fa f8 5b  |....)...7.#....[|
00000170  b7 b4 7f 50 ce 41 02 13  b4 28 4b a6 8d 2c d6 a2  |...P.A...(K..,..|
00000180  bc 51 72 5b 8c 29 2f a1  e8 0a                    |.Qr[.)/...|
0000018a
```

- `encryption.yaml` file on the control plane node is

```
root@santest114c1:/etc/kubernetes/ssl# cat encryption.yaml 
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - aescbc:
      keys:
      - name: k-fw5hn
        secret: RTczRjFDODMwQzAyMDVBREU4NDJBMU<....>
  - identity: {}
  resources:
  - secrets
```

- Now Move identity: {} to the top of the providers list, so your config looks as follows:

```
      secrets_encryption_config:
        custom_config:
          api_version: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
            - Providers:
                - Identity: {}
                - AESCBC:
                    Keys:
                      - Name: k-fw5hn
                        Secret: RTczRjFDODMwQzAyMDV<....>
                  AESGCM: null
                  Identity: null
                  KMS: null
                  Secretbox: null
                - AESCBC: null
                  AESGCM: null
                  KMS: null
                  Secretbox: null
              Resources:
                - secrets
        enabled: true
```

- Click on Save. cluster is provisioned again, goes into Updating state and comes up Active.
- The secrets are seen encrypted on the etcd

```
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 0a 6b  |s/default/test.k|
00000020  38 73 3a 65 6e 63 3a 61  65 73 63 62 63 3a 76 31  |8s:enc:aescbc:v1|
00000030  3a 6b 2d 66 77 35 68 6e  3a b0 9f 5e 03 cb c6 0e  |:k-fw5hn:..^....|
00000040  d7 f8 34 a3 0a 98 47 25  a0 64 2f c5 45 9f 77 0c  |..4...G%.d/.E.w.|
00000050  d8 52 9f bc 2e 48 7f e1  4f b1 bf f2 bd 73 31 51  |.R...H..O....s1Q|
00000060  f2 3d 8d 00 0a 2b 44 79  b2 ee ec 04 2f 01 f9 a5  |.=...+Dy..../...|
00000070  20 00 e2 bb 4e 24 a0 c5  fe 2b ca bc 48 b8 d5 00  | ...N$...+..H...|
00000080  7b 17 00 a9 7d b0 a1 df  30 f1 9b bb 3f 5d 00 c3  |{...}...0...?]..|
00000090  cb 1a 6a 3a 55 7c cc b8  c7 41 76 7a c6 c0 48 e4  |..j:U|...Avz..H.|
000000a0  05 9e 5c d7 27 5e 98 75  a7 de 26 65 91 03 69 e7  |..\.'^.u..&e..i.|
000000b0  2e ea f0 9f 7c 54 7e 2f  b6 a1 4b 78 f6 9e 40 e3  |....|T~/..Kx..@.|
000000c0  c0 9e 9b 09 d4 eb bd 9b  3c 43 7a 2b ea 71 51 6f  |........<Cz+.qQo|
000000d0  81 ec 0e c0 a4 94 d5 94  a0 05 3e 5d 5b d6 e1 bc  |..........>][...|
000000e0  c1 74 60 cc 82 fd 1e 4f  e3 a7 d3 7d 8f c1 42 1a  |.t`....O...}..B.|
000000f0  0e f8 cc 24 fa 6b 19 fb  97 5d f2 df a7 d3 64 a3  |...$.k...]....d.|
00000100  dd 80 df 83 f2 e0 8f 86  3a e0 4d 4b 35 f6 5c 2b  |........:.MK5.\+|
00000110  12 01 93 be f5 3d 11 54  32 f7 c8 22 dc 12 2c 45  |.....=.T2.."..,E|
00000120  ca e2 e0 8b 69 6d ea fa  17 1d 79 1c 67 65 17 4d  |....im....y.ge.M|
00000130  95 27 30 1f d4 b2 cf 28  52 9b c5 bb af 76 15 d1  |.'0....(R....v..|
00000140  e8 f4 a8 16 06 fc bc 18  0e 9c 4e 5f 26 49 a9 9e  |..........N_&I..|
00000150  7f 22 85 f6 28 5c 6f 76  85 a5 fb 4e f9 8d f3 60  |."..(\ov...N...`|
00000160  09 0d e9 9e 29 d0 09 9c  37 95 23 99 e2 fa f8 5b  |....)...7.#....[|
00000170  b7 b4 7f 50 ce 41 02 13  b4 28 4b a6 8d 2c d6 a2  |...P.A...(K..,..|
00000180  bc 51 72 5b 8c 29 2f a1  e8 0a                    |.Qr[.)/...|
0000018a
```

- `encryption.yaml` file looks like

```
root@santest114c1:/etc/kubernetes/ssl# cat encryption.yaml 
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - identity: {}
  - aescbc:
      keys:
      - name: k-fw5hn
        secret: RTczRjFDODMwQzAyMDVBREU4NDJ<...>
  - {}
  resources:
  - secrets
```

- Remove secrets_encryption_config directive from cluster.yml
- The cluster goes into updating state and fails to come up.
Error: `Error getting secret: illegal base64 data at input byte 3`

<img width="1290" alt="Screen Shot 2019-11-01 at 2 11 02 AM" src="https://user-images.githubusercontent.com/26032343/67985613-39920e80-fc4f-11e9-90cd-989944265ac7.png">

- encryption.yaml file is deleted on the control plane now.
- And the secrets are still see encrypted
```
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 0a 6b  |s/default/test.k|
00000020  38 73 3a 65 6e 63 3a 61  65 73 63 62 63 3a 76 31  |8s:enc:aescbc:v1|
00000030  3a 6b 2d 66 77 35 68 6e  3a b0 9f 5e 03 cb c6 0e  |:k-fw5hn:..^....|
00000040  d7 f8 34 a3 0a 98 47 25  a0 64 2f c5 45 9f 77 0c  |..4...G%.d/.E.w.|
00000050  d8 52 9f bc 2e 48 7f e1  4f b1 bf f2 bd 73 31 51  |.R...H..O....s1Q|
00000060  f2 3d 8d 00 0a 2b 44 79  b2 ee ec 04 2f 01 f9 a5  |.=...+Dy..../...|
00000070  20 00 e2 bb 4e 24 a0 c5  fe 2b ca bc 48 b8 d5 00  | ...N$...+..H...|
00000080  7b 17 00 a9 7d b0 a1 df  30 f1 9b bb 3f 5d 00 c3  |{...}...0...?]..|
00000090  cb 1a 6a 3a 55 7c cc b8  c7 41 76 7a c6 c0 48 e4  |..j:U|...Avz..H.|
000000a0  05 9e 5c d7 27 5e 98 75  a7 de 26 65 91 03 69 e7  |..\.'^.u..&e..i.|
000000b0  2e ea f0 9f 7c 54 7e 2f  b6 a1 4b 78 f6 9e 40 e3  |....|T~/..Kx..@.|
000000c0  c0 9e 9b 09 d4 eb bd 9b  3c 43 7a 2b ea 71 51 6f  |........<Cz+.qQo|
000000d0  81 ec 0e c0 a4 94 d5 94  a0 05 3e 5d 5b d6 e1 bc  |..........>][...|
000000e0  c1 74 60 cc 82 fd 1e 4f  e3 a7 d3 7d 8f c1 42 1a  |.t`....O...}..B.|
000000f0  0e f8 cc 24 fa 6b 19 fb  97 5d f2 df a7 d3 64 a3  |...$.k...]....d.|
00000100  dd 80 df 83 f2 e0 8f 86  3a e0 4d 4b 35 f6 5c 2b  |........:.MK5.\+|
00000110  12 01 93 be f5 3d 11 54  32 f7 c8 22 dc 12 2c 45  |.....=.T2.."..,E|
00000120  ca e2 e0 8b 69 6d ea fa  17 1d 79 1c 67 65 17 4d  |....im....y.ge.M|
00000130  95 27 30 1f d4 b2 cf 28  52 9b c5 bb af 76 15 d1  |.'0....(R....v..|
00000140  e8 f4 a8 16 06 fc bc 18  0e 9c 4e 5f 26 49 a9 9e  |..........N_&I..|
00000150  7f 22 85 f6 28 5c 6f 76  85 a5 fb 4e f9 8d f3 60  |."..(\ov...N...`|
00000160  09 0d e9 9e 29 d0 09 9c  37 95 23 99 e2 fa f8 5b  |....)...7.#....[|
00000170  b7 b4 7f 50 ce 41 02 13  b4 28 4b a6 8d 2c d6 a2  |...P.A...(K..,..|
00000180  bc 51 72 5b 8c 29 2f a1  e8 0a                    |.Qr[.)/...|
0000018a
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head - latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
v1.14.8
```

**Comment by alena1108** [comment]
@sangeethah With the fix, you disable custom encryption config the same way you'd disable the default one - by simply removing `secrets_encryption_config` from the cluster.yml

**Comment by sangeethah** [comment]
Tested with latest build from `v2.3-head` - `add7bda8f`

Create a 3 node cluster with default configuration ( with no secrets_encryption_config section set).

Create secret - test1.
There is no `/etc/kubernetes/ssl/encryption.yaml` in control plane node.
There is no encryption ket set for secrets.
Check the following within etcd container.
```
root@santestnew1:~# docker exec -it etcd sh
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test1 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 31 0a  |s/default/test1.|
00000020  6b 38 73 00 0a 0c 0a 02  76 31 12 06 53 65 63 72  |k8s.....v1..Secr|
00000030  65 74 12 a1 02 0a 85 02  0a 05 74 65 73 74 31 12  |et........test1.|
00000040  00 1a 07 64 65 66 61 75  6c 74 22 00 2a 24 34 66  |...default".*$4f|
00000050  64 39 38 32 32 37 2d 31  34 34 32 2d 34 66 66 38  |d98227-1442-4ff8|
00000060  2d 62 33 38 30 2d 34 36  35 35 37 65 39 34 61 39  |-b380-46557e94a9|
00000070  33 33 32 00 38 00 42 08  08 b3 d8 93 ee 05 10 00  |332.8.B.........|
00000080  62 27 0a 19 66 69 65 6c  64 2e 63 61 74 74 6c 65  |b'..field.cattle|
00000090  2e 69 6f 2f 63 72 65 61  74 6f 72 49 64 12 0a 75  |.io/creatorId..u|
000000a0  73 65 72 2d 6d 39 68 36  66 62 2c 0a 19 66 69 65  |ser-m9h6fb,..fie|
000000b0  6c 64 2e 63 61 74 74 6c  65 2e 69 6f 2f 70 72 6f  |ld.cattle.io/pro|
000000c0  6a 65 63 74 49 64 12 0f  63 2d 71 6c 34 36 32 3a  |jectId..c-ql462:|
000000d0  70 2d 34 78 6d 62 74 62  3c 0a 34 6c 69 66 65 63  |p-4xmbtb<.4lifec|
000000e0  79 63 6c 65 2e 63 61 74  74 6c 65 2e 69 6f 2f 63  |ycle.cattle.io/c|
000000f0  72 65 61 74 65 2e 73 65  63 72 65 74 73 43 6f 6e  |reate.secretsCon|
00000100  74 72 6f 6c 6c 65 72 5f  63 2d 71 6c 34 36 32 12  |troller_c-ql462.|
00000110  04 74 72 75 65 62 24 0a  1c 73 65 63 72 65 74 2e  |.trueb$..secret.|
00000120  75 73 65 72 2e 63 61 74  74 6c 65 2e 69 6f 2f 73  |user.cattle.io/s|
00000130  65 63 72 65 74 12 04 74  72 75 65 7a 00 12 0f 0a  |ecret..truez....|
00000140  05 74 65 73 74 31 12 06  76 61 6c 75 65 31 1a 06  |.test1..value1..|
00000150  4f 70 61 71 75 65 1a 00  22 00 0a                 |Opaque.."..|
0000015b
```
Edit cluster.yml and set `secrets_encryption_config` using custom key as follows:
```
      secrets_encryption_config:
        enabled: true
        custom_config:
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
          - resources:
            - secrets
            providers:
            - aescbc:
                keys:
                - name: k-fw5hn
                   secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
            - identity: {}
```

Cluster gets updated.
There is  `/etc/kubernetes/ssl/encryption.yaml` in control plane node with the correct key and secret set.
```
root@santestnew1:/etc/kubernetes/ssl# cat encryption.yaml 
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - aescbc:
      keys:
      - name: k-fw5hn
        secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
  - identity: {}
  resources:
  - secrets
```
There is  encryption ket set for existing secrets and new secrets that get created.
Check the following within etcd container.

```
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test1 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 31 0a  |s/default/test1.|
00000020  6b 38 73 3a 65 6e 63 3a  61 65 73 63 62 63 3a 76  |k8s:enc:aescbc:v|
00000030  31 3a 6b 2d 66 77 35 68  6e 3a 08 44 79 6e d1 fe  |1:k-fw5hn:.Dyn..|
00000040  72 af 36 6f 9a 93 29 2a  f7 c2 48 3b 58 71 81 fa  |r.6o..)*..H;Xq..|
00000050  98 90 01 f1 20 93 9a 01  94 9b a6 ec d3 69 9c c8  |.... ........i..|
00000060  68 be 21 fe 93 1e f6 d6  aa fa 57 e5 3e 3b ee 14  |h.!.......W.>;..|
00000070  7b e2 7b ac 1f 00 24 da  9d cc 98 e0 86 f2 56 3d  |{.{...$.......V=|
00000080  32 3f 46 a2 11 3b 3a 7e  a0 cf 92 96 7f 27 54 e3  |2?F..;:~.....'T.|
00000090  74 73 7e 56 6e 88 bc 55  a3 03 4f 8b 49 17 e0 26  |ts~Vn..U..O.I..&|
000000a0  6f f8 65 85 17 45 6d df  c5 82 53 57 a9 53 61 4d  |o.e..Em...SW.SaM|
000000b0  8e c6 9d ff 54 02 d0 41  57 12 72 8c 31 59 6f fe  |....T..AW.r.1Yo.|
000000c0  b0 bf 42 ba 0f 25 88 33  3e 5a 62 19 e9 89 25 76  |..B..%.3>Zb...%v|
000000d0  a8 da 70 4c 19 d1 59 a3  df d1 d9 b5 9e 2d 7e 5b  |..pL..Y......-~[|
000000e0  d0 32 64 cb 42 6d 4a 3a  96 e2 86 fd 97 18 f1 be  |.2d.BmJ:........|
000000f0  87 34 ff d8 47 90 a4 9c  fc 0f 18 f4 4d 6a d4 ac  |.4..G.......Mj..|
00000100  80 9e 16 b2 49 1a 98 81  be 4e ec cf 9c a4 8e 78  |....I....N.....x|
00000110  73 4c c1 2a d4 bc d4 e6  48 f0 09 2b 25 20 8d e4  |sL.*....H..+% ..|
00000120  fb 39 8a 81 43 93 d9 e3  c2 8f d2 a4 18 50 6c 61  |.9..C........Pla|
00000130  21 77 74 22 18 21 c6 f7  7f c4 81 d8 12 7d b5 54  |!wt".!.......}.T|
00000140  f1 60 ca 80 d5 d6 06 73  38 f4 6a c3 94 e2 58 68  |.`.....s8.j...Xh|
00000150  b4 65 5d a6 bb e7 2f 11  32 41 ae 2a 5e b8 cd 9b  |.e].../.2A.*^...|
00000160  72 1e 14 e2 33 d7 a1 2e  8b c5 ea fd cd 53 80 be  |r...3........S..|
00000170  7c 15 ff d2 e1 96 d2 1e  42 0f 64 d9 e1 82 a7 68  ||.......B.d....h|
00000180  29 88 9b 94 7e 4f 8d ee  31 0a 0a                 |)...~O..1..|
0000018b
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test2 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 32 0a  |s/default/test2.|
00000020  6b 38 73 3a 65 6e 63 3a  61 65 73 63 62 63 3a 76  |k8s:enc:aescbc:v|
00000030  31 3a 6b 2d 66 77 35 68  6e 3a b9 44 fb d7 cd 1c  |1:k-fw5hn:.D....|
00000040  63 db ed 7e 2a 7f dd 9b  41 ee 2d 4a 30 38 7d 06  |c..~*...A.-J08}.|
00000050  67 9f eb f2 4c 68 74 e6  1b 81 cc 1d 0b af 35 a4  |g...Lht.......5.|
00000060  21 97 e6 92 11 e4 de 81  0b ba c2 b1 94 ef 7a 38  |!.............z8|
00000070  5e 0f 48 65 bf 42 15 c9  46 5a 92 f7 75 89 33 e9  |^.He.B..FZ..u.3.|
00000080  c2 9d 9a 52 72 1c 8e 86  21 99 bd ae 75 74 53 21  |...Rr...!...utS!|
00000090  25 4b 94 f7 64 f9 89 a8  ed bc e9 cf 26 e1 2e 95  |%K..d.......&...|
000000a0  56 8d 8f 0a 08 b9 15 0e  53 3b e2 62 81 15 33 1a  |V.......S;.b..3.|
000000b0  94 12 b4 73 2d b0 c3 4a  52 cb c9 db 95 5a 6b fd  |...s-..JR....Zk.|
000000c0  2d 23 87 31 12 1d 7a 78  ef a2 1a 63 5b 6d e5 00  |-#.1..zx...c[m..|
000000d0  de e8 8b ef aa 6a eb b0  0d 9f 11 6e 24 ac 99 e3  |.....j.....n$...|
000000e0  cf 2b 09 36 5d 90 14 a1  cc 21 da e5 1c 96 5d e2  |.+.6]....!....].|
000000f0  a0 4b b4 ee 1b b5 7a 47  cf e7 06 e1 89 79 c5 69  |.K....zG.....y.i|
00000100  6c fa 0c aa 58 01 ef f6  8f a2 f4 8e f1 73 e6 26  |l...X........s.&|
00000110  b2 51 49 77 96 4f af 79  7d a8 c5 4e e6 6f b2 98  |.QIw.O.y}..N.o..|
00000120  7f d5 0f 61 7b 94 d7 17  5f 06 81 26 a0 6d 28 01  |...a{..._..&.m(.|
00000130  42 12 25 96 aa b5 96 e2  27 fa 14 fe 1d c3 4c d7  |B.%.....'.....L.|
00000140  b6 ab 36 94 cb 27 0a db  1a ab b3 91 a0 e4 42 44  |..6..'........BD|
00000150  b6 00 e9 78 3a c5 b7 ce  0e bf a0 2e 44 e7 f7 2f  |...x:.......D../|
00000160  4e 16 18 0b 40 6d 45 db  c3 5f fc e9 ec d1 5e b4  |N...@mE.._....^.|
00000170  ad 19 53 8d 8b 0f 95 10  e0 1d 49 3c 85 8b b7 59  |..S.......I<...Y|
00000180  08 aa 45 6e 9b f8 ca 35  a0 39 0a                 |..En...5.9.|
0000018b
```
Edit cluster.yml and remove the `secrets_encryption_config` .
This results in cluster getting updated.
There is no `/etc/kubernetes/ssl/encryption.yaml` in control plane node anymore.

There is no encryption ket set for existing secrets and new secret created as expected.
Check the following within etcd container.
```
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test1 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 31 0a  |s/default/test1.|
00000020  6b 38 73 00 0a 0c 0a 02  76 31 12 06 53 65 63 72  |k8s.....v1..Secr|
00000030  65 74 12 a1 02 0a 85 02  0a 05 74 65 73 74 31 12  |et........test1.|
00000040  00 1a 07 64 65 66 61 75  6c 74 22 00 2a 24 34 66  |...default".*$4f|
00000050  64 39 38 32 32 37 2d 31  34 34 32 2d 34 66 66 38  |d98227-1442-4ff8|
00000060  2d 62 33 38 30 2d 34 36  35 35 37 65 39 34 61 39  |-b380-46557e94a9|
00000070  33 33 32 00 38 00 42 08  08 b3 d8 93 ee 05 10 00  |332.8.B.........|
00000080  62 27 0a 19 66 69 65 6c  64 2e 63 61 74 74 6c 65  |b'..field.cattle|
00000090  2e 69 6f 2f 63 72 65 61  74 6f 72 49 64 12 0a 75  |.io/creatorId..u|
000000a0  73 65 72 2d 6d 39 68 36  66 62 2c 0a 19 66 69 65  |ser-m9h6fb,..fie|
000000b0  6c 64 2e 63 61 74 74 6c  65 2e 69 6f 2f 70 72 6f  |ld.cattle.io/pro|
000000c0  6a 65 63 74 49 64 12 0f  63 2d 71 6c 34 36 32 3a  |jectId..c-ql462:|
000000d0  70 2d 34 78 6d 62 74 62  3c 0a 34 6c 69 66 65 63  |p-4xmbtb<.4lifec|
000000e0  79 63 6c 65 2e 63 61 74  74 6c 65 2e 69 6f 2f 63  |ycle.cattle.io/c|
000000f0  72 65 61 74 65 2e 73 65  63 72 65 74 73 43 6f 6e  |reate.secretsCon|
00000100  74 72 6f 6c 6c 65 72 5f  63 2d 71 6c 34 36 32 12  |troller_c-ql462.|
00000110  04 74 72 75 65 62 24 0a  1c 73 65 63 72 65 74 2e  |.trueb$..secret.|
00000120  75 73 65 72 2e 63 61 74  74 6c 65 2e 69 6f 2f 73  |user.cattle.io/s|
00000130  65 63 72 65 74 12 04 74  72 75 65 7a 00 12 0f 0a  |ecret..truez....|
00000140  05 74 65 73 74 31 12 06  76 61 6c 75 65 31 1a 06  |.test1..value1..|
00000150  4f 70 61 71 75 65 1a 00  22 00 0a                 |Opaque.."..|
0000015b
/ # ETCDCTL_API=3 etcdctl get /registry/secrets/default/test2 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 32 0a  |s/default/test2.|
00000020  6b 38 73 00 0a 0c 0a 02  76 31 12 06 53 65 63 72  |k8s.....v1..Secr|
00000030  65 74 12 a1 02 0a 85 02  0a 05 74 65 73 74 32 12  |et........test2.|
00000040  00 1a 07 64 65 66 61 75  6c 74 22 00 2a 24 62 37  |...default".*$b7|
00000050  38 35 62 31 66 30 2d 64  65 34 61 2d 34 63 33 62  |85b1f0-de4a-4c3b|
00000060  2d 39 64 66 65 2d 62 66  63 36 61 37 30 37 62 35  |-9dfe-bfc6a707b5|
00000070  62 32 32 00 38 00 42 08  08 da e0 93 ee 05 10 00  |b22.8.B.........|
00000080  62 27 0a 19 66 69 65 6c  64 2e 63 61 74 74 6c 65  |b'..field.cattle|
00000090  2e 69 6f 2f 63 72 65 61  74 6f 72 49 64 12 0a 75  |.io/creatorId..u|
000000a0  73 65 72 2d 6d 39 68 36  66 62 2c 0a 19 66 69 65  |ser-m9h6fb,..fie|
000000b0  6c 64 2e 63 61 74 74 6c  65 2e 69 6f 2f 70 72 6f  |ld.cattle.io/pro|
000000c0  6a 65 63 74 49 64 12 0f  63 2d 71 6c 34 36 32 3a  |jectId..c-ql462:|
000000d0  70 2d 34 78 6d 62 74 62  3c 0a 34 6c 69 66 65 63  |p-4xmbtb<.4lifec|
000000e0  79 63 6c 65 2e 63 61 74  74 6c 65 2e 69 6f 2f 63  |ycle.cattle.io/c|
000000f0  72 65 61 74 65 2e 73 65  63 72 65 74 73 43 6f 6e  |reate.secretsCon|
00000100  74 72 6f 6c 6c 65 72 5f  63 2d 71 6c 34 36 32 12  |troller_c-ql462.|
00000110  04 74 72 75 65 62 24 0a  1c 73 65 63 72 65 74 2e  |.trueb$..secret.|
00000120  75 73 65 72 2e 63 61 74  74 6c 65 2e 69 6f 2f 73  |user.cattle.io/s|
00000130  65 63 72 65 74 12 04 74  72 75 65 7a 00 12 0f 0a  |ecret..truez....|
00000140  05 74 65 73 74 32 12 06  76 61 6c 75 65 32 1a 06  |.test2..value2..|
00000150  4f 70 61 71 75 65 1a 00  22 00 0a                 |Opaque.."..|
0000015b
/ # 
```
