### ISSUE TITLE
Log driver/log opts to exported .yml file

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2388]
log_driver and log_opts are not being set in exported .yml

**Comment by prachidamle** [comment]
rancher-compose docs.

**Comment by deniseschannon** [comment]
Verified in v0.63.0-rc1 that these are in the exported yml.

Added stack with the following docker-compose.yml
```
foo:
  image: nginx
  log_driver: json-file
  log_opt:
    labels: foo
```

UI shows:

```
foo:
  log_driver: json-file
  labels:
    io.rancher.service.hash: 0fd07371c18910c49365a2853b946d309bbba3e3
  log_opt:
    labels: foo
  image: nginx
```
