### ISSUE TITLE
[forwardport] secrets_encryption_config - rotate custom config does not work

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23900]
Forwardport https://github.com/rancher/rancher/issues/23836

**Comment by sowmyav27** [comment]
**Verified on master-head latest - commit id: `6ef25c42c`**

- Create a 3 node cluster - 1 etcd, 1 worker and 1 control node. 
- `custom_config section` in `secrets_encryption_config` is set.
```
secrets_encryption_config:
        enabled: true
        custom_config:
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
          - resources:
            - secrets
            providers:
            - aescbc:
                keys:
                - name: k-fw5hn
                   secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
            - identity: {}
```
- Existing and new secrets are encrypted.
```
ETCDCTL_API=3 etcdctl get /registry/secrets/default/test4 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 34 0a  |s/default/test4.|
00000020  6b 38 73 3a 65 6e 63 3a  61 65 73 63 62 63 3a 76  |k8s:enc:aescbc:v|
00000030  31 3a 6b 2d 66 77 35 68  6e 3a 22 0b 1e 12 6a 74  |1:k-fw5hn:"...jt|
00000040  0c 63 d6 51 59 b0 e6 9c  d1 be ed 1f e3 5b 20 57  |.c.QY........[ W|
00000050  c0 43 51 34 45 76 e5 d0  55 17 99 bc f0 a9 51 ef  |.CQ4Ev..U.....Q.|
00000060  64 0f 55 01 69 9f 71 4b  b5 29 d3 72 e1 3b c9 77  |d.U.i.qK.).r.;.w|
00000070  d7 e3 51 83 1b db 6f b8  6b 01 75 ea aa f4 6b 68  |..Q...o.k.u...kh|
00000080  a8 dd 96 9e 7f 15 be 6c  f4 04 2a c4 2c dd 0b 3c  |.......l..*.,..<|
00000090  e8 ba de b5 79 de bd d9  fe 13 0b ec f2 c0 59 5d  |....y.........Y]|
000000a0  14 5a 39 55 d1 d3 14 54  71 26 f8 7f 4b 53 bc 07  |.Z9U...Tq&..KS..|
000000b0  df 84 17 18 dc 7a b7 04  db be 89 91 18 73 4d d5  |.....z.......sM.|
000000c0  88 06 85 37 41 31 f1 30  80 7d 11 25 24 35 c0 f6  |...7A1.0.}.%$5..|
000000d0  3a 28 eb 13 43 3f 45 22  02 8d 36 41 c8 d2 65 0a  |:(..C?E"..6A..e.|
000000e0  e2 8e 47 1e 59 59 91 60  7b b6 31 e5 6f e8 d2 7d  |..G.YY.`{.1.o..}|
000000f0  da 31 ea 41 6c 02 52 3b  71 17 b7 e0 07 d0 c8 73  |.1.Al.R;q......s|
00000100  98 e0 ed 88 b4 76 31 4c  90 fc fb c2 39 73 de cf  |.....v1L....9s..|
00000110  76 2f 70 5b fd 6b c8 d1  bd a9 c0 48 db a2 e0 0d  |v/p[.k.....H....|
00000120  32 5d 3d 01 25 c4 2f 5f  82 59 19 6d fc ba 50 a2  |2]=.%./_.Y.m..P.|
00000130  6e 8c 0d 5c c0 06 c7 62  eb 4f a8 65 52 d4 8e d5  |n..\...b.O.eR...|
00000140  e8 4a 49 6b f5 25 f5 58  a3 19 79 fc a1 1b c3 89  |.JIk.%.X..y.....|
00000150  86 46 3d 04 92 27 34 7d  9a cd 8f 15 80 77 93 77  |.F=..'4}.....w.w|
00000160  06 57 e7 78 83 94 99 1a  2d b0 79 19 4e 7f 5e 0e  |.W.x....-.y.N.^.|
00000170  d3 df 31 03 6f 42 c0 3d  8f 6c 02 18 71 c3 4a f0  |..1.oB.=.l..q.J.|
00000180  04 ed e5 64 1d f4 d9 31  17 81 0a                 |...d...1...|
0000018b
```
- Edit cluster and change the existing encryption key to `k-hhsfw` in the keys section:
```
            providers:
            - aescbc:
                keys:
                  - name: k-hhsfw
                    secret: ODlENTg0M0VDNTdDREQ5MkREQzg3RTUwOTA2NDE3Nzk=
                - name: k-fw5hn
                   secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
```
- Existing and new secrets starts using the encryption key `k-hhsfw` as expected.
```
ETCDCTL_API=3 etcdctl get /registry/secrets/default/test4 | hexdump -C
00000000  2f 72 65 67 69 73 74 72  79 2f 73 65 63 72 65 74  |/registry/secret|
00000010  73 2f 64 65 66 61 75 6c  74 2f 74 65 73 74 34 0a  |s/default/test4.|
00000020  6b 38 73 3a 65 6e 63 3a  61 65 73 63 62 63 3a 76  |k8s:enc:aescbc:v|
00000030  31 3a 6b 2d 68 68 73 66  77 3a 73 7a cc 1f 97 08  |1:k-hhsfw:sz....|
00000040  82 37 b8 06 7e 7b 77 31  3a 68 42 e4 36 42 d2 be  |.7..~{w1:hB.6B..|
00000050  fa 83 f8 50 af 00 58 95  c0 98 4a 71 7c 3b 5f 1f  |...P..X...Jq|;_.|
00000060  68 b8 a7 91 ff 5b 54 9a  5f 2f 88 be fe fd 70 80  |h....[T._/....p.|
00000070  1a a2 01 7f ab 62 e5 84  44 df c4 16 8b b7 05 01  |.....b..D.......|
00000080  93 fc f7 58 aa ac 44 cc  ea ee 37 88 1c 83 29 66  |...X..D...7...)f|
00000090  6d 52 ca c8 1b a2 4c 8c  58 86 7f 33 66 2e 88 22  |mR....L.X..3f.."|
000000a0  72 da f6 74 73 26 fc cc  cf 42 c4 e7 8e 85 43 29  |r..ts&...B....C)|
000000b0  08 b3 74 d2 28 e2 26 6c  30 69 7d 13 10 a0 56 7a  |..t.(.&l0i}...Vz|
000000c0  c2 da 9c 82 ba 79 0c 11  5d e0 30 d1 e6 63 09 f5  |.....y..].0..c..|
000000d0  24 21 b6 d4 fa 81 18 98  7f 3c 42 aa 22 e9 8f 3c  |$!.......<B."..<|
000000e0  23 4b b9 5c c3 bf 0a bc  76 2a 1c 19 93 03 7e fb  |#K.\....v*....~.|
000000f0  07 29 7a 87 7f ef 6e ff  76 bb 77 20 97 92 db d3  |.)z...n.v.w ....|
00000100  f7 34 ac e5 f4 cc 3c c3  a9 7f d2 18 84 1a cb 73  |.4....<........s|
00000110  6d f9 3f 8d 59 0e c4 a6  03 5b 82 97 76 b1 45 8a  |m.?.Y....[..v.E.|
00000120  c5 55 3f fd f5 7b 79 51  41 e0 84 24 16 f1 fe a8  |.U?..{yQA..$....|
00000130  63 d9 11 11 31 34 38 3f  c0 ec 3a 7f 80 03 df 2d  |c...148?..:....-|
00000140  8c 72 74 d8 d8 d1 dd 4d  07 a4 c4 8e 32 d8 e9 ac  |.rt....M....2...|
00000150  e2 05 6e 64 95 e5 cb 52  59 57 94 ee 79 3f 36 db  |..nd...RYW..y?6.|
00000160  6e bc 4f 7a a9 8b 1a bc  67 23 3d 0d e7 1d d8 9f  |n.Oz....g#=.....|
00000170  09 d6 c3 32 02 db bf af  5a b3 ab 4c 85 05 d1 de  |...2....Z..L....|
00000180  d6 c6 9e f0 64 84 76 03  ce a3 0a                 |....d.v....|
0000018b
```
- Edit cluster and remove the old key `fw5hn` in the keys section:
```
            providers:
            - aescbc:
                keys:
                  - name: k-hhsfw
                    secret: ODlENTg0M0VDNTdDREQ5MkREQzg3RTUwOTA2NDE3Nzk=
```
- Existing and new secrets continue to use the encryption key `k-hhsfw` as expected.
- encryption.yaml file contents: `cat encryption.yaml`
```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - aescbc:
      keys:
      - name: k-hhsfw
        secret: ODlENTg0M0VDNTdDREQ5MkREQzg3RTUwOTA2NDE3Nzk=
  - identity: {}
  resources:
  - secrets
```
