### ISSUE TITLE
[CIS] Add support for current k8s versions of Rancher

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#23906]
Should be able to run the tests for all the k8s versions supported by Rancher.

**Comment by sowmyav27** [comment]
To Test:
- Create 1.15, 1.16, 1.17 clusters
- Run both Hardened/Permissive scans
- Record all the tests results - Pass/Fail/Skipped/n/a

**Comment by izaac** [comment]
Rancher version: `2.4 master-head (03/09/2020)` commit id: 17bd84f8d

All Scans executions were made in a non-CIS compliant cluster.
Benchmark version used: `rke-cis-1.4`
Kubernetes versions:

v1.15.10-rancher1-2
v1.16.7-rancher1-2
v1.17.3-rancher1-2

All k8s versions had the same results.

- Permissive Profile
  - Passed: 57/97
  - Skipped: 21/97
  - Failed: 5/97
  - N/A: 14/97
- Hardened Profile
  - Passed: 62/97
  - Skipped: 0/97
  - Failed: 21/97
  - N/A: 14/97



### cluster.yml used

```yaml
# 
# Cluster Config
# 
default_pod_security_policy_template_id: restricted
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: <name>
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: <k8s version here>
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
#
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
network:
  options:
    flannel_backend_type: vxlan
  plugin: canal
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
#
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: true
      pod_security_policy: true
      service_node_port_range: 30000-32767
      event_rate_limit:
        enabled: true
      audit_log:
        enabled: true
      secrets_encryption_config:
        enabled: true
      extra_args:
        anonymous-auth: "false"
        profiling: "false"
        service-account-lookup: "true"
        enable-admission-plugins: "ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,DenyEscalatingExec,NodeRestriction,EventRateLimit,PodSecurityPolicy"
        tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
      extra_binds:
        - "/opt/kubernetes:/opt/kubernetes"
    kubelet:
      generate_serving_certificate: true
      extra_args:
        # protect-kernel-defaults: "true"
    kube-controller:
      extra_args:
        profiling: "false"
        address: "127.0.0.1"
        terminated-pod-gc-threshold: "1000"
        feature-gates: "RotateKubeletServerCertificate=true"
    scheduler:
      extra_args:
        profiling: "false"
        address: "127.0.0.1"
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 60
windows_prefered_cluster: false
```
