### ISSUE TITLE
Scale and upgrade strategy changes for rke system addons 

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#23907]
Change scale and upgrade strategy for the RKE addons.
- [x] Make scale configurable, increase the default number of replicas for coredns, kubedns, metrics-server. Rest of the addons are daemonsets
- [x] Make upgrade strategy configurable for all addons

This involves:
- [x] Add a field for Replicas and UpdateStrategy for addons in rancher/types.
- [x] Accept this field in kontainer-driver-metadata templates
- [x] Update RKE to pass this field into kontainer-driver-metadata templates.
- [x] Test for Rancher provisioned clusters and standalone RKE clusters
- [x] default rancher addons upgrade strategy to k8s defaults for the deployment and daemonset
Should be tested for rancher provisioned clusters and standalone RKE clusters.

https://github.com/rancher/rancher/issues/23038

**Comment by mrajashree** [comment]
The ingress and networking addons are launched as daemonsets. If user doesn't pass any value for their update strategy, kubernetes sets default update strategy to rollingUpdate with maxUnavailable=1
The dns and monitoring addons are launched as deployments. If user doesn't pass any value for their update strategy, kubernetes sets default update strategy to rollingUpdate with maxUnavailable=25% and maxSurge=25%

The replicas field for monitoring deployment is made user configurable and will default to 2.
The dns addons use cluster-proportional-autoscaler which determine their replicas. So for dns, the fields needed for cluster-proportional-autoscaler are made configurable. The default of 2 for this is set in the RKE PR.

**Comment by mrajashree** [comment]
```
sample cluster.yml
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: blah
  role:
  - controlplane
  - etcd
  - worker
  user: rajashree.28m
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/rajashree
ingress:
  provider: nginx
  update_strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 5
network:
  plugin: canal
  update_strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 6
dns:
  provider: coredns
  update_strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 15%
  linear_autoscaler_params:
    cores_per_replica: 0.34
    nodes_per_replica: 4
    prevent_single_point_failure: true
    min: 2 
    max: 3
monitoring:
  provider: metrics-server
  update_strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 8
```
