### ISSUE TITLE
service links missing while creating services

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#2394]
```
Component 	Version
Rancher 	v0.42.0
Cattle 	v0.102.0
User Interface 	v0.57.0
Rancher Compose 	v0.4.3
```
service links were missing for few of the services in the yml shared. For example, for "authentication", there are two links, but only one service link got created.

**Comment by alena1108** [comment]
@ibuildthecloud debugged, looks like compose issue related to links creation and the service creation order. When service "foo" has multiple links, sometimes one of the links - say link to "bar" - is missing.

When I look at the DB, I see that for the missing use case scenario, service "bar" always gets created after service "foo".

Reproducible from time to time.

**Comment by alena1108** [comment]
Debugged some more; the user's .yml file has some indirect circular references for the service that has links missing. Here is the simplified .yml template which allows to constantly reproduce the bug:

```
nginx-lb1:
  image: rancher/load-balancer-service
  links:
  - authentication:authentication

authentication:
  image: nginx
  links:
  - nginx-lb:nginx-lb

nginx-lb:
  image: rancher/load-balancer-service
  stdin_open: true
  links:
  - nginx-lb1:nginx-lb1

```

**Comment by deniseschannon** [comment]
This is actually a duplicate of https://github.com/rancher/rancher/issues/1851.

If you do `rancher-compose create`, you cannot start the services in the UI as the links are missing, but if you do a `rancher-compose start` with the same `docker-compose.yml`, the circular links will get created when the services are started.

Another alternative is to do a `rancher-compose up` and it'll resolve the circular links when the services are started.

**Comment by ibuildthecloud** [comment]
@deniseschannon I'll have this fix in shortly, I have the change, forgot to every push it... sigh... too many things

![](http://vignette1.wikia.nocookie.net/degrassi/images/d/dc/Up-squirrel.gif/revision/latest?cb=20131018110154])

**Comment by deniseschannon** [comment]
Verified with Master with version/commit 4cd0088.

Will be released in the next version of rancher-compose.

**Comment by sangeethah** [comment]
Tested with server version - v0.43.0-rc2

Tried to create a stack with the following docker-compose.yml from UI.
```
nginx-lb1:
  image: rancher/load-balancer-service
  links:
  - authentication:authentication

authentication:
  image: nginx
  links:
  - nginx-lb:nginx-lb

nginx-lb:
  image: rancher/load-balancer-service
  stdin_open: true
  links:
  - nginx-lb1:nginx-lb1
```

authentication service is missing the nginx-lb link.

But when I tried to use the same docker-compose.ml to create a service using rancher-compose version - v0.5.0-rc1 , I see the links getting created as expected.


<img width="1160" alt="screen shot 2015-10-24 at 12 16 19 pm" src="https://cloud.githubusercontent.com/assets/4266958/10712237/5afbf68a-7a49-11e5-972c-79451bcfbf80.png">
