### ISSUE TITLE
Ability to replace Nginx ingress with Istio Ingress

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#24066]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Details:**

A customer would like to be able to run the Istio Ingress on 80/443. Currently this is not an option due to the service port range restrictions/api/etc. They'd like to be able to disable Nginx and then run the the Istio ingress as either a node or host port on 80/443 instead.

**Comment by cbron** [comment]
AFAIK you can't set NodePort to 80/443, we'd have to change the istio-ingressgateway to a daemonset with a hostPort. Not sure thats possible, their [spec for ports](https://istio.io/docs/reference/config/istio.operator.v1alpha1/#ServicePort) doesn't include hostPort option. Perhaps we can use a [patch or overlay](https://preliminary.istio.io/docs/setup/install/istioctl/#configure-gateways) to get around that and do something like the following, but even if we can change it I'm also not sure this (hostPort) is really supported by istio: 
```
kind: IstioOperator
...
spec:
  components:
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: kind
                  value: DaemonSet
```

More info here: https://preliminary.istio.io/docs/setup/install/istioctl/#configure-gateways
