### ISSUE TITLE
Add support for "exec" Credential Plugins for cluster drivers and Rancher Server

### ISSUE THREAD

**Issue by jlamillan** [rancher/rancher#24135]
Many hosted Kubernetes providers have a tool for generating authentication tokens e.g. `aws-iam-authenticator`, `gcloud` , and `oci`. 

However, support for credential plugins does not appear to be available yet for Rancher cluster drivers (e.g. [here](https://github.com/rancher/kontainer-engine/blob/master/store/types.go#L3) and [here](https://github.com/rancher/kontainer-engine/blob/master/types/drivers.pb.go#L331)) or on the Rancher Server side e.g. K8s REST [client config](https://github.com/rancher/rancher/blob/master/pkg/clustermanager/manager.go#L252).

The `exec` property (available in Kubernetes v1.10+) allows as user to define an external command that generates and returns a token, which is used as a bearer token against the API server. e.g.:

```
users:
  - name: <ClusterName>
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: gen-token
        args:
    - --cluster-id
    - <ClusterID>
```

```
{
    "apiVersion": "client.authentication.k8s.io/v1beta1",
    "kind": "ExecCredential",
    "status": {
        "token": "aHR0cHM6Ly9jb250YWluZXJlbmdpbmUudXMtxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMiUyQ3ZlcnNpb24lM0QlMjIxJTIy",
        "expirationTimestamp": "2019-11-16T03:12:18.051067Z"
    }
}
```

The client library reads the above generated token and includes it as a bearer token in the request to the API server.
