### ISSUE TITLE
Feature Request: Ability to specify type of secret

### ISSUE THREAD

**Issue by laxmanpradhan** [rancher/rancher#24240]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
When making a new secret, there is no way to specify a type. For example, when making a secret key for Ceph, you must create a secret of type kubernetes.io/rbd. 

1. Create a secret in any namespace
2. Add a parameter for key = value
3. Add a parameter for type = kubernetes.io/rbd

Creating a secret with type in the parameter does not work. If you view the secret yaml after it has been created, the type is a random string. It should not be in the parameters section regardless. There should be a separate field for this in the GUI to specific the type. If not a specific GUI element for this, there should be a way to directly edit the yaml of the secret that is about to be created. 

This is an example yaml that will correctly create a secret of the correct type:
```
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: <your output from above>
```
but the yaml has to be applied via command line. There should be a way to do this from the GUI. 

**Other details that may be helpful:**
Discussion from the Rancher Forums: https://forums.rancher.com/t/cant-make-a-secret-of-a-specific-type/15910

**Environment information**
- Rancher 2.3.2

gzrancher/rancher#11092
