### ISSUE TITLE
Rancher chart questions/values BUG in lists

### ISSUE THREAD

**Issue by RRadziejewski** [rancher/rancher#24250]
*Hi i just discovered bug with my chart it cannot run due to error with templating.

The fun thing is when i click edit as yaml  and launch the chart it works.

After i add dummy question at the end of questions yaml in my chart it starts to work.

- variable: deployments[0].containers[0].dummy.dummy[0].dummy
  default: '123'
  description: Add your Password
  type: password
  group: Configuration
  label: Enter Password
  show_if: false
  required: true

This is the question i need to add to make it work.

It looks like it's aint passing answers to chart or taking them from values.yaml with normal chart without dummy question.

I attach the chart 
[asfda.zip](https://github.com/rancher/rancher/files/3890704/asfda.zip)

Can somebody take a look at this this look suuuuper weird and i cannot explain this behavior

*

---
|Versions|Rancher `v2.2.9` |

**Comment by Piotrek52** [comment]
I have the same problem

**Comment by loganhz** [comment]
If you are using `Form` generated by `questions.yaml`, it will not send the answers which not show in UI. 

Can you try to remove `show_if: false` and `show_subquestion_if:  false` ?

If you want to hide some answers in UI but pass them to backend, you can use `group: Hidden` for it.

**Comment by RRadziejewski** [comment]
It is okey to not send answers not shown in UI they are present in values.yaml.
Btw this does not make sense can you try chart i uploaded ?
Why adding specific question is making chart launchable ?

**Comment by loganhz** [comment]
do you have a git address for the chart I can use?

**Comment by RRadziejewski** [comment]
No , unfortunately not

**Comment by RRadziejewski** [comment]
Anyone can take a look at this ?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/69713786-1c623a00-1140-11ea-8348-af18b3b49594.png)

Do you mean this error ? @RRadziejewski

**Comment by RRadziejewski** [comment]
Yeah i mean this the answer at this question is inside answers.yaml

**Comment by RRadziejewski** [comment]
I understand show if and group hidden than but why after adding a specific question with some dummy values it starts to work ?

**Comment by RRadziejewski** [comment]
For me this is really weird behaviour it turns out that it's sending sometimes even if i am not showing this specific questions in UI.

**Comment by loganhz** [comment]
After added `questions.yaml` and use Form to deploy app, UI will only pass `deployments[0].containers[0].ports[0].onPort : 36692` to server.

As Rancher is using helm `set` if deploy app in Form instead of `Edit as YAML`,  it will not just patch the answer to `values.yaml`. It will replace the it.

`values.yaml` in your chart.

```
chart:
  appVersion: ''
  description: ''
  icon: ''
  name: asfda
  version: 1.0.0
deployments:
- containers:
  - affinity: {}
    appSandboxEnabled: false
    customResources:
      enablespecificdownload: true
    image:
      repository: razikus/whoami
      tag: slim85
    initContainer:
      init: true
      initImage:
        repository: busybox
        tag: latest
    name: test
    nodeSelector: {}
    ports:
    - containerPort: 85
      onPort: 32766
      protocol: TCP
      type: NodePort
```

Pass `deployments[0].containers[0].ports[0].onPort : 36692` in answers to server and the finally `values.yaml` will be changed to 

```
chart:
  appVersion: ''
  description: ''
  icon: ''
  name: asfda
  version: 1.0.0
deployments:
- containers:
  - ports:
    - onPort: 36692
```
