### ISSUE TITLE
Monitoring - bad formatting of additionalScrapeConfigs answer value in the secret

### ISSUE THREAD

**Issue by adampl** [rancher/rancher#24274]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Go to Tools -> Monitoring
- Click "Show advanced options"
- Add an answer for `prometheus.additionalScrapeConfigs` like this:
```
- job_name: gluster
  static_configs:
  - targets:
    - 10.0.0.101:8080
    - 10.0.0.102:8080
    - 10.0.0.103:8080
- job_name: ceph
  static_configs:
  - targets:
    - 10.0.0.101:9283
    - 10.0.0.102:9283
    - 10.0.0.103:9283`
```
- Press "Save"
- Go to Resources -> Secrets
- Click the "prometheus-project-monitoring-additional-scrape-configs" secret
- View or copy the value of "additional-scrape-configs.yaml"

**Result:**
The secret value looks like this:
```
- job_name: 'federate'
  honor_labels: true
  metrics_path: /federate
  params:
    'match[]':
      - '{__name__=~".+"}'
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  static_configs:
  - targets:
    - prometheus-operated.cattle-prometheus:9090

|-
  - job_name: gluster
    static_configs:
    - targets:
      - 10.0.0.101:8080
      - 10.0.0.102:8080
      - 10.0.0.103:8080
  - job_name: ceph
    static_configs:
    - targets:
      - 10.0.0.101:9283
      - 10.0.0.102:9283
      - 10.0.0.103:9283
```
Note the YAML operator `|-` and additional indentation. As a result, the metrics are not scraped.

When I remove the operator and indent, the metrics are scraped, but changing the monitoring settings will revert the secret back to the bad value.

**Environment information**
- Rancher version: 2.3.2
- Installation option: single install
- Monitoring version: 0.0.5

**Cluster information**
- Cluster type: hosted
- Machine type: metal
- Kubernetes version: 1.15.5
- Docker version: 19.3.3
