### ISSUE TITLE
Rancher health check isn't working correctly for `net: host` services, making it appear as Degraded

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2432]
Versions affected: `0.43.0-rc2` and `0.43.0-rc3`

<img width="626" alt="captura de ecra 2015-10-25 as 00 02 29" src="https://cloud.githubusercontent.com/assets/3604053/10713194/b91a65b4-7aab-11e5-9ba3-39913be64b58.png">

**Comment by deniseschannon** [comment]
@cusspvz I was unable to reproduce. Granted all I tried was to start a service using `net:host` from the UI. It went into active state for both service and stack. 

How did you start your service? Can you provide the docker-compose.yml?

**Comment by cusspvz** [comment]
Absolutely, this is also affecting `v0.43.1`:

`docker-compose.yml`
```yml
turnserver:
  restart: on-failure:10
  ports:
  - 3478:3478/tcp
  - 3478:3478/udp
  environment:
    USE_IPV4: 'true'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: type=haendpoint
  tty: true
  image: bprodoehl/turnserver
  stdin_open: true
  net: host
```

`rancher-compose.yml`
```yaml
turnserver:
  health_check:
    port: 3478
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
```

Checking port with `netcat` (also tried udp just to be sure it was up)
```bash
root@server-hostname:/# nc -v -t localhost 3478                                 
Connection to localhost 3478 port [tcp/*] succeeded!                            
^C                                                                              
root@server-hostname:/# nc -v -u localhost 3478                                 
Connection to localhost 3478 port [udp/*] succeeded!                            
^C                                                                              
root@server-hostname:/#   
```
