### ISSUE TITLE
Provisioning cluster using vSphere driver not working

### ISSUE THREAD

**Issue by agepi477** [rancher/rancher#24320]
Hi,

maybe somebody can help! I'm running a Rancher Server for testing purposes. I already provisioned a custom cluster on 3 custom nodes (all CentOS 7.7 1908 VMs, with Docker 18.09.9) that runs very fine. But trying to provision a Cluster with the vSphere driver is not working.

**my environment**
- Single Node Rancher Test Environment
- Running Rancher `v2.3.2` on CentOS `7.7 1908` and Docker `18.09.9` installed on a VM
- our vSphere Environment is a vSphere `6.7`
- I'm using a recognized CA signed certificate
- The whole system is behind a Proxy
- CloudCredentials for vSphere
- Node Template with vSphere Credentials

This is the Rancher Template section from my Node Template:
![grafik](https://user-images.githubusercontent.com/51784015/69874061-5c4d2c80-12ba-11ea-9e45-b86a61b1c430.png)

My cloud-config.yml file is hosted on a local webserver. The file looks like that:
```
#cloud-config
rancher:
  network:
    http_proxy: http://192.168.100.101:8080
    https_proxy: http://192.168.100.101:8080
    no_proxy: localhost,127.0.0.1,0.0.0.0,.our.domain,172.16.0.0/21

runcmd:
  - echo 172.16.1.245 ranchermgmt.our.domain >> /etc/hosts
    
ssh_authorized_keys:
  - ssh-rsa <my key> me@there
```

I tried it with different amounts of nodes but it always fails with always the same error message.
My last try was a single node with etcd, control plane and worker role on a single node:

`cluster [c-nt6mr] provisioning: Failed to apply the ServiceAccount needed for job execution: Post https://172.16.3.19:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

This is the full log output from the rancher server during the cluster provisioning process:
[rancher.log](https://github.com/rancher/rancher/files/3905514/rancher.log)

After that it starts over and over and doesn´t come to an end.

Thanks in advance

Hendrik
