### ISSUE TITLE
[Enhancement] Istio Multiple Ingress Gateways

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#24394]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Currently when you enable istio you can only have one ingress gateway. Istio allows you to deploy multiple of them and we are needing that capability using the Rancher istio. Our cluster has multiple domains and we segregate those services by ingress gateway.

**Comment by cloudnautique** [comment]
@mitchellmaler, can you elaborate on the use case and/or point to the Istio docs you are referring to so we can make sure we understand the capability being requested.

**Comment by mitchellmaler** [comment]
The rancher deployment of istio only allows a single ingress gateway from the UI. Looking at the chart at https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.1.1/charts/gateways/values.yaml#L10 you only provide a single ingress gateway object (the default one in the istio chart values). Istio allows you to create multiple ingress gateways under the gateways.NAME where you don't have to even use the default one if you disable it like gateways.istio-ingressgateway.enabled=false. Currently in my deployment of istio we deploy multiple gateways istio-ingressgateway.domain1, istio-ingressgateway.domain2, etc. following the same options each gateways ingress gateway object will take as well as always specifying a 2 replica count to make sure its a N+1 deployment. The values file you use even says you can have more in the notes at https://github.com/rancher/system-charts/blob/dev/charts/rancher-istio/0.1.1/charts/gateways/values.yaml#L4.

The use case is to deploy multiple N+1 ingress gateways with autoscaling that can be used by different tenants based on their domain. This allows us to keep domain traffic separated based on tenant since our cluster is shared across different domains. 

So for example under the gateways values or the main umbrella chart values you could do something like this which would create two ingress gateway deployments using different node-ports. Then all you need to do is create the gateway CRD object for this ingress gateway to be used by namespace virtual services.

```yaml
gateways:
  istio-ig-domain1:
    enabled: true
    sds:
      enabled: false
    labels:
      domain: "domain1"
      istio: "istio-ig-domain1"
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 4
    podAntiAffinityTermLabelSelector:
      - key: istio
        operator: In
        values: "istio-ig-domain1"
        topologyKey: "kubernetes.io/hostname"
    cpu:
      targetAverageUtilization: 80
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      name: http-domain1-80
    - port: 443
      targetPort: 443
      name: http-domain1-443
 istio-ig-domain2:
    enabled: true
    sds:
      enabled: false
    labels:
      domain: "domain2"
      istio: "istio-ig-domain1"
    autoscaleEnabled: true
    autoscaleMin: 2
    autoscaleMax: 4
    podAntiAffinityTermLabelSelector:
      - key: istio
        operator: In
        values: "istio-ig-domain1"
        topologyKey: "kubernetes.io/hostname"
    cpu:
      targetAverageUtilization: 80
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      name: http-domain2-80
    - port: 443
      targetPort: 443
      name: http-domain2-443
```

**Comment by stephen-dahl** [comment]
My team uses multiple gateways also, we have a public gateway open to the internet and an internal gateway only accessible from within our vpc.

if gateways where addable after the fact like other istio objects found here /p/c-xxxxx:p-xxxxx/istio/project-istio/ that would be a great help. the gateways are just a container with a service.

**Comment by mitchellmaler** [comment]
@cloudnautique do you know if this will be possible or will we have to continue to use our custom install of istio?

One thing we wish was that the istio UI components worked in Rancher even without using the build in istio install.

**Comment by cbron** [comment]
I can't speak to long term UI enhancements, but for right now one solution here would be to fork our system-charts and adjust the values.yaml [(demo here)](https://github.com/cbron/system-charts/blob/multi-gateway-example/charts/rancher-istio/1.4.800/charts/gateways/values.yaml#L10-L34) to have multiple gateways, as your example shows. Then configure the system-library catalog  to point to your fork. Your added gateways won't show up in the UI, but they will be deployed. This path is untested on our side but it sounds like you have it working already.

**Comment by stephen-dahl** [comment]
my gateways already show up in the gateway list so that works :)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5.0-alpha1

* Rancher helm install
* Deploy a cluster
* Navigate to the dashboard and create a new namespace `testns`
* Navigate to the dashboard apps
* Install `rancher-istio 1.7.00` with an overlay file specifying another ingress in the new namespace:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
     - enabled: true
       namespace: testns
       name: istio-ingressgateway-two
       k8s:
         service:
           ports:
           - name: http2
             port: 80
             targetPort: 8080
             nodePort: 31381
           - name: https
             port: 443
             targetPort: 8443
             nodePort: 31391
```

* Deploy the demo service, utilizing the additional gateway
* Access the nodeport from the additional gateway and see the demo service as expected
