### ISSUE TITLE
Add podAntiAffinity rule to CoreDNS

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#24434]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
 Add the following to the CoreDNS chart.
```
       spec:
         affinity:
           podAntiAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                 - key: k8s-app
                   operator: In
                   values:
                   - kube-dns
               topologyKey: kubernetes.io/hostname
```

**Result:**
This will keep the scheduler from stacking multiple CoreDNS pods on the same host.

**Other details that may be helpful:**
This is really helpful when running small clusters. (3 nodes clusters) Because your doing a rolling restart/upgrade. You can run into a case where most if not all of your CoreDNS pods are on the same node.

**Workaround**
- Rancher UI
- Project: System
- Namespace: kube-system
- Workload: coredns
- View/Edit YAML
- Add the following after spec:
```
       spec:
         affinity:
           podAntiAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                 - key: k8s-app
                   operator: In
                   values:
                   - kube-dns
               topologyKey: kubernetes.io/hostname
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): HA
