### ISSUE TITLE
cert-manager related bug with long DNS name (For example AWS Internal ELB DNS)

### ISSUE THREAD

**Issue by antoniomo** [rancher/rancher#24483]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug/Feature request

**Steps to reproduce (least amount of steps as possible):**

Follow the HA install instructions, try to use a long DNS/Hostname. This is quite important on the AWS platform if we want to be able to do a HA deployment behind an internal ELB, as the generated DNS name is huge.

**Result:**

With the recommended `cert-manager` version 0.9.1 and a big DNS/Hostname, we hit this bug: https://github.com/jetstack/cert-manager/issues/1972

Disabling the `cert-manager` webhook doesn't solve the issue, as the rancher issuer will then fail to create a valid cert.

**Other details that may be helpful:**

The only workaround that I could make work (other than providing my own self-signed certificates and ditching `cert-manager` altogether, but I didn't want to handle cert rotation by hand) was to create the `tls-rancher` certificate manually:

```
# To be able to self-sign with big AWS ELB internal DNS names, we need to
# workaround this bug: https://github.com/jetstack/cert-manager/issues/1972
# For that we need this cert to override the auto-generated one, that will fail
# the webhook validation. Reference:
# https://docs.cert-manager.io/en/release-0.9/tasks/issuers/setup-ca.html#obtain-a-signed-certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    app: rancher
    chart: rancher-2.3.3
    heritage: Helm
    release: rancher
  name: tls-rancher
  namespace: cattle-system
spec:
  commonName: fake-url.com
  organization:
  - My Org
  dnsNames:
  - big-ass-amazon-generated-internal-dns-name-that-is-ridiculously-long.com
  issuerRef:
    kind: Issuer
    name: rancher
  secretName: tls-rancher
```

Ideally, we could have options to configure this certificate request, so that it doesn't grab the first hit on `dnsNames` as the `commonName` (`cert-manager` behavior when `commonName` is missing). I didn't find a way to do that on Rancher docs, github issues, or elsewhere. Let me know if I missed something or else this is a bug (or feature request).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA
