### ISSUE TITLE
[UI] Load-Balancer compose generator is not setting ports properly

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2450]
Load-Balancer is not exposing up public ports like it should. It is setting `'80'` instead of `80:80/tcp`, making docker to expose port into a random one on host.

It's setting a service with this config:
```
http-and-https:
  ports:
  - '443'
  - '80'
  restart: always
```

Instead of:
```
http-and-https:
  ports:
  - 443:443/tcp
  - 80:80/tcp
  restart: always
```

Versions affected: `0.43.0-rc2` and `0.43.0-rc3`

This is the cause of situations reported on: #2442 (and maybe others)
