### ISSUE TITLE
UI - Cluster with AWS cloud provider setting different values in 'awsCloudProvider' section in the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24515]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Note:**
This happens at random.

- on a Custom cluster, in some cases, on configuring a aws cloud provider custom cluster, the cloud provider is set as (cluster.yml)
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- In other cases
```
  cloud_provider:
    name: aws
```

**Expected:**
UI has to send the below while creating a cluster
```
{"name": "aws",
"type": "cloudProvider",
"awsCloudProvider":
{"type": "awsCloudProvider"}}
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): tested on custom cluster
- Kubernetes version (use `kubectl version`):

```
1.16.3
```

**Comment by codyrancher** [comment]
I was never able to reproduce this exact issue but after talking with @sowmyav27 we decided to make sure awsCloudProvider is present even if it's empty.

**Comment by codyrancher** [comment]
We settled on
```
cloud_provider:
    awsCloudProvider:
      type: awsCloudProvider
    name: aws
```
Because the yaml parser can't support an undefined value key.

**Comment by sowmyav27** [comment]
Deploy an rke cluster - AWS - with cloud provider enabled.
**On `2.3-head` - commit id: `78ed261c6`**
Edit as yaml shows:
```
  cloud_provider:
    awsCloudProvider:
      type: awsCloudProvider
    name: aws
```

Request sent:
```
cloudProvider: {type: "cloudProvider", name: "aws", awsCloudProvider: {type: "awsCloudProvider"}}
awsCloudProvider: {type: "awsCloudProvider"}
type: "awsCloudProvider"
name: "aws"
type: "cloudProvider"
```


**On master-head latest - commit id: `564507959`**
edit as YAML:
```
  cloud_provider:
    awsCloudProvider:
      type: awsCloudProvider
    name: aws
```
request:
```
cloudProvider: {awsCloudProvider: {type: "awsCloudProvider"}, name: "aws"}
awsCloudProvider: {type: "awsCloudProvider"}
type: "awsCloudProvider"
name: "aws"
```

The request sent on master-head is not as expected.
The cluster comes to Active status though.
