### ISSUE TITLE
Error encountered when trying to upgrade only sidekick of a service/ primary service and side kicks. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2451]
Server version - v0.43.0-rc3

Steps to reproduce the problem:

Create a service with following configuration:
```
test1:
  restart: always
  labels:
    io.rancher.service.hash: c65f5919574e035b368067dbb50c0ab9935ba1ad
  tty: true
  image: sangeetha/testclient
  stdin_open: true
sk2:
  restart: always
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
sk1:
  restart: always
  tty: true
  image: sangeetha/testclient
  stdin_open: true
test123:
  restart: always
  labels:
    io.rancher.sidekicks: sk1,sk2
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
```

From UI , truing to upgrade a service with all services (including side kick) / picking only sidekick services fail with the following exception - "Converting circular structure to JSON"

<img width="1233" alt="screen shot 2015-10-26 at 2 57 18 pm" src="https://cloud.githubusercontent.com/assets/4266958/10743939/8a5b5d0c-7bf3-11e5-8fe2-c4b1d2f7fba4.png">
