### ISSUE TITLE
When in "upgraded" state , the newly created instances show up as being in different deployment units.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2452]
Steps to reproduce the problem:

Create a service with following configuration:

```
test1:
  restart: always
  labels:
    io.rancher.service.hash: c65f5919574e035b368067dbb50c0ab9935ba1ad
  tty: true
  image: sangeetha/testclient
  stdin_open: true
sk2:
  restart: always
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
sk1:
  restart: always
  tty: true
  image: sangeetha/testclient
  stdin_open: true
test123:
  restart: always
  labels:
    io.rancher.sidekicks: sk1,sk2
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
```
From UI, choose to upgrade this service and select only the primary service.

When upgrade is completed , UI shows the newly created instance of the primary launch service as being in a different deployment unit.

<img width="360" alt="screen shot 2015-10-26 at 2 55 29 pm" src="https://cloud.githubusercontent.com/assets/4266958/10744102/cca6f616-7bf4-11e5-98fc-909c423d870f.png">

Once we finish the upgrade , the  newly created instance of the primary launch services show up in UI in the correct deployment unit along with the sidekicks.
