### ISSUE TITLE
Recurring S3 snapshots are only deleted locally when folder is configured

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#24544]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Create an RKE cluster using v0.3.2 (also known to affect v1.0.0) with S3 snapshots enabled.

Example cluster YAML:

```yaml
[...]

services:
  etcd:
    backup_config:
      interval_hours: 1
      retention: 1
      safe_timestamp: true
      enabled: true
      s3backupconfig:
        access_key: xxx
        secret_key: yyy
        bucket_name: "<bucket name>"
        region: "us-west-2"
        folder: "<folder name>"
        endpoint: "s3.us-west-2.amazonaws.com"
```

**Result:**

Local snapshots are deleted, S3 snapshots increase without being deleted, logs indicate no errors and the deletion action is occuring.

```
time="2019-12-09T12:22:24Z" level=info msg="Created backup" name="2019-12-09T12:22:24Z_etcd" runtime=119.615378ms
time="2019-12-09T12:22:24Z" level=info msg="invoking uploading backup file backup/2019-12-09T12:22:24Z_etcd.zip to s3" 
time="2019-12-09T12:22:24Z" level=info msg="Successfully uploaded backup/2019-12-09T12:22:24Z_etcd.zip of size 2683144\n" 
time="2019-12-09T12:22:24Z" level=info msg="Deleted backup" name="2019-12-09T09:11:50Z_etcd.zip" runtime=1.115608ms 
time="2019-12-09T12:22:24Z" level=info msg="Invoking delete s3 backup files" retention=3h0m0s`
```
