### ISSUE TITLE
Cloud-config YAML fails when creating docker group

### ISSUE THREAD

**Issue by msnelling** [rancher/rancher#24619]
**What kind of request is this (question/bug/enhancement/feature request):**bug

**Steps to reproduce (least amount of steps as possible):**
1. Create vSphere node template with an Ubuntu 18.04 VM template with `cloud-init` package installed.
2. specify the following YAML as the `cloud-init` config
```
#cloud-config
groups:
  - docker
users:
  - default
  - name: sysadmin
    ssh_authorized_keys:
      - ssh-rsa ...
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, docker
    shell: /bin/bash
power_state:
  timeout: 30
  mode: reboot
```
3. create cluster with node pool based on above template.

**Result:**
Node provisioning hangs at `Waiting for SSH to be available...`

**Other details that may be helpful:**
Checking the `cloud-init` logs I can see that the `docker` user fails to create. No other useful information in the logs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T13:55:44Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by msnelling** [comment]
@luthermonson issue as discussed.

**Comment by luthermonson** [comment]
https://github.com/rancher/machine/pull/59

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head 565ef1a

* Reproduced in `v2.3.3`
* Fresh install of `v2.3-head`
* Created node template with:
```
#cloud-config
groups:
  - docker
users:
  - default
  - name: sysadmin
    ssh_authorized_keys:
      - ssh-rsa ...
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, docker
    shell: /bin/bash
power_state:
  timeout: 30
  mode: reboot
```
* Cluster provisions correctly
* User is added correctly (can ssh w/ `sysadmin` user)
