### ISSUE TITLE
v2.3.3 Imported secret does not show in UI

### ISSUE THREAD

**Issue by ainiml** [rancher/rancher#24637]
![Screenshot from 2019-12-17 11-32-16](https://user-images.githubusercontent.com/28725423/71015259-45337a80-20c1-11ea-8813-b9993dd081b1.png)
![Screenshot from 2019-12-17 11-32-29](https://user-images.githubusercontent.com/28725423/71015263-482e6b00-20c1-11ea-85c3-8b49855ff3c3.png)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
`rancher kubectl create -f skynet/longhorn-system/secret/longhorn-minio.yaml --namespace longhorn-system`

```
 apiVersion: v1
 data:
   AWS_ACCESS_KEY_ID: xxx
   AWS_ENDPOINTS: xxx
   AWS_SECRET_ACCESS_KEY: xxx
 kind: Secret
 metadata:
   annotations:
     field.cattle.io/projectId: c-j8rj8:p-6rjb9
   creationTimestamp: null
   name: longhorn-minio
   selfLink: /api/v1/namespaces/longhorn-system/secrets/longhorn-minio
 type: Opaque
```

**Result:**
`secret/longhorn-minio created`

**Other details that may be helpful:**

**Environment information**

Rancher | v2.3.3
-- | --
User Interface | v2.3.25
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher20-1

- Installation option (single install/HA):
Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (4 CPU/8GB)
- Kubernetes version (use `kubectl version`): 
```
ubuntu@dream:~/rancher-cluster$ rancher kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
