### ISSUE TITLE
Bug create new namespaces could not extend project Limit Range

### ISSUE THREAD

**Issue by holooooo** [rancher/rancher#24663]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create a project and set its `Container Default Resource Limit`
![image](https://user-images.githubusercontent.com/16147105/71075845-b6f1ee00-21bf-11ea-8796-eb709e98bdac.png)
2. create a namespace with kubectl apply
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:p-6qkx7
  labels:
    field.cattle.io/projectId: p-6qkx7
  name: test5
```

**Result:**
sync function will skip create limit range, but Resource Quotas still extend to ns

**Other details that may be helpful:**
![image](https://user-images.githubusercontent.com/16147105/71076095-194aee80-21c0-11ea-996c-bc3027137c56.png)
![image](https://user-images.githubusercontent.com/16147105/71076104-1d770c00-21c0-11ea-9087-fc73a5014338.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.3.2
