### ISSUE TITLE
BUG Release 2.3.3 breaks vSphere driver : cloud-init file

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#24684]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

* create a new node-template using the GUI an provide a cloud init file
* create a new cluster / node pool from template

**Result:**

* see creation of VM fail with error: "Error in driver during machine creation: yaml: unmarshal errors:"

**Other details that may be helpful:**

* this one was especially hard to debug due to the error (see above), you never get any other piece of information
* however it seems, the core issue is that the GUI field is related to the wrong key in yaml config
* old config from before 2.3.3 works, but doesn't show init file in the edit window, in "view in api" you get:
```yaml
"vmwarevsphereConfig": {
  ...
  "cfgparam": [
    ...
    "cloudConfig": "",
    "cloudinit": "http://files.server.url/rancher/cloud-init.yaml",
    ...
```
* new config from (2.3.3) shows the file in edit, but doesn't work with the error from above, in "view in api" you get:
```yaml
"vmwarevsphereConfig": {
  ...
  "cfgparam": [
    ...
    "cloudConfig": "http://files.server.url/rancher/cloud-init.yaml",
    "cloudinit": "",
    ...
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA
