### ISSUE TITLE
type: "cloudProvider" missing in the request sent from UI when AWS Cloud config is enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24706]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy an rke cluster - AWS - with cloud provider enabled.
**On `2.3-head` - commit id: `78ed261c6`**
- Edit as yaml shows:
```
  cloud_provider:
    awsCloudProvider:
      type: awsCloudProvider
    name: aws
```

- Request sent:
```
cloudProvider: {type: "cloudProvider", name: "aws", awsCloudProvider: {type: "awsCloudProvider"}}
awsCloudProvider: {type: "awsCloudProvider"}
type: "awsCloudProvider"
name: "aws"
type: "cloudProvider"
```
**- On master-head:**

- Deploy an rke cluster - AWS - with cloud provider enabled.
- edit as YAML:
```
  cloud_provider:
    awsCloudProvider:
      type: awsCloudProvider
    name: aws
```
request:
```
cloudProvider: {awsCloudProvider: {type: "awsCloudProvider"}, name: "aws"}
awsCloudProvider: {type: "awsCloudProvider"}
type: "awsCloudProvider"
name: "aws"
```

- The request sent on master-head is not as expected. 

**Expected Result:**
The request sent on master-head is to be consistent with that of on 2.3-head.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `394aa88d6`**

**Steps:**
- in a Cloud provider enabled cluster, the cloud provider sent in the request from the UI is:
```
cloudProvider: {type: "cloudProvider", name: "aws", awsCloudProvider: {type: "awsCloudProvider"}}
type: "cloudProvider"
name: "aws"
awsCloudProvider: {type: "awsCloudProvider"}
type: "awsCloudProvider"
```

- Cluster.yml file after the cluster has come up:
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
      service_override: null
    name: aws
```
