### ISSUE TITLE
AWS Cloud provider setup has additional awsCloudProvider default parameters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24704]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy an rke cluster - AWS - with cloud provider enabled. - 2.3-head - latest and master-head
- when the cluster is up and running, go to Edit cluster --> Edit as YAML, we notice
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
        elb-security-group: ''
        kubernetes-cluster-id: ''
        kubernetes-cluster-tag: ''
        role-arn: ''
        routetable-id: ''
        subnet-id: ''
        vpc: ''
        zone: ''
      service_override: null
    name: aws
```
- This is a change of behavior from earlier release, where the edit as YAML showed only
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```

Question: Why is there this change in behavior?

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master and 2.3-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom/rke
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by deniseschannon** [comment]
@codyrancher Is this a UI bug or backend?

**Comment by codyrancher** [comment]
@deniseschannon it's most likely going to be frontend.

**Comment by codyrancher** [comment]
@deniseschannon sorry, skimming through I thought this issue was https://github.com/rancher/rancher/issues/24706.

This one is actually a backend issue. The backend sets these values.

**Comment by superseb** [comment]
@sowmyav27 What is the "earlier" release? Is this v2.2 vs v2.3 or different?

**Comment by sowmyav27** [comment]
@superseb It was the 2.3.3 release

**Comment by superseb** [comment]
@codyrancher Is this not because of https://github.com/rancher/ui/pull/3627 where it was hidden before (if I read the PR correctly)?

**Comment by codyrancher** [comment]
@superseb all of the defaults were hidden when awsCloudProvider wasn't present. I don't consider rancher/rancher#3627 to be the cause of this issue if you're thinking that we should revert or re-fix it. I think it revealed a new unrelated issue.

When I was testing rancher/rancher#3627 I'm pretty sure I only saw 
```
cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
```

But even if the above wasn't the case I believe the backend is responsible for populating those default values because I know the front didn't send them when creating the cluster. Do you know otherwise?

**Comment by superseb** [comment]
Thanks, will look into it

**Comment by superseb** [comment]
@codyrancher Based on what I found:

v2.3.3 has the same API output for a cluster with aws cloud provider, and the empty values get filtered by the function `removeEmpty`.  In https://github.com/rancher/ui/pull/3627 the value `awsCloudProvider` was added to excluded keys, making the empty values not being removed. Not really sure at this point what else it could be, but let me know if I misinterpreted the change in https://github.com/rancher/ui/pull/3627.

**Comment by codyrancher** [comment]
@superseb you're right that the removeEmpty was removing those empty values until my change went in. To me the removeEmpty was covering up the issue that the backend is sending the front useless data. The following is what the backend is sending the front:

```
"rancherKubernetesEngineConfig": {
    "addonJobTimeout": 30,
    "authentication": {
        "strategy": "x509|webhook",
        "type": "/v3/schemas/authnConfig"
    },
    "authorization": {
        "type": "/v3/schemas/authzConfig"
    },
    "bastionHost": {
        "sshAgentAuth": false,
        "type": "/v3/schemas/bastionHost"
    },
    "cloudProvider": {
        "awsCloudProvider": {
            "global": {
                "disable-security-group-ingress": false,
                "disable-strict-zone-check": false,
                "elb-security-group": "",
                "kubernetes-cluster-id": "",
                "kubernetes-cluster-tag": "",
                "role-arn": "",
                "routetable-id": "",
                "subnet-id": "",
                "type": "/v3/schemas/globalAwsOpts",
                "vpc": "",
                "zone": ""
            },
            "type": "/v3/schemas/awsCloudProvider"
        },
        "name": "aws",
        "type": "/v3/schemas/cloudProvider"
    },
    "ignoreDockerVersion": true,
    "ingress": {
        "provider": "nginx",
        "type": "/v3/schemas/ingressConfig"
    },
    "kubernetesVersion": "v1.16.4-rancher1-1",
    "monitoring": {
        "provider": "metrics-server",
        "type": "/v3/schemas/monitoringConfig"
    },
    "network": {
        "options": {
            "flannel_backend_type": "vxlan"
        },
        "plugin": "canal",
        "type": "/v3/schemas/networkConfig"
    },
    "restore": {
        "restore": false,
        "type": "/v3/schemas/restoreConfig"
    },
    "services": {
        "etcd": {
            "backupConfig": {
                "enabled": true,
                "intervalHours": 12,
                "retention": 6,
                "s3BackupConfig": null,
                "safeTimestamp": false,
                "type": "/v3/schemas/backupConfig"
            },
            "creation": "12h",
            "extraArgs": {
                "election-timeout": "5000",
                "heartbeat-interval": "500"
            },
            "gid": 0,
            "retention": "72h",
            "snapshot": false,
            "type": "/v3/schemas/etcdService",
            "uid": 0
        },
        "kubeApi": {
            "alwaysPullImages": false,
            "podSecurityPolicy": false,
            "serviceNodePortRange": "30000-32767",
            "type": "/v3/schemas/kubeAPIService"
        },
        "kubeController": {
            "type": "/v3/schemas/kubeControllerService"
        },
        "kubelet": {
            "failSwapOn": false,
            "generateServingCertificate": false,
            "type": "/v3/schemas/kubeletService"
        },
        "kubeproxy": {
            "type": "/v3/schemas/kubeproxyService"
        },
        "scheduler": {
            "type": "/v3/schemas/schedulerService"
        },
        "type": "/v3/schemas/rkeConfigServices"
    },
    "sshAgentAuth": false,
    "type": "/v3/schemas/rancherKubernetesEngineConfig"
},
```

It seems strange to expect the front-end to not display the config the back is sending us.  I suspect there may be some aspect of the backend that I'm not understanding. Can you explain why the front-end is expected to remove those fields? 

To me it doesn't seem reasonable for the front-end to remove them. I would actually argue for removing removeEmpty all together but I don't know all of the ramifications. I originally thought removeEmpty was being used to remove extraneous stuff from the store data-structure.

**Comment by superseb** [comment]
The only reason I can think of is that we don't want to show "useless" parameters that dont have a value to make the YAML view as clean as possible. If people want to use a certain parameter, they can add it and then it will be shown (as being not empty). Otherwise the YAML view will show every possible parameter of the cluster which is not very clean. 

Looking into the history, it seems to be done in https://github.com/rancher/ui/pull/2096/files to keep configs consistent.

**Comment by deniseschannon** [comment]
Based on where we are in the release and the regressions that have occurred around the AWS cloud provider section, I'm moving this out of v2.3.4 as this has no negative impact on the yaml except for no-empty values. 

I'd like to update the backend to fix sending non default values for this use case (AWS cloud provider) as well as other areas as part of the RKE config that could be populated into the yaml.

**Comment by sowmyav27** [comment]
**On latest master head - commit it: `8bd9f3be2` - ui tag - latest2.**

- Create an AWS cluster with cloud provider enabled.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.
- cluster.yml has the following.
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- On edit cluster, Modify the following
```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```
- Save the changes. The cluster comes up Active.
