### ISSUE TITLE
Manage rancher-agent with Puppet

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#2473]
Hi,

I am having some troubles in managing rancher-agent runtime via Puppet.

Essentially, Puppet puts down a systemd unit file which gets generated from a standard ERB template.

```
[Unit]
Description=Rancher-agent Service
After=docker.service
Requires=docker.service

[Service]
Restart=on-failure
ExecStartPre=-/usr/bin/docker kill rancher-agent
ExecStartPre=-/usr/bin/docker rm rancher-agent
ExecStart=/usr/bin/docker run \
  --privileged=true \
  -e='CATTLE_AGENT_IP=192.168.1.123' \
  -v=/var/run/docker.sock:/var/run/docker.sock \
  rancher/agent:v0.8.2 http://rancher
ExecStop=-/usr/bin/docker stop rancher-agent

[Install]
WantedBy=multi-user.target
```

This is quite nice as one can manage the rancher-agent in Hiera like this:
```
docker::images:
  "rancher/agent":
    image_tag: "v0.8.2"
docker::containers:
  "rancher-agent":
    image: "rancher/agent:v0.8.2"
    command: "http://rancher"
    privileged: true
    env:
      CATTLE_AGENT_IP: "%{::ipaddress}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # https://github.com/rancher/rancher/blob/master/agent/Dockerfile
    # LABEL "io.rancher.container.system"="rancher-agent" -> causes the app to crash if we manually specify the container name
    override_name: false
```

The problem is that Puppet will try to start the service over and over, as the first container seems to be some bootstrapping for the main long-running containers.

Obviously, I can hack the status command to look for rancher-agent in docker ps, but I just wanted to check if there's any nicer alternative to that.

Thanks,
Matteo
