### ISSUE TITLE
awsCloudProvider has been set for a DO cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24745]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Scenario#1**
- Deploy a DO rke cluster on master-head
- When the cluster has come up Active, Go to Edit cluster --> Edit as YAML
- Edit as cluster YAML has this

```
  cloud_provider:
    awsCloudProvider: {}
```

**Expected Result:**
Cloud provider should NOT be set on a DO cluster.
`awsCloudProvider: {}` should not be set.

**Scenario#2**
- Deploy a DO rke cluster on master-head
- When the cluster has come up Active, Go to Edit cluster --> Edit as YAML
- Change the following
```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```
- Click on Save
- When the cluster has come up Active, Go to Edit cluster --> Edit as YAML
- Edit as cluster YAML has this
```
cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
        elb-security-group: ''
        kubernetes-cluster-id: ''
        kubernetes-cluster-tag: ''
        role-arn: ''
        routetable-id: ''
        subnet-id: ''
        vpc: ''
        zone: ''
      service_override: null
```
**This issue causes the DO cluster fails to come up with the following error**

`Do cluster: [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Failed to check http://localhost:10248/healthz for service [kubelet] on host [ip]: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused, log: caused by: not found]`

**Expected Result:**
Cloud provider should NOT be set on a DO cluster.
`awsCloudProvider: {}` should not be set.

**Other details that may be helpful:**
- Cause by issue -- https://github.com/rancher/rancher/issues/24515
- Also happens on 2.3-head latest

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.15
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by westlywright** [comment]
Available in `latest2` and `latest-2.3`

**Comment by sowmyav27** [comment]
Verified on `master-head` latest - commit id: `a75a6cdc0`, ui tag: `latest2` and 2.3-head - commit id: `025625592`, ui tag: `latest-2.3`

**Scenario#1**

- Create a DO cluster.
- When the cluster comes up Active, Navigate to CLuster --> Edit cluster --> Edit as YAML.
- `cloud_provider: {}` is not seen in the YAML.
- Modify the following

```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```

- Click on Save.
-  When the cluster comes up Active, Navigate to CLuster --> Edit cluster --> Edit as YAML.
- `cloud_provider: {}` is not seen in the YAML.
- No error is seen on the UI

**Scenario#2**

Create an AWS cluster with cloud provider enabled.
When the cluster comes up `Active`, Navigate to Cluster --> Edit cluster --> Edit as YAML.
- Cluster.yaml file shows
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
        elb-security-group: ''
        kubernetes-cluster-id: ''
        kubernetes-cluster-tag: ''
        role-arn: ''
        routetable-id: ''
        subnet-id: ''
        vpc: ''
        zone: ''
      service_override: null
    name: aws
```
- Modify the following

```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```

- Click on Save.
-  When the cluster comes up Active, Navigate to CLuster --> Edit cluster --> Edit as YAML.
- Cluster.yaml file shows
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
....
```
- No error is seen on the UI

**Comment by sowmyav27** [comment]
Reopening the issue, as the issue exists on latest 2.3-head - commit id: `ed6537bfa` and master-head - commit id: `7578b3c76`

**Comment by sowmyav27** [comment]
Verified on 2.3-head - commit id:` 98bb26840`; ui tag: `latest-2.3`
and on master-head - commit id: `fa2cbfc57`; ui tag: `latest2`

Following Scenarios have been validated:

**Scenario#1**

- Create a DO cluster.
- When the cluster comes up Active, Navigate to CLuster --> Edit cluster --> Edit as YAML.
- cloud_provider: {} is not seen in the YAML.
- Modify the following

```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```

- Click on Save.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.
- cloud_provider: {} is not seen in the YAML.
- No error is seen on the UI

**Scenario#2** - **ISSUE**

- Create an AWS cluster with cloud provider enabled.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.

cloud_provider is NOT set.

But View in API of the cluster shows cloud provider set
```
"cloudProvider": {
"awsCloudProvider": {
"global": {
"disable-security-group-ingress": false,
"disable-strict-zone-check": false,
"elb-security-group": "",
"kubernetes-cluster-id": "",
"kubernetes-cluster-tag": "",
"role-arn": "",
"routetable-id": "",
"subnet-id": "",
"type": "/v3/schemas/globalAwsOpts",
"vpc": "",
"zone": ""
},
"type": "/v3/schemas/awsCloudProvider"
},
"name": "aws",
"type": "/v3/schemas/cloudProvider"
},
```
logging a new issue to track this. https://github.com/rancher/rancher/issues/24814
