### ISSUE TITLE
[load balancer] Incorrect work of multiple frontends 

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2475]
My rancher LB is configured to use two frontends: one in tcp mode for port 6379, other with http mode in v7 routing for 3000 port. I would like to pass 6379 traffic to redis target, but everything else from 3000 port to another multiple targets separed by subdomains. Here is my compose-file:
```yml
rancher-lb:
  image: rancher/load-balancer-service
  ports:
    - 3000:80
    - 6379:6379/tcp
  external_links:
    - conf/api:api
    - conf/redis:redis-conf
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.conf/api: conf.mydomain.com=3000 # 3000 port to api target 3000
    io.rancher.loadbalancer.target.conf/redis: 6379=6379 # 6379 should forward to ONLY 6379 redis target
```
Generated haproxy.conf:
```
frontend ff1f7ba3-052b-4d6d-a460-526b0c9c2d87_frontend                          
        bind 10.42.22.144:3000                                                  
        mode http                                                               
                                                                                
        acl 3_host hdr(host) -i conf.mydomain.com                              
        acl 3_host hdr(host) -i conf.mydomain.com:3000                         
        use_backend ff1f7ba3-052b-4d6d-a460-526b0c9c2d87_3_backend if 3_host    
        default_backend ff1f7ba3-052b-4d6d-a460-526b0c9c2d87_0_backend          
                                                                                
backend ff1f7ba3-052b-4d6d-a460-526b0c9c2d87_3_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server ab5b44b4-fb48-41bb-9f9b-b9f69d33ff30 10.42.42.223:3000  << sidekick  1
        server 61ed1222-b0d0-453c-9561-03b788997fab 10.42.113.201:3000  << api instance 1
        server 712c840b-29b1-40ba-b9ab-bce61c9f6550 10.42.193.171:3000  <<  sidekick 2   
        server 3e6e631d-ab90-432f-86bb-6c704bb35d1f 10.42.87.195:3000  << api instance 2

backend ff1f7ba3-052b-4d6d-a460-526b0c9c2d87_0_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server 548176bf-9379-4cc2-82d2-389ae6c08b9b 10.42.123.50:80   << why 80 to redis target?
                                                                                
frontend 904cc5fe-d717-426e-b8aa-e85c899a8bbe_frontend                          
        bind 10.42.22.144:6379                                                  
        mode tcp                                                                
                                                                                
        default_backend 904cc5fe-d717-426e-b8aa-e85c899a8bbe_0_backend          
                                                                                
backend 904cc5fe-d717-426e-b8aa-e85c899a8bbe_0_backend                          
        mode tcp                                                                
        balance roundrobin                                                      
        server ab5b44b4-fb48-41bb-9f9b-b9f69d33ff30 10.42.42.223:3000           
        server 61ed1222-b0d0-453c-9561-03b788997fab 10.42.113.201:3000          
        server 712c840b-29b1-40ba-b9ab-bce61c9f6550 10.42.193.171:3000          
        server 3e6e631d-ab90-432f-86bb-6c704bb35d1f 10.42.87.195:3000           
        server 548176bf-9379-4cc2-82d2-389ae6c08b9b 10.42.123.50:6379 << redis    
```
why i see here other targets rather than redis?
If i specify source port directly `io.rancher.loadbalancer.target.conf/api:conf.mydomain.com:3000=3000` latest entry become:
```
backend 7a2fcc80-1515-467c-aecb-27429dbaab45_0_backend                          
        mode tcp                                                                
        balance roundrobin                                                      
        server 73d03958-7184-44f2-8f71-fef2cde44f01 10.42.42.223:6379    << non-redis-target        
        server 8fc48109-7e5f-42a8-b159-cdeb1a703823 10.42.113.201:6379    << non-redis-target
        server eefd7be9-449a-410d-97eb-2e637f83a5e8 10.42.193.171:6379  << non-redis-target          
        server d229fe2d-1b4f-4a38-a1a6-f41205fa7bf4 10.42.87.195:6379  << non-redis-target
        server 845adfff-4dd1-4ac4-ac26-c897e1a05b9d 10.42.123.50:6379 << redis
```
Ohh, at least they have 6379 port... Where am i wrong or this is kinda bug?
Second question - how default backend is selected? Everything from !(conf).mydomain.com falls to my redis...
And third - in UI I see blank load balancer configuration when click "Edit"
<img width="1054" alt="screenshot 2015-10-29 17 18 54" src="https://cloud.githubusercontent.com/assets/3070298/10821011/34cefcd4-7e61-11e5-89e7-ae17c8976a8b.png">

**Comment by deniseschannon** [comment]
Rancher doesn't support multiple frontends directing to specific services. By default, any source port will access any target port. 

A workaround if you want to use only 1 load balancer is that you could use hostname routing rules to create a bogus hostname route to prevent any services using a specific port.

In your example, you could add

```
labels:
  # Create a rule that forces all traffic to redis at port 3000 to have a hostname of bogus.com
  # This eliminates any traffic from port 3000 to be directed to redis
  io.rancher.loadbalancer.target.conf/redis: bogus.com:3000
 # Create a rule that forces all traffic to api at port 6379 to have a hostname of bogus.com
  # This eliminates any traffic from port 6379 to be directed to api
  io.rancher.loadbalancer.target.conf/api: bogus.com:6379
```
