### ISSUE TITLE
parameters "extra_args: null" is is seen in cluster.yml

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24794]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
Bring up a DO cluster on 2.3-head or master-head
Cluster.yaml file contains the following
```
    kube-api:
      always_pull_images: false
      extra_args: null
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller:
      extra_args: null
    kubelet:
      extra_args: null
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy:
      extra_args: null
    scheduler:
      extra_args: null
```

**Actual Result:**
Additional arguments are seen in the cluster.yml file ` extra_args: null`

**Expected Result:**
Additional arguments should not be seen in the cluster.yml file ` extra_args: null`

On 2.3.3 - cluster.yml looks like
```
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): latest 2.3-head/master-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): do rke

**Comment by codyrancher** [comment]
@deniseschannon @sowmyav27 
This appears to be by design https://github.com/rancher/ui/commit/07b12da338af517acd36f8e77f961ad6b0519492

I think before we open more bugs regarding this yaml we may want to have a discussion and define the expectations. It seems we're now contradicting past requests.

**Comment by deniseschannon** [comment]
@loganhz why did you add this in? or what reasoninng?

**Comment by loganhz** [comment]
The commit is for supporting https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-nginx-ingress-controller

```
    extra_args:
      enable-ssl-passthrough: ""
```

In this case, we should make sure `removeEmpty` will not remove `extra_args`

`extra_args: null` is a bug we should fix. :)

**Comment by westlywright** [comment]
A fix for this has been pushed to `latest2` can we test that please?

**Comment by sowmyav27** [comment]
**On latest master head - commit it: `8bd9f3be2` - ui tag - latest2.**

Bring up a DO cluster master-head.
Cluster.yaml file contains the following
```
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
```

@westlywright the fix works on master, latest2.

**Comment by sowmyav27** [comment]
Reopening - waiting for fix for 2.3-head

**Comment by sowmyav27** [comment]
Fix has been merged on 2.3

**Comment by sowmyav27** [comment]
**On latest 2.3-head - commit id: `ab7ce7ba2` ui tag - latest-2.3**

Bring up a DO cluster master-head.
Cluster.yaml file contains the following

```
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
```

**Comment by sowmyav27** [comment]
Reopening the issue.

This is seen on the latest `master-head`.
```
kube-controller:
      extra_args: null
    kubelet:
      extra_args: null
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy:
      extra_args: null
    scheduler:
      extra_args: null
  ssh_agent_auth: false
```
