### ISSUE TITLE
CloudProvider is NOT set in cluster.yml on UI for a cluster with cloud provider enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#24814]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create an AWS cluster with cloud provider enabled.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.

cloud_provider is NOT set.

But View in API of the cluster shows cloud provider set
```
"cloudProvider": {
"awsCloudProvider": {
"global": {
"disable-security-group-ingress": false,
"disable-strict-zone-check": false,
"elb-security-group": "",
"kubernetes-cluster-id": "",
"kubernetes-cluster-tag": "",
"role-arn": "",
"routetable-id": "",
"subnet-id": "",
"type": "/v3/schemas/globalAwsOpts",
"vpc": "",
"zone": ""
},
"type": "/v3/schemas/awsCloudProvider"
},
"name": "aws",
"type": "/v3/schemas/cloudProvider"
},
```

**Expected Result:**
On Edit cluster --> Edit as YAML, cloud provider should be set

**Note:**
- On edit cluster, Modify the following

```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
``` 
- Cluster comes up active, but the node is in `Unavailable` state ; Error: `Kubelet stopped posting node status.`

- Also, cloud provider is not set for an cluster type, rke/custom, with cloud provider set. - On the UI, enabled cloud provider while creating the cluster. Do an edit on cluster, cloud provider is NOT set.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Verified on 2.3-head - commit id:` 98bb26840`; ui tag: `latest-2.3`
and on master-head - commit id: `fa2cbfc57`; ui tag: `latest2`

- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): aws rke
- Kubernetes version (use `kubectl version`):

```
1.16
```

**Comment by westlywright** [comment]
A fix for this has been pushed to `latest2` can we test that please?

**Comment by sowmyav27** [comment]
**On latest master head - commit it: `8bd9f3be2` - ui tag - latest2.**

- Create an AWS cluster with cloud provider enabled.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.
- cluster.yml has the following.
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- On edit cluster, Modify the following
```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```
- Save the changes. The cluster comes up Active.

**Comment by sowmyav27** [comment]
Reopening - waiting for fix for 2.3-head

**Comment by sowmyav27** [comment]
**On latest 2.3-head - commit id: `ab7ce7ba2` ui tag - latest-2.3**

- Create an AWS cluster with cloud provider enabled.
- When the cluster comes up Active, Navigate to Cluster --> Edit cluster --> Edit as YAML.
- cluster.yml has the following.
```
  cloud_provider:
    awsCloudProvider:
      global:
        disable-security-group-ingress: false
        disable-strict-zone-check: false
    name: aws
```
- On edit cluster, Modify the following
```
etcd:
      backup_config:
        enabled: true
        interval_hours: 1
```
- Save the changes. The cluster comes up Active.
- cloud provider is set on the cluster - in edit as yaml
