### ISSUE TITLE
Container is only reachable from its host

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2486]
Suppose i have two hosts H1 and H2, service with scale=2 with one instance on each host, and global LB balancing this instances. In rancher LB from H2 i have this entry:
```                                                                            
backend 8280f687-905a-4f2c-8f4c-5128fd21e5e5_0_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server b039aa54-3ad7-4433-a52c-99f101a2bf74 10.42.208.8:80 < service-1 sidekick
        server 2093dd69-771b-49bb-a501-a22acc52369c 10.42.185.27:80 < service-1 instance
        server 46c09fae-b26e-4eaa-b88e-b4674aae286d 10.42.189.97:80 < service-2 instance
```
From H2 LB container: ping to service-1 on H1:
```
# ping 10.42.185.27                                          
PING 10.42.185.27 (10.42.185.27) 56(84) bytes of data.                          
^C                                                                              
--- 10.42.185.27 ping statistics ---                                            
84 packets transmitted, 0 received, 100% packet loss, time 83663ms 
```
From H2 LB container: ping local service-2
```
# ping 10.42.189.97                                          
PING 10.42.189.97 (10.42.189.97) 56(84) bytes of data.                          
64 bytes from 10.42.189.97: icmp_seq=1 ttl=64 time=0.058 ms                     
64 bytes from 10.42.189.97: icmp_seq=2 ttl=64 time=0.042 ms                     
64 bytes from 10.42.189.97: icmp_seq=3 ttl=64 time=0.050 ms  
```
Mirrored picture from H1
lb.yml:
```
stack-lb:
  image: rancher/load-balancer-service
  ports:
    - 8400
  external_links:
    - frontend/frontend:frontend
    - realtime/realtime:realtime
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.realtime/realtime: rt.mydomain.com:8400=8082
    io.rancher.loadbalancer.target.frontend/frontend: mydomain.com:8400=80
    io.rancher.scheduler.affinity:host_label: role=stack
```
rancher/server:v0.42.0
```
~> docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```
