### ISSUE TITLE
Charts version should allow the + sign (SemVer)

### ISSUE THREAD

**Issue by finkr** [rancher/rancher#24863]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug report

**Steps to reproduce (least amount of steps as possible):**

1. Create a chart which version contains the "+" sign (like "foo-1.0.0+build5"), in a chart repo.
2. Refresh that catalog in rancher

**Result:**

* The repo is in "Refreshed" state.
* The View in API show:

    "lastUpdateTime": "2020-01-06T11:32:10Z",
    "message": "syncing template bar-foo",
    "status": "Unknown",
    "type": "Refreshed"

The rancher container log (`docker logs`) show:

```
2020/01/06 11:23:35 [INFO] Updating global catalog 0test
2020/01/06 11:23:35 [INFO] Catalog sync done. 0 templates created, 1 templates updated, 0 templates deleted
2020/01/06 11:23:35 [ERROR] CatalogController 0test [catalog] failed with : failed to update templates. Multiple error occurred: [CatalogTemplateVersion.management.cattle.io "bar-foo-1.0.0+build5" is invalid: metadata.name: Invalid value: "bar-foo-1.0.0+build5": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

=> This error message is rally misleading

**Other details that may be helpful:**

The version containing "+" are allowed in SemVer ([Build metadata](https://semver.org/#spec-item-10)).

**Environment information**
- Rancher version : `2.3.3`
- Docker version : `1.13.1`

**Comment by bbielicki** [comment]
I faced the same issue. It would be great to have support for this.

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/issues/24914. << related PR maybe have addressed this issue

**Comment by bmdepesa** [comment]
rancher/rancher:master-head dea9bf3bf

* Add a catalog with a chart containing a `+` in the version:
```
apiVersion: v1
entries:
  aks-helloworld:
  - apiVersion: v1
    created: 2019-05-27T08:33:22.567132062-07:00
    description: A Helm chart for Kubernetes
    digest: f4eb20e7116b24c4825861e6ff6f4303bbe83bcee4a7b2b6ea9fe6929852f34d
    name: aks-helloworld
    urls:
    - https://azure-samples.github.io/helm-charts/aks-helloworld-0.1.0.tgz
    version: foo-1.0.0+build5
```
`https://github.com/bmdepesa/helm-test-repo/blob/semver/index.yaml`

* The catalog still has the same error in syncing:
```
Error in chart(s): failed aks-helloworld template version name semvertest-aks-helloworld-foo-1.0.0_build5: [a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')];
```
