### ISSUE TITLE
migration-tool needs updating for k8s 1.16

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#24902]
A customer is having issues when using the migration-tool to move from Rancher 1.6 to 2.x. It seems that the deployment and container names need to be converted to lowercase, matchLabel needs to be added and the apiVersion needs to be switched to apps/v1.

Here is an example of the output they are currently getting:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.pull_image: always
    kompose.cmd: migration-tools_linux-amd64 parse
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: MariaDB
  name: MariaDB
spec:
  replicas: 0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: MariaDB
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MYSQL_DATABASE
          value: SECRET
        - name: MYSQL_PASSWORD
          value: SECRET
        - name: MYSQL_ROOT_PASSWORD
          value: SECRET
        - name: MYSQL_USER
          value: user
        image: mariadb:10.2.7
        name: MariaDB
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
```

**Comment by prachidamle** [comment]
Upstream Kompose issue: https://github.com/kubernetes/kompose/issues/1236

**Comment by hangyan** [comment]
@prachidamle This issue has been fixed by pr [kubernetes/kompose#1207](https://github.com/kubernetes/kompose/pull/1207). It will be released next month

**Comment by prachidamle** [comment]
Thanks for the fixes and update @hangyan!

**Comment by prachidamle** [comment]
The upstream Kompose fixes have been vendored in and a new release is created for migration-tools:
https://github.com/rancher/migration-tools/releases/tag/v0.1.3

**Comment by soumyalj** [comment]
Reproduced the issue with migration-tool version v0.1.2
1. Created a Cattle setup using Rancher v1.6.29
2. Deployed a nginx app and obtained the docker-compose and rancher-compose files
3. Used the migration-tool to obtain the K8s manifests
```
./migration-tools_darwin-amd64-v0.1.3 parse --docker-file dc.yml --rancher-file rc.yml 
```
The yaml obtained is below. This has the apiVersion "extensions/v1beta1" which will fail to deploy in K8s1.16 and above
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.container.pull_image: always
    kompose.cmd: ./migration-tools_darwin-amd64 parse --docker-file dc.yml --rancher-file
      rc.yml
    kompose.version: 1.16.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: testapp
  name: testapp
spec:
  replicas: 0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: testapp
    spec:
      containers:
      - image: nginx
        name: testapp
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
```
Tested with migration-tool version v0.1.3

```
./migration-tools_darwin-amd64-v0.1.3 parse --docker-file dc.yml --rancher-file rc.yml 

```

```
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        io.rancher.container.pull_image: always
        kompose.cmd: ./migration-tools_darwin-amd64-v0.1.3 parse --docker-file dc.yml
            --rancher-file rc.yml
        kompose.version: 1.20.0 (HEAD)
    creationTimestamp: null
    labels:
        io.kompose.service: testapp
    name: testapp
spec:
    selector:
        matchLabels:
            io.kompose.service: testapp
    strategy: {}
    template:
        metadata:
            annotations:
                io.rancher.container.pull_image: always
                kompose.cmd: ./migration-tools_darwin-amd64-v0.1.3 parse --docker-file
                    dc.yml --rancher-file rc.yml
                kompose.version: 1.20.0 (HEAD)
            creationTimestamp: null
            labels:
                io.kompose.service: testapp
        spec:
            containers:
              - image: nginx
                imagePullPolicy: ""
                name: testapp
                resources: {}
                stdin: true
                tty: true
            restartPolicy: Always
            serviceAccountName: ""
            volumes: null
status: {}
```
