### ISSUE TITLE
use charts questions, how to setting array values?

### ISSUE THREAD

**Issue by sewenc** [rancher/rancher#24918]
in docs ,current supported types are string, multiline, boolean, int, enum, password, storageclass, hostname, pvc, and secret

how to setting questions array value in question.yml?

case value: `service.externalIPs`
```
  service:
    externalPort: 39443
    externalIPs:
    - 10.x.180.106
    - 10.x.180.106
    - 10.x.180.106
```
