### ISSUE TITLE
Bug: coredns-autoscaler needs readiness and liveness check

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24939]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
coredns autoscaler does not have a readiness and liveness check

**Result:**
If a node goes offline where coredns-autoscaler is running, it will not be rescheduled properly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

gz#7893
SURE-1649

**Comment by Jono-SUSE-Rancher** [comment]
Whoever grabs this, we don't expect the liveness check to actually correct the expected behavior to have the pod rescheduled after the node goes down. In 2.5.4 we added in the ability to configure the tolerations on add-ons which may solve this issue but needs to be investigated.

**Comment by izaac** [comment]
Rancher version: `v2.5.7`

Scenarios:

Cluster type `Imported RKE`
Clusters had at least three workers.

- Cluster 1 in `1.18` with coreDNS add ons with the tolerations
- Cluster 2 in `1.19` with coreDNS add ons with the tolerations
- Cluster 3 in `1.18` with default values for coreDNS

Add-ons configuration in `cluster.yml`

```yaml
monitoring:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
ingress:
  provider: nginx
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
network:
  plugin: calico
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
dns:
  provider: coredns
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 300
```

Cluster 1 - `1.18` with coreDNS add ons with the tolerations
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. A new pod was scheduled in other available worker node and come up `Active`

Cluster 2 - `1.19` with coreDNS add ons with the tolerations
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. Config scale in the deployment 2 and Ready scale was 1. No pod was re-scheduled.

Cluster 3 - `1.18` with default values for coreDNS
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. Config scale in the deployment 2 and Ready scale was 1. No pod was re-scheduled.
