### ISSUE TITLE
CICD_GIT_TAG variable substitution in pipeline configs is not taking place

### ISSUE THREAD

**Issue by aroticoz** [rancher/rancher#24979]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add the following pipeline:
```
stages:
- name: Deploy
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo $FOO
    env:
      FOO: ${CICD_GIT_TAG}
```

**Result:**
```
+ echo '${CICD_GIT_TAG}'
${CICD_GIT_TAG}
```

**Expected result:**
`${CICD_GIT_TAG}` to be substituted with tag of the current commit

**Other details that may be helpful:**
There has been a previous issue with the CICD_GIT_BRANCH var a year ago -> resolved in #17757. However CICD_GIT_TAG does not substitute. I have not tested the other variables substitutions.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
Running rancher v2.3.3 (Latest as of 2020-01-16)

- Installation option (single install/HA):
Single install

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
Running on a local VM via docker container
