### ISSUE TITLE
[question] Selector labels and autolinking service containers

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2499]
how do they exactly works? By what hostnames i access linked containers with labels? How can i link all service containers with each other? Imagine RabbitMQ cluster and each node should be able to resolve other nodes by hostname set with `io.rancher.container.hostname_override: container_name`. Can i use "selector labels" for this scenario? 
```
rabbit-slave:
  image: rabbitmq:3.5.6
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=stack
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=rabbit/rabbit-slave
    io.rancher.service.selector.link: io.rancher.stack_service.name = rabbit/rabbit-slave
```
So if i have 2 slaves, then first should be linked with second by name `rabbit_rabbit-slave_2` and second - `rabbit_rabbit-slave_1`, something like `docker run --link rabbit_rabbit-slave_1 --link rabbit_rabbit-slave_2` for slave-3
