### ISSUE TITLE
rancher-compose: json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#2501]
Is there a way to debug this?
json: cannot unmarshal number into Go value of type string 

rancher-compose version v0.5.1
Docker version 1.7.1, build 786b29d

```
ue-developer:
  restart: 'no'
  environment:
    AES_KEY: xxx
  external_links:
  - xxxx
  tty: true
  image: xxx
  links:
  - 'redis:'
  stdin_open: true
ue-developer2:
  restart: 'no'
  environment:
    AES_KEY: xxx
  external_links:
  - xxx
  tty: true
  image: xxx
  links:
  - 'redis:'
  stdin_open: true
```

**Comment by deniseschannon** [comment]
What version of Rancher are you using with it? Also, just to confirm, are you using v0.5.0? We don't have a v0.5.1, but we also have a v0.4.1. 

Can you share your rancher-compose.yml?

**Comment by silviupanaite** [comment]
rancher-compose version v0.5.1 was released 7 days ago
tried with rancher-compose version v0.4.3 and got the same issue
```
ue-developer:
  scale: 2
ue-developer2:
  scale: 2
redis:
  scale: 1
developer-balancer:
  scale: 1
  load_balancer_config:
    name: developer-balancer2 config
```

**Comment by silviupanaite** [comment]
Can you guys tell me what debugger should I use for rancher compose?

**Comment by deniseschannon** [comment]
There's no easy way to debug this. It's hard for me to replicate when you don't have the full docker-compose.yml as it looks as if you have some other services in your rancher-compose.yml.

Are you using the command line and just doing a `rancher-compose up`? 

Are you using any kind of intepolating variables?

**Comment by deniseschannon** [comment]
One way to debug is to keep trying to eliminate certain lines of your docker-compose.yml and rancher-compose.yml to find the "offending" line.

It's just an unmarshal/conversion error so really hard to pinpoint.

**Comment by silviupanaite** [comment]
Identified the problem, it's at the cross stack linking.
The line bellow is causing the "json: cannot unmarshal number into Go value of type string" error.
'''  
external_links:
  - unificationengine-cassandra/cassandra-node:cassandra
'''

**Comment by deniseschannon** [comment]
What version of Rancher are you using? Can you please click on the cow in the upper left corner to provide the versions? 

I have seen this issue in the past reported by another user, but have never been able to reproduce it.

**Comment by silviupanaite** [comment]
Component	Version
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1

**Comment by deniseschannon** [comment]
Have you confirmed that you're using v0.5.1 by doing a `rancher-compose -v`? It's strange that the external link would cause that unmarshal error as there is obviously no number in it. 

How did you start the services (in the UI or rancher-compose)? And what commands were you doing while you were trying to use rancher-compose?

Here's the other issue that is similar issues, but never able to reproduce: 
https://github.com/rancher/rancher/issues/1316

**Comment by silviupanaite** [comment]
I started the services using the rancher-compose (witch I verified it's the v.5.1) with rancher-compose up

**Comment by deniseschannon** [comment]
I have been unable to reproduce this issue. Any time that I do a `rancher-compose up` with a cross stack link, it works fine.

**Comment by silviupanaite** [comment]
This is a isolated incident, all other services with cross stack work, but I'm not able to pin point the exact problem with this. Anyway what debug do you guys use?

**Comment by deniseschannon** [comment]
What OS are you using for your hosts?

**Comment by petyunchik** [comment]
Confirm this issue. Ubuntu 14.04
This errors raises not only for stacks that has external links, but also for "parent" stacks

**Comment by deniseschannon** [comment]
@silviupanaite @petyunchik Could you provide more details of your Rancher setup? What Rancher version are you running? Did you upgrade from a previous version? If so, which one? What OS are you running?

I still have been unable to reproduce, but am wondering if it's an issue with upgraded Rancher setups or with the OS?

**Comment by petyunchik** [comment]
@deniseschannon 

Rancher 	v0.47.0
Cattle 	v0.115.0
User Interface 	v0.68.0
Rancher Compose 	v0.5.3
Docker version 1.9.1, build a34a1d5
Ubuntu 14.04

```
nginx:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.sidekicks: django
  tty: true
  image: nginx-...
  volumes_from:
  - django
  stdin_open: true
celery-worker:
  environment:
    C_FORCE_ROOT: 'true'
  tty: true
  entrypoint:
  - sh
  - backend/docker/django/celery_worker.sh
  image: celery-worker-...
  links:
  - postgis:postgis
  stdin_open: true
redis:
  tty: true
  image: redis:latest
  volumes:
  - redis-data:/var/lib/redis
  stdin_open: true
  volume_driver: gluster-convoy
rabbitmq:
  tty: true
  image: rabbitmq:latest
  volumes:
  - rabbitmq-data:/var/lib/rabbitmq/mnesia/
  stdin_open: true
  volume_driver: gluster-convoy
django:
  tty: true
  entrypoint:
  - sh
  - backend/docker/django/runserver.sh
  image: django-...
  volumes:
  - /usr/src/app/static
  stdin_open: true
celery-beat:
  environment:
    C_FORCE_ROOT: 'true'
  tty: true
  entrypoint:
  - sh
  - backend/docker/django/celery_beat.sh
  image: celery-beat-...
  links:
  - postgis:postgis
  stdin_open: true
postgis:
  tty: true
  image: mdillon/postgis:latest
  stdin_open: true
```

```
countly:
  tty: true
  image: countly/countly-server
  volumes:
  - countly-data:/var/lib/mongodb
  stdin_open: true
  volume_driver: gluster-convoy
sentry:
  tty: true
  image: sentry-...
  stdin_open: true
sentry-data:
  tty: true
  image: postgres
  volumes:
  - sentry-data:/var/lib/postgresql/data
  stdin_open: true
  volume_driver: gluster-convoy
flower:
  environment:
    AMQP_ADMIN_HOST: ...
    AMQP_HOST: ...
  tty: true
  image: totem/celery-flower-docker:latest
  stdin_open: true
```
I can provide any additional information if you need.

**Comment by cloudnautique** [comment]
Can you provide the output of the `rancher-compose --debug up`?

**Comment by petyunchik** [comment]
@cloudnautique  it seems problem in the services that use gluster driver. I'll try to confirm it tomorrow and attach debug logs here.

**Comment by petyunchik** [comment]
@cloudnautique  so, i can confirm it. If the service has gluster driver or links to the service with gluster driver, than it raise the error "json: cannot unmarshal number into Go value of type string".

Debug output:
```
DEBU[0000] Environment Context from file : map[]        
DEBU[0000] Opening compose file: docker-compose.services.yml 
DEBU[0000] [0/0] [sentry-data]: Adding                  
DEBU[0000] [0/2] [countly]: Adding                      
DEBU[0000] [0/2] [flower]: Adding                       
DEBU[0000] Opening rancher-compose file: /Users/Petr/Projects/prime/svo-backend/rancher-compose.yml 
DEBU[0000] Not found: /Users/Petr/Projects/prime/svo-backend/rancher-compose.yml 
DEBU[0000] [0/4] [sentry]: Adding                       
DEBU[0000] Looking for stack services                   
DEBU[0000] Found stack: services(1e10)                  
DEBU[0000] Launching action for sentry-data             
DEBU[0000] Launching action for countly                 
DEBU[0000] Launching action for flower                  
ERRO[0000] Failed to find redis                         
DEBU[0000] Launching action for sentry                  
DEBU[0000] Project [services]: Creating project         
DEBU[0000] Finding service sentry-data                  
DEBU[0000] [0/4] [sentry-data]: Creating                
DEBU[0000] [0/4] [countly]: Creating                    
DEBU[0000] [0/4] [flower]: Creating                     
DEBU[0000] Finding service countly                      
DEBU[0000] Finding service flower                       
ERRO[0000] Failed Creating sentry-data : json: cannot unmarshal number into Go value of type string 
ERRO[0000] Failed to find redis                         
DEBU[0000] Finding service sentry                       
DEBU[0000] [0/4] [sentry]: Creating                     
ERRO[0000] Failed Creating countly : json: cannot unmarshal number into Go value of type string 
ERRO[0000] Failed to start: countly : json: cannot unmarshal number into Go value of type string 
DEBU[0000] Found service flower                         
DEBU[0000] Found service sentry                         
DEBU[0000] Finding service sentry-data                  
ERRO[0000] Failed Creating sentry : json: cannot unmarshal number into Go value of type string 
DEBU[0000] [0/4] [flower]: Created                      
ERRO[0000] Failed to start: sentry : json: cannot unmarshal number into Go value of type string 
ERRO[0000] Failed to start: sentry-data : json: cannot unmarshal number into Go value of type string 
FATA[0000] json: cannot unmarshal number into Go value of type string 
```
When I remove link to the service with gluster, service creates without errors

**Comment by deniseschannon** [comment]
@petyunchik Can you provide the docker-compose that you are using to create this?

**Comment by petyunchik** [comment]
@deniseschannon 
```
sentry:
  build: .
  dockerfile: backend/docker/sentry/Dockerfile
  restart: always
  stdin_open: true
  tty: true
  external_links:
  - common/redis:redis
  labels:
    io.rancher.scheduler.affinity:host_label: host.services=true


flower:
  environment:
    AMQP_HOST: rabbitmq
    AMQP_ADMIN_HOST: rabbitmq
  tty: true
  image: totem/celery-flower-docker:latest
  stdin_open: true
  external_links:
  - common/rabbitmq:rabbitmq
  labels:
    io.rancher.scheduler.affinity:host_label: host.services=true


countly:
  tty: true
  image: countly/countly-server
  volumes:
  - countly-data:/var/lib/mongodb
  stdin_open: true
  volume_driver: gluster-convoy
  labels:
    io.rancher.scheduler.affinity:host_label: host.services=true


sentry-data:
  tty: true
  image: postgres
  volumes:
  - sentry-data:/var/lib/postgresql/data
  stdin_open: true
  volume_driver: gluster-convoy
  labels:
    io.rancher.scheduler.affinity:host_label: host.services-data=true
```
External services are official images

**Comment by deniseschannon** [comment]
@silviupanaite @petyunchik Could you provide your Rancher version and rancher-compose version? I'm thinking this might be an issue with incompatibility. 

If you set an environmet variable for while you run rancher-compose, it will give a very verbose dump, but it would help us debug. 

`RANCHER_CLIENT_DEBUG=true rancher-compose`

**Comment by silviupanaite** [comment]
Component	Version
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2

doing rancher-compose up --upgrade developer

GET https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E

	Response <= {"type":"collection","resourceType":"environment","links":{"self":"https://xxx/v1/environments"},"createTypes":{},"actions":{},"data":[{"id":"1e14","type":"environment","links":{"self":"https://xxx/v1/environments/1e14","account":"https://xxx/v1/environments/1e14/account","services":"https://xxx/v1/environments/1e14/services","composeConfig":"https://xxx/v1/environments/1e14/composeconfig"},"actions":{"upgrade":"https://xxx/v1/environments/1e14/?action=upgrade","update":"https://xxx/v1/environments/1e14/?action=update","remove":"https://xxx/v1/environments/1e14/?action=remove","addoutputs":"https://xxx/v1/environments/1e14/?action=addoutputs","activateservices":"https://xxx/v1/environments/1e14/?action=activateservices","deactivateservices":"https://xxx/v1/environments/1e14/?action=deactivateservices","exportconfig":"https://xxx/v1/environments/1e14/?action=exportconfig"},"name":"xxx-cassandra","state":"active","accountId":"1a8","created":"2015-07-28T12:20:23Z","createdTS":1438086023000,"description":null,"dockerCompose":null,"environment":null,"externalId":null,"kind":"environment","outputs":null,"previousExternalId":null,"rancherCompose":null,"removed":null,"startOnCreate":null,"transitioning":"no","transitioningMessage":null,"transitioningProgress":null,"uuid":"dfb97329-1408-4eaa-88e7-82e2c3880bfb"}],"sortLinks":{"accountId":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=accountId","created":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=created","description":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=description","externalId":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=externalId","id":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=id","kind":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=kind","name":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=name","removeTime":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=removeTime","removed":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=removed","state":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=state","uuid":"https://xxx/v1/environments?name=xxx-cassandra&removed_null=%3Cnil%3E&sort=uuid"},"pagination":{"first":null,"previous":null,"next":null,"limit":100,"total":null,"partial":false},"sort":null,"filters":{"accountId":null,"created":null,"description":null,"externalId":null,"id":null,"kind":null,"name":[{"modifier":"eq","value":"xxx-cassandra"}],"removeTime":null,"removed":[{"modifier":"null","value":"<nil>"}],"state":null,"uuid":null},"createDefaults":{}}

GET https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E

	Response <= {"type":"collection","resourceType":"service","links":{"self":"https://xxx/v1/services"},"createTypes":{"dnsService":"https://xxx/v1/dnsservices","externalService":"https://xxx/v1/externalservices","loadBalancerService":"https://xxx/v1/loadbalancerservices","service":"https://xxx/v1/services"},"actions":{},"data":[{"id":"1s553","type":"service","links":{"self":"https://xxx/v1/services/1s553","account":"https://xxx/v1/services/1s553/account","consumedbyservices":"https://xxx/v1/services/1s553/consumedbyservices","consumedservices":"https://xxx/v1/services/1s553/consumedservices","environment":"https://xxx/v1/services/1s553/environment","instances":"https://xxx/v1/services/1s553/instances","serviceExposeMaps":"https://xxx/v1/services/1s553/serviceexposemaps","containerStats":"https://xxx/v1/services/1s553/containerstats"},"actions":{"update":"https://xxx/v1/services/1s553/?action=update","remove":"https://xxx/v1/services/1s553/?action=remove","setservicelinks":"https://xxx/v1/services/1s553/?action=setservicelinks","removeservicelink":"https://xxx/v1/services/1s553/?action=removeservicelink","upgrade":"https://xxx/v1/services/1s553/?action=upgrade","deactivate":"https://xxx/v1/services/1s553/?action=deactivate","addservicelink":"https://xxx/v1/services/1s553/?action=addservicelink"},"name":"cassandra-node","state":"active","accountId":"1a8","createIndex":1,"created":"2015-09-15T15:44:42Z","createdTS":1442331882000,"description":null,"environmentId":"1e14","externalId":null,"fqdn":null,"kind":"service","launchConfig":{"startOnCreate":true,"publishAllPorts":false,"privileged":false,"stdinOpen":true,"tty":true,"readOnly":false,"networkMode":"managed","healthCheck":null,"networkContainerId":null,"labels":{},"environment":{"SEEDS":"172.17.13.111"},"dataVolumes":[],"dataVolumesFrom":[],"dns":[],"dnsSearch":[],"capAdd":[],"capDrop":[],"devices":[],"imageUuid":"docker:docker.unifiedinbox.com:4433/uib/cassandra:beta","ports":[],"instanceLinks":{},"count":null,"description":null,"hostname":null,"volumeDriver":null,"workingDir":null,"user":null,"domainName":null,"memorySwap":null,"memory":null,"cpuSet":null,"cpuShares":null,"pidMode":null,"requestedHostId":5,"restartPolicy":{"name":"no"}},"metadata":null,"publicEndpoints":null,"removed":null,"scale":1,"secondaryLaunchConfigs":null,"selectorContainer":null,"selectorLink":null,"serviceSchemas":null,"transitioning":"no","transitioningMessage":null,"transitioningProgress":null,"upgrade":null,"uuid":"ac4a4b78-84d8-4215-8a81-6a0b5365a290","vip":"169.254.111.127"}],"sortLinks":{"accountId":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=accountId","createIndex":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=createIndex","created":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=created","description":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=description","environmentId":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=environmentId","externalId":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=externalId","id":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=id","kind":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=kind","name":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=name","removeTime":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=removeTime","removed":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=removed","selectorContainer":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=selectorContainer","selectorLink":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=selectorLink","state":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=state","uuid":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=uuid","vip":"https://xxx/v1/services?environmentId=1e14&name=cassandra-node&removed_null=%3Cnil%3E&sort=vip"},"pagination":{"first":null,"previous":null,"next":null,"limit":100,"total":null,"partial":false},"sort":null,"filters":{"accountId":null,"createIndex":null,"created":null,"description":null,"environmentId":[{"modifier":"eq","value":"14"}],"externalId":null,"id":null,"kind":null,"name":[{"modifier":"eq","value":"cassandra-node"}],"removeTime":null,"removed":[{"modifier":"null","value":"<nil>"}],"selectorContainer":null,"selectorLink":null,"state":null,"uuid":null,"vip":null},"createDefaults":{}}

time="2015-12-30T05:36:23Z" level=error msg="Failed Starting ue-developer : json: cannot unmarshal number into Go value of type string" 
time="2015-12-30T05:36:23Z" level=error msg="Failed to start: ue-developer : json: cannot unmarshal number into Go value of type string" 
time="2015-12-30T05:36:23Z" level=fatal msg="json: cannot unmarshal number into Go value of type string"

**Comment by deniseschannon** [comment]
@silviupanaite Can you do a `rancher-compose -v` to check your actual rancher-compose version?

Do you have the same issue if you used the same docker-compose.yml and rancher-compose.yml  in the *Add Stack* section of the UI?

**Comment by silviupanaite** [comment]
Rancher Compose v0.6.2
And in the ui there's nothing wrong, the same config works. Exported the config form the ui and tried to to a upgrade, got the same error.

**Comment by deniseschannon** [comment]
I am still unable to reproduce this issue. 

It looks like these are very old services as they have the `restart:no` in the exported yaml. We removed exporting that a couple of months ago. I'm not sure what could be the issue.

**Comment by sshipway** [comment]
FWIW, when I had this unmarshal error ocurring, it turned out to be related to these ---
- Docker 1.7 or 1.8 (some things seem to need 1.9 now) 
- Legacy docker-compose or rancher-compose with the `restart:` option (and possibly others) in it

The older docker came with the version of CoreOS we were using, and rancher seemed to not handle these old options gracefully (though now it does?)

Once I upgraded to docker 1.9, and re-created the YAML for stacks with these old options, I've not see the problem again.

**Comment by silviupanaite** [comment]
Thanks, will see what turn out.

**Comment by deniseschannon** [comment]
Actually, I could see that it might be a docker version issue as the `json` part of it has always stumped me. We only unmarshal and marshal yaml files in rancher-compose, so I still haven't pin pointed where the `json` unmarhsalling occurs...

**Comment by deniseschannon** [comment]
Seeing as we are only supporting Docker 1.9.1+ and these issues have seemed to stem from older versions of Docker, I'll be closing this issue. If you still face this issue with a later Docker version, please re-open and we can investigate.

**Comment by cruel20** [comment]
Hi 
We have the same problem as silviupanaite. 
Our Rancher versions: 
![rancher](https://cloud.githubusercontent.com/assets/6128996/13457311/d68a4f20-e067-11e5-80c9-b0c776c5c88e.png)

our docker compose: 
![1](https://cloud.githubusercontent.com/assets/6128996/13457382/35bb026e-e068-11e5-9676-bbe84e3d871b.png)

and error showing in ui 
![2](https://cloud.githubusercontent.com/assets/6128996/13457362/12cd2d0e-e068-11e5-96da-7b02e3493206.png)
 
this only exists when We add external_links. Od machine we have docker 1.9.1

**Comment by deniseschannon** [comment]
@cruel20 How are you adding the docker-compose.yml into Rancher? Are you using rancher-compose or the UI?

**Comment by sshipway** [comment]
@cruel20 - This looks like the problem we had when our Volume definitions were naked on one side.  Your links ars also naked, maybe that is it?  Try using 'db:db' rather than 'db:' and it will probably work?

**Comment by adrian-ochocki** [comment]
@deniseschannon, it doesn't matter. We use rancher-compose and UI and in both are errors. 

But we saw few things:
1) we saw that if we add by hand external link by upgrade container "backend" it works ! but it didn't on rancher-compose or the UI.  
2) if we add docker compose by rancher compose there is error, and in created stack docker compose there isn't any external links. It disappear !

**Comment by deniseschannon** [comment]
@cruel20 In v0.61.0-rc3 and rancher-compose v0.7.2, I am unable to reproduce. I made a service called `db` in stack `fdb-gap`.  I launched the following docker-compose.yml in the "Add Stack" section, which runs rancher-compose. Since the thought is that the external links are causing the issue, I removed the volumes.

```
db:
  image: postgres:9.4.1
memcache: 
  image: memcached:latest
backend:
  environment: 
    DJANGO_SETTINGS_MODULE: conf.backend.settings
  external_links:
  - fdb-gap/db:source_db
  image: nginx
  links:
  - ‘memcache:’
  - ‘db:’
  - ‘conf:’
conf:
  image: nginx
frontend:
  image: nginx
  links:
  - 'backend:'
```

Can you try removing your volumes and see if it works?

@adrian-ochocki Can you provide your docker-compose.yml?
