### ISSUE TITLE
healthcheck is applied to sidekicks too

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2503]
local rancher-comose file
```
api:
  scale: 2
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 2000
```
rancher-compose-file in UI
```
api:
  scale: 2
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
api-conf:
  scale: 2
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
```
Sidekick is nothing than volume container, why should i healthcheck it?

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml as well so I can test the use case? It sounds like a rancher-compose issue.

**Comment by ndelitski** [comment]
myapp/docker-compose.yml
```yml
redis:
  image: rancher/external-service
api-conf:
  image: # some image exposing config file in /etc/myapp, i'm using confd approach
  command: '-backend=redis -node=redis:6379 -interval=5'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - /etc/myapp
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
api:
  image: # some app using conf file mounted from sidekick
  expose:
    - 3000
  links:
    - 'redis:redis'
  volumes_from:
    - api-conf
  environment:
    NODE_ENV: production
    CONFIGURATION_FILE: /etc/myapp/config.json
  restart: always
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
    'io.rancher.scheduler.affinity:host_label': role=infra
    io.rancher.sidekicks: api-conf
```
myapp/rancher-compose.yml
```yml
redis:
  hostname: redis.domain
  health_check:
    port: 6379
    interval: 2000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 2000
api:
  scale: 2
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /ping HTTP/1.0
    healthy_twhreshold: 2
    response_timeout: 2000
```
<img width="276" alt="screenshot 2015-11-02 21 07 32" src="https://cloud.githubusercontent.com/assets/3070298/10889901/cb42d388-81a5-11e5-90ee-05ba8300f746.png">
