### ISSUE TITLE
could not find image: no such id: rancher/external-service:latest

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2505]
I suppose it is not currently possible to define external service with `rancher-compose`?
rancher 0.43.1
rancher-compose 0.5.0
UPD: `rancher-compose pull` doesn't work if compose file have external-service definition
```
FATA[0017] Pull failed on one of the hosts
```
UPD2: `rancher-compose up` trying to pull rancher/external-service and fails
UPD3: From UI everything works fine

**Comment by vincent99** [comment]
`rancher/external-service` is a special value rancher-compose recognizes and not a real image.  I think adding `:latest` makes it not recognized.

**Comment by ndelitski** [comment]
i understand that is a special value, but rancher-compose should also be aware of it independently of `:latest` hacks. btw in docs example is using `rancher/external-service`

**Comment by deniseschannon** [comment]
can you share your `docker-compose.yml`?

**Comment by ndelitski** [comment]
@deniseschannon lol false panic. This happens if you specify external service twice:
```
redis:
  hostname: redis.domain
redis:
  health_check:
    port: 6379
    interval: 2000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 2000
```
I thought healthchecks work with externals too
