### ISSUE TITLE
Role data needs to be updated for Istio 1.4.3 CRDs

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#25077]
**What kind of request is this (question/bug/enhancement/feature request):**

Istio has deprecated the [rbac.istio.io resource](https://istio.io/docs/reference/config/security/istio.rbac.v1alpha1/) in favor of the [security.istio.io resource](https://istio.io/docs/reference/config/security/authorization-policy/). 

A project member in Rancher should be able to create the new resources, but are unable to because security.istio.io group has not been added to the Project Owner and Project Member roles.

Important: Possible that other CRDs have changed....

**Steps to reproduce (least amount of steps as possible):**

* Setup rancher 2.3.4 with Istio 1.4.3/300
* Make a user, and a project, and put user in project
* Have user attempt to get/create a resource: `kubectl get authorizationpolicies.security.istio.io -n projns`, this will fail with "Forbidden" error. Note you can get old CRDs: `kubectl get serviceroles.rbac.istio.io -n projns`

**Comment by davidnuzik** [comment]
Added blocker label; blocking v2.3.5 release.

**Comment by rancher-max** [comment]
I think we also need to add resources that we are currently missing. When I enable istio in a cluster, I see all of these Namespaced CRDs:
```
policies.authentication.istio.io 
adapters.config.istio.io               
attributemanifests.config.istio.io     
handlers.config.istio.io   
httpapispecbindings.config.istio.io    
httpapispecs.config.istio.io    
instances.config.istio.io   
quotaspecbindings.config.istio.io   
quotaspecs.config.istio.io            
rules.config.istio.io                   
templates.config.istio.io       
destinationrules.networking.istio.io   
envoyfilters.networking.istio.io       
gateways.networking.istio.io       
serviceentries.networking.istio.io        
sidecars.networking.istio.io         
virtualservices.networking.istio.io                           
rbacconfigs.rbac.istio.io               
servicerolebindings.rbac.istio.io      
serviceroles.rbac.istio.io            
authorizationpolicies.security.istio.io
```
There are extras included in our role_data file which I think are okay, but the ones missing and should be included are: `adapters.config.istio.io`, `attributemanifests.config.istio.io`, `httpapispecbindings.config.istio.io`, `httpapispecs.config.istio.io`, `instances.config.istio.io`, and `templates.config.istio.io`.

**Comment by rancher-max** [comment]
As far as authorizationpolicy is concerned, **the fix is working in 2.3-head commit 026a39c** See below steps:

As project owner and project member, in default namespace:
1. `kubectl get authorizationpolicy` should not be forbidden
2. `kubectl apply -f authpol.yaml` should not be forbidden
3. `kubectl delete authorizationpolicy xyz` should not be forbidden

As read only project member in default namespace:
1. `kubectl get authorizationpolicy` should not be forbidden
2. `kubectl apply -f authpol.yaml` should be forbidden
3. `kubectl delete authorizationpolicy httpbin` should be forbidden

authpol.yaml:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: httpbin
 namespace: default
spec:
 selector:
   matchLabels:
     app: httpbin
     version: v1
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/default/sa/sleep"]
   - source:
       namespaces: ["test"]
   to:
   - operation:
       methods: ["GET"]
       paths: ["/info*"]
   - operation:
       methods: ["POST"]
       paths: ["/data"]
   when:
   - key: request.auth.claims[iss]
     values: ["https://accounts.google.com"]
```
