### ISSUE TITLE
StatefulSet.apps \"redis-master\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

### ISSUE THREAD

**Issue by Rancheroo** [rancher/rancher#25089]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug (Related to ZD-7801)

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Redis from helm library (not using Rancher library, cannot replicate using Rancher provided Redis)
NOTE:
edit yaml
```
cluster:
  enabled: false
metrics:
  enabled: true

```
2. goto Workloads and Edit the redis-master workload

3. Click edit on redis (shouls see redis and metrics Sidecar)

4. Click Save and Error message appears
StatefulSet.apps \"redis-master\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

**Result:**
Error Message
StatefulSet.apps \"redis-master\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"

However this does not occur on Rancher Library Redis

**Other details that may be helpful:**
HAR file with captured response in Zendesk 7801
(not attached to github)

This issue has the same message not sure if they are related
https://github.com/rancher/rancher/issues/17463

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.4

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by dsargent3220** [comment]
W are having this issue when we try to add the metrics endpoint via the UI, we can get around it by editing the YAML directly, but it's quite a pain at the moment.

**Comment by loganhz** [comment]
**Rancher Version:** 2.3.5 amd master
**Steps to reproduce:**

1. Import the following yaml to create a statefulset
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  serviceName: test-headless
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: ubuntu
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        app: test
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem

```
1. Try to edit the StatefulSet in Rancher UI via `Edit Workload` page 

**Results:**

User cannot update the StatefulSet due to`Validation failed in API: StatefulSet.apps "redis-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

**Root Cause:**

After enabled kubernetes audit log in user cluster, we can see there are 3 fields which Rancher should not touch for `volumeClaimTemplate` in this case. They are `kind`, `apiVersion` and `storageClassName`. So the request will not be able to pass the k8s validation.

```
     ....
      "volumeClaimTemplates": [
        {
          "kind": "PersistentVolumeClaim",
          "apiVersion": "v1",
          "metadata": {
            "creationTimestamp": null,
            "labels": { "app": "logan" }
          },
          "spec": {
            "accessModes": ["ReadWriteOnce"],
            "resources": { "requests": { "storage": "8Gi" } },
            "storageClassName": "",
            "volumeMode": "Filesystem"
          },
          "status": { "phase": "Pending" }
        }
      ],
      ...
``` 

**Workaround:**

Use `edit yaml` when your statefulset has `volumeClaimTemplates`.

**Solution:**

- In this case, `apiVersion` and `kind` should not be added in https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/norman/types/mapper/apigroup.go#L16-L28 
- Use `values.RemoveValue` instead of putting an empty string as the type of `StorageClassName`  is `* String` https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/types/mapper/persistvolumeclaim.go#L16

**Comment by deniseschannon** [comment]
@sowmyav27 @bmdepesa Can we try this in the new dashboard UI?

**Comment by aaronRancher** [comment]
This behavior is reproduced on `rancher\rancher:master-head` `version 298a206` and `rancher\rancher:v2.5-head` `version 7d5afc0` with dashboard UI
**Steps:**

- Import the following yaml to create a statefulset
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  serviceName: test-headless
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: ubuntu
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      labels:
        app: test
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
```
- Navigate to dashboard

**Case 1:**
- Edit workload as form
- Make an edit (added a label in this case)
- Save

**Result:**
User is unable to update workload. Fails with `StatefulSet.apps "test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

![Screen Shot 2020-10-20 at 10 52 52 AM](https://user-images.githubusercontent.com/57409052/96627871-53948900-12c6-11eb-8452-b63673cf95fa.png)

**Case 2:**
- Follow the above steps, but edit workload as YAML, not form.
- Make an edit (added a label in this case)
- Save

**Result:**
User is unable to update workload. Fails with `{ "type": "error", "links": {}, "code": "Invalid", "message": "StatefulSet.apps \"test\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden", "status": 422 }`

![Screen Shot 2020-10-20 at 11 02 49 AM](https://user-images.githubusercontent.com/57409052/96628016-85a5eb00-12c6-11eb-93f4-b2de2b497884.png)

Observed different behavior on `rancher\rancher:v2.4-4031-head` with dashboard UI

- Steps were the same as above.
- The user is able to make edits to the workload through form. But is NOT able to make edits through YAML.

Fails with `{ "type": "error", "links": {}, "code": "Invalid", "message": "StatefulSet.apps \"test\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden", "status": 422 }`

![Screen Shot 2020-10-20 at 11 13 27 AM](https://user-images.githubusercontent.com/57409052/96628170-bdad2e00-12c6-11eb-854f-4963683be8af.png)
