### ISSUE TITLE
Stickiness seems to be not working on v0.43.1

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2520]
We need stickiness on LB since `socket.io` doesn't support `sid` sharing between node instances.

@deniseschannon can you please confirm if LB stickiness is working?

`rancher-compose.yml`

``` yaml
https:
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: stk
      domain: omitted
  default_cert: omitted
http:
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: stk
      domain: omitted
```
