### ISSUE TITLE
Inject Build Arguments Secrets into Pipeline

### ISSUE THREAD

**Issue by SvenC56** [rancher/rancher#25246]
Hello,

I am trying to add some build arguments to the pipeline in Rancher. I am not sure how to add those into the PLUGIN_BUILD_ARGS env variable.

```yaml
stages:
  - name: Build and Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: [redacted]:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: [redacted]
        envFrom:
        - sourceName: process-monitoring-build-args
          sourceKey: ADMIN_USER
          sourceKey: ADMIN_PASSWORD
        env:
          PLUGIN_BUILD_ARGS: ADMIN_USER=$ADMIN_USER,ADMIN_PASSWORD=$ADMIN_PASSWORD
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment-rancher.yml

timeout: 60
```

I does not seems to pick up the credentials

I am running on Rancher v2.3.5 and Kubernetes v1.16.6
