### ISSUE TITLE
Mounting project-wide registry secrets as a volume causes UI to hang on Deployment view

### ISSUE THREAD

**Issue by wrossmann** [rancher/rancher#25304]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a registry secret.
    * eg: `foo-registry`
2. Check "Available to all namespaces in this project"
    * Seems to work fine for namespace-specific registry secrets.
3. Add the following to a Deployment [or DaemonSet, or probably any other spec] of your choice:
```
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /root/docker/
          name: foo-registry-config
      volumes:
      - name: foo-registry-config
        secret:
          defaultMode: 420
          secretName: foo-registry
          items:
          - key: .dockerconfigjson
            path: config.json
```
5. Try to view the deployment.

**Result:**

Infinite "page loading" overlay.

**Other details that may be helpful:**

Chrome console log:
```
socket.js:49 Socket connecting (id=1, url=wss://rancher.foo.local:8443/v3/subscribe...)
socket.js:239 Socket opened (state=connecting, id=1)
subscribe.js:254 Cluster Subscribe connected (sockId=1)
socket.js:49 Socket connecting (id=2, url=wss://rancher.foo.local:8443/v3/clusters/c-szgvd/subscribe...)
socket.js:49 Socket connecting (id=3, url=wss://rancher.foo.local:8443/v3/projects/c-szgvd:p-dw8v9/subscribe...)
socket.js:239 Socket opened (state=connecting, id=2)
subscribe.js:254  Subscribe connected (sockId=2)
socket.js:239 Socket opened (state=connecting, id=3)
subscribe.js:254 Project Subscribe connected (sockId=3)
component.js:110 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at n.updateSecretKeys (component.js:110)
    at n.init (component.js:34)
    at n [as init] (utils.js:366)
    at m (core_object.js:83)
    at Function.e.create (core_object.js:611)
    at e.n.create (container.js:554)
    at t.i.create (glimmer.js:4320)
    at Object.evaluate (runtime.js:1559)
    at e.t.evaluate (runtime.js:72)
updateSecretKeys @ component.js:110
init @ component.js:34
n @ utils.js:366
m @ core_object.js:83
e.create @ core_object.js:611
n.create @ container.js:554
i.create @ glimmer.js:4320
(anonymous) @ runtime.js:1559
t.evaluate @ runtime.js:72
t.evaluateSyscall @ runtime.js:3471
t.evaluateInner @ runtime.js:3417
t.evaluateOuter @ runtime.js:3409
a.next @ runtime.js:5530
a.execute @ runtime.js:5514
a.handleException @ runtime.js:4395
t.handleException @ runtime.js:4575
r.throw @ runtime.js:4293
n.evaluate @ runtime.js:911
r.execute @ runtime.js:4280
t.rerender @ runtime.js:4607
o.render @ glimmer.js:4775
k @ metal.js:704
t._renderRoots @ glimmer.js:5079
t._renderRootsTransaction @ glimmer.js:5117
t._revalidate @ glimmer.js:5163
t.invoke @ backburner.js:341
t.flush @ backburner.js:233
t.flush @ backburner.js:437
n._end @ backburner.js:1013
_boundAutorunEnd @ backburner.js:653
Promise.then (async)
r @ backburner.js:26
n._scheduleAutorun @ backburner.js:1227
n._end @ backburner.js:1021
[last 5 messages continue to loop]
```

"Why on earth are you even doing this?" I'm trying to set up a DaemonSet to pre-pull container images to speed up our deployments.

**Environment information**

- Rancher version: v2.3.2
- Installation option: non-HA

**Cluster information**

- Cluster type: Custom
- Machine type and specifications: VM, 8CPU, 16GB RAM
- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version:

```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.5 (single node) & master-head (HA)

* Reproduced in `v2.3.5` & `master-head`
* Deploy Rancher
* Create cluster
* Create a registry secret available to all namespaces
* Create deployment
* Edit deployment yaml to include:
```
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /root/docker/
          name: foo-registry-config
      volumes:
      - name: foo-registry-config
        secret:
          defaultMode: 420
          secretName: foo-registry
          items:
          - key: .dockerconfigjson
            path: config.json
```
* View deployment and UI gets stuck

**Comment by bmdepesa** [comment]
rancher/rancher:master-head  926997017
UI: master-dev

* Reproduced in `v2.3.5` & `master-head`
* Deploy Rancher
* Create cluster
* Create a registry secret available to all namespaces
* Create deployment
* Edit deployment yaml to include:
```
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /root/docker/
          name: foo-registry-config
      volumes:
      - name: foo-registry-config
        secret:
          defaultMode: 420
          secretName: foo-registry
          items:
          - key: .dockerconfigjson
            path: config.json
```
* View deployment and UI does not get stuck
