### ISSUE TITLE
[UI] Cluster went down because of wrong k8s version in cluster edit page

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#25335]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a rke template with the Kubernetes version set to 1.16.x
2. Create a cluster using that RKE template but set the Kubernetes version from drop down to 1.17.2
3. Edit the cluster, the Kubernetes version displayed as "1.16" instead of "1.17.2" in the page
4. Click Save

**Result:**
The cluster will be stuck in the "Updating" state

**Other details that may be helpful:**
Error on UI:
[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [172.31.0.27] failed to report healthy.  Check etcd container logs on each host for more information

Error on etcd container:
etcdserver/membership: cluster cannot be downgraded (current version: 3.3.15 is lower than determined cluster version: 3.4).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4
- Installation option (single install/HA):  HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4core/16GB
- Kubernetes version (use `kubectl version`): 1.17

- Docker version (use `docker version`):
19.03.5

**Comment by westlywright** [comment]
@nickngch do you have any additional info? The data from your rke template (sensitive info redacted please) would be ideal. I am unable to reproduce this using `v2.3.4` or later. I suspect there may be some deeper issue here as you shouldn't have been able to downgrade, at least the versions I tested against wouldn't let me. Was this truly a custom cluster? Meaning that when you launched the cluster you selected `From Existing Nodes (custom)` or did you use one the RKE providers? If at all possible can you get the values for the following settings? `k8s-version`, `ui-k8s-supported-versions-range`, `ui-k8s-default-version-range`

**Comment by nickngch** [comment]
@westlywright sure here are the requested information:

```
# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.16.6-rancher1-2
  monitoring:
    provider: metrics-server
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
windows_prefered_cluster: false
```

Yes it is custom cluster, I created an EC2 instance and ran the `docker run` manually to create the cluster.

I would love to share those information, do you mind to share where can I get those information?
