### ISSUE TITLE
Links being created due to selector links are being removed in `rancher-compose create` or `rancher-compose up`

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2539]
1. seems `io.rancher.service.selector.container` doesn't work with services having sidekicks
2. never get worked `io.rancher.service.selector.link`. tried on plain services and with sidekicks
```yml
service-A:
  image: nginx:1.9.4
  labels:
    foo: bar
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=rabbit
service-B:
  image: nginx:1.9.4
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: role=rabbit
    io.rancher.service.selector.link: foo = bar
```
```
 ~> docker exec 2d7f cat /var/lib/cattle/etc/cattle/dns/answers.json
{
    "default": {
        "recurse": [
            "172.30.0.2"
        ],
        "a": {
        	"rancher-metadata.": {"answer": ["169.254.169.250"]},
		"rancher-metadata.rancher.internal.": {"answer": ["169.254.169.250"]}
		}
    },
    "10.42.22.121": {
        "recurse": [
            "172.30.0.2"
        ],
        "a": {
        	"rancher-metadata.": {"answer": ["169.254.169.250"]},
		"rancher-metadata.rancher.internal.": {"answer": ["169.254.169.250"]},
		"service-a.": {"answer": ["10.42.22.121"]},
		"service-a.rancher.internal.": {"answer": ["10.42.22.121"]}
    	}

    },

    "10.42.8.4": {
        "recurse": [
            "172.30.0.2"
        ],
        "a": {
        	"rancher-metadata.": {"answer": ["169.254.169.250"]},
		"rancher-metadata.rancher.internal.": {"answer": ["169.254.169.250"]},
		"service-b.": {"answer": ["10.42.8.4"]},
		"service-b.rancher.internal.": {"answer": ["10.42.8.4"]}
    	}

    },

    "": {}
}
```
<img width="676" alt="screenshot 2015-11-04 04 52 40" src="https://cloud.githubusercontent.com/assets/3070298/10927333/eeb659ba-82af-11e5-91ae-bf9fd84f929c.png">
```
Rancher	v0.43.1
Cattle	v0.106.0
User Interface	v0.63.0
Rancher Compose	v0.5.0
```
Expected that links will show up in interface and dns would have corresponding entries or hostnames in /etc/hosts

**Comment by ndelitski** [comment]
UPD for 2: service links doesn't works in local stack scope, but work with external services. in local stack work only from LB-type services.
Great case: put service-A and and LB in stack-1, service-EXT in stack-2. both services A and EXT have label `foo: bar`, LB have ` io.rancher.service.selector.link: foo=bar`. When LB have only link to EXT remove service-A and then bring up. At first EXT link will drop, then will appear link to A, then no one link on LB will be left LOL

**Comment by ndelitski** [comment]
And finaly, when starting container its link selector doesn't evaluate already started services

**Comment by deniseschannon** [comment]
Have you tried to do a refresh on the UI after adding the new containers? Sometimes the links are there, but there is a UI issue displaying them.

How are you adding these services? Using rancher-compose CLI? Using the import of docker-compose through the add stack button?

```
service-A:
  labels:
    foo: bar
  image: nginx:1.9.4
service-B:
  labels:
    io.rancher.service.selector.link: foo = bar
  image: nginx:1.9.4
```

**Comment by sangeethah** [comment]
@ndelitski , Can you try with no space in selector.link value - io.rancher.service.selector.link: foo=bar ?

**Comment by ndelitski** [comment]
@sangeethah @deniseschannon don't see any links neither from `rancher-compose` CLI nor when i create stack from UI, refresh didn't help and eliminating spaces too.
What i see when created stack from UI
```
service-B:
  labels:
    io.rancher.scheduler.affinity:host_label: role=rabbit
    io.rancher.service.selector.link: foo = bar
    io.rancher.service.hash: 0c411d1f55bc43c655f59a486004af24d3683d7b
  image: nginx:1.9.4
service-A:
  labels:
    io.rancher.scheduler.affinity:host_label: role=rabbit
    io.rancher.service.hash: a1df9cf66169b6b013b3dc2995b2f4dd1b38a1a1
    foo: bar
  image: nginx:1.9.4
```
No links in rancher DNS too...
