### ISSUE TITLE
Rancher-compose: When importing stacks with selector links, two links are being made.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2541]
v0.43.1
rancher-compose v0.5.0

Using "Add Stack" and the import `docker-compose.yml` section, when I add the below docker-compose.yml, two links are being created instead of just 1. I believe this is due to how we handle circular links. 

Note: this doesn't happen when using `rancher-compose` CLI. 

```
service-A:
  labels:
    foo: bar
  image: nginx:1.9.4
service-B:
  labels:
    io.rancher.service.selector.link: foo = bar
  image: nginx:1.9.4
```
