### ISSUE TITLE
healthcheck caused initializing state on main container when it have shared network with sidekick

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2547]
```yml
frontend-conf:
  image: debian
  command: 'sleep infinity'
  volumes:
    - /etc/nginx/conf.d
frontend:
  image: nginx:1.9.4
  expose:
    - 80
  volumes_from:
    - frontend-conf
  restart: always
  tty: true
  stdin_open: true
  net: 'container:frontend-conf'
```
```yml
frontend:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
```
<img width="513" alt="screenshot 2015-11-05 00 03 44" src="https://cloud.githubusercontent.com/assets/3070298/10951826/b2b8e378-8350-11e5-83d9-cf063e8d3527.png">

**Comment by deniseschannon** [comment]
How are you adding these containers into Rancher? Using UI or CLI? Is this the docker-compose.yml and rancher-compose.yml that you're using when you do a `rancher-compose up`?

The sidekick label is missing from your `docker-compose.yml`, but even if I add it in, both of my containers end up in initializing state. I'm not sure what this docker-compose.yml is supposed to do. 

Also, expose does nothing in Rancher compose. We basically ignore it. If you want it exposed, you'd need to use ports.

**Comment by ndelitski** [comment]
Didn't know such details about expose, thx.
I used `rancher-compose up` and you are right - these are docker-compose and rancher-compose files respectively. Sorry, but I definitely have missed the sidekick label.
I post here simplified versions of what i have in reality, to make you easy to reproduce. Everything for you @deniseschannon :D
Tried again with files below just now, result is the same. All my services have configurations sidekicks, same approach you use in `rancher-catalog` services.
docker-compose.yml
```yml
frontend-conf:
  image: debian
  command: sleep infinity
  volumes:
    - /tmp
frontend:
  image: crccheck/hello-world
  volumes_from:
    - frontend-conf
  tty: true
  stdin_open: true
  net: 'container:frontend-conf'
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: frontend-conf
```
rancher-compose.yml
```yml
frontend:
  scale: 1
  health_check:
    port: 8000
    interval: 2000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 1
    response_timeout: 2000
```
run in terminal
```
$ rancher-compose --url=http://rancher-domain/v1/projects/1a7 --access-key= --secret-key= -p example -f .generated.example.compose@staging.yml -r ./stacks/example/rancher-compose@staging.yml up -d
```
<img width="1292" alt="screenshot 2015-11-06 02 33 07" src="https://cloud.githubusercontent.com/assets/3070298/10985010/c2c93126-842e-11e5-92f5-8327def10719.png">

What do you think is it normal? I expect that both containers should be green.
