### ISSUE TITLE
kube-api extra args not accepting arrays

### ISSUE THREAD

**Issue by smithhannahm** [rancher/rancher#25500]
**What kind of request is this (question/bug/enhancement/feature request):**
A bug

**Steps to reproduce (least amount of steps as possible):**
Edit the Cluster Options as YAML, and add an extra argument to the kube-api section that should accept an array, such as `service-account-key-file`

```
 kube-api: 
    always_pull_images: false
    extra_args: 
      api-audiences: "sts.amazonaws.com"
      service-account-issuer: "https://s3.amazonaws.com/mybucket"
      service-account-key-file:
        - "/etc/kubernetes/ssl/key1.pub"
        - "/etc/kubernetes/ssl/key2.pub"
      service-account-signing-key-file: "/etc/kubernetes/ssl/private.key"
    pod_security_policy: false
    service_node_port_range: "30000-32767"
```

**Result:**

When you hit save, nothing happens. When you go back to the edit YAML screen, it has reverted to the first element in the array.

```
 kube-api: 
    always_pull_images: false
    extra_args: 
      api-audiences: "sts.amazonaws.com"
      service-account-issuer: "https://s3.amazonaws.com/mybucket"
      service-account-key-file: "/etc/kubernetes/ssl/key1.pub"
      service-account-signing-key-file: "/etc/kubernetes/ssl/private.key"
    pod_security_policy: false
    service_node_port_range: "30000-32767"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): on prem VM, 2 CPU, 4GB 
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

SURE-4205

**Comment by jrdelarosa8** [comment]
Running into this same problem on Rancher v2.3.5.

**Comment by burgerjeffrey** [comment]
@smithhannahm did you ever get this working?

**Comment by burgerjeffrey** [comment]
Is this new work being added into Rancher 2.6.6.?  Is there a tentative release date?  Thanks!  Very much looking forward to this!

**Comment by snasovich** [comment]
@burgerjeffrey , yes, the plan is to have the fix included in 2.6.6 release. Unfortunately, we don't have the release date for 2.6.6, but _very_ tentatively we're looking at late July - early August at this time.

**Comment by Josh-Diamond** [comment]
Ticket #25500 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6-6fda43e5eb3654cabf6294c9a57e0ecfdfc89520-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE1 Custom cluster
3. Once `Active`, `Edit YAML` and add an array, `service-account-key-file`, under `kube-api` => `extra_args`
4. Save modified cluster config
5. Reproduced - When viewing cluster YAML, `service-account-key-file` only grabs first item in array

Screenshots:

`Step 3`
<img width="473" alt="bbefore" src="https://user-images.githubusercontent.com/46494969/169877774-31229993-535b-40dc-9eca-c218b82249d0.png">

`Step 5`
<img width="622" alt="afterrr" src="https://user-images.githubusercontent.com/46494969/169877800-454d8cca-e0c4-419f-a1cc-03a24c17c1d2.png">

---

Issue was reproduced when it was expected to be verified; requesting QA Template

**Comment by HarrisonWAffel** [comment]
### What was fixed, or what changes have occurred
  A new RKE field has been added which can be placed within the `cluster.yaml` when provisioning or editing a cluster. This field is called `extra_args_array` and can be used to specify extra arguments which can be passed multiple times with different values. 
### Areas or cases that should be tested
Test Steps:
Test case 1 (successful provisioning) 
 + Create a new DO cluster (1 node, all roles)
 + Once available, SSH into the node
   + run the following commands 
     + `cp /etc/kubernetes/ssl/kube-apiserver-key.pem /etc/kubernetes/ssl/kube-apiserver-key2.pem`
     + `cp /etc/kubernetes/ssl/kube-apiserver-key.pem /etc/kubernetes/ssl/kube-apiserver-key3.pem`
 + modify the cluster.yaml and replace the `kubeapi` section with the following 
```
kube-api:
      always_pull_images: false
      extra_args_array:
        service-account-key-file:
          - /etc/kubernetes/ssl/kube-apiserver-key.pem
          - /etc/kubernetes/ssl/kube-apiserver-key2.pem
          - /etc/kubernetes/ssl/kube-apiserver-key3.pem
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
```
 + apply changes and observe cluster go into `active` state

Test case 2 (expected failed provisioning) 
 + create new downstream cluster in DO (1 node, all roles)
 + modify the cluster yaml BEFORE creating the cluster
 + Replace the `kube-api` field with the following value 
```kube-api:
      always_pull_images: false
      extra_args_array:
        service-account-key-file:
          - /etc/kubernetes/ssl/kube-apiserver-key.pem
          - /etc/kubernetes/ssl/blah.pem
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
```
+ Save the cluster 
+ Observe cluster errors out with the following error (expected) ```
[controlPlane] Failed to upgrade Control Plane: [[Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [104.131.53.240]: Get "https://localhost:6443/healthz": dial tcp [::1]:6443: connect: connection refused, log: Error: open /etc/kubernetes/ssl/blah.pem: no such file or directory]]```

### What areas could experience regressions?
  This PR adds an extra field which is treated independently from other fields, no regressions should occur
### Are the repro steps accurate/minimal?
Yes, both test cases are minimal and should show that the new field works correctly when setup properly, and fail when not setup properly.
