### ISSUE TITLE
"upgradeStrategy" is not set on cluster when "upgradeStrategy" is set to null

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25503]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a cluster through the API. 
- "upgradeStrategy" is not set on the cluster
- View in API of the cluster, does not show the "upgradeStrategy" set

**Actual Result:**
- View in API of the cluster, does not show the "upgradeStrategy" set

**Expected Result:**

- When "upgradeStrategy" is not set, default values should be set on the cluster
- This happens when you create a cluster from the rancher UI.
- While creating a cluster with default values of the maxUnavailable and Drain input settings, View in API of the cluster shows the default values set on the cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sangeethah** [comment]
`UpgradeStatergy` is also not set on clusters that were created when rancher server was in 2.3.5 and then upgraded to `master-head` . We should expect the existing clusters to have the `UpgradeStatergy`  set when rancher server gets upgraded to  `master-head` ?

**Comment by sowmyav27** [comment]
**Verified on latest - master-head - commit id: `926997017`**
- Create a cluster, via Edit as YAML, set `upgradeStrategy: {}`
- When the cluster is deployed, do an Edit on cluster --> Edit as YAML, the default values for `upgradeStrategy` are available in the yaml

```
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: 30
      ignore_daemon_sets: true
      timeout: 60
```
