### ISSUE TITLE
istio destination rule subset should not be required

### ISSUE THREAD

**Issue by stephen-dahl** [rancher/rancher#25513]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
create a new istio destination rule without any subsets

**Result:**
```
Validation failed in API: DestinationRule.networking.istio.io "test" is invalid: spec.subsets: Invalid value: "null": spec.subsets in body must be of type array: "null"
```

**Other details that may be helpful:**
https://istio.io/docs/reference/config/networking/destination-rule/
istio does not require a subset to be specified as shown in their first example
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bookinfo-ratings
spec:
  host: ratings.prod.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
```
I am able to create this rule with kubectl however creating it through the ui would show the above error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Installation option (single install/HA): HA
