### ISSUE TITLE
istio destination rule cookie based hash error

### ISSUE THREAD

**Issue by stephen-dahl** [rancher/rancher#25515]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create new destination rule.
2. set loadbalancing to cookie based hash
![image](https://user-images.githubusercontent.com/6061073/75060563-e6f59000-5493-11ea-8f29-706d90c09186.png)
4. save

**Result:**
```
Validation failed in API: DestinationRule.networking.istio.io "test" is invalid: [: Invalid value: "": "spec.trafficPolicy.loadBalancer" must validate one and only one schema (oneOf). Found none valid, : Invalid value: "": "spec.trafficPolicy.loadBalancer.consistentHash" must validate one and only one schema (oneOf). Found 2 valid alternatives]
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Installation option (single install/HA): HA

**Comment by cbron** [comment]
Workaround here is to use `kubectl apply`.

**Comment by cbron** [comment]
I reproduced this a few weeks back, but now I can't on either Istio 1.4.7 or 1.4.8. Tested on Rancher master branch (2783-head), so it may have already been resolved.

**Comment by rancher-max** [comment]
I was able to recreate this on v2.4.3 and v2.4-head both using Istio v1.4.700 and 1.4.800 respectively, following the same steps mentioned in the issue.

**Comment by cbron** [comment]
There is an issue where our API is validating openAPI schema differently than k8s.
This works when applied with kubectl: 
``` apiVersion: networking.istio.io/v1alpha3
 kind: DestinationRule
 metadata:
   name: bookinfo-ratings
 spec:
   host: ratings.prod.svc.cluster.local
   trafficPolicy:
     loadBalancer:
       consistentHash:
         httpCookie:
           name: user
           ttl: 0s
```

The equivalent does not, when going to our api: 
```
{
  "type": "destinationrule",
  "namespaceId": "default",
  "trafficPolicy": {
    "loadBalancer": {
      "consistentHash": {
        "httpCookie": {
          "ttl": "0s",
          "name": "user"
        }
      }
    }
  }
}
```

**Comment by cbron** [comment]
Appears that somewhere along the line the 	`"useSourceIp"` param is getting set to false even if it's not set. This violates the onlyOne portion [of the requirement](https://archive.istio.io/v1.4/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB). Which makes sense as the http header option is also broken, but the useSourceIp is not. Passing it as null does not fix.

**Comment by cbron** [comment]
Here are the 4 cases I used for testing upgrade between old and new behavior:

```
k apply -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml
k apply -f ....

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "source"
spec:
  host: sleep
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "cookie"
spec:
  host: sleep
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: cookie
          path: /path
          ttl: 2s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "header"
spec:
  host: sleep
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "header"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "simple"
spec:
  host: sleep
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
```
