### ISSUE TITLE
OPA Gatekeeper - Upon Deleting Gatekeeper App, delete built in contrainttemplates

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#25575]
OPA Gatekeeper app is deployed via system chart: https://github.com/rancher/rancher/issues/23753

The chart also installs the ConstraintTemplate CRDs and few builtin ConstraintTemplates.

After Gatekeeper is deleted from the cluster,  CRDs and CRs installed by helm are not cleaned up via helm. 

Rancher needs to handle deletion of these resources after deleting Gatekeeper.

**Comment by prachidamle** [comment]
The issue with constraintTemplate CRD and constraints left behind after deleting gatekeeper seems to be an issue with gatekeeper. 

It has been documented on gatekeeper and they ask to manually cleanup the ConstraintTemplate CRD and resources before deleting gatekeeper: https://github.com/open-policy-agent/gatekeeper#uninstallation

I have tested gatekeeper on a vanilla kubernetes cluster on GKE:

1) Installed gatekeeper using the helm installation instructions on https://github.com/open-policy-agent/gatekeeper
Chart used: https://github.com/open-policy-agent/gatekeeper/tree/master/chart/gatekeeper-operator

2) This helm chart from gatekeeper installed the constrainttemplate CRD on the cluster. 
I then also installed few constraints.

3) Upon uninstalling gatekeeper via helm, the constrainttemplate CRD and constraints were not cleaned up.

**Comment by khushboo-rancher** [comment]
Tested on master-2450-head- 73f603f9f
On deleting gatekeeper app, constraint template isn't getting deleted if we have constraint under it.

Steps followed.
1. Enabled OPA gatekeeper for a cluster.
2. Create a constraint under 'k8srequiredlabels' template.
sample : 
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ingress-must-have-test-label
spec:
  match:
    kinds:
    - apiGroups:
      - extensions
      kinds:
      - Ingress
  parameters:
    message: All Ingress must have an `test` label
    labels:
    - key: test
      allowedRegex: "^[a-zA-Z]"
```
3. Delete the app using disable OPA gatekeeper option.
4.  'k8srequiredlabels' doesn't get deleted.
