### ISSUE TITLE
Accept maxUnavailable for control plane nodes during upgrade 

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#25599]
maxUnavailable can be passed for control plane nodes too during zero downtime upgrade.
Default will be 1.

**Comment by sowmyav27** [comment]
**Verified in `rancher:v2.4.0-rc1`**

- In cluster.yml, following is available:
```
    upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
```
