### ISSUE TITLE
MaxUnavailable field should be exposed for controlplane nodes too

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#25601]

**Comment by deniseschannon** [comment]
We are only going to handle updating maxUnavailable in cluster.yml and not in the form for the UI.

**Comment by sowmyav27** [comment]
**verified on latest master-head commit id: `55422ebce`**

In the cluster.yml `max_unavailable_controlplane` is seen with default value 1 
```
upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
```
