### ISSUE TITLE
parameters "extra_args: null" is is seen in cluster.yml 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25612]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- deploy a cluster on latest master
- Edit of cluster - edit in YAML

```
kube-controller:
      extra_args: null
    kubelet:
      extra_args: null
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy:
      extra_args: null
    scheduler:
      extra_args: null
  ssh_agent_auth: false
```

**Expected Result:**
Additional arguments should not be seen in the cluster.yml file extra_args: null

**Other details that may be helpful:**
Related issue: https://github.com/rancher/rancher/issues/24794

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by sowmyav27** [comment]
**verified on the latest master-head - ui tag: `latest2`**

- deploy a cluster on latest master
- Edit of cluster - edit in YAML
- Additional arguments `extra_args: null` are NOT seen

```
kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
```
