### ISSUE TITLE
Drain option should be available as part of upgrade strategy for controlplanes separately

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25636]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- On the latest master-head, currently we have drain option common for both control plane and worker nodes. 
```
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
```

**Expected Result:**
drain option is available separately for control planes and worker nodes and NOT as a common option

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `5e9cc17e8`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke DO
- Kubernetes version (use `kubectl version`):

```
1.15.10
```
