### ISSUE TITLE
Allow setting custom flexvolume directory for Canal/Calico

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#25681]
**What kind of request is this (question/bug/enhancement/feature request):** Enhancement

Rancher/RKE should support setting a custom flexvolume directory when deploying Canal/Calico. This use case is especially important for when running on ephemeral FS operating systems such as CoreOS Container Linux or Flatcar Linux.

The related RKE issue is here: https://github.com/rancher/rke/issues/1744

When deploying Calico/Canal, it should now be possible to 

Calico
```
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: "/opt/kubernetes/kubelet-plugins/volume/exec/"
network:
  plugin: calico
  options: 
   - calico_flex_volume_plugin_dir: "/opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds"
```

Canal
```
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: "/opt/kubernetes/kubelet-plugins/volume/exec/"
network:
  plugin: calico
  options: 
   - canal_flex_volume_plugin_dir: "/opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds"
```
