### ISSUE TITLE
Add Istio 1.4.6

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#25695]
https://discuss.istio.io/t/upcoming-security-releases-of-istio-1-4-6/5378/2

Changes between 1.4.4 and 1.4.6: https://github.com/istio/istio/compare/1.4.4...1.4.6

**Comment by rancher-max** [comment]
#### Validated using system-charts branch istio-1.4.6

Two main use cases, all scenarios run on both:
1. Fresh install
2. Upgrade in Rancher v2.3.5 from Istio v1.4.400 to Istio v1.4.600. (To do this scenario, I enabled Istio v1.4.400 before switching to the above system-charts branch)

Did a mixture of both automation and manual validation:

Scenario 1 Passed - All automation should execute and pass successfully. This validates gateway, destination rules, crds, rbac, and all of the potential custom answers.

Scenario 2 Passed - All images should use the correct image:
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/55997940/75932723-65a7e100-5e35-11ea-9aa2-95da1f6989ac.png">

Scenario 3 Passed - Previous bug of not being able to give a custom sidecar image passed. For this, I used the following deployment spec (Note this fails in any previous Rancher Istio version):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v1
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
      annotations:
        sidecar.istio.io/proxyImage: "rancher/istio-proxyv2:1.4.3"
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.15.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
```
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/55997940/75934944-21b7da80-5e3b-11ea-9a20-babf0d92a55e.png">

Scenario 4 Passed - All UI elements, including links to kiali, jaeger, prometheus, and grafana should be functional and give the correct results. Below screenshot is of Traffic Graph tab:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/55997940/75935086-85420800-5e3b-11ea-8b76-7a372304adcd.png">

Scenario 5 Passed - Istio v1.4.600 should be the only available version:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/55997940/75935134-ae629880-5e3b-11ea-8c14-b69753fe7919.png">
