### ISSUE TITLE
namespace via kubectl can be created exeeding the project resource Quotas

### ISSUE THREAD

**Issue by OlliL** [rancher/rancher#25794]
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
Create a namespace via "rancher kubectl create -f  yaml-file"
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: c-z8rqx:p-5k5jx
    field.cattle.io/resourceQuota: '{"limit":{"limitsCpu":"30000m","limitsMemory":"20048Mi","requestsCpu":"600000m","requestsMemory":"1000024Mi"}}'
    field.cattle.io/containerDefaultResourceLimit: '{}'
  name: dummy
```

**Result:**
Namespace is created exeeding the Project Resource Quotas. Namespace can also no longer be edited in Rancher UI because then the API Resource Quota validation kicks in and prevents saving any changes.

I would have expected that some kind of admission controller prevents me from creating a namespace in a project context via kubectl exceeding the Rancher defined Project Quota.

**Environment information**
- Rancher version: 2.3.5
- Installation option: HA

**Cluster information**
- Cluster type: Custom
- Machine type: VM
- Kubernetes version: v1.14.6
- Docker version: 19.3

gz#10910
