### ISSUE TITLE
Rancher Authorized Endpoint FQDN cert not working

### ISSUE THREAD

**Issue by isaachui** [rancher/rancher#25815]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Created a k8s cluster via rancher UI: "add cluster" --> "Amazon EC2"
Added fqdn <kube.mydomain.com> and added full wildcard crt in the cert section.

**Result:**
1. The port is not set in the KubeConfig file to 6443 (not sure if this is intentional) but setting the port to 6443 allows me to get this error
2. `Unable to connect to the server: x509: certificate is valid for kube-test-cp2, kube-test-cp1, localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not <kube.mydomain.com>`

kubeconfig file looks like this
```
apiVersion: v1
kind: Config
clusters:
- name: "domain-test"
  cluster:
    server: "https://rancher.domain.com:8443/k8s/clusters/something"
    # my rancher cluster is accessed via ssh port forwarding since its on private network
- name: "domain-test-fqdn"
  cluster:
    server: "https://domain-kube.domain.com"
    # no port specified above ^^
    certificate-authority-data: "BASE64ENCODEDCERT"
    # base64 encoded wildcard crt with ca chain appended

users:
- name: "domain-test"
  user:
    token: "kubeconfig-u-rvxvg.c-sgn4z:7p9595gjsktbh4thnbn6l2mgm9wd799qqkz487g88jcjhpdppbmc6c"

contexts:
- name: "domain-test"
  context:
    user: "domain-test"
    cluster: "domain-test"
- name: "domain-test-fqdn"
  context:
    user: "domain-test"
    cluster: "domain-test-fqdn"

current-context: "domain-test"
```

**Other details that may be helpful:**
The k8s cluster rancher was created was with rke v1.0.4
Rancher version 2.3.5

Ran on both centos and rancheros. Same problem

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Amazon EC2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

- Docker version (use `docker version`):

```
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
