### ISSUE TITLE
Scaling limits on services

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2590]
Per http://forums.rancher.com/t/prevent-service-from-scaling/658 
and
http://forums.rancher.com/t/how-to-disable-scaling-of-service/894

Users would like a way to put a maximum limit of containers on a service.

**Comment by ibuildthecloud** [comment]
+1.  I also need to be able to say only odd number and a minimum.  This is needed for clustered system that need a quorum.

**Comment by vincent99** [comment]
New scalingPolicy embedded type and rancher-compose field?

```
{
  min: 3,
  max: 9,
  increment: 2,
  global: true/false
}
```

Or `odd: true`, but with `min`+`increment` you can express "even", "odd", or "multiple of 5".

This should be combined with #2092 and http://forums.rancher.com/t/request-better-global-scheduling/895 (for global `scale` should be X containers on each host).

And is there a reason for global to be a label on service instead of a property in rancher-compose?

**Comment by ibuildthecloud** [comment]
Mainly because I don't like rancher-compose but anything that is simple key value I prefer labels.  Scale was not put as a label because it's really environment specific and "non-portable."

I would probably opt to have min, max, increment as a label too.  Increment sounds better than odd.

**Comment by ibuildthecloud** [comment]
Okay, maybe labels are bad too.  I just don't like cross referencing between two files for the same service/container

**Comment by mishak87** [comment]
I think labels are cool. I rarely need `rancher-compose.yml` to do something. For most of the time `docker-compose.yml` + `labels:` is enough for me.

Formal: `<val>|<min>..[<max>][*<mul>[+<add>]]`
[Regex](https://regex101.com/r/bD8xW5/1): `^((?P<value>\d+)|(?P<min>\d+\.\.(?P<max>\d+)?)?(\*(?P<mul>\d+(\+(?P<add>\d+))?)?))$`

```yaml
labels:
    io.rancher.service.scale: 1  # just 1
    io.rancher.service.scale: 1..10  # from 1 to 10 ie.: we don't have more licenses
    io.rancher.service.scale: 3..  # 3 and more
    io.rancher.service.scale: 1..4*5  # from 5 to 20 by increments of 5
    io.rancher.service.scale: *2+1  # odd starting from 3
    io.rancher.service.scale: 2..*2+1  # odd starting from 5
    io.rancher.service.scale: 1..10*2  # even starting from 2 to 20
```

 `rancher-compose.yml` scale would take priority if label was defined in `docker-compose.yml`.
