### ISSUE TITLE
Delete Cloned App won't recycle the resources

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#25945]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. create a simple app in project and wait for it active.
2. clone the app without changing anything and wait fir it active too.
3. delete the original app and wait for the resources got recycled.
4. delete the cloned app.

**Result:**
The resources from the cloned app won't get recycled.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
HA install.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by longgerr** [comment]
Reproduced in rancher v2.4.4

Compared the original app and cloned app, noticed `metadata.finalizers` is missed in the cloned app.

original app:
```yaml
- apiVersion: project.cattle.io/v3
  kind: App
  metadata:
    annotations:
      field.cattle.io/creatorId: user-tl48t
      lifecycle.cattle.io/create.helm-controller_c-qjct7: "true"
    creationTimestamp: "2020-08-05T07:50:52Z"
    finalizers:
    - clusterscoped.controller.cattle.io/helm-controller_c-qjct7
    generation: 7
    labels:
      cattle.io/creator: norman
    name: app-v1
```
cloned app, `finalizers` is missing:
```yaml
- apiVersion: project.cattle.io/v3
  kind: App
  metadata:
    annotations:
      field.cattle.io/creatorId: user-tl48t
      lifecycle.cattle.io/create.helm-controller_c-qjct7: "true"
    creationTimestamp: "2020-08-05T07:59:03Z"
    generation: 4
    labels:
      cattle.io/creator: norman
    name: app-v1-clone
```


After adding the missing finalizers to the cloned app with the following value, the cloned app can be deleted without any issue
```yaml
finalizers:
- clusterscoped.controller.cattle.io/helm-controller_c-qjct7
```
