### ISSUE TITLE
Helm template failure when deploying Hazelcast 4.0 using Rancher CLI (but with GUI works fine)

### ISSUE THREAD

**Issue by maurizio-lattuada** [rancher/rancher#26007]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Have this application catalog installed: https://kubernetes-charts.storage.googleapis.com/
2. Variant A: install Hazelcast using the GUI
    1. Select Hazelcast in the app list
    2. set the following yaml file as answer file (file name: "hazelcast-values.yaml")
    ```yaml
    ---
    image:
      repository: "private-internal-registry/hazelcast/hazelcast"
      tag: "4.0"
    cluster:
      memberCount: 2
    metrics:
      enabled: true
    rbac:
      enabled: false
      create: false
    serviceAccount:
      create: false
    mancenter:
      image:
        repository: "private-internal-registry/hazelcast/management-center"
        tag: "4.0"
      persistence:
        enabled: false
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts:
          - "hazelcast.slug.something.xyz"
    hazelcast:
      yaml:
        hazelcast:
          cluster-name: tomcat
          network:
            join:
              kubernetes:
                # Force service-name empty, so Hazelcast uses DNS_LOOKUP and not KUBERNETES_API
                service-name:
                service-dns: "hazelcast-mau2.hazelcast-mau-ns.svc.cluster.local"
    ```
3. Variant B: install Hazelcast using the Rancher CLI 3.2.2 instead of the GUI (as done in variant A)
    1. Of course, do a `rancher login` to target the proper cluster
    2. execute in the command line
    ```shell
    rancher apps install --namespace "hazelcast-mau-ns" --answers ./hazelcast-values.yaml hazelcast "hazelcast-mau2" --version 3.0.5
    ```
    Note that the "hazelcast-values.yaml" file has the same content of point 2.2 above (variant A).

**Result:**
1. Variant A (Hazelcast installed using the GUI): Hazelcast starts correctly, its Helm chart is properly managed and we can use that Hazelcast instance from our backend
2. Variant B (Hazelcast installed via Rancher CLI): the app is created, but its deployment fails with this error shown in red on top of the app page:
```
Wait helm template failed. Error: render error in "hazelcast/templates/tests/test-management-center.yaml": template: hazelcast/templates/tests/test-management-center.yaml:29:22: executing "hazelcast/templates/tests/test-management-center.yaml" at <.Values.image.repository>: can't evaluate field repository in type interface {} : exit status 1
```
![Hazelcast 4 installed via Rancher CLI](https://user-images.githubusercontent.com/20639827/76733201-a91d1c00-6760-11ea-81e2-737057ae60b6.png)

I would have expected the same result, since in variant B I'm using yes another method to install Hazelcast, but it is done with the same answer file using the same Helm chart.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Rancher CLI v2.3.2
- Installation option (single install/HA): I think single install
