### ISSUE TITLE
[UI] Error in generated config

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#2600]
Version: Rancher Server 0.44.0 

**Summary / Steps to replicate:**
* Define a new service with a HTTP1.1 healthcheck.
* Save the config and run it in through compose.
* Service fails to create and the logs on the rancher server show `uknown keywork 'Host: www.domain.com' in 'backend' section`. 

The generated `request_line` value field is in double quotes, if you change these to single then the code is run in fine through compose. I've had a quick look through the code, can't easily tell where that generated config actually comes from, if someone could give me a pointer, i'm happy to look at a fix myself.

**Comment by alena1108** [comment]
@Rucknar thank you for willing to look into that. Here is the method performing the conversion: https://github.com/rancher/cattle/blob/167980dc70b96c32e322785cc5476344f86e8b3f/code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/ServiceDiscoveryApiServiceImpl.java#L320

And this class does some extra formatting for a Healthcheck

https://github.com/rancher/cattle/blob/0c4066f9fd2652f99d29989c2a29065f0378c20e/code/iaas/service-discovery/api/src/main/java/io/cattle/platform/servicediscovery/api/service/impl/RancherGenericMapToComposeFormatter.java

**Comment by alena1108** [comment]
I can't seem to reproduce it on the latest Rancher (v0.46.0) and rancher-compose (v0.5.2-rc2). Tried for HTTP 1.0 and HTTP1.1 health checks; specified both httpRequest/hostHeader and just httpRequest for the latter, all works. Here are the exported rancher-compose.yml files:

with just request line
```
ffff:
  scale: 1
  health_check:
    port: 34
    interval: 2000
    unhealthy_threshold: 3
    request_line: GET /index1.html HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
```
with both request line and host header (and double quotes)
```
foo:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    request_line: "GET /index.html HTTP/1.1\r\nHost:\\ bar.com"
    healthy_threshold: 2
    response_timeout: 2000
```

both worked. 

@Rucknar could you share rancher-compose.yml that caused problem on your setup?

@sangeethah could you test for all the parameters combination for http health check, and see if you can reproduce the issue?
