### ISSUE TITLE
Allow similar syntax for scheduling labels that "Selector Labels" allow

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2601]
Hey there,
i run into a problem. I was expecting that this http://docs.rancher.com/rancher/labels/ (Selector Labels) will work for service scheduling too. But it won't. Like this

``` yml
mongo-replSet-rs0:
  container_name: mongo-replSet-rs0
  image: mongo:3.0
  command: mongod --config /mongod.yml
  stdin_open: true
  tty: true
  restart: always
  ports:
    - "27017:27017"
  volumes:
    - /mongo:/data:rw
    - /data/mongo/mongod.yml:/mongod.yml:ro
  labels:
    io.rancher.scheduler.affinity:host_label: mongo in (primary, secondary, arbiter, hidden)
```

Another solution for me would be to be able to only specify key without value.
Is this possible somehow?

_Edit: After carefully reading the docs again I saw `Key Value Pair of Host Label` specified for affinity. My fault. But is there a way?_
