### ISSUE TITLE
sumologic helm chart causes namespace removal from project

### ISSUE THREAD

**Issue by flrichar** [rancher/rancher#26111]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
- install v0.17.0 helm chart for sumologic from https://github.com/sumologic-kubernetes-collection/ into specific namespace under a current project
- use custom answers as below
```
---
  sumologic: 
    accessId: "secret"
    accessKey: "supersecret"
    clusterName: "misc-dev"
    setupEnabled: true
  prometheus-operator:
    enabled: false
```
**Result:**
namespace is removed from project, any other pods using namespace break.

**Other details that may be helpful:**
using setupEnabled: false fixes the namespace issue.

according to the documents, something in the pre-install hook is causing this behavior
``` 
 # If enabled, a pre-install hook will create Collector and Sources in Sumo Logic
  setupEnabled: true 
```

**Environment information**
- Rancher version: v2.3.4
- Installation option: HA

**Cluster information**
- Cluster type: VMWare
- Machine type: VM
- Kubernetes version:  1.17.2
- Docker version (use `docker version`): 19.03.5
