### ISSUE TITLE
Rancher Helm Chart Multiple Hostnames

### ISSUE THREAD

**Issue by forestoden** [rancher/rancher#26181]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Feature Request

Is it possible to pass in multiple hostnames into the Rancher Helm Chart?

Our system is architected with internal DNS that all cluster nodes can resolve an internal Rancher DNS name `rancher.internal.example.com` and a reverse proxy that will expose the Rancher UI at `rancher.example.com` We've set up Rancher's `server-url` as `rancher.internal.example.com` and the system functions as expected from a cluster to cluster communication point of view, however when accessing `rancher.example.com`, the request is obviously just routed to the default backend with a 404.

I was able to manually edit the Ingress and expose both URLs here and everything is working, however I would prefer to not have to manually edit this (or even automate it via a patch command after running helm) if possible.

Here's what my working, ingress spec looks like

```
 spec:
   rules:
   - host: rancher.internal.example.com
     http:
       paths:
       - backend:
           serviceName: rancher
           servicePort: 80
   - host: rancher.example.com
     http:
       paths:
       - backend:
           serviceName: rancher
           servicePort: 80
   tls:
   - hosts:
     - rancher.internal.example.com
     - rancher.example.com
     secretName: tls-rancher-ingress
```

I believe this could be accomplished fairly easily by using a `range` in the Helm chart, and I'd be happy to give that a stab but I'm not sure if there are other concerns here.
