### ISSUE TITLE
rke-user-addon-deploy-job fails to come up successfully in a hardened setup 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26194]
Version: v2.4.0-rc8

K8s version: v1.17.4-rancher1-2

Steps:

1. Create a hardened setup using the guidelines in the below docs:
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

2. After the cluster becomes active, it was observed that rke-user-addon-deploy-job (in the system project) fails to come up successfully

Logs below:

```
namespace/ingress-nginx unchanged
role.rbac.authorization.k8s.io/default-psp-role unchanged
rolebinding.rbac.authorization.k8s.io/default-psp-rolebinding unchanged
namespace/cattle-system unchanged
role.rbac.authorization.k8s.io/default-psp-role unchanged
rolebinding.rbac.authorization.k8s.io/default-psp-rolebinding unchanged
clusterrole.rbac.authorization.k8s.io/psp:restricted unchanged
clusterrolebinding.rbac.authorization.k8s.io/psp:restricted unchanged
serviceaccount/tiller unchanged
clusterrolebinding.rbac.authorization.k8s.io/tiller unchanged
error: unable to recognize "/etc/config/rke-user-addon.yaml": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1"

```

![Screen Shot 2020-03-22 at 9 08 18 PM](https://user-images.githubusercontent.com/18536626/77280360-4e645280-6c81-11ea-9d55-16ad0e9f83c1.png)

**Comment by superseb** [comment]
The `Reference Hardened RKE Template configuration` contains:

- `apiVersion: extensions/v1beta1` (wrong)

for `PodSecurityPolicy`  while the `Reference Hardened RKE cluster.yml configuration` contains:
- `apiVersion: policy/v1beta1` (correct). 

Can you try with this change?

**Comment by soumyalj** [comment]
Rancher version: v2.4.0-rc10 
K8s versions: v1.17.4-rancher1-2 , v1.15.11-rancher1-2

1. Followed the steps of hardening guide. ( CIS Benchmark v1.5)
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

2. Created a custom cluster with K8s v1.17.4-rancher1-2  specifying both public ip and internal ip in the "docker run" command for registering the agents. In the cluster.yml, for PodSecurityPolicy spec, used `apiVersion: policy/v1beta1` as below:

```
   ---
    apiVersion: extensions/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: restricted
    spec:
      requiredDropCapabilities:
      - NET_RAW
      privileged: false
      allowPrivilegeEscalation: false
      defaultAllowPrivilegeEscalation: false
      fsGroup:
        rule: RunAsAny
      runAsUser:
        rule: MustRunAsNonRoot
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        rule: RunAsAny
      volumes:
      - emptyDir
      - secret
      - persistentVolumeClaim
      - downwardAPI
      - configMap
      - projected
 

```

The cluster was active and rke-user-addon-deploy-job came up successfully without any errors.
![Screen Shot 2020-03-23 at 2 25 11 PM](https://user-images.githubusercontent.com/18536626/77364762-28d35980-6d12-11ea-9702-2aca9df1379a.png)

Logs: rke-user-addon-pod

```
namespace/ingress-nginx unchanged
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
role.rbac.authorization.k8s.io/default-psp-role configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
rolebinding.rbac.authorization.k8s.io/default-psp-rolebinding configured
namespace/cattle-system created
role.rbac.authorization.k8s.io/default-psp-role created
rolebinding.rbac.authorization.k8s.io/default-psp-rolebinding created
podsecuritypolicy.policy/restricted created
clusterrole.rbac.authorization.k8s.io/psp:restricted created
clusterrolebinding.rbac.authorization.k8s.io/psp:restricted created
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created

```
