### ISSUE TITLE
Allow load balancer target to be able to use external services that are using hostname

### ISSUE THREAD

**Issue by fernandofederico1984** [rancher/rancher#2624]
I created an external service called external-1, that external service points to a host name: dev.test.com. On the other hand, I have a service called myService that calls and endpoint in the host docker.test.com (I need it to be called that way in order to mach the host name certificate *.test.com) I want myService to call dev.test.com

here is the docker file:

```
external-1:
  image: rancher/external-service
myService:
  expose:
  - 8081/tcp
  ports:
  - 8080:8081/tcp
  image: myService:1.0.0
  links:
  - docker.test.com:external-1

```

and this is my rancher compose file

```
myService:
  scale: 1
external-1:
  hostname: dev.test.com
```

Seems that I can connect, but I always get 405 (method not allowed) from inside myService. Of course the same endpoint works fine if I hit dev.test.com directly
