### ISSUE TITLE
coredns add on job fails after an addition of worker node and a cluster upgrade

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26260]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy a cluster - 1 etcd, 1 worker, 1 control node.
2. Add a worker node.
3. Upgrade the cluster, by changing the max-pods of kubelet. (in cluster.yml)

**Expected Result:**
rke coredns add on job should have deployed and pod should be in "Active" state

**Actual Result:**
The are in error state and Unavailable
<img width="1291" alt="Screen Shot 2020-03-25 at 1 18 01 PM" src="https://user-images.githubusercontent.com/26032343/77582446-a4f9a880-6e9c-11ea-8193-3b0cbc75dc91.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancmaster-head - commit id: `ae28b67cc`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by mrajashree** [comment]
@sowmyav27 I'm not able to repro with the above steps, commit id `e783315279c389c73ed4b465b261d0004ffbf6a0`

**Comment by sowmyav27** [comment]
On master-head 
- First edit on a cluster, cluster.yaml file, change max-pods, dns params are :
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
    upstreamnameservers: null
```
- Request sent:
```
dns: {nodelocal: {updateStrategy: {}, nodeSelector: null, ipAddress: ""}, reversecidrs: null,…}
nodelocal: {updateStrategy: {}, nodeSelector: null, ipAddress: ""}
updateStrategy: {}
nodeSelector: null
ipAddress: ""
reversecidrs: null
stubdomains: null
upstreamnameservers: null
updateStrategy: {}
```
- Response received:
```
"dns":{"nodelocal":{"ipAddress":"","type":"/v3/schemas/nodelocal"},"type":"/v3/schemas/dnsConfig"}
```
- After cluster comes up active, do another edit of cluster, change max-pods, dns params are
```
dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy:
        rolling_update: {}
        type: /v3/schemas/daemonSetUpdateStrategy
    reversecidrs: null
    stubdomains: null
    update_strategy:
      rolling_update: {}
      type: /v3/schemas/deploymentStrategy
    upstreamnameservers: null
```
- request sent:
```
dns: {,…}
nodelocal: {updateStrategy: {type: "/v3/schemas/daemonSetUpdateStrategy", rollingUpdate: {}}, nodeSelector: null,…}
updateStrategy: {type: "/v3/schemas/daemonSetUpdateStrategy", rollingUpdate: {}}
type: "/v3/schemas/daemonSetUpdateStrategy"
rollingUpdate: {}
nodeSelector: null
ipAddress: ""
reversecidrs: null
stubdomains: null
upstreamnameservers: null
updateStrategy: {type: "/v3/schemas/deploymentStrategy", rollingUpdate: {}}
type: "/v3/schemas/deploymentStrategy"
rollingUpdate: {}
nodeSelector: null
linearAutoscalerParams: {max: 0, min: 1, preventSinglePointFailure: true, nodesPerReplica: 4, coresPerReplica: 128}
max: 0
min: 1
preventSinglePointFailure: true
nodesPerReplica: 4
coresPerReplica: 128
```
- response:
```
"dns":{"linearAutoscalerParams":{"coresPerReplica":128,"max":0,"min":1,"nodesPerReplica":4,"preventSinglePointFailure":true,"type":"/v3/schemas/linearAutoscalerParams"},"nodelocal":{"ipAddress":"","type":"/v3/schemas/nodelocal","updateStrategy":{"type":"/v3/schemas/daemonSetUpdateStrategy"}},"type":"/v3/schemas/dnsConfig","updateStrategy":{"type":"/v3/schemas/deploymentStrategy"}},
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `a195fe7c6`**

- deploy a cluster - 1 etcd, 2 control, 3 worker nodes.
- Edit cluster, change max-pods, yaml file has 
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
    upstreamnameservers: null
```
- Save changes. the request sent:
```
dns: {nodelocal: {updateStrategy: {}, nodeSelector: null, ipAddress: ""}, reversecidrs: null,…}
nodelocal: {updateStrategy: {}, nodeSelector: null, ipAddress: ""}
reversecidrs: null
stubdomains: null
upstreamnameservers: null
updateStrategy: {}
nodeSelector: null
linearAutoscalerParams: {}
```
- response:
```
"dns":{"nodelocal":{"ipAddress":"","type":"/v3/schemas/nodelocal"},"type":"/v3/schemas/dnsConfig"}
```
- do an edit of cluster again, change max-pods, yaml file has:
```
dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy:
        rolling_update: {}
    reversecidrs: null
    stubdomains: null
    update_strategy:
      rolling_update: {}
    upstreamnameservers: null
```
- request sent:
```
dns: {nodelocal: {updateStrategy: {rollingUpdate: {}}, nodeSelector: null, ipAddress: ""},…}
nodelocal: {updateStrategy: {rollingUpdate: {}}, nodeSelector: null, ipAddress: ""}
reversecidrs: null
stubdomains: null
upstreamnameservers: null
updateStrategy: {rollingUpdate: {}}
rollingUpdate: {}
nodeSelector: null
```
- response:
```
"dns":{"linearAutoscalerParams":{"coresPerReplica":128,"max":0,"min":1,"nodesPerReplica":4,"preventSinglePointFailure":true,"type":"/v3/schemas/linearAutoscalerParams"},"nodelocal":{"ipAddress":"","type":"/v3/schemas/nodelocal","updateStrategy":{"type":"/v3/schemas/daemonSetUpdateStrategy"}},"type":"/v3/schemas/dnsConfig","updateStrategy":{"type":"/v3/schemas/deploymentStrategy"}}
```
- rke add on core dns job -- does not have an issue.
