### ISSUE TITLE
Changes to Rancher internal DNS

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2628]
To be more aligned with docker 1.9 networking model, we should do the following for our Rancher internal DNS:

- service is discoverable to every other service within the same stack by default. Service links would only be useful if user wants to override DNS name
- every container is discoverable by its name to every other container in the same stack
- to make service discoverable to outside of the stack, links should still be used. 
- for service to register to the LB, links still be used.

@ibuildthecloud @will-chan

**Comment by sangeethah** [comment]
Tested with server version - v0.46.0-rc2

1.Services within the same stack are discoverable to each other using their service names.
2.Containres within the same stack are discoverable to each other using their container_names.

**Comment by alex88** [comment]
After upgrading to this version in both rancher and compute hosts with the agent, nginx frontends fails to start due

```
[emerg] 1#1: host not found in upstream "api:8000" in /etc/nginx/nginx.conf:38
[emerg] host not found in upstream "api:8000" in /etc/nginx/nginx.conf:38
```

with the host linked, I've to check how I can use service names instead since we've multiple environments

**Comment by alex88** [comment]
Tried also with service name (they're in the same stack), still nginx error, using ip address everything works

**Comment by pedrommone** [comment]
Same happens to me. If I force the `fpm` IP it works well, if I use a DNS, it falls.

**Comment by alex88** [comment]
@pedrommone are you using nginx? how's your config?

**Comment by pedrommone** [comment]
@alex88 yep!

```
user www-data;
worker_processes 4;
pid /run/nginx.pid;
daemon off;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    upstream phpfpm_backend {
        server %fpm-ip%:9000;
    }

    ##
    # Basic Settings
    ##

    sendfile off;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ##
    # Logging Settings
    ##

    access_log /data/logs/access.log;
    error_log /data/logs/error.log warn;

    ##
    # Gzip Settings
    ##

    gzip on;
    gzip_disable "msie6";

    include /etc/nginx/conf.d/*.conf;
}
```

**Comment by alex88** [comment]
@pedrommone how do you replace that %fpm-ip%? Is it a linked docker service?

**Comment by pedrommone** [comment]
it's a linked docker. I replace with `fpm`

heres the docker-composer.yml
```
atena:
    image: registry.pedro.com:443/atena
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat
fpm:
    image: php:7-fpm
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: atena
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - atena
nginx:
    image: registry.pedro.com:443/laravel-nginx
    links:
        - fpm:fpm
    labels:
        io.rancher.sidekicks: atena
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - atena
postgres:
    image: postgres
    volumes:
        - /var/lib/postgresql/atena:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: atena
        POSTGRES_PASSWORD: deuspedrolindo
    labels:
        io.rancher.scheduler.affinity:host_label: server=08
```
