### ISSUE TITLE
In Rancher-Compose, Environment values of True are converted to Booleans when used without quotations. 

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2634]
Hey there,
It seems I found a docker-file which is not working under rancher-compose but with docker-compose.. (?)
Here my `docker-compose.yml` for rancher-compose
```yml
images:
  image: apsl/thumbor
  stdin_open: true
  tty: true
  restart: always
  environment:
    MAX_AGE: 86400
    MIN_WIDTH: 100
    MIN_HEIGHT: 100
    ALLOW_ANIMATED_GIFS: True
    AUTO_WEBP: True
    SECURITY_KEY: "LKJSAKDnmkwle2wewkl242NKnjs230kljknm"
    ALLOW_UNSAFE_URL: False
    ALLOW_OLD_URLS: False
    STORAGE_EXPIRATION_SECONDS: 7776000 #90 days
    FILE_STORAGE_ROOT_PATH: '/data/storage'
    RESULT_STORAGE_EXPIRATION_SECONDS: 2592000 #30 days
    UPLOAD_MAX_SIZE: 10240 # 10MB
    UPLOAD_ENABLED: True
    UPLOAD_PUT_ALLOWED: True
  volumes:
    - /images/:/data/storage/:rw
  labels:
    io.rancher.scheduler.affinity:host_label:  "host=blablub"
  health_check:
    port: 80
    request_line: GET / HTTP/1.0
    interval: 2000
    healthy_threshold: 2
    unhealthy_threshold: 3
    response_timeout: 2000
```

It fails with
```log
11/11/2015 2:46:42 AMTraceback (most recent call last):
11/11/2015 2:46:42 AM  File "/usr/local/bin/thumbor", line 9, in <module>
11/11/2015 2:46:42 AM    load_entry_point('thumbor==5.2.1', 'console_scripts', 'thumbor')()
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 46, in main
11/11/2015 2:46:42 AM    config = Config.load(server_parameters.config_path, conf_name='thumbor.conf', lookup_paths=lookup_paths)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 75, in load
11/11/2015 2:46:42 AM    return cls.__load_from_path(conf, path)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 84, in __load_from_path
11/11/2015 2:46:42 AM    six.exec_(code, module.__dict__)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
11/11/2015 2:46:42 AM    exec("""exec _code_ in _globs_, _locs_""")
11/11/2015 2:46:42 AM  File "<string>", line 1, in <module>
11/11/2015 2:46:42 AM  File "<string>", line 50, in <module>
11/11/2015 2:46:42 AMNameError: name 'true' is not defined
```

If I execute this with `docker-compose` (without *health_check*) on the same host, there are no error logs at all.
Also confirmed with docker-file creator https://github.com/APSL/docker-thumbor/issues/3
