### ISSUE TITLE
[rancher-compose] sidekicks, volumes-from, and links oh my

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#2636]
Running this compose file makes rancher-compose do nothing: https://gist.github.com/stresler/aedf50d266dbc5e24233

My guess is that between the dependencies of sidekicks, volumes-from, and links it is stuck in a loop waiting for itself to finish.

**Comment by ibuildthecloud** [comment]
Reported by @stresler on IRC who now wins a kewpie.

**Comment by petyunchik** [comment]
Any suggestions how to avoid this bug while fix is not ready?

**Comment by SrgyPetrov** [comment]
+1

**Comment by stresler** [comment]
In this case it is Rancher (or docker?) not handling a circular dependency correctly.  The compose file I had there doesn't actually need the links section because all sidekicks are automatically linked.  

However, the presence of them shouldn't stop rancher-compose cold. 

The work around is to remove the links section where sidekicks are implemented.

**Comment by deniseschannon** [comment]
Here's a simplified version that causes to get stuck in a loop:

```
service1:
  image: nginx
  volumes_from:
    - data
data:
  image: nginx
service2:
  image: nginx
  links: 
    - service1
    - data
  labels:  
    io.rancher.sidekicks: service1, data
```

If I remove the `links` section, it doesn't get stuck in a loop.

```
$ rancher-compose -p linktest3 up -d
INFO[0000] Creating stack linktest3
```

**Comment by deniseschannon** [comment]
Verified with v0.8.0-rc1 and v0.63.1 that this docker-compose.yml works (has similar sidekicks/links/volumes-from)

```
portal:
  image: nginx 
  volumes_from:
    - portal-data
  expose:
    - "7080:7080"
portal-data:
  image: nginx
  volumes:
    - /home/packet/portal
nginx-portal:
  image: nginx
  expose:
    - "9080:80"
  links: 
    - portal
    - portal-data
  labels:
    io.rancher.sidekicks: portal,portal-data
  volumes_from:
    - portal-data
Portal-LB:
  restart: always
  ports:
    - "443:9080"
  image: rancher/load-balancer-service
  links:
    - nginx-portal:nginx-portal
```
