### ISSUE TITLE
Project owner cannot see PVC in 2.4.0

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#26416]
rancher/rancher:v2.4.0

Docker install

Steps:

1. Create a standard user `user1`
2. Add `user1` into Default project as project owner
3. Login as `user1`
4. Import a PVC

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 6Gi
```

Results:

Project owner can import and create PVC but can not see it in Rancher UI. 

Other:

It works in 2.3.5 and 2.3.6
