### ISSUE TITLE
OPA gatekeeper page unable to load in HA set up with ingress pointing to 8080/8443

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#26430]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create an HA set up with ingress pointing to 8080/8443 by having ingress below in yaml file.
```
ingress:
    provider: nginx
    extra_args:
      http-port: 8080
      https-port: 8443
```
2. Create a cluster, Navigate to dashboard
3. Go to OPA gatekeeper page

**Result:**
Page fails to load.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.4.2-rc2
- Installation option (single install/HA):HA
