### ISSUE TITLE
[Fresh Install] NodeController failure in connecting http://[OPENSTACK-IP]:9696/v2.0

### ISSUE THREAD

**Issue by kenhglee** [rancher/rancher#26461]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG:  Cluster provisioning is hanging due to NodeController failure complaining that it is not able to connect to openstack via port 9696/v2.0. Upon researching the web, I find that openstack stopped supporting v2.0 since Queens version which means the rancher server will have to attempt the connection via v3.0 to begin with. 

**Steps to reproduce (least amount of steps as possible):**

1. Create Node Template using OPENSTACK driver making sure to fill out **domain name** instead of **domain id**.(Not sure if there was basis to this as I could find the like from [blog1](https://www.vkhitrin.com/blog/deploying-rancher-on-openstack/) or [blog2](https://medium.com/@chfrank_cgn/creating-a-kubernetes-cluster-on-openstack-with-rancher-6f15010cf31e).
2. Correspondingly, I set OS_IDENTITY_API_VERSION="3" in the .bashrc of "rancher-server" and then restarted the docker.
3. Create Cluster Template based on the [official instruction](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/). 

**Result:**
2020/04/02 23:21:32 [ERROR] NodeController c-pcgtd/m-tb4tm [node-controller] failed with : Error creating machine: Error in driver during machine creation: Get http://[OPENSTACK-IP]:9696/v2.0/networks?name=provider: dial tcp [OPENSTACK-IP]:9696: connect: connection timed out

**Other details that may be helpful:**
Whether I fill out domain name or domain id, the failure is not going away.

**Environment information**
- Rancher version : 2.4.2
- Installation option (single install/HA): single

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
**Appendix 1. NodeTemplate**
```
{

    "annotations": {
        "ownerBindingsCreated": "true"
    },
    "baseType": "nodeTemplate",
    "cloudCredentialId": null,
    "created": "2020-04-02T22:44:08Z",
    "createdTS": 1585867448000,
    "creatorId": "user-8h2wk",
    "driver": "openstack",
    "engineEnv": { },
    "engineInstallURL": "https://releases.rancher.com/install-docker/19.03.sh",
    "engineLabel": { },
    "engineOpt": { },
    "engineRegistryMirror": null,
    "id": "cattle-global-nt:nt-hrb9b",
    "labels": {
        "cattle.io/creator": "norman"
    },
    "links": {
        "nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-hrb9b",
        "nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-hrb9b",
        "self": "…/v3/nodeTemplates/cattle-global-nt:nt-hrb9b",
        "update": "…/v3/nodeTemplates/cattle-global-nt:nt-hrb9b"
    },
    "name": "node-template-v7-2",
    "openstackConfig": {
        "activeTimeout": "200",
        "applicationCredentialId": "",
        "applicationCredentialName": "",
        "applicationCredentialSecret": "",
        "authUrl": "https://x.x.x.x:5000/v3",
        "availabilityZone": "",
        "cacert": "-----BEGIN CERTIFICATE-----xxxx-----END CERTIFICATE-----",
        "configDrive": false,
        "domainId": "",
        "domainName": "Default",
        "endpointType": "internalURL",
        "flavorId": "d795d6a5-60ce-4301-9ea3-f3e26c76d4c9",
        "flavorName": "",
        "floatingipPool": "",
        "imageId": "03bb16ae-704a-410b-9264-1e748801d866",
        "imageName": "",
        "insecure": true,
        "ipVersion": "4",
        "keypairName": "support",
        "netId": "",
        "netName": "provider",
        "novaNetwork": false,
        "region": "RegionOne",
        "secGroups": "rancher",
        "sshPort": "22",
        "sshUser": "rancher",
        "tenantDomainId": "",
        "tenantDomainName": "",
        "tenantId": "296292bad3c74830b2d325ae614d19d8",
        "tenantName": "",
        "userDataFile": "",
        "userDomainId": "",
        "userDomainName": "",
        "userId": "",
        "username": "rancher"
    },
    "principalId": "local://user-8h2wk",
    "state": "active",
    "transitioning": "no",
    "transitioningMessage": "",
    "type": "nodeTemplate",
    "useInternalIpAddress": true,
    "uuid": "86e08e25-a0b8-4768-bd81-26be16782e8f"
```
**Appendix 2. ClusterTemplate (Just the Rancher config section)**
```
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  cloud_provider:
    name: openstack
    openstack_cloud_provider:
      block_storage:
        ignore-volume-az: true
        trust-device-path: false
      global:
        auth-url: 'https://x.x.x.x:5000/v3'
        domain-name: Default
        tenant-id: 296292bad3c74830b2d325ae614d19d8
        username: rancher
      metadata:
        request-timeout: 0
  dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy:
        rolling_update: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
    upstreamnameservers: null
  ignore_docker_version: true
```
**Appendix 3: Environment Variable**
```
root@6e9bc3b2b7f7:/var/lib/rancher# cat .bashrc
export OS_IDENTITY_API_VERSION="3"
export OS_USER_DOMAIN_NAME="Default"
export OS_PROJECT_NAME="rancher"
```
#
