### ISSUE TITLE
[RBAC] - Project owner has no access to CRDs

### ISSUE THREAD

**Issue by volatilemolotov** [rancher/rancher#26504]
**What kind of request is this (question/bug/enhancement/feature request):**
question/bug

**Steps to reproduce (least amount of steps as possible):**
Create a user in rancher, assign a project role for the user (user-x), deploy a CR in a namespace (namespace-x) that is in that project

**Result:**
user-x cannot list resoruce "customresource" in Api group custom.k8s.io in the namespace-x

**Other details that may be helpful:**
User is created within RancherUI and added to project 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8, v2.3.8, v2.2.4
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): varies
- Kubernetes version (use `kubectl version`): varies

**Comment by volatilemolotov** [comment]
looks like adding 
```
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

```
to project-owner clusterrole does the trick. This still can be considered safe due to rancher using roleBinding for namespaces within projects. So this permissions is just project-wide.

Now the disscusion is about what project owner actually is. Mine understading is that a project owner should have access to all resources, not just that the rancher team added, due to some people (i reckon many) use some other stuff that rancher does not deploy (eg. ambassador, externaldns) but still are needed for users in order to achieve a "self-service" infrastructure

**Comment by volatilemolotov** [comment]
Well the "fix" with editing the project-owner role was bad, looks like rancher reconciles the roles so its not permanent.
However you can define project roles and grant them custom permissions so that looks like a viable way to handle this, no need to redefine the project-owner role perhaps?

Leaving open for discussion

**Comment by cjellick** [comment]
Can you give some more concrete steps to reproduce? Like exact kubectl commands that you're using? Does it require some interaction with the Rancher UI to reproduce?

Our project-owner role uses the kubernetes built-in "admin" role (see https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings).

This should give a user all the permissions they need to operate within a namespace, so there's some piece of the puzzle that we're missing.

**Comment by volatilemolotov** [comment]
We are using rancher UI to create projects, namespaces and users. All other interaction are via kubernetes API. When setting a user as a project owner it binds(rolebinding) that user to the project owner cluster role which has the objects defined like this:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    authz.cluster.cattle.io/clusterrole-owner: project-owner
  labels:
    cattle.io/creator: norman
  name: project-owner
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - apprevisions
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - pipelines
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - pipelineexecutions
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - pipelinesettings
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - sourcecodeproviderconfigs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - '*'
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - clusterevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertrules
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectalertgroups
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectloggings
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - clustercatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectcatalogs
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projectmonitorgraphs
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplates
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - catalogtemplateversions
  verbs:
  - '*'
- apiGroups:
  - monitoring.cattle.io
  resources:
  - prometheus
  verbs:
  - view
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - prometheusrules
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - serviceentries
  - sidecars
  - virtualservices
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - apikeys
  - authorizations
  - checknothings
  - circonuses
  - deniers
  - fluentds
  - handlers
  - kubernetesenvs
  - kuberneteses
  - listcheckers
  - listentries
  - logentries
  - memquotas
  - metrics
  - opas
  - prometheuses
  - quotas
  - quotaspecbindings
  - quotaspecs
  - rbacs
  - reportnothings
  - rules
  - solarwindses
  - stackdrivers
  - statsds
  - stdios
  verbs:
  - '*'
- apiGroups:
  - authentication.istio.io
  resources:
  - policies
  verbs:
  - '*'
- apiGroups:
  - rbac.istio.io
  resources:
  - rbacconfigs
  - serviceroles
  - servicerolebindings
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationpolicies
  verbs:
  - '*'
```

All new users created are not bound to the `admin` role
