### ISSUE TITLE
Add 'cert-manager.io/issuer-kind: Issuer' to ingress.yaml in Rancher chart to mitigate https://github.com/jetstack/cert-manager/issues/2533 

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#26505]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement

**Steps to reproduce (least amount of steps as possible):**

If a user configures a default issuer when installing cert-manager into the Kubernetes cluster during the installation of Rancher v2.x HA they will encounter the cert-manager issue documented at https://github.com/jetstack/cert-manager/issues/2533 when installing the Rancher chart. This can be mitigated by updating the ingress.yaml template in the Rancher chart to include `cert-manager.io/issuer-kind: Issuer` per the below:

```
{{- if or (.Capabilities.APIVersions.Has "cert-manager.io/v1alpha2") (and (eq (int $certmanagerVer._0) 0) (ge (int $certmanagerVer._1) 11)) }}
    cert-manager.io/issuer: {{ template "rancher.fullname" . }}
    cert-manager.io/issuer-kind: Issuer
```

**Environment information**
- Rancher v2.3.5

**Comment by cbron** [comment]
Do we want to backport to 2.2 ?

**Comment by rancher-max** [comment]
#### Reproduced in v2.3.5 and in v2.x-head (where x is all of 2, 3 and 4) and in master-head

Steps:
1. Setup kubernetes cluster for HA: 
`rke up --config ./rancher-cluster.yml`
2. After everything is running, grab the latest rancher helm chart: 
`helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`
3. Install cert-manager with a default ClusterIssuer:
```
$ kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml && \
kubectl create namespace cert-manager && \
helm repo add jetstack https://charts.jetstack.io && helm repo update

$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0 \
  --set ingressShim.defaultIssuerName=letsencrypt-staging \
  --set ingressShim.defaultIssuerKind=ClusterIssuer \
  --set ingressShim.defaultIssuerGroup=cert-manager.io
```
4. After all cert-manager pods are running, apply a default clusterissuer:
`kubectl apply -f clusterissuer.yaml`
```yaml
# clusterissuer.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: me@somefakeemail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: example-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
```
5. Install rancher into the cluster using LetsEncrypt for ingress:
```
$ kubectl create namespace cattle-system

$ helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set rancherImageTag=v2.2.12-rc1 \
  --set hostname=my.host.name \
  --set rancherImagePullPolicy=Always \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=me@somefakeemail.com
```

**Result:**
The cert ends up being unexpected. It should be signed by Let's Encrypt:
![image](https://user-images.githubusercontent.com/55997940/82093511-1d683300-96b0-11ea-80c7-29216a2373d8.png)
