### ISSUE TITLE
[question] multiple mail server one one host

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2657]
Heyho,
I already successfully set up an mail server via rancher.
Now I have a second domain and would like to use the same host for that.
I tried to create a load balancer for that with no success like:
```yml
mailserver-lb:
  image: rancher/load-balancer-service
  stdin_open: true
  tty: true
  restart: always
  links:
  - mailserver-foo
  - mailserver-bar
  ports:
  - 25/tcp
  - 143/tcp
  - 465/tcp
  - 587/tcp
  - 993/tcp
  labels:
#    io.rancher.loadbalancer.ssl.ports: 993,465,587,143
    io.rancher.loadbalancer.target.mailserver-foo: mail.foo:25=25,mail.foo:143=143,mail.foo:465=465,mail.foo:587=587,mail.foo:993=993
    io.rancher.loadbalancer.target.mailserver-bar: mail.bar:25=25,mail.bar:143=143,mail.bar:465=465,mail.bar:587=587,mail.bar:993=993
    io.rancher.scheduler.affinity:host_label: host=blabla
```

I also setting up certs via rancher (ssl) but no luck there either. 
Always getting somthing like "The server may be unavailable or is refusing [...] connections."
Anyone some experience with that?
