### ISSUE TITLE
User is not able to create a PVC using a PV created in Longhorn

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26605]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a cluster - RKE do - 1 node
- Deploy Longhorn app in the Default project
- Navigate to the Longhorn UI once it is deployed
- Deploy a Volume and create a PV say pv1
- Navigate to Rancher UI --> Cluster --> Default Project --> Resources --> Volumes
- Create a volume
- Select "Use an existing persistent volume".
- From the dropdown select pv1
- Enter other details and Click on Save.

**Actual Result:**
Error is seen `Error: storageclasses.storage.k8s.io "longhorn-static" not found` and PVC is not created.

**Expected Result:**
PVC should be created successfully

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by yasker** [comment]
I don't think we should check for the existence of StorageClass object here. StorageClass doesn't need to exist for PV and PVC to match. It will function as a label for matching if it doesn't exist as an object.

**Comment by yasker** [comment]
Example to explain and reproduce the issue without Longhorn, using following two yamls.

```
# random_pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: random-pv
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/test-tmp
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: random-storage-class
```
```
# random_pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: random-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: random-storage-class
  volumeMode: Filesystem
```

In Kubernetes, create `random_pv.yaml`, then create `random_pvc.yaml`. Now you can see PVC has been bound to PV.

In Rancher, create `random_pv.yaml`, then try to use Rancher to create PVC using the existing `random_pv`. You will get the error message `storageclasses.storage.k8s.io "random-storage-class" not found`.
