### ISSUE TITLE
Add resource limits for cattle-cluster-agent and cattle-node-agent to support Gatekeeper

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#26659]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
- Running Rancher v2.4.2
- Deploy default custom cluster
- Install Gatekeeper using [Link](https://github.com/open-policy-agent/gatekeeper#installation-instructions)

**Result:**
- cattle-cluster-agent, cattle-node-agent, and kube-api-auth all will configured with no CPU/MEM limits and requests
- Gatekeeper will block these pods from being deployed or upgraded due to the missing limits and requests

**Other details that may be helpful:**
The default enforce policy includes the rule "All pods must have resource limits" 

**Workaround**
A) Exempt cattle-system namespace from Gatekeeper [Link](https://github.com/open-policy-agent/gatekeeper/blob/master/README.md#exempting-namespaces-from-the-gatekeeper-admission-webhook)
B) Edit the workloads to include the following limits
cattle-cluster-agent
```
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
```

cattle-node-agent
```
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
```
kube-api-auth
```
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
```
**NOTE:** These limits are only starting points and may need to be tuned for your environment and requirements.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.2
- Installation option (single install/HA): HA
