### ISSUE TITLE
Audit Log activation on downstream cluster doesn't work

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#26713]
**What kind of request is this (question/bug/enhancement/feature request):**

Possibly a bug in the RKE version shipped with Rancher 2.3.2

**Steps to reproduce (least amount of steps as possible):**

- Bootstrap Rancher 2.3.2 fresh cluster.
- Create a downstream cluster
- Edit the cluster.yaml from the downstream cluster to add the Audit Log like explained in the doc below:
https://rancher.com/docs/rke/latest/en/config-options/audit-log/
  - Just using the following from the doc in the cluster.yaml file:
```
services:
  kube-api:
    audit_log:
      enabled: true
```

**Result:**

The cluster doesn't get updated.

**Other details that may be helpful:**

The issue get raised because the [terraform provider Rancher2](https://rancher.com/docs/rke/latest/en/config-options/audit-log/) reports the config as "modified" but nothing changes on the downstream cluster.

**Workaround**

Using the following config in downstream cluster.yaml is working as a workaround:
```
kube-api:
      extra_args:
        audit-log-format: json
        audit-log-maxage: '5'
        audit-log-maxbackup: '5'
        audit-log-maxsize: '100'
        audit-log-path: /var/log/kube-audit/audit-log.json
        audit-policy-file: /etc/kubernetes/audit.yaml
      extra_binds:
        - '/var/log/kube-audit:/var/log/kube-audit'
```
Uploading first the  `/etc/kubernetes/audit.yaml` file first to the manager nodes to make it work.
I used the basic file from the k8s website for testing purpose:
```
# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
```

**Environment information**
- Tested on Rancher HA and Rancher Docker: version 2.3.2
- Kubernetes 1.16
- Docker 18.9.9
- Downstream cluster is a 3 manager nodes cluster on DigitalOcean.
