### ISSUE TITLE
empty registry secret breaks the UI

### ISSUE THREAD

**Issue by ahmadalli** [rancher/rancher#26756]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

1. create empty registry secret
   ```yaml
   apiVersion: v1
   kind: Secret
   metadata:
      name: registry
      annotations:
         replicator.v1.mittwald.de/replicate-from: default/registry
   type: kubernetes.io/dockerconfigjson
   data:
      .dockerconfigjson: e30K
   ```
1. go to registry section of secrets of your project

**Result:** UI gets stuck at loading

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher Version: v2.3.5
UI Version v2.3.36

- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`): 1.15.3

```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", Build
Date:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 17:24:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
