### ISSUE TITLE
load balancer not working - missing iptable rules?

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#2676]
Heyho,
I have an load balancer like this
*docker-compose*
```yml
ex40-lb:
  image: rancher/load-balancer-service
  stdin_open: true
  tty: true
  restart: always
  links:
  - meh
  - muh
  ports:
  - 80:80
  - 443:80
  labels:
    io.rancher.loadbalancer.ssl.ports: 443
    # two different domains
    io.rancher.loadbalancer.target.meh: foo:80=8000,foo:443=8000
    io.rancher.loadbalancer.target.muh: bar:80=8000,bar:443=8000
```
*rancher-compose*
```yml
ex40-lb:
  scale: 1
  certs:
    - meh
  load_balancer_config:
    name: ex40-lb config
  default_cert: muh
```

Everything is starting all right. But If I want to connect I always only get "connection refused".
Now I guess the problem lies in the iptables of the host.
Somewhere I read that lb should be reflected as `CATTLE_PREROUTING` or somthing. But if do
```sh
root@EX40 ~ # iptables-save  | grep 80
:PREROUTING ACCEPT [35808:16668861]
root@EX40 ~ # iptables -t nat -L -n -v | grep 80
  580 37065 CATTLE_PREROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0 
```
there is nothing with port 80. Or do I miss understand iptables ( highly possible ;).
What else could it be?

(ufw disabled)

**Comment by alena1108** [comment]
@fentas could you provide the output of /etc/haproxy/haproxy config from one of your LB instances? Ports are opened on demand, and only services linked to LB - meh and muh - are active.

**Comment by fentas** [comment]
sure. To simplify things I reduced it to one domain and one service.
Here `haproxy.cfg`
```sh
root@d188fcb1e6e9:/# cat /etc/haproxy/haproxy.cfg 
global
	log 127.0.0.1 local0
    	log 127.0.0.1 local1 notice
        maxconn 4096
        maxpipes 1024
	tune.ssl.default-dh-param 2048
	ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
	ssl-default-server-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
	chroot /var/lib/haproxy
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	tcp
	option	tcplog
        option  dontlognull
        option  redispatch
        option forwardfor
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend 1beee1fc-e05a-43ba-908f-db6aed79e6c7_frontend
        bind 10.42.230.239:443 ssl crt /etc/haproxy/certs/  no-sslv3 no-tlsv10
        mode http

        acl 1_host hdr(host) -i foo
        acl 1_host hdr(host) -i foo:443
    	use_backend 1beee1fc-e05a-43ba-908f-db6aed79e6c7_1_backend if 1_host 

backend 1beee1fc-e05a-43ba-908f-db6aed79e6c7_1_backend
        mode http
        balance roundrobin
        server 2a371d69-c428-4755-a18a-b7f48c025253 10.42.193.115:80
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        
frontend bd72b7a4-d5a3-44e2-9ec7-491653fe50ff_frontend
        bind 10.42.230.239:80
        mode http

        acl 0_host hdr(host) -i foo
        acl 0_host hdr(host) -i foo:80
    	use_backend bd72b7a4-d5a3-44e2-9ec7-491653fe50ff_0_backend if 0_host 

backend bd72b7a4-d5a3-44e2-9ec7-491653fe50ff_0_backend
        mode http
        balance roundrobin
        server 2a371d69-c428-4755-a18a-b7f48c025253 10.42.193.115:80
```

**Comment by fentas** [comment]
*docker-compose* of meh. Is active and green (no error logs). 
```yml
meh:
  image: meh:latest
  stdin_open: true
  tty: true
  restart: always
  volumes:
    - /data/subscriptions:/usr/share/nginx/web/php/subscriptions:rw
  labels:
    io.rancher.scheduler.affinity:host_label: host=EX40
    io.rancher.container.pull_image: always
  health_check:
    port: 80
    request_line: GET / HTTP/1.0
    interval: 2000
    healthy_threshold: 2
    unhealthy_threshold: 3
    response_timeout: 2000
```
