### ISSUE TITLE
All project logging fails if one project has a bad endpoint

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#26771]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Issue:
When logging for one project is set with a bad endpoint configuration, it breaks logging for all of the customers on the cluster as soon as fluentd pods restart.  Other clusters have some projects successfully logging to some of the same endpoints (so the issue is endpoint independent).

Recreation:
1. We added a bad endpoint to a project with no workloads at 12:21 UTC. 
2. When we tested the configuration, we saw:
![image](https://user-images.githubusercontent.com/8906089/80090101-e42c1f80-8556-11ea-8d06-86aa619a3636.png)
3. Once we saved the configuration, we stopped seeing logs for fluentd sending to other endpoints, and instead started seeing only retries for the bad endpoint like the following (except a pod on one node):
```
020-04-22 12:21:31 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:21:31 2020-04-22 12:21:31 +0000 [warn]:    #0       Remaining retry: 14. Retry to communicate after 2 second(s).
22.4.2020 14:21:35 2020-04-22 12:21:35 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:21:35 2020-04-22 12:21:35 +0000 [warn]:    #0       Remaining retry: 13. Retry to communicate after 4 second(s).
22.4.2020 14:21:43 2020-04-22 12:21:43 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:21:43 2020-04-22 12:21:43 +0000 [warn]:    #0       Remaining retry: 12. Retry to communicate after 8 second(s).
22.4.2020 14:21:59 2020-04-22 12:21:59 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:21:59 2020-04-22 12:21:59 +0000 [warn]:    #0       Remaining retry: 11. Retry to communicate after 16 second(s).
22.4.2020 14:22:31 2020-04-22 12:22:31 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:22:31 2020-04-22 12:22:31 +0000 [warn]:    #0       Remaining retry: 10. Retry to communicate after 32 second(s).
22.4.2020 14:23:35 2020-04-22 12:23:35 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:23:35 2020-04-22 12:23:35 +0000 [warn]:    #0       Remaining retry: 9. Retry to communicate after 64 second(s).
22.4.2020 14:25:43 2020-04-22 12:25:43 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:25:43 2020-04-22 12:25:43 +0000 [warn]:    #0       Remaining retry: 8. Retry to communicate after 128 second(s).
22.4.2020 14:29:59 2020-04-22 12:29:59 +0000 [warn]:    #0       Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Temporary failure in name resolution (SocketError)
22.4.2020 14:29:59 2020-04-22 12:29:59 +0000 [warn]:    #0       Remaining retry: 7. Retry to communicate after 256 second(s).
 ```
The one other node started warning that buffer flushes were taking longer than expected (no logs were uploaded):
```
2020-04-22T13:27:21.947295419Z 2020-04-22 13:27:21 +0000 [warn]:    #0       buffer flush took longer time than slow_flush_log_threshold: elapsed_time=701.5114311971702 slow_flush_log_threshold=40.0 plugin_id="object:3ffb30460fe4"
2020-04-22T13:27:24.303826107Z 2020-04-22 13:27:24 +0000 [warn]:    #0       buffer flush took longer time than slow_flush_log_threshold: elapsed_time=640.3008295670152 slow_flush_log_threshold=40.0 plugin_id="object:3ffb30460fe4"
```
4. On all worker nodes, we see fluentd-project*.pos files in /var/lib/rancher/fluentd/log/ stop updating, though fluentd-rke-logging.pos continued to see updates. The ElasticSearch endpoint for the cluster did not receive any logs:
![image](https://user-images.githubusercontent.com/8906089/80090150-f908b300-8556-11ea-9b1d-e819fd8fcc5a.png)  ​(Time in CST)
5. We see periodic errors in the Log configuration screen for other projects though we can see in the log that it was successfully sending messages to this endpoint until the pod was restarted with the incorrect endpoint configuration.
![image](https://user-images.githubusercontent.com/8906089/80090194-0aea5600-8557-11ea-8ee0-471791dd9508.png)
6. Disabled the faulty logging at 12:52 UTC to no effect
7. Restarting the pods got logs flowing again

**Other details that may be helpful:**
DM me in slack for logs from each of the Rancher nodes, from a node with retrying failures, and from the only node where we were not seeing these retries in fluentd logs (all collected from before the pod restart and after disabling the faulty configuration).

**Environment information**
- Rancher: v2.3.3

**Cluster information**
- Downstream cluster on internal VMs (Looks like vSphere as we see things named vmware)
- Rancher-logging version: v0.1.3
- Project logging and Cluster logging enabled
- Different customers will own different Projects
- Each project may be configured with its own log forwarding endpoints.

gz#9446

**Comment by Tejeev** [comment]
The error happened again, but this time we know the endpoint was configured correctly and was sending data to a service address in a project.
The user deactivated the workload behind the service. So the fluentd got timeout errors at configuration reload and stopped working.
To fix that problem it is not enough to check endpoint configuration initially. The configuration (inclusive endpoint reachability) should be also checked before every config reload.

**Comment by MKlimuszka** [comment]
Assigning to Ron to check to see if it's also a bug in logging v2.

**Comment by ronhorton** [comment]
**I reproduced this on 2.6.5**

1. installed logging v2
2. created cluster output for elasticsearch
3. created cluster flow 
4. verified logs flowing to elasticsearch
5. created 2nd cluster output for elasticsearch with bad endpoint
6. created 2nd cluster flow to point to 2nd cluster output

`Result: all logs stopped flowing to elasticsearch`

There are 5 fluentbit pods in cattle-logging-system; they are all in error states. 

`[2022/06/03 21:10:35] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:10:35] [ warn] [engine] failed to flush chunk '1-1654290251.245664928.flb', retry in 166 seconds: task_id=250, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:10:36] [error] [net] TCP connection failed: rancher-logging-root-fluentd.cattle-logging-system.svc.cluster.local:24240 (Connection refused)
[2022/06/03 21:10:36] [error] [output:forward:forward.0] no upstream connections available`

`[2022/06/03 21:14:04] [error] [net] TCP connection failed: rancher-logging-root-fluentd.cattle-logging-system.svc.cluster.local:24240 (Connection refused)
[2022/06/03 21:14:04] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:14:04] [ warn] [engine] failed to flush chunk '1-1654290337.88620378.flb', retry in 70 seconds: task_id=369, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:14:06] [error] [net] TCP connection failed: rancher-logging-root-fluentd.cattle-logging-system.svc.cluster.local:24240 (Connection refused)
[2022/06/03 21:14:06] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:14:06] [ warn] [engine] failed to flush chunk '1-1654290094.84311874.flb', retry in 198 seconds: task_id=17, input=tail.0 > output=forward.0 (out_id=0)`

`[2022/06/03 21:15:09] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:15:09] [ warn] [engine] failed to flush chunk '1-1654290183.101587632.flb', retry in 977 seconds: task_id=144, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:15:10] [error] [net] TCP connection failed: rancher-logging-root-fluentd.cattle-logging-system.svc.cluster.local:24240 (Connection refused)
[2022/06/03 21:15:10] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:15:10] [ warn] [engine] failed to flush chunk '1-1654290093.99668038.flb', retry in 558 seconds: task_id=24, input=tail.0 > output=forward.0 (out_id=0)`

`[2022/06/03 21:15:56] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:15:56] [ warn] [engine] failed to flush chunk '1-1654290380.507058965.flb', retry in 1080 seconds: task_id=451, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:15:56] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:15:56] [ warn] [engine] failed to flush chunk '1-1654290273.507212578.flb', retry in 897 seconds: task_id=281, input=tail.0 > output=forward.0 (out_id=0)`

`[2022/06/03 21:16:46] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:16:46] [ warn] [engine] failed to flush chunk '1-1654290335.499614258.flb', retry in 729 seconds: task_id=366, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:16:47] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:16:47] [ warn] [engine] failed to flush chunk '1-1654290070.497950049.flb', retry in 540 seconds: task_id=0, input=tail.0 > output=forward.0 (out_id=0)
[2022/06/03 21:16:47] [error] [output:forward:forward.0] no upstream connections available
[2022/06/03 21:16:47] [ warn] [engine] failed to flush chunk '1-1654290182.497616378.flb', retry in 315 seconds: task_id=147, input=tail.0 > output=forward.0 (out_id=0)`

**Comment by heavenkiller2018** [comment]
what's the problem now?

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x

**Comment by eliyamlevy** [comment]
@MKlimuszka I reproduced the issue in the latest rancher and logging versions.

Configured a flow with two outputs, one that has a correct and functioning ClusterOutput and one that has an incorrect endpoint. The issue occurs when incorrectly configured output is added. No logs are sent to the correct one. 

When I removed the incorrect one no logs were sent still, however after some time logs began to send again and the issue corrects itself. So the issue does correct itself after some time if the incorrect ClusterOutput is removed from the flow but the issue still does occur. 

Logs do send if one of the flows has an incorrect output. It only occurs for flows that have one or more incorrect outputs.

This is probably an upstream issue that needs to be fixed there but it does resolve if the problem output is removed from the flow.

**Comment by MKlimuszka** [comment]
Since this was tied to an upstream issue over a year ago, I'm queuing this for reproduction in newest versions.

**Comment by adamkpickering** [comment]
I reproduced this issue using Rancher Logging `105.2.2+up4.10.0-rancher.1`.

I see the same thing described in https://github.com/rancher/rancher/issues/26771#issuecomment-1421385830: when configuring a `ClusterOutput` with an invalid endpoint (with a `ClusterFlow` that references it) logs cease to flow to elasticsearch. The logs produced by the `fluentbit` pods look as follows:
```
[2025/04/14 21:37:36] [error] [upstream] connection #129 to tcp://10.43.190.83:24240 timed out after 10 seconds (connection timeout)
[2025/04/14 21:37:36] [error] [upstream] connection #130 to tcp://10.43.190.83:24240 timed out after 10 seconds (connection timeout)
[2025/04/14 21:37:36] [error] [upstream] connection #64 to tcp://10.43.190.83:24240 timed out after 10 seconds (connection timeout)
[2025/04/14 21:37:36] [ warn] [engine] failed to flush chunk '1-1744666485.766626455.flb', retry in 46 seconds: task_id=281, input=tail.0 > output=forward.0 (out_id=0)
[2025/04/14 21:37:36] [error] [output:forward:forward.0] no upstream connections available
[2025/04/14 21:37:36] [error] [output:forward:forward.0] no upstream connections available
[2025/04/14 21:37:36] [error] [output:forward:forward.0] no upstream connections available
[2025/04/14 21:37:36] [ warn] [engine] failed to flush chunk '1-1744666391.837929658.flb', retry in 147 seconds: task_id=170, input=tail.0 > output=forward.0 (out_id=0)
[2025/04/14 21:37:36] [ warn] [engine] failed to flush chunk '1-1744666392.763873065.flb', retry in 23 seconds: task_id=172, input=tail.0 > output=forward.0 (out_id=0)
```
And once the bad `ClusterOutput` and `ClusterFlow` are deleted, the system eventually fixes itself. It appears that many of the logs eventually come through to elasticsearch, since there are more when the system is recovering than there are under normal operation.

Here are the manifests I used: 
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: badelasticsearch
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
  - badelasticsearch
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: badelasticsearch
  namespace: cattle-logging-system
spec:
  elasticsearch:
    host: invalidaddress.cattle-logging-system.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: elasticsearch
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
  - elasticsearch
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: elasticsearch
  namespace: cattle-logging-system
spec:
  elasticsearch:
    host: quickstart-es-http.cattle-logging-system.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: quickstart-es-elastic-user
          key: elastic
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: cattle-logging-system
spec:
  version: 8.17.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: cattle-logging-system
spec:
  version: 8.17.4
  count: 1
  elasticsearchRef:
    name: quickstart
```
