### ISSUE TITLE
rancher-monitoring: Access Prometheus DataSource from another pod/namespace

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#26794]
**What kind of request is this (question/bug/enhancement/feature request):**

Question

**Steps to reproduce (least amount of steps as possible):**

Enable Monitoring. 

Deploy an additional Grafana instance in the cluster in another namespace.

Try to access Prometheus DataSource from the manually created Grafana Instance.

**Result:**

Setting http://prometheus.operated:9090 as DataSource, as configured in the default Grafana is unaccessible from another namespace => expected (dns)

Setting http://prometheus.operated.cattle-prometheus.svc.cluster.local:9090 or http://\<prometheus cluster ip\>:9090 as DataSource in another Grafana results in `unauthorized` => it appears the access has been hardened with a Bearer token during `cluster-monitoring`  project deployment. 

Token stored as secret, deployed in the `plugin.json` of prometheus through `routes` => So, expected.

Setting http://prometheus.operated.cattle-prometheus.svc.cluster.local:8080 as DataSource, or `curl`  the API without kind of added auth, works without problems => is it expected ?

`cluster-monitoring` also deploys a nginx proxy for prometheus that also embeds the Bearer token and makes prometheus API available on port 8080 for other pods, without any kind of auth. 

While this makes my scenario possible, it looks inconsistent with the hardening done, or have I missed something?

**Other details that may be helpful:**

Embedded monitoring is great. 

Our app has components deployed on multiple platforms and PaaS in addition to rancher/k8s. We're looking for centralized monitoring.

Grafana Dashboard could mix Prometheus data from k8s cluster(s), Azure Monitor, ElasticSearch logging, among others DataSource, and Dashboards should be accessible outside of rancher. For k8s, reuse of Prometheus Data from Rancher monitoring is a must. Thus connecting another Grafana to Rancher's Prometheus monitoring to create dashboards that mix with other sources.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Infrastucture Provider, vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM, various templates.
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by erSitzt** [comment]
I have a similar problem.

I want to centralize monitoring dashboards in an external grafana instance and need access to prometheus datasources in several rancher managed kubernetes clusters.

What is the correct solution here ?

**Comment by Purneau** [comment]
What we did:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: company-issuer
  name: access-prometheus
  namespace: cattle-prometheus
spec:
  rules:
    - host: access-prometheus.{{ .Values.clusterHost }}
      http:
        paths:
          - backend:
              serviceName: access-prometheus
              servicePort: 80
            path: /
  tls:
    - hosts:
        - access-prometheus.{{ .Values.clusterHost }}
      secretName: very-secret
```
