### ISSUE TITLE
[question] How do you replace the primary rancher node?

### ISSUE THREAD

**Issue by wimo7083** [rancher/rancher#26803]
**What kind of request is this (question/bug/enhancement/feature request):**
I have a rancher cluster that is setup based on best HA practices. With a very minimal rancher-cluster.yml

```yaml

ssh_key_path: /home/rancher/.ssh/rancher_id_rsa
nodes:

  - address: rancher-master-1.domain.com. # primary
    user: rancher
    role: [controlplane,worker,etcd]

  - address: rancher-master-2.domain.com # secondary
    user: rancher
    role: [controlplane,worker,etcd]

  - address: rancher-master-3.domain.com # secondary
    user: rancher
    role: [controlplane,worker,etcd]

ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"
```
The initial rke up command was invoked on rancher-master-1.domain.com.

I'm attempting to practice scenario for DR in which two of the HA nodes are unhealthy  and I need to replace them. 

**Steps to reproduce (least amount of steps as possible):**

Two test cases:
1. remove and replace secondaries. - this works without any issue
2. remove and replace the primary - this has problems

Case 1:
1. Comment out the two nodes in `rancher-cluster.yml` 
2. `rke up --config /etc/rancher/rancher-cluster.yml --update-only` 
3. For those 2 removed nodes: [cleaning a node](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/#removing-rancher-components-from-imported-clusters).
4. Reboot the node.
5. Re-add 2 nodes to `rancher-cluster.yml`
6.`rke up --config /etc/rancher/rancher-cluster.yml --update-only`

Case 2:

I've tried to a few method to remove the primary and one secondary. but each time I run into problems.

If I do this using the [recover without backed up etcd snapshot](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/restoring-etcd/#recovering-etcd-without-a-snapshot) I can get the single node working without any issues. but as soon as I try and rejoin more nodes (after cleaning), things go wrong. I have a suspicion that the rkestate on the primary node needs to be updated in some manner. Or there's some other state. 

**Result:**

I haven't found a way to add a second node back to the recovered node without etcd showing unhealthy. And I don't really see anything docs suggesting how this should be done. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8GB, 2 cpu
- Kubernetes version (use `kubectl version`):

```
v1.16.3
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
