### ISSUE TITLE
[Feature Request] LetsEncrypt DNS-01 challenge type

### ISSUE THREAD

**Issue by Just-Insane** [rancher/rancher#26850]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

It would be nice to have support for DNS-01 challenge requests for LetsEncrypt during Rancher install.

Use Case:

1) Security - Would not have to expose Rancher to the internet directly in order to get a valid certificate, this increases overall security and limits the attack surface.

2) Security - Using wildcard certificates obscures the names of (potentially) internal services from showing up in certificate transparency logs, which is mostly security through obscurity, but could be useful in some cases.

3) Convenience - DNS-01 is more convenient to use since it doesn't require changing firewall rules, something which can be an issue for businesses.

**Comment by bashofmann** [comment]
One way to do this already now:

* Set `ingress.tls.source` to `secret`
* Create a certificate and issuer manually that store the certificates in a secret `tls-rancher-ingress` in the `cattle-system` namespace

```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  commonName: rancher.example.com
  dnsNames:
  - rancher.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              key: access-token
              name: digitalocean-credentials-secret
---
apiVersion: v1
data:
  access-token: <base64 encoded token>
kind: Secret
metadata:
  name: digitalocean-credentials-secret
  namespace: cert-manager
type: Opaque
```
