### ISSUE TITLE
Questions in catalog apps converts long number strings to scientific notation

### ISSUE THREAD

**Issue by bentastic27** [rancher/rancher#26862]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Set up a test chart with the following values.yaml, questions.yaml and configmap.yaml (or use [this test chart I made](https://github.com/bentastic27/helm-test-dont-use/tree/master/charts/value-test)).

Import the "custom catalog" into rancher and install as an app. Use `982345235` as the value of the "some code" question and hit save.

It doesn't matter if the answer is in quotes or not, the result is the same.

```
# values.yaml
somedefault: "982345235"
```
```
# questions.yaml
questions:
- variable: somedefault
  label: some code
  description: "code"
  default: "982345235"
  required: true
  type: string
```
```
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: {{ .Release.Name }}-cf-test
data:
  someValue: "{{ .Values.somedefault }}"
```

**Result:**

Instead of remaining as a string, the answer is converted to `9.82345235e8`.

**Other details that may be helpful:**

This doesn't have the same behavior when using `helm template .` with helm 2 or 3.

```
$ helm template .
---
# Source: values-test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-configmap
  labels:
    app: RELEASE-NAME-cf-test
data:
  someValue: "982345235"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.6

- Installation option (single install/HA):
both
