### ISSUE TITLE
Opportunity to change logging directory

### ISSUE THREAD

**Issue by demudrol** [rancher/rancher#26945]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Select Cluster
2. Go to Apps
3. rancher-logging with three dots and Upgrade menu
4. Section with Variable and Value without option to change logging dir

**Result:**
Section with Variable and Value has option to change logging dir

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6
- Installation option (single install/HA): HA

**Workaround solution**
1. Clone https://git.rancher.io/system-charts repo
2. Make branche from last release
3. Go to rancher-system-charts/charts/rancher-logging/0.2.0/charts/fluentd/charts/fluentd-linux/templates/daemonset.yaml
4. Add strings to volumeMounts and volumes:
```
      volumeMounts:
        - mountPath: /data/docker/containers
          name: datalogcontainers
      volumes:
      - hostPath:
          path: /data/docker/containers
        name: datalogcontainers  

```
5. Go to Catalog and select your branch.

**It will be awesome to change without cloning and modify repo** :revolving_hearts:
