### ISSUE TITLE
[Authorized Cluster Endpoint] Generate Kubeconfig with default Kube-CA when using FQDN

### ISSUE THREAD

**Issue by azbpa** [rancher/rancher#26986]
**Feature Request**

I have *Custom Clusters* with multi-node control planes and I would like to achieve a HA setup through an external L4 load balancer (with a virtual FQDN) when using *Authorized Cluster Endpoint* feature.

Therefore I added the value for `fqdn`  to my cluster config:

```
local_cluster_auth_endpoint:
  enabled: true
  fqdn: my-virtual-cluster-name.my.domain
```

I want to avoid TLS termination on the load balancer itself since I am fine with the certificate generated for kube-apiserver signed by `kube-ca`. So I added my `fqdn` also as SAN to my RKE config:

```
rancher_kubernetes_engine_config:
  authentication:
    sans:
      - my-virtual-cluster-name.my.domain
``` 

As a result, when using the *Kubeconfig File* feature from the Rancher UI, I am getting the following file generated:

```
apiVersion: v1
kind: Config
clusters:
- name: "my-virtual-cluster-name"
  cluster:
    server: "https://rancher.my.domain/k8s/clusters/c-abcde"
    certificate-authority-data: "...."
- name: "my-virtual-cluster-name-fqdn"
  cluster:
    server: "https://my-virtual-cluster-name.my.domain"
users:
...
```

Obviously, for my use case, I am missing the `certificate-authority-data` value containing the `kube-ca` certificate (probably because I didn't specify a custom CA within the `local_cluster_auth_endpoint` section). However, since I actually don't want to use a custom CA and certificate at the LB, I would like to have the possibility to keep the default value for `certificate-authority-data` to receive the cluster's default CA (like it is done without using `fqdn` in `local_cluster_auth_endpoint` section).

I would like to see a simple parameter like `use_custom_ca` which could be set to `false` to receive the default CA if the kubeconfig gets generated. 

```
local_cluster_auth_endpoint:
  enabled: true
  fqdn: my-virtual-cluster-name.my.domain
  use_custom_ca: false
```

The default value of `use_custom_ca` could be set to `true` to not change the current behavior when using the `fqdn` parameter with TLS termination and a well-known CA.

Of course, I could simply add the `kube-ca` certificate by hand to my config file and everything would be fine, but from the end-users perspective, this feature request would increase the user experience certainly, at lease for inexperienced users for which Rancher Server is an easy entrance to Kubernetes.

gz#10281
