### ISSUE TITLE
[BUG] Can't activate fluentd configmapReload resource limit

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#26993]
Problem:

```
fluentd:
  enabled: true
  fluentd-linux:
    configmapReload:
      resources:
        limits:
          cpu: "20m"
```

```
helm install --dry-run -f values.yaml rancher-logging2 ./charts/rancher-logging/0.1.4/
Error: YAML parse error on rancher-logging/charts/fluentd/charts/fluentd-linux/templates
/daemonset.yaml: error converting YAML to JSON: yaml: line 107: did not find expected key
```

**Comment by BobVanB** [comment]
Hi @maggieliu thank you for this.
I still wanted to add one thing. Its a choice of taste.
In the pull request i used `indent 10` and start of the first char. Only because this is used in the rest of the document. Like so:
```
        resources:
{{ toYaml .Values.configmapReload.resources | indent 10 }}
```
I like the way that the template starts at the line that it suppose to be.
Can make a template more readable and can be done with `nindent`.
```
        resources:
          {{ toYaml .Values.configmapReload.resources | nindent 10 }}
```
With kind regards,

Bob.

**Comment by maggieliu** [comment]
@BobVanB No problem. If you need to make additional changes, can you update the PR?

**Comment by izaac** [comment]
Reproduced the issue in Rancher `v2.4.5`

- Clone: `git clone git@github.com:rancher/system-charts.git`
- cd `system-charts`
- Create a file `values.yaml`
- Add the contents (as described in this issue)

```yaml
fluentd:
  enabled: true
  fluentd-linux:
    configmapReload:
      resources:
        limits:
          cpu: "20m"
```

- Run:  `helm_v3 install --dry-run -f values.yaml rancher-logging2 ./charts/rancher-logging/0.1.4/`

`Error: YAML parse error on rancher-logging/charts/fluentd/charts/fluentd-linux/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 107: did not find expected key`

**Comment by izaac** [comment]
Rancher version `master-head (07/02/2020)` _ec1ea7a99_
Rancher version `v2.4-head (07/02/2020)` _efd76d86b_
Rancher version `v2.3-head (07/02/2020)` _6967492fc_

```json
fluentd:
  enabled: true
  fluentd-linux:
    configmapReload:
      resources:
        limits:
          cpu: "20m"
```

`helm_v3 install -f values.yaml rancher-logging2 ./charts/rancher-logging/0.2.1/`

I was able to set and check the cpu configmapReload resource limit set in the cluster for `rancher/configmap-reload:v0.3.0-rancher2`
![Screen Shot 2020-07-02 at 2 54 16 PM](https://user-images.githubusercontent.com/27659/86414131-f4a7f700-bc77-11ea-92a1-31d2cca2bbba.png)


```yaml
    image: rancher/configmap-reload:v0.3.0-rancher2
    imagePullPolicy: IfNotPresent
    name: rancher-logging2-fluentd-reloader
    resources:
      limits:
        cpu: 20m
```
