### ISSUE TITLE
Ingress with no path will cause a panic

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#27230]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Ingress with no path will cause a panic

If no path is set the HTTP field is nil causing a panic. The below yaml cause Rancher to panic.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: hostname
```

**Result:**

Panic

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA):
Doesn't amtter
