### ISSUE TITLE
EmptyDir volume permission denied with SecurityContext

### ISSUE THREAD

**Issue by danielhass** [rancher/rancher#27278]
I'm currently facing an issue with a permission problem inside of pods when using an EmptyDir as volume type together with a SecurityContext.

Short summary:
- a standard EmptyDir mount is not writeable from the applicaiton user within the pod
- a EmptyDir with setting `medium: Memory` solves this problem

I stumbled across this during the deployment of the Rancher integrated monitoring (this is why in the example below I use the rancher grafana container for reference).
This may or may not be related to #17256.

Please find the details below.

Thanks for any help pointing me into the right direction!

**What kind of request is this (question/bug/enhancement/feature request):** 
Question

**Steps to reproduce (least amount of steps as possible):**
- Deploy a pod that uses an EmptyDir + a non-root SecurityContext, e.g.:
```
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-test
  namespace: default
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 1h
    image: rancher/grafana-grafana:6.3.6
    imagePullPolicy: Always
    name: emptydir-test
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 472
      runAsNonRoot: false
      runAsUser: 472
    volumeMounts:
    - mountPath: /mnt/test
      name: vol1
  restartPolicy: Always
  securityContext:
    fsGroup: 472
  volumes:
  - emptyDir: {}
    name: vol1
```
- Try to write with the applicaiton user from inside the pod to the mounted EmptyDir

**Result:**
- Permission denied

**Other details that may be helpful:**

Steps to reproduce the Permission denied error within the sample pod:
```
grafana@emptydir-test:/mnt/test$ id
uid=472(grafana) gid=472(grafana) groups=472(grafana)
grafana@emptydir-test:/mnt/test$ ls -al
total 4
drwxrwsrwx+ 2 root grafana 4096 May 27 11:36 .
drwxr-xr-x  1 root root       8 May 27 11:36 ..
grafana@emptydir-test:/mnt/test$ touch test
touch: cannot touch 'test': Permission denied
```

EmptyDir volume directory within `/var/lib/kubelet/` showning the (from my point of view) correct permissions:
```
/opt/k8s/var/lib/kubelet/pods/01dd61ce-7e67-479f-b71b-72b0f27d289c/volumes/kubernetes.io~empty-dir # ls -al
drwxr-x---+ 3 root root 4096 27. Mai 13:48 .
drwxr-x---+ 4 root root 4096 27. Mai 13:48 ..
drwxrwsrwx+ 2 root  472 4096 27. Mai 13:48 vol1
```

Docker inspect on the container of the Pod showing the Mounts section:
```
[...]
"Mounts": [
            {
                "Type": "bind",
                "Source": "/opt/k8s/var/lib/kubelet/pods/01dd61ce-7e67-479f-b71b-72b0f27d289c/volumes/kubernetes.io~empty-dir/vol1",
                "Destination": "/mnt/test",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
[...]
```

I retested this behaviour with a slightly adopted EmptyDir definition using the option `medium: Memory`:

```
[...]
volumes:
  - emptyDir:
        medium: Memory
    name: vol1
[...]
```

Now the permission denied error disappears and a write is possible:
```
grafana@emptydir-test:/mnt/test$ id
uid=472(grafana) gid=472(grafana) groups=472(grafana)
grafana@emptydir-test:/mnt/test$ ls -al
total 0
drwxrwsrwt 2 root grafana 40 May 27 11:43 .
drwxr-xr-x 1 root root     8 May 27 11:39 ..
grafana@emptydir-test:/mnt/test$ touch test
grafana@emptydir-test:/mnt/test$ ls -al
total 0
drwxrwsrwt 2 root    grafana 60 May 27 11:43 .
drwxr-xr-x 1 root    root     8 May 27 11:39 ..
-rw-r--r-- 1 grafana grafana  0 May 27 11:43 test
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 2xVM (master+worker) / 4 vCPUs + 8 GB RAM 
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838f1
 Built:             Mon Dec 16 09:43:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838f1
  Built:            Wed Nov 13 07:19:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.1.3_catatonit
  GitCommit:
```
