### ISSUE TITLE
Removing in-tree vSphere vCenter server entries does not propagate

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/rancher#27306]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Initial config:

```yaml
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.22
```

Kube-apiserver container info:

```bash
root@vsp-intree1:~# docker inspect kube-apiserver | grep cloud
            "--cloud-config=/etc/kubernetes/cloud-config",
            "--cloud-provider=vsphere",
                "--cloud-config=/etc/kubernetes/cloud-config",
                "--cloud-provider=vsphere",
root@vsp-intree1:~# 
```

Contents of /etc/kubernetes/cloud-config

```bash
root@vsp-intree1:~# cat /etc/kubernetes/cloud-config

[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"


[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.22"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

Amend config to include second vcenter, point the workspace to it

```yaml
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

Kube-apiserver restarts

```bash
41 seconds ago      Up 40 seconds                           kube-apiserver
```

 /etc/kubernetes/cloud-config gets updated:

```bash
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"

[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"
[VirtualCenter "172.16.10.23"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab2"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.23"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

Remove one of the vCenter entries (172.16.10.22 in this example)

```yaml
virtual_center:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

After clicking save, Rancher triggers a cluster upate, but kube-apiserver is not restarted. Additionally, going back to editing the cluster yaml reveals the segment previously removed has been re-inserted.

```yaml
virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

 /etc/kubernetes/cloud-config still reflects the previous configuration:

```bash
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"

[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"
[VirtualCenter "172.16.10.23"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab2"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.23"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

**Result:**

Adding additional enties works. However removing entries does not.

**Other details that may be helpful:**

**Environment information**

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

Rancher HA install on RKE

**Cluster information**
- Cluster type: Infrastructure provider leveraging vSphere node driver
- Machine type: VM 2vCPU/4GB RAM
- Kubernetes version (use `kubectl version`):

```
Infrastructure provider : vSphere
Machine Type : VM 2vCPU/4GB RAM
Kubernetes version: v1.17.5
```

- Docker version (use `docker version`):

```
19.03.9
```

gz#10316

**Comment by redi-dangeloj** [comment]
Hitting what looks like the same issue with Rancher 2.4.3.    

Our cluster's rancher_rke_template information has an erroneous IP address for vcenter and causes dynamic storage provisioning to be blocked.    

Besides uses Edit YAML for the cluster config and trying to delete the entries (with adding Password: back from presumably be redacted), we have also tried creating a RKE template, modifying a new version and verifying the yaml only has a single and correct entry, and then update the child cluster having the issue to the new version along with even deploying new nodes and always end up with having the extra erroneous entries for vcenters that don't exist.    With the vsphere provider trying to contact an unreachable vcenter, we cannot provision any Persistent Volumes and are blocked.

**Comment by superseb** [comment]
This seems to be happening around https://github.com/rancher/rancher/blob/master/pkg/api/norman/store/cluster/cluster_store.go#L945

**Comment by sadiapoddar** [comment]
Reproduced this issue on v2.4.3 
Steps to repro
1. created a cluster on vSphere cloud provider by choosing the "custom" provider option and added the clouder provider information in YMAL file
2. Once the cluster is up checked all the config info. 
`
root@sadia-control1:~# docker inspect kube-apiserver |grep cloud
            "--cloud-config=/etc/kubernetes/cloud-config",
            "--cloud-provider=vsphere",
                "--cloud-config=/etc/kubernetes/cloud-config",
                "--cloud-provider=vsphere",
root@sadia-control1:~# cat /etc/kubernetes/cloud-config

[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"


[VirtualCenter "xxx"]
        user = ""xxxxx"r"
        password = ""xxxxx""
        port = "443"
        datacenters = ""xxxxx""
        soap-roundtrip-count = "0"

[Workspace]
        server = "xxx"
        datacenter = "xxxxx"
        folder = "xxxxx"
        default-datastore ="xxxxx"
        resourcepool-path = ""xxxxx""

[Disk]

[Network]

 `

3. Edited the cluster configuration and added a second vCenter information in the cluster config and saved it
<img width="843" alt="Screen Shot 2020-12-18 at 3 34 05 PM" src="https://user-images.githubusercontent.com/72409237/102672878-f17dc600-4146-11eb-9f71-61acb5f28a66.png">

4. Since the second vCenter which was added doesn't exist, the cluster update showing an error during updating the cluster with the newly added vCenter.

<img width="1254" alt="Screen Shot 2020-12-18 at 3 11 46 PM" src="https://user-images.githubusercontent.com/72409237/102672994-4a4d5e80-4147-11eb-8657-37221648bddd.png">

5. Removed the second vCenter clause from the cluster config YMAL file and saved
Still seeing the same error on the UI. Checked the cluster config file and the second vCenter info added in YMAL file not removed. Tried a few times to remove that entry and it's not removable. 

With this 2nd vCenter the Rancher UI periodic cluster update tries to connect to the second vCenter and shows the error
<img width="1254" alt="Screen Shot 2020-12-18 at 3 11 46 PM" src="https://user-images.githubusercontent.com/72409237/102673207-09a21500-4148-11eb-8d1f-5c6683a6b851.png">

**Comment by rawmind0** [comment]
Issue reproduced on rancher v2.5.x. 

Making some testing, the issue seems to be around https://github.com/rancher/rancher/blob/master/pkg/api/norman/store/cluster/cluster_store.go#L541
Data is arriving find to update function but Rancher API is not overwriting empty `virtual_center` entries. It's merging old and new values instead of replace them.

Investigating to find out a solution for this issue.

Starting from original example:

* Deploy cluster with cloud_provider with 2 virtual_centers: Working
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

* Updating cluster removing 1 virtual_centers: Not working. It's merging old and new values instead of replace them, letting virtual_center.172.16.10.22 as was.
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

* Updating cluster setting 1 empty virtual_centers: Not working. It's merging old and new values instead of replace them, setting virtual_center.172.16.10.22 as empty.
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```
