### ISSUE TITLE
Rancher Apps fails to render Helm chart with lookup function

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#27313]
Helm `3.1.something` introduced the `lookup` function for pulling in data from the target cluster. This is potentially really useful for setting up environment specific metadata for your deployments and avoiding user input. (i.e. dynamically setting domain names for Ingress).

It looks like rancher apps use `helm template` to render the mainifests offline. `lookup` doesn't work with `helm template`, `lint` or `install --dry-run` since it needs a connection to query the target cluster for data. It would be pretty swell if charts that use `lookup` worked with the app catalog.

Link to `lookup` documentation:
https://helm.sh/docs/chart_template_guide/functions_and_pipelines/

Example error message when trying to look up a value from a ConfigMap pre-deployed in the target Namespace.

```
Wait helm template failed. Error: template: frontend/templates/ingress.yaml:12:15: executing "frontend/templates/ingress.yaml" at <include "chart.domain" .>: error calling include: template: frontend/templates/_helpers.tpl:58:47: executing "chart.domain" at <"namespace">: nil pointer evaluating interface {}.DOMAIN Use --debug flag to render out invalid YAML : exit status 1
```

Snippets from my chart.

`_helpers.tpl` - target namespace has a very creatively named ConfigMap called "namespace-values". There is a value of DOMAIN in that ConfigMap

```
{{- define "chart.domain" -}}
{{ (lookup "v1" "ConfigMap" .Release.Namespace "namespace-values").data.DOMAIN }}
{{- end }}
```

`ingress.yaml`

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: {{ include "chart.domain" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "chart.fullname" . }}
              servicePort: 80
  tls:
    - hosts:
        - {{ include "chart.domain" . }}
      secretName: {{ include "chart.fullname" . }}-tls
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|
