### ISSUE TITLE
[rancher-compose] Upload Local Volumes like build does

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#2733]
It would be awesome if in my docker-compose file, I could define my volumes that point to a local folder, eg:

``` yml
registry:
  restart: always
  ports:
  - 443:5000/tcp
  environment:
  labels:
    io.rancher.scheduler.affinity:host_label: host=registry
  image: registry:2.2.0
  volumes:
  - ./certs:/certs
```

And it would upload the contents of `./certs` to S3 and then deploys them on each host that this container is running on.

It currently does this for build which is nice, but having to copy files to each host is really a pita.
