### ISSUE TITLE
Istio V2: CNI plugin

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#27377]
- [ ] After the 1.7 install method is determined, ensure that the CNI plugin works as expected: https://istio.io/docs/setup/additional-setup/cni/

- [ ] When it does, update the rancher docs to include a 1.7 section: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/enable-istio-in-cluster/enable-istio-with-psp/

**Comment by cbron** [comment]
This will also need a docs issue/PR to update that one page. We should keep both legacy and new way in there for now.

**Comment by rancher-max** [comment]
I attempted using this on RKE2 clusters. I validated the plugin appears to be working using Rancher v2.5-head (`e2e530c`). This is important for Selinux Enforcing systems. My cluster was a rhel8 system with selinux enforcing, and standard istio installs did not work due to the NET_ADMIN capability needed and just-in-time kernel module loading for rke2 -- see https://github.com/rancher/rke2/issues/504 for more information on this. 

The way to use this for my use case required the following steps:
1. Through the Rancher Dashboard, when enabling Istio, check the box to Enable CNI component.
2. Add a custom overlay file specifying cniBinDir and cniConfDir. See mine below:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
  values:
    cni:
      image: rancher/istio-install-cni:1.7.3
      excludeNamespaces:
        - istio-system
        - kube-system
      logLevel: info
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
```
3. After installing Istio, you'll notice the cni-node pods in the istio-system namespace in a CrashLoopBackoff error. Manually edit the `istio-cni-node` daemonset to include the following on the `install-cni` container:
```yaml
securityContext:
    privileged: true
```

Now you should be able to utilize Istio as desired, including sidecar injection and monitoring via kiali.
