### ISSUE TITLE
[server-chart]  allow user to configure pullimagepolicy of busybox container

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#27384]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Deploy Rancher with Kubernetes method
2. Enable Rancher Audit log

**Result:**
`imagePullPolicy` of Rancher container is set to `ifNotPresent` while busybox container still remaining `Always`
```
    image: rancher/rancher:v2.4.3
    imagePullPolicy: IfNotPresent
....
    image: busybox
    imagePullPolicy: Always
```
**Other details that may be helpful:**
It is not configurable in the Rancher helm chart
```
{{- if gt (int .Values.auditLog.level) 0 }}
      # Make audit logs available for Rancher log collector tools.
      - image: {{ .Values.busyboxImage }}
        name: {{ template "rancher.name" . }}-audit-log
        command: ["tail"]
        args: ["-F", "/var/log/auditlog/rancher-api-audit.log"]
        volumeMounts:
        - mountPath: /var/log/auditlog
          name: audit-log
{{- end }}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA
