### ISSUE TITLE
Linking service to loadbalancer doesn't work

### ISSUE THREAD

**Issue by Slamper** [rancher/rancher#2740]
In my current setup I have to link a service to a loadbalancer.
But the env variables weren't set and the load balancer couldn't be resolved in the "test" container.

This is an example setup
```
lba:
  ports:
  - 27017:27017/tcp
  tty: true
  image: rancher/load-balancer-service
  links:
  - mongodbexternal:mongodbexternal
  stdin_open: true
test:
  ports:
  - 80/tcp
  tty: true
  image: ubuntu
  links:
  - 'lba:'
  stdin_open: true
mongodbexternal:
  image: rancher/external-service
```

The other related problem is #2047 because the lb can't resolve the external service.

If you wonder why I want to lb a single mongodb instance.
I want to make it accessible from another DC via the ipsec tunneling and therefore, I have to "proxy" it to the network via the lb. It's just a dirty hack I need for my dev env at the moment :)
