### ISSUE TITLE
Best way to expose Prometheus for external federation?

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#27428]
I have a number of cluster provisioned and managed by Rancher 2.4.4. I have monitoring enabled but I want to consolidate the metrics into a single external Prometheus instance. I looked into Prometheus documentation on Federation and it appears that the configuration requires the external Prometheus to be able to reach the 9090 port the individual instances. I do see that the default deployment created by the operator created a number of ClusterIP services. Without modifying these I created a LoadBalancer type service to the same endpoint.

```
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cattle-prometheus
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    chart: prometheus-0.0.1
    release: cluster-monitoring
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
```

While the endpoint is reachable, it's giving me a `401 unauthorized` response. Not quite sure how this security is managed or configured. Can anyone provide some guidance on this or perhaps point me to the documentation on it? I couldn't find anything after looking around on Rancher website and Google.

**Comment by eroji** [comment]
Ok figured it out. Looks like I need to create service to the nginx sidecar instead.

```
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cattle-prometheus
spec:
  ports:
  - name: nginx-http
    port: 80
    protocol: TCP
    targetPort: nginx-http
  selector:
    app: prometheus
  selector:
    app: prometheus
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
```
