### ISSUE TITLE
Rancher is unable to deploy jobs after update to 2.4

### ISSUE THREAD

**Issue by Minizinger** [rancher/rancher#27442]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create empty chart contaiting single job.yaml:  
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "bugged-job"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "bugged-job"
        image: "debian"
        command:
        - "/bin/sh"
        - "-c"
        - "echo 1"
```
2. Push it to a chart repo or use git  
3. Deploy it as rancher app through CLI or UI

**Result:**

Job will be deployed and print "1" to logs as expected. However app deployment failed with status "Failed to install app somename. Error: transport is closing". 

If there are other templates in chart to be deployed after this failed job and/or it has dependencies - they will be ignored.  

Alternatively, flag `--helm-wait` can be used to deploy this chart, in this case error message will be absent, but the rest of the issues remain (other templates and dependencies aren't deployed)

**Other details that may be helpful:**

Stumbled upon this issue right after updating from v2.3.5, charts containing jobs have been used for a long time, automatically deployed multiple times a day.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA): HA
