### ISSUE TITLE
[pipeline] [QUESTION] How-to run script with docker run in pipeline rancher 2.0

### ISSUE THREAD

**Issue by ElGranLoky** [rancher/rancher#27481]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Configure a pipeline with stage:

```
- name: Vulnerability
  steps:
  - runScriptConfig:
      image: docker:latest
      shellScript: docker run --rm -v /mnt/cache/:/root/.cache/ aquasec/trivy namespace/test:latest
```

**Result:**
Fault with:
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.6
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal
- Kubernetes version (use `kubectl version`):
1.17.4

How would I have to set the script to run the commands that require access to docker?

**Comment by ElGranLoky** [comment]
Ok, let's go!!!

One workaround until rancher found a best solution.

1.- Create a dind in the same namespace for pipeline.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: {{custom-name-workloadselector}}
  name: dind
  namespace: {{custom-pipeline}}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: {{custom-name-workloadselector}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":2375,"dnsName":"dind","hostPort":0,"kind":"ClusterIP","name":"2375tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: {{custom-name-workloadselector}}
    spec:
      containers:
      - args:
        - dockerd
        - --host=tcp://0.0.0.0:2375
        image: docker:dind
        imagePullPolicy: Always
        name: dind
        ports:
        - containerPort: 2375
          name: 2375tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostname: dind
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```
**Important:**
* add hostname 
* run the image with "dockerd --host=tcp://0.0.0.0:2375"
* export the port 2375 in clusterip

*WARNING:* TLS disable (clear connections http inside the cluster network)

2.- Connect to this pod in the yaml for the pipeline

```
- name: Scan Vulnerability
  steps:
  - runScriptConfig:
      image: rancher/plugins-docker:18.09
      shellScript: |- 
        /usr/local/bin/docker info
        /usr/local/bin/docker login ${DOCKER_REGISTRY} --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} 
        /usr/local/bin/docker pull ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DOCKER_TAG}
        /usr/local/bin/docker tag ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DOCKER_TAG} scan:latest
        /usr/local/bin/docker run --rm -e DOCKER_HOST -v /mnt/cache/:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH scan:latest
        /usr/local/bin/docker run --rm -e DOCKER_HOST -v /mnt/cache/:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL scan:latest
    env:
      DOCKER_REGISTRY: privateregister.domain.foo
      DOCKER_NAMESPACE: custom-namespace
      DOCKER_TAG: image:latest
      PLUGIN_DAEMON_OFF: true
      DOCKER_HOST: tcp://dind:2375
    envFrom:
    - sourceName: {{custom-pipeline-secret-registry}}
      sourceKey: username
      targetKey: DOCKER_USERNAME
    - sourceName: {{custom-pipeline-secret-registry}}
      sourceKey: password
      targetKey: DOCKER_PASSWORD
```

**Important:**
* Disable daemon start - PLUGIN_DAEMON_OFF: true
* Add DOCKER_HOST with the hostname of the dind pod - DOCKER_HOST: tcp://dind:2375
* Add secret to connect with the registry to import images if needed.
* If as the example the image need use docker, use -e DOCKER_HOST too.

Example:

![image](https://user-images.githubusercontent.com/2712200/85006889-05764a00-b15b-11ea-8a4c-f3efadf1c5a3.png)
