### ISSUE TITLE
Rancher support schedule cluster shutdown

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#27676]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement/feature

Rancher support schedule cluster shutdown.

Rancher is central management tools for one or more clusters. There is cost saving to shut down cluster at night. 
In AWS, it could be done via lambda function. However, Rancher master is not aware of cluster shutdown intentionally and wasting resources to check cluster status.
Moreover, I believe trouble may come when auto-healing enabled in Rancher.

**Comment by panho66** [comment]
I have Rancher master managed 15+ clusters and having 10+ shutdown for 8 hrs. Rancher memory usage increases and eventually crashed.

![image](https://user-images.githubusercontent.com/15118220/87912498-d5e79400-cab0-11ea-85cc-0a25094a767d.png)

rancher logs

ation.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:45.844139 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Job: Get https://10.97.34.171:6443/apis/batch/v1/jobs?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:45.848590 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ConfigMap: Get https://10.97.34.171:6443/api/v1/configmaps?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.062477 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Node: Get https://10.97.34.171:6443/api/v1/nodes?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.065242 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.RoleBinding: Get https://10.97.5.218:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.065433 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Endpoints: Get https://10.97.5.218:6443/api/v1/endpoints?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.066327 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRoleBinding: Get https://10.97.5.218:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.071851 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.97.5.218:6443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.075876 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ClusterRole: Get https://10.97.5.218:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.078798 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Role: Get https://10.97.5.218:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.111349 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.ReplicaSet: Get https://10.97.34.171:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.214136 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1beta1.CronJob: Get https://10.97.34.171:6443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.215438 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.APIService: Get https://10.97.5.218:6443/apis/apiregistration.k8s.io/v1/apiservices?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.221531 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Namespace: Get https://10.97.5.218:6443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.229186 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1beta1.Ingress: Get https://10.97.34.171:6443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.232462 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Secret: Get https://10.97.34.171:6443/api/v1/secrets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.331678 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.DaemonSet: Get https://10.97.34.171:6443/apis/apps/v1/daemonsets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.347656 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Event: Get https://10.97.34.171:6443/api/v1/events?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.367393 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.NetworkPolicy: Get https://10.97.34.171:6443/apis/networking.k8s.io/v1/networkpolicies?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.387664 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Deployment: Get https://10.97.34.171:6443/apis/apps/v1/deployments?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.443929 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.StatefulSet: Get https://10.97.34.171:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.553774 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.LimitRange: Get https://10.97.34.171:6443/api/v1/limitranges?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect
E0720 07:46:46.556375 8 reflector.go:123] github.com/rancher/norman/controller/generic_controller.go:175: Failed to list *v1.Service: Get https://10.97.34.171:6443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: waiting for cluster agent to connect

**Comment by Rancheroo** [comment]
The CPU will also consume whatever is available in this process.

This is problematic when a few clusters are powered down and it impact Ranchers ability to manage the remaining clusters. I would expect this to behave in the manner that the crash-loop back-off works, 
initially trying aggressively to find the missing cluster;
then throttling the efforts back over a period of time, each attempt incurring a time penalty. This penalty can top out at a ceiling i.e ( liveliness check every 15 minutes or something that)

Is this expected behavior, by design or something else altogether? (Should we be removing the cluster altogether overnight and spinning up a new one)

**Comment by paynejacob** [comment]
I tested this on rancher v2.5.8 in an HA configuration and was unable to reproduce the memory issue.

Steps taken
1. created an rke cluster with 3 vms with 4 cores and 8gb of ram.
2. installed the rancher helm chart with 3 replicas
3. Installed rancher monitoring
4. imported a k3s cluster and waited for the agent to be initialized and the cluster show as healthy in the rancher dashboard
5. repeat step 4 10 times
6. shutdown the k3s cluster and observed the dashboard show an unhealthy status
7. I let the setup sit over the weekend

The attached graph show the recorded memory usage of the 3 rancher pods and the memory usage of the nodes they were running on. All three rancher pods also have an uptime greater than 2 days  indicated there were no restarts.

![node_memory](https://user-images.githubusercontent.com/12258347/124177734-77b78500-da65-11eb-9e23-215bca94107e.png)
![pod_memory](https://user-images.githubusercontent.com/12258347/124177735-77b78500-da65-11eb-8171-06db801c99a0.png)

**Comment by laptua** [comment]
@paynejacob @Rancheroo  
I believe this ticket was related to https://github.com/rancher/rancher/issues/31712. The root causes is generate_service_certificate = true. I am not sure the contribution of shutdown downstream cluster.

I have downstream cluster of 21 worker nodes and 3 etcd/controlplane nodes. Cluster enable CIS hardening RKE-CIS-1.5 Hardened. That require generate_service_certificate = true

**The cluster yum file snapshot:**

```
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 6
        retention: 36
        s3_backup_config:
          bucket_name: middleware-rancher-dev-green
          endpoint: s3.ap-southeast-2.amazonaws.com
          folder: snapshot_cluster_dbr1-devgreen
          region: ap-southeast-2
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 52034
      retention: 72h
      snapshot: false
      uid: 52034
    kube-api:
      always_pull_images: false
      audit_log:
        enabled: true
      event_rate_limit:
        enabled: true
      pod_security_policy: true
      secrets_encryption_config:
        enabled: true
      service_node_port_range: 30000-32767
    kube-controller:
      extra_args:
        cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
        cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
        feature-gates: RotateKubeletServerCertificate=true
        terminated-pod-gc-threshold: '1000'
      extra_binds:
        - '/etc/localtime:/etc/localtime'
    kubelet:
      extra_args:
        anonymous-auth: 'false'
        event-qps: '0'
        feature-gates: RotateKubeletServerCertificate=true
        kubelet-cgroups: /systemd/system.slice
        make-iptables-util-chains: 'true'
        protect-kernel-defaults: 'true'
        runtime-cgroups: /systemd/system.slice
        streaming-connection-idle-timeout: 1800s
        tls-cipher-suites: >-
          TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
      fail_swap_on: true
      generate_serving_certificate: true
```

**At the kubelet section when generate_serving_certificate set to true around 22:00**

**5 mins average**
<img width="1691" alt="Screen Shot 2021-07-02 at 9 26 06 am" src="https://user-images.githubusercontent.com/85211269/124199958-89f1fb80-db17-11eb-9fa0-b1547c91f060.png">

**1 mins average (turn on additional EC2 monitoring at the same time setting generate_serving_certificate to true**

<img width="1691" alt="Screen Shot 2021-07-02 at 9 27 50 am" src="https://user-images.githubusercontent.com/85211269/124200067-c7568900-db17-11eb-9bd9-3be5e3f70186.png">

**The Grafana for one EC2 node with highest CPU**
<img width="1738" alt="Screen Shot 2021-07-02 at 9 31 32 am" src="https://user-images.githubusercontent.com/85211269/124200285-4c41a280-db18-11eb-9d01-7818d474419e.png">


**Environment specs**

- RHEL 7.9
- Docker 1.13.1
- K8s
- local v1.18.16
- downstream v1.18.17
