### ISSUE TITLE
User is not able to set security groups for EKS cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27709]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add catalog - `https://github.com/rmweir/system-charts`
- Branch - add-eks-controller; commit id: `c6651c4`
- Deploy `rancher-eks-controller` from this catalog.
- Deploy an eks cluster using kubectl apply -f cluster.yaml where is something like cluster.yaml

```
apiVersion: ke.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: sowmya-2
spec:
  kubernetesVersion: "1.14"
  privateAccess: true
  publicAccess: true
  cloudCredential: ""
  displayName: "sowmya-2"
  region: "us-east-2"
  loggingTypes: []
  tags:
    "test" : "one"
  securityGroups: [<sg-1>]
  nodeGroups:
  - nodegroupName: "sowmya-2-ng"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 1
    minSize: 1
```
- Cluster is created.
- The security group set - `sg-1`  is NOT seen set on the cluster

**Actual Result:**
User should be able to set security groups  for EKS cluster

**Expected Result:**
Security group set is NOT reflected on the cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `master-3244-head`
- Installation option (single install/HA): HA
