### ISSUE TITLE
deleting eks cluster through kubectl delete ekscc does not delete the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27707]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Add catalog - `https://github.com/rmweir/system-charts`
- Branch - add-eks-controller; commit id: `c6651c4`
- Deploy `rancher-eks-controller` from this catalog.
- Deploy an eks cluster using kubectl apply -f cluster.yaml where is something like cluster.yaml

```
apiVersion: ke.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: sowmya-2
spec:
  kubernetesVersion: "1.14"
  privateAccess: true
  publicAccess: true
  cloudCredential: ""
  displayName: "sowmya-2"
  region: "us-east-2"
  loggingTypes: []
  tags:
    "test" : "one"
  nodeGroups:
  - nodegroupName: "sowmya-2-ng"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 1
    minSize: 1
```
- create a couple of similar EKS clusters.
- delete a cluster using kubectl using `kubectl delete ekscc <name>`

**Actual Result:**
The cluster is not deleted. command line hung for sometime. 

**Expected Result:**
The cluster should get deleted

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - `master-3244-head`
- Installation option (single install/HA): HA
