### ISSUE TITLE
systems pods being scheduled on dead nodes

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#27734]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Power off a worker running a system pod like core-dns, metrics, cattle-cluster-agent. (Do not shutdown node but hard power it off)
- Delete the pod from the node `kubectl delete pod`

**Result:**
- The node will go into NotReady,SchedulingDisabled
- The pods running on that node will not get rescheduled on a new node
- After deleting the pods, the replacement pods will most likely be scheduled on the dead node

**Other details that may be helpful:**
This is part of the upstream issue https://github.com/kubernetes/kubernetes/issues/55713

**Workaround:**
- Option A: kubectl delete node
- Option B: Add the following tolerations to system pods then delete the pods to force a reschedule.
```
spec:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30
```
- Option C: Add the following podAntiAffinity rule to force the pods to be scheduled on a new node.
```
       spec:
         affinity:
           podAntiAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - cattle-cluster-agent
               topologyKey: kubernetes.io/hostname
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): v1.15.11

gz#10871

**Comment by sadiapoddar** [comment]
reproduced the issue.
steps to repro
1. created 3 nodes cluster( 2 worker nodes and 1 all role enabled)
2. Created a bunch of workloads and made sure workloads are up and running on all worker nodes
3. Powered off one of the worker nodes.
4. Tried to delete the pods node using kubectl, but getting an error that server
sadia-3 node is powered off state
<img width="1353" alt="Screen Shot 2020-11-06 at 2 14 08 PM" src="https://user-images.githubusercontent.com/72409237/98419988-0db42080-203b-11eb-9876-053230a6d4ca.png">
 node

From pod schedule UI, note that workload is still scheduled on this powered off node, sadia-3.
<img width="956" alt="Screen Shot 2020-11-06 at 2 24 18 PM" src="https://user-images.githubusercontent.com/72409237/98420444-0fcaaf00-203c-11eb-82d9-1fcb5f8b4f71.png">

In dashboard, it's showing node is not available
<img width="1562" alt="Screen Shot 2020-11-06 at 2 14 43 PM" src="https://user-images.githubusercontent.com/72409237/98420122-52d85280-203b-11eb-8778-3af3f572543b.png">

**Comment by sadiapoddar** [comment]
Reproduced this issue with rancher2.4.3
Steps.
1. Created custom clusters of four nodes( 1 (etcd+cntrl) + 3 workers)
2. Powered off one of the worker nodes
3. Notices that states all the workload running on that worker node went to updating state. But that the state of workload remained stuck in 'updating' status forever.

<img width="1599" alt="Screen Shot 2020-11-11 at 12 17 25 PM" src="https://user-images.githubusercontent.com/72409237/98861701-94da0d80-241a-11eb-93ef-911c4000a1b1.png">

4. Deleted one of the system pods, matrics-server was running on the powered-off node, Immediately it spawned the pod with unknow status on the same node which is powered off

<img width="1593" alt="Screen Shot 2020-11-11 at 12 10 04 PM" src="https://user-images.githubusercontent.com/72409237/98861976-fef2b280-241a-11eb-92a6-e930d1bbf79a.png">

5. The workload running on that pod also remained scheduled on the powered off node. 
<img width="1575" alt="Screen Shot 2020-11-11 at 12 09 24 PM" src="https://user-images.githubusercontent.com/72409237/98862142-48430200-241b-11eb-8aa1-e8b9836b67fb.png">

Expected behavior:  The deleted pod needs to spawn on a running worker node.

**Comment by sadiapoddar** [comment]
@superseb 
I verified the fix and here is the summary of what we are seeing with the fix.
Steps.

1. Created custom clusters of four nodes( 1 (etcd+cntrl) + 3 workers)
2. Powered off one of the worker nodes
3.Notices that states all the workload running on that worker node went to updating state.
4. Waited a few hours to see if that all the system workloads were running on the powered-off node get created automatically on the other worker nodes.  But that the state of workload remained stuck in 'updating' status forever
<img width="1642" alt="101231443-26c2e800-3660-11eb-8d91-e4ab7b16f1aa" src="https://user-images.githubusercontent.com/72409237/101231791-73a7be00-3662-11eb-8c36-2390acadcb79.png">

5. After a few hours later I deleted the coredns workload from the powered off the node, then I noticed  a new coredns wl was  created on one of the available worker nodes and the update status went from updating to green 
<img width="1397" alt="Screen Shot 2020-12-04 at 6 15 43 PM" src="https://user-images.githubusercontent.com/72409237/101231851-c97c6600-3662-11eb-9137-ef4a52b3d97b.png">

**Summery:** 
So, I am not seeing pods are getting recreated automatically on the available worker nodes until users go delete the pods manually from the powered-off node. 

I am reopening the bug, but if this is the behavior we have implemented to resolve the issue please let me know and we can close the bug.

**Comment by superseb** [comment]
@sadiapoddar This needs additional configuration as we didn't want to break existing behavior causing people that are unaware of the changes having to deal with system pods getting unscheduled. You will need to configure tolerations on the addons to override the existing behavior. Basically seeing the same behavior in this version is expected because we don't want to break existing behavior.

To test overriding tolerations, you can configure them like follows:

```
monitoring:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
ingress:
  provider: nginx
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
network:
  plugin: calico
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
```

This only applies to Deployment resources as DaemonSet resources are a special thing and don't benefit from having these.

**Comment by sadiapoddar** [comment]
@superseb 
So, basically, we need to change the toleration of the monitoring, ingress, and network workloads. 
Do I edit the YAML file of these workloads on each of the worker nodes in the cluster? or there is a central way to apply this tolerance to all the deployment sets at once.

**Comment by superseb** [comment]
No, it is configurable per add-on

**Comment by adampl** [comment]
This might be relate to a **k8s 1.19 bug** that removes the `NoExecute` taint from unavailable nodes: https://github.com/kubernetes/kubernetes/issues/94183

**Comment by sadiapoddar** [comment]
@superseb 
Verified the fix 2.5-head, commit b2953cb and
master-head commit ff16903. The fix looks good.

steps 
1. Added the add-ons for tolerations and created a rke cluster 
Sample cluster.ymal file
```
nodes:
  - address: xx
    internal_address: xx
    role: [controlplane, etcd]
    user: ubuntu
    ssh_key_path: ~/xx.pem
 ......
 ......

monitoring:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
ingress:
  provider: nginx
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
network:
  plugin: calico
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15

```

2. >rke up
3. Brought the rke cluster as an existing cluster
4. Powered off a worker node where coredns system pod was running 
5. The "coredns" system pod which was running on the powered-off node, was not automatically rescheduling on the other available worker nodes. UI is showing "updating" the workload and stuck that way.

<img width="735" alt="Screen Shot 2020-12-08 at 12 35 11 PM" src="https://user-images.githubusercontent.com/72409237/101538449-f9bd5080-3951-11eb-84be-f2ed21b09e87.png">
<img width="885" alt="Screen Shot 2020-12-08 at 12 35 26 PM" src="https://user-images.githubusercontent.com/72409237/101538737-68021300-3952-11eb-9da0-9a5fea077487.png">

**Comment by sadiapoddar** [comment]
@superseb 
With the fix,  if users add tolerations as add-ons, can users expect that the system pods which were running on the powered off the node, will automatically be recreated on the other available worker node?

**Comment by sadiapoddar** [comment]
Created a custom cluster using the following add-ons with some toleration values.
Not seeing the coredns system pod that was running on the powered-off worker node was
 -- automatically getting recreated on other available worker nodes. 

`provider: coredns
    reversecidrs: null
    stubdomains: null
    tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        toleration_seconds: 15`
I kept the setup for @superseb to debug the issue. 
Reopening the bug

**Comment by sadiapoddar** [comment]
Tested the fix on k8s 1.18.12 cluster and
The fix is working k8s 1.18.12 cluster for coredns with add-ons for toleration.

1 Created a custom cluster using the following add-ons with some toleration values.

`provider: coredns reversecidrs: null stubdomains: null tolerations: - effect: NoExecute key: node.kubernetes.io/unreachable operator: Exists toleration_seconds: 15`

2. Powered off the worker node where codedns system pod was running
3. Seeing the coredns system pod that was running on the powered-off worker node was
-- automatically got recreated on other available worker nodes.

<img width="855" alt="Screen Shot 2020-12-08 at 5 04 49 PM" src="https://user-images.githubusercontent.com/72409237/101560217-9e05be00-3977-11eb-8186-d867d048bfce.png">

Looks like the issue is in k8s 1.19, kubernetes/kubernetes#94183

@superseb thanks for fixing the issue.

**Comment by xibuka** [comment]
Still experiencing this issue in Rancher v2.5.6 + k8s v1.18.17.
I deployed the cluster with an infra provider, and no `toleration_seconds` was added to coreDNS pod by default. 
So it still can't be rescheduled to an active node even the node is NotReady.

See https://github.com/rancher/rancher/issues/24939#issuecomment-810605814

**Comment by annablender** [comment]
@Jono-SUSE-Rancher @superseb For the above linked issue #24939 where the coredns autoscaler pod was not getting rescheduled, Izaac validated it was fixed on 2.5.7. Node was not rescheduled on the imported RKE cluster with k8s version 1.19.8 because of this bug https://github.com/rancher/rancher/issues/27734#issuecomment-740647655 that removed `NoExecute` taints from unavailable nodes. Because the taint was removed, the tolerations were never hit and node was never rescheduled. We have now upgraded to k8s 1.19.9. This needs to be revalidated on 2.6.

**Comment by Jono-SUSE-Rancher** [comment]
@sowmyav27 - Could you work with a QA resource to help validate this on 2.6x and we can confirm that it is good to go?

**Comment by sowmyav27** [comment]
@rishabhmsra Pls validate this on latest 2.6-head by following [these](https://github.com/rancher/rancher/issues/27734#issuecomment-741371451) but testing on latest 1.19 k8s version.

**Comment by rishabhmsra** [comment]
**Re-opening this issue**

**Rancher Server:**
- Version : v2.6-head(6352861)
- docker install

**Validation steps followed:**
- Provisioned a k8s `v1.19.16-rancher1-3` custom cluster on AWS (`3 etcd, 2 cp, 3 worker nodes`) by adding below toleration values:
```
  dns:
    provider: coredns
    tolerations:
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      toleration_seconds: 15
```
- Powered off the worker node where coredns system pod was running.
- coredns pod running on the powered-off worker node got scheduled on another worker node. But the previous pod got stuck into `Terminating` state

![ss-coredns](https://user-images.githubusercontent.com/36376154/155725070-a495288b-71ce-4bf9-974b-494f8661b662.png)
