### ISSUE TITLE
Creating a namespace via kubectl will not set Container Default Resource Limit, creating a pod fails due to quota

### ISSUE THREAD

**Issue by 5nafu** [rancher/rancher#27750]
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
* Create a project in the Rancher UI with Resource Quotas and Container Default Resource Limits set (note the ProjectID)
* Create a new namespace via kubectl with the projectID annotation:
  ```
  apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      field.cattle.io/projectId: c-jrlpt:p-tjnls
    labels:
      field.cattle.io/projectId: p-tjnls
    name: test-namespace
  ```
* try to create a pod in the namespace:
  ```
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: debug
  spec:
    containers:
    - name: count
      image: busybox:1.28
      args: [/bin/sh, -c, 'while true; do echo "Wait ..."; sleep 1; done']
  ```

**Result:**
* A new namespace is created with the `Namespace Default Limit`s from the project, but without `Container Default Resource Limit`:
  ```
  apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      cattle.io/status: '{[...]}'
      field.cattle.io/projectId: c-jrlpt:p-tjnls
      field.cattle.io/resourceQuota: '{"limit":{"persistentVolumeClaims":"40","requestsStorage":"4Ti","limitsCpu":"64","limitsMemory":"128Gi"}}'
      kubectl.kubernetes.io/last-applied-configuration: |
        [...]
      lifecycle.cattle.io/create.namespace-auth: "true"
    creationTimestamp: "2020-06-26T14:46:45Z"
  [...]
  ```
  I would expect to find the annotation `field.cattle.io/containerDefaultResourceLimit` in the newly created namespace.

* The pod creation is rejected because the quota failed:
  ```
  Error from server (Forbidden): error when creating "pod.yaml": pods "debug" is forbidden: failed quota: default-2vpng: must specify limits.cpu,limits.memory
  ```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 24 Cores 126GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 19.3.6

gz#10910

SURE-3480

**Comment by MKlimuszka** [comment]
Reopening.

**Comment by maxsokolovsky** [comment]
Tried to reproduce in `v2.5.11`.
Reproduced only the first half. The new `test-namespace` created in kubectl does not inherit the Container Default Resource Limits, which it should.
But the created pod in this namespace starts up and runs fine, without any errors.

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause
When receiving a request to create a new namespace in a project via kubectl (bypassing the UI), Rancher wasn't checking the project's default limits explicitly. As a result, a project's limits would not be propagated to the new namespace.
When a request is sent via UI, the UI sets the appropriate annotation, and Rancher uses it to pass the limits found in the annotation to the new namespace.

### What was fixed, or what changes have occurred
Creating a namespace via kubectl directly usually does not include that annotation, so Rancher now explicitly checks if the parent project defines any container default limits and, if yes, passes them to the new namespace.

### Areas or cases that should be tested
- Create a namespace in the UI
- Create a nemsapce via kubectl
### What areas could experience regressions?

### Steps
1. Create a new project, specify container default limits. For example, 100m CPU and 128Mi memory.
2. In the UI, Create a new namespace belonging to the project and do not override container limits.
3. Verify that the namespace has received the limits from the project (its Limit Range is defined) - the output at the bottom of `kubectl describe ns ns1`.
4. Now create another namespace but use kubectl. First, obtain your project ID in the YAML. Also, get your cluster ID, if it's not local. Your values will look different, but here is an example manifest:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:p-n9r8c
  labels:
    field.cattle.io/projectId: p-n9r8c
  name: ns2
```
5. Verify that the namespace has the same limits defined as those specified in the project - the output at the bottom of `kubectl describe ns ns2`.

**Comment by brudnak** [comment]
# My checks PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3                                  |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | N/A                                     |
| Downstream K8s version  | N/A                                     |
| Browser type            | Google Chrome                           |
| Browser version         | 98.0.4758.102 (Official Build) (x86_64) |

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `local` -> `Projects/Namespaces` -> `Create Project` -> then fill out the project creation form
    - Name: `mytestproject`
    - Click -> `Container Default Resource Limit`
    - CPU Reservation: `1000`
    - CPU Limit: `1000`
    - Memory Reservation: `512`
    - Memory Limit: `512`
    - Click -> `Create` -> redirected back to the `Projects/Namespaces` page
3. Click `Create Namespace` at the row of the newly created project `mytestproject` -> fill out the creation form
    - Namespace name: `testns`
    - Click -> `Create` (leaving all other fields besides name empty) -> redirected back to the `Projects/Namespaces` page
4. Examine the namespace with the following commands

```shell
kubectl get namespace
kubectl describe namespace testns

```

5. In reproduction the resource limits aren't inherited. See issue [https://github.com/rancher/rancher/issues/18877](https://github.com/rancher/rancher/issues/18877)

6. Create a namespace using `kubectl` and bypass the UI
    - Click `Kubectl Shell`
    - Run the following commands

```shell
touch namespace.yaml
vi namespace.yaml
```

then paste the following into Vi

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:YOUR_PROJECT_ID/NAME
  labels:
    field.cattle.io/projectId: YOUR_PROJECT_ID/NAME
  name: NAME_OF_NAMESPACE_YOU_WANT
```

7. Run this command to create the namespace based on the yaml file

```shell
kubectl create -f namespace.yaml
```

8. Check the resource limit set on the newly created namespace

```shell
kubectl describe namespace YOUR_NAMESPACE
```

### Result

The limit isn't inherited in v2.6.3 when done via the UI or kubectl. See [https://github.com/rancher/rancher/issues/18877](https://github.com/rancher/rancher/issues/18877)
  
## Additional Info

  
<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-e55a04c1915c62bbc23ee1e5db70208ce2a11679-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | N/A                                                |
| Downstream K8s version  | N/A                                                |
| Browser type            | Google Chrome                                      |
| Browser version         | 98.0.4758.102 (Official Build) (x86_64)            |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `hamburger menu` -> `local` -> `Projects/Namespaces` -> `Create Project` -> then fill out the project creation form
    - Name: `mytestproject`
    - Click -> `Container Default Resource Limit`
    - CPU Reservation: `1000`
    - CPU Limit: `1000`
    - Memory Reservation: `512`
    - Memory Limit: `512`
    - Click -> `Create` -> redirected back to the `Projects/Namespaces` page
3. Click `Create Namespace` at the row of the newly created project `mytestproject` -> fill out the creation form
    - Namespace name: `testns`
    - Click -> `Create` (leaving all other fields besides name empty) -> redirected back to the `Projects/Namespaces` page
4. Examine the namespace with the following commands

```shell
kubectl get namespace
kubectl describe namespace testns
```

5. Create a namespace using `kubectl` and bypass the UI
    - Click `Kubectl Shell`
    - Run the following commands

```shell
touch namespace.yaml
vi namespace.yaml
```

then paste the following into Vi

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:YOUR_PROJECT_ID/NAME
  labels:
    field.cattle.io/projectId: YOUR_PROJECT_ID/NAME
  name: NAME_OF_NAMESPACE_YOU_WANT
```

6. Run this command to create the namespace based on the yaml file

```shell
kubectl create -f namespace.yaml
```

7. Check the resource limit set on the newly created namespace

```shell
kubectl describe namespace YOUR_NAMESPACE
```

### RESULT

Checks successful! When creating a namespace within a project that has container limits they are inherited now.
