### ISSUE TITLE
Feature Request: expose VPC field for DigitalOcean node templates

### ISSUE THREAD

**Issue by ASwingler** [rancher/rancher#27776]
Rancher 2.4.5 has no mechanism to instruct DigitalOcean to create droplets in a particular VPC. They are all created in the default VPC.
The DO API includes a droplet-creation parameter vpc_uuid where a UID for an existing VPC can be input. Please expose this field. 

Ideally a list of VPCs would be available as a dropdown but an input field for a user-designated UID would work as a quick-fix.

**Comment by GurjinderSingh** [comment]
I have submitted changes to docker/machine [Adding Virtual Private Cloud](https://github.com/docker/machine/pull/4867). I hope it is working and approved soon. 

Rancher required the following changes will try to play with it once approved from other side.

**Disclaimer**: These changes are not working right now as we need to change the docker/machine backend.

/dashboard/c/local/explorer/management.cattle.io.dynamicschema/digitaloceanconfig?mode=edit&as=yaml

```
    vpc_uuid:
      create: true
      default:
        boolValue: false
        intValue: 0
        stringSliceValue: null
        stringValue: ""
      description: VPC network UUID. Get by querying api
      type: string
      update: true
```
/n/node-templates


`,"vpc_uuid": "weed-so-high-to-the-moon"`



**other UI Changes required**

 dashboard/edit/node-config.cattle.io.digitaloceanconfig.vue 



**useful links**

https://developers.digitalocean.com/documentation/v2/#droplets

https://developers.digitalocean.com/documentation/v2/#vpcs



The best solution fetch the VPC network list from DO and provide a dropdown  🚀 


`curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer b7d03a6947b217efb6f3ec3bd3504582" "https://api.digitalocean.com/v2/vpcs"`
