### ISSUE TITLE
cni error when using openstack cloud_provider and extra_binds option

### ISSUE THREAD

**Issue by lperrin-obs** [rancher/rancher#27785]
Issue seems to be related to #26880

**What kind of request is this (question/bug/enhancement/feature request):** 
bug

**Steps to reproduce (least amount of steps as possible):**
1. create a cluster on openstack node with openstack provider, using `extra_binds` option to provide internal CA to the kubelet containers, but with no `cloud_provider` configured: 
```
# 
# Cluster Config
# 
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: rancher-test
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  dns:
    provider: coredns
    upstreamnameservers:
      - 10.36.200.1
      - 10.36.200.2
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.17.6-rancher2-2
  monitoring:
    provider: metrics-server
    replicas: 1
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  restore:
    restore: false
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
      extra_binds:
        - "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates"
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
      extra_binds:
        - "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates"
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: 'false'
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      override_benchmark_version: rke-cis-1.4
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```
2. The cluster is correctly deployed and worker nodes can be added. Add a `cloud_provider` configuration to the cluster:
```
rancher_kubernetes_engine_config:
....
  cloud_provider:
    name: openstack
    openstackCloudProvider:
      global:
        username: MMMM5064
        password: PASSWORD
        auth-url: https://api-openstack:5000/v3
        tenant-id: 42f1239d024641388654d5a16038e509
        domain-name: ad-subs
        ca-file: /usr/local/share/ca-certificates/CA-root.crt
      load_balancer:
        use-octavia: true
        subnet-id: 640f9933-6404-4913-b9b8-0421c7322e4c
      block_storage:
        ignore-volume-az: true
...
```
3. add a worker node
New node stays a at unavailable status, with this error message : ` Runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized `

Kubelet logs:
```
W0630 14:26:12.844873   13990 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0630 14:26:15.994177   13990 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0630 14:26:17.845260   13990 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W0630 14:26:19.133897   13990 setters.go:158] adding overridden hostname of worker3 to cloudprovider-reported addresses
E0630 14:26:21.001771   13990 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0630 14:26:22.845710   13990 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
E0630 14:26:26.008869   13990 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0630 14:26:27.846005   13990 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
W0630 14:26:29.154433   13990 setters.go:158] adding overridden hostname of worker3 to cloudprovider-reported addresses
E0630 14:26:31.017746   13990 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

On worker node, the `/etc/cni` directory is emtpy. 

**Result:**
Worker node cannot be deployed.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, 2vCPU, 4Go RAM
- Kubernetes version (use `kubectl version`): 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
