### ISSUE TITLE
Using a linked container hostname in the CMD

### ISSUE THREAD

**Issue by amalagaura** [rancher/rancher#2782]
We have a docker compose which has a hostname on the command line. It works in a regular docker-compose, but is failing in rancher because the hostname is not available. Presumably because DNS is added after the command is run? When exactly does DNS become available to the host. Here is the relevant parts of the docker-compose.

```
---
  postgres: 
    image: postgres:9.4
    environment:
      - LC_ALL=C.UTF-8
  example:
    links:
      - postgres
    command: ping postgres
```

So the command fails with the following error: `ping: cannot resolve postgres: Unknown host`

However if I leave out the command, let the container start and then execute a shell to `ping postgres` it succeeds. So after the DNS is available everything is fine, but how do I start this service. Even if this hostname information need to go into a file or environment variable, won't it have the same problem?
