### ISSUE TITLE
Invalid virtualNetwork in the cluster config file does not throw an error

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27844]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy eks-controller in the HA setup
- Create a cluster using the cluster file:

```
apiVersion: ke.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: sowmya-4
spec:
  kubernetesVersion: "1.14"
  privateAccess: true
  publicAccess: true
  publicAccessSources: ["0.0.0.0/0"]
  cloudCredential: "cc-sv2dv"
  displayName: "sowmya-4"
  region: "us-east-2"
securityGroups: ["<>"]
subnets: ["<>", "<>"]
virtualNetwork: "vpc-abc"
nodeGroups:
  - nodegroupName: "sowmya-4-ng"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 3
    minSize: 1
    diskSize: 15
```
- The cluster comes up successfully and the VPC on the cluster is a different one (one linked to the subnets/security groups)

**Other details that may be helpful:**
As per conversation with @rmweir the field `virtualNetwork` field will be removed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head `ec1ea7a99` using charts: `https://github.com/rmweir/system-charts` and branch - `add-eks-controller`
- Installation option (single install/HA): single
