### ISSUE TITLE
EKS cluster throws an error when the AWS credentials are changed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#27840]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy eks-controller in the HA setup
- Create a cluster using the cluster file:
```
apiVersion: ke.cattle.io/v1
kind: EKSClusterConfig
metadata:
  name: sowmya-5
spec:
  kubernetesVersion: "1.14"
  privateAccess: true
  publicAccess: true
  cloudCredential: "cc-sv2dv"
  displayName: "sowmya-4"
  region: "us-east-2"
  loggingTypes: ["audit","scheduler","authenticator", "controllerManager", "api"]
  virtualNetwork: "<>"
  serviceRole: "<>"
  subnets: ["<>"]
  securityGroups: ["<>"]
  tags:
    "test" : "one"
    "test" : "two"
  nodeGroups:
  - nodegroupName: "sowmya-5-ng"
    instanceType: "t3.medium"
    desiredSize: 1
    maxSize: 3
    minSize: 1
    diskSize: 15
    gpu: false
    labels:
      "one" : "test"
    tags:
      "test" : "one"
      "test" : "two"
    sourceSecurityGroups: [<>]
    subnets: [<>]
    version: "1.14"
    ec2SshKey: "<>"
```
- Create a cluster usiing kubectl apply -f cluster.yaml
- Cluster gets created. --> Check in the EKS console in amazon EKS.
- Delete the access keys in AWS console. 
- Update cluster, delete a nodeGroup
- Error seen in the logs: `kubectl logs eks-config-controller-dd9d9f659-zd4vc -n cattle-system`
```
E0706 19:55:39.488089       1 controller.go:166] error syncing 'default/sowmya-5': handler eks-controller: UnrecognizedClientException: 
	status code: 403, request id: da782578-2961-4752-a224-45d50b91dbd7, requeuing
E0706 19:55:39.503439       1 controller.go:166] error syncing 'default/sowmya-5': handler eks-controller: UnrecognizedClientException: 
	status code: 403, request id: 917dd889-64f7-47b6-bc3e-8f7981addee6, requeuing
```

**Expected Result:**
An error should be shown saying the credentials are invalid/Unauthorized error.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head latest - `ec1ea7a99` using charts: `https://github.com/rmweir/system-charts` and branch - `add-eks-controller`
- Installation option (single install/HA): HA
