### ISSUE TITLE
Rancher is unable to connect to dualstack provisioned vSphere nodes

### ISSUE THREAD

**Issue by PhilipSchmid** [rancher/rancher#27876]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create node template with vApp properties enabled (sorry for the bad screenshots - there seems to be a Rancher UI bug when using too long cloud-config lines ;-), therefore I had to make two separate one):
![vapp-keys](https://user-images.githubusercontent.com/5549063/87066755-5f76a680-c213-11ea-8604-3298a71dffcd.png)
![vapp-values](https://user-images.githubusercontent.com/5549063/87066823-7b7a4800-c213-11ea-8dfb-fed8eb5094d4.png)

2. Create a custom cluster with the following vSphere settings:
```yaml
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
      virtual_center:
        10.10.10.10:
          # Use the "user@domain" syntax to workaround https://github.com/rancher/rancher/issues/16371
          user: rancher@vsphere.local
          password: ------secret------
          port: 443
          datacenters: /1234
      workspace:
        server: 10.10.10.10
        folder: /1234/vm/Lab/K8s/storage
        default-datastore: /1234/datastore/ISCSI-SAN-1
        datacenter: /1234
        resourcepool-path: RP-K8s
```

3. Wait for Rancher to deploy the VMs.
4. The VMs getting created and the vApp options (e.g. the fixed IP from the vCenter network protocol pool) properly assigned.

**Result:**
Rancher always tries to connect to the IPv6 address (EUI-64 via SLAAC) which isn't the same anymore after the cloud-init configuration was made and the node rebooted. Disabling IPv6 RAs on the gateway (`ipv6 nd suppress-ra` on the Cisco SVI) for this subnet does not work since rancher still takes the IPv6 address - only this time it's the link local (`FE80::`) one. This makes it even worse... An IPv6 link local address is never even reachable outside it's broadcast domain.

![issue](https://user-images.githubusercontent.com/5549063/87066715-4c63d680-c213-11ea-8b4c-2f24f95e8bd7.png)

**Other details that may be helpful:**

My cloud-init from the node template (already with some workarounds to try to delay the open-vm-tools startup):
```yaml
#cloud-config
users:
  - name: test
    shell: /bin/bash
    groups: wheel
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAA....
packages:
 - open-vm-tools
write_files:
  - path: /root/configure-netplan.sh
    content: |
        #!/bin/bash
        vmtoolsd --cmd 'info-get guestinfo.ovfEnv' > /tmp/ovfenv
        IPAddress=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.address" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        SubnetMask=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.ip.0.netmask" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        Gateway=$(sed -n 's/.*Property oe:key="guestinfo.interface.0.route.0.gateway" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        DNS=$(sed -n 's/.*Property oe:key="guestinfo.dns.servers" oe:value="\([^"]*\).*/\1/p' /tmp/ovfenv)
        
        cat > /etc/netplan/01-netcfg.yaml <<EOF
        network:
          version: 2
          renderer: networkd
          ethernets:
            ens192:
              addresses: 
                - $IPAddress/27
              gateway4: $Gateway
              dhcp6: no
              accept-ra: no
              nameservers:
                addresses : [$DNS]
        EOF
 
        sudo netplan apply
        sleep 30
        sudo systemctl start open-vm-tools
runcmd:
  - bash /root/configure-netplan.sh
bootcmd:
  - [ cloud-init-per, once, rmdefaultnetconf, rm, -f, /etc/netplan/50-cloud-init.yaml ]
  - [ cloud-init-per, once, tempstopvmtools, sudo, systemctl, stop, open-vm-tools ]
```

This cloud-init works and the VMs come up with the properly working network configuration made via vApp options.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.4.5
- Installation option (single install/HA): single install

Why does Rancher not simply only try to connect via IPv4 when in the vApp options `IPv4` is specified as IP protocol version? VMware vApp options aren't even able to configure IPv4 and IPv6 at the same time so it would be safe for Rancher to only take the IP address from the VMware tools with the correct IP version. As an alternative I could also imagine it would make sense to add an additional configuration option inside the Rancher node template menu to enforce Rancher to only connect with the chosen IP version to the provisioned nodes.

Thanks & regards,
Philip

**Edit**

Another possible solution would be that Rancher allows the separate configuration of the cloud-init network part as described here: https://cloudinit.readthedocs.io/en/latest/topics/network-config.html#disabling-network-configuration
Unfortunately it seems Rancher only supports the configuration of the `#cloud-config` part which gets written to `user-data` and inside `user-data`, network cloud-init configuration is not allowed:
`[...] User-data cannot change an instance’s network configuration. [...]` (see https://cloudinit.readthedocs.io/en/latest/topics/network-config.html#default-behavior)
