### ISSUE TITLE
kubectl delete svc kube-dns -n kube-system

### ISSUE THREAD

**Issue by sakufo** [rancher/rancher#27901]
*Describe your issue here*
I accidentally deleted corndns service:kube-dns. The service was recreated later, but the clusterIP has changed. Now that the POD is created, the nameserver in /etc/resolv.conf in the container is still the previous service:kube-dns IP.
How can I configure to use the latest kube-dns IP

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.5` UI: `v2.4.28` |
|Route|`undefined`|

**Comment by superseb** [comment]
How did you recreate it? It should be possible to recreate the Service as it was originally deployed and work without issues. This is the CoreDNS template with a variable for Cluster DNS (which defaults to `10.43.0.10`):

```
---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: {{.ClusterDNSServer}}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP
```
