### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#27964]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Description:**
Ability to set labels on CoreDNS pods from RKE template.  Example of how this might look:
```
dns:
    provider: coredns
    labels:
      app: dns
```

gz#11220
