### ISSUE TITLE
[CLI] --rke-config parameter not working

### ISSUE THREAD

**Issue by davidcorbin** [rancher/rancher#27982]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

rke-config.yaml
```
default_pod_security_policy_template_id: restricted
docker_root_dir: /apps/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: 'test'

rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  dns:
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
  ignore_docker_version: true

  ingress:
    provider: nginx
  kubernetes_version: v1.17.5-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1

  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  private_registries:
    - is_default: true
      url: harbor.davcor.co

  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: true
      service_node_port_range: 30000-32767
      secrets_encryption_config:
        enabled: true
      event_rate_limit:
        enabled: true
      audit_log:
        enabled: true
    scheduler:
      extra_args:
        profiling: "false"
        address: "127.0.0.1"
    kube-controller:
      extra_args:
        profiling: "false"
        address: "127.0.0.1"
        feature-gates: "RotateKubeletServerCertificate=true"
    kubelet:
      extra_args:
        authorization-mode: "Webhook"
        streaming-connection-idle-timeout: "1800s"
        protect-kernel-defaults: "true"
        make-iptables-util-chains: "true"
        event-qps: "0"
        anonymous-auth: "false"
        feature-gates: "RotateKubeletServerCertificate=true"
        tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: 'false'
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
windows_prefered_cluster: false
```

```bash
rancher cluster create test --rke-config rke-config.yaml
```

**Result:**
Default configuration is used when checking the Rancher web interface. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Comment by mwpower** [comment]
I've run into a similar issue, and one thing I found is that the yaml can only contain the section listed below "rancher_kubernetes_engine_config:", so it'd look like:
```
addon_job_timeout: 30
authentication:
  strategy: x509
dns:
  nodelocal:
    ip_address: ''
    node_selector: null
    update_strategy: {}
ignore_docker_version: true

ingress:
  provider: nginx
kubernetes_version: v1.17.5-rancher1-1
monitoring:
  provider: metrics-server
  replicas: 1

network:
  mtu: 0
  options:
    flannel_backend_type: vxlan
  plugin: canal
private_registries:
  - is_default: true
    url: harbor.davcor.co

services:
  etcd:
    backup_config:
      enabled: true
      interval_hours: 12
      retention: 6
      safe_timestamp: false
    creation: 12h
    extra_args:
      election-timeout: 5000
      heartbeat-interval: 500
    gid: 0
    retention: 72h
    snapshot: false
    uid: 0
  kube_api:
    always_pull_images: false
    pod_security_policy: true
    service_node_port_range: 30000-32767
    secrets_encryption_config:
      enabled: true
    event_rate_limit:
      enabled: true
    audit_log:
      enabled: true
  scheduler:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
  kube-controller:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
      feature-gates: "RotateKubeletServerCertificate=true"
  kubelet:
    extra_args:
      authorization-mode: "Webhook"
      streaming-connection-idle-timeout: "1800s"
      protect-kernel-defaults: "true"
      make-iptables-util-chains: "true"
      event-qps: "0"
      anonymous-auth: "false"
      feature-gates: "RotateKubeletServerCertificate=true"
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
```
That being said, I've also found that this doesn't always work how I would expect, and configuring everything in a new cluster from the CLI doesn't appear to be possible, but this might help you work through a part of your issue.
