### ISSUE TITLE
Unable to select a custom PSP as a cluster default

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#27996]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
- Create a custom cluster
- use an addon to add the following custom psp
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    kubernetes.io/cluster-service: "true"
  name: 101-privileged-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
```

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  name: 201-restricted-psp
spec:
  privileged: false
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
```

**Result:**
- Currently, the is no way to set a custom psp without defining it at the global level via the cluster option `defaultPodSecurityProjectTemplateId`
- You should be able to pass the yaml for a custom psp(s) and have a cluster option like `defaultPodSecurityProject`.
- The goal is that you could customize the default psp(s) at the cluster level using the cluster.yaml

**Other details that may be helpful:**
- eks supports setting a default psp https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html
- This also affects rke managed cluster (Rancher local cluster)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.6
- Installation option (single install/HA): HA
