### ISSUE TITLE
New stack stuck in 'Activating' state forever

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2806]
I've created a stack in one environment, which consists of a service with a load balancer over the top of it.  I then export this to the two YAML files.  Next I create a new Stack ( in a different environment ) and import the YAML files.

This results in an empty Stack that is stuck in 'Activating' state.

The API shows the following, which includes a transitioning error message (and you can see the source YAML for the test stack as well).

This happens even if the new stack has the same name as the old stack, but does not seem to happen with a sinple single-service-only stack.

{
    "id": "1e52",
    "type": "environment",
    "links": {
        "self": "…/v1/projects/1a191/environments/1e52",
        "account": "…/v1/projects/1a191/environments/1e52/account",
        "services": "…/v1/projects/1a191/environments/1e52/services",
        "composeConfig": "…/v1/projects/1a191/environments/1e52/composeconfig",
    },
    "actions": {
        "remove": "…/v1/projects/1a191/environments/1e52/?action=remove",
        "error": "…/v1/projects/1a191/environments/1e52/?action=error",
        "addoutputs": "…/v1/projects/1a191/environments/1e52/?action=addoutputs",
        "activateservices": "…/v1/projects/1a191/environments/1e52/?action=activateservices",
        "deactivateservices": "…/v1/projects/1a191/environments/1e52/?action=deactivateservices",
        "exportconfig": "…/v1/projects/1a191/environments/1e52/?action=exportconfig",
    },
    "name": "Minecraft",
    "state": "activating",
    "accountId": "1a191",
    "created": "2015-11-25T02:38:57Z",
    "createdTS": 1448419137000,
    "description": null,
    "dockerCompose": "Minecraft:\r\n  restart:\r\n    name: always\r\n  environment:\r\n    EULA: 'TRUE'\r\n  labels:\r\n    io.rancher.scheduler.affinity:host_label_soft_ne: lb=1\r\n    io.rancher.service.hash: 0ec1b94b7804cfb3b7349bc1e8a1fcd47a25927f\r\n  tty: true\r\n  image: itzg/minecraft-server\r\n  volumes:\r\n  - :/data\r\n  stdin_open: true\r\nMinecraftLB:\r\n  ports:\r\n  - 25565:25565/tcp\r\n  restart:\r\n    name: always\r\n  labels:\r\n    io.rancher.scheduler.global: 'true'\r\n    io.rancher.scheduler.affinity:host_label: lb=1\r\n  tty: true\r\n  image: rancher/load-balancer-service\r\n  links:\r\n  - Minecraft:Minecraft\r\n  stdin_open: true",
    "environment": null,
    "externalId": null,
    "kind": "environment",
    "outputs": null,
    "previousExternalId": null,
    "rancherCompose": "Minecraft:\r\n  scale: 2\r\n  metadata:\r\n    io.rancher.service.hash: 365d6faa33b6c17dd9691d2e88a1af8ff588f8c7\r\nMinecraftLB:\r\n  load_balancer_config: {}",
    "removed": null,
    "startOnCreate": null,
    "transitioning": "yes",
    "transitioningMessage": "yaml: unmarshal errors:\n  line 8: cannot unmarshal !!map into string",
    "transitioningProgress": null,
    "uuid": "8ae75f98-ff34-4a63-9754-2b00280327cb",
}

**Comment by sshipway** [comment]
Note: this is Rancher 0.46.0.  I have done this successfully in Ranche 0.44.0 in the past.

**Comment by deniseschannon** [comment]
Could you provide the docker-compose.yml that you imported?

**Comment by sshipway** [comment]
I can upload it separately later, but it is shown in the API YAML above as dockerCompose

**Comment by sshipway** [comment]
This also happens in 0.47.0 (just tested) though helpfuly, 0.47.0 displays the error message in the UI.
"yaml: unmarshal errors:\n line 8: cannot unmarshal !!map into string"

The docker-compose file (this is exactly as exported from another environment, no changes):
```
Minecraft:
  restart:
    name: always
  environment:
    EULA: 'TRUE'
  tty: true
  image: itzg/minecraft-server
  volumes:
  - :/data
  stdin_open: true
MinecraftLB:
  ports:
  - 25565:25565/tcp
  restart:
    name: always
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: lb=1
  tty: true
  image: rancher/load-balancer-service
  links:
  - Minecraft:Minecraft
  stdin_open: true
```
