### ISSUE TITLE
Unable to deploy K8s Service and Endpoints with same name with Helm 3 Chart

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#28088]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a Helm 3 chart with a K8s YAML file name external-services.yml with following code:
`apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  ports:
  - port: 80
    targetPort: 8080

---

kind: Endpoints
apiVersion: v1
metadata:
 name: external-service
subsets:
- addresses:
  - ip: 10.10.10.10
  ports:
  - port: 8080
`

**Result:**
Error message "Failed to install app novas. Error: endpoints "external-service" already exists"

**Other details that may be helpful:**
All K8s examples tie the Service and Endpoints using same name.  I'm able to deploy without issue using kubctl:

`kubectl apply -f external-service.yml`

**Environment information**
- Rancher 2.4.5 in single install
- k3s Cluster

**Comment by Lebvanih** [comment]
I noticed I didn't add these details in my ticket #27039 (mostly about the error returned), but these seems to be the same error that we got with our services without selectors :/. Hopefully we'll have some feedback in this ticket..

**Comment by bentastic27** [comment]
Right now. If you create a service, Rancher will automatically create an endpoint. This is fine a vast majority of the time, but it breaks the use case of creating an endpoint to point to an external service.

To recreate, create a chart with the following template. If you pass `endpoint: true` and `service: true` (to create both), you'll be greeted with an error stating that the endpoint already exists.

It will also add it's own `io.cattle.field/appId` label/selector which may be part of the problem.

```
{{ if .Values.endpoint }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
  labels:
    some: label
subsets:
- addresses:
  - ip: 10.10.10.10
  ports:
  - port: 8080
{{ end }}
{{ if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  selector:
    some: label
  ports:
  - port: 80
    targetPort: 8080
{{ end }}
```
