### ISSUE TITLE
Istio v2: Add-Ons Kiali and Prometheus

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#28147]
- [x] Ensure Rancher monitoring's prometheus can be used.
- [x] Ensure that the meshConfig.enablePrometheusMerge options is editable.
- [x] Ensure Kiali is packaged alongside istio with a working traffic graph
- [x] Determine Kiali authentication strategy for integration into the UI
- [x] On uninstall, Kiali CRDs should be cleaned up.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head c428bc9

* Deploy cluster
* Enable v2 rancher-monitoring
* Enable v2 Istio 1.7.000
* Default values have prometheus URLs from rancher-monitoring
* Create an ingress to `rancher-istio-kiali` (workaround until UI link functions)
* Kiali is deployed and traffic graph functions
* Editing `meshConfig.enablePrometheusMerge` between true/false updates the meshConfig in Istio controlplane:
```
istio-proxy@istiod-54984f7fb6-v5n5x:/etc/istio/config$ cat mesh
defaultConfig:
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata:
    DNS_AGENT: ""
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
disableMixerHttpReports: true
enablePrometheusMerge: false
```

Also tested:
* Do not installer rancher-monitoring
* Deploy prometheus either from `values.prometheus.enabled=true` in values YAML, or deploy prometheus following Istio directions: `https://istio.io/latest/docs/ops/integrations/prometheus/`
* Edit prometheus URLs in values yaml to use the non-rancher prometheus: 
```
external_services:
    prometheus:
      custom_metrics_url: 'http://prometheus.istio-system.svc:9090'
      url: 'http://prometheus.istio-system.svc:9090'
```
* Kiali graph functions
