### ISSUE TITLE
Ability to modify the kubelet root-dir for windows worker nodes

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#28143]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

Add the option to change the kubelet root-dir startup argument for windows worker nodes only. This would be a separate configuration option than the Linux nodes to allow windows nodes to utilize additional disks (which we are currently limiting to the C: drive) for kubelet

**Comment by luthermonson** [comment]
https://github.com/rancher/rke/pull/2172

**Comment by luthermonson** [comment]
This PR added ability to add win_ only params for the following to the kubelet and proxy services in the cluster.yml.

```
win_extra_args:
win_extra_binds:
win_extra_env:
```

**Comment by sowmyav27** [comment]
**Verified on 2.4-head commit id: `0a219c19e`**

- Deploy a windows 1903 cluster - 2 linux nodes, 2 windows nodes
- Entered the below values in cluster.yml for kubelet and kube-proxy
```
extra_args:
        max-pods: 122
      extra_binds:
        - '/opt:/test'
      extra_env:
        - "t1=v1"
      win_extra_args:
        max-pods: '120'
      win_extra_binds:
        - 'c:/:c:/test'
      win_extra_env:
        - test=value
```
- on docker inpsect correct values were set for linux and windows nodes
