### ISSUE TITLE
CoreDNS v1.6.9 don't work on k8s v1.18.6: Loop detected for zone "."

### ISSUE THREAD

**Issue by Wing924** [rancher/rancher#28238]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* install rancher v2.4.5
* create new cluster with:
```yaml
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509
  ignore_docker_version: true
  ingress:
    provider: nginx
  kubernetes_version: v1.18.6-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    plugin: calico
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 8
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kubelet:
      extra_binds:
        - '/etc/iscsi:/etc/iscsi'
        - '/sbin/iscsiadm:/sbin/iscsiadm'
        - '/var/lib/iscsi:/var/lib/iscsi'
        - '/var/openebs/local:/var/openebs/local'
        - /lib/modules
      fail_swap_on: true
      generate_serving_certificate: false
    kubeproxy:
      extra_args:
        proxy-mode: ipvs
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      failures_only: false
      override_benchmark_version: rke-cis-1.4
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
windows_prefered_cluster: false
```

**Result:**
coredns can't fatal: `[FATAL] plugin/loop: Loop (127.0.0.1:42522 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting.`

**Other details that may be helpful:**
OK: cordns v1.6.5, v1.6.6
NG: cordns v1.6.7-v1.6.9
OK: cordns v1.7.0

k8s v1.17.9 works fine (coredns v1.6.5)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal 8core 32Mem
- Kubernetes version (use `kubectl version`): 1.18.6

- Docker version (use `docker version`): 1.17.9
- OS: CentOS Linux release 7.6.1810 (Core)
- kernel: 4.20.11-1.el7.elrepo.x86_64
