### ISSUE TITLE
No ingress endpoints reachable from Helm v3 deployed services

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#28275]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

We typically install Openstack Cloud Controller Manager Helm Chart with [Rancher2_App Terraform](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app). The chart is stored in a ChartMuseum, included in Rancher as Helm v3 Catalog. Part of the Helm Chart is a OpenStack loadbalancer service:

```
kind: Service
apiVersion: v1
metadata:
  name: openstack-lb
  namespace: ingress-nginx
  labels:
    app: openstack-lb
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: "Local"
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
```

**Result:**

The service is rollout with this parameter:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mcsps-openstack-cloud-controller-manager
    meta.helm.sh/release-namespace: kube-system
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
  creationTimestamp: "2020-08-06T21:05:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: openstack-lb
    app.kubernetes.io/managed-by: Helm
    io.cattle.field/appId: mcsps-openstack-cloud-controller-manager
  name: openstack-lb
  namespace: ingress-nginx
spec:
  clusterIP: 10.43.60.184
  externalTrafficPolicy: Local
  healthCheckNodePort: 32266
  ports:
  - name: http
    nodePort: 32428
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31866
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx
    io.cattle.field/appId: mcsps-openstack-cloud-controller-manager
  sessionAffinity: ClientIP
  type: LoadBalancer
```
Normaly the Nginx Ingress Controller would pickup the services with the selector `app: ingress-nginx`
But a second selector appeared : `io.cattle.field/appId: mcsps-openstack-cloud-controller-manager`

Maybe introduced [here](https://github.com/rancher/helm/pull/16/files), activated since we moved from Helm v2 catalog to Helm v3. With this second selector no endpoints are added to the service:

```
kubectl -n ingress-nginx get ep openstack-lb
NAME           ENDPOINTS   AGE
openstack-lb   <none>      13h
```
**Workaround**

Remove ` io.cattle.field/appId: mcsps-openstack-cloud-controller-manager`

```
$ kubectl -n ingress-nginx get ep openstack-lb2
NAME            ENDPOINTS                    AGE
openstack-lb   10.9.3.39:443,10.9.3.39:80   168m
```

**Other details that may be helpful:**

- terraform-providers/rancher2: 1.10.0
- Terraform = v0.12.29
- Helm = v3.2.4

**Environment information**
- Rancher version: (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.18.6
- Docker version (use `docker version`): 19.3.12
