### ISSUE TITLE
[Logging v2] - username and password is not properly configured in the ClusterOutput of the rancher-logging app

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28295]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Configure Elasticsearch/Kibana backend with basic password logging
- Deploy the `rancher-logging` chart from the Dashboard setting using the username and password

**Result:**

- The ClusterOutput generated by the install doesn't include anything about the username and password
```yaml
  spec:
    elasticsearch:
      host: <host>
      index_name: test2
      port: 9200
      scheme: http
```

There's a secret `rancher-logging-elasticsearch` with the `password` key where the password gets stored but the `ClusterOutput` doesn't reference it.

The `user` key is also not in `ClusterOutput`

**Other details that may be helpful:**

If we navigate to the installed app in the Dashboard I see the username/password shown in the Chart Options form.
![Screen Shot 2020-08-07 at 4 34 10 PM](https://user-images.githubusercontent.com/27659/89696292-0d857700-d8cc-11ea-8389-a14a3fd9eada.png)

Updating the ClusterOutput with the expected information I get the logs in the Elasticsearch server:

```yaml
spec:
  elasticsearch:
    host: <hostname>
    index_name: test2
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: rancher-logging-elasticsearch
    port: 9200
    scheme: http
    user: elastic
```
rancher/rancher#27935

**Environment information**
- Rancher version: `master-head (08/07/2020)` _4fb56e2b7_
- Installation option: HA k8s local
