### ISSUE TITLE
Replace PRTB/CRTB UID with their name+ns for use as labels and annotations

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#28370]
The projectroletemplatebinding and clusterroletemplatebinding UIDs are used as label keys for
clusterrolebindings and rolebindings in the management cluster as follows

CRTB.UID is the label key for a CRB, CRTB.UID=memberhsip-binding-owner
CRTB.UID is label key for the RB, CRTB.UID=crtb-in-project-binding-owner
PRTB.UID is the label key for a CRB, PRTB.UID=memberhsip-binding-owner
PRTB.UID is the label key for RB, PRTB.UID=memberhsip-binding-owner
PRTB.UID is also the label key for RB, PRTB.UID=prtb-in-cluster-binding-owner

PRTB/CRTB are also used as label values for clusterrolebindings and rolebindings in downstream user clusters

CRTB.UID is label value for CRB, authz.cluster.cattle.io/rtb-owner=CRTB.UID
PRTB.UID is label key for CRB, PRTB.UID=owner-user

Starting 2.5, instead of using UID, use namespace+name(+gvk if needed) as the label.
This is needed when during backup/restore UID is changed we don't lose the relation between PRTB/CRTB and RB/CRB respectively

**Comment by sowmyav27** [comment]
**On 2.4.8** (single node install)

- Add a user1 as the cluster owner of the cluster 1
- Add user2 as project owner of cluster2
- Labels set on clusterrolebindings :

- kubectl get clusterrolebinding  -o yaml | grep -B7 -A33 "authz.cluster.cattle.io/rtb-owner: a16f26e7-206a-4840-8223-af45d807b43e"
```
labels:authz.cluster.cattle.io/rtb-owner: a16f26e7-206a-4840-8223-af45d807b43e
      
```
- Add a user as a project owner -- 
- kubectl get clusterrolebinding -o yaml | grep -B5 -A30 "00d2791f-d99a-4698-a73b-15d02a710200: owner-user"
```
labels:
      00d2791f-d99a-4698-a73b-15d02a710200: owner-user
```


**Upgrade to master-head - commit id: `89dd0fe25`**

CTRB:
```
labels:
      authz.cluster.cattle.io/rtb-owner-updated: c-btcsr_crtb-rgf7w
      cattle.io/creator: norman 
```

PRTB:
- kubectl get clusterrolebindings -o yaml | grep -B5 -A30 "00d2791f-d99a-4698-a73b-15d02a710200: owner-user"
```
labels:
      00d2791f-d99a-4698-a73b-15d02a710200: owner-user
      authz.cluster.cattle.io/rtb-label-updated: "true"
      cattle.io/creator: norman
      p-qdxpv_prtb-gzp4p: owner-user
```

- clusterrolebinding related to Cluster owner is missing the label with the `uid of the CRTB`
- On deleting cluster owner role of user1 , user1 still has access to the cluster.

**Comment by mrajashree** [comment]
Along with granting/revoking permissions, these are the things I checked related to roletemplate changes
1. Clone the project-owner role
2. Assign this cloned role to a user
3. Login as this user, user can create namespaces and add new members to the project
4. Edit the cloned role to remove permissions to create ns and to create projectroletemplatebindings
5. Logged in user should not be able to create namespaces or add new members to the project

Same with cloning cluster-owner role. I checked that the user with this role can create projects in the cluster, and then edited the cloned role to remove permissions to create project. Then the user could no longer create projects

**Comment by sowmyav27** [comment]
### In 2.4.8:

Tested in a single node, using 2 custom clusters - 4 nodes each. 
- Add a user1 as the cluster owner of the cluster 1
- Add user2 as project owner of project in cluster2
- Clone roles - cluster owner and project owner 
- users3 -- cloned cluster owner role of the cluster 1
- user 4 - cloned project owner role of project in cluster2
- clusterRoleTemplateBinding of the cluster owner
 kubectl get clusterrolebinding -o yaml | grep -B7 -A33 "authz.cluster.cattle.io/rtb-owner: de9423f8-d077-43ca-9681-24ea4922e696"
```
    labels:
      authz.cluster.cattle.io/rtb-owner: de9423f8-d077-43ca-9681-24ea4922e696
      cattle.io/creator: norman
```
- clusterRoleTemplateBinding of Cloned cluster owner
kubectl get clusterrolebinding -o yaml | grep -B7 -A33 "authz.cluster.cattle.io/rtb-owner: 35edc158-10ee-4899-9914-2ec1a9d22bf3"
```   
    labels:
      authz.cluster.cattle.io/rtb-owner: 35edc158-10ee-4899-9914-2ec1a9d22bf3
      cattle.io/creator: norman
```
- projectRoleTemplateBinding of cloned project owner
kubectl get clusterrolebinding -o yaml | grep -B5 -A30 "09fa68f8-55cb-4ea6-a811-23f34cbaf05b: owner-user"
```
    labels:
      09fa68f8-55cb-4ea6-a811-23f34cbaf05b: owner-user
      cattle.io/creator: norman
```
- projectRoleTemplateBinding of project owner
kubectl get clusterrolebinding -o yaml | grep -B5 -A30 "4d7c7fcd-2908-4ade-8033-11ba97161c0b: owner-user"
```
    labels:
      4d7c7fcd-2908-4ade-8033-11ba97161c0b: owner-user
      cattle.io/creator: norman
```
### **On upgrade to master-head commit id: `4ac3a87d7`**

- ClusterOwner rolebinding
> kubectl get clusterrolebinding -o yaml | grep -B7 -A33 "authz.cluster.cattle.io/rtb-owner-updated: c-xz9c2_crtb-97zql"
```
    labels:
      authz.cluster.cattle.io/rtb-owner-updated: c-xz9c2_crtb-97zql
      cattle.io/creator: norman
```
- Cloned cluster owner rolebinding
```
labels:
      authz.cluster.cattle.io/rtb-label-updated: "true"
      authz.cluster.cattle.io/rtb-owner: 35edc158-10ee-4899-9914-2ec1a9d22bf3
      authz.cluster.cattle.io/rtb-owner-updated: c-xz9c2_crtb-9ncwl
      cattle.io/creator: norman
```
- Cloned project owner rolebinding
kubectl get clusterrolebinding -o yaml | grep -B5 -A30 "p-xjfhx_prtb-ggn9m: owner-user"
```
    labels:
      09fa68f8-55cb-4ea6-a811-23f34cbaf05b: owner-user
      authz.cluster.cattle.io/rtb-label-updated: "true"
      cattle.io/creator: norman
      p-xjfhx_prtb-ggn9m: owner-user
```
- Project owner rolebinding
kubectl get clusterrolebinding -o yaml | grep -B5 -A30 "p-xjfhx_prtb-ggn9m: owner-user"
```
    labels:
      09fa68f8-55cb-4ea6-a811-23f34cbaf05b: owner-user
      authz.cluster.cattle.io/rtb-label-updated: "true"
      cattle.io/creator: norman
      p-xjfhx_prtb-ggn9m: owner-user
```

- Cluster Owner rolebinding did not have the the older label with the UID.
- Other users had both the labels - new one and the old one with the UID (new is something like `p-xjfhx_prtb-ggn9m: owner-user`)
- From cloned Cluster owner role -- remove all rules except for "Clusters" . User with this role was not able to edit cluster/add projects
- From cloned project owner role - remove namespace create rule -- User with this role is not able to create namespace. And removed `projectroletemplatebindings` -- User with this role is not able to add members to the project
- Deploy rancher - backup restore app
- Take a backup b1
- Delete all users' rolebindings from clusters and projects
- Verified user1/2/3/4 --> Do not have access to the cluster/project
- Take a backup b2
- Restore from backup b1
