### ISSUE TITLE
Rancher deployed Apps incorrectly add io.cattle.field/appId to resource selector specification

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#28381]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy a Rancher v2.4.5 instance, with a single node custom cluster
2. Add a custom catalog (I specified Helm v3) with a test chart that contains a simple Service resource, as below. Full chart attached at [test-chart.zip](https://github.com/rancher/rancher/files/5067530/test-chart.zip)

```
kind: Service
apiVersion: v1
metadata:
  name: test-ingress
  namespace: ingress-nginx
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
```

3. Deploy this chart into the custom cluster (in my test I deployed the chart into the `ingress-nginx` namespace of the `System` project, naming the App `test`) and observe that `io.cattle.field/appId: test` is added to the `spec.selector` for the generated Service.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app.kubernetes.io/managed-by: Helm
    io.cattle.field/appId: test
  name: test-ingress
  namespace: ingress-nginx
spec:
  clusterIP: 10.43.125.32
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx
    io.cattle.field/appId: test
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
```

**Result:**

The service will not route traffic as expected to the desired selector, due to the additional `io.cattle.field/appId: test` selector that is added by the deployment.

**Other details that may be helpful:**

This behaviour does not match native Helm behaviour, deploying the same chart with helm CLI v3.2.4 (`helm install -n ingress-nginx test ./test`) the selector is not updated:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: ingress-nginx
  labels:
    app: test-ingress
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: 10.43.97.88
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
```

**Environment information**
- Rancher v2.4.5

gzrancher/rancher#11647
