### ISSUE TITLE
kubelet_* metrics not available in project monitoring

### ISSUE THREAD

**Issue by scoof** [rancher/rancher#28394]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
* Enable cluster- and project monitoring.
* Go to project Prometheus webui.
* Try to look up any of the kubelet_ metrics, e.g. kubelet_container_log_filesystem_used_bytes

**Result:**
kubelet_* metrics are not available in project monitoring.

**Other details that may be helpful:**
Prometheus federation is available and active, but is based on namespaces of the metrics. All kubelet metrics are exported from pods in the cattle-monitoring namespace, and hence get that as namespace label, and exported_namespace as the namespace that the metric really belongs to.
My proposed fix is to allow Prometheus to restore the original namespace (if present) by adding metricRelabeling to the exporter-kubelets-cluster-monitoring ServiceMonitor CRD:
```
metricRelabelings:
    - action: replace
      regex: (.+)
      sourceLabels:
      - exported_namespace
      targetLabel: namespace
```

I can submit a PR with this fix, if you agree.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Monitoring version: 0.1.1
