### ISSUE TITLE
Cluster update breaks namespace labels with OPA gatekeeper

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#28419]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Install OPA gatekeeper using `kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper.yaml`
- Deploy the following rules.
```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            labels:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_]}
          missing := required - provided
          count(missing) > 0
          msg := sprintf("you must provide labels: %v", [missing])
        }

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-project
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: ["field.cattle.io/projectId"]
```

**Result:**

The cluster will get stuck 'Updating' with the following message
```
Admission webhook "validation.gatekeeper.sh" denied the request: [denied by ns-must-have-project] you must provide labels: {"field.cattle.io/projectId"}
```

**Other details that may be helpful:**
It looks like Rancher removes and re-adds the project labels on kube-system. And OPA is blocking the removal.
Also, excluding the namespaces doesn't resolve the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

SURE-2195

**Comment by prachidamle** [comment]
This just needs correcting the Constraint yaml to specify the list of system-namespaces to be excluded from the Constraint.

The Policy/Rule "K8sRequiredLabels" applied to the Cluster via the above OPA Gatekeeper Constraint needs to mention the list of system namespaces that should be excluded from the constraint, otherwise Gatekeeper will deny requests involving the system namespaces as well.

The Constraint created using the above ConstraintTemplate should include the following whitelist of namespaces in the spec, for example:

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: testlabel
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
    - cattle-gatekeeper-system
    - kube-system
    - kube-public
    - kube-node-lease
    - cattle-system
    - security-scan
    - ingress-nginx
    - fleet-system
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  labelSelector:
  matchExpressions: []
  namespaceSelector:
  matchExpressions: []
  scope: '*'
  parameters:
    labels: 
      - "field.cattle.io/projectId"
status: 
type: constraints.gatekeeper.sh.k8srequiredlabels
```
