### ISSUE TITLE
question: pipeline trigger on tag regex filter

### ISSUE THREAD

**Issue by dev-intermedes** [rancher/rancher#28454]
Hello rancheros !
question: is it possible to filter conditionally trigger the pipeline if my tag start with production-* ?

i m using the latest rancher version.

```yml
stages:
- name: Build-app
  steps:
  - publishImageConfig:
      dockerfilePath: ./app.dockerfile
      buildContext: .
      tag: eu.gcr.io/web/app:${CICD_GIT_TAG}
      pushRemote: true
      registry: eu.gcr.io
  when:
    branch: {}
    event:
      include:
      - tag
- name: deploy-app
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
  when:
    branch: {}
    event:
      include:
      - tag
timeout: 60
branch:
  include:
  - master
notification:
  recipients:
  - recipient: '#ops'
    notifier: local:n-8888
  condition:
  - Success
  - Failed
```

Thanks for your help :D
