### ISSUE TITLE
[Monitoring V2] Broken links via proxy due to ExternalURL / RootURL defaults

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#28495]
Note: leaving this as a rancher/rancher issues until it has been identified whether any backend changes are required. If none are required, I'll move this over to rancher/dashboard.

### Issue

When utilizing links that are generated via kube-proxy such as in https://github.com/rancher/dashboard/issues/1064 in Monitoring V2, there are issues with rendering particular pages on the Prometheus, Grafana, and AlertManager UIs since they each require users to have set the External URL / Root URL fields on deploying the Helm chart in order to successfully be able to show the page. As of yet, this issue has been found to cause issues in rendering the following pages:
- Prometheus: `/graph` endpoint requires the ExternalURL to be set correctly in order to make /query requests
- Grafana: most links are broken since the Root URL needs to be set for Grafana and the External URL that is placed into the Prometheus datasource URL is incorrect
- AlertManager: no known issues, but it's possible some advanced configuration may encounter these issues.

The solution for this is to set the following fields on deployment:
```yaml
# Sets https://github.com/helm/charts/blob/506eedd8f3d58e73fd3f7b3fecfec38f9f45aedb/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L55-L61
prometheus:
  prometheusSpec:
    externalURL: <url>

# Sets https://github.com/helm/charts/blob/76982a553754904036b661d4b3c6bbb829c35886/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml#L21-L27
alertmanager:
  alertmanagerSpec:
    externalURL: <url>

grafana:
  grafana.ini:
    server:
      root_url: <url>
```

However, there are three possible cases for what this URL should be:
1. **Using Rancher:** `<rancher-url>/k8s/clusters/<cluster-id>/api/v1/namespaces/cattle-monitoring-system/services/http:<service-info>/proxy`
1. **Using `kubectl proxy`**: `http://localhost:8001/api/v1/namespaces/cattle-monitoring-system/services/http:<service-info>/proxy`
1. **Using an Ingress**: Needs to be configured by the user; for [AlertManager](https://github.com/helm/charts/blob/76982a553754904036b661d4b3c6bbb829c35886/stable/prometheus-operator/templates/alertmanager/alertmanager.yaml#L24) and [Prometheus](https://github.com/helm/charts/blob/506eedd8f3d58e73fd3f7b3fecfec38f9f45aedb/stable/prometheus-operator/templates/prometheus/prometheus.yaml#L58), an Ingress that is configured through the deployment automatically updates the external URL values, but for [Grafana](https://github.com/helm/charts/blob/9f7564d523d559c7bb06f38a7720a6626947ed55/stable/grafana/templates/configmap.yaml#L13-L18) this value is not automatically configured.

where `<service-info>` would be `rancher-monitoring-grafana:80`, `rancher-monitoring-prometheus:9090`, or `rancher-monitoring-alertmanager:9093`.

What should the expectation be with the default values for the Helm chart on deployment? 

### Proposed Solution

Don't change the Helm chart defaults. If a user is deploying Rancher Monitoring via the dashboard, we'll have the Magic URL above auto-filled out under:
- the existing `External URL` field for the `Prometheus - Network` [Advanced Configuration](https://github.com/rancher/dashboard/issues/909)
- a newly exposed `External URL` field for the `Grafana - Network` [Advanced Configuration](https://github.com/rancher/dashboard/issues/909) which will be tied to `grafana.grafana.ini.server.root_url`
- a newly exposed `External URL` field for the `AlertManager - Network` [Advanced Configuration](https://github.com/rancher/dashboard/issues/1014) which will be tied to `alertmanager.alertmanagerSpec.externalURL`

As a result, if a user deploys the Rancher Monitoring chart via Dashboard, the expectation would be that the user will not also be using `kubectl proxy` to directly access these components without modifying these external URL values.

If a user deploys the Rancher Monitoring chart via the Helm chart, however, they will be responsible for making sure this value is updated, which can be mentioned in the Rancher Monitoring documentation. This may or may not involve updating the values for kubeproxy to be usable, although using something like `kubectl port-forward` seems to have been working as expected either way.

If the user uses an Ingress, they will know to modify these values since they are in the same section where an Ingress would likely be configured on the deployment.
