### ISSUE TITLE
My angular deployment fails 

### ISSUE THREAD

**Issue by napindc** [rancher/rancher#28521]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
I have Rancher 2.4.3 deployed on a set of AWS servers. I have a website that is split into two sets of Kubernetes projects - the frontend built with Angular (and deploys the frontend app with webpack) and the backend built with Java/ spring. I am able to run the site locally, just fine.

I first run my set of frontend files with `kubectl apply -k frontend/kustomization.yaml`, and it deploys it on Rancher, and I'm able to access the site with Istio doing the DNS. However I can't do much with it since the backend isn't deployed yet. 

I then run my backend with `kubectl apply -k backend/kustomization.yaml`, which include a deployment / istio files / pvc. Once this happens, my frontend website starts to error out, saying it can't find some of the .JS files (such as manifest.bundle.js etc...). If I delete the deployment of the backend, then the frontend works fine.

Can anyone point me in the right direction as to why this is happening?

Here is what our backend deployment looks like, and it uses all different names for everything (ie. has "be" appended to everything).
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberlynx-be-custom-mount
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    spec:
      containers:
        - name: cyberlynx-be-custom-mount
          image: "1.2.0"
          envFrom:
            - configMapRef:
                name: cyberlynx-be-config
          ports:
          - name: http
            containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "2048Mi"
            requests:
              cpu: "0.1"
              memory: "64Mi"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/h2/data
              name: cyberlynx-db-vol01-custom-mount

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000

      imagePullSecrets:
        - name: regcred-nexus
      volumes:
      - name: cyberlynx-db-vol01-custom-mount
        persistentVolumeClaim:
          claimName: cyberlynx-db-pvc-volume01-custom-mount
      terminationGracePeriodSeconds: 30
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted on AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`): v1.16.8

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
