### ISSUE TITLE
rancher-gatekeeper auditinterval default is 300

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#28544]
Rancher version `master-head 8a60de75d` `master-8a60de75db5324c73535b71c087c3e4bd5f36d29-head`
- Go to the Dashboard in the local cluster
- Apps -> Charts -> rancher-gatekeeper Install.
- Note auditInterval is set to 60
![Screen Shot 2020-08-24 at 4 21 50 PM](https://user-images.githubusercontent.com/57409052/91105820-efd34400-e625-11ea-94a0-a428171f0766.png)
- After installation succeeds got o Apps -> Installed Apps

Under IRancher Gatekeeper > View as YAML:
`audInterval` is set to 300
```
values:
      affinity: {}
      auditChunkSize: 0
      auditFromCache: false
      auditInterval: 300
      constraintViolationsLimit: 20
      disableValidatingWebhook: false
      emitAdmissionEvents: false
      emitAuditEvents: false
```
