### ISSUE TITLE
User is not able to create a resourceset from dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28542]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create a repo - `https://github.com/mrajashree/charts` and branch - `backup-restore` 
- Deploy app - `backup-restore-operator` from this catalog
- From Dashboard create a Resourceset
- Resourceset Yaml file
```
apiVersion: resources.cattle.io/v1
kind: ResourceSet
metadata:
  name: ecm-resource-set
resourceSelectors:
  - apiVersion: "v1"
    kindsRegexp: "^namespaces$"
    resourceNameRegexp: "^cattle-|^p-|^c-|^user-|^u-"
    resourceNames:
      - "local"
  - apiVersion: "v1"
    kindsRegexp: "^Secret$|^serviceaccounts$"
    namespaceRegexp: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  - apiVersion: "rbac.authorization.k8s.io/v1"
    kindsRegexp: "^roles$|^rolebindings$"
    namespaceRegexp: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  - apiVersion: "rbac.authorization.k8s.io/v1"
    kindsRegexp: "^clusterrolebindings$"
    resourceNameRegexp: "^cattle-|^clusterrolebinding-|^globaladmin-user-|^grb-u-"
  - apiVersion: "rbac.authorization.k8s.io/v1"
    kindsRegexp: "^clusterroles$"
    resourceNameRegexp: "^cattle-|^p-|^c-|^local-|^user-|^u-|^project-|^create-ns$"
  - apiVersion: "apiextensions.k8s.io/v1beta1"
    kindsRegexp: "."
    resourceNameRegexp: "management.cattle.io$|project.cattle.io$"
  - apiVersion: "management.cattle.io/v3"
    kindsRegexp: "."
  - apiVersion: "project.cattle.io/v3"
    kindsRegexp: "."
controllerReferences:
  - apiVersion: "apps/v1"
    resource: "deployments"
    name: "rancher"
    namespace: "cattle-system"
```
- Click on Create
- Error seen on UI: `{ "type": "error", "links": {}, "code": "NotFound", "message": "the server could not find the requested resource", "status": 404 }`
- Error in console log:
```
xhr.js:178 POST https://<rancher-server>/v1/resources.cattle.io.resourcesets 404
(anonymous) @ xhr.js:178
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:50
Promise.then (async)
d.request @ Axios.js:61
(anonymous) @ bind.js:9
request @ actions.js:15
(anonymous) @ vuex.esm.js:847
y.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
r.dispatch @ vuex.esm.js:775
(anonymous) @ resource-instance.js:691
(anonymous) @ ResourceYaml.vue:228
d @ runtime.js:45
(anonymous) @ runtime.js:274
O.forEach.t.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
save @ ResourceYaml.vue:222
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qt @ vue.runtime.esm.js:1854
t.$emit @ vue.runtime.esm.js:3888
save @ Footer.vue:36
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
Qt @ vue.runtime.esm.js:1854
t.$emit @ vue.runtime.esm.js:3888
clicked @ AsyncButton.vue:161
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
c._wrapper @ vue.runtime.esm.js:6917
```

**Expected Result:**
User should be able to deploy resourceset

**Other details that may be helpful:**
Able to deploy this yaml through kubectl

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `56b819995`
- Installation option (single install/HA): HA - imported k8s
