### ISSUE TITLE
[Logging v2] - helm uninstall error release: not found when using additionalResources k3s enabled.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28565]
**What kind of request is this:**
bug

**Steps to reproduce:**

- install k3s cluster
- using helm install the `rancher-logging` chart

```
helm install rancher-logging-crd https://charts.rancher.io/assets/rancher-logging/rancher-logging-crd-3.4.000.tgz --create-namespace=true --namespace=cattle-logging-system
helm install --create-namespace=true --namespace=cattle-logging-system rancher-logging -f values.yaml https://charts.rancher.io/assets/rancher-logging/rancher-logging-3.4.000.tgz
```

```yaml
disablePvc: true
additionalLoggingSources:
  rke1:
    enabled: true
  rke2:
    enabled: false
  k3s:
    enabled: true
    container_engine: "openrc" #  "systemd" 
images:
  config_reloader:
    repository: rancher/jimmidyson-configmap-reload
    tag: v0.2.2
  fluentbit:
    repository: rancher/fluent-fluent-bit
    tag: 1.5.0
  fluentd:
    repository: rancher/banzaicloud-fluentd
    tag: v1.10.4-alpine-2
  syslog_forwarder:
    repository: rancher/fluent-bit-out-syslog
    tag: 0.1.0
global:
  systemDefaultRegistry: ""
```

Uninstall:

```
helm uninstall -n cattle-logging-system rancher-logging
helm uninstall -n cattle-logging-system rancher-logging-rcd
```

**Result:**

**Error: uninstall: Release not loaded: rancher-logging-rcd: release: not found**

```
helm uninstall -n cattle-logging-system rancher-logging-rcd
Error: uninstall: Release not loaded: rancher-logging-rcd: release: not found

k get no
NAME           STATUS   ROLES    AGE   VERSION
izaac-alpine   Ready    master   11m   v1.18.8+k3s1

k get crd | grep logging
flows.logging.banzaicloud.io            2020-08-26T13:35:06Z
clusterflows.logging.banzaicloud.io     2020-08-26T13:35:06Z
loggings.logging.banzaicloud.io         2020-08-26T13:35:07Z
outputs.logging.banzaicloud.io          2020-08-26T13:35:08Z
clusteroutputs.logging.banzaicloud.io   2020-08-26T13:35:08Z
```

**Other details that may be helpful:**

**_Uninstall is correct if I all additionalLoggingSources options are false._**

**Environment information**
- Rancher version: `master-head (08/26/2020)` _9b6984d5f_
- Installation option: HA k8s

**Cluster information**
- Cluster type: Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4GB 2 vcpu
- Kubernetes version: `v1.18.8+k3s1`
