### ISSUE TITLE
[Logging v2] - Document proper syslog forward configuration

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28566]
**What kind of request is this:**
bug

**Steps to reproduce (least amount of steps as possible):**

To get Logging v2 with syslog as output provider we need a fluentd to process the logs and convert them to proper syslog logging format.

**Result:**

Otherwise we will end with invalid UTF characters in the logs if `rancher-logging` is configured to forward logs directly to an rsyslog server.

**Other details that may be helpful:**

```
�Eingress-nginx.nginx-ingress-controller-w2bpd.nginx-ingress-controller�#000#000#003y��#000_E��#034Ko���log��45.33.56.164 - - [25/Aug/2020:23:50:51 +0000] "GET /v3/connect/config HTTP/2.0" 200 472 "-" "Go-http-client/2.0" 2833 0.002 [cattle-system-rancher-80] [] 10.42.0.3:80 795 0.000 200 b8bd48ea4260816e483e925f3fc3f921
Aug 25 23:51:55 ec2-x-x-x-x.us-west-2.compute.amazonaws.com �stream�stdout�time�2020-08-25T23: 50:51.474705849Z�kubernetes��pod_name�nginx-ingress-controller-w2bpd�namespace_name�ingress-nginx�pod_id�$9bf2042d-37f4-4b39-8d5b-e5af4f0ed90f�labels��app�ingress-nginx�controller-revision-hash�55dd558cd5�pod-template-generation�1�annotations��prometheus.io/port�10254�prometheus.io/scrape�true�host�54.213.148.229�container_name�nginx-ingress-controller�docker_id�@d60e8a6b0beb989f72763b42b6b5d53a2312c6a6f037a7264ca2096142df2a86�container_hash�hrancher/nginx-ingress-controller@sha256:98256ff4787045bf9914210fbb8190f806f0871270fa6654d0f92bfc3ef7b0b1�container_image�6rancher/nginx-ingress-controller:nginx-0.32.0-rancher1��size#001�compressed�text
```

**Environment information**
- Rancher version: `master-head (08/26/2020)` _9b6984d5f_
- Installation option: HA k8s

**Comment by paynejacob** [comment]
To connect to syslog we need to forward to a intermediate syslog fluentd.

Below is an example manifest for setting up a forwarding container and outputing to syslog.

```
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-syslog-forwarder
type: Opaque
stringData:
  fluent-bit.conf: |
    [INPUT]
        Name              forward
        Port              24224
    [OUTPUT]
        Name              syslog
        InstanceName      syslog-output
        Match             *
        Addr              syslog.example.com
        Cluster           514
        Buffer_Chunk_Size 64000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-syslog-forwarder
  labels:
    output: syslog
spec:
  selector:
    matchLabels:
      output: syslog
  template:
    metadata:
      labels:
        output: syslog
    spec:
      containers:
      - name: fluentbit
        image: paynejacob/fluent-bit-out-syslog:latest
        ports:
          - containerPort: 24224
        volumeMounts:
          - mountPath: "/fluent-bit/etc/"
            name: configuration
      volumes:
      - name: configuration
        secret:
          secretName: "fluentbit-syslog-forwarder"
---
apiVersion: v1
kind: Service
metadata:
  name: fluentbit-syslog-forwarder
spec:
  selector:
    output: syslog
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: fluentbit-syslog-forwarder
spec:
  forward:
    servers:
      - host: "fluentbit-syslog-forwarder"
    require_ack_response: false
    ignore_network_errors_at_startup: true
```

**Comment by cbron** [comment]
Moving out of priority 0, as this is now for docs phase.

**Comment by paynejacob** [comment]
To setup syslog forwarding A container needs to be configured to accept logs from fluentd and forward them to syslog.  The flow is configured to use a forward output.  The forward output forwards to the  syslog forwarder service.

```
apiVersion: v1
kind: Secret
metadata:
  name: syslog
type: Opaque
stringData:
  fluent-bit.conf: |
    [INPUT]
        Name              forward
        Port              24224

    [OUTPUT]
        Name              syslog
        InstanceName      syslog-output
        Match             *
        Addr              syslog.example.com
        Cluster           rancher
        Buffer_Chunk_Size 64000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-syslog-forwarder
  labels:
    output: syslog
spec:
  selector:
    matchLabels:
      output: syslog
  template:
    metadata:
      labels:
        output: syslog
    spec:
      containers:
      - name: fluentbit
        image: paynejacob/fluent-bit-out-syslog:latest
        ports:
          - containerPort: 24224
        volumeMounts:
          - mountPath: "/fluent-bit/etc/"
            name: configuration
      volumes:
      - name: configuration
        secret:
          secretName: "syslog"
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-forwarder
spec:
  selector:
    output: syslog
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: syslog
spec:
  outputRefs:
    - syslog
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: syslog
spec:
  forward:
    servers:
      - host: "syslog-forwarder"
    require_ack_response: false
    ignore_network_errors_at_startup: true
```

**Comment by cbron** [comment]
@izaac this is in test now, can you give that last comment a shot ? If that works we will throw in documentation.

**Comment by izaac** [comment]
Rancher version: `master-head (09/18/2020)` _8fd81a9_
`rancher-logging-3.6.000`

My rsyslog server is listening in port `514` so I changed a couple of things in [this config](https://github.com/rancher/rancher/issues/28566#issuecomment-694435258) 
I also changed the `ClusterFlow` `outputRefs` to `globalOutputRefs` which was changed in 3.6.

I applied the yaml to the `cattle-logging-system` namespace (`k apply -f all.yaml -n cattle-logging-system`):

```
NAME                                               READY   STATUS      RESTARTS   AGE
pod/fluentbit-syslog-forwarder-6856ff54fd-qlpht    1/1     Running     0          6m24s
pod/rancher-logging-557656f7c5-487lv               1/1     Running     0          7m2s
pod/rancher-logging-fluentbit-dq2zr                1/1     Running     0          6m56s
pod/rancher-logging-fluentd-0                      2/2     Running     0          6m56s
pod/rancher-logging-fluentd-configcheck-f63fc0f8   0/1     Completed   0          5m39s

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)               AGE
service/rancher-logging           ClusterIP   None            <none>        8080/TCP              7m2s
service/rancher-logging-fluentd   ClusterIP   10.43.155.190   <none>        24240/TCP,24240/UDP   6m56s
service/syslog-forwarder          ClusterIP   10.43.107.155   <none>        24224/TCP             6m13s

NAME                                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/rancher-logging-fluentbit   1         1         1       1            1           <none>          6m56s

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/fluentbit-syslog-forwarder   1/1     1            1           6m24s
deployment.apps/rancher-logging              1/1     1            1           7m2s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/fluentbit-syslog-forwarder-6856ff54fd   1         1         1       6m25s
replicaset.apps/rancher-logging-557656f7c5              1         1         1       7m3s

NAME                                       READY   AGE
statefulset.apps/rancher-logging-fluentd   1/1     6m57s
```

I do not see any errors in the containers logs but I still don't see the logs reaching the rsyslog server.

**Comment by paynejacob** [comment]
Updated configuration:

```
apiVersion: v1
kind: Secret
metadata:
  name: syslog
type: Opaque
stringData:
  fluent-bit.conf: |
    [INPUT]
        Name              forward
        Port              24224

    [OUTPUT]
        Name              syslog
        InstanceName      syslog-output
        Match             *
        Addr              167.99.101.174
        Port              514
        Cluster           rancher
        Buffer_Chunk_Size 64000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-syslog-forwarder
  labels:
    output: syslog
spec:
  selector:
    matchLabels:
      output: syslog
  template:
    metadata:
      labels:
        output: syslog
    spec:
      containers:
      - name: fluentbit
        image: paynejacob/fluent-bit-out-syslog:latest
        ports:
          - containerPort: 24224
        volumeMounts:
          - mountPath: "/fluent-bit/etc/"
            name: configuration
      volumes:
      - name: configuration
        secret:
          secretName: "syslog"
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-forwarder
spec:
  selector:
    output: syslog
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: syslog
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
    - syslog
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: syslog
  namespace: cattle-logging-system
spec:
  forward:
    servers:
      - host: "syslog-forwarder.default"
    require_ack_response: false
    ignore_network_errors_at_startup: false

```
