### ISSUE TITLE
Clear Backup CR Reconciling condition when backup completes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28637]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Create a Backup CR, by specifying the an incorrect credential in S3 spec. (credential does NOT exist in rancher setup yet)
- The status of the CR is "Error"
- Now create a credential in rancher setup.
- Backup happens.
- But the state of the backup shows "Error" 
- View in YAML of the backup CR status is:
```
status:
  conditions:
  - lastUpdateTime: "2020-08-29T20:39:44Z"
    message: secrets "creds2" not found
    reason: Error
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2020-08-29T20:39:46Z"
    status: "True"
    type: Uploaded
```

**Expected Result:**
Backup should be seen in "Active" state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedde93`
- Installation option (single install/HA): HA rke
