### ISSUE TITLE
CISv2 - ClusterScan is seen in Failed state when there are no failures in the scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28656]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a ClusterScan CR and give in invalid value of `scanProfileName`
- The scan is currently stuck in "In progress" state
- Edit the clusterScan CR and give in the correct `scanProfileName: rke-profile-permissive`
- The scan run finishes, but the Cluster Scan is seen in "Failed state"

```
spec:
  scanProfileName: rke-profile-permissive
status:
  conditions:
  - lastUpdateTime: "2020-08-31T19:41:42Z"
    status: "True"
    type: Stalled
  - lastUpdateTime: "2020-08-31T20:36:39Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2020-08-31T20:36:49Z"
    status: "True"
    type: RunCompleted
  - lastUpdateTime: "2020-08-31T20:36:49Z"
    status: "True"
    type: Complete
  - status: Unknown
```

**Expected Result:**
ClusterScan should be in Pass/Active state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedde93`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom - 8 nodes - 3 etcd, 2 control and 3 worker nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```
