### ISSUE TITLE
CIS scan having failures is shown as Active on Dashboard UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#28652]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Repo: `https://github.com/prachidamle/charts.git` branch: `civ-v2-chart`
- Run a CIS 1.5 hardened scan on a cluster (failures expected as a hardening step was not run on the cluster)
- Test 5.3.2 fails.
- But the ClusterScan is in "Active" state

```
spec:
  scanProfileName: rke-profile-hardened
status:
  conditions:
  - lastUpdateTime: "2020-08-31T19:29:50Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2020-08-31T19:30:01Z"
    status: "True"
    type: RunCompleted
  - lastUpdateTime: "2020-08-31T19:30:01Z"
    status: "True"
    type: Complete
  - status: Unknown
    type: Alerted
  lastRunTimestamp: 2020-08-31 19:29:50.323980787 +0000 UTC m=+652.114686434
  observedGeneration: 1
  summary:
    fail: 1
    notApplicable: 20
    pass: 71
    skip: 0
    total: 92

```
- ClusterScanReport is also in "Active" state

**Expected Result:**
Cluster scan should be seen in "Failed" state

@prachidamle Question: Should we have the status of the corresponding cluster scan report also in "Failed" state? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - 8d9cedde931
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster 8 nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```
