### ISSUE TITLE
Backup stuck in "In Progress" state after disabling recurring backup 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#28666]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch backup-restore-operator app
2. Create a recurring backup specifying the schedule and retention count
```
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: sjrec
  namespace: default
#  annotations:
#    key: string
#  labels:
#    key: string
spec:
#  encryptionConfigName: string
   resourceSetName: ecm-resource-set
   retentionCount: 3
   schedule: "*/3 * * * *"



```
3. Edit the backup CR and disable the recurring backup by commenting the schedule and retentionCount fields

**Result:**
The backup is stuck in "In Progress state"

![Screen Shot 2020-08-31 at 6 48 56 PM](https://user-images.githubusercontent.com/18536626/91785928-4955e880-ebbb-11ea-8393-a787533bb84c.png)

Message seen in the UI
![Screen Shot 2020-08-31 at 6 54 42 PM](https://user-images.githubusercontent.com/18536626/91786025-8e7a1a80-ebbb-11ea-9d5f-f929b289da89.png)

No new backups are taken as we have disabled the recurring backup, but the "In Progress" state is displayed. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head(
Installation option (single install/HA):HA
