### ISSUE TITLE
fleet-examples are not properly deployed after following the quickstart guide

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28680]
cat kustomize.yaml

```
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kustomize
  namespace: fleet-local
spec:
  repo: "https://github.com/rancher/fleet-examples"
  bundleDirs:
    - kustomize
```

```
kubectl get deploy kustomize
Error from server (NotFound): deployments.apps "kustomize" not found
```

```
kubectl -n fleet-local get fleet
NAME                                REPO                                         COMMIT                                     BUNDLEDEPLOYMENTS-READY   STATUS
gitrepo.fleet.cattle.io/kustomize   https://github.com/rancher/fleet-examples    3614aa139d8bee616fc6849d54d8d836aedfd700   0/1                       NotApplied(1) [Bundle kustomize-kustomize: ]
gitrepo.fleet.cattle.io/simple      https://github.com/rancher/fleet-examples/   3614aa139d8bee616fc6849d54d8d836aedfd700   0/1                       NotApplied(1) [Bundle simple-simple: ]

NAME                                   CLUSTERS-READY   BUNDLES-READY   STATUS
clustergroup.fleet.cattle.io/default   0/1 (local)      0/4             NotApplied(4) [Bundle fleet-agent: ]
```
