### ISSUE TITLE
[Catalog][Chart] Error when handling string contains json

### ISSUE THREAD

**Issue by chanjarster** [rancher/rancher#28694]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

I created a helm chart and add questions.yml to utilize Rancher UI when deploy app.

The catalog url: https://github.com/chanjarster/rancher-chart-jsonstring.git
App name: jsontest

template:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jsontest.fullname" . }}
  labels:
  {{- include "jsontest.labels" . | nindent 4 }}
data:
  MODE3: {{ .Values.jsonconfig | squote }}
  MODE4: {{ .Values.jsonconfig | toJson | replace "\\n" ""  }}
```

values.yaml

```yaml
jsonconfig: "{}"
```

All I want is to pass a json string to the configmap, just like above. 

**Result:**

But Rancher report this error:

```txt
Failed to install app jsontest-jqw6x. Error: UPGRADE FAILED: failed to create resource: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found [, error found in #10 byte of ...|,"MODE4":[""]},"kind|..., bigger context ...|{"apiVersion":"v1","data":{"MODE3":"[]","MODE4":[""]},"kind":"ConfigMap","metadata":{"labels":{"app|...
```

**Other details that may be helpful:**

BTW, `helm install ` is OK. I suspect that Rancher doesn't handle json string right.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **v2.3.6**
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```
