### ISSUE TITLE
Improve reporting container errors (e.g. OOMKilled, Error)

### ISSUE THREAD

**Issue by tomikmar** [rancher/rancher#28731]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**

Just create container that needs more memory than memory limit, e.g.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools-ubuntu-depl
  labels:
    app: tools-ubuntu-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools-ubuntu
  template:
    metadata:
      labels:
        app: tools-ubuntu
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: tools-ubuntu
          image: ubuntu
          command: [ "sh", "-c", "tar cvf /tmp/a.tar /" ]
          resources:
            limits:
              memory: 4Mi
              cpu: 0.2
            requests:
              memory: 4Mi
              cpu: 0.1
```

**Result:**
When a container is killed/dies you only see something like "Error" or "OOMKilled" for very short time (sometimes a fraction of second). This is easy to miss and confusing for user. After that it is not possible to check what happened using only GUI.

There should be a way to get this information. For example it can be merged with Events. In addition having only "Error" doesn't help much. In this case it would be good to show also exit code, e.g. "Error (container exited with code: 1)".

![image](https://user-images.githubusercontent.com/5788375/92140377-4b18e980-ee11-11ea-97c6-c16896463126.png)

**Environment information**

Rancher v2.4.5
User Interface v2.4.28

**Cluster information**
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
