### ISSUE TITLE
Update Kiali to 1.23.0

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#28738]
Kiali [released](https://github.com/kiali/helm-charts/releases/tag/v1.23.0) version 1.23.0 

- [x] Mirror images in rancher/image-mirror repo
- [ ] Make changes to rancher/charts Kiali server chart (potentially external services in values.yaml) 
- [ ] Update Istio Chart.yaml and Values.yaml to use the most recent version of Kiali

**Comment by cbron** [comment]
Already tested

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ec04f78

* Values yaml now contains by default:
```
kiali:
  auth:
    strategy: anonymous
  deployment:
    ingress_enabled: false
    repository: rancher/kiali-kiali
    tag: v1.23.0
```
* Istio installs Kiali & Kiali CRDs from `v1.23`
```
SUCCESS: helm upgrade --install=true --namespace=istio-system --timeout=10m0s --values=/home/shell/helm/values-rancher-kiali-server-crd-1.23.001.yaml --version=1.23.001 --wait=true rancher-kiali-server-crd /home/shell/helm/rancher-kiali-server-crd-1.23.001.tgz
```
![Screen Shot 2020-09-28 at 4 16 04 PM](https://user-images.githubusercontent.com/21316915/94497230-6d511d80-01ab-11eb-8823-21abe277bfa7.png)
