### ISSUE TITLE
[Logging v2] - rancher-logging chart yaml error when enabling rke additional source

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28741]
**What kind of request is this:**
bug

**Steps to reproduce:**

```
helm install rancher-logging-crd https://charts.rancher.io/assets/rancher-logging/rancher-logging-crd-3.4.000.tgz --create-namespace=true --namespace=cattle-logging-system

helm install --create-namespace=true --namespace=cattle-logging-system rancher-logging -f values.yaml https://charts.rancher.io/assets/rancher-logging/rancher-logging-3.4.000.tgz
```

**Result:**

`Error: YAML parse error on rancher-logging/templates/loggings/rke1/logging-rke1.yaml: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context`

**Other details that may be helpful:**

`values.yaml`
```yaml
disablePvc: true
additionalLoggingSources:
  rke1:
    enabled: true
  rke2:
    enabled: false
  k3s:
    enabled: false
    container_engine: "systemd" # openrc or systemd
images:
  config_reloader:
    repository: rancher/jimmidyson-configmap-reload
    tag: v0.2.2
  fluentbit:
    repository: rancher/fluent-fluent-bit
    tag: 1.5.0
  fluentd:
    repository: rancher/banzaicloud-fluentd
    tag: v1.10.4-alpine-2
  syslog_forwarder:
    repository: rancher/fluent-bit-out-syslog
    tag: 0.1.0
global:
  systemDefaultRegistry: ""

```

**Environment information**
- Rancher version: `master-head (09/03/2020)` _ef11fe3b0_
- Installation option:  HA k8s 

**Cluster information**
- Cluster type: Infrastructure Provider (Downstream DO Linode)
- Machine type: VM 8gb RAM all roles
- Kubernetes version (use `kubectl version`): v1.17.9
