### ISSUE TITLE
Failed to provision volume with StorageClass "": No VM found

### ISSUE THREAD

**Issue by zzbmmbzz** [rancher/rancher#28773]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Config `Cloud Vsphere Provider` from existing clusters
Step:
1. set disk.enableUUID = TRUE
2. Edit Cluster ->  and add more configuration as bellow:
```yml
.....
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        example.local:
          datacenters: DATACENTER
          port: '443'
          soap-roundtrip-count: 0
          user: admin.kuber@example.local
          password: password
      workspace:
        datacenter: DATACENTER
        default-datastore: QNAP
        folder: /
        server: example.local
....
```
3. Then Save -> Waiting For Green Status
![image](https://user-images.githubusercontent.com/41033532/92373416-7a3c9d00-f128-11ea-9195-061f37d4e884.png)

4. Provision persistent volume and got error: `Failed to provision volume with StorageClass "": No VM found`
5. Check `ProviderID` and `UUID` and see that provider ID is null:
```
 kubectl get nodes -o json | jq '.items[]|[.metadata.name, .spec.providerID, .status.nodeInfo.systemUUID]' 
```
![image](https://user-images.githubusercontent.com/41033532/92372805-a9064380-f127-11ea-8ac3-6c3afc970c8b.png)

May I know what steps are missing. Thank you.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VMs (ubuntu 18.04, 8 cores, 16GB RAM) 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Docker version 19.03.5, build 633a0ea838
```
