### ISSUE TITLE
Allow the answer to a single question to be applied to multiple value targets

### ISSUE THREAD

**Issue by depeele** [rancher/rancher#28783]
This is a feature request that could be an alternative to full yaml anchor/alias support as requested in #27240

The primary issue our team faces is with umbrella charts intended to integrate multiple existing helm charts into a single functional unit.
In this use-case there are often multiple variables for the various sub-charts that will need to receive the same value.

One solution is to use yaml anchors/aliases in the umbrella `values.yaml` that are then used in chart-specific sections to propagate the common value down.

---
Another solution, proposed by this issue, would be to allow the answer to a single question in `questions.yaml` to be applied to multiple variables / value targets.

Perhaps something like:
```yaml
questions:
- variable: [ service.dn sub-chart.service.server.dn sub-chart2.ingress.dns.name ]
   default: "test"
   description: "The DNS domain name to apply to ingresses"
   type: string
   label: DNS domain name
```

or
```yaml
questions:
- variable:
   targets:
   - service.dn
   - sub-chart.service.server.dn
   - sub-chart2.ingress.dns.name
   default: "test"
   description: "The DNS domain name to apply to ingresses"
   type: string
   label: DNS domain name
```
