### ISSUE TITLE
Panic when import cluster that has nodegroups using a launch template

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#28801]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create cluster with eksctl that has one nodegroup

**Result:**
panic observed in eks-operator logs

**Other details that may be helpful:**
There will be another issue for further support of launch templates.
EDIT: https://github.com/rancher/rancher/issues/28803

**Comment by aaronRancher** [comment]
The bug is reproduced with Rancher server `rancher\rancher:v2.5.0-alpha1`

Steps:
Create an eks cluster using eksctl: `eksctl create cluster -f managed-cluster.yaml`
This cluster will have a node group with a default launch template.
![Screen Shot 2020-09-14 at 6 00 48 PM](https://user-images.githubusercontent.com/57409052/93152733-504d2280-f6b4-11ea-9b3f-44efd28756e0.png)

YAML:
```
# managed-cluster.yaml
# A cluster with two managed nodegroups
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aaron-managed-cluster4
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    labels:
      role: worker

```
Import cluster into Rancher.

Result:
Cluster is stuck provisioning
Observed panic in eks-operator logs
![Screen Shot 2020-09-14 at 5 46 40 PM](https://user-images.githubusercontent.com/57409052/93152744-5cd17b00-f6b4-11ea-9c23-47c96a430f8e.png)
