### ISSUE TITLE
Unable to provide multiple storage-opts/log-opts when creating host via UI or REST API

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#28859]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Try to configure docker storage driver or docker logger options via UI. The docker engine format for those require using the same flag more than once. This is an example for storage-opt but the same problem happens with log-opt --storage-opt dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true ...

"storage-driver": "devicemapper",
"storage-opts": [
"dm.thinpooldev=/dev/mapper/docker-thinpool",
"dm.use_deferred_removal=true",
"dm.use_deferred_deletion=true"
]
Attempting to set multiple storage-opt options results in only one of the options being used. When the same is attempted through the REST API with json the json array is converted into a string.

Looks like map[string] is being used as the data type which causes only one value to be used.

**Result:**
In the UI case only one value will be used from all the values set and depending on those options it can cause the Docker install on the new host to fail. When done through the REST API it causes a failure when installing docker due to the json array being converted to a string.

**Other details that may be helpful:**
This is also an issue in v1.6 https://github.com/rancher/rancher/issues/9892

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.6
- Installation option (single install/HA): HA

**Comment by junkiebev** [comment]
```yaml
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "200m",
    "max-file": "2"
  }
}
```
Basically want to do this so that disks don't get written full, and configure that to happen in Engine Options in a vmware node template.

**Comment by mattmattox** [comment]
@junkiebev 
You could create a shell script in the user-data to customize /etc/docker/daemon.json
Example:
```
cat <<EOF>>/etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "200m",
    "max-file": "2"
  }
}
EOF
chown root:root /etc/docker/daemon.json
chmod 0644 /etc/docker/daemon.json
```

**Comment by junkiebev** [comment]
Yes, or do it in the `cloud-init`, which we are:

```yaml
#cloud-config
write_files:
  - path: /etc/docker/daemon.json
    permissions: "644"
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "250m",
        "max-file": "5"
        }
      }
```

but it'd be nice to do it with `Engine Options` in the GUI as well
