### ISSUE TITLE
Applying host label scheduling rule to global load balancer doesn't work

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2886]
I have a load balancer service that was initially defined as follows:

```yaml
app-lb:
  ports:
  - 81:8080
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - app:app
  stdin_open: true
```

I then added the `io.rancher.scheduler.affinity:host_label: group=app` label to that definition and upgraded the service with:

```sh
rancher-compose up -d --upgrade app-lb
```

However, the upgrade has no effect. The app-lb containers are still running on every host, rather than only the hosts with the specified label. When I view the service configuration in the Rancher UI, the rule label is missing.

--
Rancher	v0.47.0
Cattle	v0.115.0
User Interface	v0.68.0
Rancher Compose	v0.5.3
