### ISSUE TITLE
[UI Bug] Misleading Alert regarding Etcd status with an external cluster

### ISSUE THREAD

**Issue by jgerry2002** [rancher/rancher#28936]
I've setup a new install of Rancher 2.48 on top of two K3s nodes. The K3s nodes are utilizing an _external_ three node Etcd cluster for the backing keystore database.

After install there is an endless alert posted on the dashboard for the rancher cluster.

"Alert: Component etcd-X is unhealthy"

![rancher-ui-bug](https://user-images.githubusercontent.com/10225304/93349555-9d8cd980-f805-11ea-94b2-9715c18cbfa6.png)

Yet "Etcd is not applicable" since this is an externally built Etcd cluster. There needs to be a check or flag regarding Etcd to figure out whether is installed within K3s or externally. It appears there is no difference hence the error. 

**Steps to reproduce (least amount of steps as possible):**
Create an external Etcd 3 node cluster as a key database for a rancher HA configuration.

Follow: https://rancher.com/docs/k3s/latest/en/installation/datastore/
Create two k3s nodes and utilize --datastore-endpoint option with http/https://etcd-node1:2379...
helm install rancher 

**Result:**
UI Alert for etcd that never clears

**Other details that may be helpful:**
Note that the documentation link has Postgres information in the Etcd section. The documentation should be updated with correct examples.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
2.48
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
`Self hosted on Vmware Vsphere 6.7x cluster. `

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
`Rhel 7, 2 vcpu/8gb ram/20GB disk`

- K3s/Kubernetes version:
```
clientVersion:
  buildDate: "2020-08-14T20:42:29Z"
  compiler: gc
  gitCommit: 6b595318666804506c19cfc3d3d228423d38fab1
  gitTreeState: clean
  gitVersion: v1.18.8+k3s1
  goVersion: go1.13.15
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-08-14T20:42:29Z"
  compiler: gc
  gitCommit: 6b595318666804506c19cfc3d3d228423d38fab1
  gitTreeState: clean
  gitVersion: v1.18.8+k3s1
  goVersion: go1.13.15
  major: "1"
  minor: "18"
  platform: linux/amd64
```

- Rancher version: 
```
helm --kubeconfig /etc/rancher/k3s/k3s.yaml list -n cattle-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
rancher cattle-system   1               2020-09-15 20:43:57.253799123 -0400 EDT deployed        rancher-2.4.8   v2.4.8
```

- Docker version (use `docker version`):
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

- Server: Docker Engine - Community
```
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
