### ISSUE TITLE
[rancher/charts] CRD charts with assumeOwnershipOfCRDs fail on hardened cluster

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29039]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Try to install `rancher-monitoring-crd` onto a hardened cluster

**Result:**
The CRD install and uninstall jobs fail due to the following error with the deployment specified by the Job that installs / uninstall the CRDs:
```
  containerStatuses:
  - image: rancher/kubectl:v1.18.6
    imageID: ""
    lastState: {}
    name: create-crds
    ready: false
    restartCount: 0
    state:
      waiting:
        message: container has runAsNonRoot and image will run as root
        reason: CreateContainerConfigError
```

**Other details that may be helpful:**
Fix is to add a securityContext such as:
```
securityContext:
    runAsNonRoot: true
    runAsUser: 1000
```

This only impacts charts that use a Job to install / uninstall onto the cluster, so `rancher-monitoring-crd` should be the only chart at the moment that experiences this.
