### ISSUE TITLE
Fix incorrect ownerReferences created for sharing global resources prior to 2.4.6

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#29122]
Up to 2.4.5, the Roles and RoleBindings created for sharing global resources had incorrect ownerReferences format. This bug is [fixed in 2.4.6](https://github.com/rancher/rancher/pull/27445). But the roles/rolebindings created prior to 2.4.6 (on 2.4.5 and earlier) don't get updated to use the right ownerRef. 
This can lead to errors when restoring using backup-restore, not functionality wise, because the actual resource and its role/rolebindings will get restored, but there will be error in logs and they won't get cleaned up (because of incorrect ownerRef format).
Update existing roles/rolebindings with incorrect ownerRefs to use the right ownerRefs

**Comment by sowmyav27** [comment]
**On master-head - commit id: `a2a141eb3c`**

- Deploy multicluster app and cluster template and revisions in 2.4.8
- Upgrade to master-head
- Owner references have changed for existing ones. 
- On deleting the cluster templates -template revisions are left behind
<img width="1487" alt="Screen Shot 2020-09-29 at 6 04 58 PM" src="https://user-images.githubusercontent.com/26032343/94633932-90e79700-0283-11eb-99fa-d3e5a8491545.png">
<img width="627" alt="Screen Shot 2020-09-29 at 6 08 14 PM" src="https://user-images.githubusercontent.com/26032343/94633939-93e28780-0283-11eb-99ed-256722bc5613.png">

- On deleting the multiclusterapp -multiclusterapp revisions are left behind

This issue is seen https://github.com/rancher/rancher/issues/26861. Reopening the issue

**Comment by mrajashree** [comment]
I see that the multiclusterapp revisions also have the wrong ownerRefs, that can be changed. But the clusterTemplateRevisions being left around is not a regression caused by this fix. I see it happening when I upgrade from 2.4.5 to v2.5.0-rc2 as well (which doesn't include the fix), where even if I delete a clustertemplate, the clustertemplaterevisions are left
<img width="1436" alt="Screen Shot 2020-09-29 at 10 25 13 PM" src="https://user-images.githubusercontent.com/10672776/94646390-02830d80-02a3-11eb-985e-62b74ece9da9.png">

**Comment by mrajashree** [comment]
I see the same on upgrade from 2.4.5 to 2.4.8 as well
<img width="1427" alt="Screen Shot 2020-09-29 at 10 51 18 PM" src="https://user-images.githubusercontent.com/10672776/94647918-580ce980-02a6-11eb-98a3-909d53267984.png">

**Comment by sowmyav27** [comment]
See this issue https://github.com/rancher/rancher/issues/29122#issuecomment-701109257 on an upgrade from 2.4.5 to 2.4.6 also.

**Comment by mrajashree** [comment]
The ownerReferences on multiclusterapprevisions are fixed. Prior to today's master-head they were of the format
```
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      kind: multiclusterapps
      name: datadogmcapp
      uid: 32cdd51f-b152-44fa-93bb-1054a3203541
```

With today's fix, they will have the right ownerRef format
```
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      kind: MultiClusterApp
      name: datadogmcapp
      uid: 32cdd51f-b152-44fa-93bb-1054a3203541
```

the revisions created before upgrade to today's master-head will be updated, and new ones will have right ownerRefs.

**Comment by sowmyav27** [comment]
### **On 2.4.5**
- Deploy a multicclusterapp and cluster template with revisions
- mcapprevision's owner reference was incorrect - 
- MultiClusterAppRevision
```
kubectl get multiclusterapprevisions mcapprevision-gh7hj -n cattle-global-data -o yaml
...
apiVersion: management.cattle.io/v3
kind: MultiClusterAppRevision
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: multiclusterapps
```
- Cluster template revision's owner reference is correct
```
kubectl get clustertemplaterevisions ctr-cd492 -n cattle-global-data -o yaml
apiVersion: management.cattle.io/v3
kind: ClusterTemplateRevision
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: ClusterTemplate
```

### Upgrade to master-head - commit id: `5044f25e6`
- mcapprevision's owner reference has been corrected
```
kubectl get multiclusterapprevisions mcapprevision-gh7hj -n cattle-global-data -o yaml
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: MultiClusterApp
```

- New mcapps and new cluster templates were deployed. And deleted. Revisions of these also got deleted.
- Existing mcapps and new cluster templates ' revisions not deleted when the resource is deleted. - known issue - https://github.com/rancher/rancher/issues/29269
