### ISSUE TITLE
RKE install: nginx-ingress-controller pods crashloop due to missing service account token

### ISSUE THREAD

**Issue by rust84** [rancher/rancher#29154]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Create a cluster for HA Rancher deployment using RKE (v1.1.7).

```
---
kubernetes_version: v1.15.12-rancher2-5

authentication:
  strategy: x509
  options: {}

authorization:
  mode: none
  options: {}

network:
  plugin: weave
  options:

nodes:
  - machine_name: ip-172-32-0-61.eu-west-1.compute.internal
    address: 34.242.x.199
    internal_address: 172.32.0.61
    user: ec2-user
    role: [etcd,controlplane,worker]
  - machine_name: ip-172-32-0-9.eu-west-1.compute.internal
    address: 3.249.x.133
    internal_address: 172.32.0.9
    user: ec2-user
    role: [etcd,controlplane,worker]
  - machine_name: ip-172-32-0-7.eu-west-1.compute.internal
    address: 3.249.x.99
    internal_address: 172.32.0.7
    user: ec2-user
    role: [etcd,controlplane,worker]

# Ensure key is available
ssh_key_path: ~/.ssh/key.pem

services:
  etcd:
    extra_args:
      election-timeout: "5000"
      heartbeat-interval: "600"

addon_job_timeout: 120
```

Wait until nginx-ingress-controller pods are running.

Install Rancher 2.4.8.

```
helm upgrade --install rancher --namespace cattle-system --set hostname=rancher.ourdomain.com --set privateCA=true --set tls=external rancher/rancher 
```

Restart one of the nginx ingress pods in the ingress-nginx namespace and watch as it errors and enters CrashLoopBackOff.

```
(∩｀-´)⊃ ❯ KUBECONFIG=kube_config_rancher-ha.yml k get po -n ingress-nginx
NAME                                    READY   STATUS             RESTARTS   AGE
default-http-backend-6ffd4cbc89-hc6wp   1/1     Running            0          11h
nginx-ingress-controller-npgsx          0/1     CrashLoopBackOff   19         74m
nginx-ingress-controller-rzfq7          1/1     Running            0          81m
nginx-ingress-controller-vdqzw          1/1     Running            0          81m
```

**Result:**

Nginx controller log shows that it is unable to find a valid service account token at the path `'/var/run/secrets/kubernetes.io/serviceaccount/token`.

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       0.32.0
  Build:         git-29dd9760f
  Repository:    https://github.com/rancher/ingress-nginx.git
  nginx version: nginx/1.17.10

-------------------------------------------------------------------------------

I0925 10:52:48.053653       6 flags.go:204] Watching for Ingress class: nginx
W0925 10:52:48.053935       6 flags.go:249] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)
W0925 10:52:48.053988       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0925 10:52:48.054027       6 client_config.go:548] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F0925 10:52:48.054125       6 main.go:272] Error while initiating a connection to the Kubernetes API server. This could mean the cluster is misconfigured (e.g. it has invalid API server certificates or Service Accounts configuration). Reason: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Refer to the troubleshooting guide for more information: https://kubernetes.github.io/ingress-nginx/troubleshooting/
```

Inspecting the nginx controller pod shows that no account tokens are mounted.

```
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:            <none>
```

One of the running pods looks like this and is using the default token.

```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-zgmfm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zgmfm
    Optional:    false
```

When inspecting the 'default' serviceaccount in the ingress nginx namespace I saw that automountServiceAccountToken is set to false. 

This means that the default serviceaccount token will not be mounted automatically. Reading the rancher docs I note that it is recommended to set this to false for hardening (https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/). We did not at any point set this ourselves however.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server

I tried changing automountServiceAccountToken to true however it was immediately changed back to false after saving.

```
apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-09-25T09:22:31Z"
    name: default
    namespace: ingress-nginx
    resourceVersion: "236756125"
    selfLink: /api/v1/namespaces/ingress-nginx/serviceaccounts/default
    uid: d181992e-5f53-47fd-b11a-3f58f87d722e
  secrets:
  - name: default-token-zgmfm
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Other details that may be helpful:**

I did some digging and came across this pull request https://github.com/rancher/rancher/pull/27336. That appears to block use of the default token in non system namespaces.

System namespaces are defined in the pull request as:

```
	SystemNamespaces                  = NewSetting("system-namespaces", "kube-system,kube-public,cattle-system,cattle-alerting,cattle-logging,cattle-pipeline,cattle-prometheus,ingress-nginx,cattle-global-data,cattle-istio,kube-node-lease,cert-manager,cattle-global-nt,security-scan")
```

I am not completely sure why it is having this effect because ingress-nginx is a system namespace so should be allowed. However to prove my point I scaled down Rancher and then tried to edit the serviceaccount again. This time the setting was saved and the following restart of the nginx controller pod got it back up and running again.

Scaling Rancher back up and pods are back to normal. We only noticed this by chance because one of the pods got restarted and we received an alert from the load balancer. In a worst case, if all nginx pods get restarted for an upgrade for example then the rancher frontend becomes unavailable. A temporary solution to at least disable the nsserviceaccount controller behaviour would be welcomed.  

```
(∩｀-´)⊃ ❯ KUBECONFIG=kube_config_rancher-ha.yml kubectl get po -n ingress-nginx
NAME                                    READY   STATUS    RESTARTS   AGE
default-http-backend-6ffd4cbc89-hc6wp   1/1     Running   0          11h
nginx-ingress-controller-j2b4r          1/1     Running   0          23s
nginx-ingress-controller-rzfq7          1/1     Running   0          111m
nginx-ingress-controller-vdqzw          1/1     Running   0          111m
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **2.4.8**
- Installation option (single install/HA): **HA**
