### ISSUE TITLE
[Logging V2] Update user roles

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#29168]
**edit: This issue now only exists now to handle case of if project-owner and project-member should be able to see ClusterOuput.**

---old----

- project members should not be able to create flows or outputs
- project owners should be able to create flows and outputs
- all users should be able to view flows, outputs, cluster flows and cluster outputs

**Comment by paynejacob** [comment]
https://github.com/rancher/charts/pull/699

**Comment by izaac** [comment]
Rancher version: `master-head (09/28/2020)` _ec04f78_ HA k8s with DO RKE Downstream cluster

I am not able to get clusterflows and clusteroutputs with project member or owner. Only flows and outputs from a namespace in the project they own or are member of.

Sample project member:

```
k get flows -A
Error from server (Forbidden): flows.logging.banzaicloud.io is forbidden: User "u-bx9pp" cannot list resource "flows" in API group "logging.banzaicloud.io" at the cluster scope

k get outputs -A
Error from server (Forbidden): outputs.logging.banzaicloud.io is forbidden: User "u-bx9pp" cannot list resource "outputs" in API group "logging.banzaicloud.io" at the cluster scope
k get outputs -n dummyapp-dev
```


In the UI I only see Flows and Outputs:


![Screen Shot 2020-09-28 at 4 34 00 PM](https://user-images.githubusercontent.com/27659/94496158-72609d80-01a8-11eb-90f3-0a7287d34322.png)

**Comment by izaac** [comment]
I have the latest roles update in my last Rancher setup, moving from Reopened to Test.

**Comment by izaac** [comment]
Rancher version: `master-head (09/28/2020)` _ec04f78_


Here's the cluster role for view

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: rancher-logging
    meta.helm.sh/release-namespace: cattle-logging-system
  creationTimestamp: "2020-09-29T01:42:43Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: logging-view
rules:
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - flows
  - outputs
  - clusterflows
  - clusteroutputs
  verbs:
  - get
  - list
  - watch
```

![Screen Shot 2020-09-28 at 6 43 56 PM](https://user-images.githubusercontent.com/27659/94503350-1b17f880-01bb-11eb-8bbd-ff7d08cd1f75.png)



# Cluster Owner

```
k get clusteroutputs.logging.banzaicloud.io -A

NAMESPACE               NAME         AGE
cattle-logging-system   archive      5m41s
cattle-logging-system   dev-team-a   5m41s
cattle-logging-system   security     5m40s

k get clusterflows.logging.banzaicloud.io -A
NAMESPACE               NAME       AGE
cattle-logging-system   app1       6m38s
cattle-logging-system   security   6m38s

k get flows -n dummyapp-dev
NAME           AGE
example-flow   10m

k get outputs -n dummyapp-dev
NAME        AGE
nsoutput1   10m
nsoutput2   10m
```


![Screen Shot 2020-09-28 at 6 49 45 PM](https://user-images.githubusercontent.com/27659/94503521-8366da00-01bb-11eb-8e8d-a03d6e3188b2.png)


# Cluster Member


```
k get clusteroutputs.logging.banzaicloud.io -A
Error from server (Forbidden): clusteroutputs.logging.banzaicloud.io is forbidden: User "u-hszh6" cannot list resource "clusteroutputs" in API group "logging.banzaicloud.io" at the cluster scope

k get clusterflows.logging.banzaicloud.io -A
Error from server (Forbidden): clusterflows.logging.banzaicloud.io is forbidden: User "u-hszh6" cannot list resource "clusterflows" in API group "logging.banzaicloud.io" at the cluster scope

k get outputs -n dummyapp-dev
Error from server (Forbidden): outputs.logging.banzaicloud.io is forbidden: User "u-hszh6" cannot list resource "outputs" in API group "logging.banzaicloud.io" in the namespace "dummyapp-dev"

k get flows -n dummyapp-dev
Error from server (Forbidden): flows.logging.banzaicloud.io is forbidden: User "u-hszh6" cannot list resource "flows" in API group "logging.banzaicloud.io" in the namespace "dummyapp-dev"
```

**(Can't access the  Logging overview)**
https://github.com/rancher/dashboard/issues/1492

![Screen Shot 2020-09-28 at 6 53 51 PM](https://user-images.githubusercontent.com/27659/94503790-24559500-01bc-11eb-9d8c-d9f6a50e2724.png)


# Project Owner

```
k get flows -n dummyapp-dev
NAME           AGE
example-flow   17m

k get outputs -n dummyapp-dev
NAME        AGE
nsoutput1   17m
nsoutput2   17m

k get clusterflows.logging.banzaicloud.io -A
Error from server (Forbidden): clusterflows.logging.banzaicloud.io is forbidden: User "u-jllp7" cannot list resource "clusterflows" in API group "logging.banzaicloud.io" at the cluster scope

k get clusteroutputs.logging.banzaicloud.io -A
Error from server (Forbidden): clusteroutputs.logging.banzaicloud.io is forbidden: User "u-jllp7" cannot list resource "clusteroutputs" in API group "logging.banzaicloud.io" at the cluster scope
```

![Screen Shot 2020-09-28 at 7 02 31 PM](https://user-images.githubusercontent.com/27659/94504245-34ba3f80-01bd-11eb-8005-a1a1dfc8872b.png)


# Project Member


```
k get flows -n dummyapp-dev
NAME           AGE
example-flow   19m

k get outputs -n dummyapp-dev
NAME        AGE
nsoutput1   19m
nsoutput2   19m

k get clusterflows.logging.banzaicloud.io -A
Error from server (Forbidden): clusterflows.logging.banzaicloud.io is forbidden: User "u-zmsxk" cannot list resource "clusterflows" in API group "logging.banzaicloud.io" at the cluster scope
k get clusteroutputs.logging.banzaicloud.io -A
Error from server (Forbidden): clusteroutputs.logging.banzaicloud.io is forbidden: User "u-zmsxk" cannot list resource "clusteroutputs" in API group "logging.banzaicloud.io" at the cluster scope
```

![Screen Shot 2020-09-28 at 7 04 06 PM](https://user-images.githubusercontent.com/27659/94504345-67fcce80-01bd-11eb-865a-e1241fead235.png)
