### ISSUE TITLE
[Monitoring V2] Use anonymous access by default in Grafana

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29165]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Currently, Grafana requires a user to log in with the default admin credentials (default password: `prom-operator`) in order to be able to view dashboards on Grafana. However, to access Grafana, a user anyways must have access to the service, which means that they must have been authenticated via the kube-proxy in order to access it in the first place.

Therefore, the default option for Grafana should be set to using anonymous authn; users should be able to set the configuration to use authn/authz only if that's what they require via the `values.yaml` or the chart deployment UI.

Namely, this just involves making the following change to the defaults:
```yaml
grafana:
  grafana.ini:
    users:
      auto_assign_org_role: Editor
    auth:
      disable_login_form: true
    auth.basic:
      enabled: false
    auth.anonymous:
      enabled: true
      org_role: Editor
```
