### ISSUE TITLE
[ Istio V2 ] Telemetry V2 is not enabled by default

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#29169]
IstioOperator config added the following section to enable and disable telemetry v1 and v2 separately:
```
telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        metadataExchange:
          wasmEnabled: false
        prometheus:
          enabled: true
          wasmEnabled: false
        stackdriver:
          configOverride: {}
          enabled: false
          logging: false
          monitoring: false
          topology: false
```
Using Mixer telemetry is deprecated in 1.7.x, but the Istio base-config file is only set up to enable and disable Mixer telemetry. This is incorrect and needs to be updated to enable/disable Telemetry V2 by default.

**Comment by bmdepesa** [comment]
rancher/rancher:master-head ec04f78

* Telemetry v2 is enabled by default in values YAML
```
telemetry:
  enabled: true
  v1:
    enabled: false
    repository: rancher/istio-mixer
    tag: 1.7.1
  v2:
    enabled: true
```

and Mixer is not deployed w/ Istio

* Upgrade the Istio installation and edit values YAML to include: 
```
telemetry:
  enabled: true
  v1:
    enabled: true
    repository: rancher/istio-mixer
    tag: 1.7.1
  v2:
    enabled: false
```
* Istio is updated and Mixer is deployed with `Container Image rancher/istio-mixer:1.7.1`
