### ISSUE TITLE
Rancher deployed Apps incorrectly add io.cattle.field/appId to NetworkPolicy selector specification

### ISSUE THREAD

**Issue by bmalynovytch** [rancher/rancher#29272]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
- Rancher v2.4.6
- deploy an app containing a NetworkPolicy definition from a custom v3 catalog

**Result:**
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/managed-by: Helm
    io.cattle.field/appId: test
  name: test
  namespace: test
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-controller
      podSelector:
        matchLabels:
          app: nginx-ingress
          io.cattle.field/appId: test
          release: nginx-ingress
    - podSelector:
        matchLabels:
          io.cattle.field/appId: test
          release: test
  podSelector:
    matchLabels:
      io.cattle.field/appId: test
      release: test
  policyTypes:
  - Ingress
```

**Other details that may be helpful:**
Probably related to rancher/rancher#28381 
When Rancher adds `io.cattle.field/appId` to `podSelector` for `nginx-ingress`, it mixes labels related to the deployed app and the targeted pod.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.6
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): N/A
- Kubernetes version (use `kubectl version`): N/A

gz#14513

**Comment by evhan** [comment]
We're running into this as well. In our situation Rancher is adding an `io.cattle.field/appId` label to our network policy's `matchLabels` clauses, but does *not* add it to the templated labels for jobs, meaning that (of course) the job pods can't connect.

We need for this label to be applied to neither or both, but it shouldn't *just* change the network policy.

**Comment by RoSk0** [comment]
For clarity, we noticed this behaviour on resources created by [Helm hooks](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks), particularly `post-install` one.

So maybe Rancher fails to apply additional labels only to those resources. I'm pretty sure this is the case because when the job created by the `post-install` hook times out and stuck and you manually delete the app that job resource is **not** deleted by Rancher but all other app resources are.

**Comment by beaniebag** [comment]
I'm having an issue with this as well.

It breaks the functionality for jupyterhub's kubernetes deployment.  Jupyterhub's kubespawner builds a new pod when a user signs in and the new pod is missing the io.cattlefieldapp label.  This causes the pod to be unable to communicate to the service due to this additional label.

**Comment by ztjohns** [comment]
I can verify this incorrect behavior. We had the exact same issue when launching an application via the catalog vs. using helm cli.

Rancher 2.4.5 and Helm 3.0.2

Additionally we tried to force the appId selector to be "null" in our helm chart, but it just gets overwritten. If you edit the yaml file after the app launch, you can remove the selector and everything should work fine, but obviously this is not a fix.

I commented on a [previous ticket](https://github.com/rancher/rancher/issues/28381), but it was incorrectly closed for a misunderstood bug

**Comment by beaniebag** [comment]
The workaround I did to atleast get this deployable was to add to the extraLabels in the helm chart (for jupyterhub).  This would add additional labels under the network policy selector.  As part of my answers.yaml I put:
extraLabels:
  io.cattle.field/appId: "jupyterhub"
A bit of a hack if rancher chooses to change the label naming convention, but only way I could get this to work

**Comment by evhan** [comment]
> The workaround I did to atleast get this deployable was to add to the extraLabels in the helm chart (for jupyterhub). This would add additional labels under the dynamically deployed pod. As part of my answers.yaml I put:
> extraLabels:
> io.cattle.field/appId: "jupyterhub"
> A bit of a hack if rancher chooses to change the label naming convention, but only way I could get this to work

We've done something similar, adding this `io.cattle.field/appId` label to the relevant resources whether one has `--set rancher=true` via Helm values. Not great, but at least it clearly isolates the workaround until this is fixed.

**Comment by macedonia3** [comment]
Hi,
@beaniebag, @evhan: I'm trying to apply your workaround but while using a custom io.cattle.field/appId  in metadata.labels and spec.selector sections, its get overridden.
I'm using Rancher 2.4.6 and Helm 3.2.0.

Can you give more details regarding the workaround?

Thanks.

**Comment by ztjohns** [comment]
> Hi,
> @beaniebag, @evhan: I'm trying to apply your workaround but while using a custom io.cattle.field/appId in metadata.labels and spec.selector sections, its get overridden.
> I'm using Rancher 2.4.6 and Helm 3.2.0.
> 
> Can you give more details regarding the workaround?
> 
> Thanks.

This is not a valid workaround for what you are experiencing.  This is the exact thing we are dealing with.

You can edit the deployed yaml manually and remove that appId selector and things will work, however this is a terrible long term work around for devops.

**Comment by macedonia3** [comment]
Yes, I agree.
I'm asking because it seems that @beaniebag and @evhan succeeded editing io.cattle.field/appId.
Maybe, it works with newer versions of Rancher/Helm?

**Comment by beaniebag** [comment]
@macedonia3
The workaround for me was dependent on the application's kubespawner and helm chart.
By default, all pods deployed by helm3 were getting the io.cattle.field/appId included.  The problem occurred because the jupyterhub application had a kubespawner that would deploy it's own pods (not by helm3) and was missing the io.cattle.field/appId label.
Luckily for me the helm chart had a extraLabels property that the kubespawner would use to include the additional labels for the pods it deployed.  I recommend seeing whether your helm chart has such a property first.  Otherwise, it would be require modifications or if possible deploy using Helm 2 instead.

**Comment by ztjohns** [comment]
> @macedonia3
> The workaround for me was dependent on the application's kubespawner and helm chart.
> By default, all pods deployed by helm3 were getting the io.cattle.field/appId included. The problem occurred because the jupyterhub application had a kubespawner that would deploy it's own pods (not by helm3) and was missing the io.cattle.field/appId label.
> Luckily for me the helm chart had a extraLabels property that the kubespawner would use to include the additional labels for the pods it deployed. I recommend seeing whether your helm chart has such a property first. Otherwise, it would be require modifications or if possible deploy using Helm 2 instead.

It sounds like you are having the opposite issue we were experience, where the appId was **_NOT_** being applied?   The issue for us, is the fact that the `spec: selector: io.cattle.field/appId` _**IS**_ getting applied to our _aliased_ services.   This restricts the scope of where the pointers look for that service to that appId (matching the pod we are in, not the one we want to point too).

**Comment by LeankitJSmith** [comment]
Rancher needs to not modify my application labels. There is absolutely zero reason for it. If you care so much about tainting my resources, set an annotation. This makes using Rancher Apps at all a very tough decision to justify. You need to fix this as soon as possible.
I have to manually modify the deployed Services to remove this stupid label in my Service's _selector_ array, just so that my apps can communicate. And I have to do it _again_ and every time after upgrading the app that deploys my Service.

**Comment by ouchuji** [comment]
> Rancher needs to not modify my application labels. There is absolutely zero reason for it. If you care so much about tainting my resources, set an annotation. This makes using Rancher Apps at all a very tough decision to justify. You need to fix this as soon as possible.
> I have to manually modify the deployed Services to remove this stupid label in my Service's _selector_ array, just so that my apps can communicate. And I have to do it _again_ and every time after upgrading the app that deploys my Service.

Mee too !!!

**Comment by konvergence** [comment]
Hi all,
I use rancher 2.5.7, and get the same issue.

My `app1` use a specific chart on the namespace `namespace1` 
So the labels for my app1 are 
- `io.cattle.field/appId: app1`
- `app.kubernetes.io/instance: namespace1`
- `app.kubernetes.io/name: app1`

I have a dedicated helm chart, just to declare egress network policy `egress-policy`
but this chart use the same namespace   `namespace1`

 When I try to set the `spec: podSelector:`
```
spec:
 podSelector:
  app.kubernetes.io/name: app1
```

But when the NetworkPolicy is created, I get that

```
spec:
 podSelector:
  app.kubernetes.io/name: app1
  io.cattle.field/appId: egress-policy
```

The result is that the NetworkPolicy the not applied correcly, because there no pod with these 2 labels

**Comment by izaac** [comment]
Reproduced on `2.5.8`

I used the gitea app to compare with `2.6 master-head`
Rancher is adding `io.cattle.field/appId` selector labels

```yaml
            matchLabels:
              app.kubernetes.io/component: primary
              app.kubernetes.io/instance: gitea
              app.kubernetes.io/name: postgresql
              io.cattle.field/appId: gitea
```


Rancher version: `2.6 master-head (07/15//2021)` _44bb5b4_
On this version the label is not added no the matchers by Rancher.

```yaml
            matchLabels:
              app.kubernetes.io/component: primary
              app.kubernetes.io/instance: gitea
              app.kubernetes.io/name: postgresql
```

I will validate on Rancher `2.5.10` in a separate issue.
