### ISSUE TITLE
Unable to use Privat Network Interface for Inter-host communication

### ISSUE THREAD

**Issue by venomone** [rancher/rancher#29274]
**Describe the bug**
If I deploy a new cluster or edit a existing one and I try to set the Private-IP Interface for inter-host communication, my config seems to get ignored. Every time the Deployment/Update of the cluster is done nothing seems to have changed, I still see that the deployment gets executed over the public interface/IP

**To Reproduce**
1. Go to 'Cluster > Edit Cluster '
2. Click on 'Edit as YAML'
3. Perform 'Update network: configs'
4. See nothing has changed

**Expected behaviour**
I setup private IP for inter-host communication like so:
```

  network:
    mtu: 0
    options:
      canal_flannel_backend_type: vxlan
      canal_iface: enp7s0
    plugin: canal
  restore:
    restore: false
```
But it seems that these settings have no effect, I would expect that the inter-host communication is done over the enp7s0 private network interface and not over my public interface

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: v1.18.8
 - Node OS type and version: Ubuntu 18.04.5
