### ISSUE TITLE
Exposed ports are not accessible locally on host server

### ISSUE THREAD

**Issue by y8** [rancher/rancher#2929]
Hi.

When Load Balancer container deployed, it's ports can't be reached locally, from the host server. 

To test, I've deployed the following:

````yml 
# docker-compose.yml
test-service:
  tty: true
  image: nginx
  stdin_open: true
balancer:
  ports:
  - '80'
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - test-service:test-service
  stdin_open: true
````

```` yml
# rancher-compose.yml
test-service:
  scale: 1
balancer:
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
````

It's deployed over 4 servers `host{n}`. On the `host0` I can curl other servers:

````
host0:~$ curl -I <host1_public_ip>
HTTP/1.1 200 OK
````

But on the `host0` itself, it fails:

````
host0:~$ curl -I <host0_public_ip>
curl: (7) Failed to connect to <host0_public_ip> port 80: Connection refused

host0:~$ curl -I 127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
````

Strangely, on this environment port can be reached by container IP. But in another one, with just one host, port can't be reached by container IP.

We're using ufw on the host server, but I've disabled it during the testing. Same result. 

Here `iptables -L` and `iptables -L -t nat`: https://gist.github.com/y8/b0546ef5993e9b720144

All host servers are identical:

````
3.19.0-33-generic #38~14.04.1-Ubuntu

Rancher: v0.47.0
Cattle: v0.115.0
User Interface: v0.68.0
Rancher Compose: v0.5.3

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
````

Thanks.

**Comment by y8** [comment]
Seems like `CATTLE_PREROUTING` rules are not matching on loopback interface.

**Comment by y8** [comment]
Yeah, thats the case: http://grainier.net/iptables-nat-prerouting-not-work-localhost/

**Comment by y8** [comment]
Also #147. But now it's closed without any resolution. :(

**Comment by y8** [comment]
For googlers: 

TL:DR: See: https://github.com/y8/rancher-localroute. This is temporary solution until issue is resolved by Rancher. Enable `net.ipv4.conf.all.route_localnet` and `net.ipv4.ip_forward`, reboot host and then fire this compose file on all your environments:

````yml
rancher-localroute:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: yopp/rancher-localroute:0.1.0
  privileged: true
  stdin_open: true
  net: host
````

Long part:

This issue is huge pain in the ass: _all_ the services on the same host can't talk to each other using the public IP. Route53 for service discovery? Ha-ha. Good luck debugging randomly failed services with cryptic "connection refused" errors. I don't know why #147 was closed, but this is must be addressed as soon as possible.

There two options here:

1. Opt-out style `docker-proxy` option for exposed ports.
2. Mandatory `route_localnet` on host system and two extra iptables rules per port: one to route locally generated packages to the IPSec network (OUTPUT DNAT), and one to change source address from loopback to //some// IPSec routable address, so target container can respond to the real source host, not the loopback (PREROUTING SNAT).

  Example:

  ````
-t nat -A POLLER_OUTPUT
       -d 127.0.0.1 
       -p %{proto} 
       --dport %{source_port} 
       -j DNAT 
       --to %{dest_address}:%{dest_port}"

-t nat -A POLLER_POSTROUTING
       -d %{dest_address} 
       -p %{proto} 
       --dport %{dest_port} 
       -j SNAT 
       --to-source %{host_public_ip}"
  ````

I don't know anything about possible side-effecs of enabling `route_localnet`, but it seems like the best solution, because it requires couple extra lines in the https://github.com/rancher/cattle/blob/master/resources/content/config-content/host-iptables/content-home/etc/cattle/host-iptables.ftl. 

Additionally `route_localnet` flag must be verified upon network-agent start. On our ubutnu hosts changing the `net.ipv4.conf.all.route_localnet` had no effect until the reboot. I've tried restarting networking service, but without any luck. It might be related to the `veth` interface management.

I'm bad on shell scripting, so I've made a small container with simple ruby script inside. It polls the `CATTLE_PREROUTING` chain and updates `POLLER_OUTPUT` and `POLLER_PREROUTING` accordingly. See https://github.com/y8/rancher-localroute. Quick and dirty, but works on our ubuntu cluster.

Cheers.
