### ISSUE TITLE
[Logging v2] - Deploy to control plane nodes is always active even then unchecked when installing

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29297]
Rancher version `master-head (09/19/2020)` _bd88c23_

 - Install Rancher HA k8s.
- Downstream cluster is RKE DO or k3s/rke2/EKS
- Navigate to Dashboard and Apps
- Click `rancher-logging`
- Chart Options leave `Deploy to control plane nodes` unchecked
- Preview YAML

Values YAML generates:

```yaml
additionalLoggingSources:
  eks:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: true
  rke:
    enabled: false
  rke2:
    enabled: false
.....
```

![Screen Shot 2020-09-19 at 8 02 22 PM](https://user-images.githubusercontent.com/27659/93693327-3a27d380-fab3-11ea-9212-89b174b67cdd.png)

![Screen Shot 2020-09-19 at 8 03 34 PM](https://user-images.githubusercontent.com/27659/93693329-3dbb5a80-fab3-11ea-9e6b-808ab8b4d91e.png)
