### ISSUE TITLE
[Monitoring V2] Add default dashboard on Grafana Homepage

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#29308]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

The default Grafana page should show some Rancher Monitoring specific dashboards. We can configure this via the `grafana.ini` in the following way on chart deployment (where home.json is the key on the ConfigMap that stores the dashboard):

```yaml
grafana:
  grafana.ini:
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/home.json 
```

![Bildschirmfoto 2020-10-01 um 17 28 08](https://user-images.githubusercontent.com/13127443/94849064-b25a9700-03d9-11eb-851e-3894ae39d2a1.png)

Thanks @bashofmann for coming up with the dashboard!
