### ISSUE TITLE
APP Traefik: Basic auth

### ISSUE THREAD

**Issue by Dogy007** [rancher/rancher#29314]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Launch traefik app via GUI, try to add basic auth for Dashboard

**Result:**
Error while deploying, "could not iterate over user: $pas$$word"

**Other details that may be helpful:**
Template version: Traefik 1.0.0

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
V2.4.8
- Installation option (single install/HA):
 Single

- Docker version (use `docker version`):
19.03.13

Steps to Resolve the Issue:

Edit as yaml

Change The Following:
From 
```
  dashboard: 
    enabled: true
    domain: "traefik.example.domain"
    auth: 
      basic: "user:$encryptedPassword"
```

To:

```
  dashboard: 
    enabled: true
    domain: "traefik.example.domain"
    auth: 
      basic: 
       user: $encryptedPassword
```
