### ISSUE TITLE
Console Logs shows error on system:k3s-controller is invalid: roleRef

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rancher#29359]
Version:
```
rancherd -v
rancherd version v2.5.0-rc6 
```
Issue:
Console log displays errors on  failed to process /var/lib/rancher/rke2/server/manifests/rolebindings.yaml
Cluster is up

```
kubectl get clusterrolebinding |grep k3s-controller
system:k3s-controller                                  ClusterRole/system:rke2-controller                                 56m

kubectl get nodes
NAME               STATUS   ROLES         AGE   VERSION
ip-172-31-25-239   Ready    etcd,master   64m   v1.18.9-rc1+rke2
```
Steps to reproduce:
```
curl -sfL https://get.rancher.io | sh -
rancherd server
```

Console Logs:
```
ERRO[3337] Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rolebindings.yaml: failed to update system:k3s-controller rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding for  kube-system/rolebindings: ClusterRoleBinding.rbac.authorization.k8s.io "system:k3s-controller" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system:k3s-controller"}: cannot change roleRef 
ERRO[3352] Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rolebindings.yaml: failed to update system:k3s-controller rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding for  kube-system/rolebindings: ClusterRoleBinding.rbac.authorization.k8s.io "system:k3s-controller" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system:k3s-controller"}: cannot change roleRef 
ERRO[3367] Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rolebindings.yaml: failed to update system:k3s-controller rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding for  kube-system/rolebindings: ClusterRoleBinding.rbac.authorization.k8s.io "system:k3s-controller" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system:k3s-controller"}: cannot change roleRef 
```

Additional info:
```
kind: ClusterRoleBinding
metadata:
  name: kube-apiserver-kubelet-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-apiserver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:k3s-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - list
  - get
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:k3s-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:k3s-controller
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:k3s-controller
```
