### ISSUE TITLE
rancher in rancher not working in v2.5.x

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#29474]
In earlier releases of Rancher, I was able to start rancher using `kind: Deployment` (see below for full manifest) inside a cluster managed by Rancher. 

With v2.5.x, I am not able to do the same. (I did add `privilged: true` as pointed out in the docs, and also added memory limits as a workaround for: https://github.com/rancher/k3s/issues/1164)

**Older manifest:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher2dotx
  name: rancher
spec:
  selector:
    matchLabels:
      app: rancher2dotx
  template:
    metadata:
      labels:
        app: rancher2dotx
    spec:
      automountServiceAccountToken: false
      containers:
      - image: rancher/rancher:v2.3.5
        imagePullPolicy: IfNotPresent
        name: rancher
---
apiVersion: v1
kind: Service
metadata:
  name: np-rancher2dotx
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
  selector:
    app: rancher2dotx
```

**Current manifest:**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher2dotx
  name: rancher
spec:
  selector:
    matchLabels:
      app: rancher2dotx
  template:
    metadata:
      labels:
        app: rancher2dotx
    spec:
      automountServiceAccountToken: false
      containers:
      - image: rancher/rancher:v2.5.1
        imagePullPolicy: IfNotPresent
        name: rancher
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: np-rancher2dotx
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
  selector:
    app: rancher2dotx
```
