### ISSUE TITLE
can not deploy local-cluser

### ISSUE THREAD

**Issue by minchieh-fay** [rancher/rancher#29534]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.1` UI: `v2.5.0` |
|Route|`undefined`|

1.Offline, Air Gapped Environment
2. only one node
3.  install rancher by docker
4.  when rancher is ok, i choose 'LOCAL' to run, emmm, this 'LOCAL' cluser cannot pull image form my private-register to deploy app, include system-namespace's "myreg:8080/rancher/shell:v0.1.4".  I run rancher had set "CATTLE_SYSTEM_DEFAULT_REGISTRY=myreg:8080", but not work
5. I try to edit this 'LOCAL' , but no place to set private-register

**Comment by minchieh-fay** [comment]
i resolve it by add /etc/rancher/k3s/registries.yaml like:
```
mirrors:
  docker.io:
    endpoint:
      - "http://mycustomreg.com:5000"
configs:
  "mycustomreg:5000":
    auth:
      username: admin
      password: 123456
```
in namespace `cattle-system` is all ok now, but in namespace `kube-system`, the pod `coredns` is not ok, because his image not had {host}, but 'rancher/coredns-coredns:1.6.9'
he need be `mycustomreg:5000/rancher/coredns-coredns:1.6.9` too!!!
now i manully to modify it, it works, does offical can fix this bug?
