### ISSUE TITLE
Degraded stack when using only run once containers

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#2957]
I have a stack that only contains run once containers. The stack reports as degraded since nothing else is running.

It would be nice to keep a stack as healthy if:

1. Stack only has run once containers
1. None of the containers have exited non-zero

**Comment by deniseschannon** [comment]
What version of Rancher are you running? I don't see this issue in v0.49.1 (latest).

**Comment by andyshinn** [comment]
I'm on v0.49.1. The container is exiting 0. I'll try and create simple project to reproduce it.

**Comment by andyshinn** [comment]
Here is a pretty simple reproduce:

```yaml
runonce:
  restart: no
  image: alpine:3.2
  command: sh -c 'echo Run once'
  labels:
    io.rancher.container.start_once: true
runforever:
  command: sh -c 'while true; do echo Keep running; sleep 5; done'
  image: alpine:3.2
```

Which yields:

![image](https://cloud.githubusercontent.com/assets/315485/11754736/1f7c45d6-a002-11e5-8bd4-30b4c3f0b7ab.png)
