### ISSUE TITLE
[2.5.1] Cannot Delete Cluster (using terraform) since coredns cannot run on control-plane nodes

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#29584]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster (using terraform) with one control plane pool (control + etcd) and one worker pool using vsphere node template. After it comes up destroy the cluster.

**Result:**
The worker pool is deleted which causes the cluster-agent to not run. Rancher starts throwing errors saying `waiting for cluster [c-gq2bw] agent to connect`. Since the worker pool has been deleted it will never be able to run and never be able to connect. Rancher wont delete the nodes cause it is waiting.

```
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node dev-k8s-c02-cp-3: "-dev-k8s-c02-cp-3" not found]]
```

**Other details that may be helpful:**
The fix here is to make sure the cluster-agent has toleration to run on the control-nodes. Another option would be for rancher to ignore the agent missing if all node pools are marked for deletion.

Terraform will delete the resources backwards in order for example worker, then deletes control-plane pool. The cluster isn't actually marked for deletion yet since that would be last after the node pools are removed. This seems like a race condition around rancher wanting to manage the cluster and terraform just trying to destroy the cluster resources.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.19.2 (rancher version)

**Comment by superseb** [comment]
Given the `cattle-cluster-agent` Deployment contains of:

```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/os
                  operator: NotIn
                  values:
                    - windows
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/controlplane
                operator: In
                values:
                - "true"
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/etcd
                operator: In
                values:
                - "true"
      tolerations:
      - operator: Exists
```
I don't understand why it can't run. What error does it show when its being scheduled that indicates it cannot run? To avoid any misinterpretation, please provide example code and versions used of all components involved that can be used to reproduce including logging that you used to confirm the statements.

**Comment by mitchellmaler** [comment]
@superseb Good call on that. I should of dug a bit more. 
I just tested a rancher provisioned rke cluster with just 1 control-plane node (etcd+control). This should at least bring the cluster up even though there isn't a worker.

The UI is showing this which is the basic error:
```
This cluster is currently Error; areas that interact directly with it will not be available until the API is ready.
Cluster health check failed: cluster agent is not ready
```

I was able to get the admin config from the secret that rancher created and found the issue.

It isn't the cluster-agent but is the coredns pods. Since the worker or worker pool has been removed the coredns pods have no where to schedule too since they do not include tolerations to run on control-plane nodes. If the cluster-agent was running on a worker node it would be deleted/drained and moved to a master but without working cluster dns it cannot resolve rancher and hit the /ping endpoint. 

### pods
```
cattle-system   cattle-cluster-agent-6db6c86f57-stzdc     0/1     CrashLoopBackOff   9          23m
cattle-system   cattle-node-agent-zhkww                   1/1     Running            0          23m
cattle-system   kube-api-auth-vq7tr                       1/1     Running            0          23m
kube-system     calico-kube-controllers-8868bdc57-v9vjc   1/1     Running            0          24m
kube-system     canal-hlznn                               2/2     Running            0          24m
kube-system     coredns-8544b74885-rsbwh                  0/1     Pending            0          23m
kube-system     coredns-autoscaler-5fb8c46699-h76w4       0/1     Pending            0          23m
kube-system     metrics-server-c7999db78-f68g4            0/1     Pending            0          23m
kube-system     rke-coredns-addon-deploy-job-wnbtd        0/1     Completed          0          24m
kube-system     rke-metrics-addon-deploy-job-72bzl        0/1     Completed          0          23m
kube-system     rke-network-plugin-deploy-job-z642v       0/1     Completed          0          24m
```

### coredns tolerations
```
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
```
 
So either coredns needs tolerations or Rancher server needs to ignore the cluster not being accessible if all pools are deleted.


My only work around to delete the cluster is to remove the finalizers from the rancher node objects and manually delete the VMs myself.
