### ISSUE TITLE
Support for Fedora CoreOS

### ISSUE THREAD

**Issue by olivierlemasle** [rancher/rancher#29593]
Some issues related to the support of Fedora CoreOS have been recently fixed:
- https://github.com/rancher/rke/issues/2194 in RKE
- https://github.com/rancher/machine/pull/97 and https://github.com/rancher/machine/pull/98 in rancher/machine

Here is a list of current limitations with Rancher and Fedora CoreOS:

1. Need to specify a custom flex-volume-plugin-dir for Canal/Calico: cf. #25681

   E.g in RKE template:
   ```
   network:
     plugin: canal
     options:
       canal_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
       flannel_backend_type: vxlan 
   services:
     kube-controller:
       extra_args:
         flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
   ```

1. As Fedora CoreOS does not support cloud-init, rancher-machine drivers that depends on cloud-init, such as `vmwarevsphere`, cannot work (#26735). Other providers work (tested only with `amazonec2`)

1. I had to disable the Fedora CoreOS auto-update service or specify an [update strategy](https://coreos.github.io/zincati/usage/updates-strategy/) (e.g. tested with [poseidon/fleetlock](https://github.com/poseidon/fleetlock)). Otherwise, the VM was updated and rebooted automatically just after its first boot, and rancher-machine could not complete its configuration. I also configured Fedora CoreOS to enable docker service, because it is active after `rancher-machine create` but inactive after reboot.

1. There is also an issue with Canal/Flannel. Cf:
   - https://github.com/coreos/flannel/issues/1155 / https://github.com/coreos/flannel/issues/1321
   - https://github.com/rancher/rke/issues/2270
   - https://github.com/poseidon/typhoon/commit/78e6409bd0abac23451951dc93748513d238bcec#diff-149624b2865445eeec93184c0504e405
   - https://github.com/coreos/fedora-coreos-tracker/issues/574#issuecomment-665487296
   
   This is fixed whendding a file `/etc/systemd/network/50-flannel.link` with the following content:

   ```
   [Match]
   OriginalName=flannel*
   [Link]
   MACAddressPolicy=none
   ```

1. For the last two items, I had to use Ignition:

   ```
   variant: fcos
   version: 1.1.0
   systemd:
      units:
       - name: docker.service
         enabled: true
   storage:
     files:
       - path: /etc/systemd/network/50-flannel.link
         mode: 0644
         contents:
           inline: |
             [Match]
             OriginalName=flannel*
             [Link]
             MACAddressPolicy=none
       - path: /etc/zincati/config.d/55-updates-strategy.toml
         mode: 0644
         contents:
           inline: |
             [updates]
             enabled = false
   ```
   
   And after [transpiling](https://docs.fedoraproject.org/en-US/fedora-coreos/using-fcct/), I had to pass the Ignition file as amazonec2 `userdata` (escaping the content and using the Rancher API, as this is not available in Rancher UI)

After these configuration steps, my 3-nodes RKE cluster on Amazon EC2 worked well with Fedora CoreOS (using [`rancher/rancher:v2.4-head` - f210f54bd ](https://github.com/rancher/machine/pull/97#issuecomment-710685414))

I don't know if these steps should be added in Rancher documentation, or if Rancher itself can make things easier (e.g. making userdata customizable using UI)
