### ISSUE TITLE
Make more ciphers available for ingress TLS

### ISSUE THREAD

**Issue by matfiz** [rancher/rancher#29698]
**What kind of request is this (question/bug/enhancement/feature request):**
I need to make more ciphers available on my TLS ingress. Namely, I need to add `ECDHE-ECDSA-AES256-GCM-SHA384`
**Steps to reproduce (least amount of steps as possible):**
I have added the following lines to my `cluster.yml`:

```yaml
  ingress:
    options:
      ssl-ciphers: >-
        ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS
      ssl-protocols: TLSv1.2 TLSv1.3
    provider: nginx
```
This resulted in adding the correct options to `nginx-configuration` ConfigMap. Also, the changes are reflected in `nginx.conf`.

However, both SSL Labs and `nmap` are still showing the limited number of cipher suites: 
```
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
```

I have also checked through API: `v3/settings/tls-ciphers` but it lists the correct ciphers:
```json
{"value": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"}
```
**Result:**
In nginx-ingress-controller terminal, I can see:
```
bash-5.0$ cat /etc/nginx/nginx.conf | grep cipher
        # allow configuring custom ssl ciphers
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
```

Nmap results:
```
nmap --script ssl-enum-ciphers -p 443 api-minesider.beta.grontpunkt.no
Starting Nmap 7.80 ( https://nmap.org ) at 2020-10-22 13:05 CEST
Nmap scan report for api-minesider.beta.grontpunkt.no (82.163.160.141)
Host is up (0.042s latency).
rDNS record for 82.163.160.141: 141.160.163.82.customer.static.mhhosting.dk

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 1.89 seconds
```
**Other details that may be helpful:**
How can I make more ciphers visible? What is limiting the listed ciphers? I have tried to find help through Rancher Slack, but no one could help.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 nodes 4 cores/8GB RAM each
- Kubernetes version (use `kubectl version`): v1.19.3
- Docker version (use `docker version`): 19.3.13
