### ISSUE TITLE
[Master] Ingress Status Load Balancer IPs Not Being Updated

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29714]
Tracking remaining issue on master for: 
https://github.com/rancher/rancher/issues/28230#issuecomment-712501176
https://github.com/rancher/rancher/issues/26677#issuecomment-712485488

**Comment by sowmyav27** [comment]
**On master-head commit id: `5aa3918`**

- Deploy a 2 worker node cluster.
- Enabled Project Network Isolation
- Pod name label is seen on the ingress-controller in System project.
- Labels:

```
labels:
    app: ingress-nginx
    controller-revision-hash: 5dd9dd4479
    field.cattle.io/podName: nginx-ingress-controller-kmj7k
    pod-template-generation: "1"
```

- Deploy a GDNS - provider and entry
- The A record for the GDNS provider points to only one worker node

Reopening the issue.
