### ISSUE TITLE
Rancher's alerting intervals have no effect

### ISSUE THREAD

**Issue by hatharom** [rancher/rancher#29785]
**In short:**  Interval/wait time settings have no effect at all. Alerts will be sent by some strange,random settings.

**In details:**
Rancher's alerting system has these advanced configuration:

**Group Wait Time :** How long to wait to buffer alerts of the same group before sending initially.
**Repeat Interval Time:** How long to wait before re-sending a given alert that has already been sent.
**Group Interval Time:** How long to wait before sending an alert that has been added to a group which contains already fired alerts.

I created an alert for a Pod , which will send an alert when warning event happens. I started out with the default interval configurations inherited from the group.

Then I changed my POD manifest and the image name to a non-existent one, to make the pod fail and generate events.
Events occured :

![kép](https://user-images.githubusercontent.com/15161542/97338144-76540e00-1881-11eb-8c40-1c9cc04131fd.png)

Events appeared correctly, the POD alert turned into 'alerting' state and I started to receive the message to my email account. Got ~20 message - with a counter in them - for 4 different warning events.
So far so good.

Then I restarted the same process as above, but before that I changed the advanced settings to 10minutes, just to test out whether it will delay anything (I tested these as inherited and as not-inherited):
**Group Wait Time :** 600s
**Repeat Interval Time:**  600s
**Group Interval Time:**  600s

And it has no effect at all. After the image pull fails, it immediatly started to send the same ~20 message to my email account.
It just doesn't wait for anything defined in the interval settings. Neither for the initially buffering nor for resending the same event.

```
Alert Name: my-pod
Severity: warning
Cluster Name: minikube-cluster (ID: c-rfj9g)
Workload Name: my-postgresql
Target: rancherbug:my-postgresql-0
Count: 1
Event Message: Error: ImagePullBackOff
First Seen: 2020-10-27 16:07:46 +0000 UTC
Last Seen: 2020-10-27 16:07:46 +0000 UTC

Alert Name: my-pod
Severity: warning
Cluster Name: minikube-cluster (ID: c-rfj9g)
Workload Name: my-postgresql
Target: rancherbug:my-postgresql-0
Count: 2
Event Message: Error: ImagePullBackOff
First Seen: 2020-10-27 16:07:46 +0000 UTC
Last Seen: 2020-10-27 16:08:12 +0000 UTC

Alert Name: my-pod
Severity: warning
Cluster Name: minikube-cluster (ID: c-rfj9g)
Workload Name: my-postgresql
Target: rancherbug:my-postgresql-0
Count: 3
Event Message: Error: ImagePullBackOff
First Seen: 2020-10-27 16:07:46 +0000 UTC
Last Seen: 2020-10-27 16:09:03 +0000 UTC
...
...
..etc
```

The same applies to the other events as well.
As you can see i received the same events and only 20-50sec are between them.

How are these interval settings supposed to work? What are the purpose of them?
Seems totally useless currently.

version: Rancher 2.4.5, 2.4.8

**Comment by hatharom** [comment]
Checking the alertmanager-cluster-alerting's log

`level=warn ts=2020-10-27T17:23:00.005Z caller=main.go:452 component=configuration msg="repeat_interval is greater than the data retention period. It can lead to notifications being repeated more often than expected." repeat_interval=146h0m0s retention=24h0m0s route="{}/{group_id=\"c-rfj9g:cag-kpsgd\"}/{rule_id=\"c-rfj9g:cag-kpsgd_car-w2bks\"}"`

**Comment by hatharom** [comment]
Checked the alertmanager.yml created by rancher and it looks like this:

```
route:
  receiver: rancherlabs
  routes:
  - receiver: c-jhbll:cag-fb6rn
    group_by:
    - group_id
    match:
      group_id: c-jhbll:cag-fb6rn
    continue: true
    routes:
    - group_by:
      - rule_id
      - resource_kind
      - target_namespace
      - target_name
      - event_message
      match:
        rule_id: c-jhbll:cag-fb6rn_car-pbxsh
      continue: true
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 146h
    group_wait: 10m
    group_interval: 10m
    repeat_interval: 10m
  group_wait: 10m
  group_interval: 10m
  repeat_interval: 10m
```

The bottom two group of settings with the '10m' comes from my Alert configuration
But as you can see there is an additional entry with 1s,1s,146h.   
What the heck is that?
Where can I configure that?
