### ISSUE TITLE
Container fails when using a named volume on a sidekick container

### ISSUE THREAD

**Issue by gcallsen** [rancher/rancher#2980]
I'm unable to get any useful logs to help track down the error, but the context is:

docker-compose.yml

    postgres-data:
        ..
        volume_driver: local
        volumes:
            - "postgres_data:/data/db"

    postgres:
        ...
        labels:
            ...
            io.rancher.sidekicks: postgres-data
        volumes_from:
            - postgres-data

When launching this service the `postgres-data` container tries to start and immediately fails/is removed.

If, instead, the `postgres-data` container exposes a standard volume, it works correctly

    postgres-data:
        ...
        volumes:
            - /data/db

* Named volume was manually created on the host
* Docker version 1.9.0
* Rancher version 0.49.0
* Rancher-compose version 0.6.0

**Comment by deniseschannon** [comment]
Can you share your entire docker-compose.yml?

I have been unable to reproduce your issue. I am using Rancher v0.50.2, Rancher-Compose v0.6.2 and Docker 1.9.1.

We strongly recommend upgrading to Docker 1.9.1. 

```
postgres:
  environment:
    POSTGRES_PASSWORD: mysecretpassword
  labels:
    io.rancher.sidekicks: postgres-data
  tty: true
  image: postgres
  volumes_from:
  - postgres-data
  stdin_open: true
postgres-data:
  environment:
    POSTGRES_PASSWORD: mysecretpassword
  tty: true
  image: postgres
  volumes:
  - postgres_data:/data/db
  stdin_open: true
  volume_driver: local
```
