### ISSUE TITLE
[cli] Unable to configure location of .cache/token

### ISSUE THREAD

**Issue by tjcain** [rancher/rancher#29807]
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Steps to reproduce (least amount of steps as possible):**
using 
```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - token
        - --server=<server>
        - --user=<user>
      command: rancher
```
in kubeconfig

```
kubectl --kubeconfig ./config get ns
https://<auth-provider>
Enter auth provider
... complete log in flow
```

```
cd some/other/directory
kubectl get ns
```
**Result:**
```
kubectl get ns
https://<auth-provider>
Enter auth provider
... complete log in flow
```

**Other details that may be helpful:**
Being able to configure the location of the .config directory rancher cli looks for via a flag or envvar would prevent having to re-log in upon changing directory.

I have submitted https://github.com/rancher/cli/pull/287 to suggest a possible change.
