### ISSUE TITLE
[Dashboard] RFE Support specifying UI images path in Rancher Helm Chart

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29813]
Tracking the RFE [here](https://github.com/rancher/rancher/issues/29419#issuecomment-717631419) for Cluster explorer

**Comment by jiaqiluo** [comment]
wait for a v2.5.4-rc to validate the changes in the chart.

**Comment by jiaqiluo** [comment]
Failed to validate this enhancement on `v2.5.4-rc2` and we need instruction on how to configure the local cluster to use this feature. 

Because we start using `subpath` in the volume, so we cannot use [hostpath Volume](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) to validate it, and [here is why](https://github.com/rancher/rancher/issues/14836#issuecomment-624186494)

Instead, I tried to use the [local storage class](https://github.com/rancher/rancher/issues/14836#issuecomment-624186494), but it also did not work.

Here is what I have tried and how it failed:
- create a 1-node rke cluster
- create the storage class

```
> cat local-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

- create the dir `/jiaqi-test` on the node and chmod 777
- create the PV,

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-1
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jiaqi-test"
```

- install rancher

```
helm install rancher rancher-latest/rancher \
--version v2.5.4-rc2 \
--namespace cattle-system \
--set hostname=jack-ha.qa.rancher.space \
--set customLogos.enabled=true \
--set customLogos.storageClass=local-storage
```

But rancher’s pod cannot run up and shows this error

```
 Warning  Failed     11s (x3 over 13s)  kubelet            Error: stat /jiaqi-test: no such file or directory
```

**Comment by rawmind0** [comment]
@jiaqiluo, using local-path storage you shouldn't create PV (automatically created by storageClass), just PVC. Take a look to our [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner) repo

This is working fine for me using local-path storage on a new k3s cluster:
* Create pvc using local-path storageclass (installed by default on k3s)
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
```
* Install cert-manager following [docs](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/#5-install-cert-manager)
* Install rancher enabling custom logos
```
helm install rancher rancher-latest/rancher \
--version v2.5.4-rc2 \
--namespace cattle-system \
--set hostname=<FQDN> \
--set replicas=1 \
--set customLogos.enabled=true \
--set customLogos.volumeName=local-path-pvc
```

By default, local-path volumes are created under k3s host `/var/lib/rancher/k3s/storage/<PVC>` 

Accessing Rancher server pod, i can see both custom logos subpaths mounted
```
/dev/vda1 on /usr/share/rancher/ui/assets/images/logos type ext4 (rw,relatime)
/dev/vda1 on /usr/share/rancher/ui-dashboard/dashboard/_nuxt/img/pl type ext4 (rw,relatime)
```
