### ISSUE TITLE
vSphere Cloud Provider not initialized properly

### ISSUE THREAD

**Issue by biscaldis** [rancher/rancher#29834]
**What kind of request is this (question/bug/enhancement/feature request):** 
Question or Bug 

**Steps to reproduce (least amount of steps as possible):**
1. Download rke binaries and set permissions
2. Configure `cluster.yml` 
3. Set up vSphere permissions according to [this link](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html)
4. Create VMs for the Kubernetes cluster
5. Enable disk UUID 
6. Set vSphere VM Hardware version to 15 
7. `rke up`
8. Create a storage class with thin disks 
9. Create a stateful set with a persistent disk of 1Gb 

**Result:**
The stateful set is not bootstrapped and in the Events of disk creation it's reported `Cloud provider not initialized properly`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA using RKE and HELM (stable) 

**Other details that may be helpful:**

**RKE version:** 
```
INFO[0000] Running RKE version: v1.0.0                  
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Docker version: (`docker version`,`docker info` preferred)** 

```bash
Containers: 13
 Running: 7
 Paused: 0
 Stopped: 6
Images: 12
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-5-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.8GiB
Name: DEV-K8S-03
ID: CVWA:5JSJ:YTEO:Y36R:KS4P:G6O7:AA4E:V7RA:5FTU:34UZ:HPZ3:VKB3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`4.9.0-5-amd64`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`vSphere`

**Comment by biscaldis** [comment]
Here are logs of kubelet on each node 
```E1030 09:42:14.018376   14376 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
E1030 09:42:14.029541   14376 kubelet.go:1302] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
E1030 09:42:14.073140   14376 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
E1030 09:42:14.125771   14376 controller.go:220] failed to get node "172.22.27.91" when trying to set owner ref to the node lease: nodes "172.22.27.91" not found
E1030 09:42:14.152722   14376 kubelet.go:2267] node "172.22.27.91" not found
E1030 09:42:14.333336   14376 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by DH-Rancher** [comment]
Can you post your cluster yaml, please?

**Comment by biscaldis** [comment]
Here it is

```yaml
nodes:
  - address: 172.22.27.91
    internal_address: 172.22.27.91
    user: pdxeng
    role: ["controlplane", "worker", "etcd"]
  - address: 172.22.27.92
    internal_address: 172.22.27.92
    user: pdxeng
    role: ["controlplane", "worker", "etcd"]
  - address: 172.22.27.93
    internal_address: 172.22.27.93
    user: pdxeng
    role: ["controlplane", "worker", "etcd"]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

dns:
  provider: coredns
  upstreamnameservers:
  - 172.22.24.10
  - 172.22.24.11
  - 8.8.8.8
  - 8.8.4.4

rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
      virtual_center:
        172.22.22.20:
          user: "***************"
          password: "***************"
          port: 443
          datacenters: "/PDXENG Datacenter"
      workspace:
        server: 172.22.22.20
        datacenter: "/PDXENG Datacenter"
        folder: K8S_folder
        default-datastore: "/PDXENG Datacenter/datastore/MSA2040_Storage_3"
        resourcepool-path: "/PDXENG Datacenter/PDXENG Cluster/DEV/Kg8S-02"
```
