### ISSUE TITLE
Pod Predicate NodeAffinity failed error seen on default-http-backend pod

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29882]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy an azure v1.19.3 cluster in 2.5.1
- Run pre upgrade checks
- Upgrade rancher to 2.5.2-rc5
- Run post upgrade checks.
- Noticed `Pod Predicate NodeAffinity failed error` seen on default-http-backend pod
<img width="1442" alt="Screen Shot 2020-10-31 at 2 00 29 PM" src="https://user-images.githubusercontent.com/26032343/97790144-6b4ff500-1b83-11eb-9d8c-3447228d3803.png">

**Other details that may be helpful:**
This is seen on one of the clusters in the setups
Other clusters in the setup:
AKS - 1.17
EKS - 1.17
Windows 1.16

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2-rc5
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Azure node driver

- Kubernetes version (use `kubectl version`):

```
1.19.3
```

SURE-3728

**Comment by maggieliu** [comment]
Does not reproduce all the time. Potential upstream issue: https://github.com/rancher/rke2/issues/127#issuecomment-699254134. Moving out of 2.5.2.

**Comment by sowmyav27** [comment]
- See this issue on a HA local cluster on 2.5-head - commit id: `9ee39b9` on `coredns` pod when the nodes used are flatlinux stable-2605.6.0 instances with t3a.medium. 
- The cluster.yml file has these network settings

```
network:
  plugin: calico
  options:
    calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    flannel_backend_type: vxlan
 
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
```
