### ISSUE TITLE
[Logging] Support syslog

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#29892]
Add a `syslog` output plugin for the [logging-operator](https://github.com/banzaicloud/logging-operator). All currently available plugins are listed in the [logging-operator docs](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs).

EDIT: This has been made available in the [3.8.0 logging-operator release](https://github.com/banzaicloud/logging-operator/releases/tag/3.8.0).

**Comment by nickgerace** [comment]
Relevant Issue: https://github.com/rancher/rancher/issues/28566

**Comment by nickgerace** [comment]
Research phase complete. Submitted issue: https://github.com/banzaicloud/logging-operator/issues/623

**Comment by nickgerace** [comment]
Awaiting `logging-operator` release containing recent `syslog` output addition.

**Comment by iosifnicolae2** [comment]
The `syslog` output has been developed in https://github.com/banzaicloud/logging-operator/releases/tag/3.8.0 .

**Comment by nickgerace** [comment]
Updating to chart 3.8.2 due to missing CRD fix.

**Comment by izaac** [comment]
I've tried a few configurations on the rsyslog and also yaml spec setting in the ClusterOuput but Im still getting mal formed messages in the rsyslog.

One of the syslog servers i tried was with this docker image:

https://hub.docker.com/r/rsyslog/syslog_appliance_alpine
`docker run -d -p 514:514 -p 514:514/udp -p 1601:1601 rsyslog/syslog_appliance_alpine`

And I custom server that has always worked with Logging v1 from Ember UI.

**Comment by izaac** [comment]
Working configuration:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: syslogtest1
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      timekey: 30s
      timekey_use_utc: true
      timekey_wait: 10s
      flush_interval: 5s
    format:
      type: json
      app_name_field: testrancher1
    host: <REDACTED>
    insecure: true
    port: 514
    transport: tcp
```

the syslog output seems to be using tls by default.
