### ISSUE TITLE
Weird etcdHighNumberOfFailedGRPCRequests prometheus rule in v2.5 rancher-monitoring

### ISSUE THREAD

**Issue by gmintoco** [rancher/rancher#29939]
I just was trying out the v2.5 monitoring chart and noticed that I was getting a large number of alerts for
`etcdHighNumberOfFailedGRPCRequests for kube-etcd (alertname="etcdHighNumberOfFailedGRPCRequests", grpc_method="Watch", grpc_service="etcdserverpb.Watch", prometheus="monitoring/monitoring-rancher-monitor-prometheus", severity="critical")` 

I took a look at the rules and something struck me as odd. This is the expression used to determine this alert: `100 * sum(rate(grpc_server_handled_total{job=~".*etcd.*", grpc_code!="OK"}[5m])) BY (job, instance, grpc_service, grpc_method) / sum(rate(grpc_server_handled_total{job=~".*etcd.*"}[5m])) BY (job, instance, grpc_service, grpc_method)`

Which seems to result in garbage data: 
![image](https://user-images.githubusercontent.com/50625416/95537068-68f0f400-0a38-11eb-9efd-a4f1a14829b9.png)  

However changing `BY (job, instance, grpc_service, grpc_method)` with simply `BY (instance)` seems to produce a much more meaningful metric (% grpc failed per node) 
![image](https://user-images.githubusercontent.com/50625416/95537117-950c7500-0a38-11eb-9569-e109488257ac.png)

From my perspective, it seems like it should be changed to BY (instance) as this seems to make more sense but not 100% sure. I am very new to Prometheus in general.

gz#14464
gz#14015

gz#14746

gz#15416

gz#16124
gz#16211

**Comment by aiyengar2** [comment]
@gmintoco thanks for calling this out! Based on https://github.com/etcd-io/etcd/pull/12122/files#diff-051b19bef7add661d9678608040a89efaead1aa9d3063323effdfedae11c9978R76-R100, it seems like you are correct, although the etcd team seems to replace `BY (job, instance, grpc_service, grpc_method)` with `without (grpc_type, grpc_code)` instead. Can you see if that also works for you?

With respect to bringing this change into Rancher, Rancher pulls these rules from the upstream Prometheus community Helm chart [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), which has an open issue out w.r.t. trying to update the etcd alerts in https://github.com/prometheus-community/helm-charts/issues/225. Once that is resolved, we can pull in the latest etcd alerts to get those changes in.

**Comment by gmintoco** [comment]
Hi @aiyengar2 yeah I realised that after digging into things a little deeper. I actually opened that issue :) but yes just waiting to see what happens there. Thanks for the response

**Comment by immanuelfodor** [comment]
This alert started to rain down on me today after a node memory pressure event, and it is firing constantly even though all the nodes were rebooted. Latest RKE with latest Rancher 2.5 and Monitoring V2 stack. Can it be supressed somehow until it is fixed in upstream? 

```yaml
alerts:
- annotations:
    message: 'etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd
      instance 192.168.1.100:2379.'
  endsAt: '0001-01-01T00:00:00Z'
  fingerprint: bce5342bd6fd6152
  generatorURL: http://rancher-monitoring-prometheus.cattle-monitoring-system:9090/graph?g0.expr=100+%2A+sum+by%28job%2C+instance%2C+grpc_service%2C+grpc_method%29+%28rate%28grpc_server_handled_total%7Bgrpc_code%21%3D%22OK%22%2Cjob%3D~%22.%2Aetcd.%2A%22%7D%5B5m%5D%29%29+%2F+sum+by%28job%2C+instance%2C+grpc_service%2C+grpc_method%29+%28rate%28grpc_server_handled_total%7Bjob%3D~%22.%2Aetcd.%2A%22%7D%5B5m%5D%29%29+%3E+5&g0.tab=1
  labels:
    alertname: etcdHighNumberOfFailedGRPCRequests
    grpc_method: Watch
    grpc_service: etcdserverpb.Watch
    instance: 192.168.1.100:2379
    job: kube-etcd
    prometheus: cattle-monitoring-system/rancher-monitoring-prometheus
    severity: critical
  startsAt: '2020-12-12T18:45:10.979Z'
  status: firing
commonAnnotations:
  message: 'etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd instance
    192.168.1.100:2379.'
commonLabels:
  alertname: etcdHighNumberOfFailedGRPCRequests
  grpc_method: Watch
  grpc_service: etcdserverpb.Watch
  instance: 192.168.1.100:2379
  job: kube-etcd
  prometheus: cattle-monitoring-system/rancher-monitoring-prometheus
  severity: critical
externalURL: http://rancher-monitoring-alertmanager.cattle-monitoring-system:9093
groupKey: '{}:{job="kube-etcd"}'
groupLabels:
  job: kube-etcd
receiver: matrix
status: firing
truncatedAlerts: 0
version: '4'
```

**Comment by immanuelfodor** [comment]
After another 109 alerts over the night, I added a silence for `etcdHighNumberOfFailedGRPCRequests` in AlertManager.

**Comment by m4r1u2** [comment]
Can confirm we also have the same issue in our v2.5 rancher-monitoring rke setup.. 
Are we all waiting on upstream fixes or any updates to this issue?

**Comment by jonathon2nd** [comment]
Still happens after the 2.5.5 update. 

Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

**Comment by vitobotta** [comment]
Hi, I set up a new instance of Rancher 2.5.5 and a new RKE cluster and am getting these alerts. Do I need to worry about the health of the cluster? I literally just started setting things up and there are plenty of resources / low load on the servers. Thanks

**Comment by immanuelfodor** [comment]
My cluster is healthy and fairly sable, and I also get these constantly. I eventually silenced them through the alertmanager secret (under `alertmanager.yaml`): 

```yaml
route:
...
  # temporarily silence this alert until it's fixed upstream                         
  - match:                                                                               
      alertname: etcdHighNumberOfFailedGRPCRequests                                    
    receiver: "null"
... 
```
