### ISSUE TITLE
Add docker label org.label-schema.version to rancher/rancher image

### ISSUE THREAD

**Issue by felipecrs** [rancher/rancher#30002]
It would be very useful if we could have this label set in the `rancher/rancher` docker image.

Currently, these are the labels:

```json
"Labels": {
    "org.label-schema.build-date": "2020-10-08T00:18:07Z",
    "org.label-schema.schema-version": "1.0",
    "org.label-schema.vcs-ref": "eb990af66be155262dc722e35a34e48309e0c150",
    "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
}
```

The new label would be:

```json
"org.label-schema.version": "v2.5.1"
```

**Comment by vincent99** [comment]
These are set by the drone docker plugin, not by rancher specifically.. Useful for what?

**Comment by felipecrs** [comment]
I'm writing an automated rancher upgrade script for single node installations, and at a point I need the version of Rancher running in the container. 

If that label was set, it would be straightforward to find.

**Comment by felipecrs** [comment]
Something like this should work:

```yaml
    tag: ${DRONE_BRANCH/release\//}-${DRONE_COMMIT}-linux-amd64
    label_schema:
      version: ${DRONE_BRANCH/release\//}
    repo: rancher/rancher
```
