### ISSUE TITLE
CIS Scan 1.5 does not work with canal/calico network plugin

### ISSUE THREAD

**Issue by p7kdev** [rancher/rancher#30029]
**What kind of request is this (question/bug/enhancement/feature request):** Bug / Question

**Steps to reproduce (least amount of steps as possible):** Run CIS 1.5 Permissive scan (v1 and v2 generate the same error) in a canal/calico cluster.

**Result:**
```
error running sonobuoy
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.8, v2.5.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.19.3, v1.18.8, v1.16.15
- Network Plugin: canal / calico

Hi,

we run some rancher servers with different Kubernetes clusters. Since CIS 1.5 the scans do not work anymore. These only deliver the error `error running sonobuoy`. When I look into the Daemonset Pods, I see the additional error:
```
time="2020-10-30T17:14:15Z" level=info msg="Detected done file, transmitting result file" resultFile=/tmp/results/kb.tar.gz
time="2020-10-30T17:15:05Z" level=error msg="error entry for attempt: 1, verb: PUT, time: 2020-10-30 17:15:05.582244577 +0000 UTC m=+52.054651549, URL: https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: Put https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: dial tcp: lookup service-rancher-cis-benchmark on 10.43.0.10:53: read udp 192.168.10.15:35549->10.43.0.10:53: i/o timeout"
time="2020-10-30T17:15:56Z" level=error msg="error entry for attempt: 2, verb: PUT, time: 2020-10-30 17:15:56.587283218 +0000 UTC m=+103.059690179, URL: https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: Put https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: dial tcp: lookup service-rancher-cis-benchmark on 10.43.0.10:53: read udp 192.168.10.15:58790->10.43.0.10:53: i/o timeout"
time="2020-10-30T17:16:47Z" level=error msg="error entry for attempt: 3, verb: PUT, time: 2020-10-30 17:16:47.593623731 +0000 UTC m=+154.066030696, URL: https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: Put https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: dial tcp: lookup service-rancher-cis-benchmark on 10.43.0.10:53: read udp 192.168.10.15:60552->10.43.0.10:53: i/o timeout"
time="2020-10-30T17:16:47Z" level=error msg="gathering results: error encountered dialing aggregator at https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: Put https://service-rancher-cis-benchmark/api/v1/results/by-node/pkm03/rancher-kube-bench: dial tcp: lookup service-rancher-cis-benchmark on 10.43.0.10:53: read udp 192.168.10.15:60552->10.43.0.10:53: i/o timeout"
```

During the scans the DNS in the Pods does not work. I can confirm this when I manually open a shell in the container.

Under 1.4 these have still worked perfectly. 

This is reproducible with the canal and calico network plugin. weave and flannel work perfectly. So I attribute the problem to calico.

Is anything known about this? Are there any possibilities how we can analyze the problem more precisely?

Best regards,
Paul

**Comment by sowmyav27** [comment]
**On 2.5.1**

- Deployed a 1 node(all roles) Canal network provider cluster and 2 nodes (1 etcd/control and 1 worker node) Calico cluster. (DO ubuntu nodes)
- Verified able to run CIS 1.5 v1 permissive scans

@p7kdev Can you give us more info -
- What is the Cluster configuration ?
- What is the OS on the cluster instances? 
- Was CIS v2 run before CIS v1 ?

**Comment by p7kdev** [comment]
@sowmyav27 Thank you! I have set up a separate test setup. It looks like this:

1 Rancher Server (single Installation - docker) v2.4.8

4 Clusters:
* 1 Master + 1 Worker (flannel network plugin): successful
* 1 Master + 1 Worker (calico network plugin): failed
* 1 Master + 1 Worker (canal network plugin): failed
* 1 Master + 1 Worker (weave network plugins): successful

All nodes were set up identically with with Ubuntu 20.04 and the "Custom" cluster (Kubernetes: v1.18.10-rancher1-2) option. No further adjustments were made. The test (v1) was performed directly after the setup. No other applications were running in this cluster. The VMs run on an OpenStack platform. 

Here is an example of a complete cluster.yml (mainly default values except the network plugin option):
```yaml
# 
# Cluster Config
# 
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: test-cluster-3
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
    reversecidrs: null
    stubdomains: null
    update_strategy: {}
    upstreamnameservers: null
  ignore_docker_version: true
# 
# # Currently only nginx ingress provider is supported.
# # To disable ingress controller, set `provider: none`
# # To enable ingress on specific nodes, use the node_selector, eg:
#    provider: nginx
#    node_selector:
#      app: ingress
# 
  ingress:
    provider: nginx
  kubernetes_version: v1.18.10-rancher1-2
  monitoring:
    provider: metrics-server
    replicas: 1
# 
#   If you are using calico on AWS
# 
#    network:
#      plugin: calico
#      calico_network_provider:
#        cloud_provider: aws
# 
# # To specify flannel interface
# 
#    network:
#      plugin: flannel
#      flannel_network_provider:
#      iface: eth1
# 
# # To specify flannel interface for canal plugin
# 
#    network:
#      plugin: canal
#      canal_network_provider:
#        iface: eth1
# 
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: calico
  restore:
    restore: false
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
# 
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```

**Comment by sowmyav27** [comment]
**On 2.4.8**

- Deployed a custom cluster with 1 master and 1 worker node. - Ubuntu 20.04 LTS instances
- Cluster.yml is from [here](https://github.com/rancher/rancher/issues/30029#issuecomment-725476637) 
- When the cluster comes up active, user is able to run CIS v1 permissive scan on the cluster. Scan runs fine and report is generated.

**Comment by p7kdev** [comment]
After some research I was able to limit the problem to the Calico configuration. By default an IPPool is created with the cidr

```yaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  blockSize: 26
  cidr: 192.168.0.0/16
```

I have changed this to `10.0.0./8` . Now it works. My nodes even had IP addresses from this 192 network. Probably this was the reason. My knowledge of Calico is unfortunately somewhat limited. Therefore I can not explain this in detail. Should this be the same as the actual Kubernetes subnet? Strange that this only affected the CIS/Scan pods. In general there were no problems with the DNS in the cluster.
