### ISSUE TITLE
Update ingress api when lowest supported k8s version is 1.19

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#30053]
When installing with `helm template rancher` the Ingress resource was showing the following warning `Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress` this was resolved for `helm install` in this issue https://github.com/rancher/rancher/issues/29144 but still warns with helm template, unless passing in the apiVersion. 

The resolution added an [if else statement](https://github.com/rancher/rancher/pull/29922/files) which defaults to `networking.k8s.io/v1beta1` as the else. In 1.22+ , `networking.k8s.io/v1beta1` will be unavailable so the if statement needs to be removed and/or the default needs to be `networking.k8s.io/v1`

**Comment by cbron** [comment]
@brendarearden above we wrote: 
> In 1.22+ , networking.k8s.io/v1beta1 will be unavailable

But its only extensions.k8s.io thats removed right ? Is `networking.k8s.io/v1beta1` deprecated anywhere ? I don't see that announcement.

**Comment by brendarearden** [comment]
Based on the [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) I am going to update this card to be: Update ingress when lowest supported k8s version is 1.19. 

This is because the `networking.k8s.io/v1 API version` is only available starting in 1.19. We are currently supporting 1.18 for the 2.6 release so the api version check is still necessary in our rancher helm chart. 

```
Ingress
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress will no longer be served in v1.22.
Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.
All existing persisted objects are accessible via the new API
Notable changes:
spec.backend is renamed to spec.defaultBackend
The backend serviceName field is renamed to service.name
Numeric backend servicePort fields are renamed to service.port.number
String backend servicePort fields are renamed to service.port.name
pathType is now required for each specified path. Options are Prefix, Exact, and ImplementationSpecific. To match the undefined v1beta1 behavior, use ImplementationSpecific.

IngressClass
The networking.k8s.io/v1beta1 API version of IngressClass will no longer be served in v1.22.

Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19.
All existing persisted objects are accessible via the new API
No notable changes
```

**Comment by cbron** [comment]
Moving this to 2.6.x

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by jakefhyde** [comment]
Setup
=
Validated on HA install of `v2.6.3-rc3`.

Commands
=
```
helm install --dry-run rancher ./rancher-2.6.3-rc3.tgz --namespace cattle-system --set hostname=jhyde.cp-dev.rancher.space --set useBundledSystemChart=true --kubeconfig ./kube_config_cluster.yml
```

Validation
=

On a `v1.18.20` rke cluster, `helm install` correctly uses `networking.k8s.io/v1beta1`
```yaml
---
# Source: rancher/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rancher
  labels:
    app: rancher
    chart: rancher-2.6.3-rc3
    heritage: Helm
    release: rancher
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - host: jhyde.cp-dev.rancher.space  # hostname to access rancher server
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
  tls:
  - hosts:
    - jhyde.cp-dev.rancher.space
    secretName: tls-rancher-ingress
```
On `v1.20.8` rke cluster, `helm install` correctly uses `networking.k8s.io/v1`
```yaml
---
# Source: rancher/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  labels:
    app: rancher
    chart: rancher-2.6.3-rc3
    heritage: Helm
    release: rancher
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - host: jhyde.cp-dev.rancher.space  # hostname to access rancher server
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - jhyde.cp-dev.rancher.space
    secretName: tls-rancher-ingress
```

**Comment by anupama2501** [comment]
@jakefhyde thank you for the validations! 
Could we also verify a scenario where we install rancher by generating a helm template on 2.6.2 and k8s on the cluster set to 1.18 or 1.19 . Upgrade the rancher server to v2.6.3-rc4 by generating a helm template and verifiy the api version?

**Comment by jakefhyde** [comment]
# Setup

HA install 
k8s version `v1.18.20-rancher1-2`

# Validation
Generated helm template on `v2.6.2` - k8s `v1.18.20`. Upgrade rancher version to `v2.6.3-rc4` using helm template, the following is the generated `ingress.yaml`:
```
---
# Source: rancher/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rancher
  labels:
    app: rancher
    chart: rancher-2.6.3-rc4
    heritage: Helm
    release: rancher
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - host: <REDACTED>  # hostname to access rancher server
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
  tls:
  - hosts:
    - <REDACTED>
    secretName: tls-rancher-ingress
```
Ingress still working as intended post upgrade:
![v2 6 3-rc4-1 18 20](https://user-images.githubusercontent.com/33796120/145631536-e6f2a637-6ced-4288-a666-21ebcc879c82.png)
