### ISSUE TITLE
Nodes can not be drained if Istio is enabled

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#30082]
Due to the disruption budget, we can not drain nodes in a cluster with Istio deployed. We should update the istio overlay to have a min of 2 replicas of pilot and gateways.  Hypothetically this should allow nodes to be successfully drained.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy cluster
2. Enable Istio with ingress gateways
3. Drain a node

**Result:**
The node will timeout and remain cordoned but not drained.

**Other details that may be helpful:**
Updating the istio overlay to have a min of 2 replicas of pilot and gateways may help work around this.
I've tried setting `galley.replicaCount` to `2` and `mixer.policy.replicaCount` to `2` in the app's answers then upgrading. Though they do not appear in the values.yml in the chart, the configurations appear to have been accepted (but nodes still do not drain).  Scaling pilot to 2 manually hung.

It's been proposed that we may be able to fix this by adding an overlay file with the following contents:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
```

See: https://github.com/istio/istio/issues/12602#issuecomment-701038118

I'm not sure yet how to test this.

**Environment information**
- Rancher version: v2.4.5
- Installation option (single install/HA): single docker
- Kubernetes version (use `kubectl version`): 1.18
