### ISSUE TITLE
Private Catalog Use OAuth Token To Download Releases

### ISSUE THREAD

**Issue by pkroan** [rancher/rancher#30105]
**Question**
I am trying to get clarity that the OAuth option for private catalogs is used on the urls served from a index.yaml file. 

index.yaml Example:
```
apiVersion: v1
entries:
  example-app:
  - apiVersion: v2
    appVersion: 1.16.1
    created: "2020-11-12T00:12:57.53060062-06:00"
    description: A Helm chart for Kubernetes
    digest: 573df9104c1b43802b9745221cc885fd9c572396ad13f077faf5456d3049928d
    name: example-app
    type: application
    urls:
    - https://github.com/Example/helm-charts/releases/download/example-app-0.1.0/example-app-0.1.0.tgz
    version: 0.1.0
```
I am using github pages to serve the index.yaml, and this works fine for rancher when it is a public catalog. When it is a private catalog I can add the catalog and it shows under the catalog apps correctly but when I go to launch it cannot download the urls to the chart packages. 

If the url above `https://github.com/Example/helm-charts/releases/download/example-app-0.1.0/example-app-0.1.0.tgz` was behind authentication, is the desired behavior to use the OAuth token in the request? 

**Result:**
I am not seeing this behavior and am getting a 404 from github (normal response when you try and access a restricted repo on github) when rancher is trying to pull the chart release down. The file is there and the chart works when I set the repository to public. So I know the url and the chart are not the issue. 

Ideally it would be great if we could add support for this. But mainly I just want to know if perhaps I am doing something wrong or if it is indeed the intended behavior.

**Environment information**
- Rancher Version: `rancher/rancher` `v2.5.2`

I used this documentation when setting up the private repo: 
https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/catalog-config/#using-an-oauth-token
