### ISSUE TITLE
Charts are not updated/populated from chart repositories 2.5.2

### ISSUE THREAD

**Issue by brodul** [rancher/rancher#30108]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

- Create 1 helm chart and package it with `helm package <chart_dir>`
- Create `index.yaml` with `helm repo index . --url <url>`
- Upload to host server (GCS, github pages ....)
- Add repo to the `dashboard/c/local/apps/catalog.cattle.io.clusterrepo`

![image](https://user-images.githubusercontent.com/204514/99381285-4d94c680-28cb-11eb-9765-fbeea8e65a65.png)

- Go to `dashboard/c/local/apps/charts` confirm that the chart is there:
![image](https://user-images.githubusercontent.com/204514/99381545-8f257180-28cb-11eb-9d70-711f42112ca6.png)

- Package a different chart with `helm package <chart_dir>`, create an updated `index.yaml` with old and the new chart.
- Inspect that there are 2 charts in the `index.yaml`
- Upload the new chart `tgz` and the new `index.yaml`

- Go to the `dashboard/c/local/apps/catalog.cattle.io.clusterrepo` and refresh the repository
- Go to `dashboard/c/local/apps/charts` and refresh the charts

**Expected behavior:**

- New chart **should be** on the list on `dashboard/c/local/apps/charts`

**Result:**

- New chart is **not** be on the list on `dashboard/c/local/apps/charts`

UPDATE: After 1 hour I checked again and it seems that its a caching issue. So one could say "Refresh" button for a chart repository is not working. I am not sure what is the function of the refresh button.

**Other details that may be helpful:**
Logs:
```
2020/11/17 10:24:22 [INFO] Downloading repo index from https://helm3.brodul.org/index.yaml
2020/11/17 10:26:28 [INFO] Downloading repo index from https://storage.googleapis.com/helm3.brodul.org/index.yaml
2020/11/17 10:26:32 [INFO] Downloading repo index from https://storage.googleapis.com/helm3.brodul.org/index.yaml
2020/11/17 10:26:32 [INFO] Downloading repo index from https://helm3.brodul.org/index.yaml
2020/11/17 10:26:50 [INFO] Downloading repo index from https://storage.googleapis.com/helm3.brodul.org/index.yaml
2020/11/17 10:26:50 [INFO] Downloading repo index from https://helm3.brodul.org/index.yaml
2020/11/17 10:27:02 [INFO] Downloading repo index from https://helm3.brodul.org/index.yaml
2020/11/17 10:32:38 [INFO] Downloading repo index from https://storage.googleapis.com/helm3.brodul.org/index.yaml
2020/11/17 10:34:22 [INFO] Downloading repo index from https://helm3.brodul.org/index.yaml
2020/11/17 10:37:38 [INFO] Downloading repo index from https://storage.googleapis.com/helm3.brodul.org/index.yaml
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): single install

**Comment by jiaqiluo** [comment]
Hi @brodul, I cannot reproduce this bug in the rancher:`v2.5.2` single-install setup. Can you see how my steps are different from yours?

I tried both kinds of repositories: git-repo and URL 

### prepare the Rancher server
- run rancher:`v2.5.2` single-install
- provision a cluster 
```
helm version v3.4.1
```

## Git Repo 
### prepare the helm chart
- create 1 helm chart and package it using `helm package alpine`
- delete the chart and keep only the archive file 
- generate the index file by using `helm repo index ./`
```
> ls 
alpine-test-v1-0.1.0.tgz index.yaml
```
```
> cat index.yaml
apiVersion: v1
entries:
  alpine-test-v1:
  - apiVersion: v1
    appVersion: "3.3"
    created: "2020-11-17T14:26:29.222744-07:00"
    description: Deploy a basic Alpine Linux pod - test v1
    digest: 2c113e0e9eefa7a98629f88e0b2f1d251298594057155f8f4b25cb2502bebec4
    home: https://github.com/helm/helm
    name: alpine-test-v1
    sources:
    - https://github.com/helm/helm
    urls:
    - alpine-test-v1-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-17T14:26:29.222313-07:00"
```
 
- push the repo to Github 
- add the chart repo in the cluster's Explorer
<img width="1606" alt="Screen Shot 2020-11-17 at 2 34 03 PM" src="https://user-images.githubusercontent.com/6218999/99455015-75445880-28e4-11eb-8d6f-7b8932d65663.png">
- check the Charts page to confirm the app is listed 
<img width="701" alt="Screen Shot 2020-11-17 at 2 34 22 PM" src="https://user-images.githubusercontent.com/6218999/99455064-8ab98280-28e4-11eb-8e7d-f4edaa8d9ac3.png">

- repeat the above steps to add a new chart to the repo 
- re-generate the index 
```
apiVersion: v1
entries:
  alpine-test-v1:
  - apiVersion: v1
    appVersion: "3.3"
    created: "2020-11-17T14:36:16.110734-07:00"
    description: Deploy a basic Alpine Linux pod - test v1
    digest: 2c113e0e9eefa7a98629f88e0b2f1d251298594057155f8f4b25cb2502bebec4
    home: https://github.com/helm/helm
    name: alpine-test-v1
    sources:
    - https://github.com/helm/helm
    urls:
    - alpine-test-v1-0.1.0.tgz
    version: 0.1.0
  basic-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-11-17T14:36:16.111254-07:00"
    description: A Helm chart for Kubernetes
    digest: ad678f0b4cf32bdfbb529b61463697a31951f6759ff339c76b98f17dfb9b3670
    name: basic-app
    type: application
    urls:
    - basic-app-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-17T14:36:16.109336-07:00"
```
- push the change to Github
- refresh the repo in the Cluster Explorer 
- Now we see both the old and new app in the list
![image](https://user-images.githubusercontent.com/6218999/99455251-d4a26880-28e4-11eb-9e1c-08a7cc9f3e92.png)

## URL

- add the repo 
<img width="1600" alt="Screen Shot 2020-11-17 at 3 17 08 PM" src="https://user-images.githubusercontent.com/6218999/99457744-b3437b80-28e8-11eb-8f02-3123f1cda280.png">

- check the app
<img width="807" alt="Screen Shot 2020-11-17 at 3 15 21 PM" src="https://user-images.githubusercontent.com/6218999/99457763-bb9bb680-28e8-11eb-9142-4069734b9d54.png">

- add a new app and update the index.yaml
- refresh the repo 
<img width="1116" alt="Screen Shot 2020-11-17 at 3 17 01 PM" src="https://user-images.githubusercontent.com/6218999/99457794-c8b8a580-28e8-11eb-90d8-a4263d0ae561.png">

**Comment by brodul** [comment]
Yea, thats it. The only difference is the expected result. 

I checked if the `index.yaml` would be in some kind of CND/cache, but its not.

When I click on the refresh button in the chart list I can see that the `generation`, `lastUpdateTime`, `downloadTime` change. `generation` for `i++` and other field to the new timestamp. 

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  creationTimestamp: "2020-11-17T10:12:38Z"
  generation: 22
  managedFields:
  - apiVersion: catalog.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:forceUpdate: {}
        f:url: {}
      f:status:
        .: {}
        f:conditions: {}
        f:downloadTime: {}
        f:indexConfigMapName: {}
        f:indexConfigMapNamespace: {}
        f:indexConfigMapResourceVersion: {}
        f:observedGeneration: {}
        f:url: {}
    manager: rancher
    operation: Update
    time: "2020-11-19T14:56:22Z"
  name: test
  resourceVersion: "13501566"
  selfLink: /apis/catalog.cattle.io/v1/clusterrepos/test
  uid: 03fa1ac7-1029-4a9e-abf0-3f48ba4bf049
spec:
  forceUpdate: "2020-11-19T14:56:22Z"
  url: https://storage.googleapis.com/helm3.brodul.org/
status:
  conditions:
  - lastUpdateTime: "2020-11-17T10:12:38Z"
    status: "True"
    type: FollowerDownloaded
  - lastUpdateTime: "2020-11-19T14:56:22Z"
    status: "True"
    type: Downloaded
  downloadTime: "2020-11-19T14:56:22Z"
  indexConfigMapName: test-c7sgt
  indexConfigMapNamespace: cattle-system
  indexConfigMapResourceVersion: "12776787"
  observedGeneration: 22
  url: https://storage.googleapis.com/helm3.brodul.org/
type: catalog.cattle.io.clusterrepo
```

**Comment by brodul** [comment]
The response from `https://rancher.example.org/v1/catalog.cattle.io.clusterrepos/test?link=index`
```json
{
  "apiVersion": "v1",
  "generated": "2020-11-17T15:37:30.214423189+01:00",
  "entries": {
    "response-hostname": [
      {
        "name": "response-hostname",
        "version": "0.1.1",
        "description": "Respond with the hostname of container",
        "apiVersion": "v2",
        "appVersion": "0.1.0",
        "type": "application",
        "urls": [
          "https://rancher.brodul.org/v1/catalog.cattle.io.clusterrepos/test?chartName=response-hostname\\u0026link=chart\\u0026version=0.1.1"
        ],
        "created": "2020-11-17T15:37:30.215512505+01:00",
        "digest": "3ee1defac2fe9c6425e8e57e0deaecb1890c791bd33e07bd4850823d1f074975"
      },
      {
        "name": "response-hostname",
        "version": "0.1.0",
        "description": "Respond with the hostname of container",
        "apiVersion": "v2",
        "appVersion": "1.16.0",
        "type": "application",
        "urls": [
          "https://rancher.brodul.org/v1/catalog.cattle.io.clusterrepos/test?chartName=response-hostname\\u0026link=chart\\u0026version=0.1.0"
        ],
        "created": "2020-11-17T15:37:30.214991011+01:00",
        "digest": "2d7dfd934ea04a84012ab61d66c501c0d9218d6fa14eff188190b03b99cb9e64"
      }
    ],
    "response-hostname2": [
      {
        "name": "response-hostname2",
        "version": "0.1.1",
        "description": "Respond with the hostname of container",
        "apiVersion": "v2",
        "appVersion": "0.1.0",
        "type": "application",
        "urls": [
          "https://rancher.brodul.org/v1/catalog.cattle.io.clusterrepos/test?chartName=response-hostname2\\u0026link=chart\\u0026version=0.1.1"
        ],
        "created": "2020-11-17T15:37:30.216017885+01:00",
        "digest": "d44506021e901d45b4cca94d83869d30ab41d8a03ba0ce13cd54fecce9b2a325"
      }
    ],
    "response_hostname": [
      {
        "name": "response_hostname",
        "version": "0.1.0",
        "description": "Respond with the hostname of container",
        "apiVersion": "v2",
        "appVersion": "1.16.0",
        "type": "application",
        "urls": [
          "https://rancher.brodul.org/v1/catalog.cattle.io.clusterrepos/test?chartName=response_hostname\\u0026link=chart\\u0026version=0.1.0"
        ],
        "created": "2020-11-17T15:37:30.216531058+01:00",
        "digest": "00a961c85a9e5fc125d1f308a366ab2edbdfcebcf46dc61cb95f4091fa472a71"
      }
    ]
  }
}
```

The `index.yaml`
```
apiVersion: v1
entries:
  response-hostname:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-11-19T15:42:39.871040621+01:00"
    description: Respond with the hostname of container
    digest: ae06c3ad67075d3bd2752b31ebd096ff5c1c02e4e0d6a1e7e0a93af5e926dbb5
    name: response-hostname
    type: application
    urls:
    - https://helm3.brodul.org/response-hostname-0.1.2.tgz
    version: 0.1.2
generated: "2020-11-19T15:42:39.87010412+01:00"
```
