### ISSUE TITLE
endpointCA doesn't work for backup

### ISSUE THREAD

**Issue by maxisam** [rancher/rancher#30181]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

```yml
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: k8s-dev-backup
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  storageLocation:
    s3:
      bucketName: k8s-dev-backup
      credentialSecretName: minio-secret
      credentialSecretNamespace: longhorn-system
      endpoint: cminio.company.com
      endpointCA: |-
        -----BEGIN CERTIFICATE-----
        MIID8TCCAtmgAwIBAgIUT4J8Jfw555VvyB0R5wRfwQEqUIQwDQYJKoZIhvcNAQEL
        blahblahblah
        s=
        -----END CERTIFICATE-----
      folder: backup
```

**Result:**

![image](https://user-images.githubusercontent.com/456807/99859116-b3e04a00-2b54-11eb-822e-93478a34b855.png)
**Environment information**
- Rancher version  2.5.2
- Installation option HA
