### ISSUE TITLE
Internal Server Error In Cluster Explorer After Upgrade to v2.5.2

### ISSUE THREAD

**Issue by tyzbit** [rancher/rancher#30182]
Hello,

I upgraded Rancher from v2.3.3 to v2.5.2 and afterwards, when navigating to one of my clusters in the cluster explorer I get 
```
HTTP Error 500: Internal Server Error
from /k8s/clusters/c-mppz8/v1/schemas 
```
I can see and interact with the local cluster just fine.

I tried upgrading the k8s version of the affected cluster to v1.19.4 but that did not help fix the issue.

**Comment by cite** [comment]
Is your environment using a HTTP proxy? If so, did you follow the upgrade procedure and add exceptions for cluster-internal services?

**Comment by tyzbit** [comment]
I have a reverse proxy in front of Rancher, yes.  I was unable to find the exceptions you mentioned for cluster-internal services, can you point me to the docs?

For reference, here's my nginx config:

<details><summary>Click to expand</summary><pre>
server {
        listen 8443;
        server_name rancher.example.com;
        access_log /var/log/nginx/access.log extended;
        ssl on;
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        ssl_protocols SSLv3 TLSv1.2;
        location / {
                resolver 192.168.1.1 valid=30s;
                proxy_pass https://rancher;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # websockets
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_connect_timeout 60;
                proxy_read_timeout 240;
                error_page 502 404 /500.html;
        }
        location /500.html {
                 root /docroot/genericdown;
        }
}
server {
        listen 8080;
        server_name rancher.example.com;
        rewrite     ^   https://$server_name$request_uri? permanent;
}
</pre><details>

**Comment by cite** [comment]
https://github.com/rancher/docs/issues/2725#issuecomment-702454584

**Comment by tyzbit** [comment]
I do not have an HTTP proxy in my environment, but I do have a reverse proxy in front of Rancher.  Does that still somehow apply?

**Comment by hunghoang** [comment]
Same issue here:
_HTTP Error 500:
from /k8s/clusters/c-vqfqg/v1/schemas_
When I upgrade rancher from 2.4.5 to 2.5.2.
Is this known issue? Please help

**Comment by simoferr98** [comment]
Hi, I have the same problem:
 HTTP Error 500:
from / k8s / clusters / c-nzzm4 / v1 / schemas

I started Rancher version 2.5.2

**Comment by tyzbit** [comment]
I got the Cluster Explorer working.  Looking at the response from that API call I realized that rancher is proxying the call to the cluster and the cluster doesn't support websockets:
```
invalid upgrade response: status code 200
```

The fix was to have an additional `location` block that did not try to upgrade the connection to websockets for `/k8s`:

<details><summary>Click to expand</summary>
<pre>
server {
        listen 8443;
        server_name rancher.example.com;
        access_log /var/log/nginx/access.log extended;
        ssl on;
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        ssl_protocols SSLv3 TLSv1.2;
        location /k8s/ {
                resolver 192.168.1.1 valid=30s;
                proxy_pass https://rancher/k8s/;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_connect_timeout 60;
                proxy_read_timeout 240;
                error_page 502 404 /500.html;
        }
        location / {
                resolver 192.168.1.1 valid=30s;
                proxy_pass https://rancher;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # websockets
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_connect_timeout 60;
                proxy_read_timeout 240;
                error_page 502 404 /500.html;
        }
        location /500.html {
                 root /docroot/genericdown;
        }
}
server {
        listen 8080;
        server_name rancher.example.com;
        rewrite     ^   https://$server_name$request_uri? permanent;
}
</pre>
</details>

I will leave the issue open for feedback as to whether or not this configuration would cause further problems (maybe I should be more specific, like set the location as `/k8s/cluster`?).

Also the permanent fix that would prevent a configuration like this from being necessary is for Rancher to accept websockets but proxy requests to clusters as normal HTTP.  Or to clarify that reverse proxies should not use websockets at all.

**Comment by BarthV** [comment]
Same issue here !
But since I'm using nginx-ingress & rancher with a helm install, I'm not able to edit the nginx config directly.

So based on @tyzbit workaround I managed to find a way to replicate it inside my setup :
ingress-nginx Helm chart values : 
```yaml
    controller:
      # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
      config:
        http-snippet: |2
          ## Rancher 2.5.x websocket management issue : https://github.com/rancher/rancher/issues/30182
          map $http_upgrade $custom_rnch25_conn {
            default "";
            websocket "Upgrade";
          }
```

rancher Helm chart values :
```yaml
    ingress:
      extraAnnotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"

      # configurationSnippet - Add additional Nginx configuration. This example statically sets a header on the ingress.
      configurationSnippet: |
        proxy_set_header Upgrade $http_upgrade ;
        proxy_set_header Connection $custom_rnch25_conn;
```

So far, it seems working for me.
Don't hesitate to fix this snippet if you feel anything is bad/wrong.
