### ISSUE TITLE
Apps & Marketplace install unset all helm values

### ISSUE THREAD

**Issue by mecseid** [rancher/rancher#30196]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Add https://charts.reactiveops.com/stable as a HTTP Helm Chart from new Dasboard -> Apps & Marketplace.
2. From charts, choose Polaris
3. Delete everything from Values YAML
4. Install

_Comment_: It "works" with any chart, but I tried it with polaris, because in simple scenarios you don't have to change any parameter on Helm values (values.yaml).

**Result:**
Cannot install Helm chart, becasue the server clear (unset) all values from values.yaml.
In other words, the Rancher helm install procedure use the base values.yaml file with unset (nulled) values.
In the old Apps page, the helm installation/upgrade works as expected (the values.yaml only contains what I wrote in Form or YAML view).

**Other details that may be helpful:**
The formatted values.yaml file that generated by Rancher, and used by helm for installation.
```yaml
{
  "audit": {
    "cleanup": null,
    "enable": null,
    "outputURL": null
  },
  "dashboard": {
    "enable": null,
    "ingress": {
      "enabled": null,
      "hosts": null,
      "tls": null
    },
    "priorityClassName": null,
    "replicas": null,
    "resources": {
      "limits": {
        "cpu": null,
        "memory": null
      },
      "requests": {
        "cpu": null,
        "memory": null
      }
    },
    "service": {
      "type": null
    },
    "tolerations": null
  },
  "global": {
    "cattle": {
      "clusterId": "c-l7czx",
      "clusterName": "test",
      "systemDefaultRegistry": ""
    },
    "systemDefaultRegistry": ""
  },
  "image": {
    "pullPolicy": null,
    "pullSecrets": null,
    "repository": null,
    "tag": null
  },
  "rbac": {
    "enabled": null
  },
  "serviceAccount": {
    "create": null,
    "name": null
  },
  "templateOnly": null,
  "webhook": {
    "enable": null,
    "priorityClassName": null,
    "replicas": null,
    "resources": {
      "limits": {
        "cpu": null,
        "memory": null
      },
      "requests": {
        "cpu": null,
        "memory": null
      }
    },
    "tolerations": null
  }
}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher v2.5.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, not related
- Kubernetes version (use `kubectl version`): v1.17.4
