### ISSUE TITLE
Forward port for ingress controller label issues

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#30208]
Forward port fix in both 2.5 and master for the following issues:  
https://github.com/rancher/rancher/issues/30045 
https://github.com/rancher/rancher/issues/30044

**Comment by sowmyav27** [comment]
On 2.5-head - commit id: `b2953cbc`

- Create cluster with Project Network Isolation Enabled 1 etcd/control and 2 worker nodes.
- Pods of `nginx-ingress-controller` in system project have podName labels

```
labels:
    app: ingress-nginx
    controller-revision-hash: 6f4d9bb968
    field.cattle.io/podName: nginx-ingress-controller-fgcm4
    pod-template-generation: "1"
```
- Ingress is stuck in Initializing state

On master-head, the ingress do not get all the worker nodes' ip addresses.

**Comment by sowmyav27** [comment]
### Fresh install usecase - On 2.5-head - commit id: `baf4867c`

- Create cluster with Project Network Isolation Enabled 1 etcd/control and 2 worker nodes.
- Pods of `nginx-ingress-controller` in system project do not have podName labels.
- In Debug mode, redeploy `nginx-ingress-controller` and confirm the pods don't get updated without cause. `podHandler: addLabelIfHostPortsPresent: deleting podNameFieldLabel` is NOT seen in logs.
- Deploy user ingress, verified the status.LoadBalancer shows IPs of all the worker nodes - 2 worker nodes.
```
status:
  loadBalancer:
    ingress:
    - ip: <ip-1>
    - ip: <ip-2>
```
---
### Upgrade from 2.5.2 to 2.5-head
On 2.5.2
- Deploy a cluster - 2 worker nodes, 1 etcd/control plane node
- Enable cluster level monitoring
- Deploy a workload and an ingress pointing to the workload.
- User ingress has only one worker node's ip address in status.LoadBalancer
```
status:
  loadBalancer:
    ingress:
    - ip: <wk01>
```
- ingress controller pods in the system project have podName labels
- Create network policies using [doc](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource)
- Upgrade rancher to 2.5-head - blocked because of issue - https://github.com/rancher/rancher/issues/30434
