### ISSUE TITLE
v2.5.2 Rancher doesn't generate .xip hostnames for the TLS Ingress config

### ISSUE THREAD

**Issue by stefannica** [rancher/rancher#30217]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

 * Deploy a helm chart that uses a combination of Ingress and TLS secret (e.g. Harbor)
 * Select to _Automatically generate a .xip.io hostname_ for the ingress rules
 * Enable TLS for the Ingress
 * Launch

**Result:**

The Ingress route rules are properly replaced with `xip.io` generated hostnames, but the `tls` section is left untouched:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  ...
  labels:
    app: harbor
    app.kubernetes.io/managed-by: Helm
    chart: harbor
    heritage: Helm
    io.cattle.field/appId: harbor
    release: harbor
 ...
  name: harbor-harbor-ingress
  namespace: harbor
...
spec:
  rules:
  - host: harbor-harbor-ingress.harbor.10.162.66.51.xip.io
    http:
      paths:
      - backend:
          serviceName: harbor-harbor-portal
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
      - backend:
          serviceName: harbor-harbor-core
          servicePort: 80
        path: /api
        pathType: ImplementationSpecific
...
  tls:
  - hosts:
    - xip.io
    secretName: harbor-harbor-ingress
  
```

**Other details that may be helpful:**

A quick glance at the Rancher code confirms that the TLS Ingress section is ignored by the logic that replaces the `xip.io` hostname with the auto-generated hostname: https://github.com/rancher/rancher/blob/master/pkg/controllers/managementuser/ingresshostgen/ingresshostgen.go#L55-L61

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): HA
