### ISSUE TITLE
Using USER in rancher/rancher-agent docker image to avoid runAsRoot problems

### ISSUE THREAD

**Issue by VannTen** [rancher/rancher#30246]
**What kind of request is this (question/bug/enhancement/feature request):**
bug / enhancement

**Steps to reproduce (least amount of steps as possible):**
- Provision a Kubernetes cluster (not through Rancher)
- Create A PodSecurityPolicy with 
 runAsUser:
    rule: 'MustRunAsNonRoot'
(such as the default one created by kubespray)
- Add the Kubernetes Cluster to Rancher
- Remove the Kubernetes Cluster to Rancher.

**Result:**

The cattle-system becomes stuck in Terminating state.
There is a finalizer left on that namespace : `controller.cattle.io/namespace-auth`
The job cattle-cleanup-<random-suffix> does not work, because the template PodSpec specify an empty securityContext
(template in the Job)
```
      spec:
        containers:
        - env:
          - name: CLUSTER_CLEANUP
            value: "true"
          - name: SLEEP_FIRST
            value: "true"
          image: rancher/rancher-agent:v2.4.6
          imagePullPolicy: Always
          name: cleanup-agent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: cattle-cleanup-52kbq
        serviceAccountName: cattle-cleanup-52kbq
```
But the Pod is mutated by the PSP admission controller using the restricted Policy
see https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups
(resulting pods)
```
spec:
    containers:
    - env:
      - name: CLUSTER_CLEANUP
        value: "true"
      - name: SLEEP_FIRST
        value: "true"
      image: rancher/rancher-agent:v2.4.6
      imagePullPolicy: Always
      name: cleanup-agent
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
```
As a result the pod is prevented from running 
```
    state:
        waiting:
          message: container has runAsNonRoot and image will run as root
          reason: CreateContainerConfigError
```

**Other details that may be helpful:**

The simplest solution would be to add an appropriate USER directive to the rancher-agent Docker image ; that would allow the default mechanism to work nicely.
I would have done it myself but I can not find the relevant Dockerfile in the repository :/

Image version : rancher-agent:v2.4.6
