### ISSUE TITLE
Sidekick is not exposed as "Link" to the "master" service.

### ISSUE THREAD

**Issue by y8** [rancher/rancher#3024]
For example: 

````yml
mongodb:
  tty: true
  image: mongo:3.2.0
  stdin_open: true
app:
  labels:
    io.rancher.sidekicks: mongodb
  tty: true
  image: example.net/my-app
  stdin_open: true
````

With this configuration environment variables, like `MONGODB_PORT_27017_TCP_ADDR` are not set in `app` containers.

Since there no way to explicitly link `mongodb` to `app ` in the Rancher UI, it's expected that 
sidekick will be automatically linked to the `mongodb`, so environment variables will be available.
