### ISSUE TITLE
[UI] OPA Gateway Constraint creating page is not honouring the template in YAML

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#30241]
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Create a new constraint template
2. Click `Create` button in constraint page
3. Click `Edit as YAML`
4.  Paste the following YAML
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowPrivilegeEscalationContainer
metadata:
  name: psp-allow-privilege-escalation-container
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
```
5. Click `Create`

**Result:**
The constraint is created with `K8sAllowedRepos` instead of `K8sPSPAllowPrivilegeEscalationContainer`

**Other details that may be helpful:**
Manually select the template on the UI before clicking `Edit as YAML` then the constraint will get the correct template

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): HA
