### ISSUE TITLE
On host restart nginx keeps failing due to unresolved upstream

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#3026]
After restarting host `nginx` container is unable to find `registry`. It keeps restarting (because nginx exits with error). After manual restart of container it finds `registry`. This happens always after restarting host.

Example configuration (mine setup has additional volumes-from and volumes).
```yaml
nginx:
  ports:
  - 9000:443/tcp
  image: nginx:1.9
  links:
  - registry:registry
registry:
  image: registry:2.2
```
Nginx config:
```nginx
# ...
 proxy_pass http://registry:5000;  
# ...
```

I tried searching for similar issue but have not found one apologies if this is a duplicate.
