### ISSUE TITLE
[Logging v2] Docker Root Dir not exposed for Rancher 2.5.2 logging

### ISSUE THREAD

**Issue by hunghoang** [rancher/rancher#30329]
**What kind of request is this (question/bug/enhancement/feature request):**

I've deployed rancher-logging and created ClusterFlow and ClusterOutput to stream log to ElasticSearch but no log is inserted into ES
**Steps to reproduce (least amount of steps as possible):**
- Using Rancher 2.5.2
- Install App: rancher-logging
- Deploy ElasticSearch 7.9.1
- Create ClusterFlow and ClusterOutput

**Result:**
- No log is written into ElasticSearch

**Other details that may be helpful:**
- No error log fount FluentBit and Fluentd. But I think the problem is our serves configure docker home with  Docker Root Dir: /home/docker/data. How we change the volumemount in Fluentbit configuration ? What else I need to change to make the rancher-logging work?

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal, 256GB RAM
- Kubernetes version (use `kubectl version`): 1.18.8,

```
(paste the output here)
```

- Docker version (use `docker version`):
19.3.12
```
(paste the output here)
```

gz#13801

**Comment by pulberg** [comment]
Same issue here, maybe related to, or a regression of - https://github.com/rancher/rancher/issues/21112

**Comment by oxr463** [comment]
Possible duplicate of https://github.com/rancher/rancher/issues/29952

**Comment by oxr463** [comment]
# Reproduction Steps

1. Modify `/etc/docker/daemon.json` to include the following contents:

```
{
  "data-root": "/opt/docker"
}
```

2. Modify `cluster.yml` to include the following line:

```
docker_root_dir: /opt/docker
```

3. Then restart the docker service, and re-run `rke up`.

# Versions

```
docker --version
Docker version 19.03.14, build 5eb3275d4006e4093807c35b4f7776ecd73b13a7
```

```
rke --version
rke version v1.2.3
```

```
helm list -n cattle-system
NAME           	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART                        	APP VERSION
rancher        	cattle-system	1       	2020-12-08 21:42:10.856571518 +0000 UTC	deployed	rancher-2.5.3                	v2.5.3     
rancher-webhook	cattle-system	1       	2020-12-08 21:44:19.729962301 +0000 UTC	deployed	rancher-webhook-0.1.0-beta700	0.1.0-beta7
```

**Comment by izaac** [comment]
We need https://github.com/rancher/dashboard/issues/2199 for complete E2E testing.

**Comment by izaac** [comment]
Rancher version `v2.5-head (01/26/2020)` _cf8bbee_
Logging chart version: `3.8.201`

I am using an RKE cluster where the nodes have a non-default docker root.

The values in the installed logging chart show this:

```yaml
  values:
    additionalLoggingSources:
      rke:
        enabled: true
        fluentbit:
          mountPath: /mnt/docker-data
    global:
      cattle:
        clusterId: c-jb5db
        clusterName: izectest2
        systemDefaultRegistry: ""
      systemDefaultRegistry: ""
```

Cluster configuration:

![Screen Shot 2021-01-26 at 4 56 27 PM](https://user-images.githubusercontent.com/27659/105925301-1a726000-5ffd-11eb-873a-0b8438e8aed1.png)
![Screen Shot 2021-01-26 at 4 56 15 PM](https://user-images.githubusercontent.com/27659/105925304-1ba38d00-5ffd-
11eb-85a7-38ad138e5417.png)


I create a ClusterFlow and a ClusterOutput I don't get any index created in the logging provider side (Elasticsearch)

All the fluent-bit pods show an output similar to this in the logs:

```
Fluent Bit v1.6.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/01/27 00:27:57] [ info] [engine] started (pid=1)
[2021/01/27 00:27:57] [ info] [storage] version=1.0.6, initializing...
[2021/01/27 00:27:57] [ info] [storage] root path '/buffers'
[2021/01/27 00:27:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/01/27 00:27:57] [ info] [storage] backlog input plugin: storage_backlog.1
[2021/01/27 00:27:57] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 4.8M
[2021/01/27 00:27:57] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2021/01/27 00:27:57] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2021/01/27 00:27:57] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2021/01/27 00:27:57] [ info] [filter:kubernetes:kubernetes.0] API server connectivity OK
[2021/01/27 00:27:57] [ info] [sp] stream processor started
```

No errors or anything so I'm not sure what could be the problem here.
Also not setting the fluentbit `fluentbit.mountPath` results in the same behavior.

**Comment by nickgerace** [comment]
Hmmm this is chart `3.8.2`, which is interesting. If it was `3.9.0`, I'd re-evaluate the new chart. I'll take a look.

**Comment by nickgerace** [comment]
There does not seem to be a regression between `3.8.2` and `3.9.0`. I posted a new PR to clean up the UX. Setting the `mountPath` at installation time to be the same will help determine the issue.

We should test this using the path from https://github.com/rancher/rancher/issues/30329#issuecomment-745459815: `/opt/docker/containers`.

**Comment by izaac** [comment]
@nickgerace I see, I will follow the exact specs in that scenario described in #30329

**Comment by izaac** [comment]
Rancher version `v2.5-head (02/03/2021)` _55384b8_
Logging chart version `3.9.000-rc03 `

Following the scenario described here https://github.com/rancher/rancher/issues/30329#issuecomment-745459815. I used the `/opt/docker/containers` mountPath and `docker-root` docker setting as `/opt/docker` for the nodes in a cluster. The cluster also was configured to use the `docker_root_dir` as `/opt/docker`

After installing from Dashboard this is the excerpt of the values in the `rancher-logging` app:

```
values:
    additionalLoggingSources:
      rke:
        enabled: true
        fluentbit:
          mountPath: /opt/docker/containers
    fluentbit:
      mountPath: ''
```

After this I didn't see any log files collected by the fluentbit pods.

I changed that to also include `mountPath` under `values.fluentbit`:

```
values:
    additionalLoggingSources:
      rke:
        enabled: true
        fluentbit:
          mountPath: /opt/docker/containers
    fluentbit:
      mountPath: /opt/docker/containers
```

Still not seeing the fluentbit pods collecting log files.

**Comment by nickgerace** [comment]
Figured out the issue. The rke daemonset needs to be changed as well. Reflected in a new PR along with better UX after speaking with @izaac and @paynejacob.

**Comment by izaac** [comment]
Needs UI changes: https://github.com/rancher/dashboard/issues/2199

**Comment by izaac** [comment]
Rancher version: `master-head (02/11/2021)` __
Logging chart version: `3.9.000-rc05`

I am only seeing logs from the RKE node filesystem but not from the docker containers.

```json
{
  "_index": "izaac-docker1",
  "_type": "_doc",
  "_id": "_xM-k3cBcv3rcfdnIqg1",
  "_version": 1,
  "_score": 0,
  "_source": {
    "log": "rke: [1613082995.343843059, {\"filename\":\"/var/lib/rancher/rke/log/kubelet_9d4c0cf6af9bb293435b2b94b3977a829ea9d8309ee5a98132e0320fd3e9bcbd.log\",\"log\":\"I0211 22:36:35.343493   23715 streamwatcher.go:114] Unexpected EOF during watch stream event decoding: unexpected EOF\\n\",\"stream\":\"stderr\"}]"
  }
}
```

Values yaml in an RKE cluster using a custom Docker root, Logging chart installed from Dashboard UI:


```yaml
additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
  rke:
    enabled: true
    fluentbit:
      log_level: info
      mem_buffer_limit: 5MB
  rke2:
    enabled: false
affinity: {}
annotations: {}
createCustomResource: false
disablePvc: true
fluentbit:
  resources: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: 'true'
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: 'true'
fluentd:
  resources: {}
fullnameOverride: ''
global:
  cattle:
    systemDefaultRegistry: ''
  dockerRootDirectory: /opt/docker/containers
  psp:
    enabled: true
  systemDefaultRegistry: ''
http:
  port: 8080
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: rancher/banzaicloud-logging-operator
  tag: 3.9.0
imagePullSecrets: []
images:
  config_reloader:
    repository: rancher/jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/fluent-fluent-bit
    tag: 1.6.10
  fluentbit_debug:
    repository: rancher/fluent-fluent-bit
    tag: 1.6.10-debug
  fluentd:
    repository: rancher/banzaicloud-fluentd
    tag: v1.11.5-alpine-9
monitoring:
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    metricRelabelings: []
    relabelings: []
nameOverride: ''
namespaceOverride: ''
nodeSelector:
  kubernetes.io/os: linux
podSecurityContext: {}
priorityClassName: {}
rbac:
  enabled: true
  psp:
    enabled: false
replicaCount: 1
resources: {}
securityContext: {}
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

fluentbit container log from the `rancher-logging-fluentbit` daemonset:

```
Fluent Bit v1.6.10
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2021/02/11 22:32:30] [ info] [engine] started (pid=1)
[2021/02/11 22:32:30] [ info] [storage] version=1.0.6, initializing...
[2021/02/11 22:32:30] [ info] [storage] root path '/buffers'
[2021/02/11 22:32:30] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/02/11 22:32:30] [ info] [storage] backlog input plugin: storage_backlog.1
[2021/02/11 22:32:30] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 4.8M
[2021/02/11 22:32:30] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2021/02/11 22:32:30] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2021/02/11 22:32:30] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2021/02/11 22:32:31] [ info] [filter:kubernetes:kubernetes.0] API server connectivity OK
[2021/02/11 22:32:31] [ info] [sp] stream processor started
```

**Comment by izaac** [comment]
Rancher version `v2.5.6-rc5`
Logging v2 chart version: `3.9.000-rc08`

- RKE EC2 cluster k8s `v1.19.8-rancher1-1`  Ubuntu 18.04
  - 1 etcd, 1 ControlPlane, 3 Workers
- Docker 19.03


I see both logs (containers and rke) flowing and stored in the output.
Everything was configured from the Dashboard UI.
There's a difference from the [scenario](https://github.com/rancher/rancher/issues/30329#issuecomment-745459815) I tested. I set the `mountPath` to `/opt/docker` instead of `/opt/docker/containers` as there's a rule in place for the path to not end with `/` or `containers`

`Error: execution error at (rancher-logging/templates/validate-install.yaml:3:5): global.dockerRootDirectory must not end with suffix: '/' or '/containers' `

Everything else is the same `docker-root` was set to `/opt/docker` and the cluster `dockerRootDir` to the same value.

Volumes are properly picked and set by helm for fluentbit

![Screen Shot 2021-02-22 at 12 08 28 PM](https://user-images.githubusercontent.com/27659/108757178-bd3bd280-7506-11eb-93c6-62f73eb89ed6.png)
![Screen Shot 2021-02-22 at 12 08 23 PM](https://user-images.githubusercontent.com/27659/108757183-bdd46900-7506-11eb-8dc9-ededf42407b8.png)

**Comment by pulberg** [comment]
@izaac Can you please clarify something, I have updated to v2.5.6, but I do not see any bind-mount for my custom docker-root.  Should this have been done automatically via "Volumes are properly picked and set by helm for fluentbit" or is this something that a user has to manually set on existing or upgraded clusters?

**Comment by izaac** [comment]
@pulberg I think you will need to change the this manually as this is a new setting introduced in the 3.9.000 chart. After this upgrading to new chart versions should keep this value automatically.

**Comment by pulberg** [comment]
@izaac Sorry, i'm still not clear on this.  I thought the point of these fixes was for the logging mechanism to pull the docker-root value from the cluster yaml and to then create the proper bind-mounts, why would the user need to manually do anything if all of the required info is available already?  And if i had hundreds of clusters, would you tell me to go update them all by hand or create some automation to do this work?, this should all be done by Rancher, not the user.

**Comment by cbron** [comment]
Hello @pulberg, the point of this issue was to make a non-standard docker root dir compatible with our new logging framework. We are still in the process of reviewing differences between the previous logging framework and new one, and how best to address the differences. In this case there are a few ways to approach the auto-fill situation: per-node, per-cluster, distro differences etc... So we are still researching it, among other things.

**Comment by carlcauchi** [comment]
@izaac / @cbron maybe you can help - I'm trying to mount/create a volume pvc for the fluentd StatefullSets for the /buffer path. The idea is to have an AWS gp2 volume which is mounted in this path so that the buffer is written to a persistant storage so that if the pods restarts, I won't lose any logs in the process.
I cannot find any working configuration for the helm chart which allows creation of a volume for fluentd. Last configuration that I have tried:
```
additionalLoggingSources:
  eks:
    enabled: true
createCustomResource: false
fluentd:
  enabled: true
  fluentdPvcSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
    storageClassName: "gp2"
```

**Comment by nickgerace** [comment]
Hello @carlcauchi: `fluentdPvcSpec` has been deprecated of `bufferStorageVolume`, which is ironically (given the timing) being added in: https://github.com/rancher/charts/pull/1112

I believe that the above PR being merged will expose the field for you. From there, you can use our new chart once it's released by adding it in your Cluster Explorer, or you can upgrade to a future Rancher release containing the change. Alternatively, you can always delete, edit, and recreate the Logging CR yourself to mimic what we are doing too.

Source: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/fluentd_types/
>`fluentdPvcSpec` \[is\] `Deprecated, use bufferStorageVolume`

**Comment by carlcauchi** [comment]
That's great @nickgerace ! Would you be able to share how would the new chart look like to configure a gp2 volume for /buffers and also perhaps a dedicated nodeSelector just for the fluentd deployment?

I'm guessing something like the following in the main values.yaml file you pass to the rancher logging helm chart:

```
fluentd:
  nodeSelector:
    node-type: "workload"
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
          storageClassName: gp2
          volumeMode: Filesystem
```

On another note, what does the `additionalLoggingSources` for `eks` do exactly? As its deploying a new set of fluentd + fluentbit instances (so there would be the default set + an eks set). Does the eks one capture anything else the default one doesn't?
