### ISSUE TITLE
Add catalog.cattle.io/os=linux

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30450]
Need to add new annotation: `catalog.cattle.io/os=linux` to all of our current charts so that they will be hidden in the Apps/Market Place when it's a windows cluster.

- [x]  CIS
- [x]  Logging
- [x]  Backup/restore
- [x]  OPA
- [x]  Istio
- [x]  Monitoring
- [x]  Longhorn
- [x]  external-ip-webhoook

**Comment by aaronRancher** [comment]
Tested with Rancher server `rancher\rancher:master-head` `version 495f7a1d6` and `rancher\rancher:v2.5-head` `version 182e3de71`

On Ubuntu 20.04, OPA `v3.2.1` is available. Annotation is seen:
![Screen Shot 2020-12-14 at 5 01 39 PM](https://user-images.githubusercontent.com/57409052/102153097-a9536080-3e33-11eb-936a-d8707aa30ff4.png)

**Comment by izaac** [comment]
Rancher version: `v2.5-head (12/15/2020)` _182e3de_
Rancher version: `master-head (12/15/2020)` _495f7a1_
`rancher-logging:3.8.201`

Logging chart has these annotations in a Linux only cluster:

```yaml
annotations:
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: "true"
        catalog.cattle.io/namespace: cattle-logging-system
        catalog.cattle.io/release-name: rancher-logging-crd
        catalog.cattle.io/ui-source-repo: rancher-charts
        catalog.cattle.io/ui-source-repo-type: cluster
```
