### ISSUE TITLE
Rancher 2.5.3 creates namespaces with LimitRange of zero, breaks app install

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#30469]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

- create a `kyverno` namespace via the Rancher UI with defaults
- add Kyverno (https://kyverno.github.io/kyverno) repo to Apps and deploy Kyverno with defaults

**Result:**

- the deployment fails with error

<img width="1020" alt="9-kyverno-requests-error" src="https://user-images.githubusercontent.com/171292/102119036-46f06500-3e1f-11eb-8c83-fc60b1bdff80.png">

**Other details that may be helpful:**

Instead of "zero means don't create a limitrange for the namespace," Rancher is creating the namespace with a limitrange of all zeroes, so any deployment that specifies a request higher than 0 but does not also specify a limit higher than 0 fails. This removes the ability to create burstable resources.

```
  spec:
    limits:
    - default:
        cpu: "0"
        memory: "0"
      defaultRequest:
        cpu: "0"
        memory: "0"
      type: Container
```

Kyverno specifies a cpu request of 100m but no cpu limit. This causes Rancher to throw the error.

Upon removing the LimitRange from the namespace, or adding a limit to `values.yaml` for that chart, the deployment succeeds.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA):
