### ISSUE TITLE
Cannot rancher-composer up

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#3047]
I'm getting this error when trying to up an service.

```
pedro@pedro-xps:~/Code/project$ rancher-compose --verbose up -p
DEBU[0000] Environment Context from file : map[]        
DEBU[0000] Opening compose file: docker-compose.yml     
DEBU[0000] [0/1] [atena]: Adding                        
DEBU[0000] [0/1] [fpm]: Adding                          
DEBU[0000] [0/3] [nginx]: Adding                        
DEBU[0000] [0/3] [postgres]: Adding                     
DEBU[0000] Opening rancher-compose file: /home/pedro/Code/project/rancher-compose.yml 
DEBU[0000] Not found: /home/pedro/Code/project/rancher-compose.yml 
DEBU[0001] Looking for stack atena                      
DEBU[0001] Found stack: atena(1e22)                     
DEBU[0001] Launching action for fpm                     
DEBU[0001] Launching action for nginx                   
DEBU[0001] Launching action for atena                   
DEBU[0001] Launching action for postgres                
DEBU[0001] Project [atena]: Creating project            
DEBU[0001] Finding service fpm                          
DEBU[0001] [0/4] [fpm]: Creating                        
DEBU[0001] [0/4] [postgres]: Creating                   
DEBU[0001] Finding service postgres                     
INFO[0001] Creating service fpm                         
INFO[0001] Creating service postgres                    
DEBU[0001] Creating service postgres with hash: digest.ServiceHash{Service:"f68a8954350600516863af202d15b807e55230e6", LaunchConfig:"5493b619d3539dc5c15396ef60dd3b2944563607", SecondaryLaunchConfigs:map[string]string(nil)} 
DEBU[0002] Creating service fpm with hash: digest.ServiceHash{Service:"a8801eccddd52d961c8503f29f43b428bd2db438", LaunchConfig:"e59ee91d932db78d8998a340330fb4083d0b0e6b", SecondaryLaunchConfigs:map[string]string{"atena":"ba56be8375881dfffeb7da466eabb51e3e107a24"}} 
DEBU[0002] Finding service postgres                     
DEBU[0002] Found service postgres                       
DEBU[0002] Finding service fpm                          
DEBU[0002] Found service fpm                            
DEBU[0004] [0/4] [postgres]: Created                    
DEBU[0010] [0/4] [fpm]: Created                         
DEBU[0010] Finding service nginx                        
DEBU[0010] [0/4] [nginx]: Creating                      
INFO[0011] Creating service nginx                       
DEBU[0011] Creating service nginx with hash: digest.ServiceHash{Service:"06edda9f41172f270e12dd7959e1d0215e7b3f08", LaunchConfig:"405a1e3644dec67ca3b9231211327ede8827fdcb", SecondaryLaunchConfigs:map[string]string{"atena":"ba56be8375881dfffeb7da466eabb51e3e107a24"}} 
ERRO[0012] Failed Creating nginx : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://rancher.pedro.com:8080/v1/services] 
ERRO[0012] Failed to start: nginx : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://rancher.pedro.com:8080/v1/services] 
DEBU[0012] [0/4] [atena]: Creating                      
DEBU[0012] [0/4] [atena]: Created                       
FATA[0012] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://rancher.pedro.com:8080/v1/services]
```

__docker-composer.yml__
```yml
atena:
    image: registry.pedro.com:443/atena
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat
fpm:
    image: php:7-fpm
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: atena
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - atena
nginx:
    image: registry.pedro.com:443/laravel-nginx
    links:
        - fpm:fpm
    labels:
        io.rancher.sidekicks: atena
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - atena
postgres:
    image: postgres
    volumes:
        - /var/lib/postgresql/atena:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: atena
        POSTGRES_PASSWORD: deuspedrolindo
    labels:
        io.rancher.scheduler.affinity:host_label: server=08

```

**Comment by alena1108** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3037. Please upgrade to v0.50.1:

http://forums.rancher.com/t/rancher-release-v0-50-1/1272

**Comment by pedrommone** [comment]
@alena1108 i'm already using the latest version!

```
customer@07:~$ docker pull rancher/server:latest
latest: Pulling from rancher/server
Digest: sha256:6ce16284f81f707b571e4bd06691cf3d025edf0e98bcd8ebd5984ed9547fc1e6
Status: Image is up to date for rancher/server:latest
```

```
pedro@pedro-xps:~/Code//laravel-nginx$ rancher-compose 
Usage: rancher-compose [OPTIONS] COMMAND [arg...]

Docker-compose to Rancher

Version: v0.6.2

Author:
  Rancher Labs, Inc.
```

**Comment by deniseschannon** [comment]
@pedrommone Can you try pulling rancher/server v0.51.1 and check that the image IDs match? We only updated latest a couple of hours ago.

**Comment by pedrommone** [comment]
I've updated ~30 minutes a go. :smile:

**Comment by deniseschannon** [comment]
Can you click on the cow in the upper right hand corner of your Rancher set up to make sure the version is v0.50.1?

**Comment by deniseschannon** [comment]
Also, are you sure that there are no services in the stack that you are doing the `rancher-compose up` that do not have any of the same names?

**Comment by pedrommone** [comment]
I rollback to v0.49, but, I was doing `rancher-composer up` and some of the containers were running.

**Comment by deniseschannon** [comment]
If the services are already running in the stack that you are adding services to, then the name validation will fail. 

You cannot have 2 services with the same name in the same stack. Are you trying to upgrade the services to the newer docker-compose.yml that you have? If so, you can use `rancher-compose up --upgrade`.

Read more about in-service upgrades: http://docs.rancher.com/rancher/rancher-compose/upgrading/#in-service-upgrade

**Comment by RVN-BR** [comment]
I'm having a similar issue, but I'm not upgrading... I delete all stacks in my setup, then try a rancher-compose create, and no matter what I name it, one of my containers always comes back with: 
```
ERRO[0003] Failed Creating nginxweb : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://core-01:8080/v1/services]
ERRO[0003] Failed to start: nginxweb : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://core-01:8080/v1/services]
FATA[0003] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique] from [http://core-01:8080/v1/services]
```

Docker compose is pretty standard I think... it is working with docker-compose... but not rancher compose...

```
nginx-static-files:
    build: nginx-static-files
    volumes:
        - /var/www
    labels:
        io.rancher.container.pull_image: always
    command: cat
    tty: true
    stdin_open: true
php5-fpm:
    build: php5-fpm
    ports:
        - 9000:9000
    volumes_from:
        - nginx-static-files
    labels:
        io.rancher.sidekicks: nginx-static-files
        io.rancher.container.pull_image: always
nginxweb:
    build: nginx
    ports:
        - 8080:80
    volumes_from:
        - nginx-static-files
    links:
        - php5-fpm:php5-fpm
    labels:
        io.rancher.sidekicks: nginx-static-files
        io.rancher.container.pull_image: always
```

The php container is going up, with the sidekick (apparently) ok... but the second container that has volumes_from, doesnt work...

If I remove one of the containers volumes_from and sidekick label, then it works... From the above example I understadn it should be working on multiple containers?

![image](https://cloud.githubusercontent.com/assets/1218902/11901423/af76e192-a592-11e5-98dd-604be32a0224.png)

**Comment by deniseschannon** [comment]
@RVN-BR Are you trying to have `php5-fpm` and `nginxweb` use separate `nginx-static-files` services? OR use the same `nginx-static-files` container for both services?

**Scenario 1:** `php5-fpm` and `nginxweb` use volumes from `nginx-static-files`, which are 2 separate services. Since we don't allow 2 services in the same stack to have the same name in order to allow Rancher DNS and metadata to work properly, you would need to define 2 separate `nginx-static-files` services with 2 different names. 

```
nginx-static-files-1:
nginx-static-files-2:
php5-fpm:
      volumes_from:
        - nginx-static-files-1
      labels:
        io.rancher.sidekicks: nginx-static-files-1
nginxweb:
    volumes_from:
        - nginx-static-files-1
    labels:
        io.rancher.sidekicks: nginx-static-files-2 
```

**Scenario 2:** Share the same container (There are some caveats). To share the same container for the `volumes_from`, you'd need to make either `php` or `nginxweb` the primary service and make the `nginx-static-files`, `php5-fpm` as sidekicks. There are some issues that you might hit if this is what you are trying to do:
* With this setup, you can only load balance/target/link the service you make as the primary one (aka whichever service has the sidekick label). We have a feature request that would allow you to share the same data container and be able to load balance. https://github.com/rancher/rancher/issues/2159 
* Links are not established for sidekicked containers. https://github.com/rancher/rancher/issues/1589
* When you have sidekicks and links, rancher-compose will freeze. https://github.com/rancher/rancher/issues/2636
```
nginx-static-files:
php5-fpm:
      volumes_from:
        - nginx-static-files
nginxweb:
    volumes_from:
        - nginx-static-files
    labels:
        io.rancher.sidekicks: nginx-static-files, php5-fpm
```

**Comment by RVN-BR** [comment]
Understood... I need both php & nginx to be "loadbalancable", so I think what I will do for now is clone the application data container into 2 like you suggest in your first scenario, and then hopefully once the restriction is removed for multiple container I can remove the dupplication...

Both nginx and php-fpm need access to the volumes apparently, so I think this is the best scenario... will try it out and revert...

**Comment by RVN-BR** [comment]
I'm getting an extremely long build time, without any progress apparently...

and also getting some WARN[0001] Service php5-fpm is out of sync with local configuration file errors for both the application containers (not the data-only vol)...

Any idea what this might be?  I tried erasing the s3 bucket, deleting the stack and restarting but it always says that...

I wouldnt be too worried if there was any network traffic coming into the host (I'd assume it was pulling images or smothing, but nothing is happening... no network traffic)...

**Comment by RVN-BR** [comment]
A cleanup of the machine and re-run of rancher-server and agent (without using fleet) is now working on the php-fpm container... but its still hanging "activating" the nginx container...

Looking at processes I see a service.activate process that times out after abt 15-20 seconds... If I hit stop on the "hanging" container, and start it again, I get a new process but it always timesout...  I see this in the process api view:
```
"exception": null,
"exitReason": "TIMEOUT",
"name": "service.activate", 
```
No idea whats going on... A regular docker-compose on the same file runs without any issues...

I'd still like to uderstand what the "out of sync with local configuration" means... 

Also, when changing data in a data volume, is changed, what would be the appropriate way to push them up/upgrade the image when using a local build?

**Comment by pedrommone** [comment]
@deniseschannon so, as you told @RVN-BR. I cannot make it:

```
yoda:
    image: registry.fakename.com:443/yoda
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

fpm:
    image: registry.fakename.com:443/laravel-fpm
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: yoda
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - yoda
    links:
        - postgres
    environment:
        APP_URL: yoda.ms.ezlv.com 
        APP_KEY: gotcha
        DB_CONNECTION: pgsql
        DB_HOST: postgres
        DB_DATABASE: yoda
        DB_USERNAME: yoda
        DB_PASSWORD: maytheforcebewithyou

nginx:
    image: registry.fakename.com:443/laravel-nginx
    links:
        - fpm
    labels:
        io.rancher.sidekicks: yoda
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - yoda

postgres:
    image: postgres
    volumes:
        - /var/lib/postgresql/yoda:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: yoda
        POSTGRES_PASSWORD: maytheforcebewithyou
    labels:
        io.rancher.scheduler.affinity:host_label: server=08
```

I cannot have two sidekicks for the same container?

**Comment by RVN-BR** [comment]
@pedrommone If your yoda container is just a data container (I assume from your cat command and context of what I had said), you can try making 2 definitions in the compose file, one calling the service yodanginx and one yodaphp for example, and point both to the same image...  In theory you are then linking each one to a different service (as you have 2 yoda services now), but in practice since they are running the same image you are achieving the same result...  I had mixed results but then started having issues with my general rancher setup, so I had to take a step back and see how to correctly get the nodes working etc as the repo Vagrant setup isnt workable...

**Comment by deniseschannon** [comment]
@pedrommone Your docker-compose shows me that you are trying to create 2 primary services (services that have a sidekick label) that use the same sidekick service, which is currently not possible. This is issue https://github.com/rancher/rancher/issues/2159

The workaround to have individual sidekicks for each primary service requires 2 sidekick services with unique names. Rancher-compose is erroring out due to a name conflict in your stack. Only 1 unique service name per stack. To fix your docker-compose.yml, it would need to look something like this:

```
yoda1:
    image: registry.fakename.com:443/yoda
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

yoda2:
    image: registry.fakename.com:443/yoda
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

fpm:
    image: registry.fakename.com:443/laravel-fpm
    tty: true
    stdin_open: true
    labels:
        io.rancher.sidekicks: yoda1
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - yoda1
    links:
        - postgres
    environment:
        APP_URL: yoda.ms.ezlv.com 
        APP_KEY: gotcha
        DB_CONNECTION: pgsql
        DB_HOST: postgres
        DB_DATABASE: yoda
        DB_USERNAME: yoda
        DB_PASSWORD: maytheforcebewithyou

nginx:
    image: registry.fakename.com:443/laravel-nginx
    links:
        - fpm
    labels:
        io.rancher.sidekicks: yoda2
        io.rancher.scheduler.affinity:host_label: server=08
    volumes_from:
        - yoda2

postgres:
    image: postgres
    volumes:
        - /var/lib/postgresql/yoda:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: yoda
        POSTGRES_PASSWORD: maytheforcebewithyou
    labels:
        io.rancher.scheduler.affinity:host_label: server=08
```

**Comment by sdmorenob** [comment]
Hello friends.
I'm trying to upload a stack to scale a microservice. However, I have not been able to. I get the following error.
```
ERRO[0000] Failed Creating ps_app : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, baseType=error, fieldName=name] from [http://192.168.99.100:8080/v1/services]
ERRO[0000] Failed to start: ps_app : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, baseType=error, fieldName=name] from [http://192.168.99.100:8080/v1/services]
ERRO[0000] Failed to start: ps_db : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, baseType=error, code=InvalidCharacters] from [http://192.168.99.100:8080/v1/services]
FATA[0000] Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, baseType=error, fieldName=name] from [http://192.168.99.100:8080/v1/services]

```
My docker-compose.yml:
```
`ps_db:
  container_name: ps_db
  image: postgres
  env_file: .env
  ports:
    - "5433:5432"

ps_app:
  container_name: ps_app
  # build: .
  image: sdmorenob/postclipsmsback_ps_app
  command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  env_file: .env
  # volumes:
  #   - .:/PostClips/:rw
  ports:
    - "3000:3000"
  #depends_on:
  links:
    - ps_db`
```

and my rancher-compose

```
ps_db:
  scale: 2
ps_app:
  scale: 2

```
I appreciate if you help me
