### ISSUE TITLE
rotateEncryptionKey action does not work on a cluster with custom encryption enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30539]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- On 2.4.8, enable custom encryption on the cluster. Have this in cluster.yml
```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: <base64 encoded>
          - identity: {}
```
- Create some secrets/add them to workloads as environment variables.
- Upgrade to 2.5-head - commit id: `bb69b03`
- View in API of the cluster, do a `rotateEncryptionKey` action on the cluster.
- Cluster goes into updating but errors out
- Error: 
```
This cluster is currently Updating.
Encryption key rotation failed, please restore your cluster from backup
```
- Able to restore the cluster from a snapshot

**Expected Result:**
User should not be allowed to do a `rotateEncryptionKey` action on this type of cluster

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `bb69b03`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE do
- Kubernetes version (use `kubectl version`):

```
1.18.12
```
