### ISSUE TITLE
Enabling custom encryption does not work on 2.5

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30538]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy a DO cluster, enable custom config:
```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: <base64 encoded>
          - identity: {}
```
- The cluster fails to come up with error: `[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [ip]: Get "https://localhost:6443/healthz": dial tcp 127.0.0.1:6443: connect: connection refused, log: Error: error while parsing encryption provider configuration file "/etc/kubernetes/ssl/encryption.yaml": error while parsing file: resources: Required value: at least one resources is required]`

- On the control plane:
```
cat /etc/kubernetes/ssl/encryption.yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources: []
```
**Expected Result:**
The cluster should come up active, the encryption yaml should be set with the values provided in cluster.yml

**Other details that may be helpful:**
It works on 2.4.8

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3/2.5-head - latest
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO rke
- Kubernetes version (use `kubectl version`):

```
1.18 on 2.4.8  and 1.19 on 2.5 (any)
```
