### ISSUE TITLE
[UI] [cluster-manager] external IP services render as unknown unless field.cattle.io annotations are present

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#30533]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Create a service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  clusterIP: None
  externalIPs:
  - 1.1.1.1
  ports:
  - name: telemetry
    port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Result:**

Renders as unknown type in Rancher Cluster Manager UI

**Other details that may be helpful:**

If you add 

```yaml
  annotations:
    field.cattle.io/ipAddresses: '["1.1.1.1"]'
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
```

It then renders properly. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA
