### ISSUE TITLE
The number of etcd snapshots saved in GCS exceeds the retention of backup_config

### ISSUE THREAD

**Issue by xibuka** [rancher/rancher#30565]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. deploy a 1 node k8s cluster via Rancher UI 
2. edit the cluster and `edit as YAML`, config the backup_config of etcd to use google cloud storage as following.
```
    etcd:
      backup_config:
        enabled: true
        interval_hours: 1
        retention: 2
        s3_backup_config:
          access_key: XXXXXXXXXXXXXXXX
          bucket_name: etcd-snapshot-test
          endpoint: storage.googleapis.com
          folder: backups
          region: asia-northeast1
        safe_timestamp: false
```
3. wait and see the snapshots are saved in GCS.
4. delete the snapshot in Rancher UI, and check the file in GCS

**Result:**
the number of snapshots in Rancher is 2, which is not over the retention in the setting.
![image](https://user-images.githubusercontent.com/21263862/102732626-90d8ce00-437e-11eb-8967-ef00058a6f47.png)

However the number of snapshots in GCS is not been limited to 2, the old snapshot is never get removed.
![image](https://user-images.githubusercontent.com/21263862/102732704-c4b3f380-437e-11eb-85b2-b574bea88e22.png)

And even we delete the snapshot in Rancher UI, but it doesn't get removed in GCS.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- v2.4.11

- Installation option (single install/HA):
single install on docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Digital Ocean
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud, 2core CPU and 4GB memory
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-09T16:50:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
> docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.1
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

gz#13882

**Comment by xibuka** [comment]
gz#13882

**Comment by kravciak** [comment]
I was able to reproduce this on v2.4.11.
I noticed missing `secret_key` parameter in reproducer, without it you can't apply cluster changes (error 404)
For access to s3 I used google IAM service account with Storage Admin role.

```
# https://rancher.com/docs/rke/latest/en/etcd-snapshots/recurring-snapshots/#configuring-the-snapshot-service-in-yaml

s3_backup_config:
  access_key: XXXXXXXXXXXXXXXX
  secret_key: XXXXXXXXXXXXXXXX
  ...
```

Used components:
```
Rancher v2.4.11 (docker single node)
Infrastructure provider cluster (DigitalOcean v1.18.16)
1 node cluster s-4vcpu-8gb

# Snapshots visible from rancher
# c-dcq9h-rs-mb6mx snapshot deleted manually
S3 | c-dcq9h-rs-fzg96 | 44 minutes ago -- | -- | --

# Snapshots visible from cloud storage google dashboard
c-dcq9h-rs-8m5sf_2021-03-18T09:26:32Z.zip Mar 18, 2021, 10:26:47 AM	Standard	
c-dcq9h-rs-fzg96_2021-03-18T11:36:32Z.zip Mar 18, 2021, 12:36:46 PM	Standard	
c-dcq9h-rs-mb6mx_2021-03-18T10:31:32Z.zip Mar 18, 2021, 11:31:46 AM	Standard	

```
