### ISSUE TITLE
Missing options (log_driver and log_opt) in docker-compose.yml configuration

### ISSUE THREAD

**Issue by miko** [rancher/rancher#3065]
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2

When starting a new service with rancher-compose using following file:
```
echo:
  image: ubuntu:14.04
  command:
    /bin/echo 'Hello world'
  log_driver: "syslog"
  log_opt:
    syslog-address: "tcp://192.168.1.1:514"
    tag: "{{.Name}}_{{.ID}}"
```
everything works OK (e.g. container is sending out logs to the external syslog host). But when exporting configuration (view/export) both options (log_driver and log_opt) are missing from docker-compose.yml file. Also, when upgrading the service, remote logging no longer works.
