### ISSUE TITLE
system-default-registry behavior changed between 2.4.8 and 2.4.11 for k3s clusters

### ISSUE THREAD

**Issue by asreich** [rancher/rancher#30670]
First ticket here, y'all are awesome btw.

**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Production Cluster: 2x node Rancher 2.4.8, k3s 1.18.8, monitoring 0.1.2 installed
Development Cluster: 2x nodeRancher 2.4.11, k3s 1.18.13, monitoring 0.1.2 installed

Background: Testing upgrade of k3s and Rancher versions on development cluster

On Rancher 2.4.11:

1. Set system-default-registry to `our-artifactory.registry.net/docker` ([repo path style](https://www.jfrog.com/confluence/display/JFROG/Getting+Started+with+Artifactory+as+a+Docker+Registry#GettingStartedwithArtifactoryasaDockerRegistry-TheRepositoryPathMethod))
2. Attempt to upgrade 0.1.2 monitoring to 0.1.4 on RKE cluster, works fine, pulls images from our Artifactory
3. Attempt to upgrade/reinstall 0.1.2 monitoring to 0.1.4 on Rancher Server k3s cluster, fails with "ErrImagePull" cannot pull image `our-artifactory.registry.net/docker/same-components-as-rke`

On Rancher 2.4.8:

Installing monitoring disregards the system-default-registry for the Rancher Server k3s cluster, and installs fine.

**Result:**

When system-default-registry is set to a registry using the repo path style in Rancher 2.4.11, a k3s cluster cannot pull the images

**Other details that may be helpful:**

We use the repo path version of Artifactory's Docker registry, which apparently prevents k3s `registries.yaml` from working properly, based on our testing. Our issue is basically [this rewrite](https://github.com/k3s-io/k3s/issues/2161), we need to be able to have `our-artifactory.valassisdigital.net/docker` as the prefix of `rancher/coredns:1.6.3`.

Reference: https://rancher.com/docs/k3s/latest/en/installation/private-registry/

**Environment information**
Production Cluster: 2x node Rancher 2.4.8, k3s 1.18.8, monitoring 0.1.2 installed
Development Cluster: 2x nodeRancher 2.4.11, k3s 1.18.13, monitoring 0.1.2 installed

A workaround for this is to unset the system-default-registry temporarily, upgrade/install the monitoring in the k3s cluster and then reset the system-default-registry. 

Does this work for other people using a private registry as system-default-registry with k3s? I thought if containerd didn't have the private registry in its mirror list (aka k3s registries.yaml) then it couldn't pull these images? I may be incorrect.

**Comment by AustinReichert** [comment]
Interesting note, some of the pods are successfully starting now. I didn't change anything aside from flipping monitoring on and off/system-default-regsitry none and our private registry. However, if you do a describe on the pod and a get -o yaml

Describe: 
```Containers:
  prometheus-operator:
    Container ID:  containerd://2f99e1ea8033f9c556b501855b63751e6fe169f62153cba025b772677cfe55b6
    Image:         artifactory.valassisdigital.net/docker/rancher/coreos-prometheus-operator:v0.38.1
    Image ID:      artifactory.valassisdigital.net/docker/rancher/coreos-prometheus-operator@sha256:62b8cf466e9b238a9fcf0bcba74562c8833e7451042321e323a46de3f1dbe1bc
```

`get -o yaml`:
```
spec:
...
  image: artifactory.valassisdigital.net/docker/rancher/coreos-prometheus-operator:v0.38.1
...
statuses:
  containerStatuses:
    - containerID: containerd://2f99e1ea8033f9c556b501855b63751e6fe169f62153cba025b772677cfe55b6
      image: docker.io/rancher/coreos-prometheus-operator:v0.38.1
      imageID: artifactory.valassisdigital.net/docker/rancher/coreos-prometheus-operator@sha256:62b8cf466e9b238a9fcf0bcba74562c8833e7451042321e323a46de3f1dbe1bc```

That's the one that started, but Grafana hasn't started and has this for the `get -o yaml`

```
containerStatuses:
  - image: artifactory.valassisdigital.net/docker/rancher/grafana-grafana:7.1.5
    imageID: ""
```
