### ISSUE TITLE
Enabling IDP authentication results in local users no longer getting a valid kubeconfig

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#30689]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug:
  - breaking local users from authenticating via tokens in generated kubeconfig for a cluster
  - also breaks a local user from using a kubectl shell from the ui in the same manor

**Steps to reproduce (least amount of steps as possible):**
- create a local user
- enable an idp authentication (okta saml in my case)
- log in to ui with local user
- click on a cluster
- click "launch kubectl" or "kubeconfig file"

**Result:**
- "launch kubectl" results in a black window with no prompt
- "kubeconfig file" results in a config that has the following user in it:
```
users:
- name: "${cluster}"
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - token
        - --server=${rancher_fqdn}
        - --user=${cluster}
      command: rancher
```
instead of the expected:
```
users:
- name: "${cluster}"
  user:
    token: ${token}
```
  
**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): kubernetes HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 1.18.x
