### ISSUE TITLE
[Cluster Manager UI] Update UI to support new env var structure

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#30683]
Issue: https://github.com/rancher/rancher/issues/16148

The Cluster Manager UI needs to be updated to support the new Name/Value Name/ValueFrom structure.
Only affects Cluster Manager UI.

**Comment by codyrancher** [comment]
@paynejacob

As one of the reviewers for the backend would you mind confirming my understanding here?


Is this the new interface of the `environment` field within the container schema?
```
[
  {
      name: "variableName",
      valueFrom: "secret, config or container if used",
      value: "value for key value pairs or the name of the key within the resource pointed to by valueFrom"
  }
]
```

**Comment by paynejacob** [comment]
Yes it is returned with the container object https://github.com/rancher/rancher/pull/30634/files#diff-7db0a06f1c829c0dd9501d5a34504ab4094a0884a09c6ce671a6add4f1bffa5e

**Comment by PennyScissors** [comment]
@superseb @paynejacob @codyrancher 
Did the following to test how this change will impact workloads created with the previous structure. 

1. Ran Rancher locally, master branch.

2. Deployed a workload in "local" cluster with the following env vars:

Edit YAML View:
```
- name: A
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
- name: B
  value: $(A):5000
```
API UI:
![image](https://user-images.githubusercontent.com/8951271/103953439-0373d880-50f7-11eb-9999-c49b3e21202d.png)

3. Stopped Rancher, pulled in the commits with my changes, and ran Rancher again

4. The workload shows up, env vars are still present in the container.
API UI after pulling in my changes:
![image](https://user-images.githubusercontent.com/8951271/103953807-a9274780-50f7-11eb-9e99-b2dcb82ee9b4.png)

5. UI's environment variables drop down is broken (expected):
![image](https://user-images.githubusercontent.com/8951271/103954098-58641e80-50f8-11eb-9d3a-5bd60cfca759.png)

6. Redeployed workload and added a new variable.  Order was preserved and variables were present in the container and API UI.
```
- name: A
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
- name: B
  value: $(A):5000
- name: C
  value: $(B)
```
![image](https://user-images.githubusercontent.com/8951271/103954385-fa840680-50f8-11eb-8ac0-a6cffbb0dc0d.png)

![image](https://user-images.githubusercontent.com/8951271/103954693-9f9edf00-50f9-11eb-9066-17d09a6d587f.png)
