### ISSUE TITLE
[Continous Delivery] GitRepo and cluster stuck in Modified state indefinitely

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#30696]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a repository on a Git service with a subdirectory named `mongo` which contains a `fleet.yaml` with the following content:

```
namespace: test
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: mongo
  chart: "mongodb"
  repo: "https://charts.bitnami.com/bitnami"
  version: ""
  force: false
  timeoutSeconds: 0
  values:
    auth:
      enabled: false
```
2. Setup a Rancher management server and a k3s downstream cluster
3. Navigate to the `local` Cluster Explorer -> Continuous Delivery and create a `GitRepo` resource specifying the previously created Git URL and `/mongo` subdirectory.
4. Once the status of the `GitRepo` resource has switched to `modified`, inspect the `test` namespace of the downstream cluster and notice that the mongo chart appears to have been successfully rolled out.
5. Monitor the status of the mongo `GitRepo` resource in the Cluster Explorer

**Result:**
Status of GitRepo and Cluster resources never becomes `active` and is stuck on `modified` indefinitely even though the chart deployment was successful.

Could be a parsing issue wherein fleet and Kubernetes interpret literal `null` values differently. Note for example the `nodePort: null` statement in the [chart source file](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/standalone/svc.yaml).

<img width="1360" alt="Screenshot 2021-01-06 at 14 31 20" src="https://user-images.githubusercontent.com/3813921/103773781-e3c3ae00-502b-11eb-9c31-7d75eef9e2cf.png">

<img width="1352" alt="Screenshot 2021-01-06 at 14 15 47" src="https://user-images.githubusercontent.com/3813921/103773693-bd9e0e00-502b-11eb-8a40-09658acef45b.png">

<img width="1349" alt="Screenshot 2021-01-06 at 14 15 57" src="https://user-images.githubusercontent.com/3813921/103773717-c7277600-502b-11eb-95c8-1cf447c36ba9.png">

```
Modified(1) [Bundle asdasdasd-mongo]; deployment.apps test/mongo-mongodb modified {"spec":{"strategy":{"$retainKeys":["type"]},"template":{"spec":{"$setElementOrder/containers":[{"name":"mongodb"}],"affinity":{"nodeAffinity":null,"podAffinity":null},"containers":[{"$setElementOrder/volumeMounts":[{"mountPath":"/bitnami/mongodb"}],"name":"mongodb","resources":{"limits":{},"requests":{}},"volumeMounts":[{"mountPath":"/bitnami/mongodb","subPath":null}]}],"securityContext":{"sysctls":[]}}}}}; service.v1 test/mongo-mongodb modified {"spec":{"$setElementOrder/ports":[{"port":27017}],"ports":[{"nodePort":null,"port":27017}]}}; serviceaccount.v1 test/mongo-mongodb modified {"$setElementOrder/secrets":[{"name":"mongo-mongodb"}]}
```

**Environment information**
Rancher version: v2.5.3

**Comment by jiaqiluo** [comment]
The bug is reproduced on rancher:v2.5-head fc09f27

Steps:
- run Rancher single install
- add a cluster 
- first, install Longhorn because the example chart will create PVC and PV
- Now follow the steps in the issue to create the gitRepo. 

The results are exactly as the issue says.

<img width="1872" alt="Screen Shot 2021-01-06 at 10 24 33 AM" src="https://user-images.githubusercontent.com/6218999/103800314-7ef75c00-5009-11eb-9581-c03d91e657c4.png">
<img width="1869" alt="Screen Shot 2021-01-06 at 10 24 47 AM" src="https://user-images.githubusercontent.com/6218999/103800324-828ae300-5009-11eb-9c2f-fed2ce40618d.png">
<img width="1870" alt="Screen Shot 2021-01-06 at 10 24 59 AM" src="https://user-images.githubusercontent.com/6218999/103800328-83bc1000-5009-11eb-8916-ce922b133f41.png">

**Comment by janeczku** [comment]
Further details: https://github.com/rancher/fleet/issues/189

**Comment by StrongMonkey** [comment]
There is a big improvement in diff comparison. @jiaqiluo make sure we can test multiple applications using fleet and check if fleet has better detection of unnecessary diff reports.

**Comment by jiaqiluo** [comment]
The bug fix is validated on rancher `v2.5-head` 1b5aad6 with the fleet chart `0.3.400-rc07`

The example app used in my [previous comment](https://github.com/rancher/rancher/issues/30696#issuecomment-755442406) is installed successfully into a downstream cluster.

![image](https://user-images.githubusercontent.com/6218999/109347580-9ba55880-7830-11eb-8c5c-b95ea92f0aa4.png)

------

Besides that, [this comment](https://github.com/rancher/fleet/issues/189#issuecomment-772777839) provides another example which tried installing Longhorn in Fleet.
I reproduced the bug in Rancher v2.5.5, and confirm the longhorn was installed successfully and working properly on v2.5-head with fleet chart `0.3.400-rc07`

here is the link to the repo and fleet.yaml: https://github.com/jiaqiluo/fleet-examples/tree/qa/longhorn

**Comment by Shaked** [comment]
I have just upgraded to 2.5.6 and I am still seeing "Modified" on a working deployment. 

I have used the following fleet.yaml: 

```
defaultNamespace: devops
helm:
  releaseName: csi-secrets-store-provider-azure
  repo: https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
  chart: csi-secrets-store-provider-azure
  values:
    enableSecretRotation: true
``` 

which shows the following yaml:

```
status:
  commit: c3411f5f03bf37f339c87cfc4c18e5dcb7ac8dc7
  conditions:
  - lastUpdateTime: "2021-03-10T23:04:05Z"
    message: Modified(1) [Bundle azure-keyvault-driver-helm-charts-azure-keyvault-driver];
      serviceaccount.v1 devops/csi-secrets-store-provider-azure missing; serviceaccount.v1
      devops/secrets-store-csi-driver missing
    status: "False"
    type: Ready
  - lastUpdateTime: "2021-03-10T23:04:05Z"
    status: "True"
    type: Accepted
  - lastUpdateTime: "2021-03-10T22:58:53Z"
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2021-03-10T22:54:37Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2021-03-10T22:58:55Z"
    status: "True"
    type: Synced
``` 
<img width="1249" alt="Dashboard 2021-03-11 15-25-14" src="https://user-images.githubusercontent.com/960015/110794187-28fb9a80-827e-11eb-8ae3-a25a942946b1.png">

While this SA and secrets do exists:

```
╰─$ ku devops get sa | grep secrets-store-csi-driver                                                                                                                                                                130 ↵
secrets-store-csi-driver           1         6d17h
╰─$ ku devops get secrets | grep secrets-store-csi-driver
secrets-store-csi-driver-token-h6tc2                      kubernetes.io/service-account-token   3      6d17h
```

Am I doing something wrong? 

Thank you
Shaked
