### ISSUE TITLE
Health check action strategy

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3076]
Today once service instance becomes unhealthy, we simply destroy it. We need to make health check actions strategy configurable. Following to support:

* destroy once unhealthy - existing strategy 
* noop strategy - do nothing, just provide an indication that the instance is unhealthy 
* perform action based on service's quorum. Lets say you have service of scale=5 and quorum=3. Don't destroy unhealthy instances if the healthy instances count < quorum. 

@cloudnautique ^^ point if any strategy is missing (but don't be too creative! :)

**Comment by cloudnautique** [comment]
Allow a post hook of some sort. Like the ability to run a container. In some instances you might need the ability to run cleanup scripts etc. (one could even fire off an alert! :) )

**Comment by sangeethah** [comment]
Tested with latest build from master.

strategy "none" and "recreate" works expected.

@alena1108 , Can you assign this issue back to me for testing when the changes to  strategy - "recreateOnQuorum" is available?

**Comment by alena1108** [comment]
@sangeethah sure

**Comment by sangeethah** [comment]
Tested with v0.55.0-rc3:

"recreateOnQuorum" strategy is now available for services with health check enabled . There is a UI issue that prevents the quorum to be not set which is tracked in  #3328.

**Comment by flypenguin** [comment]
Are data containers also recreated on failures? Cause my owncloud installation crashes (for some reason) every 2-3 minutes, and then the database settings are all gone, too, although they should be in a data container. 
(If you're interested: catalog item is here - http://is.gd/exlG8j)

**Comment by deniseschannon** [comment]
Yes, data containers are recreated on failures as we don't distinguish between data and non-data containers. You can specify to not recreate in your health check strategy for your sidekick (ie. data container), so your container will be preserved if the health check fails.

**Comment by ianwalter** [comment]
@deniseschannon How would you specify this? Would this example work:
```yml
server:
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
data:
  health_check:
    strategy: noop
```
Or would I have to specify more in the data health_check?

**Comment by ianwalter** [comment]
@flypenguin were you able to fix the issue you mentioned? I can't seem to get a working configuration.

**Comment by deniseschannon** [comment]
@ianwalter The health check action strategy has to be in the service that has a health check enabled. If you click around in the UI when adding services, you can always add a health check strategy when you pick a health check. 

Note: The easiest way to find this is to see it's done in the UI and then click on "View Config" of the stack to see the equivalent docker-compose.yml and rancher-compose.yml.

Destroy once
```
test:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
```

Noop strategy
```
test1:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 2000
    healthy_threshold: 2
```

Destroy based on quorum
```
test2:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    healthy_threshold: 2
    response_timeout: 2000
```
