### ISSUE TITLE
How can i restore the etcd backup? FATA[0018] etcd snapshots are not consistent

### ISSUE THREAD

**Issue by jinchenghe92** [rancher/rancher#30767]
**What kind of request is this (question):**
This issue seems similar to #25410,but is not。

**Steps to reproduce (least amount of steps as possible):**
1. exsit RKE deploy K8s Cluster(two node(100,101))
   - RKE version: v1.0.14 
   - docker version: 19.03.13
   - k8s version && kubectl: v1.17.14
   - etcd version: v3.4.3-rancher1
2. I backkup the etcd, then i copy the cluster.yaml、rke、kubctl and db file to mathine(10)
3. extra mathine to use etcd snapshot-restore(10)：rke etcd snapshot-restore --config rancher-cluster.yml --name /opt/rke/etcd-snapshots/snapshot-1.db

**Result:**
The mathine 10 screen:
INFO[0014] [etcd] Checking if all snapshots are identical 
INFO[0014] Image [rancher/rke-tools:v0.1.66] exists on host [192.168.247.10] 
INFO[0014] Starting container [etcd-checksum-checker] on host [192.168.247.10], try #1 
INFO[0017] [etcd] Successfully started [etcd-checksum-checker] container on host [192.168.247.10] 
INFO[0017] Waiting for [etcd-checksum-checker] container to exit on host [192.168.247.10] 
INFO[0017] Container [etcd-checksum-checker] is still running on host [192.168.247.10] 
INFO[0018] Waiting for [etcd-checksum-checker] container to exit on host [192.168.247.10] 

FATA[0018] etcd snapshots are not consistent

**Other details that may be helpful:**
rancher-cluster.yml
```
nodes:
  - address: 192.168.247.100
    user: docker
    role: [controlplane, worker]
  - address: 192.168.247.101
    user: docker
    role: [etcd]
#  - address: 192.168.247.10
#    user: docker
#   role: [etcd]

#services:
#  etcd:
#    backup_config:
#      interval_hours: 1
#      retention: 30
#
## 当使用外部 TLS 终止，并且使用 ingress-nginx v0.22或以上版本时，必须。
#ingress:
#  provider: nginx
#  options:
#    use-forwarded-headers: "true"
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted):
- Machine type (VM) and specifications (2C/4G):
- Kubernetes version (v1.17.14):

```
cat't work now。
v1.17.14
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
