### ISSUE TITLE
[Question] How to make node-exporter run behind rancher-pushprox

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#30775]
**What kind of request is this (question/bug/enhancement/feature request):**
How can I enable pushprox for node exporter and run it behind the proxy?

**Steps to reproduce (least amount of steps as possible):**
1. Deployed `rancher-monitoring`
2. Enabled `rke` proxy components
3. Enabled `node-exporter`

**Result:**
Metrics are exposed to the public IP and port.

**Other details that may be helpful:**
I have downstream cluster only with public IPs

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by abhi1693** [comment]
@slickwarren Can you help with this issue? Even with v2 monitoring, the metrics are exposed n the public port

**Comment by slickwarren** [comment]
@abhi1693 is this on the same setup as the last ticket I was tagged in that you filed? (vsphere, 8core cluster)

**Comment by abhi1693** [comment]
No, this was a development cluster built on vsphere with 6 nodes 4vcpu, 8gb ram. This was a different cluster built to test the new features of rancher pushprox

**Comment by abhi1693** [comment]
Here is my configuration
[moitoring.zip](https://github.com/rancher/rancher/files/5890726/moitoring.zip)

**Comment by abhi1693** [comment]
@slickwarren Any update?

**Comment by slickwarren** [comment]
you must configure `rancher-pushprox` chart in order to run node exporter behind it.  Once on the charts page, you can add `?hidden` to the URL, which will expose the `rancher-pushprox` chart. 
From there, you need to edit the yaml. You can copy the code below, and update the port from `10015` to the port you want to use: 
```
clients:
  command:
    - pushprox-client
  copyCertsImage:
    repository: rancher/library-busybox
    tag: 1.31.1
  enabled: true
  https:
    caCertFile: ''
    certDir: ''
    certFile: ''
    enabled: false
    insecureSkipVerify: false
    keyFile: ''
    useServiceAccountCredentials: false
  image:
    repository: rancher/pushprox-client
    tag: v0.1.0-rancher1-client
  nodeSelector: {}
  port: 10015
  proxyUrl: ''
  resources: {}
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
  useLocalhost: false
component: node-exporter
global:
  cattle:
    systemDefaultRegistry: ''
  systemDefaultRegistry: ''
metricsPort: 9796
proxy:
  command:
    - pushprox-proxy
  enabled: true
  image:
    repository: rancher/pushprox-proxy
    tag: v0.1.0-rancher1-proxy
  nodeSelector: {}
  port: 8080
  resources: {}
  tolerations: []
serviceMonitor:
  enabled: true
enabled: true

```
