### ISSUE TITLE
rancher-logging installation fails when clusters uses PodSecurityPolicies

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#30771]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a cluster with PodSecurityPolicy Support
* Install rancher-logging

**Result:**
The installation fails because of missing PSPs for the operator pod as well as missing PSPs for the default fluentd and fluentbit logging pods.

**Other details that may be helpful:**
The logging-operator chart allows to activate PSPs with `rbac.psp.enabled: true`. For fluentd and fluentbit you can activate PSPs in the Logging spec with:

```
...
spec:
  fluentbit:
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
....
  fluentd:
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
...
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA
- rancher-logging version: 3.8.2.001
- Kubernetes version: v1.19.6
