### ISSUE TITLE
[rancher-istio] system-charts values.yaml Error: "must specify limits.cpu,limits.memory,requests.cpu,requests.memory"

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#30774]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Setup istio on a cluster level, available for any authenticated user - when enabling auto-inject on a namespace and redeploying pod getting either errors "must specify limits.cpu,limits.memory,requests.cpu,requests.memory" this is when PSP is unrestricted. And this is when restricted - invalid values NET_ADMIN / NET_RAW. 

On enabling "Allow Privilege Escalation" it worked for sometime, but giving errors messages. 

**Result:**
Errors messages 
- PSP is unrestricted: **"must specify limits.cpu,limits.memory,requests.cpu,requests.memory"**
- PSP restricted  **"invalid values NET_ADMIN / NET_RAW"**

**Other details that may be helpful:**

The problem is that the proxy and proxy_init containers injected into Pods by Istio, should be configured with CPU and memory limits and requests. 
However, in the Rancher v2.4 istio chart default values.yaml, there is an extraneous init key, which means there are no limits or requests configured by default. 
(https://github.com/rancher/system-charts/blob/release-v2.4/charts/rancher-istio/1.5.900/values.yaml#L370).
The value has to be set for: limits.cpu, limits.memory, requests.cpu,requests.memory

In values.yaml there is a wrong value "init:" to be removed.
```
  proxy_init:
    # Base name for the istio-init container, used to configure iptables.
    repository: rancher/istio-proxyv2
    tag: 1.5.9
    # Configuration for the proxy init container
    init:
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
```
It should be:
```
  proxy_init:
    # Base name for the istio-init container, used to configure iptables.
    repository: rancher/istio-proxyv2
    tag: 1.5.9
    # Configuration for the proxy init container
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 10Mi
```

**The workaround is:**

Specifying the global.proxy_init.resources and, global.proxy.resources variables "requests and limits" in Rancher 2.4 with Custom Answers in v2.3-v2.4, or in Rancher 2.5 via a custom overlay file
Rancher v2.4: with Custom Answers in v2.3-v2. Below are the defaults which could be used to override:
global.proxy.resources.limits.cpu=2000m
global.proxy.resources.limits.memory=1024Mi
global.proxy.resources.requests.cpu=100m
global.proxy.resources.requests.memory=128Mihow
global.proxy_init.resources.limits.cpu=100m   
global.proxy_init.resources.limits.memory=50Mi   
global.proxy_init.resources.requests.cpu=10m   
global.proxy_init.resources.requests.memory=10Mi

Rancher v2.4: https://rancher.com/docs/rancher/v2.x/en/istio/v2.3.x-v2.4.x/setup/enable-istio-in-cluster/enable-istio-with-psp/

How to override in v2.5, with the default values:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
      proxy_init:
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 10Mi
```
See https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/enable-istio-in-cluster/#overlay-file ).

**Environment information**
- Rancher version (`v2.4`/`v2.5`):
- Installation option (HA):

gz#13939
