### ISSUE TITLE
[2.4] systems pods being scheduled on dead nodes

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#30790]
Backport of https://github.com/rancher/rancher/issues/27734

**Comment by sadiapoddar** [comment]
Reproduced with 2.4.13-rc1, commit id b5935be78
Steps.

1. Created custom clusters of four nodes( 1 (etcd+cntrl) + 3 workers)
2. Powered off one of the worker nodes where coredns pod was running
3. Notices that states all the workload running on that worker node went to updating state.
4. Waited about 30 mins to see if that all the system workloads were running on the powered-off node get created automatically on the other worker nodes. But that the state of workload remained stuck in 'updating' status forever

<img width="1354" alt="Screen Shot 2021-01-12 at 6 23 03 PM" src="https://user-images.githubusercontent.com/72409237/104398990-a916b580-5504-11eb-89e4-2b04629154b3.png">

coredns pod was running on powered off node remain in unkonw state and never recreated on the other available worker node

<img width="1291" alt="Screen Shot 2021-01-12 at 6 28 09 PM" src="https://user-images.githubusercontent.com/72409237/104399005-b16ef080-5504-11eb-98d5-a552712985cd.png">


Deleted one of the system pods, matrics-server which was running on the powered-off node, with 2.4.13-rc1 it spawned the pod on another the available node, not on the powered-off node. 
This behavior was different than what we saw in the 2.4.3 version. 

<img width="1230" alt="Screen Shot 2021-01-12 at 6 39 21 PM" src="https://user-images.githubusercontent.com/72409237/104399536-b97b6000-5505-11eb-8d66-98aff74268f4.png">

**Comment by sadiapoddar** [comment]
Verified on 2.4.13-rc3, 013c03811 by adding the following add-ons

```
monitoring:
  provider: metrics-server
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    toleration_seconds: 15
ingress:
  provider: nginx
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    toleration_seconds: 15
dns:
  provider: coredns
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    toleration_seconds: 15
  
```

1. Created custom clusters of four nodes( 1 (etcd+cntrl) + 3 workers)
2. Powered off two worker nodes, 1. where coredns pod was running and the other where the matrics-server pod was running. 
3. Notices that states all the workload running on that worker nodes went to updating state.
4. All pods with add-ons tolerations were running on these powered off nodes got recreated automatically. 
5. Verified add-ons pods tolerations were set properly in node-scheduling section. 

Related the above steps a few times to make sure with add-ons tolerations pods are not getting scheduled on dead nodes and automatically gets created on the available nodes.

The fix is working with add-ons.
