### ISSUE TITLE
Audit Logs-Additional audit log entries when service is activated using rancher-compose.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3082]
Server version - Build from master
Steps to reproduce the problem:

Activate 2 services in a project using rancher compose up.
``` 
web1:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
web2:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
```

Following are the issue seen:

1. Multiple api.scripts.create entries which have identical values for all the values exposed in the UI.
Are these needed?

2. "api.container.create" event for each of the containers that get created. These entries do not have any containerId in the "ResourceType" field. Note that when I create a service from UI , i dont see api.container.create events for service containers.

3. "api.stack.create" event has "Resource Type" field in the format "stack:1s<id>". Sholud this be "stack:1e<id>" ?

  <img width="1459" alt="screen shot 2015-12-18 at 11 56 49 am" src="https://cloud.githubusercontent.com/assets/4266958/11906042/bd3fdcd4-a57e-11e5-9e89-750ed4851705.png">
