### ISSUE TITLE
[kind/enhancement] - AWS S3 Nested Folder Rancher-Backup Support

### ISSUE THREAD

**Issue by soriaj** [rancher/rancher#30830]
What kind of request is this (question/bug/enhancement/feature request):
- Feature Request
- When using S3 as the rancher-backup target with nested folders (i.e. /backup/cluster1) in S3, the backup will fail. If you create a backup using a non-nested folder (i.e. /backup) on the S3 bucket the backup will complete. Requesting that nested folders be supported when using an S3 object-store.

Steps to reproduce (least amount of steps as possible):
- Deploy rancher-backup using cluster explorer and configure S3 object store as target

Non-Working: Configure backup target using AWS S3 with nested directory/folder (example below)
```
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: <backupName>
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  storageLocation:
    s3:
      bucketName: <bucketName>
      credentialSecretName: <awsCertSecretName>
      credentialSecretNamespace: cattle-resources-system
      endpoint: s3.<region>.amazonaws.com
      folder: /mainDirectory/nestedDirectoryName
      region: <region>
```
Working configuration; Configure backup target using AWS S3 with non-nested directory/folder (example below)
```
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: <backupName>
spec:
  resourceSetName: rancher-resource-set
  retentionCount: 10
  storageLocation:
    s3:
      bucketName: <bucketName>
      credentialSecretName: <awsCertSecretName>
      credentialSecretNamespace: cattle-resources-system
      endpoint: s3.<region>.amazonaws.com
      folder: /mainDirectory
      region: <region>
```
Result:
- Non-working configuration will fail with error message: 'mkdir /tmp/uploadpath108797194/etcd_backups/rke-ddtc-mis-mdg-b: no such file or directory'
- Working configuration will complete successfully

**Other details that may be helpful:**

**Environment information**
- Rancher Version: 2.5.3
- Installation Option:  HA
- Cluster Type: Imported
- Machine Type: VM (8core/24GB RAM)
- Kubernetes Version: 1.18.3
- Docker Version: 19.03.11

gz#14342
