### ISSUE TITLE
HostPath volume type: FileOrCreate creates a directory not a file in RKE provisioned clusters

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#30843]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.5.5 instance and a custom cluster
2. Deploy the following Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: host-path-test
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /foo.txt
      name: hostpath
  volumes:
  - hostPath:
      path: /tmp/foo.txt
      type: FileOrCreate
    name: hostpath               
```

**Result:**

Exec into the Pod and observe that `/foo.txt` is a directory, not a file. Same can be confirmed of `/tmp/foo.txt` on the node running the pod.

**Other details that may be helpful:**

Behaviour not seen on a k3s or rke2 cluster, so this appears to be related to containerized kubelet. Upstream issue reported in kubernetes/kubernetes at https://github.com/kubernetes/kubernetes/issues/84663

**Environment information**
- Rancher v2.5.5
