### ISSUE TITLE
Incorrect workloadSelector spec key in upstream Kiali ServiceEntry model prevents displaying workloadSelector in Kiali UI

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#30876]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**
1. Provision a Rancher v2.5.5 instance and a custom cluster.
2. Deploy the monitoring and istio charts from the Cluster Explorer UI
3. Create a `ServiceEntry` resource with a `workloadSelector`, per the following example from the [Istio Service Entry docs](https://istio.io/v1.7/docs/reference/config/networking/service-entry/#ServiceEntry):
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: details-svc
spec:
  hosts:
  - details.bookinfo.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app: details
```
2. Navigate to `Istio Config` within the kiali UI and open the `details-svc` ServiceEntry.

**Result:**

Observe the workloadSelector is blank with `workloadSelector: ~` per the following screenshot:
![Screenshot from 2021-01-18 15-13-49](https://user-images.githubusercontent.com/9771530/104927014-347ac580-59a1-11eb-9d92-afa46291d488.png)

**Other details that may be helpful:**

I have opened an upstream issue for this at https://github.com/kiali/kiali/issues/3587 and a PR to fix at https://github.com/kiali/kiali/pull/3588

**Environment information**
- Rancher v2.5.5
