### ISSUE TITLE
[Question] Is there any way to preconfigure Rancher ?

### ISSUE THREAD

**Issue by rjshrjndrn** [rancher/rancher#30880]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: rancher
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: ClusterRoleBinding
metadata:
  name: rancher
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: cattle-system
  apiGroup: ""
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: rancher
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      serviceAccountName: rancher
      containers:
      - name: name
        image: rancher/rancher:v2.5.5
        args:
          - "--features"
          - "fleet=false"   # tried comma seperated like `fleet=false,dashboard=false` But it's not working. Single feature disable is working.
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  type: LoadBalancer
  ports:
  - port: 8443
    targetPort: 443
  selector:
    app: rancher
```

**Result:**
This will install rancher with lots of feature.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Cluster creation: `k3d cluster create rancher --k3s-server-arg --no-deploy --k3s-server-arg traefik --network rancher`

## Question
Is there any way to preconfigure
1. admin password
2. Cluster url
3. project - namespace organization ( for example create a project called `dev` and add namespaces `dev` in that)
Something like a `config.yaml` or a set of env vars ?
I tried `CATTLE_FEATURES=fleet=false,dashboard=false`. Seems like it's not working. Other params I couldn't find any docs.
