### ISSUE TITLE
Validate v1 and v2 charts for SLES 15 SP2

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#30892]

**Comment by thehejik** [comment]
### Test environment description

Testing `rancher:v2.5.6-rc2` from official `rancher-latest` chart repo. Kubernetes-`v1.19.7-rancher1-1` is deployed on custom cluster, used `canal` as network provider.

Tested on custom cluster running on Linux KVM hypervisor with `SLE15-SP2 JeOS` images with `kernel-default 5.3.18-24.46-default`, enabled `firewalld`, `apparmor` and `docker-19.03.11_ce-6.34.2` from official `SLE-Module-Containers15-SP2-Updates` channel. 

All VM nodes (1x cp, 1x etcd, 3x workers) with 4CPUs and 8GB RAM each, connected to hypervisor's brctl based bridge.

Used firewalld rules on all nodes:
```
  public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client
  ports: 6443/tcp 2376-2380/tcp 8472/udp 9099/tcp 80/tcp 443/tcp 10250-10252/tcp 10254/tcp 30000-32767/tcp 9796/tcp
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:
 ```
