### ISSUE TITLE
Feature chart links to components fails to load using custom CIDR in the cluster.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30901]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install HA RKE Rancher v2.5.5 
These settings were used with the rke `cluster.yml`

```yaml
    services:
      kube-api:
        service_cluster_ip_range: 198.19.0.0/16
      kube-controller:
        cluster_cidr: 198.18.0.0/16
        service_cluster_ip_range: 198.19.0.0/16
      kubelet:
        cluster_domain: cluster.local
        cluster_dns_server: 198.19.0.10
```

Deploy a downstream I used the RKE DO provider and edit as YAML before provisioning to set the above settings.

- Go to dashboard
- Install the monitoring v2 chart
- Install Istio

**Result:**

Trying clicking in the Monitoring links: Promethreus, Alertmanager, Grafana, P. Graph, P. Targets, P. Rules. Results in a 500  after the request times out.

**Environment information**
- Rancher version: `v2.5.5`
- Installation option: HA
- OS ubuntu 18.04 for both HA cluster and Downstream cluster.
