### ISSUE TITLE
Istio v2 chart links to components fails to load using custom CIDR in the cluster.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#30902]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Install HA RKE Rancher v2.5.5 
These settings were used with the rke `cluster.yml`

```yaml
    services:
      kube-api:
        service_cluster_ip_range: 198.19.0.0/16
      kube-controller:
        cluster_cidr: 198.18.0.0/16
        service_cluster_ip_range: 198.19.0.0/16
      kubelet:
        cluster_domain: cluster.local
        cluster_dns_server: 198.19.0.10
```

Deploy a downstream I used the RKE DO provider and edit as YAML before provisioning to set the above settings.

- Go to dashboard
- Install the Istio v2 chart
- Install Istio

**Result:**

Trying to click in the Istio Jaeger or Kiali links results in a 500 after the request times out.

**Environment information**
- Rancher version: `v2.5.5`
- Installation option: HA
- OS ubuntu 18.04 for both HA cluster and Downstream cluster.

**Comment by cbron** [comment]
Similar to https://github.com/rancher/rancher/issues/30901

**Comment by aiyengar2** [comment]
Since we're closing https://github.com/rancher/rancher/issues/30901 out in favor of this, we'll need to ensure that the Monitoring Pane links (Prometheus, Grafana, Alertmanager) also work when the fix is in for this.

**Comment by izaac** [comment]
@aiyengar2 @cbron I had a conversation with @brendarearden today about this issue because she wasn't able to reproduce it.

Decided to try it again and I followed the exact same steps and setup described in the issue description.

Rancher version: `v2.5.5`
Monitoring chart version: `9.4.202`
Istio chart version: `1.7.301`

- Rancher self signed certs.
- Local RKE HA cluster with the services using the custom CIDR and hosted in AWS
- Downstream RKE EC2 driver cluster (Cluster 1)
- Second Downstream RKE EC2 driver cluster (for v1 charts checks)
  - Istio 1.5.900
  - Monitoring 0.2.0


Links worked for both monitoring and Istio v2 charts in cluster 1.
Links worked for both monitoring and Istio v1 charts in cluster 2.

**Comment by cbron** [comment]
Bumping this to 2.5.7, @izaac if you see this again can you save the setup and we can take a look. We can adjust milestone at that point.

**Comment by cbron** [comment]
Have we seen this one since ? If not I will put in backlog.

**Comment by izaac** [comment]
Rancher version: `v2.5-head (03/15/2021)` _38649e2_
Monitoring chart version: `9.4.204-rc04`
Istio chart version: `1.8.300-rc01`

I was able to click in the links from the Dashboard and the links opened fine for both Monitoring and Istio/
Below are the configurations used.


### Local cluster RKE services section

```yaml
services:
    kube-api:
      service_cluster_ip_range: 198.19.0.0/16
    kube-controller:
      cluster_cidr: 198.18.0.0/16
      service_cluster_ip_range: 198.19.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 198.19.0.10
```


### Downstream cluster services section excerpt

```yaml
    kube-api:
      service_cluster_ip_range: 198.19.0.0/16
      service_node_port_range: 30000-32767
    kube-controller:
      cluster_cidr: 198.18.0.0/16
      service_cluster_ip_range: 198.19.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 198.19.0.10
    kubeproxy:
      extra_args:
        cluster-cidr: 198.18.0.0/16
```

**Comment by cbron** [comment]
Ok, moved to backlog for now, if we don't see it we can close.

**Comment by MKlimuszka** [comment]
@samkulkarni20 , this isn't a top priority, but please put this in a queue for infracloud QA to validate.

**Comment by vivek-infracloud** [comment]
### Validated this issue for v1 and v2 charts.

### On rancher version 2.5.12 and following versions for monitoring and Istio the issue is not active for v2 charts.
Kiali and Jaeger links open up fine.
Monitoring : 16.6.1+up16.6.0
Istio : 1.11.700


However, the issue is still active for v1 charts.

**Rancher version: v2.5.12**
**Monitoring chart version: 0.2.2
Istio chart version: 1.5.901**

I was able to open the Kiali without any error. However, the Jaeger failed to open and shows following error.
![JaegerFailed](https://user-images.githubusercontent.com/83208989/162184805-3eb4916d-ca17-4087-a756-901fc520daf9.png)


**Local cluster RKE services section**
```
services:
    kube-api:
      service_cluster_ip_range: 198.19.0.0/16
    kube-controller:
      cluster_cidr: 198.18.0.0/16
      service_cluster_ip_range: 198.19.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 198.19.0.10

```

**Downstream cluster services section excerpt**
```
    kube-api:
      service_cluster_ip_range: 198.19.0.0/16
      service_node_port_range: 30000-32767
    kube-controller:
      cluster_cidr: 198.18.0.0/16
      service_cluster_ip_range: 198.19.0.0/16
    kubelet:
      cluster_domain: cluster.local
      cluster_dns_server: 198.19.0.10
    kubeproxy:
      extra_args:
        cluster-cidr: 198.18.0.0/16
```
