### ISSUE TITLE
Add configurable delay parameter between restarts upon crash/exit/fail/etc.

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3096]
For instance I'd like my containers to be restarted with 60 seconds delay after they crash/exit/fail/etc. Exponential delay with upper limit would be another nice addition to reduce the load on hosts that run rancher agents. I think docker labels is a good place to store such configuration.

**Comment by amalagaura** [comment]
We ran into this. We had a few services which were failing on startup. They started getting continuously restarted and caused a huge load on the system. We eventually had a lot of problems.

I would prefer to have the startup delay be exponential with an upper limit by default as suggested. After 4-5 tries, why keep trying? Rancher should be smarter than that.

**Comment by yaroslavbikov** [comment]
@amalagaura I managed to limit retrying by the following in rancher-compose file:
```
    dbupgrade:
      health_check:
        strategy: none
        unhealthy_threshold: 1
        healthy_threshold: 1
```
