### ISSUE TITLE
[v2.5.5] Monitoring V2 - Adding remoteWrite with tlsConfig is not working as expected

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#30991]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
- Configure Thanos receiver with TLS in an external system 
- Create a secret in the cluster with cert, key and ca.
```
kubectl create secret generic client-certs --from-file=ca.crt --from-file=tls.crt --from-file=tls.key -n cattle-monitoring-system 
```
- Deploy Monitoring chart with below Helm values
```
    remoteWrite:
      - url: 'https://<THANOS_ENDPOINT>:10908/api/v1/receive'
        tlsConfig:
          ca:
            secret:
              name: client-certs
              key: ca.crt
          cert:
            secret:
              name: client-certs
              key: tls.crt
          keySecret:
            name: client-certs
            key: tls.key
          insecureSkipVerify: true
```

**Result:**
- Prometheus errors out with below log 
```
level=error ts=2021-01-25T11:27:47.767Z caller=main.go:608 msg="Error reloading config" err="one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
```

**Other details that may be helpful:**

Output from Pod `prometheus-rancher-monitoring-prometheus-0`  shows that the `prometheus.env.yaml` is populated but no certificates were present in the mentioned path.

```
cat /etc/prometheus/config_out/prometheus.env.yaml  
...   
remote_write:
- url: https://192.168.110.192:10908/api/v1/receive
  remote_timeout: 30s
  tls_config:
    insecure_skip_verify: true
    ca_file: /etc/prometheus/certs_client-certs_ca.crt
    cert_file: /etc/prometheus/certs_client-certs_tls.crt
    key_file: /etc/prometheus/certs_client-certs_tls.key
```
No certificate files present inside Prometheus pod 
```
/ $ ls -l /etc/prometheus/
total 12
drwxrwsrwt    3 root     2000            80 Jan 19 09:23 certs
drwxrwsrwx    2 root     2000          4096 Jan 25 11:24 config_out
lrwxrwxrwx    1 nobody   nogroup         39 Jun  9  2020 console_libraries -> /usr/share/prometheus/console_libraries
lrwxrwxrwx    1 nobody   nogroup         31 Jun  9  2020 consoles -> /usr/share/prometheus/consoles/
-rw-r--r--    1 nobody   nogroup        926 Jun  9  2020 prometheus.yml
drwxr-xr-x    3 root     root          4096 Jan 19 09:23 rules
/ $ 

/ $ ls -l /etc/prometheus/certs/
total 0
/ $ 
```
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

gz#14545

**Comment by ansilh** [comment]
Looks like we need the recent operator with his commit https://github.com/prometheus-operator/prometheus-operator/commit/be0bf2fc267f3229e351c43870dccb16a0492a07 to get it working (at least v0.42.0)

Linking this to the chart upgrade tracker https://github.com/rancher/rancher/issues/29871

**Comment by ansilh** [comment]
Instead of using the configmap/secret, we can get the secret mounted inside the prometheus Pod and then use `File` option in `tlsConfig` to point to the certificates.

The steps are outlined below.

- Create a secret with CA, certificate & key

```
kubectl create secret generic client-certs --from-file=ca.crt --from-file=tls.crt --from-file=tls.key -n cattle-monitoring-system 
```
- Add secret name to values.yaml

```
  prometheusSpec:
    secrets:
      - client-certs
``` 
- Add remoteWrite configuration
```
    remoteWrite:
      - tlsConfig:
          caFile: /etc/prometheus/secrets/client-certs/ca.crt
          certFile: /etc/prometheus/secrets/client-certs/tls.crt
          insecureSkipVerify: false
          keyFile: /etc/prometheus/secrets/client-certs/tls.key
        url: 'https://192.168.110.192:10908/api/v1/receive'
```
- After upgrading the chart, the certificates will be mounted as below.
```
/prometheus $ ls -l /etc/prometheus/secrets/client-certs/
total 0
lrwxrwxrwx    1 root     root            13 Jan 27 15:38 ca.crt -> ..data/ca.crt
lrwxrwxrwx    1 root     root            14 Jan 27 15:38 tls.crt -> ..data/tls.crt
lrwxrwxrwx    1 root     root            14 Jan 27 15:38 tls.key -> ..data/tls.key
/prometheus $ 
```
- Prometheus get below config
```
remote_write:
- url: https://192.168.110.192:10908/api/v1/receive
  remote_timeout: 30s
  tls_config:
    insecure_skip_verify: false
    ca_file: /etc/prometheus/secrets/client-certs/ca.crt
    cert_file: /etc/prometheus/secrets/client-certs/tls.crt
    key_file: /etc/prometheus/secrets/client-certs/tls.key
```
