### ISSUE TITLE
Unable to attach a persistent volume in vsphere in-tree cluster's workload in k8s 1.20

### ISSUE THREAD

**Issue by sadiapoddar** [rancher/rancher#31172]
on 2.5-head, commit eb160e0 and master-head commit fbe2c30
Rancher server docker version:  20.10.1
1. Created a in-tree cluster using rancher's node driver ( providing vsphere datacenter info as cloud provider) 
```
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    global:
      insecure-flag: true
      soap-roundtrip-count: 0
    virtual_center:
      x.x.x.com:
        user: VCENTER_USER_NAME
        password: VCENTER_PASSWORD
        port: 443
        datacenters: vCenter Name
    workspace:
      server: x.x.x.com
      folder: /XXX/vm/
      default-datastore: /XX/datastorename
      datacenter: xxx
      resourcepool-path: /x/x/x1/Resources/RESOURCE_POOL
```
2. Created a storage class type "VMware vSphere" 
3. During creating a workload of type deployment, choose "add volume" --> "Add a new persistent volume(claim) and chose the storage class created on step 2
4. The container creation is in a hang state since it couldn't attach the pv with the workload
<img width="1262" alt="Screen Shot 2021-02-06 at 3 40 55 PM" src="https://user-images.githubusercontent.com/72409237/107133900-d6574900-68a1-11eb-86b6-8cb5ad1466d3.png">

5. Rancher UI is showing a pv is been created with the following vmkd id
<img width="781" alt="Screen Shot 2021-02-06 at 4 12 02 PM" src="https://user-images.githubusercontent.com/72409237/107132708-2d572100-6896-11eb-9a65-a980d164f863.png">

6. Checked on the vCenter for the pv's  vmdk in kubevol and seeing the vmkd is there but the size is zero 
<img width="1239" alt="Screen Shot 2021-02-06 at 4 06 03 PM" src="https://user-images.githubusercontent.com/72409237/107132593-43b0ad00-6895-11eb-9da9-55aa0aa24646.png">

Repeated the tests on 2.5.6-rc4 and master-head the same issue, pv attachment is failing. 

Additional info that can be helpful, when tried the same test on v2.5.5, the workload deployment attaching a pv with it was successful.

I have the setup can complete logs available for debugging.

**Comment by mrajashree** [comment]
The error is due to invalid datastore path. Nothing changed between these two versions with respect to the in-tree provider. And the changes for out-of-tree only apply if the chart is launched. So I think the input needs to be checked again

**Comment by deniseschannon** [comment]
@sadiapoddar Yes, can you please re-try and let me know what happens. I'm surprised this is blocking out of tree cloud provider testing as this has nothing to do with in-tree.

**Comment by sadiapoddar** [comment]
Check the datastore path,  there was no error in input for the datastore path, the same datastore was used on v2.5.5 and it worked.

On v2.5.5 the k8s version is v1.19.7 and retried the same test on 2.5-head, commit  eb160e06
The same test with k8s 1.19.7, workload creation with a persistent volume attached worked without any issue. 
Looks like the issue with k8s version, on 2.5-head, commit eb160e06 the default version is v1.20.2

Hi Denise, why I marked it blocker since all our in-tree to out-tree migration tests require that cluster needs to have at least a workload with a persistent volume attached to the workload. From in-tree to out-tree migration we are testing CPI and CSI drivers migration, we can't test CSI  migration if there is no PV attached workload in the migration process.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head eb160e0

* Created a 1.19 cluster with cloud provider enabled
* Created a workload with a PV from vSphere storage class
  * This attaches and mounts correctly
* Upgraded the cluster to 1.20
* Attempt to create a workload with PV from the same storage class used earlier and see the same error as in the opening issue, even though nothing changed aside from the k8s version. 

Datastore path is correct.

**Comment by dramich** [comment]
This could be related to [this change](https://github.com/kubernetes/kubernetes/commit/6c4c5ab691a41a29283cf72ae0d17c6f202cd755) which was introduced in 1.20 line

**Comment by deniseschannon** [comment]
@dramich Can you file an issue with k8s as it looks like it's a k8s 1.20 issu with the vsphere in tree cloud provider. 

We will release note this: @Jono-SUSE-Rancher and this isn't a blocker for the release.

Note: for anyone who finds this, Rancher supports the out of tree vsphere cloud provider starting as of v2.5.6 which is when k8s 1.20 support was introduced.

**Comment by SheilaghM** [comment]
Since we now support out-of-tree provider, do we still need this ticket/fix @deniseschannon ?

**Comment by deniseschannon** [comment]
Yes, even though vSphere doesn't recommend the in-tree, we should still note when this gets fixed. Did @dramich open an upstream issue?

**Comment by SheilaghM** [comment]
This is actually a docs/configuration bug and no upstream issue is needed.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 67228a3

The problem here was not following the cloud provider format specified by the in-tree cloud provider docs. Using the format from the cloud provider docs (https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#template-config-file) which does not include the full path to the datastore allows the user to provision the volume successfully:
```
cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
      virtual_center:
        my.virtualcenter.com:
          user: user
          password: supersecret
          port: 443
          datacenters: datacenter
      workspace:
        server: my.virtualcenter.com
        folder: /
        default-datastore: datastore
        datacenter: datacenter
        resourcepool-path: resourcepool
```

I also tested a scenario where I created a cluster using the previously used format and saw it fail to provision the volume, then updated the cluster's cloud provider to the format specified above and was then able to see the volume provision successfully. 

Our docs however, specify using the full path to the datastore: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/

I've logged an issue to update the docs here: https://github.com/rancher/docs/issues/3071
