### ISSUE TITLE
Rancher v2.5.2 install cert-manager

### ISSUE THREAD

**Issue by tinohager** [rancher/rancher#31183]
**What kind of request is this (question/bug/enhancement/feature request):** question

**Steps to reproduce (least amount of steps as possible):**

I have add the Repository `charts.jetstack.io`
![image](https://user-images.githubusercontent.com/8215186/107243278-2282c480-6a2d-11eb-89ce-5b4d50323d90.png)
After that i have install `cert-manager`
![image](https://user-images.githubusercontent.com/8215186/107244389-409cf480-6a2e-11eb-85a1-c6872167a581.png)
![image](https://user-images.githubusercontent.com/8215186/107243702-91601d80-6a2d-11eb-98cb-a35732e45967.png)

Now i try to activate the certbot for my nginx ingress, i have not found any ui for this.
Now i try to add a `ClusterIssuer` via `kubectl` but i have always this error `error: unable to recognize "letsencrypt-issuer-staging.yaml": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"`

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: user@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: example-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
```

`kubectl describe crd clusterissuers.cert-manager.io`
> Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "clusterissuers.cert-manager.io" not found

`kubectl get crd`

> NAME                                                  CREATED AT
> alertmanagers.monitoring.coreos.com                   2020-11-16T22:49:23Z
> apps.catalog.cattle.io                                2020-11-16T22:49:26Z
> bgpconfigurations.crd.projectcalico.org               2020-11-16T22:46:16Z
> bgppeers.crd.projectcalico.org                        2020-11-16T22:46:16Z
> blockaffinities.crd.projectcalico.org                 2020-11-16T22:46:16Z
> clusterauthtokens.cluster.cattle.io                   2020-11-16T22:46:52Z
> clusterinformations.crd.projectcalico.org             2020-11-16T22:46:16Z
> clusterrepos.catalog.cattle.io                        2020-11-16T22:49:26Z
> clusters.management.cattle.io                         2020-11-16T22:49:26Z
> clusteruserattributes.cluster.cattle.io               2020-11-16T22:46:52Z
> features.management.cattle.io                         2020-11-16T22:49:26Z
> felixconfigurations.crd.projectcalico.org             2020-11-16T22:46:16Z
> globalnetworkpolicies.crd.projectcalico.org           2020-11-16T22:46:16Z
> globalnetworksets.crd.projectcalico.org               2020-11-16T22:46:16Z
> hostendpoints.crd.projectcalico.org                   2020-11-16T22:46:16Z
> ipamblocks.crd.projectcalico.org                      2020-11-16T22:46:16Z
> ipamconfigs.crd.projectcalico.org                     2020-11-16T22:46:16Z
> ipamhandles.crd.projectcalico.org                     2020-11-16T22:46:16Z
> ippools.crd.projectcalico.org                         2020-11-16T22:46:16Z
> kubecontrollersconfigurations.crd.projectcalico.org   2020-11-16T22:46:16Z
> networkpolicies.crd.projectcalico.org                 2020-11-16T22:46:16Z
> networksets.crd.projectcalico.org                     2020-11-16T22:46:16Z
> operations.catalog.cattle.io                          2020-11-16T22:49:26Z
> preferences.management.cattle.io                      2020-11-16T22:49:26Z
> prometheuses.monitoring.coreos.com                    2020-11-16T22:49:23Z
> prometheusrules.monitoring.coreos.com                 2020-11-16T22:49:23Z
> servicemonitors.monitoring.coreos.com                 2020-11-16T22:49:23Z
> settings.management.cattle.io                         2020-11-16T22:49:26Z

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.2
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.19.4
