### ISSUE TITLE
Default to IfNotPresent for the rancher-audit-log container

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#31182]
This is cont. of original v2.5.6 issue https://github.com/rancher/rancher/issues/30582 for v2.6

For testing purposes we need 2.6x candidate to be available.

Related PR into master https://github.com/rancher/rancher/pull/30648

**Comment by thehejik** [comment]
In current `rancher/rancher:master-head` `b202f20` after enabling audit logging by `helm upgrade [...] --set auditLog.level=1` I can see that sidecar `audit-log busybox` container has:
``` yaml
    ...
    image: busybox
    imagePullPolicy: IfNotPresent
    name: rancher-audit-log
```

Prior this fix there was `imagePullPolicy: Always` set. The issue seems to be fixed in master branch, closing.
