### ISSUE TITLE
Rancher metadata casting int32/int64 to float64

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3123]
Hi,

Rancher metadata is casting int32/64 to float64.

rancher-compose.yml
```
influxdb:
  metadata:
    config:
      hinted-handoff:
        max-size: 1073741824
```

Then, metadata query:
```
curl http://rancher-metadata/latest/services/influxdb/met
adata/config/hinted-handoff/max-size                                            
1.073741824e+09
```
