### ISSUE TITLE
Unable to edit a Deployment with Cluster Explorer UI form when not created via the Cluster Explorer

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#31235]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug  / Enhancement

**Steps to reproduce (least amount of steps as possible):**
Create a deployment with legacy GUI Cluster Manager
Edit the deployment with "Config" View of Cluster Explorer by setting a new image

**Result:**

```
Deployment.apps "my-deployment" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"workload.user.cattle.io/workloadselector":"apps.deployment-my-namespace-my-deployment"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.5
- Installation option (single install/HA):
HA

Editing the YAML from the GUI works.

Other details irrelevant IMHO

**Comment by mscbpi** [comment]
2.5.6: 
Still struggling with this error when editing deployment with Cluster Explorer GUI

**Comment by benoist** [comment]
Hi,

We have the same issue.

Is there a way can we migrate the deployments from cluster manager to cluster explorer without having to recreate it with a different name?

**Comment by axeal** [comment]
This issue appears to apply to any Deployment resource that is not created via the Cluster Explorer UI, when an edit is then attempted by the `Edit Config` form for the Deployment within the Cluster Explorer.

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.5.7 instance, managing a single all role node custom cluster
2. Source kubeconfig for the custom cluster and deploy nginx example Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
3. Navigate to the Cluster Explorer UI, and click `Edit Config`
4. Make a change to the Deployment specification, i.e. scale the number of replicas or update the image and click `Save`

**Result:**

Observe an error of the format `Deployment.apps "nginx-deployment" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"workload.user.cattle.io/workloadselector":"apps.deployment-default-nginx-deployment"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

**Other details that may be helpful:**

Same behaviour occurs when creating the Deployment via the `Deploy` form in the Cluster Manager UI, and then attempting to edit via `Edit Config` form in the Cluster Explorer UI. Editing the Deployment via the `Edit YAML` option in the Deployments view of Cluster Explorer works as expected, but not navigating to `Edit as YAML` via the `Edit as Config` form, which adds the offending selector.

**Environment information**
- Rancher v2.5.7
