### ISSUE TITLE
RKE network config is not correctly applied when creating custom cluster

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#31236]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. In the UI click on "Add Cluster"
2. Click on "Existing Nodes" and then click on "Edit as Yaml"
3. Enter the following config in the `rancher_kubernetes_engine_config` block to enable the Cisco ACI network plugin ([available in Rancher API since 2.5.5](https://github.com/rancher/rancher/blob/v2.5.5/pkg/client/generated/management/v3/zz_generated_network_config.go#L19)):
```
  network:
    plugin: "aci"
    aci_network_provider:
      system_id: "rancher"
      apic_hosts:
      - "172.28.184.110"
      token: "2f8cc816-21e6-49d3-b18e-00d1bf38f37d"
      apic_user_name: "rancher"
      apic_user_key: "ABC"
      apic_user_crt: "ABC"
      encap_type: "vxlan"
      mcast_range_start: "225.10.1.1"
      mcast_range_end: "225.10.255.255"
      aep: "sauto-aep"
      vrf_name: "sauto_l3out-1_vrf"
      vrf_tenant: "common"
      l3out: "sauto_l3out-1"
      node_subnet: "10.100.1.1/24"
      l3out_external_networks:
      -  "sauto_l3out-1_epg"
      extern_dynamic: "10.3.0.1/24"
      extern_static: "10.4.0.1/24"
      node_svc_subnet: "10.5.0.1/24"
      kube_api_vlan: "213"
      service_vlan: "214"
      infra_vlan: "4081"
      service_monitor_interval: "5" 
```

4. Click on "Next" to create the cluster object in Rancher
5. Click the context menu for the cluster to edit it
6. Inspect the network configuration in the YAML editor. Note how the entire `aci_network_provider` YAML block is missing.
<img width="294" alt="Screenshot 2021-02-10 at 12 34 09" src="https://user-images.githubusercontent.com/3813921/107506417-56312c00-6b9e-11eb-9d56-8de2933cc257.png">

7. Enter the same network configuration again as in step 3 and click on "Save"
8. Inspect again the network configuration in the cluster YAML editor. Note how the `aci_network_provider` YAML block is now present but some of its subkeys are still missing, e.g. `l3out`.
<img width="439" alt="Screenshot 2021-02-10 at 12 47 39" src="https://user-images.githubusercontent.com/3813921/107506511-7365fa80-6b9e-11eb-9358-123a6c21deec.png">

**Expected Result:**
The RKE `rancher_kubernetes_engine_config` provided in the YAML editor is correctly applied to the cluster configuration.

**Actual Result:**

The configuration is applied inconsistently and incomplete.

**Other details that may be helpful:**

Possibly related to erroneous unmarshalling of the nested RKE config JSON object

**Environment information**
- Rancher version: v2.5.5

**Comment by kinarashah** [comment]
Fixed in `v2.5-head`, created cluster and passed the following in Edit as yaml option. They only difference was I got back the l3out field as `l3_out` after cluster was created. Works with Edit as well.

```
  network:
    aci_network_provider:
      aep: sauto-aep
      apic_hosts:
        - 172.28.184.110
      apic_refresh_time: '1200'
      apic_user_crt: ABC
      apic_user_key: ABC
      apic_user_name: rancher
      encap_type: vxlan
      extern_dynamic: 10.3.0.1/24
      extern_static: 10.4.0.1/24
      infra_vlan: '4081'
      l3_out: sauto_l3out-1
      mcast_range_end: 225.10.255.255
      mcast_range_start: 225.10.1.1
      node_subnet: 10.100.1.1/24
      node_svc_subnet: 10.5.0.1/24
      service_monitor_interval: '5'
      service_vlan: '214'
      system_id: rancher
      token: 2f8cc816-21e6-49d3-b18e-00d1bf38f37d
      vrf_name: sauto_l3out-1_vrf
      vrf_tenant: common
 ```
