### ISSUE TITLE
ReplicaSets deployed by Argo don't show their pods

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#31286]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Deploy a ReplicaSet with the following YAML
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    rollout.argoproj.io/desired-replicas: "3"
    rollout.argoproj.io/revision: "3"
  labels:
    app: argo-demo-rollouts
    rollouts-pod-template-hash: 6b4d44785c
  name: argo-demo-rollouts-6b4d44785c
  namespace: default
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: argo-demo-rollouts
    uid: e64580d7-a1fe-4735-8127-f55250a04c88
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-demo-rollouts
      rollouts-pod-template-hash: 6b4d44785c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-demo-rollouts
        rollouts-pod-template-hash: 6b4d44785c
    spec:
      containers:
      - image: ubuntu
        imagePullPolicy: IfNotPresent
        name: argo-demo-rollouts
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

**Result:**
ReplicaSet doesn't show any pods in the group by workload page in the Cluster Manager
The ReplicaSet doesn't show up in the Overview section in the Cluster Overview

**Other details that may be helpful:**
This is related to https://github.com/rancher/rancher/issues/27923. The reproduction needs to include the Argo ownerReferences section.  In the pods the workload shows up as a Rollout.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA

gz#14993
gz#13893
