### ISSUE TITLE
Configmap not updated when upgrading apps

### ISSUE THREAD

**Issue by angeloudy** [rancher/rancher#31351]
I have a chart that includes lots of children charts.
One of those children charts creates a configmap.
It utilises a pre-install,pre-upgrade hook so that the configmap is created before all other charts are deployed.

The problem I am having now is that the configmap does not update when I upgrade the app in Rancher.

However, if I deploy my application with helm install and then use helm upgrade to upgrade it, I can see the configmap is successfully updated.

Here's what my configmap looks like
```
{{- $url := include "neon.url" . -}}
{{- $database := include "neon.database" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.global.customer }}-{{ .Values.global.environment }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
data:
  CLIENT_DOMAIN: "{{ $url }}"
  DB_HOST: "{{ $database }}"
  STACK_DOMAIN: "{{ $url }}"
  STAGING_DOMAIN: "{{ .Values.global.vault.vault_template }}"
  VAULT_ADDR: "{{ .Values.global.vault.vault_addr }}"
  VAULT_PORT: "{{ .Values.global.vault.vault_port }}"
  ENVIRONMENT: "{{ .Values.global.environment }}"
  PARTITION: "{{ .Values.global.customer }}"
  CUSTOMER: "{{ .Values.global.customer }}"
```
I added a new key in `data` section and the configmap couldn't be updated.

Environment:
Rancher 2.5.2
Kubernetes 1.19
OS Ubuntu 16.04
Docker 18.9.9
