### ISSUE TITLE
[import cluster] "websocket: bad handshake"

### ISSUE THREAD

**Issue by sfhl** [rancher/rancher#31354]
Hi there,

after importing a cluster to our rancher deployment, we always get the following errors. We are running rancher inside a kubernetes cluster.

```
...
INFO: Environment: CATTLE_ADDRESS=192.168.116.96 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=192.168.116.96 CATTLE_SERVER=https://rancherv2.redacted.url
INFO: Using resolv.conf: nameserver 100.125.4.25 options timeout:2 single-request-reopen
INFO: https:///rancherv2.redacted.url/ping is accessible
INFO: rancherv2.coc09.mms-support.de resolves to 172.29.20.68
time="2021-02-17T10:02:48Z" level=info msg="Rancher agent version v2.4.13 is starting"
time="2021-02-17T10:02:48Z" level=info msg="Option controlPlane=false"
time="2021-02-17T10:02:48Z" level=info msg="Option worker=false"
time="2021-02-17T10:02:48Z" level=info msg="Option requestedHostname=192.168.116.96"
time="2021-02-17T10:02:48Z" level=info msg="Option customConfig=map[address:192.168.116.96 internalAddress: label:map[] roles:[] taints:[]]"
time="2021-02-17T10:02:48Z" level=info msg="Option etcd=false"
time="2021-02-17T10:02:48Z" level=info msg="Listening on /tmp/log.sock"
...
time="2021-02-17T10:24:21Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-x7vmf/m-433af576b1bc\" not found" error="websocket: bad handshake"
time="2021-02-17T10:24:21Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2021-02-17T10:24:31Z" level=info msg="Connecting to wss://rancherv2.redacted.url/v3/connect with token 7wjjjrt2mcgfjdzwts2qkzm88bfwjwt4wbv7x7kzrxb8psq8t9sgq9"
time="2021-02-17T10:24:31Z" level=info msg="Connecting to proxy" url="wss://rancherv2.redacted.url/v3/connect"
time="2021-02-17T10:24:31Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-x7vmf/m-433af576b1bc\" not found" error="websocket: bad handshake"
time="2021-02-17T10:24:31Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
...
```

rancher logs:

```
...
2021/02/17 10:36:04 [DEBUG] 2021/02/17 10:36:04 http: superfluous response.WriteHeader call from github.com/rancher/rancher/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:24)
2021/02/17 10:36:07 [DEBUG] 2021/02/17 10:36:07 http: superfluous response.WriteHeader call from github.com/rancher/rancher/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:24)
2021/02/17 10:36:10 [DEBUG] 2021/02/17 10:36:10 http: superfluous response.WriteHeader call from github.com/rancher/rancher/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:24)
2021/02/17 10:36:12 [DEBUG] 2021/02/17 10:36:12 http: superfluous response.WriteHeader call from github.com/rancher/rancher/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:24)
2021/02/17 10:36:14 [TRACE] machineName: returning [m-63e3c675843c] for node with RequestedHostname [192.168.116.58]
2021/02/17 10:36:14 [TRACE] getMachine: looking up machine [m-63e3c675843c] in cluster [c-x7vmf]
2021/02/17 10:36:14 [TRACE] getMachine: looking up [192.168.116.58] as node name in cluster [c-x7vmf]
2021/02/17 10:36:14 [TRACE] getMachine: looking up [192.168.116.58] as RequestedHostname in cluster [c-x7vmf]
2021/02/17 10:36:14 [DEBUG] 2021/02/17 10:36:14 http: superfluous response.WriteHeader call from github.com/rancher/rancher/vendor/github.com/rancher/remotedialer.DefaultErrorWriter (server.go:24)
2021/02/17 10:36:14 [TRACE] machineName: returning [m-433af576b1bc] for node with RequestedHostname [192.168.116.96]
2021/02/17 10:36:14 [TRACE] getMachine: looking up machine [m-433af576b1bc] in cluster [c-x7vmf]
2021/02/17 10:36:14 [TRACE] getMachine: looking up [192.168.116.96] as node name in cluster [c-x7vmf]
2021/02/17 10:36:14 [TRACE] getMachine: looking up [192.168.116.96] as RequestedHostname in cluster [c-x7vmf]
...
```

Rancher itself is running behind a traefik instance, terminating tls connections and routing the traffic to the corresponding service via tcp to port 80. There is no problem using the web ui.

We are running rancher (single installation) inside of one Open Telekom Cloud (OTC) tennant/project, the imported cluster inside another. The two VPCs are peered, the routing is setup correctly, communication seems fine, there are now firewalls and/or security groups blocking traffic.

Any help would be really appreciated, as we are not able to use rancher at the moment at all.

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.13` UI: `v2.4.13` |
|Route|`undefined`|

**Comment by sfhl** [comment]
Hi there,
even if it seems that nobody is able to help here, is figured out that the uses traefik instance is not the problem.
Even if using the following flow:
```
node-agent -> ELB (tcp) -> k8s service (tcp) -> rancher-server
```

the error is still the same. 

```
...
time="2021-02-23T07:02:13Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-8qwdt/m-433af576b1bc\" not found" error="websocket: bad handshake"
time="2021-02-23T07:02:13Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
...
```

**Comment by sfhl** [comment]
Hi there
i still hope that somebody is interested in errors this software causes, which make it unuuable...

Even if i mount the needed CA directly into the rancher (server) container and the agent downlaods it, the error persists:

```
INFO: Arguments: --debug
+ '[' false '!=' true ']'
+ '[' '!' -w /var/run/docker.sock ']'
+ '[' '!' -S /var/run/docker.sock ']'
+ '[' -z 192.168.116.58 ']'
++ get_address
++ local address=
++ '[' -z ']'
++ echo ''
+ export CATTLE_ADDRESS=
+ CATTLE_ADDRESS=
++ get_address
++ local address=
++ '[' -z ']'
++ echo ''
+ export CATTLE_INTERNAL_ADDRESS=
+ CATTLE_INTERNAL_ADDRESS=
+ '[' -z '' ']'
++ ip -o route get 8.8.8.8
++ sed -n 's/.*src \([0-9.]\+\).*/\1/p'
+ CATTLE_ADDRESS=192.168.116.58
+ '[' true '!=' true ']'
+ '[' '' = true ']'
+ '[' '' = true ']'
+ '[' '' = true ']'
+ '[' '' = true ']'
+ '[' -z https://\rancherv2.redacted.url ']'
+++ printenv
+++ grep CATTLE
+++ sort
+++ sed -e 's/\(CATTLE_TOKEN=\).*/\1REDACTED/'
++ echo CATTLE_ADDRESS=192.168.116.58 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME
=192.168.116.58 CATTLE_SERVER=https://\rancherv2.redacted.url
+ info 'Environment: CATTLE_ADDRESS=192.168.116.58 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CAT
TLE_NODE_NAME=192.168.116.58 CATTLE_SERVER=https://\rancherv2.redacted.url'
+ echo INFO: 'Environment: CATTLE_ADDRESS=192.168.116.58 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=tr
ue CATTLE_NODE_NAME=192.168.116.58 CATTLE_SERVER=https://\rancherv2.redacted.url'
INFO: Environment: CATTLE_ADDRESS=192.168.116.58 CATTLE_AGENT_CONNECT=true CATTLE_CA_CHECKSUM=139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 CATTLE_CLUSTER=false CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTL
E_NODE_NAME=192.168.116.58 CATTLE_SERVER=https://\rancherv2.redacted.url
+++ cat /etc/resolv.conf
+++ grep -v '^#'
++ echo nameserver 100.125.4.25 options single-request-reopen timeout:2
+ info 'Using resolv.conf: nameserver 100.125.4.25 options single-request-reopen timeout:2'
+ echo INFO: 'Using resolv.conf: nameserver 100.125.4.25 options single-request-reopen timeout:2'
INFO: Using resolv.conf: nameserver 100.125.4.25 options single-request-reopen timeout:2
+ grep -E -q '^nameserver 127.*.*.*|^nameserver localhost|^nameserver ::1' /etc/resolv.conf
+ CATTLE_SERVER_PING=https://\rancherv2.redacted.url/ping
++ check_url https://\rancherv2.redacted.url/ping
++ local url=https://\rancherv2.redacted.url/ping
++ local err
+++ curl --insecure -sS -fL -o /dev/null --stderr - https://\rancherv2.redacted.url/ping
+++ head -n1
+++ exit 0
++ err=
++ '[' 0 -eq 0 ']'
++ echo ''
+ err=
+ [[ -n '' ]]
+ info 'https://\rancherv2.redacted.url/ping is accessible'
+ echo INFO: 'https://\rancherv2.redacted.url/ping is accessible'
INFO: https://\rancherv2.redacted.url/ping is accessible
++ echo https://\rancherv2.redacted.url
++ sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/'
+ CATTLE_SERVER_HOSTNAME=\rancherv2.redacted.url
++ echo https://\rancherv2.redacted.url
++ sed -e 's/[^/]*\/\/\([^@]*@\)\?\(.*\).*/\2/'
+ CATTLE_SERVER_HOSTNAME_WITH_PORT=\rancherv2.redacted.url
++ getent ahostsv4 \rancherv2.redacted.url
++ sed -n 's/ *STREAM.*//p'
+ RESOLVED_ADDR=172.29.20.68
+ '[' \rancherv2.redacted.url '!=' 172.29.20.68 ']'
++ echo 172.29.20.68
+ info '\rancherv2.redacted.url resolves to 172.29.20.68'
+ echo INFO: '\rancherv2.redacted.url resolves to 172.29.20.68'
INFO: \rancherv2.redacted.url resolves to 172.29.20.68
+ '[' -n 139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 ']'
++ mktemp
+ temp=/tmp/tmp.skl4IQUggx
+ curl --insecure -s -fL https://\rancherv2.redacted.url/v3/settings/cacerts
+ jq -r '.value | select(length > 0)'
+ '[' '!' -s /tmp/tmp.skl4IQUggx ']'
++ check_x509_cert /tmp/tmp.skl4IQUggx
++ local cert=/tmp/tmp.skl4IQUggx
++ local err
+++ openssl x509 -in /tmp/tmp.skl4IQUggx -noout
++ err=
++ '[' 0 -eq 0 ']'
++ echo ''
+ err=
+ [[ -n '' ]]
+ info 'Value from https://\rancherv2.redacted.url/v3/settings/cacerts is an x509 certificate'
+ echo INFO: 'Value from https://\rancherv2.redacted.url/v3/settings/cacerts is an x509 certificate'
INFO: Value from https://\rancherv2.redacted.url/v3/settings/cacerts is an x509 certificate
++ sha256sum /tmp/tmp.skl4IQUggx
++ awk '{print $1}'
+ CATTLE_SERVER_CHECKSUM=139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99
+ '[' 139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 '!=' 139a5e4a4e0fa505378c72c5f700934ce8333f4e6b1b508886c4b0eb14f4be99 ']'
+ mkdir -p /etc/kubernetes/ssl/certs
+ mv /tmp/tmp.skl4IQUggx /etc/kubernetes/ssl/certs/serverca
+ chmod 755 /etc/kubernetes/ssl
+ chmod 700 /etc/kubernetes/ssl/certs
+ chmod 600 /etc/kubernetes/ssl/certs/serverca
+ mkdir -p /etc/docker/certs.d/\rancherv2.redacted.url
+ cp /etc/kubernetes/ssl/certs/serverca /etc/docker/certs.d/\rancherv2.redacted.url/ca.crt
+ exec agent
time="2021-03-02T05:55:41Z" level=info msg="Rancher agent version v2.4.13 is starting"
time="2021-03-02T05:55:41Z" level=info msg="Option controlPlane=false"
time="2021-03-02T05:55:41Z" level=info msg="Option worker=false"
time="2021-03-02T05:55:41Z" level=info msg="Option requestedHostname=192.168.116.58"
time="2021-03-02T05:55:41Z" level=info msg="Option customConfig=map[address:192.168.116.58 internalAddress: label:map[] roles:[] taints:[]]"
time="2021-03-02T05:55:41Z" level=info msg="Option etcd=false"
time="2021-03-02T05:55:41Z" level=info msg="Listening on /tmp/log.sock"
time="2021-03-02T05:55:41Z" level=info msg="Connecting to wss://\rancherv2.redacted.url/v3/connect with token v7g7fszs74wzbd5zsgsbh57mfbt9z76dpXXXXXXXXXXXXXr4xwtmd6wqz"
time="2021-03-02T05:55:41Z" level=info msg="Connecting to proxy" url="wss://\rancherv2.redacted.url/v3/connect"
time="2021-03-02T05:55:41Z" level=error msg="Failed to connect to proxy. Response status: 200 - 200 OK. Response body: node.management.cattle.io \"c-27dxj/m-63e3c675843c\" not found" error="websocket: bad handshake"
time="2021-03-02T05:55:41Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
...
```

**Comment by sfhl** [comment]
Hi there,
still the same issue and no solution in sight. Is there anybody able to help?
For us rancher is now unusable, because we are not able to upgrade to v2.5 and are not able to use 2.4 because of this issue.

Any help is much appreciated,
Thanks in advance!

**Comment by superseb** [comment]
Please supply more info which can be used to reproduce, the filed issue leaves too much room to guess the exact setup.

- `We are running rancher (single installation) inside of one Open Telekom Cloud (OTC) tennant/project, the imported cluster inside another.`: please describe what this means, and share the exact commands and configs used. I guess its Rancher DNS name -> Traefik (what version and what configuration) -> Rancher single install using Docker (what command was used to create this)
- The imported cluster, what type of k8s cluster is it, how is it created, what is it configuration, how many nodes with what roles?

**Comment by sfhl** [comment]
Hi there,
thanks for the reply!

Both clusters are hosted kubernetes clusters (CCE, managed service in opentlekomcloud), so we do not know the exact commands to create them. We provosion them via terraform (opentelekomcloud provider)
We only are able to access the api and the nodes, in both cases.

1. Cluster hosting the rancher instance:
```bash
NAME           STATUS   ROLES    AGE   VERSION                             INTERNAL-IP    EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION                              CONTAINER-RUNTIME
172.29.20.69   Ready    <none>   86d   v1.17.9-r0-CCE20.7.1.B003-17.36.3   172.29.20.69   <none>        EulerOS 2.0 (SP5)   3.10.0-862.14.1.5.h442.eulerosv2r7.x86_64   docker://18.9.0
172.29.20.78   Ready    <none>   86d   v1.17.9-r0-CCE20.7.1.B003-17.36.3   172.29.20.78   <none>        EulerOS 2.0 (SP5)   3.10.0-862.14.1.5.h442.eulerosv2r7.x86_64   docker://18.9.0
172.29.20.91   Ready    <none>   86d   v1.17.9-r0-CCE20.7.1.B003-17.36.3   172.29.20.91   <none>        EulerOS 2.0 (SP5)   3.10.0-862.14.1.5.h442.eulerosv2r7.x86_64   docker://18.9.0
```

2. The flow is as follows:
`Rancher DNS Name -> ELB (loadbalancer) -> tcp forward -> k8s node ports -> traefik -> ssl termination -> traefik ingressroute -> k8s service -> rancher server pod`

The two Kubernetes Clusters residing in network segments peered via VPC-peering (routing and access is checked and working). For the imported cluster there is a private dns zone + record pointing the same FQDN used for external access to.
This record resolves to the internal Laodbalancer IP address, where traefik is listening providing a valid certificate (letsencrypt).

3. Rancher Server running via k8s deployment, using the following manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rancher-v2-1"
  namespace: rancher-v2
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: "rancher-v2-1"
  template:
    metadata:
      labels:
        app: "rancher-v2-1"
        workload: "rancher-v2"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: "rancher-v2"
      containers:
        - name: "rancher-v2"
          image: "rancher/rancher:v2.4.15"
          args:
            - "--http-listen-port=80"
            - "--https-listen-port=443"
            - "--k8s-mode=embedded"
            - "--add-local=false"
            - "--no-cacerts"
          env:
            - name: "CATTLE_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "CATTLE_PEER_SERVICE"
              value: "rancher-v2"
            - name: "CATTLE_RESTRICTED_DEFAULT_ADMIN"
              value: "true"
```

4. traefik config
```toml
    [ping]
      entryPoint = "web"

    [providers]
      [providers.kubernetesCRD]
      [providers.kubernetesIngress]

    [entryPoints]
      [entryPoints.web]
        address = ":8000"

      [entryPoints.websecure]
        address = ":4443"

    [certificatesResolvers.tls.acme]
      storage = "/acme.json"
      [certificatesResolvers.tls.acme.tlsChallenge]

    [certificatesResolvers.http.acme]
      storage = "/acme.json"
      [certificatesResolvers.http.acme.httpChallenge]
        entryPoint = "web"

    [certificatesResolvers.otcdns.acme]
      storage = "/certs/acme.json"
      [certificatesResolvers.otcdns.acme.dnsChallenge]
        provider = "otc"
```

5. traefik deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "traefik"
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "traefik"
  template:
    metadata:
      labels:
        app: "traefik"
        workload: "traefik"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: "traefik"

      containers:
        - name: "traefik"
          image: "traefik:v2.4"
          imagePullPolicy: "Always"
          volumeMounts:
            - name: "traefik-config"
              mountPath: "/etc/traefik/"

      volumes:
        - name: "traefik-config"
          configMap:
            name: "traefik-config"
            items:
              - key: "traefik.toml"
                path: "traefik.toml"
```

6. the imported cluster
```bash
NAME             STATUS   ROLES    AGE   VERSION                                        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION                    CONTAINER-RUNTIME
192.168.116.58   Ready    <none>   1y    v1.11.7-r0-CCE2.0.23.B001-25-g7c586d2b0bacab   192.168.116.58   <none>        EulerOS 2.0 (SP2)   3.10.0-327.62.59.83.h128.x86_64   docker://17.6.1
192.168.116.96   Ready    <none>   1y    v1.11.7-r0-CCE2.0.23.B001-25-g7c586d2b0bacab   192.168.116.96   <none>        EulerOS 2.0 (SP2)   3.10.0-327.62.59.83.h128.x86_64   docker://17.6.1
```

For the imported cluster i have tested several versions, old clusters and newly created ones, all with the same problem.

Let me know if further information is needed.

Thanks in advance!
