### ISSUE TITLE
Custom encryption config is case sensitive in 2.5.x

### ISSUE THREAD

**Issue by WalterDurkee** [rancher/rancher#31385]
**What kind of request is this (question/bug/enhancement/feature request):**
Question/bug

**Steps to reproduce (least amount of steps as possible):**
We've upgraded our cluster from 2.3.8 to 2.5.5. local cluster is not encrypted but for our managed cluster we use following config provided via rke templates:
```
rancher_kubernetes_engine_config:
...
  services:
...
      secrets_encryption_config:
        custom_config:
          apiVersion: apiserver.config.k8s.io/v1
          kind: EncryptionConfiguration
          resources:
          - providers:
              - aescbc:
                  keys:
                    - name: key1
                      secret: xxxx
              - identity: {}
            resources:
              - secrets
        enabled: true
```
And this used to work on 2.3.x without any problems. With 2.5.5 `/etc/kubernetes/ssl/encryption.yaml` is zeroed and looks like:
```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources: []
```
which basically causes kube-apiserver not to start. 

**Result:**
kube-apiserver not starting

**Other details that may be helpful:**
Tried without custom_config like:
```
rancher_kubernetes_engine_config:
...
  services:
...
      secrets_encryption_config:
        enabled: true
```
and the result was the same. 

Tried also spinning literally one node aio cluster with new template and behaviour was the same.

**Environment information**
- Rancher version: 2.5.5
- Installation option: H/A

**??**
Are we doing something that we shouldn't? Did something change? Config matches with the docs.

gz#15889
gz#16142

**Comment by dramich** [comment]
When using a [custom configuration for encrypting data at rest](https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/), there is a bug relating to the format that exists in Rancher 2.5.0+.

In 2.4.x, when configuring `secrets_encryption_config` Rancher would take any case for the keys and adjust them to be the case it needed, and that cycle repeated. In 2.5 however, the cases have to match on submit. The RKE docs linked above display the configuration keys all starting with lowercase, and with this issue that format will not work.

If you set this configuration in 2.4 and you upgraded to 2.5, everything should continue to work, as the configuration's case will still be correct. But if you edit the configuration and change the case of the keys, the cluster will become unavailable. It appears some workloads may continue to run, but the cluster's API server will be unresponsive.

If you start a 2.5 cluster with the configuration containing incorrect cases it will fail to start with the same error.

The workaround in 2.5 is to continue to use the cases that Rancher expects:
```
secretsEncryptionConfig:
  customConfig:
    Resources:
    - Providers:
      - AESCBC:
          Keys:
          - Name: k-fw5hn
            Secret: <encoded secret>
        AESGCM: null
        Identity: null
        KMS: null
        Secretbox: null
      Resources:
      - secrets
    apiVersion: apiserver.config.k8s.io/v1
    kind: EncryptionConfiguration
  enabled: true
```

**Comment by WalterDurkee** [comment]
Wow. That worked! Many thanks @dramich!

**Comment by dramich** [comment]
https://github.com/rancher/rke/pull/2409

**Comment by sowmyav27** [comment]
**On master-head commit id: `5715b8a`**

- Enable custom encryption on the cluster (during creation) by setting this
```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: <base64 encoded>
          - identity: {}
```

- Cluster comes up successfully.
- On control plane node `cat /etc/kubernetes/ssl/encryption.yaml` is set with the custom excrption details
- Create a secret `test` in default namespace
- `ETCDCTL_API=3 etcdctl get /registry/secrets/default/test | hexdump -C` --> secret is encrypted
