### ISSUE TITLE
Add some hints for the Answers section of forms

### ISSUE THREAD

**Issue by JensHeinrich** [rancher/rancher#31384]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
Insert
```
one.two=true
one.three=false
two.four="some,key"
three.seven='another key'
```
into the answers section for an app

**Result:**
it gets rendered as
```yaml
---
  one: 
    two: "true"
    three: "false"
  two: 
    four: "\"some,key\""
  three: 
    seven: "'another key'"
```

**Suggestion:**
Inform that for booleans the yaml editor should be used and that fields are expected to be already containing strings for qoutes
Maybe add an "autoclean"-button next to the message

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
