### ISSUE TITLE
[Monitoring V2] Create default Roles for monitoring components

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#31411]
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

Create default roles for viewing Grafana + Alertmanager + Prometheus in the cattle-monitoring-system namespaces to allow users to access the UIs by being added to a RoleBinding for it.

**Comment by aiyengar2** [comment]
Instructions for testing:
- Deploy Monitoring V2 onto the cluster
- As the cluster admin / person who deployed the chart, navigate to the Monitoring Pane and copy the Alertmanager UI link from the button provided
- Create a Cluster Member user with scoped down privileges
- Identify the Cluster Member user's name (e.g. `u-XXXXX`) and deploy the following RoleBinding onto the cluster
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: override-monitoring-view # can be anything you want
  namespace: cattle-monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-alertmanager-view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-XXXXX (NOTE: must replace)
```
- Log out of Rancher as the Admin and Log in as the scoped down cluster member
- Paste the prior copied Alertmanager link on your browser

Expected Outcome:
Alertmanager UI should pop up and you should be able to perform any of the default actions

Repeat the same steps for Prometheus + Grafana, except replace the `roleRef.name` with `monitoring-<prometheus|grafana>-view` to point to the right ClusterRole.
