### ISSUE TITLE
RTNETLINK answers: Operation not permitted

### ISSUE THREAD

**Issue by dmzaytsev** [rancher/rancher#3142]
There are two hosts in my environment.
I have set load balancer with option "Always run one instance of this container on every host"
The load balancer successfully started on the first host.
But it's failed on the second host with message "RTNETLINK answers: Operation not permitted"
these hosts absolutely identical. 

Rancher	v0.50.2
Cattle	v0.127.0
User Interface	v0.75.0
Rancher Compose	v0.6.2

docker logs:

>INFO: Running /var/lib/cattle/download/agent-instance-startup/agent-instance-startup-1-40090a0051cbcfe987de329f0
1bd52c08158b1990564b419ee71ee9204cf5d8f/apply.sh
INFO: Assigning 10.42.129.178/16 to eth0
RTNETLINK answers: Operation not permitted
[[scripts.sh:184] script_env
[[scripts.sh:109] '[' -n https://****.com/v1 ']'
[[scripts.sh:110] return
[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:187] export CATTLE_CONFIG_URL=https://**.**.com/v1
[[scripts.sh:187] CATTLE_CONFIG_URL=https://**.**.com/v1
[[scripts.sh:188] export CATTLE_STORAGE_URL=https://**.**.com/v1
[[scripts.sh:188] CATTLE_STORAGE_URL=https://**.**.com/v1
[apply.sh:5] read DEV MAC IP
[[apply.sh:6] ip link show dev eth0
[[apply.sh:6] awk '{print $2}'
[[apply.sh:6] grep link/ether
[apply.sh:6] '[' 02:f6:fd:0f:6b:bc '!=' 02:f6:fd:0f:6b:bc ']'
[apply.sh:11] ip addr show dev eth0
[apply.sh:11] grep -iq 10.42.129.178/16
[apply.sh:12] info Assigning 10.42.129.178/16 to eth0
[scripts.sh:19] echo INFO: Assigning 10.42.129.178/16 to eth0
INFO: Assigning 10.42.129.178/16 to eth0
[apply.sh:13] ip addr add dev eth0 10.42.129.178/16
RTNETLINK answers: Operation not permitted
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot

**Comment by yutian1224** [comment]
I have the same question as u.

**Comment by dmzaytsev** [comment]
I just recreated load balancer 
Right now I have same error on both nodes
How it can be fixed?

**Comment by deniseschannon** [comment]
I have been unable to reproduce.

Can you provide more details on:
1. What setup is this? Fresh install or upgraded setup? What OS is your hosts?
2. Can you provide more details on your load balancers? Are both of you selecting (Always run one instance of this container on every host)?

Providing either a snapshot of what you created or a copy of the docker-compose.yml of the load balancer portion would be great.

**Comment by yutian1224** [comment]
STEP 1: Added a new stack and started it.
![image](https://cloud.githubusercontent.com/assets/13673671/12028736/5aa74b4c-ae17-11e5-8ece-b00088943a74.png)

STEP 2: Add Load Balancer with conf below and start it.
![image](https://cloud.githubusercontent.com/assets/13673671/12028856/52ab4b26-ae19-11e5-885b-ff631a0eb0dd.png)
![image](https://cloud.githubusercontent.com/assets/13673671/12028897/df458a1a-ae19-11e5-9c99-04dea0a9a057.png)

STEP 3: Checking 2 Load Balancer container on hosts. one succ but another failed.
![image](https://cloud.githubusercontent.com/assets/13673671/12028900/f554bb8c-ae19-11e5-8e3f-ef432b2a385c.png)
![image](https://cloud.githubusercontent.com/assets/13673671/12028914/2959e33a-ae1a-11e5-9d6e-ad3dfc0ffad2.png)

I think it's because there's no privileges to change MAC in container by agent run.

**Comment by ibuildthecloud** [comment]
I'll take a look at this tomorrow.  You right in that the container doesn't have privileged to change the mac, but I think the issue might be why is the mac different?  We set the mac on container create so on boot we shouldn't try to adjust the mac.  What version of Docker are you running?  `docker version; docker info`?

**Comment by yutian1224** [comment]
docker version: 1.9.1

![image](https://cloud.githubusercontent.com/assets/13673671/12029122/867f06f4-ae1e-11e5-8d24-f06a44c6fb0c.png)

**Comment by dmzaytsev** [comment]
@deniseschannon 
> Can you provide more details on:
1. What setup is this? Fresh install or upgraded setup? What OS is your hosts?

this is fresh install. virtual machine on GCE `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux` 


> 2. Can you provide more details on your load balancers? Are both of you selecting (Always run one instance of this container on every host)?
Providing either a snapshot of what you created or a copy of the docker-compose.yml of the load balancer portion would be great.

I have set jenkins from the catalog and load balancer

**docker-compose.yml:** 
```
jenkins-plugins:
  labels:
    io.rancher.service.hash: 904a8db3f0345c66251d49fc71e00445cec1dc11
  image: rancher/jenkins-plugins:v0.1.1
jenkins-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.service.hash: 23b552bbadc507473ac27387b83c68151a5eb500
  entrypoint:
  - /bin/true
  image: jenkins:1.625.2
lb:
  ports:
  - 80:8080
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - jenkins-primary:jenkins-primary
  stdin_open: true
jenkins-primary:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
    io.rancher.service.hash: 7e4bb2e64078e5bb189752994fd105870948af7a
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - /usr/share/jenkins/rancher/jenkins.sh
  image: jenkins:1.625.2
  volumes_from:
  - jenkins-plugins
  - jenkins-datavolume
```

**rancher-compose.yml :**
```
jenkins-plugins:
  scale: 1
  metadata: &id001
    io.rancher.service.hash: 353441f698f31a149b827cb76e733a7ebb1c39b6
    plugins: |+
      credentials
      greenballs
      git
      junit
      git-client
      github-api
      github-oauth
      github
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm

jenkins-datavolume:
  scale: 1
  metadata: *id001
lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
jenkins-primary:
  scale: 1
  metadata: *id001
```

```
 sudo docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                          NAMES
f849a985094a        rancher/agent-instance:v0.6.0    "/etc/init.d/agent-in"   12 minutes ago      Up 12 minutes                                                      90678e79-5d8c-4785-a832-3d4368de6a96
01adbf0507d0        jenkins:1.625.2                  "/usr/share/jenkins/r"   23 minutes ago      Up 23 minutes       8080/tcp, 50000/tcp                            d289a50e-9853-4297-a5dd-ea3f495e059b
7937cf9bf1d8        rancher/jenkins-plugins:v0.1.1   "/confd --backend ran"   24 minutes ago      Up 24 minutes                                                      4cd6fae4-0585-4168-82fa-b4d88027db60
5b9e748645a7        rancher/agent-instance:v0.6.0    "/etc/init.d/agent-in"   34 hours ago        Up 34 hours         0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   bc6a849e-692c-4aa6-9d71-3266b3c483fe
b081d3183e99        rancher/agent:v0.8.2             "/run.sh run"            5 days ago          Up 5 days                                                          rancher-agent
```

I expect to see a few listen tcp ports: 80, 8080, 50000
but I don't see the ports
```
netstat -na | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:9344          0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN  
```

```
$ docker --version
Docker version 1.9.1, build a34a1d5

$ sudo docker info
Containers: 8
Images: 93
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 109
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 2
Total Memory: 7.324 GiB
Name: paas-host-1
ID: D6J3:QIHR:557Q:DGOF:L4CA:TR2T:5IXZ:RMGN:JUHZ:J7OZ:GZQA:CTRG
WARNING: No memory limit support
WARNING: No swap limit support
```
