### ISSUE TITLE
forwardport: Alerting v1 not triggering/sending notifications #31365 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31522]
forwardport:  rancher/rancher#31365 for master-head 

the [tickets mentioned here](https://github.com/rancher/rancher/issues/31365#issuecomment-785480061) were related to this failure

**Comment by slickwarren** [comment]
not working on master-head (caa261959550c2f104a450e54d00bf4d49e17c9c).  
`alertmanager-cluster-monitoring` in crashloopbackoff with this error in logs 
```
level=warn ts=2021-03-04T20:29:50.666Z caller=cluster.go:228 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-cluster-alerting-0.alertmanager-operated:9094: lookup alertmanager-cluster-alerting-0.alertmanager-operated on 10.43.0.10:53: no such host\n\n"
... 
level=error ts=2021-03-04T20:24:45.688Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="not a valid duration string: \"6d2h\""
```

**Comment by aiyengar2** [comment]
Is this still an issue? iirc the fix was not with the Monitoring chart, but rather with rancher/rancher changes.

**Comment by aiyengar2** [comment]
Was able to reproduce the issue. Seeing the following on master-head:

### /namespaces/cattle-prometheus/yaml is returning an invalid object

https://RANCHER_URL/v3/cluster/c-ck775/namespaces/cattle-prometheus/yaml

```json
{
"baseType": "error",
"code": "ServerError",
"message": "invalid character '\\x1f' looking for beginning of value",
"status": 500,
"type": "error"
}
```

This only happens with the `cattle-prometheus` namespace after Catalog V1 deploys `cluster-alerting` for Alerting V1.

### Alertmanager Config Secret has wrong input

Within the alertmanager-cluster-alerting secret (the Alertmanager Config for Monitoring V1), I also see:

```yaml
global:
  resolve_timeout: 5m
  smtp_require_tls: false
  slack_api_url: https://api.slack.com
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
route:
  receiver: rancherlabs
  routes:
  - receiver: c-ck775:cag-mj4gp
    group_by:
    - group_id
    match:
      group_id: c-ck775:cag-mj4gp
    continue: true
    routes:
    - group_by:
      - rule_id
      - resource_kind
      - target_namespace
      - target_name
      - event_message
      match:
        rule_id: c-ck775:cag-mj4gp_car-rzcbn
      continue: true
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 6d2h
    group_wait: 30s
    group_interval: 3m
    repeat_interval: 1h
  group_wait: 1m
  group_interval: 10s
  repeat_interval: 1h
receivers:
- name: rancherlabs
  slack_configs:
  - send_resolved: false
    channel: '#alert'
    title_link: ""
- name: c-ck775:cag-mj4gp
  slack_configs:
  - send_resolved: false
    api_url: <REDACTED by @aiyengar2>
    color: '{{ if eq (index .Alerts 0).Labels.severity "critical" }}danger{{ else
      if eq (index .Alerts 0).Labels.severity "warning" }}warning{{ else }}good{{
      end }}'
    title: '{{ template "rancher.title" . }}'
    title_link: ""
    text: '{{ template "slack.text" . }}'
templates:
- /etc/alertmanager/config/notification.tmpl
```

In the above configuration, I'm not sure where `repeat_interval: 6d2h` is coming from. 

#### Workload service generation controller is logging errors

Within the logs, I see the following, which means that this could be related to https://github.com/rancher/rancher/issues/32692:

```
2021/05/20 17:21:57 [ERROR] error syncing 'cattle-prometheus/prometheus-operator-monitoring-operator': handler workloadServiceGenerationController: cannot find app namespace in labels of cattle-prometheus, requeuing
2021/05/20 17:22:05 [ERROR] error syncing 'cattle-prometheus/alertmanager-cluster-alerting': handler workloadServiceGenerationController: cannot find app namespace in labels of cattle-prometheus, requeuing
```
