### ISSUE TITLE
Implement ACE for RKE2/K3S clusters provisioned in Rancher

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#31604]
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Result:**
ACE should be installed on an RKE2/K3S cluster provisioned in Rancher.

**Comment by Martin-Weiss** [comment]
Will this also work for imported RKE2 clusters? Today we deploy and import RKE2 - but we need ACE once available and we would not want to redeploy all the clusters...

**Comment by rancher-max** [comment]
Using https://github.com/rancher/rancher/issues/32388 for rke2. Blocked on trying with k3s due to https://github.com/rancher/rancher/issues/33443

**Comment by rancher-max** [comment]
When using ACE for both rke2 and k3s on v2.6-head commit `e3316c9`, the downloaded kubeconfig is duplicating the direct node IP(s). This gives an error when trying to use it: `error: error loading config file "~/.kube/config": error converting *[]NamedCluster into *map[string]*api.Cluster: duplicate name "maxrke2ace-ip-<redacted-ip>" in list:` 

The downloaded kubeconfig, with some redacted information, looks like:
```
apiVersion: v1
kind: Config
clusters:
- name: "maxrke2ace"
  cluster:
    server: "https:/<rancher_server>/k8s/clusters/c-m-81d7f8c5"
    certificate-authority-data: "<redacted>"
- name: "maxrke2ace-ip-<redacted-ip>"
  cluster:
    server: "https://<redacted-ip>:6443"
    certificate-authority-data: "<redacted>"
- name: "maxrke2ace-ip-<redacted-ip>"
  cluster:
    server: "https://<redacted-ip>:6443"
    certificate-authority-data: "<redacted>"

users:
- name: "maxrke2ace"
  user:
    token: "<redacted-token>"


contexts:
- name: "maxrke2ace"
  context:
    user: "maxrke2ace"
    cluster: "maxrke2ace"
- name: "maxrke2ace-ip-<redacted-ip>"
  context:
    user: "maxrke2ace"
    cluster: "maxrke2ace-ip-<redacted-ip>"
- name: "maxrke2ace-ip-<redacted-ip>"
  context:
    user: "maxrke2ace"
    cluster: "maxrke2ace-ip-<redacted-ip>"

current-context: "maxrke2ace"
```
where `<redacted-ip>` is the same ip.
