### ISSUE TITLE
Custom NGINX Ingress Configuration fails with 304 error

### ISSUE THREAD

**Issue by ashishmgofficial** [rancher/rancher#31615]
Installed Rancher as in the documentation in my EKS cluster with ```ingress.enabled=false``` . I want to host rancher in the ```<ingress>/rancher``` path. So I deployed the corressponding nginx ingress as below :

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: cattle-system
  annotations:
          cert-manager.io/issuer: rancher
          cert-manager.io/issuer-kind: Issuer
          meta.helm.sh/release-name: rancher
          meta.helm.sh/release-namespace: cattle-system
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - http:
      paths:
        - path: /rancher
          backend:
             serviceName: rancher
             servicePort: 80


```

But when I try access the UI , Im getting blank browser and When I try hitting the URI using curl ..Im seeing ```304``` as return code.  

I know I might be doing something stupid, but Can you help me out here
