### ISSUE TITLE
Rancher monitoring fleet gitrepo status is coming as Modified

### ISSUE THREAD

**Issue by gouravsw** [rancher/rancher#31620]
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
I have deployed the rancher monitoring example via fleet in one of the k8s cluster. Resources got crated and all the objects are running as pods. But while checking the gitrepo status getting the below messages

Repo URL: https://github.com/rancher/fleet-examples/tree/master/single-cluster/helm-multi-chart/rancher-monitoring

**Result:**

`{"webhooks":[{"admissionReviewVersions":["v1beta1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJOakNCM3FBREFnRUNBaEJXb3o1L1NkMGRMVnhXMUcwclk1UlFNQW9HQ0NxR1NNNDlCQU1DTUFBd0lCY04KTWpFd016QTBNRGsxTVRVeVdoZ1BNakV5TVRBeU1EZ3dPVFV4TlRKYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVNTb0EzZ2IyUjVacDZoS2JpU01lS2VrQkdpdlNCNGdJT0FWc3ZBVityVkJxRjhFajlGClpRZFh3aEFlamVDRGN6Umx4SDFiQk1pVmFhS20xRTJlV25IVW96Z3dOakFPQmdOVkhROEJBZjhFQkFNQ0FnUXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBS0JnZ3Foa2pPUFFRRApBZ05IQURCRUFpQlpMbFplZzU4dk5LdUNJQUd2NVRJbDkvRlNuVEprK283endVdzFtaEU5ZUFJZ1pRdlhRR3ZOCkthcXRRQjA2QmtIcFlVeDR5YXJEb3NrTG9Qa3dRODdNeitzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"rancher-monitoring-operator","namespace":"cattle-monitoring-system","path":"/admission-prometheusrules/mutate","port":443}},"failurePolicy":"Ignore","matchPolicy":"Exact","name":"prometheusrulemutate.monitoring.coreos.com","namespaceSelector":{},"objectSelector":{},"reinvocationPolicy":"Never","rules":[{"apiGroups":["monitoring.coreos.com"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["prometheusrules"],"scope":"*"}],"sideEffects":"Unknown","timeoutSeconds":30}]}`

To fix these issues I have added the diff section and below are its values. Basically I have tried all the combinations.

```
  - apiVersion: admissionregistration.k8s.io/v1beta1
    kind: MutatingWebhookConfiguration
    name: rancher-monitoring-admission
    operations:
    - {"op":"remove", "path":"/webhooks/0/admissionReviewVersions/0/v1beta1"}
    - {"op":"remove", "path":"/webhooks/0/admissionReviewVersions/v1beta1"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/caBundle"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/name"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/namespace"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/path"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/port"}
    - {"op":"remove", "path":"/webhooks/0/failurePolicy"}
    - {"op":"remove", "path":"/webhooks/0/matchPolicy"}
    - {"op":"remove", "path":"/webhooks/0/name"}
    - {"op":"remove", "path":"/webhooks/0/namespaceSelector"}
    - {"op":"remove", "path":"/webhooks/0/objectSelector"}
    - {"op":"remove", "path":"/webhooks/0/reinvocationPolicy"}
    - {"op":"remove", "path":"/webhooks/0/sideEffects"}
    - {"op":"remove", "path":"/webhooks/0/timeoutSeconds"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/scope"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/0/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/0/*"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups/0/monitoring.coreos.com"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources/0/prometheusrules"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/*"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups/monitoring.coreos.com"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources/prometheusrules"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/1/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/1/CREATE"}
```

**Other details that may be helpful:**

Kindly help me here. Thank you in advance.
Could someone point me what I am not doing? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): V2.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloude
- Kubernetes version (use `kubectl version`): 1.19

```
(paste the output here)
```
`{"webhooks":[{"admissionReviewVersions":["v1beta1"],"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJOakNCM3FBREFnRUNBaEJXb3o1L1NkMGRMVnhXMUcwclk1UlFNQW9HQ0NxR1NNNDlCQU1DTUFBd0lCY04KTWpFd016QTBNRGsxTVRVeVdoZ1BNakV5TVRBeU1EZ3dPVFV4TlRKYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVNTb0EzZ2IyUjVacDZoS2JpU01lS2VrQkdpdlNCNGdJT0FWc3ZBVityVkJxRjhFajlGClpRZFh3aEFlamVDRGN6Umx4SDFiQk1pVmFhS20xRTJlV25IVW96Z3dOakFPQmdOVkhROEJBZjhFQkFNQ0FnUXcKRXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBS0JnZ3Foa2pPUFFRRApBZ05IQURCRUFpQlpMbFplZzU4dk5LdUNJQUd2NVRJbDkvRlNuVEprK283endVdzFtaEU5ZUFJZ1pRdlhRR3ZOCkthcXRRQjA2QmtIcFlVeDR5YXJEb3NrTG9Qa3dRODdNeitzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"rancher-monitoring-operator","namespace":"cattle-monitoring-system","path":"/admission-prometheusrules/mutate","port":443}},"failurePolicy":"Ignore","matchPolicy":"Exact","name":"prometheusrulemutate.monitoring.coreos.com","namespaceSelector":{},"objectSelector":{},"reinvocationPolicy":"Never","rules":[{"apiGroups":["monitoring.coreos.com"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["prometheusrules"],"scope":"*"}],"sideEffects":"Unknown","timeoutSeconds":30}]}`

To fix these issues I have added the diff section and below are its values. Basically I have tried all the combinations.

```
  - apiVersion: admissionregistration.k8s.io/v1beta1
    kind: MutatingWebhookConfiguration
    name: rancher-monitoring-admission
    operations:
    - {"op":"remove", "path":"/webhooks/0/admissionReviewVersions/0/v1beta1"}
    - {"op":"remove", "path":"/webhooks/0/admissionReviewVersions/v1beta1"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/caBundle"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/name"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/namespace"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/path"}
    - {"op":"remove", "path":"/webhooks/0/clientConfig/service/port"}
    - {"op":"remove", "path":"/webhooks/0/failurePolicy"}
    - {"op":"remove", "path":"/webhooks/0/matchPolicy"}
    - {"op":"remove", "path":"/webhooks/0/name"}
    - {"op":"remove", "path":"/webhooks/0/namespaceSelector"}
    - {"op":"remove", "path":"/webhooks/0/objectSelector"}
    - {"op":"remove", "path":"/webhooks/0/reinvocationPolicy"}
    - {"op":"remove", "path":"/webhooks/0/sideEffects"}
    - {"op":"remove", "path":"/webhooks/0/timeoutSeconds"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/scope"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/0/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/0/*"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups/0/monitoring.coreos.com"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources/0/prometheusrules"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiVersions/*"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/apiGroups/monitoring.coreos.com"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/resources/prometheusrules"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/0/CREATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/1/UPDATE"}
    - {"op":"remove", "path":"/webhooks/0/rules/0/operations/1/CREATE"}
```
