### ISSUE TITLE
RKE cluster with DNS as address do not create certiuficates with nodeIP

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#31650]
**BUG**

RKE clusters created with the node DNS name set as `address` doesn't create etcd certificates with the `nodeIP` in the SAN.
This creates an issue with `monitoring V2` where data from etcd cannot be scrapped.

You can see the following logs:
err="failed to scrape https://{NODEIP}:2379/metrics: Get https://{NODEIP}:2379/metrics: x509: certificate is valid for 127.0.0.1, 10.43.0.1, not {NODEIP}"

**Steps to reproduce (least amount of steps as possible):**

* Create a node with a resolvable DNS name.
* Create a cluster.yaml RKE cluster with the node DNS name as the `address` field.
* `rke up`
* Check the etcd certificates ( probably others, didn't check )
 ```
CERT=/etc/kubernetes/ssl/kube-etcd-{NODE_DNS_NAME}.pem
 for i in $(openssl x509 -in $CERT -noout -text | grep -A1 'Subject Alternative Name' | tail -n1 | tr -d ','); { echo $i | cut -f2 -d:; }
```

**Result:**

The Etcd data cannot be scrapped.

**Environment information**

Rancher 2.5.5
Monitoring v2 enabled from Cluster Explorer  

**Workaround**

As a workaround, you can edit the Helm monitoring Deployment and set `rkeEtcd.clients.useLocalhost ` to `true`

```
rkeEtcd:
  clients:
    https:
      caCertFile: kube-ca.pem
      certDir: /etc/kubernetes/ssl
      [...]
    useLocalhost: true
  component: kube-etcd
```

gz#15390
gz#15251
