### ISSUE TITLE
PodSecurityPolicy.extensions "psp.logging-operator" is invalid

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#31661]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Delete logger installed with v2.5.5
2. Install a new rancher-logger with the following template
```
additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
  rke:
    enabled: true
    fluentbit:
      log_level: info
      mem_buffer_limit: 5MB
  rke2:
    enabled: false
affinity: {}
annotations: {}
createCustomResource: true
disablePvc: true
fluentbit:
  resources: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: 'true'
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: 'true'
fluentd:
  resources: {}
fullnameOverride: ''
global:
  cattle:
    systemDefaultRegistry: ''
  dockerRootDirectory: ''
  psp:
    enabled: true
  systemDefaultRegistry: ''
http:
  port: 8080
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: rancher/mirrored-banzaicloud-logging-operator
  tag: 3.9.0
imagePullSecrets: null
images:
  config_reloader:
    repository: rancher/mirrored-jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10-debug
  fluentd:
    repository: rancher/mirrored-banzaicloud-fluentd
    tag: v1.11.5-alpine-9
monitoring:
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    metricRelabelings: null
    relabelings: null
nameOverride: ''
namespaceOverride: ''
nodeSelector:
  kubernetes.io/os: linux
podSecurityContext: {}
priorityClassName: {}
rbac:
  enabled: true
  psp:
    enabled: true
replicaCount: 1
resources: {}
securityContext: {}
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

**Result:**

**Other details that may be helpful:**
```

helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-crd-3.9.000.yaml --version=3.9.000 --wait=true rancher-logging-crd /home/shell/helm/rancher-logging-crd-3.9.000.tgz
--
Thu, Mar 11 2021 10:06:30 pm | Release "rancher-logging-crd" does not exist. Installing it now.
Thu, Mar 11 2021 10:06:32 pm | W0311 16:36:32.592537 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:32 pm | W0311 16:36:32.605817 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:32 pm | W0311 16:36:32.613885 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:32 pm | W0311 16:36:32.620817 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:32 pm | W0311 16:36:32.643699 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:32 pm | creating 5 resource(s)
Thu, Mar 11 2021 10:06:33 pm | W0311 16:36:33.010112 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:33 pm | W0311 16:36:33.018747 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:33 pm | W0311 16:36:33.140547 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:33 pm | W0311 16:36:33.200513 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:33 pm | W0311 16:36:33.212328 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:33 pm | beginning wait for 5 resources with timeout of 10m0s
Thu, Mar 11 2021 10:06:35 pm | W0311 16:36:35.334960 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:35 pm | W0311 16:36:35.434551 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:35 pm | W0311 16:36:35.507639 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:35 pm | W0311 16:36:35.587867 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:35 pm | W0311 16:36:35.736840 24 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Thu, Mar 11 2021 10:06:36 pm | NAME: rancher-logging-crd
Thu, Mar 11 2021 10:06:36 pm | LAST DEPLOYED: Thu Mar 11 16:36:31 2021
Thu, Mar 11 2021 10:06:36 pm | NAMESPACE: cattle-logging-system
Thu, Mar 11 2021 10:06:36 pm | STATUS: deployed
Thu, Mar 11 2021 10:06:36 pm | REVISION: 1
Thu, Mar 11 2021 10:06:36 pm | TEST SUITE: None
Thu, Mar 11 2021 10:06:36 pm |  
Thu, Mar 11 2021 10:06:36 pm | ---------------------------------------------------------------------
Thu, Mar 11 2021 10:06:36 pm | SUCCESS: helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-crd-3.9.000.yaml --version=3.9.000 --wait=true rancher-logging-crd /home/shell/helm/rancher-logging-crd-3.9.000.tgz
Thu, Mar 11 2021 10:06:36 pm | ---------------------------------------------------------------------
Thu, Mar 11 2021 10:06:36 pm | helm upgrade --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-3.9.000.yaml --version=3.9.000 --wait=true rancher-logging /home/shell/helm/rancher-logging-3.9.000.tgz
Thu, Mar 11 2021 10:06:36 pm | Release "rancher-logging" does not exist. Installing it now.
Thu, Mar 11 2021 10:06:37 pm | creating 16 resource(s)
Thu, Mar 11 2021 10:06:37 pm | Error: PodSecurityPolicy.extensions "psp.logging-operator" is invalid: metadata.annotations[seccomp.security.alpha.kubernetes.io/defaultProfileName]: Invalid value: "docker/default,runtime/default": must be a valid seccomp profile


```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.6
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 24CPU, 48G ram
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
(paste the output here)
```
