### ISSUE TITLE
use helm template to reduce the redundant label section in Rancher Helm chart

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#31667]
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

The following set of labels are used in multiple resources in Rancher's helm chart.
```
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
```
A Helm template can be used to avoid the redundant code in the chart.
