### ISSUE TITLE
Adding a clusterrepos.catalog.cattle.io with custom certificate in a dowstream repo is failing.

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#31676]
SURE-3086

**BUG**

**Steps to reproduce (least amount of steps as possible):**
* Start a Rancher cluster in version 2.5.x
* Add a downstream cluster
* Open the Cluster Explorer on the downstream cluster
* Add a custom HTTPS Chart repo with a custom certificate in the Rancher downstream cluster

**Result:**

 * The Chart Repository status stays at `Downloading`.

```
$ k -n cattle-system describe clusterrepos.catalog.cattle.io my-chart
[...]
Status:
  Conditions:
    Last Update Time:                 2021-03-12T10:47:44Z
    Status:                           True
    Type:                             FollowerDownloaded
    Last Update Time:                 2021-03-12T13:39:32Z
    Message:                          Get "https://138.68.84.135:443/index.yaml": x509: certificate signed by unknown authority
    Reason:                           Error
    Status:                           False
    Type:                             Downloaded
[...]
```

**Other details that may be helpful:**

If we add the same Chart Repo in the Rancher cluster it is falling too.

Adding the `tls-additionnal-ca` secret fixes the issue for the Rancher cluster but not for the downstream cluster.

**Workaround**  

* Edit the chart with the UI with "Edit YAML"  
   Then add the key/value `spec.insecureSkipTLSVerify: true`

* We can also add the CA like below.  
  The caBundle key is a base64 encoded DER certificate.  
  `openssl x509 -outform der -in ca.pem | base64 -w0`

Open "Edit YAML":

```
spec:
  forceUpdate: "2021-03-12T12:24:46Z"
  url: https://[chart-DNS-Name]
  caBundle: "MIIE6DCCA1CgAwIBAgIRAITlspLzb2L1lpZxfarCn2AwDQYJKoZIhvcNAQELBQAwgYsxHjAcBgNVBpoezaihf&piurhfpzaoiuefjpeoirzjpfoirejpfoirejgpoijpoijg1UECwwncm9vdEBhcGlub24tcmFuY2hlcjItcmFuY2hlcmFnZW50LWFsbC0wMTcwNQYDVQQDDC5ta2NlcnQgcm9vdEBhcGlub24tcmFuY2hlcjItcmFuY2hlcmFnZW50LWFsbC0wMB4X9w0BAQsFAAOCAYEASUDe/q7Ga64wpT/74AWQoXT6RTZ/V6kUHXdiLAgd//OOYo15dOa2g/7g7rDTbtg0AkeU59asg5TqBK+6BIm8t3qsRoV03dHO6+1uO2yEPQyxagyTEw3RKZ8A7P5Sw1ffjCoeo7ri4/vfTg496UYVYMlqbdoMJ5c05IWFVOPQgCEsHqkWmR9/Q2FJHNxP+830xr73v6r2B2UOYJ1fWiNyhlu7ExT50MO23CJTW9k0SuXPhSav8+gVLRsbfzm4oMe7/1SqlJqBzW0LWk3UwtFA4uKm/F700TtrphPMG2Q+0ZTx9fMNAenDS3ee2zmelfkzprkgpekrporekgporeppppapapappapapadI8GjllB+iva5d9mE1Y9/zeqnx83fOQyNZx0VHtA8B0b3D8NVLc2HBFvjmmqjRh3GLr73UDrZ8J2yY0rs3yWkpvgh9IGFy7Zyqx/mwTX2E12'"lkjkljlkjj11556Tx9VXoqAqMvoLl11ChkQhXPYGQBDwfHN81ct8RMu7ShkR4"
```

**Environment information**
- Rancher version : 2.5.5

gz#15337

**Comment by zaggash** [comment]
https://github.com/rancher/dashboard/issues/1713

**Comment by ansilh** [comment]
`caBundle` won't work on `gitRepo`. Only workaround we have for `gitRepo` is to set `spec.insecureSkipTLSVerify: true`

**Comment by andrisro** [comment]
Are there any news on this ? We've got the same issue, but skipping tls verification is not really an acceptable workaround.

**Comment by MSpencer87** [comment]
**Verified on 2.5.12 and 2.6.4 for local and downstream clusters**

Adding caBundle to yaml of ClusterRepo resource resolves error on local and downstream clusters:
`Get "https://<hostname url>/charts/index.yaml": x509: certificate signed by unknown authority`

Status of `Downloading` becomes `Active`

**Steps for Validation:**
(using AWS)
1. Create ec2 instance/Route53 entry
2. Add ec2 instance public ip as A record for Route 53 Entry
3. Setup NGINX webserver with custom SSL/Certs 
-Move files from local to instance
```
scp -i "your-aws.pem" certs/*.pem ubuntu@<server>:/home/ubuntu
```
-Move files on server, create `nginx/html` folder and `default.conf`
```
sudo mv *.pem /etc/ssl/certs/
mkdir -p ~/nginx/html
sudo vi ~/nginx/default.conf
```

default.conf
```
server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
 
    server_name <host_url>;
 
    ssl_certificate /etc/ssl/certs/cert.pem;
    ssl_certificate_key /etc/ssl/certs/key.pem;
   
    root /usr/share/nginx/html;
 
    location / {
    }
}
```
-Clone the charts repo into ngnix/html folder , pick a branch
```
git clone https://github.com/rancher/charts.git
git checkout dev-v2.6
```
-Start the NGINX server
```
sudo docker run --name docker-nginx -p 443:443 -v ~/nginx/html:/usr/share/nginx/html -v ~/nginx/default.conf:/etc/nginx/conf.d/default.conf -v /etc/ssl/certs:/etc/ssl/certs -d nginx
```
4. Bring up HA Rancher on 2.5.12/2.6.4
5. Create a downstream cluster
6. Add HTTPS chart repo on local/downstream cluster with hostname url from Route53 entry
7. Trigger Get "<hostname url>/charts/index.yaml": x509: certificate signed by unknown authority
8. Edit YAML for ClusterRepo yaml for local and downstream clusters and append `caBundle: "cert data from ca.pem"` into spec section
```
spec:
  clientSecret: null
  url: https://[hostname url from Route53 entry]
  caBundle: "cert data from ca.pem" <---
```
