### ISSUE TITLE
Private registry not applied to all ACI network provider system images

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#31726]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster whereby:
    - A private Registry is configured
    - The ACI network provider is enabled by adding the following configuration via "Edit as YAML"

```

  network:
    plugin: "aci"
    aci_network_provider:
      system_id: "rancher"
      apic_hosts:
      - "172.28.184.110"
      token: "2f8cc816-21e6-49d3-b18e-00d1bf38f37d"
      apic_user_name: "rancher"
      apic_user_key: "ABC"
      apic_user_crt: "ABC"
      encap_type: "vxlan"
      mcast_range_start: "225.10.1.1"
      mcast_range_end: "225.10.255.255"
      aep: "sauto-aep"
      vrf_name: "sauto_l3out-1_vrf"
      vrf_tenant: "common"
      l3out: "sauto_l3out-1"
      node_subnet: "10.100.1.1/24"
      l3out_external_networks:
      -  "sauto_l3out-1_epg"
      extern_dynamic: "10.3.0.1/24"
      extern_static: "10.4.0.1/24"
      node_svc_subnet: "10.5.0.1/24"
      kube_api_vlan: "213"
      service_vlan: "214"
      infra_vlan: "4081"
      service_monitor_interval: "5" 
```

**Expected Result:**
All system images are pulled from the private registry.

**Actual Result:**

One of the ACI CNI system images is not prefixed with the private registry and therefore fails to deploy in air-gapped setup.

`daemonset.apps/aci-containers-openvswitch `

```k get  deployment.apps/aci-containers-controller -o wide
NAME                        READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                  IMAGES                                                             SELECTOR
aci-containers-controller   0/1     1            0           49m   aci-containers-controller   ghcr.io/janeczku/noiro/aci-containers-controller:5.1.1.0.1a
k get daemonset.apps/aci-containers-host -o wide
NAME                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS                                      IMAGES                                                                                                                                                   SELECTOR
aci-containers-host   1         1         0       1            0           <none>          49m   aci-containers-host,opflex-agent,mcast-daemon   ghcr.io/janeczku/noiro/aci-containers-host:5.1.1.0.1ae238a,ghcr.io/janeczku/noiro/opflex:5.1.1.0.1ae238a,ghcr.io/janeczku/noiro/opflex:5.1.1.0.1ae238a   name=aci-containers-host,network-plugin=aci-containers
k get daemonset.apps/aci-containers-openvswitch -o wide
NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS                   IMAGES                              SELECTOR
aci-containers-openvswitch   1         1         1       1            1           <none>          51m   aci-containers-openvswitch   noiro/openvswitch:5.1.1.0.1ae238a   name=aci-containers-openvswitch,network-plugin=aci-containers
```

**Other details that may be helpful:**

Rancher 2.5.6
