### ISSUE TITLE
[rancher-compose] hangs on 

### ISSUE THREAD

**Issue by boedy** [rancher/rancher#3174]
Quite often rancher-compose hangs when running doing a inservice upgrade. I'm using this step in my CI setup. My deploys fail because rancher-compose never completes. I run the following command

> rancher-compose --verbose up -d --upgrade -c --interval 3000 --batch-size 1

Here is the full output:

```
time="2016-01-06T09:04:45Z" level=debug msg="Environment Context from file : map[]" 
time="2016-01-06T09:04:45Z" level=debug msg="Opening compose file: docker-compose.yml" 
time="2016-01-06T09:04:45Z" level=debug msg="[0/0] [app-data]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="[0/2] [beanstalkd]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="[0/2] [memcached]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="[0/4] [mysql]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="[0/4] [php]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="Opening rancher-compose file: /pipeline/source/rancher-compose.yml" 
time="2016-01-06T09:04:45Z" level=debug msg="[0/6] [webapp]: Adding " 
time="2016-01-06T09:04:45Z" level=debug msg="Looking for stack instore-backend" 
time="2016-01-06T09:04:46Z" level=debug msg="Found stack: instore-backend(1e63)" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for mysql" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for beanstalkd" 
time="2016-01-06T09:04:46Z" level=debug msg="Ignoring cycle for php->webapp->php" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for webapp" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for php" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for app-data" 
time="2016-01-06T09:04:46Z" level=debug msg="Project [instore-backend]: Creating project " 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [memcached]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [mysql]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [beanstalkd]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service mysql" 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service beanstalkd" 
time="2016-01-06T09:04:46Z" level=debug msg="Found service memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="Found service mysql" 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [mysql]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="Found service beanstalkd" 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [memcached]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [beanstalkd]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service webapp" 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [webapp]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="Found service webapp" 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [webapp]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [php]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [php]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [app-data]: Creating " 
time="2016-01-06T09:04:46Z" level=debug msg="[0/6] [app-data]: Created " 
time="2016-01-06T09:04:46Z" level=debug msg="Project [instore-backend]: Project created " 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for mysql" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="Launching action for beanstalkd" 
time="2016-01-06T09:04:46Z" level=info msg="Project [instore-backend]: Starting project " 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service mysql" 
time="2016-01-06T09:04:46Z" level=info msg="[0/6] [mysql]: Starting " 
time="2016-01-06T09:04:46Z" level=info msg="[0/6] [memcached]: Starting " 
time="2016-01-06T09:04:46Z" level=info msg="[0/6] [beanstalkd]: Starting " 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="Finding service beanstalkd" 
time="2016-01-06T09:04:46Z" level=debug msg="Found service memcached" 
time="2016-01-06T09:04:46Z" level=debug msg="Found service mysql" 
time="2016-01-06T09:04:46Z" level=info msg="[1/6] [mysql]: Started " 
time="2016-01-06T09:04:46Z" level=debug msg="Found service beanstalkd" 
time="2016-01-06T09:04:46Z" level=debug msg="Comparing hashes for memcached: old: digest.ServiceHash{Service:\"cda7a40ad7b8e911a3856711aec85763d5454084\", LaunchConfig:\"8fde712f4af5b587ca7eb95a09195e930eab29d5\", SecondaryLaunchConfigs:map[string]string{}} new: digest.ServiceHash{Service:\"cda7a40ad7b8e911a3856711aec85763d5454084\", LaunchConfig:\"8fde712f4af5b587ca7eb95a09195e930eab29d5\", SecondaryLaunchConfigs:map[string]string(nil)}" 
time="2016-01-06T09:04:46Z" level=debug msg="Comparing hashes for beanstalkd: old: digest.ServiceHash{Service:\"82f0a66d41781499e016f37ecc6d1e5455c0dd8c\", LaunchConfig:\"571a4e5c462538ed505a678983f3caf64d2ca4e6\", SecondaryLaunchConfigs:map[string]string{}} new: digest.ServiceHash{Service:\"82f0a66d41781499e016f37ecc6d1e5455c0dd8c\", LaunchConfig:\"571a4e5c462538ed505a678983f3caf64d2ca4e6\", SecondaryLaunchConfigs:map[string]string(nil)}" 
time="2016-01-06T09:04:46Z" level=info msg="[2/6] [memcached]: Started " 
time="2016-01-06T09:04:46Z" level=info msg="[3/6] [beanstalkd]: Started "
```

**Comment by deniseschannon** [comment]
Could you share your docker-compose.yml? Does it happen to have sidekicks and links in it? 

You might be hitting https://github.com/rancher/rancher/issues/2636

**Comment by boedy** [comment]
Here is my composer file (left out some image names):
```
webapp:
    image: <nginx container>
    ports:
        - "8080:80"
    volumes_from:
        - app-data
    links:
        - mysql
        - memcached
        - beanstalkd
    labels:
        io.rancher.sidekicks: php, app-data
        io.rancher.scheduler.affinity:host_label: web=true
php:
    image : <php container>
    labels:
        io.rancher.scheduler.affinity:host_label: web=true
    volumes_from:
        - app-data
    net: "container:webapp"
app-data:
    image: <datacontainer>
    labels:
        io.rancher.container.start_once: "true"
memcached:
    image: memcached:latest
beanstalkd:
    image: schickling/beanstalkd
mysql:
    image: mysql:5.6
```
