### ISSUE TITLE
GKE operator can have "Enable auto-upgrade" flag for Node Pools

### ISSUE THREAD

**Issue by prabalsharma** [rancher/rancher#31750]
**What kind of request is this (question/bug/enhancement/feature request):** feature request

GKE sets Enable auto-upgrade by default. This means if CP (control plane) k8s version is set to 1.18.15-gke.1100 the NP (node pool) version will also get set to 1.18.15-gke.1100, irrespective of version provided in clusterConfig.
However, GKE allows user to downgrade NP's k8s version after cluster creation by allowing users to unset Enable auto-upgrade.
GKE operator can have this flag in NP which will allow users to have different k8s version for CP and NP. 
However, once this flag is introduced in gke operator user will be able to have different k8s version from the get go, instead of just being able to change it via update of existing cluster, as **intended** by GKE.

**Comment by prabalsharma** [comment]
The main intent of auto-upgrade flag is to keep NP's k8s version up-to-date with cluster control plane (master) version (when GKE updates CP's k8s version automatically). Not to downgrade NP k8's version.

**Comment by cmurphy** [comment]
Fields added to GKEClusterConfigSpec:

```
nodePools:
- name: example
  management:
    autoRepair: true
    autoUpgrade: true
```

**Comment by prabalsharma** [comment]
Tested on RC 4: PASSED

Create cluster with `autoUpgrade: false`
```
config:
  kubernetesVersion: 1.18.15-gke.1100
    name: example-node-pool
    version: 1.17.17-gke.1101
    management:
      autoRepair: false
      autoUpgrade: false

gcloud:
currentMasterVersion: 1.18.15-gke.1100
currentNodeCount: 1
currentNodeVersion: 1.17.17-gke.1101
  version: 1.17.17-gke.1101
  management: {}
```
Update the above cluster
```
Config:
    management:
      autoRepair: false
      autoUpgrade: true
gcloud:
  management:
    autoUpgrade: true
  version: 1.17.17-gke.1101
```
Create Cluster with `autoUpgrade: true`
```
Config:
kubernetesVersion: 1.18.15-gke.1100
    management:
      autoUpgrade: true
    version: 1.17.17-gke.1101

gcloud:
currentMasterVersion: 1.18.15-gke.1100
currentNodeCount: 1
currentNodeVersion: 1.17.17-gke.1101
  management:
    autoUpgrade: true
  version: 1.17.17-gke.1101
```

Downgrade k8s version of NP
```
gke cluster:
currentMasterVersion: 1.18.15-gke.1100
  management:
    autoUpgrade: true
  version: 1.18.15-gke.1100

Config:
  kubernetesVersion: 1.18.15-gke.1100
      autoUpgrade: true
    version: 1.17.17-gke.1101

gcloud:
currentMasterVersion: 1.18.15-gke.1100
    autoUpgrade: true
  version: 1.17.17-gke.1101
  ```
