### ISSUE TITLE
After host recover from reconnecting stack's don't update in that same host

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#3175]
After a host recover from a reconnecting state the stack's in that host don't update automatically. I have to update the stack again to changes take effect in the affected host.

**Comment by cusspvz** [comment]
@fernandoneto is referring to global services, whenever you get a host online or add a new host, it should schedule a deployment of a container into those, thats not occurring. (it was on older versions)

Reproducible steps:
* Create an empty environment
* Create a stack
* Add a global service
* Add a host
* At this time, service should be scheduled on the recently added host, it won't be unless you edit the service and save it.

**Comment by deniseschannon** [comment]
I am unable to reproduce. If I add a host, the service is schedule on the recently added host.

When you "edit" the service, what are you doing? Are you just clicking on edit and then save?

What version of Rancher are you using? Can you share your docker-compose.yml of the global service.

**Comment by cusspvz** [comment]
Has happened with a host that went from `Reconnecting` state to `Active`, and with a host we added back up.

The services affected with this behavior were: a load-balancer and one maintenance image, both are running as global services.
It initially happened with me more than once, always with `Reconnecting` hosts being back up (instances were being deleted but not populated). Seems this behavior is intermittent because today it didn't happened once.

```
Component	Version
Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0
```

```yaml
autotune:
  environment:
    net__ipv4__tcp_max_orphans: '40000'
    net__ipv4__tcp_fin_timeout: '30'
    docker_remove_containers: '0'
    docker_remove_images: '1'
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: cusspvz/autotune:1.1.1
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
  net: host
```
