### ISSUE TITLE
Could we get certificate monitoring and alerting into Rancher / Prometheus / Alert Manager / Grafana?

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#31757]
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement request

**Steps to reproduce (least amount of steps as possible):**

How can we find out which certificates exist and get an alert before the certificate expieres so that we can act ahead of time before the certificate is expired?

**Result:**

It would be nice if we could add a cert-exporter that exports to prometheus, then an alert manager rule and a grafana dashboard for the certificates.

This should cover k8s certificates / host certificates and also certificates that might exist as secrets in namespaces.

**Comment by Tejeev** [comment]
@aiyengar2 What are the chances of us including some cert exporter (I found a couple online but they are user projects and didn't want to link them here yet)

**Comment by Martin-Weiss** [comment]
We had one included as part of SUSE CaaSP also having a Grafana dashboard.. Maybe we can re-use that?

**Comment by Tejeev** [comment]
Is the code on GH?
Could we link it here as a reference?

**Comment by Martin-Weiss** [comment]
I believe this was build on top of https://github.com/joe-elliott/cert-exporter (see helm chart https://kubernetes-charts.suse.com/cert-exporter-1.0.3.tgz) and the dashboard can be found here https://github.com/SUSE/caasp-monitoring/blob/master/grafana-dashboards-caasp-certificates.yaml

**Comment by Tejeev** [comment]
Awesome! Hopefully, this is stuff @aiyengar2 can work with

**Comment by aiyengar2** [comment]
Given the above code (the Grafana dashboard + the exporter to add) I think this is doable. 

Also, if we want alerts on certificate management (seems like there are no PrometheusRules for alerting linked here), we might need to design those from scratch.

But this may be more of a product question as to whether Monitoring V2 should support this / what are the feature requirements; @cloudnautique @deniseschannon any thoughts here?

**Comment by Martin-Weiss** [comment]
Sorry  - forgot to add this... here are also the alerts we had in CaaSP - see caasp.certs.rules below
(reference: https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-admin/#alertmanager-configuration-example):

```
serverFiles:
  alerts: {}
  rules:
    groups:
    - name: caasp.node.rules
      rules:
      - alert: NodeIsNotReady
        expr: kube_node_status_condition{condition="Ready",status="false"} == 1 or kube_node_status_condition{condition="Ready",status="unknown"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} is not ready'
      - alert: NodeIsOutOfDisk
        expr: kube_node_status_condition{condition="OutOfDisk",status="true"} == 1
        labels:
          severity: critical
        annotations:
          description: '{{ $labels.node }} has insufficient free disk space'
      - alert: NodeHasDiskPressure
        expr: kube_node_status_condition{condition="DiskPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available disk space'
      - alert: NodeHasInsufficientMemory
        expr: kube_node_status_condition{condition="MemoryPressure",status="true"} == 1
        labels:
          severity: warning
        annotations:
          description: '{{ $labels.node }} has insufficient available memory'
    - name: caasp.certs.rules
      rules:
      - alert: KubernetesCertificateExpiry3Months
        expr: (cert_exporter_cert_expires_in_seconds / 86400) < 90
        labels:
          severity: info
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 3 months'
      - alert: KubernetesCertificateExpiry30Days
        expr: (cert_exporter_cert_expires_in_seconds / 86400) < 30
        labels:
          severity: warning
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 30 days'
      - alert: KubernetesCertificateExpiry7Days
        expr: (cert_exporter_cert_expires_in_seconds / 86400) < 7
        labels:
          severity: critical
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 7 days'
      - alert: KubeconfigCertificateExpiry3Months
        expr: (cert_exporter_kubeconfig_expires_in_seconds / 86400) < 90
        labels:
          severity: info
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 3 months'
      - alert: KubeconfigCertificateExpiry30Days
        expr: (cert_exporter_kubeconfig_expires_in_seconds / 86400) < 30
        labels:
          severity: warning
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 30 days'
      - alert: KubeconfigCertificateExpiry7Days
        expr: (cert_exporter_kubeconfig_expires_in_seconds / 86400) < 7
        labels:
          severity: critical
        annotations:
          description: 'The cert for {{ $labels.filename }} on {{ $labels.nodename }} node is going to expire in 7 days'
      - alert: AddonCertificateExpiry3Months
        expr: (cert_exporter_secret_expires_in_seconds / 86400) < 90
        labels:
          severity: info
        annotations:
          description: 'The cert for {{ $labels.secret_name }} is going to expire in 3 months'
      - alert: AddonCertificateExpiry30Days
        expr: (cert_exporter_secret_expires_in_seconds / 86400) < 30
        labels:
          severity: warning
        annotations:
          description: 'The cert for {{ $labels.secret_name }} is going to expire in 30 days'
      - alert: AddonCertificateExpiry7Days
        expr: (cert_exporter_secret_expires_in_seconds / 86400) < 7
        labels:
          severity: critical
        annotations:
          description: 'The cert for {{ $labels.secret_name }} is going to expire in 7 days'

```
