### ISSUE TITLE
Support passing more configs (like fluentd scaling and `nodeSelector`) in the values.yaml 

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#31807]
**What kind of request is this (question/bug/enhancement/feature request):**
RFE

**Description**
Users are experiencing fluentd crashloops and failures due to the fluentd pod being overloaded.  The solution is to scale as per https://banzaicloud.com/docs/one-eye/logging-operator/configuration/fluentd/#scaling
This is currently not persistently possible with our charts.

@paynejacob  noted the following:

I was able to scale fluend by updating the spec.fluentd.scaling.replicas  key on the logging resources generated by the rancher chart.  This change will be overwritten any time the rancher-logging helm chart is updated but we can make an issue to add the fluentd scaling spec to the values.

WORKAROUND:
set `spec.fluentd.scaling.replicas`  on the logging resources generated by the rancher-logging helm chart. [example spec included below]

```
spec:
  controlNamespace: cattle-logging-system
  fluentbit:
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: 1.6.10
    nodeSelector:
      kubernetes.io/os: linux
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    configReloaderImage:
      repository: rancher/mirrored-jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.11.5-alpine-9
    nodeSelector:
      kubernetes.io/os: linux
    scaling:
      replicas: 3
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
```

LONG TERM FIX:
support passing fluentd scaling in the values.yaml

gz#15936
gz#15846

**Comment by zaggash** [comment]
It would also be good to pass the option for the Fluentd NodeSlector as well.

For now, the `nodeSelector` variable exposed to the chart applies to all the workloads from our chart.
However, upstream fluentd chart allows setting fluentd `nodeSelector`.

gz#15846

**Comment by bbenduduh** [comment]
Yes we need dedicated nodeSelector for fluentd to run on dedicated nodes for production architecture.

**Comment by Tejeev** [comment]
`nodeSelector` is definitely another one that comes up.. I've modified the issue name to address that we should expose more configs rather than one specifically.

**Comment by maxisam** [comment]
it would be nice to have buffer setting as well

**Comment by dbason** [comment]
> it would be nice to have buffer setting as well

Buffers can currently be configured as part of a Output or ClusterOutput using the operator.  The docs for the buffer settings are [here](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/buffer/)

**Comment by maxisam** [comment]
> > it would be nice to have buffer setting as well
> 
> Buffers can currently be configured as part of a Output or ClusterOutput using the operator. The docs for the buffer settings are [here](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/buffer/)

``
@dbason I meant something like the storage location

```yml
    bufferStorageVolume:
      pvc:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
          storageClassName: fast-storage
          volumeMode: Filesystem
```

**Comment by nickgerace** [comment]
## Additions

Merged PR https://github.com/rancher/charts/pull/1182 included changes from closed PR https://github.com/rancher/charts/pull/1112/ with the help of @dbason. These changes explicitly alter settings under `spec.fluentd` for all bundled Logging CRs in our chart.

## Details

Added option for `bufferStorageVolume`.
```
{{- if not .Values.disablePvc }}
{{- with .Values.fluentd.bufferStorageVolume }}
bufferStorageVolume: {{- toYaml . | nindent 6 }}
{{- end }}
{{- end }}
```

Added option for `fluentd`-only `tolerations` and `nodeSelector` settings.
```
{{- with (default .Values.tolerations .Values.fluentd.tolerations) }}
tolerations: {{- toYaml . | nindent 6 }}
{{- end }}
{{- with (default .Values.nodeSelector .Values.fluentd.nodeSelector) }}
nodeSelector: {{- toYaml . | nindent 6 }}
{{- end }}
```

Added option for `fluentd` `replicas`.
```
{{- if .Values.fluentd.replicas }}
scaling:
  replicas: {{ .Values.fluentd.replicas }}
{{- end }}
```

**Comment by izaac** [comment]
Rancher version: `master-head (05/14/2021)` _d7ef41e_
Logging chart version: `3.9.401`

```yaml
  values:
    additionalLoggingSources:
      rke:
        enabled: true
    disablePvc: false
    fluentd:
      bufferStorageVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            volumeMode: Filesystem
            volumeName: fluentvolume1

```

If I install with `disablePvc: true` and I include the `bufferStorageVolume` the volume information is not included as expected.

Validation of `fluentd`'s `tolerations`, `nodeSelector` and `replicas` is in progress.

**Comment by izaac** [comment]
Rancher version: `master-head (05/14/2021)` _be0b016_
Logging chart version: `3.9.401`

I see fluentd pods getting scheduled in control plane nodes in the cluster.
If I remove the toleration I also see these pods are removed from the control plane nodes.
```yaml
fluentd:
  tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: 'true'
```

If I set the replicas to 4 I see 4 pods in the fluentd deployment.
If I remove the key only 1 replica is created.
Increasing and decreasing the value and upgrading the app also reflects the applied value.
```yaml
fluentd:
  replicas: 4
```

With a combination of `nodeSelector`, `tolerations` and labels I was able to move around the fluentd pod.
```yaml
fluentd:
  nodeSelector:
     izaac.me/fav: test
```
