### ISSUE TITLE
rancher 流水线构建镜像使用的上海时区出现异常

### ISSUE THREAD

**Issue by TanLiangZhong** [rancher/rancher#31808]
环境：
  Rancher 2.5 ，使用的上海时区， 不是上海时区时构建没有问题
  k3s v1.20.4+k3s1

使用流水线构建Docker镜像异常:  
`
time="2021-03-26T04:27:42Z" level=fatal msg="Error authenticating: exit status 1"
`
![image](https://user-images.githubusercontent.com/30589592/112577843-25484600-8e30-11eb-9ee9-dd7775a34e3f.png)

.rancher-pipeline.yml
```
stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        yarn
        npm run build
- name: Push Images
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: liangzhong/jt-web:0.0.1-SNAPSHOT
      pushRemote: true
      registry: registry.cn-zhangjiakou.aliyuncs.com
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml
timeout: 60
notification: {}
```
