### ISSUE TITLE
[CatalogV2] rancher-logging helm chart - Splunk certificate issue

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#31810]
#### Using both secret definition explained in the [BanzaiCloud upstream doc](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/secret/)  

```
ca_file:
 valueFrom:
    secretKeyRef:
      name: <kubernetes-secret-name>
      key: <kubernetes-secret-key>
```  

Check the config in the `rancher-logging-fluentd` pod at `/fluentd/app_config/fluentd.conf`  

Currently, the `secret` is pasted in the config file as a _raw PEM_ and not as a _file location_.  
```
@id clusterflow:cattle-logging-system:splunk-hec-prd-all:clusteroutput:cattle-logging-system:splunk-hec-prd-output 
 ca_file -----BEGIN CERTIFICATE----- 
<redacted PEM> 
 -----END CERTIFICATE-----
```
Looking at the documentation from the [fluentd Splunk plugin documentation](https://github.com/fluent/fluent-plugin-splunk/blob/master/README.hec.md#ca_file)  it should be a file location.
A path to the cert and not the raw cert content pasted into the config file.

The other secret definition like below is not working either,  the content of `mountFrom` is deleted.
```
mountFrom:
    name: <kubernetes-secret-name>
    key: <kubernetes-secret-key>
```

#### Environment
Rancher version 2.5.6
rancher-logging Helm Chart version 3.9.000

gz#16014
gz#15792
gz#16219

**Comment by zaggash** [comment]
The same apply for the Elasticsearch CA definition.
gz#16014

**Comment by bbenduduh** [comment]
When using TLS, same dysfunctional behavior observed for Kafka and Syslog Outputs !

**Comment by dbason** [comment]
The syntax for using `mountFrom` should be:
```yaml
ca_file:
 mountFrom:
    secretKeyRef:
      name: <kubernetes-secret-name>
      key: <kubernetes-secret-key>
```

If the secret has been added in the UI, you should be able to modify the yaml for the installed app and change `valueFrom` to `mountFrom`.  Currently the UI is just adding the secret as a standard secretKeyRef
