### ISSUE TITLE
[UI] - Links not represented in UI despite existing and working.

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#3184]
```
Component	Version
Rancher	v0.50.1
Cattle	v0.127.0
User Interface	v0.74.0
Rancher Compose	v0.6.2
Close
```

**Summary**
Found a scenario where links aren't shown in the UI correctly despite working, steps to replicate below. 

**Steps to Replicate**
Run rancher compose with the below configuration, this configuration was created through the UI. 
```
bob:
  tty: true
  image: ubuntu:14.04.3
  links:
  - tim:divvytim
  stdin_open: true
tim:
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```
**Issue**
With the above, `bob` can indeed resolve `divvytim`. This isn't however represented in the UI under the 'Links' section of Bob's container page.
