### ISSUE TITLE
Given prefixPath of wins-upgrader is not considered

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31876]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.7 - deployed a windows cluster (2004 SAC) with `win_prefix_path` set.
- deployed the wins-upgrader app with the following set

```
masquerade:
  as: 'c:\\host\opt\etc\wmi-exporter\wmi-exporter.exe'
  enabled: false
prefixPath: 'c:\\host\opt'
```
- The app failed to deploy. The wins-upgrader pod logs show:
```
FATA[2021-03-31T13:51:18Z] rpc error: code = NotFound desc = could not found binary: could not get checksum: exec: "c:\\etc\\rancher\\wins\\wins-upgrade.exe": file does not exist
Returned exit 1
```

**Expected Result:**
Given prefixPath of wins-upgrader should be considered

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.8-rc1/2.5.7
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom windows
- Kubernetes version (use `kubectl version`):

```
1.20(Any)
```

**Comment by aiyengar2** [comment]
@sowmyav27 I was able to successfully deploy in a cluster using win_prefix_path.

I tried this in a 2 node cluster (1 Ubuntu, 1 Windows 1909 Server Core) with the following override to the cluster.yaml:
```
rancher_kubernetes_engine_config:
  win_prefix_path: 'c:\host\opt'
```

And the following override on deploy:
```
masquerade:
  as: 'c:\host\opt\etc\wmi-exporter\wmi-exporter.exe'
  enabled: true
prefixPath: 'c:\host\opt\'
```

Moving it back to test to see if it can be replicated.

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `41f173ae93`**

- monitoring chart version `14.5.100-rc07`, deployed wins upgrader using 
```
masquerade:
  as: 'c:\host\opt\etc\wmi-exporter\wmi-exporter.exe'
  enabled: true
prefixPath: 'c:\host\opt\'
```
- and no error was seen.
