### ISSUE TITLE
[Monitoring v2] root_url issues for non-local clusters

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#31891]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a NON-local cluster
2. On the non-local cluster install monitoring with this addition to the configuration
```
grafana:
   grafana.ini:
      server:
         root_url: https://floof.com/floofy
```

**Result:**
The base url of the grafana dashboard isn't changing which prevents me from loading grafana dashboards within the rancher dashboard because I either load the iframe with the original url and can't inject our assets or I load the iframe with localhost and subsequent resources and scripts fail to load due to cors.
![image](https://user-images.githubusercontent.com/55104481/113362538-79a56700-9303-11eb-9c1b-a8257a2220fb.png)
![image](https://user-images.githubusercontent.com/55104481/113362832-2849a780-9304-11eb-9ae7-464fecaa36d1.png)

**Other details that may be helpful:**
This is only happening for non-local clusters. When defining root_url for local we can see the base url change.
![image](https://user-images.githubusercontent.com/55104481/113363167-08ff4a00-9305-11eb-9d74-d81dc7faa7bd.png)

I've also attempted to use the domain and subpath properties without luck.
```
grafana:
   grafana.ini:
      server:
         root_url: https://floof.com/floofy
         domain: floof.com
         serve_from_sub_path: true
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head
- Installation option (single install/HA): single install
