### ISSUE TITLE
default backend ingress not work on another nodes

### ISSUE THREAD

**Issue by bilemedimkq** [rancher/rancher#31913]
**What kind of request is this (question/bug/enhancement/feature request):** Question

**Steps to reproduce (least amount of steps as possible):** 
https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#about-rancherd-installs
I followed the steps on these documents. I have installed this to three vm servers.(HA-Cluster)

**Result:**
When a create an ingress, i can only access that ingress from the first node i installed rancherd. i can't access these ingress from other two nodes. Based on a high availability structure, i need to access these ingress from all my nodes. 

**Other details that may be helpful:** These three are only present in the first node i create, but need them in all nodes.

![image](https://user-images.githubusercontent.com/42588052/113584092-27ca4d00-9633-11eb-81ca-9fe2b040837b.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom (Hetzner Cloud VMs)
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 VCpu 8 GB memory per node
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16+rke2r1", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-24T15:46:26Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16+rke2r1", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-24T15:46:26Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): Rancherd (v1.18.16+rke2r1)

Node 1: 
```
Architecture | amd64
-- | --
Boot ID | f318c67d-e2be-4982-a0d0-e2741569d3f6
Container Runtime Version | containerd://1.3.9-k3s1
Image | Ubuntu 20.04.2 LTS
Kernel Version | 5.4.0-66-generic
Kube Proxy Version | v1.18.16+rke2r1
Kubelet Version | v1.18.16+rke2r1
Machine ID | 85bf48ff45314b9d815a6bedce32f3b5
Operating System | linux
System UUID | 85bf48ff-4531-4b9d-815a-6bedce32f3b5
```

Node 2:

```
Architecture | amd64
-- | --
Boot ID | 8c147cbb-5406-45ec-af7d-9f8fbdef5b9a
Container Runtime Version | containerd://1.3.9-k3s1
Image | Ubuntu 20.04.2 LTS
Kernel Version | 5.4.0-66-generic
Kube Proxy Version | v1.18.16+rke2r1
Kubelet Version | v1.18.16+rke2r1
Machine ID | 41525295cb304506847a0a26629d5052
Operating System | linux
System UUID | 41525295-cb30-4506-847a-0a26629d5052
```

Node 3:
```
Architecture | amd64
-- | --
Boot ID | d6938e2b-f1d0-430a-9800-3496a160a6db
Container Runtime Version | containerd://1.3.9-k3s1
Image | Ubuntu 20.04.2 LTS
Kernel Version | 5.4.0-66-generic
Kube Proxy Version | v1.18.16+rke2r1
Kubelet Version | v1.18.16+rke2r1
Machine ID | 9143c6b0b1c34bed92b0e7b8c4f27ca1
Operating System | linux
System UUID | 9143c6b0-b1c3-4bed-92b0-e7b8c4f27ca1
```

**Comment by Martin-Weiss** [comment]
I assume you might have to change the number of replicas for the components you want to run multiple times.. if I remember right - the ingress controller is running only once and is configured for host networking per default - so changing this to three replicas and running one on each host should do the trick.

**Comment by bilemedimkq** [comment]
@Martin-Weiss 
I cannot modify any deployments managed by rancher helm. 
![image](https://user-images.githubusercontent.com/42588052/113677000-c1423f00-96c5-11eb-9a88-c6705876d138.png)
![image](https://user-images.githubusercontent.com/42588052/113677161-f3ec3780-96c5-11eb-9306-6337a99937f2.png)

but I saw something like this on this page(global > rke templates > add template), I guess it might be related to that 
![image](https://user-images.githubusercontent.com/42588052/113677377-331a8880-96c6-11eb-8c46-1e0ae744ecca.png)

**Comment by Martin-Weiss** [comment]
I do this override with a helmchartconfig:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      replicaCount: 3

```

**Comment by bilemedimkq** [comment]
yes this will make sense, but how can we make possible at least one pod running on every node?

**Comment by Martin-Weiss** [comment]
Not sure if I understand this question right.. why should we run a replica of a pod on every node? 
Is this required and if yes - why?

Ways to think about:
- adjust the number of replicas based on the number of nodes?
- use a daemon set instead of a deployment?
- in case you want to make the service reachable on all hosts you could also use nodeport instead of host network?

**Comment by bilemedimkq** [comment]
@Martin-Weiss Thank you for reply.

As you said I solved it using DaemonSet. I can access nginx-controller on any node right now. 


```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
```

I don't know what the DaemonSet is, I researched it when you said it.

Thank you!

**Comment by bilemedimkq** [comment]
@Martin-Weiss Thank you for reply.

As you said I solved it using DaemonSet. I can access nginx-controller on any node right now. 


```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
```

I don't know what the DaemonSet is, I researched it when you said it.

Thank you!
