### ISSUE TITLE
Environment ordering and substitution

### ISSUE THREAD

**Issue by boindil** [rancher/rancher#32095]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
dont reorder env variables where ordering (for subtitution) matters

```
 env:
        - name: VAR_A
          valueFrom:
            configMapKeyRef:
              name: confmap
              key: key1
        - name: VAR_B
          valueFrom:
            configMapKeyRef:
              name: confmap
              key: key2
        - name: CONCAT_VAR
          value: "a=$(VAR_A) b=$(VAR_B)"
```

**Result:**
Rancher reorders the entries resulting in the expression failing.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Kubernetes version (use `kubectl version`): v1.20.5+k3s1
