### ISSUE TITLE
[Monitoring V2] Set security.allow_embedding to true

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#32101]
To allow embedding grafana graphs and dashboards in the rancher dashboard we need the following to be set
```
grafana:
   grafana.ini:
      security:
         allow_embedding: true
```

https://grafana.com/docs/grafana/latest/administration/configuration/#allow_embedding
