### ISSUE TITLE
Unable to install on GKE Autopilot

### ISSUE THREAD

**Issue by crumohr** [rancher/rancher#32129]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Trying to install rancher via helm on GKE Autopilot.

```
kubectl create namespace cattle-system
helm install -f values.yaml rancher rancher-latest/rancher --namespace cattle-system
```

**Result:**

Pods crash on start, service account can't write to namespace `kube-system`.

```
error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:cattle-system:rancher" cannot create resource "configmaps" in API group "" in the namespace "kube-system": GKEAutopilot authz: the namespace "kube-system" is managed and the request's verb "create" is denied
```

**Other details that may be helpful:**

**Environment information**

```
CHART        	APP VERSION
rancher-2.5.7	v2.5.7
```

values.yaml

```yaml
additionalTrustedCAs: false
antiAffinity: preferred

auditLog:
  destination: sidecar
  hostPath: /var/log/rancher/audit/
  level: 0
  maxAge: 1
  maxBackup: 1
  maxSize: 100

addLocal: "true"
busyboxImage: busybox
debug: false
restrictedAdmin: true
hostname: rancher25.example.org
imagePullSecrets: []
ingress:
  enabled: true
  extraAnnotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  tls:
    source: secret
letsEncrypt:
  environment: production
  ingress:
    class: ""
privateCA: false
noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
rancherImage: rancher/rancher
replicas: 3
resources: {}
tls: external
systemDefaultRegistry: ""
useBundledSystemChart: false
certmanager:
  version: ""
customLogos:
  enabled: false
  volumeSubpaths:
    emberUi: "ember"
    vueUi: "vue"
  volumeKind: persistentVolumeClaim
  accessMode: ReadWriteOnce
  size: 1Gi
```

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE Autopilot
- Machine type (cloud/VM/metal) and specifications (CPU/memory): on demand
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
