### ISSUE TITLE
RKE2 Ingores multiple endpoint setting of private registry servers

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#32189]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Set main and fall back mirror in **registries.yaml** 

registries.yaml 
```
Customer registries.yaml  shown below.
mirrors:
  docker.io:
    endpoint:
      - "https://repo.infra.example.com/de:5002"
  mirror.lab.example.com:
    endpoint:
      - "https://mirror.lab.example.com:5000"
      - "https://repo.lab.example.com:5000"
```

Shut down 1st mirror mirror.lab.exaple.com:5000. 
The image will not be downloaded from 2nd mirror https://repo.lab.example.com:5000

**Result:**
```
# cricti -D mirror.lab.example.com:5000/gisys/oes-httpd:2.4.46-2
Error message is:
rpc error: code = Unknown desc = failed to pull and unpack image "mirror.lab.example.com:5000" connect: no route to host
```

**Other details that may be helpful:**

The idea is to use the 2nd server as a fallback in case the first endpoint is offline. 

Based on the Rancher RKE2 documentation the setting in registries.yaml with two mirrors looks correct.
The documentation says: Each mirror must have a name and set of endpoints. When pulling an image from a registry, containerd will try these endpoint URLs one by one, and use the first working one. 

Also /var/lib/rancher/rke2/agent/etc/containerd/config.toml  shows both mirrors set.
```
[plugins.cri.registry.mirror."mirror.lab.gothaer.de:5002"]
endpoint = [https://mirror.lab.gother.de:5000", "https://repo.lab.gothaer.de:5000"]
```

If the first set mirror is up and running, the image will be downloaded. 

**Environment information**
- Rancher version `Rancher v2.5.7`
- Installation option RKE 2 HA

**Cluster information**
- Cluster type Custom
- Machine type VM Nexus 3  (OSS Version, running outside of Kubernetes on VMs in Docker )
- Kubernetes version  v1.20.4

SF#280713
