### ISSUE TITLE
rancher-monitoring-windows-exporter fails to deploy on a windows cluster with win_prefix_path set

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32194]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- On a windows 2004 cluster - 3 linux worker nodes, 1 etcd/coontrol and 3 windows worker nodes, deploy wins upgrader with this set
- win_prefix_path set is `'c:\host\opt\'`
```
masquerade:
  as: 'c:\host\opt\etc\wmi-exporter\wmi-exporter.exe'
  enabled: true
prefixPath: 'c:\host\opt\'
```
- When this is deployed successfully, deploy monitoring v2 on the cluster, with provider selected as Windows.
- rancher-monitoring-windows-exporter fails to deploy
- Error in the `exporter node` pod's logs:
```
FATA[2021-04-16T18:26:24Z] rpc error: code = InvalidArgument desc = invalid path
```

**Expected Result:**
rancher-monitoring-windows-exporter should not fail to come up in a windows cluster with wins_prefix_path set

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `41f173a `
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): windows custom RKE
- Kubernetes version (use `kubectl version`):

```
1.20.5
```

**Comment by sirredbeard** [comment]
What happens if you use \\ in the path?

```
masquerade:
  as: 'c:\\host\\opt\\etc\\wmi-exporter\\wmi-exporter.exe'
  enabled: true
prefixPath: 'c:\\host\\opt\\'
```

**Comment by phillipsj** [comment]
We store the prefixPath and windowsPrefixPath on the cluster in the rancherKubernetesEngineConfig if it is set in the cluster yaml. We could do something like this in the chart to look it up. 

```
(lookup "v3" "clusters.management.cattle.io" "" "<cluster name>").spec.rancherKubernetesEngineConfig.PrefixPath
(lookup "v3" "clusters.management.cattle.io" "" "<cluster name>").spec.rancherKubernetesEngineConfig.WindowsPrefixPath
```

**Comment by sirredbeard** [comment]
Issue summary:

If you create a cluster with a custom windows prefix path, rancher-monitoring-windows-exporter fails. rancher-monitoring-windows-exporter has a hardcoded path. This information is stored in clusters.cattle.management.io for an existing downstream cluster, if the information isn't there, the user didn't supply a custom path and used the defaults.

One idea is that, because it is information about a cluster we are installing into, that prefixPath and wins_prefix_path should be populated by the UI and set in a global.cattle.* value. This would require a UI change, hence #32342. A possible approach would be to query for it on downstream cluster's config, if the values are present supply those, if not present, fall back to default locations.

**Comment by deniseschannon** [comment]
The UI request has been resolved. https://github.com/rancher/dashboard/issues/2837

Does this mean that this should be able to go to test?

**Comment by izaac** [comment]
I am trying to install rancher-wins-upgrader on `v2.5.8-rc15`

And end up with this error using default values:

```
helm install --namespace=cattle-wins-system --timeout=10m0s --values=/home/shell/helm/values-rancher-wins-upgrader-0.0.100.yaml --version=0.0.100 --wait=true rancher-wins-upgrader /home/shell/helm/rancher-wins-upgrader-0.0.100.tgz
Error: execution error at (rancher-wins-upgrader/templates/configmap.yaml:1:3): Must provide value for .Values.global.cattle.rkeWindowsPathPrefix 
```

Checking the Edit `Values YAML` section during install show these:

```
lobal:
  cattle:
    rkeWindowsPathPrefix: 'C:/'
    systemDefaultRegistry: ''
masquerade:
  as: >-
    {{ .Values.global.cattle.rkeWindowsPathPrefix 
    }}etc/wmi-exporter/wmi-exporter.exe
  enabled: false
```

```
status:
  branch: dev-v2.5
  commit: 1b856479033464d10ff5f2c6a523941fe1bd7157
```
