### ISSUE TITLE
[Logging v2] - win-agent-rke invalid volume specification when using a non default win_prefix_path

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32268]
**What kind of request is this:**
bug

**Steps to reproduce:**

- create a windows cluster (1 etcd/control plane, 1 linux worker, 1 windows worker
  - set the win_prefix_path to something non-default in `cluster.yml` (`win_prefix_path: 'c:\host\opt\'`)
- 

**Result:**

the win-agent-rke `rancher-logging-win-agent-rke-fluentbit` DaemonSet fails to create the pod as the path doesn't exist.

`CreateContainerError: Error response from daemon: invalid volume specification: 'c:/var/lib/rancher/rke/log:c:/var/lib/rancher/rke/log:ro': invalid mount config for type "bind": bind source path does not exist: c:\var\lib\rancher\rke\log`

Logging chart version `3.9.400-rc04`

**Environment information**
- Rancher version: `v2.5.8-rc7`
- Installation option: HA RKE

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (05/17/2021)`  _5d2b7ac_
Chart version: `3.9.401+up3.9.4`

This is part of values YAML (I've only added `global.cattle.windows.enabled: true`)
```yaml
...
global:
  cattle:
    systemDefaultRegistry: ''
    clusterId: c-4s9m8
    clusterName: izwinec2t2
    rkePathPrefix: ''
    rkeWindowsPathPrefix: 'c:\host\opt\'
    url: 'https://<REDACTED>'
    windows:
      enabled: true
  dockerRootDirectory: ''
  psp:
    enabled: true
  rkeWindowsPathPrefix: 'c:\'
  seLinux:
    enabled: false
  systemDefaultRegistry: ''
...
```


Error observed:

```
Error: Logging.logging.banzaicloud.io "rancher-logging" is invalid: [spec.nodeAgents.nodeAgentFluentbit.extraVolumeMounts.source: Invalid value: "": spec.nodeAgents.nodeAgentFluentbit.extraVolumeMounts.source in body should match '^/.+$', spec.nodeAgents.nodeAgentFluentbit.extraVolumeMounts.destination: Invalid value: "": spec.nodeAgents.nodeAgentFluentbit.extraVolumeMounts.destination in body should match '^/.+$']
```
