### ISSUE TITLE
[rancher-compose] Using rancher-compose up hangs.

### ISSUE THREAD

**Issue by jalleyne** [rancher/rancher#3230]
Hi, when i try to bring up a stack with django, mysql and nginx the host becomes disconnected in the rancher ui and cpu seems to spike on that host. In rancher the container seems to get activated but removed very quickly, before i can get any stadout or stderr. The interesting thing is if i docker-compose up, everything works fine on the same host. 

```yaml
web:
  build: ./web
  dockerfile: Dockerfile-staging
  privileged: true
  ports:
    - "8000"
  environment:
    - PYTHONPATH=/usr/src/app/[project name]
    - DJANGO_SETTINGS_MODULE=[project name].settings.dev
  links:
    - mysql
  labels:
    io.rancher.scheduler.affinity:host_label: environment=development,driver=virtualbox,os=boot2docker


nginx:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
  labels:
    io.rancher.scheduler.affinity:host_label: environment=development,driver=virtualbox,os=boot2docker


mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes_from:
    - mysqlData
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  labels:
    io.rancher.sidekicks: mysqlData
    io.rancher.scheduler.affinity:host_label: environment=development,driver=virtualbox,os=boot2docker


mysqlData:
  image: tianon/true
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: environment=development,driver=virtualbox,os=boot2docker
  net: none
  volumes:
    - /var/lib/mysql
```

i've seen reference to a websocket issue in the past, but from my understanding it should already have been resolved in my current versions:

`
Rancher	v0.51.0
Cattle	v0.130.0
User Interface	v0.78.0
Rancher Compose	v0.7.0
`

the only sign of error i can track down is rancher-agent logs `[WARNING] 007/215755 (670) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.`, any suggestions on debugging?
