### ISSUE TITLE
Non-default services fail dns checks in 1.21 k3s

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#32329]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Import a v1.20.6+k3s1 cluster into rancher
2. Upgrade the cluster to v1.21.0-rc1+k3s1
3. Deploy a workload into the cluster:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: busyb
spec:
  selector:
    app: busy
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
        - name: busybox
          image: busybox:1.28
          command:
            - sleep
            - "3600"
```
4. Run a standalone pod that has ping: `kubectl run tester --image=ranchertest/mytestcontainer`
5. Notice that running `kubectl exec tester -- nslookup busyb.default.svc.cluster.local` gives a valid result:
```
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	busyb.default.svc.cluster.local
Address: 10.42.2.45
Name:	busyb.default.svc.cluster.local
Address: 10.42.1.45
Name:	busyb.default.svc.cluster.local
Address: 10.42.3.42
```
6. Now use Rancher Service Discovery tab to deploy a service to "One or more workloads", selecting this "busydep" as the target. `kubectl exec tester -- nslookup <service name>.default.svc.cluster.local` does not work, but should.

**Result:**
This is because the service that gets deployed does not have the selector, even though the annotation is there:
```yaml
metadata:
  annotations:
    field.cattle.io/creatorId: user-2f6b2
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:default:busydep"]'
...
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
```

**Other details that may be helpful:**
Comparing this with the same process on a v1.20.6+k3s1 cluster, the service spec looks like this:
```yaml
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadID_w1: "true"
  sessionAffinity: None
  type: ClusterIP
```

I can edit the service manually via kubectl to add the same selector, which then allows nslookup to work as expected. The resulting spec after editing is:
```yaml
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadID_w1: "true"
  sessionAffinity: None
  type: ClusterIP
```
I'm unsure why in both cases on the 1.21 cluster it also adds the ipFamilies and ipFamilyPolicy information.

Somewhat related to v1.21 support in Rancher and https://github.com/rancher/rancher/issues/32298.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): single

**Cluster information**
versions specified above
