### ISSUE TITLE
helm chart - questions.yaml does not support slice or list? Bug

### ISSUE THREAD

**Issue by bjin01** [rancher/rancher#32336]
### questions.yaml does not handle list values e.g. ingress.hosts[0].host

**What kind of request is this (question/bug/enhancement/feature request):**
bug/feature 

**Steps to reproduce (least amount of steps as possible):**
helm create myapp
default ./templates/ingress.yaml
```
rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
```
In values.yaml:
```
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: test.domain.com
      paths: 
        - '/'
  tls: 
    - secretName: secret
      hosts:
        - test.domain.com
```

In questions.yaml I try to set the ingress.hosts.host but fails:
```
- variable: ingress.hosts.host
  default: "test.domain.com"
  required: true
  description: "Enter the rancher ingress hostname."
  type: string
  label: Rancher ingress - FQDN
  group: "Rancher ingress"
```

**Result:**
The value set in questions.yaml or via rancher cluster explorer app deployment configuration UI will not be taken into deployment.

**Other details that may be helpful:**
To review my chart go here:
['my chart'](https://github.com/bjin01/myrancher/tree/main/charts/myrancher)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.5.6
```
helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

**Cluster information**
hosted cluster
