### ISSUE TITLE
[Logging v2] - container miss security context after daemonset re-deploy from Rancher

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32344]
**What kind of request is this:**
bug

**Steps to reproduce:**

- SELinux enabled RKE2 downstream cluster (CentOS 8.3)
- Install Logging chart with `selinux.enabled = true` and select a Project 
- Chart installs properly, rke2 aggregator is present and available
- Go to Rancher and in from the UI select re-deploy on the rke2 aggregator daemonset. (Ember UI)

Working security context after chart install
```yaml
  spec:
      containers:
      - image: rancher/mirrored-fluent-fluent-bit:1.6.10
        imagePullPolicy: IfNotPresent
        name: fluentd
        resources: {}
        securityContext:
          seLinuxOptions:
            type: rke_logreader_t
```

**Result:**

container SecurityContext is missing if I check the YAML, the pod fails to create

`CrashLoopBackOff: back-off 5m0s restarting failed container=fluentd pod=rancher-logging-rke2-journald-aggregator-z69zc_cattle-logging-system(39b0fd90-6746-41d4-ac9d-4fb47b1db930)`

**Environment information**
- Rancher version: `v2.5.8-rc9`
- Installation option: HA RKE Centos 8 SELinux.
