### ISSUE TITLE
RKE2 Provisioning: Arbitrary Manifest Support (User Add-ons)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32365]
Ability to add any k8s yaml to a cluster

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#    additionalManifest: string
```
