### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Kubernetes Version - 1.21 Only

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32364]
Confirm that only k8s 1.21+ is shown when RKE2 provisioning feature flag is on. 

* Node Provisioning
* Custom
* Imported RKE2 clusters  
 
Test importing a k8s 1.19 cluster to see what happens with available 

Test use cases where RKE2 provisioning feature flag is on vs. off

**Comment by deniseschannon** [comment]
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
```
