### ISSUE TITLE
RKE2 Provisioning: Cluster Options - workerConfig => Agent Args

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32376]
Cluster Yaml
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:
     workerConfig:
#      - config:
#          
#        machineLabelSelector:
#          matchExpressions:
#            - key: string
#              operator: string
#              values:
#                - string
#          matchLabels:
#            key: string
```

Options for the agents are stored in KDM

https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml

```
agentArgs: &agentArgs-v1
      profile:
        type: enum
        options:
        - cis-1.5
        - cis-1.6
        nullable: true
      cloud-provider-config:
        type: string
      cloud-provider-name:
        default: null
        type: enum
        options:
        - aws
        - azure
        - gcp
        - vsphere
        - external
        nullable: true
      selinux:
        type: bool
      audit-policy-file:
        type: string
      system-default-registry:
        type: string
      protect-kernel-defaults:
        type: boolean
        default: false
      kubelet-arg:
        type: array
      kube-proxy-arg:
        type: array
```
