### ISSUE TITLE
RKE2 Provisioning: Cluster Options - controlPlaneConfig => serverArgs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32375]
Ability to configure ControlPlaneConfig:

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:
     controlPlaneConfig:
 ```

All options are  stored in KDM

https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml

```
serverArgs:
      cni:
        type: array
        options:
        - canal
      tls-san:
        type: array
      cluster-cidr:
        type: string
      service-cidr:
        type: string
      service-node-port-range:
        type: string
      cluster-dns:
        type: string
      cluster-domain:
        type: string
      kube-apiserver-arg:
        type: array
      kube-scheduler-arg:
        type: array
      kube-controller-manager-arg:
        type: array
      etcd-expose-metrics:
        type: boolean
      etcd-disable-snapshots:
        type: boolean
      etcd-snapshot-name:
        type: string
      etcd-snapshot-schedule-cron:
        type: string
      etcd-snapshot-retention:
        type: string
      etcd-snapshot-dir:
        type: string
      disable:
        type: array
        options:
        - rke2-coredns
        - rke2-ingress-nginx
        - rke2-kube-proxy
        - rke2-metrics-server
      secrets-encryption:
        type: boolean
      profile:
        type: string
        options:
        - cis-1.5
        - cis-1.6
      audit-policy-file:
        type: string
```
