### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Agent Environment Variables

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32385]
To be used for Proxy testing:

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#  agentEnvVars:
#    - name: string
#      value: string
#      valueFrom:
#        configMapKeyRef:
#          key: string
#          name: string
#          optional: boolean
#        fieldRef:
#          apiVersion: string
#          fieldPath: string
#        resourceFieldRef:
#          containerName: string
#          divisor: string
#          resource: string
#        secretKeyRef:
#          key: string
#          name: string
#          optional: boolean
```
