### ISSUE TITLE
RKE2 Provisioning: Cluster Options - CNI - Cilium

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32381]
`cilium` as a CNI Option

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#    cni: string
```
