### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Cluster Private Registry

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32389]
Unauthenticated (without username/password)
Authenticated (with username/password)
 - Using Amazon ECR (credential helper is typically built into docker so need to specifically test this use case)
 - Using Quay.io

https://rancher.com/docs/k3s/latest/en/installation/private-registry/

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
    rkeConfig:
 
#    registries:
#      configs:
#        authConfigSecretName: string
#          insecureSkipVerify: boolean
#          tlsSecretName: string
#      mirrors:
#        endpoints:
#            - string
#          rewrites:
#            key: string
```
