### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Pod Security Policy

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32383]
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  defaultPodSecurityPolicyTemplateName: null
 
```
