### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Default Cluster Role for Project Members

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32384]
Pick the default role for project members

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#  defaultClusterRoleForProjectMembers: string
```
