### ISSUE TITLE
RKE2 Provisioning: Cluster Options Upgrade Strategy (By Percentage of Nodes and Drain Options)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32387]
Concurrency - Control Plane - by percentage
Concurrency - Workers - by percentage support
Drain Options

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  defaultPodSecurityPolicyTemplateName: null
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  rkeConfig:
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
#        deleteEmptyDirData: boolean
#        disableEviction: boolean
#        enabled: boolean
#        force: boolean
#        gracePeriod: int
#        ignoreDaemonSets: boolean
#        ignoreErrors: boolean
#        skipWaitForDeleteTimeoutSeconds: int
#        timeout: int
      workerConcurrency: 10%
      workerDrainOptions:
#        deleteEmptyDirData: boolean
#        disableEviction: boolean
#        enabled: boolean
#        force: boolean
#        gracePeriod: int
#        ignoreDaemonSets: boolean
#        ignoreErrors: boolean
#        skipWaitForDeleteTimeoutSeconds: int
#        timeout: int
```
