### ISSUE TITLE
RKE2 Provisioning: Cluster Options Upgrade Strategy (Node Count and ability to drain)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32386]
Concurrency - Control Plane - by Node Count
Concurrency - Workers - by Node Count
Drain Control Plane
Drain Worker

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:
#    upgradeStrategy:
#      drainServerNodes: boolean
#      drainWorkerNodes: boolean
#      serverConcurrency: int
#      workerConcurrency: int
```
