### ISSUE TITLE
RKE2 Provisioning: Day 2 Ops - On Demand Etcd Snapshot and Restore (Local Snapshots)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32391]
Support for Local snapshot and Restore Use case

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  rkeConfig:

#    etcdSnapshotCreate:
#      name: string
#      nodeName: string
#      s3:
#        bucket: string
#        cloudCredentialName: string
#        endpoint: string
#        endpointCA: string
#        folder: string
#        region: string
#        skipSSLVerify: boolean
```
