### ISSUE TITLE
RKE2 Provisioning: Day 2 Ops - Etcd Restore

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32392]
local
s3
Restore with only etcd
Restore with etcd & k8s version
Restore with etcd snapshot, k8s version & cluster config

**Comment by deniseschannon** [comment]
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  rkeConfig:

#    etcdSnapshotRestore:
#      createdAt: string
#      name: string
#      nodeName: string
#      s3:
#        bucket: string
#        cloudCredentialName: string
#        endpoint: string
#        endpointCA: string
#        folder: string
#        region: string
#        skipSSLVerify: boolean

```
