### ISSUE TITLE
In the View Config of a stack, values that require $ are not being exported into the yml correctly. 

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3244]
If your Catalogue template needs to include a '$', then there is no way to do this; the template process assumes this to be a variable expansion.

EG: docker-compose.yml (simplified for clarity)
````
ssl-proxy:
  image: sshipway/nginx:1.9.9
  tty: true
  stdin_open: true
  ports:
    - ${PPORT}:443/tcp
  links:
    - portus:portus
  environment:
    NGINX_CONFIG: proxy_set_header X-Forwarded-Host \$http_host;
````

The `${PPORT}` will be correctly expanded.  We do not want the `$http_host` to be expanded; however the initial backstroke is ignored and this becomes `proxy_set_header X-Forwarded-Host \\;`.

I have tried this with and without a backstroke (no difference).  There is no template variable http_host defined and yet a replacement is attempted anyway.

Possible solutions -
- Require variable name ot be upper case, or require the {} surrounding the variable name
- Allow backstroke escapes to the $ symbol
- Replace templating system with Go Templates (so when in Go mode the $x expansion will not happen) - see #3239
