### ISSUE TITLE
NetworkFrom: service instance doesn't recreate on dependent container removal 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3245]
Steps to reproduce:

1) Create a service with 1 sidekick. Make sidekick reference primary launch config via networkFrom/volumesFrom. Its important that the primary config is being referenced
2) Destroy primary config instance.

Bug: secondary config instance doesn't get recreated

**Comment by sangeethah** [comment]
Tested with build from master:

1) Create a service with 1 sidekick. Make sidekick reference primary launch config via networkFrom/volumesFrom. 
2) Destroy primary config instance.

secondary config instance gets recreated

Following is docker-compose.yml used to create the service:

```
testnet2:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  net: "container:testnet1"
  stdin_open: true
testnet1:
  labels:
    io.rancher.sidekicks: testnet2
    io.rancher.container.pull_image: always
  tty: true
  image: nginx
  stdin_open: true
```
