### ISSUE TITLE
Add a 'certificate' type to Catalogue templates  [enhancement]

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3246]
Currently, templates can have variables of string, int, enum and boolean.

It would be helpful to have a 'certificate' type that gives a dropdown list of currently defined certificates for the Environment.  This would set the variable to the certificate name which could then be use to configure an SSL-offload load balancer in the default_cert option of the rancher-compose stanza for that load balancer.

By doing this, certificate management in Catalogue services could be handled via the Rancher UI automatically rather than having to make non-SSL services or have certificates mounted from shared volumes.

E.G. 
- rancher-compose.yml
````
.catalog:
  name: "MyService"
  version: "v1"
  description: "My Service"
  uuid: myservice-0
  questions:
    - variable: "CERTNAME"
      label: "Certificate"
      description: "SSL certificate to use"
      required: true
      type: "certificate"

mylb:
  load_balancer_config:
    haproxy_config: {}
  default_cert: ${CERTNAME}
````
- docker-compose.yml
````
mylb:
  ports:
  - 443:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
  tty: true
  image: rancher/load-balancer-service
  links:
  - web:web
  stdin_open: true
````

**Comment by blaggacao** [comment]
+1, @cloudnautique as discussed with Shannon by Mail, I'm working also on make this happen for a generic registry image.

**Comment by sshipway** [comment]
That's an interesting idea; how would you manage it?  

I've been theorising about having a sidekick container that obtains the cert (from an env var or HTTP URL in my case) and writes it to a filesystem which is exported and mounted by the main container (running e.g. nginx which just takes a path for the cert).  If the sidekick were to pull the cert from the Rancher API then this would work too, though it would be inconvenient to have to specify credentials to do this

**Comment by vincent99** [comment]
This would only work for the values going into the load balancer service.. The private key for certs is not readable from the API.

**Comment by blaggacao** [comment]
@vincent99 I think of exactly that use case, I wouldn't want more...

**Comment by blaggacao** [comment]
@sshipway I'm fiddling arround with this, can you confirm?

What is possible already:

```
.catalog:
  name: "Registry"
  version: "v2.1.0-1.1"
  description: "Docker Registry"
  uuid: registry-1
  questions: 

... 

    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server.  This should be the CN in the certificates and will be the URL to contact the Registry"
      required: true
      type: "string"

...

lb-registry:
  load_balancer_config: {}
  default_cert: ${DOMAIN}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

What would be ideal:

```
    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server.  This should be the CN in the certificates and will be the URL to contact the Registry"
      required: true
      type: "cert-select"
```

note proposed `cert-select` type
