### ISSUE TITLE
Why is binding proxy-clusterrole-kubeapiserver ClusterRole to the user kube-apiserver？

### ISSUE THREAD

**Issue by lshmouse** [rancher/rancher#32475]
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
- Add Cluster - Select Cluster Type
- Register an existing Kubernetes cluster
- Import Cluster: demo
- kubectl apply -f https://rancher-host/v3/import/wlzxhljjpglnswz8hjnn2ml8px57bsrb9nsg7nc46p7g49zplsftzc_c-62xvl.yaml    

**Result:**
There is a ClusterRoleBinding: proxy-role-binding-kubernetes-master.
Why is this ClusterRoleBinding binding proxy-clusterrole-kubeapiserver ClusterRole to the user kube-apiserver？
What is the user of kube-apiserver? Where is it used? Thanks~
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-role-binding-kubernetes-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-clusterrole-kubeapiserver
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kube-apiserver
---
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/server
- Installation option (single install/HA): single install/

**Cluster information**
- Cluster type (Imported):
- Machine type (metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-mi.2", GitCommit:"0ff048667d878bac63e3729f656774146bf3f955", GitTreeState:"clean", BuildDate:"2020-12-30T10:31:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
$ docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:  
```
