### ISSUE TITLE
vsphere cpi and csi charts incompatible with rke2

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#32604]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Bring up an rke2 cluster with `cloud-provider-name: "vsphere"`

**Result:**
There are 3 incompatibilities here:

1. The CPI helm job fails to install due to RBAC conflicts:
```
Unable to continue with install: ClusterRole "cloud-controller-manager" in namespace "" exists...
Unable to continue with install: ClusterRoleBinding "cloud-controller-manager" in namespace "" exists...
```
2. If I delete those roles manually, the CPI chart installs, but it fails to set ProviderID on the node due to the selector on the daemonset - notice it does not contain the dash in `control-plane` for the node-selector, but the node does have it.  

    Not having the dash on the `control-plane` node-role label seems to make both this chart and RKE1 noncomplaint with upstream: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#:~:text=Introduce%20a%20new%20label

3. The CSI chart installs, but it has the same nodeselector issue on the `vsphere-csi-controller` pod. 

```
$ k describe ds -n kube-system vsphere-cloud-controller-manager
...
Node-Selector:  node-role.kubernetes.io/controlplane=true
...
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
...

$ k describe nodes
...
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=maxrke2
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=true
...

$ k get deployment.apps/vsphere-csi-controller -n kube-system -o yaml
...
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/controlplane: "true"
...
```

**Other details that may be helpful:**
I start my rke2 server with:
```
# /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: 644
cloud-provider-name: "vsphere"
```
and 
```
# /var/lib/rancher/rke2/server/manifests/vsphere-values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "myhost"
      datacenters: "mydatacenter"
      username: "myuser"
      password: "mypass"
      credentialsSecret:
        generate: true
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-csi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
      host: "myhost"
      datacenters: "mydatacenter"
      username: "myuser"
      password: "mypass"
      clusterId: "myid"
      configSecret:
        generate: true
    storageClass:
      datastoreURL: "mydatastoreurl"
```

Initial failing helm pod logs:
```
+ helm_v3 install rancher-vsphere-cpi /rancher-vsphere-cpi.tgz
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "cloud-controller-manager" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher-vsphere-cpi"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```
After clusterrole is manually deleted, the next failing helm pod logs:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRoleBinding "cloud-controller-manager" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher-vsphere-cpi"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**Versions:**
rke2 v1.21.0-alpha2+rke2r1
CPI Chart: https://charts.rancher.io/assets/rancher-vsphere-cpi/rancher-vsphere-cpi-1.0.000.tgz

**Comment by PennyScissors** [comment]
Some thoughts on this issue:
1. The RBAC conflicts are due to RKE2 and the vsphere chart using generic names. Since they don't deploy the same resources, I will update the chart to use a less generic name and wrap the RBAC logic in a toggle to provide more flexibility. 
2. I don't think the chart should contain any logic to set a node selector label based on RKE vs RKE2. It already provides a way to pass in your own node selector labels through the values.yaml, so you could pass in the `control-panel` label to override the `controlplane` default and it will work. The questions.yaml doesn't support objects though, so the user will need to do it through the values.yaml directly. As for RKE, I will create an issue to update the labels since we should aim to match upstream and we can then update the chart's default to `control-plane` so that default values work with both.

**Comment by cbron** [comment]
On part 2 above, if those labels don't change in time then that should at minimum be called out in the app-readme.md. A better solution would be to add a flag in the values.yaml that was for rke vs rke2 and then it swapped it for you. There is precedence for that where the UI will set it for you.

**Comment by PennyScissors** [comment]
@cbron I've brought that up to @vincent99 before, and he mentioned there isn't something in the UI to configure the chart based on rke1 vs rke2. Also, questions.yaml doesn't support objects so it would need to be a field to specify the cluster type like rk1, rk2, or other, and swap the label based on the user's selection.

**Comment by cbron** [comment]
Oh, maybe the UI never did implement that, I get mixed up. Yes we'd do it that way, the logging chart does similar thing: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/rancher-logging/3.9.401+up3.9.4/values.yaml#L108

**Comment by PennyScissors** [comment]
@cbron I updated my PR to include a question with a dropdown so the user can select between "rke", "rke2", or "other" and configure the chart with the correct node selector label based on the cluster type the user selects. However, there is a problem in the UI with enum typed field where the value is not overriding the value in the chart's values, so the user won't be able to use the drop down to select the cluster type. I created [this](https://github.com/rancher/rancher/issues/33032) issue to address that.

**Comment by vincent99** [comment]
@cbron @PennyScissors I guess Vue doesn't currently support question defaults so we can add that.  But If you want default values to be applied, they should really be in values.yaml instead of questions.yaml.  If you do a cluster template or helm install of this chart directly, questions.yaml is not going to be read or processed by anything.

**Comment by PennyScissors** [comment]
@vincent99 I agree for the most part. Default values should go in the values.yaml, but a default in questions.yaml seems like a better approach in this case because the question is used to set up something Rancher specific. If we set a default in values.yaml, the user would need to change it if they want to install the chart directly in a non-rke cluster.

**Comment by rancher-max** [comment]
Validated this is now working. RBAC issues have been resolved, and can specify the node selector which makes the other parts of the issue fine as well:
```
# /var/lib/rancher/rke2/server/manifests/vsphere-values.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-cpi
  namespace: kube-system
spec:
  valuesContent: |-
    vCenter:
    ...
    cloudControllerManager:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher-vsphere-csi
  namespace: kube-system
spec:
  valuesContent: |-
    ...
    csiController:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
```

I used v1.21.3+rke2r1 when validating.
