### ISSUE TITLE
run_once dont stop sidekicks

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#3261]
I've the following scenario

```
atena-cli:
    image: registry.pedro.com/atena:latest
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

cli:
    image: registry.pedro.com/laravel-cli
    labels:
        io.rancher.container.pull_image: always
        io.rancher.sidekicks: atena-cli
        io.rancher.scheduler.affinity:host_label: server=11
        io.rancher.container.start_once: true
    volumes_from:
        - atena-cli
    links:
        - postgres
    command: php /data/www/artisan migrate --force
```

The *cli* service works fine, it runs once and them die but the sidekick *atena-cli* keeps running and using resources. In my opinion, it should stop like the "parent" container.
