### ISSUE TITLE
worker label missing on custom RKE2 all-in-one node deployed from Explorer

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32654]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
* Use Cluster Management in Cluster Explorer UI
* Create a Custom RKE2 single-node cluster by using Registration Command with all 3 roles set

**Result:**
The managed rke2 cluster is up after a while but `node-role.kubernetes.io/worker=true` is not set. There are `etcd`,  `control-plane` and `master` role lables set.

**Other details that may be helpful:**
Ember UI is showing roles `etcd, Control Plane` and Explorer UI is showing only `Etcd` - but in both cases there should be role `All` present.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:master-head `8c014ef`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom RKE2
- Machine type (cloud/VM/metal) and specifications (CPU/memory): any
- Kubernetes version (use `kubectl version`): `v1.21.0-alpha2+rke2r1`

**Comment by deniseschannon** [comment]
Besides adding the label, we also need to taint the nodes to support the worker role.

Note: when adding these taint, this will cause toleration issues to the RKE2 charts.

**Comment by deniseschannon** [comment]
We need to add the context where if the worker role is selected, then add the worker label (`node-role.kubernetes.io/worker=true`):

https://github.com/rancher/rancher/blob/113c35317ea3524a8d6e9da6659c772377d33f2b/pkg/provisioningv2/rke2/planner/planner.go#L554

This issue should be used in conjunction with https://github.com/rancher/rancher/issues/32904

**Comment by sowmyav27** [comment]
**On master-head commit id: `2e6926b`**

- Deployed a 1 node rke2 cluster.
- `All` roles is seen on the cluster details page in Machines tab
- Labels on the node
```
  labels:
    cluster.x-k8s.io/cluster-name: custom
    objectset.rio.cattle.io/hash: <>
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/init-node: "true"
    rke.cattle.io/machine-id: <>
    rke.cattle.io/worker-role: "true"
```
<img width="1673" alt="Screen Shot 2021-07-27 at 12 57 43 PM" src="https://user-images.githubusercontent.com/26032343/127219477-d18c7426-368e-4064-bcbd-2d93bb9b8b41.png">

**Comment by deniseschannon** [comment]
The machine object is getting the label for the worker role, but the Kubernetes node is not getting the worker role label.

Using master-head, commit 94bca99, I deployed a 1 node all role cluster using DO.

In the cluster managements page, the machine indicates that the node is "All" roles:
<img width="975" alt="Screen Shot 2021-08-01 at 9 42 54 PM" src="https://user-images.githubusercontent.com/11410997/127805267-cab0d10f-eff8-490e-8011-5729ac8507a8.png">


Labels on Machine:
```
  labels:
    cluster.x-k8s.io/cluster-name: denisecanaltest
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/deployment-name: denisecanaltest-pool1
    machine-template-hash: "87634117"
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/init-node: "true"
    rke.cattle.io/machine-id: e5e04e5a34d9696efbb2f0ecf46e945fe4c1f7c9477713791fcd82077ea160c
    rke.cattle.io/worker-role: "true"
```

In the dedicated cluster view, under Cluster -> Kube Node, the node is labeled as "etcd, controlplane" and there is no node-role label to indicate it's a worker node. 

<img width="975" alt="Screen Shot 2021-08-01 at 9 42 54 PM" src="https://user-images.githubusercontent.com/11410997/127805276-9fa76724-479b-4fc4-9048-405eb3ffbec7.png">

Labels on the Kube Node:
<img width="1110" alt="Screen Shot 2021-08-01 at 9 43 57 PM" src="https://user-images.githubusercontent.com/11410997/127805342-cf0864dc-6430-4c89-8a88-beaa17ec5f15.png">
