### ISSUE TITLE
[Bug] Authentication Proxy does not work with Skaffold (blocks on rollout status)

### ISSUE THREAD

**Issue by Blackclaws** [rancher/rancher#32676]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug related to https://github.com/GoogleContainerTools/skaffold/issues/5810

**Steps to reproduce (least amount of steps as possible):**
Manage a cluster via rancher
Get the kubeconfig for the cluster and make sure your context is set to accessing the cluster via the rancher url (proxy mode) and not via the Authenticated Cluster Endpoint
Try using skaffold with the kubectl deployer and a deployment manifest (can be any simple deployment):

skaffold.yaml
```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: minimal-example
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minimal
  template:
    metadata:
      labels:
        app: minimal
    spec:
      containers:
      - name: minimal
        image: busybox
        command:
          - sleep
        args:
          - "10000"
```
**Result:**
Skaffold gets stuck at waiting for deployments to stabilize https://github.com/GoogleContainerTools/skaffold/issues/5810 and only converges after approximately 7 minutes

**Other details that may be helpful:**
Directly accessing the cluster via the api server authorized endpoint instead of the endpoint proxied by the rancher server works fine. So it appears that there is either missing functionality or some sort of weird caching behavior in play. 

Happens for all kinds of downstream clusters such as k3s or rke spawned by rancher.

**Environment information**
- Rancher version 2.5.8
- Installation option (single install/HA): HA
