### ISSUE TITLE
Websocker connect error: 'upgrade' token not found in 'Connection' header 

### ISSUE THREAD

**Issue by cantaylancapraz** [rancher/rancher#32751]
Hi,

I deployed rancher to existing EKS cluster. 
Dashboard is not able to connect websocket, and I couldn't find the reason. 

Versions:
Rancher: v2.5.8
ingress-nginx:3.30.0
load balancer: aws clasic load balancer

When I check logs of rancher pods, I see following logs:
```
[rancher-7cbb45db4-nk5x5] 2021/05/15 14:20:21 [ERROR] Error during subscribe websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header 
[rancher-7cbb45db4-nk5x5] 2021/05/15 14:20:21 [ERROR] Unknown error: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header 
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: rancher
    cert-manager.io/issuer-kind: Issuer
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"kubernetes.deneme.io","path":"/","allNodes":false}]'
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  creationTimestamp: "2021-05-14T16:23:52Z"
  generation: 2
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.5.8
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  rules:
  - host: kubernetes.deneme.io
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kubernetes.deneme.io
    secretName: tls-rancher-ingress
```

I can share any other resource if you want.
