### ISSUE TITLE
RKE2 EC2 multi-node diferent roles on node/nodepool provisioning is stalled

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32779]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Go to Cluster Explorer -> Cluster Management
- Make sure RKE2 is active
- Click on EC2 to start with the RKE2 EC2 cluster configuration.
- Select proper VPC and other configuration options

Create three different nodepools each one with different role selected and 1 node.

- 1 etcd
- 1 cp
- 1 worker

Leave other values with defaults.

**Result:**

![Screen Shot 2021-05-18 at 12 55 55 PM](https://user-images.githubusercontent.com/27659/118715391-69c0e400-b7d8-11eb-991b-ed0725ae62ae.png)

![Screen Shot 2021-05-18 at 12 55 17 PM](https://user-images.githubusercontent.com/27659/118715318-59a90480-b7d8-11eb-85eb-4016d2271044.png)

```
status:
  clusterName: c-m-933e844b
  conditions:
  - lastUpdateTime: "2021-05-18T19:44:43Z"
    reason: Reconciling
    status: "True"
    type: Reconciling
  - lastUpdateTime: "2021-05-18T19:44:43Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2021-05-18T19:44:43Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2021-05-18T19:45:44Z"
    status: "True"
    type: RKECluster
  - lastUpdateTime: "2021-05-18T19:45:44Z"
    message: waiting for control plane to be available
    reason: Waiting
    status: Unknown
    type: Provisioned
  observedGeneration: 2
```

**Other details that may be helpful:**

- Single node all roles node/nodepool works

**Environment information**
- Rancher version: `v2.6 master-head (05/18/2021)` _55f0bb2_
- Installation option: HA RKE1

**Cluster information**
- Cluster type: RKE2 EC2
- Kubernetes version: `v1.21.1-alpha4+rke2r1`
