### ISSUE TITLE
log_driver and log_opt are lost on round trip of rancher compos

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3277]
Steps to reproduce:
1. Create and start a stack that looks like the following:
```
foo:
  image: nginx
  log_driver: json-file
  log_opt:
    labels: foo
```
2. In the UI, view the stack config (ie, look at its docker and rancher compose)

Actual result: log_driver and log_opt do not appear in the config. However, containers that are part of the stack are appropriately configured with the log driver and opts.

Expected result: log_driver and log_opt show up in the compose yml.
