### ISSUE TITLE
rke2 cluster provisioning - Access to configure audit logging from the API is missing

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#32784]
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Audit logging cannot be configured via rancher UI/API on the rke2 clusters.
As an enhancement,  provision to configure audit logging on the API for easier access is needed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit 55f0bb2
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider

SURE-5352
SURE-6389 (Terraform side of this)

**Comment by deniseschannon** [comment]
In theory, if you set the audit policy file, there is a way:

https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml#L38

**Comment by snasovich** [comment]
Need to add support for specifying contents of audit-policy-file to "machineGlobalConfig" and push contents of this file to RKE2 via plan and set audit-policy-file option to point to this file.

**Comment by snasovich** [comment]
This is likely to miss 2.6.4 release, so adding `release-note` label on it (at least for now) to make sure we include call out that this is not supported yet.

**Comment by snasovich** [comment]
Need functionality similar to https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-cluster-yml-configuration (search for `audit_log`).

**Comment by snasovich** [comment]
The following PR (https://github.com/rancher/rancher/pull/40353/) adds support for delivering files to downstream nodes which is needed for this enhancement.

**Comment by sadhugit** [comment]
[SURE-5352] recently another customer also requested this.

**Comment by jiaqiluo** [comment]
Since Rancher v2.7.2, we can configure the audit logging for RKE2 clusters in Rancher's Dashboard.  

### Step 1: Prepare a Secret or ConfigMap containing the audit policy 

Below is an example of such a Secret, and it needs to meet the following two requirements:
1. The namespace needs to be `fleet-default` where the Cluster object exists
2. It must have the annotation ` rke.cattle.io/object-authorized-for-clusters: <Cluster-Name>` to allow Rancher to use the secret for the target cluster

Rancher Dashboard has an easy-to-use UI for creating the secret. 

```
apiVersion: v1
data:
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
kind: Secret
metadata:
  annotations:
    rke.cattle.io/object-authorized-for-clusters: jiaqi-c1
  name: jiaqi-audit-policy
  namespace: fleet-default
```
 
### Step 2: Edit the cluster as YAML 
 
First, we need to instruct Rancher to send the file to the control plane node. The field is under `.spec.rkeCofig.machineSelectorFiles`. 

```
    machineSelectorFiles:
      - fileSources:
          - configMap:
              name: ''
            secret:
              items:
                - key: audit-policy
                  path: /etc/rancher/rke2/jiaqi-audit-policy.yaml
              name: jiaqi-audit-policy
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
```

Second,  we need to instruct kube-apiserver to use the above audit  policy. The field is under `.spec.rkeCofig.machineGlobalConfig.kube-apiserver-arg`:
```
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/rke2/jiaqi-audit-policy.yaml
        - audit-log-path=/etc/rancher/rke2/jiaqi-audit.logs
```

Finally, we need to save the change and allow the cluster to finish the upgrading.

**Comment by jiaqiluo** [comment]
waiting for the updated Rancher docs to be live.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 cluster with audit logging enabled, validate in the control plane node that auditing is enabled|
|2|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled|
|3|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled, remove audit logging from the cluster and validate the audit logs remain|

**Comment by markusewalker** [comment]
Tested this against `v2.8-head` https://github.com/rancher/rancher/commit/efc48ac09ab8307cc949f13aa5e57cc2568c4ab6. See results below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/efc48ac09ab8307cc949f13aa5e57cc2568c4ab6

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster with audit logging enabled, validate in the control plane node that auditing is enabled|:x:|
|2|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled|:white_check_mark:|
|3|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled, remove audit logging from the cluster and validate the audit logs remain|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As the local admin user, created a secret in the `fleet-default` namespace with the sample YAML:
```
apiVersion: v1
kind: Secret
metadata:
  name: test
  annotations:
    rke.cattle.io/object-authorized-for-clusters: <downstream cluster to later be provisioned>
    #  key: string
  labels:
    {}
    #  key: string
  namespace: default
type: Opaque
data:
  test: <retracted>
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
  #  key: string
__clone: true
#immutable: boolean
```
2. Logged out and logged back in as a standard user.
3. Provisioned a downstream RKE2 `v1.27.5+rke2r1` node driver cluster.
     - When provisioning, the node driver is being recognized as a custom cluster. This is unexpected behavior, therefore, this test failed.

_________

**Scenario 2**
1. Repeated scenario 1, steps 1-3, but ensured I created a new secret for this separate downstream RKE2 `v1.27.5+rke2r1` node driver cluster.
2. Edited the downstream cluster to include the following snippets of YAML under `rkeConfig`:
```
machineSelectorFiles:
      - fileSources:
          - secret:
              name: '<secret name>'
              items:
                - key: audit-policy
                  path: /etc/rancher/rke2/mew-audit-policy.yaml
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
    machineGlobalConfig:
      cni: canal
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/rke2/mew-audit-policy.yaml
        - audit-log-path=/etc/rancher/rke2/mew-audit.logs
```
3. Validated that the cluster and nodes came back as `Active` after the changes were applied.
5. SSH'ed into the control plane node and validated that the logging is now present:
```
# pwd
/etc/rancher/rke2
# ll
total 22880
drwxr-xr-x 3 root root     4096 Sep 20 18:45 ./
drwxr-xr-x 5 root root     4096 Sep 20 18:01 ../
drwxr-xr-x 2 root root     4096 Sep 20 18:01 config.yaml.d/
-rw------- 1 root root 23398661 Sep 20 18:47 mew-audit.logs
-rw------- 1 root root      107 Sep 20 18:42 mew-audit-policy.yaml
-rw------- 1 root root       29 Sep 20 18:42 registries.yaml
-rw------- 1 root root      365 Sep 20 18:46 rke2-pss.yaml
-rw------- 1 root root     2969 Sep 20 18:47 rke2.yaml

```

_______

**Scenario 3**
1. Repeated scenario 2, steps 1-4, but ensured I created a new secret for this separate downstream RKE2 `v1.27.5+rke2r1` node driver cluster.
2. Edited the downstream cluster and removed the snippets of YAML added under the `rkeConfig` block.
3. Validated that the cluster and nodes came back as `Active` after the changes were applied.
4. SSH'ed into the control plane and validated that the logging files still remain despite updating the cluster.

**Comment by jiaqiluo** [comment]
The failure of Scenario 1 is caused by a regression in the Dashboard UI, which is tracked here https://github.com/rancher/dashboard/issues/9724

We will be able to re-validate Scenario 1 after the UI bug is fixed.

**Comment by markusewalker** [comment]
Tested this against `v2.8-head` https://github.com/rancher/rancher/commit/4c55a12f9c27873b31cd42bb60917c68df857e5b.


**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/4c55a12f9c27873b31cd42bb60917c68df857e5b

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster with audit logging enabled, validate in the control plane node that auditing is enabled|:x:|
|2|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled|:white_check_mark:|
|3|As a standard user, provision a downstream K3S cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled|:x:|
|4|As a standard user, provision a downstream RKE2 cluster, edit the cluster to enable audit logging, validate in the control plane node that auditing is enabled, remove audit logging from the cluster and validate the audit logs remain|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As the local admin user, created a secret in the `fleet-default` namespace with the sample YAML:
```
apiVersion: v1
kind: Secret
metadata:
  name: test
  annotations:
    rke.cattle.io/object-authorized-for-clusters: <downstream cluster to later be provisioned>
    #  key: string
  labels:
    {}
    #  key: string
  namespace: default
type: Opaque
data:
  test: <retracted>
  audit-policy: >-
    IyBMb2cgYWxsIHJlcXVlc3RzIGF0IHRoZSBNZXRhZGF0YSBsZXZlbC4KYXBpVmVyc2lvbjogYXVkaXQuazhzLmlvL3YxCmtpbmQ6IFBvbGljeQpydWxlczoKLSBsZXZlbDogTWV0YWRhdGE=
  #  key: string
__clone: true
#immutable: boolean
```
2. Logged out and logged back in as a standard user.
3. Provisioned a downstream RKE2 `v1.27.6+rke2r1` node driver cluster - ensured I specified the following YAML snippet:
```
machineSelectorFiles:
      - fileSources:
          - secret:
              name: '<secret name>'
              items:
                - key: audit-policy
                  path: /etc/rancher/rke2/mew-testing-cluster.yaml
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
    machineGlobalConfig:
      cni: canal
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/rke2/mew-testing-cluster.yaml
        - audit-log-path=/etc/rancher/rke2/mew-testing-cluster.logs
```
4. Validated that the cluster and nodes came back as `Active` after the changes were applied.
5. SSH'ed into the control plane node and validated that the logging is now present:
```
# pwd
/etc/rancher/rke2
# ll
total 16592
drwxr-xr-x 3 root root     4096 Oct  3 17:29 ./
drwxr-xr-x 5 root root     4096 Oct  3 17:29 ../
drwxr-xr-x 2 root root     4096 Oct  3 17:29 config.yaml.d/
-rw------- 1 root root 16958471 Oct  3 17:33 mew-testing-cluster.logs
-rw------- 1 root root      107 Oct  3 17:29 mew-testing-cluster.yaml
-rw------- 1 root root       29 Oct  3 17:29 registries.yaml
-rw------- 1 root root      365 Oct  3 17:29 rke2-pss.yaml
-rw------- 1 root root     2969 Oct  3 17:29 rke2.yaml
```

_________

**Scenario 2**
1. Provisioned a downstream RKE2 `v1.27.6+rke2r1` node dirver cluster - ensured that I have a separate secret for auditing.
2. Validated that the cluster and nodes came back as `Active` after the changes were applied.
3. Edited the cluster YAML to have the audit snippet seen in scenario 1.
4. Validated that the cluster and nodes came back as `Active` after the changes were applied.
5. SSH'ed into the control plane and validated that the logging is present.

_______

**Scenario 3**
1. Provisioned a downstream K3S `v1.27.6+k31` node driver cluster with the following snippet:
```
machineSelectorFiles:
      - fileSources:
          - secret:
              name: '<secret name>'
              items:
                - key: audit-policy
                  path: /etc/rancher/k3s/mew-audit-policy.yaml
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
    machineGlobalConfig:
     disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: false
      kube-apiserver-arg:
        - audit-policy-file=/etc/rancher/k3s/mew-k3s-test.yaml
        - audit-log-path=/etc/rancher/k3s/mew-k3s-test.logs
```
2. Cluster never provisions and I am left with the following:

![image](https://github.com/rancher/rancher/assets/52591819/9ba53f0f-9c21-4064-b9e9-838765d0e096)

_________


**Scenario 4**
1. Repeated scenario 2, steps 1-5, but ensured I created a new secret for this separate downstream RKE2 `v1.27.6+rke2r1` node driver cluster.
2. Edited the downstream cluster and removed the snippets of YAML added under the `rkeConfig` block.
3. Validated that the cluster and nodes came back as `Active` after the changes were applied.
4. SSH'ed into the control plane and validated that the logging files still remain despite updating the cluster.
