### ISSUE TITLE
fleet fails to deploy on 2.6 on cis-1.5 compliant hardened cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32825]
**What kind of request is this:**
bug

**Steps to reproduce:**

- Create an RKE cluster with nodes/kubernetes cis-1.5 compliant (See [doc](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.4/hardening-2.4/))
- Use valid certs to install Rancher `2.6 master-head (05/21/2021)` _4f9850d_ (to avoid [this issue](https://github.com/rancher/rancher/issues/32823))

**Result:**

`Error creating pods`

`Pods "fleet-controller-79554fcbf5-" is forbidden: PodSecurityPolicy: unable to admit pod: []; `

**Other details that may be helpful:**

Fleet version: `v0.3.5`

![Screen Shot 2021-05-21 at 10 35 23 AM](https://user-images.githubusercontent.com/27659/119176950-88192080-ba20-11eb-8771-3d5c19c6f35d.png)

**Environment information**
- Rancher version: `2.6 master-head (05/21/2021)` _4f9850d_ 
- Installation option: HA RKE1

**Comment by StrongMonkey** [comment]
I don't see these two resources being created. 
```
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
```
This will allow pods in all namespace to be able to use restricted psp. Otherwise you can't create pod in any namespace.

I see the resource is available in 2.5 cluster.yaml [doc](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.5-hardening-2.5/). Any chance you deployed an old version of cluster.yaml?
