### ISSUE TITLE
Validate HA Rancher deployment on hardened K3s cluster

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#32858]
Validate HA Rancher deployment on hardened K3s cluster.

**Comment by rancher-max** [comment]
Am able to deploy v2.6 rancher using both ingress-nginx and traefik on a hardened k3s cluster. Validated on master-head commit `cf5a75f`. In traefik setups, the following network policy is required to be deployed: 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-traefik-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [traefik,svclb-traefik]}
  policyTypes:
  - Ingress
```
