### ISSUE TITLE
[Backport 2.5] CleanupDuplicateBindings blocks rancher startup

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#32873]
This is to backport the fix fo https://github.com/rancher/rancher/issues/32792

Rancher 2.5.8

The call to https://github.com/rancher/rancher/blob/master/pkg/multiclustermanager/app.go#L217 needs to be done in a goroutine. In a setup that has thousands of duplicates this is a blocking call and stops rancher startup from completing until the cleanup is done.

gz#16062

**Comment by Jono-SUSE-Rancher** [comment]
This needs to be checked for the v.2.5.9-RC and v2.5.-head.

**Comment by dramich** [comment]
https://github.com/rancher/rancher/pull/32870

**Comment by jiaqiluo** [comment]
available for testing in rancher v2.5.9-rc1

**Comment by anupama2501** [comment]
Reproduced the issueon rancher v2.5.8
Before upgrade Rancher version: v2.5.6
After upgrade Rancher version: v2.5.8

1. Created a rancher server on v2.5.8
2. Created a cluster c1 with 3 worker nodes, 1 etcd node,1 cp 
3. Created a standard user user1 and created a project in the cluster c1 as P1 and added the user1 as both project owner and project member
4. Created 10k duplicates for the user1 from the project owner template created above with the yaml:
```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
 labels:
  "cattle.io/creator": norman
  "p-g9lm4_prtb-w2kdj": "membership-binding-owner"
 name: "text2000"
 namespace: "c-z8ntn"
roleRef:
 apiGroup: "rbac.authorization.k8s.io"
 kind: Role
 name: "p-g9lm4-projectowner"
subjects:
- apiGroup: "rbac.authorization.k8s.io"
  kind: User
  name: "u-xdr67"
```
5. Duplicates seen in the rancher server:
```
DEBU[0000] running deduperbs command
DEBU[0000] kubeConfig: kubeconfig.yaml
DEBU[0000] using kubeconfig: kubeconfig.yaml
DEBU[0000] groups of duplicate role bindings: 1
DEBU[0000] total duplicate role bindings: 10002
DEBU[0000] groups of duplicate cluster role bindings: 1
DEBU[0000] total duplicate cluster role bindings: 2
```
7. Upgraded the server to rancher v2.5.8, the duplicates were seen cleaned up and the rancher server took more than 2 minutes to come up:
