### ISSUE TITLE
kubectl exec fails with "Error 400"

### ISSUE THREAD

**Issue by learningkeeper** [rancher/rancher#32881]
We managed to install a rancher server inside a vm and it would coordinate to a GKE kube server API.
However, while we were using kubectl exec to get a shell, we always get the information. Just wonder how we solve it..

The vm is behind the GCP loadblancer with ssl termination. 

user->lb->vm(rancher)->kube API

```
error: unable to upgrade connection: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>

```

docker command and rancher version as below 
```
[root@rancher ~]# cat rancher/docker-compose.yaml
version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    restart: unless-stopped
    #command: --no-cacerts
    volumes:
      - /srv/docker/rancher/data:/var/lib/rancher
      - /srv/docker/rancher/log:/var/log/auditlog
    environment:
      - AUDIT_LEVEL=3
      - AUDIT_LOG_PATH=/var/log/auditlog/rancher-api-audit.log
      - AUDIT_LOG_MAXAGE=20
      - AUDIT_LOG_MAXBACKUP=30
      - AUDIT_LOG_MAXSIZE=1000

```

Any more information needed?
