### ISSUE TITLE
monitoring V2 - 14.5

### ISSUE THREAD

**Issue by kombiwagon** [rancher/rancher#32908]
Rancher 2.5.8
Monitoring Version 14.500

Hi, is it possible to collect metrics from outside the cluster by prometheus.
In other words can I add external target to prometheus.
for example: collect metrics from different kubernetes cluster or from database installed on external VM
thank you for replay.

**Comment by konstantin-921** [comment]
Hi
Yes, it is possible. I have configured the prometheus provided by Rancher to retrieve logs from external sources. Of course, node-exporters must already be running on the target nodes before that. To do this, you need to create the following resources in one of your namespaces:

**ServiceMonitor**

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: gpu-metrics-sm
    namespace: monitoring
    labels:
        k8s-app: gpu-metrics
        release: rancher-monitoring-prometheus
spec:
    selector:
      matchLabels:
          k8s-app: gpu-metrics
          release: rancher-monitoring-prometheus
    endpoints:
    - port: metrics
      interval: 10s
      honorLabels: true
      relabelings:
      - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
        targetLabel: instance
```

**Service**

```
apiVersion: v1
kind: Service
metadata:
    name: gpu-metrics
    namespace: monitoring
    labels:
        k8s-app: gpu-metrics
        release: rancher-monitoring-prometheus
spec:
    clusterIP: ""
    ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
```
**Endpoints**

```
apiVersion: v1
kind: Endpoints
metadata:
  namespace: monitoring
  name: gpu-metrics
  labels:
    k8s-app: gpu-metrics
subsets:
  - addresses:
    - ip: 10.0.1.111
      targetRef:
        name: jenkins
    - ip: 10.0.1.100
      targetRef:
        name: elk
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
```

After that in Grafana you will be able to see new metrics.

But on our project we abandoned this approach because:
- we can't know if our custom resources will be broken after updating monitoring or updating the whole Rancher
- I don't remember exactly how it happened, but the new metrics somehow broke some default dashboards

So we came to the decision to use a separate monitoring system for external or any other custom targets (including within the cluster). We simply used [Victoria Metrics helm chart](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/README.md). This solution showed itself perfectly. Now we have 2 independent monitoring systems in the cluster.
