### ISSUE TITLE
Rancher doesn't apply Pod Security Policy to the cluster

### ISSUE THREAD

**Issue by konstantin-921** [rancher/rancher#32940]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. From the Global view, find the cluster to which I want to apply a pod security policy. I Selected ⋮ > Edit.
2. Expanded Cluster Options.
3. From Pod Security Policy Support, it was selected Enabled.
4. From the Default Pod Security Policy drop-down I selected "restricted".
5. Clicked Save.
6. Created following Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: privileged-deploy
  name: privileged-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-deploy
  template:
    metadata:
      labels:
        app: privileged-deploy
    spec:
      containers:
        - image: alpine
          name: alpine
          stdin: true
          tty: true
          securityContext:
            privileged: true
      hostPID: true
      hostNetwork: `true`
```

As I understand this Deployment should not have started the pods, as it does not match "restricted" PSP thanks by fields: privileged, hostPID, hostNetwork.

**Result:**
Pod started without any problems.

**Expected result**
There should have been an error and the pod was not supposed to start

**Environment information**
- Rancher version: 2.5.5
- Installation option (single install/HA): HA
- Kubernetes Version: v1.19.3-rancher1-2

**Comment by anupama2501** [comment]
On rancher version v2.5.8, k8s version: v1.20.6 

1. Created a 1 node all roles node driver DO cluster
2. Once it is active, edited the cluster and enabled the Pod security Policy with restricted "Default Pod Security Policy*
3. Cluster goes into updating state and once it is active, deployed 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: privileged-deploy
  name: privileged-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privileged-deploy
  template:
    metadata:
      labels:
        app: privileged-deploy
    spec:
      containers:
        - image: alpine
          name: alpine
          stdin: true
          tty: true
          securityContext:
            privileged: true
      hostPID: true
      hostNetwork: true
```

4. It immediately errors out as follows:
```
Pods "privileged-deploy-8878b565b-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]; Deployment does not have minimum availability.
```

**Comment by konstantin-921** [comment]
Thank you for testing. I will update the Rancher and the cluster to the versions you mentioned. After that, I will check again to see if the PSP is enabled. I will post the results here.

**Comment by konstantin-921** [comment]
Updated to:
1) Rancher version: 2.5.8
2) Rancher local cluster k8s version: v1.20.5-rancher1-1
3) Kubernetes Version: v1.20.6

When upgrading, I also enabled Default Pod Security Policy drop-down I selected "restricted"
![Selection_001](https://user-images.githubusercontent.com/34741216/120169257-6d0c9480-c208-11eb-8ddf-97843b7e510f.png)

After that deployed the same test deployment. It was deployed without any errors again. I can't figure out what I'm doing wrong.

**Comment by konstantin-921** [comment]
What ClusterRole and ClusterRoleBinding should exist after enabling a PSP with restricted "Default Pod Security Policy"?

**Comment by konstantin-921** [comment]
Additional cluster details:

**ClusterRole**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    serviceaccount.cluster.cattle.io/pod-security: restricted
  labels:
    cattle.io/creator: norman
  name: restricted-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
  ```

**RoleBinding** for default ns:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    podsecuritypolicy.rbac.user.cattle.io/psptpb-role-binding: "true"
    serviceaccount.cluster.cattle.io/pod-security: restricted
  labels:
    cattle.io/creator: norman
  name: default-default-default-restricted-clusterrole-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```

**ServiceAccount** for default ns:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
secrets:
- name: default-token-hs7bn
```
