### ISSUE TITLE
Sorting of env vars leads to error state

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#32963]
*After editing a deployment or statefulset the ordering of the env vars gets changed. This can lead to issues if the env vars depend on one another (see example below). The kubernetes documentation states that the ordering is important.(https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)*
```
env:
  - name: MY_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: RABBITMQ_NODE_NAME
    value: "rabbit@$(MY_POD_NAME)"
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.7` UI: `v2.5.6` |
