### ISSUE TITLE
Network Adapter is missing after adding windows 2004 host

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#32970]
## Rancher Server
`v2.5.8`
## K8S Version
`v1.18.18`
## Windows UBR
`10.0.19041.985`
## Docker Version
`20.10.5`
## logs 
```text
C:\Users\Administrator>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::dd63:c1ac:342b:2b26%8
   IPv4 Address. . . . . . . . . . . : 192.168.10.161
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 192.168.15.1

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::686b:539b:76ae:cb81%13
   IPv4 Address. . . . . . . . . . . : 172.17.112.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

C:\Users\Administrator>docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS          PORTS     NAMES
51c1dc3a3d20   rancher/rke-tools:v0.1.74             "pwsh -NoLogo -NonIn…"   20 hours ago   Up 50 seconds             nginx-proxy
5e67d450e784   rancher/hyperkube:v1.18.18-rancher1   "pwsh -NoLogo -NonIn…"   20 hours ago   Up 26 seconds             kubelet
66a7c62d6189   rancher/hyperkube:v1.18.18-rancher1   "pwsh -NoLogo -NonIn…"   20 hours ago   Up 21 seconds             kube-proxy
2486f71d1ade   rancher/rke-tools:v0.1.74             "pwsh -NoLogo -NonIn…"   20 hours ago   Up 50 seconds             service-sidekick
919cc49657b8   rancher/rancher-agent:v2.5.8          "pwsh -NoLogo -NonIn…"   20 hours ago   Up 54 seconds             boring_jennings

C:\Users\Administrator>ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (Ethernet) 6:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::6186:43fc:8b78:422c%9
   IPv4 Address. . . . . . . . . . . : 10.0.19.25
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.19.1

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::686b:539b:76ae:cb81%13
   IPv4 Address. . . . . . . . . . . : 172.17.112.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

C:\Users\Administrator>docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS              PORTS     NAMES
51c1dc3a3d20   rancher/rke-tools:v0.1.74             "pwsh -NoLogo -NonIn…"   20 hours ago   Up 57 seconds                 nginx-proxy
5e67d450e784   rancher/hyperkube:v1.18.18-rancher1   "pwsh -NoLogo -NonIn…"   20 hours ago   Up 32 seconds                 kubelet
66a7c62d6189   rancher/hyperkube:v1.18.18-rancher1   "pwsh -NoLogo -NonIn…"   20 hours ago   Up 28 seconds                 kube-proxy
2486f71d1ade   rancher/rke-tools:v0.1.74             "pwsh -NoLogo -NonIn…"   20 hours ago   Up 57 seconds                 service-sidekick
919cc49657b8   rancher/rancher-agent:v2.5.8          "pwsh -NoLogo -NonIn…"   20 hours ago   Up About a minute             boring_jennings

C:\Users\Administrator>
```

**Comment by sirredbeard** [comment]
Are you using Host Gateway (L2bridge) or VXLAN (Overlay)?

**Comment by laoshancun** [comment]
VXLAN (Overlay)

**Comment by laoshancun** [comment]
`Ethernet adapter Ethernet`  is missing after hnsnetwork created。

**Comment by laoshancun** [comment]
Custom Kubernetes Cluster Yaml
```yaml
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: windows
windows_prefered_cluster: true
system_images:
  alpine: rancher/rke-tools:v0.1.74
  nginx_proxy: rancher/rke-tools:v0.1.74
  cert_downloader: rancher/rke-tools:v0.1.74
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.74
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509|webhook
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy:
        rolling_update: {}
    options: null
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy:
      rolling_update: {}
    upstreamnameservers: null
  ignore_docker_version: true
  ingress:
    default_backend: true
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.18.18-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_port: '4789'
      flannel_backend_type: vxlan
      flannel_backend_vni: '4096'
    plugin: flannel
  restore:
    restore: false
  rotate_encryption_key: false
  system_images:
    alpine: rancher/rke-tools:v0.1.74
    nginx_proxy: rancher/rke-tools:v0.1.74
    cert_downloader: rancher/rke-tools:v0.1.74
    kubernetes_services_sidecar: rancher/rke-tools:v0.1.74
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      debug_master: false
      debug_worker: false
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24

```
