### ISSUE TITLE
Rancher pods are redirecting incoming calls internally to https with tls=external

### ISSUE THREAD

**Issue by ToniIltanen** [rancher/rancher#33041]
K3s & HA Rancher V2.5.8 + nginx ingress

Description: Rancher pods are redirecting incoming calls internally http -> https - ingress config has no affect

Should be: 
- If tls=external is used, rancher should listen only in port 80 (or other custom defined port)
- Rancher should not internally redirect anything to https

my ingress conf 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher
  namespace: cattle-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/use-forwarded-header: "true"
spec:
  rules:
  - host: domain.com
    http:
      paths:
      - backend: 
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific  
```

result is a redirection to https: 
```
curl rancher-server-1 -H "Host: domain.com"
HTTP/1.1 302 Found
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 04 Jun 2021 08:55:51 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 54
Connection: keep-alive
Location: https://domain.com

<a href="https://domain.com/">Found</a>.
```

if i delete the ingress, and inside the pod run the curl against localhost the result is the same:
```
user@rancher-server-1:~/template$ sudo kubectl -n cattle-system exec --stdin --tty rancher-6bcc7cc457-j2zp9 -- /bin/bash
root@rancher-6bcc7cc457-j2zp9:/var/lib/rancher# curl localhost -i
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: https://localhost/
Date: Fri, 04 Jun 2021 08:56:36 GMT
Content-Length: 41

<a href="https://localhost/">Found</a>.

root@rancher-6bcc7cc457-j2zp9:/var/lib/rancher# 
```

how can i prevent this? It seems that rancher itself is doing redirects.
I am using an external load balancer which terminates the TLS instead kubernetes.

i installed rancher with helm and tls external
```
  helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=domain.com \
  --set replicas=3 \
  --set tls=external \
  --version v2.5.8
```

my external nginx loadbalancer configs

```
upstream rancher {
        server rancher-server-1:80;
        server rancher-server-2:80;
        server rancher-server-3:80;
    }

map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
    listen 443 ssl spdy;
    server_name domain.com;
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name domain.com;
    return 301 https://$server_name$request_uri;
```

I have other deployments that works, so this must be a rancher issue - not an issue of the external load balancer.
K3s masters were installed without the default lb (nginx-ingress used instead) with:
```
curl -sfL https://get.k3s.io | sh -s - server --no-deploy traefik --datastore-endpoint=db_address
```

**Comment by oxr463** [comment]
See also: https://github.com/rancher/rancher/issues/25176

**Comment by oxr463** [comment]
I am running into the same issue after modifying my Elastic Load Balancer (ELB) to use an AWS Certificate Manager (ACM) certificate. Here is my terraform code:

- https://gist.github.com/oxr463/01f13f9e9079e4743962a982966428b9
-

**Comment by ToniIltanen** [comment]
As you can see, i had the forward headers option enabled but still no success

`nginx.ingress.kubernetes.io/use-forwarded-header: "true"`

**Comment by ToniIltanen** [comment]
In my case, we stopped using rancher and changed to using plain k3s + prometheus

**Comment by oxr463** [comment]
For my issue, it was due to the listener port(s) (30422 and 30770). I also had to adjust my security group to account for the new load balancer port (4432). This is not ideal, but it is working for now.

**Comment by perrefe** [comment]
Hi,

I'm having exactly the same issue here (well, not exacly because I'm on premise), I'm terminating SSL with my own nginx ands proxy passing to plain http k3s nginx ingress controller and rancher is redirecting me to https so I'm having a recursive loop.

Here is my ingress manifest:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    meta.helm.sh/release-name: rancher
    meta.helm.sh/release-namespace: cattle-system
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  generation: 4
  labels:
    app: rancher
    app.kubernetes.io/managed-by: Helm
    chart: rancher-2.5.9
    heritage: Helm
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  ingressClassName: nginx
  rules:
  - host: rancher.xxx.xx
    http:
      paths:
      - backend:
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - rancher.xxx.xx
    secretName: tls-rancher-ingress
```

I'm still trying a good workaround but no luck for now.

Also, if I try to access to rancher service NodePort with target port 80, it redirects the request to the https NodePort.

```
 curl -i http://rancher.xxx.xx:32080
HTTP/1.1 302 Found
Date: Thu, 09 Sep 2021 21:57:29 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 57
Connection: keep-alive
Location: https://rancher.xxx.xx:32443/

<a href="https://rancher.xxx.xx:32443/">Found</a>.
```
