### ISSUE TITLE
ReplicationController is missing some required fields in rancher UI -- fails to deploy with default required fields

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33051]
**What kind of request is this (question/bug/enhancement/feature request):**
* bug

**Steps to reproduce (least amount of steps as possible):**
* go to dashboard
* search for `repicationController` -> select it
* click `create`
* fill in required fields

**Result:**
* Request returns an error, user is unable to create the replicationController
```
ReplicationController in version "v1" cannot be handled as a ReplicationController: v1.ReplicationController.Spec: v1.ReplicationControllerSpec.Selector: ReadString: expects " or n, but found {, error found in #10 byte of ...|hLabels":{"workload.|..., bigger context ...|},"spec":{"replicas":1,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"replic|...
```

**Other details that may be helpful:**
if you `create` -> `edit as yaml` and copy the [default K8s template for replication controllers](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/), it works fine 
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (772ef96)
- Installation option (single install/HA):single
