### ISSUE TITLE
[UI] Project stuck on "Cluster not ready" after failed monitoring app installation.

### ISSUE THREAD

**Issue by alvaromlg** [rancher/rancher#33104]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

We have upgraded to rancher 2.5.5 and we have stopped using rancher cluster manager monitoring and replaced it with cluster explorer monitoring as suggested from this warning.

> Monitoring in Cluster Manager has been deprecated as of Rancher v2.5.0 - check out the FAQ. The updated version of monitoring in Cluster Explorer Apps and Marketplace is currently deployed.

We first disabled rancher cluster manager monitoring and then we installed the monitoring app through cluster explorer.

The monitoring app installation initially failed (I think this is what caused the inconsistency) and the project became "Cluster not ready" on the GUI as you can see on the attached picture.

![Captura de pantalla de 2021-06-09 15-45-56](https://user-images.githubusercontent.com/2621635/121366466-cdeb4980-c939-11eb-8d60-af912afd708a.png)

That happened only on project level, not cluster level. We also tried to reproduce it on our staging cluster but installation there went correctly and we didnt have any issue on the project not being accessible.

We also retried the installation on the production cluster and it was successful the second time but unfortunately it didnt clear the "Cluster not ready" message.

This is only affecting to one of the projects from the cluster, other cluster's projects are accessible and we can also access this affected project directly with the url, looks like it's just a GUI bug, cluster is ready and ok.

**Steps to reproduce (least amount of steps as possible):**
We could only reproduce the issue once.

Having rancher 2.4, upgrade it to rancher 2.5, disable rancher cluster manager monitoring and install rancher explorer monitoring.

**Result:**
One of the cluster's project might become stuck on "Cluster not ready" even though the cluster is ok and you can access the projects directly knowing the url.

**Other details that may be helpful:**
We had a server issue that might have affected the first installation by not letting prometheus to correctly create the volumes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.5
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
19.03.5
```

**Comment by alvaromlg** [comment]
I have fixed the issue with the next steps:

First I inspected the project yaml:

`kubectl get projects.management.cattle.io -n cluster project -o yaml > backup.yaml`

As I suspected the status was stuck on failed to update

```
status:
  conditions:
  - lastUpdateTime: "2019-06-19T06:51:09Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2019-06-19T06:51:09Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2019-06-19T06:51:09Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2019-06-19T06:51:09Z"
    status: "True"
    type: MetricExpressionDeployed
  - lastUpdateTime: "2021-06-03T06:33:11Z"
    reason: Error
    status: "False"
    type: MonitoringEnabled
  monitoringStatus:
    conditions:
    - lastUpdateTime: "2021-06-03T06:33:11Z"
      status: "False"
      type: PrometheusDeployed
    - lastUpdateTime: "2021-06-03T06:33:11Z"
      status: "False"
      type: GrafanaDeployed
  podSecurityPolicyTemplateId: ""
```

First I tried removing only the monitoringStatus block, but it didnt work. I removed it anyway because monitoring is on cluster explorer not on cluster manager anymore and it doesnt have sense to have it there anymore.

Then I removed last error status block:
```
  - lastUpdateTime: "2021-06-03T06:33:11Z"
    reason: Error
    status: "False"
    type: MonitoringEnabled
```
And now the project is accessible.

I think rancher should have some way to refresh/update project status. I also think it may be possible to reproduce the issue by updating the project metadata status to "unkown" or "error" and then it will get stuck there.
