### ISSUE TITLE
Introduce support for IP dual-stack 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#33107]
Feature gate `IPv6DualStack` for IPv4/IPv6 dual-stack networking is enabled by default for 1.21 kubernetes cluster. But cluster needs to meet a few requirements and configurations before it works correctly. 

So we're going to disable the feature flag by default in Rancher 2.6, k8s 1.21. In order to support this, we need to validate prerequisites and configure the command args to kubernetes components in RKE. 

Refer to https://kubernetes.io/docs/concepts/services-networking/dual-stack/ for more details.

**Comment by SheilaghM** [comment]
We switched it off - this ask is to turn it back on and verify that it works.

**Comment by kinarashah** [comment]
k8s upstream enables this feature gate by default, so the idea is to leave it as is once #33085 is fixed. 

So now there's no need to introduce a field/flag to enable/disable it. 
For better user experience, we'll validate the flags passed for IPv6DualStack with networking requirements (similar to how k3s/kubeadm implements it `https://github.com/k3s-io/k3s/pull/3212`) and error out if cluster's not configured correctly. 

Otherwise we'll default to ipv4 and nothing should error out.

**Comment by superseb** [comment]
To test this:

- It should only work on Calico, selecting a different CNI should error
- We only successfully tested this on AWS EC2, with the following prerequisites:
  - Add IPv6 default gateway to VPC routes
  - Disable source/destination checks on all EC2 instances in the cluster
- Use the configuration below:

```
kubernetes_version: "v1.21.1-rancher2-1"
services:
  kube-api:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
  kube-controller:
    service_cluster_ip_range: 10.43.0.0/16,fd98::/108
    cluster_cidr: 10.42.0.0/16,fd01::/64

network:
  plugin: calico
```

Commands that can be used:

```
kubectl create deployment nginx --image=nginx --replicas=5
# IPv4 + IPv6 pod addresses
kubectl get pods -l app=nginx -o jsonpath='{range .items[*]}{@.status.podIPs[0].ip}{@.status.podIPs[1].ip}{" "}{@.spec.nodeName}{"\n"}{end}'
```

And the adjusted overlay check script for IPv6:

```
#!/bin/sh
cat <<EOF | kubectl create -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: overlaytest
spec:
  selector:
      matchLabels:
        name: overlaytest
  template:
    metadata:
      labels:
        name: overlaytest
    spec:
      tolerations:
      - operator: Exists
      containers:
      - image: busybox:1.28
        imagePullPolicy: Always
        name: busybox
        command: ["sh", "-c", "tail -f /dev/null"]
        terminationMessagePath: /dev/termination-log
EOF

kubectl rollout status ds/overlaytest -w

echo "=> Start network overlay test"; kubectl get pods -l name=overlaytest -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.nodeName}{"\n"}{end}' | while read spod shost; do kubectl get pods -l name=overlaytest -o jsonpath='{range .items[*]}{@.status.podIPs[1]}{" "}{@.spec.nodeName}{"\n"}{end}' | while read tip thost; do kubectl --request-timeout='10s' exec $spod -- /bin/sh -c "ping -c2 $tip > /dev/null 2>&1"; RC=$?; if [ $RC -ne 0 ]; then echo $shost cannot reach $thost; fi; done; done; echo "=> End network overlay test"
```

The network requirement (and I assume the reason it only works on AWS EC2), is  based on the comment from Calico Slack:

```
For IPv6, calico assigns /128s to pods from IP pools just like IPv4.  We don't currently support any kind of overlay for IPv6 so you need to peer with your fabric over BGP to advertise out the routes.  We don't currently support borrowing IPs from the host's subnet.
As with IPv4, Calico assigns IPs to hosts in blocks and those are then sub-divided into /128s for the individual pods.
You can use multiple IP pools to assign different IP ranges to different groups of pods.
```
