### ISSUE TITLE
Manually created duplicate rolebindings are not cleaned up when Rancher is upgraded to 2.5.8

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33144]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Before upgrade rancher version: v2.5.6
After rancher upgrade version: v2.5.8

1. On v2.5.6, create a node driver DO cluster with 3 nodes with 1 role in each of the nodes (cp, worker, etcd)
2. Create a user1 from global --> security --> users
3. Create a project P1 in the cluster created above and add user1 as a project owner and project member in P1.
4. By executing the command grab the role template of the role binding for the above user for project member

```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
 labels:
  "cattle.io/creator": norman
  "p-krzs2_prtb-vpn2999": "membership-binding-owner"
 name: "rolebinding-k48nc"
 namespace: "c-gh6nj"
roleRef:
 apiGroup: "rbac.authorization.k8s.io"
 kind: Role
 name: "p-krzs2-projectmember"
subjects:
- apiGroup: "rbac.authorization.k8s.io"
  kind: User
  name: "u-9bj7w"
```
5. Create 10k duplicates for the above rb by changing the name ` name: "rolebinding-k48nc"`
6. verify the number of duplicates created are more than or equal to 10k 
7.  Upgrade rancher server to the version v2.5.8, and the manually created duplicates are not deleted:

From Rancher server logs:
```
2021/06/10 21:15:54 [INFO] Total PRTB duplicate clusterRoleBindings 1, roleBindings 6
2021/06/10 21:15:54 [INFO] Done Duplicate CRB and RB cleanup
2021/06/10 21:15:54 [INFO] Rancher startup complete
```

Duplicates on the cluster:
```
DEBU[0000] rb: kube-system/system::leader-locking-kube-scheduler has multiple subjects
DEBU[0001] crb: /system:public-info-viewer has multiple subjects
DEBU[0001] groups of duplicate role bindings: 1
DEBU[0001] total duplicate role bindings: 10436
DEBU[0001] no dupe crbs found
```

**Result:**
The duplicates that were created manually should be deleted

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Kubernetes version (use `kubectl version`): v1.20.6

**Comment by anupama2501** [comment]
Reproduced the issue when upgraded from v2.5.6 to master-head 5715b8a

1. On v2.5.6 rancher server, created a node driver EC2 cluster with 1 cp, 1 worker, 1 etcd nodes and create a user u1 from global --> users
2. Create a project P1 in the cluster once it is active, and add the user to this project as project member and project owner
3. Create 10k duplicates from the below yaml file by the command `kubectl apply -f copy_crb.yaml`
```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
 labels:
  "cattle.io/creator": norman
  "p-8h7b5_prtb-zjmzr": "membership-binding-owner"
 name: "test"
 namespace: "c-m8gdc"
roleRef:
 apiGroup: "rbac.authorization.k8s.io"
 kind: Role
 name: "p-8h7b5-projectowner"
subjects:
- apiGroup: "rbac.authorization.k8s.io"
  kind: User
  name: "u-9shnc"
```
4. Verify 10k duplicates exists in the rancher before the upgrade to master-head:
```
DEBU[0000] running deduperbs command
DEBU[0000] kubeConfig: kubeconfig.yaml
DEBU[0000] using kubeconfig: kubeconfig.yaml
DEBU[0000] rb: kube-system/system::extension-apiserver-authentication-reader has multiple subjects
DEBU[0000] rb: kube-system/system::leader-locking-kube-controller-manager has multiple subjects
DEBU[0000] rb: kube-system/system::leader-locking-kube-scheduler has multiple subjects
DEBU[0001] crb: /system:public-info-viewer has multiple subjects
DEBU[0001] groups of duplicate role bindings: 1
DEBU[0001] total duplicate role bindings: 10008
DEBU[0001] no dupe crbs found
```

5. Upgrade the rancher server to the version master-head 5715b8a
6. While the rancher is coming up, verify the logs as below:
```
2021/06/14 23:41:57 [INFO] Calling Duplicate CRB and RB cleanup
2021/06/14 23:41:57 [INFO] Starting bindings cleanup
 range_end:\"/registry/rolebindings0\" " with result "range_response_count:10127 

2021/06/14 23:43:26 [INFO] Total PRTB duplicate clusterRoleBindings 1, roleBindings 10008
2021/06/14 23:43:27 [INFO] Done Duplicate CRB and RB cleanup
2021/06/15 00:36:04 [INFO] Total PRTB duplicate clusterRoleBindings 0, roleBindings 0
2021/06/15 00:36:04 [INFO] Done Duplicate CRB and RB cleanup
```
But on the rancher server we see the duplicates are present:
```
DEBU[0001] crb: /system:public-info-viewer has multiple subjects
DEBU[0001] groups of duplicate role bindings: 1
DEBU[0001] total duplicate role bindings: 10008
DEBU[0001] no dupe crbs found
```
sample `kubectl rolebindings -A` result:

```
c-m8gdc                                      test9800                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9801                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9802                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9803                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9804                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9805                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9806                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9807                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9808                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9809                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test981                                             Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9810                                            Role/p-8h7b5-projectowner                             15h
c-m8gdc                                      test9811                                            Role/p-8h7b5-projectowner                             15
```
