### ISSUE TITLE
Why terminating pod is ready to accept incoming traffic?

### ISSUE THREAD

**Issue by rafis** [rancher/rancher#33143]
During rolling update I got strange behaviour with Rancher while I have never got this with any other Kubernetes:

workpc:~/project1 $ kubectl -n project1 get pods
NAME                                                 READY   STATUS        RESTARTS   AGE
project1-postgresql-0                                    1/1     Running       4          20d
project1-web-85976f74d4-bz5vx                            1/1     Running       0          3m22s
project1-web-59456ddcb6-94zlb                            1/1     Terminating   1          12d

In the READY column the terminating pod has 1/1, while other Kubernetes cluster usually have 0/1 on Terminating state.

I haven't touched rolling update configuration:
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```
