### ISSUE TITLE
RKE2 Nodes stuck in Deleting state in Machines list after a successful removal from backend

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#33197]
After successful Azure RKE2 cluster removal from `rancher/rancher:master-head 66c31dd` all nodes are still present in `Cluster Management -> Advanced -> Machines` list. 

Almost all resources are deleted from Azure apart used `Resource Group` and `Availability Set` which comes from `Availability Set (unmanaged)` field so it is probably expected that it will stay in place.

This is how it looks:
![machines-deleting](https://user-images.githubusercontent.com/12828077/122059440-ebfaf300-cdec-11eb-8554-61855fd2d2dd.png)
Note: Machines from `thehejik-azure-rke2-1211` are from cluster which failed to provision (wrong region or something like that), machines from `thehejik-rke2-az` are from working cluster  which has been deleted from rancher.

[yaml from working node on cluster thehejik-rke2-az](https://github.com/rancher/dashboard/files/6655869/thehejik-rke2-az-thehejik-master-6477d568c9-wf6z5.yaml.txt)
[yaml from failed node on cluster thehejik-azure-rke2-1211](https://github.com/rancher/dashboard/files/6655946/thehejik-azure-rke2-1211-thehejik-worker-64fcf7db48-thjnt.yaml.txt)

**Comment by sowmyav27** [comment]
Notice this issue ona DO RKE2 cluster also - on master-head commit id: `65e625a `
Node config/yaml of the deleting mahcine
```
conditions:
  - lastTransitionTime: "2021-06-16T04:48:21Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-06-16T04:18:11Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-06-16T04:48:21Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: InfrastructureReady
  - lastTransitionTime: "2021-06-16T04:48:20Z"
    reason: Deleting
    severity: Info
    status: "False"
    type: NodeHealthy
  - lastTransitionTime: "2021-06-16T04:48:20Z"
    status: "True"
    type: PreTerminateDeleteHookSucceeded
  - lastTransitionTime: "2021-06-16T04:19:29Z"
    message: plan applied
    reason: InSync
    severity: Info
    status: "True"
    type: Provisioned
```
