### ISSUE TITLE
Convoy Gluster Container degraded with custom GlusterFS Stack

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#3319]
If I deploy from Rancher Catalog the GlusterFS + Convoy GlusterFS, everything works fine. But, if I try to deploy Convoy GlusterFS + a custom GlusterFS stack, it trows the bellow error. It isn't related to the scheduler.affinity, beucase I've made a test without it and the error persists.

It seems that Convoy GlusterFS **only** works with GlusterFS deployed from official rancher catalog... 

``` bash
1/18/2016 2:58:55 PMWaiting for metadata.time="2016-01-18T16:58:55Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2541/ns/mnt -F -- /var/lib/docker/overlay/97baf3aa4e91c15bb47cee03cb804e0d3f5ecd7346a1ed4198b2090fb04ecc62/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd -- /launch volume-agent-glusterfs-internal]"
1/18/2016 2:58:55 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_glusterfs glusterfs.servers=glusterfs]"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=info msg="Got: drivers [glusterfs]"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --driver-opts=glusterfs.defaultvolumepool=datastore_glusterfs --driver-opts=glusterfs.servers=glusterfs --root=/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd --drivers=glusterfs]"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd" pkg=daemon
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_glusterfs glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:58:55 PMtime="2016-01-18T16:58:55Z" level=debug msg="Volume datastore_glusterfs is being mounted it to /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs, with option [-t glusterfs]" pkg=util
1/18/2016 2:58:56 PMtime="2016-01-18T16:58:56Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/18/2016 2:58:56 PMtime="2016-01-18T16:58:56Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:58:56 PM{
1/18/2016 2:58:56 PM    "Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:58:56 PM}
1/18/2016 2:58:56 PMtime="2016-01-18T16:58:56Z" level=info msg="convoy exited with error: exit status 1"
1/18/2016 2:58:56 PMtime="2016-01-18T16:58:56Z" level=info msg=Exiting.
1/18/2016 2:59:01 PMWaiting for metadata.time="2016-01-18T16:59:01Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2541/ns/mnt -F -- /var/lib/docker/overlay/97baf3aa4e91c15bb47cee03cb804e0d3f5ecd7346a1ed4198b2090fb04ecc62/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd -- /launch volume-agent-glusterfs-internal]"
1/18/2016 2:59:01 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=info msg="Got: drivers [glusterfs]"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_glusterfs glusterfs.servers=glusterfs]"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=datastore_glusterfs --driver-opts=glusterfs.servers=glusterfs]"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd" pkg=daemon
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_glusterfs glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:01 PMtime="2016-01-18T16:59:01Z" level=debug msg="Volume datastore_glusterfs is being mounted it to /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs, with option [-t glusterfs]" pkg=util
1/18/2016 2:59:02 PMtime="2016-01-18T16:59:02Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/18/2016 2:59:02 PMtime="2016-01-18T16:59:02Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:02 PMtime="2016-01-18T16:59:02Z" level=info msg="convoy exited with error: exit status 1"
1/18/2016 2:59:02 PMtime="2016-01-18T16:59:02Z" level=info msg=Exiting.
1/18/2016 2:59:02 PM{
1/18/2016 2:59:02 PM    "Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:02 PM}
1/18/2016 2:59:08 PMWaiting for metadata.time="2016-01-18T16:59:08Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2541/ns/mnt -F -- /var/lib/docker/overlay/97baf3aa4e91c15bb47cee03cb804e0d3f5ecd7346a1ed4198b2090fb04ecc62/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd -- /launch volume-agent-glusterfs-internal]"
1/18/2016 2:59:08 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="Got: drivers [glusterfs]"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_glusterfs glusterfs.servers=glusterfs]"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=datastore_glusterfs --driver-opts=glusterfs.servers=glusterfs]"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd" pkg=daemon
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_glusterfs glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=debug msg="Volume datastore_glusterfs is being mounted it to /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs, with option [-t glusterfs]" pkg=util
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:08 PM{
1/18/2016 2:59:08 PM    "Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:08 PM}
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg="convoy exited with error: exit status 1"
1/18/2016 2:59:08 PMtime="2016-01-18T16:59:08Z" level=info msg=Exiting.
1/18/2016 2:59:14 PMWaiting for metadata.time="2016-01-18T16:59:14Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2541/ns/mnt -F -- /var/lib/docker/overlay/97baf3aa4e91c15bb47cee03cb804e0d3f5ecd7346a1ed4198b2090fb04ecc62/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd -- /launch volume-agent-glusterfs-internal]"
1/18/2016 2:59:14 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="Got: drivers [glusterfs]"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_glusterfs glusterfs.servers=glusterfs]"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=datastore_glusterfs --driver-opts=glusterfs.servers=glusterfs]"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd" pkg=daemon
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_glusterfs glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=debug msg="Volume datastore_glusterfs is being mounted it to /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs, with option [-t glusterfs]" pkg=util
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:14 PM{
1/18/2016 2:59:14 PM    "Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:14 PM}
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg="convoy exited with error: exit status 1"
1/18/2016 2:59:14 PMtime="2016-01-18T16:59:14Z" level=info msg=Exiting.
1/18/2016 2:59:20 PMWaiting for metadata.time="2016-01-18T16:59:20Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/2541/ns/mnt -F -- /var/lib/docker/overlay/97baf3aa4e91c15bb47cee03cb804e0d3f5ecd7346a1ed4198b2090fb04ecc62/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd -- /launch volume-agent-glusterfs-internal]"
1/18/2016 2:59:20 PMRegistering convoy socket at /var/run/conoy-convoy-gluster.sock
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="Listening for health checks on 0.0.0.0:10241/healthcheck"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="Got: root /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="Got: drivers [glusterfs]"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="Got: driver-opts [glusterfs.defaultvolumepool=datastore_glusterfs glusterfs.servers=glusterfs]"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="Launching convoy with args: [--socket=/host/var/run/conoy-convoy-gluster.sock daemon --root=/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd --drivers=glusterfs --driver-opts=glusterfs.defaultvolumepool=datastore_glusterfs --driver-opts=glusterfs.servers=glusterfs]"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=debug msg="Creating config at /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd" pkg=daemon
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=debug msg= driver=glusterfs driver_opts=map[glusterfs.defaultvolumepool:datastore_glusterfs glusterfs.servers:glusterfs] event=init pkg=daemon reason=prepare root="/var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=debug msg="Volume datastore_glusterfs is being mounted it to /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs, with option [-t glusterfs]" pkg=util
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=debug msg="Cleaning up environment..." pkg=daemon
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:20 PM{
1/18/2016 2:59:20 PM    "Error": "Failed to execute: mount [-t glusterfs glusterfs:/datastore_glusterfs /var/lib/rancher/convoy/convoy-gluster-027bc516-cfda-4ae9-887e-0fd7f2af5afd/glusterfs/mounts/datastore_glusterfs], output Mount failed. Please check the log file for more details.\n, error exit status 1"
1/18/2016 2:59:20 PM}
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg="convoy exited with error: exit status 1"
1/18/2016 2:59:20 PMtime="2016-01-18T16:59:20Z" level=info msg=Exiting.
```

This is my custom GlusterFS stack:

docker-compose.yml

``` yaml
glusterfs-volume-create:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.service.hash: 8241a6e1aff83756d3a011a6eb51a4d07233bef9
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: glusterfs=true
  command:
  - /opt/rancher/replicated_volume_create.sh
  image: rancher/glusterfs:v0.1.3
  volumes_from:
  - glusterfs-data
  net: container:glusterfs-server
glusterfs-data:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.service.hash: f4d07cb897b9dc1aeeabf72237e58d1323319665
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: glusterfs=true
  command:
  - /bin/true
  image: rancher/glusterfs:v0.1.3
  volumes:
  - /var/run
glusterfs-server:
  labels:
    io.rancher.sidekicks: glusterfs-peer,glusterfs-data,glusterfs-volume-create
    io.rancher.service.hash: dcf6e4993347614cd50edc09552cb420e7cf4f3c
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: glusterfs=true
  command:
  - glusterd
  - -p
  - /var/run/gluster.pid
  - -N
  image: rancher/glusterfs:v0.1.3
  volumes_from:
  - glusterfs-data
  cap_add:
  - SYS_ADMIN
glusterfs-peer:
  labels:
    io.rancher.service.hash: 0b43835fcd1acb04a250665ddb8346de892d7c52
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: glusterfs=true
  command:
  - /opt/rancher/peerprobe.sh
  image: rancher/glusterfs:v0.1.3
  volumes_from:
  - glusterfs-data
  net: container:glusterfs-server
```

rancher-compose.yml

``` yaml
glusterfs-volume-create:
  scale: 1
  metadata: &id001
    io.rancher.service.hash: b8db0dc8ddf6daac5170b75c629ce10a64a4a943
    volume_name: datastore_glusterfs
glusterfs-data:
  scale: 1
  metadata: *id001
glusterfs-server:
  scale: 1
  metadata: *id001
glusterfs-peer:
  scale: 1
  metadata: *id001
```

This is the Convoy GlusterFS stack deployed from catalog:

docker-compose.yml

``` yaml
convoy-gluster-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.service.hash: b83fa513ee2cbb1f41bff4c2a578e52d97e5b29e
    io.rancher.scheduler.affinity:host_label_soft: convoy.glusterfs=true
  command:
  - storagepool-agent
  image: rancher/convoy-agent:v0.1.2
convoy-gluster:
  external_links:
  - glusterfs/glusterfs-server:glusterfs
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.service.hash: 22b447683742ed243fdd896fe2d0a00426b47676
    io.rancher.scheduler.affinity:host_label_soft: convoy.glusterfs=true
  command:
  - volume-agent-glusterfs
  image: rancher/convoy-agent:v0.1.2
  privileged: true
  volumes:
  - /lib/modules:/lib/modules:ro
  - /proc:/host/proc
  - /var/run:/host/var/run
  - /etc/docker/plugins:/etc/docker/plugins
```

rancher-compose.yml

``` yaml
convoy-gluster-storagepool:
  scale: 1
  health_check:
    port: 10241
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    request_line: GET /healthcheck HTTP/1.0
    healthy_threshold: 2
  metadata:
    io.rancher.service.hash: 01d8e9c645e283126a39d9043e4acfbbbb90548a
convoy-gluster:
  health_check:
    port: 10241
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    request_line: GET /healthcheck HTTP/1.0
    healthy_threshold: 2
  metadata:
    io.rancher.service.hash: fc2b1ca4c4d9ca86247c2fa8568ea4b3fe776a30
    volume_pool: datastore_glusterfs
```
