### ISSUE TITLE
 rke2 HA single node DO has machine stuck in Waiting for infra but the cluster shows active status

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33228]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
 1. Create an rke2 DO cluster single node all role on rancher HA self-signed server. 
 2. After sometime the cluster becomes active but the machine in the cluster management page --> Advanced --> Machines is stuck in `Waiting for Infra` and has the Phase `Provisioning`

**Expected Result:**
The machine should have come active and should not be stuck in `waiting for infra` or the cluster if the node is stuck in `waiting for infra` should not show active status

**Other details that may be helpful:**

- Single node rke2 node driver works on single install setup. Issue is only seen on HA
- Node is created in the digital ocean droplets.
- This happens on Azure rke2 node driver 1 node all roles as well.

If we navigate to ember UI, the cluster shows 2 nodes in the node page instead of 1 which are duplicates to each other.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head 479795f
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Node driver
- Kubernetes version (use `kubectl version`):
 
```
v1.21.1-rc3+rke2r1
```

**Comment by thehejik** [comment]
Same experience with `rancher:master-head abeea84` today on RKE2 DO singlenode cluster.

Cluster is `Active` and node is in `Waiting for Infra` state.

This is strip of machine.yaml from the affected machine - I don't see anything suspicious there:

```
...
status:
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2021-06-18T13:10:44Z"
    message: 1 of 2 completed
    reason: WaitingForInfrastructure
    severity: Info
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-06-18T13:10:44Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-06-18T13:10:44Z"
    reason: WaitingForInfrastructure
    severity: Info
    status: "False"
    type: InfrastructureReady
  - lastTransitionTime: "2021-06-18T13:10:44Z"
    reason: WaitingForNodeRef
    severity: Info
    status: "False"
    type: NodeHealthy
  - lastTransitionTime: "2021-06-18T13:12:08Z"
    message: plan applied
    reason: InSync
    severity: Info
    status: "True"
    type: Provisioned
  infrastructureReady: false
  lastUpdated: "2021-06-18T13:10:44Z"
  observedGeneration: 2
  phase: Provisioning
```
