### ISSUE TITLE
Fleet Deploy: cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by danielbjornadal** [rancher/rancher#33274]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Add Git Repo with any YAML Resource.

**Result:**
cannot re-use a name that is still in use
`level=error msg="error syncing 'cluster-fleet-default-c-cm6h8-408d830136ab/mqn-deps': handler bundle-deploy: cannot re-use a name that is still in use, requeuing"`

YAML can be deployed without any issue using kubectl.

**Environment information**
- Rancher version: v2.5.7
- Installation option: HA

- Docker version: 20.10.7
- Kubernetes version: 1.20.6

![image](https://user-images.githubusercontent.com/7441428/122543294-eb9c6b00-d02b-11eb-936e-2b1a96636f20.png)

YAML:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  use-forwarded-headers: "true"
  use-http2: "false"
  use-proxy-protocol: "true"
```
