### ISSUE TITLE
rke2 cluster templates: Unable to deploy other v2 charts (i.e. monitoring) using the template

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#33339]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy a rancher setup
* add some rke2 template(s) to your rancher setup that allow monitoring to be enabled (the example repo has this option)
* use said template to deploy a cluster
  * enable monitoring through the template
  * ensure the cluster has enough resources to deploy monitoring

**Result:**
monitoring fails to install with error 
```
ErrApplied(1) [Cluster fleet-default/ctw-cluster2-xyz: error while running post render on files: invalid cluster scoped object [name=rancher-monitoring-crd-manager kind=PodSecurityPolicy apiVersion=policy/v1beta1] found, consider using "defaultNamespace", not "namespace" in fleet.yaml]
```

**Expected Result:**
* monitoring should install without issue when installing via rke2 templates

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head (51d074b202ee3445bb87b827fc1f06f5a66627ff)
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke2 template, Digital Ocean 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4vCPU, 3nodes
- Kubernetes version (use `kubectl version`): v1.21.1-rc3+rke2r1

**Comment by gray314** [comment]
Hello!
we have also the same issue with deploy the v2 app's CPI, CSI Helm charts via rke2 template.
we found that the values from 'chartValues' key from the values.yaml are not passed to the template and little modified the file [cluster.yaml](https://github.com/rancher/cluster-template-examples/blob/main/charts/templates/cluster.yaml) at chart templates - add the key 'chartValues:' in 'rkeConfig:'  (how is this done when a cluster is created via a form in the Rancher UI)

but this not helped... :(

````yaml
.....
#charts/templates/cluster.yaml
  rkeConfig:
    # specify rancher helm chart values deployed into downstream cluster
    {{- if .Values.rke.chartValues }}
    chartValues:
{{ toYaml .Values.rke.chartValues | indent 8 }}
    {{- end }}
....

#charts/values.yaml
.....
# specify rancher helm chart values deployed into downstream cluster
  chartValues:
    rancher-vsphere-cpi:
      vCenter:
        datacenters: MSK-********
        host: vcenter.********
        password: ********
        username: ********
    rancher-vsphere-csi:
      storageClass:
        datastoreURL: ds:///vmfs/volumes/********
        name: vsphere-csi-storage
        storagePolicyName: SSD ********
      vCenter:
        datacenters: MSK-********
        host: vcenter.********
        password: ********
        username: ********
    rke2-calico: {}
....
````

Rancher version - v2.6.5
k8s version - v1.23.7+rke2r2
CloudProvider - vSphere

ps. when a cluster with vSphere cloudProvider is created through a form in the Rancher UI - there are no problems - app's CPI and CSI are installed successfully and working
