### ISSUE TITLE
[Logging v2] Upgrade to upstream 3.12.0

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#33462]

**Comment by izaac** [comment]
This needs validating the P0 QA scenarios. 
Also this would need validation of the rancher-images and rancher-win-images txt files once a 2.6 RC is available.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (07/14/2021)` _58f6425_
I covered `rke2` and `k3s` as part of this other issue: https://github.com/rancher/rancher/issues/33463

**Comment by izaac** [comment]
Rancher version `2.6 master-head (07/14/2021)` _8073489_

P0 tests done for the following cluster types:

- AKS 1.20.7
- EKS 1.20.7
- RKE 1.20.7
- GKE 1.20

Moving to Waiting for RC to follow up the images validations on alphas/RCs

**Comment by deniseschannon** [comment]
Available to test with v2.6.0-rc1

**Comment by izaac** [comment]
Rancher version: `2.6.0-rc2`
Repo info:

```
spec:
  gitBranch: dev-v2.6
  gitRepo: https://git.rancher.io/charts
status:
  branch: dev-v2.6
  commit: abcc294eed065e8dec10a1757ed9dd5f808d15f4
```

The chart install works as expected on an Airgap HA setup with private registry. (RKE1)
