### ISSUE TITLE
Which type to assign "objects" or arrays in questions.yaml?

### ISSUE THREAD

**Issue by exocode** [rancher/rancher#33485]
**What kind of request is this (question/bug/enhancement/feature request):**

## FEATURE

**Steps to reproduce (least amount of steps as possible):**

I have a Helm chart with something like this: 

```yaml
  clusterRoleBinding:
    labels: {}
    annotations: {}

```

I wanna create a `questions.yml` like this.

with content 

```yaml
  - variable: manager.clusterRoleBinding.labels
    group: "ClusterRoleBinding"
    label: ClusterRoleBinding labels
    description: "Additional labels for ClusterRoleBinding resource"
    default: {}
    type: string   <<<<<<----- WHAT TYPE SHOULD I PUT HERE ????
  - variable: manager.clusterRoleBinding.annotations
    group: "ClusterRoleBinding"
    label: ClusterRoleBinding annotations
    description: "Additional annotations for ClusterRoleBinding resource"
    default: {}

```

When I assign `string` I get this: `"{}"`

I didn't found any type like `array` or `object` in the docs https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/creating-apps/#question-variable-reference

What is the right approach for objects?

Or should I keep them out of `questions.yml`?
