### ISSUE TITLE
[Backport] Removing in-tree vSphere vCenter server entries does not propagate

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33491]
Backport of https://github.com/rancher/rancher/issues/27306

**Comment by rawmind0** [comment]
Submitted PR https://github.com/rancher/rancher/pull/33510 to backport fix

**Comment by SheilaghM** [comment]
@rawmind0 - since this is a backport, would you please merge it so QA can validate?

**Comment by rawmind0** [comment]
@SheilaghM , it was being reviewed, just approved 2 hours ago. Merged

**Comment by anupama2501** [comment]
Verified on v2.4-head `9fdf6824a`

1. Created a vsphere node driver cluster with 3 nodes 1 role each
2. Added the following in tree cloud provider config:
```
 cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      virtual_center:
        host1:
          user: u***
          password:***
          datacenters: /***
       host2:
          user: u***
          password: ***
          datacenters: /***
      workspace:
        server: host1
        folder: /***
        default-datastore: /***
        datacenter: /***
        resourcepool-path: ***/anupama
```
3. Edited the config via API and added a vcenter host3 by removing the host2 from config above.
```
       host3:
          user: u***
          password: ***
          datacenters: /***
```
4. Verified the host2 was removed and host3 was added from the configs in the /etc/kubernetes/cloud-config, on the UI and in the API.
```
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"


[VirtualCenter "wrangler.fremont.rancherlabs.com"]
        user = "u***"
        password = ""
        datacenters = "/***"
        soap-roundtrip-count = "0"
[VirtualCenter "host3"]
        user = "u***"
        password = ""
        datacenters = "***"
        soap-roundtrip-count = "0"
[VirtualCenter "host2"]
        user = "u***"
        password = ""
        datacenters = "***"
        soap-roundtrip-count = "0"

[Workspace]
        server = "host1"
        datacenter = "/***"
        folder = "/RNCH-HE-FMT/vm/"
        default-datastore = "/***"
        resourcepool-path = "/***/anupama"
```
5. Re-edited the config via API by removing the newly added config in step2
6. Cluster went into updating state and kube-api restarted
7. Verified the cloud config in the API, UI and /etc/kubernetes/cloud-config reflected the correct vcenter.
