### ISSUE TITLE
Rancher request - remove unhealthy hosts automatically

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3354]
I have noticed that whenever you have an "unhealthy host" for your environment, rancher refuses to start any new containers (even on new healthy hosts) until that host becomes healthy and or manually removed. 
This causes an issue with autoscaling. 
I can set  a container to "global" scaling, and autoscaling up will work great, but I can not autoscale down because then the host that gets autoscaled (through AWS) away, becomes "unhealthy" in rancher, and all the sudden the environment wont start any more containers unless I go manually remove the host. A common scenario is when trying to replace hosts with new hosts. 

It would be great if rancher could automatically remove/delete unhealthy hosts (maybe by some threshold I define)

**Comment by deniseschannon** [comment]
What do you mean by "refuses to start any new containers"? If your host becomes unhealthy AND it has a heath check on it, Rancher should be re-scheduling the containers on the unhealthy host onto a healthy host. Without the health check, Rancher will not schedule any new containers of existing services.

With a global scale. if you added another host, it should automatically start containers of the service onto any newly added hosts. Having an unhealthy host shouldn't affect that deployment. 

By design, Rancher is not planning to remove unhealthy hosts automatically, there are too many variables that could have caused the host to become unhealthy and we want the users to look into those issues to either reconcile what's wrong to get hte host healthy or determine to remove the host themselves.

**Comment by nhumrich** [comment]
How do add a health-check to a host? I wasn't aware you could do that. 

Also you say "With a global scale. if you added another host, it should automatically start containers of the service onto any newly added hosts. Having an unhealthy host shouldn't affect that deployment. " but that isnt what happens. If I terminate an ec2 host, it becomes unhealthy, autoscaling brings up another, and the new one has 0 containers on it. As soon as I delete the unhealthy one, the "global scale" containers start to go up on the new one, but not until I delete it. 

I understand not remove unhealthy hosts by default. I also like the idea of moving containers onto a healthy host if the host isnt responding, but currently that doesnt happen. If it did, that would be expectable, then I could just go delete the old ones every once in a while.

**Comment by deniseschannon** [comment]
Here's the health checks information in the UI.
http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-services/#health-checks

Concepts of Rancher:
http://docs.rancher.com/rancher/concepts/health-checks/

Can you share your docker-compose.yml for your global service? Do you have any host labels to select which hosts or is any host in your environment? 

I just ran this test. Had 5 hosts in my environment and used a global scale with no scheduling rules. Terminated 1 of my hosts in AWS so that it caused the host to go into reconnecting state. Added a different host into my Rancher setup. As soon as it joined Rancher, the container from the global service started on the new host.

**Comment by nhumrich** [comment]
I thought you meant there was a way to do a health check on the host. I am already doing service health checks. When i did the test, I had just one host. I terminated it, and let autoscaling create another. Here is the docker compose:

```
docker-gc:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    service: docker-gc
  tty: true
  image: spotify/docker-gc
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /etc:/etc
  stdin_open: true
logspit:
  environment:
    SYSLOG_HOST: sumo
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: canopytax/logspit
  links:
  - sumo-collector:sumo
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
loadbalancer:
  ports:
  - 30001:8080
  labels:
    io.rancher.scheduler.global: 'true'
    service: loadbalancer
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
sumo-collector:
  ports:
  - 514:514/tcp
  - 514:514/udp
  labels:
    io.rancher.scheduler.global: 'true'
    service: sumo-collector
  tty: true
  image: sumologic/collector:latest-syslog
  stdin_open: true
cronboss:
  environment:
    INTERVAL: '2'
    SELECTOR_LABEL: service=myservice
    UNIT: minutes
  labels:
    service: cronboss
  command:
  - something
  - useful
  - here
  tty: true
  image: canopytax/cronboss
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
```

And I also created a demo. This demo starts after the first host is terminated and the second host has registered itself with rancher, you will see that the global services dont move over until the first host is deleted. https://youtu.be/yQaZzSD5JHY
