### ISSUE TITLE
rancher-compose.yml seems to not be working in UI when adding stack

### ISSUE THREAD

**Issue by cloudguru-bb** [rancher/rancher#3357]
Rancher Compose is not rendering stacks from the GUI.  This is a fresh install on Digital Ocean with Docker 1.9.1 on Ubuntu 14.04  LTS.  UFW has been disabled.  The Docker Compose LHS of GUI works as expected to launch a new stack.  RHS of GUI using Rancher Compose appears to do nothing.  I'm using the io.rancher set of labels :
```
ubuntu:
  image: ubuntu:latest
  cap_add:
  - ALL
  labels:
    io.rancher.container.requested_ip: 10.42.11.101
  privileged: true
  restart: 'no'
```
Ideas what could be the problem ?
