### ISSUE TITLE
The cloud provider config is ineffective.

### ISSUE THREAD

**Issue by yaocw2020** [rancher/rancher#33611]
**Rancher Server Setup**
- Rancher version: master-8073489a3224599856e4adc48cfa04132262b077
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When setting up an RKE2 cluster, the cloud provider config is ineffective.

We can see the cloud provider config item in the request body. However, it disappears in the response body.

![image](https://user-images.githubusercontent.com/7421463/125587110-e68a35f1-2b75-4e32-b63f-74a4e861d54c.png)
![image](https://user-images.githubusercontent.com/7421463/125587225-8ab7d978-0912-42fa-bd00-a772e65edbb9.png)

After setting up the RKE, if you look at the annotations on a node in the cluster, you should see one called rke2.io/node-args. This should have an arg for `--cloud-provider-config`.  However, I didn't see the arg. 

**To Reproduce**
 
- Provision new nodes and create a cluster using RKE2
- Select `external` for the Cloud Provider drop-down box.
- Edit the Cloud Provider Config text box.
![image](https://user-images.githubusercontent.com/7421463/125588696-37e1882f-6d12-4f51-95cc-ccbb42cda360.png)

**Result**

**Expected Result**

The cloud provider config should be effective in the RKE2 cluster.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by davidnuzik** [comment]
Assigned to @rancher-max with the following goals in mind:
1. Please try to reproduce this issue
2. See if you can determine if this is likely a Rancher integration issue or a native RKE2 issue
3. When done, leave a comment with your findings and notify Chris Wayne and I in a comment so we can determine how to proceed from there.

Let Chris W. and I know if you have any questions. Thanks!

**Comment by guangbochen** [comment]
based on our testing this is an RKE2 provision issue, could be related to the file is not passed and saved properly: https://github.com/rancher/rancher/blob/c7acf95d6ed7b58005c014d9bdf62890c55e64c5/pkg/provisioningv2/rke2/planner/planner.go#L475
additionally we have tried with the native RKE2 with specify the `--cloud-provider-name=external` and `--cloud-provider-config=/path/to-the-file` and it works as expected, thanks.
https://docs.rke2.io/install/install_options/server_config/#rke2-server-cli-help

**Comment by cjellick** [comment]
Thanks for following up on this @davidnuzik

**Comment by cjellick** [comment]
Actually, @guangbochen has proven what we needed to prove here: it works in standalone RKE2, but not when provisioned through Rancher.

Thanks for the follow up @guangbochen.

No need to have Max duplicate this effort. I'm going to unassign him and kick that back over to the Rancher team.

**Comment by Jono-SUSE-Rancher** [comment]
Thanks for the investigation and clarification gentlemen, Rancher team will grab this and get it assigned out.

**Comment by yasker** [comment]
@Jono-SUSE-Rancher Harvester team can take care of this one. Thanks.

**Comment by Jono-SUSE-Rancher** [comment]
Even better! Thanks @yasker - I'll mark it in the sheet.

**Comment by yaocw2020** [comment]
I have figured out that it's a frontend bug. According to the backend API definition, the cloud-config content should be placed in `machineSelectorConfig[].config`, while the frontend caller place it in `machineSelectorConfig`

![image](https://user-images.githubusercontent.com/7421463/128320167-f0c86ffb-918d-4938-968f-61c54d40b87c.png)

``` go
type RKEClusterSpecCommon struct {
	LocalClusterAuthEndpoint LocalClusterAuthEndpoint `json:"localClusterAuthEndpoint,omitempty"`
	UpgradeStrategy          ClusterUpgradeStrategy   `json:"upgradeStrategy,omitempty"`
	ChartValues              GenericMap               `json:"chartValues,omitempty" wrangler:"nullable"`
	MachineGlobalConfig      GenericMap               `json:"machineGlobalConfig,omitempty" wrangler:"nullable"`
	MachineSelectorConfig    []RKESystemConfig        `json:"machineSelectorConfig,omitempty"`
	AdditionalManifest       string                   `json:"additionalManifest,omitempty"`
	Registries               *Registry                `json:"registries,omitempty"`
	ETCD                     *ETCD                    `json:"etcd,omitempty"`
}

type RKESystemConfig struct {
	MachineLabelSelector *metav1.LabelSelector `json:"machineLabelSelector,omitempty"`
	Config               GenericMap            `json:"config,omitempty" wrangler:"nullable"`
}
```

**Comment by vincent99** [comment]
Rebase first, that should have been fixed a couple days ago...

**Comment by deniseschannon** [comment]
@yaocw2020 @yasker Can we retest with the latest v2.6-head to see if cloud provider is being passed and set up as expected.

cc: @davidnuzik This is a perfect use case/testing of the `external` option for cloud provider.

**Comment by yaocw2020** [comment]
- Create a custom RKE2, select external cloud provider and add the cloud provider config.
![image](https://user-images.githubusercontent.com/7421463/130033641-9cfbf599-2b0f-4783-9ab3-20e3e35cc133.png)

- We can see that the cloud provider config in the API response.
![image](https://user-images.githubusercontent.com/7421463/130034016-97a591d3-44e6-4307-817f-16989712c403.png)

- Login the machine and find the cloud provider config in the path `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config`
``` yaml
root@rke2-custom:/var/lib/rancher/rke2/etc/config-files# cat cloud-provider-config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTWpreE9EZzNNemN3SGhjTk1qRXdPREUzTURneU5UTTNXaGNOTXpFd09ERTFNRGd5TlRNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTWpreE9EZzNNemN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSb3dGcVU0SnNjMWRocVlrRy9vZ2tMTDAvZk9od1daYkhMb0lhRFNRdWgKSnI1c2NBK3pRc01taSs1aHYwKzFUMzNvMjZBWXZQWC9GOEFFNzJQSUZqZ2ZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTNaczk1amh5YjZtRXd3Ri8xa0wyCkFRTE13dG93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9RQmsxMk5RakRtWUNQSlF1NWRmeXJORndyNUt1eTYKZ2ZkbmZ6bS9wY0dkQWlCL0dwSGk4M3QyZWtXZUVGdXNJNXI4VzF0RjJyelZ2YWhEZmw4OEg1YjZiQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.16.4.4:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: ccm-test-default-default
  name: ccm-test-default-default
current-context: ccm-test-default-default
kind: Config
preferences: {}
users:
- name: ccm-test-default-default
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ikc2MWRBSlZSYkNXNWd5bnBFWUhLVjl0LWF0elRacXMtazQ0ZXdkMWloYmsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNjbS10ZXN0LXRva2VuLTd2ZGQyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImNjbS10ZXN0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOTc5YzViOTMtNWQzNi00YzJhLWIwOWMtZjNkNDE5ZjEwMGY1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6Y2NtLXRlc3QifQ.nDJEyf9030Tt28QM23EKA63hvcBs7ZI4D2rY9sbDCWsTI4HkaMCvu64YvcSOfalyovtUGZ7qkvdEQlc7vcTmaK72DoPaxMJcbF9TCl7vH9rynI2_WklNeYALG6vIUynDWJ8a9dn8yg3mLSItFePQlL2zOkiZ6WTqYrROum9BFEyQqSPnRN9RmiHGAtV_EaoGDuuB5hL8w9i-J3ZqQqRHF8wqvasOGpwvo0sdBMQ4Dhhf0SgIYrTEn3O8wLBLTMIptCZK_VAOJAKJih-l_lJ9ys-qnAfrdjq9yP5CJCzMaJEfcBi5SrH_AZ3qtbkofnFhbs_9VgBtTLJmgOMRRhQTlQroot@rke2-custom:/var/lib/rancher/rke
```
The problem is solved. Thanks a lot!
