### ISSUE TITLE
[v2.5 Backport] Manually created duplicate rolebindings are not cleaned up when Rancher is upgraded to 2.5.8

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#33682]
Backport to 2.5 for https://github.com/rancher/rancher/issues/33144

Referenced issue description snapshot:

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Before upgrade rancher version: v2.5.6
After rancher upgrade version: v2.5.8

1. On v2.5.6, create a node driver DO cluster with 3 nodes with 1 role in each of the nodes (cp, worker, etcd)
2. Create a user1 from global --> security --> users
3. Create a project P1 in the cluster created above and add user1 as a project owner and project member in P1.
4. By executing the command grab the role template of the role binding for the above user for project member

```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
 labels:
  "cattle.io/creator": norman
  "p-krzs2_prtb-vpn2999": "membership-binding-owner"
 name: "rolebinding-k48nc"
 namespace: "c-gh6nj"
roleRef:
 apiGroup: "rbac.authorization.k8s.io"
 kind: Role
 name: "p-krzs2-projectmember"
subjects:
- apiGroup: "rbac.authorization.k8s.io"
  kind: User
  name: "u-9bj7w"
```
5. Create 10k duplicates for the above rb by changing the name ` name: "rolebinding-k48nc"`
6. verify the number of duplicates created are more than or equal to 10k 
7.  Upgrade rancher server to the version v2.5.8, and the manually created duplicates are not deleted:

From Rancher server logs:
```
2021/06/10 21:15:54 [INFO] Total PRTB duplicate clusterRoleBindings 1, roleBindings 6
2021/06/10 21:15:54 [INFO] Done Duplicate CRB and RB cleanup
2021/06/10 21:15:54 [INFO] Rancher startup complete
```

Duplicates on the cluster:
```
DEBU[0000] rb: kube-system/system::leader-locking-kube-scheduler has multiple subjects
DEBU[0001] crb: /system:public-info-viewer has multiple subjects
DEBU[0001] groups of duplicate role bindings: 1
DEBU[0001] total duplicate role bindings: 10436
DEBU[0001] no dupe crbs found
```

**Result:**
The duplicates that were created manually should be deleted

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider
- Kubernetes version (use `kubectl version`): v1.20.6
