### ISSUE TITLE
ImportYaml Error when deploying through the UI

### ISSUE THREAD

**Issue by manicole** [rancher/rancher#33712]
Hi all !

**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option: Helm Chart on Kubernetes 1.20

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type: Imported (managed a provider)

**Describe the bug**
On "local" cluster, on a project on which I have privileges to do so, I try to deploy a workload by importing a yaml. I often encounter an error.

**To Reproduce**
Login to Rancher UI, go to local cluster, choose a project. On "Resources" > "Workloads" screen, click  "Import YAML" button.
Copy-paste the following in the black box, and "import":
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: volume-snapshot
spec:
  volumeSnapshotClassName: csi-cinder-snapclass
  source:
    persistentVolumeClaimName: volume
```

I am not sure if you need it, but my user has the following privileges on VolumeSnapshot:
<html><body>

Create | Delete | Get | List | Patch | Update | Watch | Resource | Non-Resource URLs (path only) | API Groups |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
 x | x | x | x | x | x | x | volumesnapshot | n/a | snapshot.storage.k8s.io

</body>
</html>

**Result**
I get the error:
```sh
ImportYaml Error
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 2 of the JSON data
```
This happen while trying to import VolumeSnapshot as well as other resources. Sometimes it does happen, sometimes it does not, but I am not able to identify the reason ...

**Expected Result**
I expect the VolumeSnapshot to be created.

Thanks for helping !
