### ISSUE TITLE
how to config lifecycle  "postStart" 、"preStop"  by the rancher UI?  

### ISSUE THREAD

**Issue by rayshen3** [rancher/rancher#33726]
rancher  version: 2.5.7
kubernetes version: 1.20.5
docker version: 18.6.3

i can't find any place to config the container lifecycle hook in the ui,  Is it only by editing the yaml?

what i want:

```
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - appctl.sh stop

```

thx~
