### ISSUE TITLE
Rancher on master node redirects letsencrypt validate traffic to worker node?

### ISSUE THREAD

**Issue by syphernl** [rancher/rancher#33728]
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart):
   - RKE1 (v1.2.9) used to deploy
   - Deployed via:
      ```
     helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher.k8s.example.com --set replicas=1 --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=devops@example.com
      ```
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.8
- Cluster Type (Local/Downstream): Local (imported)

**Describe the bug**

Using RKE I have setup two nodes:

```
nodes:
  - address: master01.k8s.example.com
    internal_address: 10.0.1.1
    user: root
    role: [controlplane, worker, etcd]
        
  - address: worker01.k8s.example.com
    internal_address: 10.0.2.1
    user: root
    role: [worker]

```

On `master01` I have installed Helm, Cert-manager and Rancher. 
The certificate can not be deployed, because the  LetsEncrypt challenge URL (`.../.well-known/....`) cannot be reached: a 504 is given. 

Once I removed the `worker01` node from RKE the certificate could be issued just fine.

`kubectl describe ingress -n cattle-system` shows both hosts mentioned in `Address`.

```
root@master01:~# kubectl describe ingress -n cattle-system
Name:             rancher
Namespace:        cattle-system
Address:          master01.k8s.example.com,worker01.k8s.example.com
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  tls-rancher-ingress terminates rancher.k8s.example.com
Rules:
  Host                   Path  Backends
  ----                   ----  --------
  rancher.k8s.example.com  
                            rancher:80 (10.42.0.25:80)
```

Strangely, the webinterface works just fine. But as soon as the `well-known` is being loaded this results in a 504.

**To Reproduce**
 

**Result**
504 on `.well-known` endpoint until the worker-node has been removed from the RKE config.

**Expected Result**
Certificate to be issued, as the `.well-known` is reachable on the master node.
