### ISSUE TITLE
Allow ability to change the health check settings for load balancers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3375]
Currently, the health checks are overridden based on the defaults, so even if you provided a different rancher-compose.yml that had different values, the health check of the load balancer would still be the default values.

Note: There is no option to change health checks of a load balancer in the UI. If we allow being able to change it, we might want to allow users to change it in the UI?

**Comment by sangeethah** [comment]
@alena , tested with server version - v0.56.0-rc2

Able to override health check params by passing values for health_check params in rancher-compose.yml:

```
lb-7777:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 52
    interval: 3000
    unhealthy_threshold: 4
    healthy_threshold: 3
    response_timeout: 3000
test1:
  scale: 2
test2:
  scale: 2
``` 

Probably we should not allow for overriding port parameter . I set it to port 52 and see my lb instance is stuck in initializing state.
