### ISSUE TITLE
Incorrect behavior/parsing of yaml data between CLI and GUI when creating a new cluster (upload of YAML in GUI works, but using rancher CLI it doesn't)

### ISSUE THREAD

**Issue by dmpe** [rancher/rancher#33760]
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, local cluster on 1.20.6, target new cluster on 1.20.6
   - rancher -v -> rancher version v2.4.11

- Proxy/Cert Details: NA - not relevant here

**Information about the Cluster**
- Kubernetes version: 1.20.6
- Cluster Type (Local/Downstream): Donwstream; Custom

**Describe the bug**

My goal is to create a new downstream cluster, avoiding rancher GUI, by using rancher CLI/curl etc.

As I understand, you can create cluster using CLI
```
rancher clusters create --rke-config ./config-rancher.yml cluster3
```
When your yaml is like this:

```
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: "cluster3"
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509
  authorization: {}
  bastion_host:
    ssh_agent_auth: false
  cloud_provider: {}
  ignore_docker_version: true
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: none
  kubernetes_version: "v1.20.6-rancher1-1"
  monitoring:
    provider: none
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  private_registries:
    - is_default: true
      url: "docker-proxy.firm.com" # private proxy
      user: null
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
    kube-controller: {}
    kubelet:
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: true
  upgrade_strategy:
    drain: false
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: true
  scan_config:
    cis_scan_config:
      debug_master: false
      debug_worker: false
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```
Cluster3 is created, but majority of the fields in the GUI are incorrect, e.g. docker proxy is not set. Ingress is still enabled, even though it should be disabled, etc. 

**To Reproduce**

1. Store above yaml in file
2. use rancher cluster to provision a new cluster using rancher cli
3. check in the rancher gui the cluster3 - observer that both ingresses should be disabled but they are NOT!
---------
1. Now use above yaml file and go to rancher gui and create a new cluster ("existing nodes")
2. Edit YAML on the right side and paste above yaml file into the filed. Save/Store and check results. 
3. All Fields are as expected, i.e. ingress is disabled etc.

**Expected Result**

There is no difference between rancher GUI and rancher CLI. but clearly rancher CLI does not parse yaml properly and hence is creating cluster incorrectly. 

The workaround is to use curl, which is very problematic because it does not map yaml naming correctly either. Can provide further details if/when necessary.
