### ISSUE TITLE
RKE2 missing the following server arguments

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#33786]
From https://github.com/rancher/rancher/issues/32375#issuecomment-854254795
```
- container-runtime-endpoint
- snapshotter
- Image overrides:
  - kube-apiserver-image
  - kube-controller-manager-image
  - kube-scheduler-image
  - pause-image
  - runtime-image
  - etcd-image  
- disable-scheduler
- disable-cloud-controller
- disable-kube-proxy
- kubelet-path
```

Also note that `disable-kube-proxy` is a new arg to disable the kube-proxy static pod. There still remains the disabling of the kube-proxy helm chart, but now rke2 presents two separate options for kube-proxy, with the default being the static pod. This arg can be addressed specifically by https://github.com/rancher/rancher/issues/33785

Another new server arg: `etcd-arg`

**Comment by rancher-max** [comment]
@deniseschannon Since this is being tracked with v2.6.4 now, do we also want to throw in the new server-arg we included in our most recent k3s/rke2 releases into this? I made a comment about it in the KDM tracking issue for those: https://github.com/rancher/rancher/issues/35370#issuecomment-976801167.

**Comment by deniseschannon** [comment]
@rancher-max Yes, let's add them here ot the list of missing other args

**Comment by snasovich** [comment]
Seems we need to add these args to KDM.

**Comment by snasovich** [comment]
The same comment as https://github.com/rancher/rancher/issues/34315#issuecomment-1060943631 is applicable. Moving back to test.

**Comment by bguzman-3pillar** [comment]
Validated using `v1.21.10+rke2r1`

Modifying this RKE config:
```
{
  "refresh-interval-minutes": "1",
  "url": "https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6/data.json"
}
```

Yaml modified before log into server node and check:
```
...
    machineGlobalConfig:
      cloud-controller-manager-extra-env: null
      cloud-controller-manager-extra-mount: /home/cloudcontrollermount
      cni: calico
      control-plane-resource-limits: null
      control-plane-resource-requests: null
      disable-kube-proxy: false
      etcd-expose-metrics: false
      etcd-extra-env: etcd=etcdEnv
      etcd-extra-mount: /home/etcdextramount
      kube-apiserver-extra-env: kubeapi=apiEnv
      kube-apiserver-extra-mount: /home/apiservermount
      kube-controller-manager-extra-env: test=foo
      kube-controller-manager-extra-mount: /home/managerextramount
      kube-proxy-extra-env: proxy=proxyEnv
      kube-proxy-extra-mount: /home/proxyextramount
      kube-scheduler-extra-env: scheduler=schedulerEnv
      kube-scheduler-extra-mount: /home/schedulermount
      profile: null
...
```

Once that is ready, log into server node and run this command `cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml` to verify the file is populated:
```
{
  "agent-token": "6rpz6mwcgs6vfxkmmfbhfnlnzbxxt4gcn7zxd5ddm5qrjnprb6wlbr",
  "cloud-controller-manager-extra-mount": "/home/cloudcontrollermount",
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-extra-env": "etcd=etcdEnv",
  "etcd-extra-mount": "/home/etcdextramount",
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-apiserver-extra-env": "kubeapi=apiEnv",
  "kube-apiserver-extra-mount": "/home/apiservermount",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-env": "test=foo",
  "kube-controller-manager-extra-mount": [
    "/home/managerextramount",
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-proxy-extra-env": "proxy=proxyEnv",
  "kube-proxy-extra-mount": "/home/proxyextramount",
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-env": "scheduler=schedulerEnv",
  "kube-scheduler-extra-mount": [
    "/home/schedulermount",
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "rke.cattle.io/machine=ab2a15de-0433-4269-af99-dc150ba40eed"
  ],
  "node-taint": [
    "node-role.kubernetes.io/control-plane:NoSchedule",
    "node-role.kubernetes.io/etcd:NoExecute"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "token": "<redacted>"
}
```
