### ISSUE TITLE
rancher-compose up --upgrade is not the same as the interface

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#3382]
For understanding this issue, I've put on the end my `rancher-compose.yml` and `docker-compose.yml` on the end.

I'm trying to run an _continous delivery_ with Rancher. My last step is run and full upgrade of update services on target stack. To make this work, I run the following procedure as an Jenkins step:

```
cd ${WORKSPACE} && \
    rancher-compose --verbose -p arrow pull --cached && \
    rancher-compose --verbose -p arrow up -d --force-upgrade --confirm-upgrade arrow-fpm arrow-cli && \
    rancher-compose --verbose -p arrow up -d --upgrade --confirm-upgrade --pull
```

But sometimes, it don't upgrade my side kick container. If I go to the interface and upgrade the service manually - making sure that `fpm` and `atena-fpm` are checked - it runs very well.

All I wanna do is make it pull the latest `data-container` from registry and deploy it with zero-downtime.

_rancher-compose.yml_

```
arrow-fpm:
    upgrade_strategy:
        start_first: true

arrow-nginx:
    upgrade_strategy:
        start_first: true

arrow-worker:
    upgrade_strategy:
        start_first: true

arrow-cli:
    upgrade_strategy:
        start_first: true

fpm:
    upgrade_strategy:
        start_first: true

nginx:
    upgrade_strategy:
        start_first: true

postgres:
    upgrade_strategy:
        start_first: true
```

_docker-compose.yml_

```
arrow-fpm:
    image: registry.fakename.com/arrow:latest
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

arrow-nginx:
    image: registry.fakename.com/arrow:latest
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

arrow-cli:
    image: registry.fakename.com/arrow:latest
    tty: true
    stdin_open: true
    labels:
        io.rancher.container.pull_image: always
    command: cat

fpm:
    image: registry.fakename.com/laravel-fpm:latest
    labels:
        io.rancher.sidekicks: arrow-fpm
        io.rancher.scheduler.affinity:host_label: server=11
        io.rancher.container.pull_image: always
    volumes_from:
        - arrow-fpm
    links:
        - postgres
    environment:
        APP_URL: arrow.ms.fakename.com 
        DB_CONNECTION: pgsql
        DB_HOST: postgres
        DB_DATABASE: arrow
        DB_USERNAME: arrow
        DB_PASSWORD: arrow

nginx:
    image: registry.fakename.com/laravel-nginx:latest
    links:
        - fpm
    labels:
        io.rancher.sidekicks: arrow-nginx
        io.rancher.scheduler.affinity:host_label: server=11
        io.rancher.container.pull_image: always
    volumes_from:
        - arrow-nginx

postgres:
    image: postgres:9.5.0
    volumes:
        - /var/lib/postgresql/arrow:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: arrow
        POSTGRES_PASSWORD: arrow
    labels:
        io.rancher.scheduler.affinity:host_label: server=11

cli:
    image: registry.fakename.com/laravel-cli:latest
    command: php /data/www/artisan migrate --force
    labels:
        io.rancher.sidekicks: arrow-cli
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label: server=11
        io.rancher.container.start_once: true
    volumes_from:
        - arrow-cli
    links:
        - postgres
    environment:
        APP_URL: arrow.ms.fakename.com 
        DB_CONNECTION: pgsql
        DB_HOST: postgres
        DB_DATABASE: arrow
        DB_USERNAME: arrow
        DB_PASSWORD: arrow
```

Currently running on:
![Stack](http://i.imgur.com/KNXKq2h.png)

**Comment by deniseschannon** [comment]
Which sidekick container is it not upgrading? I see that in your command, you don't have the upgrade to request `arrow-nginx` to be upgraded.

**Comment by pedrommone** [comment]
arrow-fpm and arrow-cli.

**Comment by deniseschannon** [comment]
I am unable to reproduce. Can you confirm whether the images for the sidekicks were updated on your hosts? 

Steps I took:
1. Launch your list of services, but modified the docker-compose.yml to make it easier for me.
2. Update the docker-compose.yml by changing the image for the 2 sidekicks
3. Upgrade the stack using this command:

```
rancher-compose up -d --upgrade --confirm-upgrade
```

4. The sidekicks `arrow-fpm` and `arrow-cli` were upgraded and are at the new image. 

Docker-compose.yml

```
arrow-fpm:
    #Started with ubuntu 14.04.3 and updated to 14.04 for "upgrade"
    image: ubuntu:14.04
    tty: true
    stdin_open: true
    command: cat

arrow-nginx:
    image: nginx
    tty: true
    stdin_open: true
    command: cat

arrow-cli:
   #Started with ubuntu 14.04.3 and updated to 14.04 for "upgrade"
    image: ubuntu:14.04 
    tty: true
    stdin_open: true
    command: cat

fpm:
    image: ubuntu:14.04.3 
    labels:
        io.rancher.sidekicks: arrow-fpm
    volumes_from:
        - arrow-fpm
    links:
        - postgres
    tty: true
    stdin_open: true

nginx:
    image: nginx
    links:
        - fpm
    labels:
        io.rancher.sidekicks: arrow-nginx
    volumes_from:
        - arrow-nginx

postgres:
    image: postgres:9.5.0
    environment:
        POSTGRES_USER: arrow
        POSTGRES_PASSWORD: arrow

cli:
    image: ubuntu:14.04.3 
    labels:
        io.rancher.sidekicks: arrow-cli
        io.rancher.container.start_once: true
    volumes_from:
        - arrow-cli
    tty: true
    stdin_open: true
    links:
        - postgres
```
