### ISSUE TITLE
RKE2 based provisioning fails on vmware

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/rancher#33867]
**Rancher Server Setup**
- Rancher version: master-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  v1.21.3+k3s1
- Proxy/Cert Details: letsEncrypt

**Information about the Cluster**
- Kubernetes version: any RKE2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vmware node driver

**Describe the bug**

On current master-head provisioning a RKE2 based cluster on vmware fails if the network name has a space.

A sample vmwarevspheremachinetemplate is as follows:

```yaml:
apiVersion: rke-machine.cattle.io/v1
kind: VmwarevsphereMachineTemplate
metadata:
  name: vmware-grke2m
  namespace: fleet-default
spec:
  clusterName: vmware
  template:
    spec:
      boot2dockerUrl: ""
      cfgparam:
      - disk.enableUUID=TRUE
      cloneFrom: /RNCH-HE-FMT/vm/openSUSE-Leap-15.2-Rancher-Tmpl
      cloudConfig: |+
        #cloud-config
      cloudinit: ""
      common:
        cloudCredentialSecretName: vmware
      contentLibrary: ""
      cpuCount: "2"
      creationType: template
      customAttribute: []
      datacenter: /RNCH-HE-FMT
      datastore: /RNCH-HE-FMT/datastore/ranch01-silo02-vm01
      datastoreCluster: ""
      diskSize: "20000"
      folder: null
      hostsystem: __SENTINEL__
      memorySize: "2048"
      network:
      - /RNCH-HE-FMT/network/Private Range 172.16.128.1-21
      password: ""
      pool: /RNCH-HE-FMT/host/FMT2.R620.1/Resources/gmehta
      sshPassword: tcuser
      sshPort: "22"
      sshUser: docker
      sshUserGroup: staff
      tag: []
      username: ""
      vappIpallocationpolicy: null
      vappIpprotocol: null
      vappProperty: []
      vappTransport: null
      vcenter: ""
      vcenterPort: "443"
```

**To Reproduce**
 
Create a cluster on vmware with the sample settings in the machine pool.

**Result**
Cluster provisioning fails
```
k get machine
NAME                             PROVIDERID   PHASE    VERSION
vmware-grke2w-55c7956499-tql44                Failed
vmware-grke2m-f6d76f6bb-gxp4p                 Failed
```

Reason for failure in the machine status
```
Failure Message:         Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=VmwarevsphereMachine with name "vmware-grke2m-6b4l4": Invalid command line. Found extra arguments [172.16.128.1-21 --vmwarevsphere-pool=/RNCH-HE-FMT/host/FMT2.R620.1/Resources/gmehta --vmwarevsphere-ssh-password=tcuser --vmwarevsphere-ssh-port=22 --vmwarevsphere-ssh-user-group=staff --vmwarevsphere-ssh-user=docker --vmwarevsphere-vcenter-port=443 vmware-grke2m-6b4l4]
  Failure Reason:          CreateError
```

**Expected Result**

Cluster should provision correctly.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>
