### ISSUE TITLE
Unable to view resources in downstream clusters when my user is associated with a group from an external auth provider

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33912]
Rancher Users Setup:

Rancher with GH enabled
Add `rancher` org as a group to the setup and given the role "admins"
Create a RKE2 cluster.

If I search for PodSecurityPolicies through cluster explorer, I can find the list page of all the policies in a cluster, but when I click on one of the them, the page never loads and gets stuck in "Loading..."

**Comment by thedadams** [comment]
I am not able to reproduce this issue. After deploying a cluster and navigating to the PSP page, I can see the details of all PSPs.
![Screen Shot 2021-08-04 at 12 33 29 PM](https://user-images.githubusercontent.com/3682717/128243884-216fb8f0-9dff-4140-8132-d6dd98074b7e.png)

**Comment by deniseschannon** [comment]
I updated the title and think this is more generic and I just happened to stumble upon this resource, but my user is associated to a group which seems to be causing failures for loading the resource in a downstream cluster

```
apiVersion: v1
code: 403
details:
  kind: groups
  name: github_org://9343010
kind: Status
message: ‘groups “github_org://9343010” is forbidden: User “system:serviceaccount:cattle-impersonation-system:cattle-impersonation-u-vnds56pccy”
  cannot impersonate resource “groups” in API group “” at the cluster scope’
metadata: {}
reason: Forbidden
status: Failure
```
