### ISSUE TITLE
RKE2 & RKE1 with calico and project network isolation breaks ingress controller to pod communication

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#33979]
**Rancher Server Setup**
- Rancher version: v2.5.9 and v2.6.0-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.21.3+k3s1
- Proxy/Cert Details: no proxy, Let's Encrypt certificate

**Information about the Cluster**
- Kubernetes version: RKE2: v1.21.3+rke2r1 and RKE: v1.20.9-rancher1-1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested with custom and digital ocean infrastructure provider

**Describe the bug**
When you create an RKE1 or RKE2 cluster with calico as a CNI (default for RKE2) and activate project network isolation. The communication between the ingress controller and the Pods does not work anymore.

**To Reproduce**
* Create a multi node RKE2 custom cluster
* Choose default Calico CNI
* Activate project network isolation
* Create a workload (e.g.) an nginx and an ingress
* Try to reach the ingress

**Result**
The nginx ingress controller will get a gateway timeout when communication with the pod:

```
curl 35.158.100.209 -H 'Host: nginx.example'
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Expected Result**
The communication works out of the box.

**Additional context**
The communication works out of the box, if you choose canal as a CNI. Rancher automatically creates a `hn-nodes` NetworkPolicy in every namespace, which should allow communication from the ingress controller. The policy works fine for canal, but not for calico.
If I understand it correctly, Rancher creates the policy from the node's podCIDRs:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-08-05T13:28:45Z"
  generation: 3
  name: hn-nodes
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: default
    uid: f6372a0d-28e0-4538-b649-ae8dd62355d8
  resourceVersion: "3157"
  uid: e31fe0a2-0f2c-43de-877b-450fb8b0cd01
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.42.0.0/32
    - ipBlock:
        cidr: 10.42.1.0/32
    - ipBlock:
        cidr: 10.42.2.0/32
  podSelector: {}
  policyTypes:
  - Ingress
```

With Calico the communication only works, if I create such a policy from the `projectcalico.org/IPv4VXLANTunnelAddr`:

```
kubectl get nodes -o yaml | grep projectcalico.org/IPv4VXLANTunnelAddr
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.0.0
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.32.0
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.212.0
```

A working policy

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: default
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.42.0.0/32
  - from:
    - ipBlock:
        cidr: 10.42.212.0/32
  - from:
    - ipBlock:
        cidr: 10.42.32.0/32                
  podSelector: {}
  policyTypes:
  - Ingress
```

In not quite sure though, if adding this allows to much or is too broad.
