### ISSUE TITLE
Logging Operator 3.9.400 : parser multiline generating fluentd config with escape characters

### ISSUE THREAD

**Issue by mfbrj** [rancher/rancher#34177]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.9
- Cluster Type (Local/Downstream): Downstream Rancher provisioning the nodes in vSphere 6.5
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
I don't know what is the right repo to post this bug. And I already posted [here](https://github.com/banzaicloud/logging-operator/issues/802).

The issue occurs in the Banzai Cloud Logging Operator available on Apps & Marketplace (which is provided by Rancher). When using parser `multiline` in a flow, the logging operator generates the `format_firstline` parameter with quotes and escape characteres. This seems to disturb the log parser, since only the firstline is parsed and formated.

**To Reproduce**

1. On Rancher 2.5.9, install the chart Logging, version 3.9.400
2. After install, create a clusteroutput
3. Create a clusterflow which uses the parser `multiline`, with a regex with `\`, such as:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: java
  namespace: cattle-logging-system
spec:
  filters:
    - parser:
        parse:
          type: multiline
          # Reference: https://docs.fluentd.org/parser/multiline#java-stacktrace-log
          format_firstline: /\d{2}:\d{2}:\d{2},\d{3}/
          multiline:
            - /\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
        reserve_data: true
        remove_key_name_field: true
        reserve_time: true
    - record_transformer:
        records:
        - flow: "java"
    - tag_normaliser:
        format: k8s.${namespace_name}.${labels.app}
  globalOutputRefs:
    - ssr-es
  match:
    - select:
        namespaces:
          - some-namespace-with-java-logs-with-stack-traces
```
4. apply the configuration: `kubectl apply -f myclysterflow.yml`
5. Verify that the operator generates a fluentd config with quotes and `\\` in `format_firstline` parameter:
`k -n cattle-logging-system logs rancher-logging-fluentd-configcheck-62b2c0d5 | grep -A 10 -B 10 message`

This will show something like this:
```
    <filter **>
      @type parser
      @id clusterflow:cattle-logging-system:java:0
      key_name "log"
      remove_key_name_field true
      reserve_data true
      reserve_time true
      <parse>
        @type "multiline"
        format1 /\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
        format_firstline "/\\d{2}:\\d{2}:\\d{2},\\d{3}/"
      </parse>
    </filter>
```

**Result**
If fluentd parser a java log with stack traces such as:
```
[0m[33m03:31:59,449 WARN  [com.arjuna.ats.jta] (Periodic Recovery) ARJUNA016009: Caught:: java.lang.NullPointerException
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoverySecondPass(XARecoveryModule.java:738)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.bottomUpRecovery(XARecoveryModule.java:519)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkSecondPass(XARecoveryModule.java:270)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:816)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)
```
The output (i.e Elasticsearch) will get the event with the key/values:
Key | Value
-- | --
level|WARN
class|com.arjuna.ats.jta
thread|Periodic Recovery
message|ARJUNA016009: Caught:: java.lang.NullPointerException

The other lines `at com.arjuna.ats...` are added as other event log, one event per line.

**Expected Result**

The output (i.e Elasticsearch) shoud get a single event with the key/values:

Key | Value
-- | --
level|WARN
class|com.arjuna.ats.jta
thread|Periodic Recovery
message|ARJUNA016009: Caught:: java.lang.NullPointerException at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoverySecondPass(XARecoveryModule.java:738) at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.bottomUpRecovery(XARecoveryModule.java:519) at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkSecondPass(XARecoveryModule.java:270) at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:816) at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)

**Screenshots**

**Additional context**

Version images in the Logging Operator chart yml:
```
image:
  pullPolicy: IfNotPresent
  repository: rancher/mirrored-banzaicloud-logging-operator
  tag: 3.9.4
imagePullSecrets: []
images:
  config_reloader:
    repository: rancher/mirrored-jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10-debug
  fluentd:
    repository: rancher/mirrored-banzaicloud-fluentd
    tag: v1.11.5-alpine-12
  nodeagent_fluentbit:
    os: 'windows,linux'
    repository: rancher/fluent-bit
    tag: 1.6.10
```
