### ISSUE TITLE
[Rancher-webhook] Add support for hardened cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#34188]
`Rancher-webhook`'s newly-added pre-delete-hook does not support harden cluster. 
We need to add the PSP to it. 

Note: 
The `Rancher-webhook` app itself works in a hardened cluster because its SA is bind to `cluster Admin`

**Comment by jiaqiluo** [comment]
can be tested in `rancher-webhook 0.2.0-beta05`

**Comment by kinarashah** [comment]
Available to test with v2.6.0-rc5.

**Comment by cbron** [comment]
Assigning to @aiyengar2 for dev-validate since he is working on other rancher chart validation.

**Comment by aiyengar2** [comment]
Hmm, since both the original issue https://github.com/rancher/rancher/issues/33988 and this were fixed in the same RC, I cannot check for a regression and then a fix. Therefore, I will just ensure the same use case in the previous ticket works in a hardened cluster and is reproduced in an older Rancher version, when I am able to test this.

---

Unable to test. CIS 1.16 benchmark is not passing on a cluster provisioned using the above steps, so I cannot confirm that the cluster is hardened before attempting to uninstall. Opened up a ticket to follow up: https://github.com/rancher/rancher/issues/34409

**Comment by aiyengar2** [comment]
#### Steps to Reproduce

1. Provision a node and run the following commands provided in https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#configure-kernel-runtime-parameters and https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#create-etcd-user-and-group.
```bash
curl https://releases.rancher.com/install-docker/20.10.sh | sh

mkdir -p /etc/sysctl.d

cat << EOF > /etc/sysctl.d/90-kubelet.conf
vm.overcommit_memory=1
vm.panic_on_oom=0
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
EOF

sysctl -p /etc/sysctl.d/90-kubelet.conf

groupadd --gid 52034 etcd
useradd --comment "etcd service account" --uid 52034 --gid 52034 etcd
```
2. Create an A record pointing at the node; this will be HOSTNAME
3. On my local machine, run `rke up --ssh-agent-auth` using the following `cluster.yml`, as copied from https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-cluster-yml-configuration:

```yaml
nodes:
  - address: HOSTNAME
    user: root
    role:
      - controlplane
      - etcd
      - worker
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 52034
    gid: 52034
    snapshot: false
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: ""
    service_node_port_range: ""
    pod_security_policy: true
    always_pull_images: false
    secrets_encryption_config:
      enabled: true
      custom_config: null
    audit_log:
      enabled: true
      configuration: null
    admission_configuration: null
    event_rate_limit:
      enabled: true
      configuration: null
  kube-controller:
    image: ""
    extra_args:
      feature-gates: RotateKubeletServerCertificate=true
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: ""
    service_cluster_ip_range: ""
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args:
      feature-gates: RotateKubeletServerCertificate=true
      protect-kernel-defaults: "true"
      tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: ""
    fail_swap_on: false
    generate_serving_certificate: true
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: ""
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
authentication:
  strategy: ""
  sans: []
  webhook: null
addons: |
  apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: restricted
  spec:
    requiredDropCapabilities:
    - NET_RAW
    privileged: false
    allowPrivilegeEscalation: false
    defaultAllowPrivilegeEscalation: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: MustRunAsNonRoot
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - emptyDir
    - secret
    - persistentVolumeClaim
    - downwardAPI
    - configMap
    - projected
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: default-allow-all
  spec:
    podSelector: {}
    ingress:
    - {}
    egress:
    - {}
    policyTypes:
    - Ingress
    - Egress
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
  automountServiceAccountToken: false
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  coredns: ""
  coredns_autoscaler: ""
  nodelocal: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  calico_flexvol: ""
  canal_node: ""
  canal_cni: ""
  canal_controllers: ""
  canal_flannel: ""
  canal_flexvol: ""
  weave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
  metrics_server: ""
  windows_pod_infra_container: ""
ssh_key_path: ""
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: ""
  options: {}
ignore_docker_version: false
kubernetes_version: v1.18.12-rancher1-1
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
cluster_name:
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
restore:
  restore: false
  snapshot_name: ""
dns: null
upgrade_strategy:
  max_unavailable_worker: ""
  max_unavailable_controlplane: ""
  drain: null
  node_drain_input: null
```
4. Run `export KUBECONFIG=kube_config_cluster.yml` in the directory that you ran `rke up --ssh-agent-auth` within
5. Run the following commands to finish setting up the CIS 1.16 Hardened Cluster, adapted from https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#set-automountserviceaccounttoken-to-false-for-default-service-accounts and https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#ensure-that-all-namespaces-have-network-policies-defined

```
cat <<EOF > account_update.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
automountServiceAccountToken: false
EOF

cat <<EOF > account_update.sh
for namespace in \$(kubectl get namespaces -A -o json | jq -r '.items[].metadata.name'); do
  kubectl patch serviceaccount default -n \${namespace} -p "\$(cat account_update.yaml)"
done
EOF

cat <<EOF > default-allow-all.yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
EOF

cat <<EOF > apply_networkPolicy_to_all_ns.sh
for namespace in \$(kubectl get namespaces -A -o json | jq -r '.items[].metadata.name'); do
  kubectl apply -f default-allow-all.yaml -n \${namespace}
done
EOF

chmod +x account_update.sh
chmod +x apply_networkPolicy_to_all_ns.sh

./account_update.sh
./apply_networkPolicy_to_all_ns.sh

rm account_update.sh
rm account_update.yaml
rm apply_networkPolicy_to_all_ns.sh
rm default-allow-all.yaml
```

6. Run the following command to get the cluster ready to install Rancher by getting cert-manager installed:

```bash
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml
kubectl create namespace cert-manager
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4
```

7. Once cert-manager pods are all ready, run the following command to install Rancher in the cluster
```
# HOSTNAME=${HOSTNAME}
# RANCHER_VERSION=v2.6.0-rc1
RANCHER_VERSION=v2.6.0-rc5
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
```
8. Run step 5 once again (just for good measure)
9. Ensure that the MutatingWebhookConfiguration named `rancher.cattle.io` was created: `kubectl get MutatingWebhookConfiguration`. This takes a minute or so to be created.
10. Uninstall Rancher: `helm uninstall rancher --namespace cattle-system`
11. Check if the MutatingWebhookConfiguration named `rancher.cattle.io` was deleted post-install: `kubectl get MutatingWebhookConfiguration`. This should be true when reproducing and false after.
12. Reinstall Rancher: 

```bash
# HOSTNAME=${HOSTNAME}
# RANCHER_VERSION=v2.6.0-rc1
RANCHER_VERSION=v2.6.0-rc5

helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
```

#### 2.6.0-rc1

```bash
arvindiyengar: ~/Downloads/test2/est2/260rc1 
$ kubectl get MutatingWebhookConfiguration
NAME                             WEBHOOKS   AGE
cert-manager-webhook             1          3m22s
mutating-webhook-configuration   7          116s
rancher.cattle.io                2          11s
arvindiyengar: ~/Downloads/test2/est2/260rc1 
$ helm uninstall rancher --namespace cattle-system
release "rancher" uninstalled
arvindiyengar: ~/Downloads/test2/est2/260rc1 
$ kubectl get MutatingWebhookConfiguration
NAME                             WEBHOOKS   AGE
cert-manager-webhook             1          3m52s
mutating-webhook-configuration   7          2m26s
rancher.cattle.io                2          41s
arvindiyengar: ~/Downloads/test2/est2/260rc1 
$ helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
Error: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s: service "rancher-webhook" not found
```

Reproduced error on ticket.

#### 2.6.0-rc5

```bash
arvindiyengar: ~/Downloads/test2/est2/260rc5 
$ kubectl get MutatingWebhookConfiguration
NAME                             WEBHOOKS   AGE
cert-manager-webhook             1          5m22s
mutating-webhook-configuration   7          3m34s
rancher.cattle.io                2          2m
arvindiyengar: ~/Downloads/test2/est2/260rc5 
$ helm uninstall rancher --namespace cattle-system
release "rancher" uninstalled
arvindiyengar: ~/Downloads/test2/est2/260rc5 
$ kubectl get MutatingWebhookConfiguration
NAME                             WEBHOOKS   AGE
cert-manager-webhook             1          6m13s
mutating-webhook-configuration   7          4m25s
arvindiyengar: ~/Downloads/test2/est2/260rc5 
$ helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
NAME: rancher
LAST DEPLOYED: Tue Aug 24 11:27:50 2021
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued, Containers are started and the Ingress rule comes up.

Check out our docs at https://rancher.com/docs/

If you provided your own bootstrap password during installation, browse to https://arvind-rancher-260rc5.cp-dev.rancher.space to get started.

If this is the first time you installed Rancher, get started by running this command and clicking the URL it generates:

\`\`\`
echo https://arvind-rancher-260rc5.cp-dev.rancher.space/dashboard/?setup=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')
\`\`\`

To get just the bootstrap password on its own, run:

\`\`\`
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}'
\`\`\`


Happy Containering!
```

Looks like the fix worked! Job was able to successfully deployed in a hardened cluster setup, so PSP is set up correctly.
