### ISSUE TITLE
rancher-compose-executer timeout

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#3424]
I'm trying to create a new stack via the api and it just sits in the api as activiating

here is what is the rancher-server logs
```
2016-01-26T16:26:04.419516216Z time="2016-01-26T16:26:04Z" level=info msg="[rgonzalezmacaroon1162pro:]: Project created " eventId=c0ed7b69-ab1f-4693-a54d-c8f929feb70d resourceId=1e3387
2016-01-26T16:26:04.419531079Z time="2016-01-26T16:26:04Z" level=info msg="[rgonzalezmacaroon1162pro:]: Creating project " eventId=c0ed7b69-ab1f-4693-a54d-c8f929feb70d resourceId=1e3387
```

Here is the compose file
```yml
---
db:
  image: mysql:5.6
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: host=deploy
    sugarcrm.deploy_type: dev-build
    sugarcrm.app: mysql
    sugarcrm.instance: "${build_prefix}"
    sugarcrm.flavor: "${flavor}"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: sugar
    MYSQL_USER: sugar
    MYSQL_PASSWORD: sugar
web:
  restart: always
  image: <my custom image>
  labels:
    io.rancher.sidekicks: db
    sugarcrm.deploy_type: dev-build
    sugarcrm.app: sugarcrm
    sugarcrm.honeycomb.build_id: "${build_id}"
    sugarcrm.instance: "${build_prefix}"
    sugarcrm.flavor: "${flavor}"
    io.rancher.scheduler.affinity:host_label: host=deploy
  environment:
    SUGAR_DB_TYPE: mysql
    SUGAR_ANALYTICS_ID:
    MYSQL_PORT: tcp://db:3306
    MYSQL_NAME: db
    SUGAR_DEMO_DATA: true
    SUGAR_SITE_URL: 
    SUGAR_LICENSE_KEY:
    SUGAR_SITE_GUID:
    SUGAR_FTS_HOST:
  links:
  - db:mysql
```

here is the error that the front end is giving me when checking the running processes.
```
io.cattle.platform.async.utils.TimeoutException
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl$1.run(RetryTimeoutServiceImpl.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
![screenshot 2016-01-26 11 39 43](https://cloud.githubusercontent.com/assets/26738/12587257/9c986084-c421-11e5-8aeb-9a794b90567b.png)

This is random and causes rancher-compose to freeze up, and when checking via, the api, it doesn't ever switch state from activating.
