### ISSUE TITLE
RKE2 missing the following agent arguments

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34315]
After reviewing the first list of agentArgs for RKE2 compared to standalone RKE2, there was a comprehensive list of the missing set of args. https://github.com/rancher/rancher/issues/32376#issuecomment-895641963

There is no way to add these through the UI but it's available through yaml:

- audit-policy-file 
- kube-proxy-arg 

After reviewing the list, these were identified to be added into Rancher/KDM and figure out which ones should be added to the UI. 

resolv-conf (k3s and rke2)
Add for RKE2 only

control-plane-resource-requests
control-plane-resource-limits
*-extra-mount
kube-apiserver-extra-mount
kube-scheduler-extra-mount
kube-controller-manager-extra-mount
kube-proxy-extra-mount
etcd-extra-mount
cloud-controller-manager-extra-mount
*-extra-env
kube-apiserver-extra-env
kube-scheduler-extra-env
kube-controller-manager-extra-env
kube-proxy-extra-env
etcd-extra-env
cloud-controller-manager-extra-env

**Comment by snasovich** [comment]
This is more of a UI issue and we need to understand the requirements on which of these args need to be exposed and where.

**Comment by snasovich** [comment]
Need to discuss with PM on whether we want to expose any of these settings on the UI. If we do, do we need custom UI for some of them?

**Comment by snasovich** [comment]
Per discussion with @cloudnautique we've confirmed these settings don't need to be exposed in UI explicitly and having them be set via YAML is sufficient.
QA should validate that these settings can be set via YAML and perform as expected.

**Comment by bguzman-3pillar** [comment]
I would like to test it but I have one question: where exactly should I put this info in the yaml file?
I already tried below this part `machineGlobalConfig ` and didn’t work
Can someone help us?
Thanks
```
Add for RKE2 only

control-plane-resource-requests
control-plane-resource-limits
*-extra-mount
kube-apiserver-extra-mount
kube-scheduler-extra-mount
kube-controller-manager-extra-mount
kube-proxy-extra-mount
etcd-extra-mount
cloud-controller-manager-extra-mount
*-extra-env
kube-apiserver-extra-env
kube-scheduler-extra-env
kube-controller-manager-extra-env
kube-proxy-extra-env
etcd-extra-env
cloud-controller-manager-extra-env
```

**Comment by rancher-max** [comment]
It appears the value is being sent correctly from the UI:
![image](https://user-images.githubusercontent.com/55997940/152587657-c30171a0-f67e-4905-9190-857aa1b18399.png)

Also, setting a value that already exists by default in the config.yaml appears to work. I tried setting the following:
```
machineGlobalConfig:
      cni: calico
      kube-controller-manager-arg:
        - v=4
```
And see this value being set correctly, but no new values will work (for example `kube-controller-manager-extra-env` as shown in the API screenshot). The config.yaml on the node after setting these values looks like the following:
```
{
  "advertise-address": "<redacted>",
  "agent-token": "<redacted>",
  "cni": "calico",
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "--v=4",
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-external-ip": [
    "<redacted>"
  ],
  "node-ip": [
    "<redacted>"
  ],
  "node-label": [
    "rke.cattle.io/machine=58af8953-3af5-4f5d-998f-cfe72f466474"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "tls-san": [
    "<redacted>"
  ],
  "token": "<redacted>"
}
```

**Comment by bguzman-3pillar** [comment]
Validated but it looks the same, the config.yaml doesn't change/populated.
Editing the yaml file with this: 
```
Add for RKE2 only

control-plane-resource-requests
control-plane-resource-limits
*-extra-mount
kube-apiserver-extra-mount
kube-scheduler-extra-mount
kube-controller-manager-extra-mount
kube-proxy-extra-mount
etcd-extra-mount
cloud-controller-manager-extra-mount
*-extra-env
kube-apiserver-extra-env
kube-scheduler-extra-env
kube-controller-manager-extra-env
kube-proxy-extra-env
etcd-extra-env
cloud-controller-manager-extra-env
```

Yaml file edited:
![image](https://user-images.githubusercontent.com/95362932/156020624-9a1bc342-df42-4324-bd13-07fc77ce460f.png)


Then log into it and check the config file: `cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml`

```
{
  "agent-token": "9zclwxzzpzc55hxjs5v9wpbhmxxf2b5vf4d457fk7xm47ppfd5dj5c",
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "rke.cattle.io/machine=1bc075d9-695c-4337-ab45-ff55ebbe1eb1"
  ],
  "node-taint": [
    "node-role.kubernetes.io/control-plane:NoSchedule",
    "node-role.kubernetes.io/etcd:NoExecute"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "token": "<redacted>"
```

**Comment by snasovich** [comment]
Moving to test based on comment above.

**Comment by bguzman-3pillar** [comment]
Validated using `v1.21.10+rke2r1`

Modifying this RKE config:
```
{
  "refresh-interval-minutes": "1",
  "url": "https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6/data.json"
}
```

Yaml modified before log into server node and check:
```
...
    machineGlobalConfig:
      cloud-controller-manager-extra-env: null
      cloud-controller-manager-extra-mount: /home/cloudcontrollermount
      cni: calico
      control-plane-resource-limits: null
      control-plane-resource-requests: null
      disable-kube-proxy: false
      etcd-expose-metrics: false
      etcd-extra-env: etcd=etcdEnv
      etcd-extra-mount: /home/etcdextramount
      kube-apiserver-extra-env: kubeapi=apiEnv
      kube-apiserver-extra-mount: /home/apiservermount
      kube-controller-manager-extra-env: test=foo
      kube-controller-manager-extra-mount: /home/managerextramount
      kube-proxy-extra-env: proxy=proxyEnv
      kube-proxy-extra-mount: /home/proxyextramount
      kube-scheduler-extra-env: scheduler=schedulerEnv
      kube-scheduler-extra-mount: /home/schedulermount
      profile: null
...
```

Once that is ready, log into a worker node and run this command: `cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml`:
```
root@ranchertest-pool2-e581189e-hxtlw:~# cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml
{
  "cloud-controller-manager-extra-mount": "/home/cloudcontrollermount",
  "etcd-extra-env": "etcd=etcdEnv",
  "etcd-extra-mount": "/home/etcdextramount",
  "kube-apiserver-extra-env": "kubeapi=apiEnv",
  "kube-apiserver-extra-mount": "/home/apiservermount",
  "kube-controller-manager-extra-env": "test=foo",
  "kube-controller-manager-extra-mount": "/home/managerextramount",
  "kube-proxy-extra-env": "proxy=proxyEnv",
  "kube-proxy-extra-mount": "/home/proxyextramount",
  "kube-scheduler-extra-env": "scheduler=schedulerEnv",
  "kube-scheduler-extra-mount": "/home/schedulermount",
  "node-label": [
    "rke.cattle.io/machine=30615ba4-a814-452c-ae38-1beb7b96f451"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "server": "https://143.110.154.242:9345",
  "token": "<redacted>"
```
![image](https://user-images.githubusercontent.com/95362932/157322509-89b84168-2aaa-40e6-9a15-cbab1b76f55b.png)

Note: etcd args from a worker node are allowed.
