### ISSUE TITLE
Disable NAT for flannel when backend_type is host-gw

### ISSUE THREAD

**Issue by vitalvas** [rancher/rancher#34378]
**Is your feature request related to a problem? Please describe.**
There is a technical need to disable NAT in flannel when using it with host-gw.

**Describe the solution you'd like**
Disable via options in network settings. Example:
```
network:
  plugin: flannel
  options:
    flannel_backend_type: host-gw
    flannel_ipmasq: false
```
