### ISSUE TITLE
Multiple configuration requirements not meet for deploying Rancher´s cattle-logging-system on RKE2 with SELinux enabled and CIS-1.5 profile.

### ISSUE THREAD

**Issue by frjaraur** [rancher/rancher#34387]
**Rancher Server Setup**
- Rancher version:
```
Rancher | v2.5.9
User Interface | v2.5.9
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher55
```

- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Info:
         Cluster Type RKE2:
         Node Setup: 
        - Red Hat 8.4 ( 4.18.0-305.10.2.el8_4.x86_64)
        - SElinux Enabled (targeted)

```
Lis of relevant helm installed charts:
rancher-2.5.9 (v2.5.9)
rancher-logging-3.9.400 (3.9.4)
rancher-logging-crd  (rancher-logging-crd-3.9.400)
```

RKE2 release
```
# rke2 --version
rke2 version v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)
go version go1.16.6b7
```

**Information about the Cluster**
- Kubernetes version:
-  v1.21.3+rke2r1
```
WHATEVER1 Ready    control-plane,etcd,master   4d19h   v1.21.3+rke2r1
WHATEVER2 Ready    control-plane,etcd,master   4d22h   v1.21.3+rke2r1
WHATEVER3 Ready    control-plane,etcd,master   4d19h   v1.21.3+rke2r1
WHATEVERW1 Ready    ingress,rancher,worker      5d      v1.21.3+rke2r1
WHATEVERW2 Ready    ingress,rancher,worker      4d22h   v1.21.3+rke2r1
WHATEVERW3 Ready    ingress,rancher,worker      4d21h   v1.21.3+rke2r1
WHATEVERW4 Ready    worker                      4d      v1.21.3+rke2r1
```

- Cluster Type Local.
- Infrastructure hyper-v deployment.

**Describe the bug**
Multiple configuration requirements not meet for deploying Rancher´s cattle-logging-system.
It seems to me that securityContext values configured during deployment of helm (helm values defined in Rancher catalog view) will not be used correctly.

For example, in rancher-logging-fluentd-0 pod.
```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true

....
....

  securityContext:
    fsGroup: 101
    supplementalGroups:
    - 1
```
I managed to make it work replacing StafulSet manifest with appropriate values (I added manually  runAsUser: 1000 in the securityContext key of the current statefulset) , but I get read access errors due to the fact that  /fluentd/log/out will never be accesible to non-root users. I changed to /tmp and started to work, but after some minutes statefulset is redeployed and all changes are lost (is this automated?).

These problem also applies to rancher-logging-rke2-containers-fluentd

On the other hand, with SElinux enabled and configured in during deployment of helm (helm values defined in Rancher catalog view), I get access errors to /proc files in rancher-logging-fluentbit pods:
```
 kubectl describe pod rancher-logging-fluentbit-5kr8ll

  Warning  Failed     37m (x5 over 38m)      kubelet            Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown
```
This seems related to non-working selinux labels or accesses. Latest rke2-selinux package is applied, but problem persists. I also used restorecon to verify that appropriate labels are applied. I don´t see any errors on /var/log/messages.
```
# rpm -qa|grep selinux
selinux-policy-3.14.3-67.el8.noarch
rke2-selinux-0.7-1.el8.noarch
libselinux-2.9-5.el8.x86_64
selinux-policy-targeted-3.14.3-67.el8.noarch
usbguard-selinux-1.0.0-2.el8.noarch
container-selinux-2.162.0-1.module+el8.4.0+11311+9da8acfb.noarch
python3-libselinux-2.9-5.el8.x86_64
rpm-plugin-selinux-4.14.3-14.el8_4.x86_64
libselinux-utils-2.9-5.el8.x86_64
```

**To Reproduce**
Deploy logging from Rancher 2.5.9 catalog using following yaml:
```
additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
  rke:
    enabled: false
    fluentbit:
      log_level: info
      mem_buffer_limit: 5MB
  rke2:
    enabled: true
affinity: {}
annotations: {}
createCustomResource: false
disablePvc: true
extraArgs: []
fluentbit:
  resources: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: 'true'
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: 'true'
fluentd:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    tcpSocket:
      port: 24240
  resources: {}
  securityContext: {"runAsNonRoot": true, "runAsUser": 1000, "fsGroup": 2000, "allowPrivilegeEscalation": false}
fullnameOverride: ''
global:
  cattle:
    systemDefaultRegistry: ''
  dockerRootDirectory: ''
  psp:
    enabled: true
  seLinux:
    enabled: true
http:
  port: 8080
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: rancher/mirrored-banzaicloud-logging-operator
  tag: 3.9.4
imagePullSecrets: []
images:
  config_reloader:
    repository: rancher/mirrored-jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.6.10-debug
  fluentd:
    repository: rancher/mirrored-banzaicloud-fluentd
    tag: v1.11.5-alpine-12
  nodeagent_fluentbit:
    os: 'windows,linux'
    repository: rancher/fluent-bit
    tag: 1.6.10
monitoring:
  serviceMonitor:
    additionalLabels: {}
    enabled: true
    metricRelabelings: []
    relabelings: []
nameOverride: ''
namespaceOverride: ''
nodeAgents:
  tls:
    enabled: true
nodeSelector:
  kubernetes.io/os: linux
podLabels: {}
podSecurityContext: {"runAsNonRoot": true, "runAsUser": 1000, "fsGroup": 2000}
priorityClassName: {}
rbac:
  enabled: true
  psp:
    enabled: true
replicaCount: 1
resources: {}
securityContext: {"runAsNonRoot": true, "runAsUser": 1000, "allowPrivilegeEscalation": false, "readOnlyRootFilesystem": true}
systemdLogPath: /run/log/journal
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```

**Result**
```
(⎈ |rke2c-secure:cattle-logging-system)>> kubectl get pods
NAME                                                           READY   STATUS                       RESTARTS   AGE
rancher-logging-57c4b957cd-mjjmk                               1/1     Running                      0          61m
rancher-logging-fluentbit-556vz                                0/1     CrashLoopBackOff             16         61m
rancher-logging-fluentbit-5kr8l                                0/1     CrashLoopBackOff             10         29m
rancher-logging-fluentbit-nfqxv                                0/1     CrashLoopBackOff             16         61m
rancher-logging-fluentbit-qqdgm                                0/1     CrashLoopBackOff             16         61m
rancher-logging-fluentd-0                                      1/2     CreateContainerConfigError   0          34m
rancher-logging-fluentd-configcheck-c3054702                   0/1     Completed                    0          61m
rancher-logging-rke2-containers-fluentbit-ntmbb                0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-containers-fluentbit-qb5j5                0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-containers-fluentbit-sd9pz                0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-containers-fluentbit-whhcr                0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-containers-fluentd-0                      1/2     CreateContainerConfigError   0          61m
rancher-logging-rke2-containers-fluentd-configcheck-c3054702   0/1     Completed                    0          61m
rancher-logging-rke2-journald-aggregator-66btg                 0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-journald-aggregator-95ssm                 0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-journald-aggregator-f5q5j                 0/1     CrashLoopBackOff             16         61m
rancher-logging-rke2-journald-aggregator-fkm6z                 0/1     CrashLoopBackOff             16         61m
```

rancher-logging-fluentd daemonset issues:
```
 kubectl describe pod rancher-logging-fluentd-0

Warning  Failed     34m (x11 over 35m)   kubelet            Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root (pod: "rancher-logging-fluentd-0_cattle-logging-system(0ee1b17d-5b04-4524-8935-1bd8e58c6b66)", container: fluentd)
```

**Expected Result**
Well, first I expect to propagate all defined values to appropriate values in manifests, and logging should work with selinux enabled and CIS-1.5 profile applied on RKE2 secure environment.

**Additional context**
RKE2, with SElinux enabled at OS level and RKE2 level, with CIS.15 secure profile applied.

Please let me know any additional information required. Many logging components are implied in this issue.

**Comment by kphunter** [comment]
I never achieved a successful deployment on an selinux-enabled system - even without CIS-1.5 profile set... (described here: https://github.com/rancher/rke2/issues/1649).

**Comment by frjaraur** [comment]
I will try to explain all the steps, configurations I did (with some workarounds) and issues found.

My RKE2 cluster is build on top of Red Hat 8.4 (customized with CIS security settings). __SElinux in enabled in Enforcing mode__. 
```
$ rke2 --version
rke2 version v1.21.3+rke2r1 (2ed0b0d1b6924af4414393cd1796c174a1ff5352)
go version go1.16.6b7


>> kubectl get nodes
NAME            STATUS   ROLES                       AGE   VERSION
whatevercc1   Ready    control-plane,etcd,master   28d   v1.21.3+rke2r1
whatevercc2   Ready    control-plane,etcd,master   28d   v1.21.3+rke2r1
whatevercc3   Ready    control-plane,etcd,master   28d   v1.21.3+rke2r1
whateverwc1   Ready    ingress,rancher,worker      28d   v1.21.3+rke2r1
whateverwc2   Ready    ingress,rancher,worker      28d   v1.21.3+rke2r1
whateverwc3   Ready    ingress,rancher,worker      28d   v1.21.3+rke2r1
whateverwc4   Ready    worker                      27d   v1.21.3+rke2r1
```

My RKE2 settings:
```
# cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0600"
profile: "cis-1.5"
selinux: true
disable-cloud-controller: true
token: "WHATEVERTOKEN"
tls-san:
- rke2c.whatever
cluster-cidr: "10.42.0.0/16"
service-cidr: "10.43.0.0/16"
cluster-dns: "10.43.0.10"
cluster-domain: "rke2.secure"
node-taint:
- "node-role.kubernetes.io/master=true:NoSchedule"
```

Therefore CIS 1.5 for RKE2 is applied and we have a bunch of PSP applied by default.

I first tried logging charts deployment using latest Rancher 2.5 release catalog, I found issues regarding PSP settings (reported to banzaicloud/logging-operator here [https://github.com/banzaicloud/logging-operator/issues/830](https://github.com/banzaicloud/logging-operator/issues/830)). I tried different combinations for the logging deployment at "values" configuration using Rancher GUI but finally moved to helm charts provided by banzaicloud. The problem I found is that fluentd deployment does not inherit neither Security Context nor Pod Security Context configurations when logging-operator-logging is applied. After some research and tries, I was able to make it work patching logging definition created.

```
spec:
  fluentd:
    fluentOutLogrotate:
      enabled: false
    security:
      podSecurityPolicyCreate: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
```
This patch solves two issues: 
- "Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root " is found because runAsUser isn´t applied from helm´s values configuration. I apply at "logging" resource these podSecurityContext to correctly configure the fluentd StatefulSet generated by the controller.
- I had to disable fluentOutLogrotate because logs will be written in /fluentd/logs/out, which is not writable for the user with ID 1000 (not sure which is the "fluent" user´s ID and I just wanted to make it work).

In the meantime, I upgraded to Rancher 2.6 and tried everything again. I was in the same situation but I managed to make Rancher´s catalog Logging using following values file (after some tries combining Pod Security Context and Security Context), anyway, patch should be applied on "logging" resource (in this case rancher-logging).
This is the full values file applied to Rancher's catalog Logging deployment:
```
# Values file used for Rancher-Logging deployment.

additionalLoggingSources:
  aks:
    enabled: false
  eks:
    enabled: false
  gke:
    enabled: false
  k3s:
    container_engine: systemd
    enabled: false
    stripUnderscores: false
  kubeAudit:
    auditFilename: ''
    enabled: false
    fluentbit:
      logTag: kube-audit
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/controlplane
          value: 'true'
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          value: 'true'
    pathPrefix: ''
  rke:
    enabled: false
    fluentbit:
      log_level: info
      mem_buffer_limit: 5MB
  rke2:
    enabled: true
    stripUnderscores: false
affinity: {}
annotations: {}
createCustomResource: true
disablePvc: true
extraArgs:
  - '-enable-leader-election=true'
fluentbit:
  inputTail:
    Buffer_Chunk_Size: ''
    Buffer_Max_Size: ''
    Mem_Buf_Limit: ''
    Multiline_Flush: ''
    Skip_Long_Lines: ''
  resources: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: 'true'
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: 'true'
  security:
    podSecurityPolicyCreate: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000  
fluentd:
  bufferStorageVolume: {}
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    tcpSocket:
      port: 24240
  nodeSelector: {}
  resources: {}
  tolerations: {}
  fluentOutLogrotate:
    enabled: false
  security:
    podSecurityPolicyCreate: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000    
fullnameOverride: ''
global:
  cattle:
    systemDefaultRegistry: ''
  dockerRootDirectory: ''
  psp:
    enabled: false
  rkeWindowsPathPrefix: c:\
  seLinux:
    enabled: true
http:
  port: 8080
  service:
    annotations: {}
    clusterIP: None
    labels: {}
    type: ClusterIP
image:
  pullPolicy: IfNotPresent
  repository: rancher/mirrored-banzaicloud-logging-operator
  tag: 3.12.0
imagePullSecrets: []
images:
  config_reloader:
    repository: rancher/mirrored-jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.7.9
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.7.9-debug
  fluentd:
    repository: rancher/mirrored-banzaicloud-fluentd
    tag: v1.12.4-alpine-1
  nodeagent_fluentbit:
    os: windows
    repository: rancher/fluent-bit
    tag: 1.7.4
monitoring:
  serviceMonitor:
    additionalLabels: {}
    enabled: false
    metricRelabelings: []
    relabelings: []
nameOverride: ''
namespaceOverride: ''
nodeAgents:
  tls:
    enabled: false
nodeSelector:
  kubernetes.io/os: linux
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
priorityClassName: {}
rbac:
  enabled: true
  psp:
    annotations:
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
      seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
    enabled: true
replicaCount: 1
resources: {}
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
     drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 1000
systemdLogPath: /run/log/journal
tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
```
Notice that selinux configurations are applied (rancher-selinux is also installed), PodSecurityContext and SecurityContext are configured, but as I said, they are not really working (not applied to neither fluentd dm nor sts).
__The funny thing here is that rke2-logging is not deployed even it is configured (it will be deployed using default values file, but of course it does not works because PSP features).__

I patched rancher-logging with security settings:
```
kubectl patch logging rancher-logging --patch "$(cat rancher-logging.patch.yaml)" --type=merge
```

This is the complete patch file:
```
spec:
  fluentbit:
    security:
      serviceAccount: rancher-logging
  fluentd:
    fluentOutLogrotate:
      enabled: false
    security:
      podSecurityPolicyCreate: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: rancher-logging
```

You can notice that I added "rancher-logging" Service Account. As I realized that rke2-logging wasn´t deployed, I prepared my own logging resource (using customized values from other rke cluster settings, paths will change of course). 
I just prepared a simple audit-logging logging resource with /var/lib/rancher/rke2/server/logs/audit.log, just to get this log.
This is teh content of my audit-logging-rke2.logging.yaml 
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  labels:
    app.kubernetes.io/name: audit-logging
  name: audit-logging-rke2
spec:
  controlNamespace: logging
  fluentbit:
    security:
      podSecurityPolicyCreate: true
      serviceAccount: rancher-logging
    extraVolumeMounts:
    - destination: /var/lib/rancher/rke2/server/logs
      readOnly: true
      source: /var/lib/rancher/rke2/server/logs
    image:
      repository: rancher/fluent-fluent-bit
      tag: 1.6.4
    inputTail:
      Parser: json
      Path: /var/lib/rancher/rke2/server/logs/audit.log
      Tag: rke2
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      value: "true"
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      value: "true"
  fluentd:
    fluentOutLogrotate:
      enabled: false
    security:
      podSecurityPolicyCreate: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: rancher-logging
    configReloaderImage:
      repository: rancher/jimmidyson-configmap-reload
      tag: v0.2.2
    disablePvc: true
    image:
      repository: rancher/banzaicloud-fluentd
      tag: v1.11.5-alpine-1
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
```
Because PSP are applied and by default hostPath volumes are not allowed to be used I tried adding rancher-logging service account but I am still stuck with following event:
```
13m         Warning   FailedCreate   daemonset/rancher-logging-rke2-journald-aggregator   Error creating: pods "rancher-logging-rke2-journald-aggregator-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```

I found that my settings are not applied:
```
 kubectl get ds rancher-logging-rke2-journald-aggregator  -o yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: rancher-logging
    meta.helm.sh/release-namespace: cattle-logging-system
  creationTimestamp: "2021-09-15T12:41:35Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rancher-logging-rke2-journald-aggregator
  namespace: cattle-logging-system
  resourceVersion: "16840954"
  uid: 2266df4c-6ed2-4f57-866b-7171446243e2
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: rancher-logging-rke2-journald-aggregator
  template:
    metadata:
      annotations:
        checksum/config: 2f9f5c4dd58a8c52ea3331479642e88da00b897d93b00a91e449ac8bb0895c7c
      creationTimestamp: null
      labels:
        name: rancher-logging-rke2-journald-aggregator
      name: rancher-logging-rke2-journald-aggregator
      namespace: cattle-logging-system
    spec:
      containers:
      - image: rancher/mirrored-fluent-fluent-bit:1.7.9
        imagePullPolicy: IfNotPresent
        name: fluentbit
        resources: {}
        securityContext:
          seLinuxOptions:
            type: rke_logreader_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluent-bit/etc/
          name: config
        - mountPath: /run/log/journal
          name: journal
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/agent/logs/kubelet.log
          name: kubelet
          readOnly: true
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rancher-logging-rke2-journald-aggregator
      serviceAccountName: rancher-logging-rke2-journald-aggregator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      volumes:
      - configMap:
          defaultMode: 420
          name: rancher-logging-rke2
        name: config
      - hostPath:
          path: /run/log/journal
          type: ""
        name: journal
      - hostPath:
          path: /var/lib/rancher/rke2/agent/logs/kubelet.log
          type: ""
        name: kubelet
      - hostPath:
          path: /etc/machine-id
          type: ""
        name: machine-id
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```
Neither Security Context nor Service Account are configured with my settings. Not sure if my values are not valid or just operator does not use them. And the thing is that rancher-logging-rke2-journald-aggregator does not have any PSP associated, but rancher-logging does, with the right hostPath permissions

📙 PSP rancher-logging-fluentd
└── 📓 Role cattle-logging-system/rancher-logging-fluentd-psp
    └── 📓 RoleBinding cattle-logging-system/rancher-logging-fluentd-psp
        └── 📗 Subject{Kind: ServiceAccount, Name: rancher-logging, Namespace: cattle-logging-system}

```
>> kubectl get psp rancher-logging-fluentd
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
rancher-logging-fluentd   false          RunAsAny   MustRunAs   MustRunAs   MustRunAs   false            configMap,emptyDir,secret,hostPath,persistentVolumeClaim
```
And this is where I am stuck now.... sorry for this long and probably chaotic steps and workarounds description.

I will love to make everything work with Rancher´s catalog Logging, but patches and issues found because I think it is not really prepared for secure environments.

If I finally make it work I will write a guide and try to fix/PR the patches and workarounds used.

Let me know if there is something you want me to try.

**Comment by kphunter** [comment]
And so, @frjaraur, did you ever get it to work?

**Comment by The-Loeki** [comment]
Update from my lab @frjaraur it seems to work with these fixes in place, @frjaraur thanks for the extensive writeup for me to build upon!

## Setup
Fedora 35/rke2-selinux-0.9-1.el8 (no specific hardening benchmark) / rke2-1.22_cis-1.6 / cilium

## Used Chart values

```yaml
global:
  seLinux:
    enabled: true
  psp:
    enabled: true

additionalLoggingSources:
  rke2:
    enabled: true
  kubeAudit:
    enabled: true

fluentd:
  podSecurityPolicy:
    create: true

```

## UID constraint
### runAsNonRoot 
Logging/Statefulset FluentD 
```
CreateContainerConfigError: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root 
```
As discussed above, error+fix say it all. 
*Needs `securityContext.runAsUser` with a numeric value in `StatefulSet` through `Logging`.*
Inspecting the containers 100 is the assumed value for `fluent`.

_DevOps cannot hack this through the chart's values currently._


### Clobbering the image overlay with no perms
```
$ k logs statefulset/rancher-logging-fluentd fluentd

(...)
/usr/lib/ruby/2.7.0/logger/log_device.rb:103:in `initialize': Permission denied @ rb_sysopen - /fluentd/log/out (Errno::EACCES)
(...)
```
Notice using the "container-native" uid didn't matter.
Banzaicloud [strongly suggests](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/fluentd/#fluentoutlogrotate) nót disabling this.
AFAICT `/fluentd(/log)` is not ever mounted as separate Volume, which would mean that it's clobbering the overlayfs which should've been ReadOnlyRoot anyway.
So rather than looking at the perms issue further
*I opted for relaying the `path` to `/buffers/fluentd.log`* 

Buffers ís a Volume with it's own extensive config for persistence, this had no permissions issue regardless of uid.
Some talk in other places of placing `FLUENTD_UID=` in env to help FluentD along but haven't needed it yet.

_DevOps cannot hack this through the chart's values currently._

### PatchSet

`kubectl patch logging/rancher-{logging,logging-kube-audit} --type merge --patch-file modules/k8s-mods/mf/patch-rancher-logging.yml`:
```yaml
spec:
  fluentd:
    fluentOutLogrotate:
      path: /buffers/fluentd.log  # Logs to writable volume
    security:
      podSecurityContext:
        runAsUser: 100            # Numeric uid for mustRunAsNonRoot
```


## SELinux
``` 
$ kubectl describe pod
(...)
failed to create containerd task: failed to create shim: OCI runtime create failed: 
container_linux.go:380: starting container process caused:
process_linux.go:545: container init caused: 
failed to set /proc/self/attr/keycreate on procfs: 
write /proc/self/attr/keycreate: invalid argument: unknown
(...)
```

This error usually means kernel says no to SELinux type change.
This is AFAIK nót a violation of policy but a broken/missing one.
Indeed, replacing `rke_logreader_t` with e.g. OS-delivered `spc_t` makes all at least start again.
```
[root@same-rig ~]# podman run --rm -it --security-opt label=type:rke_logreader_t quay.io/theloeki/toolbox:drhalo bash 
Error: `/proc/self/attr/keycreate`: OCI runtime error: unable to process security attribute
```
Yup other container engines also cannot do it.

OP had RHEL8/rke2-selinux-0.7-1, I have F35/rke2-selinux-0.9-1.el8. Yet 
```
[root@same-rig ~]# seinfo -t|grep rke
   rke2_service_db_t
   rke2_service_t
```

Sure enough @cbron and @brandond added `rke_logreader_t` to rke2-selinux in https://github.com/rancher/rke2-selinux/pull/13 only to revert 3 weeks later https://github.com/rancher/rke2-selinux/pull/15 and hasn't returned since.
Based on their reasoning when adding it it seems some components of this policy might not be necessary for rke2 but trying the generic `container_logreader_t` they based this off solves the error while running into new ones.



## OPEN
* What do i do with {{- $containerLogPath := printf "%s/containers/" (default "/var/lib/docker" .Values.global.dockerRootDirectory) }} considering rke2 has no docker anymore


### Hotfix the SELinux policy

`rke2_hotfix_logreader.te`
```
policy_module(rke2_hotfix_logreader, 1.0)
# HOTFIX https://github.com/rancher/rancher-selinux/blob/main/policy/centos8/rancher.te

########################
# type rke_logreader_t #
########################
gen_require(`
        type container_runtime_t, unconfined_service_t;
        type container_log_t;
        type syslogd_var_run_t;
        type var_log_t;
        class dir { read search };
        class file { open read };
        class lnk_file { getattr read };
')
container_domain_template(rke_logreader)
virt_sandbox_domain(rke_logreader_t)
corenet_unconfined(rke_logreader_t)
allow rke_logreader_t container_log_t:dir { open read search };
allow rke_logreader_t container_log_t:lnk_file { getattr read };
allow rke_logreader_t container_log_t:file { getattr open read };
allow rke_logreader_t container_var_lib_t:dir search;
allow rke_logreader_t container_var_lib_t:file { getattr open read };
allow rke_logreader_t container_var_lib_t:lnk_file { getattr read };
allow rke_logreader_t syslogd_var_run_t:dir read;
allow rke_logreader_t syslogd_var_run_t:file { getattr map open read };
allow rke_logreader_t var_log_t:dir read;
allow rke_logreader_t var_log_t:file { getattr map open read };
```
```
make -f /usr/share/selinux/devel/Makefile rke2_hotfix_logreader.pp
sudo semodule -i ./rke2_hotfix_logreader.pp 
seinfo -t|grep rke
```
Should show the `rke_logreader_t` available & working
