### ISSUE TITLE
Running CIS 1.6 hardened scan after installing CIS Benchmark in local, hardened cluster fails

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#34409]
**Rancher Server Setup**
- Rancher version: v2.6.0-rc5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
         Node Setup: Single node all roles
         Version: `v1.2.11`
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: `v1.18.12`
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

After following instructions in https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/ to provision a hardened cluster, installing CIS Benchmark and running a one-time `rke-profile-hardened-1.6` Scan fails.

**To Reproduce**
 

1. Provision a node and run the following commands provided in https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#configure-kernel-runtime-parameters and https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#create-etcd-user-and-group.
```bash
curl https://releases.rancher.com/install-docker/20.10.sh | sh

mkdir -p /etc/sysctl.d

cat << EOF > /etc/sysctl.d/90-kubelet.conf
vm.overcommit_memory=1
vm.panic_on_oom=0
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
EOF

sysctl -p /etc/sysctl.d/90-kubelet.conf

groupadd --gid 52034 etcd
useradd --comment "etcd service account" --uid 52034 --gid 52034 etcd
```
2. Create an A record pointing at the node; this will be HOSTNAME
3. On my local machine, run `rke up --ssh-agent-auth` using the following `cluster.yml`, supplying the path to the SSH keys to the node under SSH_KEY_PATH, as copied from https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-cluster-yml-configuration:

```yaml
nodes:
  - address: HOSTNAME
    user: root
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: SSH_KEY_PATH
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 52034
    gid: 52034
    snapshot: false
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    service_cluster_ip_range: ""
    service_node_port_range: ""
    pod_security_policy: true
    always_pull_images: false
    secrets_encryption_config:
      enabled: true
      custom_config: null
    audit_log:
      enabled: true
      configuration: null
    admission_configuration: null
    event_rate_limit:
      enabled: true
      configuration: null
  kube-controller:
    image: ""
    extra_args:
      feature-gates: RotateKubeletServerCertificate=true
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_cidr: ""
    service_cluster_ip_range: ""
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
  kubelet:
    image: ""
    extra_args:
      feature-gates: RotateKubeletServerCertificate=true
      protect-kernel-defaults: "true"
      tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: ""
    fail_swap_on: false
    generate_serving_certificate: true
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    win_extra_args: {}
    win_extra_binds: []
    win_extra_env: []
network:
  plugin: ""
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
authentication:
  strategy: ""
  sans: []
  webhook: null
addons: |
  apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: restricted
  spec:
    requiredDropCapabilities:
    - NET_RAW
    privileged: false
    allowPrivilegeEscalation: false
    defaultAllowPrivilegeEscalation: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: MustRunAsNonRoot
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - emptyDir
    - secret
    - persistentVolumeClaim
    - downwardAPI
    - configMap
    - projected
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: default-allow-all
  spec:
    podSelector: {}
    ingress:
    - {}
    egress:
    - {}
    policyTypes:
    - Ingress
    - Egress
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
  automountServiceAccountToken: false
addons_include: []
system_images:
  etcd: ""
  alpine: ""
  nginx_proxy: ""
  cert_downloader: ""
  kubernetes_services_sidecar: ""
  kubedns: ""
  dnsmasq: ""
  kubedns_sidecar: ""
  kubedns_autoscaler: ""
  coredns: ""
  coredns_autoscaler: ""
  nodelocal: ""
  kubernetes: ""
  flannel: ""
  flannel_cni: ""
  calico_node: ""
  calico_cni: ""
  calico_controllers: ""
  calico_ctl: ""
  calico_flexvol: ""
  canal_node: ""
  canal_cni: ""
  canal_controllers: ""
  canal_flannel: ""
  canal_flexvol: ""
  weave_node: ""
  weave_cni: ""
  pod_infra_container: ""
  ingress: ""
  ingress_backend: ""
  metrics_server: ""
  windows_pod_infra_container: ""
ssh_key_path: ""
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: ""
  options: {}
ignore_docker_version: false
kubernetes_version: v1.18.12-rancher1-1
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
cluster_name:
cloud_provider:
  name: ""
prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
restore:
  restore: false
  snapshot_name: ""
dns: null
upgrade_strategy:
  max_unavailable_worker: ""
  max_unavailable_controlplane: ""
  drain: null
  node_drain_input: null
```
4. Run `export KUBECONFIG=kube_config_cluster.yml` in the directory that you ran `rke up --ssh-agent-auth` within
5. Run the following commands to finish setting up the CIS 1.16 Hardened Cluster, adapted from https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#set-automountserviceaccounttoken-to-false-for-default-service-accounts and https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#ensure-that-all-namespaces-have-network-policies-defined

```
cat <<EOF > account_update.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
automountServiceAccountToken: false
EOF

cat <<EOF > account_update.sh
for namespace in \$(kubectl get namespaces -A -o json | jq -r '.items[].metadata.name'); do
  kubectl patch serviceaccount default -n \${namespace} -p "\$(cat account_update.yaml)"
done
EOF

cat <<EOF > default-allow-all.yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
EOF

cat <<EOF > apply_networkPolicy_to_all_ns.sh
for namespace in \$(kubectl get namespaces -A -o json | jq -r '.items[].metadata.name'); do
  kubectl apply -f default-allow-all.yaml -n \${namespace}
done
EOF

chmod +x account_update.sh
chmod +x apply_networkPolicy_to_all_ns.sh

./account_update.sh
./apply_networkPolicy_to_all_ns.sh

rm account_update.sh
rm account_update.yaml
rm apply_networkPolicy_to_all_ns.sh
rm default-allow-all.yaml
```

6. Run the following command to get the cluster ready to install Rancher by getting cert-manager installed:

```bash
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
helm repo add jetstack https://charts.jetstack.io
helm repo update

kubectl create namespace cattle-system

kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml
kubectl create namespace cert-manager
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.0.4
```

7. Once cert-manager pods are all ready, run the following command to install Rancher in the cluster
```
# HOSTNAME=${HOSTNAME}
RANCHER_VERSION=v2.6.0-rc5
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --version ${RANCHER_VERSION} \
  --set hostname=${HOSTNAME} --create-namespace
```
8. Log into Rancher and navigate to the local cluster -> Apps & Marketplace -> Charts -> CIS Benchmark and install the chart into the System project
  - CIS 2.0.0 from `dev-v2.6` branch of `rancher/charts` based on commit `644d0f2eaaf3dd464f4f506126474d0336d82286` 
9. Navigate to CIS Benchmark -> Scan -> Create and trigger a one-time `rke-profile-hardened-1.6` Scan. Wait for it to complete and assert that it passes.

**Result**

CIS Scan fails.

**Expected Result**

CIS Scan should pass.

**Screenshots**

#### CIS values.yaml

![Screen Shot 2021-08-23 at 7 16 05 PM](https://user-images.githubusercontent.com/13127443/130545141-f4da979f-8976-4ca0-968d-eed661c6c160.png)

#### CIS Scan fails after following above steps

![Screen Shot 2021-08-23 at 7 26 59 PM](https://user-images.githubusercontent.com/13127443/130546107-ec866589-82ce-4a5a-9ab3-4badf67c2021.png)

#### CIS Scan still fails after repeating step 5, but with one less error

![Screen Shot 2021-08-23 at 7 28 53 PM](https://user-images.githubusercontent.com/13127443/130546287-44760766-0884-45ec-936e-8b6c4b53b494.png)

**Additional context**

Rerunning Step 5 at the very end does **not** resolve the issue. It only partially resolves the failure

Could the issue be because I am using `rke up --ssh-agent-auth`? 

#### Another Issue: Cannot get Logs

I am unsure if this is unrelated or not. I can open up another issue if so.

Downloading logs for CIS-Operator also fails with a 500 on the endpoint `RANCHER_URL/api/v1/namespaces/cis-operator-system/pods/cis-operator-58d7cff9b5-rzq29/log?container=cis-operator&previous=false&pretty=true&limitBytes=786432000`, where NODE_IP is my Rancher node's IP, which has been omitted in this issue description.

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Get https://NODE_IP:10250/containerLogs/cis-operator-system/cis-operator-58d7cff9b5-rzq29/cis-operator?limitBytes=786432000: x509: cannot validate certificate for NODE_IP because it doesn't contain any IP SANs",
  "code": 500
}
```

Running `kubectl logs -n cis-operator-system cis-operator-58d7cff9b5-rzq29` locally gives a similar error:

```bash
arvindiyengar: ~/Downloads/test2/est2/hardened_260_rc5 
$ kubectl logs -n cis-operator-system cis-operator-58d7cff9b5-rzq29
Error from server: Get https://143.198.153.37:10250/containerLogs/cis-operator-system/cis-operator-58d7cff9b5-rzq29/cis-operator: x509: cannot validate certificate for 143.198.153.37 because it doesn't contain any IP SANs
```

#### Another Issue: Helm Operation Pods get left behind Pending

I am unsure if this is unrelated or not. I can open up another issue if so.

![Screen Shot 2021-08-23 at 7 23 52 PM](https://user-images.githubusercontent.com/13127443/130545884-5dc0a900-5c4e-41c3-9cd6-97a55d6d83c8.png)

The pending Helm operation Pods appear to be using the default ServiceAccount:
```

spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - helm-cmd
    env:
    - name: KUBECONFIG
      value: /home/shell/.kube/config
    image: rancher/shell:v0.1.10
    imagePullPolicy: IfNotPresent
    name: helm
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /home/shell/helm
      name: data
    - mountPath: /home/shell/.kube/config
      name: user-kubeconfig
      readOnly: true
      subPath: config
    workingDir: /home/shell/helm
  - command:
    - sh
    - -c
    - kubectl proxy --disable-filter || true
    env:
    - name: KUBECONFIG
      value: /root/.kube/config
    image: rancher/shell:v0.1.10
    imagePullPolicy: IfNotPresent
    name: proxy
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /root/.kube/config
      name: admin-kubeconfig
      readOnly: true
      subPath: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: pod-impersonation-helm-op-87brr-token-k9lhm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: arvind-260rc5-hardened.cp-dev.rancher.space
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    key: cattle.io/os
    operator: Equal
    value: linux
  - effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: node.cloudprovider.kubernetes.io/uninitialized
    operator: Equal
    value: "true"
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    secret:
      defaultMode: 420
      secretName: helm-operation-tsfvd
  - configMap:
      defaultMode: 420
      name: impersonation-helm-op-admin-kubeconfig-kjt9q
    name: admin-kubeconfig
  - configMap:
      defaultMode: 420
      name: impersonation-helm-op-user-kubeconfig-r6nx6
    name: user-kubeconfig
  - name: pod-impersonation-helm-op-87brr-token-k9lhm
    secret:
      defaultMode: 420
      secretName: pod-impersonation-helm-op-87brr-token-k9lhm
```

Diagnosed as part of reproducing https://github.com/rancher/rancher/issues/34188.
