### ISSUE TITLE
RKE2 Provisioning: Day 2 Ops - On Demand/Recurring Etcd Snapshot and Restore with Options

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#34417]
This is to validate S3 Support for snapshot and restore. 

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  rkeConfig:

#    etcdSnapshotCreate:
#      name: string
#      nodeName: string
#      s3:
#        bucket: string
#        cloudCredentialName: string
#        endpoint: string
#        endpointCA: string
#        folder: string
#        region: string
#        skipSSLVerify: boolean
```

Note: Things changed with https://github.com/rancher/rancher/issues/34088
An s3-compatible cloud credential was created, you can create one and specify when making a cluster, and override defaults (if any are set).
