### ISSUE TITLE
Rancher metadata returning wrong numbers

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3441]
Look at this:

rancher-compose.yml
```
test:
  metadata:
    config:
      "log.index.size.max.bytes": 10485760
```

in the container:

```
curl http://rancher-metadata/latest/services/test/metadata/config/log.index.size.max.bytes
1048576
```

Missing trailing zero(s).

Thanks,
Matteo

**Comment by m4ce** [comment]
It's actually a pretty bad bug. I have applications whose timers are expressed in milliseconds and all the trailing zeros are removed.

**Comment by vincent99** [comment]
This was fixed a couple weeks ago (https://github.com/rancher/rancher-metadata/pull/8) but a new rancher-metadata wasn't packaged into 0.56 @ibuildthecloud

**Comment by sangeethah** [comment]
Tested with server version - v0.57.0-rc1

Trailing zeros are not lost when fetching metadata .

Created service with following rancher-compose.yml

```
test:
  metadata:
    config:
      "log.index.size.max.bytes": 10485760
```
From within container:

```
curl http://rancher-metadata/latest/services/test/metadata/config/log.index.size.max.bytes
10485760
```

@m4ce : This fix should be available in the  next rancher server release.
