### ISSUE TITLE
Unable to explore imported RKE2 clusters in Vue UI - imported RKE2 cluster shows Connected = false in mgmt cluster conditions

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34519]
**Summary:**
When you import any RKE2 cluster into the Vue UI you cannot explore it. Thus you cannot create any projects/namespaces/apps/workloads. It is "useless" to import an RKE2 cluster in the Vue UI today for the most part since we can't really do much with it. We can't deploy stuff to the cluster. This is NOT the case with an imported RKE1 cluster. An imported RKE1 cluster in the Vue UI works as expected.

I checked that the imported rke2 cluster is fully up. The cluster appears to be fully and properly registered. When I check conditions on the management.cattle.io.cluster it looks nominal.

Last, when I try to explore this imported cluster in the ember UI - it works fine.

It appears that any RKE2 cluster that gets imported does not have the condition "Connected" set to True - it is false. This appears to be why this won't be explorable in the Vue UI.

**Environment:**
Rancher version: v2.6-head `6d10a6d50` pulled at 8/27/21 11:45 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2 imported - SINGLE NODE in my case
Downstream K8s version: v1.21.3+rke2r1

**Steps to Reproduce:**
1. Import a single-node RKE2 cluster. To do this you can just run the following on the node:
`curl -sfL https://get.rke2.io | sh -` 
This will install the latest stable release of RKE2. RKE2 does not install kubectl for you, so you can either [install kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) on the node, or just grab the kubeconfig from /etc/rancher/rke2/rke2.yaml on the node.
2. Import the cluster in the Vue UI. This succeeds. The imported RKE2 cluster becomes active and checking conditions on management cluster show that Connected is NOT true:
```
conditions:
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2021-08-27T20:01:30Z"
    status: "True"
    type: Pending
  - lastUpdateTime: "2021-08-27T20:01:34Z"
    status: "True"
    type: Provisioned
  - lastUpdateTime: "2021-08-27T20:01:45Z"
    status: "True"
    type: Waiting
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: "2021-08-27T19:58:57Z"
    status: "True"
    type: NoMemoryPressure
  - lastUpdateTime: "2021-08-27T20:02:45Z"
    status: "False"
    type: Connected
  - lastUpdateTime: "2021-08-27T20:01:31Z"
    status: "False"
    type: AlertingEnabled
  - lastUpdateTime: "2021-08-27T20:01:32Z"
    status: "True"
    type: SystemAccountCreated
  - lastUpdateTime: "2021-08-27T20:01:34Z"
    status: "True"
    type: AgentDeployed
  - lastUpdateTime: "2021-08-27T20:01:34Z"
    status: "True"
    type: Updated
  - lastUpdateTime: "2021-08-27T20:01:34Z"
    status: "True"
    type: GlobalAdminsSynced
  - lastUpdateTime: "2021-08-27T20:01:34Z"
    status: "False"
    type: PrometheusOperatorDeployed
  - lastUpdateTime: "2021-08-27T20:01:45Z"
    status: "True"
    type: Ready
```
![image](https://user-images.githubusercontent.com/45179589/131189967-18646ce6-9321-46c3-8ef2-1b843c448c2d.png)
The cluster is active but connected never switches to true
```
    type: Connected
  - lastUpdateTime: "2021-08-27T20:01:31Z"
    status: "False"
```

3. Try to explore the cluster. This is grayed out in the Vue UI:
![image](https://user-images.githubusercontent.com/45179589/131190005-ecba44f0-a750-4fdb-9332-52aa0f57d655.png)
![image](https://user-images.githubusercontent.com/45179589/131190024-5d51aa1e-daf5-4fb2-adf7-8aeb0347a655.png)

4. Now, go to the ember UI. We can explore the cluster there and create projects/namespaces/apps/workloads.
_To get to the ember UI you can go to `https://serverIP_or_FQDN/g`_
![image](https://user-images.githubusercontent.com/45179589/131190126-07b48f98-3511-4cc6-a771-f58f89379cc6.png)
Note, clicking the Explorer button may result in an error, but we can click on the link for the cluster to browse in ember.
![image](https://user-images.githubusercontent.com/45179589/131190269-10eec2c8-6301-484e-bbc1-181d61602a18.png)

The Vue UI requires that the Connected condition be True.

**Expected Result:**
I expected to be able to explore the imported RKE2 cluster in the Vue UI.

**Actual Result:**
I cannot explore the imported RKE2 cluster in the Vue UI. I can in the ember UI.
The Vue UI is waiting for the Connected condition to be True. It will never switch to True.
