### ISSUE TITLE
Missing Permissions in catalog management roles

### ISSUE THREAD

**Issue by ryansann** [rancher/rancher#34592]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Cluster Type (Local/Downstream): local

**Describe the bug**

The builtin `catlaogs-manage` GlobalRole is missing permissions for verb: `*` on resource: `clusterrepos`, this permissions grants the ability to manage chart repositories. 

**To Reproduce**
 
- After Rancher starts, run: `kubectl get globalroles catalogs-manage -o yaml` against the local cluster

**Result**
```yaml
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - catalogs
  - templates
  - templateversions
  verbs:
  - '*'
```

**Expected Result**

```yaml
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - catalogs
  - templates
  - templateversions
  verbs:
  - '*'
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - '*'
```

**Comment by ryansann** [comment]
Testing steps:

Start Rancher v2.6.0 (version without this change)
Create a standard user, check the "Configure Catalogs" builtin role
Add new user as a member to a cluster (local or downstream)
Log in as user and go to Apps & Marketplace > Chart Repositories in the cluster
Note that chart repositories cannot be modified in any way
Upgrade to this PR
Refresh browser, user can modify chart repositories
catalogs-manage GlobalRole:

rules:
- apiGroups:
  - management.cattle.io
  resources:
  - catalogs
  - templates
  - templateversions
  verbs:
  - '*'
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - '*'

**Comment by ryansann** [comment]
This issue needs to be backported to 2.5

**Comment by ryansann** [comment]
Small change to this. After some discussions, I've also added:
```yaml
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - '*'
```
to the `clustercatalogs-manage` Role.

The `clusterrepo` permissions are not being added to the `projectcatalogs-manage` role because there is no concept of project level catalogs in dashboard / `catalog.cattle.io`

**Comment by anupama2501** [comment]
Reproduced on v2.6.0

1. Created an rke1 and rke2 node driver clusters
2. Created a standard user -user1, and added `configure catalog` option in the global permissions.
3. Added the user as a cluster member and logged in as user1
4. From apps & market --> chart repos no options were available for the user to change the repos

**Comment by anupama2501** [comment]
On v2.6-head 1a57856

Api groups are added in the rules in the local cluster after upgrading the rancher server:
`kubectl get globalroles catalogs-manage -o yaml`

```
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - catalogs
  - templates
  - templateversions
  verbs:
  - '*'
- apiGroups:
  - catalog.cattle.io
  resources:
  - clusterrepos
  verbs:
  - '*'
```

- Upgraded rancher server to v2.6-head
- Created a new user with `Configure cluster` in the global permissions assigned.
- Added the user in the local, rke1 and rke2 cluster as a cluster member
- standard user in the local cluster, can edit/delete/create repositories from apps&Market --> charts
- User in rke1 and rke2 downstream clusters for the same user cannot still edit/remove/add

@ryansann 
Standard user in rke1 and rke2 clusters can edit the repositories if we add an additional permission to the user in the cluster RBAC `Manage Cluster Catalogs` but for local cluster even without that permission a cluster member can manage the catalogs.
