### ISSUE TITLE
Best practice for prometheus monitoring field.cattle.io/workloadMetrics vs ServiceMonitors

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rancher/rancher#34654]
Right now I couldn't find a clean documentation on whats the best way to collect custom prometheus data..

We played around over 2.4, 2.5 and now 2.6 and it seems that something like following works (without extra ServiceMonitor):

```yaml
  template:
    metadata:
      annotations:
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":9394,"schema":"HTTP"}]'
```

But on the other hand, other components require a ServiceMonitor and it looks like the mentioned cattle configuration above doesn't work..

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom1-prometheus-exporter-service-monitor
  labels:
    app: custom1-prometheus-exporter-service-monitor
spec:
  selector:
    matchLabels:
      app: custom1-prometheus-exporter
  endpoints:
  - port: prometheus
    scheme: http
```

And sometimes it is recommended to add following annotations, f.e.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: custom1-prometheus-exporter
  labels:
    app: custom1-prometheus-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9394'
```

Could you tell me (or improve the documentation) what is now the recommended way of collecting custom prometheus data?
It's really confusing, since there are so many examples to find in google and it's not really clear what is up to date... :/

Thank you so much for your great work! ❤️
