### ISSUE TITLE
helm upgrade/delete intermittently fails with errors like "unable to create impersonator account: error setting up impersonation for user u-xxxxx..Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again."

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#34671]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): **?**
- Proxy/Cert Details: **?**

**Information about the Cluster**
- Kubernetes version: **?**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): **?**

**Describe the bug**

Running `helm upgrade` / `helm uninstall` for an unknown application intermittently fails with errors like this:
```
error: unable to recognize "/tmp/kubectl_replace_486731274/resource.stdin": an error on the server ("unable to create impersonator account: error setting up impersonation for user u-8j72f: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding
```
```
Error: uninstall: Release not loaded: katana-api-dev: query: failed to query with labels: an error on the server ("unable to create impersonator account: error setting up impersonation for user u-8j72f: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding (get secrets)
```

**Additional context**

Created from the following comment: https://github.com/rancher/rancher/issues/34187#issuecomment-914575796

**Comment by snasovich** [comment]
@andrew-landsverk-win , so far I'm not successful with reproducing it. Tried installing/uninstalling couple charts a few times via Helm v3.6.0 on a single-cluster RKE2 downstream cluster - all successful.
How often do you get these errors? Also, I'm wondering if you could share helm charts you're trying to install as well as details on your downstream cluster and k8s versions on both the downstream cluster and Rancher cluster itself.

**Comment by andrew-landsverk-win** [comment]
Some details: Downstream cluster is microk8s (3 nodes, k8s 1.21.3), I am not using the authorized cluster endpoint, we are calling rancher directly using the rancher API to create the kubeconfig. Then using that kubeconfig with helm and kubectl commands via CI pipelines.

Helm version is 3.6.2 and the error occurs when trying to upgrade or delete a chart, I'm not sure about install as I haven't tested that extensively yet. One example of a chart where this happened on is: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak the rest are internal charts that are based off of the GitLab auto-deploy chart. 

It doesn't occur consistently but it does occur enough to cause me to not want to upgrade our production Rancher cluster yet.

**Comment by davidnuzik** [comment]
@anupama2501 to try to reproduce this before the weekend.

**Comment by snasovich** [comment]
@andrew-landsverk-win , so far I could not reproduce it, but others are looking into it as well.
Couple questions:
1. I'm guessing you're using non-admin credentials in this flow. What kind of user is it and what access they have to downstream cluster and Rancher cluster?
2. How often does keycloak chart upgrade/uninstall fails? I understand it happens often enough for you to hold off upgrading, but it would be helpful for us to know for reproduction. One out of how many times on average does it fail?

**Comment by andrew-landsverk-win** [comment]
The user is a local rancher user, globally they have:

- Create new clusters
- create RKE template revisions
- use catalogs

For the downstream cluster, they are a `Cluster Owner`.

On average, I'd guess 1 in 5 times? It's been inconsistent so far :( 

Is there something else I can look into the next time it fails, some logs somewhere?

**Comment by snasovich** [comment]
@andrew-landsverk-win , thank you for this additional info, this is helpful.

As for the logs, there is logging for this added impersonation code, but most of them are at TRACE level. So if's feasible to enable trace logging for your Rancher pod(s) (or Docker container if that's how you're running it), these logs could be helpful. Since those will be rather large, knowing exact time stamp you've got the failure would help a lot with narrowing down our search.

**Comment by andrew-landsverk-win** [comment]
Sure, how would I go about enabling TRACE on the rancher pods?

**Comment by snasovich** [comment]
@andrew-landsverk-win , this should help: https://rancher.com/docs/rancher/v2.6/en/troubleshooting/logging/

**Comment by andrew-landsverk-win** [comment]
Looks good, I'll try to capture it next time it happens, although I don't think I'll leave trace on too long without watching it :)

**Comment by snasovich** [comment]
@cmurphy , since you're back on Monday and it much more familiar with this code than anyone else, please investigate this issue.

**Comment by anupama2501** [comment]
I'm not able to reproduce either. I tried the following:
1. Created a rancher HA
2. Created 1 user with global permissions - user1 :
- Create new clusters
- create RKE template revisions
- use catalogs
3. Create a cluster as user1
4. Using the kubeconfig, and via helm `v3.4.1`, installed the app `helm install keycloak codecentric/keycloak`  and upgraded it a few times `helm upgrade --install keycloak`, have not seen the error mentioned
4. Downloaded rancher cli and logged in as admin and added the catalog `codecentric https://codecentric.github.io/helm-charts` 
5. as user1 from rancher cli installed the app `./rancher app install keycloak codecentric/keycloak` , and don't see the error mentioned above.

@andrew-landsverk-win would you be able to provide us any helm upgrade commands that were used or how the app was installed and the upgraded ?

**Comment by andrew-landsverk-win** [comment]
Sure, the process goes like this:

1. Login to rancher cluster via Rancher CLI 2.4.12 as `Cluster Owner` user via token, to obtain kubeconfig file: `rancher login $KUBE_SERVER -t $KUBE_TOKEN --context $KUBE_PROJECT_ID`
2. Write out a kubeconfig file: `
`rancher kubectl config view --raw > ~/.kube/config``
2. Use said kubeconfig file to launch helm `v3.6.3` : 
`helm upgrade --install --values values.yaml --namespace=keycloak --version=15.0.2 --repo=codecentric keycloak keycloak`

values.yaml: 
```
---
replicas: 2
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list

affinity: |
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - keycloak-dev
        topologyKey: kubernetes.io/hostname

resources:
  requests:
    cpu: "1000m"
    memory: "2048Mi"
  limits:
    cpu: "1000m"
    memory: "2048Mi"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  rules:
    - host: dev-keycloak.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev-keycloak.example.com
      secretName: star-example-com
```

**Comment by snasovich** [comment]
@andrew-landsverk-win , thank you for providing this additional info.
Couple follow up questions / requests:
1. I see you run `helm upgrade --install` - does the app exist on the downstream cluster already and is actually being upgraded or it doesn't exist and fresh install is actually run?
2. If would be great If you could provide full output of `helm` command on an attempt that has failed.
Thank you for your help with investigating this.

**Comment by andrew-landsverk-win** [comment]
1. The app may or may not exist when you run helm that way, if it doesn't exist, it gets created, if it does, it gets upgraded
2. This is all I get when it failed:
```
W0907 12:43:53.267131      51 helpers.go:557] --dry-run is deprecated and can be replaced with --dry-run=client.
error: unable to recognize "/tmp/kubectl_replace_486731274/resource.stdin": an error on the server ("unable to create impersonator account: error setting up impersonation for user u-8j72f: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding
```

**Comment by andrew-landsverk-win** [comment]
I'm unsure about that first bit of the error `/tmp/kubectl_replace_XXXXXX/resource.stdin` could be an issue on the machine running `kubectl` or something on the node? However, these errors only showed up when upgrading to rancher `2.6.0` so it's still unclear to me :) I really appreciate the help though!

**Comment by cmurphy** [comment]
Hi @andrew-landsverk-win, I have a couple of clarification questions:

* Is the local Rancher cluster a helm deployment on a kubernetes cluster, or a docker installation?
* If it's a helm install, how many nodes is it running on?
* When you say "these errors only showed up when upgrading to rancher 2.6.0", that's an in-place upgrade from `2.5.9` to `2.6.0`, not a fresh `2.6.0` install, right?

**Comment by andrew-landsverk-win** [comment]
In this case, it is a single node helm install and yes it was an in place upgrade from 2.5.9 to 2.6.0.

**Comment by ctrox** [comment]
I just ran into a very similar sounding issue. I also upgraded from 2.5.9 to 2.6.0. Plus I changed over from Keycloak SAML to OIDC as the auth provider. This might be relevant here as I observed the following:

While I was getting the error

`unable to create impersonator account: error setting up impersonation for user u-96k65: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \\\"cattle-impersonation-u-96k65\\\": the object has been modified`

I checked said `clusterRole` in the affected RKE cluster and noticed that the resource kept being updated by rancher. What changed between each resource version was the order of the `resourceNames` in the `rules` of the `clusterRole`:

```yaml
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-96k65
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - keycloakoidc_group://SomeGroup
  - keycloak_group:///SomeGroup
  - system:authenticated
  - system:cattle:authenticated
 ```

next resource version:

```yaml
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-96k65
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - keycloak_group:///SomeGroup
  - keycloakoidc_group://SomeGroup
  - system:authenticated
  - system:cattle:authenticated
 ```

Notice that the two keycloak group names have switched position. The issue in the code seems to be more or less [here](https://github.com/rancher/rancher/blob/6a0a991109ca2e88aff9687300b2fe5a70ff8e49/pkg/impersonation/impersonation.go#L177). Because the `resourceNames` do not appear to be ordered this `DeepEqual` frequently returns `false`.

So I'm not actually sure if this only can happen if you have two auth providers configured but I guess a simple sort on that `resourceNames` slice should fix this.

@andrew-landsverk-win Does your user also have groups attached?

**Comment by andrew-landsverk-win** [comment]
@ctrox  here are the rules for my `ClusterRole`:

```yaml
rules:
- apiGroups:
  - ""
  resourceNames:
  - u-8j72f
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - system:authenticated
  - system:cattle:authenticated
  resources:
  - groups
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - local://u-8j72f
  resources:
  - userextras/principalid
  verbs:
  - impersonate
- apiGroups:
  - authentication.k8s.io
  resourceNames:
  - gitlab-deploy
  resources:
  - userextras/username
  verbs:
  - impersonate
```
