### ISSUE TITLE
Rancher 2.6 Cannot Login

### ISSUE THREAD

**Issue by clayrisser** [rancher/rancher#34686]
I deployed rancher 2.6 and cannot login. I followed the instructions for getting the bootstrap password, and it does not work.

https://rancher.com/docs/rancher/v2.6/en/installation/resources/bootstrap-password/

I get the following error from the Rancher UI.

```
Logging in failed: Check credentials, or your account may not be authorized to log in.
```

I tried deploying rancher with a custom bootstrap password and it also failed with the same login error.

```sh
      helm install rancher rancher-latest/rancher \
        --version ${rancher_version} \
        --namespace cattle-system \
        --set hostname=${hostname} \
        --set ingress.tls.source=letsEncrypt \
        --set bootstrapPassword=Passw0rd \
        --set letsEncrypt.email=${email}
```

**Comment by tabnul** [comment]
I have the same issue, Rancher 2.6 on EKS.
Tried downgrading to 2.5.9 (after helm delete) . No option given to  reset the default password, normally it asks for this.
Helm delete doesnt remove all resources, possibly leaving conflicting resources behind?

**Comment by tabnul** [comment]
After a re-deploy of the entire EKS cluster, and immediately setting the bootstrappassword in the helm values it works correctly.

Not setting it apparently breaks any new installation of rancher on the kubernetes cluster afterwards.

**Comment by all4innov** [comment]
> After a re-deploy of the entire EKS cluster, and immediately setting the bootstrappassword in the helm values it works correctly.
> 
> Not setting it apparently breaks any new installation of rancher on the kubernetes cluster afterwards.

Same conclusion: with EKS version 1.20, it's mandatory to set bootstrap password in helm, else the secret will be empty. 
The autogenerated password is not working well with EKS.

**Comment by paynejacob** [comment]
Changing the bootstrap password secret after will not affect the admin password.  The secret is only used once when the admin user is created.  If the secret is not found rancher will set it for easy reference.  If a password is not set on helm install there can be a delay between the helm install finishing and rancher setting the password.  @clayrisser when you say the linked instructions do not work did you see a generated password in that secret? Did the secret exist?

**Comment by tabnul** [comment]
In my case, even after an hour there was no password , secret was still empty. No bootstrappassword set.

**Comment by atrauzzi** [comment]
Experiencing the same on RKE2.  Password ended up blank, can't figure out how to get things going again, feels like state is pocketed all over the place by Rancher and any failure sends me on a chase to reset it.

I wish there was a way to tell RKE2 to just wipe itself clean. That way even if I encounter issues like this one, I can avoid the lingering state as I figure out the **perfect** incantations.

**Comment by paynejacob** [comment]
The rancher docs for uninstalling rancher do not use helm uninstall they use system-tools remove to uninstall rancher.  Following the steps outlined in this document I am able to uninstall rancher and re-install it on the same cluster.

https://rancher.com/docs/rancher/v2.5/en/faq/removing-rancher/#what-if-i-don-t-want-rancher-anymore

using the system tools remove command I am able to re-install rancher after uninstalling.

```
#!/bin/bash
k3d cluster delete issue-34686 || true
k3d cluster create issue-34686

kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml

helm upgrade \
  --install \
  --create-namespace \
  --namespace cert-manager \
  --create-namespace \
  --version v1.5.1 \
  cert-manager \
  jetstack/cert-manager

helm upgrade \
        --install \
        --create-namespace \
        --version 2.6.1 \
        --namespace cattle-system \
        --set hostname=rancher.local \
        rancher \
        rancher-latest/rancher

until [ $(kubectl -n cattle-system get secret/bootstrap-secret -o json | jq -r '.data.bootstrapPassword | length') -gt 0 ]; do
  sleep 0.1
done

echo "bootstrap password found"
kubectl -n cattle-system get secret/bootstrap-secret -o json | jq -r '.data.bootstrapPassword' | base64 -d

./system-tools remove --force

while kubectl get ns cattle-system >> /dev/null; do :; done

helm upgrade \
        --install \
        --create-namespace \
        --version 2.6.1 \
        --namespace cattle-system \
        --set hostname=rancher.local \
        rancher \
        rancher-latest/rancher

until [ $(kubectl -n cattle-system get secret/bootstrap-secret -o json | jq -r '.data.bootstrapPassword | length') -gt 0 ]; do :; done

echo "bootstrap password found"
kubectl -n cattle-system get secret/bootstrap-secret -o json | jq -r '.data.bootstrapPassword' | base64 -d
```

**Comment by paynejacob** [comment]
@clayrisser @tabnul Do you see any differences in my setup for a clean install from what you did?  If you are able to consistently reproduce the missing bootstrap password on clean install could you share detailed steps and any errors you find in your rancher logs related to the bootstrap password secret.

**Comment by tabnul** [comment]
@paynejacob I indeed used helm uninstall.
Further, i used 2.6.0 and deployed on top of EKS.

Didnt get errors during deployment. Secret was just empty when not specifying bootstrappassword

**Comment by paynejacob** [comment]
Tested this on eks and was still unable to reproduce:

1. created an eks cluster with Kubernetes 1.21
2. added a node group with 2 t3.medium nodes
3. got cluster kubeconfig with aws cli
4. `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.1/cert-manager.crds.yaml`
5. `helm upgrade --install --create-namespace --namespace cert-manager --create-namespace --version v1.5.1 cert-manager jetstack/cert-manager`
6. `helm upgrade --install --create-namespace --version 2.6.1 --namespace cattle-system --set hostname=rancher.local rancher rancher-latest/rancher`
7. `kubectl -n cattle-system get secret/bootstrap-secret -o json | jq -r '.data.bootstrapPassword'`

after about 1m I saw the bootstrap password returned.

@tabnul do you see any differences between the steps I took and the steps you took?

**Comment by JmbFountain** [comment]
Same issue on my end. If I install rancher without giving a bootstrap password, I just get an empty string returned:

```
johannes:kubeconfig/ (master✗) $ helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.nathan.home --set ingress.tls.source=secret --set additionalTrustedCAs=true
NAME: rancher
LAST DEPLOYED: Sun Nov 14 10:50:43 2021
NAMESPACE: cattle-system
STATUS: deployed
[...]
johannes:kubeconfig/ (master✗) $ echo https://rancher.nathan.home/dashboard/\?setup\=$\(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')

johannes:kubeconfig/ (master✗) $ helm get values rancher -n cattle-system -a
COMPUTED VALUES:
addLocal: "true"
additionalTrustedCAs: true
antiAffinity: preferred
auditLog:
  destination: sidecar
  hostPath: /var/log/rancher/audit/
  level: 0
  maxAge: 1
  maxBackup: 1
  maxSize: 100
bootstrapPassword: ""
busyboxImage: busybox
[...]
```
If I declare the bootstrap password in my values YAML file, I do get a bootstrap password accordingly. However, by experimenting with all this stuff I seem to have broken something... (Can't access the web UI anymore, end of file error)

[rancher_values.txt](https://github.com/rancher/rancher/files/7533539/rancher_values.txt)

----
running on k3s:
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
