### ISSUE TITLE
Quota scopes in Rancher

### ISSUE THREAD

**Issue by San-Pedror** [rancher/rancher#34703]
Hi,

In Kubernetes there is the option to add [quota scopes](https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-scopes) to your ResourceQuota object, however there is no such option in the Rancher UI. Is this something that you could implement? I have tried adding scopeSelector with a webhook to create the file underneath, but I keep getting errors which seem to be coming from rancher stating that the the action I am trying to perform is unsupported. Do you know if what I am trying to do is possible?

Thanks!

``` yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
  scopeSelector:
    matchExpressions:
      - scopeName: Terminating
        operator: Exists
```
