### ISSUE TITLE
Provision rke2 cluster from 3rd party node driver

### ISSUE THREAD

**Issue by danbaie** [rancher/rancher#34782]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.21.4+rke2r3
- Proxy/Cert Details: lets-encrypt

**Information about the Cluster**
- Kubernetes version: v1.21.4+rke2r3
- Cloud provider: Hetzner Cloud

**Describe the bug**

Cannot create RKE2 cluster from RancherUI because I can't create cloud credentials for hetzner node driver.

**To Reproduce**
 
- Add Hetzner node driver to Rancher via UI
- Go to Cluster Management -> Cluster -> Create
- Get prompted a form where I can create cloud credentials
![image](https://user-images.githubusercontent.com/83769222/133759887-52b83b74-1e11-4b59-a722-3349a623e558.png)
- Add information and click on create
- Get prompted a dropdown list where I can select the cloud provider to use
- Dropdown list is empty
![image](https://user-images.githubusercontent.com/83769222/133760851-c37f930a-04e8-475b-80d3-bc61779d9bc4.png)

I tried to add cloud credentials from the cloud credentials menu but there is no option for hetzner or custom or similar.
I tried to activate some of the built-in node drivers in rancher and some have the same problem but some work.

**Result**
Not able to provision RKE2 cluster with Hetzner node driver because of cloud credentials

**Expected Result**

I should be able to create cloud credentials in some way. When activating a node driver, the cloud provider should be added to the list of creatable cloud credentials.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>
Maybe I am just to stupid to find the right option. All I want to do is use the node driver to spawn servers on hetzner and provision a RKE2 cluster on these servers. This should happen automated like I can already do for RKE.

**Comment by Negashev** [comment]
Fix on [2.6.3](https://github.com/rancher/rancher/issues/33392)?

**Comment by phal0r** [comment]
@Negashev 
Can you tell, when your fix will be merged? I can provision VMs with your workaround aswell. But initializing rancher gets stuck. The last log entry is `Custom install script was sent via userdata, provisioning complete...`. So I guess, this is the same problem.

**Comment by Negashev** [comment]
@phal0r 
I don’t know when it will be merged, it’s out of my control

**Comment by apo2k7** [comment]
Are there any news to this? I ran into the exact problem. @Negashev did you find a workaround if this dosn't get fixed?

**Comment by Negashev** [comment]
@apo2k7 
I have not yet found the right solution, in the pull request, they offer me a fix, but I have not tested it) https://github.com/rancher/machine/pull/153

Work with yandex
```yaml
apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  annotations:
    privateCredentialFields: saKeyFile
  name: yandex  # fix name
spec:
  active: true
  addCloudCredential: false
  builtin: false
  checksum: ""
  description: ""
  displayName: yandex
  externalId: ""
  uiUrl: ""
  url: https://github.com/yandex-cloud/docker-machine-driver-yandex/releases/download/v0.1.35/docker-machine-driver-yandex_0.1.35_linux_amd64.tar.gz
```

but problem with ENV name in rancher YANDEX_* in docker-driver YC_*

and we can't hide `token` to YANDEX_TOKEN in rancher because in yandex docker driver use YC_TOKEN

i'm not use sa-key-file and in creadential it empty)

```yaml
apiVersion: v1
data:
  yandexcredentialConfig-saKeyFile: ""
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-xxxxx
    field.cattle.io/name: My-Team
    provisioning.cattle.io/driver: yandex
  labels:
    cattle.io/creator: norman
  name: cc-xxxxx
  namespace: cattle-global-data
type: Opaque

```

**Comment by dcardellino** [comment]
I also ran in this issue with Hetzner, is there any update on this issue?

**Comment by phal0r** [comment]
still relevant

**Comment by hoerup** [comment]
still relevant

**Comment by hoerup** [comment]
Still relevant

**Comment by Negashev** [comment]
I think we need to add changes on the hetzner side of the docker driver, a key that would read userdata from a file, I'll try to make a pull request today

**Comment by Audifire** [comment]
> I think we need to add changes on the hetzner side of the docker driver, a key that would read userdata from a file, I'll try to make a pull request today

Yep, that's what I also found out. I tried to change it. But sadly I have not much experience with Go and I get other errors when importing the driver. 😅

**Comment by Negashev** [comment]
Ohhhh.... nex level problem...

```
2022/12/07 02:03:47 [ERROR] error syncing 'hetzner': handler node-driver-controller: DynamicSchema.management.cattle.io "hetzner_instrumentedconfig" is invalid: metadata.name: Invalid value: "hetzner_instrumentedconfig": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```

in hetzner driver, `instrumented` auto added


rancher generate `docker-machine-driver-hetzner_instrumented`

**Comment by Negashev** [comment]
After 3.9.2 (hetzner docker machine) tar.gz include 2 binary files, it seems the rancher takes the one with the end `_instrumented`

**Comment by simonostendorf** [comment]
Getting "[ERROR] error syncing 'fleet-default/test-pool1-b0030872-r5rgz': handler machine-provision: nodedrivers.management.cattle.io "hetzner" not found, requeuing" when using your instructions @Negashev .
Any idea why third party node drivers (hetzner) not working for me?

**Comment by Negashev** [comment]
@simonostendorf 
It's important to add nodedriver in local cluster as yaml deploy with metadata/name: hetzner, not in rancher nodedriver UI

**Comment by simonostendorf** [comment]
> @simonostendorf It's important to add nodedriver in local cluster as yaml deploy with metadata/name: hetzner, not in rancher nodedriver UI

Thank you very much, i thought that if i set the name via GUI it is also possible. This fixed my initial problem, hope there will be no more big problems :D

**Comment by klauserber** [comment]
The Solution does not working for me. It fixes the driver filename successfully and there are no related error messages in the log or on screen anymore. But I still cannot create a credential for Hetzner, the key field is not populated.

The Version 3.10.1 is switching back the driver name, so we should not need this workaround anymore. But this Version is also not working for me to create RKE2 clusters. Btw, the creation of RKE clusters works fine.

**Comment by Negashev** [comment]
@klauserber 
I create `Cloud Credential`, before i create cluster
![image](https://user-images.githubusercontent.com/4653589/216906787-70250ef3-4a82-4581-87e6-70eec42c7509.png)
![image](https://user-images.githubusercontent.com/4653589/216906903-06f7c76a-ea04-4083-806d-c9cd29061655.png)

**Comment by klauserber** [comment]
@Negashev 
ok, interesting. That solves it. The Hetzner NodeDriver CR has the privateCredentialFields annotation.

I already have tried to create a credential as a Secret like so:
```
apiVersion: v1
kind: Secret
metadata:
  name: cc-test
  namespace: cattle-global-data
  labels:
    cattle.io/creator: norman
  annotations:
    field.cattle.io/creatorId: user-r8flk
    field.cattle.io/name: hetzner
    provisioning.cattle.io/driver: hetzner
type: Opaque
stringData:
  apiToken: XXXX  
```

But this secret does not appear in the UI. After that I can add Hetzner Cloud Credentials. The resulting secrets have a Field called `hetznercredentialConfig-apiToken` an the `provisioning.cattle.io/driver: hetzner` is obviously not needed.

```
apiVersion: v1
kind: Secret
metadata:
  name: cc-lab2-2
  namespace: cattle-global-data
  labels:
    cattle.io/creator: norman
  annotations:
    field.cattle.io/creatorId: user-r8flk
    field.cattle.io/name: hetzner-lab2-2
type: Opaque
stringData:
  hetznercredentialConfig-apiToken: XXXX
```

Now I have the Hetzner credentials type and I can create them and get into the UI.

Don't understand it completely, but it works. Thank you.
