### ISSUE TITLE
cis.f5.com VirtualServer CRDs do not load in the Rancher Cluster Explorer

### ISSUE THREAD

**Issue by bmayfi3ld** [rancher/rancher#34790]
**Rancher Server Setup**
- Rancher version:
2.6.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
 Helm, RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
1.21
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Custom, RHEL7 boxes, RKE 1.21

**Describe the bug**

When trying to view cis.f5.com virtual servers the screen gets stuck at loading and never shows the resources. 

This error appears in the console

```
Error: The intl string context variable "count" was not provided to the string "{count, plural,
  one { Host }
  other { Hosts }
}"
    at new t (formatters.js:25)
    at K (formatters.js:86)
    at W (formatters.js:174)
    at e.format (core.js:61)
    at i18n.js:103
    at $ (type-map.js:917)
    at Object.<anonymous> (type-map.js:873)
    at f.headers (index.vue:80)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.evaluate (vue.runtime.esm.js:4584)
```

**To Reproduce**
 
 
Install cis.f5.com crd, create virtual server resource. Try to view resource in cluster explorer.

```yaml
Name:         virtualservers.cis.f5.com
Namespace:
Labels:       app.kubernetes.io/instance=f5-bigip-ctlr
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=f5-bigip-ctlr
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-09-17T16:41:28Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:scope:
        f:versions:
    Manager:      helm
    Operation:    Update
    Time:         2021-09-17T16:41:28Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
          k:{"type":"Established"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
          k:{"type":"NamesAccepted"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
            f:type:
    Manager:         kube-apiserver
    Operation:       Update
    Time:            2021-09-17T16:41:28Z
  Resource Version:  175401
  UID:               af7b6af4-4b2c-4973-84ba-c61dcfc5e41f
Spec:
  Conversion:
    Strategy:  None
  Group:       cis.f5.com
  Names:
    Kind:       VirtualServer
    List Kind:  VirtualServerList
    Plural:     virtualservers
    Short Names:
      vs
    Singular:  virtualserver
  Scope:       Namespaced
  Versions:
    Additional Printer Columns:
      Description:  hostname
      Json Path:    .spec.host
      Name:         host
      Type:         string
      Description:  TLS Profile attached
      Json Path:    .spec.tlsProfileName
      Name:         tlsProfileName
      Type:         string
      Description:  Http Traffic Termination
      Json Path:    .spec.httpTraffic
      Name:         httpTraffic
      Type:         string
      Description:  IP address of virtualServer
      Json Path:    .spec.virtualServerAddress
      Name:         IPAddress
      Type:         string
      Description:  ipamLabel for virtual server
      Json Path:    .spec.ipamLabel
      Name:         ipamLabel
      Type:         string
      Description:  IP address of virtualServer
      Json Path:    .status.vsAddress
      Name:         IPAMVSAddress
      Type:         string
      Json Path:    .metadata.creationTimestamp
      Name:         Age
      Type:         date
    Name:           v1
    Schema:
      openAPIV3Schema:
        Properties:
          Spec:
            Properties:
              Allow Vlans:
                Items:
                  Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9-_]+\/?)*$
                  Type:     string
                Type:       array
              Host:
                Pattern:  ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
                Type:     string
              Http Traffic:
                Type:  string
              I Rules:
                Items:
                  Type:  string
                Type:    array
              Ipam Label:
                Type:  string
              Pools:
                Items:
                  Properties:
                    Monitor:
                      Properties:
                        Interval:
                          Type:  integer
                        Recv:
                          Type:  string
                        Send:
                          Type:  string
                        Timeout:
                          Type:  integer
                        Type:
                          Enum:
                            http
                            https
                          Type:  string
                      Required:
                        type
                        send
                        interval
                      Type:  object
                    Node Member Label:
                      Pattern:  ^[a-zA-Z0-9][-A-Za-z0-9_.]{0,61}[a-zA-Z0-9]=[a-zA-Z0-9][-A-Za-z0-9_.]{0,61}[a-zA-Z0-9]$
                      Type:     string
                    Path:
                      Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$
                      Type:     string
                    Rewrite:
                      Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$
                      Type:     string
                    Service:
                      Pattern:  ^([A-z0-9-_+])*([A-z0-9])$
                      Type:     string
                    Service Port:
                      Maximum:  65535
                      Minimum:  1
                      Type:     integer
                  Type:         object
                Type:           array
              Rewrite App Root:
                Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$
                Type:     string
              Service Address:
                Items:
                  Properties:
                    Arp Enabled:
                      Type:  boolean
                    Icmp Echo:
                      Enum:
                        enable
                        disable
                        selective
                      Type:  string
                    Route Advertisement:
                      Enum:
                        enable
                        disable
                        selective
                        always
                        any
                        all
                      Type:  string
                    Spanning Enabled:
                      Type:  boolean
                    Traffic Group:
                      Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$
                      Type:     string
                  Type:         object
                Max Items:      1
                Type:           array
              Snat:
                Type:  string
              Tls Profile Name:
                Type:  string
              Virtual Server Address:
                Pattern:  ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
                Type:     string
              Virtual Server HTTP Port:
                Maximum:  65535
                Minimum:  1
                Type:     integer
              Virtual Server HTTPS Port:
                Maximum:  65535
                Minimum:  1
                Type:     integer
              Virtual Server Name:
                Pattern:  ^([A-z0-9-_+])*([A-z0-9])$
                Type:     string
              Waf:
                Pattern:  ^\/([A-z0-9-_+]+\/)*([A-z0-9]+\/?)*$
                Type:     string
            Type:         object
          Status:
            Properties:
              Vs Address:
                Type:  string
            Type:      object
        Type:          object
    Served:            true
    Storage:           true
    Subresources:
      Status:
Status:
  Accepted Names:
    Kind:       VirtualServer
    List Kind:  VirtualServerList
    Plural:     virtualservers
    Short Names:
      vs
    Singular:  virtualserver
  Conditions:
    Last Transition Time:  2021-09-17T16:41:28Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-09-17T16:41:28Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>
```

```yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: nginx-vip
  labels:
    f5cr: "true"
spec:
  host: test.sk8s.organization.org
  virtualServerAddress: "10.88.126.22"
  pools:
    - path: /
      service: ngnix-service
      servicePort: 80
```

**Result**
GUI is stuck on "Loading..."

Error in Console. (Attached above)

**Expected Result**

Resources appear and are visible. 

**Screenshots**

![image](https://user-images.githubusercontent.com/563214/133842431-cedadf32-b928-490f-b269-be09ed961806.png)

**Additional context**
<!--Add any other context about the problem here.—>
