### ISSUE TITLE
Failures seen when rke-profile-permissive-1.6 scan is run on an rke1 node driver cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34807]
**On 2.6-head commit id: `1a57856`**

- Deploy CIS chart - 2.0.1 version with these images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.6-rc1
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.4-rc1
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.53.2
```
- Run CIS scan `rke-profile-permissive-1.6` on a 1 etcd+cp and 1 worker node cluster (RKE1 EC2 node driver cluster)
- There are 6 failures.
[scan-h977z-xbs5r--2021-09-18-132053.csv](https://github.com/rancher/rancher/files/7190641/scan-h977z-xbs5r--2021-09-18-132053.csv)

**Note:**
With CIS 2.0.0 version, permissive scan works fine. No failures are seen

**Comment by paynejacob** [comment]
Looks like the scan is running tests specific to a given role on nodes that do not have that role.

**Comment by paynejacob** [comment]
looks related to this commit https://github.com/rancher/security-scan/commit/d7071178a48d01e3ec8ad03403847a63b9e5b8b0#diff-4c5afb79b816098b6fd0be966e352312bd3cebd2ff416b72957019bcf28eb381R62

**Comment by prachidamle** [comment]
Yes, this is the change added for k3s. https://github.com/rancher/cis-operator/issues/100 cc @dereknola

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ba43472`**

- CIS Benchmark version - 2.0.1
- Images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.6-rc1
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.4-rc2
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.53.2
```
- On a custom cluster - 1 etcd + cp and 3 worker nodes
- RUn `rke-profile-permissive-1.6` CIS scan on the cluster 
- No Failures as expected
<img width="1446" alt="Screen Shot 2021-09-20 at 11 37 49 PM" src="https://user-images.githubusercontent.com/26032343/134123220-2ffe2463-0024-4a49-aeae-75867dfa41de.png">
