### ISSUE TITLE
Service shown as "degraded" for no reason

### ISSUE THREAD

**Issue by rdigiorgio** [rancher/rancher#3494]
Hi,

My environment:
Rancher: v0.51.0
Cattle: v0.130.0
User Interface: v0.78.0
Rancher Compose: v0.7.0

I am currently experiencing something that seems to be a bug.
Here is the problematic stack to reproduce the problem:

```
couchbase-server:
  restart: always
  image: couchbase/server:community-4.0.0
  net: host
  volumes_from:
   - couchbase-data
  labels:
      io.rancher.scheduler.global: true
      io.rancher.scheduler.affinity:host_label: host.role=couchbase
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: couchbase-data
  tty: true
  stdin_open: true

couchbase-data:
  image: couchbase/server:community-4.0.0
  entrypoint: /bin/true
  net: none
  volumes:
   - /opt/couchbase/var
  labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
  tty: true
  stdin_open: true
```

The stack is created, containers also are.
couchbase-server container is running fine, and sidekick is stopped.
BUT, in web interface, my service shows up as "degraded".

I tried something else to debug it, and found out that removing the label "io.rancher.scheduler.global: true" fixed the problem.
Another working solution, with global scheduling enabled, is to remove the sidekick.
