### ISSUE TITLE
RKE: Mismatch between GUI and created Yaml

### ISSUE THREAD

**Issue by BiggA94** [rancher/rancher#35042]
**Rancher Server Setup**
- Rancher version: 2.6.0

**Information about the Cluster**
Desired Kubernetes version: v1.19.15-rancher1-2
Actual deployed: v1.21.5-rancher1-1

**Describe the bug**
I want to create a RKE Cluster with version v1.19.15-rancher1-2. If I change the Version of the Cluster to this, and then create the Cluster, the Cluster gets provisioned with version v1.21.5-rancher1-1.

I already tried to change it in the yaml, but it seems that a lot of the configuration is ignored, e.g. extra_args for the kubelet.

I also tried to create a Cluster Template (RKE1) where I added the following yaml: 
``` yaml
# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
labels:
  provider: hcloud
local_cluster_auth_endpoint:
  enabled: true
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  authentication:
    strategy: x509
  cloud_provider:
    name: external
  dns:
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
  driver_name: rancherkubernetesengine
  ignore_docker_version: false

  ingress:
    default_backend: false
    provider: none
  kubernetes_version: v1.19.15-rancher1-2
  monitoring:
    provider: metrics-server

  network:
    options:
      flannel_backend_type: vxlan
    plugin: canal

  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      snapshot: false
    kube_api:
      pod_security_policy: false
      secrets_encryption_config:
        enabled: true
      service_node_port_range: 30000-32767
    kubelet:
      extra_args: 
        cloud-provider: "external"
    kube-controller:
       cluster_cidr: 10.0.0.0/16
         
  upgrade_strategy:
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
windows_prefered_cluster: false
```
but after I save this as Template, the yaml (via view as YAML) is only shown as:
```yaml
# 
# Cluster Config
# 
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  driver_name: rancherkubernetesengine
  kubernetes_version: v1.21.5-rancher1-1
windows_prefered_cluster: false
```

**To Reproduce**
(1) Create a new RKE1 Cluster and select version v1.19.15-rancher1-2 from select field, or via yaml.
Then create the Cluster.
(2) Create a new RKE1 Template and select version v1.19.15-rancher1-2 from select field, or via yaml. Then create it. After that, you can look at the resulting confi either via api, the gui, or the yaml in the gui.

**Result**
(1) Cluster is created with verison v1.21.5-rancher1-1 (latest?)
(2) Template is created with version v1.21.5-rancher1-1

**Expected Result**
(1) Cluster is created with verison v1.19.15-rancher1-2 
(2) Template is created with version v1.19.15-rancher1-2

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1473122/135980969-bfe30dc1-bd73-4a41-ad88-bfe090f6c4be.png)
![grafik](https://user-images.githubusercontent.com/1473122/135981081-a4a7c6a4-0424-466d-9ba9-c0b19736c90b.png)
resulting Template:
![grafik](https://user-images.githubusercontent.com/1473122/135982028-4d5de6a3-3bbe-4a5b-9467-7cce920b9a34.png)
Template in API:
![grafik](https://user-images.githubusercontent.com/1473122/135982254-c6ffa840-af3c-48f4-9185-db258ec0a4a5.png)

**Additional context**
We're using Hetzner Node Driver (https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/3.4.0/docker-machine-driver-hetzner_3.4.0_linux_amd64.tar.gz) with Hetzner Node Driver UI(https://github.com/mxschmitt/ui-driver-hetzner)
<!--Add any other context about the problem here.—>
