### ISSUE TITLE
Ignoring ingress because of error while validating ingress class" ingress="cattle-system/rancher" error="ingress does not contain a valid IngressClass

### ISSUE THREAD

**Issue by ryanpeach** [rancher/rancher#35053]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: cert-manager rancher

**Information about the Cluster**
- Kubernetes version: 1.20.0
- Cluster Type (Local/Downstream): local

**Describe the bug**
NGIX 404 Error

When running `kubectl -n ingress-nginx logs ingress-ngix-pod-...` I find the following error:

"Ignoring ingress because of error while validating ingress class" ingress="cattle-system/rancher" error="ingress does not contain a valid IngressClass"

**Additional context**
This is caused by the info described in the following documentation.

https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now

It can be resolved by adding the following option to the helm install of ingress-ngix:

`--set ingressClassResource.default=true`

Petition to add this to the documentation at the following link

https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/amazon-eks/#5-install-an-ingress

**Comment by ryanpeach** [comment]
Perhaps also `--set controller.watchIngressWithoutClass=true`

**Comment by Mtze** [comment]
I ran into exactly that problem. This should definitely be added to the documentation!

**Comment by govbetrieb** [comment]
We ran also into this problem..

**Comment by vkruoso** [comment]
Same here.

**Comment by bearrito** [comment]
Same here. Created a bug report for at https://github.com/rancher/rancher/issues/39452 before finding this issue. It should really be added to the docs.

**Comment by sandeepraj786** [comment]
It can be resolved by adding the following option to the helm install of ingress-ngix:
--set ingressClassResource.default=true

**Comment by soakes** [comment]
> Perhaps also `--set controller.watchIngressWithoutClass=true`

Thank you @ryanpeach, this resolved my issue.  For some reason using `ingress-nginx` with the following `values.yaml` didn't work until I added in the `watchIngressWithoutClass`

```
 ❯ cat values.yaml
controller:
  replicaCount: 3
  allowSnippetAnnotations: true
  service:
    type: LoadBalancer
    loadBalancerIP: "10.xx.xx.1"
    externalTrafficPolicy: "Local"
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  extraArgs:
    default-ssl-certificate: "external-secrets/example-dev-tls"
```
