### ISSUE TITLE
Add "syslog_rfc5424" format to Rancher Logging (fluentd) syslog output type

### ISSUE THREAD

**Issue by adepretis** [rancher/rancher#35113]
**Is your feature request related to a problem? Please describe.**
The `clusteroutputs.logging.banzaicloud.io` and `outputs.logging.banzaicloud.io` CRDs are missing `syslog_rfc5424` as format. The correct format is required for the Fluentd syslog output plugin formatting to work:

```
format:
  type:
    enum:
    - out_file
    - json
    - ltsv
    - csv
    - msgpack
    - hash
    - single_value
```

**Describe the solution you'd like**
Please add `syslog_rfc5424` to the CRDs `clusteroutputs.logging.banzaicloud.io` and `outputs.logging.banzaicloud.io`.

```
format:
  type:
    enum:
    - out_file
    - json
    - ltsv
    - csv
    - msgpack
    - hash
    - single_value
    - syslog_rfc5424
```
