### ISSUE TITLE
rancher-monitoring: rke2 - cis 1.6 - network-policy

### ISSUE THREAD

**Issue by chickeaterbanana** [rancher/rancher#35226]
After installing a rke2 cluster with rancher and enabled cis 1.6 prometheus isn't allowed to fetch the coredns metrics. Its missing a network policy. This policy works for me:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-coredns-policy
  namespace: kube-system
spec:
  ingress:
  - ports:
    - port: 9153
      protocol: TCP
    from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: cattle-monitoring-system
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  policyTypes:
  - Ingress
```

For better debugging it would be great to have a network debug example with nonroot container. If you use following documentation in a rke2 cis 1.6 cluster the pods didn't start.
https://rancher.com/docs/rancher/v2.6/en/troubleshooting/networking/
