### ISSUE TITLE
Rancher 2.6 - Doesn't always preserve values if they don't correspond to questions.yaml

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#35236]
**Rancher Server Setup**
- Rancher version: 2.6.1
- Installation option (Docker install/Helm Chart): Docker Install
- Proxy/Cert Details: NGINX reverse proxy

**Information about the Cluster**
- Kubernetes version: v1.20.10
- Cluster Type (Local/Downstream): Downstream, custom cluster
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
I have a simple Helm template ([can be seen here](https://github.com/ajacques/helm-catalog/tree/master/vouch-proxy)) that includes a questions.yaml, however I need to specify custom values as values.yaml. I switch to the values.yaml tab and enter my changes. Example:

```yaml
config:
  // ...
  whiteList:
    - user1
    - user2
```

When I go to submit the helm template, Rancher will delete all the custom fields and will instead generate a configuration that looks like:

```yaml
config: "null"
```

If I try to upgrade the helm template, Rancher tries to show the questions tab and then it clears out all of my custom values. Thus I am unable to use Rancher's UI to administrate this helm template without removing questions.yaml.

While Rancher 2.5.x has had it's own share of Helm bugs, this is definitely a regression between 2.5.x and 2.6.1.

**To Reproduce**
1. Try to deploy or upgrade a Helm template that contains questions.yaml and has custom values that need to be added to the values.yaml explicitly
2. Hit update and watch as Rancher fails to generate the correct yaml template

**Result**

**Expected Result**
* Rancher should not silently drop changes the values.yaml that don't match a questions.yaml if I explicitly add them
* Rancher preferably should have some better support for custom fields. e.x. more custom controls so I don't need to use Edit YAML, or some kind of indication that custom fields are added and are being maintained.

**Screenshots**

**Additional context**

**Comment by ajacques** [comment]
I can confirm this is still an issue on 2.6.2.

**Comment by ajacques** [comment]
After removing the questions.yaml, I still experience this issue. My values.yaml in the helm template looks like:
```yaml
config: null
ingress:
  tls_replicate: false
```

And the values that I enter in the UI are:
```yaml
config:
  vouch:
    domains:
    - [...]
    jwt:
      compress: true
  oauth:
    provider: oidc
    [...]
ingress:
  tls_replicate: true
  hostname: login.example.com
  ...
persistence:
  hostPath:
    path: /home/docker/vouch
  type: BindMount
```

But then Rancher installs:
```yaml
config: null
ingress:
  tls_replicate: true
  hostname: login.example.com
  ...
global:
  cattle:
    clusterId: c-bxttz
    clusterName: adamsnet
    rkePathPrefix: ''
    rkeWindowsPathPrefix: ''
    systemDefaultRegistry: ''
    url: https://rancher.example.net:8443
  systemDefaultRegistry: ''
persistence:
  hostPath:
    path: /home/docker/vouch
  type: BindMount

```
