### ISSUE TITLE
Missing ClusterRoleBinding when using unrestricted as default Cluster Policy

### ISSUE THREAD

**Issue by revog** [rancher/rancher#35242]
**Rancher Server Setup**
- Rancher version: 2.6.0 / 2.6.1
- Installation option (Docker install/Helm Chart): Helm RKE2

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): 1.21.4
Cluster Type (Local/Downstream): Downstream, Imported RKE2 on-premise VM

**Describe the bug**

**To Reproduce**
Deploy new Cluster with default PSP set to `unrestricted`

**Result**
Pods in all namespaces (except kube-system) won't start due to no usable PSP
```
Error creating: pods "cluster-deployment-tst-5b6947bcc7-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

**Expected Result**
Running pods with assigned PSP `unrestricted-psp`

**Additional context**
It seems that when using `unrestricted` PSP the needed ClusterRoleBinding does not get created. When using `RKE2 Default` or `restricted`as default policy, the ClusterRoleBinding `global-restricted-psp-rolebinding`  gets created.

Is this by design?

After creating a ClusterRoleBinding on my own, it works:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unrestricted-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unrestricted-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
