### ISSUE TITLE
Project Resource Quotas leads to wrong ResourceQuotas in Namespaces

### ISSUE THREAD

**Issue by sdillen** [rancher/rancher#35285]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option: Docker
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.5, 1.20.4 (multiple cluster)
- Cluster Type: Downstream
   - Custom

**Describe the bug**

Creating a namespace inside a project which have resource quotas configured for cpu and memory, will be converted wrongfully into the default ResourceQuota.

**To Reproduce**

Project Resource Quota:
- Project Limits:
     - CPU: 1000m
     - Memory: 1024Mi
 - Namespace Default Limits:
     - CPU: 500m
     - Memory: 512Mi

The description of the UI form imposes that 'milli CPUs' and 'MiB' are used. In the YAML object those will not be declared.

```yaml
apiVersion: management.cattle.io/v3
kind: Project
...
spec:
  namespaceDefaultResourceQuota:
    limit:
      limitsCpu: "500"
      limitsMemory: "512"
  resourceQuota:
    limit:
      limitsCpu: "1000"
      limitsMemory: "1024"
    usedLimit:
      limitsCpu: "500"
      limitsMemory: "512"
```

**Result**

```yaml
apiVersion: v1
kind: ResourceQuota
...
spec:
  hard:
    limits.cpu: "500"
    limits.memory: "512"
status:
  hard:
    limits.cpu: "500"
    limits.memory: "512"
  used:
    limits.cpu: "0"
    limits.memory: "0"
```

**Expected Result**

```yaml
apiVersion: v1
kind: ResourceQuota
...
spec:
  hard:
    limits.cpu: "500m"
    limits.memory: "512Mi"
status:
  hard:
    limits.cpu: "500m"
    limits.memory: "512Mi"
  used:
    limits.cpu: "0"
    limits.memory: "0"
```
