### ISSUE TITLE
Fail to upgrade a local RKE2 cluster if node drain is enabled

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#35310]
**Rancher Server Setup**
- Rancher version: `2.6.2`
- Installation option (Docker install/Helm Chart): rancherd 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:`v1.21.5+rke2r2`
- Cluster Type (Local/Downstream): a local cluster provisioned by rancherd
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

I enable node drain options and upgrade a local RKE2 cluster, only the first node has RKE2 upgraded. 

**To Reproduce**
 

Note: this is spotted when developing the upgrade feature in Harvester. I try to create a simple environment to reproduce this issue.

- Use rancherd to provision a RKE2 cluster (1 server + 1 worker).

    On node1 (server):
    ```
    mkdir -p /etc/rancher/rke2/config.yaml.d/
    
    cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
    disable: rke2-ingress-nginx
    EOF
    
    mkdir -p /etc/rancher/rancherd
    cat > /etc/rancher/rancherd/config.yaml << EOF
    role: cluster-init
    token: somethingrandom
    kubernetesVersion: stable:rke2
    rancherVersion: stable
    rancherValues:
      features: multi-cluster-management=true
    EOF
    curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
    ```
    
    On node2 (worker):
    ```
    mkdir -p /etc/rancher/rancherd
    cat > /etc/rancher/rancherd/config.yaml << EOF
    role: agent
    token: somethingrandom
    kubernetesVersion: stable:rke2
    rancherVersion: stable
    server: https://192.168.121.38:8443
    EOF
    curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
    ```

- After everything is OK, upgrade the local RKE2 cluster by editing the resource:
    ```
    kubectl edit clusters.provisioning.cattle.io local -n fleet-local
    ```

    change `spec` from:
    ```
    spec:
      kubernetesVersion: v1.21.5+rke2r2
      rkeConfig: {}
    ```

    to:

    ```
      kubernetesVersion: v1.21.5-rc2+rke2r3
      rkeConfig:
        upgradeStrategy:
          controlPlaneDrainOptions:
            deleteEmptyDirData: true
            enabled: true
            force: true
            ignoreDaemonSets: true
          workerDrainOptions:
            deleteEmptyDirData: true
            enabled: true
            force: true
            ignoreDaemonSets: true
    ```

**Result**

- The upgrade starts and first controller (node1) is drained.
- The rancher-system-agent on node1 upgrades the RKE2 server on node1.
- The first node is uncordened.
- The second node (node2) is not drained or upgraded.

**Expected Result**

All nodes should be drained and RKE2 on them should be upgraded.

**Screenshots**

**Additional context**
                                  
```
$ kubectlk get nodes
NAME    STATUS   ROLES                              AGE   VERSION
node1   Ready    control-plane,etcd,master,worker   16h   v1.21.5+rke2r3   <-- upgraded
node2   Ready    worker                             16h   v1.21.5+rke2r2

$ kubectl get node node1 -o yaml | grep custom
    cluster.x-k8s.io/machine: custom-90bcca39537e

$ kubectl get node node2 -o yaml | grep custom
    cluster.x-k8s.io/machine: custom-15385a9eb488
```

Not sure if this is the cause, an error in rancher:

```
2021/10/28 08:06:20 [INFO] rkecluster fleet-local/local: provisioning bootstrap node(s) custom-90bcca39537e: waiting for plan to be applied
2021/10/28 08:06:20 [ERROR] error in planner for 'fleet-local/local': Operation cannot be fulfilled on machines.cluster.x-k8s.io "custom-90bcca39537e": the object has been modified; please ap
ply your changes to the latest version and try again
2021/10/28 08:06:20 [INFO] rkecluster fleet-local/local: uncordoning bootstrap node(s) custom-90bcca39537e
2021/10/28 08:06:20 [INFO] rkecluster fleet-local/local: uncordoning bootstrap node(s) custom-90bcca39537e
2021/10/28 08:06:20 [INFO] rkecluster fleet-local/local: uncordoning bootstrap node(s) custom-90bcca39537e
2021/10/28 08:06:20 [INFO] rkecluster fleet-local/local: uncordoning bootstrap node(s) custom-90bcca39537e
```
[rancher.log](https://github.com/rancher/rancher/files/7433663/rancher.log)

**Comment by thedadams** [comment]
For this issue, I was having certificate issues as well as the uncordon problem indicated in the description. The default setting when setting up Rancher via `rancherd` is to have `tls: external`. Rancher will run Rancher with the `--no-cacerts` argument. This assumes that something in front of Rancher (a load balancer or ngrok) has a valid certificate signed by a known CA. This was not the case for me and I couldn't run `rancherd` with the default `tls: external`.

In addition, the RKE2 team has elevated v1.21.6 to the stable version. Therefore, I had to set an explicit version in the config so that I could upgrade the Kubernetes version after everything was setup.

In order to get this working properly, I had to follow these steps on node1 (server):
```
mkdir -p /var/lib/rancher/rke2/server/manifests/
curl -sfL https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml -o /var/lib/rancher/rke2/server/manifests/cert-manager.yaml

mkdir -p /etc/rancher/rke2/config.yaml.d/
cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
disable: rke2-ingress-nginx
EOF

mkdir -p /etc/rancher/rancherd
cat > /etc/rancher/rancherd/config.yaml << EOF
role: cluster-init
token: somethingrandom
kubernetesVersion: v1.21.2+rke2r1
rancherVersion: stable
rancherValues:
  features: multi-cluster-management=true
  tls: ingress
EOF
curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```

The steps for node2 and editing the `local` cluster are the same as above.

**Comment by slickwarren** [comment]
Donnie and I went through this process together on v2.6-head (7b17c57), however I was not able to get the upgrade to occur. The following was tested:
* deploy a node with hostname `ctw-server1`, and run the following on the node (from Donnie's instructions above)
```
mkdir -p /var/lib/rancher/rke2/server/manifests/
curl -sfL https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml -o /var/lib/rancher/rke2/server/manifests/cert-manager.yaml

mkdir -p /etc/rancher/rke2/config.yaml.d/
cat > /etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml <<EOF
disable: rke2-ingress-nginx
EOF

mkdir -p /etc/rancher/rancherd
cat > /etc/rancher/rancherd/config.yaml << EOF
role: cluster-init
token: somethingrandom
kubernetesVersion: v1.21.2+rke2r1
rancherVersion: v2.6-head
rancherValues:
  features: multi-cluster-management=true
  tls: ingress
EOF
curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```
* wait for the server to be healthy, then setup rancher by logging in and saving the server URL
* deploy another node with hostname `ctw-agent1` and run the following on it, replacing the URL with your server node IP (from Kiefer's instructions in the original post)
```
mkdir -p /etc/rancher/rancherd
cat > /etc/rancher/rancherd/config.yaml << EOF
role: agent
token: somethingrandom
kubernetesVersion:  v1.21.2+rke2r1
rancherVersion: v2.6-head
server: https://<your_server_node_ip>:8443
EOF
curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```

* wait for the worker to register with the server node. You should see this come to `active` as a node in the local cluster on rancher, and you could also check with kubectl get nodes from the server. 
```
ctw-agent1    Ready                      worker                             76m   v1.21.2+rke2r1
ctw-server1   Ready   control-plane,etcd,master,worker   83m   v1.21.2+rke2r1
```

* upgrade the setup by updating the following (from Kiefer's instructions in the original post)
  * editing the resource: `kubectl edit clusters.provisioning.cattle.io local -n fleet-local`
  * change spec from:
```
spec:
  kubernetesVersion: v1.21.2+rke2r1
  rkeConfig: {}
```
  * to:
```
  kubernetesVersion: v1.21.6+rke2r1
  rkeConfig:
    upgradeStrategy:
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
      workerDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
```

* REOPENING FOR THE FOLLOWING ISSUE:
  * now, the server node is not being upgraded. The rancher-agent pod on the server goes into a `pending` state, but other than that we could not find much out of the ordinary.  Donnie is aware of this issue and will try to reproduce the issue I'm seeing separately.

**Comment by thedadams** [comment]
OK. This was a oversight on my part: this issue needs an RC before it can be tested. In addition, in the `rancherd` config, the `rancherVersion` should be `latest` instead of `stable`.

Once Rancher v2.6.3-rc1 is published, this issue should be ready to test.

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by sowmyav27** [comment]
`2.6.3-rc2` is also tagged. Please use this for validation

**Comment by TachunLin** [comment]
Verified fixed on rancher `v2.6.3-rc2`. Close this issue. 

### Result
All nodes should be drained and RKE2 on them could be upgraded from `v1.21.5+rke2r2` to `v1.21.7+rke2r1`

```
node1:/etc/rancher/rke2 # kubectl get nodes
NAME    STATUS   ROLES                              AGE   VERSION
node1   Ready    control-plane,etcd,master,worker   34m   v1.21.7+rke2r1
node2   Ready    worker                             28m   v1.21.7+rke2r1
```

### Test Environment
* Rancher version: v2.6.3-rc2
* Kubernetes version: v1.21.5+rke2r2 (before upgrade) 

### Reproduce steps

1. Use rancherd to provision a RKE2 cluster (1 server + 1 worker).

On node1 (server):

```
cat > /etc/rancher/rancherd/config.yaml << EOF
role: cluster-init
token: somethingrandom
kubernetesVersion: v1.21.5+rke2r2
rancherVersion: v2.6.3-rc2
rancherValues:
  features: multi-cluster-management=true
EOF
```
On node2 (worker):
```
mkdir -p /etc/rancher/rancherd
cat > /etc/rancher/rancherd/config.yaml << EOF
role: agent
token: somethingrandom
kubernetesVersion: v1.21.5+rke2r2
rancherVersion: v2.6.3-rc2
server: https://192.168.121.38:8443
EOF
curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
```

2. After everything is OK, upgrade the local RKE2 cluster by editing the resource:
```
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
kubectl edit clusters.provisioning.cattle.io local -n fleet-local
```

change `spec:` to:
```
spec:
  kubernetesVersion: v1.21.7+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig: 
    upgradeStrategy:
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
      workerDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
```

3. Run `kubectl get nodes -w` to check status
