### ISSUE TITLE
Migration from deprecated RancherD to RKE2

### ISSUE THREAD

**Issue by lgraziosi** [rancher/rancher#35318]
Hello. A while ago we tried to install RancherD, and everything was fine.  
We installed a few custom cluster by "launching" them directly from it.  
Now that RancherD is dead, and we need to upgrade to 2.6.X, we are kind of stuck.  
The migration doesn't seem to work, since the port changes from 8443 to 443, and that breaks agents.  
If we create a new cluster directly on RKE2, we lose the "custom cluster" featureset, like certificate rotations and so on.  
What can we do here? Is there a way, for example, to change the agents to let them works vs 443 instead of 8443?  
Thank you.

**Comment by seimic** [comment]
Yes, using experimental features is sometimes not the best idea. Similar problem here... *lol*
RancherD is if I got it right rke2 bundled with the rancher chart, nothing special, only the binary has different name.

Could the following solution work? (I didn't try it yet!)

1. Backup the current rancher cluster and verify the backup is usable
2. Add additional master nodes using rke2 with same kubernetes version as rancherd \
(as many as necessary, lets say 3 for HA)
3. Copy the config manifests to the new nodes (I mean the ones from /var/log/rancher/rke2/server/manifest)
4. Cordon and drain the rancherd nodes one by one and wait the workloads to move to the new rke2-nodes
5. Verify everything works as expected (evtl. adjust your loadbalancer to forward traffic to the new nodes too)
6. Remove the rancherd nodes (from loadbalancer too)
7. Install the [System Upgrade Controller](https://github.com/rancher/system-upgrade-controller)
8. Labe the new nodes with "rke2-upgrade=true"
9. Upgrade rke2 to a newer version applying the following upgrade plan (I assume there are only master nodes!)
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: rke2-v1.21.5-rke2r2-upgrade
  server-plan
  namespace: system-upgrade
  labels:
    rke2-upgrade: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
       - {key: rke2-upgrade, operator: Exists}
       - {key: rke2-upgrade, operator: NotIn, values: ["disabled", "false"]}
       - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/rke2-upgrade
  version: v1.21.5+rke2r2
```
10. Verify rancher still works as expected
11. Set the label back to "rke2-upgrade=false" to avoid any unwanted upgrades
12. Upgrade the rancher helm chart (config). 
13. Verify the new rancher version works as expected
14. Backup everything again
15. Live long and prosper :)

Kind regards,
Michael
