### ISSUE TITLE
[Istio] k8s IP service is set to default IP which does not work for all environments

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35339]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A
- Rancher-Istio Chart Version: Starting in [100.0.2+up1.10.4](https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-istio/rancher-istio/100.0.2%2Bup1.10.4)

**Describe the bug**
Recent changes to the istio-installer resulted in the kubeconfig [using the default IP](https://github.com/rancher/istio-installer/blob/04f05d569dc5b69fdd1d29fa2f799516c37eb0db/scripts/init_kubeconfig.sh#L5) for the k8s service. This is causing issues if you are not using the default IP address for the k8s service because the istio-installer is not able to find it. 

**Expected Outcome**
Do not set the server address to a static variable in the istio-installer - instead utilize the existing ENV var or allow users to set it

**Comment by brendarearden** [comment]
Available to test on v2.6.3-rc1

**Comment by anupama2501** [comment]
Verified on v2.6.3-rc2

1. Created a node driver rke1 AWS 3 worker, 1 etcd and 1 cp cluster
2. Added the following in the edit as yaml while creating the cluster 
```
    kube-api:
      service_cluster_ip_range: 11.23.0.0/16
    kube-controller:
      service_cluster_ip_range: 11.23.0.0/16
    kubelet:
      cluster_dns_server: 11.23.0.10
```
3. Verified the kubernetes cluster IP is set to 11.23.0.1
4. Installed istio in the downstream cluster version `100.0.2+up1.10.4`
5. Verified the following error is seen 
```
unable to retrieve Pods: Get "https://10.43.0.1/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=app%3Distiod": dial tcp 10.43.0.1:443: i/o timeout
--
Mon, Nov 29 2021 8:59:15 pm | 1.10.4
Mon, Nov 29 2021 9:01:45 pm | Unable to connect to the server: dial tcp 10.43.0.1:443: i/o timeout
Mon, Nov 29 2021 9:02:45 pm | 2021-11-30T05:02:45.496357Z error analysis error getting mesh config from running kube source: Get "https://10.43.0.1/api/v1/namespaces/istio-system": dial tcp 10.43.0.1:443: i/o timeout

echo $KUBERNETES_SERVICE_HOST
11.23.0.1
```
6. Uninstalled the istio version and re-installed the version `100.1.0+up1.11.4`
7. Installation went through fine without any error but kiali crd is not installed https://github.com/rancher/rancher/issues/35686

**Comment by anupama2501** [comment]
Linked issue is only a docs issue. As the validations look god for this ticket, closing.

**Comment by vivek-infracloud** [comment]
**Verified on v2.5-head**

- Created a node driver rke1 AWS 2 worker, 1 etcd and 1 cp cluster
- Added the following in the edit as yaml while creating the cluster
```
    kube-api:
      service_cluster_ip_range: 11.23.0.0/16
    kube-controller:
      service_cluster_ip_range: 11.23.0.0/16
    kubelet:
      cluster_dns_server: 11.23.0.10
```
- Verified the kubernetes cluster IP is set to 11.23.0.1
- Installed istio in the downstream cluster version 1.10.400. 
- **Installation went through fine without any error.**
