### ISSUE TITLE
[Backport 2.5][Istio] k8s IP service is set to default IP which does not work for all environments

### ISSUE THREAD

**Issue by brendarearden** [rancher/rancher#35341]
Backport: https://github.com/rancher/rancher/issues/35339

**Comment by vivek-infracloud** [comment]
On 2.5-head provisioned a downstream cluster with 1 CP, 1 ETCD and 2 Worker nodes.

However, the Chart Repositories are not showing up. Created a Chart Repository, but it remained "In Progress" state.
Wasn't able to install any charts.
![Screenshot from 2021-12-08 17-21-14](https://user-images.githubusercontent.com/83208989/145204473-0c1f4202-3296-446c-8a3f-8259c69fa593.png)

**Comment by vivek-infracloud** [comment]
#35820

**Comment by vivek-infracloud** [comment]
### Verified on v2.5-head

- Created a node driver rke1 AWS 2 worker, 1 etcd and 1 cp cluster
- Added the following in the edit as yaml while creating the cluster
```
    kube-api:
      service_cluster_ip_range: 11.23.0.0/16
    kube-controller:
      service_cluster_ip_range: 11.23.0.0/16
    kubelet:
      cluster_dns_server: 11.23.0.10
```

- Verified the kubernetes cluster IP is set to 11.23.0.1
- Installed istio in the downstream cluster version 1.10.400.
- **Installation went through fine without any error.**
