### ISSUE TITLE
Cluster status gets stuck "provisioning worker nodes" if provisioning many nodes at once and drain on upgrade is enabled

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#35364]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Nah

**Information about the Cluster**
- Kubernetes version: `v1.21.5+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**
When provisioning many controlplane/worker nodes at the same time when enabling "drain" for upgrade (think automation, i.e. terraform), sometimes the cluster state can get stuck stating "provisioning worker node(s) <node>" even though the cluster is fully provisioned.

In this case, the UI should probably state that the node is "Upgrading" or "Draining" or something like that. 

**To Reproduce**
Create many nodes at once that are workers

**Result**
Cluster status gets stuck stating "provisioning worker node(s) <node-names>" even though the nodes are active/healthy

**Expected Result**
Cluster should not show a status and just say "Active"

**Screenshots**

<img width="2321" alt="Screen Shot 2021-11-03 at 10 07 24 AM" src="https://user-images.githubusercontent.com/30601846/140132271-1b4291b5-865f-49b5-9299-01da858d75b8.png">

**Additional context**

I'm pretty sure this is being caused due to the "enablement" of drain settings in Rancher for my upgrade strategy.

Looking in Rancher logs, I see 

```
2021/11/03 17:13:51 [ERROR] error syncing 'fleet-default/custom-8a2eda577c70': handler machine-drain: cannot delete Pods with local storage (use --delete-emptydir-data to override): kube-system/rke2-metrics-server-5df7d77b5b-bgskf, requeuing
```

The cluster has drain enabled which is why I believe this happening
```
upgradeStrategy:
      controlPlaneDrainOptions:
        enabled: true
        ignoreDaemonSets: true
        timeout: 300
      workerDrainOptions:
        enabled: true
        ignoreDaemonSets: true
        timeout: 300
```
