### ISSUE TITLE
Cluster health check failed: deployments.apps "cattle-cluster-agent" not found; Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: dial tcp [::1]:443: connect: cannot assign requested address

### ISSUE THREAD

**Issue by suharevA** [rancher/rancher#35435]
**Rancher Server Setup**
- Rancher version:v1.19.6-rancher1-1
- Installation option (Docker install/Helm Chart):Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:1.19.15
- Cluster Type (Local/Downstream):Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

Cluster health check failed: deployments.apps "cattle-cluster-agent" not found; Error while applying agent YAML, it will be retried automatically: exit status 1, Unable to connect to the server: dial tcp [::1]:443: connect: cannot assign requested address

Feature Flag proxy there is no such option
edit yml
```
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
local_cluster_auth_endpoint:
  enabled: true
name: <ИМЯ КЛАСТЕРА>
rancher_kubernetes_engine_config:
cloud_provider:
  name: vsphere
  vsphereCloudProvider:
    disk: {}
    global:
      insecure-flag: true
      soap-roundtrip-count: 0
    network: {}
    virtual_center:
      vcsa-dc151.tau.mos.lan:
        datacenters: /DC15
        port: '443'
        soap-roundtrip-count: 0
        user: admin
        password: <ПО ЗАПРОСУ>
    workspace:
      datacenter: /DC15
      default-datastore: /DC15/datastore/dc15-cl07/d66-h132-e58
      folder: /DC15/datastore/dc15-cl07
      server: vcsa-dc151.tau.mos.lan
  addon_job_timeout: 45
  authentication:
    strategy: x509
  dns:
    nodelocal:
      ip_address: ''
      node_selector: null
      update_strategy: {}
  ignore_docker_version: true
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: nginx
  kubernetes_version: v1.19.6-rancher1-1
  monitoring:
    provider: metrics-server
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: canal
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        election-timeout: 5000
        heartbeat-interval: 500
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube_api:
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
  ssh_agent_auth: false
  upgrade_strategy:
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
windows_prefered_cluster: false
```
running containers

```
d139835a6dbf        b5af743e5984                           "/server"                3 minutes ago       Up 3 minutes                            k8s_default-http-backend_default-http-backend-65dd5949d9-bwkrw_ingress-nginx_78e8505e-6a99-465d-8f1c-1f93c84d5cb4_0
73cca834f6c2        rancher/pause:3.2                      "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_default-http-backend-65dd5949d9-bwkrw_ingress-nginx_78e8505e-6a99-465d-8f1c-1f93c84d5cb4_0
3c123a4f0f6b        rancher/metrics-server                 "/metrics-server --k…"   3 minutes ago       Up 3 minutes                            k8s_metrics-server_metrics-server-8449844bf-2ls9v_kube-system_9d84c1aa-2aed-44b4-8a8d-c35d55d6c183_0
dd6da1d49539        rancher/pause:3.2                      "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_metrics-server-8449844bf-2ls9v_kube-system_9d84c1aa-2aed-44b4-8a8d-c35d55d6c183_0
96593dd85635        4f1064cf7caf                           "/cluster-proportion…"   3 minutes ago       Up 3 minutes                            k8s_autoscaler_coredns-autoscaler-79599b9dc6-52pzm_kube-system_e8c2909b-dbd3-45f5-9e09-05ed5476ba08_0
aa2a079e8575        rancher/pause:3.2                      "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_coredns-autoscaler-79599b9dc6-52pzm_kube-system_e8c2909b-dbd3-45f5-9e09-05ed5476ba08_0
48a5e6006b32        1120bf0b8b41                           "/usr/bin/kube-contr…"   3 minutes ago       Up 3 minutes                            k8s_calico-kube-controllers_calico-kube-controllers-7fbff695b4-9ntms_kube-system_009dbec5-e957-4bee-bbf6-7fe2410cafb7_0
888ffef9941a        rancher/pause:3.2                      "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_calico-kube-controllers-7fbff695b4-9ntms_kube-system_009dbec5-e957-4bee-bbf6-7fe2410cafb7_0
8e08d8835ca2        0bfefe9f649b                           "/opt/bin/flanneld -…"   3 minutes ago       Up 3 minutes                            k8s_kube-flannel_canal-qvxgw_kube-system_9deedbfc-27d5-446d-b5cc-55336b41f662_0
c0357dcfdbda        c1fa37765208                           "start_runit"            3 minutes ago       Up 3 minutes                            k8s_calico-node_canal-qvxgw_kube-system_9deedbfc-27d5-446d-b5cc-55336b41f662_0
48571f15516b        rancher/pause:3.2                      "/pause"                 3 minutes ago       Up 3 minutes                            k8s_POD_canal-qvxgw_kube-system_9deedbfc-27d5-446d-b5cc-55336b41f662_0
c9fbcc5aa1af        rancher/hyperkube:v1.19.6-rancher1     "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kube-proxy
6d98f95a1e4e        rancher/hyperkube:v1.19.6-rancher1     "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kubelet
610df0a0a50a        rancher/hyperkube:v1.19.6-rancher1     "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kube-scheduler
cabf66e7cfb9        rancher/hyperkube:v1.19.6-rancher1     "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kube-controller-manager
235d0c493daa        rancher/hyperkube:v1.19.6-rancher1     "/opt/rke-tools/entr…"   4 minutes ago       Up 4 minutes                            kube-apiserver
8471e57a6810        rancher/coreos-etcd:v3.4.13-rancher1   "/usr/local/bin/etcd…"   4 minutes ago       Up 4 minutes                            etcd
078a79218a9f        bfe3a36ebd25                           "/coredns -conf /etc…"   5 minutes ago       Up 5 minutes                            k8s_coredns_coredns-6f85d5fb88-m69l7_kube-system_6dad80df-b4c5-467e-8486-c1d461bb6a7d_1
a0a979a0a2fd        rancher/mirrored-pause:3.2             "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_coredns-6f85d5fb88-m69l7_kube-system_6dad80df-b4c5-467e-8486-c1d461bb6a7d_7
a64445d51f90        1f0ca6d99110                           "/usr/bin/dumb-init …"   5 minutes ago       Up 5 minutes                            k8s_nginx-ingress-controller_nginx-ingress-controller-hfhh7_ingress-nginx_121cb742-5649-4b7d-b228-26de91a9457d_1
dc9136ffa9dd        rancher/mirrored-pause:3.2             "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_nginx-ingress-controller-hfhh7_ingress-nginx_121cb742-5649-4b7d-b228-26de91a9457d_1
d705fa36d673        rancher/rancher-agent:v2.5.5           "run.sh --server htt…"   5 minutes ago       Up 5 minutes                            trusting_kapitsa
a0b6faa4fba1        rancher/rancher-agent:v2.5.5           "run.sh --server htt…"   2 hours ago         Up 5 minutes                            determined_antonelli
835df7fd7252        rancher/rancher-agent:v2.5.5           "run.sh --server htt…"   2 hours ago         Up 5 minutes                            amazing_ganguly

```
**To Reproduce**
 

**Result**

**Expected Result**

![Снимок экрана от 2021-11-09 14-50-14](https://user-images.githubusercontent.com/48557725/141039821-f5d9bc78-7aa1-4b98-8504-060800473e87.png)

**Screenshots**

**Additional context**
