### ISSUE TITLE
[UI] Cannot create a load balancer with random port mapping 

### ISSUE THREAD

**Issue by shotai** [rancher/rancher#3547]
Try to create a load balancer without source port via UI, get error message: 
**Choose one or more ports to listen on**

However, I can create using docker-compose with only target ports defined. 
i.e.

```
testlb:
  image: rancher/load-balancer-service
  ports:
  - 3000
  links:
  - test:test
  stdin_open: true
  tty: true
```

Version:
Rancher v0.56.1
Cattle  v0.141.1
User Interface  v0.86.0
Rancher Compose v0.7.1
