### ISSUE TITLE
Rancher doesn't update calico version when upgrade RKE2 cluster with canal

### ISSUE THREAD

**Issue by Dador** [rancher/rancher#35562]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: `v1.21.6+rke2r1` (upgraded from `v1.21.4+rke2r1` if I remember correctly, it was Kubernetes version used in RKE2 in Rancher 2.6.0)
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**
I upgraded Rancher from 2.6.0 to 2.6.2 and then upgraded RKE2 cluster to Kubernetes v1.21.6+rke2r1 using Rancher (Cluster -> "Edit config" -> Changed version to "v1.21.6+rke2r1" -> Saved).

But versions inside `rke2-canal` isn't updated to new versions, in my case it's versions when cluster was created:
```yaml
      rke2-canal:
        calico:
          clusterType: k8s,canal
          cniImage:
            repository: rancher/hardened-calico
            tag: v3.13.3-build20210223
          datastoreType: kubernetes
          disableFileLogging: true
          felixDefaultEndpointToHostAction: ACCEPT
          felixFailsafeInboundHostPorts: ""
          felixFailsafeOutboundHostPorts: ""
          felixHealthEnabled: true
          felixIptablesBackend: auto
          felixIptablesRefreshInterval: 60
          felixIpv6Support: false
          felixLogSeverityScreen: info
          felixPrometheusMetricsEnabled: true
          felixXDPEnabled: false
          flexVolumePluginDir: /var/lib/kubelet/volumeplugins
          flexvolImage:
            repository: rancher/hardened-calico
            tag: v3.13.3-build20210223
          masquerade: true
          networkingBackend: none
          nodeImage:
            repository: rancher/hardened-calico
            tag: v3.13.3-build20210223
          typhaServiceName: none
          usePodCIDR: true
          vethuMTU: 1450
          waitForDatastore: true
```

When I try to create new cluster with the same Kubernetes version, then config with new versions are generated:
```yaml
     rke2-canal:
        calico:
          clusterType: k8s,canal
          cniImage:
            repository: rancher/hardened-calico
            tag: v3.20.1-build20211006
          datastoreType: kubernetes
          disableFileLogging: true
          felixDefaultEndpointToHostAction: ACCEPT
          felixFailsafeInboundHostPorts: ''
          felixFailsafeOutboundHostPorts: ''
          felixHealthEnabled: true
          felixIptablesBackend: auto
          felixIptablesRefreshInterval: 60
          felixIpv6Support: false
          felixLogSeverityScreen: info
          felixPrometheusMetricsEnabled: true
          felixXDPEnabled: false
          flexVolumePluginDir: /var/lib/kubelet/volumeplugins
          flexvolImage:
            repository: rancher/hardened-calico
            tag: v3.20.1-build20211006
          masquerade: true
          networkingBackend: none
          nodeImage:
            repository: rancher/hardened-calico
            tag: v3.20.1-build20211006
          typhaServiceName: none
          usePodCIDR: true
          vethuMTU: 1450
          waitForDatastore: true
```

In my case that leaded to a lot of errors and troubles after cluster upgrade. Cluster became unavailable because `rke2-canal-*` were unable to start due to error in init container ` install-cni`, error: `exec: "/opt/cni/bin/install": stat "/opt/cni/bin/install" no such file or directory: unknown`. (probably `/opt/cni/bin/install` located in different location or not exists in older versions of `rancher/hardened-calico`).

P.S. For context and searchability: just after upgrade I got a lot of errors like `Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "[...]": error getting ClusterInformation: connection is unauthorized: Unauthorized` which were related to wrong token in config `/etc/cni/net.d/calico-kubeconfig` (or maybe not propertly configured ClusterRole/ClusterRoleBinding), which looked similar to issues https://github.com/rancher/rke/issues/2527 and #18713. But looking at situation now, I think just updating image version is enough to fix these problems (looks like calico generate new tokens during initialization process).

**Workaround:**
If the cluster is already unavailable (from outside), probably you won't be able to change versions using Rancher. In that case you can update versions manually by editing DaemonSet `rke2-canal`, just update all references to image `rancher/hardened-calico` to actual version (`v3.20.1-build20211006` in my case, to check actual version you can start creating new cluster in Rancher and check in YAML which version it's using for new clusters).

**To Reproduce**
In theory:
- Install Rancher 2.6.0
- Create cluster with RKE2 with canal, Custom Type (using provisioned nodes)
- Upgrade to Rancher 2.6.2
- Upgrade cluster to `v1.21.6+rke2r1`

**Expected Result**
Versions inside `rke2-canal` are updated (and hopefully cluster will be upgraded without troubles).
