### ISSUE TITLE
Why would the node be deleted

### ISSUE THREAD

**Issue by lework** [rancher/rancher#35561]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Helm 

**Information about the Cluster**
- Kubernetes version: v1.19.10

- Cluster Type (Local/Downstream):  huawei cce

**Describe the bug**
Node is deleted

**yaml**

```yaml
# Source: rancher/templates/serviceAccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rancher
  namespace: ops
  labels:
    app: rancher
    chart: rancher-2.6.2
    heritage: Helm
---
# Source: rancher/templates/clusterRoleBinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rancher
  namespace: ops
  labels:
    app: rancher
    chart: rancher-2.6.2
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: ops
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: rancher/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "bootstrap-secret"
  namespace: ops
type: Opaque
data:
  bootstrapPassword: ""

---
# Source: rancher/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rancher
  namespace: ops
  annotations:
  labels:
    app: rancher
    chart: rancher-2.6.2
    heritage: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher
    spec:
      serviceAccountName: rancher
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rancher
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms: 
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
      tolerations: 
        - key: "cattle.io/os"
          value: "linux"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
      - image: rancher/rancher:v2.6.2
        imagePullPolicy: IfNotPresent
        name: rancher
        ports:
        - containerPort: 80
          protocol: TCP
        args:
        # Public trusted CA - clear ca certs
        - "--no-cacerts"
        - "--http-listen-port=80"
        - "--https-listen-port=443"
        - "--add-local=true"
        env:
        - name: CATTLE_NAMESPACE
          value: ops
        - name: CATTLE_PEER_SERVICE
          value: rancher
        - name: CATTLE_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "bootstrap-secret"
              key: "bootstrapPassword"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
        resources:
          {}
        volumeMounts:
      volumes:

---
# Source: rancher/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: ops
  labels:
    app: rancher
    chart: rancher-2.6.2
    heritage: Helm
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 444
    protocol: TCP
    name: https-internal
  selector:
    app: rancher

---
# Source: rancher/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rancher
  namespace: ops
  labels:
    app: rancher
    chart: rancher-2.6.2
    heritage: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - host: rancher.ops.putaoevent.com
    http:
      paths:
      - backend:
          serviceName: rancher
          servicePort: 80
```

```bash
kubectl create ns ops
kubectl apply -f rancher.yaml
```

**Result**

**Screenshots**

![20211117180548](https://user-images.githubusercontent.com/17396943/142180385-07b0f06e-1610-4508-a3c0-e11852836f93.jpg)
