### ISSUE TITLE
Upgraded service leaves linked service connected to most recently upgraded container

### ISSUE THREAD

**Issue by jraede** [rancher/rancher#3565]
## Versions
Component	Version
Rancher	v0.56.1
Cattle	v0.141.1
User Interface	v0.86.0
Rancher Compose	v0.7.1

## Issue
We have two services running on two servers. One service ("the sender") forwards messages to another service ("the worker") via container link. There is one instance of each service running on each server.

With previous versions of Rancher, each "sender" container would automatically link to the "worker" container that was on its same physical host. A "start first" upgrade to "the sender" would end up re-linking the containers in the same way, so the "worker" on server 1 would forward messages to the "sender" on server 1, and the same with server 2.

However with 0.56.1, we have noticed that a "start first" upgrade to "the worker" would end up leaving each "sender" connected to the most recently upgraded "worker" container. In the most recent case, both "senders" were forwarding messages to the "worker" on server 2 because it was the last to start. (I am ~90% sure of the start order, so I could be wrong, but it seems reasonable that the order would affect things)

By performing a subsequent upgrade to the "sender" service, the containers were re-linked according to their physical host.

I'm able to reproduce this with 100% accuracy so I can give you more information if you need.

Thanks,
Jason

**Comment by deniseschannon** [comment]
Do you have a docker-compose.yml that I could try? I'm not quite sure I understand what you're saying.

Service Foo is linked to Service Bar.

Any container in service Foo should be linked to any container in service bar (Regardless of host placement).

**Comment by jraede** [comment]
Here's a diagram:

```
How it should be/how it starts
[SERVER 1]                [SERVER 2]
[    sender  ]                 [    sender  ]
          |                                 |
          |                                 |
          |                                 |
[   worker   ]                 [   worker   ]

How it ends up after upgrade:
[SERVER 1]                [SERVER 2]
[    sender  ]                 [    sender  ]
          \_______________         |
                                          \       |   
                                           |      |
[   worker   ]                 [   worker   ]
```

The compose file is basically. There are 2 servers with `service=cache` label.
```
sender:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: service=cache
  tty: true
  image: dispatch/worker:<hash>
  links:
  - my-stack:worker
  stdin_open: true
worker:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: service=cache
  tty: true
  image: dispatch/sender:<hash>
  stdin_open: true
```

**Comment by jraede** [comment]
(diagram didn't work so well - I'm figuring out a different way)

**Comment by deniseschannon** [comment]
FWIW, nothing has changed between v0.51.0 and v0.56.1 in regards to linking. 

For DNS resolution, it has always been all containers of sender would be resolvable to all containers of worker. So with your docker-compose.yml

server1_sender would have dns resolution to server1_worker AND server2_worker
server2_sender would have dns resolution to server1_worker AND server2_worker

What are you trying to achieve with the `links`?

**Comment by jraede** [comment]
OK, good to know. I suppose we are looking for what sidekicks theoretically give us. I notice there's no way in the UI to set up the linking and alias between the sidekick and the main container - is there a way to do this in the compose file?

**Comment by deniseschannon** [comment]
Just to clarify, what are you expecting to happen with the linking? DNS resolution or environment variable?

**Comment by jraede** [comment]
It seemed to me that in the past there was automatic resolution to a container on the same physical host if it existed (e.g. our servers linked to the DataDog agent service, which runs on every server, seem to be connecting to the container on their same physical host. I will verify). That might not be the case, but that's essentially what we're trying to achieve. Something similar to load balancing because we don't want 1 worker processing the messages from 2 senders.

**Comment by deniseschannon** [comment]
For DNS resolution, there have been no changes. I just did another test (without even upgrading).

```
foo:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  links:
  - bar:foobar
  stdin_open: true
bar:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```

If you exec into any of the foo containers and `ping foobar`, the first container that was chosen was on another host. 

I'm going to close as there is no error here.
