### ISSUE TITLE
Can't connect to new K8s clusters without CNIs

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#35678]
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.5
- Cluster Type (Local/Downstream): RKE1 Downstream, Custom cluster running on an Ubuntu Server VM
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
I created a new cluster without any custom network provider since I plan to install my own custom one after cluster creation. After creation, I'm not able to access it any any way. The option to download the kube config is not present on this cluster. The cluster can't be opened in the dashboard. I've previously been able to download the kube config in Rancher 2.6.x (not sure if I was on 2.6.2 before). Which I could then load into kubectl and manually install my CNI. 

In Rancher 2.5, I was able to use the UI to modify the cluster, but I understand that the cluster-register pod runs on a CNI-provisioned network.

**To Reproduce**
1. Create a new RKE1 cluster with the following config:
```
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
  enabled: true
name: dhcp-cni-test-2
rancher_kubernetes_engine_config:
  addon_job_timeout: 45
  authentication:
    strategy: x509
  authorization: {}
  bastion_host:
    ignore_proxy_env_vars: false
    ssh_agent_auth: false
  cloud_provider: {}
  dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 0
      min: 1
      nodes_per_replica: 4
      prevent_single_point_failure: true
    node_selector: null
    nodelocal:
      node_selector: null
      update_strategy:
        rolling_update: {}
    options: null
    reversecidrs: null
    stubdomains: null
    tolerations: null
    update_strategy:
      rolling_update: {}
    upstreamnameservers: null
  enable_cri_dockerd: false
  ignore_docker_version: true
  ingress:
    default_backend: false
    http_port: 0
    https_port: 0
    provider: none
  kubernetes_version: v1.21.5-rancher1-1
  monitoring:
    provider: none
    replicas: 1
  network:
    mtu: 0
    options:
      flannel_backend_type: vxlan
    plugin: none
  restore:
    restore: false
  rotate_encryption_key: false
  services:
    etcd:
      backup_config:
        enabled: false
        interval_hours: 12
        retention: 6
        safe_timestamp: false
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      extra_args:
        service-cluster-ip-range: '10.43.0.0/16,2001:db8:42:1::/112'
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
    kube-controller:
      extra_args:
        cluster-cidr: '10.42.0.0/16,abcd:db8:42:2::/100'
        node-cidr-mask-size-ipv6: '110'
        service-cluster-ip-range: '10.43.0.0/16,abcd:db8:42:1::/100'
    kubelet:
      extra_args:
        kubelet-cgroups: /systemd/system.slice
        runtime-cgroups: /systemd/system.slice
      fail_swap_on: false
      generate_serving_certificate: false
    kubeproxy: {}
    scheduler: {}
  ssh_agent_auth: false
  upgrade_strategy:
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input:
      delete_local_data: false
      force: false
      grace_period: -1
      ignore_daemon_sets: true
      timeout: 120
scheduled_cluster_scan:
  enabled: false
  scan_config:
    cis_scan_config:
      debug_master: false
      debug_worker: false
      override_benchmark_version: rke-cis-1.5
      profile: permissive
  schedule_config:
    cron_schedule: 0 0 * * *
    retention: 24
```

2. Run the provision commands to provision a cluster and wait for the Ready condition to be = True, but Connected=False
3. Attempt to download the kube config in the Cluster Management page, but fail because the option isn't available
![image](https://user-images.githubusercontent.com/945049/143932542-d76f8858-07e1-4b06-a751-2c68121b4ffe.png)
 

**Result**

**Expected Result**
I would expect there to be some way to access my newly created, CNI-less cluster either using the UI or using kubectl using a kube config

**Screenshots**
![image](https://user-images.githubusercontent.com/945049/143932666-d4282a8c-8d2b-4b06-9f51-6757483cca87.png)
![image](https://user-images.githubusercontent.com/945049/143932690-ad4774eb-1b44-4680-aeb4-4d55a339de5a.png)

**Additional context**
This worked previously. In Rancher 2.5, I could use the UI to load a CNI. In Rancher 2.6.x (unknown minor version,) I was able to download the kube config on a cluster. I was able to access clusters through the Rancher Server proxy and through the private API endpoint.

**Comment by ajacques** [comment]
Also. a related bug that lead to this bug:
I created this cluster to replace a previous test cluster with the same name that I had to recreate because 1 of the 2 etcd nodes died and the other node was unable to recover. I attempted to delete that node out of the Cluster Management, but RKE was unable to fix the cluster as the first etcd kept trying to connect back to the failed etcd node. The online node kept restarting etcd.

**Comment by ajacques** [comment]
Well I managed to find an option to download kube config in the advanced > Mgmt Clusters, however I'm not sure why the option isn't available on the main Cluster Management page. I think you should add the option to that page too.

**Comment by ajacques** [comment]
Whelp, this trick doesn't seem to work on K3s clusters. I just spun up a new k3s cluster, and 

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: mycluster
  namespace: fleet-default
spec:
  agentEnvVars:
    - name: INSTALL_K3S_EXEC
      value: '--flannel-backend=none --flannel-iface=cni0'
  kubernetesVersion: v1.22.7+k3s1
```

Going to Rancher UI > Cluster Management > Advanced > Mgmt Clusters, clicking Download KubeConfig, nothing works.

There's a XHR request that returns a 500:
```
/v3/clusters/c-m-x42qml9w?action=generateKubeconfig
{"baseType":"error","code":"ServerError","message":"cluster context c-m-x42qml9w is unavaiblable","status":500,"type":"error"}
```

Thus, I'm not sure how to get a kube config to be able to install my CNI
