### ISSUE TITLE
Unable to start a container with volumes-from and convoy

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3568]
I have a sidekick container that has a convoy volume, and then the primary container has a volume-from that container. I get this error:

```
Removed (500 Server Error: Internal Server Error ("get $VOL_NAME: invalid character 'H' looking for beginning of value"))
```

where $VOL_NAME is the name of the volume in the sidekick container.

Docker 1.10
Fresh install: 0.56.1

**Comment by withinboredom** [comment]
docker-compose.yml
``` yml
prim:
  labels:
    io.rancher.sidekicks: sidekick
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  volumes_from:
  - sidekick
  stdin_open: true
sidekick:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  volumes:
  - broken:/broken
  stdin_open: true
  volume_driver: convoy-nfs
```

rancher-compose.yml
``` yml
prim:
  scale: 1
sidekick:
  scale: 1
```
