### ISSUE TITLE
Rancher Helm corrupts Helm values.yaml leading to broken applications and doesn't handle upstream changes

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#35717]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.20.12
- Cluster Type (Local/Downstream): Downstream, Custom, RKE1
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
In Rancher 2.6 (as opposed to how 2.5 and before behaved) I now have to explicitly provide all values, even values that I don't change. Thus when an upstream repository changes their values, I don't get the newest changes, and I don't seem to have any way to actually see that the upstream changed values, without seeing a bug or manually investigating. Instead, my explicit values are carried forward through every Helm upgrade without knowing which ones to merge.

There's been what seems like several regressions in the UX for Helm applications. This issue is actually a major trust buster for me since I can no-longer trust that Rancher is going to be able to safely upgrade a Helm upgrade.

**To Reproduce**
1. Install a helm application (e.g. Prometheus v14.10.x. Note I didn't use Rancher cluster tools to install this, the issue would apply to any other Helm application)
2. Change one or two values (e.g. change `serverFiles.prometheus.yml.scrape_config:` from the default
3. Install the application
4. Attempt to upgrade to Prometheus Helm 15.0.1
5. Make the upgrade. When it finally upgrades, note that all image versions are still at the old version and commits like [this one](https://github.com/prometheus-community/helm-charts/commit/df8add6a684501ca655c5162890f7e15aa7afc72#diff-a7d2f872af425efb23e365d063a23bdfcc33de8728c2b7bb4d536b7b8e80981a) are missed
 

Additionally, if I try to delete the value from the values.yaml view hoping for Rancher to fallback to the 2.5 behavior, it just proceeds with an empty value, breaking the application.

**Result**

**Expected Result**
1. I want Rancher to be able to show me a diff of the default values from the upstream repo (What did they change?)
2. If I have overridden values in my Helm application, I want Rancher to be able to show me which values I'm overriding have changed in the upstream or help me perform 3-way.
3. I want to be able to store only the values that I've overridden, not have to look at the entire set of all values. (This was the Rancher 2.5 behavior)
4. If I hit upgrade or install with some values, I want to see the exact same values in the Values YAML tab in the Heml UI

**Screenshots**

**Additional context**

Possibly related to some other Helm issues I've had: https://github.com/rancher/rancher/issues/35236

**Comment by ajacques** [comment]
Another issue with Rancher's Helm implementation: I made several changes to the Helm values, but they got lost after another edit operation. It seems like the Rancher UI keeps a cache of the values somewhere (possibly in the browser side) and the next time I performed an upgrade, it lost those changes. I'm trying to track down a repro, but these issues are causing me to not want to make any changes to Helm until these issues are resolved.

**Comment by ajacques** [comment]
There's something really weird going on with Rancher 2.6.2's Helm UI. Possibly some kind of client-side state related issues. I've attempt to change values and when I saved a completely different area of the values changed and corrupted the values.

**Comment by ajacques** [comment]
After further investigation, I do believe the issue is caused by how Rancher merges array values.

Example, if you have an upstream repo that has something like this:

````
someArrayValue:
- name: Foo
  value: XYZ
- name: Foobar
  value2: ABC
```

and you make changes, and/or rearrange them (which is a entirely valid change to make as a user)

```
someArrayValue:
- name: Foobar
  value2: ABC
- name: Foo
  value: XYZ
```

Then rancher will incorrectly merge these and it'll look like:

```
someArrayValue:
- name: Foobar
  value2: ABC
  value: XYZ
- name: Foo
  value: XYZ
  value2: ABC
```

Rancher doesn't seem to have any semantic understanding of the values, thus it seems to just merge things based on array index. I understand a fix for this may be challenging.

I think the solution should be something like:
1. Don't try to merge array values unless the user hasn't modified the array
2. Diff the upstream values from vPrev to vNext and present this in a UI for the user to review and decide
3. Visually separate the overridden values from the upstream values so I can understand what I've actually changed
4. Highlight conflicts between my overridden values and changes in the upstream values

**Comment by ajacques** [comment]
This issue is definitely still happening. I just hit it on yet another Helm template that included arrays.

**Comment by jonathon2nd** [comment]
> In Rancher 2.6 (as opposed to how 2.5 and before behaved) I now have to explicitly provide all values, even values that I don't change. Thus when an upstream repository changes their values, I don't get the newest changes, and I don't seem to have any way to actually see that the upstream changed values, without seeing a bug or manually investigating. Instead, my explicit values (even ones I didn't change) are carried forward through every Helm upgrade.

This is wild, was so confused when we upgraded to 2.6.3. Is previous behaviors with values going to be restored?

**Comment by ajacques** [comment]
Still happening

**Comment by jonathon2nd** [comment]
This is really terrible. 

One idea for a possible work around was to install with helm, and then maybe others can update in UI. NOPE
![Screenshot_20220511_154215](https://user-images.githubusercontent.com/52681917/167952692-b90c1c5f-79bd-4da7-8a0d-88fcbce6fc2b.png)
It just never loads
![Screenshot_20220511_154237](https://user-images.githubusercontent.com/52681917/167952740-15c04c20-17c7-47bb-828b-7b8df5a13089.png)

And when you view the installed app in the UI, the values are garbage there too
![Screenshot_20220511_154317](https://user-images.githubusercontent.com/52681917/167952844-a30fd8cc-8743-4b12-b40f-eaad1070964e.png)
I know that it is *not garbage* values, and that that is the complete list of values for the application installed. But I do not care about the *entire* values. I only care about the changes I made to the values.

**Comment by ajacques** [comment]
Confirmed that Rancher 2.6.5 still incorrectly handles YAML values.

@jonathon2nd, totally agree on the user experience for these values. I gave some ideas above, but I want to see some clearer diffing to show what I actually changed vs what changed upstream.

**Comment by ajacques** [comment]
Still broken v2.6.6

**Comment by ajacques** [comment]
Trying to comment again because it's still marked as stale. But Rancher's helm handing is still buggy.

**Comment by ajacques** [comment]
Still broken on v2.6.8

**Comment by jonathon2nd** [comment]
@ajacques We have so far had great success with Argo-cd. We are currently setting up new infra and clusters, and all non cluster charts are managed by Argo-cd. We are managing both infrastructure (metallb, storage CSI, and a few others) as well as applications and their dbs.

May not be what you are looking for, but so far we are happy. The automatic syncing and updating of our applications is a bonus. 

We are still in the early stages, could let you know in a couple months how it is going.

**Comment by ajacques** [comment]
@jonathon2nd Thanks for the update. I've been meaning to try out ArgoCD, but haven't yet and keep this open in the futile hope that Rancher will fix this bug. Maybe I'll find some time over the holidays to try out ArgoCD.

**Comment by ajacques** [comment]
bump

**Comment by ajacques** [comment]
bump still broken 2.7.1

**Comment by ajacques** [comment]
Bump. Still broken in v2.7.3

**Comment by ajacques** [comment]
Still broken

**Comment by jonathon2nd** [comment]
Lmao just realized I never updated this. We have been using Argo-CD for all of our deployments without issue.

**Comment by ajacques** [comment]
Still broken 2.8.1

**Comment by ajacques** [comment]
Not stale bump

**Comment by qaz-t** [comment]
still happened in 2.8.2. I deploy helm chart: argocd-apps, parameters in chart is empty, and overwrite them in rancher ui.
when i upgrade values in chart
before:
```yaml
applications:
  - source:
      helm:
        parameters:
          - name: na
            value: ''
          - name: nc
            value: ''
```
after:
```yaml
applications:
  - source:
      helm:
        parameters:
          - name: na
            value: ''
          - name: nb
            value: ''
          - name: nc
            value: ''
```
rancher display values:
before:
```yaml
applications:
  - source:
      helm:
        parameters:
          - name: na
            value: v1
          - name: nc
            value: v3
```
after:
```yaml
applications:
  - source:
      helm:
        parameters:
          - name: na
            value: v1
          - name: nc
            value: v3
          - name: nc
            value: ''
```
