### ISSUE TITLE
rancher-compose doesn't replace environment variables on upgrade

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#3574]
When using rancher-compose (0.7.1) to recreate a stack, old values of environment variables are used:

```sh
rancher-compose rm --force
rancher-compose up --pull --recreate --force-recreate --confirm-upgrade -d
```

The only way to replace environment variables seems to delete the stack entirely in the UI, and rancher-compose does not provide a way to do that.

**Comment by deniseschannon** [comment]
Can you share your old docker-compose.yml and your new one?

**Comment by pvalsecc** [comment]
I think there is a misunderstanding. The docker-compose.yml and the rancher-compose.yml files are not changing. What is changing are the environment variables (answers to the questions in the rancher-compose.yml file).

So, for example, our rancher-compose.yml file contains:
```yaml
.catalog:
  questions:
    - variable: "BATCH_SECRET_KEY"
      label: "Batch secret key"
      description: "Secret Key for the batch service"
      type: "password"
      required: true
```

The docker-compose.yml contains:
```yaml
batch:
  environment:
    CATALINA_OPTS: -Dsecret.key=${BATCH_SECRET_KEY}
  image: example/batch:latest
```

You first do that:
```
$ export BATCH_SECRET_KEY=foo
$ rancher-compose up
```

Then you want to change the secret key:
```
$ export BATCH_SECRET_KEY=bar
$ rancher-compose rm --force
$ rancher-compose up --pull --recreate --force-recreate --confirm-upgrade -d
```

If you check the rancher web pages, you'll see that the BATCH_SECRET_KEY value remains at foo.
