### ISSUE TITLE
sidekick metadata is ignored

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#3575]
I've created a small utility which dumps the user-provided metadata to a file. It's at https://github.com/DanielDent/rancher-metadata-dump.

The included docker-compose.yml & rancher-compose.yml will do a test run of the utility.

It creates the following in `test-dumptruck-output.yml`:
```
example2:                                                                       
  foo: bar                                                                      
io.rancher.service.hash: d1c34bdb7950640442c08b5fb54756b36b94294b               
rock:                                                                           
  belongs: in_gravelpits                                                        
  value: world                                                                  
```
I was expecting:
```
sand:
  belongs: in_dumptrucks
  value: world
example2:
  foo: bar
```

1. The sidekick service's own metadata appears to be ignored. The main service's metadata is used instead.
2. The `io.rancher.service.hash` key appears out of no where. I understand this showing up as a label on the container. I don't understand why it is being added to the user-provided metadata.
