### ISSUE TITLE
Rancher is not opening when installed in K3s with nginx-ingress-controller

### ISSUE THREAD

**Issue by saggiyogesh** [rancher/rancher#35887]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm on K3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
Rancher UI is not opening on K3s with[ nginx-ingress-controller](https://docs.nginx.com/nginx-ingress-controller/ ) 

**To Reproduce**
- Deploy a new K3s master without traefik.
- Install Helm
- Install `nginx-ingress-controller` using helm chart

**Result**

**Expected Result**
- It should map the rancher service in `nginx-ingress-controller` as the default backend just like its works with K3s + traefik, instead of giving 404

**Comment by headwhacker** [comment]
I am trying the same setup Rancher on K3s with traefik disable and ingress-nginx installed as ingress controller. Anyone got this working? It works fine with Traefik. The reason I am trying to use ingress-nginx instead of Traefik is I have a few deployments that need TCP/UDP ports to be exposed. I'm having a hard time doing it with Traefik.

**Comment by saggiyogesh** [comment]
It's not possible to use Rancher on K3S with nginx-ingress-controller, at least no docs are there for same. 
Finally deployed Rancher on different VM & imported the K3s cluster.

**Comment by headwhacker** [comment]
That's a shame, it is already working with Traefik on K3s. Also running fine on RKE2/ingress-nginx as well. So it's surprising to find it won't work on K3s with nginx.

**Comment by rancher-max** [comment]
I saw this same issue, but using this HelmChart was successful in my case so might help here as well:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: v4.0.19
  set:
  valuesContent: |-
    fullnameOverride: ingress-nginx
    controller:
      kind: DaemonSet
      dnsPolicy: ClusterFirstWithHostNet
      watchIngressWithoutClass: true
      allowSnippetAnnotations: false
      hostNetwork: true
      hostPort:
        enabled: true
      publishService:
        enabled: false
      service:
        enabled: false
```

One of the key values here that I was initially missing is:
```
      watchIngressWithoutClass: true
```
since ingress-nginx requires an IngressClass set without this in v1.21+. Notice below that without this, my ingress resource was not getting any addresses:
```
$ k get ingress -A
NAMESPACE       NAME      CLASS    HOSTS                      ADDRESS   PORTS     AGE
cattle-system   rancher   <none>   <redacted>                           80, 443   18m
```
After setting this correctly, it did get addresses and my UI was accessible.
