### ISSUE TITLE
Deployment securityContext is missing when created from new UI

### ISSUE THREAD

**Issue by sebastien-helbert** [rancher/rancher#35889]
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option :
   - Helm Chart, RKE1

**Information about the Cluster**
- Kubernetes version: v1.21.6
- Cluster Type : Downstream, Custom

**Describe the bug**
securityContext section is missing when created from new UI which prevents pods from starting when Pod Security Policy Support is enabled.

**To Reproduce**
Create a new workload of type Deployment from UI

**Result**

**Expected Result**

Add this section in yaml file like the old UI does :
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
```
