### ISSUE TITLE
Rancher 2.6.3: Cluster Management not remove imported cluster

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#35967]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
- If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray

**Information about the Cluster**
- Kubernetes version: 1.21.1
- Cluster Type (Local/Downstream): Downstream
* Hosted = cloud vps
 * Infrastructure Provider = Hetzner

**Describe the bug**
Deleted cluster already exists in rancher dashboard and in the menu 

**To Reproduce**
* Setup cluster for Rancher
* Add rancher in cluster
* Setup additional cluster
* Add `additional cluster` into rancher in cluster manager(type generic)
* Delete additional cluster(remove vms)
* Remove cluster in rancher
 

**Result**
Cluster removed only in Cluster Management -> Clusters
**Expected Result**
Cluster removed in all components, Dashboard, Menu

**Screenshots**
![image](https://user-images.githubusercontent.com/8457572/147340330-2f7240d2-3d0e-4195-acb6-5c2332d6a905.png)
![image](https://user-images.githubusercontent.com/8457572/147340368-ed6d6109-4a07-487f-a0f6-7f2232c54f7e.png)
![image](https://user-images.githubusercontent.com/8457572/147340413-eeab4b68-1c47-428a-8634-547164294450.png)

**Additional context**

**Comment by wirwolf** [comment]
This cluster already exist in tab 'Cluster Management -> Advanced -> Mgmt Clusters' but i can not remove item

![image](https://user-images.githubusercontent.com/8457572/147342360-05110c10-ff1f-4b49-9675-6f483c96dd4f.png)

**Comment by wirwolf** [comment]
I found some resources for the old cluster in the rancher
```
cat cluster-scan-alert_clusteralertgroups.management.cattle.io.yaml

apiVersion: management.cattle.io/v3
kind: ClusterAlertGroup
metadata:
  annotations:
    lifecycle.cattle.io/create.cluster-alert-group-lifecycle_c-m-xlp7prgz: "true"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-12-24T08:33:42Z"
  labels:
    cattle.io/creator: norman
  name: cluster-scan-alert
  namespace: c-m-xlp7prgz
spec:
  clusterName: c-m-xlp7prgz
  description: Alert for Cluster Scans, both manual and scheduled
  displayName: A set of alerts for cluster scans
  groupIntervalSeconds: 180
  groupWaitSeconds: 180
  repeatIntervalSeconds: 3600


cat etcd-alert_clusteralertgroups.management.cattle.io.yaml

apiVersion: management.cattle.io/v3
kind: ClusterAlertGroup
metadata:
  annotations:
    lifecycle.cattle.io/create.cluster-alert-group-lifecycle_c-m-xlp7prgz: "true"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-12-24T08:33:42Z"
  labels:
    cattle.io/creator: norman
  name: etcd-alert
  namespace: c-m-xlp7prgz
spec:
  clusterName: c-m-xlp7prgz
  description: Alert for etcd leader existence, db size
  displayName: A set of alerts for etcd
  groupIntervalSeconds: 180
  groupWaitSeconds: 180
  repeatIntervalSeconds: 3600

cat event-alert_clusteralertgroups.management.cattle.io.yaml

apiVersion: management.cattle.io/v3
kind: ClusterAlertGroup
metadata:
  annotations:
    lifecycle.cattle.io/create.cluster-alert-group-lifecycle_c-m-xlp7prgz: "true"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-12-24T08:33:42Z"
  labels:
    cattle.io/creator: norman
  name: event-alert
  namespace: c-m-xlp7prgz
spec:
  clusterName: c-m-xlp7prgz
  description: Alert for receiving resource event
  displayName: A set of alerts when event happened
  groupIntervalSeconds: 180
  groupWaitSeconds: 180
  repeatIntervalSeconds: 3600

cat kube-components-alert_clusteralertgroups.management.cattle.io.yaml

apiVersion: management.cattle.io/v3
kind: ClusterAlertGroup
metadata:
  annotations:
    lifecycle.cattle.io/create.cluster-alert-group-lifecycle_c-m-xlp7prgz: "true"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-12-24T08:33:42Z"
  labels:
    cattle.io/creator: norman
  name: kube-components-alert
  namespace: c-m-xlp7prgz
spec:
  clusterName: c-m-xlp7prgz
  description: Alert for kube components api server, scheduler, controller manager
  displayName: A set of alerts for kube components
  groupIntervalSeconds: 180
  groupWaitSeconds: 180
  repeatIntervalSeconds: 3600

cat node-alert_clusteralertgroups.management.cattle.io.yaml

apiVersion: management.cattle.io/v3
kind: ClusterAlertGroup
metadata:
  annotations:
    lifecycle.cattle.io/create.cluster-alert-group-lifecycle_c-m-xlp7prgz: "true"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-12-24T08:33:42Z"
  labels:
    cattle.io/creator: norman
  name: node-alert
  namespace: c-m-xlp7prgz
spec:
  clusterName: c-m-xlp7prgz
  description: Alert for Node Memory, CPU, Disk Usage
  displayName: A set of alerts for node
  groupIntervalSeconds: 180
  groupWaitSeconds: 180
  repeatIntervalSeconds: 3600
```
