### ISSUE TITLE
flannel network config cannot specify more than one interface

### ISSUE THREAD

**Issue by samene** [rancher/rancher#35980]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart (rancher-stable)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom Baremetal

**Describe the bug**
Flannel networking config in RKE can only specify one network interface like this
```
  network:
    options:
      flannel_iface: eth0
    plugin: flannel
````
This translates to flannel daemonset
```
containers:
  - args:
    - --ip-masq
    - --kube-subnet-mgr
    - --iface=eth0
 ```
However flannel doc states that we can use the `--iface` multiple times. In my case I have nodes with different interface names. So I would like to do something like
```
  network:
    options:
      flannel_iface: eth0,ens192,eno1
    plugin: flannel
````
so as to become
```
containers:
  - args:
    - --ip-masq
    - --kube-subnet-mgr
    - --iface=eth0
    - --iface=ens192
    - --iface=eno1
 ```
But this does not work.

**Result**

**Expected Result**
There should be a way to specify multiple interfaces or IP addresses to flannel network config.
