### ISSUE TITLE
Cannot create Azure Disk and PVC with RKE2 template

### ISSUE THREAD

**Issue by GeertvanHorrik** [rancher/rancher#35993]
I am trying to create an Azure disk for a RKE2 Rancher managed cluster.

I created the yaml files, but the disk is not being created. The PVC cannot be provisioned with the following error:

`ProvisioningFailed: no volume plugin matched name: kubernetes.io/azure-disk`

Everything is based on naming convention and I double checked all settings.

## Disk
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "mychart.diskName" . }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS #Premium_LRS
  kind: Managed
  cachingmode: ReadOnly
  resourceGroup: {{ include "mychart.azureResourceGroup" . }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

## PV
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "mychart-%s-postgres-data" .Values.slug }}
  namespace: {{ include "mychart.namespace" . }}
spec:
  capacity:
    storage: {{ .Values.auth.diskSize | quote }}
  azureDisk:
    diskName: {{ include "mychart.diskName" . }}
    {{- $secretObj := (lookup "v1" "Secret" "cattle-global-data" (printf "%s" (.Values.cloudCredentialSecretName | replace "cattle-global-data:" ""))) | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}
    diskURI: {{ printf "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/disks/%s" (get $secretData "azurecredentialConfig-subscriptionId" | b64dec | default "MISSING" ) (include "mychart.azureResourceGroup" .) (include "mychart.diskName" .) }} 
    cachingMode: ReadOnly
    fsType: ''
    readOnly: false
    kind: Managed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ include "mychart.diskName" . }}
  volumeMode: Filesystem
```

## PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "-%s-postgres-data" .Values.slug }}
  namespace: {{ include "mychart.namespace" . }}
  labels:
    app: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.auth.diskSize | quote }}
  storageClassName: {{ include "mychart.diskName" . }}
  volumeMode: Filesystem
```

How can I *automatically* (via the Helm chart) create an Azure disk that can be used for PV and PVC? Or is this a known limitation?
