### ISSUE TITLE
Multiple nodes are upgraded at the same time when enabling pre/post-drain hooks during a RKE2 upgrade

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#35999]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:v2.6.3-rc4`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.7+rke2r1`
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

RKE2 runtime on multiple nodes are upgraded at the same time but the `controlPlaneConcurrency` and `workerConcurrency` are both `1`.

**To Reproduce**
 
We upgrade the RKE2 cluster in Harvester with the following manifest by modifying the `clusters.provisioning.cattle.io/local` CR:

```
  spec:
    kubernetesVersion: v1.22.4+rke2r2       # upgrade from v1.21.7+rke2r1
    localClusterAuthEndpoint: {}
    rkeConfig:
      chartValues: "null"
      machineGlobalConfig: "null"
      provisionGeneration: 1
      upgradeStrategy:
        controlPlaneConcurrency: "1"
        controlPlaneDrainOptions:
          deleteEmptyDirData: true
          enabled: true
          force: true
          ignoreDaemonSets: true
          postDrainHooks:
          - annotation: harvesterhci.io/post-hook
          preDrainHooks:
          - annotation: harvesterhci.io/pre-hook
          timeout: 0
        workerConcurrency: "1"
        workerDrainOptions:
          deleteEmptyDirData: true
          enabled: true
          force: true
          ignoreDaemonSets: true
          postDrainHooks:
          - annotation: harvesterhci.io/post-hook
          preDrainHooks:
          - annotation: harvesterhci.io/pre-hook
          timeout: 0
```

In the middle of the upgrade, we found node condoning, hooks, and RKE2 upgraded are performed on multiple nodes at the same time. In the environment we tested, it's `harvester-node-2` and `harvester-node-3`:

```
harvester-node-0:~ # kubectl get nodes
NAME               STATUS                     ROLES                       AGE     VERSION
harvester-node-0   Ready                      control-plane,etcd,master   8h      v1.22.4+rke2r2
harvester-node-1   Ready                      control-plane,etcd,master   7h56m   v1.22.4+rke2r2
harvester-node-2   Ready,SchedulingDisabled   control-plane,etcd,master   7h43m   v1.22.4+rke2r2
harvester-node-3   Ready,SchedulingDisabled   <none>                      7h27m   v1.22.4+rke2r2
```

**Result**

Multiple nodes are upgraded at the same time.

**Expected Result**

The node should be upgraded one by one.

**Additional context**
- Harvester support bundle: https://github.com/harvester/harvester/files/7746633/supportbundle_6ef2a384-9005-4692-a4d7-c7ac911e69ed_2021-12-20T13-24-43Z.zip
- rancher pod logs: 
[rancher-7b5f66c7cb-gndj6.log](https://github.com/rancher/rancher/files/7801080/rancher-7b5f66c7cb-gndj6.log)
[rancher-7b5f66c7cb-q2gq6.log](https://github.com/rancher/rancher/files/7801081/rancher-7b5f66c7cb-q2gq6.log)

@ibuildthecloud  This was spotted when testing a Harvester upgrade, it can't be always reproed. I'm not quite sure what info will be helpful for debugging, if you can provide some guidelines, I can capture them if I saw it again.
