### ISSUE TITLE
v2.6 KDM - Tracking issue for K3s k8s January Patches

### ISSUE THREAD

**Issue by katran001** [rancher/rancher#36011]
This is the tracking issue for the K3s January k8s Patches. We should be checking/validating the following versions:

v1.22.6
v1.21.9
v1.20.15

**Comment by rancher-max** [comment]
As part of this, we will also add `system-default-registry` as an agent flag for https://github.com/rancher/rancher/issues/35922

**Comment by rancher-max** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/802

**Comment by rancher-max** [comment]
#### Validated using rancher v2.6.3 with KDM pointing to dev-v2.6 branch

- Versions are as expected and defaults are as expected, although I'm unsure why k3s is showing as experimental.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/55997940/151624868-cdf7d67c-986a-4b44-b2f8-7c4d38b42a48.png">

- Provisioning a cluster using 3 server nodes is successful for both versions
- Upgrading an imported cluster shows all expected versions:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/55997940/151629660-3f18bd1f-4ce1-4122-8c3d-46607eda038f.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/55997940/151629684-50e2a7d3-4cf7-46fd-9c10-3bbab1951049.png">

- Upgrading to the latest in each of those version lines is successful
- Confirmed system-default-registry flag is present in KDM and is passed through similar to rke2 when filling out the private registry field in the UI. Here's a snippet when viewing Edit as YAML for that:
```
...
machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          system-default-registry: some-fake-reg
#      - config:
#          
#        machineLabelSelector:
#          matchExpressions:
#            - key: string
#              operator: string
#              values:
#                - string
#          matchLabels:
#            key: string
    registries:
      configs:
        {}
...
```

### Leaving this issue open to address the following potential issue:
1. v1.21.9+k3s1 shows experimental during provisioning (and only during provisioning. Note v1.21.8+k3s2 did NOT show experimental. Also, v1.21.9+k3s1 does not show experimental during upgrade.)
