### ISSUE TITLE
Update RKE Downstream cluster failed: Not a valid ECR registry, requeuing

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#36093]
**Rancher Server Setup**
- Rancher version: 2.6.3,2.6.2

**Describe the bug**
Enabling private registry should not add ecr_credential_plugin by default

**To Reproduce**
- Install Rancher v2.6.2 or v2.6.3
- Deploy an RKE cluster
- Enable private registry after deployment and check the registry setting
- Cluster manager -> Edit config -> Enable private registry   Cluster manager -> Edit config -> Enable private registry   
For testing purpose , set it as registry.hub.docker.com 
- Apply the spec 
- Cluster manager -> Edit config _> View as YAML 
- The private registry adds ecr_credential_plugin even though we didn't specify it 

**Result**
The private registry adds ecr_credential_plugin even though we didn't specify it 
**Expected Result**
The ecr_credential_plugin is not on our registry 

**Additional context**
Troubleshooting steps:

Tried to remove the ecr_credential_plugin , but it came back after reconciliation 
Tried with both UI and YAM, but still, ecr_credential_plugin appeared in the private registry

SURE-3873
SURE-3997

**Comment by jiaqiluo** [comment]
The bug is reproduced in v2.6.3

when updating a cluster via Rancher UI, the following values are added in the payload of the PUT request to the endpoint `v3/clusters/c-smz6w?_replace=true`

```
rancher_kubernetes_engine_config:
  ...
  private_registries:
    - ecr_credential_plugin: {}
      is_default: true
      url: registry.hub.docker.com
```

The following is in the response:
```
rancher_kubernetes_engine_config:
  ...
  private_registries:
    - ecr_credential_plugin:
        type: "/v3/schemas/ecrCredentialPlugin"   <--------- Here the problem is!  
      is_default: true
      url: registry.hub.docker.com
```

Error in Rancher UI
```
This cluster is currently Provisioning.

Not a valid ECR registry
```

**Comment by jiaqiluo** [comment]
The bug cannot be reproduced in rancher:v2.6-head e7f03fd

I guess it might be fixed by other changes in the release-v2.6 branch, such as bumping the version of dependencies and packages. 

Move it to test.

**Comment by slickwarren** [comment]
hmm, I can reproduce this on both 2.6.4-alpha3 and 2.6-head(c682e30).
steps to repro:
* provision rke1 cluster (1.22.5)
* wait for cluster to come to active state, then edit the cluster
  * enable and add something to the registry field
  * edit as yaml, user can see the following:
```
rancher_kubernetes_engine_config:
  ...
  private_registries:
    - ecr_credential_plugin: {}
      is_default: true
      url: registry.hub.docker.com
```
* save changes to the cluster -- The following is in the response:
```
rancher_kubernetes_engine_config:
  ...
  private_registries:
    - ecr_credential_plugin:
        type: "/v3/schemas/ecrCredentialPlugin"   <--------- this is the issue
      is_default: true
      url: registry.hub.docker.com
```

Error in Rancher UI
```
This cluster is currently Provisioning.

Not a valid ECR registry
```
* cluster is stuck in `updating` state
<img width="549" alt="Screen Shot 2022-02-02 at 11 33 22 AM" src="https://user-images.githubusercontent.com/16691014/152223866-eec16574-13cd-4685-adda-95353cc76a18.png">
