### ISSUE TITLE
[2.6.3] Error -  Unknown schema for type: management.cattle.io.cluster

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#36102]
**Rancher Server Setup**
- Rancher version: v2.6.3 (3c1d5fac3)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin
   
**Describe the bug**
When I work with an external imported cluster and refresh page I see this error. On this page when I click reload, the page reloaded but content is apsent

**To Reproduce**
* Setup new k8s cluster use 3 VPS(only for running rancher)
* Install Rancher on helm chart into `rancher cluster`
```
bootstrapPassword: **********************

replicas: 3

ingress:
  enabled: false

tls: external
#tls: ingress
resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

```
* Setup new k8s cluster use 3 VPS(for Downstream management)
* login into rancher with Admin user
* open tab Cluster manager
* Click to button "Import exist"
* Import Downstream cluster to rancher

**Result**
* When I work with Downstream cluster and I refresh the page sometimes I see this error text

**Expected Result**
Page refreshed and display content

**Screenshots**
![image](https://user-images.githubusercontent.com/8457572/148904945-f8440873-2e26-4bc5-bf0a-fa923e981e92.png)

**Additional context**
![](https://visitor-badge.glitch.me/badge?page_id=rancher_rancher_issues_36102)
