### ISSUE TITLE
Files secret not passed to rancher-machine command

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#36109]
**Rancher Server Setup**
- Rancher version: v2.6-head

**Information about the Cluster**
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Provisioned RKE2

**Describe the bug**
When passing cloud-config data to the create job, a files secret is created and things like the cloud-config contents are put into the secret and volumes are created for the job. This construction needs to happen before the `cmd` is created so the file gets passed to the command instead of its contents. A previous change reorder this and broke it.

**To Reproduce**
 
1. Provision an RKE2 cluster and pass cloud-config information. The bug was found with VSphere.

**Result**
The machine will not be created.

**Expected Result**
The machine should be created and the cluster should come up.

**Comment by slickwarren** [comment]
tested using 2.6.4-rc3 in vsphere. 

cloud config used: 
```
#cloud-config
password: password
chpasswd: {expire: False}
sshpwauth: True
```

* provision single node, all roles rke2 cluster (1.22.6-rke2r1) with above cloud config -- fail


Note: I was able to provision the same cluster, without the cloud config, with no issues.

**Comment by slickwarren** [comment]
tested on v2.6-head (024e6fa):
user is now able to add cloud config data to both rke1 and rke2 clusters. Example used with vsphere for 1.23 (for both rke1 and rke2):
```
#cloud-config
users:
  - default
  - name: rancher
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    no_ssh_fingerprints: true
    groups: users, sudo
    hashed_passwd: $HASHED_PASSWD
    ssh_authorized_keys:
    - $YOUR_SSH_KEY
ssh_authorized_keys:
  - $YOUR_SSH_KEY
write_files:
- path: /root/CLOUD_INIT_WAS_HERE
```
