### ISSUE TITLE
Pods for some type of deployments fail to become Active in a hardened Rancher server 

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36125]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: byo valid certs

**Information about the Cluster**
- Kubernetes version: v1.21.5
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
 
**Describe the bug**

Some workloads fail to become Active in a hardened Rancher server.
Pod error: `Error: container has runAsNonRoot and image will run as root (pod: "nginx-57787f676d-fhktk_default(7f355c86-e57e-43f4-aa46-e1e42b7410cf)", container: container-0)`

**To Reproduce**
 
1. Create a HA clutser 
2. Install Rancher
3. Harden the cluster https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/

Create a deployment with `nginx:latest` image
OR
install rancher gatekeeper app
OR 
create a cron job 
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Result**
All those workloads/deployments fail with pods returning errors:
`Error: container has runAsNonRoot and image will run as root`

**Expected Result**

All expected pods running successfully 

**Screenshots**

![errros](https://user-images.githubusercontent.com/40282141/149238278-b4b3db70-4736-4096-a584-091f0dfa3d68.jpg)

**Additional context**
