### ISSUE TITLE
[release/v2.6] HorizontalPodAutoscalers display metrics wrong

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#36169]
**Rancher Server Setup**
- Rancher version: v2.6.3 (3c1d5fac3)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin

**Describe the bug**
In deployed HorizontalPodAutoscalers with two metrics, it displays duplicated value.

**To Reproduce**
Perform Deployment with two metrics(CPU and Memory)
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```
Open tab HorizontalPodAutoscalers then open info about hpa
compare values with console ``` kubectl get hpa backend-app ```

**Result**
In all metrics item rancher display CPU metrics displays

**Expected Result**
In CPU, the CPU target values and in Memory, memory target values should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/8457572/149741345-fb38424b-d01d-4081-ad86-e5b796a3310c.png)
![image](https://user-images.githubusercontent.com/8457572/149741266-c183743b-786f-4784-a1fe-59ad5b5367ea.png)

**Additional context**
