### ISSUE TITLE
 Imported cluster not deleted

### ISSUE THREAD

**Issue by rjbaat** [rancher/rancher#36225]
I tried deleting an imported DigitalOcean cluster. I deleted the cluster first from DO and then I wanted to delete is from rancher.
But now its stuck in deletion. 

I have several namespaces that can't be deleted from my rancher local instance. 

Iam running rancher 2.5.11

What can I do to get rid of the imported cluster from my rancher instance?

The namespace of the cluster I want to delete gives me this conditions:

```
status:
  conditions:
  - lastTransitionTime: "2022-01-20T14:54:37Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-01-20T14:54:37Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-01-20T14:54:37Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-01-20T14:54:37Z"
    message: 'Some resources are remaining: clusterroletemplatebindings.management.cattle.io
      has 2 resource instances, nodes.management.cattle.io has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-01-20T14:54:37Z"
    message: 'Some content in the namespace has finalizers remaining: clusterscoped.controller.cattle.io/cluster-crtb-sync_c-225nd
      in 2 resource instances, controller.cattle.io/mgmt-auth-crtb-controller in 2
      resource instances, controller.cattle.io/node-controller in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```

And this project namespaces:

```
status:
  conditions:
  - lastTransitionTime: "2022-01-20T14:54:43Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-01-20T14:54:43Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-01-20T14:54:43Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-01-20T14:54:43Z"
    message: 'Some resources are remaining: projectroletemplatebindings.management.cattle.io
      has 2 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-01-20T14:54:43Z"
    message: 'Some content in the namespace has finalizers remaining: clusterscoped.controller.cattle.io/cluster-prtb-sync_c-225nd
      in 2 resource instances, controller.cattle.io/mgmt-auth-prtb-controller in 2
      resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```

Any idea how I can remove the cluster and its related resources?
