### ISSUE TITLE
Modifying a cluster's label doesn't remove the bundles applied via clusterSelector

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36241]
Issue description:
After creating a GitRepo with clusters selected by labels, modifying the labels on the cluster (so they no longer match) doesn't remove the bundle from the cluster.

Business impact:
<text>

Troubleshooting steps:
<text>

Repro steps:

 ** Create a GitRepo with this yaml:

 

```
apiVersion: fleet.cattle.io/v1alpha1
type: fleet.cattle.io.gitrepo
kind: GitRepo
metadata:
  name: test-my-labels
  namespace: fleet-default
spec:
  branch: master
  paths:
  - simple
  repo: https://github.com/rancher/fleet-examples
  targets:
  - clusterSelector:
      matchLabels:
        some: label
    name: label-tester
```

 

Then apply `some: label` to a cluster. Notice that it's applied to that cluster.

Modify the label or delete it from the cluster. Notice that it doesn't get removed from that cluster.

Actual behavior:
It doesn't get removed from that cluster.

Expected behavior:
It gets removed from the cluster.

Additional notes:
The reverse works. Creating the GitRepo with the cluster label selector and then adding the label to the cluster causes the bundles to be applied to it.

Applying a Force Update to the GitRepo in Rancher causes it to kick off and delete the bundles.

SURE-3002
