### ISSUE TITLE
Rancher UI requires "Username" field for basic-auth secrets

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#36248]
**Rancher Server Setup**
- Rancher version: 
2.6.1
- Installation option (Docker install/Helm Chart): 
Docker + Helm installs are affected

**Information about the Cluster**
- Kubernetes version:
v1.21.8+rke2r2 
- Cluster Type: 
Local, Custom + Imported + Hosted clusters are all affected

**User Information**
- What is the role of the user logged in?
Admin

**Describe the bug**
Kubernetes will allow you to create a basic-auth secret without a username or password. 
Kubernetes specs advise that either username OR password fields be present, not simply the Username.
https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret
 
When viewing a basic-auth secret in the Rancher UI that *does not have a username field saved*, the UI will fail to decode the secret:
TypeError: e is undefined
    base64Decode index.js:48
    get secret.class.js:201

**To Reproduce**
Import this secret, and try to view the secret in the Rancher UI
```
apiVersion: v1
data:
  password: Y2hhbmdlLW1lLWluLXByb2Q=
kind: Secret
metadata:
  name: jwt-token
  namespace: test
type: kubernetes.io/basic-auth
```

In order to get the UI to show the secrets for the namespace, you need to edit the secret and add an encoded username field:
```
apiVersion: v1
data:
  username: aGVsbG8K
  password: Y2hhbmdlLW1lLWluLXByb2Q=
kind: Secret
metadata:
  name: jwt-token
  namespace: test
type: kubernetes.io/basic-auth
```

**Result**
The secrets pane never loads

**Expected Result**
The secrets pane should load
