### ISSUE TITLE
Need to be able to set resource limits to cattle-cluster-agent (in a easy Rancher way)

### ISSUE THREAD

**Issue by thsnielsen** [rancher/rancher#36276]
Internal reference: https://jira.suse.com/browse/SURE-9655

**Is your feature request related to a problem? Please describe.**
Customer worry about the cattle-cluster-agent gets deployed where there are not sufficient resources, and therefore want to define resource limits.

**Describe the solution you'd like**
Resource limits CAN be set on cattle-cluster-agent, but it is cumbersome, and should be settable in Rancher UI
Expected behavior:
 cattle-cluster-agent resource limits should be settable in the Rancher UI with __suggested values and minimum requirement__
 something like the end of this :
 ```- name: CATTLE_SERVER_VERSION
      value: v2.6.3
    - name: CATTLE_INSTALL_UUID
      value: aabbaabb-1a3b-1234-8f3c-6e77fcf12345
    - name: CATTLE_INGRESS_IP_DOMAIN
      value: sslip.io
    image: docker-dev-virtual.repository.customer.intra/rancher/rancher-agent:v2.6.3
    imagePullPolicy: IfNotPresent
    name: cluster-register
    resources:
      limits:
        cpu: "1"
        memory: 3Gi
      requests:
        cpu: 50m
        memory: 64Mi
```
**Describe alternatives you've considered**
Workaround / What is the workaround:
Yes, the work around is customer doing like this, but it is not "nice" :
`kubectl patch deployment cattle-cluster-agent --patch "$(cat tmp.yaml)" -n cattle-systemwith this file tmp.yaml` :
```
spec:
  template:
    spec:
      containers:
      - name: cluster-register
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 250m
            memory: 500Mi
```

**Additional context**
Business Case:
 Customer is in the process of (considering progressing and well intended) to move 10000+ pods from a competitor to rke2 Rancher, and we try hard to listen to their demands. They worry about the cattle-cluster-agent gets deployed where there are not sufficient resources, and therefore want to define resource limits.
