### ISSUE TITLE
embedded KDM data is not consistent with RKE1 data

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#36346]
**Steps to reproduce**
- Rancher image: `rancher/rancher:v2.6-da382a88600d0272d48537c5de88b3ce0ede6dd3-head`
- Provision RKE1 cluster using any of the following k8s versions: 
   - `v1.21.8-rancher2-2`
   - `v1.20.14-rancher2-2`
   - `v1.19.16-rancher1-3` 
- Cluster comes up active. nginx ingress controller in system project will show errors in logs like, 
`
E0913 18:50:22.898485 8 leaderelection.go:361] Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress-nginx:ingress-nginx" cannot update resource "configmaps" in API group "" in the namespace "ingress-nginx"
`

**Analysis**

The issue is RKE1 doesn't have the latest data Rancher is using, so there's inconsistency between embedded data and data vendored in RKE. 

- k8s version is using the correct nginx ingress image `nginx-1.1.0-rancher1` but with the wrong template. View yaml on the nginx ingress controller daemonset - shows that it's using the old template. 
```
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.49.3
```
- RKE1 is using the old template, because Rancher thinks it doesn't need to send the new template `v3/rkeAddons/cattle-global-data:nginxingress-v1.1.0-rancher2` 
```
  "io.cattle.rke_store": "false"
```
