### ISSUE TITLE
Allow public access to well-known and openid/v1/jwks

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#36444]
**Is your feature request related to a problem? Please describe.**

Related to the feature request about Rancher 2 providing certain flags regarding service account issuer and jwk urls https://github.com/rancher/rancher/issues/36443

This request is to allow for `k8s/clusters/<id>/.well-known/openid-configuration` and `k8s/clusters/<id>/openid/v1/jwks` to be accessibly without authenticating to the Rancher 2 API.

The use case is to allow federation of authentication and token exchange. For example Azure Workload Identity allows you to authenticate to Azure as a service principal with a JWT signed by the cluster so long as it can access and validate the openid configuration and the jwks. From there Azure will provide a token for the service principal that can then be used against the rest of Azure.

**Describe the solution you'd like**

- Allow public/unauthorized (no auth header) access to to `k8s/clusters/<id>/.well-known/openid-configuration` and `k8s/clusters/<id>/openid/v1/jwks`

**Describe alternatives you've considered**

Publishing the data at those two location to a different domain and writing a tool to keep it in sync.

**Comment by domruf** [comment]
@ekristen correct me if I'm wrong, but AFAIS .../.well-known/openid-configuration and .../openid/v1/jwks are not available at all on a rancher cluster. No matter if authenticated or not.

**Comment by ekristen** [comment]
They are by default after 1.21 or 1.22, but you can also turn them on my setting the right feature gate.

**Comment by domruf** [comment]
My IT department provided me with a rancher 2.6 cluster with kubernetes 1.21. But neither on the rancher URL nor the kubernetes api server URL .../.well-known/openid-configuration and .../openid/v1/jwks are available.
But according to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ ServiceAccountIssuerDiscovery should be enabled since kubernetes 1.20.

**Comment by websi96** [comment]
I discoverd that this only works on downstream clusters and not on the local cluster.
My solution now was to create an ingress for the default endpoint:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: YOUR_ISSUER
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: YOUR_HOST
    http:
      paths:
      - path: /.well-known/openid-configuration
        pathType: Exact
        backend:
          service:
            name: kubernetes
            port:
              number: 443
      - path: /openid/v1/jwks
        pathType: Exact
        backend:
          service:
            name: kubernetes
            port:
              number: 443
  tls:
  - hosts:
    - YOUR_HOST
    secretName: oidc-ingress-tls
```
