### ISSUE TITLE
[RBAC] permission not apply for some users

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#36458]
**Rancher Server Setup**
- Rancher version: v2.6.3 (3c1d5fac3)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin
   
**Describe the bug**
When I apply some rules for users which use google auth? some rules are not applied.

**To Reproduce**
1. Create custom RBAC rules for cluster and project:
```
apiVersion: management.cattle.io/v3
builtin: false
context: project
description: ""
displayName: Project-ReadOnly-Pods
external: false
hidden: false
kind: RoleTemplate
metadata:
  name: project-readonly-pods
  labels:
    authz.management.cattle.io/bootstrapping: default-roletemplate
    cattle.io/creator: norman
  annotations:
    cleanup.cattle.io/rtUpgradeCluster: "true"
    lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle: "true"
  finalizers:
    - controller.cattle.io/mgmt-auth-roletemplate-lifecycle
roleTemplateNames:
  - view
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: management.cattle.io/v3
builtin: false
context: cluster
description: ""
displayName: Cluster Common
external: false
hidden: false
kind: RoleTemplate
metadata:
  name: cluster-common
  annotations:
    cleanup.cattle.io/rtUpgradeCluster: "true"
    lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle: "true"
  labels:
    authz.management.cattle.io/bootstrapping: default-roletemplate
    cattle.io/creator: norman
  finalizers:
    - controller.cattle.io/mgmt-auth-roletemplate-lifecycle
rules:
  - apiGroups: ["ui.cattle.io"]
    resources: ["navlinks"]
    verbs: ["get", "list", "watch"]
```
2. Configure Google auth in Auth Provider
3. Login with any google user(for example test1@company.com)
4. Logout
5. Login as cluster admin
6. Open tab RBAC in the cluster
7. Assign cluster-common role to user test1@company.com
8. Open tab project Projects/Namespaces
9. Create a new project, and attach user test1@company.com with rule Project-ReadOnly-Pods
10. Logout
11. Login using test1@company.com

**Result**
I see so many resources, and I can change secrets, scale deployment, end etc...
![Screenshot_20220209_104213](https://user-images.githubusercontent.com/8457572/153159556-6f3313f1-7386-4e52-8168-e6bb4fd662a1.png)

**Expected Result**
I see only pods in read only mode
![Screenshot_20220209_104122](https://user-images.githubusercontent.com/8457572/153159701-19eaea64-7b29-4499-a1ab-58e29d6cec84.png)

**Additional context**
When I test this case using base user(create in GUI), this permission works correctly.
![](https://visitor-badge.glitch.me/badge?page_id=rancher_rancher_issues_)
