### ISSUE TITLE
ConfigMap name for nginx-ingress changed after upgrade

### ISSUE THREAD

**Issue by ThorstenKunz** [rancher/rancher#36484]
**Rancher Server Setup**
- Rancher version: 2.5.12
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: 1.20.15
- Cluster Type (Local/Downstream): local

**Describe the bug**
I upgraded the k8s version from 1.18.20 to 1.20.15 and after the upgrade all of my nginx config map options specified under `ingress.options` in the cluster config were completely ignored. What I found is that there are now two different ConfigMaps for the nginx-controller:
- the old one `nginx-configuration`: this one contained all the nginx options I specified in the cluster configuration
- the new one `ngress-nginx-controller`: this one is empty

The issue now is that the nginx-controller was started with the following parameter: `'--configmap=$(POD_NAMESPACE)/ingress-nginx-controller'` which makes the controller use the new but empty one.
So it would be great for rke and nginx-controller to agree what ConfigMap is the right one. For now I modified the DaemonSet for the nginx-controller to use the old ConfigMap name and everything works. But this will most likely break when the next upgrade is being executed?

Thanks

Thorsten

**Comment by barryboubakar** [comment]
I have the same issue after upgrading from Kubernetes 1.18.10 to 1.20.15.

**Comment by jeroenhartgers** [comment]
Same issue here. I just moved all the nginx variables to the ingress-nginx-controller ConfigMap and I removed the "old" nginx-configuration ConfigMap. (Which is quite obvious of course)

**Comment by junkiebev** [comment]
rke also doesn't populate the new configmap from answers provided to cluster.yaml

**Comment by jeroenhartgers** [comment]
> rke also doesn't populate the new configmap from answers provided to cluster.yaml

Environment:

- RHEL 8.4
- RKE1 v1.3.3 
- k8s v1.21.7
- Rancher 2.6.2

@junkiebev In my environment, all the cluster.yaml entries were correctly populating the new ingress-nginx-controller ConfigMap .

This is part of my cluster.yaml:

`ingress:
  provider: nginx
  options:
    client-body-buffer-size: "128k"
    client-header-buffer-size: "5120k"
    client-max-body-size: "10m"
    large-client-header-buffers: "16 5120k"
    proxy-body-size: "60m"
    proxy-connect-timeout: "60"
    proxy-read-timeout: "611"
    proxy-next-upstream: "off"`

**Comment by vivek-infracloud** [comment]
Validated on rancher v2.5-head

Steps followed to validate.

- Installed rancher v2.5-head
- Provisioned a k8s cluster with following ingress options as mentioned [here](https://github.com/rancher/rancher/issues/36484#issuecomment-1060532809) for validation.

```
ingress:
  provider: nginx
  options:
    client-body-buffer-size: "128k"
    client-header-buffer-size: "5120k"
    client-max-body-size: "10m"
    large-client-header-buffers: "16 5120k"
    proxy-body-size: "60m"
    proxy-connect-timeout: "60"
    proxy-read-timeout: "611"
    proxy-next-upstream: "off"
```
- `nginx-configuration` configmap shows the above data.
- Updated the k8s cluster to v1.20.
- New configmap `ingress-nginx-controller` is created with same data as in `nginx-configuration`.

**Comment by vivek-infracloud** [comment]
Based on above validation, there won't be need of changing the name of DaemonSet for the nginx-controller to use as pointed out in the [issue](https://github.com/rancher/rancher/issues/36484#:~:text=For%20now%20I%20modified%20the%20DaemonSet%20for%20the%20nginx%2Dcontroller%20to%20use%20the%20old%20ConfigMap%20name%20and%20everything%20works).

Closing the issue based on above comments.

**Comment by vivek-infracloud** [comment]
Validated on rancher v2.5-head (7a5cee3) and upgrade scenario to k8s v1.19 from v1.18

Steps followed to validate.

- Installed rancher v2.5-head
- Provisioned a k8s cluster v1.18 with following ingress options as mentioned [here](https://github.com/rancher/rancher/issues/36484#issuecomment-1060532809) for validation.

```
ingress:
  provider: nginx
  options:
    client-body-buffer-size: "128k"
    client-header-buffer-size: "5120k"
    client-max-body-size: "10m"
    large-client-header-buffers: "16 5120k"
    proxy-body-size: "60m"
    proxy-connect-timeout: "60"
    proxy-read-timeout: "611"
    proxy-next-upstream: "off"
```
- `nginx-configuration` configmap shows the above data.
- Updated the k8s cluster to v1.19.
- New configmap `ingress-nginx-controller` is created with same data as in `nginx-configuration`.

After updating from v1.18 to v1.19 or v1.20 there won't be need of changing the name of DaemonSet for the nginx-controller to use as pointed out in the original issue description https://github.com/rancher/rancher/issues/36484#:~:text=For%20now%20I%20modified%20the%20DaemonSet%20for%20the%20nginx%2Dcontroller%20to%20use%20the%20old%20ConfigMap%20name%20and%20everything%20works.

Since issue is resolved, closing.
