### ISSUE TITLE
Node's external IP is set as the internal IP

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36507]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): Linode node driver cluster - 1 etcd, 1 cp and 3 worker nodes. Container network - `Cilium`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard user
   
**Describe the bug**
Node's external IP is set as the internal IP

**To Reproduce**

- Deploy an RKE2 cluster Linode
- Wait for the cluster to come up Active.
- Navigate to Cluster Explorer --> Nodes --> External and Internal IP
- The nodes have 1 IP address and the Internal IP addresses are set. The external IP addresses = `None`
- Yaml of the node also has the internal IP set
```
status:
  addresses:
  - address: Ip
    type: InternalIP
  - address: sowmya-cilium-pool1-83e7c181-xwv4t
    type: Hostname
```

**Expected result:**
The Ip is the external IP.
