### ISSUE TITLE
Rancher Logging v2 - UI - ClusterOutput form creates wrong YAML for secrets

### ISSUE THREAD

**Issue by belgaied2** [rancher/rancher#36515]
**Rancher Server Setup**
- Rancher version: v.2.6.3
- Installation option : Helm Chart on RKE

**Information about the Cluster**
- Kubernetes version: v1.20.7
- Cluster Type: Downstream
  
   
**Describe the bug**
UI of the ClusterOutput form in Rancher Logging V2 generates the wrong YAML for secrets.

**To Reproduce**
- Install Logging V2
- Add an Elasticsearch ClusterOutput (also types of backends have the same issue)
- In the Form, `CA File from secret` multiple choice menu, select a secret containing a certificate, then choose certificate name and click on `Edit as YAML`. 
- See the `ca_file.valueFrom` in the YAML where as `ca_file.mountFrom` should be expected. 

**Result**
Generating ClusterOutput YAML looks like:
```yaml
  elasticsearch:
    ca_file:
      valueFrom:
        secretKeyRef:
          key: ca.crt
          name: default-token-d8dvn
```

**Expected Result**
```yaml
  elasticsearch:
    ca_file:
      mountFrom:
        secretKeyRef:
          key: ca.crt
          name: default-token-d8dvn
```

**Screenshots**
ClusterOutput Form:
![image](https://user-images.githubusercontent.com/60746935/153956833-f291075d-f2ed-40b9-9a3b-1c6526f0f32a.png)

Generated YAML:
![image](https://user-images.githubusercontent.com/60746935/153956858-c7c4c734-ea13-48d9-90d1-5ee4fbfffaa9.png)

**Additional context**
This is also the same for other types of Logging backends, not limited to Elasticsearch.
