### ISSUE TITLE
RKE2 upgrade doesn't work if pre-drain/post-drain hooks are enabled

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#36536]
**Rancher Server Setup**
- Rancher version: `v2.6-11a7451ffee557897197fc624af03ac6fd34a9f0-head`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `v1.21.7+rke2r1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.21.7+rke2r1`
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

Upgrading an RKE2 runtime doesn't seem to work if [pre-drain and post-drain hooks](https://github.com/rancher/rancher/issues/35464) are enabled.

**To Reproduce**
 
- Use rancherd to provision an RKE2 cluster that has an embedded rancher server
- Upgrade the RKE2 cluster by editing the cluster resource:
```
kubectl edit clusters.provisioning.cattle.io local -n fleet-local
```

Update the existing spec from:
```
spec:
  kubernetesVersion: v1.21.7+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig: {}
```

to

```
spec:
  kubernetesVersion: v1.21.8+rke2r2
  localClusterAuthEndpoint: {}
  rkeConfig:
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      workerConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
        preDrainHooks:
          - annotation: harvester.cattle.io/pre-hook
        postDrainHooks:
          - annotation: harvester.cattle.io/post-hook
      workerDrainOptions:
        deleteEmptyDirData: true
        enabled: true
        force: true
        ignoreDaemonSets: true
        preDrainHooks:
          - annotation: harvester.cattle.io/pre-hook
        postDrainHooks:
          - annotation: harvester.cattle.io/post-hook
```

**Result**
- The upgrade doesn't seem to begin, the pre-hook annotation on CAPI machine is not set (supposed to have a `harvester.cattle.io/pre-hook` annotation)
```
╰─$ k get nodes
NAME    STATUS   ROLES                       AGE     VERSION
node1   Ready    control-plane,etcd,master   5h40m   v1.21.7+rke2r1
node2   Ready    <none>                      65m     v1.21.7+rke2r1

╰─$ k get machines -n fleet-local
NAME                  CLUSTER   NODENAME   PROVIDERID     PHASE     AGE     VERSION
custom-30618c47c2e9   local     node2      rke2://node2   Running   61m
custom-a7fea0bdcbdd   local     node1      rke2://node1   Running   5h31m

╰─$ k get machine custom-a7fea0bdcbdd -n fleet-local -o yaml | yq e .metadata.annotations -
objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5yTQY+bPhDFv8pfc4ZswsI/gNRLq55W7SGteh/b4+BgbGIPhO4q370iW2U3jZq2e7R4z7w3v/ETdMSokBHqJ0DnPCMb7+J89GJHkiPxIhi/kMhsaWH8nVFQw+A6dLgllXYoG+MIkt8a/MFRSLdjCzXcjavkvwfj1LsvJAPxH20OO4Ia5BDZdymuNeFSKCmU+itr7FHOfuslWjgmIAOdKn41HUXGrofaDdYmYFGQvVm8wdhADUWWVzoXuc4qWZVUZav7UuY6y/VquVovSWTyfp3l/0MCoaVXfmmHyC+VniNdibzj4G3aW3SUBm9nKYeBrpTEUt0U/CSTnoAVj9O4U0XVRK6KzD5mYnJZ29p+2u9FtStD7HJRtvlkD7LR22LfTWU+Xt158KGlcPHbYwI3Ib3GoC0Rp2cYsSc5T1x4z5ED9vNBeqfNdkP6tJO9+UYhGu+g/iXKuIIEWuPmdpuHj+/Pd7w1z7wdz4g+XxIyTgeMHAbJQ6B/S/bhlOHT+ZG8OVpk5CFeTGtDqL5DrdFGuk758u14/BEAAP//IqwLl+kDAAA
objectset.rio.cattle.io/id: unmanaged-machine
objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
objectset.rio.cattle.io/owner-name: custom-a7fea0bdcbdd
objectset.rio.cattle.io/owner-namespace: local
```

**Expected Result**

`harvester.cattle.io/pre-hook` annotation should be set on the CAPI machine, so Harvester will perform pre-drain operations like live-migrate VMs.

**Screenshots**

**Additional context**

Rancher logs:
[rancher-58c78b84db-kgl8k.log](https://github.com/rancher/rancher/files/8081344/rancher-58c78b84db-kgl8k.log)
[rancher-58c78b84db-gclr2.log](https://github.com/rancher/rancher/files/8081346/rancher-58c78b84db-gclr2.log)

**Comment by bk201** [comment]
If I remove the options:
```
        preDrainHooks:
          - annotation: harvester.cattle.io/pre-hook
        postDrainHooks:
          - annotation: harvester.cattle.io/post-hook
```

The upgrade will be complete without error (nodes are also drained during the upgrade).
