### ISSUE TITLE
Blocked in "waiting for agent to check in and apply initial plan"

### ISSUE THREAD

**Issue by caatclaudia** [rancher/rancher#36534]
### Rancher Server Setup
- Rancher version: v.2.6.3

### Information about the Cluster
- Installation option:
   - Helm version: v3.8.0
   - k3s version: v1.22.6+k3s1
- Openstack:
   - Microstack Installation - version ussuri, Revision 245

### Describe the bug

I want to integrate OpenStack Cloud Provider in the Rancher interface. To do that in the Drivers tab (on Rancher Interface) I enabled the option "_OpenStack_".
Then, I created a Cluster with “_RKE2/K3s_” and OpenStack options. Filled the following parameters:
```
authURL: https://XX:5000/v3
availabilityZone: nova
domainId: default
flavorId: 1
floatingipPool: XX
imageName: cirros
ipVersion: 4
keypairName: XX
netId: XX
privateKeyFile: <content of XX.pem>
region: XX
secGroups: default
sshPort: 22
sshUser: XXX
tenantId: XX
userDomainId: default
username: admin
```

In "_Cluster Configuration_", I selected "_External_" in the Cloud Provider field and "_v1.21.9+rke2r1_" in the Kubernetes Version field and placed the following configuration in "_Cloud Provider Config_":
cloud_provider:
```
 name: openstack
  openstackCloudProvider:
    global:
      username: admin
      password: XX
      auth-url: https://XX:5000/v3
      tenant-id:  XX
      domain-id: default
    load_balancer:
      subnet-id: XX
    block_storage:
      ignore-volume-az: true
    route:
      router-id: XX
```

When I clicked on "_Create_" and verified on "_Provisioning Log_" in the Cluster, this is the output:

> ![image](https://user-images.githubusercontent.com/56655085/154287713-77bc4480-3f3a-4d43-8473-edc9518688a2.png)

On the Kubernetes side, the container that has been created in the log "creating server (OpenstackMachine) in infrastructure provider" is in the "Completed" state.

### Result
In Rancher Interface, the "_Provisioning Log_" doesn't show any error or warning, but also doesn't move forward. 

### Expected Result
In Rancher Interface, the "_State_" of the Cluster should become "_Active_"

### To Reproduce
Create a Cluster with the configuration mentioned.
