### ISSUE TITLE
cluster unmanageable with etcd/controlplane only (all workers down)

### ISSUE THREAD

**Issue by patrikbeno** [rancher/rancher#36542]
RKE 1.3.7, Rancher 2.6.3

There is no way to schedule rancher + rancher-webhook components to master/controlplane nodes

If all regular workers are down (leaving only etcd/controlplane components), cluster becomes unmanageable since rancher-webhook has no node to run on, and webhooks fail

Currently, rancher helm chart **does not** allow following:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/controlplane
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/controlplane
        operator: Exists
```

This can be worked around by kustomize post-renderer.

However, since rancher-webhook is deployed by rancher itself, such configuration is (of course) ignored by rancher-webhook helm release.
