### ISSUE TITLE
"Waiting for SSH to be available" message

### ISSUE THREAD

**Issue by caatclaudia** [rancher/rancher#36551]
### Rancher Server Setup
Rancher version: v.2.6.3
### Information about the Cluster
Installation option:
- Helm version: v3.8.0
- k3s version: v1.22.6+k3s1
Openstack:
- Microstack Installation - version ussuri, Revision 245

### Describe the bug
I want to integrate OpenStack Cloud Provider in the Rancher interface. To do that in the Drivers tab (on Rancher Interface) I enabled the option "_OpenStack_".
Then, I created a "_Node Template_" with the following options:

```
authURL: https://XX:5000/v3
availabilityZone: nova
domainId: default
flavorId: 1
floatingipPool: XX
imageName: cirros
ipVersion: 4
keypairName: <keyPair to SSH to the instance>
netId: <network "test" ID>
password: XX
privateKeyFile: <content of XX.pem>
region: XX
secGroups: default
sshPort: 22
sshUser: <user to OpenStack machine>
tenantId: XX
userDomainId: default
username: admin
```

Then, I created a Cluster with “_RKE1_” and OpenStack options. I selected Node Template that I have created and options "etcd", "Control Plane" and "Worker". In "_Cluster Options_", I selected "_External_" in the Cloud Provider field and edit the YAML to introduce the following configuration:
```
cloud_provider:
 name: openstack
  openstackCloudProvider:
    global:
      username: admin
      password: XX
      auth-url: https://XX:5000/v3
      tenant-id:  XX
      domain-id: default
    load_balancer:
      subnet-id: XX
    block_storage:
      ignore-volume-az: true
    route:
      router-id: XX
bastion_host:
  port: '22'
  ssh_agent_auth: true
  user: <User of instance>
```
When I clicked on "_Create_" and verified on "_Provisioning Log_" in the Cluster, this is the output:

![image](https://user-images.githubusercontent.com/56655085/154510571-89c3e402-f391-422d-9292-6e8181cf6740.png)

### Result
In Rancher Interface, the "_Provisioning Log_" shows the message "_Waiting for SSH to be available..._".

### Expected Result
In Rancher Interface, the "_State_" of the Cluster should become "_Active_"

### To Reproduce
Create a Cluster with the configuration mentioned.
