### ISSUE TITLE
KMS Custom Encryption Error while applying YAML

### ISSUE THREAD

**Issue by luker31337** [rancher/rancher#36577]
**Rancher Server Setup**
Rancher: v2.6.3
Helm: v2.16.8-rancher1
Machine: v0.15.0-rancher73

**Describe the bug**
Unable to add KMS configuration to cluster config as outlined here: https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#example-using-custom-encryption-configuration-with-amazon-kms

Issue appears to be with the YAML validation when saving in the UI.

**To Reproduce**
Following all steps to KMS doesn't appear to be necessary since it seems to be part of the YAML validation when the user attempts to save the configuration.
1. Add the following under **kube-api** section when using "Edit as YAML" in the cluster Config.
```
    extra_binds:
      - "/var/run/kmsplugin/:/var/run/kmsplugin/"
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
          - resources:
            - secrets
            providers:
            - kms:
                name: aws-encryption-provider
                endpoint: unix:///var/run/kmsplugin/socket.sock
                cachesize: 1000
                timeout: 3s
            - identity: {}
 ```

 2. Save the YAML

**Result**
```
Error while applying agent YAML, it will be retried automatically: exit status 1, The request is invalid: : {"Code":{"Code":"InvalidFormat","Status":422},"Message":"rancherKubernetesEngineConfig=InvalidFormat 422: services=InvalidFormat 422: kubeApi=InvalidFormat 422: secretsEncryptionConfig=InvalidFormat 422: customConfig=InvalidFormat 422: resources=InvalidFormat 422: providers=InvalidFormat 422: kms=InvalidFormat 422: timeout=InvalidFormat 422: InvalidFormat 422: Value can not be converted to type duration: 3s","Cause":null,"FieldName":""} 
```

**Expected Result**
YAML saves without error. Ideally, the rest of the KMS configuration was completed and the cluster is encrypted now.

**Screenshots**
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/89045171/154741089-85a75451-5d58-4729-919a-3e176bf3bfd4.png">

**Additional context**
- This was found after upgrading from Rancher 2.4.8, where we already have clusters with KMS enabled. There were no issues with the upgrade, but the clusters with KMS enabled can't be reached and the configs can't be editted. The clusters report the same error on the Cluster Management page.
- New, basic clusters can't be created either. The same error appears when attempting to create. 
- Templates can't be created. Receiving the same error.
- Assuming the validation of the YAML happens against all configurations, even when creating a new cluster.

**Comment by luker31337** [comment]
Also, removing the `timeout` line, allows the config changes to be validated.
```
    extra_binds:
      - "/var/run/kmsplugin/:/var/run/kmsplugin/"
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
          - resources:
            - secrets
            providers:
            - kms:
                name: aws-encryption-provider
                endpoint: unix:///var/run/kmsplugin/socket.sock
                cachesize: 1000
                timeout: 3s
            - identity: {}
   ```
