### ISSUE TITLE
Workload metrics tab not displayed

### ISSUE THREAD

**Issue by bla-ckbox** [rancher/rancher#36587]
**Rancher Server Setup**
- Rancher version: V2.6.3
- Installation option : Helm Chart on RKE1 cluster

**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type: Downstream
   - Custom (RKE1)

**User Information**
The basic permission is User-Base (login-access only).
User have a project role inspired by the View Workloads and View Config Maps role and which applyed to the project containing the workloads .
This is complemented by a second role that inherits the View Monitoring and Project Monitoring View Role and which is applied to the System project containing cattle-monitoring-system namespace .

**Describe the bug**
User cant see  the metrics tab on the workloads page.

**To Reproduce**
Create User with *View Workloads* role on a project and with minimu project role to see/access to the monitoring

**Result**
User can see/access to the monitoring
But workload-metrics tab not displayed when wiewing a workload (daemonset or statefullset for example)

**Screenshots**
![pod-no-metrics](https://user-images.githubusercontent.com/2076045/154799817-04b8bdf2-d89a-4629-919b-861ab8e39c95.png)

**Expected Result**
User can see  the metrics tab on the workloads page, for example here is what I see with my cluster owner profile:
![pod-tab-metrics](https://user-images.githubusercontent.com/2076045/154799951-74a6c9b9-4c5e-49a0-b094-189778123753.png)

**Additional context**
See https://forums.rancher.com/t/advanced-view-workloads-role/37032

**Comment by bla-ckbox** [comment]
I finally managed to bring up the metrics tab, it depends on the following permission:

```
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - list
```

I also solved another problem, because despite the tab being visible, an error popin appeared a few seconds after being on a page with metrics (this also applies to Grafana).

![metrics-popin-error](https://user-images.githubusercontent.com/2076045/154836558-ed1e8261-2af6-406d-992d-a69df2e97d78.png)

This is from a POST call on _frontend-metrics_ url:
![post403](https://user-images.githubusercontent.com/2076045/154836706-d1829bc0-979f-4244-8aa7-1616ad27657b.png)

I got around this by applying

```
- apiGroups:
  - '*'
  resources:
  - services/proxy
  verbs:
  - create
```

To summarize my role template to see the metrics gives this:
```
roleTemplateNames:
- monitoring-ui-view
- project-monitoring-readonly
rules:
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - list
- apiGroups:
  - '*'
  resources:
  - services/proxy
  verbs:
  - create
```
