### ISSUE TITLE
Not authorized to provision an RKE2 cluster using a bearer token created by a standard user

### ISSUE THREAD

**Issue by igomez06** [rancher/rancher#36671]
**Rancher Server Setup**
- Rancher version: Rancher version: v2.6-head commit: (635286172d41b24c074236060651af34c831b133)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.21.6+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 
      digital ocean, from rke2 template

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Standard User

   
**Describe the bug**

Using the rancher API (through the go automation framework) I create a token for a standard user, create a client using that token, and attempt to provision a node-driver rke2 cluster; I get this error `admission webhook "[rancherauth.cattle.io](http://rancherauth.cattle.io/)" denied the request: Unauthorized ` This also happens when I use the UI to create a token/api key, and then use said token in my test runs (in the go automation framework). But if I use the UI to login as the standard user and provision the cluster, it works fine with no issues. One more note if I instead use the username and password to create the client and then provision an rke2 cluster it works fine (using API in the go automation framework).

**To Reproduce**
 

- In code or using the go automation framework, instantiate a provisioning.cattle.io/v1 client using a bearer token created by a standard user.
- Using the provisioning.cattle.io API attempt to provision a cluster
- API calls
    1. /v3/tokens POST to create the bearer token. 
    2. /v3/cloudcredentials POST to create the cloud credential
    3. /v1/rke-machine-config.cattle.io.digitaloceanconfig/fleet-default POST for the machine config
    4. /v1/provisioning.cattle.io.clusters POST to provision the cluster.
- Also in the go automation framework run test `TestProvisioning` found in `rancher/rancher/tests/v2/validation/provisioning`
- Make sure config file is properly setup please look at https://confluence.suse.com/display/RANQA/Rancher+Automation+Framework+for+Testing
- With these entries for a digital ocean cluster
```
provisioningInput:
    kubernetesVersion:  ["v1.21.6+rke2r1"]
    cni: ["calico"]
    providers: ["do"]
digitalOceanCredentials:
     accessToken: "" //actually put in a token
doMachineConfig: //fill out appropriately
    image: ""
    backups: false
    ipv6: false
    monitoring: false
    privateNetworking: false
    region: ""
    size: ""
    sshKeyContents: ""
    sshKeyFingerprint: ""
    sshPort: ""
    sshUser: ""
    tags: ""
    userdata": ""
```

**Result**

**Expected Result**

That standard user is authorized to provision a cluster just like in the UI.

**Screenshots**

**Additional context**

This is done in code, but even creating the bearer token in the UI, and then using the token for the test runs causes the same issue.
