### ISSUE TITLE
Rke2-server does not start

### ISSUE THREAD

**Issue by caatclaudia** [rancher/rancher#36759]
### Rancher Server Setup
Rancher version: v.2.6.3

### Information about the Cluster
Installation option:
- Helm version: v3.8.0
- k3s version: v1.22.6+k3s1

Openstack:
- Microstack Installation - version ussuri, Revision 245

### Describe the bug
I want to integrate OpenStack Cloud Provider in the Rancher interface. To do that, I created a Cluster with “RKE2” and Custom options, since I used a machine already created. In "Cluster Options", I selected "External" in the Cloud Provider field and edit the YAML to introduce the following configuration:

```
cloud_provider:
 name: openstack
  openstackCloudProvider:
    global:
      username: admin
      password: XX
      auth-url: https://XX:5000/v3
      tenant-id:  XX
      domain-id: default
    load_balancer:
      subnet-id: XX
    block_storage:
      ignore-volume-az: true
    route:
      router-id: XX
bastion_host:
  port: '22'
  ssh_agent_auth: true
  user: <User of instance>
  ```
Then I clicked on "Create", selected "etcd", "Control Plane" and "Worker" options, copy and paste the command in machine and verified on "Provisioning Log" in the Cluster. 

### Result
In Rancher Interface, the "Provisioning Log" shows the message:
![image](https://user-images.githubusercontent.com/56655085/156741841-6a740c66-ca44-48ef-bb3a-c96dcb1f9348.png)

The rke2-server does not start. Status of this service:
![image](https://user-images.githubusercontent.com/56655085/156742211-1e869139-bf33-4dff-958b-fb620ed63264.png)

The logs of rke2-server:
![image](https://user-images.githubusercontent.com/56655085/156741969-649fdd45-bf6f-4fd0-91fc-8f3d99f3df24.png)

In machine, firewalls are not blocking any traffic, since I can "telnet" the ports.

### Expected Result
In Rancher Interface, the "State" of the Cluster should become "Active"

### To Reproduce
Create a Cluster with the configuration mentioned.
