### ISSUE TITLE
Sidekicks and Link Alias'

### ISSUE THREAD

**Issue by sjiveson** [rancher/rancher#3686]
I have an issue where I have service A, with a sidekick of service B and C. These services are automatically linked. However, I also need to use link alias' between B and C and this doesn't appear to be possible when they are both sidekicks of A.

I don't believe this is the issue discussed in: #2636 

Rancher Version: 0.56.1

Docker Version: 1.9.1

OS: Rancher OS

Steps to Reproduce: 

1. In a suitable docker-compose file add a sidekick label to service A, referencing services B and C. Also add links to service B and C with an alias.

2. Alternatively, add the link and alias to service B and C individually.

Results:

1. The relevant rancher-compose up command hangs when it attempts to launch service A and the stack is not created.

2. The stack is launched but no links exist.

Expected:

1. The stack is created and services B and C can ping each other using the alias as well as the 'standard' service names. Same for A (not that I care).

2. The stack is created and services B and C can ping each other using the alias as well as the 'standard' service names.

**Comment by deniseschannon** [comment]
Are actually using volumes from Service B and C or are you just trying to schedule them on the same hosts?

**Comment by mark-r-m** [comment]
Hi @deniseschannon 
I'm working with @itsthenetwork 

- A is our data-volume, which has volumes in the Dockerfile and in the docker-compose file, and has a sidekick label referencing B and C.
- B and C are tomcat servers running applications that need config to be persisted into A using volumes_from A.
- However, B and C need to be able to address each other as "a.mydomain.uk" and "b.mydomain.uk" so we can configure the security between each one

**Comment by mark-r-m** [comment]
```yaml
a-data-volume-service:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.sidekicks: tomcat-b-service,tomcat-c-service
  tty: true
  image: someserver:5000/data-volume:1.0.0
  volumes:
  - /data/condif/b
  - /data/config/c
  stdin_open: true
tomcat-b-service:
  ports:
  - 8081:8081
  links: 
  - tomcat-c-service:tomcat-c-service
  - tomcat-c-service:c.mydomain.com
  tty: true
  hostname: b.mydomain.com
  volumes_from:
  - a-data-volume-service
  image: someserver:5000/tomcat-b:1.0.0
  stdin_open: true
tomcat-c-service:
  ports:
  - 8082:8082
  links: 
  - tomcat-b-service:tomcat-b-service
  - tomcat-b-service:b.mydomain.com
  tty: true
  hostname: c.mydomain.com
  volumes_from:
  - a-data-volume-service
  image: someserver:5000/tomcat-c:1.0.0
  stdin_open: true 
```
