### ISSUE TITLE
Enabling HTTP Health Check on a Sidekick Service Prevents it from Starting

### ISSUE THREAD

**Issue by sjiveson** [rancher/rancher#3689]
Leading on from #3686 we seem to have stumbled across another sidekick related issue perhaps. If we enable HTTP health checking on a sidekick service (via compose or GUI/upgrade), it will not start. Manually performing a curl from the host or another container on that host (also a sidekick) using the health check URL and settings (before the check is applied) works as expected.

Rancher Version: 0.56.1

Docker Version: 1.9.1

OS: Rancher OS

Steps to Reproduce: In a suitable docker-compose file add a sidekick label to service A, referencing service B. Also apply a HTTP health check to service B.

Results: Service B will not start (service A will). 

Expected: Service B starts and is monitored.

**Comment by deniseschannon** [comment]
What do you mean by doesn't start? 

>Manually performing a curl from the host or another container on that host (also a sidekick) using the health check URL and settings (before the check is applied) works as expected.

Is it stuck in Initializing state? If you'll actually need to do the curl from another host and not the same host.

**Comment by sjiveson** [comment]
Hey Denise,

> What do you mean by doesn't start?

Using Rancher Compose at the CLI, the 'primary' service will start, the sidekick will not and the command 'hangs' - insofar as Ctrl+C is required to return to the prompt and no further execution is performed by it.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml?

**Comment by sjiveson** [comment]
Just waiting for it to arrive via the dev. Will update this once it has.

**Comment by deniseschannon** [comment]
Using v0.63.0, I am unable to reproduce. I used a simpler service with a sidekick that had health check enabled

```
sk:
  tty: true
  image: nginx
  stdin_open: true
primary:
  labels:
    io.rancher.sidekicks: sk
  tty: true
  image: nginx
  stdin_open: true
```

```
sk:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
primary:
  scale: 1
  metadata: *id001
```
