### ISSUE TITLE
bug:  Service alias pointing to service alias does not resolve in DNS

### ISSUE THREAD

**Issue by wundram** [rancher/rancher#3690]
Rancher Version:
0.59.1
Docker Version:
1.10.2
OS: 
centos
Steps to Reproduce: 
Create a stack (stack1) with an external service (extsrv) pointing to  an IP
Create a second stack (stack2) with a service alias (alias1) pointing to extsrv on stack1
Create a third stack (stack3) with a service alias (alias2) pointing to alias1 on stack2
Add an ubuntu container to stack3 and open a shell
Try to resolve the name with a command like "ping alias2"
Results: 
The service alias (alias2 in this example) cannot be resolved by name from a container in the stack containing this alias.
Expected:
You should be able to resolve alias2, and it should return the IP address in extsrv.

**Comment by tfiduccia** [comment]
This is reproducible.  Easy way to do this is to create the external service, both service alias' and the ubuntu service in one stack.  The first service alias resolves, the second service alias cannot be found.

**Comment by tfiduccia** [comment]
docker-compose.yml
```
alias2:
  image: rancher/dns-service
  links:
  - alias1:alias1
alias1:
  image: rancher/dns-service
  links:
  - externalService:externalService
externalService:
  image: rancher/external-service
ubuntu1:
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```

rancher-compose.yml
```
externalService:
  external_ips:
  - 1.2.3.4
```
