### ISSUE TITLE
provide helm values for location of privateCA

### ISSUE THREAD

**Issue by Torkolis** [rancher/rancher#36994]
**Is your feature request related to a problem? Please describe.**
I have set up a cert-manager with vault pki engine in my cluster (see https://learn.hashicorp.com/tutorials/vault/kubernetes-cert-manager). Now the vault stores a CA with which cert-manager can sign self generated certificates and store them in a kubernetes secret. These secrets contain 3 data blocks named exactly:
ca.crt:  ...
tls.crt:  ...
tls.key:  ...
and I have not found a way to change that.

The Problem is that while I can tell cert-manager to set the name for the secret which it generates to e.g. "tls-ca" so that the Helm deployment for rancher finds it, I can not name the ca portion of the secret "cacerts.pem" as requested in deployment.yaml of rancher
```yml 
       # Pass CA cert into rancher for private CA
        - mountPath: /etc/rancher/ssl/cacerts.pem
          name: tls-ca-volume
          subPath: cacerts.pem
          readOnly: true
```
so the workaround would be either creating the CA secret manually which would mean maintaining it manually, which I want to avoid, because that is what I have cert-manager for and with the current setup I would just need to replace the CA in vault and let cert-manager do the distribution to ingresses and everything else.
Or manually edit the rancher helm chart, which then would not allow "helm upgrade" anymore.

**Describe the solution you'd like**
Please add helm values for privateCA (and additionalTrustedCAs) in templates/deployment.yaml:
```yml
{{- if .Values.privateCA }}
        # Pass CA cert into rancher for private CA
        - mountPath: /etc/rancher/ssl/cacerts.pem
          name: tls-ca-volume
          subPath: cacerts.pem
          readOnly: true
{{- end }}
```
making it e.g.
```yml
{{- if .Values.privateCA }}
        # Pass CA cert into rancher for private CA
        - mountPath: /etc/rancher/ssl/cacerts.pem
          name: tls-ca-volume
          subPath: {{ .Values.privateCA.secret.dataBlockName }}
          readOnly: true
{{- end }}
```
and 
```yml
{{- if .Values.privateCA }}
      - name: tls-ca-volume
        secret:
          defaultMode: 0400
          secretName: tls-ca
{{- end }}
```
making it e.g.
```yml
{{- if .Values.privateCA }}
      - name: tls-ca-volume
        secret:
          defaultMode: 0400
          secretName:  {{ .Values.privateCA.secret.name }}
{{- end }}
```
