### ISSUE TITLE
Longhorn 100.1.2+up1.2.4 stuck uninstalling in RKE1 Windows cluster

### ISSUE THREAD

**Issue by PennyScissors** [rancher/rancher#37030]
**Rancher Server Setup**
- Rancher version: v2.6.4-rc11
- Installation option (Docker install/Helm Chart): n/a
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Windows

**Describe the bug**

**To Reproduce**
* Install longhorn`100.1.2+up1.2.4`
* Uninstall longhorn
* Check longhorn resources, specifically pods related to the longhorn-uninstall job

**Result**
The longhorn chart gets stuck uninstalling, seemingly due to resources being scheduled on windows nodes which may not be supported.
![image](https://user-images.githubusercontent.com/8951271/159970015-9a72d277-dbe4-4af2-b0d5-63e5d95d2bcf.png)

**Comment by PennyScissors** [comment]
Looks like installation is affected in RKE2 Windows as well. Seeing many longhorn pods (scheduled on Windows nodes) with problems after installation.
![image](https://user-images.githubusercontent.com/8951271/159975939-023d2320-4db3-413c-8ee6-be90b65240ab.png)

**Comment by innobead** [comment]
cc @PhanLe1010 we allow users to install in a hybrid cluster but users need to use node selector to  skip installing longhorn components on it.

https://longhorn.io/docs/1.2.4/advanced-resources/deploy/rancher_windows_cluster/

**Comment by PhanLe1010** [comment]
Yeah, please check if you have set the node selector and taint toleration as mentioned in the doc provided by @innobead

**Comment by PennyScissors** [comment]
This was a found in a test case from [this](https://github.com/rancher/dashboard/issues/5137) issue for allowing installation of charts in hybrid clusters without the need for setting tolerations/node-selectors manually. Sounds like this is not a regression, is just longhorn missing the right tolerations/node-selectors to account for the new behavior.

**Comment by innobead** [comment]
> This was a found in a test case from [this](https://github.com/rancher/dashboard/issues/5137) issue for allowing installation of charts in hybrid clusters without the need for setting tolerations/node-selectors manually. Sounds like this is not a regression, is just longhorn missing the right tolerations/node-selectors to account for the new behavior.

That means probably we should know what things we missed, then we can add to the next chart release.

**Comment by sirredbeard** [comment]
This should be re-tested following Team 3's additional annotations design, this should block from deploying on Windows nodes.

**Comment by ronhorton** [comment]
@nickwsuse @nwilliams22 when working this ticket, reach out to brandon depesa in team-rancher-qa-team3 re: provisioning windows clusters

**Comment by PennyScissors** [comment]
@MKlimuszka @ronhorton @sirredbeard This issue has not been fixed, the chart needs node-selectors, tolerations, and windows annotations to support hybrid clusters the same way we do in our other charts, instead of expecting the user to manually add them.

**Comment by brandonsuse** [comment]
@innobead I'm assigning this to you per @yasker

**Comment by innobead** [comment]
Let's fix this in the upcoming 1.3.1 and 1.2.5.
- Add `permit-os` as @PennyScissors mentioned
- Add the default toleration and node selector (@PennyScissors mentioned) for user-deployed components (Manager, Driver, UI), this part can be handled in the chart manifests
- Need to update the code to introduce this implicit default toleration and node selector at runtime

**Comment by innobead** [comment]
This has been improved in upcoming Longhorn 1.4.0, 1.3.1, and 1.2.5.

**Comment by prachidamle** [comment]
@innobead Since the Rancher chart for 1.3.1 has been released already - can this now be moved to-test for v2.6.9?

**Comment by innobead** [comment]
> @innobead Since the Rancher chart for 1.3.1 has been released already - can this now be moved to-test for v2.6.9? 

Yes, please.

**Comment by MSpencer87** [comment]
_Closing as verified_

This was tested on RKE2 mixed windows cluster using Longhorn v1.31

Steps for validation on RKE2 Windows Cluster
1. Deploy Longhorn Prerequesties into cluster
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-iscsi-installation
  labels:
    app: longhorn-iscsi-installation
  annotations:
    command: &cmd OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f 2); fi; if [[ "${OS}" == *"debian"* ]]; then sudo apt-get update -q -y && sudo apt-get install -q -y open-iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid && sudo modprobe iscsi_tcp; elif [[ "${OS}" == *"suse"* ]]; then sudo zypper --gpg-auto-import-keys -q refresh && sudo zypper --gpg-auto-import-keys -q install -y open-iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid && sudo modprobe iscsi_tcp; else sudo yum makecache -q -y && sudo yum --setopt=tsflags=noscripts install -q -y iscsi-initiator-utils && echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi && sudo systemctl -q enable iscsid && sudo systemctl start iscsid && sudo modprobe iscsi_tcp; fi && if [ $? -eq 0 ]; then echo "iscsi install successfully"; else echo "iscsi install failed error code $?"; fi
spec:
  selector:
    matchLabels:
      app: longhorn-iscsi-installation
  template:
    metadata:
      labels:
        app: longhorn-iscsi-installation
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: iscsi-installation
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - *cmd
        image: alpine:3.12
        securityContext:
          privileged: true
      containers:
      - name: sleep
        image: k8s.gcr.io/pause:3.1
  updateStrategy:
    type: RollingUpdate
____
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-nfs-installation
  labels:
    app: longhorn-nfs-installation
  annotations:
    command: &cmd OS=$(grep -E "^ID_LIKE=" /etc/os-release | cut -d '=' -f 2); if [[ -z "${OS}" ]]; then OS=$(grep -E "^ID=" /etc/os-release | cut -d '=' -f 2); fi; if [[ "${OS}" == *"debian"* ]]; then sudo apt-get update -q -y && sudo apt-get install -q -y nfs-common && sudo modprobe nfs; elif [[ "${OS}" == *"suse"* ]]; then sudo zypper --gpg-auto-import-keys -q refresh && sudo zypper --gpg-auto-import-keys -q install -y nfs-client && sudo modprobe nfs; else sudo yum makecache -q -y && sudo yum --setopt=tsflags=noscripts install -q -y nfs-utils && sudo modprobe nfs; fi && if [ $? -eq 0 ]; then echo "nfs install successfully"; else echo "nfs install failed error code $?"; fi
spec:
  selector:
    matchLabels:
      app: longhorn-nfs-installation
  template:
    metadata:
      labels:
        app: longhorn-nfs-installation
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: nfs-installation
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - *cmd
        image: alpine:3.12
        securityContext:
          privileged: true
      containers:
      - name: sleep
        image: k8s.gcr.io/pause:3.1
  updateStrategy:
    type: RollingUpdate
```
2. Install the Longorn v1.3.1 chart into the cluster, inside Edit YAML, edit the value for windowsCluster, enabled: true
```
global:
  cattle:
    systemDefaultRegistry: ""
    windowsCluster:
      # Enable this to allow Longhorn to run on the Rancher deployed Windows cluster
      enabled: true
```
3. Verify Longhorn UI is fucntional and properly displayed
4. Uninstall the Longhorn chart from the UI by navigating to Installed Apps, first removing the longhorn chart and then the longhorn-crd
5. The ui terminal is displayed for each chart, displaying the helm uninstall command and completes with success message
```
---------------------------------------------------------------------
SUCCESS: helm uninstall --namespace=longhorn-system longhorn
---------------------------------------------------------------------
```
