### ISSUE TITLE
Rancher Monitoring:  Create a custom role for access to monitoring resource when creating user in cluster

### ISSUE THREAD

**Issue by vtrenton** [rancher/rancher#37048]
**Is your feature request related to a problem? Please describe.**
Currently if I want to create a user in the UI with only access to Grafana I need to create a role and rolebinding manually as well as create a user with view access to all projects.

**Describe the solution you'd like**
A single click cluster role to grant a user permissions to the monitoring application

**Describe alternatives you've considered**
manually setting up the user with the RB and role - not in the UI.

**Additional context**

example manifests:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-view-rb
  namespace: cattle-monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-view-role #name of role created for rolebinding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-x698k #not rancher username
--
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-view-role
  namespace: cattle-monitoring-system
  uid: 56815885-2a3b-4e31-8a2a-f77ca662891e
rules:
- apiGroups:
  - ""
  resourceNames:
  - http:rancher-monitoring-grafana:80
  resources:
  - services/proxy
  verbs:
  - get
  - list
```
This is the menu this feature would make most sense in:

<img width="1301" alt="image (3)" src="https://user-images.githubusercontent.com/85969349/160182144-b8e8036c-e458-4d28-a99d-b36058fab9e2.png">
