### ISSUE TITLE
Generating a kubeconfig for downstream cluster fails when cluster-agent is disconnected, even when token hashing is disabled

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#37147]
**Is your feature request related to a problem? Please describe.**
When ACE is enabled for a downstream cluster, generating a kubeconfig for the cluster will fail when the cluster-agent is disconnected. This is due to a change for token hashing. However, generating a kubeconfig when the cluster-agent is disconnected will still fail if token hashing is not enabled.

**Describe the solution you'd like**
If token hashing is not enabled, then generating a kubeconfig for a cluster with ACE enabled should not fail.

**Additional context**
SURE-3334

**Comment by thedadams** [comment]
### Root cause
Rancher would try to create a ClusterAuthToken in the downstream cluster in the API layer. This would cause API to return a bad status code if the cluster was not active.

### What was fixed, or what changes have occurred
Now, when token hashing is disabled (which it is by default), the ClusterAuthToken is not created in the API layer. Instead, it is created by a controller later when the cluster is ready.

### Areas or cases that should be tested
1. Start Rancher with token hashing disabled (it is disabled by default)
2. Provision an RKE1 cluster from Rancher
3. While the cluster is provisioning, create a kubeconfig for the cluster. This will have to be done through the API.
4. The kubeconfig should be successfully generated.

1. Start Rancher and enable token hashing. This can be enabled after Rancher starts by editing the feature `kubectl edit feature token-hashing` or when starting Rancher by passing `--features token-hashing=true`
2. Provision an RKE1 cluster from Rancher.
3. Wait for the cluster to be active.
4. Download a kubeconfig for the cluster (this should be possible through the UI).

All contexts should be tested when the clusters are active in both cases.

### What areas could experience regressions?
Generating kubeconfigs for clusters when token hashing is enabled in the Rancher cluster.

### Are the repro steps accurate/minimal?
Yes.

**Comment by markusewalker** [comment]
Verified this has been addressed on `v2.6-head` https://github.com/rancher/rancher/commit/25381f9b0a1868e25ea6b0a33ac9e545257d2b80.

**ENVIRONMENT DETAILS**
- Rancher HA: Helm Install
- Rancher versions
     - Reproduced version: `v2.6.4`
     - Verified version: `v2.6-head-25381f9`
- Browser: Chrome

**TEST RESULT**
PASS

**REPRODUCTION STEPS**
1. Setup Rancher  `v2.6.4` and navigate to Rancher UI in a browser.
2. Created standard user and logged in to Rancher as that standard user.
3. Created an API token for the standard user.
4. Created a downstream RKE1 cluster within Rancher.
5. While the cluster was provisioning, performed the following workflow to generate the kubeconfig: 
     - Navigated to https://<Rancher Server>/v3/clusters, searched for `kubeconfig`. Clicked the `generateKubeconfig` link.
     - Navigated to a client machine and performed the following: `curl -s -X POST -H "Authorization: Bearer <user token>" https://<Rancher Server>/v3/clusters/c-<ClusterID>?action=generateKubeconfig | jq -r ".config"`. This was UNSUCCESSFUL:
```
# curl -s -X POST -H "Authorization: Bearer <userToken>" https://<RancherURL>/v3/clusters/c-izsn4?action=generateKubeconfig | jq -r ".config"
#
```
	
**VERIFICATION STEPS**
1. Setup Rancher  `v2.6-head-25381f9` and navigate to Rancher UI in a browser.
2. Created standard user and logged in to Rancher as that standard user.
3. Created an API token for the standard user.
4. Created a downstream RKE1 cluster within Rancher.
5. While the cluster was provisioning, performed the following workflow to generate the kubeconfig: 
     - Navigated to https://<Rancher Server>/v3/clusters, searched for `kubeconfig`. Clicked the `generateKubeconfig` link.
     - Navigated to a client machine and performed the following: `curl -s -X POST -H "Authorization: Bearer <user token>" https://<Rancher Server>/v3/clusters/c-<ClusterID>?action=generateKubeconfig | jq -r ".config"`. This was SUCCESSFUL:
```
# curl -s -X POST -H "Authorization: Bearer <userToken>" https://<RancherURL>/v3/clusters/c-kf4zm?action=generateKubeconfig | jq -r ".config"
apiVersion: v1
kind: Config
clusters:
- name: "rke1-test-one"
  cluster:
    server: "https://<RancherURL>/k8s/clusters/c-kf4zm"
- name: "rke1-test-one-test-one1"
  cluster:
    server: "https://:6443"
		
users:
- name: "rke1-test-one"
  user:
    token: "……"
		
		
contexts:
- name: "rke1-test-one"
  context:
    user: "rke1-test-one"
    cluster: "rke1-test-one"
- name: "rke1-test-one-test-one1"
  context:
    user: "rke1-test-one"
    cluster: "rke1-test-one-test-one1"
		
current-context: "rke1-test-one"
```
6. Imported the generated kubeconfig file and verified I could run command `kubectl config get-contexts`.
7. Navigated back to Rancher > Global Settings > Feature Flags and enable `token-hashing`.
8. Created a new downstream RKE1 cluster.
9. Downloaded the kubeconfig for the new cluster via the UI. Imported this new kubeconfig and verified I could run `kubectl config get-contexts`.
Downloaded the kubeconfig for all of the clusters via the UI. Imported this new kubeconfig and verified I could run `kubectl config get-contexts`.
