### ISSUE TITLE
Rancher assumes auto-created service account token secrets

### ISSUE THREAD

**Issue by liggitt** [rancher/rancher#37194]
**Describe the bug**

The following locations assume secret-based tokens will always be created for service accounts:

* https://github.com/rancher/rancher/blob/8858a2446c6286c17b424aaa9d2432638351c5d5/pkg/agent/cluster/cluster.go#L67
* https://github.com/rancher/rancher/blob/8858a2446c6286c17b424aaa9d2432638351c5d5/pkg/controllers/provisioningv2/rke2/common.go#L208
* https://github.com/rancher/rancher/blob/8858a2446c6286c17b424aaa9d2432638351c5d5/pkg/tunnelserver/peermanager.go#L83
* https://github.com/rancher/rancher/blob/8858a2446c6286c17b424aaa9d2432638351c5d5/pkg/controllers/dashboard/apiservice/apiservice.go#L144
* https://github.com/rancher/rancher/blob/8858a2446c6286c17b424aaa9d2432638351c5d5/pkg/api/norman/customization/monitor/handler_utils.go#L190

That assumption is not universally correct.

In 1.21+ secret-based tokens are no longer used for mounting into pods (ephemeral time-limited tokens are), and the token controller can be turned off.

In 1.24+, secret-based tokens are no longer auto-created by default for new service accounts.

**To Reproduce**

Run against a 1.24+ cluster, or a 1.21+ cluster with the token controller disabled.

**Result**

No auto-generated secret tokens exist, and these code locations return failure/errors.

Using ephemeral time-bound tokens is preferred in 1.21+ (see the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API) if possible.

If a secret-based token is still desired, one can be [created manually](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token), but will not be referenced from the service account's .secrets list (for reference, the `.secrets` field in a service account is documented to list secrets for mounting into pods running as the service account, not for other purposes, and may contain secrets that are not token secrets... there's no guarantee the first item in that list will be a token secret).

**Comment by easayliu** [comment]
Dear，i hava apply the yaml like
```
apiVersion: v1
kind: Secret
metadata:
  name: cattle
  namespace: cattle-system
  annotations:
    kubernetes.io/service-account.name: cattle-system/cattle
type: kubernetes.io/service-account-token
```
for this ,i got the problem.
i

**Comment by easayliu** [comment]
Fix this problem
```yaml
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: cattle
  namespace: cattle-system
secrets:
- name: cattle-token
```
cattle-token need create first

The another attention is cattle-impersonation-system. There is anothor sa,you should add secrets like cattle.
