### ISSUE TITLE
Wrong TCP load-balancing configuration (based on ports)

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#3722]
Rancher Version: 0.59.1

Steps to Reproduce: 

Using the following `docker-compose.yml` file:

``` yaml
lb:
  ports:
  - 8080:80
  - 8081:80
  labels:
    io.rancher.loadbalancer.target.hello1: 8080=80
    io.rancher.loadbalancer.target.hello2: 8081=80
  image: rancher/load-balancer-service
  links:
  - hello1
  - hello2

hello1:
  image: tutum/hello-world

hello2:
  image: tutum/hello-world
```

Do a curl request on port 8080:

``` sh
$ curl http://lb.<stack>.<env>.<domain>:8080
```

Results: 

The request falls on either of the hello1 and hello2 backends (the same happens with port 8081):

``` logs
hello1_1 | 2016-02-29T13:17:39.733814873Z 10.42.200.152 - - [29/Feb/2016:13:17:38 +0000] "GET / HTTP/1.1" 200 490 "-" "curl/7.38.0"
hello2_1 | 2016-02-29T13:17:43.546348713Z 10.42.200.152 - - [29/Feb/2016:13:17:42 +0000] "GET / HTTP/1.1" 200 490 "-" "curl/7.38.0"
```

Expected:

The requests on port 8080 should on end up on hello1, and the requests on port 8081 on hello2.

**Comment by raphink** [comment]
Here is the HAProxy configuration generated (backends and frontends sections only):

```
                                                                                
        default_backend 3cd3ef85-2722-4531-a111-e9a25bd91ed4_8081_1_backend     
                                                                                
backend 3cd3ef85-2722-4531-a111-e9a25bd91ed4_8081_1_backend                     
        mode http                                                               
        server 51cdbe91-c00e-4bb6-a087-ba5ff9c1f4bd 10.42.35.34:80              
        server 1c965f1b-b4c0-4aff-87b2-1b482e5cacaf 10.42.31.247:80             
                                                                                
frontend 3cd3ef85-2722-4531-a111-e9a25bd91ed4_8080_frontend                     
        bind 10.42.200.152:8080                                                 
        mode http                                                               
                                                                                
        default_backend 3cd3ef85-2722-4531-a111-e9a25bd91ed4_8080_0_backend     
                                                                                
backend 3cd3ef85-2722-4531-a111-e9a25bd91ed4_8080_0_backend                     
        mode http                                                               
        server 51cdbe91-c00e-4bb6-a087-ba5ff9c1f4bd 10.42.35.34:80              
        server 1c965f1b-b4c0-4aff-87b2-1b482e5cacaf 10.42.31.247:80   
```

**Comment by raphink** [comment]
Note: adding `/tcp` to port bindings doesn't change the behavior.

**Comment by deniseschannon** [comment]
Rancher doesn't support multiple frontends directing to specific services. By default, any source port will access any target port.

A workaround is to create a bogus hostname route to prevent any services using a specific port.

```
lb:
  ports:
  - 8080:80
  - 8081:80
  labels:
    io.rancher.loadbalancer.target.hello1: 8080=80
    io.rancher.loadbalancer.target.hello2: 8081=80
    #Bogus rule
    io.rancher.loadbalancer.target.hello1: bogus:8081=80
    io.rancher.loadbalancer.target.hello2: bogus:8080=80
  image: rancher/load-balancer-service
  links:
  - hello1
  - hello2

hello1:
  image: tutum/hello-world

hello2:
  image: tutum/hello-world
```

**Comment by raphink** [comment]
Thank you for the explanation. The routing specification seems precise enough to represent such constraints though. Where can I find the load balancer code to provide a patch for this?

**Comment by alena1108** [comment]
@raphink unfortunately we can't change the way existing hostname routing rules work as it would break backwards compatibility. But we have major LB refactoring in plans which will support the model you are interested in - when it would be possible to bind a particular backend to only one of the listening ports (https://github.com/rancher/rancher/issues/2179)

By then, workaround mentioned by Denise should be used.

**Comment by raphink** [comment]
Thanks. Any idea when the new version will be available?

**Comment by alena1108** [comment]
@raphink LB refactoring is something we consider doing immediately after GA

**Comment by raphink** [comment]
GA?

**Comment by vincent99** [comment]
The 1.0/**G**eneral **A**vailability release.

**Comment by raphink** [comment]
Ah OK, thanks. Is there a date for this milestone?

**Comment by deniseschannon** [comment]
GA is expected to be end of this month.

**Comment by sangeethah** [comment]
Tested with latest build from master:

Currently we have the a ability to set source port and target port for each defined port rules.

A sample rancher yml file  
```
version: '2'
services:
  test1:
    image: sangeetha/testnewhostrouting:latest
  test2:
    image: sangeetha/testnewhostrouting:latest
  LB-test:
    ports:
    - 7907:7907/tcp
    - 7908:7908/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:latest
```
```
version: '2'
services:
  test1:
    scale: 2
  test2:
    scale: 2
  LB-test:
    scale: 1
    lb_config:
      certs: []
      config: null
      default_cert: null
      port_rules:
      - backend_name: null
        hostname: www.abc1.com
        path: /service1.html
        priority: null
        protocol: http
        selector: null
        service: testenv/test1
        source_port: 7907
        target_port: 80
      - backend_name: null
        hostname: www.abc2.com
        path: /service3.html
        priority: null
        protocol: http
        selector: null
        service: testenv/test2
        source_port: 7908
        target_port: 81
      stickiness_policy:
        cookie: null
        domain: null
        indirect: false
        mode: insert
        name: null
        nocache: false
        postonly: false
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 2000
      healthy_threshold: 2
```
