### ISSUE TITLE
CoreDNS pod getting stuck into Terminating state after powering off the worker node.

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#37226]
**Rancher Server:**
- Version : v2.6-head(https://github.com/rancher/rancher/commit/635286172d41b24c074236060651af34c831b133)
- docker install

**Information about the Cluster**
- Kubernetes version: v1.19.16-rancher1-3
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom cluster on AWS (`3 etcd, 2 cp, 3 worker nodes`) 

**To Reproduce**
- Provision a k8s `v1.19.16-rancher1-3` custom cluster on AWS (3 etcd, 2 cp, 3 worker nodes) by adding below toleration values:
```
dns:
    provider: coredns
    tolerations:
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      toleration_seconds: 15
```
- Power off the worker node where coredns system pod was running.
- Coredns pod, running on the powered-off worker node will get scheduled on another available worker node(because of this [issue](https://github.com/rancher/rancher/issues/27734) fix). But the previous pod will get stuck into **Terminating** state

**Result**
- CoreDNS pod will get stuck into Terminating state :
![image](https://user-images.githubusercontent.com/36376154/162192297-f845af7a-e46d-4753-a1c5-69764bf6a029.png)

**Expected Result**
Previous pod should terminate once it is scheduled successfully on another available worker node.

**Additional context**
https://github.com/rancher/rancher/issues/27734
https://github.com/rancher/rancher/issues/27734#issuecomment-1090492894
