### ISSUE TITLE
Allow lasso resync time to be configured via env var

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37251]
This will come in advance of larger fix: https://github.com/rancher/rancher/issues/36785
Part of SURE-4048

**Comment by brandond** [comment]
For what it's worth, upstream intentionally adds a random skew to the resync intervals for each individual controller specifically to avoid this sort of thing. I'm not sure why our default would be a fixed interval, since that pretty much guarantees everything will all refresh at once.

**Comment by rmweir** [comment]
To test this, setup controllers as seen here https://github.com/rancher/rancher/wiki/How-to-setup-prometheus-dashboard-for-controllers. Then change value and ensure the difference is observed in the handler frequency graph. Spike interval should match the env var setting. The env var being set to "15" should look like this: 
![image](https://user-images.githubusercontent.com/19376037/162836985-266d14fd-4971-496f-8849-e358d9c0df62.png)

The env var being set to 0 should have almost no spikes. Some spikes may be there do to cronjob-like activity but there will be less handlers and the execution number will probably be smaller.

If spikes are difficult to observe then making many resources of a 1-3 types will help. Something like making 1000 secrets.

**Comment by brudnak** [comment]
# :x: FAILED / REOPENED 

## Validation Environment

| Component                 | Version / Type                                                                                                                                   |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Rancher version           | v2.5-cb699448e05d294fae461ec1bae039753b56bb9b-head [cb69944](https://github.com/rancher/rancher/commit/cb699448e05d294fae461ec1bae039753b56bb9b) |
| Installation option       | Helm high availability                                                                                                                           |
| RKE binary version used   | v1.2.19                                                                                                                                          |
| If Helm Chart k8s cluster | v1.20.15                                                                                                                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                                                                              |
| Docker version            | 20.10.7, build f0df350                                                                                                                           |
| Helm version              | v2.16.8-rancher1                                                                                                                                 |
| Downstream cluster type   | not applicable                                                                                                                                   |
| Downstream K8s version    | not applicable                                                                                                                                   |
| Logged in user role       | Administrator                                                                                                                                    |
| Browser type              | Google Chrome                                                                                                                                    |
| Browser version           | 100.0.4896.75 (Official Build) (x86_64)                                                                                                          |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$omitted \
  --set ingress.tls.source=secret \
  --version 2.5.13-rc1 \
  --set rancherImageTag=v2.5-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Run terraform to create 1000 secrets in the local cluster under a new project
2. Add `CATTLE_PROMETHEUS_METRICS` with value `true` to the rancher environment variable for the rancher deployment
3. Also add `CATTLE_RESYNC_DEFAULT` with a value of `5`
4. Install monitoring against the local cluster `System`
5. Create a service monitor similar to the following
   - Replaced `<this should match the rancher service's chart label's value>` with `rancher-2.5.13-rc1`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rancher
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
  jobLabel: rancher
  namespaceSelector:
    matchNames:
    - cattle-system
  selector:
    matchLabels:
      app: rancher
      chart: <this should match the rancher service's chart label's value>
      release: rancher
```

6. Go to prometheus and login. Default login credentials can be found here: https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/guides/customize-grafana/

7. Hover over the `+` in the sidebar and then select import

8. Copy and paste JSON from here: https://raw.githubusercontent.com/rancher/rancher2-scaling/master/control-plane/files/controllers-dashboard.json

9. Navigate to the Rancher Internal Controllers Dashboard. The graphs should start to populate. The top two may not populate right away.
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
I expect the Grafana dashboard to start to populate

#### :x: Actual
The Grafana dashboard is not populating

![2022-04-12_15-13-31](https://user-images.githubusercontent.com/40877149/163063653-da53d0cf-f1b0-499a-b80f-558b92ab2a79.png)

<hr>

**Comment by brandond** [comment]
Here is the behavior from upstream that we need to be copying:

https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/cmd/kube-controller-manager/app/controllermanager.go#L183-L191

Anything that sticks all the various controllers and informers on the same resync schedule is going to cause a problem eventually, regardless of how long or short it is.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Validation Environment

| Component                 | Version / Type                                                                                                                                   |
| ------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------ |
| Rancher version           | v2.5-cb699448e05d294fae461ec1bae039753b56bb9b-head [cb69944](https://github.com/rancher/rancher/commit/cb699448e05d294fae461ec1bae039753b56bb9b) |
| Installation option       | Helm high availability                                                                                                                           |
| RKE binary version used   | v1.2.19                                                                                                                                          |
| If Helm Chart k8s cluster | v1.20.15                                                                                                                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                                                                              |
| Docker version            | 20.10.7, build f0df350                                                                                                                           |
| Helm version              | v2.16.8-rancher1                                                                                                                                 |
| Downstream cluster type   | RKE1 Amazon EC2                                                                                                                                  |
| Downstream K8s version    | v1.20.15-rancher1-2                                                                                                                              |
| Logged in user role       | Administrator                                                                                                                                    |
| Browser type              | Google Chrome                                                                                                                                    |
| Browser version           | 100.0.4896.75 (Official Build) (x86_64)                                                                                                          |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$omitted \
  --set ingress.tls.source=secret \
  --version 2.5.13-rc1 \
  --set rancherImageTag=v2.5-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Run Terraform module to create 1000 secrets in the local cluster under a new project
2. Add `CATTLE_PROMETHEUS_METRICS` with value `true` to the rancher environment variable for the rancher deployment
3. Add `CATTLE_RESYNC_DEFAULT` with a value of `5`
4. Add `CATTLE_AGENT_IMAGE` with a value of `rancher/rancher-agent:v2.5-head`
5. Install monitoring against the local cluster `System`
6. Create a service monitor similar to the following
   - Replaced `<this should match the rancher service's chart label's value>` with `rancher-2.5.13-rc1`

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rancher
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
  jobLabel: rancher
  namespaceSelector:
    matchNames:
    - cattle-system
  selector:
    matchLabels:
      app: rancher
      chart: <this should match the rancher service's chart label's value>
      release: rancher
```

6. Go to prometheus and login. Default login credentials can be found here: https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/guides/customize-grafana/

7. Hover over the `+` in the sidebar and then select import

8. Copy and paste JSON from here: https://raw.githubusercontent.com/rancher/rancher2-scaling/master/control-plane/files/controllers-dashboard.json

9. Navigate to the Rancher Internal Controllers Dashboard. The graphs should start to populate. The top two may not populate right away.
  
## Additional Info

Variables tried with this test

- 5
- 0
- 10

## RESULTS

#### :white_check_mark: Expected
The Grafana dashboard to display the rancher internal state controllers dashboard, and be able to change the `CATTLE_RESYNC_DEFAULT` environment variable to different values

#### :white_check_mark: Actual
The Grafana dashboard to display the rancher internal state controllers dashboard, and be able to change the `CATTLE_RESYNC_DEFAULT` environment variable to different values

#### Screenshots

![2022-04-12_17-10-38](https://user-images.githubusercontent.com/40877149/163077496-b72d7acd-97ca-4de9-bf91-2291aff796eb.png)


<hr>
