### ISSUE TITLE
[Forwardport] v2.6: Allow lasso resync time to be configured via env var

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#37271]
**Original Issue:**
https://github.com/rancher/rancher/issues/37251

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                                |
| ------------------------- | --------------------------------------------------------------------------------------------- |
| Rancher version           | v2.6-6bb6e45fba97f58443e547e2f57d2807a424467f-head                                            |
| Rancher commit link       | [6bb6e45](https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f) |
| Installation option       | Helm high availability (in AWS)                                                               |
| RKE binary version used   | v1.3.8                                                                                        |
| If Helm Chart k8s cluster | v1.22.7                                                                                       |
| Cert Details              | ingress.tls.source=secret (certificates from files)                                           |
| Docker version            | 20.10.7, build f0df350                                                                        |
| Helm version              | v2.16.8-rancher1                                                                              |
| Downstream cluster type   | not applicable                                                                                |
| Downstream K8s version    | not applicable                                                                                |
| Logged in user role       | Administrator                                                                                 |
| Browser type              | Google Chrome                                                                                 |
| Browser version           | 100.0.4896.127 (Official Build) (x86_64)                                                      |

**ADDITIONAL SETUP**

- Helm install commands:

```shell
kubectl create namespace cattle-system
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$omitted \
  --set ingress.tls.source=secret \
  --set rancherImageTag=v2.6-head
```

```shell
kubectl -n cattle-system create secret tls tls-rancher-ingress \
  --cert=tls.crt \
  --key=tls.key
```

## Validation steps

1. Run Terraform module to create 1000 secrets in the local cluster under a new project
2. Add `CATTLE_PROMETHEUS_METRICS` with value `true` to the rancher environment variable for the rancher deployment
3. Add `CATTLE_RESYNC_DEFAULT` with a value of `5`
4. Add `CATTLE_AGENT_IMAGE` with a value of `rancher/rancher-agent:v2.6-head`
5. Install monitoring against the local cluster `System`
6. Create a service monitor similar to the following
   - Replaced `<this should match the rancher service's chart label's value>` with `rancher-2.6.4`
  
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rancher
    release: rancher
  name: rancher
  namespace: cattle-system
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
      serverName: rancher
  jobLabel: rancher
  namespaceSelector:
    matchNames:
    - cattle-system
  selector:
    matchLabels:
      app: rancher
      chart: <this should match the rancher service's chart label's value>
      release: rancher
```

6. Go to prometheus and login. Default login credentials can be found here: https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/guides/customize-grafana/

7. Hover over the `+` in the sidebar and then select import

8. Copy and paste JSON from here: https://raw.githubusercontent.com/rancher/rancher2-scaling/master/control-plane/files/controllers-dashboard.json

9. Navigate to the Rancher Internal Controllers Dashboard. The graphs should start to populate. The top two may not populate right away.
  
## Additional Info

Variables tried with this test

- 5
- 0
- 10

## RESULTS

#### :white_check_mark: Expected
The Grafana dashboard to display the rancher internal state controllers dashboard, and be able to change the `CATTLE_RESYNC_DEFAULT` environment variable to different values

#### :white_check_mark: Actual
The Grafana dashboard to display the rancher internal state controllers dashboard, and be able to change the `CATTLE_RESYNC_DEFAULT` environment variable to different values

#### Screenshots

![2022-04-20_23-05-09](https://user-images.githubusercontent.com/40877149/164385655-bc6ea7bd-e66e-4d83-a6fc-f97ba9332c43.png)

<hr>
