### ISSUE TITLE
OpenAPI Required Validation Broken, Possibly Others?

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#37310]
When using `norman` on 0.5.3 to specified a field is required, I see the schema and openapiv3schema gets generated, but it appears to be at the wrong level.

```
versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          attributes:
            properties:
              additional:
                additionalProperties:
                  type: string
                type: object
              platform:
                required:
                - platform
                type: string
              serial:
                required:
                - serial
                type: string
              version:
                type: string
            type: object
```

For example platform and serial are required, but I can create a resource without setting these fields and kubernetes allows it. 

```
versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          attributes:
            properties:
              additional:
                additionalProperties:
                  type: string
                type: object
              platform:
                type: string
              serial:
                type: string
              version:
                type: string
            type: object
            required:
              - platform
              - serial
```
