### ISSUE TITLE
Rancher release checklist needs to be automated for future milestones.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37386]
**Describe your Request**
The SUSE-Rancher engineering team strives to improve each time we release a milestone. As part of our new processes we are tracking issues in GitHub using a standard GitHub issue and a lot of associated issues that track the various steps required for the release process.

This request is for an **automated** way to create these tickets. Either through a script, or GitHub actions, etc.

**Describe the solution you'd like**
I would like some sort of automated solution like a bot - maybe a Release Checklist bot or an automation script or something.

**Describe alternatives you've considered**
I would consider anything that makes it easier to create these issues.

SURE-4496

**Comment by Jono-SUSE-Rancher** [comment]
@paynejacob can you maybe add some details or comments to this ticket on your thoughts? I added an internal JIRA reference if you want to put it there instead. I'll try to get it assigned for an upcoming milestone.

**Comment by paynejacob** [comment]
My thoughts for this are we have a repository with a configuration file with templates for all the release issues.  We could have a ci  process where when you tag a release it creates those github issues on the rancher/rancher repository. The repo could have different branches for the different release types, e.g. minor release, patch release, 2.6-patch.  Release could then fork off these branches and update the assigned captains and then tag the release.  CI would publish the issues to rancher/rancher and assign the appropriate captains.  By using source control for the issues templates we can also keep instructions and tasks lists up to date easier.

All issues created will have a common label to make cleanup easier and the issue titles will be prefixed with the tag version.

example configuration file:

team-2/tasks.yaml
```yaml
team2-first-mate: @paynejacob,@jakeofhyde

issues:
  - title: Release EKS Operator
     description: |
          Goto this repo and run these commands...
  - title: Release AKS Operator
    description: |
      Goto that repo and run those commands....
```
