### ISSUE TITLE
rancher cli login command SSL error

### ISSUE THREAD

**Issue by X-rapido** [rancher/rancher#37413]
**Rancher Server Setup**
- Rancher version: 2.3.3 (Companies use)

** My kubectl version **
```
➜  kubectl version --client --output=yaml

clientVersion:
  buildDate: "2022-03-16T15:58:47Z"
  compiler: gc
  gitCommit: c285e781331a3785a7f436042c65c5641ce8a9e9
  gitTreeState: clean
  gitVersion: v1.23.5
  goVersion: go1.17.8
  major: "1"
  minor: "23"
  platform: darwin/amd64
```

   
**issue**

![image](https://user-images.githubusercontent.com/9986850/164218647-9b3424a5-90ed-4ec1-844c-1eab46218387.png)

`rancher login http://rancher.co-xxxx.com --token xxx: xxx`  400 problems occur，How can I solve this problem？

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**
