### ISSUE TITLE
Support Needed for shipping rke2 kube audit logs using cluster flow by using rancher logging 100.0.1+up3.15.0

### ISSUE THREAD

**Issue by sureshgoli25** [rancher/rancher#37423]
Hi,

I need your support to create cluster flow for shipping RKE2 audit log files and understanding of `rancher-logging-kube-audit ` logging resource. I couldnt find definiative example in rancher docs for shipping audit logs.

After installation of rancher logging chart, we have observed there is another logging resource `rancher-logging-kube-audit ` got created. Which created another set of fluentbit daemonset + fluentd for handling audit cluster flows and outputs.

Our understanding is whenever we are creating the clusterflow for namespaces both `rancher-logging-kube-audit`  and `rancher-logging` related fluentd are getting updated. But, how can we create only clusterflow in such a way it only handls the kube audit logs.

Below cluster flow, i am using for testing. Kindly let me know your suggestion/approach for creating the kube audit clusterflow.

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: rke2-clusterflow
spec:
  globalOutputRefs:
    - rke2-clusteroutput
  match:
    - select: {}
```

Our environment details are:
Rancher: 2.6.3
Rancher Logging Chart: 100.0.1+up3.15.0
RKE2: V1.21.7
