### ISSUE TITLE
[Neuvector] Unable to access neuvector UI when neuvector is installed via terraform

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37434]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head 3990208
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.8, 1.3.10-rc3

**Information about the Cluster**
- Kubernetes version: v1.22.8
- Cluster Type (Local/Downstream): `Downstream node driver 3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Neuvector UI isn't accessible as an admin, when the app is installed using terraform scripts.

**To Reproduce**
1. Create a downstream cluster with the above mentioned spec
2. Install nuevector app version `100.0.0+up2.2.0-b1` using terraform scripts by providing the namespace `cattle-neuvector-system` and cluster id.
3. As admin launch the nuevector UI once the app is installed.

**Result**
Not able to get into neuvector as the launch fails with `Authentication failed!`

**Expected Result**
Able to launch neuvector UI and access the UI as admin

**Screenshots**
<img width="398" alt="tf" src="https://user-images.githubusercontent.com/38144301/164564825-56aafb2b-33b8-4926-aff7-889deef59525.png">

**Additional context**
Rancher endpoint url   value is missing and is not set when the app is deployed via terraform.  
Should be set to Rancher URL

`helm get values neuvector -n cattle-neuvector-system` from the cluster with neuvector created via terraform
```
USER-SUPPLIED VALUES:
global:
  cattle:
    clusterId: c-vwxmt
    clusterName: tf
    systemDefaultRegistry: ""
  systemDefaultRegistry: ""
```
`helm get values neuvector -n cattle-neuvector-system` from the cluster with neuvector created from rancher UI

```
USER-SUPPLIED VALUES:
docker:
  enabled: true
global:
  cattle:
    clusterId: c-7457l
    clusterName: user-nv-w
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    url: https<redacted>
  systemDefaultRegistry: "
```
