### ISSUE TITLE
Load Balancer - 503 Service Unavailable error

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#3744]
I have 2 services running via different stacks (wordpress on port 8080 and myapp on port 8030).

I have added a load balancer inside a separate stack. This works with wordpress, but the other service keeps give in me a 503 Service Unavailable error.  I still have the same error if I remove wordpress from the LB and keep only the other service.

My LB is configured to map ports 80/80, and various hostnames to each service, using default ports, e.g
wp.mysite.com -> wordpress
my.app.com -> myapp

Changing the config to use each service's actual target port doesn't work either, even for wordpress:.
wp.mysite.com -> wordpress [8080]
my.app.com -> myapp [8030]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by opichon** [comment]
The documentation is confusing.

Should I map the myapp service (running in its container on port 8030) to port 8030 in "targetts" config?
Do I need to add pot 8030 to the lb "ports" config?

In addition, trying to add various ports in the "targets" configuration results in an API error "invalid port".

**Comment by opichon** [comment]
The doc say"s: The target port is the private port that traffic will be directed to the services." This is not even proper english. What does it mean?

**Comment by opichon** [comment]
The docs uses as an example (if I understand it correctly) an attempt to map the host name on port 8090 to the container port 80. I don't understand the point of this. in probably 99% of the cases, it is port 80 on  host a custom hostname needs to be mapped to a container port of 8090.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml? If you have 2 services and want specific ports to be directed to specific services you are most likely hitting this common confusion. I will try and update the docs to reflect this. 

https://github.com/rancher/rancher/issues/2475

**Comment by opichon** [comment]
Here is the wordpress docker-compose.yml:

```yaml
wordpress:
  ports:
  - 8080:80/tcp
  environment:
    WORDPRESS_DB_HOST: database:3306
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_PASSWORD: my-secret-pw
    WORDPRESS_DB_USER: wordpress
  labels:
    io.rancher.service.hash: c8470a3d1431c78fea99679fe399dee026c15334
  tty: true
  image: wordpress
  links:
  - database:database
  stdin_open: true
database:
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_PASSWORD: my-secret-pw
    MYSQL_ROOT_PASSWORD: my-secret-pw
    MYSQL_USER: wordpress
  labels:
    io.rancher.service.hash: f05507ee5c38c055725fa11846fba78678a08695
  tty: true
  image: mysql
  stdin_open: true
```

and for the other service:
```
app:
  ports:
  - 8030:80/tcp
  image: my.registry.com:5000/frimus/bolt:latest
  links:
  - 'db:'
db:
  environment:
    MYSQL_DATABASE: 
    MYSQL_PASSWORD: XXXXXX
    MYSQL_ROOT_PASSWORD: XXXXXXXXXXXX
    MYSQL_USER: XXXXXX
  labels:
    io.rancher.service.hash: a81c486c99177854e2f2b0bfa9077b14ebb925fc
  image: unitedasian/mysql:5.7
phpmyadmin:
  ports:
  - 8031:80/tcp
  environment:
    PMA_ABSOLUTE_URI: http://pma.myapp.fr
    PMA_HOST: dbmyapp
    VIRTUAL_HOST: pma..fr
  labels:
    io.rancher.service.hash: 7a827b1fa0be79140dd55fb312a9f85c3e48f27c
  image: phpmyadmin/phpmyadmin:latest
  links:
  - db:db
```

**Comment by deniseschannon** [comment]
What about the load balancer? That is the key component. :)

**Comment by opichon** [comment]
Here is the lb config:

```
lb:
  ports:
  - 80:80
  external_links:
  - wordpress/wordpress:wordpress
  - frimus/phpmyadmin:phpmyadmin
  - frimus/app:app
  labels:
    io.rancher.loadbalancer.target.wordpress/wordpress: wp.united-asian.com
    io.rancher.loadbalancer.target.frimus/phpmyadmin: pma.friandisesmusicales.fr
    io.rancher.loadbalancer.target.frimus/app: www.friandisesmusicales.fr
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```
