### ISSUE TITLE
Helm App upgrade ignores change in values.yaml

### ISSUE THREAD

**Issue by michalbehun** [rancher/rancher#37516]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): Helm, RKE1
- Proxy/Cert Details: Let's Encrypt

**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type (Local/Downstream): Custom

**User Information**
- What is the role of the user logged in: Admin
   
**Describe the bug**
When updating (even installing) polyaxon app deployed from Apps & Marketplace, definition of parameter `artifactsStore:` in values.yaml is ignored. After update is completed change has not been applied and modification in values.yaml is lost.
I have checked generated values.yaml in secret for helm operation, there is `artifactsStore: null` generated instead. 

**To Reproduce**

1. update app from Apps & Marketplace
2. change values.yaml
3. changed values are ignored
4. no change is applied and disappear from values.yaml

**Result**
Required app settings cannot be modified.

**Expected Result**
Changes in values.yaml are applied.

**Additional context**
There are listed only changes made in values.yaml, although whole values.yaml was provided when upgrading app.
```  
...
artifactsStore:
  name: artifacts-pvc
  kind: volume_claim
  schema:
    mountPath: /plx-data
    volumeClaim: artifacts-store
...
connections:
  - kind: registry
    name: docker_connection
    schema:
      url: registry.domain
    secret:
      mountPath: /kaniko/.docker
      name: kaniko-conf
...
ingress:
  enabled: true
  hostName: polyaxon.domain
...
intervals:
  compatibilityCheck: '-1'
...
postgresql:
  persistence:
    enabled: true
    size: 5Gi
...
securityContext:
  enabled: true
...
ui:
  adminEnabled: true
  enabled: true
...
```

Generated values-polyaxon-1.12.3.yaml in secret for helm operation. The first item is being set with null:
```
{"artifactsStore":null,"connections":[{"kind":"registry","name":"docker_connection","schema":{"url":"registry.domain"},"secret":{"mountPath":"/kaniko/.docker","name":"kaniko-conf"}}],"global":{"cattle":{"clusterId":"c-xxxxx","clusterName":"eu1","rkePathPrefix":"","rkeWindowsPathPrefix":"","systemDefaultRegistry":"","url":"https://rancher.domain"},"systemDefaultRegistry":""},"ingress":{"enabled":true,"hostName":"polyaxon.domain"},"intervals":{"compatibilityCheck":"-1"},"postgresql":{"persistence":{"enabled":true,"size":"5Gi"}},"securityContext":{"enabled":true},"ui":{"adminEnabled":true,"enabled":true}}
```

I came up with workaround to edit generated secret and rerun pod for helm operation, but I'm not sure if it is possible.
