### ISSUE TITLE
Monitoring installation does not complete because PVC is stuck pending

### ISSUE THREAD

**Issue by trexmaster** [rancher/rancher#37643]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart, RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.21.9 & 1.21.12
- Cluster Type (Local/Downstream): Downstream, Custom

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Exact same bug as in [https://github.com/rancher/rancher/issues/29634](https://github.com/rancher/rancher/issues/29634)

**To Reproduce**

- Install monitoring from cluster tools
- Configure persistent storage for Prometheus using a storage class

**Result**

- PVC stays in pending status and never reaches bound which blocks deployment

**Expected Result**

- PVC reaches bound status and deployment completes

**Additional context**
This is related to [this issue](https://github.com/helm/charts/issues/11707) where I found the solution, i.e. to remove the entire selector block from prometheus' storageSpec. Original storageSpec looks like this :

```yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
          selector:
            matchExpressions: null
            matchLabels: {}
          storageClassName: ceph-rbd-sc
          volumeMode: Filesystem
```

Working one looks like this :

```yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
          storageClassName: ceph-rbd-sc
          volumeMode: Filesystem
```
