### ISSUE TITLE
[2.6] Support for multiple private registries is broken

### ISSUE THREAD

**Issue by zerotens** [rancher/rancher#37658]
**Rancher Server Setup**
- Rancher version: 2.6.4
   
**Describe the bug**

RKE supports multiple private registries:
https://rancher.com/docs/rke/latest/en/config-options/private-registries/

1. Create or edit a cluster/rke cluster template and directly modify the RKE yaml.
2. Click Edit Yaml button and create multiple registry entries like so

```
  private_registries:
    - ecr_credential_plugin: {}
      is_default: true
      url: my-private-registry
      user: tobias
      password: secure
    - ecr_credential_plugin: {}
      is_default: false
      url: my-private-registry-2
      user: frank
      password: securepw2
```
3. Try to submit it and you will be greeted with an error "resourceVersion should not be set on objects to be created"

Relevant broken function:
https://github.com/rancher/rancher/blob/dfe44512d12d5674607be1848e53ce83f5b67e6c/pkg/controllers/management/secretmigrator/clusters.go#L661

Should be assigned to @cmurphy as she wrote the secret migrator code.
