### ISSUE TITLE
RKE support for IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by hchen-tubi** [rancher/rancher#37664]
**Is your feature request related to a problem? Please describe.**

I'm trying to implement IRSA for a custom RKE provisioned cluster in rancher following this document:
https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md

One necessary [step](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#kubernetes-api-server-configuration) in the document is to enable Service Account Token Volume Projection In order to integrate API service with the OIDC provider. 

I added these settings in the Rancher Cluster Options YAML config as below:
```
    extra_args:
        service-account-key-file: /etc/kubernetes/ssl/oidc-issuer.pub
        service-account-signing-key-file: /etc/kubernetes/ssl/oidc-issuer.key
        api-audiences: sts.amazonaws.com
        service-account-issuer: https://s3-us-east-2.amazonaws.com/xxxxxxxxxxx
```
![image](https://user-images.githubusercontent.com/94601339/167654688-62510c40-3799-47a2-8e44-521b69c1461f.png)

But after I saved the changes above and the cluster got updated by rancher, rancher UI got below error:

`
cluster health check failed: Failed to communicate with API server during namespace check: Unauthorized
`

And when I use `kubectl`  to connect to the cluster it also got errors:
`
error: You must be logged in to the server (Unauthorized)
`

I think it is because Rancher communicates with Kubernetes clusters using a service account and it also depends on the Service Account Token Volume Projection feature, and the error happened after I overwrite the default RKE provisioned API server parameters:
```
k8s-controleplane:~$ ps aux |grep kube-api
kube-apiserver --service-account-issuer=rke --service-account-key-file=/etc/kubernetes/ssl/kube-service-account-token-key.pem --service-account-signing-key-file=/etc/kubernetes/ssl/kube-service-account-token-key.pem ......
```

**Describe the solution you'd like**

1. For Rancher RKE provisioned custom clusters, it should allow user to set `--service-account-issuer`, `service-account-key-file`, and `service-account-issuer` with no errors to support IAM Roles for Service Accounts.
2. Support cluster build-in OpenID discovery endpoint: https://github.com/kubernetes/enhancements/issues/1393

**Describe alternatives you've considered**
Other type of clusters managed by Rancher can support IRSA. (Imported/Hosted EKS?)

**Additional context**

*Environment*
- Rancher server: v2.6.4
- Kubernetes version: 1.22.9
- Logging user: Admin
