### ISSUE TITLE
System tools does not remove Rancher

### ISSUE THREAD

**Issue by time4116** [rancher/rancher#37709]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Helm Chart:
   - rancher-stable/rancher  2.6.4
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.9 (v1.21.9-eks-14c7a48)
- Cluster Type (Local/Downstream):
   - local
* Hosted = EKS
 * Infrastructure Provider = AWS

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
Unable to remove Rancher from the EKS cluster using system-tools. Namespaces are stuck in a terminating state and have been for 21+ hours.
```
kubectl get namespace
NAME                                                        STATUS        AGE
cattle-fleet-clusters-system                      Active           22h
cattle-fleet-local-system                           Active           22h
cattle-fleet-system                                    Active           22h
cattle-global-data                                     Active           22h
cattle-global-nt                                         Active           22h
cattle-impersonation-system                    Active            22h
cattle-system                                            Terminating   23h
cluster-fleet-local-local-1a3d67d0a899   Terminating    22h
default                                                       Active            23h
fleet-default                                              Active            22h
fleet-local                                                  Active            22h
ingress-nginx                                            Active            23h
kube-node-lease                                      Active            23h
kube-public                                              Active            23h
kube-system                                            Active             23h
local                                                         Terminating    22h
p-98fcq                                                    Terminating    22h
p-9wcml                                                   Terminating    22h
```

**To Reproduce**
Follow the [AWS quickstart](https://aws-quickstart.github.io/quickstart-eks-rancher/) guide provided in the Rancher documentation [here](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/amazon-eks/#automated-quickstart-using-aws-best-practices), use the following Cloudformation template [Deploy Rancher into a new VPC and new Amazon EKS cluster](https://fwd.aws/w684k), once Rancher setup is finished attempt to run [system-tools](https://github.com/rancher/system-tools/releases/tag/v0.1.1-rc7) remove.

**Result**
Namespaces are stuck in a terminating state.

**Expected Result**
All resources and namespaces pertaining to rancher are deleted.

**Additional context**
The Cloudformation template is an easy way to reproduce the issue. My initial use case was to run rancher in an existing EKS cluster. The first deployment yielded no issues. However, trying to remove rancher resources from the cluster is a bit tricky. I was able to avoid rancher syncing/cleanup issues by creating and executing the below script. I've experienced issues where not deleting left over resources in the Rancher CRD's can cause a new deployment of rancher to have syncing issues and in some cases actually remove the nodes from the cluster. I have also been able to reproduce this issue on minikube.

Rancher webhook needed to remove some specific resources
```
---
# Create this or it wont' work
apiVersion: v1
kind: Secret
metadata:
  name: rancher-webhook-tls
  namespace: cattle-system
type: Opaque
---
# Source: rancher-webhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-webhook
  namespace: cattle-system
---
# Source: rancher-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rancher-webhook
  namespace: cattle-system
---
# Source: rancher-webhook/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: rancher-webhook
  namespace: cattle-system
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  selector:
    app: rancher-webhook
---
# Source: rancher-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-webhook
  namespace: cattle-system
spec:
  selector:
    matchLabels:
      app: rancher-webhook
  template:
    metadata:
      labels:
        app: rancher-webhook
    spec:
      volumes:
      - name: tls
        secret:
          secretName: rancher-webhook-tls
      containers:
      - env:
        - name: STAMP
          value: ""
        - name: ENABLE_CAPI
          value: "true"
        - name: ENABLE_MCM
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: 'rancher/rancher-webhook:v0.2.5'
        name: rancher-webhook
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: https
          containerPort: 9443
        - name: capi-https
          containerPort: 8777
        volumeMounts:
        - name: tls
          mountPath: /tmp/k8s-webhook-server/serving-certs
      serviceAccountName: rancher-webhook
---
# Source: rancher-webhook/templates/webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: rancher.cattle.io
  sideEffects: None
  timeoutSeconds: 10
---
# Source: rancher-webhook/templates/pre-delete-hook-psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: rancher-webhook-pre-delete
  labels: 
    app: rancher-webhook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  privileged: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  volumes:
    - 'secret'
---
# Source: rancher-webhook/templates/pre-delete-hook-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-webhook-pre-delete
  namespace: cattle-system
  labels: 
    app: rancher-webhook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
---
# Source: rancher-webhook/templates/pre-delete-hook-cluster-role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rancher-webhook-pre-delete
  labels: 
    app: rancher-webhook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "delete" ]
    resourceNames: [ "rancher.cattle.io" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get" ]
  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
    resourceNames: [ "rancher-webhook-pre-delete" ]
---
# Source: rancher-webhook/templates/pre-delete-hook-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-webhook-pre-delete
  labels: 
    app: rancher-webhook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-webhook-pre-delete
subjects:
  - kind: ServiceAccount
    name: rancher-webhook-pre-delete
    namespace: cattle-system
---
# Source: rancher-webhook/templates/pre-delete-hook-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: rancher-webhook-pre-delete
  namespace: cattle-system
  labels: 
    app: rancher-webhook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      name: rancher-webhook-pre-delete
      labels: 
        app: rancher-webhook
    spec:
      serviceAccountName: rancher-webhook-pre-delete
      restartPolicy: OnFailure
      containers:
        - name: rancher-webhook-pre-delete
          image: "rancher/kubectl:v1.20.2"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command: [ "kubectl", "delete", "--ignore-not-found=true", "mutatingwebhookconfigurations", "rancher.cattle.io" ]

```
Cleanup
```
#!/bin/bash

timestamp=$(date "+%Y.%m.%d-%H.%M.%S")
backupPath="/tmp/rancher/$timestamp"

mkdir -p $backupPath

# Replace path with location of "rancher-webhook.yaml" included in the issue
cp path-to-included-rancher-webhook-yaml $backupPath/rancher-webhook.yaml

# Backup webhooks
mkdir $backupPath/MutatingWebhookConfiguration
kubectl get MutatingWebhookConfiguration rancher.cattle.io -o yaml > $backupPath/MutatingWebhookConfiguration/rancher.cattle.io.yaml
kubectl get MutatingWebhookConfiguration mutating-webhook-configuration -o yaml > $backupPath/MutatingWebhookConfiguration/mutating-webhook-configuration.yaml

# Delete webhooks
kubectl delete MutatingWebhookConfiguration rancher.cattle.io
kubectl delete MutatingWebhookConfiguration mutating-webhook-configuration

# Get CRD's that have resources
declare -a resources=()
declare -a crds=($(kubectl get customresourcedefinitions |grep cattle.io |awk '{print $1}'))
for crd in "${crds[@]}"
do
    echo "Working on CRD: $crd"
    result=$(kubectl get $crd -A 2>/dev/null)
    if [[ ! -z "$result" ]]; then
        echo -e "\tFound stuff!"
        resources+=("$crd")
    fi
done

# Remove controller.cattle.io/namespace-auth from cattle-system
kubectl get ns cattle-system| awk '{print $1}'| xargs kubectl patch namespace -p '{"metadata":{"finalizers":[]}}' --type='merge'

echo "Creating rancher-webhook so that we can pass validation on some of the finalizers"
kubectl apply -f $backupPath/rancher-webhook.yaml

while ! [ "$(kubectl -n cattle-system get pods -l app=rancher-webhook|grep "Running")" ]; do
    printf "Waiting for rancher-webhook pods to spin up\n" && sleep 5
done

echo "Waiting for webhook \"rancherauth.cattle.io\"..."
# If you see: 'Error from server (InternalError): Internal error occurred: failed calling webhook \"rancherauth.cattle.io\"' then the webhook isn't ready and you will need to execute this script again.
sleep 35

# Delete resources that are found within rancher CRD's
mkdir $backupPath/Resources
for crd in "${resources[@]}"
do
    result=$(kubectl get $crd -A)
    echo "Working on $crd"
    mkdir $backupPath/Resources/$crd
    if [[ "$result" == *"NAMESPACE"* ]]; then
        echo "$result"| tail -n +2 | awk '{print $2 " " $1}' | xargs -L1 bash -c "kubectl get $crd \$0 -n \$1 -o yaml > $backupPath/Resources/$crd/\$0.yaml"
        echo "$result"| tail -n +2 | awk '{print $2 " " $1}' | xargs -L1 bash -c "kubectl patch $crd \$0 -n \$1 -p '{\"metadata\":{\"finalizers\":[]}}' --type='merge'"
        echo "$result"| tail -n +2 | awk '{print $2 " " $1}' | xargs -L1 bash -c "kubectl delete $crd \$0 -n \$1"
        echo ""
    elif [[ "$result" == *"NAME"* ]]; then
        echo "$result"| tail -n +2 | awk '{print $1}' | xargs -L1 bash -c "kubectl get $crd \$0 -o yaml > $backupPath/Resources/$crd/\$0.yaml"
        echo "$result"| tail -n +2 | awk '{print $1}' | xargs -L1 bash -c "kubectl patch $crd \$0 -p '{\"metadata\":{\"finalizers\":[]}}' --type='merge'"
        echo "$result"| tail -n +2 | awk '{print $1}' | xargs -L1 bash -c "kubectl delete $crd \$0"
        echo ""
    else
        echo "$result"| awk '{print $1}' | xargs -L1 bash -c "kubectl get $crd \$0 -o yaml > $backupPath/Resources/$crd/\$0.yaml"
        echo "$result"| awk '{print $1}' | xargs -L1 bash -c "kubectl patch $crd \$0 -p '{\"metadata\":{\"finalizers\":[]}}' --type='merge'"
        echo "$result"| awk '{print $1}' | xargs -L1 bash -c "kubectl delete $crd \$0"
        echo ""
    fi
done

# Remove rancher webhook
kubectl delete -f $backupPath/rancher-webhook.yaml
kubectl delete MutatingWebhookConfiguration rancher.cattle.io

# Delete rancher state namespaces
kubectl get ns| grep cattle | awk '{print $1" -n "$1}' |xargs kubectl patch namespace -p '{"metadata":{"finalizers":[]}}' --type='merge'
kubectl get ns| grep cattle | awk '{print $1}' | xargs kubectl delete namespace

kubectl get ns| grep fleet | awk '{print $1" -n "$1}' |xargs kubectl patch namespace -p '{"metadata":{"finalizers":[]}}' --type='merge'
kubectl get ns| grep fleet | awk '{print $1}' | xargs kubectl delete namespace

kubectl get ns| grep p- | awk '{print $1" -n "$1}' |xargs kubectl patch namespace -p '{"metadata":{"finalizers":[]}}' --type='merge'
kubectl get ns| grep p- | awk '{print $1}' | xargs kubectl delete namespace

kubectl get ns| grep local | awk '{print $1}' |xargs kubectl patch namespace -p '{"metadata":{"finalizers":[]}}' --type='merge'
kubectl get ns |grep local | awk '{print $1}' | xargs kubectl delete namespace 

# Delete rancher CRDs
kubectl get customresourcedefinitions |grep cattle.io |awk '{print $1}' |xargs kubectl patch -p '{"metadata":{"finalizers":[]}}' --type=merge crd
kubectl get customresourcedefinitions |grep cattle.io |awk '{print $1}' |xargs kubectl delete customresourcedefinitions
```
