### ISSUE TITLE
Trying to use AWS LB Controller w Rancher - fails on 63 chars limit

### ISSUE THREAD

**Issue by funes79** [rancher/rancher#37766]
**Rancher Server Setup**
- Rancher version: latest
- Installation option (Docker install/Helm Chart): Helm + EKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.22
- Cluster Type (Local/Downstream):  Local

**User Information**
- Admin 

  
**Describe the bug**

I have sucesfully installed Rancher in EKS and tested it accoring the official documentation with nginx-ingress controller.
```
helm install rancher rancher-latest/rancher \
   --namespace cattle-system \
   --set hostname=alb.dev.my.domain.net \
   --set bootstrapPassword=<pwd>
```
I wanted to setup a ALB controller (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/) and use that instead to expose rancher. I successfully installed the AWS ALB controller and created this Ingress to expose the Rancher Web UI

Ingress defintion:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb
  namespace: cattle-system
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: common-alb
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: alb.dev.my.domain.net
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: rancher
                port:
                  number: 443
```

but after creating an Ingress object the rancher pod reports this error:

```
2022/05/18 13:56:26 [INFO] Creating new TLS secret for serving-cert (count: 5): map[listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.2.129.207:172.2.129.207 listener.cattle.io/cn-adb1caa82a5e64dxxxxxxxxxxxxxxx-1399999615.eu-west-1.elb.amazonaws.com:adb1caa82a5e64dxxxxxxxxxxxxxxx-1399999615.eu-west-1.elb.amazonaws.com listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=74EA97A3A1886E336CB9CF4D5D7XXXXXXXXXXXXXXXXX]
2022/05/18 13:56:26 [INFO] failed to create TLS cert for: 172.2.129.207, Secret "serving-cert" is invalid: metadata.annotations: Invalid value: "listener.cattle.io/cn-adb1caa82a5e64dxxxxxxxxxxxxxxx-1399999615.eu-west-1.elb.amazonaws.com": name part must be no more than 63 characters
2022/05/18 13:56:27 [ERROR] Failed to connect to peer wss://172.2.149.171/v3/connect [local ID=172.2.129.207]: remote error: tls: internal error
```

**To Reproduce**
 

**Result**

**Expected Result**

Access the Rancher web ui via `alb.dev.my.domain.net` or ideally a subpath `alb.dev.my.domain.net/rancher`

**Screenshots**

**Additional context**

**Comment by anupama2501** [comment]
Was able to reproduce the issue on v2.6.4:

Followed the docs to install rancher on eks cluster https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/amazon-eks/
Once rancher is up, set the rancher URL to a value more than 64 chars.
After the above step set up ALB controller, follow these steps:

1. eksctl utils associate-iam-oidc-provider  --region  us-east-2 --cluster  anu5 --approve  
2. eksctl create iamserviceaccount --cluster=<clustername> --namespace=kube-system --name=aws-load-balancer-controller --attach-policy-arn=arn:aws:iam::<AWSAccountID>:policy/<policyNameforThePolicy> --override-existing-serviceaccounts --region <regionName> --approve 
3. helm repo add eks https://aws.github.io/eks-charts
4. kubectl apply -k "[github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master](http://github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master)"
5. helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<clustername> --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller 
Add ingress definition from the original ticket and run`kubectl apply -f ingress`
In the rancher pod logs, see the error:
```
2022/07/14 19:47:28 [INFO] Updating TLS secret for serving-cert (count: 8): map[[field.cattle.io/projectId:local:p-zhlpl](http://field.cattle.io/projectId:local:p-zhlpl) [listener.cattle.io/cn-127.0.0.1:127.0.0.1](http://listener.cattle.io/cn-127.0.0.1:127.0.0.1) [listener.cattle.io/cn-<redacted>:<redacted>](http://listener.cattle.io/cn-<redacted>:<redacted>) [listener.cattle.io/cn-<redacted>:<redacted>](http://listener.cattle.io/cn-<redacted>:<redacted>) [listener.cattle.io/cn-<redacted>:<redacted>](http://listener.cattle.io/cn-<redacted>:<redacted>) [listener.cattle.io/cn-localhost:localhost](http://listener.cattle.io/cn-localhost:localhost) [listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system](http://listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system) [listener.cattle.io/cn-<bigURL>](http://listener.cattle.io/cn-<bigURL>) [listener.cattle.io/fingerprint:SHA1=AA7335BA9B36150F52175749F394DD73695FD9DF](http://listener.cattle.io/fingerprint:SHA1=AA7335BA9B36150F52175749F394DD73695FD9DF)]
2022/07/14 19:47:28 [INFO] failed to create TLS cert for: 127.0.0.1, Secret “serving-cert” is invalid: metadata.annotations: Invalid value: “[listener.cattle.io/cn-<bigURL>](http://listener.cattle.io/cn-<bigURL>)”: name part must be no more than 63 characters
```


Upgraded the server to v2.6-head 3506e43
Verified from local cluster `k get secrets -n cattle-system serving-cert -o yaml` and notice the annotation is truncated:
```    listener.cattle.io/cn-<truncatedURL>-ef7cf8: ```

**Comment by samjustus** [comment]
pushing to 2.6.8

**Comment by maxsokolovsky** [comment]
The main question here is what we should test for. Is this issue about testing the ability to run an AWS LB controller in Rancher or ensuring Rancher truncates an annotation that is too long without throwing an error?

**Comment by KevinJoiner** [comment]
I was able to run rancher with AWS load balancer. I followed @anupama2501 steps with one minor alteration to step 5. Instead of using the ingress definition provided in the original ticket, I applied the following service definition.
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: aws-rancher
  namespace: cattle-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP 
    - name: https
      port: 443
      targetPort: 444 
      protocol: TCP 
  
  type: LoadBalancer
  selector:
    app: rancher
```

**Comment by anupama2501** [comment]
Verified on v2.6.7-rc3:
1. Create an eks cluster:
```
eksctl create cluster \
  --name <clustername> \
  --version 1.22 \
  --region ca-central-1 \
  --nodegroup-name <ngname> \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 3 \
  --managed --ssh-access --instance-types=t3.xlarge
```
2. Run `eksctl utils associate-iam-oidc-provider --region us-east-2 --cluster <clustername> --approve`
3. Run `eksctl create iamserviceaccount --cluster=<clustername> --namespace=kube-system --name=aws-load-balancer-controller --attach-policy-arn=arn:aws:iam::<AWSAccountID>:policy/<PolicyName> --override-existing-serviceaccounts --region <aws-region> --approve
4. helm repo add eks https://aws.github.io/eks-charts
5. kubectl apply -k "[github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master](https://github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master)"
6. helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=<clustername> --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller
7. Add ingress definition from the original ticket and runkubectl apply -f ingress
Ingress definition:
```
apiVersion: v1
kind: Service
metadata:
  name: aws-rancher
  namespace: cattle-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP 
    - name: https
      port: 443
      targetPort: 444 
      protocol: TCP 
  
  type: LoadBalancer
  selector:
    app: rancher
```
8. Create a route53 record and add the dns name of the load balancer
9. Install rancher on the cluster 
10. While rancher is up, provide a very large URL that is more than 64 chars
11. Rancher server comes up and the large url is truncated:
```
metadata:
  annotations:
    listener.cattle.io/cn-<truncatedURL>-8f8ce2: <LargeURL>
    listener.cattle.io/fingerprint: SHA1=CF1819DC2C5F723626303646C4C1BF68359D00F9
  creationTimestamp: "2022-07-25T04:34:12Z"
```
