### ISSUE TITLE
[release/v2.6] Dashboard metric display wrong

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#37895]
**Rancher Server Setup**
- Rancher version: v2.6.3 (3c1d5fac3)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin

**Describe the bug**
In Dashboard metric Reserved and Used displayed is wrong.

**To Reproduce**
Install Kubernetes cluster without metric-server
Install metric-server 3.8.2 using helm chart with values
```
priorityClassName: high-priority-nonpreempting

containerPort: 4443

replicas: 2

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

service:
  labels:
  #  Add these labels to have metrics-server show up in `kubectl cluster-info dump`
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Metrics-server"
```
Open Dashboard page

**Result**
![image](https://user-images.githubusercontent.com/8457572/171806005-fb790fa1-2e78-43eb-8860-87b4e35574cc.png)
Memory used 120%
Cores Reserved avalible(3.8) not eqals Cores Used avalible(4)
Values Used not actual
![Screenshot_20220603_103003](https://user-images.githubusercontent.com/8457572/171810626-828e9728-8b66-4386-85ea-dd8c3ca9c70a.png)

**Expected Result**
All values must be equal, usage Memory cannot exceed 100%

**Screenshots**

**Additional context**
![](https://visitor-badge.glitch.me/badge?page_id=rancher_rancher_issues_37895)
