### ISSUE TITLE
kube dns pod in crashloopbackoff on k8s 1.23 with dns provider kube-dns

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37890]
**Rancher Server Setup**
- Rancher version: `v2.6.5`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.23.6+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Custom cluster 1 worker + etcd + cp`,`RKE1`

**Describe the bug**
kube dns workload pod goes into crash loop back off and never comes back up active. This is seen happening only on k8s version v1.23.6 and not on k8s version v1.22.9 on all four network providers - calico, weave, flannel and canal

**To Reproduce**
1. Create a downstream custom cluster with 1 node all roles
2. While creating the cluster, go to edit as yaml >> provide the following details:
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: <redacted>
      node_selector: null
      update_strategy: {}
    options: null
    provider: kube-dns
```
3. Add the single node by running the registration command from the cluster
4. Cluster goes into active state
5. Go to explorer >> workload pods >> Verify the kubedns pod

**Result**
kube dns pod goes into crash loop backoff with the errors and never comes backup active:
```
2022/06/02 16:01:32 [INFO] Starting node-cache image: 1.21.1
--
Thu, Jun 2 2022 9:01:32 am | flag provided but not defined: -domain
Thu, Jun 2 2022 9:01:32 am | Usage of /node-cache:
Thu, Jun 2 2022 9:01:32 am | Runs CoreDNS v1.7.0 as a nodelocal cache listening on the specified ip:port

```

**Expected Result**
Expected the kube dns deployment to come up active with no errors.

**Additional context**
kube-dns image version `rancher/mirrored-k8s-dns-node-cache:1.21.1`
