### ISSUE TITLE
Can't roll back

### ISSUE THREAD

**Issue by peterwoo1224** [rancher/rancher#37928]
**Rancher Server Setup**
- Rancher version: 2.5.6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): ACK
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.18.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): aliyun

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
  - Admin and/or Standard User

   
**Describe the bug**

When deploying Deployment through the yaml file, the new version of rancher must specify workload.user.cattle.io/workloadselector to roll back on the UI interface, otherwise it will report an error that the tag cannot be found.
```
Deployment.apps "nginx-deployment" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{}: `selector` does not match template `labels`
```

**To Reproduce**
 
Unavailable yaml file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 'nginx:1.14.0'
          name: nginx
          ports:
            - containerPort: 80
```
or Available yaml files
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    workload.user.cattle.io/workloadselector: nginx
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: nginx
  template:
    metadata:
      labels:
        app: nginx
        workload.user.cattle.io/workloadselector: nginx
    spec:
      containers:
        - image: 'nginx:1.13.0'
          name: nginx
          ports:
            - containerPort: 80
```

**Result**

**Expected Result**

**Screenshots**

**Additional context**
