### ISSUE TITLE
Intermittent connection dropping between linked containers

### ISSUE THREAD

**Issue by jbaxleyiii** [rancher/rancher#3793]
Rancher Version: v0.59.0

Docker Version: v1.10.2

OS: CoreOS 976.0.0 (4.4.3-coreos)

Steps to Reproduce: 
1. Create two stacks and link a service from stackA to stackB
2. Ping the service

Results: 
The ping resolves most of the time, but occasionally the connection is dropped.
<img width="543" alt="screenshot 2016-03-04 19 39 14" src="https://cloud.githubusercontent.com/assets/4967600/13544652/8a438fb0-e246-11e5-8833-855a528ff837.png">

Expected:
The connection always resolves

Its also worth noting that if the method calling to the linked container (in this case using `fetch` in a node application) uses an external url that is linked to the lb of the linked service, it works 100% of the time. If it uses the internal DNS to resolve, it only works about 70% of the time.

**Comment by jbaxleyiii** [comment]
It looks like this might have been on the application level not a problem with Rancher. Closing. Thanks for the great product!

**Comment by deniseschannon** [comment]
Could you share your docker-compose.yml of your services so I could try and reproduce? I've never seen this before.

**Comment by delianides** [comment]
@deniseschannon I'm working with @jbaxleyiii on the same project.

`docker-compose.yml`
```yaml
haproxy:
  expose:
  - 80:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - heighliner:heighliner
  stdin_open: true
heighliner:
  ports:
  - 80/tcp
  environment:
    ...
  image: newspring/heighliner:ec81cde1bad317fb24a7d31fecc994d50071beb4
```

`rancher-compose.yml`

```yaml
haproxy:
  scale: 1
  load_balancer_config:
    lb_cookie_stickiness_policy:
      cookie: api.heighliner
    haproxy_config:
      defaults: |-
        balance roundrobin
        log global
        mode http
        option redispatch
        option httplog
        option dontlognull
        option forwardfor
        timeout connect 5000
        timeout client 50000
        timeout server 50000
      global: |-
        log logs.papertrailapp.com:**** local0
        log logs.papertrailapp.com:**** local1 notice
        log-send-hostname heighliner-haproxy
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
heighliner:
  scale: 3
```

Here's what we know so far:

- When we first started this service, we had one container and one LB and everything worked great. We could ping the service from our app stack without any issues. 
- Then we scaled up to 3 containers. At first everything was ok, but within a few minutes we started getting dropped connections.
- I removed the LB and linked the `heighliner` service directly with the app using the alias `heighliner`. Same result, running `ping heighliner.rancher.internal` yielded the same result.
- Scaled back down to one 1 container and the dropped connections stopped.
