### ISSUE TITLE
Regression: "required: true" validation not working when installing app from Catalog

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#37980]
**Rancher Server Setup**
- Rancher version: v2.6.5

**Describe the bug**
Create an app with `questions.yml` having a question marked as `required: true`. The UI shows an asterisk (*) but performs no validation.

**To Reproduce**
```
questions:
# Image configuration
- variable: imagePullSecrets
  default: ""
  required: true
  description: "Secret name to pull image from Registry"
  type: secret
  label: Image Pull Secrets
  group: "Container Images"
``` 

**Result**
The app installation proceeds without any error.

**Expected Result**
UI should not proceed and instead throw an error after the validation check.
