### ISSUE TITLE
Unable to provision RKE2 cluster using Cilium CNI with AWS ENI

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rancher#38111]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): RKE2
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.22.10
- Cluster Type (Local/Downstream): custom downstream cluster hosted on aws

**User Information**
- What is the role of the user logged in?:  Admin
   
**Describe the bug**
Unable to provision RKE2 cluster using Cilium CNI with AWS ENI.
Bootstrap instance goes to the `Ready` state with no issues, however other control-plane nodes can't join the cluster due to wrong `"server": "https://<IP>:9345"` <IP> address,  instead of NODE-IP address planner gets _whatever_ is the last IP address in the k8s node `status. addresses`

Corresponding code: https://github.com/rancher/rancher/blob/v2.6.5/pkg/provisioningv2/rke2/planner/store.go#L412-L421

```
  status:
    addresses:
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: xxx.xx.xxx.xxx
      type: InternalIP
    - address: ip-xxx-xx-xxx-xxx.eu-central-1.compute.internal
      type: InternalDNS
    - address: ip-xxx-xx-xxx-xxx.eu-central-1.compute.internal
      type: Hostname
```

I guess the assumption here is that only one InternalIP would be there but with AWS ENI any POD IP would be added to the node adresse unless `kubelet` arg `--node-ip=<NODE-IP>` is set which is impossible currently due to another bug https://github.com/rancher/rke2/issues/3108 as there is no way to pass any dynamic `kubelet` arg that is not supported by `KubeletConfiguration`...

**To Reproduce**
Try to provision RKE2 cluster using Cilium CNI with enabled AWS ENI

```
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    eni:
      enabled: true
    ipam:
      mode: eni
```

**Result**
Cluster provisioning is stuck because secondary control plane nodes got random server IP

**Expected Result**
`/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` have correct `server` address.
```
...
server": "https://<ACTUAL_NODE_IP>:9345",
...
```

**Screenshots**

**Additional context**
