### ISSUE TITLE
rancher-logging: Rancher Logging Chart fails to create fluentd pod on a CIS1.6 Cluster

### ISSUE THREAD

**Issue by dyslexicat** [rancher/rancher#38110]
Trying to install the [Logging Operator Chart](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-logging/100.1.2%2Bup3.17.4) on a downstream RKE2 cluster with CIS1.6 enabled but the **runAsNonRoot** pod security policy prevents the fluentd pod from running successfully.

These are the helm values I am using for the release:
```
  systemdLogPath: /var/log/journal
  podSecurityContext:
    fsGroup: 101
    runAsNonRoot: true
    runAsUser: 100
  fluentbit:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
  additionalLoggingSources:
    rke2:
      enabled: true
```
      
Looking at the Logging CRD in the [rancher logging-chart](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/100.1.2%2Bup3.17.4/templates/_generic_logging.yaml) the problematic part seems to be

<img width="810" alt="Screen Shot 2022-06-27 at 18 12 50" src="https://user-images.githubusercontent.com/6024972/175974199-30a47968-fba4-413a-9ef1-1a0c87d04594.png">

In the security field for the fluentdSpec **runAsUser** should be set as **100** which creates the corresponding fluentd statefulset and pod without any issues.

#35210 seems to be the same issue.

A fix would be to add the appropriate **podSecurityContext** field underneath the security value:
    
<img width="491" alt="Screen Shot 2022-06-27 at 18 19 26" src="https://user-images.githubusercontent.com/6024972/175975411-1255477f-b1a3-4b0c-9cea-f4c22616270e.png">
