### ISSUE TITLE
cloud provider config for vSphere complains about missing password

### ISSUE THREAD

**Issue by sayshh** [rancher/rancher#38146]
**Rancher Server Setup**

- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: NA

**Information about the Cluster**

- Kubernetes version: v1.21.13 (also tried with v1.20.15)
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): VMware vSphere

**User Information**

- What is the role of the user logged in? Admin (local)
  - If custom, define the set of permissions: NA
   
**Describe the bug**

We have downstream clusters provisioned on VMware vSphere. We would like to use the "in-tree" cloud provider configuration. Hence we edit the cluster as YAML, and add the cloud provider configuration as described in [documentation](https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/config-reference/) (of course changing the values to match our infrastructure).

**To Reproduce**

1. Have (or create) a downstream cluster provisioned on VMware vSphere. For the record, I think the **Cloud Provider** choice was left the default of **None**
2. From **Cluster Management**, select the cluster and choose **Edit Config**
3. In the cluster configuration screen, choose **Edit as YAML**
4. Paste the cloud configuration under the `cloud_provider:` section, so it looks like below example.
5. Click **Save**

Example cloud provider configuration:

```yaml
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      global:
        insecure-flag: true
      virtual_center:
        vc.example.com:
          user: provisioner
          password: secret
          port: 443
          datacenters: /My-Datacenter
          soap-roundtrip-count: 0
      workspace:
        server: vc.example.com
        folder: vm/myvmfolder
        default-datastore: vsan-1
        datacenter: /My-Datacenter
        resourcepool-path: /My-Datacenter/My-Cluster/Resources/My-ResourcePool
```

**Result**

1. The configuration is not applied, and an error (as shown in screenshot below) is shown. 
2. `kubelet` container on the (master) node keeps restarting

Output of `docker ps`:
```
CONTAINER ID   IMAGE                                           COMMAND                  CREATED         STATUS                          PORTS     NAMES
f16372512c01   rancher/hyperkube:v1.21.13-rancher1             "/opt/rke-tools/entr…"   8 minutes ago   Restarting (1) 30 seconds ago             kubelet
```

Output of `docker logs kubelet`:

```
W0630 08:51:34.709243    4272 vsphere.go:332] SecretName and/or SecretNamespace is not provided. VCP will use username and password from config file
E0630 08:51:34.709258    4272 vsphere.go:436] vcConfig.Password is empty for vc vc.example.com!
E0630 08:51:34.709283    4272 server.go:292] "Failed to run kubelet" err="failed to run Kubelet: could not init cloud provider \"vsphere\": Password is missing"
```

**Expected Result**

1. Cloud provider configuration is applied successfully
2. `kubelet` container comes up successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/20085373/176629407-f1219295-a012-4517-8976-04f57999efc0.png)

**Additional context**

* Even if we specify an incorrect password deliberately, same error is shown instead of authentication error.
* The same credentials and settings are used in node templates to provision clusters.
