### ISSUE TITLE
Deleted CRDs for Logging V1

### ISSUE THREAD

**Issue by rs-oinis** [rancher/rancher#38186]
Hi, I deleted by mistake the following CRDs that are necessary to install Logging V1:
- `clusterloggings.management.cattle.io`
- `projectloggings.management.cattle.io`

So I tried to re-apply the manifests (see below for an example) and got the following error: 
`"clusterloggings.management.cattle.io" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]` 

Manifest for `clusterloggings.management.cattle.io`:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterloggings.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: ClusterLogging
    listKind: ClusterLoggingList
    plural: clusterloggings
    singular: clusterlogging
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v3
    served: true
    storage: true
```

So I modified the manifests so that they looked like that:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterloggings.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: ClusterLogging
    listKind: ClusterLoggingList
    plural: clusterloggings
    singular: clusterlogging
  scope: Namespaced
  versions:
  - name: v3
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties: {}
      x-preserve-unknown-fields: true
```

Now, when I try to enable Logging V1, I get no error but no pod is being created and in `Cluster Tools` it does not appear as installed:
![image](https://user-images.githubusercontent.com/108675021/177176511-b3552305-c6cd-42d7-90ab-7f800b18b65c.png)

Moreover, I do not see `rancher-logging` among the installed apps in the `Legacy` > `Project` > `Apps` menu.

How can I fix this so that I can properly enable Logging V1?
