### ISSUE TITLE
Istio - Unable to change cpu and memory allocation for istio-sidecar proxy

### ISSUE THREAD

**Issue by rafael-natali-bzy** [rancher/rancher#38230]
**Is your feature request related to a problem? Please describe.**
Unable to change `cpu` and `memory` allocation for `istio-proxy` sidecar. The [default](https://rancher.com/docs/rancher/v2.6/en/istio/resources/) values are stored in a `ConfigMap` named `istio-sidecar-injector` that is (apparently) created during installation by the `Job` `istioctl-installer` and not directly by the `Helm Chart`.

Running `helm get all rancher-istio` the `istio-sidecar-injector` is not listed as part of the `Helm`.

`pod-with-default-values`

```yaml
Init Containers:
  istio-validation:
    Container ID:  docker://9ba6af97b0ec9f811fe59f73a7a7a961100f8e64b7d1a1f5aad4f11f57095a68
    Image:         docker.repo.bfl.local/rancher/mirrored-istio-proxyv2:1.13.3
    Image ID:      docker-pullable://docker.repo.bfl.local/rancher/mirrored-istio-proxyv2@sha256:b4123efa0ad03a007bdae4b0348085ea24b68af6b2ec439c9bf5360339ed1d22
  ....
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 08 Jul 2022 14:38:57 +0100
      Finished:     Fri, 08 Jul 2022 14:38:57 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     128Mi
...
```

`pod-with-edited-values`

```yaml
istio-proxy:
    Container ID:  docker://627f0521e0d561ac3c5a929070a730ce2fd5d0955ab835ae53a033c0019cb031
    Image:         docker.repo.bfl.local/rancher/mirrored-istio-proxyv2:1.13.3
    Image ID:      docker-pullable://docker.repo.bfl.local/rancher/mirrored-istio-proxyv2@sha256:b4123efa0ad03a007bdae4b0348085ea24b68af6b2ec439c9bf5360339ed1d22
    ...
    State:          Running
      Started:      Fri, 08 Jul 2022 14:39:00 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  256Mi
    Requests:
      cpu:      100m
      memory:   128Mi
...
```

Also I noticed that the `proxy` is using a different `requests` value than in the documentation:

```bash
"requests": {
     "cpu": "100m",
     "memory": "128Mi"
}
```

Rancher: v2.6.6
Istio: 1.13.3

**Describe the solution you'd like**
To have the possibility in the `Edit/Upgrade` screen to change the `values.yaml` and update the `istio-proxy` sidecar. 

**Describe alternatives you've considered**
Manually edit the `ConfigMap` after the installation is a functional workaround.
