### ISSUE TITLE
GitRepo in stalled condition Git Updating when using SSH 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38242]
**Rancher Server Setup**
- Rancher version: v2.6.6 and v2.6.2
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: RKE1, - Rancher 2.6.2 with k8s 1.21.5 and Rancher 2.6.6 with k8s 1.23.6
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: 1.21.13 and 1.23.7
- Cluster Type: Downstream 
   - If downstream, what type of cluster?: Custom

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**

When adding a GitRepo the GitRepo goes into Active state and I can visually see it gets the correct commit ID from the repository but after some time it goes into the `Git Updating` state and it stays there indefinitely 

**To Reproduce**

- Create a Git repository with fleet bundles and make sure to use your SSH credentials. (the [fleet-examples](https://github.com/rancher/fleet-examples) repo can be used for this purpose)
- Copy the SSH url and configure a GitRepo with it. Use your ssh public and private keys. This should match the public key configured in your Git server (ex. Github)
- Apply the configuration now check the commit ID is shown in the GitRepo entry in the Rancher UI
- After some time it will go into the Git Updating state

**Result**

- The GitRepo condition `Stalled: True` (view Yaml -> conditions)
- There isn't any logs about it in the controller or fleet agent.

**Expected Result**
- Fleet clones the fleet repo properly and deploys the bundles to the downstream cluster.

**Screenshots**

![Screen Shot 2022-07-08 at 5 57 03 PM](https://user-images.githubusercontent.com/27659/178315462-a56f195a-100b-49c5-8c3b-e55ec5d5463c.png)
![Screen Shot 2022-07-08 at 5 57 22 PM](https://user-images.githubusercontent.com/27659/178315454-c908fe2a-5b9c-40d2-b1a6-bfd0a835dcc7.png)

**Additional context**

Rancher version `v2.6.6` has fleet `v0.3.9`
Rancher version `v2.6.2` has fleet `v0.3.7`

GitRepo Conditions

```yaml
status:
  commit: 763fe7f7defce8f7878469efe5a2b213e4432cbd
  conditions:
  - lastUpdateTime: "2022-07-11T15:40:23Z"
    status: "True"
    type: Ready
  - lastUpdateTime: "2022-07-11T16:45:33Z"
    status: "True"
    type: Accepted
  - lastUpdateTime: "2022-07-11T15:40:24Z"
    status: "True"
    type: ImageSynced
  - lastUpdateTime: "2022-07-11T15:40:24Z"
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2022-07-11T15:40:47Z"
    reason: Stalled
    status: "True"
    type: Stalled
  - lastUpdateTime: "2022-07-11T16:45:33Z"
    status: "True"
    type: Synced
```

**Comment by manno** [comment]
Can you provide the output of `kubectl get gitrepo -A -o jsonpath='{.items[*].status}'`?

**Comment by izaac** [comment]
@manno sure here it is:

```json
{
    "commit": "763fe7f7defce8f7878469efe5a2b213e4432cbd",
    "conditions": [{
        "lastUpdateTime": "2022-07-12T16:10:55Z",
        "status": "True",
        "type": "Ready"
    }, {
        "lastUpdateTime": "2022-07-12T16:12:12Z",
        "status": "True",
        "type": "Accepted"
    }, {
        "lastUpdateTime": "2022-07-12T16:10:55Z",
        "status": "True",
        "type": "ImageSynced"
    }, {
        "lastUpdateTime": "2022-07-12T16:10:55Z",
        "status": "False",
        "type": "Reconciling"
    }, {
        "lastUpdateTime": "2022-07-12T16:11:19Z",
        "reason": "Stalled",
        "status": "True",
        "type": "Stalled"
    }, {
        "lastUpdateTime": "2022-07-12T16:12:12Z",
        "status": "True",
        "type": "Synced"
    }],
    "desiredReadyClusters": 0,
    "display": {
        "readyBundleDeployments": "0/0",
        "state": "GitUpdating"
    },
    "gitJobStatus": "Failed",
    "lastSyncedImageScanTime": null,
    "observedGeneration": 1,
    "readyClusters": 0,
    "resourceCounts": {
        "desiredReady": 0,
        "missing": 0,
        "modified": 0,
        "notReady": 0,
        "orphaned": 0,
        "ready": 0,
        "unknown": 0,
        "waitApplied": 0
    },
    "summary": {
        "desiredReady": 0,
        "ready": 0
    }
}
```

**Comment by manno** [comment]
Interesting, it says `"gitJobStatus": "Failed"`. We could try to look at the gitjob resource status (`kubectl get gitjob -A -o jsonpath='{.items[*].status}'`), but I guess the error message really is in the gitjob's job log. 

Sorry, I can't give you a complete command to run, that job's pod is hard to match. There should be a 'completed' pod with a name like `kustomize-f5b73-ldfzv`. Is there something about a failed git clone in that pod's log? `kubectl logs -n fleet-default kustomize-f5b73-ldfzv --all-containers`.

**Comment by manno** [comment]
Hm, the key needs to be in PEM format (not e.g. DER). 
In my test I used a gitrepo like this:
```
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: testing
spec:
  repo: git@github.com:fleetrepoci/testeks.git
  clientSecretName: git-auth
```
And created the key with `ssh-keygen -f id_rsa_test -N ""` and the secret with `kubectl create secret generic git-auth --type kubernetes.io/ssh-auth --from-file=ssh-privatekey=id_rsa_test --from-file=ssh-publickey=id_rsa_test.pub`
