### ISSUE TITLE
[RKE2] Unable to add custom encryption configuration to yaml

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#38246]
**Rancher Server Setup**
- Rancher version: v2.6-head 13482ca
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

EC2 node driver cluster
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

When provisioning a cluster, user is not able to add custom encryption configuration to the yaml. The yaml file is editable during cluster creation, but once the user clicks `Create`, the custom configuration is removed and changes are not preserved.

**To Reproduce**
 
1. Create RKE2 cluster
2. Edit YAML and add the following configuration under `rkeConfig` and Click `Create`
```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
          - identity: {} 
```

**Result**
The custom configuration is removed and secret is not created

**Expected Result**

The custom configuration should be preserved and secret should be created
