### ISSUE TITLE
rancher alerting-drivers does not detect receivers and routes unless they're configured in the 'deprecated' section

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#38260]
**Rancher Server Setup**
- Rancher version: `2.6.5`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.22`
- Cluster Type (Local/Downstream): `downstream ec2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

   
**Describe the bug**
When configuring receivers and routes in an alertmanager config, the sachet driver (that sends the alerts to the chosen provider (eg, telegram) does not detect those routes & receivers. 
configuring identical routes and receivers in the deprecated section allows alerting-drivers sachet to register them. after adding there, the alerts are sent to the chosen sms endpoint. 

**To Reproduce**
1. install monitoring
2. install alerting-drivers
3. create alertmanager config
4. add receiver
5. add route
6. create prometheus rule
7. configure sachet config map to send alert to desired provider (eg, telegram)

**Result**
alerts are not sent. they are, however, observed in the UI

**Expected Result**

routes and receivers are detected by alerting-drivers and sent to the configured endpoint.

**Screenshots**

<img width="1623" alt="2022-07-12_17-31-55" src="https://user-images.githubusercontent.com/89212856/178599208-62ba5674-78f7-43db-b933-cf6b69489fe4.png">

<img width="1623" alt="2022-07-12_17-33-30" src="https://user-images.githubusercontent.com/89212856/178599472-1f1a8baa-994a-4db8-a704-cedcadcbdda5.png">

<img width="1620" alt="2022-07-12_17-35-15" src="https://user-images.githubusercontent.com/89212856/178599815-a9ee222b-b9a5-4273-b1f3-a15fa980cbe4.png">

**Additional context**

**Comment by rmammadli** [comment]
I hit the same issue.
Additional matcher is added indeed for namespace, where AlertmanagerConfig is deployed (see **match** section for **default-app-a-alertmanager-app-a-reciever**)

```
...
route:
  receiver: "null"
  group_by:
  - job
  continue: false
  routes:
  - receiver: default-app-a-alertmanager-app-a-reciever
    group_by:
    - app
    match:
      alertname: .*
      namespace: default
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
  - receiver: "null"
    match:
      alertname: Watchdog
    continue: false
...
```

Since matchers are ANDed together, even putting label '**namespace: default**' in PrometheusRule object did not solve the issue.
