### ISSUE TITLE
> @boot-vue I'm having the same problem with rancher and traefik, rancher-ui shows 404 page not found but has a valid certificate. How did you solve the issue?

### ISSUE THREAD

**Issue by flanet88** [rancher/rancher#38271]
> @boot-vue I'm having the same problem with rancher and traefik, rancher-ui shows 404 page not found but has a valid certificate. How did you solve the issue?

I changed to k3s  , install rancher server  based on k3s cluster ,  after changed traefik config,  visit rancher-ui normal

1.  not recommend 
     edit  `/var/lib/rancher/k3s/server/manifests/traefik.yml`  , saved  , k3s will auto update
     
     after restart k3s-server service,  the yaml file  will renew

     ```yml
        .............
          valuesContent: |-
             additionalArguments:
                - "--entryPoints.web.proxyProtocol.insecure"
                - "--entryPoints.web.forwardedHeaders.insecure"
        ....
        ....
     ```
    

2.  recommend
     add `HelmChartConfig`   `/var/lib/rancher/k3s/server/manifests/traefik-config.yml` 
     
  ```yml

  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    name: traefik
    namespace: kube-system
  spec:
    valuesContent: |-
      additionalArguments:
        - "--entryPoints.web.proxyProtocol.insecure"
        - "--entryPoints.web.forwardedHeaders.insecure" 


  ```

_Originally posted by @boot-vue in https://github.com/rancher/rancher/issues/36499#issuecomment-1062465664_
