### ISSUE TITLE
Where does rancher store server data when installed on a kubernetes cluster?

### ISSUE THREAD

**Issue by ViniciusBastosTR** [rancher/rancher#38278]
I installed Rancher following the tutorial https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/ and I'm not sure where Rancher stores application data.

Before installing on Kubernetes, Rancher was running in a Docker container created through a Docker compose, which had been configured its own volume for the container.

```yaml
version: "3.3"

volumes:
  rancher_data: {}

networks:
  rancher_network:
    ipam:
      driver: default

services:
  rancher:
    container_name: rancher
    image: rancher/rancher:v2.6.2
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher_data:/var/lib:rw
      - /data/rancher:/var/lib/rancher:rw
    networks:
      - rancher_network
    environment:
      - HTTP_PROXY=""
      - HTTPS_PROXY=""
      - NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local"
```

But today, using Kubernetes I could not find the persistent volumes within the cluster.
