### ISSUE TITLE
[BUG] Rancher handler `cluster-create` deleting secrets in other namespaces related to clusters

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/rancher#38350]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): Helm chart RKE2

**Information about the Cluster**
- Kubernetes version: v1.22.9+rke2r2
- Cluster Type (Local/Downstream): Local

**Describe the bug**

We are creating clusters for ArgoCD based on our Rancher clusters by hitting the API and pulling their names, ids, and labels and creating a secret in the argocd namespace with this information.

General layout of the secret is
```yaml
apiVersion: v1
kind: Secret
metadata:
  generateName: argocd-
  labels:
    app.kubernetes.io/managed-by: my-sync-job
    argocd.argoproj.io/secret-type: cluster
    objectset.rio.cattle.io/hash: ...
    ...Cluster Labels
  name: argocd-generated-name
  namespace: my-ns
type: Opaque
data:
  config: ...Things like access token, CA information, etc.
  name: ...Cluster Name in Rancher
  server: ...ServerURL in Rancher API
```

We have tried multiple methods to get Rancher to stop deleting the secret such as
- Changing the name/generating it
- Removing all contents of the secret
- Removing all labels of the secret
- Removing any annotations of the secret

Everything causes the secret to still be deleted, and we also confirmed its not related to the specific namespace as we cloned the secret to a different namespace and it still deletes it.

The only way we can get Rancher to stop deleting it is to make an OPA rule that deny's the ability to delete the secrets. Of which then puts all of the Clusters in `ClusterProvisioning` in an errored state with the error of

`Failed to delete argocd/argocd-gen-name /v1, Kind=Secret for cluster-create fleet-default/my-cluster-name: admission webhook "validation.gatekeeper.sh" denied the request: [argocd-protection] Cannot delete Secret <argocd-gen-name> since it is set as a protected resource via a special label`

This error is on all of our clusters now, except the local one which isn't deleted and seems to be ignored (guessing because it's in fleet-local).

**To Reproduce**
1. Create a K8s jobs to automate [this](https://gist.github.com/janeczku/b16154194f7f03f772645303af8e9f80) process as well as sync things like labels from the API
2. Run cronjob

**Result**

Clusters (except the local) synced with this method are automatically deleted after around 30-45 seconds at most.

**Expected Result**

Nothing should happen.

**Additional context**

We are using ArgoCD for deployments and are trying to automate the syncing of Rancher cluster object to ArgoCD's cluster secrets.
