### ISSUE TITLE
[RFE] Steve should only send schema updates when schemas change

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#38467]
We are seeing on various systems at scale that the backend if almost flooding the web socket every few seconds with schema updates, even though schemas have not changed.

The UI has to process these and since these drive a lot of the UI, this causes a lot of elements in the UI to re-compute.

It would be nice if the backend could check that a schema did actually change before sending updates.

You can see this for yourself by opening the UI with developer tools in Chrome, going to the Network tab and looking at web sockets. Find the Steve web socket - do this on a downstream cluster.

Create a new CRD (e.g. create the one from here - https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)

You will observe that in addition to the new schema, you get web sockets for a tonne of other schemas that were not changed).

**Comment by gaktive** [comment]
Internal reference: SURE-5398

**Comment by KevinJoiner** [comment]
Rancher PR for Steve changes https://github.com/rancher/rancher/pull/39782

**Comment by KevinJoiner** [comment]
# Validation

## Root Cause
The Steve Websocket used to stream schema updates contained false positives when detecting changes in schemas causing the unnecessary change event to be sent on the websocket. These false positives were caused by the access attribute being stripped before checking for equivalency to the previously saved list of schemas.

## What was fixed, or what change has occurred
Steve's change detection logic was updated to ignore the access attribute since it is not sent to the frontend.

## Areas or cases that should be tested
### Test that only correct schema changes are sent on the socket
1. Start Rancher server v2.7-HEAD
2. Login to the Rancher server
3. Open Developer UI in Chrome
4. Select network tab
5. Select WS filter for Websockets
6. Navigate to the local cluster dashboard
7. Refresh the page.
8. Select `subscribe?socketId=1`
9. Select the Messages tab
10. In the filter bar under the message tab, input `"resourceType":"schema"` so we only see relevant messages.
11. Apply the given CRD
    ```yaml
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: crontabs.stable.example.com
    spec:
      group: stable.example.com
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    cronSpec:
                      type: string
                    image:
                      type: string
                    replicas:
                      type: integer
      scope: Namespaced
      names:
        plural: crontabs
        singular: crontab
        kind: CronTab
        shortNames:
        - ct
    ```
12.  Verify that there are only two new messages for the added schema.
    `{"name":"resource.create","resourceType":"schema","data":{"id":"stable.example.com.v1.crontab.spec",...`
    `"{"name":"resource.create","resourceType":"schema","data":{"id":"stable.example.com.crontab",...`


## Are the repro steps accurate/minimal?
1. Start Rancher server v2.7.0
2. Login to the Rancher server
3. Open Developer UI in Chrome
4. Select network tab
5. Select WS filter for Websockets
6. Navigate to the local cluster dashboard
7. Refresh the page.
8. Select `subscribe?socketId=1`
9. Select the Messages tab
10. In the filter bar under the message tab, input `"resourceType":"schema"` so we only see relevant messages.
11. Apply the given CRD
    ```yaml
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: crontabs.stable.example.com
    spec:
      group: stable.example.com
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    cronSpec:
                      type: string
                    image:
                      type: string
                    replicas:
                      type: integer
      scope: Namespaced
      names:
        plural: crontabs
        singular: crontab
        kind: CronTab
        shortNames:
        - ct
    ```
12.  Verify that there are multiple 100+ resource.change events for schemas.
