### ISSUE TITLE
[BUG] Cannot change the kubelet root dir

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#38539]
## Issue
Trying to change the kubelet root dir is failing if you have a private registry setup.

There is a file `config.json`  that contains the private registry token ( pull the images from a private registry with user/password auth ) and it cannot be changed through a extra_binds or extra_args

It is possible to change the kubelet root dir by modifying the extra_args and extra_binds on an existing cluster, however editing the extra_args and extra_binds in the cluster config before provisioning a new cluster the cluster creation fails.

Following the KB is not working
https://www.suse.com/support/kb/doc/?id=000020058

Moving the different folders created in /var/lib/kubelet with extra_args and binding the folders is working up to the point where we had to move the config.json file.

## Repro steps:

Create a cluster with a private registry and user/pass authentication

Apply an extended version of the KB:
```
kubelet:
  extra_args:
   cert-dir: /data/kube/pki
   root-dir: /data/kube
   seccomp-profile-root: /data/kube/seccomp
   volume-plugin-dir: /data/kube/volumeplugins
 extra_binds:
   '/data/kube:/data/kube:shared,z'
```

There are still 2 folders that do not move:
```
:/var/lib/kubelet# ls
config.json device-plugins
```

### Actual behavior:
The cluster deployment is failing

### Expected behavior:
The cluster deployment works and the kubelet folder is moved to a custom location.

SURE-3331
