### ISSUE TITLE
[BUG] Nodelocal.IPAddress field is not used when creating kubelet arguments

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#38564]
**Rancher Server Setup**
- Rancher version: 2.6-head, latest RKE
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Describe the bug**
The `DNS.Nodelocal.IPAddress` is not being utilized when RKE creates arguments for the kublet. This issue was introduced in https://github.com/rancher/rke/commit/fbac9aa8f95dfaad3bdc46ae82b21b27662e518b when the logic for creating the command arguments was changed. 

**To Reproduce**
Create a cluster which utilizes node-local DNS, following this documentation https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#nodelocal-dns 

**Result**
the `cluster-dns` field is not passed as an argument the kubelet

**Expected Result**
the `cluster-dns` field is passed as an argument to the kubelet

**Comment by HarrisonWAffel** [comment]
This bug found its way into RKE 1.3.12, however rancher v2.6.6 uses RKE 1.3.11, so I do not think there is a way to test this issue without directly modifying the go.mod file used by Rancher. Regardless, I'm leaving this template here in case this needs to be tested in the future or that someone on QA knows of a way to specify the RKE version outside of changing it directly in the go.mod

### Root cause
  When implementing #25500 the logic for crafting kubelet arguments was updated, but unfortunately the `cluster-dns` argument was left behind. 
### What was fixed, or what changes have occurred
  The logic for determining if the `cluster-dns` argument needs to be supplied was moved so that the call to `appendArgs` would properly incorporate that argument. 
### Areas or cases that should be tested
  The passing of the `cluster-dns` argument, as specified in this documentation https://rancher.com/docs/rke/latest/en/config-options/add-ons/dns/#nodelocal-dns. 

To properly determine if this has been fixed, follow these steps 

+ Create a rancher server
+ provision an RKE1 cluster on any cloud-provider (1 node, all roles)
+ SSH into the single node once it has finished provisioning 
+ run `docker inspect kubelet`
+ Find the `Entrypoint` array within the output of the above command
+ ensure that the `--cluster-dns` flag has been passed properly, and its value is equal to the one passed in the cluster yaml

These steps can be done off of 2.6.7-rc7 to determine that the flag has **not** been passed properly, and retested on 2.6-head to confirm the fix.

### What areas could experience regressions?
  None, this change resolves a regression introduced before the release of 2.6.7

**Comment by sowmyav27** [comment]
**On 2.6.6 this issue isn't there**

- Deploy a single node AWS node driver cluster RKE1 1.23 k8s cluster with this in cluster.yml
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ip-1
      node_selector: null
```
- On the node `docker logs kubelet` shows `--cluster-dns=ip-1` (ip in cluster.yml) which is expected

---
**On 2.6.7-rc7**

- Deploy a single node AWS node driver cluster RKE1 1.24 k8s cluster with this in cluster.yml
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ip-1
      node_selector: null
```
- On the node `docker logs kubelet` shows --cluster-dns=10.43.0.10 which is not the same IP as set in cluster.yml

**Comment by sowmyav27** [comment]
**On `v2.6.7-rc9`**

- Deploy a single node AWS node driver cluster RKE1 1.23 k8s cluster with this in cluster.yml
```
  dns:
    linear_autoscaler_params: {}
    node_selector: null
    nodelocal:
      ip_address: ip-1
      node_selector: null
```
- On the node `docker logs kubelet` shows `--cluster-dns=ip-1` (ip in cluster.yml) which is expected
