### ISSUE TITLE
[BUG] Cannot create AKS cluster using existing VNET with kubenet plugin

### ISSUE THREAD

**Issue by rajan2** [rancher/rancher#38560]
SURE-5140

**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):AKS 1.23.8
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AKS cluster in AZURE

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

From Rancher terraform provider, it's not possible to create a new AKS cluster with existing VNET and SUBNET. Instead of using existing network details, rancher always try to create a new VNET with kubenet plugin.

When using Azure terraform module, its possible to create AKS in custom VNET. 

In rancher UI, its not possible to select VNET when using kubenet plugin. 

**To Reproduce**

```
resource "rancher2_cloud_credential" "foo-aks" {
  name = "foo-aks"
  azure_credential_config {
    client_id = "<CLIENT_ID>"
    client_secret = "<CLIENT_SECRET>"
    subscription_id = "<SUBSCRIPTION_ID>"
  }
}

resource "rancher2_cluster" "foo" {
  name = "foo"
  description = "Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    resource_group = "<RESOURCE_GROUP>"
    resource_location = "<RESOURCE_LOCATION>"
    dns_prefix = "<DNS_PREFIX>"
    kubernetes_version = "1.21.2"
    network_plugin = "kubenet"
    virtual_network = "AZURE VNET"
    virtual_network_resource_group = "VNET RG GROUP"
    subnet = "SUBNET NAME"
    node_pools {
      availability_zones = ["1", "2", "3"]
      name = "<NODEPOOL_NAME>"
      count = 1
      orchestrator_version = "1.21.2"
      os_disk_size_gb = 128
      vm_size = "Standard_DS2_v2"
    }
  }
}
```

**Result**
AKS cluster is created with new VNET in the subscription.
**Expected Result**

AKS cluster should be installed in existing VNET/SUBNET.  
**Screenshots**

**Additional context**

**Comment by rajan2** [comment]
Update:

With  `aks_config` terraform resource its possible to use existing VNET and SUBNET, But its provisioning AV set in Azure and not VMSS. 
Some how this feature is not included in `aks_config_v2` terraform.

From the UI, Its not possible to select VNET to use with kubenet plugin. However azure supports bring your own VNET option when creating AKS clusters

**Comment by rajan2** [comment]
Kindly check the following PRs
https://github.com/rancher/aks-operator/pull/163
https://github.com/rancher/aks-operator/pull/158

With this, Its possible to create AKS cluster with `aks_config_v2` and disable creation of EGRESS load balancer

**Comment by rajan2** [comment]
@snasovich Can kindly someone review my changes

**Comment by kkaempf** [comment]
Adding UI as users need to be able to pick an existing VNET with the Kubenet CNI.

**Comment by kkaempf** [comment]
Opened https://github.com/rancher/dashboard/issues/8750

**Comment by valaparthvi** [comment]
Validated on Rancher(v2.9-a9355940c0629ca419b7dd3e4098c4ea0e52c0c0-head); Dashboard(master 46a44c1), it is **partially** fixed.

Also, tested this via Terraform script with `aks_config_v2`, it uses existing vnet with kubenet plugin.

<details><summary>TF script</summary>
<p>

```terraform

terraform { 
 required_providers { 
   rancher2 = { 
     source = "rancher/rancher2" 
     version = "4.1.0" 
   } 
 } 
} 
               
provider "rancher2" { 
 api_url   = "hostname"
 access_key = "access-key" 
 secret_key = "secret" 
 insecure = true 
} 
               
resource "rancher2_cloud_credential" "rancher2_cloud_credential" { 
 name = "aks" 
 azure_credential_config { 
   client_id      = "client-id" 
   client_secret  = "client-secret"
   subscription_id = "subscription-id" 
 } 
} 
               
resource "rancher2_cluster" "rancher2_cluster" { 
 name = "pvala-aks-terraform-kubenet" 
 aks_config_v2 { 
   cloud_credential_id = rancher2_cloud_credential.rancher2_cloud_credential.id 
   resource_group = "rg-name"
   resource_location = "location" 
   dns_prefix = "dns-prefix"
   kubernetes_version = "1.28.10" 
   network_plugin = "kubenet"
   virtual_network = "existing-vnet-name"
   virtual_network_resource_group = "vnet-rg-name"
   subnet = "snet-eastus-1"
   node_pools { 
     name = "pool1" 
     vm_size = "Standard_DS2_v2" 
     mode = "System" 
     count = 1
     max_surge = "1" 
     orchestrator_version = "1.28.10" 
   } 
 } 
}

```

</p>
</details> 

Even though it is possible to select an existing VNET from UI and successfully create a cluster, that even shows up in `AKSConfig` as seen in the YAML below, the UI stills shows `None`.

![image](https://github.com/rancher/rancher/assets/11015077/9f5ea4bf-93ef-4c69-9083-29e605bec746)


<details><summary>kubenet plugin with calico network policy</summary>
<p>

```
  aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-29dkf
    baseUrl: null
    clusterName: pvala-aks-kubenet-calico
    dnsPrefix: pvala-aks-dns
    dnsServiceIp: 10.0.0.10
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: false
    kubernetesVersion: 1.30.0
    linuxAdminUsername: azureuser
    loadBalancerSku: standard
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: null
    monitoring: null
    networkPlugin: kubenet
    networkPolicy: calico
    nodePools:
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.30.0
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
        vnetSubnetID: >-
          /subscriptions/<omitted>/resourceGroups/pvala-aks-rg/providers/Microsoft.Network/virtualNetworks/<omitted>/subnets/<omitted>
    outboundType: loadBalancer
    podCidr: null
    privateCluster: false
    privateDnsZone: null
    resourceGroup: pvala-aks-rg
    resourceLocation: eastus
    serviceCidr: 10.0.0.0/16
    subnet: null
    userAssignedIdentity: null
    virtualNetwork: null
    virtualNetworkResourceGroup: null
```

</p>
</details> 

<details><summary>kubenet plugin and vnet</summary>
<p>

```
spec:
  agentImageOverride: ''
  aksConfig:
    authBaseUrl: null
    authorizedIpRanges: null
    azureCredentialSecret: cattle-global-data:cc-29dkf
    baseUrl: null
    clusterName: pvala-aks-kubenet
    dnsPrefix: pvala-aks-dns
    dnsServiceIp: 10.0.0.10
    dockerBridgeCidr: null
    httpApplicationRouting: null
    imported: false
    kubernetesVersion: 1.30.0
    linuxAdminUsername: azureuser
    loadBalancerSku: standard
    logAnalyticsWorkspaceGroup: null
    logAnalyticsWorkspaceName: null
    managedIdentity: null
    monitoring: null
    networkPlugin: kubenet
    networkPolicy: null
    nodePools:
      - availabilityZones:
          - '1'
          - '2'
          - '3'
        count: 1
        maxPods: 110
        maxSurge: '1'
        mode: System
        name: agentpool
        orchestratorVersion: 1.30.0
        osDiskSizeGB: 128
        osDiskType: Managed
        osType: Linux
        vmSize: Standard_DS2_v2
        vnetSubnetID: >-
          /subscriptions/<omitted>/resourceGroups/pvala-aks-rg/providers/Microsoft.Network/virtualNetworks/<omitted>/subnets/<omitted>
    outboundType: loadBalancer
    podCidr: null
    privateCluster: false
    privateDnsZone: null
    resourceGroup: pvala-aks-rg
    resourceLocation: eastus
    serviceCidr: 10.0.0.0/16
    subnet: null
    tags:
      Account Owner: mlatimer@suse.com
      Account Type: group
      Cost Center: '211799999'
      Department: ecm
      Environment: development
      Finance Business Partner: geoff.guest@suse.com
      General Ledger Code: '200000119'
      Stakeholder: jeff.hobbs@suse.com
      Team: enterprise-storage
    userAssignedIdentity: null
    virtualNetwork: null
    virtualNetworkResourceGroup: null
```

</p>
</details>
