### ISSUE TITLE
LDAP - Group's members identification

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3875]
@ViBiOh wrote:

I'm currently looking to set Access Control with OpenLDAP on Docker Rancher Server. Mapping of Users was made but identifying them into groups for easy environment configuration doesn't work.

After search, I found that piece of code in OpenLDAPIdentityProvider and requests seems wrong to me.

``` java
if (memberOf != null) {// null if this user belongs to no group at all
    for (int i = 0; i < memberOf.size(); i++) {
        identities.addAll(resultsToIdentities(searchLdap("(&(" + getConstantsConfig().getUserMemberAttribute() +
                '=' + memberOf.get(i).toString() + ")(" + getConstantsConfig().objectClass() + '=' +
                getConstantsConfig().getGroupObjectClass() + "))")));

    }
}
```

For example, this will generate `(& (memberOf=CN_OF_MY_GROUP) (objectclass=group))` but there is no attribute named `memberOf` on Groups. The same attribute name `getUserMemberAttribute` is used for both User and Groups mapping.

From my point of view, `memberOf` must be replaced by `distinguishedName` or a configurable value

Below code (next to the first), is trying to do the inverse but again, `getLogin` doesn't match our expectations, we store DN inside `member` attribute of Groups.

``` java
if (user != null && StringUtils.isNotBlank(user.getLogin())){
    String query = "(&(" + getConstantsConfig().getGroupMemberMappingAttribute()
            + '=' + user.getLogin()
            + ")(" + getConstantsConfig().objectClass() + '='
            + getConstantsConfig().getGroupObjectClass() + "))";
    identities.addAll(resultsToIdentities(searchLdap(query)));
}
```

Am I wrong ?

**Comment by hibooboo2** [comment]
The above code works as expected and designed. Your setup seems to be a different use case.

**Comment by frol** [comment]
I have just bumped in this issue on Rancher Server v0.63, so I decided to start with an upgrade to v1.0.0-rc4, which didn't help.

**Comment by frol** [comment]
Digging into the source code, it seems that `getUserMemberAttribute` is not `memberOf`, but `gidNumber`; here is an extract from API response for `api.auth.ldap.openldap.user.member.attribute` key:

```json
"name": "api.auth.ldap.openldap.user.member.attribute",
"activeValue": "gidNumber",
"inDb": true,
"source": "Database",
"value": "gidNumber",
```

Using a sniffer I can see the following search performed on our LDAP:

```
(&(gidNumber=1489000011)(objectClass=groupofnames))
```

This thing is OK, but according to the source code:

```java
Attribute memberOf = userAttributes.get(getConstantsConfig().getUserMemberAttribute());
...
if (memberOf != null) {// null if this user belongs to no group at all
    for (int i = 0; i < memberOf.size(); i++) {
        identities.addAll(resultsToIdentities(searchLdap("(&(" + getConstantsConfig().getUserMemberAttribute() +
                '=' + memberOf.get(i).toString() + ")(" + getConstantsConfig().objectClass() + '=' +
                getConstantsConfig().getGroupObjectClass() + "))")));
    }
}
```

, given that `getConstantsConfig().getUserMemberAttribute()` is `gidNumber`, we end up having one value in `memberOf`, and it is user's group ID (!) instead of a list of membership groups.

Just for your reference, here is an extract of LDAP user search response:

```yaml
uid: test_user
mail: test_user@my-company.com
krbPrincipalName: test_user@MY-COMPANY.COM
givenName: Test
sn: User
uidNumber: 1489000011
gidNumber: 1489000011
mepManagedEntry: cn=test_user,cn=groups,cn=accounts,dc=my-company,dc=com
memberOf: cn=ipausers,cn=groups,cn=accounts,dc=my-company,dc=com
memberOf: cn=developers,cn=groups,cn=accounts,dc=my-company,dc=com
memberOf: ipaUniqueID=xxxxxxxxx-f3db-11e5-8567-0242ac110003,cn=hbac,dc=my-company,dc=com
```

**Comment by frol** [comment]
BTW, changing `api.auth.ldap.openldap.user.member.attribute` to `memberOf` from API resulted in a "proper" environments mapping, but it is just a pure luck, because the search requests to our LDAP server are broken, here is one of them:

```
(&(memberOf=cn=developers,cn=groups,cn=accounts,dc=sparky,dc=salford-systems,dc=com)(objectClass=groupofnames))
```

Thus, it is a miracle that the environments mapping is working somehow!

**Comment by frol** [comment]
The second chunk of code mentioned by the topic starter:

```java
if (user != null && StringUtils.isNotBlank(user.getLogin())){
    String query = "(&(" + getConstantsConfig().getGroupMemberMappingAttribute()
            + '=' + user.getLogin()
            + ")(" + getConstantsConfig().objectClass() + '='
            + getConstantsConfig().getGroupObjectClass() + "))";
    identities.addAll(resultsToIdentities(searchLdap(query)));
}
```

results in the following request sent to the LDAP server:

```
(&(gidNumber=ipaUniqueID=xxxxxxxxx-f3db-11e5-8567-0242ac110003,cn=hbac,dc=my-company,dc=com)(objectClass=groupofnames))
```

Again, just for your reference, here how my group record looks like in LDAP:

```yaml
# developers, groups, accounts, my-company.com
dn: cn=developers,cn=groups,cn=accounts,dc=my-company,dc=com
objectClass: ipaobject
objectClass: top
objectClass: ipausergroup
objectClass: posixgroup
objectClass: groupofnames
objectClass: nestedgroup
cn: developers
ipaUniqueID: xxxxxxxx-f3d9-11e5-9e56-0242ac110003
gidNumber: 1489000018
memberOf: ipaUniqueID=xxxxxxxx-f3db-11e5-8567-0242ac110003,cn=hbac,dc=my-company,dc=com
member: uid=frol,cn=users,cn=accounts,dc=my-company,dc=com
member: uid=test_user,cn=users,cn=accounts,dc=my-company,dc=com
```
