### ISSUE TITLE
[BUG] cattle agent panic: "invalid memory address or nil pointer dereference" with ingress using resource backends

### ISSUE THREAD

**Issue by WintonHuang1893** [rancher/rancher#38782]
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm Chart
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.10
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): GKE

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
cattle-cluster-agent pods CrashLoopBackOff and restarts in downstream clusters, when there is an ingress using resource backends as its backends instead of service backends.
https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

Error logs:
```
  | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2f85a2b]
  | goroutine 4927 [running]:
  | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
  | /go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0x109
  | panic(0x3ccd600, 0x6eb69c0)
  | /usr/local/go/src/runtime/panic.go:965 +0x1b9
  | github.com/rancher/rancher/pkg/controllers/managementagent/endpoints.convertIngressToServicePublicEndpointsMap(0x4d318f0, 0xc0077c4f00, 0x0, 0xc000074026, 0x5, 0x1)
  | /go/src/github.com/rancher/rancher/pkg/controllers/managementagent/endpoints/endpoints.go:312 +0x6cb
  | github.com/rancher/rancher/pkg/controllers/managementagent/endpoints.(*WorkloadEndpointsController).UpdateEndpoints(0xc00a0fb340, 0xc00ab3ff98, 0x13, 0xc00620a820, 0x3a919a0, 0xc00456fed0)
  | /go/src/github.com/rancher/rancher/pkg/controllers/managementagent/endpoints/workload_endpoints.go:89 +0x674
  | github.com/rancher/rancher/pkg/controllers/managementagent/workload.(*CommonController).syncStatefulSet(0xc004162690, 0xc00ab3ff98, 0x13, 0xc00b500000, 0x10, 0x7fb18bbfe5b8, 0x10, 0xc00456fea0)
--
/go/src/github.com/rancher/rancher/pkg/controllers/managementagent/workload/workload_common.go:179 +0x1a4
```

**To Reproduce**
Add  an ingress using resource backends as its backends:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
  labels:
    app: hologram-workflow
  name: hologram-workflow
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: k8s.example.com
    http:
      paths:
      - backend:
          resource:
            apiGroup: k8s.example.com
            kind: Pod
            name: hologram-workflow-0
        path: /
        pathType: ImplementationSpecific
```

**Result**
cattle-cluster-agent pods CrashLoopBackOff and restarts 

**Expected Result**
cattle-cluster-agent runs normally.

**Screenshots**

**Additional context**
There is a nil pointer that agent cannot get `path.Backend.Service.Name` when the ingress uses resource backends
https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/managementagent/endpoints/endpoints.go#L312
