### ISSUE TITLE
[BUG] Exposing Rancher Monitoring Grafana via ingress on a subpath has some broken URLs

### ISSUE THREAD

**Issue by garrmark** [rancher/rancher#38797]
**Rancher Server Setup**
- Rancher version: 2.6.7
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: RKE1

**Information about the Cluster**
- Kubernetes version: v1.21.12
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? Custom RKE

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
I am exposing Grafana outside of Rancher via the helm config changes in the grafana chart documented here https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3/charts/grafana#example-ingress-with-path

Most things work properly, but the navigation menu on the side, for example Dashboards->Manage are using an incorrect URL with the subpath doubled up

I get the URL [https://monitoring.example.com/grafana/**grafana**/dashboards](https://monitoring.example.com/grafana/grafana/dashboards)

**To Reproduce**
Use these settings in the rancher-monitoring chart:
```yaml
grafana.ini:
  server:
    domain: monitoring.example.com
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
ingress:
  enabled: true
  hosts:
    - "monitoring.example.com"
  path: "/grafana"
```
Go to Dashboards->Manage

**Result**
Page not found 404 error

**Expected Result**
the page at https://monitoring.example.com/grafana/dashboards should come up

**Screenshots**
![image](https://user-images.githubusercontent.com/2669864/187997823-d8312b36-76de-462f-ba84-4dcba7dc4f98.png)

**Additional context**
I see this, which describes the problem and that it may have been worked on, but no solution 
https://stackoverflow.com/questions/66666230/why-does-grafana-double-the-sub-page-within-the-url-on-certain-links
