### ISSUE TITLE
When Amazon EC2 instance is stopped/started (from AWS console) the public ipaddress of the host changes and is not detected by the network agent. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#388]
Version - V0.14.1
Steps to reproduce the problem:

Add amazon host.
Create a container on this host and export port 8080.

F0rom Amazon EC2 Dashboard , stop and start the host instance.
This results in a different public ip address being assigned the host.

This results in Network Agent on this host being restarted.
I don't see the ipaddress  of the host being updated on the rancher server.

**Comment by kurtaschliman** [comment]
Has there been any progress on this issue? I'm seeing it currently in my testing of Rancher Server and AWS. It seems as though there should be a way to allocate and set an elastic ip address when launching an AWS EC2 instance in order to keep the IP from changing when the instance is shut down and started back up (which results in the public IP change when no elastic IP is assigned)

**Comment by sangeethah** [comment]
Also wanted to note that in this case after the host has gotten to "Active" state , we are not able to ping containers in different host.

To recover from this state, we need to run the rancher-agent command again by passing " -e CATTLE_AGENT_IP=" with the new ipaddress.

**Comment by deniseschannon** [comment]
Confirmed the workaround works and it's documented: http://docs.rancher.com/rancher/faqs/troubleshooting/#what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot

Leaving it open for when we could fix it without the need of the workaround.

**Comment by getapp** [comment]
I'd like to share our workaround. We created a service (using official workaround) that we can run on all EC2 hosts to update IPs.

```
update-host-ip:
  log_driver: ''
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  log_opt: {}
  image: getapp/rancher-reset-host-ip
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
```
