### ISSUE TITLE
[RFE] Add securityContext option to cattle-cluster-agent and fleet-agent

### ISSUE THREAD

**Issue by iMikeG6** [rancher/rancher#38805]
**Is your feature request related to a problem? Please describe.**

When deploying rancher on a restricted cluster the cannot run pods as root, rancher cattle-cluster-agent does not run.
It would be great to be able to run the cattle-cluster-agent as well as fleet-agent in non root mode with securityContext as described below.

Also, on the cattle-cluster-agent, some folders require permissions so as a workaround, I had to add new mountPath along with emptyDir volumes as shown in the below patch:

```
spec:
    volumes:
      - name: kubernetesetc
        emptyDir: {}
      - name: dockeretc
        emptyDir: {}
      - name: rancherhelm
        emptyDir: {}
      - name: rancherstate
        emptyDir: {}
    containers:
        volumeMounts:
          - name: kubernetesetc
            mountPath: /etc/kubernetes
          - name: dockeretc
            mountPath: /etc/docker
          - name: rancherhelm
            mountPath: /var/lib/rancher-data/local-catalogs
          - name: rancherstate
            mountPath: /var/lib/rancher/management-state
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
```

Though, this workaround solve running the agent as non root, when trying to execute shell or install helm charts using rancher on this cluster, it's not working cause rancher apply job or pod without securityContext.

**Describe the solution you'd like**
Add securityContext to cattle-cluster-agent, fleet-agent, shell

```
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
```
