### ISSUE TITLE
Value of label io.rancher.scheduler.global is not properly evaluated

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3881]
Rancher Version:
v0.59.1
Docker Version:
1.9.1
OS: 
Ubuntu 14.04-64bit

Steps to Reproduce: 

```YAML
hello-world:
  image: hello-world
  tty: true
  stdin_open: true
  labels:
    io.rancher.scheduler.global: 'false'
    io.rancher.container.start_once: 'true'
```

> $ rancher-compose -p test up

Results: 

A global service is created and containers are started on every host

Expected:

A single container should have been started

**Comment by vincent99** [comment]
The only defined value for this and similar labels is `true`.. If you don't want then don't include the label.

**Comment by vincent99** [comment]
I don't think this is a great idea.. These have a value just because they have to have one in a map, but various other code like the UI look at it without considering the value.

**Comment by janeczku** [comment]
> These have a value just because they have to have one in a map

Looking at the current code state this doesn't seem to be the general consensus as in some parts it is actually expected that the label has a value of `true`.

> but various other code like the UI look at it without considering the value

Doesn't the UI pull the value from Cattle? 

>  If you don't want then don't include the label

Generally i agree with you, but this is not feasible in the following case:

Rancher catalog template:

```YAML
    - variable: "global_service"
      label: "Deploy as global service"
      type: "boolean"
      default: false
```

docker-compose.yml

```YAML
  labels:
    io.rancher.scheduler.global: "${global_service}"
```
