### ISSUE TITLE
[BUG] Question about AlertManagerConfig resource usage and Cluster Alerting

### ISSUE THREAD

**Issue by Shiftmaj** [rancher/rancher#38818]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 cluster

- Proxy/Cert Details: Private CA

**Information about the Cluster**
- Kubernetes version: v1.23.7+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  vSphere provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions: 

**Describe the bug**

![image](https://user-images.githubusercontent.com/37184320/188669758-d8846a6a-f3d8-4762-8e4a-6fe941dce999.png)
`AlertManagerConfig` resource is namespaced. 

The resulting config matches alerts from namespace where the resource is created.

How are we supposed to manage project alerting and cluster alerting within `AlertmanagerConfig` resources.

**Result**
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alerts-to-teams
  namespace: cattle-monitoring-system
spec:
  receivers:
  - name: monitoring-Teams
    webhookConfigs:
    - httpConfig:
        tlsConfig: {}
      sendResolved: false
      url: http://rancher-alerting-drivers-prom2teams.cattle-monitoring-system.svc:8089/v2/connector
  route:
    groupBy: []
    groupInterval: 5m
    groupWait: 30s
    matchers: []
    receiver: monitoring-Teams
    repeatInterval: 4h
```
This config results in the following `alertmanager.yaml`:
```
route:
  receiver: "null"
  group_by:
  - job
  continue: false
  routes:
  - receiver: cattle-monitoring-system-alerts-to-teams-monitoring-Teams
    match:
      namespace: cattle-monitoring-system
    continue: true
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
  - receiver: "null"
    match:
      alertname: Watchdog
    continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
  - receiver: teams
    match_re:
      alertname: .*
    continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
```

**Expected Result**

A way to manage cluster alerting, i.e. not matching any namespace in the generated config.

**Screenshots**

![image](https://user-images.githubusercontent.com/37184320/188669758-d8846a6a-f3d8-4762-8e4a-6fe941dce999.png)
