### ISSUE TITLE
[Backport v2.6] [BUG] Upgrading Kubernetes Version does not retain RKE User Addons

### ISSUE THREAD

**Issue by rancherbot** [rancher/rancher#38877]
This is a backport issue for https://github.com/rancher/rancher/issues/38703, automatically created via rancherbot by @kinarashah

Original issue description:

**Rancher Server Setup**
- Rancher version: v2.6.2

**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE

**Describe the bug**

When upgrading Kubernetes Version for Rancher provisioned clusters, the RKE User Addons job is not replaced, which means that addons will not be retained if overwritten by RKE's other jobs.

**To Reproduce**

- Provision an RKE1 cluster
- Add the following under `rancher_kubernetes_engine_config`:
```
ing under rancher_kubernetes_engine_config:
addons: |-
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            prometheus :9153
            forward . "/etc/resolv.conf"
            cache 30
            loop
            reload
            loadbalance
        }
```
- After deployment, verify coredns config map has the corefile as intended
- Edit cluster and upgrade the Kubernetes version
- Look at the CoreDNS config map and see it has returned to default

**Result**
Logs from upgrading indicates rke-user-addon job was not executed after upgrading

```
2021/10/14 20:34:35 [INFO] cluster [c-dnrn6] provisioning: [addons] Successfully saved ConfigMap for addon rke-user-addon to Kubernetes
2021/10/14 20:34:35 [INFO] cluster [c-dnrn6] provisioning: [addons] Executing deploy job rke-user-addon
2021/10/14 20:34:35 [DEBUG] [k8s] Job rke-user-addon-deploy-job already exists..
2021/10/14 20:34:35 [INFO] cluster [c-dnrn6] provisioning: [addons] User addons deployed successfully
```

But the CoreDNS job was replaced, which replaced the configmap with the default:

```
2021/10/14 20:34:23 [INFO] cluster [c-dnrn6] provisioning: [addons] Successfully saved ConfigMap for addon rke-coredns-addon to Kubernetes
2021/10/14 20:34:23 [INFO] cluster [c-dnrn6] provisioning: [addons] Executing deploy job rke-coredns-addon
2021/10/14 20:34:23 [DEBUG] [k8s] replacing job rke-coredns-addon-deploy-job..
2021/10/14 20:34:29 [DEBUG] [k8s] waiting for job rke-coredns-addon-deploy-job to complete..
```

**Expected Result**

`rke-user-addons` job is replaced similar to the rke-coredns-addon job, or the ability to configure a corefile to replace default that can be retained between upgrades. It seems reasonable to run the user addon job again on upgrade because the system job runs and changes what the user addon changed. The reason that it does not run in this case is because nothing has changed in the addon; Rancher believes it not necessary to re-run the job because it was already run successfully once.

**Screenshots**

**Additional context**

SURE-3508

**Comment by kinarashah** [comment]
# QA Template

## What was fixed, or what changes have occurred
User addon reconciliation logic was modified, addons aren't deleted anymore. we let kubectl apply -f reconcile the updates and retain user config changes. 
 
## Areas or cases that should be tested

**Fresh Install Rancher v2.6-head**
--- 

Create a downstream cluster with k8s 1.22.x or 1.23.x and addon field defined per https://docs.ranchermanager.rancher.io/v2.0-v2.4/reference-guides/rancher-security/rancher-v2.4-hardening-guides/hardening-guide-with-cis-v1.5-benchmark#reference-hardened-rke-template-configuration. Also include the coredns configmap mentioned in the issue description above. 

1. Addon changes are retained after upgrade 
- Edit cluster and change or add any field under addon config and save cluster. The changes should reflect as expected after cluster reconciliation goes through. For example, changing `lameduck 5s` to `lameduck 15s`

2. Upgrade cluster by changing k8s version 
- Make sure resources defined in the addon config don't get deleted during the upgrade. Could the check the duration of the resources after the upgrade to make sure they weren't created new. Since the addon config includes `cattle-system` namespace, the cluster upgrade will fail if addons get deleted - so the cluster upgrade should go through successfully. 

3. Default cluster reconciliation 
- Edit cluster and change any non-addon field under rke config. For example, change `addon_job_timeout`. Make sure the resources defined in the addon config don't get deleted or updated during the upgrade. Changes stay as is for the addon config. We only expect the user addon job to get recreated in this usecase but not the actual user addons. 

4. Delete addons 
- The addon config defined above initially is critical to cluster so deleting that would break the cluster. Download kubeconfig beforehand if ok with broken cluster or Edit cluster and update the addon config to something simple like a user configmap or namespace.
- Edit cluster and remove the addon field. Make sure all resources under addon field are removed. 

**Rancher upgrade from v2.6.8 to v2.6-head**
--- 

In Rancher v2.6.8, create a downstream cluster with k8s 1.22.x or 1.23.x and addon field defined in the issue description. Upgrade Rancher to v2.6-head and make sure the cluster doesn't auto upgrade. Also make sure the configmap defined in the addon config stays the same. Repeat Step 2 defined above. 

**RKE standalone v1.3.15-rc1**
--- 

Create a cluster with addon config defined in the issue description. Rerun `rke up` after cluster comes up successfully. We only expect the rke-user-addon job to get recreated, not the configmap itself.

**Comment by markusewalker** [comment]
**FRESH INSTALL RANCHER V2.6-HEAD TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Provision a downstream RKE1 node driver cluster to the second highest K8s version available.
     - While provisioning, edit the cluster's YAML and add the following underneath the `rancher_kubernetes_engine_config` block:
```
addons: |-
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            prometheus :9153
            forward . "/etc/resolv.conf"
            cache 30
            loop
            reload
            loadbalance
        }
```
     - Open the browser's developer tools and view the traffic before pressing `Create`. Once done, create the cluster and validate in the `rancherKubernetesEngineConfig` block that the above is present.
3. Validate that the cluster and nodes appear in a status of `Active` in Cluster Management and Cluster Explorer.
4. Edit the cluster's YAML and validate that the custom ConfigMap has the corefile as specified.
5. Navigate to Cluster Explorer > cluster > Workload > Storage > ConfigMaps.
6. View the `coredns` YAML and validate if the corefile is preserved.
7. Upgrade the cluster's K8s version while inspecting the network traffic in the browser's developer tools.
     - Validate once more in the `rancherKubernetesEngineConfig` block if the specified information is present.
8. Once upgraded, validate that the cluster and nodes remain in a state of `Active` in Cluster Management and Cluster Explorer.
9. Once more, edit the clusters YAML and validate if the custom ConfigMap still has the corefile specified.
10. Navigate back to Cluster Explorer > cluster > Workload > Storage > ConfigMaps.
11. Validate if the corefile is preserved in the `coredns`.
____
**RANCHER UPGRADE FROM V2.6.8 -> V2.6-HEAD TEST PLAN**
1.  Setup Rancher `v2.6.8`, create a standard user and login as that user.
2. Provision a downstream RKE1 node driver cluster with highest K8s v1.23.x version.
     - While provisioning, edit the cluster's YAML and add the following underneath he `rancher_kubernetes_engine_config` block:
```
addons: |-
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            prometheus :9153
            forward . "/etc/resolv.conf"
            cache 30
            loop
            reload
            loadbalance
        }
```
3. Validate that the cluster comes up as `Active` in Cluster Management and Cluster Explorer.
4. Edit the cluster's YAML and validate that the custom ConfigMap has the corefile as specified.
5. Navigate to Cluster Explorer > cluster > Workload > Storage > ConfigMaps.
6. View the `coredns` YAML and validate if the corefile is preserved.
7. Upgrade Rancher from `v2.6.8` to `v2.6-head` and validate that the provisioned cluster does not auto-upgrade the cluster's K8s version.
8. Edit the cluster's configuration and ensure the addons are still present.
9. Upgrade the the cluster's K8s version and ensure that this is successful.
10. Repeat steps 4-10.
____
**RKE STANDALONE TEST PLAN**
1. On a client machine, stand up the latest stable RKE version.
2. In the `cluster.yml`, add the addons defined in the earlier test plans.
3. Run `rke up --config cluster.yml` and ensure that the cluster comes up successfully.
4. Rerun the above `rke up` command and validate that only the `rke-user-addon` job gets recreated.

**Comment by kinarashah** [comment]
Available to test with v2.6-head, https://drone-publish.rancher.io/rancher/rancher/8300 is green

**Comment by markusewalker** [comment]
Validated that this has been addressed. Please see details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version:
     - Fresh install: `v2.6-head`
     - Upgrade: `v2.6.8` -> `v2.6-head`
- Browser: Chrome

**TEST RESULT**
**PASS**

**VERIFICATION STEPS**

Scenario 1 - Fresh install Rancher `v2.6-head`  - **PASS**
1. Setup Rancher, create a standard user and login as that user.
2. Provisioned a downstream RKE1 node driver cluster to the second highest K8s version available.
     - While provisioning, edited the cluster's YAML and add the following underneath the `rancher_kubernetes_engine_config` block:
```
addons: |-
---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: ingress-nginx
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: default-psp-role
      namespace: ingress-nginx
    rules:
    - apiGroups:
      - extensions
      resourceNames:
      - default-psp
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: default-psp-rolebinding
      namespace: ingress-nginx
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: default-psp-role
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:authenticated
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cattle-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: default-psp-role
      namespace: cattle-system
    rules:
    - apiGroups:
      - extensions
      resourceNames:
      - default-psp
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: default-psp-rolebinding
      namespace: cattle-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: default-psp-role
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:authenticated
    ---
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: restricted
    spec:
      requiredDropCapabilities:
      - NET_RAW
      privileged: false
      allowPrivilegeEscalation: false
      defaultAllowPrivilegeEscalation: false
      fsGroup:
        rule: RunAsAny
      runAsUser:
        rule: MustRunAsNonRoot
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        rule: RunAsAny
      volumes:
      - emptyDir
      - secret
      - persistentVolumeClaim
      - downwardAPI
      - configMap
      - projected
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: psp:restricted
    rules:
    - apiGroups:
      - extensions
      resourceNames:
      - restricted
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: psp:restricted
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: psp:restricted
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:authenticated
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: tiller
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: tiller
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: tiller
      namespace: kube-system    
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            prometheus :9153
            forward . "/etc/resolv.conf"
            cache 30
            loop
            reload
            loadbalance
        }
```
3. Validated that the cluster and nodes appear in a status of `Active` in Cluster Management and Cluster Explorer.
4. Edited the cluster's YAML and validate that the addons have been preserved.
5. Navigated to Cluster Explorer > cluster > Storage > ConfigMaps.
6. Viewed the `coredns` YAML and validated that the corefile is preserved:
![image](https://user-images.githubusercontent.com/52591819/189994324-399aed2f-29e9-4ade-9071-0ea63c19c9a3.png) 
7. Upgrade the cluster's K8s version while inspecting the network traffic in the browser's developer tools.
     - Validated once more in the `rancherKubernetesEngineConfig` block if the specified information is present.
8. Validated that the cluster and nodes remain in a state of `Active` in Cluster Management and Cluster Explorer.
9. Once more, edited the clusters YAML and validated that the custom ConfigMap still has the corefile specified.
10. Navigated back to Cluster Explorer > cluster > Storage > ConfigMaps.
11. Validated that the corefile is preserved in the `coredns`.
_____
Scenario 2 - Upgrade Rancher from `v2.6.8` -> `v2.6-head` - **PASS**
1. Setup Rancher, create a standard user and login as that user.
2. Provisioned a downstream RKE1 node driver cluster to the second highest K8s version available.
     - While provisioning, edited the cluster's YAML and added scenario 1's addon.
3. Validated that the cluster and nodes appear in a state of `Active` in Cluster Management and Cluster Explorer.
4. Edited the cluster's YAML and validated that the user addons have been preserved.
5. Navigated to Cluster Explorer > cluster > Storage > ConfigMaps.
6. Validated that the corefile is preserved:
![image](https://user-images.githubusercontent.com/52591819/189994255-175886eb-1ede-4991-8c7d-56728d8a8241.png) 
7. Upgraded Rancher from `v2.6.8` to `v2.6-head`; validated that the cluster and nodes are still `Active` and that the K8s version did not auto-update.
8. Repeated steps 4-6; validation was successful at each step.
9. Upgraded the cluster's K8s version to `v1.24.4`; validated that the cluster and nodes appear in a state of `Active` in Cluster Management and Cluster Explorer.
10. Repeated steps 46; validation was successful at each step with the updated K8s version.
_____
Scenario 3 - Standalone RKE1 - **PASS**
1. On a client machine, setup RKE version `v1.3.15-rc1`.
2. In the `cluster.yml`, added the addons defined in scenarios 1 and 2.
3. Ran `rke up --config cluster.yml` and validated that the cluster came up successfully:
```
$ kubectl get nodes
NAME       STATUS   ROLES                      AGE     VERSION
mew-rke1   Ready    controlplane,etcd,worker   2m44s   v1.24.4
mew-rke2   Ready    controlplane,etcd,worker   2m44s   v1.24.4
mew-rke3   Ready    controlplane,etcd,worker   2m43s   v1.24.4
$ kubectl get pods -A
NAMESPACE       NAME                                       READY   STATUS      RESTARTS   AGE
ingress-nginx   ingress-nginx-admission-create-ht62t       0/1     Completed   0          2m11s
ingress-nginx   ingress-nginx-admission-patch-lwkgz        0/1     Completed   1          2m11s
ingress-nginx   nginx-ingress-controller-gzmtp             1/1     Running     0          2m11s
ingress-nginx   nginx-ingress-controller-k8mmq             1/1     Running     0          2m11s
ingress-nginx   nginx-ingress-controller-ncn4t             1/1     Running     0          2m11s
kube-system     calico-kube-controllers-74df54cbb7-zdx8v   1/1     Running     0          2m40s
kube-system     canal-tnlz9                                2/2     Running     0          2m41s
kube-system     canal-wnmq9                                2/2     Running     0          2m41s
kube-system     canal-z45tm                                2/2     Running     0          2m41s
kube-system     coredns-59499769fb-7d75l                   1/1     Running     0          2m31s
kube-system     coredns-59499769fb-mcj6k                   1/1     Running     0          2m30s
kube-system     coredns-autoscaler-67cbd4599c-lcn7b        1/1     Running     0          2m31s
kube-system     metrics-server-585b7cc746-zf9wt            1/1     Running     0          2m21s
kube-system     rke-coredns-addon-deploy-job-r6gsf         0/1     Completed   0          2m33s
kube-system     rke-ingress-controller-deploy-job-zct45    0/1     Completed   0          2m12s
kube-system     rke-metrics-addon-deploy-job-pnx5t         0/1     Completed   0          2m23s
kube-system     rke-network-plugin-deploy-job-qwfhl        0/1     Completed   0          2m43s
kube-system     rke-user-addon-deploy-job-stccc            0/1     Completed   0          2m2s
```
4. Re-edited the cluster.yml and validated that the addons remained.
5. Re-ran `rke up --config cluster.yml` with no changes; validated that the user addon was recreated:
```
$ kubectl get nodes
NAME       STATUS   ROLES                      AGE     VERSION
mew-rke1   Ready    controlplane,etcd,worker   4m41s   v1.24.4
mew-rke2   Ready    controlplane,etcd,worker   4m41s   v1.24.4
mew-rke3   Ready    controlplane,etcd,worker   4m40s   v1.24.4
$ kubectl get pods -A
NAMESPACE       NAME                                       READY   STATUS      RESTARTS   AGE
ingress-nginx   nginx-ingress-controller-gzmtp             1/1     Running     0          4m6s
ingress-nginx   nginx-ingress-controller-k8mmq             1/1     Running     0          4m6s
ingress-nginx   nginx-ingress-controller-ncn4t             1/1     Running     0          4m6s
kube-system     calico-kube-controllers-74df54cbb7-zdx8v   1/1     Running     0          4m35s
kube-system     canal-tnlz9                                2/2     Running     0          4m36s
kube-system     canal-wnmq9                                2/2     Running     0          4m36s
kube-system     canal-z45tm                                2/2     Running     0          4m36s
kube-system     coredns-59499769fb-7d75l                   1/1     Running     0          4m26s
kube-system     coredns-59499769fb-mcj6k                   1/1     Running     0          4m25s
kube-system     coredns-autoscaler-67cbd4599c-lcn7b        1/1     Running     0          4m26s
kube-system     metrics-server-585b7cc746-zf9wt            1/1     Running     0          4m16s
kube-system     rke-coredns-addon-deploy-job-r6gsf         0/1     Completed   0          4m28s
kube-system     rke-ingress-controller-deploy-job-zct45    0/1     Completed   0          4m7s
kube-system     rke-metrics-addon-deploy-job-pnx5t         0/1     Completed   0          4m18s
kube-system     rke-network-plugin-deploy-job-qwfhl        0/1     Completed   0          4m38s
kube-system     rke-user-addon-deploy-job-w28f9            0/1     Completed   0          47s
```
