### ISSUE TITLE
Restrict Access Between Containers

### ISSUE THREAD

**Issue by fbrbovic** [rancher/rancher#3895]
From what I understand about rancher all of the containers on rancher network can talk to each other on exposed ports. This makes it easy for simple systems and applications, but when you need to host more complicated setups which require services to live in separate zones and to be restricted from each other for security reasons,  it creates problems. 

Now there could be many possible solutions for this, some of it which require custom networking setups which would not work with default rancher network and automation. 

So I would propose that Rancher provides a native way to restrict access between apps, containers and services on the network. 

Here is one proposed solution:
**Add ability to firewall a stack using rancher-compose.yml.**
For example in rancher-compose we would configure something like this if we wanted to by default to block all of the access to services in the stack except from those allowed services and ports.

Examples:
_docker-compose.yml_

```
web:
  ports:
  - 80:80
  - 443:443:
  image: million12/nginx-php
mysql:
  ports:
  - 3306:3306/tcp
  image: mariadb:10.1.11
```

_rancher-compose.yml_

```
.firewall:
  default-access:  BLOCK
web:
  scale: 1
  firewall-allow-service: "lb:80"
mysql:
  scale: 1
```

Or we can even utilize the docker linking as a way to determine who should have access
_rancher-compose.yml_

```
.firewall:
  default-access:  BLOCK
  allow-linked: TRUE
web:
  scale: 1
mysql:
  scale: 1
```

so if we have a LB that links to the above web service it would allow it to be accessed
For example lets say we have some Load Balancer 
_docker-compose.yml:_

```
lb:
  ports:
  - 80:80
  - 443:80
  external_links:
  - somestack-website/web:web
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '443'
  image: rancher/load-balancer-service
```

What do you think of such proposal ?
