### ISSUE TITLE
[BUG]Rancher import of GKE autopilot cluster fails

### ISSUE THREAD

**Issue by YouthInThinking** [rancher/rancher#39052]
rancher gives error when importing GKE autopilot cluster:
`
Error from server ([denied by autogke-node-affinity-selector-limitation]): error when creating "https://aa.test.com/v3/import/fkg7fjzvbjpbxprgclnq5bwr8569nxcxrdqmfnv7l2nm86dk2wvpz8_c-m-dmmb2tz8.yaml": admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-node-affinity-selector-limitation]":["If not using workload separation, node affinity is not allowed on labels with keys: 'beta.kubernetes.io/os'; Autopilot only allows labels with keys: 'cloud.google.com/gke-spot,topology.kubernetes.io/region,topology.kubernetes.io/zone,failure-domain.beta.kubernetes.io/region,failure-domain.beta.kubernetes.io/zone,cloud.google.com/gke-os-distribution,kubernetes.io/os,kubernetes.io/arch'. Requested by user: 'kang@michaels.com', groups: 'system:authenticated'."]}
`

Rancher Version: 2.6.7

GKE autopilot cluster has a public address, so the network is open and there are no network problems, but it still reports the above error

if you can help me to solve this problem, I will be very grateful for the help of friends

**Comment by mjura** [comment]
During importing GKE Autopilot managed cluster, Rancher is trying to annotate all namespaces on GKE autopilot managed cluster, but there are some namespaces where Rancher don't have access to update them, due to lack of permissions.

Message from Rancher logs:

```
2024/01/24 18:32:01 [ERROR] error syncing 'c-rjhnq/p-lcqm5': handler project-namespace-auth: namespaces "kube-system" is forbidden: User "system:serviceaccount:cattle-system:kontainer-engine" cannot update resource "namespaces" in API group "" in the namespace "kube-system": GKE Warden authz [denied by managed-namespaces-limitation]: the namespace "kube-system" is managed and the request's verb "update" is denied, requeuing
```

Problem is that rancher-agent is trying to annotate `gke-gmp-system` with `field.cattle.io/projectId=c-rjhnq:p-86wcs` whcih can't do because of missing permissions. Namespace `gke-gmp-system` is managed by Autopilot.


Metadata section for `gke-gmp-system` namespace:

```
metadata:
  annotations:
    components.gke.io/component-name: managed-prometheus
    components.gke.io/component-version: 0.7.4-gke.2
    components.gke.io/layer: addon
  creationTimestamp: "2024-01-24T14:06:59Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/metadata.name: gke-gmp-system
  name: gke-gmp-system
```
