### ISSUE TITLE
[BUG] k3s cluster is in `updating` state when its controlplane is in `updating` state, but worker pool is in `error` state

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#39164]
**Rancher Server Setup**
- Rancher version: v2.7-head (c567ef3)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: v1.24.4+k3s1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested with node driver, aws and linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
tested with standard user, cluster owner
tested with admin

**Describe the bug**

when a cluster's only worker node is in `error` state, the cluster's status shows as `updating` if the controlplane node(s) are updating. The cluster is not accessible when it is in this error state and the user gets a 500 error

**To Reproduce**

* deploy a k3s cluster with dedicated nodes-per-role
* wait for the cluster to get to an active state
* edit the cluster.yaml and add the following to the `rkeConfig` section:
```
machineSelectorConfig:
    - config:
      kubelet-arg:
        - 'streaming-connection-idle-timeout=5m'
      flannel-conf: /tmp/fake.conf
      flannel-iface: eth0
      kube-proxy-arg: feature-gates=CSIMigrationAWS=false
      resolv-conf: /tmp/resolv.conf
```
* wait for the worker node to get to an `error` state (~5 minutes)

**Result**
though the node will intermittently get to an error state, it mostly stays in `updating` even though the only worker node is in `error` state.

**Expected Result**

I would expect a cluster to be in `error` state if it's node(s) are in an error state. Specifically if it has no access to any worker nodes

**Screenshots**

<img width="1031" alt="Screen Shot 2022-09-28 at 4 17 50 PM" src="https://user-images.githubusercontent.com/16691014/192906580-c8a78a19-f8ef-491d-a350-0488884837d8.png">

**Additional context**

related dashboard issue: https://github.com/rancher/dashboard/issues/7036
