### ISSUE TITLE
[Backport v2.6] [BUG] CIS scan failures on RKE2 hardened clusters

### ISSUE THREAD

**Issue by rancherbot** [rancher/rancher#39171]
This is a backport issue for https://github.com/rancher/rancher/issues/39170, automatically created via rancherbot by @rishabhmsra

Original issue description:

**Rancher Server Setup**
- Rancher version: v2.7-head(35388ea)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.24.4+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom RKE2 hardened cluster(1-cp, 1-etcd, 1-w)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- CIS scans using profiles `rke2-cis-1.23-profile-hardened` and `rke2-cis-1.23-profile-permissive` fails on RKE2 hardened clusters.

**To Reproduce**

- Provision a RKE2 hardened cluster. Followed this [guide](https://github.com/rancher/rancher/issues/36629#issuecomment-1100426864) to hardened the cluster.
- Install CIS benchmark chart `3.0.0-rc2` with below chart versions:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.10-rc2
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.9-rc3
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.56.7
```
- Ran scans using `rke2-cis-1.23-profile-hardened` and `rke2-cis-1.23-profile-permissive` profile.

**Result**
- Getting failures in both permissive and hardened scans:
![image](https://user-images.githubusercontent.com/36376154/193038143-24358a16-df11-4f12-8c01-62aef4a594a5.png)

![image](https://user-images.githubusercontent.com/36376154/193038156-9b7603c2-19fa-4f81-b340-8df0ac289ff2.png)

![image](https://user-images.githubusercontent.com/36376154/193038185-9390799c-2071-45b8-966e-8b26a652bc4a.png)

**Expected Result**

- Scan should pass for both hardened and permissive profile

**Additional context**

- https://github.com/rancher/security-scan/pull/94
