### ISSUE TITLE
[BUG] metrics from kubelets cadvisor are missing labels

### ISSUE THREAD

**Issue by BBQigniter** [rancher/rancher#39185]
On our lab-rancher setup (v2.6.8) with a Kubernetes RKE v1.24.4 cluster I observed today that metrics from kubelet's included cadvisor endpoint are missing labels.

The Kubernetes cluster runs with `enable_cri_dockerd: true` and has three nodes:

```
NAME     STATUS   ROLES                      AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
node-1   Ready    controlplane,etcd,worker   252d   v1.24.4   10.12.101.47   <none>        CentOS Linux 7 (Core)   5.19.5-1.el7.elrepo.x86_64   docker://20.10.17
node-2   Ready    controlplane,etcd,worker   252d   v1.24.4   10.12.101.48   <none>        CentOS Linux 7 (Core)   5.19.5-1.el7.elrepo.x86_64   docker://20.10.17
node-3   Ready    controlplane,etcd,worker   252d   v1.24.4   10.12.101.49   <none>        CentOS Linux 7 (Core)   5.19.5-1.el7.elrepo.x86_64   docker://20.10.17
```

So today I had a look at some Grafana dashboards and spotted that I could not see any pod's container metrics. After further looking into
the problem I figured out that the `container` labels for example in `container_memory_usage_bytes` are missing. So Prometheus queries like
`sum(container_memory_usage_bytes{namespace="$namespace", pod=~"$pod", container!="", container!="POD", container=~"$container"}) by (pod, container)` 
are not working anymore.

Googling around I stumbled upon following issues https://github.com/kubernetes/kubernetes/issues/89903 and https://github.com/kubernetes/kubernetes/issues/111077

So how can this be fixed for Rancher clusters?

**Comment by panis16** [comment]
Same problem here after RKE deploy with 1.24.4. Grafana’s dashboards are broken.

**Comment by pavel-khritonenko** [comment]
https://github.com/rancher/rancher/issues/38934 - the same issue, cadvisor in rancher deployment doesn't expose container metrics

**Comment by ItsReddi** [comment]
Example output from cadvisor
```
> kubectl get --raw /api/v1/nodes/sp-worker1/proxy/metrics/cadvisor|grep -i container_network
# HELP container_network_receive_bytes_total Cumulative count of bytes received
# TYPE container_network_receive_bytes_total counter
container_network_receive_bytes_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 2.7382759192e+10 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 2.7391326616e+10 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 2.63848781e+08 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 1.0360318772e+10 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 1.73172021942e+11 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 6.484393211e+09 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 5.38347469212e+11 1665555320087
container_network_receive_bytes_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 2.62944174022e+11 1665555320087
# HELP container_network_receive_errors_total Cumulative count of errors encountered while receiving
# TYPE container_network_receive_errors_total counter
container_network_receive_errors_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_errors_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 0 1665555320087
# HELP container_network_receive_packets_dropped_total Cumulative count of packets dropped while receiving
# TYPE container_network_receive_packets_dropped_total counter
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_dropped_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 0 1665555320087
# HELP container_network_receive_packets_total Cumulative count of packets received
# TYPE container_network_receive_packets_total counter
container_network_receive_packets_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 1.12974545e+08 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 1.12869733e+08 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 2.767534e+06 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 9.4014945e+07 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 2.20807411e+08 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 1.5599241e+07 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 1.160195987e+09 1665555320087
container_network_receive_packets_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 7.04645412e+08 1665555320087
# HELP container_network_transmit_bytes_total Cumulative count of bytes transmitted
# TYPE container_network_transmit_bytes_total counter
container_network_transmit_bytes_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 4.4389443975e+10 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 4.4372634585e+10 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 2.52283422e+08 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 1.9263076103e+10 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 1.5148089306e+11 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 2.1199909328e+10 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 446 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 3.95238254615e+11 1665555320087
container_network_transmit_bytes_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 1.95585258952e+11 1665555320087
# HELP container_network_transmit_errors_total Cumulative count of errors encountered while transmitting
# TYPE container_network_transmit_errors_total counter
container_network_transmit_errors_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_errors_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 0 1665555320087
# HELP container_network_transmit_packets_dropped_total Cumulative count of packets dropped while transmitting
# TYPE container_network_transmit_packets_dropped_total counter
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 0 1665555320087
container_network_transmit_packets_dropped_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 5 1665555320087
# HELP container_network_transmit_packets_total Cumulative count of packets transmitted
# TYPE container_network_transmit_packets_total counter
container_network_transmit_packets_total{container="",id="/",image="",interface="cali4b582af34b2",name="",namespace="",pod=""} 8.7684945e+07 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="cali5b356189d55",name="",namespace="",pod=""} 8.7560083e+07 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="cali5c76cea7293",name="",namespace="",pod=""} 2.838119e+06 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="cali8fe0f89ee8d",name="",namespace="",pod=""} 1.85677477e+08 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="cali9399a8b58c4",name="",namespace="",pod=""} 2.51034659e+08 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="calif83974f8c40",name="",namespace="",pod=""} 1.7146167e+07 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="calif8ece5a72ea",name="",namespace="",pod=""} 5 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="eth0",name="",namespace="",pod=""} 1.218668968e+09 1665555320087
container_network_transmit_packets_total{container="",id="/",image="",interface="flannel.1",name="",namespace="",pod=""} 7.58932678e+08 1665555320087
```

**Comment by AcidAngel21** [comment]
> Same problem here after RKE deploy with 1.24.4. Grafana’s dashboards are broken.

The same problem here after upgrade to 1.24.4. If there is currently no fix or workaround available, it should be documented in the Known Major Issues   section of RKE.

**Comment by js-max** [comment]
Hi, any update or workaround available?

**Comment by BBQigniter** [comment]
@js-max have a look at https://github.com/google/cadvisor/issues/3162 - as a workaround we setup cadvisor with the latest image as daemonset and changed the kubernetes-cadvisor job in prometheus to scrape the stuff from there

**Comment by ngadde** [comment]
For RKE environments for me its fix by configuring containerd path to : --containerd=/run/k3s/containerd/containerd.sock
after that configuration  its start showing metrics

**Comment by macrokernel** [comment]
> `--containerd=/run/k3s/containerd/containerd.sock`

Hi, where do you add this parameter to? Is it kubelet args? Can you please give some more detail?

**Comment by macrokernel** [comment]
I am still having this issue on a K3s cluster with 3 control nodes and 5 worker nodes. Confirmed with these versions:

- v1.32.9+k3s1
- v1.32.10+k3s1
- v1.33.6+k3s1

The cAdvisor work-around for containerd has been applied to all nodes:

```
--kubelet-arg="containerd=/run/k3s/containerd/containerd.sock"
```

While checking the output of

```
kubectl get --raw /api/v1/nodes/k3s-node-name/proxy/metrics/cadvisor | grep container_cpu_usage_seconds_total
```

In most of the records `container`  is empty, but in some records it has a value, see below:

```
container_cpu_usage_seconds_total{container="",cpu="total",id="/",image="",name="",namespace="",pod=""} 118448.591108 1766129163720
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice",image="",name="",namespace="",pod=""} 14909.913801 1766129163738
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice",image="",name="",namespace="",pod=""} 11345.040246 1766129170862
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0424a739_74d9_46f1_ba60_b5dcefb83545.slice",image="",name="",namespace="calico-system",pod="csi-node-driver-cw5mj"} 16.21603 1766129164949
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0424a739_74d9_46f1_ba60_b5dcefb83545.slice/cri-containerd-32659ab8e8795ce29e190f4c5288d3b0f1f1ab8431e8fcc7274f1b8ee9ed2cb9.scope",image="docker.io/rancher/mirrored-pause:3.6",name="32659ab8e8795ce29e190f4c5288d3b0f1f1ab8431e8fcc7274f1b8ee9ed2cb9",namespace="calico-system",pod="csi-node-driver-cw5mj"} 0.01129 1766129163472
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod14fd5130_8c6b_47d4_ac15_c9907578cc6a.slice",image="",name="",namespace="calico-system",pod="calico-node-j2p8q"} 8010.411972 1766129162883
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod14fd5130_8c6b_47d4_ac15_c9907578cc6a.slice/cri-containerd-7c1b497364afc1e6bbfb703da9b85ccc85bd46dfaad196e53abe153b5fe43cc7.scope",image="docker.io/rancher/mirrored-pause:3.6",name="7c1b497364afc1e6bbfb703da9b85ccc85bd46dfaad196e53abe153b5fe43cc7",namespace="calico-system",pod="calico-node-j2p8q"} 0.008947 1766129157405
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd2eeed88_c092_4ec1_8142_9a7347389ea9.slice",image="",name="",namespace="metallb-system",pod="speaker-4zxrz"} 2206.786458 1766129165534
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd2eeed88_c092_4ec1_8142_9a7347389ea9.slice/cri-containerd-9d503a2e2ab17b6eeb5d80d58faf5ff12b47e181f7d8b2be98526ab44dc3bde4.scope",image="docker.io/rancher/mirrored-pause:3.6",name="9d503a2e2ab17b6eeb5d80d58faf5ff12b47e181f7d8b2be98526ab44dc3bde4",namespace="metallb-system",pod="speaker-4zxrz"} 0.030873 1766129162942
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf2527246_51c0_4621_babb_994481a0f6e8.slice",image="",name="",namespace="monitoring",pod="vmks-prometheus-node-exporter-5wqft"} 114.275429 1766129164672
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf2527246_51c0_4621_babb_994481a0f6e8.slice/cri-containerd-630c35289c6f823642190694012932ba0fa817038533e7df304d376ea80830ff.scope",image="docker.io/rancher/mirrored-pause:3.6",name="630c35289c6f823642190694012932ba0fa817038533e7df304d376ea80830ff",namespace="monitoring",pod="vmks-prometheus-node-exporter-5wqft"} 0.034138 1766129157859
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podfe292ba1_4113_4102_8072_d2adf6910123.slice",image="",name="",namespace="kube-system",pod="kube-vip-ds-5mmtn"} 254.989046 1766129160744
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podfe292ba1_4113_4102_8072_d2adf6910123.slice/cri-containerd-1be5814406ab6f018d25c264bfcd502f757b74b9b2b7e1c0b9a8046196f4252b.scope",image="docker.io/rancher/mirrored-pause:3.6",name="1be5814406ab6f018d25c264bfcd502f757b74b9b2b7e1c0b9a8046196f4252b",namespace="kube-system",pod="kube-vip-ds-5mmtn"} 0.029134 1766129162733
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice",image="",name="",namespace="",pod=""} 3564.996831 1766129164797
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4e7e1197_5f62_4938_b4af_58ce3da0ae6e.slice",image="",name="",namespace="kube-system",pod="coredns-6d668d687-v4tf6"} 246.112615 1766129158696
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4e7e1197_5f62_4938_b4af_58ce3da0ae6e.slice/cri-containerd-e49122876f54d9ff442093367be127e77744be0c46557f9fbffe7d4d812c492b.scope",image="docker.io/rancher/mirrored-pause:3.6",name="e49122876f54d9ff442093367be127e77744be0c46557f9fbffe7d4d812c492b",namespace="kube-system",pod="coredns-6d668d687-v4tf6"} 0.03399 1766129158158
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda2fc3cbb_2db0_4954_9890_3dc51d74092c.slice",image="",name="",namespace="logging",pod="promtail-qmjtj"} 3318.777174 1766129155359
container_cpu_usage_seconds_total{container="",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda2fc3cbb_2db0_4954_9890_3dc51d74092c.slice/cri-containerd-a45aeeeb2fb0cc85ff346b965f103a97d27342d153a8a53447c380aabdbbc336.scope",image="docker.io/rancher/mirrored-pause:3.6",name="a45aeeeb2fb0cc85ff346b965f103a97d27342d153a8a53447c380aabdbbc336",namespace="logging",pod="promtail-qmjtj"} 0.031188 1766129164633
container_cpu_usage_seconds_total{container="",cpu="total",id="/system.slice/k3s.service",image="",name="",namespace="",pod=""} 116385.196844 1766129163493
container_cpu_usage_seconds_total{container="calico-csi",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0424a739_74d9_46f1_ba60_b5dcefb83545.slice/cri-containerd-7d924b29ef7dfeb7d40ca7a5c7ede6ff080fa22db6649b27e069ff2ab3ac91b2.scope",image="docker.io/calico/csi:v3.29.6",name="7d924b29ef7dfeb7d40ca7a5c7ede6ff080fa22db6649b27e069ff2ab3ac91b2",namespace="calico-system",pod="csi-node-driver-cw5mj"} 0.578437 1766129158671
container_cpu_usage_seconds_total{container="calico-node",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod14fd5130_8c6b_47d4_ac15_c9907578cc6a.slice/cri-containerd-03aebfbe74b79d6d7219f1a8ca8bbed16d2278ecb5208b400a8629ac1fe17475.scope",image="docker.io/calico/node:v3.29.6",name="03aebfbe74b79d6d7219f1a8ca8bbed16d2278ecb5208b400a8629ac1fe17475",namespace="calico-system",pod="calico-node-j2p8q"} 8009.70434 1766129163402
container_cpu_usage_seconds_total{container="coredns",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4e7e1197_5f62_4938_b4af_58ce3da0ae6e.slice/cri-containerd-0214b65abe6038af1a642ec443255e36a7468b6daad0fae0b808fa6d60414c65.scope",image="docker.io/rancher/mirrored-coredns-coredns:1.13.1",name="0214b65abe6038af1a642ec443255e36a7468b6daad0fae0b808fa6d60414c65",namespace="kube-system",pod="coredns-6d668d687-v4tf6"} 246.099875 1766129162384
container_cpu_usage_seconds_total{container="csi-node-driver-registrar",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod0424a739_74d9_46f1_ba60_b5dcefb83545.slice/cri-containerd-bc01146df1b9a21afa403fc62c6fcc5fea9bbae914baf469a0a0703d119c91a5.scope",image="docker.io/calico/node-driver-registrar:v3.29.6",name="bc01146df1b9a21afa403fc62c6fcc5fea9bbae914baf469a0a0703d119c91a5",namespace="calico-system",pod="csi-node-driver-cw5mj"} 15.626217 1766129159946
container_cpu_usage_seconds_total{container="kube-vip",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podfe292ba1_4113_4102_8072_d2adf6910123.slice/cri-containerd-432f1fdc02d69f0477ae614a44146c43f8c943f98e65422a341f3a46204717b4.scope",image="ghcr.io/kube-vip/kube-vip:v0.8.10",name="432f1fdc02d69f0477ae614a44146c43f8c943f98e65422a341f3a46204717b4",namespace="kube-system",pod="kube-vip-ds-5mmtn"} 13.336434 1766129169982
container_cpu_usage_seconds_total{container="node-exporter",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podf2527246_51c0_4621_babb_994481a0f6e8.slice/cri-containerd-f291d79eeb22a57e02d01adf317a8e448d0aac1327dd1c01bc975be29c81f799.scope",image="quay.io/prometheus/node-exporter:v1.10.2",name="f291d79eeb22a57e02d01adf317a8e448d0aac1327dd1c01bc975be29c81f799",namespace="monitoring",pod="vmks-prometheus-node-exporter-5wqft"} 114.241291 1766129168121
container_cpu_usage_seconds_total{container="promtail",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda2fc3cbb_2db0_4954_9890_3dc51d74092c.slice/cri-containerd-4dc2741451ee1f52726d3d0200724d41890bc62ec85dc0a14a93fe325bc610cb.scope",image="docker.io/grafana/promtail:3.5.1",name="4dc2741451ee1f52726d3d0200724d41890bc62ec85dc0a14a93fe325bc610cb",namespace="logging",pod="promtail-qmjtj"} 3318.854732 1766129168488
container_cpu_usage_seconds_total{container="speaker",cpu="total",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd2eeed88_c092_4ec1_8142_9a7347389ea9.slice/cri-containerd-8e95d620c30fd41ed02b8d94ccbc78c268af9db17f64c1383d7e16455a3f5950.scope",image="quay.io/metallb/speaker:v0.14.8",name="8e95d620c30fd41ed02b8d94ccbc78c268af9db17f64c1383d7e16455a3f5950",namespace="metallb-system",pod="speaker-4zxrz"} 2206.77462 1766129169000
```

From Grafana dashboards it looks like pods on k3s control nodes do have CPU and memory usage data, while pods on worker nodes don't have these data. Note 3 node-exporter pods in the screenshot below - these are running on control nodes. The other 5 (worker) nodes are also running node-exporter, but there is no CPU and RAM usage data for them.

<img width="3463" height="2098" alt="Image" src="https://github.com/user-attachments/assets/e3375d5f-d0e4-4bc6-ad41-940316dccff1" />

UPDATE:
Found out that it is something to do with VictoriaMetrics kubelet/cAdvisor metrics scrape or relabeling. Argo CD might also be involved. I solved the issue by creating a kubelet ServiceMonitor in exactly the same way Kube-prometheus-stack does it:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-kubelet
  namespace: monitoring
spec:
  attachMetadata:
    node: false
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: true
    metricRelabelings:
    - action: drop
      regex: (csi_operations|storage_operation_duration)_seconds_bucket;(0.25|2.5|15|25|120|600)(\.0)?
      sourceLabels:
      - __name__
      - le
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: true
    interval: 10s
    metricRelabelings:
    - action: drop
      regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_(mapped_file|swap)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_(file_descriptors|tasks_state|threads_max)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_failures_total;hierarchy
      sourceLabels:
      - __name__
      - scope
    - action: drop
      regex: container_network_.*;(cali|cilium|cni|lxc|nodelocaldns|tunl).*
      sourceLabels:
      - __name__
      - interface
    - action: drop
      regex: container_spec.*
      sourceLabels:
      - __name__
    - action: drop
      regex: .+;
      sourceLabels:
      - id
      - pod
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    trackTimestampsStaleness: true
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: true
    path: /metrics/probes
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
```
