### ISSUE TITLE
[BUG] unable to edit deployment rancher 2.6.8

### ISSUE THREAD

**Issue by ItsReddi** [rancher/rancher#39183]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart):
   - HA Helm RKE 1

**Information about the Cluster**
- Kubernetes version: v1.24.4
- Cluster Type (Local/Downstream):
Downstream RKE hetzner

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  admin

**Describe the bug**
If you create a deployment with more than one Container you are unable to edit the second pod after creating.

**To Reproduce**

1. Create deployment with 2 Containers
2. Save
3. Edit

**Result**
Now you are unable to switch between containers (for example, look at healthcheck port)
!None! of the Form value updates

**Expected Result**
Form values should all be switched to correct container.

**Additional context**
Example yaml... where an example health check port should switch between 80 & 8080 on edit.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-test
    spec:
      affinity: {}
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: container
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx
        imagePullPolicy: Always
        name: anothercontainer
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
