### ISSUE TITLE
[BUG] Rancher cannot import GKE Zonal Clusters

### ISSUE THREAD

**Issue by deltasquare4** [rancher/rancher#39231]
**Rancher Server Setup**
- Rancher version: `2.6.8`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `k3s`
- Proxy/Cert Details: `Cert Manager + Lets Encrypt`

**Information about the Cluster**
- Kubernetes version: `v1.23.8+k3s1`
- Cluster Type (Local/Downstream): `local`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**
When importing a zonal GKE cluster in Rancher, the respective Management Cluster instance (`management.cattle.io.cluster`) responds with the following error: `googleapi: Error 400: Must specify a field to update., badRequest`. Here's the `gkeConfig` in the `management.cattle.io.cluster` object:

```
  gkeConfig:
    clusterAddons: null
    clusterIpv4Cidr: null
    clusterName: xxxxxx-secondary-1
    description: ""
    enableKubernetesAlpha: null
    googleCredentialSecret: cattle-global-data:cc-xxxxxx
    imported: true
    kubernetesVersion: null
    labels: null
    locations: null
    loggingService: null
    monitoringService: null
    nodePools: null
    projectID: xxxxxxxxxx
    region: ""
    zone: us-east1-b
```
![2022-10-05_12-26](https://user-images.githubusercontent.com/205111/193999353-850e199e-2640-47d5-abfc-15f971bd89f2.png)

**To Reproduce**
1. Import a zonal GKE cluster on a Rancher instance.

**Result**
1. The imported cluster gets stuck in `Updating` state with its management cluster having the error described above.

**Expected Result**
Cluster should be imported successfully just like how regional clusters do.

**Screenshots**
Attached above.

**Additional context**
I believe this could be because the `region` field in `gkeConfig` is empty.
