### ISSUE TITLE
[rancher-compose] random panic on rm -f a b followed by up a b

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#3927]
Rancher Version:
0.59.1
Rancher Compose Version:
0.7.2
Docker Version: (rancher server)
1.10.2
OS: (rancher server)
Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016

Steps to Reproduce:
This happened to me once while prototyping setup (creating and destroying services in same stack using UI and CLI a lot). It is probably race/timing issue because it happened to me only once so far.
Sidekick is commented out by mistake but was that way before and after the panic.
192.168.99.1:6000 is a container running registry:2.2 with filesystem backend (running on my host not in VM).

docker-compose.yml

``` yml
loadbalancer:
    ports:
        - 5432:9999/tcp
    labels:
        io.rancher.scheduler.global: 'true'
    links:
        - pool
    tty: true
    image: rancher/load-balancer-service
    stdin_open: true

pool:
    image: 192.168.99.1:6000/pgpool/pool
    ports:
        - '9999:9999'
    links:
        - database
    volumes-from:
        - pool-confd
    labels:
        io.rancher.sidekicks: pool-confd
        io.rancher.container.pull_image: always
        # do not deploy to same host
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

pool-confd:
    image: 192.168.99.1:6000/pgpool/pool-confd
    environment:
    labels:
        io.rancher.container.start_once: 'true'

database:
    image: 192.168.99.1:6000/pgpool/postgres
    ports:
        - '5000:5432'
    volumes-from:
        - database-data
    labels:
        io.rancher.sidekicks: database-data #, database-pool
        io.rancher.container.pull_image: always
        # do not deploy to same host
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

database-data:
    image: sheldonh/dvc
    command: /var/lib/postgresql:755:999:999
    volumes:
        - /var/lib/postgresql
    labels:
        io.rancher.container.start_once: 'true'
```

rancher-compose.yml

``` yml
pool:
    retain_ip: true
    scale: 3

database:
    retain_ip: true
    scale: 1
```

``` sh
# setup credentials
rancher-compose rm -f pool pool-confd
rancher-compose up pool pool-confd
```

Results: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5404da]

goroutine 23 [running]:
github.com/rancher/rancher-compose/rancher.(*RancherService).containers(0xc208249f20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:488 +0x21a
github.com/rancher/rancher-compose/rancher.(*RancherService).Log(0xc208249f20, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:527 +0x10d
created by github.com/rancher/rancher-compose/rancher.func·001
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:98 +0x4e

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc2080511a0)
    /usr/src/go/src/sync/waitgroup.go:132 +0x169
github.com/docker/libcompose/project.(*serviceWrapper).Wait(0xc208051180, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/service-wrapper.go:112 +0x46
github.com/docker/libcompose/project.(*Project).traverse(0xc208060380, 0xc20833a601, 0xc20833a6f0, 0xc20833a720, 0xbcbb68, 0xbcbb70, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:354 +0x6e2
github.com/docker/libcompose/project.(*Project).forEach(0xc208060380, 0xc20800a020, 0x2, 0x2, 0xbcbb68, 0xbcbb70, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:268 +0x1a6
github.com/docker/libcompose/project.(*Project).perform(0xc208060380, 0x1b, 0x1c, 0xc20800a020, 0x2, 0x2, 0xbcbb68, 0xbcbb70, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:250 +0xb0
github.com/docker/libcompose/project.(*Project).Up(0xc208060380, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:208 +0x85
github.com/rancher/rancher-compose/app.ProjectUp(0xc208060380, 0xc2080ba0c0)
    /source/gopath/src/github.com/rancher/rancher-compose/app/app.go:208 +0x192
github.com/docker/libcompose/cli/app.func·001(0xc2080ba0c0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/cli/app/app.go:40 +0x160
github.com/codegangsta/cli.Command.Run(0xa67fa0, 0x2, 0x0, 0x0, 0xaa2150, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
    /source/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc208036f70, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.cliMain()
    /source/main.go:85 +0x1054
main.main()
    /source/main.go:27 +0x95

goroutine 5 [syscall]:
os/signal.loop()
    /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/rancher/go-machine-service/locks.locker()
    /source/Godeps/_workspace/src/github.com/rancher/go-machine-service/locks/locks.go:61 +0x6c
created by github.com/rancher/go-machine-service/locks.init·1
    /source/Godeps/_workspace/src/github.com/rancher/go-machine-service/locks/locks.go:7 +0x5c

goroutine 7 [chan send]:
github.com/docker/libcompose/cli/logger.generateColors()
    /source/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:27 +0x191
created by github.com/docker/libcompose/cli/logger.init·1
    /source/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:33 +0x25

goroutine 8 [chan receive]:
github.com/docker/libcompose/project.(*defaultListener).start(0xc2080b4980)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/listener.go:47 +0x8e
created by github.com/docker/libcompose/project.NewDefaultListener
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/listener.go:42 +0xa6

goroutine 22 [sleep]:
github.com/rancher/rancher-compose/rancher.(*RancherService).WaitFor(0xc208249ea0, 0xc208053800, 0x839380, 0xc208053800, 0xc208367cc0, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/wait.go:15 +0x98
github.com/rancher/rancher-compose/rancher.(*RancherService).Wait(0xc208249ea0, 0xc208053800, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/wait.go:27 +0x8c
github.com/rancher/rancher-compose/rancher.(*RancherService).createService(0xc208249ea0, 0xc208089200, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:310 +0x335
github.com/rancher/rancher-compose/rancher.(*RancherService).up(0xc208249ea0, 0xc208089201, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:134 +0x351
github.com/rancher/rancher-compose/rancher.(*RancherService).Up(0xc208249ea0, 0x0, 0x0)
    /source/gopath/src/github.com/rancher/rancher-compose/rancher/service.go:86 +0x3f
github.com/docker/libcompose/project.func·012(0x7fdc2c933428, 0xc208249ea0, 0x0, 0x0)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:204 +0x43
github.com/docker/libcompose/project.(*serviceWrapper).Do(0xc208051180, 0xc20833a720, 0x4, 0x6, 0xbcbb60)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/service-wrapper.go:100 +0x1e9
github.com/docker/libcompose/project.func·013(0xc208051180, 0xc20833a720)
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:205 +0x50
created by github.com/docker/libcompose/project.(*Project).startService
    /source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:314 +0x5bb

goroutine 14 [runnable]:
net/http.(*persistConn).readLoop(0xc208072370)
    /usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
    /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc208072370)
    /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/src/go/src/net/http/transport.go:661 +0xcbc

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc208080300, 0x72, 0x0, 0x0)
    /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208080300, 0x0, 0x0)
    /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080802a0, 0xc208313000, 0x1000, 0x1000, 0x0, 0x7fdc2c928078, 0xc2080dc4d0)
    /usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e5a0, 0xc208313000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/src/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fdc2c92d360, 0xc20802e5a0, 0xc208303028, 0xc208313000, 0x1000, 0x1000, 0x8ea6e0, 0x0, 0x0)
    /usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2082674e0, 0xc208313000, 0x1000, 0x1000, 0xc208014000, 0x0, 0x0)
    <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20807e5a0)
    /usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20807e5a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208302fd0)
    /usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
    /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc208302fd0)
    /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /usr/src/go/src/net/http/transport.go:661 +0xcbc
```

Expected:
Output of logs from services pool and pool-confd.
