### ISSUE TITLE
[BUG] Groups are not synced in via OpenLDAP

### ISSUE THREAD

**Issue by bjd2385** [rancher/rancher#39287]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: Sectigo RSA Domain Validation Secure Server CA
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
  - 
**Describe the bug**

Groups aren't showing up in the UI under 

> Users & Authentication > Groups

despite syncing groups with OpenLDAP. The data appears to be there though when we navigate to 

> Explore Cluster > Local > More Resources > Rancher > User Attributes > click on your local user ID

For example, I'm a member of the `Development` group in our ldap, and it shows up at the latter location - 
```
GroupPrincipals:
...
  openldap:
    Items:
    - displayName: Development
      loginName: Development
      me: true
      metadata:
        creationTimestamp: null
        name: openldap_group://cn=Development,ou=groups,dc=<our-dc-name>,dc=com
      principalType: group
      provider: openldap
```
so the group shows up here, but clicking refresh, etc. on the Groups tab does not show any groups.

**To Reproduce**

I'm not sure I have a minimal example, I will give it a try, however.

**Result**

Groups do not sync.

**Expected Result**

Groups to sync.
