### ISSUE TITLE
`json unmarshall error` when using external_link to a service that was scheduled on a specific host

### ISSUE THREAD

**Issue by prelegalwonder** [rancher/rancher#3929]
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: Ubuntu 14.04.4 LTS 

Steps to Reproduce: 
1. create an applications stack with a service 
(eg. Stack called Data, service is consul )
2. create a new stack with a container that references an external_link that exists in the first "Data" stack that is of type "service".
eg. 
```yaml
my-portal:
    restart: always
    tty: TRUE
    image: some.registry.com:5000/dev/myportal:v2
    expose:
     - "8443"
    external_links:
        - Data/consul:consul
    environment:
        NODE_ENV: "staging"
        MY_BRANCH: "master"
```
Results: 
```
level=error msg="Failed Creating portal : json: cannot unmarshal number into Go value of type string"
level=error msg="Stack Create Event Failed: json: cannot unmarshal number into Go value of type string" eventId=27b40da6-04b6-4271-911c-cb7fbf1a3fb1 resourceId=1e44
level=info msg="[bugtest:]: Project created " eventId=27b40da6-04b6-4271-911c-cb7fbf1a3fb1 resourceId=1e44 
```
Service never gets activated and hangs indefinitely because external_link doesn't get created. 

Expected:
Service gets activated and has access to external_link reference. 

Notes: If the external_link is of type "External" instead of "Service", there is no issue.
