### ISSUE TITLE
[RFE] Rancher CRDs should support descriptions

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#39335]
Controller frameworks like kubebuilder support adding descriptions for CRDs and their fields from within the Go type definition.

[kubernetes-sigs/security-profiles-operator](https://github.com/kubernetes-sigs/security-profiles-operator/) is an operator created with kubebuilder. Using it as an example, we can see that the [godoc comments](https://github.com/kubernetes-sigs/security-profiles-operator/blob/c29644e6702f65e54e67de663f223ed1de66d690/api/seccompprofile/v1beta1/seccompprofile_types.go#L60-L64) for types and fields become the [descriptions](https://github.com/kubernetes-sigs/security-profiles-operator/blob/c29644e6702f65e54e67de663f223ed1de66d690/deploy/base-crds/crds/seccompprofile.yaml#L111-L116) in the generated CRD YAMLs:

```
type SeccompProfileSpec struct {
...
	// match a syscall in seccomp. While this property is OPTIONAL, some values
	// of defaultAction are not useful without syscalls entries. For example,
	// if defaultAction is SCMP_ACT_KILL and syscalls is empty or unset, the
	// kernel will kill the container process on its first syscall
	Syscalls []*Syscall `json:"syscalls,omitempty"`
```

=>

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: seccompprofiles.security-profiles-operator.x-k8s.io
spec:
  group: security-profiles-operator.x-k8s.io
  names:
    kind: SeccompProfile
...
              syscalls:
                description: match a syscall in seccomp. While this property is OPTIONAL,
                  some values of defaultAction are not useful without syscalls entries.
                  For example, if defaultAction is SCMP_ACT_KILL and syscalls is empty
                  or unset, the kernel will kill the container process on its first
                  syscall
```
 Ranhcer has no such functionality.

CRD descriptions are useful because they appear when using `kubectl explain`, for example:

```
kubectl explain pod.spec.automountServiceAccountToken
KIND:     Pod
VERSION:  v1

FIELD:    automountServiceAccountToken <boolean>

DESCRIPTION:
     AutomountServiceAccountToken indicates whether a service account token
     should be automatically mounted.
```

or in [published API docs](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#service-account).

If Rancher supported this, it would be helpful both to rancher developers and users to understand rancher CRDs better and to be able to document a public API from the code itself easily.
