### ISSUE TITLE
Installing a custom cluster via Rancher with the vSphere cloud provider the CSI vsphere-config-secret remains empty

### ISSUE THREAD

**Issue by rhessing** [rancher/rancher#39348]
**Environmental Info:**
RKE2 Version: 
v1.24.4+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux rke2-controlnode.example.com 4.18.0-372.26.1.el8_6.x86_64 rancher/rke2#1 SMP Tue Sep 13 18:09:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
3 control nodes, 4 workers

**Describe the bug:**
When creating a new custom cluster in the Rancher UI with vSphere as the cloud provider only the vsphere CPI configmap (vsphere-cloud-config) is populated, the CSI remains empty:
```
[root@rke2-controlnode ~]# kubectl get -n kube-system secret/vsphere-config-secret -o yaml | grep -i -e csi-vsphere | awk '{print $2}' | base64 -d
[Global]
cluster-id = "c-m-xc98bnfh"
user = ""
password = ""
port = "443"
insecure-flag = "1"

[VirtualCenter ""]
datacenters = ""
```
This causes the CSI controller to fail

When customising the config in the Rancher UI via YAML by adding these lines:
```
spec:
  rkeConfig:
    chartValues:
      rancher-vsphere-csi:
        vCenter:
          datacenters: datacenter
          host: esx-host.example.com
          password: extremely-secret
          username: vsphere-user
```
The vsphere-config-secret is correctly populated and the CSI controller does start

**Steps To Reproduce:**
Create a new custom cluster with the vSphere cloud provider and supply the CPI configuration details within the Add-On Config section.
Run the one-liner on a single system
vSphere CSI remains in a crashback loop

**Expected behavior:**
The configuration details from the CPI part within the Add-On Config should also be applied on the CSI vsphere-config-secret

**Actual behavior:**
the config variables are not included in the CSI vsphere-config-secret
