### ISSUE TITLE
[BUG] backup-restore operator falls in to infinite error loop

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rancher#39391]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): k3s with helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: no

**Information about the Cluster**
- Kubernetes version: 1.24.4
- Cluster Type (Local/Downstream): local and down stream rke2 clsuters
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
I have a local k3s cluster that hosts rancher and 2 downstream RKE2 clusters. I was following official back/restore [docs](https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher)

I have succesfully created backup, but when I am trying to restore from that back up, backup-restore operator have some issues and infinitely trying to restore.

Errors:
```
ERRO[2022/10/24 09:09:18] Error restoring resource rancher-euc1-te-test02-managed-system-agent of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err updating status resource Operation cannot be fulfilled on bundledeployments.fleet.cattle.io "rancher-euc1-te-test02-managed-system-agent": the object has been modified; please apply your changes to the latest version and try again
ERRO[2022/10/24 09:09:23] Error restoring resource rancher-euc1-te-test02 of type cluster.x-k8s.io/v1beta1, Resource=clusters: restoreResource: err updating resource Operation cannot be fulfilled on clusters.cluster.x-k8s.io "rancher-euc1-te-test02": the object has been modified; please apply your changes to the latest version and try again
ERRO[2022/10/24 09:09:44] Error restoring namespaced resources [error restoring rancher-euc1-te-test02-managed-system-agent of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err updating status resource Operation cannot be fulfilled on bundledeployments.fleet.cattle.io "rancher-euc1-te-test02-managed-system-agent": the object has been modified; please apply your changes to the latest version and try again error restoring rancher-euc1-te-test02 of type cluster.x-k8s.io/v1beta1, Resource=clusters: restoreResource: err updating resource Operation cannot be fulfilled on clusters.cluster.x-k8s.io "rancher-euc1-te-test02": the object has been modified; please apply your changes to the latest version and try again]
ERRO[2022/10/24 09:09:44] error syncing 'restore-thdvk': handler restore: error restoring namespaced resources, check logs for exact error, requeuing
ERRO[2022/10/24 09:11:29] Error restoring resource rancher-euc1-te-test02-managed-system-agent of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err updating status resource Operation cannot be fulfilled on bundledeployments.fleet.cattle.io "rancher-euc1-te-test02-managed-system-agent": the object has been modified; please apply your changes to the latest version and try again
ERRO[2022/10/24 09:12:01] Error restoring resource crt-rancher-euc1-te-test01-cluster-admin of type rbac.authorization.k8s.io/v1, Resource=roles: restoreResource: err updating resource Operation cannot be fulfilled on roles.rbac.authorization.k8s.io "crt-rancher-euc1-te-test01-cluster-admin": the object has been modified; please apply your changes to the latest version and try again
ERRO[2022/10/24 09:12:08] Error restoring resource rancher-euc1-te-test02-managed-system-upgrade-controller of type management.cattle.io/v3, Resource=managedcharts: restoreResource: err updating status resource Operation cannot be fulfilled on managedcharts.management.cattle.io "rancher-euc1-te-test02-managed-system-upgrade-controller": the object has been modified; please apply your changes to the latest version and try again
ERRO[2022/10/24 09:12:40] Error restoring namespaced resources [error restoring rancher-euc1-te-test02-managed-system-agent of type fleet.cattle.io/v1alpha1, Resource=bundledeployments: restoreResource: err updating status resource Operation cannot be fulfilled on bundledeployments.fleet.cattle.io "rancher-euc1-te-test02-managed-system-agent": the object has been modified; please apply your changes to the latest version and try again error restoring crt-rancher-euc1-te-test01-cluster-admin of type rbac.authorization.k8s.io/v1, Resource=roles: restoreResource: err updating resource Operation cannot be fulfilled on roles.rbac.authorization.k8s.io "crt-rancher-euc1-te-test01-cluster-admin": the object has been modified; please apply your changes to the latest version and try again error restoring rancher-euc1-te-test02-managed-system-upgrade-controller of type management.cattle.io/v3, Resource=managedcharts: restoreResource: err updating status resource Operation cannot be fulfilled on managedcharts.management.cattle.io "rancher-euc1-te-test02-managed-system-upgrade-controller": the object has been modified; please apply your changes to the latest version and try again]
ERRO[2022/10/24 09:12:40] error syncing 'restore-thdvk': handler restore: error restoring namespaced resources, check logs for exact error, requeuing
```

**To Reproduce**
- Provision downstream rke2 cluster
- create backup
- create restore (default config)

My restore config:
```
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-thdvk
spec:
  backupFilename: s3-recurring-backup-84f7b85d-033a-44cb-b9e9-286d2215aaa3-2022-10-24T08-06-18Z.tar.gz
  deleteTimeoutSeconds: 10
  prune: true
  storageLocation:
    s3:
      bucketName: rancher-euc1-te-mgmt01-backups
      endpoint: s3.eu-central-1.amazonaws.com
      folder: rancher-euc1-te-mgmt01
      region: eu-central-1
status:
  backupSource: ""
  conditions:
  - lastUpdateTime: "2022-10-24T09:18:34Z"
    message: error restoring namespaced resources, check logs for exact error
    reason: Error
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2022-10-24T08:54:28Z"
    message: Retrying
    status: Unknown
    type: Ready
  observedGeneration: 0
  restoreCompletionTs: ""
  summary: ""

```

**Result**
backup-restore operator infinitely reattempting to restore and fails. It seems there is no even failure threshold it just falls in to never ending loop of failures.

**Expected Result**
Restore happens without **any** errors.

**Screenshots**

**Additional context**
