### ISSUE TITLE
Rancher deployment with replicas >1 very unstable [BUG]

### ISSUE THREAD

**Issue by bjd2385** [rancher/rancher#39400]
**Rancher Server Setup**
- Rancher version: 2.6.9, 2.6.8
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): GKE v1.23.8-gke.1900
- Proxy/Cert Details: Bringing my own certs, stashing them in a secret

**Information about the Cluster**
- Kubernetes version: 1.23 - I'm deploying Rancher on a cluster of this version
- Cluster Type (Local/Downstream): N/A
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): N/A

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin, but I can't always login. I had to refer to #34686 to even get logged in _sometimes_.

**Describe the bug**

- I can't always log in, replica pods don't always come up, citing 
```Unable to attach or mount volumes: unmounted volumes=[custom-logos], unattached volumes=[custom-logos kube-api-access-962r5]: timed out waiting for the condition```
in the events. Almost like more than one pod is, for some reason trying to mount the same PV created by the singular PVC.

- Also, the `bootstrapPassword` isn't respected. I can exec into the containers, and the env var is set, but the password is not correct. I literally cannot log in without running the last step in #34686, or
```
kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password
```
but even that only works _sometimes_, like only one pod is updated with the correct password.

**To Reproduce**

Simply deploy the chart. My values.yaml just looks like
```
rancher:
  hostname: <some-hostname>
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      source: secret
      secretName: rancher-tls
  replicas: 1
  bootstrapPassword: rancher
  customLogos:
    enabled: true
    storageClass: standard
    volumeName: "" # For bringing our own volume
    accessMode: ReadWriteOnce
    size: 1Gi
```
and I've extended the chart with an additional secret named `rancher-tls`, with our cert info.

**Result**

**Expected Result**

1. I should be able to log in with the intended `bootstrapPassword`.
2. I should be able to deploy this chart and see the pods (multiple replicas) come up as intended.

**Screenshots**

**Additional context**
