### ISSUE TITLE
UI: Stop button for stack does not work anymore

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3944]
Rancher Version: 0.63

Docker Version: 1.10.2

OS: n/a but browser is Chrome for Mac Version 48.0.2564.116 (64-bit)

Steps to Reproduce: Click on the global stack stop button or dropdown

Results: Confirmation dialog pops up, after confirm no services are stopped. Stopping individual services works after confirmation

Expected: Clicking Stack Stop should stop all Services after confirmation

**Comment by hwinkel** [comment]
Thats only true for certain stacks, here the files of a affected test stack:

docker-compose
```
swagedit:
  ports:
  - 80:8080/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label_ne: rancher=true
  tty: true
  image: swaggerapi/swagger-editor
  stdin_open: true
swaglb:
  ports:
  - 443:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.swagedit: '8080'
  tty: true
  image: rancher/load-balancer-service
  links:
  - swagedit:swagedit
  stdin_open: true
```

rancher-compose

```
swagedit:
  scale: 2
swaglb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: '*.tpip.net'
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```
