### ISSUE TITLE
RKE2 with CIS1.6 cannot install OPA Gatekeeper

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#39443]
SURE-4028

**Issue description:**
Trying to install the OPA Gatekeeper on the RKE2 server with CIS-1.6 enabled is failing.

**Business impact:**
Can't install chart without modifying 

**Troubleshooting steps:**

- Create Rancher server 2.6.3
- Create a RKE2 cluster v1.21.7+k3s1  with CIS-1.6 profile enabled
- Import the RKE2 cluster in Rancher.
- Install the OPA Gatekeeper chart, default values.
- Getting the below error.
```
Error: container has runAsNonRoot and image will run as root (pod: "gatekeeper-update-crds-hook-r74bt_cattle-gatekeeper-system(5078dd3d-00bc-4b16-8eb3-99e3eef128e1)", container: crds-upgrade)
```
**Repro steps:**

Above steps 
 
**Workaround:**
Is workararound available and implemented? yes
**What is the workaround:**

Created below patch-rancher-logging.yaml using below manifests
```
spec:
  fluentd:
    security:
      podSecurityPolicyCreate: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 100
    fluentOutLogrotate:
      enabled: true
      path: /buffers/fluentd.log
```

Ran below commands to patch CRD
kubectl patch logging/rancher-logging --type merge --patch "$(cat ./patch-rancher-logging.yaml)"
kubectl patch logging/rancher-logging-kube-audit --type merge --patch "$(cat ./patch-rancher-logging.yaml)"
**Actual behavior:**
Cannot deploy OPA Gatekeeper helm chart in downstream RKE2 when CIS1.6 enabled.

**Expected behavior:**
We should be able to deploy the OPA Gatekeeper chart on a CIS1.6 enabled RKE2 cluster

**Files, logs, traces:**
Error: container has runAsNonRoot and image will run as root (pod: "gatekeeper-update-crds-hook-r74bt_cattle-gatekeeper-system(5078dd3d-00bc-4b16-8eb3-99e3eef128e1)", container: crds-upgrade) Also attaching the error screenshot for reference Environment : Rancher 2.6.3 ( Fresh installation on rke2 v1.21.7+rke2r2 ) Downstream clusters ( 6x RKE2 , rke2 v1.21.7+rke2r2 )

**Additional notes:**
Its the same issue mentioned in SURE-3893 and the customer also same.
