### ISSUE TITLE
vSphere CPI/CSI options omitted when selecting `vsphere` cloud provider in Rancher 2.6.7 or newer

### ISSUE THREAD

**Issue by David-VTUK** [rancher/rancher#39462]
**Setup**
- Rancher version: >= 2.6.7
- Browser type & version: Firefox 104.0

**Describe the bug**
vSphere CSI options are omitted when selecting the respective cloud provider in rke2 provisioning. vSphere CPI options however remain

**To Reproduce**
Create cluster -> RKE2 -> Select `vSphere` as the cloud provider > Navigate to addon config

**Result**

**Expected Result**
vSphere CPI options presented, vSphere CSI options are omitted. 

**Screenshots**
In 2.6.7/2.6.8:

![image](https://user-images.githubusercontent.com/5892615/188305043-df1b018b-cea3-457d-afa5-7a1a3ee2977d.png)

in 2.6.6

![image](https://user-images.githubusercontent.com/5892615/188305170-b0258539-cbc7-4cf8-80b6-bb25510b0613.png)

**Additional context**

In 2.6.6 the latest (non experimental) version of RKE2 is 1.22.13
In 2.6.8 the latest version of RKE2 is 1.24.4

The CSI chart has a version restriction:

https://github.com/rancher/charts/blob/36de515042fb94888c751aeedd645f6ffae6a854/index.yaml#L8784

```
  rancher-vsphere-csi:
  - annotations:
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: vSphere CSI
      catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.24.0-0'
```

Even in 2.6.8, if a valid version is specified for the RKE2 version, the CSI options are not present.

The CPI chart does have a version restriction, but is higher:

https://github.com/rancher/charts/blob/36de515042fb94888c751aeedd645f6ffae6a854/index.yaml#L8576

```
  rancher-vsphere-cpi:
  - annotations:
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: vSphere CPI
      catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.25.0-0'
```

What I suspect is happening:

- in 2.6.8 when an RKE2 version is created, it defaults to the latest version (1.24.4) which is outside the range of the CSI chart but not the CPI chart. However, if you were to select a different version that does fall within this range, this is not re-evaluated.

- in 2.6.6 when an RKE2 cluster is created, it defaults to the latest version (1.22.13) which is inside the range of both charts, therefore both chart values are seen 

Therefore, I believe an action needs to be performed in the UI whenever a specific k8s version is selected to re-evaluate respective addon charts for the vSphere cloud provider, assuming the version restriction is for a legitimate reason.
