### ISSUE TITLE
[BUG] Pod Labels and Service selectors not shown properly in UI

### ISSUE THREAD

**Issue by arne-reinhardt** [rancher/rancher#39492]
**Rancher Server Setup**
- Rancher version: RD 1.6.1
- Installation option (Docker install/Helm Chart):
Example helloworld-application:
* "Hello World" echoing web app
* corresponding Service and Ingress
```
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: helloworld
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /helloworld
        pathType: Prefix
        backend:
          service:
            name: helloworld
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: helloworld
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: helloworld
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - image: tutum/hello-world
          name: helloworld
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
```

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local / Rancher Desktop (containerd)

**Describe the bug**
The application is working fine but the dashboard UI has got me confused with respect to labels on Pods and selectors on Services. 

Inspecting Pods via the "config" UI I see no labels though they're visible in the Deployment config (and in the YAML view of course). Services do show their related Pods in the overview but in the "selectors" pane of the "config" UI I'm told the (perfectly working) selectors would match "0 of 0 Pods".

**To Reproduce**
Run the application above and inspect the UI as described.

**Result**
See screenshots below

**Expected Result**
I would expect
* the Pod config pane to show the label "app: helloworld" (as the Deployment/Pod Labels pane correctly does)
* the Service selectors pane to show the matching "helloworld"-Pod (as the Service overview correctly does)

**Screenshots**
**Reply from web app**
proof things are working correctly
![helloworld](https://user-images.githubusercontent.com/75505180/199689838-8502ffdb-4dc3-42c5-ad05-bb3dfa3835c4.png)
**Deployment / Pod Labels**
Labels placed on Pod are shown correctly
![Deployment_pod-labels](https://user-images.githubusercontent.com/75505180/199688098-a1d47841-e19c-4c18-9603-cf4609f4bccd.png)
**Pod config pane**
no labels shown
![Pod-config](https://user-images.githubusercontent.com/75505180/199688100-4a114367-0035-4391-afde-ceb74420507f.png)
**Service overview**
associated Pod is shown
![Service-Pods](https://user-images.githubusercontent.com/75505180/199688101-46549936-95dd-4360-949d-948bbf37e3a7.png)
**Service / Selectors**
selectors are not evaluated correctly
![Service-selectors](https://user-images.githubusercontent.com/75505180/199688103-d3921327-d047-487c-bd09-d9d689250808.png)

**Additional context**
