### ISSUE TITLE
[BUG] Rancher 2.6.9 misses spec.rkeConfig.chartValues.rke2-ingress-nginx chart values after Edit Config

### ISSUE THREAD

**Issue by mfbrj** [rancher/rancher#39556]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.24.4+k3s1 with postgres datasource
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.4
- Cluster Type (Local/Downstream): Downstream RKE2 on vSphere on premise
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

Rancher misses yml values of a RKE2 downstream cluster after user save cluster configuration from UI, causing misconfiguration on nginx ingress controller.

**To Reproduce**

1. From Rancher 2.6.9 UI, creates a RKE2 cluster with nginx ingress enabled.
2. After the cluster provision is completed, edit the cluster yaml to add some configuration to the rke2-ingress-nginx chart values, such as:
```
      rke2-ingress-nginx:
        controller:
          config:
            enable-brotli: "true"
            use-forwarded-headers: "true"
          extraArgs:
            default-ssl-certificate: kube-system/ingress-controller-cert
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
          podAnnotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
```
The above snnipet must be placed with the proper indentation at:
![image](https://user-images.githubusercontent.com/835834/200915111-eb7b9142-03c3-42d1-8e1b-a170e86e9299.png)
3. Save the cluster yaml. This will start some deployments on nginx controller Daemonset on `kube-system` Namespace. Wait for the complete redeploy.
4. From Rancher UI Cluster Management, click on the 3 vertical dots and then click on Edit Config:
![image](https://user-images.githubusercontent.com/835834/200916730-91e7ed06-d27f-45ef-917c-0a1670c6fc5a.png)
5. Perform some modification on the cluster, such as add another pool. Click Save button.

**Result**
The rke2-ingress-nginx config on cluster yaml is lost. Nginx ingress controller Daemonsets are redeployed without the configurations on `kube-system` Namespace.
![image](https://user-images.githubusercontent.com/835834/200919044-7c462814-d56b-42dd-b183-3ac1c49f955e.png)

**Expected Result**

No config should be lost on the cluster yaml after perform some modification on the cluster. No redeploy on nginx ingress controller Daemonset on `kube-system` Namespace.

**Screenshots**

**Additional context**
