### ISSUE TITLE
[BUG] Some nodes are not deleted upon node-pool deletion

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#39557]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  OpenStack (Should repro on other providers), RKE1

**Describe the bug**
Nodes often fail to be removed by a rancher when the corresponding nodepool is deleted. This affects greatly the decommissioning of clusters as the nodepools are removed by rancher, and some nodes are left off, which then prevents the removal of complementary resources like networks and security groups that we are provisioning alongside the cluster/nodepools as the dangling nodes are still using them.

As an exemple, in the following rancher logs, we can see that the `sd-pulumi3-system1` node fail to be drained:

 ```
rancher-5d7584b7b8-j6f4l 2022/08/08 12:24:33 [INFO] Removing node sd-pulumi3-system3 {ref-1}
rancher-5d7584b7b8-j6f4l 2022/08/08 12:24:33 [INFO] node [sd-pulumi3-system3] requires draining before delete{ref-2}
rancher-5d7584b7b8-j6f4l 2022/08/08 12:24:33 [INFO] node [sd-pulumi3-system3] attempting to drain, retrying up to 3 times{ref-3} .
 rancher-5d7584b7b8-j6f4l 2022/08/08 12:25:07 [ERROR] node [sd-pulumi3-system3] kubectl drain error, retrying: exit status 1{ref-4}
rancher-5d7584b7b8-j6f4l 2022/08/08 12:25:11 [ERROR] error syncing 'c-t9fvv/m-9hxmm': handler node-controller: timed out waiting for the condition, requeuing{ref-5} ...
rancher-5d7584b7b8-j6f4l 2022/08/08 12:26:11 [INFO] Deleted cluster [c-t9fvv]{ref-6}
rancher-5d7584b7b8-j6f4l 2022/08/08 12:26:36 [ERROR] error syncing 'c-t9fvv/m-9hxmm': handler node-controller: nodes.management.cattle.io "m-9hxmm" not found, requeuing {ref-7}
```

```
{ref-1} Deletion for the node starts: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/node/controller.go#L274
{ref-2} Node requires to be drained: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/node/cleanup.go#L95
{ref-3} Drain will be retried 3 times: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/node/cleanup.go#L119
{ref-4} Drain failed 3 times with no details: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/node/cleanup.go#L132
{ref-5} The `wait.ExponentialBackoff` will return an ErrWaitTimeout error: https://github.com/kubernetes/apimachinery/blob/v0.24.3/pkg/util/wait/wait.go#L429 Which will be returning here: https://github.com/rancher/rancher/blob/v2.6.6/pkg/controllers/management/node/controller.go#L276 and somehow requeued in contrary of the code comments saying that the node will still be removed: ``` // purposefully ignoring error, if the drain fails this falls back to deleting the node as usual // kubectl failed continue on with delete any way
{ref-6} The cluster is removed, which means that rancher answered that the nodepools have been removed, otherwise, the cluster deletion wouldn't have been triggered. Cluster and nodepools are separated pulumi resources with one depending on the other (cluster <- nodepools), so nodepools are deleted first, then comes the cluster.
{ref-7} rancher retry for the failed drain node, but the cluster is gone so the node isn't referenced/found anymore. That being said, the node server is still there in Openstack. If the rancher would have tried to remove the node, we would have seen a log like: ``` [INFO] [node-controller-rancher-machine] About to remove sd-pulumi3-system3
```

This is likely due to mishandling error's encountered during failed attempts to drain nodes.

**To Reproduce**
Delete cluster created on OpenStack environment

**Result**
some nodes and resources are left behind after cluster deletion 

**Expected Result**
All resources and dependencies used by the cluster should be removed

SURE-5118

**Comment by slickwarren** [comment]
Reproduced on v2.7.0-rc11

Test Plan - Fresh Install:
+ Begin creating an RKE1 cluster with two node pools. 1 Node pool will have the `etcd` & `cp` role, and 1 will be a worker only pool
+ Enable `Drain Before Delete` for the worker only node pool
+ Under `Advanced Options` enable `drain nodes`
+ Create the cluster and wait for it to become available
+ Enter the cluster explore page and create a new deployment 
   + The image for the deployment isn't important, I used `nginx:latest` 
   + The number of replicas for the deployment must be `1`
   + A label named `app` must be added to the deployment, and its value must be `test`
+ Create a deployment and PodDisruptionBudget by adding the following manifest to the cluster using the `import YAML` button
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draindeployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx:latest

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: drain-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: test
```
+ After creating the pod disruption budget delete the cluster (or any node within the worker node pool which has drain before delete enabled)
+ Observe the node get properly cleaned up and not stuck in a deleting phase, also observe that all resources are deleted from the infrastructure provider.

Test Plan - upgrade: 

* follow same steps for fresh install on a known version of rancher where this is breaking (i.e. 2.7.0)
  * observe that the nodes aren't deleted in the backend
* upgrade rancher, do the same steps on the same cluster and ensure that the node with drain enabled, when deleted, is removed both from rancher and the backend. 

Potential other tests:
* do fresh install steps, but instead of the custom app, delete a control plane node with drain enabled. Ensure the node is deleted in the backend.

**Comment by slickwarren** [comment]
Tested on v2.7-head (ae44c39):

Fresh Install -- PASS
+ Begin creating an RKE1 cluster with two node pools. 1 Node pool will have the `etcd` & `cp` role, and 1 will be a worker only pool
+ Enable `Drain Before Delete` for the worker only node pool
+ Under `Advanced Options` enable `drain nodes`
+ Create the cluster and wait for it to become available
+ Enter the cluster explore page and create a new deployment 
   + The image for the deployment isn't important, I used `nginx:latest` 
   + The number of replicas for the deployment must be `1`
   + A label named `app` must be added to the deployment, and its value must be `test`
+ Create a deployment and PodDisruptionBudget by adding the following manifest to the cluster using the `import YAML` button
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draindeployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx:latest

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: drain-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: test
```
+ After creating the pod disruption budget delete the cluster (or any node within the worker node pool which has drain before delete enabled)
+ Observe the node get properly cleaned up and not stuck in a deleting phase, also observe that all resources are deleted from the infrastructure provider.

upgrade -- PASS

* follow same steps for fresh install on a known version of rancher where this is breaking (i.e. 2.7.0)
  * observe that the nodes aren't deleted in the backend
* upgrade rancher, do the same steps on the same cluster and ensure that the node with drain enabled, when deleted, is removed both from rancher and the backend. 
* 
Additional Testing: 
* do fresh install steps, but instead of the custom app, delete a control plane node with drain enabled. Ensure the node is deleted in the backend -- PASS
