### ISSUE TITLE
error syncing kube-system/rke2-etcd-snapshots

### ISSUE THREAD

**Issue by xhejtman** [rancher/rancher#39600]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart):
   helm chart, rke2

**Information about the Cluster**
- Kubernetes version: 1.24.7 (local cluster), 1.21.13 (c-m-frtz2drj cluster)

In Rancher logs 2.6.9, I am continuously seeing:
```
2022/11/15 09:27:35 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster local from cache via index: Index with name by-cluster does not exist, requeuing
2022/11/15 09:27:35 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster c-m-frtz2drj from cache via index: Index with name by-cluster does not exist, requeuing
2022/11/15 09:29:35 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster local from cache via index: Index with name by-cluster does not exist, requeuing
2022/11/15 09:29:35 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster c-m-frtz2drj from cache via index: Index with name by-cluster does not exist, requeuing
```

Is this some kind of new bug?

**Comment by MKlimuszka** [comment]
SURE-5650

**Comment by Florianisme** [comment]
We were told that SUSE is aware of this issue and is investigating it.

It might occur when updating from around Rancher 2.6.5 to 2.6.9 directly without incrementally updating to each patch version in-between.

**Comment by oingooing** [comment]
same issue.
i did upgrade version 2.6.8 to 2.6.9.

**Comment by atsai1220** [comment]
Running into this issue as well. We create our clusters by applying the `cluster.provisioning` object and using `v1.23.12+rke2r1`.

``` yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: az-eastus-proxytest
spec:
  cloudCredentialSecretName: cattle-global-data:cc-clvwk
  enableNetworkPolicy: true
  kubernetesVersion: v1.23.12+rke2r1
  rkeConfig:
    etcd:
      disableSnapshots: false
      s3:
        bucket: etcd
        cloudCredentialName: cattle-global-data:s3-proxy
        endpoint: https://az-eastus-dockyard-local-s3proxy.marina.viasat.io
        endpointCA: |
          -----BEGIN CERTIFICATE-----
          ...
          ...
          -----END CERTIFICATE-----
        folder: az-eastus-proxytest-etcd
        region: ''
        skipSSLVerify: false
      snapshotRetention: 24
      snapshotScheduleCron: 0 */4 * * *
```

![image](https://user-images.githubusercontent.com/14171643/215607435-5256a934-58e1-4662-bb2f-ec3847d417cb.png)

**Comment by atsai1220** [comment]
Running into this issue as well. We create our clusters by applying the `cluster.provisioning` object and using `v1.23.12+rke2r1`.

I wonder if we can't specify the `metadata.name` of `cluster.provisioning` because the etcd snapshot controller is expecting the generated cluster ID (e.g. `c-m-qnmnhjl8`). This would be quite unfortunate if we can't define the name and it's unintuitive to how Kubernetes works.

``` yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: az-eastus-proxytest
spec:
  cloudCredentialSecretName: cattle-global-data:cc-clvwk
  enableNetworkPolicy: true
  kubernetesVersion: v1.23.12+rke2r1
  rkeConfig:
    etcd:
      disableSnapshots: false
      s3:
        bucket: etcd
        cloudCredentialName: cattle-global-data:s3-proxy
        endpoint: https://az-eastus-dockyard-local-s3proxy.marina.io
        endpointCA: |
          -----BEGIN CERTIFICATE-----
          ...
          ...
          -----END CERTIFICATE-----
        folder: az-eastus-proxytest-etcd
        region: ''
        skipSSLVerify: false
      snapshotRetention: 24
      snapshotScheduleCron: 0 */4 * * *
```

![image](https://user-images.githubusercontent.com/14171643/215607435-5256a934-58e1-4662-bb2f-ec3847d417cb.png)
