### ISSUE TITLE
[BUG] RKE Template: 'Edit as Yaml' with agent_env_vars breaks the Template

### ISSUE THREAD

**Issue by TobiasMuellerES** [rancher/rancher#39617]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, Kubernetes v1.21.8
- Proxy/Cert Details: No Proxy, Private PKI with self managed Certificate

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere Provider

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
I've a RKE Template with some agent environment variables configured:

That's the current template in yaml view. This template is working without problems.
```yaml
agent_env_vars:
  - name: HTTP_PROXY
    value: 'http://webproxy.demo.lab:8888'
  - name: HTTPS_PROXY
    value: 'http://webproxy.demo.lab:8888'
  - name: NO_PROXY
    value: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost

answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
...
```

Today i had to add some options to the ingress controller that can only made via yaml. I clone the template and use the 'Edit as YAML' Option. No I've the following yaml:
```yaml
agent_env_vars:
  - name: HTTP_PROXY
    value: 'http://webproxy.demo.lab:8888'
    value_from: {}
  - name: HTTPS_PROXY
    value: 'http://webproxy.demo.lab:8888'
    value_from: {}
  - name: NO_PROXY
    value: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost
    value_from: {}

answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
...
```

**To Reproduce**
Add some agent environment variables to an RKE template or a cluster configuration and press 'Edit as Yaml'

**Result**
This yaml format for the Agent_env_vars is incompatible with the format that Kubernetes needs for the cluster-cattle-agent. When I try to apply a template with the agent_env_vars above I get a large error text:

```text
DaemonSet.apps "cattle-node-agent" is invalid: [spec.template.spec.containers[0].env[9].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`, spec.template.spec.containers[0].env[10].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`, spec.template.spec.containers[0].env[11].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`, spec.template.spec.containers[0].env[12].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`, spec.template.spec.containers[0].env[13].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`, spec.template.spec.containers[0].env[14].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`]
```

**Expected Result**
The RKE Template will correctly applied to the cluster

**Additional context/ Workaround**
When you manually remove the value_from Attributes from the YAML Config before saving the template you get a working RKE Template.
