### ISSUE TITLE
Cluster stuck in waiting to register with kubernetes state and is not using the specified VMware vSphere cloud provider.

### ISSUE THREAD

**Issue by jainpulkit22** [rancher/rancher#39686]
**Rancher Server Setup**
Rancher server is running successfully on my linux vm.
- Rancher version:
rancher server version: v2.6.9
- Installation option (Docker install/Helm Chart):
istalled the rancher server using docker run command, and the server was working fine, then installed rancher cli using the tar.gz file on another linux vm, and connected it to the rancher server with the help of token and access key.
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.6
- Cluster Type (Local/Downstream):
Downstream cluster with vsphere as an Infrastructure Provider..

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
- Admin

**Describe the bug**
When I am trying to create a cluster with the help of rancher cli with vmware vsphere as the infrastructure provider, I am not able to create the cluster, the clusters are stuck in the provisioning state(waiting to register with kubernetes), and also when i log in to the UI there the provider is shown as Custom only, even though in the config yaml I have passed vsphere as the cloud provider.
I am able to create the cluster successfully and provision the nodes also on vsphere, if i create the cluster directly from UI, but same fails when I try to create it with the help of rancher cli commands.

**To Reproduce**
1) Deploy the rancher server.
2) Install rancher cli tool and connect it to the rancher server with the help of access key and tokens.
3) Now deploy a rancher cluster using rancher cli and pass a customized rke config using the --rke-config flag, to set the Infrastructure provider to VMware vSphere.
cmd: `./rancher cluster create --rke-config <rkeconfig yaml name> --network-provider none <name of the cluster>`
4) Now login to the rancher dashboard, and select the cluster you have created and then switch to the registration tab, and copy paste the command there in your vm to register the nodes. We need to register the nodes explicitly by running the commands on the vm, because the vm's are not provisioned automatically as it happens in the case of the UI.
5) rke config file used:
```
answers: {}
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
fleet_workspace_name: fleet-default
local_cluster_auth_endpoint:
 enabled: true
name: rke-demolatest
rancher_kubernetes_engine_config:
 addon_job_timeout: 45
 addons_include:
  - >-
   <yaml of our custom cni>
 authentication:
  strategy: x509|webhook
 authorization: {}
 bastion_host:
  ignore_proxy_env_vars: false
  ssh_agent_auth: false
 cloud_provider: {}
 dns:
  linear_autoscaler_params: {}
  node_selector: null
  nodelocal:
   node_selector: null
   update_strategy:
    rolling_update: {}
  options: null
  reversecidrs: null
  stubdomains: null
  tolerations: null
  update_strategy: {}
  upstreamnameservers: null
 enable_cri_dockerd: true
 ignore_docker_version: true
 ingress:
  default_backend: false
  default_ingress_class: true
  http_port: 0
  https_port: 0
  provider: nginx
 kubernetes_version: v1.24.6-rancher1-1
 monitoring:
  provider: metrics-server
  replicas: 1
 network:
  mtu: 0
  options:
   flannel_backend_type: vxlan
  plugin: none
 restore:
  restore: false
 rotate_encryption_key: false
 services:
  etcd:
   backup_config:
    enabled: true
    interval_hours: 12
    retention: 6
    safe_timestamp: false
    timeout: 300
   creation: 12h
   extra_args:
    election-timeout: '5000'
    heartbeat-interval: '500'
   gid: 0
   retention: 72h
   snapshot: false
   uid: 0
  kube-api:
   always_pull_images: false
   pod_security_policy: false
   secrets_encryption_config:
    enabled: false
   service_node_port_range: 30000-32767
  kube-controller: {}
  kubelet:
   fail_swap_on: false
   generate_serving_certificate: false
  kubeproxy: {}
  scheduler: {}
 ssh_agent_auth: false
 upgrade_strategy:
  max_unavailable_controlplane: '1'
  max_unavailable_worker: 10%
  node_drain_input:
   delete_local_data: false
   force: false
   grace_period: -1
   ignore_daemon_sets: true
   timeout: 120
 cloud_provider:
  name: vsphere
  vsphereCloudProvider:
   virtual_center:
    <VC IP>:
     user: <username>
     password: <password>
     port: <port>
     datacenters: <datacenter>
   workspace:
    server: <VC IP>
    default-datastore: <datastore>
    datacenter: <datacenter>
    resourcepool-path: <resourcepool path> 
```

**Result**
```
time="2022-11-22T11:36:37Z" level=error msg="Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: cluster not found" error="websocket: bad handshake"
time="2022-11-22T11:36:37Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
```
<img width="1452" alt="Screenshot 2022-11-24 at 5 04 28 PM" src="https://user-images.githubusercontent.com/42600268/203775098-33bfac39-b70e-4c92-96a1-c20a2e3ed4b9.png">

**Expected Result**
<img width="1462" alt="Screenshot 2022-11-24 at 5 07 47 PM" src="https://user-images.githubusercontent.com/42600268/203775341-161ab4b7-fc30-4e9b-bb58-aa41632c659f.png">

**Screenshots**

**Additional context**
