### ISSUE TITLE
[rancher-compose] Support for docker-compose v2 syntax?

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#3973]
Is there a timeline on when the [docker-compose v2 file format](https://docs.docker.com/compose/compose-file/#version-2) will be supported?

```
Rancher Compose Version: 0.7.2
Docker Version: 1.10.3
OS: OS X 10.11.4 Beta
```

Steps to Reproduce:  

`docker-compose.yml`

```
version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  redis:
    image: redis
```
then execute:

`rancher-compose -p NewApp up`

Results: 

```
ERRO[0000] Could not parse config for project newapp : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2` into project.RawService
FATA[0000] Failed to read project: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `2` into project.RawService
```

Expected:
