### ISSUE TITLE
Rancher metrics error with Pods with duplicate name in different namespaces

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39778]
The customer has a use case, where pods might be named equally on different namespaces. With v2 monitoring enabled at the cluster level, looking at the deployment page, where the metrics are shown in graphs, they get the error attached.

"many-to-many matching not allowed: matching labels must be unique on one side"

Business impact:
Nuisance. Users have to alter the query to see metrics and no error

Troubleshooting steps:
<text>

Repro steps:

    install the rancher-monitoring app (v100.3.0+up19.0.3)
    create two namespaces
    create two pods with the same name in the previously created namespaces
    access Metrics view on Pod level in the Rancher UI or the Rancher / Workload (Pods) Grafana dashboard

Workaround:
Is workararound available and implemented? yes/no
What is the workaround: Seems like you can alter the query to focus on a specific namespace

Actual behavior:
User is presented with error message and no metrics are displayed.

Expected behavior:
User should be presented with proper pod metrics.

Files, logs, traces:
<text>

Additional notes:
https://github.com/rancher/charts/issues/1848

https://github.com/rancher/rancher/issues/37282

https://github.com/rancher/charts/pull/2064

SURE-5264

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x,  2023-Q1-2.6x, and if it cannot be reproduced in those, 2.6.4

**Comment by PennyScissors** [comment]
Couldn't reproduce in the following Rancher and Monitoring versions following the steps in the description.
Rancher 2.7-head 828fe61 - Monitoring 102.0.0+up40.1.2
Rancher 2.6-head 8175777 - Monitoring 100.2.0+up40.1.2 
Rancher 2.6.4 - Monitoring 100.1.3+19.0.3

**Comment by cfuntis** [comment]
Important Information: We only have troubles with Pods in a StatefulSet

**Comment by MKlimuszka** [comment]
Thank you for the info. We will continue trying to reproduce this.

**Comment by PennyScissors** [comment]
Was NOT able to reproduce in the versions below following the same steps to reproduce it in 2.6.9:

Rancher 2.7-head 9376ad2 - Monitoring 102.0.0+up40.1.2
![image](https://user-images.githubusercontent.com/8951271/220489385-446ea978-18c5-4a64-8a26-a075a2246f54.png)

Rancher 2.6-head 6d1bd94 - Monitoring 100.2.0+up40.1.2
![image](https://user-images.githubusercontent.com/8951271/220489344-2455be7c-4aac-4316-bfcc-7f826c4abc87.png)


Was able to reproduce in Rancher 2.6.9 with Monitoring 100.1.3+19.0.3 installed following these steps:
1. Install Monitoring 100.1.3+19.0.3
2. Create namespaces `ns1` and `ns2`
3. Create the following StatefulSets (One for each namespace, same name, only the namespace is different)
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello
  namespace: <ns1 or ns2>
spec:
  serviceName: "no-real-service"
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: rancher/hello-world
        ports:
        - containerPort: 80
          name: hello
```
4. Refresh page (sometimes I need to do this for the namespaces and StatefulSets to show up in the Grafana dashboard)
5. Navigate to the Grafana dashboard and search for `Rancher / Workloads (Pods)`
6. See the following error pop up on the right corner of the screen
![image](https://user-images.githubusercontent.com/8951271/220482135-8b910b1b-0ae5-4d9b-9aa4-ecbd58c840df.png)
