### ISSUE TITLE
Random mapping of ports is broken on upgrade

### ISSUE THREAD

**Issue by rzachariah** [rancher/rancher#3979]
Rancher Version: Rancher 0.59.1

Docker Version: Docker 1.10.2

OS: Ubuntu 14.04.4 LTS

Steps to Reproduce: 
1. Create a Rancher catalog entry that deploys a stack containing a service that gets assigned a random high value port. For example, you could have a snippet of docker-compose.yml that looks like this. Note we only specify the private port for the collector. We rely on Rancher to assign the public port.

```
collector:
  ports:
  - "80"
```

2. Deploy this Rancher catalog entry to a Rancher environment. The first time you deploy, everything will work great. Collector will be assigned a random high value port.
3. Now make a modification to the catalog entry.
4. Perform an upgrade to the new catalog version.

Results: After upgrade, collector will have lost its public port.

Expected: Collector should retain its public port.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml of the original catalog entry and the updated one? I was unable to reproduce. My upgraded catalog kept the same random public port.

**Comment by rzachariah** [comment]
Here's the docker-compose template for the catalog definition. There are some variables in here that we populate in Bamboo.

```
ims-capture:
  ports:
  - "33300"
  image: dockertrustedregistry.ezesoft.net/exhaust/ims-capture:iota
  environment:
    - "ROUTING_PATH=/app/exhaust/module"
  labels:
    io.rancher.container.pull_image: always
    eze.routing.registrator.http: ":33300:/app/exhaust/module"
collector:
  ports:
  - "80"
  image: "$bamboo_properties_collector_tag"
  environment:
    - "ROUTING_PATH=/api/exhaust/v1/collection"
    - "AWS_ACCESS_KEY_ID=\${accesskey}"
    - "AWS_SECRET_ACCESS_KEY=\${secretkey}"
  labels:
    eze.routing.registrator.http: ":80:/api/exhaust/v1/collection"
```

Here's what the config looks like once I deploy the catalog entry for the first time (I obfuscated the access keys).

```
ms-capture:
  ports:
  - 56304:33300/tcp
  environment:
    ROUTING_PATH: /app/exhaust/module
  labels:
    io.rancher.container.pull_image: always
    eze.routing.registrator.http: :33300:/app/exhaust/module
    io.rancher.service.hash: eb7c91d6076ad0742ad3cde0a38f47fb38f9ac8c
  image: dockertrustedregistry.ezesoft.net/exhaust/ims-capture:theta
collector:
  ports:
  - 62290:80/tcp
  environment:
    AWS_ACCESS_KEY_ID: *****
    AWS_SECRET_ACCESS_KEY: *****
    ROUTING_PATH: /api/exhaust/v1/collection
  labels:
    eze.routing.registrator.http: :80:/api/exhaust/v1/collection
    io.rancher.service.hash: bd1520618777f518109a566f531abc45b9b85ae2
  image: dockertrustedregistry.ezesoft.net/exhaust/collector:0.0.18
```

Note the services have random public ports assigned. Here's what it looks like after upgrade.

```
ims-capture:
  ports:
  - 33300/tcp
  environment:
    ROUTING_PATH: /app/exhaust/module
  labels:
    io.rancher.container.pull_image: always
    eze.routing.registrator.http: :33300:/app/exhaust/module
    io.rancher.service.hash: e5c9765e4db253d3f501a5044c053b89680fb93d
  image: dockertrustedregistry.ezesoft.net/exhaust/ims-capture:iota
collector:
  ports:
  - 80/tcp
  environment:
    AWS_ACCESS_KEY_ID: *****
    AWS_SECRET_ACCESS_KEY: *****
    ROUTING_PATH: /api/exhaust/v1/collection
  labels:
    eze.routing.registrator.http: :80:/api/exhaust/v1/collection
    io.rancher.service.hash: 1a208e679e1387655a615886e4b40c8599c50de4
  image: dockertrustedregistry.ezesoft.net/exhaust/collector:0.0.19
```

Note the public ports are gone.

**Comment by deniseschannon** [comment]
I have been able to reproduce.

1. Created a simple docker-compose.yml template for my private catalog. 

```
test:
  image: nginx
  ports: 
  - 80 
```
2. Launch catalog entry and view config of the stack.

```
test:
  ports:
  - 54685:80/tcp
  labels:
    io.rancher.service.hash: b20e0420ae3ac2fa8434e9abebee440046309a1b
  image: nginx
```

3. Edited my template by adding a label.

```
test:
  image: nginx
  restart: always
  ports: 
  - 80
  labels:
    foo: bar
```

4. View Config in UI. Random port is missing in Config.

```
test:
  ports:
  - 80/tcp
  labels:
    io.rancher.service.hash: 0816529997040e2c0d2d0d8a39409a37c2bc9d32
    foo: bar
  image: nginx
```
