### ISSUE TITLE
Selector links overrides explicit links in compose file

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3988]
Rancher Version: 0.63.1

Docker Version: 1.10.1

OS: boot2docker

Steps to Reproduce: `rancher-compose up -d`

Using this `docker-compose.yml` file:

```
a:
  image: ubuntu
  tty: true
  stdin_open: true
  command:
    - cat
  labels:
    io.rancher.service.selector.link: foo
  links:
    - b
b:
  image: ubuntu
  tty: true
  stdin_open: true
  command:
    - cat
c:
  image: ubuntu
  tty: true
  stdin_open: true
  command:
    - cat
  labels:
    foo: bar
```

Results: 

```
b:
  labels:
    io.rancher.service.hash: 74a27fb8a287886a4cd9591acb03f3da5268fe80
  command:
  - cat
  tty: true
  image: ubuntu
  stdin_open: true
c:
  labels:
    io.rancher.service.hash: bc5fdcc87fb79a2fc5ccb7ab991d960c0fc93b2b
    foo: bar
  command:
  - cat
  tty: true
  image: ubuntu
  stdin_open: true
a:
  labels:
    io.rancher.service.selector.link: foo
    io.rancher.service.hash: 1b520b790c03bb0c80481d99a52a776964911844
  command:
  - cat
  tty: true
  image: ubuntu
  links:
  - c:c
  stdin_open: true
```

Expected:

```
b:
  labels:
    io.rancher.service.hash: 74a27fb8a287886a4cd9591acb03f3da5268fe80
  command:
  - cat
  tty: true
  image: ubuntu
  stdin_open: true
c:
  labels:
    io.rancher.service.hash: bc5fdcc87fb79a2fc5ccb7ab991d960c0fc93b2b
    foo: bar
  command:
  - cat
  tty: true
  image: ubuntu
  stdin_open: true
a:
  labels:
    io.rancher.service.selector.link: foo
    io.rancher.service.hash: 1b520b790c03bb0c80481d99a52a776964911844
  command:
  - cat
  tty: true
  image: ubuntu
  links:
  - c:c
  - b:b
  stdin_open: true
```

I.e. I miss the link to the `b` service. I discovered this issue using `external_links`, but seeing as the issue also applies to `links`, I've only made a reproducible test for that scenario, but please also consider the use for `external_links`.
