### ISSUE TITLE
[BUG] In a K3s cluster, `publicEndpoints` does not show field `addresses` as a designated field when it should

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#39926]
**Rancher Server Setup**
- Rancher version: `v2.7.0`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.4+k3s1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

After importing a K3s cluster, when looking into a created daemonset, we see that there is a `publicEndpoints` annotation such as the following:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    field.cattle.io/creatorId: user-pt9fx
    field.cattle.io/publicEndpoints: '[{"port":30456,"protocol":"TCP","serviceName":"test-94402:default-95981-nodeport","allNodes":true}]'
```
Considering it is a Rancher annotation that is getting added to this workload, I would expect it to be a designed K8s field, but it is not. RKE2/K3s clusters should properly get the `addresses` field in the `publicEndpoints` annotation as right now, it is currently missing.

**To Reproduce**

1. Create a standalone K3s cluster and import it into Rancher. Ensure that it is using traefik as the Ingress.
2. Navigate to Rancher UI > Imported Cluster > Workload > Dameonsets.
3. In `kube-system`, you should have have a traefik dameonset. Edit the YAML and you should see a similar YAML as seen above.

**Result**
The `addresses` is not seen in the `publicEndpoints`.

**Expected Result**

`addresses` should be seen in the `publicEndpoints`.
