### ISSUE TITLE
[BUG] failed to parse constraint version >= 2.7.0.0 < 2.8.0-0: improper constraint: >= 2.7.0.0 < 2.8.0-0

### ISSUE THREAD

**Issue by jbliao** [rancher/rancher#39972]
**Rancher Server Setup**
- Rancher version: `2.7.0`
- Installation option (Docker install/Helm Chart):
   - `Helm on k3s`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  `v1.24.8-k3s1`
- Cluster Type (Local/Downstream):
  - `local`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - `admin`

**Describe the bug**
Got this error message just after deploy rancher helmchart:
```
[ERROR] failed to parse constraint version >= 2.7.0.0 < 2.8.0-0: improper constraint: >= 2.7.0.0 < 2.8.0-0
```
According to https://github.com/Masterminds/semver/blob/master/constraints.go
`validConstraintRegex` must match the given constraint version string, which is `>= 2.7.0.0 < 2.8.0-0` here.
And `validConstraintRegex` would look like below:
```
^(\s*(=||!=|>|<|>=|=>|<=|=<|~|~>|\^)\s*(v?([0-9|x|X|\*]+)(\.[0-9|x|X|\*]+)?(\.[0-9|x|X|\*]+)?(-([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?(\+([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?)\s*)((?:\s+|,\s*)(=||!=|>|<|>=|=>|<=|=<|~|~>|\^)\s*(v?([0-9|x|X|\*]+)(\.[0-9|x|X|\*]+)?(\.[0-9|x|X|\*]+)?(-([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?(\+([0-9A-Za-z\-]+(\.[0-9A-Za-z\-]+)*))?)\s*)*$
```
Which allow version string with 3 digits, but for `2.7.0.0` which is 4 digits.
It may be a typo.

**To Reproduce**

**Result**

**Expected Result**
```
No error log
```

**Screenshots**

**Additional context**

**Comment by niusmallnan** [comment]
This should be caused by this line:

https://github.com/rancher/charts/blob/d0f4ab5acb9173cead5c0b116ccc5b0fb9dc445c/index.yaml#L2494-L2509
```
  - annotations:
      catalog.cattle.io/auto-install: neuvector-crd=match
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: NeuVector
      catalog.cattle.io/kube-version: '>=1.18.0-0 < 1.25.0-0'
      catalog.cattle.io/namespace: cattle-neuvector-system
      catalog.cattle.io/os: linux
      catalog.cattle.io/permit-os: linux
      catalog.cattle.io/provides-gvr: neuvector.com/v1
      catalog.cattle.io/rancher-version: '>= 2.7.0.0 < 2.8.0-0'
      catalog.cattle.io/release-name: neuvector
      catalog.cattle.io/type: cluster-tool
      catalog.cattle.io/ui-component: neuvector
      catalog.cattle.io/upstream-version: 2.2.3
    apiVersion: v1
    appVersion: 5.0.3
```
