### ISSUE TITLE
Unable to change the admin password

### ISSUE THREAD

**Issue by divyashukla25** [rancher/rancher#40117]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart):
   - Helm chart
  - Kubernetes version: v1.24.4+k3s1

Trying to change the admin password but in admin.yaml, it is showing the encrypted password for admin. Could you please tell me, which encryption algo it is using and how we can decrypt. And also how to change the password.

admin.yaml
```
---
apiVersion: management.cattle.io/v3
kind: User
metadata:
  name: admin
  labels:
    created-by: test
    authz.management.cattle.io/bootstrapping: admin-user
username: admin
password: "$2a$12$.DyyasORiWTxwooS2oNUX.kEchlw99v/2EsW.v1.A0.z.XQ1HEx/K"
displayName: "Default Admin"
mustChangePassword: false
enabled: true
```
