### ISSUE TITLE
[BUG] Websockets appear nonfunctional when Rancher is installed in an existing k8s cluster with an alternative ingress controller

### ISSUE THREAD

**Issue by alandsidel** [rancher/rancher#40125]
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K8S 1.24.9
- Proxy/Cert Details: No proxy.  
- Other: Helm chart installed with:
```
      helm install rancher rancher-stable/rancher
      --wait
      --kubeconfig=/home/ansibleadmin/.kube/config
      --version {{ ansiblevars['rancher-ver'] }}
      --namespace cattle-system
      --create-namespace
      --set hostname={{ rancher_host }}
      --set bootstrapPassword={{ temppassword }}
      --set ingress.enabled=false
      --set ingressClassName=nginx
      --set tls=external
```
Created nginx-ingress with yaml:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-lb
  namespace: cattle-system
spec:
  ingressClassName: nginx
  rules:
  - host: {{ rancher_host }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: rancher
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
    - hosts:
      - {{ rancher_host }}
      secretName: rancher-lb-cert
```

**Information about the Cluster**
- Kubernetes version: K8S 1.24.9
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

Cannot view pod logs or open shells.  Attempts all fail to connect / show "disconnected" in the bottom status bar.  Apparently no websocket connectivity.

**To Reproduce**
Install Rancher in a vanilla k8s cluster running metallb as the cluster provided LoadBalancer, with nginx-ingress (note: not ingress-nginx) as the ingress controller as above.

**Result**
A *mostly* functional Rancher installation.  The dashboard and other features work and the cluster can be explored, but some functionality is missing as described above.

**Expected Result**
A functional Rancher installation.

**Additional context**
I believe this is simply some missing configuration for the ingress.  The nginx-ingress documentation mentions that to support websockets, you need to add the annotation `nginx.org/websocket-services` to the ingress configuration, but this requires service details that aren't documented anywhere I have been able to find.
