### ISSUE TITLE
allow read-only users to view metrics of pods

### ISSUE THREAD

**Issue by Rez0k** [rancher/rancher#40182]
Hi,
im trying to allow read-only users to view metrics of pods
I tried adding those to my rule
```
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - list
- apiGroups:
  - '*'
  resources:
  - services/proxy
  verbs:
  - create
 ```
but I can't see the metrics tab
what is the correct configuration?
(it's working if I am using * on apigroups and resources)
![image](https://user-images.githubusercontent.com/23296337/212841086-6dd5cbba-4290-49ed-8dc0-621345c5c231.png)
