### ISSUE TITLE
[rancher-compose] rancher-compose up hangs at "Starting"

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#4019]
Rancher Version: v0.51.0
Rancher Compose: v0.7.0
Docker Version: 1.10.3
OS: OS X 10.11.4 Beta

## Task:
I want to create a Gitlab instance on a remote rancher instance (which contains one host with multiple working stacks already).

## Steps to Reproduce: 
**1. create this `docker-compose.yml`:**
```
GitLab:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gitlab/gitlab-ce:latest
  volumes:
  - /opt/gitlab/config:/etc/gitlab
  - /opt/gitlab/logs:/var/log/gitlab
  - /opt/gitlab/data:/var/opt/gitlab
  stdin_open: true
```

**2. execute `rancher-compose up`**

## Results: 
```
INFO[0001] Creating stack gitlab
INFO[0002] Creating service GitLab
INFO[0005] Creating service GitLab-Runner
INFO[0006] Project [gitlab]: Starting project
INFO[0006] [0/2] [GitLab]: Starting
```
It hangs forever at the last line.
 
In the webapp it looks like this:
![rancher 2016-03-18 00-37-02](https://cloud.githubusercontent.com/assets/7140800/13864416/8f1c6812-eca1-11e5-879a-529f28f464a0.png)

**Comment by deniseschannon** [comment]
Where is the Gitlab-Runner service that's in the logs for rancher-compose?

Also, would you be willing to upgrade to v0.63.1 as we have introduced error state of containers, which would help determine why your container is not launching. Otherwise, you could look in the server logs to see what the issue is.

**Comment by dj-hedgehog** [comment]
I tried it with different docker-compose.yml. Hence there is no Gitlab-Runner in the docker-compose.yml. The result is still the same. I also just tried creating an ordinary MongoDB stack from the UI catalog. It hangs at "Activating" as well.

I'm no Admin in this Rancher-instance yet. I'll ask for it to be updated and will get back as soon as its done and I got a proper error.

**Comment by dj-hedgehog** [comment]
So I installed Rancher v0.59.1, then registered the host to Rancher as told in Add Hosts -> Custom.
Then I went to the catalog and launched the Gitlab Community image from the community catalog.
It still stays forever at `Activating`: 

![image](https://cloud.githubusercontent.com/assets/7140800/13898078/2facb036-edc7-11e5-92c1-1a4ce3a1c482.png)

![rancher 2016-03-19 11-42-14](https://cloud.githubusercontent.com/assets/7140800/13898094/b04ddd64-edc7-11e5-9ed6-ab1505ead918.png)

![rancher 2016-03-19 11-46-17](https://cloud.githubusercontent.com/assets/7140800/13898121/4644c760-edc8-11e5-9878-32745de65794.png)

**Comment by deniseschannon** [comment]
It's stuck in "Activating" state because the main service "gitlab-server" is unable to start for some reason. 

The templates in the community catalog are not maintained by Rancher so you'd need to make an issue open in the rancher/community-catalog repo if you have specific questions on those templates. 

For your original issue, if you could share your entire docker-compose.yml, then I could see why it might be stuck in Activating. As the steps in your rancher-compose output indicate there are at least 2 services. 

```
INFO[0006] [0/2] [GitLab]: Starting
```

**Comment by dj-hedgehog** [comment]
After upgrading to v0.63.1 and looking into the containers I found out that the problem was that gitlab_server couldn't bind itself to port 22 and 80. 

I altered my docker-compose file to switch to different ports and bam, it works :)

```
gitlab-server:
  hostname: my.host.com
  ports:
  - 8101:22/tcp
  - 8100:8100/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://my.host.com:8100'
      gitlab_rails['gitlab_shell_ssh_port'] = 8101
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data
```
