### ISSUE TITLE
MonitoringV2 sometimes includes an alert name in the subject of the email and sometimes it does not

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40252]
Rancher Cluster:
Rancher version: 2.5.5
Number of nodes:
Node OS version:

Downstream Cluster:
Number of Downstream clusters:
Node OS:
RKE/RKE2/K3S version:
Kubernetes version:
CNI:

Longhorn:
Longhorn version:
CPU per node:
Memory per node:
Disk type: HDD/SSD/NVMe
Network bandwidth between the nodes:

Other:
Underlying Infrastructure: AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal

ssue description:
MonitoringV2 sometimes includes an alert name in the subject of the email and when multiple alerts are triggered, it does not show the alert name.

Business impact:
The customer is unable to find what alert is triggered when multiple alerts are fired at the same time.

Troubleshooting steps:
No

Repro steps:

    Fire multiple alerts at the same time.

Workaround:
Is workararound available and implemented? No
What is the workaround:

Actual behavior:
Multiple alerts fired at the same time don’t have an alert name in the alert

Expected behavior:
Multiple alerts fired at the same time should have an alert name in the alert, like it is there in a single alert.

Files, logs, traces:
Single alert containing alert name at the starting

[FIRING:1] (Cluster-CPU-usage-more-than-95% cattle-monitoring-system/rancher-monitoring-prometheus critical [realtime])

 

Multiple alerts missing the alert name at the starting

[FIRING:2] ([Warning] [merchantscreening] cattle-monitoring-system/rancher-monitoring-prometheus [online])

[FIRING:2]kube-state-metrics (Deployments-have-lower-number-of-pods-in-card-merchant-screening-* http 10.42.152.151:8080 [Warning] rancher-monitoring-kube-state-metrics-5c549477ff-wgccj [merchantscreening] cattle-monitoring-system/rancher-monitoring-

Additional notes:
SURE-5088

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x

**Comment by stormqueen1990** [comment]
Since this behaviour was reproducible on our chart, I decided to give it a try with the upstream version of the Kube Prometheus Stack (`kube-prometheus-stack`) chart. I installed chart version 45.4.0 from the `prometheus-community` Helm repository in a downstream RKE cluster with Kubernetes v1.25.6 on Rancher 2.7-head.

<details>
<summary>Setup instructions & replication steps</summary>

1. Add the `prometheus-community` Helm repository to your local Helm install:
    ```shell
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    ```

1. Change the Helm driver so that installation does not fail on the downstream cluster with an HTTP 413:
    ```shell
    export HELM_DRIVER=configmap
    ```

1. Targeting the downstream cluster, install the required CRD chart:
    ```shell
    helm upgrade --install prometheus-operator-crds \
      prometheus-community/prometheus-operator-crds \
      --namespace monitoring-system --create-namespace
    ```

1. Create a `values.yaml` with the following content:
    ```
    prometheus:
      prometheusSpec:
        ruleSelector:
          test.example.org/selected-rule: "true"
    ```
    This ensures that alerts generated by `PrometheusRules` that match the selector are going to be picked up by Alertmanager.

1. Install `kube-prometheus-stack`:
    ```shell
    helm upgrade --install kube-prometheus-stack \
      prometheus-community/kube-prometheus-stack \
      --namespace monitoring-system \
      --values values.yaml
    ```

1. Create an echo SMTP server using Python smtpd:
    ```yaml
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: smtp-server
      name: smtp-server
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: smtp-server
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: smtp-server
        spec:
          containers:
          - command:
            - python3
            - -u
            - -m
            - smtpd
            - -c
            - DebuggingServer
            - -n
            - 0.0.0.0:5678
            image: python
            imagePullPolicy: IfNotPresent
            name: python
            ports:
            - containerPort: 5678
              name: smtp-port
              protocol: TCP
          restartPolicy: Always
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: smtp-server
      name: smtp-server
      namespace: default
    spec:
      ports:
      - port: 5678
        protocol: TCP
        targetPort: 5678
      selector:
        app: smtp-server
      type: ClusterIP
    ```

1. Create an `AlertmanagerConfig` to target alerts towards the newly deployed e-mail server in your cluster:
    ```yaml
    apiVersion: monitoring.coreos.com/v1alpha1
    kind: AlertmanagerConfig
    metadata:
      name: test-alert
      namespace: default
    spec:
      receivers:
      - emailConfigs:
        - from: test@example
          requireTLS: false
          sendResolved: true
          smarthost: smtp-server.default.svc:5678
          tlsConfig: {}
          to: recipient@example
        name: test-receiver
      route:
        groupBy: []
        groupInterval: 30s
        groupWait: 15s
        matchers:
        - matchType: =
          name: team
          value: test
        receiver: test-receiver
        repeatInterval: 45s
    ```

1. Create a `PrometheusRule` to fire those alerts at a regular interval:
    ```yaml
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: prom-rule-test
      namespace: default
      labels:
        test.example.org/selected-rule: "true"
    spec:
      groups:
      - name: test-group
        rules:
        - alert: test-alert
          expr: vector(1)
          for: 0s
          labels:
            namespace: default
            severity: none
            team: test
    ```

1. Watch the `smtp-server` logs for e-mails coming in:
    ```shell
    kubectl logs -f deploy/smtp-server
    ```
    
    Notice that the e-mails contain the alert name `test-alert` in the subject line:
    ```
    Subject: [FIRING:1] default (test-alert monitoring-system/kube-prometheus-stack-prometheus none test)
    ```

1. Create a new `PrometheusRule`:
    ```yaml
    apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: prom-rule-second-test
      namespace: default
      labels:
        test.example.org/selected-rule: "true"
    spec:
      groups:
      - name: test-group
        rules:
        - alert: test-second-alert
          expr: vector(1)
          for: 0s
          labels:
            namespace: default
            severity: none
            team: test
    ```

1. Notice that in the output for `smtp-server` the e-mails now show `FIRING:2` without an alert name:
    ```
    Subject: [FIRING:2] default (monitoring-system/kube-prometheus-stack-prometheus none test)
    ```
   
</details>

Using the above setup instructions, I was able to confirm the same behaviour happens with the upstream chart. Whenever a single alert is firing, the e-mail is sent with the alert name in the subject line. If more than one alert is fired, then the subject line omits the alert name.

* Relevant template: https://github.com/prometheus/alertmanager/blob/eea788a968c870e3bd78a228e394f745701f18a0/template/default.tmpl#L4
