### ISSUE TITLE
[BUG] managed cluster lost on migrating Rancher from rke to rke2

### ISSUE THREAD

**Issue by harridu** [rancher/rancher#40322]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): helm chart, RKE2 v1.24.8+rke2r1

**Describe the bug**
After migrating my rancher cluster from RKE to RKE2 (using the restore mechanism as described) all managed clusters based on RKE are back, but my one-and-only managed cluster ("kube003") based on RKE2 v1.24.8+rke2r1 is stuck in Updating. Error message is
```
Configuring bootstrap node(s) custom-7e6e3f6464e0: waiting for plan to be applied
```
In the cluster manager for kube003 is a message
```
the server has asked for the client to provide credentials
```
All clusters are on-premises. The common hostname has been modified in DNS (TTL is 300secs) to point to the new hosts, as requested in the migration guide. It was set on the helm install command line on the new rancher cluster. The native host names of the old cluster nodes have not been preserved.

**Comment by brandond** [comment]
> After migrating my rancher cluster from RKE to RKE2 (using the restore mechanism as described)

Just to clarify - did you install a new RKE2 cluster and migrate the Rancher application over via backup/restore, or did you in-place upgrade your cluster from RKE to RKE2?

**Comment by snasovich** [comment]
@harridu , adding to the above, and assuming it's the Rancher itself that was migrated from RKE1 to RKE2, could you please clarify what exact restore procedure was used, is it https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster 
> using the restore mechanism as described

**Comment by harridu** [comment]
I have set up new hosts rancher01{a..c} using Debian 11 and rke2 v1.24.8+rke2r1. The old hosts (rr0{1..3}) were based upon Debian 11 and rke v1.24.8. All hosts are virtual hosts (qemu, libvirt, ...) with 4 cores and 8 GByte RAM.

Migration has been done using the backup helm chart and the restore object (and local S3 storage on minio), as described in the documentation. First the restore operator, the S3 secret and the certificate have been created. kubectl describe did not indicate any problems with the restore object.
````
 apiVersion: resources.cattle.io/v1
 kind: Restore
 metadata:
   name: restore-migration
 spec:
   backupFilename: hourly-95f76381-d9e5-4644-af1b-ca8fdf93a7ae-2023-01-23T10-56-59Z.tar.gz
   prune: false
   storageLocation:
     s3:
       bucketName: rancher01
       credentialSecretName: rancher-backup-s3
       credentialSecretNamespace: cattle-resources-system
       endpoint: minio.example.com:9010
       folder: backup
```
Next rancher was installed using 
```
helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher01.example.com --set ingress.tls.source=secret --version 2.6.9
```
