### ISSUE TITLE
Metrics for nginx and kube-controller-manager cannot be scraped in harvester 1.0.3

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40320]
Harvester Cluster:
Harvester version: 1.0.3

Issue description:

Nginx and kube-controller-manager metric targets are not activated by default in the rancher-monitoring helm preinstalled by the harvester installer.

The customer has added the following values to the chart via patching the fleets ManagedChart rancher-monitor by:

rke2Etcd :
enabled : true

rke2IngressNginx :
enabled : true

rke2Scheduler :
enabled : true

rke2ControllerManager :
enabled : true

ingressNginx :
enabled : false

The metrics for etcd and the scheduler are working fine. just the pushprox client for nginx and kube-controller-manager cannot gather the metrics
The same works fine for all additional metrics targets in harvester 1.0.2.

Customer can see the following error message in the harvester 1.0.3 clusters:
e.g pushprox-kube-controller-manager-client-bvxz6 :
level=info ts=2022-10-18T16:14:10.752Z caller=main.go:113 msg="Pushed failed scrape response"
level=info ts=2022-10-18T16:15:10.751Z caller=main.go:232 msg="Got scrape request" scrape_id=521299c2-ce81-42d3-b77e-1c1d5d1683c1 url=http://10.2.53.12:10252/metrics
level=error ts=2022-10-18T16:15:10.752Z caller=main.go:101 err="failed to scrape http://127.0.0.1:10252/metrics: Get \"[http://127.0.0.1:10252/metrics\](http://127.0.0.1:10252/metrics/)": dial tcp 127.0.0.1:10252: connect: connection refused"

and pushprox-ingress-nginx-client-zn6ls
level=info ts=2022-10-21T06:15:55.989Z caller=main.go:113 msg="Pushed failed scrape response"
level=info ts=2022-10-21T06:16:55.988Z caller=main.go:232 msg="Got scrape request" scrape_id=36916191-0681-4192-8518-2075cbe57a94 url=http://10.2.53.11:10254/metrics
level=error ts=2022-10-21T06:16:55.988Z caller=main.go:101 err="failed to scrape http://127.0.0.1:10254/metrics: Get \"[http://127.0.0.1:10254/metrics\](http://127.0.0.1:10254/metrics/)": dial tcp 127.0.0.1:10254: connect: connection refused"

It seems that the metrics port has changed with the newer RKE version:

The nginx metrics are available in the corresponding pods via
curl http://127.0.0.1:10254/metrics
and controller-manager via
curl -k https://localhost:10257/metrics, but the access is now secured by a token:
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {

},
"status": "Failure",
"message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
"reason": "Forbidden",
"details": {

},
"code": 403
}

For NGINX they found the following general RKE2 issue https://github.com/rancher/charts/issues/2042, which is still open.

Workaround:
Is workararound available and implemented? no
**

Actual behavior:
Scraping nginx and kube-controller-manager metrics is not possible

Expected behavior:
It should be possible to scrape nginx and kube-controller-manager metrics

SURE-5455

**Comment by w13915984028** [comment]
For rke2ControllerManager:

The metricsPort is 10257 in v1.0.3, it is not the default  10252, user needs to change the managedchart as following

```
kubectl edit managedchart -n fleet-local pushprox-kube-etcd-proxy-57df468748-l4s76

    rke2ControllerManager:
      enabled: true
      metricsPort: 10257
    rke2Etcd:
      enabled: true
```

After that, we get the below log:
```
harv41:~ # kubectl logs -n cattle-monitoring-system pushprox-kube-controller-manager-client-kmjhd
level=info ts=2023-02-08T11:28:47.857Z caller=main.go:269 msg="URL and FQDN info" proxy_url=http://pushprox-kube-controller-manager-proxy.cattle-monitoring-system.svc:8080/ fqdn=192.168.122.141
level=info ts=2023-02-08T11:29:03.862Z caller=main.go:232 msg="Got scrape request" scrape_id=df4e4fe0-f9d1-48a3-a533-f5683113c173 url="http://192.168.122.141:10257/metrics?_scheme=https"
level=error ts=2023-02-08T11:29:03.875Z caller=main.go:101 err="failed to scrape https://127.0.0.1:10257/metrics: Get \"https://127.0.0.1:10257/metrics\": x509: certificate signed by unknown authority"
level=info ts=2023-02-08T11:29:03.876Z caller=main.go:113 msg="Pushed failed scrape response"
level=info ts=2023-02-08T11:30:11.642Z caller=main.go:232 msg="Got scrape request" scrape_id=1618df57-ea3f-4387-b4a3-3623847f9d97 url=http://192.168.122.141:10257/metrics
level=info ts=2023-02-08T11:30:11.642Z caller=main.go:167 scrape_id=1618df57-ea3f-4387-b4a3-3623847f9d97 msg="Retrieved scrape response"
level=info ts=2023-02-08T11:30:11.643Z caller=main.go:173 scrape_id=1618df57-ea3f-4387-b4a3-3623847f9d97 msg="Pushed scrape result"
level=info ts=2023-02-08T11:31:11.643Z caller=main.go:232 msg="Got scrape request" scrape_id=85d1014e-f168-4bd9-b9f0-bcb04771aee5 url=http://192.168.122.141:10257/metrics
level=info ts=2023-02-08T11:31:11.644Z caller=main.go:167 scrape_id=85d1014e-f168-4bd9-b9f0-bcb04771aee5 msg="Retrieved scrape response"
level=info ts=2023-02-08T11:31:11.644Z caller=main.go:173 scrape_id=85d1014e-f168-4bd9-b9f0-bcb04771aee5 msg="Pushed scrape result"
```

except the first failure (maybe the ENV is not fully ready), later all scrapes are successful.

**Comment by w13915984028** [comment]
For rke2-ingress-nginx:

the POD metrics port 10254 is not mapped to host level, it could be accessed inside POD, but in HOST and other PODs, it is not accessible

// inside POD
harv41:~ # kubectl exec -i -t  -n kube-system rke2-ingress-nginx-controller-6qb8s -- /bin/sh

```
sh-4.4$ curl http://localhost:10254/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 2.2382e-05
go_gc_duration_seconds{quantile="0.25"} 3.178e-05
go_gc_duration_seconds{quantile="0.5"} 5.1247e-05
go_gc_duration_seconds{quantile="0.75"} 0.000107624
go_gc_duration_seconds{quantile="1"} 0.001801615
go_gc_duration_seconds_sum 0.003688788
go_gc_duration_seconds_count 27
```

// from HOST
hharv41:~ # curl http://localhost:10254/metrics
curl: (7) Failed to connect to localhost port 10254: Connection refused


// POD port
```
kubectl get pods  -n kube-system rke2-ingress-nginx-controller-6qb8s -o yaml
...
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1

    name: rke2-ingress-nginx-controller

    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      name: https
      protocol: TCP
    - containerPort: 8444
      name: webhook
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP

```




// ETCD POD
// the POD port 2381 is mapped to host level, it could be accessed inside POD and HOST
```
kubectl get pods -n kube-system etcd-harv41 -o yaml
...
    name: etcd
...
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /health?serializable=true
        port: 2381
        scheme: HTTP
```

// from HOST
```
harv41:~ # curl http://localhost:2381/metrics
# HELP etcd_cluster_version Which version is running. 1 for 'cluster_version' label with current cluster version
# TYPE etcd_cluster_version gauge
etcd_cluster_version{cluster_version="3.5"} 1
# HELP etcd_debugging_auth_revision The current revision of auth store.
# TYPE etcd_debugging_auth_revision gauge
etcd_debugging_auth_revision 1
# HELP etcd_debugging_disk_backend_commit_rebalance_duration_seconds The latency distributions of commit.rebalance called by bboltdb backend.
# TYPE etcd_debugging_disk_backend_commit_rebalance_duration_seconds histogram
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.001"} 77841
etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{le="0.002"} 77848
```


// workaround

try to add "host: localhost" to "rke2-ingress-nginx-controller", it will cause the POD cannot start successfully

continue checking root cause
