### ISSUE TITLE
Metadata "links" contains slash, messes up confd

### ISSUE THREAD

**Issue by michaellopez** [rancher/rancher#4032]
Rancher Version: v0.59.1

Docker Version: Docker version 1.9.1, build 994543b

OS: RancherOS version v0.4.2

Steps to Reproduce: Run the following compose file:

```yml
other:
  image: nginx:1.9.11
  ports:
    - 80
  labels:
    io.rancher.container.hostname_override: container_name
  
web:
  image: nginx:1.9.11
  ports:
    - 80
    - 443
  labels:
    io.rancher.sidekicks: conf
    io.rancher.container.hostname_override: container_name
  links:
    - other:something
  volumes_from:
    - conf

conf:
  image: nginx:1.9.11
  labels:
    io.rancher.container.hostname_override: container_name
```

Then exec into web container and fetch `http://rancher-metadata/latest/self/stack/services/web/links`

Results: 
`the-stack-name/other`

Expected:
`other:something` as per documentation at http://docs.rancher.com/rancher/metadata-service/#service 

| Fields | Description |
|--------|------------------|
| `links` | List of linked services. Format for links is `stack_name/service_name:service_alias`. If the service is in the same stack, there will be no `stack_name`. |

If the endpoint was actually behaving according to docs, there is still the possibility of a slash in the value from `links`. Using [confd](https://github.com/kelseyhightower/confd) I get the following:

```
# /etc/confd/conf.d/default.toml
[template]
src = "default.tmpl"
dest = "/tmp/default.conf"
keys = [
  "/self/service/metadata/",
  "/self/stack/"
]
```

```
# /etc/confd/templates/default.tmpl
{{range lsdir "/self/stack/services/web/links" }}
  {{.}}
{{end}}
```

```
# /confd -onetime --backend rancher --prefix /2015-12-19 && cat /tmp/default.conf
2016-03-18T16:20:09Z metadata-tester_web_1 /confd[587]: INFO Backend set to rancher
2016-03-18T16:20:09Z metadata-tester_web_1 /confd[587]: INFO Starting confd
2016-03-18T16:20:09Z metadata-tester_web_1 /confd[587]: INFO Backend nodes set to
2016-03-18T16:20:09Z metadata-tester_web_1 /confd[587]: INFO Using Rancher Metadata URL: http://rancher-metadata

  metadata-tester
```
Notice the missing service name...I'm thinking this is because of the slash? Is there another recommended way of iterating the links in rancher-metadata with confd?

**Comment by cloudnautique** [comment]
Thanks for such a detailed report! 

In looking into this, it appears there is a problem with our metadata server. The links are a map[string]string, and the key is "the-stack-name/other" since it has a "/" in it, the server should be able to take "the-stack-name%2Fother" get the data.

I expect, when this is working that the confd template will look something like:
```
range links...
{{ getv (printf "/self/stack/services/web/links/%s" . )}} 
...
```

**Comment by vincent99** [comment]
Seems like 2 problems.. 

1) The docs say the name will not include the stack if it's the same stack.  So either we should make that ( @alena1108 ) or fix the docs ( @deniseschannon ).

2) Metadata/Gorilla mux doesn't urldecode so the string doesn't match a metadata key.  @joshwget can you look at that?

**Comment by alena1108** [comment]
@vincent99 I think we should just fix the docs for now as even if we put a code fix to not include / if it's the same stack, we will still hit the problem for the diff stacks use case.

**Comment by michaellopez** [comment]
Thanks for the fast response. I'll hardcore for now and wait eagerly for a fix.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher-metadata/pull/15

**Comment by deniseschannon** [comment]
Updated the docs to 
```
List of linked services. Format for links is stack_name/service_name:service_alias.
```
Verified with v1.0.0-rc6 that the http://rancher-metadata/latest/self/stack/services/web/links is getting `<stack_name>%2Fother`, but still missing the `service alias` for this link.

**Comment by deniseschannon** [comment]
Spoke with @alena1108. When using `http://rancher-metadata/latest/self/stack/services/web/links` you get the key, which will be `<stack_name>%2Fother`. When you ping `http://rancher-metadata/latest/self/stack/services/web/links/<stack_name>%2Fother`, you would get the value `something`. It shows up in metadata as map of keys/values.

If you added another link to the service, you would get the list of services. 

Sample docker-compose.yml
```
other:
  image: nginx:1.9.11
  ports:
    - 80
  labels:
    io.rancher.container.hostname_override: container_name

web:
  image: nginx:1.9.11
  ports:
    - 80
    - 443
  labels:
    io.rancher.sidekicks: conf
    io.rancher.container.hostname_override: container_name
  links:
    - other:something
    - test:alias1
  volumes_from:
    - conf

conf:
  image: nginx:1.9.11
  labels:
    io.rancher.container.hostname_override: container_name

test:
  image: nginx:1.9.11
```

Using `http://rancher-metadata/latest/self/stack/services/web/links` would return:

```
<stack_name>%2Fother
<stack_name>%2Ftest
```

You can drill down to the specific link to get the service alias.
