### ISSUE TITLE
rancher-charts/rancher-alerting-drivers

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40347]

**Comment by aiyengar2** [comment]
rancher-alerting-drivers's `questions.yml` UI is overridden by Rancher Dashboard, so the fix to add in the following box needs to be done by the Rancher UI team:

```yaml
  - variable: global.cattle.psp.enabled
    default: "false"
    description: "Flag to enable or disable the installation of PodSecurityPolicies by this chart in the target cluster. If the cluster is running Kubernetes 1.25+, you must update this value to false."
    label: "Enable PodSecurityPolicies"
    type: boolean
    group: "Security Settings"
```
