### ISSUE TITLE
Update rancher-charts/rancher-monitoring chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40350]
### Parent issue: rancher/rancher#40331
---
Implement the changes specified in the parent issue for the rancher-monitoring chart and the following subcharts:
- [x] rancher-charts/prometheus-federator
- [x] rancher-charts/rancher-grafana
- [x] rancher-charts/rancher-kube-state-metrics
- [x] rancher-charts/rancher-pushprox
- [x] rancher-charts/rancher-windows-exporter
- [x] rancher-charts/rancher-node-exporter
- [x] rancher-charts/rancher-project-monitoring

**Comment by aiyengar2** [comment]
Note: I'm adding `validate-psp-install.yaml` to the rancher-pushprox chart since there are standalone use-cases for it, although it's hidden on the Rancher UI and not explicitly supported.

However, since it is hidden I am not incorporating the `questions.yml` change and I am putting the README.md note directly in the README.md.

**Comment by aiyengar2** [comment]
rancher-monitoring-crd chart installs Prometheus Operator CRDs via a Job, we need a UI issue to make sure that the value that is set for `global.cattle.psp.enabled` is also passed down to the CRD chart.

ref: https://github.com/rancher/dashboard/issues/8062

**Comment by aiyengar2** [comment]
rancher-monitoring's `questions.yml` UI is overridden by Rancher Dashboard, so the fix to add in the following box needs to be done by the Rancher UI team:

```yaml
  - variable: global.cattle.psp.enabled
    default: "false"
    description: "Flag to enable or disable the installation of PodSecurityPolicies by this chart in the target cluster. If the cluster is running Kubernetes 1.25+, you must update this value to false."
    label: "Enable PodSecurityPolicies"
    type: boolean
    group: "Security Settings"
```

ref: https://github.com/rancher/dashboard/issues/8053
