### ISSUE TITLE
Ability to add nodeselector/tolerations to cluster autoscaler[RFE] 

### ISSUE THREAD

**Issue by dylanhitt** [rancher/rancher#40380]
**Is your feature request related to a problem? Please describe.**
We have a very specific configuration on a bare metal cluster. The networking for both in cluster and the hosts is extremely specific. I don't want to get into the details, but it is vital that the autoscaler is scheduled to a specific set of nodes. We've been able to use nodeselector/tolerations with the rest of the services and we would like to do the same for the DNS autoscaler.

**Describe the solution you'd like**
Input in the cluster config: 
```yaml
dns:
    linear_autoscaler_params:
      cores_per_replica: 128
      max: 3
      min: 3
      nodes_per_replica: 1
      prevent_single_point_failure: true
      tolerations: {}
      node_selector: {}
```

**Describe alternatives you've considered**
Using add_ons to to apply the deployment again. This issue with it is that it can easily fall out of sync with RKE based deployment.
