### ISSUE TITLE
[BUG] dashboard login error while using SSL/TLS termination

### ISSUE THREAD

**Issue by owenchenxy** [rancher/rancher#40422]
I installed rancher using helm command below:
```
helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin \
  --set tls=external
```

I used istio gateway and virtual service as proxy and L7 load balancer. In virtual service config I set header `x-forwarded-proto: https` to terminate SSL/TLS.
```
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-ingress
      enabled: true
      label:
        istio: istio-ingressgateway
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "false"
        affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: istio
                          operator: In
                          values:
                            - istio-ingressgateway
                    topologyKey: "kubernetes.io/hostname"

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*/*"
  - port:
      number: 443
      name: http_s
      protocol: HTTP
    hosts:
    - "*/*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rancher
spec:
  hosts:
    - "rancher.my.org"
  gateways:
    - "istio-ingress-gateway"
  http:
    - match:
          - uri:
              prefix: /dashboard/
          - uri:
              prefix: /v1/
          - uri:
              prefix: /v3/
          - uri:
              prefix: /v3-public/
          - uri:
              prefix: /k8s/
          - uri:
              prefix: /api/
          - uri:
              prefix: /apis/
      route:
        - destination:
            host: rancher.cattle-system.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                x-forwarded-proto: https
```

login site can be loaded, but error occurred while logging in:
<img width="1726" alt="Screen Shot 2023-02-06 at 10 03 08" src="https://user-images.githubusercontent.com/31439930/216865799-91bafd03-ffec-4228-b8b2-66c46008ad8e.png">

I found a similar issue #26422, #26434, which said this was fixed in version 2.4.2. My version is below:
```
➜  ~ helm list -A
NAME             	NAMESPACE                	REVISION	UPDATED                                	STATUS  	CHART                                                                                   	APP VERSION
fleet            	cattle-fleet-system      	1       	2023-02-05 13:03:29.630596943 +0000 UTC	deployed	fleet-101.0.1+up0.5.1                                                                   	0.5.1
fleet-agent-local	cattle-fleet-local-system	6       	2023-02-05 23:07:26.646373283 +0000 UTC	deployed	fleet-agent-local-v0.0.0+s-8b93727e6b501f4a7a6d7e1eafa4836900f2814382605d5f7aa500c80c4e5
fleet-crd        	cattle-fleet-system      	1       	2023-02-05 13:03:19.275970203 +0000 UTC	deployed	fleet-crd-101.0.1+up0.5.1                                                               	0.5.1
rancher          	cattle-system            	1       	2023-02-05 21:01:39.410366 +0800 CST   	deployed	rancher-2.7.1                                                                           	v2.7.1
rancher-webhook  	cattle-system            	1       	2023-02-05 13:03:51.119898913 +0000 UTC	deployed	rancher-webhook-2.0.0+up0.3.0
```

hope someone can kindly help me out

**Comment by niusmallnan** [comment]
Rancher has never supported access through the istio gateway. Even if it is solved by troubleshooting once, it does not mean that it will always able to work.
Is there any special reason why the standard install cannot be used?

**Comment by owenchenxy** [comment]
no really special reason not to use the standard install. Just because in our environment there's already istio gateway acting as the ingress. I just think it's supposed to work fine as long as I correctly configure my LB(no matter it's istio or some other kind of LB)

**Comment by owenchenxy** [comment]
I think the problem is that I didn't really configure the SSL/TLS in my istio gateway as the rancher login process indeed needs, even if I point all requests to rancher port 80. I fixed it by generate a set of Self-Assigned Certs and configure to use them in Istio gateway. 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-ingress-gateway
spec:
  selector:
    istio: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*/*"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: rancher-credential 
    hosts:
    - "*/*"
```
