### ISSUE TITLE
Namespace Controller creates namespace again, when the project is deleted

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#40645]
**Cluster Setup**
- Kubernetes version: v1.20.15
- Rancher 2.6.9
- Type of Cluster (RKE1, RKE2, k3s, EKS, GKE, AKS, OKE, etc): RKE1
- Installation option (Helm Chart / Custom Installation): Helm prometheus-federator 0.1.1

**Describe the bug**

A project is created on downstream cluster and prometheus-federator created the namespace
`cattle-project-p-jmqqq`.
If the project is deleted in Rancher, the controller creates the namespace again and again, out of scope of the user because the project doesn't exists

**To Reproduce**
Create Pproject
Create namespace in project
`cattle-project-p-jmqqq` appears
Delete project 

**Result**
`cattle-project-p-jmqqq` exists without corresponding project

**Expected Result**

`cattle-project-p-jmqqq` should deleted as well.

**Screenshots**

**Additional context**
@aiyengar2 : I think this was the behavior in this [function](https://github.com/rancher/helm-project-operator/blob/51c8c99ef7f4c29c92dc03e8ef8e8dbb231c49e4/pkg/controllers/namespace/controller.go#L88)

**Comment by eumel8** [comment]
Hello @aiyengar2 

the left namespace has the following label

```yaml
  labels:
    field.cattle.io/projectId: p-xxxx
    helm.cattle.io/helm-project-operated: 'true'
    helm.cattle.io/helm-project-operator-orphaned: 'true'
    helm.cattle.io/projectId: p-xxxxxx
    kubernetes.io/metadata.name: cattle-project-p-xxxxxx
    objectset.rio.cattle.io/hash: 244ac0a875e2b8deec08969b192e174205a719def
```

I think we have meanwhile hundreds of them. The problem is: the user had the role project owner at the cluster and the project is removed. At the end the user has no access anymore to the cluster and also not to this namespace.
Or I understand the Rancher Project Concept wrong
