### ISSUE TITLE
Cannot set proxy environment variables for fluentd in rancher-logging chart

### ISSUE THREAD

**Issue by sanjay920** [rancher/rancher#40656]
### Issue description:
The fluentd spec in a banzai cloud logging operator resource permits definition of envVars (https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/fluentd_types/#fluentdspec-envvars), but these are not exposed in the rancher-logging chart (https://github.com/rancher/charts/blob/release-v2.6/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.12.0/templates/loggings/root/logging.yaml). As a result a user logging to an external endpoint, e.g. datadog, in an environment without transparent internet access that requires a proxy configuration, is unable to set the proxy environment variable settings for fluentd.

### Business impact:
rancher-logging chart does not work for user requiring a proxy configuration to log to an external endpoint

### Workaround:
Is workararound available and implemented? Yes
What is the workaround: Manually edit the logging resource after chart deployment, with caveat that setting will not persist chart upgrades

### Actual behavior:
rancher-logging chart does not permit configuration of fluentd environment variables to enable setting of proxy configuration

### Expected behavior:
rancher-logging chart does permit configuration of fluentd environment variables to enable setting of proxy configuration

**Comment by sanjay920** [comment]
https://github.com/rancher/charts/pull/2365 resolves this

**Comment by nickwsuse** [comment]
`Verified on v2.7.2-rc8`

I see the `env` option under fluentd in the chart's values.yaml

```
fluentd:
  bufferStorageVolume: {}
  env: null
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    tcpSocket:
      port: 24240
  nodeSelector: {}
  resources: {}
  tolerations: {}
```
