### ISSUE TITLE
[BUG] tcp-services ingress-nginx-controller not forward realip

### ISSUE THREAD

**Issue by todeb** [rancher/rancher#40758]
**Rancher Server Setup**
- Rancher version: v2.6.9

**Information about the Cluster**
- Kubernetes version: 1.24.8
- Cluster Type (Local/Downstream):
   - downstream, custom

**Describe the bug**
Connecting via tcp-services showing ingress-controller IP instead of Real Client IP.

**To Reproduce**
Configure tcp and udp services in nginx controller:
```
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
```

Configure service with custom port:
kubctl  edit svc -n ingress-nginx
```
...
    - name: proxied-tcp-54321
      port: 54321
      protocol: TCP
      targetPort: 54321
...
```
kubectl edit cm/ingress-nginx-controller -n ingress-nginx 
```
apiVersion: v1
data:
  real-ip-header: proxy_protocol
  use-forwarded-headers: "true"
  use-proxy-protocol: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.2.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
```

Connect to your service on tcp port from outside cluster.
Observe connection on destination port.

**Result**
Ingress-controller IP.

**Expected Result**
Real Client IP

**Comment by todeb** [comment]
adding service definition where also  externalTrafficPolicy is set to Local
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app.kubernetes.io/name: ingress-nginx
    name: ingress-nginx
    namespace: ingress-nginx
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.43.129.64
    clusterIPs:
    - 10.43.129.64
    externalTrafficPolicy: Local
    healthCheckNodePort: 30681
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerIP: 192.168.2.10
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: proxied-tcp-54321
      port: 54321
      protocol: TCP
      targetPort: 54321
    selector:
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: LoadBalancer
```
