### ISSUE TITLE
Rancher container upgrade shows error when "Start before stopping" checkbox selected

### ISSUE THREAD

**Issue by bartovski** [rancher/rancher#40869]
Rancher v1.6.30
I'm trying to reduce downtime when deploying new versions and when upgrading service, there is option: 
![Start before stopping](https://i.stack.imgur.com/mRQOD.png)
When I select it and click Upgrade - Rancher shows error:
![Error](https://i.stack.imgur.com/1BA9y.png)

rancher-compose.yml settings shown in Rancher:

```
version: '2'
services:
  service-name:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```

rancher-compose.yml in IDE: ![rancher-compose.yml](https://i.stack.imgur.com/383m3.png)

I tried retainIp instead of retain_ip, tried removing it and place in another block, didn't help.
