### ISSUE TITLE
cert-manager `v1.7.1` not properly applying resources to standalone RKE1 clusters with PSACT, but `v1.11.0` does

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#40880]
**RKE version:** `v1.4.4-rc3`

**Docker version: (`docker version`,`docker info` preferred)** 20.10.21

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**cluster.yml file:**
```
kubernetes_version: v1.24.10-rancher4-1
nodes:
  - address: <retracted>
    port: 22
    internal_address: <retracted>
    ssh_key_path: <retracted>
    user: ubuntu
    role: [etcd, controlplane,worker]
  - address: <retracted>
    port: 22
    internal_address: <retracted>
    ssh_key_path: <retracted>
    user: ubuntu
    role: [etcd, controlplane,worker]
  - address: <retracted>
    port: 22
    internal_address: <retracted>
    ssh_key_path: <retracted>
    user: ubuntu
    role: [etcd, controlplane,worker]
services:
   kube-api:
     admission_configuration:
       apiVersion: apiserver.config.k8s.io/v1
       kind: AdmissionConfiguration
       plugins:
         - name: PodSecurity
           configuration:
             apiVersion: pod-security.admission.config.k8s.io/v1beta1
             kind: PodSecurityConfiguration
             defaults:
               enforce: restricted
               enforce-version: latest
             exemptions:
               namespaces:
               - ingress-nginx
               - kube-system
               - cattle-system
               - cattle-epinio-system
               - cattle-fleet-system
               - longhorn-system
               - cattle-neuvector-system
               - cattle-monitoring-system
               - rancher-alerting-drivers
               - cis-operator-system
               - cattle-csp-adapter-system
               - cattle-externalip-system
               - cattle-gatekeeper-system
               - istio-system
               - cattle-istio-system
               - cattle-logging-system
               - cattle-windows-gmsa-system
               - cattle-sriov-system
               - cattle-ui-plugin-system
               - tigera-operator
               runtimeClasses: []
               usernames: []
```

**Issue Description**
When a hardened or non-hardened RKE1 cluster has PSACT configuration in its `cluster.yml`, then using cert-manager `v1.7.1` fails to properly apply resources to the cluster. However, when using `v1.11.0`, then resources are properly applied to the cluster. This is specific to PSACT as removing the configuration from the `cluster.yml`, then this problem is not witnessed.

**Steps to Reproduce:**
1. Using the above `cluster.yml` file, provision a 3 node standalone RKE1 cluster.
2. Run the following series of commands:
```
helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
kubectl create ns cattle-system
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.7.1 --debug
```
3. Note that the chart is stuck in a hanging state when you use . Forcefully terminate the process with Ctrl + C.
4. Run `kubectl get pods --namespace cert-manager` and validate you see the following:
```
$ kubectl get pods --namespace cert-manager
No resources found in cert-manager namespace.
```
5. Run the following commands:
```
kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
kubectl delete ns cert-manager
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --debug
kubectl get pods --namespace cert-manager
```
7. Note that the chart installs with cert-manager `v1.11.0` and that resources are properly in the `cert-manager` namespace.

**Results:**
cert-manager `v1.7.1` does not apply resources properly to the cluster whereas `v1.11.0` does just fine; this is specific to PSACT configuration in the `cluster.yml`. The logs of the `helm install` for both versions below:

[v1.7.1.txt](https://github.com/rancher/rke/files/10946999/v1.7.1.txt)
[v1.11.0.txt](https://github.com/rancher/rke/files/10947000/v1.11.0.txt)
