### ISSUE TITLE
external_links gets removed from config, it doesn't work

### ISSUE THREAD

**Issue by fbrbovic** [rancher/rancher#4095]
Rancher Version:
v0.63.0
Docker Version:
Version:      1.10.1
OS: 
RancherOS
Steps to Reproduce: 
Use following : 
```
web-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: busybox
  volumes:
    - /data
web-conf:
  labels:
    io.rancher.container.hostname_override: container_name
  image: ubuntu
  volumes_from:
    - web-data
  external_links:
    - vault/vault:vault
web:
  ports:
    - 8081:80/tcp
  labels:
    io.rancher.sidekicks: web-data,web-conf
  image: ubuntu
  volumes_from:
    - web-data
```
Results: 
```
web-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: busybox
  volumes:
    - /data
web-conf:
  labels:
    io.rancher.container.hostname_override: container_name
  image: ubuntu
  volumes_from:
    - web-data
web:
  ports:
    - 8081:80/tcp
  labels:
    io.rancher.sidekicks: web-data,web-conf
  image: ubuntu
  volumes_from:
    - web-data
```
Expected:

I set the above docker-compose.yml via gui when creating a new stack , but when service is started external link is never linked and it get remvoed from the config.  I do have that external link live and functioning

For some reason external_links are not set and disappear from the config
