### ISSUE TITLE
[BUG] Neuvector install with Rancher not respecting controller.configmap.data?

### ISSUE THREAD

**Issue by t80027t** [rancher/rancher#40989]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.23
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: RKE1 + VMWare

**User Information**
- What is the role of the user logged in?: Admin

**Describe the bug**
controller.configmap.data for Neuvector helm chart values not respected with Rancher install?

**To Reproduce**
Install Neuvector via Rancher Marketplace UI. Edit yaml helm chart values to include settings e.g.

```
controller:
  configmap:
    enabled: true
    data:
      sysinitcfg.yaml: |
        Syslog_ip: 127.0.0.1
        Syslog_Port: 5140
        Syslog_IP_Proto: 17
        Syslog_Level: Info
        Syslog_status: true
        Syslog_Categories:
          - event
          - security-event
          - audit
        Syslog_in_json: true
```

**Result**
Empty config map
```
NAME             DATA   AGE
neuvector-init   0      21m
```

**Expected Result**
Configmap should contain data given by helm chart values
