### ISSUE TITLE
[BUG] Bootstrap secret lifecycle isn't respected

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41021]
**Rancher Server Setup**
- Rancher version: v2.7-head

**Describe the bug**

The RKEBootstrap data secret is deleted after the associated CAPI Machine object transitions into the `Provisioned` phase. This prevents upstream infrastructure providers from working properly, since the system-agent will fail to connect if the bootstrap secret does not exist.

**To Reproduce**

From a QA perspective this is not reproducible, but to reproduce:

- Install DO CAPI provider in cluster
- Apply the following yaml:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DOCluster
metadata:
  name: do-test
  namespace: fleet-default
spec:
  region: nyc3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DOMachineTemplate
metadata:
  name: do-test-0
  namespace: fleet-default
spec:
  template:
    spec:
      size: g-2vcpu-8gb
      image: ubuntu-20-04-x64
      sshKeys:
        - <SSH_KEY>
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  generation: 4
  name: jhyde-do-test
  namespace: fleet-default
spec:
  cloudCredentialSecretName: <SECRET_NAME>
  kubernetesVersion: v1.25.7+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DOCluster
      name: do-test
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: DOMachineTemplate
          name: do-test-0
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120

```

**Result**

`/var/log/cloud-init-output.log` is spammed with the following log message:
```
500 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
```

**Expected Result**

Machine successfully provisions.

**Screenshots**

**Additional context**

The bootstrap secret will now live for a machine object in the cluster until the machine is deleted. This behavior can be changed to instead be deleted after the machine is `Running`, however this change would put rancher in parity with upstream providers.
SURE-6263
