### ISSUE TITLE
[BUG] Alertmanager in Rancher doesn't load receiver configuration with webhook

### ISSUE THREAD

**Issue by MatthiasWer** [rancher/rancher#41030]
**Rancher Server Setup**
- Rancher version: 2.5.16

**Information about the Cluster**
- Kubernetes version: 1.19.6

**Describe the bug**
I try to create a webhook receiver for the monitoring in rancher. Alertmanager doesn't load the receiver if I add the oauth2 part to the http_config. On my local system it works fine. I get the problem only in rancher.

Prometheus version: 2.27.1
Alertmanager version: 0.22.2

This is my receiver.yaml in rancher:
```
webhook_configs:
  - http_config:
      oauth2:
        client_id: id
      tls_config: {}
    send_resolved: false
```

This is the alertmanager config after redeployment:
```
name: Name
  webhook_configs:
  - send_resolved: false
    http_config:
      follow_redirects: true
```

**To Reproduce**
Create a generic webhook receiver and add in the yaml the oauth2 part to the http_config

**Result**

**Expected Result**
Oauth2 works with http_config in an webhook receiver
