### ISSUE TITLE
Cannot retrieve bootstrap password on first login to webgui

### ISSUE THREAD

**Issue by martyav** [rancher/rancher#41177]
This was originally opened by @jakeconnolly on the Rancher Docs repo: https://github.com/rancher/rancher-docs/issues/523

> I'm very new to this.
> 
> I'm running:
> ubuntu 22.04.2
> docker 20.10.21
> 
> I installed rancher using the following command:
> docker run -d --restart=unless-stopped
> -p 80:80 -p 443:443
> -v /opt/rancher:/var/lib/rancher
> --privileged
> rancher/rancher:latest
> 
> I can reach the prompt on the web gui asking me to run:
> docker logs container-id 2>&1 | grep "Bootstrap Password:"
> to get my temporary password. When i run this command after getting the container ID using docker ps, the command returns nothing.
> I have also tried setting the password by adding:
> -e CATTLE_BOOTSTRAP_PASSWORD=password
> to the docker run command, this did not work.
> 
> Thank you for the help.

**Comment by jakefhyde** [comment]
Did you kill the rancher pod and restart it? This would cause rancher to not print the logs. Additionally, setting the environment variable should work. Can you share the output of `docker manifest inspect`? Do the rancher logs show anything potentially anomalous?

**Comment by brobotic** [comment]
I had this same issue. Removing the `2>&1` from the command provided by the web UI revealed that the bootstrap password was indeed in the logs.

Example: `docker logs <container id> | grep -i pass`

**Comment by don-rumata** [comment]
My solution:

```bash
cat docker-compose.yml
```

```yaml
services:
  rancher:
    container_name: rancher
    image: rancher/rancher:${RANCHER_VERSION:-stable}
    ports:
      - "${RANCHER_PORT:-8888}:80"
      - "${RANCHER_SSL_PORT:-8443}:443"
    volumes:
      - /opt/rancher:/var/lib/rancher
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
```

```bash
docker compose up --detach
```

```bash
docker compose exec rancher bash
```

```bash
kubectl get secret --namespace cattle-system bootstrap-secret -o go-emplate='{{.data.bootstrapPassword|base64decode}}{{"\n"}}'
```
