### ISSUE TITLE
[project-monitoring] Can't set remoteWrite option in Helm chart

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#41197]
**Describe the bug**

We want to use the [RemoteWrite](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RemoteWriteSpec) feature of the Prometheus Operator. 
In the [rancher-monitoring chart](https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/101.0.0%2Bup19.0.3/values.yaml#L3015) it's possible, not in the [project-monitoring Helm chart](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/values.yaml)

**To Reproduce**

setup value

**Result**

noting happened

**Expected Result**

expected output in prometheus.env.yaml

```
remoteWrite:
 - oauth2:
   clientId:
    secret:
     key: key
     name: remote-writer
   clientSecret:
    key: secret
    name: remote-writer
   scopes:
   - openid
   tokenUrl: https://keycloak.example.com/auth/realms/default/protocol/openid-connect/token
  url: https://remotelog.example.com/v1/api/v1/write
```

The secret can be currently setup as follow:

```yaml
      prometheus:
        extraSecret:
          data:
            key: xxxxx
            secret: xxxxx
          name: remote-writer
```
