### ISSUE TITLE
[BUG] chartValues for provisioning.cattle.io/v1 downstream cluster not applied

### ISSUE THREAD

**Issue by l-behrens** [rancher/rancher#41238]
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option (Helm Chart):
   - RKE2

**Information about the Cluster**
- Kubernetes version:   v1.24.8+rke2r1 
- Cluster Type (Downstream):
   - Type: Custom on prem

**User Information**
- What is the role of the user logged in?
  -  Project Member

**Describe the bug**
Bug occurs while provisioning a RKE2 downstreamcluster using the calico cni plugin. The cluster is defined via CR (provisioning.cattle.io/v1/Cluster). Inside this resource we configure chart values for rke2-calico:

```
[...]
  rkeConfig:
    chartValues:
      rke2-calico:
        global:
          clusterCIDR: 10.45.0.0/16
          clusterCIDRv4: 10.45.0.0/16
          clusterDNS: 10.46.0.10
          serviceCIDR: 10.46.0.0/16
        tigeraOperator:
          image: rancher/mirrored-calico-operator
          version: v1.28.1
          registry: docker.io
        calicoctl:
          image: rancher/mirrored-calico-ctl
          tag: v3.24.1
        # Tolerations for the tigera/operator pod.
        tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists

        installation:
          enabled: true
          controlPlaneTolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/etcd"
            operator: "Exists"
            effect: "NoExecute"
          calicoNetwork:
            bgp: Disabled
[...]
```
We expect that the helm chart: rke2-calico will be installed with the given configuration.
However looking at the Helm Chart wrapper: `/var/lib/rancher/rke2/server/manifests/rke2-calico.yaml ` we observe that the values are set as follows:

```
[...]
  set:
    global.cattle.systemDefaultRegistry: ""
    global.clusterCIDR: 10.42.0.0/16
    global.clusterCIDRv4: 10.42.0.0/16
    global.clusterCIDRv6: ""
    global.clusterDNS: 10.43.0.10
    global.clusterDomain: cluster.local
    global.rke2DataDir: /var/lib/rancher/rke2
    global.serviceCIDR: 10.43.0.0/16
    global.systemDefaultRegistry: ""
```

**To Reproduce**
create a cluster from a manifest like this:

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: tinylab
  namespace: fleet-default
spec:
  defaultPodSecurityPolicyTemplateName: ""
  kubernetesVersion: v1.24.8+rke2r1

  rke2Config:
    chartValues:
      rke2-calico:
        global:
          clusterCIDR: 10.45.0.0/16
          clusterCIDRv4: 10.45.0.0/16
          clusterDNS: 10.46.0.10
          serviceCIDR: 10.46.0.0/16

    etcd:
      disableSnapshots: true

    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: true
      etcd-expose-metrics: false
      profile: null
    machinePools: []
    machineSelectorConfig:
    - config:
        protect-kernel-defaults: false
    registries:
      configs: {}
      mirrors: {}
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: "1"
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
```

apply this config to the upstream cluster
`kubectl apply -f <cluster-manifest.yaml>`

add a node to the new cluster via registration command from the rancher ui with control and etcd role.

**Result**
The CNI will use the default settings for clusterCIDR (10.42.0.0/16) rather then the chartValue configuration (10.45.0.0/16)

**Expected Result**
The chartValue configuration from the cluster manifest should apply.
