### ISSUE TITLE
[BUG] Machine Cloud-Init does not support #include

### ISSUE THREAD

**Issue by atsai1220** [rancher/rancher#41402]
**Rancher Server Setup**
- Rancher version: v2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart, RKE2

**Information about the Cluster**
- Kubernetes version:  v1.23.15+rke2r1
- Cluster Type (Local/Downstream): Downstream AWS (CAPI)

**Describe the bug**
Leveraging the `#include` feature for user-data will cause a failure. We are unable to have user-data more than 16k due to size restriction from AWS. However, the `machine` driver does not support `#include` directive.

**To Reproduce**
Put this inside user-data for CAPI an rke2 CAPI cluster and you will encounter error described here: https://github.com/rancher/machine/blob/1ab6e014ec703091b38e3a6db32d10f3415a635b/commands/create.go#L611-L646

``` yaml
ami: ami-0638741e0c9aabde6
apiVersion: rke-machine-config.cattle.io/v1
blockDurationMinutes: '0'
deviceName: /dev/sda1
encryptEbsVolume: true
endpoint: null
iamInstanceProfile: foo
insecureTransport: false
instanceType: m5.4xlarge
keypairName: null
kind: Amazonec2Config
metadata:
  name: foo
  namespace: fleet-default
monitoring: false
privateAddressOnly: true
region: us-east-1
requestSpotInstance: false
retries: '5'
rootSize: '300'
securityGroup:
  - 123123
securityGroupReadonly: true
sessionToken: null
spotPrice: '0.50'
sshUser: ubuntu
subnetId: subnet-123123
tags: null
useEbsOptimizedInstance: false
usePrivateAddress: false
userdata: |-
    #include
    https://valid-endpoint.com/cloud-init.yaml
volumeType: gp3
vpcId: vpc-123123
zone: a
```

**Result**

**Expected Result**
Machine driver should parse `#include` and append user provided user-data. This can be viewed here: https://github.com/rancher/machine/blob/1ab6e014ec703091b38e3a6db32d10f3415a635b/commands/create.go#L611-L646

**Screenshots**

**Additional context**
Error message
``` yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: foo
  namespace: fleet-default
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: foo-122
      namespace: fleet-default
    dataSecretName: foo-223
  clusterName: foo
  infrastructureRef: {}
  nodeDeletionTimeout: 10s
status:
  bootstrapReady: true
  failureMessage: >-
    Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=AzureMachine with name
    "foo-123": Trying to access
    option  which does not exist

    THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR

    Type assertion did not go smoothly to string for key 

    [cmdCreateInner] could not alter cloud-init file: existing userdata file
    does not begin with '#!' or '#cloud-config'
  failureReason: CreateError
  lastUpdated: '2023-05-04T05:07:50Z'
  observedGeneration: 3
  phase: Deleting

```
