### ISSUE TITLE
[BUG] XFS PersistentVolumes can't be mounted on Centos 7

### ISSUE THREAD

**Issue by bfbachmann** [rancher/rancher#41414]
**Rancher Server Setup**
- Rancher version: v2.7.2
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: Default

**Information about the Cluster**
- Kubernetes version: v1.23.16
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean droplet

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
XFS PersistentVolumes fail to mount with the following error (note the `invalid argument` at the end of the error message):

```
MountVolume.MountDevice failed for volume "pvc-db411f72-d19a-4dfc-8bd4-f9847ee8e21a" : rpc error: code = Internal desc = mounting failed: exit status 255 cmd: 'mount -t xfs /dev/disk/by-id/scsi-0DO_Volume_pvc-db411f72-d19a-4dfc-8bd4-f9847ee8e21a /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-db411f72-d19a-4dfc-8bd4-f9847ee8e21a/globalmount' output: "mount: mounting /dev/disk/by-id/scsi-0DO_Volume_pvc-db411f72-d19a-4dfc-8bd4-f9847ee8e21a on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-db411f72-d19a-4dfc-8bd4-f9847ee8e21a/globalmount failed: Invalid argument\n"
```

A corresponding kernel error can also be found using `dmesg`:

```
[Mon Aug 22 15:36:40 2022] XFS (vdi): Superblock has unknown read-only compatible features (0x4) enabled. 
[Mon Aug 22 15:36:40 2022] XFS (vdi): Attempted to mount read-only compatible filesystem read-write. 
[Mon Aug 22 15:36:40 2022] XFS (vdi): Filesystem can only be safely mounted read only. 
[Mon Aug 22 15:36:40 2022] XFS (vdi): SB validate failed with error -22.  
```

This appears to be because they are created with reflink=1, which is incompatible with kernels older than 3.16, such as the kernel in centos 7.

Hyperkube images since 1.19 are built by Rancher from ubuntu, which has xfsprogs 5.3.0-1ubuntu2. This defines the default arguments used by mkfs.xfs. These arguments are incompatible with centos 7.

**To Reproduce**
1. Create an RKE cluster using k8s 1.19+(such as 1.21) on Centos 7 nodes
2. Create a PersistentVolume from a storage class that uses XFS (example below is for DigitalOcean droplet, which requires installation of DO storage drivers)

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-xfs-sc
provisioner: dobs.csi.digitalocean.com
parameters:
  type: "standard"
  fsType: "xfs"
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-xfs-sc
```

3. Try use the PV from a pod (example below)

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-do-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-do-volume
      persistentVolumeClaim:
        claimName: my-pvc
```

**Result**
Volume mount fails with the error above, and the pod cannot be created.

**Expected Result**
Volume mounts successfully.

**Screenshots**

**Additional context**
SURE-5279
