### ISSUE TITLE
Add more control for liveness in the helm chart 

### ISSUE THREAD

**Issue by Rez0k** [rancher/rancher#41482]
**Is your feature request related to a problem? Please describe.**
My rancher instance start to restart when I upgraded to version 2.7.3, the reason is liveness
```
  livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds | default 60 }}
      periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 30 }}
``` 
This is the current configuration of rancher liveness probe, on helm install we are getting few more default properties to the liveness section
```
livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 80
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 1
```
I want to control the timeoutSeconds and failiureThreshold by passing a values file, and prevent the liveness probe from failing (without increasing the resources)

**Describe the solution you'd like**
Add support to this values in the helm chart
