### ISSUE TITLE
[BUG] After adding service-account-issuer for conformance test cluster-agent goes into crashloopBrackoff

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#41521]
**Rancher Server Setup**
- Rancher version: v2.7.5-rc1
- Installation option (Docker install/Helm Chart): Docker and Helm both. 
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.26.4-rancher2-1 Or Any k8s version. 
- Cluster Type (Local/Downstream): Downstream Custom.
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom (AWS)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
After adding service-account-issuer for the conformance test cluster-agent goes into CrashloopBackoff. Issue is NOT k8s v1.26 specific.

```
Services:
  kube-api:
    extra_args:
      service-account-issuer: 'https://xx-xx-xx-xx:6443' (Controlplane IP address)
```

**To Reproduce**

1. Create a rancher server v2.7.5-rc1
2. Go ahead and create custom cluster (make sure the NGINX is disabled in Advanced Options) with jenkins job `add custom host`.
3. Once the cluster is in active state, Edit cluster Yaml.
4. Add the following extra argument under the kube-api in service.
Services:
  kube-api:
    extra_args:
      service-account-issuer: 

5. Cluster goes into `updating` state.
6. Once cluster comes back in active state, download kubeconfig file by clicking on Ellipsis. 
7. Click on Explore and try to access the cluster.
8. List all pods using kubeconfig from terminal.

**Result**
1. User gets logged out. 
2. cattle-cluster-agent and calico-kube-controllers status shows CrashloopBrackOff.

**Expected Result**
All the pods' status is active.

**Screenshots**

![Screenshot from 2023-05-11 12-19-18](https://github.com/rancher/rancher/assets/83208989/2eed20e5-8134-4d11-950b-ca53d2dee8b0)

**Comment by vardhaman22** [comment]
the reason behind cluster agent getting stuck in CrashLoopBackOff is that the cluster agent and all other pods have the service account token issued by the previous so kube-api-server starts giving UnAuthorized error for all the requests sent to it by those pods.
One workaround to make the cluster active is delete all the existing pods (in all namespaces) so the newly created pods have service account token issued by the updated issuer.

One other way to keep the cluster active after updating issuer is to keep the earlier issuer in service account issuer list.
to set it we will need to add configuration in following manner while updating the issuer:
```
kube-api:
  extra_args:
    service-account-issuer: 'https://xx.xx.xx.xx:6443' (Control Plane IP address)
  extra_args_array:
    service-account-issuer:
      - rke // keep existing issuer so that pre existing pods continue to work
``` 

the "rke" is the issuer which is set by default from KDM. [ref](https://github.com/rancher/kontainer-driver-metadata/blob/749a0311749a8692dc062938bec24bcf2bbcbf55/pkg/rke/k8s_service_options.go#L449)
