### ISSUE TITLE
[BUG]: missing toleration AKS CriticalAddonsOnly

### ISSUE THREAD

**Issue by nickvth** [rancher/rancher#41578]
**Rancher Server Setup**
- Rancher version: 2.7.3

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Imported = Running kubectl apply onto an existing k8s cluster
Hosted = AKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Add toleration to cattle-cluster-agent and rancher-webhook

CriticalAddonsOnly=true:NoSchedule when using AKS.

Pods are pending.

**To Reproduce**
Run AKS with system node pool + criticaladdons

**Result**

**Expected Result**

```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: CriticalAddonsOnly
        value: "true"

```
