### ISSUE TITLE
Error "failed to wait for roles to be populated" when deploying Apps to user-created Namespaces

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41605]
[SURE-6365](https://jira.suse.com/browse/SURE-6365)

**Comment by eumel8** [comment]
Headed here by Google to find a solution for this error message above. No idea what's the content of this internal SUSE ticket. In my investigation the error occured in the `createNamespace` function of catalogv2 helm ops.  In this function [a namespace condition is checked](https://github.com/rancher/rancher/blob/release/v2.7/pkg/catalogv2/helmop/operation.go#L891-L901) in the namespace annotation. The problematic thing: it checks if the condition exists and returned, or it returned an error.  My target namespace of my catalog app is very old (creationTimestamp: "2020-08-06T07:42:54Z") and doesn't have this condition which comes in a later Rancher release.  Straight forward add this annotation solves the problem and the app can be installed in this namespace:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-11-11T15:33:50Z"},{"Type":"ResourceQuotaValidated","Status":"True","Message":"","LastUpdateTime":"2022-10-24T13:24:40Z"},{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2023-05-20T17:04:29Z"}]}'
```

surely, if the namespace is empty you can delete the namespace and re-creating will have this annotation.

similar issues:
https://github.com/rancher/rancher/issues/37951
https://github.com/rancher/rancher/issues/33554
