### ISSUE TITLE
[BUG] NFS file locks with Kubernetes v1.24.10+ require manual intervention

### ISSUE THREAD

**Issue by km-bh** [rancher/rancher#41601]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm chart; RKE1 v1.24.9-rancher1-1
- Proxy/Cert Details: LetsEncrypt via cert-manager

**Information about the Cluster**
- Kubernetes version: v1.24.13-rancher2-1, v1.24.10-rancher4-1, v1.24.9-rancher2-1 tested
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Rancher-provisioned vmware vSphere nodes, sourced on Ubuntu 20.04 templates

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions: N/A

**Describe the bug**
Kubernetes v1.24.10-rancher4-1 and newer seem to have broken NFS client file locking. We use a number of NFS shares in Persistent Volumes and some databases -- mongodb and mysql in particular -- are no longer able to lock certain files, leading them to exit with errors about no locks being available. File locking works if the rpc-statd service on the underlying node is manually started, but this is not necessary with Kubernetes v1.24.9 and below.

Actually mounting, writing to, and reading NFS shares is not impacted. File locking seems to be the only issue.

If a node is running v1.24.9 and upgraded to v1.24.10+, existing pods are not affected. If a single pod on the node was using NFS file locking, then any new pods are able to successfully lock files even after upgrading Kubernetes. Once all pods using NFS file locking are deleted, new pods are unable to utilize locking on NFS shares.

MongoDB logs show similar entries to this:
> 2023-05-18T19:03:25.914+0000 I STORAGE [initandlisten] exception in initAndListen: DBPathInUse: Unable to lock the lock file: /data/mongod.lock (No locks available). Another mongod instance is already running on the /data directory, terminating

The kernel produces logs similar to this:
> [Thu May 18 15:03:19 2023] lockd: cannot monitor nfs-server.example.org

**To Reproduce**
- Deploy a Kubernetes v1.24.9 (any -rancher subversion)
- Create a Persistent Volume and associated claim that uses default NFS mount options (no mountOptions in storageclass, etc)
- Deploy a database that utilizes file locking (a 3-node mongodb instance with the MongoDB community operator works) using the aforementioned NFS-based persistent volume for its data directory
- Wait for statefulset to become Running
- Upgrade Kubernetes cluster to v1.24.10+ (tested up to v1.24.13-rancher2-1)
- Delete any of the mongodb pods

**Result**
mongodb instances are unable to create a file lock on its lockfile, stating that there are no locks available.

**Expected Result**
mongodb (and other processes) should be able to lock its lock file

**Screenshots**
N/A

**Additional context**
https://github.com/coreos/bugs/issues/2038#issuecomment-313483221 seems to follow the same behavior that we're seeing, but is from 2017. We've allowed Rancher to recreate nodes and have replaced all workers in our testing. The only thing that seems to affect the behavior is the Kubernetes version that we're running. We wanted to upgrade to v1.24.10+ to avoid the known CPU issues, but it appears that either upstream Kubernetes (re-)introduced this bug or the fix to address high dockerd CPU usage.

**Comment by km-bh** [comment]
I believe I've tracked this issue down to this specific commit: https://github.com/rancher/hyperkube-base/commit/bdb81f92258a04cb63d8f9208c86e4618b09bd40

By adding the systemd package to Rancher's hyperkube-base image, it has also pulled in the systemctl binary and this is where things went wrong.

Taking a look at the kubelet container in v1.24.9:
```
root@test1:/# which systemctl
root@test1:/#
```

In a 1.24.10 container:
```
root@test2:/# which systemctl
/usr/bin/systemctl
```

Taking a look at mount.nfs, to see what it does exactly, I found that it wants to run /usr/sbin/start-statd.
```
$ strings /usr/sbin/mount.nfs | grep statd
%s: rpc.statd is not running but is required for remote locking.
   Either use ‘-o nolock’ to keep locks local, or start statd.
%s: rpc.statd is not running but is required for remote locking.
%s: Either use ‘-o nolock’ to keep locks local, or start statd.
/usr/sbin/start-statd
```

/usr/sbin/start-statd is identical on all of the hyperkube image versions that I checked. Here is the important excerpt:
```
# First try systemd if it’s installed.
if [ -d /run/systemd/system ]; then
    # Quit only if the call worked.
    if systemctl start rpc-statd.service; then
        # Ensure systemd knows not to stop rpc.statd or its dependencies
        # on ‘systemctl isolate ..’
        systemctl add-wants --runtime remote-fs.target rpc-statd.service
        exit 0
    fi
fi
cd /
# Fall back to launching it ourselves.
exec rpc.statd --no-notify
```

Specifically: `if systemctl start rpc-statd.service`. In v1.24.9 and lower, this test would fail as the systemctl binary is missing, thus the `exec rpc.statd --no-notify` command would run. However, since systemd was installed in the hyperkube-base image, the systemctl binary is present. However, systemctl does a Bad here and returns an exit code of 0 if it willingly fails to run in a chroot environment.
```
root@test2:/# systemctl start rpc-statd.service
Running in chroot, ignoring command ‘start’
root@test2:/# echo $?
0
```

Now, if I shell into the v1.24.10 kubelet container and manually run `exec rpc.statd --no-notify`, I am able to lock files in my pods as expected.
```
root@test2:~# lslocks
COMMAND           PID   TYPE SIZE MODE  M START END PATH
<...>
flock           31222  FLOCK      WRITE 0     0   0 /var/lib/kubelet/pods/72cd03b8-05ea-424f-afbd-69f41345c5fe/volumes/kubernetes.io~nfs/nfsv3-testing...
```

Once kubelet has started rpc-statd, we can see that there was no need to start the host's rpc-statd service.
```
root@test2:~# systemctl status rpc-statd
○ rpc-statd.service - NFS status monitor for NFSv2/3 locking.
     Loaded: loaded (/lib/systemd/system/rpc-statd.service; enabled-runtime; vendor preset: enabled)
     Active: inactive (dead)
```

**Comment by superseb** [comment]
@rayandas This seems to be a regression after the change in hyperkube-base, can you please check

**Comment by rayandas** [comment]
@superseb Sure. I'll take a look.

**Comment by chiukapoor** [comment]
Hello @km-bh, I am trying to reproduce the issue with the steps mentioned in the issue description but not able to hit the file lock issue.

- Created three EFS store on AWS.
- Deployed a three-node Kubernetes cluster (1.24.9-rancher1-1) on Ubuntu 22.04 AWS.
- Deployed Mongodb community operator on the above cluster.
- Created 3 Persistent Volumes using the NFS stores provided by EFS and the Local hostPath store for logs.
```
# Example PV using NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-volume-example-mongodb-0
    namespace: default
  nfs:
    path: /
    server: REDACTED
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
- Created mongoDBCommunity object with the below yaml
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      serviceName: example-mongodb
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: 
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      template:
        spec:
          initContainers:
          - command:
              - chown
              - -R
              - "2000"
              - /data
            image: busybox
            volumeMounts:
            - mountPath: /data
              name: data-volume
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            name: change-dir-permissions
          volumes:
            - name: custom-volume
              emptyDir: {}
          containers:
          - name: mongodb-agent
            volumeMounts:
              - name: custom-volume
                mountPath: /my-custom-version/mount-path
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: my-user-password
type: Opaque
stringData:
  password: test123
```
- Statefulsets successfully came to running state.
- Upgrade Kubernetes cluster to `v1.24.13-rancher2-1`.
- Restarted/Removed 1 and later all the mongodb pods created by statefulset but pods came back to running state successfully without any file locking issue.

**Comment by chiukapoor** [comment]
Hello @km-bh, I am trying to reproduce the issue with the steps mentioned in the issue description but not able to hit the file lock issue.

- Created three EFS file stores on AWS.
- Deployed a three-node Kubernetes cluster (1.24.9-rancher1-1) on Ubuntu 22.04 AWS.
- Deployed Mongodb community operator on the above cluster.
- Created 3 Persistent Volumes using the NFS stores provided by EFS and the Local hostPath store for logs.
```
# Example PV using NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-volume-example-mongodb-0
    namespace: default
  nfs:
    path: /
    server: REDACTED
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
- Created mongoDBCommunity object with the below yaml
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      serviceName: example-mongodb
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: 
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      template:
        spec:
          initContainers:
          - command:
              - chown
              - -R
              - "2000"
              - /data
            image: busybox
            volumeMounts:
            - mountPath: /data
              name: data-volume
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              runAsGroup: 0
            name: change-dir-permissions
          volumes:
            - name: custom-volume
              emptyDir: {}
          containers:
          - name: mongodb-agent
            volumeMounts:
              - name: custom-volume
                mountPath: /my-custom-version/mount-path
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: my-user-password
type: Opaque
stringData:
  password: REDACTED
```
- Statefulsets successfully came to running state.
- Upgrade Kubernetes cluster to `v1.24.13-rancher2-1`.
- Restarted/Removed 1 and later all the mongodb pods created by statefulset but pods came back to running state successfully without any file locking issue.
