### ISSUE TITLE
[BUG] Rancher assumes all conditions are positive polarity, leading to computing incorrect Rancher API state

### ISSUE THREAD

**Issue by oivindoh** [rancher/rancher#41679]
**Rancher Server Setup**
- Rancher version: 2.7.3 - further setup not relevant

**Describe the bug**
As per [rancher blog](https://www.suse.com/c/rancher_blog/crds-and-custom-kubernetes-controllers-in-rancher/), Rancher uses the conditions of custom resources to inform its own API about the state of a custom resource. If all conditions are True:

> But as a user you might not care about each particular condition value. On Rancher API level, we have State field aggregating the condition values, and going into Active only when all conditions are met.

This is not quite in line with the [kubernetes api convention docs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) where both positive (Good state (tm) assigned the value `True`) and negative polarity (Good state assigned value `False`):

> For some conditions, True represents normal operation, and for some conditions, False represents normal operation. ("Normal-true" conditions are sometimes said to have "positive polarity", and "normal-false" conditions are said to have "negative polarity".) Without further knowledge of the conditions, it is not possible to compute a generic summary of the conditions on a resource.

I'd argue this is terrible design on part of kubernetes, but it is what it is.

This gives us issues with any CRD that uses negative polarity, such as the following object (edited for brevity):

```yaml
apiVersion: stackgres.io/v1
kind: SGDbOps
metadata:
  name: restart-paste
spec:
  maxRetries: 1
  op: restart
  restart:
    method: ReducedImpact
  sgCluster: paste
status:
  conditions:
    - lastTransitionTime: '2023-05-26T14:42:49.270789Z'
      reason: OperationNotRunning
      status: 'False'
      type: Running
    - lastTransitionTime: '2023-05-26T14:42:49.270789Z'
      reason: OperationCompleted
      status: 'True'
      type: Completed
    - lastTransitionTime: '2023-05-26T14:42:49.270789Z'
      reason: OperationNotFailed
      status: 'False'
      type: Failed
  opRetries: 0
  opStarted: '2023-05-26T14:40:18.960521Z'
  restart: {}
```

This has two negative polarity conditions and one positive polarity condition, all of which currently signify successful operation. However, Rancher assigns it a big red `Error` state in the UI, and the Rancher API has the following information:

```json
"state": {
  "error": true,
  "message": "",
  "name": "error",
  "transitioning": false
}
```

**To Reproduce**
Use any CRD where responsible controllers use negative polarity in the conditions set on related objects

**Result**
Rancher status is Error even for OK objects

**Expected Result**
As the kubernetes doc says we can't machine-compute a status based on conditions for reasons outlined above, so perhaps what Rancher needs in this case is some way of specifying what a good set of conditions should look like, or some way to skip computing state for certain objects altogether.
