### ISSUE TITLE
[BUG] CIS Benchmark App - TLS Issue

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#41709]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.9+rke2r2 and v1.24.9-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

After applying some hardening to the RKE1 or RKE2 cluster, the cluster is working fine; however, the CIS Benchmark App is failing us with this error:
```
Calculated Rancher Kubernetes Version: v1.24.9+rke2r2
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/notapplicable/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/defaultskip/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/userskip/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ rke2-cis-1.23-permissive != '' ]]
Wed, Feb 15 2023 4:52:18 pm | + echo 'using OVERRIDE_BENCHMARK_VERSION: rke2-cis-1.23-permissive'
Wed, Feb 15 2023 4:52:18 pm | + kb-summarizer --benchmark-version rke2-cis-1.23-permissive --controls-dir /etc/kube-bench/cfg --input-dir /tmp/kb-summarizer/input/plugins/rancher-kube-bench/results --output-dir /tmp/kb-summarizer/output --output-filename output.json
Wed, Feb 15 2023 4:52:18 pm | using OVERRIDE_BENCHMARK_VERSION: rke2-cis-1.23-permissive
Wed, Feb 15 2023 4:52:18 pm | + kubectl -n cis-operator-system create cm cisscan-output-for-scan-s42n8 --from-file /tmp/kb-summarizer/output/output.json
Wed, Feb 15 2023 4:52:18 pm | + echo 'error creating configmap for storing the report'
Wed, Feb 15 2023 4:52:18 pm | + tee -a /tmp/kbs.error.log
Wed, Feb 15 2023 4:52:18 pm | error creating configmap for storing the report
Wed, Feb 15 2023 4:52:18 pm | + exit 1 
```

Running the command manually throws us this error:
```
$kubectl -n cis-operator-system create cm cisscan-output-for-scan-s42n8                                                  
Unable to connect to the server: remote error: tls: protocol version not supported
```

Here is the RKE cluster.yaml override causing the issue.
tls-min-version: 'VersionTLS13'

```
services:
  etcd:
    extra_args:
      experimental-initial-corrupt-check: true
  kube-api:
    extra_args:
      anonymous-auth: false
      enable-admission-plugins: 'AlwaysPullImages,NodeRestriction'
      tls-cipher-suites: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
      tls-min-version: 'VersionTLS13' 
```

The problem might be the kubect version shipped in the pod is VERY old
https://github.com/rancher/security-scan/blob/master/package/Dockerfile#L25

Using a kubectl version compatible with the Kubernetes version do not throw this error.

**To Reproduce**

1. Build a RKE1 hardened cluster with following extra args for kube-api service for services
```
 services:
  etcd:
    extra_args:
      experimental-initial-corrupt-check: true
  kube-api:
    extra_args:
      anonymous-auth: false
      enable-admission-plugins: 'AlwaysPullImages,NodeRestriction'
      tls-cipher-suites: 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
      tls-min-version: 'VersionTLS13' 
```
2.  Install the CIS Benchmak app and run it. 
3. the scan will stuck in running state and the security scan runner pod will be deleted after an error.
```
Calculated Rancher Kubernetes Version: v1.24.9+rke2r2
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/notapplicable/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/defaultskip/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ -f /etc/kbs/userskip/config.json ]]
Wed, Feb 15 2023 4:52:18 pm | + [[ rke2-cis-1.23-permissive != '' ]]
Wed, Feb 15 2023 4:52:18 pm | + echo 'using OVERRIDE_BENCHMARK_VERSION: rke2-cis-1.23-permissive'
Wed, Feb 15 2023 4:52:18 pm | + kb-summarizer --benchmark-version rke2-cis-1.23-permissive --controls-dir /etc/kube-bench/cfg --input-dir /tmp/kb-summarizer/input/plugins/rancher-kube-bench/results --output-dir /tmp/kb-summarizer/output --output-filename output.json
Wed, Feb 15 2023 4:52:18 pm | using OVERRIDE_BENCHMARK_VERSION: rke2-cis-1.23-permissive
Wed, Feb 15 2023 4:52:18 pm | + kubectl -n cis-operator-system create cm cisscan-output-for-scan-s42n8 --from-file /tmp/kb-summarizer/output/output.json
Wed, Feb 15 2023 4:52:18 pm | + echo 'error creating configmap for storing the report'
Wed, Feb 15 2023 4:52:18 pm | + tee -a /tmp/kbs.error.log
Wed, Feb 15 2023 4:52:18 pm | error creating configmap for storing the report
Wed, Feb 15 2023 4:52:18 pm | + exit 1 
```
**Result**

**Expected Result**

It should not fail and gives a report.

**Screenshots**

![Screenshot from 2023-05-31 18-57-37](https://github.com/rancher/rancher/assets/115442970/18c709b4-f642-4b7c-9415-cbb88318f1fe)

**Additional context**
