### ISSUE TITLE
[BUG] rancher-backup Chart - Deployment needs PSA-restricted-compliant securityContext

### ISSUE THREAD

**Issue by ron1** [rancher/rancher#41742]
### Rancher Server Setup
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): RKE2
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version: 1.25
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use?
- What is the version of Terraform in use?

### Describe the bug

The rancher-backup Deployment fails to deploy on a 1.25+ PSA-restricted-profile cluster because it is missing a PSA-restricted-compliant securityContext. Suggest adding a Helm values parameter for the Deployment securityContext property with a default value provided below:
```
    # -- Security context for the containers
    securityContext:
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
```
