### ISSUE TITLE
Deployment.apps "xxxxxx" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms: Required value: must have at least one node selector term

### ISSUE THREAD

**Issue by liuxin638507** [rancher/rancher#41807]
**Rancher Server Setup**
- Rancher version: v2.7.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.25.9
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
rancher version 2.6.x or 2.7.4 default ui select deployments Click Edit Save error report, compatible old ui /g/clusters upgrade can be modified normally

But if I choose to edit the yaml form, can I save it without changing anything

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by Privatecoder** [comment]
I can confirm this bug with a deployment on Rancher v2.7.4 (`Node Scheduling`, Priority `Preferred`, `topology.kubernetes.io/zone` `in list` `us-west`)

**Comment by zhengcan** [comment]
The issue still exists in 2.7.9

**Comment by william0503** [comment]
I've got the same error in v2.8.0.
In my case, I did a yaml import from old gui and import in the new rancher version.
After click to add a node selector, then remove it , the save occours correctly.

Trying to edit as YAML after click to Edit Config (by form), I can see a missing uncommented line
Form:
![image](https://github.com/rancher/rancher/assets/1506975/f683585a-4234-468d-997c-db918ad5a7ad)

Yaml:
![image](https://github.com/rancher/rancher/assets/1506975/4a83200b-8d14-4f3e-868a-0f25f5bd7f0a)

**Comment by pffs** [comment]
Still having this same issue on 2.10.1. Unfortunately, we have a large number of deployments with affinity configured which means I hit this on a pretty regular basis. 

As the fastest workaround I've found so far, I go in and literally just delete and retype the last letter of the selector string and save works as expected, no need to recreate it entirely.

**Comment by Naroh091** [comment]
Still happening in 2.10.3.

**Comment by Clashsoft** [comment]
Still happening in v2.11.2.

**Comment by dierbei** [comment]
Still happening in v2.12.2.

To reproduce the issue, add `affinity` to the `Deployment`. Then, an error will occur the next time you edit the `Deployment`.

```yaml
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
              weight: 100
```

<img width="3016" height="1376" alt="Image" src="https://github.com/user-attachments/assets/91494afd-ab24-44c4-a3d4-b9bd161324c2" />
