### ISSUE TITLE
[BUG] failed calling webhook "rancher.cattle.io.secrets": failed to call webhook: the server could not find the requested resource

### ISSUE THREAD

**Issue by samene** [rancher/rancher#41826]
**Rancher Server Setup**
- Rancher version: **v2.7.3**
- Installation option (Docker install/Helm Chart): **Helm Chart**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): **RKE1 1.23.16-rancher2-1**
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: **1.23.16-rancher2-1**
- Cluster Type (Local/Downstream): **Downstream**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): **Custom**

**Describe the bug**

After creating a Downstream cluster if within a few minutes we try to deploy a helm chart which creates a secret then the installation fails with below error
```
Error: failed to install app v2: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=ServerError, 
message=Internal error occurred: failed calling webhook "rancher.cattle.io.secrets": 
failed to call webhook: the server could not find the requested resource] 
from [https://xx-rancher.xxxxxcom/k8s/clusters/c-tv8lb/v1/catalog.cattle.io.clusterrepos/xxx?action=install]
```

**Additional context**

The problem seems to be the `rancher-webhook` helm chart deployed in the downstream cluster. The initial version that is installed is `2.0.3+up0.3.3`, but after a few minutes the chart is automatically upgraded to `2.0.4+up0.3.4`.

This happens in ~ 5 minutes.

```
REVISION        UPDATED                         STATUS          CHART                           APP VERSION     DESCRIPTION     
1               Tue Jun 13 04:12:18 2023        superseded      rancher-webhook-2.0.3+up0.3.3   0.3.3           Install complete
2               Tue Jun 13 04:17:20 2023        deployed        rancher-webhook-2.0.4+up0.3.4   0.3.4           Upgrade complete
```

In the `0.3.3` version of the chart, the Mutatingwebhook contains an entry for secrets as well,

```
      service:
        name: rancher-webhook
        namespace: cattle-system
        path: /v1/webhook/mutation/secrets
        port: 443
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: rancher.cattle.io.secrets
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - secrets
        scope: Namespaced
    sideEffects: NoneOnDryRun
```

But in the `0.3.4` version this entry is removed. The patching of the webhook is done by the service and not the helm chart. There is a delay of 15 seconds between the service starting and the patch being applied to the webhook. 

```
time="2023-06-13T04:17:22Z" level=info msg="Sleeping for 15 seconds then applying webhook config"
```

During these 15 seconds, if anyone tries to create a secret then the original (unpatched) webhook is invoked, but the new endpoint service in already running and the `/v1/webhook/mutation/secrets` is unreachable and secret creation fails since failurePolicy is Fail.

Retrying again in 15 seconds works. But this is causing problems for automated pipelines.
