### ISSUE TITLE
[BUG] Unable to create RKE2 cluster using the rancher CLI

### ISSUE THREAD

**Issue by jattind** [rancher/rancher#41867]
**Rancher Server Setup**
- Rancher version: 2.6.8
- CLI version: Version: v2.7.0

**Information about the Cluster**
- Kubernetes version:
- Cluster Type Downstream:
   - custom RKE2 cluster
   - Bare Metal Server

**User Information**
- role: admin

**Describe the bug**
Using the Rancher UI, I am able to create a cluster and specify "Use existing nodes and create a cluster using RKE2/K3s" Custom cluster. Able to create the RKE2 cluster.

Using the CLI to login and set the project to local.
Tried to create a cluster with the following command and its it's only creating an RKE1 cluster:
```
1. rancher cluster create new-cluster 

Tried to specify RKE2 version, but fails as shown below
rancher cluster create new-cluster --k8s-version v1.23.17+rke2r1
Available Kubernetes versions:
v1.19.16-rancher2-1
v1.20.15-rancher2-2
v1.21.14-rancher1-1
v1.22.17-rancher1-2
v1.23.16-rancher2-2
v1.24.13-rancher2-1
v1.18.20-rancher1-3
```

**To Reproduce**
Using the CLI, login and then the create cluster command.

**Result**
Only able to create RKE1 cluster

**Expected Result**
I should be able to specify RKE2 and create the cluster.

**Comment by jattind** [comment]
Even tried creating a cluster using an rke2 config file. Still unable to successfully create an RKE2 clsuter:
```
rancher cluster create --rke-config rke2-cluster-template.yaml

apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: test2
  namespace: fleet-default
spec:
  kubernetesVersion: v1.24.13+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    machineSelectorConfig:
    - config:
        protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: "1"
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
```
