### ISSUE TITLE
[RFE] Fleet RBAC in Rancher

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#42170]
**Is your feature request related to a problem? Please describe.**
Fleet RBAC can be challenging to control in Rancher. We need a solution which allows:
- Users to mimic the permissions of Restricted Admin (permissions to create/update workspaces, and move non-local clusters between any workspace) (minimum requirement)
- Users to grant more granular access to specific fleet workspaces

**Describe the solution you'd like**
N/A - design should address the above concerns

**Comment by raulcabello** [comment]
# Validation
## Root Cause
We need to provide a way to allow users to deploy resources using fleet in downstream clusters. The only way of doing this at the moment is using the deprecated Restricted Admin user. 

## What was fixed, or what change has occurred
Each `fleetworkspace` has a backing namespace in the local cluster. In order for a user to be able to deploy resources using fleet in a downstream cluster it needs:
- Permissions to deploy fleet resources in the backing namespace of the `fleetworkspace`. For example, permission to create `GitRepos` in fleet-default.
- Permissions to get `fleetworkspace` cluster-wide resources in the local cluster.
Two new fields were added to `GlobalRole` in order to provide access to all fleet `workspaces` except local. 
- `FleetWorkspacePermission.ResourceRules`: rules granted in all backing namespaces for all fleet workspaces besides the local one
- `FleetWorkspacePermission.WorkspaceVerbs`: verbs used to grant permissions to the cluster-wide `fleetworkspace` resources. ResourceNames for this rule will contain all fleet workspace names except local

## Areas or cases that should be tested
- Admin and Restricted Admins can create `GlobalRoles` with `FleetWorkspacePermission` that allows user to deploy fleet resources in all workspaces except fleet-local.
- Users that can create `GlobalRole` or `GlobalRoleBindings` can create them with `FleetWorkspacePermission` just if they have the necessary permissions. For example, given a user that is granted a GR with `FleetWorkspacePermission` that allows him to create `gitrepos` and get `fleetworkspaces`. He should be able to grant the same GR, but he shouldn't be able to create a GR with `FleetWorkspacePermission` that allows to create or delete bundles.
- When a new workspace is created/deleted users see the new `fleetworkspace`, and have the relevant permissions.
- Migrate cluster to a different workspace. User needs update permissions for `clusters.management.cattle.io`, which can be granted by `cluster-owner` in `inheritedClusterRoles`, and `fleetaddcluster` permissions for `fleetworkspace`

example:
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-permissions
inheritedClusterRoles:
   - cluster-owner
inheritedFleetWorkspacePermissions:
  resourceRules:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - clusterregistrationtokens
        - gitreporestrictions
        - clusterregistrations
        - clusters
        - gitrepos
        - bundles
        - clustergroups
      verbs:
        - "*"
  workspaceVerbs:
    - get
    - list
    - update
    - create
    - delete
    - patch
    - fleetaddcluster
```

## What areas could experience regressions
- `GlobalRoles` without `FleetWorkspacePermission` should keep working as before.
