### ISSUE TITLE
[RFE] Add new "NamespacedRules" field.

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42215]
Related to Global Roles v2

SURE-6636

**Comment by MbolotSuse** [comment]
## Basic Requirements

- A new field should be added on the `GlobalRole` [type](https://github.com/rancher/rancher/blob/b74a73ce418ba74aec4f15d835fa64d7ca8851d9/pkg/apis/management.cattle.io/v3/authz_types.go#L143) called `NamespacedRules`. 
- This field should be a `map[string][]rbacv1.PolicyRule`, indicating which rules are active in which namespaces. 
- The use of `*` should have no special meaning as a key.
- Each value in the map should result in one role in the namespace specified by key 
- When a GlobalRoleBinding is made to a global role using these fields, one rolebinding should be made (per namespace) to the role created in the handler
- The role/rolebinding should have labels indicating which GlobalRole/GlobalRoleBinding they are owned by
- The role/rolebinding should have an ownerRef referring to the GlobalRole/GlobalRoleBinding
- If the role/rolebinding is updated/deleted, it should [enqueue](https://github.com/rancher/rancher/blob/d101c27fe5eb6bfd1992165b2f08c9fc02a2a55f/pkg/controllers/management/auth/globalroles/enqueue.go#L1) the owning GlobalRole/GlobalRoleBinding (as defined by the label)
- The GlobalRole/GlobalRoleBinding controllers should remove any roles/bindings which claim to be owned by the GlobalRole/GlobalRoleBinding (by label) but are for a different subject or have different rules.
- Tests should be written for all net-new code

**Comment by JonCrowther** [comment]
# Validation

## Root Cause

Users would like more fine grained control over the permissions provided by Global Roles (GR) and Global Role Bindings (GBR). Specifically, they want to be able to provide rules that apply only in specific namespaces. 

## What was fixed, or what change has occurred

We have added a new field to GRs called `NamespacedRules`. It is a map of Policy Rules where the key is the Namespace it should apply to.

Example `NamespacedRules`:
```
...
namespacedRules:
  namespace1:
    - apiGroups:
      - catalog.cattle.io
      resources:
      - apps
      verbs:
      - edit
  namespace2:
    - apiGroups:
      - catalog.cattle.io
      resources:
      - apps
      verbs:
      - list
...
```

When a GR with `NamespacedRules` is created, a Role is created in each of those Namespaces that has the Policy Rules specified. When a GRB is created to assign that GR to a user, it creates Role Bindings in each Namespace to assign the Roles in the respective Namespaces.

In order to manage all the Roles and Role Bindings, they have a label on them with key `authz.management.cattle.io/gr-owner` (`grb-owner` for GRB) and the value is the name of the owning GR or GRB.

## Areas or cases that should be tested

This is a fairly significant change in GRs and GRBs, so they need to be thoroughly tested. Some tests could include:
- Creating, updating and removing GR and GRBs with `NamespacedRules`
- Modifying and deleting the created Roles and Role Bindings
  - After deleting a Role/Role Binding, Rancher should attempt to recreate it immediately
  - Deleting a Namespace that contains the Role/Role Binding removes those resources and it does not attempt to recreate them. It should log a warning and then stop warning the user.
  - After modifying the Rules in the Role, Rancher should revert it immediately
- The `*` wildcard does not work for `NamespacedRules`. It should not provide access to all resources in a Namespace
- Creating Role and Role Bindings with an GR or GRB owner label to a GR or GRB that should not exist gets removed
- `kubectl explain globalrole` should give a clear explanation of how to use `NamespacedRules`

## What areas could experience regressions

It's important that these new changes don't affect the other aspects of GRs and GRBs.
- Inherited cluster rules and global rules would be the most likely to experience regressions. 
- The UI could experience some regressions or have poor design/UX so that is something to look out for. I made no changes to the UI so I'm not sure how it might react to the new field.

## Are the repro steps accurate/minimal?

This is a new feature so there aren't repro steps. I've added an example GR below that I used to test. Applying it via `kubectl apply -f gr.yaml` is the easiest way to create them.

<details> <summary> Example GlobalRole with NamespacedRules and standard global Rules </summary>
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  namespace: default
  name: test-gr-2
rules:
- apiGroups:
  - catalog.cattle.io
  resources:
  - apps
  verbs:
  - create
namespacedRules:
  namespace1:
    - apiGroups:
      - catalog.cattle.io
      resources:
      - apps
      verbs:
      - edit
  namespace2:
    - apiGroups:
      - catalog.cattle.io
      resources:
      - apps
      verbs:
      - list
```
</details>
