### ISSUE TITLE
[RFE] Network Policy for agent template

### ISSUE THREAD

**Issue by anders-swanson** [rancher/rancher#42225]
Can we add a network policy to the [system agent template](https://github.com/rancher/rancher/blob/release/v2.7/pkg/systemtemplate/template.go)? I am manually adding a policy here on rancher clusters every time I spin them off. Something built-in to the Rancher system would be great to have, even a simple policy like so:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cattle-cluster-agent
  namespace: cattle-system
spec:
  podSelector:
    matchLabels:
      app: cattle-cluster-agent
  policyTypes:
    - Ingress

```

If this sounds OK, I can create the PR to add this netpol.
