### ISSUE TITLE
Using kubectl from a developer machine results in errors for some commands

### ISSUE THREAD

**Issue by zekizeki** [rancher/rancher#4227]
Rancher Version: 1.0.0
Docker Version: Docker version 1.10.2, build c3959b1
Kubernetes Version:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8.15+3f0153c9163cee-dirty", GitCommit:"3f0153c9163cee5aafdcf6fdd21e783495f5bba4", GitTreeState:"dirty"}

```

OS: osx

Steps to Reproduce: 

Install a default non secured rancher instance with a kubernetes environment configured.
Export the kubectl config from the Rancher UI

run a command such as...

```
kubectl create -f nginx.yaml 
```

nginx.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
      
---            
            
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
    type: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: nginx
```
Results: 

error validating "nginx.yaml": error validating data: invalid character '<' looking for beginning of value; if you choose to ignore these errors, turn validation off with --validate=false

re-running the command with --validate=false works

Expected:

replicationcontroller "nginx" created
service "nginx" created
