### ISSUE TITLE
[BUG] Adding a Cluster-Badge wants to downgrade an imported K3s-Cluster

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#42286]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm

**Information about the Cluster**
- Kubernetes version: v1.27.3
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**

Adding a Badge to an imported k3s-cluster fails with "cannot upgrade cluster version..." see screenshot

**To Reproduce**

1. Create a downstream cluster with k3s 1.27.3
2. import this cluster to rancher v2.7.5
3. try adding a cluster-badge

**Result**
Badge can't be added, because Rancher is unable to up/downgrade the cluster. 
Yes, 1.27 might not be supported by rancher yet, but this shouldn't interfere with a simple badge.

**Expected Result**

Badge should be added, or the option unavailable for said cluster.

**Screenshots**

![image](https://github.com/rancher/rancher/assets/589662/904a7cd6-f4e0-42f9-a2da-41983072e409)

**Additional context**

**Comment by rrigal-lo** [comment]
I have the same issue, I believe it's caused by the `Cluster` object not being up-to-date with the current version. A badge is added in Rancher by adding the following annotations to the `Cluster` object:
```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    ui.rancher/badge-color: "#ff0000"
    ui.rancher/badge-text: "Example Text"
...
```
So basically when you click on the `Apply` button it tries to change the whole `Cluster` object definition, which fails because the `kubernetesVersion` spec is not up-to-date with the actual version. In my case the `kubernetesVersion` is `v1.25.11+rke2r1` while the actual version is `1.26.9+rke2r1`:
```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
...
spec:
  rke2Config:
    kubernetesVersion: v1.25.11+rke2r1
...
```

The workaround I found is to annotate the `Cluster` object manually, like so:
```bash
kubectl -n fleet-local annotate clusters.management.cattle.io <YOUR_CLUSTER_NAME> 'ui.rancher/badge-text=LTE' 'ui.rancher/badge-color=#FF0000'
```
