### ISSUE TITLE
docker-compose.yml link aliases with dots doesn't work

### ISSUE THREAD

**Issue by bonifaido** [rancher/rancher#4229]
**Rancher Version:**
1.0.0
**Docker Version:**
1.10.3
**OS:**
OSX 10.11.4
**Steps to Reproduce:**
My docker-compose.yml file:
```
redis:
  image: redis
  links:
    - graphite:graphite.me # This works in docker-compose 1.6.2
graphite:
  image: hopsoft/graphite-statsd
```
Run the following:
```
rancher-compose create
```
**Results:**
```
ERRO[0000] Failed Creating redis : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=InvalidCharacters] from [http://192.168.99.100:8080/v1/services/1s27/?action=setservicelinks] 
ERRO[0001] Failed to start: redis : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=InvalidCharacters] from [http://192.168.99.100:8080/v1/services/1s27/?action=setservicelinks] 
FATA[0001] Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=InvalidCharacters] from [http://192.168.99.100:8080/v1/services/1s27/?action=setservicelinks]
```
**Expected:**
This worked in rancher/server 0.63.1. It works in docker-compose 1.6.2.
