### ISSUE TITLE
When creating a stack using docker-compose/rancher-compose encounters api error for service creation , stack is stuck in "Activating" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4234]
Rancher Version:v1.0.0

Steps to reproduce the problem:

Create a stack by providing the following docker-compose.yml which has name field with "." which will fail API validation

```
test.client2:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: nginx
  stdin_open: true
```

Stack creation fails and  is stuck in "Activating" state forever.

<img width="1196" alt="screen shot 2016-03-30 at 2 12 49 pm" src="https://cloud.githubusercontent.com/assets/4266958/14157940/4f1f6396-f682-11e5-8f3d-65add64253b6.png">

Expected Behavior:
Stack should be created successfully.
But the service creation failure should be notified to the user.
