### ISSUE TITLE
[BUG]Windows rke2 custom cluster - nodes stop displaying metrics in Monitoring after upgrading kubernetes version

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#42414]
**Rancher Server Setup**
- Rancher version: v2.7.6-rc2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2
- Proxy/Cert Details: valid, signed certs

**Information about the Cluster**
- Kubernetes version: v1.25.12+rke2r1 -> v1.26.7+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom,  with windows workers, all running on ec2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when using monitoring 102.0.1+up40.1.2, windows metrics are displaying properly. However after upgrading, the metrics stop being posted though all the pods appear to be active in cattle-monitoring

**To Reproduce**

* deploy a custom rke2 cluster on 1.25
  * 3etcd, 2cp, 3linux workers, 3 windows workers
* wait for the cluster to become active
* install monitoring
* upgrade the cluster to 1.26
* wait for the upgrade to complete
* check monitoring metrics

**Result**
windows metrics no longer show

**Expected Result**

windows metrics should persist after upgrading k8s versions

**Screenshots**

<img width="635" alt="Screen Shot 2023-03-24 at 9 51 03 PM" src="https://user-images.githubusercontent.com/16691014/227698075-20212dcf-d8ed-4564-95ee-039aecfb82de.png">

**Additional context**

uninstalling -> re-installing the chart seems to fix this problem.

seems to be a regression from https://github.com/rancher/rancher/issues/40982

SURE-7731

**Comment by MKlimuszka** [comment]
If it's a quick fix after initial investigation, we can get it done. If it looks like it's medium loe or higher, then we should reconsider since there is a straightforward workaround.

**Comment by aiyengar2** [comment]
@MKlimuszka @joshmeranda we'll take this issue since we're working actively on windows-exporter changes at the moment. Targeting 2.8.0 / 2.9.0.

**Comment by snasovich** [comment]
The issue is reproducible per @HarrisonWAffel

**Comment by HarrisonWAffel** [comment]
I've reproduced the above bug in a standalone RKE2 cluster, I've done the following 

1. Deploy a 1 server 1 windows worker cluster using the latest version of RKE2 installed via the installation script 
2. Deploy a sample windows workload to the cluster and wait for it to deploy properly (see detail below for workload used)
3. Upgrade the server node to the next available version of rke2 (I went from 1.27 → 1.28, but considering the above comment this likely happens for any version) 
4. Upgrade the worker node to the next available version
5. Attempt to delete the workload created before upgrading the cluster using `kubectl`

The same error shown in the above comment also appears in this scenario, which indicates that the error is not specific to the monitoring chart 

<details>
<summary>
Sample Workload
</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
        - name: windowswebserver
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - "<#code used from https://gist.github.com/19WAS85/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
      nodeSelector:
        kubernetes.io/os: windows
```

</details>
