### ISSUE TITLE
[BUG] SELinux prevents Rancher-provisioned cluster from starting

### ISSUE THREAD

**Issue by aleiner** [rancher/rancher#42415]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 - 1.25.11
- Proxy/Cert Details: Cert-Manager

**Information about the Cluster**
- Kubernetes version: 1.25.11
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): VMware

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
Trying to provision a new RKE2 cluster via Rancher.  Via cloud-config, I install rke2-selinux (and container-selinux) and add `selinux: true` to `/etc/rancher/rke2/config.yaml`.  After RKE2 is installed, `kube-controller-manager` and `kube-scheduler` will fail to start with the following errors.

`E0814 19:47:05.410150       1 run.go:74] "command failed" err="error creating self-signed certificates: open /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt: permission denied"`

and 

`E0814 19:45:45.017894       1 run.go:74] "command failed" err="error creating self-signed certificates: open /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt: permission denied"`

Audit logs point to SELinux context issues:

`type=AVC msg=audit(1692042425.409:2240): avc:  denied  { create } for  pid=165513 comm="kube-controller" name="kube-controller-manager.crt" scontext=system_u:system_r:rke2_service_t:s0:c688,c805 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file permissive=0`

`type=AVC msg=audit(1692042345.016:2232): avc:  denied  { create } for  pid=164925 comm="kube-scheduler" name="kube-scheduler.crt" scontext=system_u:system_r:rke2_service_t:s0:c264,c1014 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file permissive=0`

**To Reproduce**
Create Rancher provisioned cluster for VMware with the following cloud-config (this was being done in an air-gap environment):
```
#cloud-config
runcmd:
  - 'curl 10.10.10.101:30002/ca-cert.pem -o /etc/pki/ca-trust/source/anchors/cert-manager.pem; update-ca-trust extract'
  - 'rpm -i http://10.10.10.101:30002/Packages/rke2-selinux-0.14-1.el8.noarch.rpm http://10.10.10.101:30002/Packages/container-selinux-2.205.0-2.module+el8.8.0+1265+fa25dd7a.noarch.rpm'

write_files:
  - content: |
      selinux: true
    owner: root:root
    path: /etc/rancher/rke2/config.yaml
    permissions: '0644'
```
**Result**
Cluster fails to become ready and `kube-controller-manager` and `kube-scheduler` continually restart. 

**Expected Result**
Cluster runs successfully with the proper SELinux contexts set.

@galal-hussein @dweomer
