### ISSUE TITLE
[BUG]  failed to create mutating configuration

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#42611]
**Rancher Server Setup**
- Rancher version: 2.7.5

**Information about the Cluster**
- Kubernetes version: v1.28.1

**Describe the bug**
level=error msg="error syncing 'cattle-system/cattle-webhook-ca': handler secrets: failed to create mutating configuration: MutatingWebhookConfiguration.admissionregistration.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required, requeuing"

**To Reproduce**
Follow these steps: https://ranchermanager.docs.rancher.com/v2.7/troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation

Then the rancher-webhook pod in cattle-system won't come back online with the error described above

**Comment by tomleb** [comment]
Thanks for opening an issue. Closing as duplicate of https://github.com/rancher/webhook/issues/286.

**Comment by KevinJoiner** [comment]
@brisp-jelle 
To manually recover from this state, you can recreate an empty configuration and restart the rancher-webhook pod
``` yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
  ```
  `kubectl delete pod -n cattle-system -l app=rancher-webhook`
