### ISSUE TITLE
log_opt, log_driver are exported in the yaml even if they are not set

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4268]
Rancher Version:
v1.0.0

Steps to Reproduce: 

1. Add a service
2. Look at the related docker-compose.yml

Results: 
```
testing:
  log_driver: ''
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  stdin_open: true
```
Expected:

```
testing:
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev4-rc1. The docker-compose.yml is generated correctly as below:

```
dockertest:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
```
