### ISSUE TITLE
[BUG] Removing the last InheritedClusterRole does not remove backing CRTBs

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#42721]
**Rancher Server Setup**
- Rancher version: v2.8-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Local
- Proxy/Cert Details: N/A

**Information about the Cluster**
N/A should affect all versions.
Local cluster version: 1.26.6+k3s1 (rancher desktop)
Downstream Cluster Version: Digital Ocean 1.26.7+rke2r1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When removing the last `InheritedClusterRole` from a GlobalRole, the related CRTBs are not removed as they should be.

**To Reproduce**
1. Create a downstream cluster.
2. Using the below yaml, create a GlobalRole giving read-only access to downstream clusters:
```yaml
apiVersion: management.cattle.io/v3
kind: GlobalRole
displayName: Example Role
description: Base user + Read-only on all downstream clusters
metadata:
  name: example-gr
inheritedClusterRoles:
- projects-view
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - preferences
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - features
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.cattle.io
  resources:
  - sourcecodecredentials
  verbs:
  - '*'
- apiGroups:
  - project.cattle.io
  resources:
  - sourcecoderepositories
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - rancherusernotifications
  verbs:
  - get
  - list
  - watch
```
3. Create a user, and give them a binding to this GlobalRole.
4. Verify that a backing CRTB was created for this user on the downstream cluster.
5. Edit the GlobalRole, and remove the `inheritedClusterRoles` (i.e. make it empty).

**Result**

The backing CRTB created in step 4 still exists.

**Expected Result**

The backing CRTB should be removed, since the new version of the GlobalRole doesn't give the `projects-view` permission any more.
