### ISSUE TITLE
[RFE] Ability to deploy AWS external tree provider in RKE2

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#42749]
**This is a placeholder ticket for AWS external tree provider in RKE2.** 
The external AWS cloud provider (CCM) deploys onto a cluster and relies on the hostname and/or --provider-id flag (kubelet) to describe the node and initialise into the cluster.
With v2-provisioning, the hostname is always set to a node pool naming convention (OS (see userdata example below) & with -hostname-override), and there appears to be no way of providing the values dynamically to the -provider-id flag.
Here is an example gist to demonstrate a single-node cluster built directly - https://gist.github.com/dkeightley/26607d6739429a174675a81cd6fe65d6
Note the provider_id variable retrieves the AZ and instance ID from EC2 metadata.

Repro steps:
Create an RKE2 cluster using the external cloudprovider (terraform example might be the easiest option)
The hostname is overriden, auto-detection of the instance can't be completed (as above)
The provider-id flag can't be set appropriately via userdata

SURE-4760

**Comment by Sahota1225** [comment]
https://github.com/rancher/rancher-docs/pull/826

**Comment by jakefhyde** [comment]
https://github.com/rancher/rancher-docs/pull/844

**Comment by slickwarren** [comment]
testing this on 1.27.6+rke2r1 using aws node driver is no longer working. I originally tested on 2.8-head and 2.8.0-alpha1.

Currently, 1.26.8 is working fine, and I can see it is using the aws-cloud-controller resource when creating upstream resources, i.e. LBs

when trying to provision 1.27.6 with the same steps however, the cluster hangs during provisioning. The control plane nodes are stuck with status `Waiting for probes: calico, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet`. I have tried to find meaningful logs on both the etcd and control plane nodes, as well as through the local cluster's logs, but did not find anything. I can provide a setup with this problem upon request. 

here's a snippet of the changes to the cluster.yaml that were being applied
```

  rkeConfig:
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: aws-cloud-controller-manager
        namespace: kube-system
      spec:
        chart: aws-cloud-controller-manager
        repo: https://kubernetes.github.io/cloud-provider-aws
        targetNamespace: kube-system
        bootstrap: true
        valuesContent: |-
          hostNetworking: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          args:
            - --configure-cloud-routes=false
            - --v=5
            - --cloud-provider=aws
...
    machineGlobalConfig:
      cloud-provider-name: aws
...
machineSelectorConfig:
      - config:
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/etcd-role: 'true'
      - config:
          disable-cloud-controller: true
          kube-controller-manager-arg:
            - cloud-provider=external
          kubeapi-server-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
      - config:
          disable-cloud-controller: true
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/worker-role: 'true'
      - config:
          cloud-provider-name: aws
          protect-kernel-defaults: false
...
```

**Comment by kinarashah** [comment]
@slickwarren I looked into the issue and the issue is `kubelet-arg` is missing for control plane role nodes. I think this isn't a problem for 1.26 clusters because the default value `aws` still works but fails for 1.27 with kubelet crashing with invalid cloud provider value. 

Also since `config` under `machineSelectorConfig` without selectors is the same as `machineGlobalConfig`, we don't need both of them. 

Config below worked for `v1.27.6+rke2r1` on `v2.8-head`: 

```
  rkeConfig:
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: aws-cloud-controller-manager
        namespace: kube-system
      spec:
        chart: aws-cloud-controller-manager
        repo: https://kubernetes.github.io/cloud-provider-aws
        targetNamespace: kube-system
        bootstrap: true
        valuesContent: |-
          hostNetworking: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          args:
            - --configure-cloud-routes=false
            - --v=5
            - --cloud-provider=aws
    machineSelectorConfig:
      - config:
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/etcd-role: 'true'
      - config:
          disable-cloud-controller: true
          kube-controller-manager-arg:
            - cloud-provider=external
          kubeapi-server-arg:
            - cloud-provider=external
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/control-plane-role: 'true'
      - config:
          disable-cloud-controller: true
          kubelet-arg:
            - cloud-provider=external
        machineLabelSelector:
          matchLabels:
            rke.cattle.io/worker-role: 'true'
      - config:
          cloud-provider-name: aws
          protect-kernel-defaults: false
```
