### ISSUE TITLE
Verison variable not recognized

### ISSUE THREAD

**Issue by jiangjian0920** [rancher/rancher#42876]
**Rancher Server Setup**
- Rancher version: v2.5.15
- Installation option (Docker install/Helm Chart): docker install
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.6-tke.37

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

**Describe the bug**

Successfully published using the ranger pipeline, but found that the version variable in Chart.yaml pushed to the repo was not recognized

**To Reproduce**

1.rancher-pipeline.yaml
```yaml
- name: Publish Chart
  steps:
  - publishCatalogConfig:
      path: ./charts
      catalogTemplate: id-service
      version: ${CICD_EXECUTION_SEQUENCE}
      gitUrl: http://****/paas-charts/custom-chart.git
      gitBranch: master
      gitAuthor: test
      gitEmail: ***.com
    envFrom:
    - sourceName: custom-library-secret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: custom-library-secret
      sourceKey: PASSWORD
      targetKey: PASSWORD
    when:
      branch:
        include:
        - maste
```        
2.  Chart.yaml
```yaml
apiVersion: v1
description: id-service
name: id-service
version: ${VERSION}
appVersion: v1.0.30-master-374440e
```

4. publish chart log 

+ publish-catalog
[INFO]check done...
[INFO]prepare config done...
[INFO]publishing to http://***/paas-charts/custom-chart.git
Cloning into '/tmp/repo'...
[INFO]variable substitution done...
[master 0f01df28] add version 30 of template id-service.
 4 files changed, 161 insertions(+)
 create mode 100644 charts/id-service/30/Chart.yaml
 create mode 100644 charts/id-service/30/questions.yaml
 create mode 100644 charts/id-service/30/requirements.yaml
 create mode 100644 charts/id-service/30/values.yaml
To http://****/paas-charts/custom-chart.git
   9f36aca5..0f01df28  master -> master

5. pipeline Chart.yaml file
```yaml
apiVersion: v1
description: id-service
name: id-service
version: ${VERSION}
appVersion: v1.0.${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
```
```
```

**Result**

**Expected Result**

**Screenshots**

**Additional context**
