### ISSUE TITLE
[BUG] can't delete cluster with rke2/k3s stacked (etcd+controlplane) node - cluster gets stuck in removing state

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#42890]
**Rancher Server Setup**
- Rancher version: v2.8-head (efc48ac)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1 1.26.8-rancher1-1
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: 1.26.8+rke2r1 and k3s1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested with both standard user, cluster owner and administrator

**Describe the bug**

when deleting a custom cluster that has an etcd+controlplane ( aka 'stacked') node, the cluster fails to delete said node but all others are removed. Results in the cluster hung in a 'removing' state

**To Reproduce**

* create an rke2/k3s custom cluster
* register an etcd+controlplane node
* register a worker node
* wait for the cluster to become active
* delete the cluster

**Result**
stacked node stays in cluster, cluster remains in 'removing' state

**Logs**
```
2023-09-21T17:13:58.623305205Z 2023/09/21 17:13:58 [ERROR] error syncing 'fleet-default/custom-c1c13c206825': handler rke-bootstrap: failed to delete fleet-default/custom-c1c13c206825-machine-plan /v1, Kind=Secret for rke-bootstrap fleet-default/custom-c1c13c206825: secrets "custom-c1c13c206825-machine-plan" not found, failed to delete fleet-default/custom-c1c13c206825-machine-plan /v1, Kind=ServiceAccount for rke-bootstrap fleet-default/custom-c1c13c206825: serviceaccounts "custom-c1c13c206825-machine-plan" not found, requeuing

```

**Expected Result**

cluster should be removed from rancher

**Screenshots**

**Additional context**

workaround: manually delete the node from the cluster -> cluster exits removing state and is indeed removed from the management view

needs to be tested:
* 2.7-head
* alternate k8s versions (1.27, 1.25)
* node driver cluster(s)

tested working:
* 2.7.6 latest k8s version (1.26.8)
* rke1 1.26.8-rancher1-1 on same 2.8-head version as this ticket

**Comment by susesgartner** [comment]
Additional testing:
1. I was unable to reproduce this issue using v2.7-head and k8s version 1.26
2. I was able to reproduce this issue on v2.8-head and k8s version 1.27 
3. I was unable to reproduce this on v2.8-head with a node driver cluster

**Comment by bfbachmann** [comment]
I spent some time looking into this and found the following.

In Rancher v2.7, this issue doesn't crop up because **all** machine (`machines.cluster.x-k8s.io`) resources are created with a proper `Cluster` owner ref like this:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  finalizers:
  - machine.cluster.x-k8s.io
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: bruno-custom
    objectset.rio.cattle.io/hash: d14104b9b6dc8924262ac6cdd7de3a7a00c11fe7
    rke.cattle.io/cluster-name: bruno-custom
    rke.cattle.io/machine-id: 81f2227859c998b1b7104335c747c0cd679923f6e2cf2afd53838f7c93f92c1
    rke.cattle.io/worker-role: "true"
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    kind: Cluster
    name: bruno-custom
    uid: 0581db99-d873-4a5d-902b-0c3f29e83675
  
  # ...
```

My understanding is that the `ownerRef` there tells the CAPI machine controller that the machine belongs to that cluster, and this in turn allows the controller to automatically delete the machine when the corresponding cluster is deleted.

The problem is that, with Rancher v2.8, machines that have the control-plane role (`rke.cattle.io/control-plane-role`) do not get any owner references like the one above. My thinking is that, as a result of this, CAPI does not know to delete these machines when the corresponding cluster is deleted. I confirmed this myself by adding the owner ref to control plane machine objects manually and then proceeding with cluster deletion – the machines were deleted properly as expected.

What I'm trying to figure out at this point is why these machine objects are suddenly missing the owner ref in Rancher v2.8. As far as I can tell, we didn't change the CAPI version we're using. I'm still actively investigating to see if I can find where the problem lies.

It's worth noting that there were some changes to how machine adoption works in CAPI between v1.0.0 and v1.4.4 (the version we're currently using). Here is how machine adoption is decided in v1.0.0 https://github.dev/kubernetes-sigs/cluster-api/blob/e09ed61cc9ba8bd37b0760291c833b4da744a985/controllers/machine_controller.go#L666. Here's how it's decided in v1.4.4 https://github.dev/kubernetes-sigs/cluster-api/blob/00dbf7b9f6322d7ebd06ae2efa703b23354dd37d/internal/controllers/machine/machine_controller.go#L762.
