### ISSUE TITLE
[RFE] Projects Public API: validate `ClusterName`

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#42913]
**Is your feature request related to a problem? Please describe.**

Projects disappear from the UI when not in the correct namespace.

Add project:
```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: das-kubectl-projekt
  namespace: default
spec:
  displayName: created via kubectl
  clusterName: local
```

The project appears on the UI. Then by using the "Create namespace" button of that project to add a new namespace, the project disappears and the namespace appears into "Not in a Project".

![image (3)](https://github.com/rancher/rancher/assets/1220710/9d1afdf0-e7eb-422c-a216-18f5b935cafe)

As soon as the namespace is deleted, the project reemerges:

![image (4)](https://github.com/rancher/rancher/assets/1220710/efabf70b-1ba8-48a2-b00a-8b2f4329665c)

**Describe the solution you'd like**

The project must be in the cluster namespace, and `clusterName` must match the namespace. Either we need to validate the two fields are the same, and possibly validate that the cluster exists, or remove `clusterName` entirely since it is redundant with `namespace`.
