### ISSUE TITLE
Feature Request: Add in ipc support 

### ISSUE THREAD

**Issue by demohi** [rancher/rancher#4294]
_Describe your issue here_

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
| Access | `Disabled` |
| Route | `environment.code` |

I create a stack by a docker-compose config file, I found the ipc options is ignored in rancher.
### original config

``` yaml
xxx:
  restart: always
  image: "xxx"
  ipc: host
  ports:
    - 8002:3000
```
### rancher parsed config

``` yaml
xxx:
  ports:
  - 8002:3000/tcp
  image: xxx
```

**Comment by deniseschannon** [comment]
Currently, ipc is not supported in Rancher, which is why it would not export it into the docker-compose.yml config.

**Comment by demohi** [comment]
@deniseschannon Thanks for your reply.  Any plan for that ?  I want use that to fix some issues

**Comment by deniseschannon** [comment]
There are some implications around sidekicks that need to be considered, but I've updated this ticket as the feature request for the implementation of it.

**Comment by demohi** [comment]
👍

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by treyd** [comment]
Will this be addressed in 2.x?  ipc opens up a lot of interesting options for coordinating containers

**Comment by leonsp** [comment]
Note: I've confirmed with Rancher support that `ipc: host` is implemented and released in Rancher 1.6.x. 

This works for me in Rancher 1.6.x:
```
---
version: "2"
services:
  bar:
    image: ubuntu:18.04
    ipc: host
```

But I haven't yet tested the ipc features extensively.
