### ISSUE TITLE
Deploying KeyCloak OIDC configuration with helm chart install

### ISSUE THREAD

**Issue by ValeriiVozniuk** [rancher/rancher#42944]
Hi,

I'm testing KeyCloak OIDC auth for Rancher, and while I was able to successfully create integration manually, following the guide [here](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-oidc), I cannot find anywhere any mentions about how to do this automatically during deployment via Helm chart or CLI.
Could anybody tell me please, is it possible to create KeyCloak OIDC auth integration in Rancher during deployment using any automations, or it is not supported?
Per what I see, such integration creates secret with jwt token for KeyCloak client, and populate data in keycloakoidc AuthConfig, but it is clearly not enough to get the integration working, as it have fields like 
```
allowedPrincipalIds:
- keycloakoidc_user://<GUID>
clientSecret: cattle-global-data:keycloakoidcconfig-clientsecret
```
and it is not clear where this guid and reference is coming from.
Also there is a question about KeyCloak group mapping to Rancher roles, is it possible to create it during helm install too? Via params/env variables/cli tools/whatever, just not manually?

**Comment by barrettMCW** [comment]
Just dug as far as I needed to for my similar situation, here's my understanding.

Rancher Keycloak OIDC integration uses a single filter, all who pass are given the defined ownerReferences. 
The filter can be all users in a given keycloak realm (accessMode: unrestricted), or all users in a given set of groups (accessMode: required).

clientId and clientSecret are from your Keycloak Client configuration.

I've found two types of allowedPrincipalIds:
-  keycloakoidc_user: //<UID>
- keycloakoidc_group://<group_name>
you can find a keycloak users uid through the ui (first property on a given users page)  but i'm sure there's a way to get that uid non-interactively too
the groups in keycloaks don't have uids, so we just use whatever name we called the group

As for doing all this noninteractively i am using a set of ansible tasks (still in development this is messy, but hopefully helpful):
``` yaml
- name: Create Rancher Client
  community.general.keycloak_client:
    auth_keycloak_url: http://{{ idp.hostname }}
    auth_realm: "master"
    auth_username: "admin"
    auth_password: "{{ admin_password }}"
    state: present
    realm: "{{ idp.realm.name }}"
    client_id: "rancher"
    name: "rancher" 
    description: "Client used by Rancher for OIDC authentication"
    protocol: "openid-connect"
    enabled: true
    public_client: false
    client_authenticator_type: client-secret
    secret: "{{ rancher_client_secret }}"
    web_origins:
      - "https://{{ ranch.rancher.hostname }}/*"
    redirect_uris:
      - "https://{{ ranch.rancher.hostname }}/verify-auth" 
    protocol_mappers:
      - name: "Groups Mapper"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "groups"
          id.token.claim: false
          access.token.claim: false
          userinfo.token.claim: true
      - name: "Client Audience"
        protocol: "openid-connect"
        protocolMapper: "oidc-audience-mapper"
        config:
          included.client.audience: "rancher" 
          id.token.claim: false
          access.token.claim: true
          userinfo.token.claim: false
      - name: "Groups Path"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "full_group_path"
          full.path: true
          id.token.claim: false
          access.token.claim: false
          userinfo.token.claim: true
  when: inventory_hostname == groups[ranch.rancher.cluster].0

- name: Test and Apply Rancher Keycloak OIDC Config
  uri:
    url: "https://{{ ranch.rancher.hostname }}/v3/keyCloakOIDCConfigs/keycloakoidc"
    method: PUT
    validate_certs: no
    headers:
      Authorization: "Bearer {{ rancher_api_token }}"
    body: 
      type: "keyCloakOIDCConfig"
      name: "keycloakoidc"
      clientId: "rancher"
      clientSecret: "{{ rancher_client_secret }}"
      issuer: "http://{{ idp.hostname }}/realms/{{ idp.realm.name }}"
      authEndpoint: 'http://{{ idp.hostname }}/realms/{{ idp.realm.name }}/protocol/openid-connect/auth'
      rancherUrl: "https://{{ ranch.rancher.hostname }}/verify-auth"
      enabled: true
      scope: "rancher"
      groupSearchEnabled: true
      allowedPrincipalIds: [ "keycloakoidc_group://rancher" ]
      accessMode: "required"
    body_format: json
    status_code: 200
  when: inventory_hostname == groups[ranch.rancher.cluster].0
```
ultimately the (seeming) lack of ability to map specific users (or more accurately users of specific groups) to specific ownerships makes it not viable for my implementation. 
unfortunately for our setup we will be just doing an unrestricted provider, managing the permissions in rancher, and crossing our fingers that a better keycloak role mapping solution comes out soon!
