### ISSUE TITLE
[BUG] Mismatch in kube-version annotation for rancher-webhook

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42949]
**Rancher Server Setup**
- Rancher version: v2.8-a4eae8069b625263cef30b257f94ef9dce0a58fa-head
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE

**Information about the Cluster**
- Kubernetes version: v1.27.5

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
kube-version annotation for rancher-webhook does not match with what's provided [here](https://github.com/rancher/rancher/issues/41789)

**To Reproduce**

1. Create a rancher server v2.8-head with k8s v1.27
2. Navigate to Installed Apps -> rancher-webhook.
3. Verify that the kube-version annotation in the rancher-webhook's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Issue:  kube-version annotation in the rancher-webhook's yaml has: catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.28.0-0'
- Min version is 1.16.0 instead of 1.23.0

![image](https://github.com/rancher/rancher/assets/42880103/acc6c08d-a7f7-42e9-8963-80c57ca6a04c)

Link to the webhook chart where the annotation is updated: https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-webhook/103.0.0%2Bup0.4.0-rc7/Chart.yaml

**Comment by Priyashetty17** [comment]
Verified that the annotations are accurate. 
```
Rancher version: v2.8-e5ce94a4c8572a8af176188172a57805e1dc76a4-head 
Webhook version: rancher-webhook:v0.4.0-rc9
```

```
annotations:
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: 'true'
        catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
        catalog.cattle.io/namespace: cattle-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
        catalog.cattle.io/release-name: rancher-webhook
```
