### ISSUE TITLE
[BUG] Mismatch in kube-version annotation for rancher-cis-benchmark

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42950]
**Rancher Server Setup**
- Rancher version: v2.8-a4eae8069b625263cef30b257f94ef9dce0a58fa-head
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE

**Information about the Cluster**
- Kubernetes version: v1.27.5

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
kube-version annotation for rancher-cis-benchmark does not match with what's provided [here](https://github.com/rancher/rancher/issues/41787)

**To Reproduce**

1. Create a rancher server v2.8-head with k8s v1.27
2. Install Rancher CIS Benchmark Chart 5.0.0-rc2. 
3. Navigate to Installed Apps -> rancher-cis-benchmark.
4. Verify that the kube-version annotation in the rancher-cis-benchmark's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Issue:  kube-version annotation in the rancher-cis-benchmark's yaml has: catalog.cattle.io/kube-version: '>= 1.21.0-0 < 1.28.0-0'
- Min version is 1.21.0 instead of 1.23.0

![image](https://github.com/rancher/rancher/assets/42880103/68d7f6c1-392b-4fec-a902-fed4749a76b0)

Link to the rancher-cis-benchmark chart where the annotation is updated: https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-cis-benchmark/5.0.0-rc2/Chart.yaml

cc @rayandas @andypitcher @JonCrowther

**Comment by Priyashetty17** [comment]
Validated with v2.8-c55d3344dc46525a860c712f868f1b7ab1826b1b-head and CIS chart **5.0.0-rc3**
```
spec:
  chart:
    metadata:
      annotations:
        catalog.cattle.io/auto-install: rancher-cis-benchmark-crd=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/display-name: CIS Benchmark
        catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
        catalog.cattle.io/namespace: cis-operator-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/provides-gvr: cis.cattle.io.clusterscans/v1
        catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
        catalog.cattle.io/release-name: rancher-cis-benchmark
        catalog.cattle.io/type: cluster-tool
        catalog.cattle.io/ui-component: rancher-cis-benchmark
        catalog.cattle.io/ui-source-repo: rancher-charts
        catalog.cattle.io/ui-source-repo-type: cluster
```
