### ISSUE TITLE
[RancherMonitoring] ServiceMonitors: metricRelabelings settings in value.yaml are not considered

### ISSUE THREAD

**Issue by SebManGK** [rancher/rancher#43011]
**Environment:**

Rancher: v2.7.1
RKE: v1.24.16-rancher1-1
RancherMonitoring: v102.0.2+up40.1.2

**Problem description:**

MetricRelabelings of the serviceMonitors within the custom value.yaml settings are not correctly taken into account during Helm installation and are therefore missing in the resulting serviceMonitor objects. Seems that Helm templating is broken in this case.

**Reproduction:**

Install Monitoring (102.0.2+up40.1.2) chart via Rancher-UI with e.g. values for coreDns-Exporter (also other serviceMonitors are affected):

```
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
  serviceMonitor:
    interval: 30s
    proxyUrl: ""
    metricRelabelings:
      - action: keep
        regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
        sourceLabels: [__name__]
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        separator: ;
        regex: ^(.*)$
        targetLabel: nodename
        replacement: $1
        action: replace
    additionalLabels: {}
       foo: bar
```

**Result:**

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: rancher-monitoring
    meta.helm.sh/release-namespace: cattle-monitoring-system
  labels:
    app: rancher-monitoring-coredns
    app.kubernetes.io/instance: rancher-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: rancher-monitoring
    app.kubernetes.io/version: 102.0.2_up40.1.2
    chart: rancher-monitoring-102.0.2_up40.1.2
    heritage: Helm
    release: rancher-monitoring
  name: rancher-monitoring-coredns
  namespace: kube-system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      metricRelabelings:
        - action: replace
          replacement: <hidden>
          sourceLabels:
            - __address__
          targetLabel: cluster_id
        - action: replace
          replacement: <hidden>
          sourceLabels:
            - __address__
          targetLabel: cluster_name
      port: http-metrics
      relabelings:
        - action: replace
          regex: ^(.*)$
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: nodename
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: rancher-monitoring-coredns
      release: rancher-monitoring
```

The metricRelabelings settings are ignored, because the templating doesn't seem to work or the parsing from yaml to json with the corresponding templates.

Additionally strangely enough, sometimes the installation of the Monitoring chart with default values - except the additional metricRelabeling settings - itself results in error:

`Error: YAML parse error on rancher-monitoring/templates/exporters/core-dns/servicemonitor.yaml: error converting YAML to JSON: yaml: line 30: did not find expected key`

In such cases you have to comment out again the metricRelabelings settings and the installation is working again (without custom metricRelabelings settings within the resulted serviceMonitor object).
