### ISSUE TITLE
[BUG] Editing ConfigMap breaks YAML formatting when using tabulator

### ISSUE THREAD

**Issue by altulek** [rancher/rancher#43035]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.25.10
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom

**Describe the bug**
ConfigMap edit doesn't work properly when you are using "\t" (tabulator) character.

**To Reproduce**

1. Create new config map
2. key: a, value: a
a	b 	c  <- with tab instead of space
3. key: b, value:a
a	b 	c  <- with tab instead of space
4. save

**Result**
Error: "a line break is expected"
**Expected Result**
Saved properly

**Screenshots**

![Zrzut ekranu 2023-10-03 142028](https://github.com/rancher/rancher/assets/83636764/2493fe4a-c400-493d-8a75-6d4e732f1779)

![Zrzut ekranu 2023-10-03 142003](https://github.com/rancher/rancher/assets/83636764/4201f724-d7b6-4b4d-bfaf-2db6c34ce13f)

**Additional context**
The issue happens when values are saved as string. Rancher adds additional key into first data section.

**Comment by altulek** [comment]
It happened always when YAML data elements becomes a string. I Can see the same when I use "\r" char.

**Comment by slickwarren** [comment]
I can't reproduce this on rancher version v2.7.6. Here's what I've tried:
* import a yaml file with the following:
```
apiVersion: v1
data:
    a: a
    b:  b
kind: ConfigMap
metadata:
  name: ctw-testyml
  namespace: default
  annotations: {}
  labels: {}
```
* entering this manually in the `configMap` -> `create` -> `edit as yaml` option
this was using `tab` instead of `spaces`. Can you perhaps add an example configMap.yaml that is causing the problem (before it is created on the rancher side)?

**Comment by altulek** [comment]
You can try this one: 
```
apiVersion: v1
data:
  a: "a\nb\tc"
  b: "a\nb\tc"
kind: ConfigMap
metadata:
  name: yaml-tab-test
``` 
After saving this yaml I can't save it again through "Edit Config". 
After I chose "Edit Config" -> "Edit as YAML" data section looks like this: 
```
data:
  b: |+a: |+a: "a\nb\tc"
  b: "a\nb\tc"
``` 

I think that new line also is necessary to trigger this error.

**Comment by slickwarren** [comment]
repro steps:
* deploy the following yaml on any cluster using the `import yaml` function
```
apiVersion: v1
data:
  a: "a\nb\tc"
  b: "a\nb\tc"
kind: ConfigMap
metadata:
  name: yaml-tab-test
```
* edit the configMap via `configMaps -> use the ... dropdown on the configmap -> edit Config` 
  * intermediate step to view problem - once edit as form is loaded, switch to `edit as yaml`, this will show that the UI added `|+a: |+a:` to the yaml, however if you do not do `view as yaml` first, the resource creation is not caught before erroring out the whole page with the screenshot mentioned by the user
* save the changes
user is hit with the error screen shown in the original comment

tested on v2.7.6 and v2.8.0-alpha2
