### ISSUE TITLE
health_state metadata not updated for stopped containers during upgrade.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#4308]
Stopped container is still listed as healthy by metadata.  No container state endpoint available yet (feature requested in #4042) so I can't tell which containers are really healthy or down.

Rancher Version:
Rancher	v1.0.0
Cattle	v0.159.2
User Interface	v0.100.3
Rancher Compose	v0.7.3

Docker Version:
1.10.1

OS: 
Ubuntu 14.04 LTS

Steps to Reproduce: 
 1. Trigger a service upgrade.
 1. Shell into active container. 
 1. `curl` health_state endpoint. 

Stopped container is still listed as healthy by metadata.  

```
# curl -w '\n' rancher-metadata/latest/self/service/containers/0/health_state
healthy
# curl -w '\n' rancher-metadata/latest/self/service/containers/1/health_state
healthy
```

docker-compose.yml
```
metadata:
  environment:
    DEBUG: 'true'
  labels:
    io.rancher.container.pull_image: always
  image: jgreat/rancher-metadata-listen
```

rancher-compose.yml
```
metadata:
  scale: 1
  health_check:
    port: 10000
    interval: 5000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 2000
    healthy_threshold: 2
```
