### ISSUE TITLE
Add a validation check on service/container to prevent attempts to mount a local file as as a volume

### ISSUE THREAD

**Issue by mymanga** [rancher/rancher#4313]
Rancher Version: v1.0.0

Docker Version: 1.10.3

OS: Ubuntu 14.04

Steps to Reproduce: volumes: "./volumes/proxy/certs:/etc/nginx/certs"

Results:   Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidReference, fieldName=LaunchConfigName] from [http://localhost:9000/v1/services]

Expected: create a file

**Comment by cjellick** [comment]
This works find for me:
```
foo:
  image: ubuntu:14.04.4
  volumes:
  - /tmp/foobar:/myfoobar
  tty: true
  stdin_open: true
```

It worked both when /tmp/foobar pre-existed and when it didnt (and was created). Can you provide your full config so that we can troubleshoot better?
