### ISSUE TITLE
[BUG] - Edit cluster not possible on rancher cluster managemant after rke2 update, version not update in cluster managemant

### ISSUE THREAD

**Issue by mailsonsantana** [rancher/rancher#43172]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart): RKE2

**Information about the Cluster**
- Kubernetes version: v1.26.9+rke2r1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in?:  Admin/Cluster

**Describe the bug**
After updating the rke2 cluster version from v1.26.6+rke2r1 to v1.26.9+rke2r1 using the OS package in ubuntu 22.04, it is not possible to edit the cluster in rancher cluster managemant, displaying the message:

 Validation failed in API: cannot upgrade cluster version from [v1.26.9+rke2r1] to [v1.26.6+rke2r1]. New version must be higher.

**To Reproduce**
1º Install RKE2 v1.26.6+rke2r1 in ubuntu 22.04.
2º Install Rancher stable version 2.7.6.
3º Update RKE2 version to v1.26.9+rke2r1 using os package.

**Result**

![image](https://github.com/rancher/rancher/assets/29410717/8b2587d6-0192-44bf-8dca-7aa5696a5f2a)

![image](https://github.com/rancher/rancher/assets/29410717/d18ef75d-bbb2-4dac-ab2a-34e6e69bf62d)

**Expected Result**
Update information in Cluster Management

**Comment by P-n-I** [comment]
I'm seeing this issue as well.

RKE2 cluster with `local` hosted on 3 AWS EC2s.  
Rancher 2.7.9.

RKE2 is installed by the `https://get.rke2.io` script which sets it up as an RPM so dnf will update it periodically.

Our `local` cluster's YAML (truncated):
```
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    management.cattle.io/current-cluster-controllers-version: v1.26.7+rke2r1
  creationTimestamp: '2023-08-02T11:02:32Z'
  name: local
....
spec:
  rke2Config:
    kubernetesVersion: v1.26.11+rke2r1
....
status:
  conditions:
    - lastUpdateTime: '2024-01-15T16:37:06Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-08-02T11:02:43Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-08-02T11:02:43Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-08-02T11:02:41Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-08-02T11:02:45Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-08-02T11:02:48Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-08-02T11:02:50Z'
      status: 'True'
      type: Pending
    - lastUpdateTime: '2023-08-02T11:03:01Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2023-08-02T11:03:06Z'
      status: 'True'
      type: Waiting
    - lastUpdateTime: '2023-08-02T11:02:51Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-08-02T11:02:56Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-08-02T11:02:58Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-08-02T11:02:58Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-08-02T11:03:03Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2023-08-02T11:03:03Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-08-02T11:03:04Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-08-02T11:03:04Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-08-02T11:03:04Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2024-01-03T16:31:20Z'
      status: 'True'
      type: Upgraded
  driver: rke2
....
  provider: rke2
  requested:
    cpu: 4575m
    memory: 7070Mi
    pods: '41'
  version:
    buildDate: '2023-12-20T17:23:45Z'
    compiler: gc
    gitCommit: df63cd7cd818dd2262473d2170f4957c6735ba53
    gitTreeState: clean
    gitVersion: v1.26.12+rke2r1
    goVersion: go1.20.12 X:boringcrypto
    major: '1'
    minor: '26'
    platform: linux/amd64
```
and the packages on the rancher hosts:
```
rke2-common.x86_64                        1.26.12~rke2r1-0.el9                @rancher-rke2-1.26-stable  
rke2-selinux.noarch                       0.17-1.el9                          @rancher-rke2-common-stable
rke2-server.x86_64                        1.26.12~rke2r1-0.el9                @rancher-rke2-1.26-stable  
```
