### ISSUE TITLE
Environment vars that are multiline text are getting newlines removed

### ISSUE THREAD

**Issue by ianwalter** [rancher/rancher#4317]
If you specify an environment variable like the following in the rancher-compose file:
```yml
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      foo = bar
      port = 1234
```
And then try to do an upgrade. The environment variable is displayed in a text field. This should be a text field or text area instead. But this isn't just a display issue, the real issue is that the newlines are removed and so that it's impossible to accurately modify during an upgrade.
