### ISSUE TITLE
namespace does not default to the namespace that is currently selected.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4320]
Rancher Version:v1.0.0

Steps to reproduce the problem:
Create a kubernetese environment with few hosts.
Create a new namespace and then go to this namespace.
Created a Replication Control for nginx container with replicas 2 without providing namespace using the below command:

RC gets created in "default" namespace . 
In this we expect the RC to get created in the namespace that we are currently in ?
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
