### ISSUE TITLE
[BUG] helm-operation is blocked in Pending-Install state

### ISSUE THREAD

**Issue by ZouhairCharef** [rancher/rancher#43237]
**Rancher Server Setup**
- Rancher version: `v2.7.5 `
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `k3s`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.26.6+k3s1`
- Cluster Type (Local/Downstream): `Local`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

**Describe the bug**
The rancher webhook deployment resources already exist on the cluster. However, the webhook is stuck in the "pending install" state, causing the helm operation pod to fail. This results in numerous pods being spawned on the same node, which subsequently leads the node to crash due to an OOM Kill issue.

**Screenshots**
![image](https://github.com/rancher/rancher/assets/38728584/2f165ac9-07f0-4d50-a0c9-78b9025a7c81)

![image](https://github.com/rancher/rancher/assets/38728584/c40daf7a-69aa-41e2-8ec6-6733ee9af262)

![image](https://github.com/rancher/rancher/assets/38728584/48365654-8ae1-42b1-b505-bcda84ea972f)

![image](https://github.com/rancher/rancher/assets/38728584/354ed819-cdee-421a-8e87-4db54f029146)

**Comment by cloudlady911** [comment]
I am having this exact problem after upgrading to Rancher 2.7.7.  Is there a fix?

**Comment by Valgueiro** [comment]
Any updates on it? i am having the same issue on rancher 2.7.9

**Comment by fadjar340** [comment]
So do I....
Even I have to remove the error helm-operation, the pending-install still there...
I use Rancher 2.8.0, Ubuntu 22.04

**Comment by wotsyula** [comment]
Duplicate of #46228

**Comment by wotsyula** [comment]
I have a workaround. In the cluster definition you can add relevant tolerations

```yaml
---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  labels:
  name: ${CLUSTER_NAME}
  namespace: fleet-default
spec:
  agentEnvVars:
    # Enable debug logs
    - name: CATTLE_AGENT_LOGLEVEL
      value: 'debug'
    - name: RKE2_DEBUG
      value: 'TRUE'
    # Enable API audit logging
    - name: RKE2_AUDIT_POLICY_FILE
      value: '/etc/rancher/rke2/audit-policy.yaml'
    # Customize Pod Security Admission config file
    - name: RKE2_POD_SECURITY_ADMISSION_CONFIG_FILE
      value: '/etc/rancher/rke2/rancher-psact.yaml'
  cloudCredentialSecretName: cattle-global-data:${DC8_NAME}
  clusterAgentDeploymentCustomization:
    appendTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  fleetAgentDeploymentCustomization:
    appendTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
```
