### ISSUE TITLE
[BUG] Project Helm Chart creation fails on harden cluster

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#43235]
**Rancher Server Setup**
- Rancher version: v2.8-head/v2.8-alpha2
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.27.6-rancher1-1
- Cluster Type (Local/Downstream): Hardened RKE1 Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS Node Driver

**User Information**
- What is the role of the user logged in? - Admin

**Describe the bug**

Project Helm Chart creation fails on harden RKE1 cluster. (Most probably on RKE2 and K3S as well.)

**To Reproduce**

- Create a rancher server v2.8.0-alpha2
- Provision a downstream RKE1 harden cluster v1.27.6. (2cp, 3etcd, 3 worker nodes) - [hardening guide](https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/rke1-hardening-guide)
- Install Monitoring and Prometheus Federator charts.
- Create a new Project ex. test-project
  - Create a new namespace in a test-project e.g. test-ns
  - Another namespace (Project Registration Namespace) should get created in test-project (cattle-project-p-ID) (ID is randomaly generated string) 
- Create a ProjectHelmChart with following YAML in test-project.
```
apiVersion: helm.cattle.io/v1alpha1
kind: ProjectHelmChart
metadata:
  name: demo
  namespace: cattle-project-p-ID
#  annotations:  key: string
#  labels:  key: string
spec:
  helmApiVersion: monitoring.cattle.io/v1alpha1
```
- A monitoring job gets triggered. This job creates an another namespace and try creating a deployment and app.
- Check the logs of monitoring job.

**Result**
Following error is seen in the monitoring job.
`would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

**Expected Result**
Deployment and Apps get created successfully.

**Additional context**
This issue was encountered while testing Prometheus Federator support for k8s v1.27. - https://github.com/rancher/rancher/issues/41784

**Comment by alexandreLamarre** [comment]
@vivek-shilimkar

It looks like the error seen:

```
would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "patch-sa-cattle-project-p-gn9ww-monitoring" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
````

can indeed be fixed by configuring the security settings in values.yaml  of the helm-project-operator :

 https://github.com/rancher/helm-project-operator/blob/d17d1d9fe1d761759dd60ba1233e28589ef637f3/charts/helm-project-operator/values.yaml#L173-L179
 
and these options IIRC and directly exposed in the prometheus-federator as well, since it directly depends on the helm-project-operator chart :

https://github.com/rancher/prometheus-federator/blob/1edea93ad2496a8837e4ce78abebac60a14d9e47/charts/prometheus-federator/0.4.1/Chart.yaml#L11-L14

**Comment by alexandreLamarre** [comment]
From the original issue : https://github.com/rancher/rancher/issues/41784 , there is a workaround without configuring the security context : 

> Test passes on the harden cluster if the namespaces are set as privileged on harden cluster

**Comment by alexandreLamarre** [comment]
Was able to reproduce this on a downstream hardened rke1 cluster

**Comment by alexandreLamarre** [comment]
I validate that the workaround I proposed, i.e upgrading from this values.yaml:
```yaml
global:
  cattle:
    clusterId: c-lzb44
    clusterName: nick-hardened-rke1
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-dnnp5
    url: https://nick282.qa.rancher.space
  systemDefaultRegistry: ""
helmProjectOperator:
  releaseRoleBindings:
    clusterRoleRefs:
      admin: admin
      edit: edit
      view: view
```
to ones with an added security context in hemlProjectOperator work as expected:
```
global:
  cattle:
    clusterId: c-lzb44
    clusterName: nick-hardened-rke1
    rkePathPrefix: ""
    rkeWindowsPathPrefix: ""
    systemDefaultRegistry: ""
    systemProjectId: p-dnnp5
    url: https://nick282.qa.rancher.space
  systemDefaultRegistry: ""
helmProjectOperator:
  releaseRoleBindings:
    clusterRoleRefs:
      admin: admin
      edit: edit
      view: view
  securityContext:
    runAsGroup : 1000
    runAsUser : 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    privileged: false
    readOnlyRootFilesystem: true
```
