### ISSUE TITLE
script `user-cluster.sh` fails to cleanup Rancher Components from Registered Clusters 

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#43343]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 / RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

script [user-cluster.sh]( https://github.com/rancher/rancher/blob/master/cleanup/user-cluster.sh) fails to cleanup Rancher Components from Registered Clusters .

**To Reproduce**

Create and Import the RKE Cluster:
Stop Rancher Server:
Use the cleanup script: https://github.com/rancher/rancher/blob/master/cleanup/user-cluster.sh to remove the rancher components.

**Result**

```
root@server-2:~# ./user-cluster.sh rancher/rancher-agent:v2.7.6 -dry-run
serviceaccount/cattle-cleanup-sa created
clusterrolebinding.rbac.authorization.k8s.io/cattle-cleanup-binding created
job.batch/cattle-cleanup-job created
clusterrole.rbac.authorization.k8s.io/cattle-cleanup-role created
Error from server (BadRequest): container "cleanup-agent" in pod "cattle-cleanup-job-9j6dc" is waiting to start: ContainerCreating
Error from server (BadRequest): container "cleanup-agent" in pod "cattle-cleanup-job-9j6dc" is waiting to start: ContainerCreating
Error from server (BadRequest): container "cleanup-agent" in pod "cattle-cleanup-job-9j6dc" is waiting to start: ContainerCreating
time="2023-10-31T13:34:22Z" level=warning msg="failed to reconcile kubelet, error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
time="2023-10-31T13:34:22Z" level=info msg="Starting cluster cleanup"
time="2023-10-31T13:34:22Z" level=info msg="Listening on /tmp/log.sock"
time="2023-10-31T13:34:22Z" level=fatal msg="checking for cattle-system/rancher service: services \"rancher\" is forbidden: User \"system:serviceaccount:default:cattle-cleanup-sa\" cannot get resource \"services\" in API group \"\" in the namespace \"cattle-system\""
serviceaccount "cattle-cleanup-sa" deleted
clusterrolebinding.rbac.authorization.k8s.io "cattle-cleanup-binding" deleted
job.batch "cattle-cleanup-job" deleted
clusterrole.rbac.authorization.k8s.io "cattle-cleanup-role" deleted
root@server-2:~# 
```

**Expected Result**

script shouldn't fail

**Screenshots**

```
time="2023-10-31T13:34:22Z" level=fatal msg="checking for cattle-system/rancher service: services \"rancher\" is forbidden: User \"system:serviceaccount:default:cattle-cleanup-sa\" cannot get resource \"services\" in API group \"\" in the namespace \"cattle-system\""

time="2023-10-31T13:37:09Z" level=fatal msg="Errors: mutatingwebhookconfigurations.admissionregistration.k8s.io \"rancher.cattle.io\" is forbidden: User \"system:serviceaccount:default:cattle-cleanup-sa\" cannot delete resource \"mutatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope validatingwebhookconfigurations.admissionregistration.k8s.io \"rancher.cattle.io\" is forbidden: User \"system:serviceaccount:default:cattle-cleanup-sa\" cannot delete resource \"validatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\"
```

**Additional context**

**Comment by KevinJoiner** [comment]
The Webhook errors seem to be related to changes added in https://github.com/rancher/rancher/issues/40164.

@skanal are there missing logs? The output of the script does not appear to contain the webhook error under additional context.

**Comment by skanakal** [comment]
@KevinJoiner Nope. The script is exiting before reaching that point. So, once I fix permissions related to services, it then moves to webhook errors.

**Comment by chimisu** [comment]
below yaml is worked for me

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cattle-cleanup-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cattle-cleanup-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cattle-cleanup-role
subjects:
- kind: ServiceAccount
  name: cattle-cleanup-sa
  namespace: default

---

apiVersion: batch/v1
kind: Job
metadata:
  name: cattle-cleanup-job
  namespace: default
  labels:
    rancher-cleanup: "true"
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: CLUSTER_CLEANUP
          value: "true"
        # - name: DRY_RUN
          # value: "true"
        image: rancher/rancher-agent:v2.7.8
        imagePullPolicy: Always
        name: cleanup-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: cattle-cleanup-sa
      terminationGracePeriodSeconds: 30

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cattle-cleanup-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - list
  - get
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - get
  - update
  - delete
```
