### ISSUE TITLE
[feature] [pool] Should we configure MELB routes on services definition?

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#4335]
You probably are wondering what MELB means, well, when I see a pattern and I don't know what to call it I give it a name:
###### Main Endpoint Load Balancers.

Probably most of us are using main load balancers as entrypoints for the multiple services we offer on our servers.

Since there is a load balancer refactoring going on (#2179), I wanted to know what the community and rancher team members think about this.

My proposal resides to evolve the **MELB** pattern and make it easier to use, by allowing services to dictate routing configuration instead. Before giving you further explanation, I would like you to see some service proposal examples.

## Proposal examples:

Those examples cover: 
- multiple route definitions per service
- http and https
- source and target ports (source ports should be previously defined on the MELB)
- path definition
- https certificate definition

### Yaml
```yaml
redirect-example-org:
  environment:
    REDIRECT: https://www.example.org/en
  tty: true
  stdin_open: true
  image: cusspvz/redirect:0.0.1
  loadbalancer:
    -
      service: main-lb/http
      domain: example.org
      lb-port: 80
      port: 80
    -
      service: main-lb/http
      domain: www.example.org
      lb-port: 80
      port: 80

example-org:
  image: tutum/nginx
  tty: true
  stdin_open: true
  loadbalancer:
    -
      service: main-lb/https
      domain: www.example.org
      path: /en
      certificate: www.example.org
      lb-port: 443
      port: 80
```

### Labels
```yaml
redirect-example-org:
  environment:
    REDIRECT: https://www.example.org/en
  tty: true
  stdin_open: true
  image: cusspvz/redirect:0.0.1
  labels:
    - io.rancher.loadbalancer.route.0: service=main-lb/http&domain=example.org&lb-port=80&port=80
    - io.rancher.loadbalancer.route.1: service=main-lb/http&domain=www.example.org&lb-port=80&port=80

example-org:
  image: tutum/nginx
  tty: true
  stdin_open: true
  labels:
    - io.rancher.loadbalancer.route.0: service=main-lb/https&domain=www.example.org&path=/en&certificate=www.example.org&lb-port=443&port=80
```

## Why?

I've been using **MELB** for a while and whenever I want to expose a service on a cluster I have to manually go the MELB configuration and edit it. There is, of course, the chance to edit it over the API or the respective compose but that means to figure out different implementations on different services or to carry out constantly updated composes, but both of those solutions are either complex and/or completely non fault tolerant.

## How?

If the community manifests interest to evolve this concept/proposal, I see two chances here:
- To include this as a feature part of the rancher load balancer service, which could be togglable for security reasons;
- Or to create a service based on `rancher-metadata` service data fetching, but the offer of features couldn't be as high as the rancher load-balancer service is.

#### Pros:

- This would allow us to automatically launch canary http-based services or any other kind of temporary services without much hassle.

#### Cons:
- ...

#### Other ideas:
- A DNS service or integration could be offered in case this is implemented over the second approach.
