### ISSUE TITLE
Unable to create application stack

### ISSUE THREAD

**Issue by Aamir010** [rancher/rancher#4337]
Rancher Version:1.0

Docker Version: 1.10.3

OS: Ubuntu 14.04

Steps to Reproduce: Create a application with docker-compose.yml

services:
  web:
    image: 192.168.0.102:5000/jahia-web
    hostname: Jahia-CMS
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db:db

  db:
    image: 192.168.0.102:5000/jahia-db
    hostname: Jahia-DB
    ports:
      - "3306:3306"
    environment:
      - CREATEDB=true
      - MYSQL_CLIENT=%
      - MYSQL_PASS=root
      - MYSQL_DB=digital_factory
      - APP_USER=jahia
      - APP_PASS=jahia

Results: 

Activating (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidOption, fieldName=Image is required when selectorContainer is not passed in] from [http://localhost:8080/v1/projects/1a5/services]) 

Expected:
Application stack started. As its work with Docker-Compose

**Comment by Beanow** [comment]
I've had the same issue just now.
You can add a label `io.rancher.service.selector.container` (see http://docs.rancher.com/rancher/labels/).
I'm a fairly new users, but as I understand it this is used for the DNS routing capabilities.

**Comment by deniseschannon** [comment]
First issue: `depends_on` is not in libcompose, which is what rancher-compose is based on. If a service is dependent on another starting up, you can just use links, which will start the services in the desired order. 

Second Issue: The `services` that is in the docker-compose.yml is causing the error that you are facing as rancher-compose is considering `services` as a service name and expecting an `image` or `build`

If you run this docker-compose.yml, then it should work as expected.

```
web:
  image: 192.168.0.102:5000/jahia-web
  hostname: Jahia-CMS
  ports:
    - "8080:8080"
  depends_on:
    - db
  links:
    - db:db

db:
  image: 192.168.0.102:5000/jahia-db
  hostname: Jahia-DB
  ports:
    - "3306:3306"
  environment:
    - CREATEDB=true
    - MYSQL_CLIENT=%
    - MYSQL_PASS=root
    - MYSQL_DB=digital_factory
    - APP_USER=jahia
    - APP_PASS=jahia
```

**Comment by Aamir010** [comment]
Yeah. Its working fine. Thanks :)

**Comment by maslennikov** [comment]
Hi @deniseschannon 

I had a related dependency problem with Rancher v1.6.2 which was solved by providing an extra `links` key. Could you elaborate on a couple of questinos though?

Simplified `docker-compose.yml` describes two services, a postgres server and a dummy start-once migrator that immediately tries to connect to the server at $NET_DB_URL env variable after it is started. Without `links` key it started first and DNS didn't even resolve the `postgres` host at that time (or it ended anyways with ECONNREFUSED).

```yaml
version: '2'
services:
  postgres:
    image: postgres:9.6
    labels:
      io.rancher.service.wait_for_healthcheck: 'true'  # <== not working solely with depends_on

  migrator:
    image: ${MIGRATOR__IMAGE_VERSION}
    depends_on:  # <== not listed in the "Compose YAML" UI
      - postgres
    links:
      - postgres  # <== not working without it
    labels:
      io.rancher.container.start_once: 'true'
    environment:
      NET_DB_URL: postgres://postgres@postgres
```

Questions:

A) You mentioned that `depends_on` is not in libcompose, but as I looked up, it is already there since v0.3.0. Is there a place where I can look which libcompose version my current Rancher setup is using? 

B) There ls a label description at https://docs.rancher.com/rancher/v1.6/en/cattle/labels/ telling us: 

> `io.rancher.service.wait_for_healthcheck` Available as of v1.6.1: Used to require health check to transition to healthy before considering the service deployed. Any services dependent on this service **(when using depends_on in compose)** will not deploy until the service is in a healthy stated defined by the health check. 

Is it broken or am I missing something assuming that I need to provide only the label - `depends_on` pair to kick this off? When I go into the "Compose YAML" section of a stack in the UI, I don't even see the `depends_on` key.
