### ISSUE TITLE
[BUG] Rancher-monitoring serviceMonitor rke etcd,scheduler,proxy,controller-manager broken

### ISSUE THREAD

**Issue by rlanore** [rancher/rancher#43382]
### Rancher Server Setup
- Rancher version: no
- Installation option (Docker install/Helm Chart):
   -  Rke v1.4.8
   - Helm chart rancher-monitoring 102.0.1+up40.1.2

### Information about the Cluster
- Kubernetes version:  v1.26.7-rancher1-1
- Cluster Type: Local ( bare metal )
  
### User Information
Default cluster admin from rke up command

### Describe the bug
After helm install rancher-monitoring chart no metric from etcd, controller-manager, sheduler, proxy
You can see this log into prometheus operator

```
level=warn XXX caller=operator.go:2253 component=prometheusoperator msg="skipping servicemonitor" error="relabel configuration for replace action needs targetLabel value" service
```

Foreach servciemonitor

### To Reproduce
Generate yaml template with helm values

```yaml
namespaceOverride: "monitoring"
prometheus-adapter:
  enabled: true
  prometheus:
    url: http://rancher-monitoring-prometheus.monitoring.svc
    port: 9090
  psp:
    create: true
  resources:
    limits:
      memory: 2048Mi
      cpu: 2000m
    requests:
      memory: 1024Mi
      cpu: 1000m
rkeControllerManager:
  enabled: true
rkeScheduler:
  enabled: true
rkeProxy:
  enabled: true
rkeEtcd:
  enabled: true
rancherMonitoring:
  enabled: false
ingressNginx:
  enabled: true
  namespace: ingress-nginx
alertmanager:
  enabled: false
grafana:
  enabled: true
  namespaceOverride: "monitoring"
  grafana.ini:
    users:
      auto_assign_org_role: Viewer
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false
      org_role: Viewer
    auth.basic:
      enabled: false
    auth.ldap:
      enabled: false
    dashboards:
      default_home_dashboard_path: /tmp/dashboards/rancher-default-home.json
    security:
      allow_embedding: true
  defaultDashboards:
    namespace: monitoring
    useExistingNamespace: true
    cleanupOnUninstall: false
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    ingressClassName: private
    hosts:
    - grafana.private-svc.foo.bar
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring
      annotations: {}
      multicluster:
        global:
          enabled: false
        etcd:
          enabled: false
      provider:
        allowUiUpdates: false
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      annotations: {}
      createPrometheusReplicasDatasources: false
      label: grafana_datasource
  persistence:
    type: pvc
    enabled: true
    existingClaim: grafana-manual-claim
prometheusOperator:
  enabled: true
  nodeSelector:
    namenode: "true"
prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: private
    annotations: {}
    labels: {}
    hosts:
    - prometheus.private-svc.foo.bar
    paths: []
    tls: []
  ingressPerReplica:
    enabled: false
    annotations: {}
    labels: {}
    hostPrefix: ""
    hostDomain: ""
    paths: []
    tlsSecretName: ""
    tlsSecretPerReplica:
      enabled: false
      prefix: "prometheus"
  podSecurityPolicy:
    allowedCapabilities: []
    allowedHostPaths: []
    volumes: []
  serviceMonitor:
    interval: ""
    selfMonitor: true
    scheme: ""
    tlsConfig: {}
    bearerTokenFile:
    metricRelabelings: []
    relabelings: []
  prometheusSpec:
    nodeSelector:
      namenode: "true"
    retention: 10d
    retentionSize: "10GB"
    resources:
      limits:
        memory: 6000Mi
        cpu: 4000m
      requests:
        memory: 750Mi
        cpu: 750m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "ceph-filesystem"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "20Gi"
```
Template a yaml file with helm template

```bash
helm template test ./ -f /tmp/values.yaml > /tmp/rancher-monitoring.yaml
```

This command produce a very big yaml file. it contain serviceMonitor like this:

```yaml
# Source: rancher-monitoring/charts/rkeScheduler/templates/pushprox-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-kube-scheduler
  namespace: monitoring
  labels:
    app: test-kube-scheduler
    release: test
    component: "kube-scheduler"
    provider: kubernetes
spec:
  endpoints:
    - metricRelabelings:
      - {}
      - {}
      params:
        _scheme:
        - https
      port: metrics
      proxyUrl: http://pushprox-kube-scheduler-proxy.monitoring.svc:8081
  jobLabel: component
  podTargetLabels:
  - component
  - pushprox-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      k8s-app: pushprox-kube-scheduler-client
      release: test
      component: "kube-scheduler"
      provider: kubernetes
---
```
After a kubectl apply of this yaml the two line empty on metricRelabelings
```yaml
spec:
  endpoints:
    - metricRelabelings:
      - {}
      - {}
```

is replaced by k8s like this

```yaml
spec:
  endpoints:
   - metricRelabelings:
     - action: replace
     - action: replace
```
Example helm template for etcd: https://github.com/rancher/charts/blob/dev-v2.8/charts/rancher-monitoring/102.0.1%2Bup40.1.2/templates/exporters/kube-etcd/servicemonitor.yaml

### Actual Result
No scrap from prometheus

### Expected Result
Scrap from prometheus
