### ISSUE TITLE
[BUG] Rancher Monitoring Chart: MetricRelabeling for ingress-nginx exporter has wrong indentation in template

### ISSUE THREAD

**Issue by staerion** [rancher/rancher#43396]
### Rancher Server Setup
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart):
   - Chart version 102.0.1+up40.1.2 and chart rancher-monitoring
- Proxy/Cert Details: N/A

### Information about the Cluster
- Kubernetes version: 25.9
- Cluster Type (Local/Downstream):
   -Downstream

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Cluster Owner

### Describe the bug
When we had the values

```yaml
ingressNginx:
  enabled: true
  serviceMonitor:
    metricRelabelings:
    - action: drop
      regex: (.*bucket)
      sourceLabels:
      - __name__
```

and feed them to the rancher-monitoring chart with version 102.0.1+up40.1.2 we get an error:

```bash
Error: YAML parse error on rancher-monitoring/templates/rancher-monitoring/exporters/ingress-nginx/servicemonitor.yaml: error converting YAML to JSON: yaml: line 30: did not find expected key
```

We suspect this is related to the line

```
    {{ tpl (toYaml .Values.ingressNginx.serviceMonitor.metricRelabelings | indent 4) . }}
```
in the servicemonitor template which has an erroneous indentation.

### To Reproduce
Create a values file:

```yaml
---
ingressNginx:
  enabled: true
  serviceMonitor:
    metricRelabelings:
    - action: drop
      regex: (.*bucket)
      sourceLabels:
      - __name__
---

```bash
helm template rancher-monitoring rancher/rancher-monitoring  -f <values-file> --version 102.0.1+up40.1.2

### Actual Result
An error is returned:

```bash
Error: YAML parse error on rancher-monitoring/templates/rancher-monitoring/exporters/ingress-nginx/servicemonitor.yaml: error converting YAML to JSON: yaml: line 30: did not find expected key

Use --debug flag to render out invalid YAML
```

### Expected Result
The ingress-nginx service monitor is updated with the desired metricRelabelings:

```yaml
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: (.*bucket)
      sourceLabels:
      - __name__
```

### Screenshots
N/A

### Additional context
Link to the erroneous line:
https://github.com/rancher/charts/blob/8ab2bb4a519bfcc7d788ba00e1bda57a060ca243/charts/rancher-monitoring/102.0.1%2Bup40.1.2/templates/rancher-monitoring/exporters/ingress-nginx/servicemonitor.yaml#L33
