### ISSUE TITLE
[BUG] Wrong "metricRelabelings" after upgrade to 102.0.1+up40.1.2

### ISSUE THREAD

**Issue by thystips** [rancher/rancher#43397]
### Rancher Server Setup
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.24.3+rke2r1
- Proxy/Cert Details: LetsEncrypt

### Information about the Cluster
- Kubernetes version: v1.24.3+rke2r1
- Cluster Type (Local/Downstream): local

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? None
- What is the version of Terraform in use? None

### Describe the bug
Unable to fresh install rancher-monitoring version 102.0.1+up40.1.2 from local helm

### To Reproduce
1.Get values from chart
2. Enable :
  - rke2ControllerManager
  - rke2Scheduler
  - rke2Proxy
  - rke2Etcd
  - rke2IngressNginx
3. Deploy with HELM

```yaml
rke2ControllerManager:
  enabled: true
rke2Scheduler:
  enabled: true
rke2Proxy:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx:
  enabled: true
  component: kube-system
```

### Actual Result
CrashLoopBackOff on Prometheus Pod.

Logs from init-config-reloader :
```
ts=2023-07-10T14:01:34.863Z caller=main.go:454 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

I found this when getting helm values :

```yaml
rke2ControllerManager:
  [...]
  serviceMonitor:
    enabled: true
    endpoints:
      - metricRelabelings:
          - {}
          - {}
```

Same in `rke2Etcd`, `rke2IngressNginx`, `rke2proxy` and `rke2Scheduler`

### Expected Result
Working rancher-monitoring install.

### Additional context
- No issue with older version

**Comment by cornfeedhobo** [comment]
@murand78 I think this essentially confirms what I was trying to figure out; in rancher, name is the same as "id". Thanks :)

**Comment by cornfeedhobo** [comment]
@murand78 Could you provide a screenshot of where you think the cluster-events view is showing a cluster id?

Regardless, it would appear that this suggested workaround **does not work**

```yaml
global:
  cattle:
    clusterId: xxxxx
    clusterName:  xxxxx
```
