### ISSUE TITLE
Can't install rancher-monitoring 102.0.0+up40.1.2 with Fleet

### ISSUE THREAD

**Issue by mkindalov** [rancher/rancher#43404]
### Rancher Server Setup
- Rancher version: 2.7..we the same issue with 2.7.*
- Installation option (Docker install/Helm Chart):
   - RKE1

### Information about the Cluster
- Kubernetes version: 1.24 and 1.25
- Cluster Type (Local/Downstream):
   - downstream, RKE1:

### Describe the bug
Chart version "100.1.3+up19.0.3" is the last version that can be installed with Fleet. The problem is: chart becomes too big.
Fleet produces an error: "etcdserver: request is too large"
I tried this with 102.0.0+up40.1.2.
We can say that this is a "bug" in fleet: https://github.com/rancher/fleet/issues/205, but this does not solve the problem :)

### To Reproduce
```yaml
defaultNamespace: cattle-monitoring-system
helm:
  releaseName: rancher-monitoring
  chart: rancher-monitoring
  repo: https://charts.rancher.io
  version: 102.0.0+up40.1.2
```

### Actual Result
Fleet job fails with:
`Error (time="2023-06-13T13:39:46Z" level=fatal msg="etcdserver: request is too large" )`

### Expected Result
Rancher monitoring is installed on a downstream cluster

### Proposed solution
Split the chart in some way.
