### ISSUE TITLE
[BUG] [KSM/Kubelet] Bugs in templating of metricRelabelings icw cluster{Id|Name}

### ISSUE THREAD

**Issue by hansbogert** [rancher/rancher#43402]
### Rancher Server Setup
- Rancher version: 2.7
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

### Information about the Cluster
N/A

### User Information
N/A

### Provider Information
N/A

### Describe the bug
When templating rancher-monitor with metricRelabelings for kube-state-metrics and the kubelet, the templating fails, see reproduction

### To Reproduce

```
cd charts/rancher-monitoring/102.0.1+up40.1.2
cat << EOF > minimal.yaml
global:
  cattle:
    clusterId: "foobar"
    clusterName: foorbar

kube-state-metrics:
  enabled: true
  prometheus:
    monitor:
      enabled: true
      interval: 60s
      metricRelabelings:
        - action: keep
          regex: kube_configmap_info
          sourceLabels: [__name__]
kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: keep
        regex: kubelet_node_config_error
        sourceLabels:
        - __name__
EOF

helm template .  -f minimal.yaml

# output:

```

### Actual Result

```
helm template .  -f minimal.yaml
Error: YAML parse error on rancher-monitoring/templates/exporters/kubelet/servicemonitor.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key

Use --debug flag to render out invalid YAML
```

### Expected Result
Would've expected properly rendered yaml.

### Additional context
SURE-7384
