### ISSUE TITLE
[BUG] Rancher-logging chart seems to have fluentd.tolerations as a map but probably should be a slice

### ISSUE THREAD

**Issue by herrbpl** [rancher/rancher#43419]
### Describe the bug
Chart rancher-logging values.yaml has default for `fluentd.tolerations` as empty map

Bug only appears if you want to specify custom tolerations for fluentd deployment. 

https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-logging/100.1.4%2Bup3.17.7/values.yaml#L214 

```yaml
fluentd:
  tolerations: {}
```
This makes it incompatible to pass down to actual Logging object which exptect per spec
https://github.com/rancher/charts/blob/release-v2.6/charts/rancher-logging-crd/100.1.4%2Bup3.17.7/templates/logging.banzaicloud.io_loggings.yaml#L4309 :
```yaml
tolerations:
  items:
    properties:
      effect:
        type: string
      key:
        type: string
      operator:
        type: string
      tolerationSeconds:
        format: int64
        type: integer
      value:
        type: string
    type: object
  type: array
```

### To Reproduce
Pass tolerations as array down to chart and see it failing to merge slice and array

### Actual Result
Fluentd deployed with tolerations applied

### Expected Result
Chart fails to deploy because of incompatible parameter type for fluentd.tolerations in values.yaml
