### ISSUE TITLE
[BUG][rancher-monitoring-crd] Missing subresource status on prometheus operator

### ISSUE THREAD

**Issue by QustodioPablo** [rancher/rancher#43418]
# Issue
After upgrading to 100.2.0+up40.1.2, alert manager was not updating its configuration.
Checked the prometheus operator logs, and found the following error:
```
level=error ts=2023-03-24T17:11:18.663327398Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"cattle-monitoring-system/rancher-monitoring-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"rancher-monitoring-prometheus\" not found"
```

# Additional info
On the prometheus-operator repository found this issue: https://github.com/prometheus-operator/prometheus-operator/issues/4823#issuecomment-1154934837
I checked the CRD on rancher-monitoring-crd, and there is no status subresource defined.

**Comment by junkiebev** [comment]
There's an ugly way to get over this if it's present in your version and not likely to to fixed (2.7, etc)

Just add this manifest to your cluster:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  labels:
    app: rancher-monitoring-crd-manager-patch
  name: rancher-monitoring-crd-manager-patch
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - patch
  - delete
  - replace
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: rancher-monitoring-crd-manager-patch
  name: rancher-monitoring-crd-manager-patch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-monitoring-crd-manager
subjects:
- kind: ServiceAccount
  name: rancher-monitoring-crd-manager
  namespace: cattle-monitoring-system
```
