### ISSUE TITLE
[RFE] [rancher-logging] Prefix systemDefaultRegistry to all images

### ISSUE THREAD

**Issue by mouellet** [rancher/rancher#43421]
### Is your feature request related to a problem? Please describe.

Right now most of the images used have repositories and tag values found in the chart's value.yaml and those values are automatically prefixed w/ the `{{ template "system_default_registry" . }}`.

Some of them, found in the logging crd, are missing. Here's what I've found, there might be others.. :
- `fluentbit.bufferVolumeImage`
- `fluentd.bufferVolumeImage`
- `fluentd.volumeModImage`
- `fluentd.scaling.drain.image`
- `fluentd.scaling.drain.pauseImage`

### Describe the solution you'd like
For all images used in the chart to be automatically prefixed w/ the system default registry.

### Describe alternatives you've considered
The values can be specified explicitly, but would required chart consumer to dig for the new/updated images tag or repository on upgrades.

Ex.:
```
  loggingOverlay:
    spec:
      fluentbit:
        bufferVolumeImage:
          repository: my.private-registry.io/banzaicloud/custom-runner
          tag: 0.1.0
      fluentd:
        bufferVolumeImage:
          repository: my.private-registry.io/banzaicloud/custom-runner
          tag: 0.1.0
        volumeModImage:
          repository: my.private-registry.io/busybox
          tag: latest
```
