### ISSUE TITLE
[rancher-vsphere-csi] Variables for X_CSI_DEBUG and LOGGER_LEVEL in values.yaml

### ISSUE THREAD

**Issue by yannpichon-su** [rancher/rancher#43436]
## Expected Behavior
I would like to set the log level of the CSI Driver depending on my Kubernetes environment (dev, staging, prod ...). To do so, I want to
set the X_CSI_DEBUG and LOGGER_LEVEL environnement variables used by the vsphere-csi-node DaemonSet template in  values.yaml. 

Example : 
```` yaml
# templates/vsphere-csi-node-ds.yaml
- name: X_CSI_DEBUG
  value: {{ .Values.csiNode.env.x_csi_debug }}
- name: LOGGER_LEVEL
  value: {{ .Values.csiNode.env.logger_level}}

# values.yaml
csiNode:
  env:
    x_csi_debug: false
    env.logger_level: PRODUCTION
````
## Actual Behavior
As these variables are set by default in templates/vsphere-csi-node-ds.yaml, I have to patch the DaemonSet after deploying the Helm chart to make sure I have the adequate log level depending on my environment :
````
kubectl set env -n kube-system daemonset/vsphere-csi-node -c vsphere-csi-node X_CSI_DEBUG=false
````

## Specifications
  - Version: 2.1.000
  - Platform: Rancher 2.5 - Kubernetes 1.19
