### ISSUE TITLE
rancher-monitoring kind: AlertmanagerConfig doesn't appear in route

### ISSUE THREAD

**Issue by Giancarlo1974** [rancher/rancher#43435]
I read in [this issue](https://github.com/rancher/charts/issues/871), that you have introduces the CRD AlertmanagerConfig

However when I try it, the configuration does not appear in the Cluster Monitoring routes

This is the yaml of what i have created:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  namespace: cattle-monitoring-system
  name: example
  labels:
    alertmanagerConfig: example
    release: prometheus-stack
spec:
  route:
    groupBy: ["job"]
    groupInterval: 1m
    groupWait: 30s
    receiver: "null"
    repeatInterval: 12h
    routes:
      - receiver: foo-msteams
        matchers:
          - name: customer
            value: foo
```

I don't know if it's a Rancher Monitoring bug or I'm setting up the wrong one

can you help me?
