### ISSUE TITLE
[Rancher-Monitoring] Alertmanager.yaml does not support side car container

### ISSUE THREAD

**Issue by xxmaestroxx** [rancher/rancher#43431]
We tried to secure the Alertmanager container and UI via tls and authentication and wanted to add just an ngnix sidecar to it, to use the easiest way. We did the same for Prometheus and there it worked.

We could just find one difference between both:
- templates/Prometheus.yaml -> {{ tpl .Values.prometheus.prometheusSpec.containers $ | indent 4 }}
- templates/Alertmanager.yaml -> {{ toYaml .Values.alertmanager.alertmanagerSpec.containers | indent 4 }}

Not sure why it is different in this case, but our code snippet works for Prometheus, but is not working for Alertmanager.

The snippet below shows the config for Prometheus. For Alertmanager we just adapted the port to the correct one.

Snippet:
```
prometheusSpec:
      containers: |
        - name: prometheus-proxy
          args:
          - nginx
          - -g
          - daemon off;
          - -c
          - /nginx/ssl/nginx.conf
          image: "rancher/library-nginx:1.19.2-alpine"
          ports:
          - containerPort: 8080
            name: nginx-http
            protocol: TCP
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "32Mi"
              cpu: "100m"
          volumeMounts:
          - name: prometheus-cert
            readOnly: true
            mountPath: /etc/ssl/certs/
          - name: prometheus-client-cert
            readOnly: true
            mountPath: /etc/nginx/client_certs/
          - mountPath: /nginx
            name: prometheus-nginx
          - mountPath: /var/cache/nginx
            name: nginx-home
          - mountPath: /nginx/ssl
            name: prometheus-nginx-ssl
          securityContext:
            runAsUser: 101
            runAsGroup: 101
        - name: prometheus
          env:
          - name: JAEGER_AGENT_PORT
            value: "5775"
```
