### ISSUE TITLE
rancher-logging-crd: cloudwatch output requires log_group_name/log_stream_name preventing the use of use_tag_as_group/use_tag_as_stream

### ISSUE THREAD

**Issue by aven-mathew** [rancher/rancher#43441]
Trying to use rancher logging with an output to cloudwatch. Similar to the below.
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: ingress-nginx-logging-output
  namespace: ingress-nginx
spec:
  cloudwatch:
    auto_create_stream: true
    buffer:
      timekey: 30s
      timekey_use_utc: true
      timekey_wait: 30s
    log_group_name: ingress-nginx
    use_tag_as_stream: true
    region: us-east-2
```
However this is not allowed by the CRD restrictions. Looking at the upstream these requirements appear to not exist.

https://github.com/banzaicloud/logging-operator/blob/master/config/crd/bases/logging.banzaicloud.io_outputs.yaml#L1170
