### ISSUE TITLE
[rancher-gatekeeper] gatekeeper-update-crds-hook fails when PodSecurityPolicies are enabled

### ISSUE THREAD

**Issue by brownz11** [rancher/rancher#43453]
When installing `rancher-gatekeeper` version `100.0.1+up3.6.0` in a cluster that has the PSP admission controller enabled, the installation fails when running _gatekeeper-update-crds-hook_ with an error message of `Error: container has runAsNonRoot and image will run as root`

The relevant part of the Pod created from the Job appears to be
```
apiVersion: v1
kind: Pod
metadata:
  name: gatekeeper-update-crds-hook-7f69l
  namespace: cattle-gatekeeper-system
spec:
  containers:
  - args:
    - apply
    - -f
    - crds/
    image: rancher/mirrored-openpolicyagent-gatekeeper-crds:v3.6.0
    imagePullPolicy: IfNotPresent
    name: crds-upgrade
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    [...SNIP...]
```
It looks like the Pod is set to runAsNonRoot, but has no runAsUser. I assume this is due to the fact that the Helm Chart for this specific Job doesn't have a `runAsUser` stanza.
