### ISSUE TITLE
[BUG] --audit-policy-file flag is missing in API Server when setting audit-policy-file

### ISSUE THREAD

**Issue by enneitex** [rancher/rancher#43522]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.26.5
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): rke2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

`--audit-log-path` is missing in API server flags after upgrading downstream cluster from 1.257 to 1.26.5

**To Reproduce**

- create a downstream rke2 cluster in v1.25 withan audit policy configured (following method 1in [this doc](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-api-audit-log-in-downstream-clusters#method-1-recommended-set-audit-policy-file-in-machineglobalconfig)):
```yaml
    machineGlobalConfig:
      audit-policy-file: |
        apiVersion: audit.k8s.io/v1 
        kind: Policy 
        rules: 
        - level: RequestResponse
          resources:
          - group: ""
            resources: 
            - pods
```
- upgrade the cluster to 1.26.
- The flag `audit-policy-file` is missing
**Result**

Flags are `kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-policy-file=/var/lib/rancher/rke2/etc/config-files/audit-policy-file --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100`

**Expected Result**

Flags are `kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-policy-file=/var/lib/rancher/rke2/etc/config-files/audit-policy-file --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100` with `audit-log-path` defined

**Screenshots**

**Additional context**
As a workaround, I added the flag manually:
```yaml
kube-apiserver-arg:
  - audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log
```
