### ISSUE TITLE
Rancher moves loadbalancer to new host and it stops routing traffic correctly

### ISSUE THREAD

**Issue by ianwalter** [rancher/rancher#4352]
Rancher Version: v1.0.0

Docker Version: v1.10.3

OS: 
Original Host: Debian 8
New Host: Ubuntu 14.04

Steps to Reproduce:
1. Create a service
2. Create a loadbalancer to forward a domain name to the service.
3. Add a new host

Results: 
Rancher moved the loadbalancer to the new host (and left all the other containers on the original host). The loadbalancer is no longer forwarding to the service. Rancher says all services are healthy but the service is not configured for a health check.

Expected:
The loadbalancer continues to route traffic to the service.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml of your stack?

Also, when you added a new host, did anything happen to your old host? If your old host went into reconnecting, Rancher knows nothing of the state of those containers (as they don't have a health check), where as it sounds as if the load balancer (which comes with a health check) determined there was something wrong with the old host and moved to the new one. In order for targets of a load balancer to move to the new host, they would need to be enabled with their own health checks.

**Comment by ianwalter** [comment]
Here is the app's docker-compose.yml (is this what you meant?):
```
gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:8.6.4-ce.0
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab
gitlab-server:
  ports:
  - 22:22/tcp
  - 9801:80/tcp
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      nginx['listen_port'] = 9801
      nginx['listen_https'] = false
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.mailgun.org"
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: git.optick.io
  image: gitlab/gitlab-ce:8.6.4-ce.0
  volumes_from:
  - gitlab-data
```

I didn't see anything happen to my old host. Also, when I deactivated the new host, the loadbalancer didn't go back to the old host, which is troubling. When I manually deleted the server through Packet, the loadbalancer did go back to the old host and is routing traffic correctly again.

**Comment by ianwalter** [comment]
I should also note that the loadbalacer and the application are in different stacks. I didn't want to put them in the same stack because the loadbalancer is listening on 443 and will be routing traffic to different services based on domain.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml for your load balancer?

**Comment by ianwalter** [comment]
```yml
loadbalancer:
  ports:
  - 443:80
  external_links:
  - gitlab/gitlab-server:gitlab-server
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.gitlab/gitlab-server: git.mydomain.com:443=9801
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```
