### ISSUE TITLE
Isolating pod from replication controller from UI doesn't work  

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4356]
Rancher Version:
1.0.0
Docker Version:
1.10.3, build 20f81dd
OS: 
ubuntu 14.04
Steps to Reproduce: 
- Install Rancher and register one host
- run kubernetes environment
- create replication controller for Nginx with 2 replicas:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: nginx
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
    livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
              - name: X-Custom-Header
                value: Awesome
        initialDelaySeconds: 15
        timeoutSeconds: 1
        ports:
        - containerPort: 80
```
- Edit the label of one of the pods and remove the app: nginx label to isolate the pod from replication controller.
- Try the same procedure but using: 

```
kubectl edit pods podname
```

Results: 

When trying to edit the pods label from the UI the label keeps regenerated, but when removing the pod's label using kubectl it gets removed and the rc schedule another pod to replace the removed pod from the pool. 

Expected:

The label gets removed in both Rancher UI and kubectl.
