### ISSUE TITLE
[BUG] RKE2: "Additional Manifest" when restarting the master node, the node does not start

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [rancher/rancher#43614]
**Rancher Server Setup**
- Rancher version: v2.7.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1/RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.24.17+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   Hosted

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
  Cluster Owner

**Describe the bug**

When restarting the master node, the Additional Manifest is not applied to the master. Node does not start

**To Reproduce**

Restart the master node. The node becomes unavailable. There is no config on the master along the path /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml. In order for the cluster to start, you need to update the cluster settings, remove the Additional Manifest field, save, then add Additional Manifest again, and only then the file will appear on the node and the cluster will work properly.

**Result**
As a result, when a node crashes, it is not enough to simply restart the node; you need to update the cluster
**Expected Result**

Valid restart of the node without unnecessary actions.
**Screenshots**

**Additional context**

/var/lib/rancher/rke2/server/manifests/rancher/addons.yaml:

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        mtu: MTU
        nodeAddressAutodetectionV4:
          firstFound: false
          cidrs:
            - "IP/24"
```

**Comment by Oats87** [comment]
Will be investigated for potential fix in 2.7.10

**Comment by jiaqiluo** [comment]
Hi @IlyaNakhaichuk, I could not reproduce the issue, so would like to collect more information about the downstream cluster for further investigation:
- You mentioned your downstream RKE2 cluster is a **hosted** cluster, is it a node-driver cluster that Rancher creates the VMs or an imported cluster that is provisioned outside of Rancher? 
-  When you say "master node", do you mean the node that runs only the control plane, or control plane + etcd ? 

-----

The following are details about my attempt:
- Run Rancher v2.7.6 in single-installation mode (docker run) 
- Log in as admin 
- Create a downstream node-driver RKE2 cluster:
  - Infrastructure: Digital Ocean 
  - version: v1.24.17+rke2r1
  - 3 etcd + control plane nodes, 2 worker nodes 
- While creating the cluster, Edit the cluster as YAML to add the following additional manifest: 
```
spec:
  ... 
  rkeConfig:
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-calico
        namespace: kube-system
      spec:
        valuesContent: |-
          installation:
            calicoNetwork:
              mtu: 1600
              nodeAddressAutodetectionV4:
                firstFound: false
                cidrs:
                  - "IP/24"
```
- Wait for the cluster to be provisioned and become active
- SSH into one of the control plane nodes, and check the content of the file `/var/lib/rancher/rke2/server/manifests/rancher/addons.yaml`. See the following:
```
>  cat /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        mtu: 1600
        nodeAddressAutodetectionV4:
          firstFound: false
          cidrs:
            - "IP/24"
```

- Run the command `sudo reboot` to restart the node 
- Notice that the VM is restarted. During the restarting, the node goes into the Reconciling state, and the cluster goes into the Updating state in Rancher UI,  and it does not take much time for the cluster and the node to come back to active.   
- SSH into the nod again and check the same file. 
- The same content exists in the file.

**Comment by IlyaNakhaichuk** [comment]
Hi @jiaqiluo 
1. Virtual machines created in the proxmox virtualization environment, added as a Custom node (“Use existing nodes and create a cluster using RKE2/K3s”)
2. Control Plane + Etcd
3. 1 node: Control Plane, Etcd; 2 nodes: Worker.

After restarting the master node, the config is still visible through the UI
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    installation:
      calicoNetwork:
        mtu: 1600
        nodeAddressAutodetectionV4:
          firstFound: false
          cids:
            - "IP/24"
```

But it does not apply to the cluster. As a temporary fix, remove the config from the UI. Save the configuration, wait until the cluster is updated, then add it again through the UI and only after that everything is added.
We make all edits to the cluster through the UI.

**Comment by jiaqiluo** [comment]
All right, I got the bug reproduced eventually!
The setup and step in [my previous comment](https://github.com/rancher/rancher/issues/43614#issuecomment-1856926857) are all correct, except the values to be added when editing the cluster as YAML should be the following ( notice that the cids part is dropped): 
```
  rkeConfig:
    additionalManifest: |-
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-calico
        namespace: kube-system
      spec:
        valuesContent: |-
          installation:
            calicoNetwork:
              mtu: 1601
              nodeAddressAutodetectionV4:
                firstFound: false
```

In general, Rancher runs a Helm operation to install or update the `rke2-calico` app after we edit the cluster to add the above values or after we reboot the node. Rancher does it by running a pod, whose name is like "helm-install-rke2-calico-pwqqd", in the local cluster, and we can find the exact command from the pods:
```
helm_v3 upgrade --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 rke2-calico /tmp/rke2-calico.tgz --values /config/values-10_HelmChartConfig.yaml
```
By checking the pod's YAML file, we can find that the file `/config/values-10_HelmChartConfig.yaml` is read from a secret named `chart-values-rke2-calico` in the namespace `kube-system` in the local cluster.

It turns out the data in the secret is changed:
-  After we update the cluster to add the above values, the secret's value matches the additional manifest:
```
installation:
  calicoNetwork:
    mtu: 1601
    nodeAddressAutodetectionV4:
      firstFound: false%
```
- After the node is rebooted, its value becomes:
```
{"global":{"cattle":{"clusterId":"c-m-dg486f9r"}}}%
```

Therefore, the values from the additional manifest are not applied.

**Comment by jiaqiluo** [comment]
Based on further investigation, this is an expected behavior, not a bug. Let me explain below:

By default, Rancher generates and puts a `HelmChartConfig` object (file) for the app `rke2-calico` at the path `/var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml ` on the control plane nodes. 

Now, we add another `HelmChartConfig` object (file) for the same app `rke2-calico` via the `additionalManifest` field, and the file is put at `/var/lib/rancher/rke2/server/manifests/rancher/addons.yaml` on the control plane nodes. 

RKE2 (and K3s) handles the Kubernetes manifests by automatically deploying Kubernetes manifests found in `/var/lib/rancher/rke2/server/manifests` directory in a manner similar to `kubectl apply`.  **But the order is not guaranteed**. ([docs](https://docs.rke2.io/helm?_highlight=managing&_highlight=packaged&_highlight=components#automatically-deploying-manifests-and-helm-charts)) ( the docs does not mention the ordering though) 

So now, when we have 2 files that contain the `HelmChartConfig` objects with the same name `rke2-calico`,  the one from the file `managed-chart-config. yaml` wins and is applied after rebooting the node.

## Recommendation / Workaround

The field `.spec.rkeConfig.chartValues` is provided for customizing the built-in Apps. In this case, we can add the following configuration when editing the cluster as YAML:
```
spec:
  rkeConfig:
    chartValues:
      rke2-calico:
        installation:
          calicoNetwork:
            mtu: 1604
            nodeAddressAutodetectionV4:
              firstFound: false
```

Rancher will combine those values with the built-in ones into a single `HelmChartConfig` object (file), then RKE2 will apply it properly to install/update the `rke2-calico` app. 



Hi @IlyaNakhaichuk , I hope the above will be helpful.  Let me know if you have any questions.
