### ISSUE TITLE
imageScanner: unable to provide CA when using private registry with self-signed certificates

### ISSUE THREAD

**Issue by RenneNiku** [rancher/rancher#43628]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option: Helm Chart:
   - rke2: v1.25.9+rke2r1  

**Information about the Cluster**
- Kubernetes version: rke2: v1.25.9+rke2r1
- Cluster Type: Local

**Describe the bug**
We're running private registy, with self-signed certificates. imageScanner complains about certificate singed by unknown authority. No surprise as such, as it is self-signed certificate:

`time="2023-11-24T12:35:30Z" level=error msg="error syncing 'fleet-local/project-dev': handler image-sync: imageScan project-container is not ready: Get \"https://registry.company.intranet/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority; Get \"http://registry.company.intranet/v2/\": dial tcp xx.xx.xx.xx:80: i/o timeout, requeuing" 
`

We also have private git with self-signed certificates, both git and registry are having same CA. For fleet to be able to see changes in git repositories, we needed to add `caBundle` to `GitRepo` to avoid another `failed to verify certificate` when fleet was accessing our git repositories. But imageScanner does not seem to be using `caBundle`.

Also created  `tls-ca-additional ` with proper CA and set `privateCA` to `true` when installing Rancher Helm chart.. as suggested in https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#additional-trusted-cas. That did not help. imageScanner still complains about certificate signed by unknown authority.

So the question is, if imageScanner does not use `tls-ca-additinonal` secret nor `caBundle` defined in  `GitRepo` resource, then how do I tell imageScanner to trust the certificate our registry is using?

Below are used the GitRepo and fleet.yaml

***Gitrepo***

```
apiVersion: fleet.cattle.io/v1alpha1 
kind: GitRepo 
... 
spec: 
  branch: main 
  clientSecretName: repo-secret 
  insecureSkipTLSVerify: false 
  caBundle: LS0tLS1CR.............. 
  paths: 
    - helm 
  repo: https://git.company.intranet/project.git 
  imageScanInterval: 30s 
  imageScanCommit: 
    authorName: foobar 
    authorEmail: foo@bar.com 
    messageTemplate: "update image" 
  targets: [] 

```

***fleet.yaml***

```
imageScans: 

  - policy: 
      semver: 
        range: "*" 
    image: "registry.company.intranet/project-container" 
    tagName: project-container 
    secretRef: 
      name: project-git-registry 
    interval: 30s 

```
**To Reproduce**

I guess just telling image scanner to scan private  image registry, with self-signed certificates.

**Result**

` tls: failed to verify certificate: x509: certificate signed by unknown authority` with self-signed image registry certificate.

**Expected Result**
Possibility add CA imageScanner would use to verify the certificate and to be able to scan the image registry
