### ISSUE TITLE
[RFE] Allow chart to have full customization over http01.ingress

### ISSUE THREAD

**Issue by lwj5** [rancher/rancher#43677]
**Is your feature request related to a problem? Please describe.**

Unable to specify additional settings to http01.ingress in https://github.com/rancher/rancher/blob/release/v2.8/chart/templates/issuer-letsEncrypt.yaml

**Describe the solution you'd like**
Chart should accept full yaml in `letsEncrypt.ingress`

```
letsEncrypt:
  ingress:
    class: class
    serviceType: ClusterIP
    ...
```

For any ingress config in https://cert-manager.io/docs/configuration/acme/http01/

**Describe alternatives you've considered**
None

**Additional context**
