### ISSUE TITLE
[BUG] kubectl exec broken after switching ingress from nginx to traefik when using AWS ALB

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#43683]
**Rancher Server Setup**
- Rancher version: v2.8-head
- Installation option (Docker install/Helm Chart): both
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.27 (latest, but reproducible on old versions)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): n/a

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

Issue occurs when migrating from a custom deployed ingress nginx controller to k3s' default traefik ingress or installing rancher on k3s from scratch. Users cannot run `kubectl exec` commands to downstream clusters (port-forward is effected as well).

This seems to only be reproducible when using traefik behind an amazon ALB - I tested behind HAProxy and it seemed to work fine. So the fix may just need to be for that specific usecase and not all of them. 

**To Reproduce**

- spin up ec2 node, install k3s
- helm install rancher into k3s cluster with URL defined
- apply traefik k3s config to forward insecure headers (below, collapsed)
- set up an amazon ALB pointing at the ec2 node over port 80 - terminating TLS traffic at the load balancer
- setup rancher, observe it mostly works

<details>
  <summary>Traefik `helmChartConfig` resource</summary>

```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    - "--entryPoints.web.proxyProtocol.insecure"
    - "--entryPoints.web.forwardedHeaders.insecure"
    deployment:
      kind: DaemonSet
    logs:
      access:
        enabled: true 
```

</details> 

**Result**
...but download a kubeconfig and attempt to `kubectl exec` into the cluster or a downstream cluster. it won't work. 

**Expected Result**

All k8s api operations should work as expected.

**Screenshots**

N/A

**Additional context**

This appears to be the traefik ingress dropping the necessary headers for websocket upgrades - notably this config is in the nginx ingress but has no equivalent within traefik:
```
            # Allow websocket connections
            proxy_set_header                        Upgrade           $http_upgrade;
            proxy_set_header                        Connection        $connection_upgrade; 
```

There is a semi-workaround which involves creating a few more traefik specific CRs - notably an `ingressRoute` object that matches any paths that require websockets and then a `middleware` object that injects the headers:

<details>
  <summary>Traefik CRs to make Websockets work</summary>

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: svc-rancher-https
  namespace: cattle-system
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/{path:([a-z]|[A-Z]|[0-9]|/|-)+/(exec|portforward|attach)$}`)
    middlewares:
    - name: svc-rancher-headers
      namespace: cattle-system
    services:
    - name: rancher
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: svc-rancher-headers
  namespace: cattle-system
spec:
  headers:
    customRequestHeaders:
      Connection: "Upgrade"
      Upgrade: "SPDY/3.1" 
```

</details>

This feels extremely hacky - but works. 

SURE-6216
