### ISSUE TITLE
Unable to download HA generation script

### ISSUE THREAD

**Issue by marksullivancrowd** [rancher/rancher#4372]
Rancher Version:
v1.0.1-rc2 CATTLE_RANCHER_SERVER_IMAGE=v1.0.1-rc2
Docker Version:
Server Version: 1.10.1
OS: 
boot2docker virtualbox, MacOSX mavericks 
Steps to Reproduce: 
```
server:
  image: rancher/server:v1.0.1-rc2
  ports:
   - 8080:8080
  environment:
   - CATTLE_DB_CATTLE_MYSQL_HOST=mysql
   - CATTLE_DB_CATTLE_MYSQL_NAME=cattle
   - CATTLE_DB_CATTLE_MYSQL_PORT=3306
   - CATTLE_DB_CATTLE_USERNAME=cattle
   - CATTLE_DB_CATTLE_PASSWORD=cattle
  links:
   - mysql:mysql
mysql:
  image: percona:5.6
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
   - MYSQL_DATABASE=cattle
   - MYSQL_USER=cattle
   - MYSQL_PASSWORD=cattle
  log_driver: json-file
  log_opt:
    max-size: 10m
  volumes:
   - /projects/dbs/rancher/mysql:/var/lib/mysql
```

proceed to admin/ha fill out hostname 3 hosts, and provide key cert and bundle for ssl cert, click generate script, click download script....
Results: 
server_1 | 2016/04/11 23:53:49 http: proxy error: net/http: request canceled
Expected:
file download to browser
