### ISSUE TITLE
[Charts] - Upgrade Windows agent image version within rancher-logging

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#43740]
The current image used for windows agents within the rancher-logging chart is [outdated and not inline with the linux image versions 
](https://github.com/rancher/charts/blob/7d81e80ebc0dc938ad180b2ff18e9f5983ac605a/charts/rancher-logging/103.0.0%2Bup3.17.10/values.yaml#L143-L159)

```yaml
images:
  config_reloader:
    repository: rancher/mirrored-jimmidyson-configmap-reload
    tag: v0.4.0
  fluentbit:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.9.5
  nodeagent_fluentbit:
    os: "windows"
    repository: rancher/fluent-bit
    tag: 1.8.9
  fluentbit_debug:
    repository: rancher/mirrored-fluent-fluent-bit
    tag: 1.9.5-debug
  fluentd:
    repository: rancher/mirrored-banzaicloud-fluentd
    tag: v1.14.6-alpine-5
```

In order to keep up to date with the latest changes within `fluent-bit` for windows we should look into bumping this version to the 1.9 line, or potentially the 2.0 line. I've tested `fluent-bit` `v1.9.8` on a few Windows nodes recently and saw that the current chart does not properly deploy on to the nodes, so changes to the logging chart will be needed in order to properly upgrade. 

For reference, the image used for windows agents comes from https://github.com/rancher/fluent-bit-package
