### ISSUE TITLE
[BUG] How to set limits memory for kube-api service 

### ISSUE THREAD

**Issue by KKulishov** [rancher/rancher#43809]
- Rancher version: 2.6.9
- Installation option (Docker install):
- Kubernetes version: 1.23.15

I add to kube-api  (limits && requests)
```
resources:
        limits:
          cpu: 3000m
          memory: 3000Mi
        requests:
          cpu: 1000m
          memory: 1000Mi
```

go to cluster --> select cluster --> Config --> Cluster Options (edit yaml)

```yaml
services:
    kube-api:
      resources:
        limits:
          cpu: 3000m
          memory: 3000Mi
        requests:
          cpu: 1000m
          memory: 1000Mi
      always_pull_images: false
      pod_security_policy: false
      secrets_encryption_config:
        enabled: false
      service_node_port_range: 30000-32767
 ```
but limits and requests are not added; they are saved and then disappear from the configuration

As a result, the docker container (kube-apiserver) does not apply the changes

can you tell me how to apply memory limits for the service kube-api ?
