### ISSUE TITLE
[BUG] rke1 etcd snapshots not saving to s3

### ISSUE THREAD

**Issue by bbatha** [rancher/rancher#43813]
**Rancher Server Setup**
- Rancher version: 2.7.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.20.15
- Cluster Type (Local/Downstream): downstream, custom
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**

Configuring etcd snapshot to s3 after cluster creation does not seem to result in snapshots being stored but the rancher UI says that they are saved to s3.

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

![rancher screen](https://github.com/rancher/rancher/assets/301475/e94db08a-87e0-4a77-a227-65c120f0798f)

**Additional context**

`cluster.yml` etcd section. The access key was added but does not show here after save presumably for security reasons:

```
  services:
    etcd:
      backup_config:
        enabled: true
        interval_hours: 1
        retention: 28
        s3_backup_config:
          access_key: xxx
          bucket_name: xxx
          endpoint: xxx
          folder: xxx
          region: xxx
        safe_timestamp: true
        timeout: 300
      creation: 12h
      extra_args:
        election-timeout: '5000'
        heartbeat-interval: '500'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
 ```

I tried setting `safe_timestamp` after seeing the date parsing error pasted below, it did not seem to impact this.

The `etcd-rolling-snapshots` container appears to not have the s3 options saved:

```
[
    {
        "Id": "b4414b1c5b09b2b97687a07d8d4480cc3be76485630a773dad00bdf637f0f7ba",
        "Created": "2023-12-18T19:04:18.358549609Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "/opt/rke-tools/rke-etcd-backup",
            "etcd-backup",
            "save",
            "--cacert",
            "/etc/kubernetes/ssl/kube-ca.pem",
            "--cert",
            "/etc/kubernetes/ssl/kube-node.pem",
            "--key",
            "/etc/kubernetes/ssl/kube-node-key.pem",
            "--name",
            "etcd-rolling-snapshots",
            "--endpoints=10.1.117.16:2379",
            "--creation=12h",
            "--retention=72h"
```

I also have errors in the `etcd-rolling-snapshots` container pertaining to parsing the time from the backup name:

```
time="2023-12-19T07:04:19Z" level=warning msg="Couldn't parse backup" error="parsing time \"c-w9mf2-rl-8mr8s\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"c-w9mf2-rl-8mr8s\" as \"2006\"" name="c-w9mf2-rl-8mr8s_2023-12-18T19:12:31Z.zip"
time="2023-12-19T07:04:19Z" level=warning msg="Couldn't parse backup" error="parsing time \"c-w9mf2-rs-l8pjk\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"c-w9mf2-rs-l8pjk\" as \"2006\"" name="c-w9mf2-rs-l8pjk_2023-12-19T01:21:05Z.zip"
```

Finally, if I click "Create Snapshot" in the rancher UI it makes a local snapshot not an s3 one.
