### ISSUE TITLE
[BUG] CATTLE_TLS_MIN_VERSION ignored on port 444 (https-internal)

### ISSUE THREAD

**Issue by xBlast59** [rancher/rancher#43871]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option : Helm Chart in RKE v1 cluster

**Information about the Cluster**
- Kubernetes version: v1.26.8
- Cluster Type : downstream
   - If downstream, what type of cluster? Imported

**User Information**
- Cluster owner

**Describe the bug**
The CATTLE_TLS_MIN_VERSION environment variable applies on port 443 correctly but the port 444 which is the target port of the service rancher when using the helm chart keeps responding with TLS1.0.
Here is the service generated via the Helm chart
```
apiVersion: v1                                  
kind: Service                                   
metadata:                                       
  labels:                                       
    app: rancher                                                        
  name: rancher                                 
  namespace: cattle-system                      
spec:                                                  
  ports:                                        
  - name: http                                  
    port: 80                                    
    protocol: TCP                               
    targetPort: 80                              
  - name: https-internal                        
    port: 443                                   
    protocol: TCP                               
    targetPort: 444                             
  selector:                                     
    app: rancher                                
  sessionAffinity: None                         
  type: ClusterIP                               

```
**To Reproduce**
Inside the pod, port 443 is not responding with tls1.0 : 
```
rancher # env| grep -i tls
CATTLE_TLS_MIN_VERSION=1.2
rancher # openssl s_client -connect 127.0.0.1:443  -tls1 --quiet
140481595004736:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1544:SSL alert number 70
```
but responds with port 444:
```
rancher-74cdd5d456-fwsbw:/var/lib/rancher # openssl s_client -connect 127.0.0.1:444  -tls1 --quiet
Can't use SSL_get_servername
depth=1 O = dynamiclistener-org, CN = dynamiclistener-ca
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 O = dynamiclistener-org, CN = dynamiclistener-ca
verify return:1
depth=0 O = dynamic, CN = dynamic
verify return:1
^C
```
Because of the configuration of the Rancher kubernetes service, the TLS1.0 is also available on port 443
```
rancher # openssl s_client -connect rancher.cattle-system:443  -tls1 --quiet
depth=1 O = dynamiclistener-org, CN = dynamiclistener-ca
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 O = dynamiclistener-org, CN = dynamiclistener-ca
verify return:1
depth=0 O = dynamic, CN = dynamic
verify return:1

```

**Result**
TLS 1.0 is available directly on Rancher pod, port 444 and on Rancher service https port (443).
The issue has also been reproduced on EKS cluster v1.24.17-eks-8cb36c9 and rancher v2.6.11.
**Expected Result**
TLS 1.0 should be disabled on the port 444 use as target port in the Rancher service.
