### ISSUE TITLE
Service links aren't being created in Bridge mode

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#4387]
I recently upgrade from rancher server v1.9.x to v1.0.0. The upgrade wiped out my Rancher DB server so I had to start fresh. (Clean DB, no previous state).

Service links don't get created after upgrading to v1.0.0 which prevents any inter-container communication from happening when I use Bridge networking.

Rancher Version: v1.0.0

Docker Version: v1.6.2

OS: Ubuntu Server 3.13.0-83-generic # 127-Ubuntu SMP

Steps to Reproduce: 

* Create a new service stack: (Sample from a production .yml)
```
redis:
  cap_drop:
  - ALL
  labels:
    io.rancher.container.pull_image: always
  image: redis:3.0.7-alpine
  net: bridge
  mem_limit: 268435456
  cap_add:
  - CHOWN
  - SETGID
  - SETUID
WebUI:
  cap_drop:
  - ALL
  tty: true
  image: ubuntu:latest
  links:
  - redis:redis
  stdin_open: true
  net: bridge
```
* Login to the WebUI container with "Execute Shell"
* Execute `cat /etc/hosts` or `ping redis`

Results: 
The container 'redis' isn't resolvable

sudo docker inspect r-TestStack_WebUI_1:
```
[...]
    "HostConfig": {
[...]
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
[...]
```
Redis NetworkSettings:
```
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "[---]:beef:231:359e:ae61",
        "GlobalIPv6PrefixLen": 80,
        "IPAddress": "172.17.0.134",
        "IPPrefixLen": 16,
        "IPv6Gateway": "fe80::1",
        "LinkLocalIPv6Address": "fe80::31:35ff:fe9e:ae61",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:31:35:9e:ae:61",
        "PortMapping": null,
        "Ports": {
            "6379/tcp": null
        }
    },
```
WebUI NetworkSettings:
```
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "[---]:beef:231:351c:63a8",
        "GlobalIPv6PrefixLen": 80,
        "IPAddress": "172.17.0.135",
        "IPPrefixLen": 16,
        "IPv6Gateway": "fe80::1",
        "LinkLocalIPv6Address": "fe80::31:35ff:fe1c:63a8",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:31:35:1c:63:a8",
        "PortMapping": null,
        "Ports": {}
    },
```

Expected:

I expect that the redis container is available as a link to the WebUI container. This is how it worked previously before I upgraded to Rancher v1.0.0. So far, no links appear to be created for any of my services in any of my stacks.

I've tried deleting and recreating the stack several times to see if that fixes anything, but so far nothing.
