### ISSUE TITLE
[QUESTION] Custom TLS-Certificate not being applied

### ISSUE THREAD

**Issue by morzan1001** [rancher/rancher#43928]
**Rancher Server Setup**
- Rancher version: 2.8
- Installation option: Helm, deployed on a k3s cluster (v1.27.7+k3s2)

**Information about the Cluster**
- Kubernetes version: v1.27.7+k3s2
- Cluster Type: local

**User Information**
- What is the role of the user logged in? -> Admin

**Question**
Hi everyone, I would like to deploy Rancher on my K3S cluster. The actual deployment also works, I can reach rancher via the created ingress route (ingress controller -> traefik) and use rancher correctly. 

In the cluster I have deployed cert-manager in a separate namespace next to Rancher. The cert-manager can request TLS certificates from LetsEncrypt via a DNS challenge. 

I would now like to secure the Rancher web interface with such a certificate. For this I read in the documentation that it is sufficient to create a secret with the certificate and to reference this secret during installation as follows: 

```
helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.<hidden> --set ingress.tls.source=tls-rancher-ingress
```

I have checked that the secret is created correctly by the cert-manager and is also stored in the correct namespace:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-<hidden>
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  renewBefore: 240h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "rancher.<hidden>"
  dnsNames:
  - "rancher.<hidden>"
```

Unfortunately, the certificate is not used but a self-signed certificate from rancher is still issued. What am I missing here?

Many thanks for your tips, cheers

**Comment by mhazan01** [comment]
@morzan1001 i have the same issue, what did you do to fix it ?

**Comment by morzan1001** [comment]
> @morzan1001 i have the same issue, what did you do to fix it ?

Hi, i had to set a traefik label that assigns the endpoint. My HTTPS endpoint is called “websecure”.  I have the following values.yaml, it works.

```yaml
hostname: "<hidden>"
ingress:
  ingressClassName: "traefik"
  tls: 
    source: secret
    secretName: tls-rancher-ingress
  extraAnnotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
```
