### ISSUE TITLE
[BUG] Alertmanager configuration not applied when editing helm release

### ISSUE THREAD

**Issue by ArneRanvik** [rancher/rancher#43954]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart):
   - RKE1

**Information about the Cluster**
- Kubernetes version: 1.23.15
- rancher-monitoring chart version: 102.0.2+up40.1.2

**Describe the bug**
Alert manager configuration is not applied when adding config in helm values. I added this config section to rancher-monitoring chart values:
```
alertmanager:
      enabled: true
      config:
        route:
          groupBy: ['namespace'] # Labels to which alerts are grouped together
          groupWait: 30s # A wait time to catch all alerts to be grouped into one alert notification
          groupInterval: 5m # After a notification event, wait this time before sending new notification
          repeatInterval: 168h # Wait at least this amount before repeating the same alert if still active
          receiver: 'webhook' # Receiver type
        receivers:
        - name: 'webhook'
          webhookConfigs:
          - url: 'http://my-url/webhook'
            sendResolved: false # Send alerts that are resolved
            maxAlerts: 0
      alertmanagerSpec:
        replicas: 3
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 500Mi
```

**Result**
The secret `alertmanager-rancher-monitoring-alertmanager` is updated but the `generated` version is not updated and the alert manager does not change its config file at all.

**Expected Result**
The alert managers active configuration should be updated and webhook should be called when alerts happen in any namespace.
