### ISSUE TITLE
[BUG]  When accessing a service with redoc/swagger resources through proxy, the reference  resource cannot be found

### ISSUE THREAD

**Issue by microhuang** [rancher/rancher#43955]
**Rancher Server Setup**
- Rancher version: **2.7.9**
- Installation option (Docker install/Helm Chart): **Docker install**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: **v1.26.4+k3s1**
- Cluster Type (Local/Downstream): **Local**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): **Admin**
  - If custom, define the set of permissions:

**Describe the bug**

- When accessing a service with redoc/swagger resources through proxy, the reference  resource cannot be found

**To Reproduce**

1. Deploy a Deployment in namespace:
```
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: service-test
  namespace: airflow273
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_test_pod
  template:
    metadata:
      labels:
        app: service_test_pod
    spec:
      containers:
      - name: simple-http
        image: apache/airflow:2.7.3
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo '<html><head></head><body><redoc spec-url=\"/api/v1/openapi.yaml\"></redoc><script src=\"/static/dist/redoc.standalone.js\"></script></body></html>' > index.html; python -m http.server 8080"]
        ports:
        - name: http
          containerPort: 8080
```

2. Deploy a Service in namespace:
```
apiVersion: v1
kind: Service
metadata:
  name: service-test
  annotations:
    {}
  labels:
    {}
  namespace: airflow273
spec:
  selector:
    app: service_test_pod
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
```

3、Accessing the service from proxy：
```curl https://127.0.0.1:30443/api/v1/namespaces/airflow273/services/http:service-test:8080/proxy/```

**Result**
`<html><head></head><body><redoc spec-url="/api/v1/openapi.yaml"></redoc><script src="/api/v1/namespaces/airflow273/services/http:service-test:8080/proxy/static/dist/redoc.standalone.js"></script></body></html>`

**Expected Result**

`<html><head></head><body><redoc spec-url="/api/v1/namespaces/airflow273/services/http:service-test:8080/proxy/api/v1/openapi.yaml"></redoc><script src1111="/api/v1/namespaces/airflow273/services/http:service-test:8080/proxy/static/dist/redoc.standalone.js"></script></body></html>`

**Screenshots**

![图片](https://github.com/rancher/rancher/assets/3072926/46a8e282-6172-4d40-908c-e43c27cb8044)
![图片](https://github.com/rancher/rancher/assets/3072926/81ddb132-189b-43ba-a495-8d692a48e48c)

**Additional context**

In Airflow, “meta”、“redoc” are widely used, and their attribute values have not been rewritten:
![图片](https://github.com/rancher/rancher/assets/3072926/76ff45cf-07f9-4143-8b8f-4f3441050afe)
