### ISSUE TITLE
[Backport] aks-operator k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44109]
Backport of https://github.com/rancher/rancher/issues/41796

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by valaparthvi** [comment]
```yaml
spec:
  chart:
    metadata:
      annotations:
        catalog.cattle.io/auto-install: rancher-aks-operator-crd=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: 'true'
        catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0'
        catalog.cattle.io/namespace: cattle-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/provides-gvr: aksclusterconfigs.aks.cattle.io/v1
        catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
        catalog.cattle.io/release-name: rancher-aks-operator
        catalog.cattle.io/scope: management
      apiVersion: v2
      appVersion: 1.1.3
      description: A Helm chart for provisioning AKS clusters
      home: https://github.com/rancher/aks-operator
      name: rancher-aks-operator
      sources:
        - https://github.com/rancher/aks-operator
      version: 102.3.2+up1.1.3
    values:
      additionalTrustedCAs: false
      aksOperator:
        image:
          repository: rancher/aks-operator
          tag: v1.1.3
      global:
        cattle:
          systemDefaultRegistry: ''
      httpProxy: ''
      httpsProxy: ''
      noProxy: ''
      nodeSelector: {}
      priorityClassName: ''
      tolerations: null
  helmVersion: 3
  info:
    description: Install complete
    firstDeployed: '2024-01-29T09:58:18Z'
    lastDeployed: '2024-01-29T09:58:18Z'
    notes: |
      You have deployed the Rancher AKS operator
      Version: 1.1.3
      Description: This operator provisions AKS clusters
      from AKSClusterConfig CRs.
    status: deployed
  name: rancher-aks-operator
  namespace: cattle-system
```

I noticed that lowest k8s version is `1.20.0-0` in annotation `catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0'`. The issue description says it should be `>=1.23.0-0`.

FYI, I ran the following steps:
1. Installed rancher v2.7-head on k3s v1.26.
2. Created AKS cluster 1.27.
3. Upgraded k3s to v1.27.
4. Validated that AKS cluster was still functional.
5. Validated the aks-operator chart annotations to be as mentioned.
