### ISSUE TITLE
[Backport] eks-operator k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44111]
Backport of https://github.com/rancher/rancher/issues/41797

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by valaparthvi** [comment]
Tested with the following steps:
1. Installed rancher v2.7-head on k3s v1.26.9.
2. Installed eks-operator-crd and eks-operator --version 103.0.0+up1.3.0.
3. Provisioned and imported EKS cluster.
4. Updated both the clusters and validated the update.
5. Downgraded to --version 102.1.4+up1.2.2
6. Updated both the clusters and validated the update.
7. Deleted the operator charts.
8. Updated both the clusters.
9. Re-installed both the charts.
10. **The last updated cluster in line was only updated; eks-operator did not take into account the first cluster.**
11. Upgraded k3s to v1.27.9
12. updated the imported and provisioned EKS cluster.
13. upgrade the helm charts to latest
14. updated the imported and provisioned EKS cluster.

Overall, things work as expected, except:
1. https://github.com/rancher/dashboard/issues/9519
2. When the operator charts are deleted and clusters are updated; reinstalling the operator charts only updates the last cluster in line. (This behavior is noticeable in other operator charts too.)
3. `.spec.chart.metadata.annotations.catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0' has `1.20.0-0` as the lowest supported version, but the description says `1.23.0-0`. This behavior is consistent in both v1.3.0 and v1.2.2.

<details><summary>eks-operator YAML</summary>
<p>
```yaml
apiVersion: catalog.cattle.io/v1
kind: App
metadata:
  name: eks-operator
  namespace: cattle-system
spec:
  chart:
    metadata:
      annotations:
        catalog.cattle.io/auto-install: rancher-eks-operator-crd=match
        catalog.cattle.io/certified: rancher
        catalog.cattle.io/hidden: 'true'
        catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0'
        catalog.cattle.io/namespace: cattle-system
        catalog.cattle.io/os: linux
        catalog.cattle.io/permits-os: linux,windows
        catalog.cattle.io/provides-gvr: eksclusterconfigs.eks.cattle.io/v1
        catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
        catalog.cattle.io/release-name: rancher-eks-operator
        catalog.cattle.io/scope: management
      apiVersion: v2
      appVersion: 1.3.0
      description: A Helm chart for provisioning EKS clusters
      home: https://github.com/rancher/eks-operator
      name: rancher-eks-operator
      sources:
        - https://github.com/rancher/eks-operator
      version: 103.0.0+up1.3.0
    values:
      additionalTrustedCAs: false
      eksOperator:
        image:
          repository: rancher/eks-operator
          tag: v1.3.0
      global:
        cattle:
          systemDefaultRegistry: ''
      httpProxy: ''
      httpsProxy: ''
      noProxy: ''
      nodeSelector: {}
      priorityClassName: ''
      tolerations: null
  helmVersion: 3
```
</p>
</details>
