### ISSUE TITLE
[BUG] Adding OpenTelemetry Auto-Instrumentation

### ISSUE THREAD

**Issue by fendrifirasleminnov** [rancher/rancher#44204]
**Rancher Server Setup**
- Rancher version: 2.7.9

**Objective**
- Adding OpenTelemetry Auto instrumentation with Rancher

**Describe the bug**
I tried all kind of the installation of the instrumentation (k8s manifests ,Helm chart , add a sidecar manually..)
Still not being able to get any traces and the instrumentation always looping on this logs :

```
{"level":"info","ts":1706104626.5336874,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:94","msg":"building OpenTelemetry Go instrumentation ...","globalImpl":false}
{"level":"info","ts":1706104628.5348074,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:73","msg":"process not found yet, trying again soon","exe_path":"/usr/bin/rancher"}
{"level":"info","ts":1706104630.537463,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:73","msg":"process not found yet, trying again soon","exe_path":"/usr/bin/rancher"}
{"level":"info","ts":1706104632.5345259,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:73","msg":"process not found yet, trying again soon","exe_path":"/usr/bin/rancher"}
{"level":"info","ts":1706104634.5344791,"logger":"Instrumentation.Analyzer","caller":"process/discover.go:73","msg":"process not found yet, trying again soon","exe_path":"/usr/bin/rancher"}

```

**To Reproduce**
After installing OpenTelemetry Manager and enabling go auto instrumentation feature just adding this lined in rancher deployment :
```
...
      containers:
        - env:
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /usr/bin/rancher
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4318
          image: otel/autoinstrumentation-go
          imagePullPolicy: IfNotPresent
          name: autoinstrumentation-go
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          
```

**Result**
I am asking this here because i think it's related to Rancher binary flags in the creation i tried to remove the -s flag still same errors
