### ISSUE TITLE
[BUG] status of EKSClusterConfig(eksclusterconfigs.eks.cattle.io) is not changing.

### ISSUE THREAD

**Issue by githubeto** [rancher/rancher#44224]
**Rancher Server Setup**
- Rancher version: v2.7.9
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: 1.26
- Cluster Type (Local/Downstream): DownStream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Terraform Rancher provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

----

I made changes to the subnet configuration for the networking of the EKS cluster, but the Status field of the EKSClusterConfig resource remains unchanged. Why is this happening? Do you know where it is being retrieved from?

> kubectl get eksclusterconfigs.eks.cattle.io -n cattle-global-data -o yaml

```
  status:
    failureMessage: ""
    generatedNodeRole: ""
    managedLaunchTemplateID: lt-052329e0e1453433c
    managedLaunchTemplateVersions:
      spot_instances_3: "11"
      spot_instances_4: "12"
    networkFieldsSource: provided
    phase: active
    securityGroups:
    - sg-06c2766f4f71a445e
    subnets:
    - subnet-013d84b7eb368943d
    - subnet-01e5f33c6ed510793
    - subnet-06a74f9f28259d456
    templateVersionsToDelete: null
    virtualNetwork: ""
```
