### ISSUE TITLE
NFS volume mounting failed in Kubernetes environment

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4423]
Rancher Version:
1.0.0
Docker Version:
1.10.3
OS: 
Ubuntu 14.04
Steps to Reproduce: 
- create nfs exported volume  (/nfs) on the registered host
- install nfs-common on the registered host
- create the PV and PVC for nfs

nfs-pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 82.191.4.78
    path: "/nfs"
```
nfs-pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```
- try to mount the nfs volume from within a pod:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-web
spec:
  replicas: 2
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
```
Results: 
the mounting failed and the pod stuck in pending state
```
Mounting arguments: 82.191.4.78:/nfs /var/lib/kubelet/pods/1dae9e6b-02a2-11e6-9a27-0286285ab4f0/volumes/kubernetes.io~nfs/nfs nfs []
Output: mount: wrong fs type, bad option, bad superblock on 82.191.4.78:/nfs,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

; skipping pod
```
