### ISSUE TITLE
rancher-compose drops host IP in ports when creating services

### ISSUE THREAD

**Issue by bluebu** [rancher/rancher#4425]
Rancher Version: v1.0.0 & v 1.0.1

Docker Version: 1.9.1

OS:  Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)

Steps to Reproduce: 

1. Set Ports with IP in the Catalog's `docker-compose.yml`, like below:
>  ports:
>     -   "192.168.1.81:8118:8118"

2. Create a Stack `StackA` from this Catalog.

Results: 
  The StackA's generated `docker-compose.yml` has wrong Ports config, like below:
> ServiceA:
>   ports:
>     -   8118:8118/tcp

Expected:
  The StackA's generated `docker-compose.yml` should have the same IP & ports with the Catalog's docker-compose.yml:
> ServiceA:
>  ports:
>     -   "192.168.1.81:8118:8118"

It seems to be caused when parse the Catalog's docker-compose.yml to the Stack's config.

**Comment by alena1108** [comment]
@prachidamle could you take a look? Looks like a bug in service's docker-compose file generation; we should switch it to use a new supported port format.

**Comment by egobude** [comment]
I have the same issue

**Comment by deniseschannon** [comment]
This is actually a rancher-compose issue.

I tried adding the following in rancher-compose and it didn't hold on to the host IP.

```
hostportmap1:
  ports:
  - 81:80/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: test=true
  tty: true
  image: nginx
  stdin_open: true 
```
