### ISSUE TITLE
[BUG] Projects created via `kubectl` in downstream clusters are visible in local cluster as namespaces.

### ISSUE THREAD

**Issue by torchiaf** [rancher/rancher#44280]
**Rancher Server Setup**
- Rancher version: 2.8.1
- Installation option: Helm, v1.26.10+k3s2, rke2

**Information about the Cluster**

local +1 Digital Ocean provider downstream cluster

**User Information**

Admin user

**Describe the bug**

1- When I create a project `foo` on a downstream cluster with kubectl/V1 endpoint -> The project is created and displaying as a project in Downstream cluster but it is also displaying the namespace `foo` in local cluster.

2- In case of `foo` project is created in the downstream, it's not possible to create a new namespace in local cluster, with the same name, the backend throws an error since the namespace `foo` already exists.

3- In case of a `foo` namespace exists in local cluster and the user creates a new project `foo` in the downstream, when the `foo` project is deleted, then the namespace `foo` in local cluster, which was existing before the test, is also deleted.

Related UI issue: https://github.com/rancher/dashboard/issues/9880

**To Reproduce**

2. Create downstream cluster
3. Create a project from kubectl/V1 endpoint
4. Copy the local cluster KUBECONFIG and export it on to terminal.
5.  Export the kubeconfig and run on local cluster
6.  `kubectl apply -f ~/create_project.yaml`

```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: foo
  namespace: c-4k7jp // downstream cluster-id
spec:
  clusterName: c-4k7jp // downstream cluster-id

```

**Result**

See description.

**Expected Result**

**Screenshots**

**Additional context**
