### ISSUE TITLE
private registry ECR credentials not working in v1.27.8-rancher2-2

### ISSUE THREAD

**Issue by mofr93** [rancher/rancher#44365]
**Rancher Server Setup**
- Rancher version: v2.8.1
- Installation option: Docker Install
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.27.8-rancher2-2
- Cluster Type: Downstream
   - Custom
   - OS: Fedora CoreOS 39.20231119.3.0
   - Kernel: 6.5.11-300.fc39.x86_64
   - Docker version: 24.0.5

**User Information**
- What is the role of the user logged in?
  - Cluster Owner

**Describe the bug**
ECR credentials stops working after upgrading Kubernetes to `v1.27.8-rancher2-2`.  I can confirm it works in `v1.26.11-rancher2-2`

Configured in `rke_config` block in Terraform:

    private_registries {
      url = data.vault_kv_secret_v2.ecr.data.registry_address
      ecr_credential_plugin {
        aws_access_key_id     = data.vault_kv_secret_v2.ecr.data.access_key_id
        aws_secret_access_key = data.vault_kv_secret_v2.ecr.data.secret_access_key
      }
    }

Image pull error in kubelet:
```
E0207 08:39:43.319282    2947 remote_image.go:167] "PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: Head \"https://[redacted].dkr.ecr.eu-west-1.amazonaws.com/v2/[redacted]/dino-pod-killer/dino-pod-killer/manifests/latest\": no basic auth credentials" image="[redacted].dkr.ecr.eu-west-1.amazonaws.com/[redacted]/dino-pod-killer/dino-pod-killer:latest"
E0207 08:39:43.319351    2947 kuberuntime_image.go:53] "Failed to pull image" err="rpc error: code = Unknown desc = Error response from daemon: Head \"https://[redacted].dkr.ecr.eu-west-1.amazonaws.com/v2/[redacted]/dino-pod-killer/dino-pod-killer/manifests/latest\": no basic auth credentials" image="[redacted].dkr.ecr.eu-west-1.amazonaws.com/[redacted]/dino-pod-killer/dino-pod-killer:latest"
```

**To Reproduce**
Upgrade to or create new cluster with Kubernetes version `v1.27.8-rancher2-2`.

**Result**

**Expected Result**
Private registry images should be pulled

**Screenshots**

**Additional context**

**Comment by tunaman** [comment]
We encountered this bug after upgrading Rancher to version `2.8.2` and one of our downstream clusters from version `1.26.13` to `1.27.10` on AWS. This issue specifically affects private ECR repositories, while public ECR repositories remain unaffected. To mitigate this, we've implemented a workaround by adding a Docker secret containing AWS ECR credentials to the relevant namespaces. These credentials are refreshed every 6 hours. Additionally, we've included this Docker secret in the `imagepullsecrets` of applicable service accounts.

**Comment by mofr93** [comment]
@yha-sparklane
 
Thanks.

I got it working by using `ecr-credential-provider` and removing `ecr_credential_plugin` from current config.

I used this guide:
https://medium.com/@sajjadzaheri/how-to-authenticate-aws-ecr-on-any-kubernetes-cluster-the-right-way-26b6ee190125

Terraform:
```hcl
services {
  kubelet {
    extra_env = [
      # Inject AWS credentials for ECR authentication
      "AWS_ACCESS_KEY_ID=${data.vault_kv_secret_v2.ecr.data.access_key_id}",
      "AWS_SECRET_ACCESS_KEY=${data.vault_kv_secret_v2.ecr.data.secret_access_key}"
    ]

    extra_binds = [
      # Custom binaries available to kubelet
      "/opt/danskespil/bin:/opt/danskespil/bin:ro",
      # Custom configs available to kubelet
      "/opt/danskespil/config:/opt/danskespil/config:ro"
    ]

    extra_args = {
      # https://github.com/kubernetes/cloud-provider-aws/blob/master/docs/credential_provider.md
      image-credential-provider-bin-dir = "/opt/danskespil/bin"
      image-credential-provider-config  = "/opt/danskespil/config/credential-provider-config.yaml"
    }

    cluster_dns_server = var.cluster_dns_server
  }
```

Butane config (CoreOS):
```yaml
variant: fcos
version: 1.4.0

storage:
  files:
    - path: /opt/danskespil/bin/ecr-credential-provider
      overwrite: true
      contents:
        source: https://storage.googleapis.com/k8s-artifacts-prod/binaries/cloud-provider-aws/v1.29.0/linux/amd64/ecr-credential-provider-linux-amd64
      mode: 0755

    - path: /opt/danskespil/config/credential-provider-config.yaml
      mode: 0600
      overwrite: true
      contents:
        inline: |
          apiVersion: kubelet.config.k8s.io/v1
          kind: CredentialProviderConfig
          providers:
            - name: ecr-credential-provider
              matchImages:
                - "*.dkr.ecr.*.amazonaws.com"
                - "public.ecr.aws"
              defaultCacheDuration: "12h"
              apiVersion: credentialprovider.kubelet.k8s.io/v1

```
