### ISSUE TITLE
[RFE] [CAPR] Support K3s/RKE2 EtcdSnapshot Custom Resources

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#44452]
**Is your feature request related to a problem? Please describe.**
K3s/RKE2 have implemented a new EtcdSnapshot CR and are intending to utilize this to get around the etcd snapshot configmap size limit. See issue here for reference: https://github.com/rancher/rke2/issues/4495

**Describe the solution you'd like**
Rancher should start being able to support the EtcdSnapshot custom resources for snapshot backpopulate. This should be a configurable option, with defaults based on version of K3s/RKE2.

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by brandond** [comment]
x-ref: https://github.com/k3s-io/k3s/blob/master/docs/adrs/etcd-snapshot-cr.md

**Comment by Josh-Diamond** [comment]
Ticket #44452 - Test Results -
---

Verified on Rancher `v2.11-1ec5c626b1f615573b7f7269d4eb67ddb8c82749-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Fresh install of Rancher `v2.11-head` => provision downstream RKE2 cluster + take snapshot => deploy a workload => restore to snap | ✅ |
| 2. | Fresh install of Rancher `v2.11-head` => provision downstream K3S cluster + take snapshot => deploy a workload => restore to snap | ✅ |
| 3. | Fresh install of Rancher `v2.11-head` => provision downstream RKE2 cluster + take snapshot => upgrade k8s version => restore to snap | ✅ |
| 4. | Fresh install of Rancher `v2.11-head` => provision downstream K3S cluster + take snapshot => upgrade k8s version => restore to snap | ✅ |
| 5. | Fresh install of Rancher `v2.10.2` => provision downstream RKE2 cluster + take snapshot => upgrade Rancher to `v2.11-head` => upgrade downstream k8s version => restore to snap | ✅ |
| 6. | Fresh install of Rancher `v2.10.2` => provision downstream K3S cluster + take snapshot => upgrade Rancher to `v2.11-head` => upgrade downstream k8s version => restore to snap | ✅ |
| 7. | Fresh install of Rancher `v2.11-head` => provision downstream RKE2 cluster w/ 5 nodes + s3 backups w/ retention set to 72 => ensure snapshots do no fail to update | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.32.1+rke2r1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Deploy a workload
6. Verified - workload successfully deployed
7. Restore to snap from step 3
8. Verified - cluster successfully restores to snapshot; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision a downstream K3S cluster w/ k8s `v1.32.1+k3s1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Deploy a workload
6. Verified - workload successfully deployed
7. Restore to snap from step 3
8. Verified - cluster successfully restores to snapshot; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.31.5+rke2r1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Upgrade k8s version to `v1.32.1+rke2r1`
6. Verified - cluster successfully upgrades
7. Restore to snap from step 3
8. Verified - cluster successfully restores to snapshot; as expected

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision a downstream K3S cluster w/ k8s `v1.31.5+k3s1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Upgrade k8s version to `v1.32.1+k3s1`
6. Verified - cluster successfully upgrades
7. Restore to snap from step 3
8. Verified - cluster successfully restores to snapshot; as expected

---

Scenario 5 - ✅ 
1. Fresh install of Rancher `v2.10.2`
2. Provision a downstream RKE2 cluster w/ k8s `v1.31.5+rke2r1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Upgrade Rancher to `v2.11-head`
6. Verified - Rancher successfully upgrades
7. Upgrade downstream RKE2 k8s version
8. Verified - cluster successfully upgrades to k8s `v1.32.1+rke2r1`
9. Restore to snapshot taken in step 3
10. Verified - cluster successfully restores to snapshot, k8s version is once again `v1.31.5+rke2r1`; as expected

---

Scenario 6 - ✅ 
1. Fresh install of Rancher `v2.10.2`
2. Provision a downstream K3S cluster w/ k8s `v1.31.5+k3s1`
3. Once `active`, take a snapshot
4. Verified - snapshot successfully captured
5. Upgrade Rancher to `v2.11-head`
6. Verified - Rancher successfully upgrades
7. Upgrade downstream K3S k8s version
8. Verified - cluster successfully upgrades to k8s `v1.32.1+k3s1`
9. Restore to snapshot taken in step 3
10. Verified - cluster successfully restores to snapshot, k8s version is once again `v1.31.5+k3s1`; as expected

---

Scenario 7 - ✅ 
1. Fresh install of Rancher `v2.11-head`
2. Provision a downstream RKE2 cluster w/ 5 nodes, s3 backups + retention limit set to 72 - (i used the following cron schedule, to collect snaps every minute: `* * * * *`)
3. Verified - snaps are collected every minute, when retention limit is hit, new snaps are still collected and the oldest snaps "drop-off"; no errors and clean logs; as expected

**Comment by jakefhyde** [comment]
ETCD Snapshots are now populated within Rancher by listing the `etcdsnapshotfile.k3s.cattle.io` resources in the downstream cluster, instead of periodically scraping the CLI and `rke2/k3s-etcd-snapshots` configmap for local and s3 snapshots respectively. Local and s3 snapshots will now populate much faster within the Rancher UI as a result. 

Please note that as before this change, snapshots will not sync to the Rancher server without an active connection to the downstream cluster's apiserver, so in the event of a total failure of the etcd plane, snapshots can be restored by first copying the snapshot to the desired new etcd node, and creating an etcdsnapshot.rke.cattle.io object in the local cluster. An example manifest for a local snapshot can be found below:

```
apiVersion: rke.cattle.io/v1
kind: ETCDSnapshot
metadata:
  annotations:
    etcdsnapshot.rke.io/snapshot-file-name: <etcdsnapshotfile.k3s.cattle.io spec.nodeName>
    etcdsnapshot.rke.io/storage: local
  labels:
    rke.cattle.io/cluster-name: <CLUSTER_NAME>
    rke.cattle.io/machine-id: <value of rke.cattle.io/machine-id label on the corresponding machine.cluster.x-k8s.io object>
    rke.cattle.io/node-name: <NODE_NAME>
  name: <NAME>
  namespace: <CLUSTER_NAMESPACE>
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Machine
      name: <MACHINE_NAME>
snapshotFile:
  createdAt: <etcdsnapshotfile.k3s.cattle.io status.creationTime>
  location: <etcdsnapshotfile.k3s.cattle.io spec.location>
  name: <etcdsnapshotfile.k3s.cattle.io spec.snapshotName>
  nodeName: <NODE_NAME>
  size: <etcdsnapshotfile.k3s.cattle.io status.size>
  status: successful
spec:
  clusterName: <CLUSTER_NAME>
```
