### ISSUE TITLE
Assign one port multiple times does not work 

### ISSUE THREAD

**Issue by egobude** [rancher/rancher#4449]
Hey, 

i have trouble to assign one port multiple times on different ips. The server has multiple virtual network adapters. I get the following error message:

> Activating (Waiting for [instance:test2projectserver_backend_4]. Instance status: Scheduling failed: host needs ports 5683/tcp, 5683/udp, 5684/tcp, 5684/udp, 9977/tcp, 51186/tcp available)

My docker-compose.yml looks like the following:

```
backend:
  ports:
  - IP_ADDRESS:PORT:1234/tcp
```

I'm on CentOS Linux release 7.2.1511 (Core)

What am I doing wrong? 

Thanks for your help :)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`environment.index`|

**Comment by egobude** [comment]
Some feedback on this. It is working right now but only with bridged network. With the managed network it didn't work.

```
nginx2:
  ports:
  - IP_ADDRESS_A:80:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: nginx
  stdin_open: true
  net: bridge
nginx1:
  ports:
   - IP_ADDRESS_B:80:80/tcp
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: nginx
  stdin_open: true
  net: bridge
```
