### ISSUE TITLE
Federator cannot create ConfigMaps due to registration namespace resourcequotas 

### ISSUE THREAD

**Issue by puffitos** [rancher/rancher#44501]
**Cluster Setup**
- Kubernetes version: 
- Type of Cluster (RKE1, RKE2, k3s, EKS, GKE, AKS, OKE, etc): RKE1, imported
- Installation option (Helm Chart / Custom Installation):
   - If Helm Chart, did you supply any non-default values? If so, what values did you supply: 
   - If Custom Installation, how did you install it (kustomize, k8s manifest, etc.):
   
**Describe the bug**

The automatically created namespace `cattle-project-p-xxxxx` uses a projects default namespace resource quotas. If a project already has fully-booked project resource quotas, this creates a namespace with a ResourceQuota that allows no objects to be created in it:

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2023-03-09T10:36:52Z"
  generateName: default-
  labels:
    cattle.io/creator: norman
    resourcequota.management.cattle.io/default-resource-quota: "true"
  name: default-2dfbc
  namespace: cattle-project-p-5tmh6
spec:
  hard:
    configmaps: "0"
    limits.cpu: "0"
    limits.memory: "0"
    persistentvolumeclaims: "0"
    pods: "0"
    replicationcontrollers: "0"
    requests.cpu: "0"
    requests.memory: "0"
    requests.storage: "0"
    secrets: "0"
    services: "0"
    services.loadbalancers: "0"
    services.nodeports: "0"
status:
  used:
    configmaps: "2"
    limits.cpu: "0"
    limits.memory: "0"
    persistentvolumeclaims: "0"
    pods: "0"
    replicationcontrollers: "0"
    requests.cpu: "0"
    requests.memory: "0"
    requests.storage: "0"
    secrets: "1"
    services: "0"
    services.loadbalancers: "0"
    services.nodeports: "0"
```

This results in the federator throwing the following error:
```
time="2023-03-09T10:43:16Z" level=error msg="error syncing 'p-5tmh6': failed to create cattle-project-p-j7dqd/monitoring.cattle.io.v1alpha1 /v1, Kind=ConfigMap for cattle-project-p-5tmh6-monitoring-data cattle-project-p-5tmh6: configmaps \"monitoring.cattle.io.v1alpha1\" is forbidden: exceeded quota: default-2dfbc, requested: configmaps=1, used: configmaps=1, limited: configmaps=0, requeuing"
```

**To Reproduce**
 

1. Create a project with resource quotas
2. Create a namespace that fully uses the quotas
3. Enable project monitoring for the project

**Result**

The aforementioned problem appears in the logs. The configmap containing the helm chart values isn't saved in the user's registration namespace.

**Expected Result**

The config map should be present (along with everything else the federator creates) and no error should appear in the federator's logs.

**Screenshots**

None needed.

**Additional context**

Please consider **not** using the default namespace resource quotas when creating the registration namespace. They may be high, which creates a namespace that unnecessarily binds precious resources from the project, like CPU and RAM. Consider using dedicated `ResourceQuotas` for the creation of this namespace.
