### ISSUE TITLE
422 Body: [code=NotUnique, fieldName=name] when multiple containers use the same data volume

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#4460]
Rancher Version: v1.0.0

Docker Version: 1.10.3

OS: Ubuntu 15.04

Steps to Reproduce:

`docker-compose --verbose up` with this `docker-compose.yml`:

```
app:
  image: mageinferno/magento2-nginx:1.9.9-2
  ports:
    - "80:80"
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - VIRTUAL_HOST=shop.liquid-trading.de
  labels:
    io.rancher.sidekicks: appdata, phpfpm, setup

appdata:
  image: tianon/true
  volumes:
    - "/var/magento2/src:/src"

phpfpm:
  image: mageinferno/magento2-php:7.0.2-fpm-1
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=default
    - PHP_MEMORY_LIMIT=2048M

db:
  image: mariadb:10.1.10
  ports:
    - "3306:3306"
  volumes:
    - "/var/magento2/mysql:/var/lib/mysql"

setup:
  image: mageinferno/magento2-php:7.0.2-fpm-1
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
```

Results: 

```
INFO[0000] Creating service app
DEBU[0000] Creating service app with hash: digest.ServiceHash{Service:"04eebe96f990ab64972bce5193990b3e6b8da6a2", LaunchConfig:"792bc6859a5da13c8bc9ce0c1e502a38418e3cb8", SecondaryLaunchConfigs:map[string]string{"appdata":"a4b64bdd56ddf28671e2787b7fc583bb55b804e9", "phpfpm":"5b7975000c982dd602f04b98f9e55f63d3b9817c", "setup":"367a2ef15c2a8d522e9f05f9ed23229eb02b05bd"}}
ERRO[0000] Failed Creating app : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name] from [http://rancher.storyx.company:8080/v1/services]
```

Expected:

Spinning up all containers.

**Comment by willseward** [comment]
Verified in Rancher v1.0.1 as well

**Comment by deniseschannon** [comment]
I was unable to reproduce.

I used a simplified docker-compose.yml and it had no issues launching even tho it's using teh same volume name. 

Is this a fresh stack? Do you already have a service called `app` in the stack?

```
app:
  image: nginx
  ports:
    - "80:80"
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  labels:
    io.rancher.sidekicks: appdata, phpfpm, setup

appdata:
  image: nginx
  volumes:
    - "/var/magento2/src:/src"

phpfpm:
  image: nginx
  links:
    - db
  volumes_from:
    - appdata

db:
  image: nginx
  ports:
    - "3306:3306"
  volumes:
    - "/var/magento2/mysql:/var/lib/mysql"

setup:
  image: nginx
  links:
    - db
  volumes_from:
    - appdata
```
