### ISSUE TITLE
[BUG] Can't overwrite/supply custom system images in an RKE Cluster

### ISSUE THREAD

**Issue by mueller-tobias** [rancher/rancher#44611]
**Rancher Server Setup**
- Rancher version: 2.7.10
- Installation option (Docker install/Helm Chart): Helm Chart on RKE1
- Proxy/Cert Details: Behind Proxy, Private PKI

**Information about the Cluster**
- Kubernetes version: 1.24.17
- Cluster Type (Local/Downstream): Downstream
 * Infrastructure Provider = vSphere

**User Information**
- What is the role of the user logged in? Administrator Role

**Describe the bug**
We've a cluster with 1.24.17 and currently can't upgrade to 1.25+ due to Applications in the Cluster that are not ready for 1.25+.
In the Cluster we've Calico v3.22.5 installed via the Rancher Deployment/Upgrade Process. Now we would like to use a higher Version of Calico. We tried to configure the `systemImages` below the `rancherKubernetesEngineConfig`. But every time we save the changes Rancher resets the systemImages Attribute to an empty object 

**To Reproduce**
Create an RKE1 Cluster and try to change the `systemImages` Attribute below the `rancherKubernetesEngineConfig`.

```
rancherKubernetesEngineConfig
  systemImages:
    calicoCni: rancher/calico-cni:v3.26.3-rancher1
    calicoControllers: rancher/mirrored-calico-kube-controllers:v3.26.3
    calicoCtl: rancher/mirrored-calico-ctl:v3.26.3
    calicoFlexVol: rancher/mirrored-calico-pod2daemon-flexvol:v3.26.3
    calicoNode: rancher/mirrored-calico-node:v3.26.3
```
**Result**
The `systemImages` is reset to an empty object

**Expected Result**
The Cluster is deployed with the correct specified `systemImages`.
