### ISSUE TITLE
[BUG] Fleet controller can't provision local cluster immediately

### ISSUE THREAD

**Issue by weyfonk** [rancher/rancher#44630]
#41848 was originally created against Rancher 2.8.

More context there.

TL;DR: When installed via Docker or Harvester, Rancher uses an API server URL which is not known in advance. In such cases, the API server URL is not configured, meaning that Fleet does not provision the local cluster immediately.

This is a forward-port for 2.9.

**Comment by weyfonk** [comment]
## Additional QA
 
### Problem
(copied over from [this issue description](https://github.com/rancher/rancher/issues/41848#issue-1757976273))

Local cluster provision doesn't happen immediately after we set the secret; sometimes, it takes a very long time (up to 10 minutes). Restarting fleet-controller pod makes the cluster provision happen immediately.

### Solution
When the API server URL is not set, Rancher's Fleet chart controller uses the local cluster's internal API server URL when installing a local Fleet cluster, populating that URL in the corresponding Kubeconfig secret.
 
### Testing

(copied over from [this issue description](https://github.com/rancher/rancher/issues/41848#issue-1757976273))

Provision a local cluster with rancherd; its basic flow is:
- Deploy an RKE2 server node.
- Deploy Rancher, rancher will deploys rancher-webhook and fleet controller.
- Update secret `local-kubeconfig`. 
    - `apiServerURL`: value of Rancher setting "internal-server-url".
    - `apiServerCA`: value of Rancher setting "internal-cacerts".
- Apply cluster manifests:
  ```
  ---
  apiVersion: v1
  kind: Node
  metadata:
    labels:
      node-role.kubernetes.io/etcd: "true"
    name: node1
  
  ---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: fleet-local
  
  ---
  apiVersion: provisioning.cattle.io/v1
  kind: Cluster
  metadata:
    name: local
    namespace: fleet-local
  spec:
    kubernetesVersion: v1.25.9+rke2r1
    rkeConfig:
      controlPlaneConfig:
        disable:
        - rke2-snapshot-controller
        - rke2-snapshot-controller-crd
        - rke2-snapshot-validation-webhook
  
  ---
  apiVersion: v1
  data:
    agentToken: YWEgYmIgY2M=
    serverToken: YWEgYmIgY2M=
  kind: Secret
  metadata:
    name: local-rke-state
    namespace: fleet-local
  type: rke.cattle.io/cluster-state
  
  ---
  apiVersion: management.cattle.io/v3
  kind: ClusterRegistrationToken
  metadata:
    name: default-token
    namespace: local
  spec:
    clusterName: local
  status:
    token: aa bb cc
  
  ---
  apiVersion: catalog.cattle.io/v1
  kind: ClusterRepo
  metadata:
    name: rancher-stable
  spec:
    url: https://releases.rancher.com/server-charts/stable
  ```
The local cluster should immediately be provisioned with a `fleet-agent` pod.
