### ISSUE TITLE
[BUG] Namespace created (via kubectl) in a project (with container default resource limit) is missing containerDefaultResourceLimit annotation

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#44635]
**Rancher Server Setup**
- Rancher version: v2.9-head

**Describe the bug**
Namespace created in a project with a container default limit set is missing the `field.cattle.io/containerDefaultResourceLimit` annotation. This issue is observed only when the namespace is created via kubectl.

**To Reproduce**
	1. Create a Project with container default resource limits set.
	2. Using kubectl, create a namespace within the project.
	3. Verify that the `field.cattle.io/containerDefaultResourceLimit` annotation is present in the namespace spec.

**Issue**
When a namespace is created using kubectl, the `field.cattle.io/containerDefaultResourceLimit` annotation is missing from the namespace object. However, the corresponding **LimitRange** is correctly created.
**Note**: When a namespace is created via the UI, the `field.cattle.io/containerDefaultResourceLimit` annotation is added to the namespace object as expected.

**Expected Result**
When a namespace is created within a project with a container default limit set, it should include the `field.cattle.io/containerDefaultResourceLimit` annotation regardless of the creation method (UI or kubectl).

**Additional context**
Updating the project's container limit configuration does not propagate to LimitRanges for existing namespaces created via the UI, which is documented as normal behavior.
However, updating the project's container limit configuration does propagate to LimitRanges for existing namespaces created using kubectl. This behavior deviates from what's expected and maybe as a result of the missing annotation.

cc @maxsokolovsky

**Comment by maxsokolovsky** [comment]
If a project has resource quota limit defined, then every project namespace gets a special annotation that marshals the configuration.
Similarly, if a project also has a container default limit defined, then every project namespace gets a special annotation that marshals the configuration.

However, there is a difference in behavior depending on how you create the namespace in the project.
If you use the UI, then the annotation for the container default limit gets added to the namespace object.
If you use kubectl, it doesn't appear. The corresponding LimitRange does get created, though, which is good.
But there is a difference in behavior when you update the project's container limit configuration.
The update to the project doesn't get propagated to LimitRanges for namespaces made with the UI (which the docs describe as normal).

But the update to the project does get propagated to LimitRanges for namespaces made with kubectl. Is this bad? Should the behavior be the same regardless of how you create the namespace in the project? Should the controller then immediately create the annotation (when kubectl is used), so that the behavior is the same?

Note that this difference isn't found with resource quota limits, as no matter how you create the namespace, its corresponding annotation appears on the object.

**Comment by ericpromislow** [comment]
What's the `kubectl` command to create a namespace and associate it with a rancher project?

**Comment by maxsokolovsky** [comment]
There is no simple `kubectl` command, unfortunately, because you'd need to specify a special annotation.

The manifest for a manifest associated with a project would look like the following:

```yaml
apiVersion: v1
kind: Namespace
metadata:
    name: my-ns
    annotations:
        field.cattle.io/projectId: c-m-pkmqcb64:p-st7gk
```

Here, `c-m-pkmqcb64:p-st7gk` is the clusterID:projectID pair.

**Comment by andreas-kupries** [comment]
Confirmed for commit 367154dc973e716ced307f73fab9a9be2679b804 (current head).

kubectl apply -f <<
```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-used-1
  namespace: local
spec:
  clusterName: local
  displayName: test-project-used-1
  resourceQuota:
    limit:
      pods: "2"
  namespaceDefaultResourceQuota:
    limit:
      pods: "2"
  containerDefaultResourceLimit:
    requestsCpu:  "10m"
    limitsCpu:   "100m"
```

Namespace from kubectl apply -f <<
```
apiVersion: v1
kind: Namespace
metadata:
  name: ns-moving
  annotations:
    field.cattle.io/projectId: local:p-used-1
```

Annotation missing.
Namespace `dashboard-1` created via dashboard has the annotation.
