### ISSUE TITLE
[BUG] Cannot drop metric container

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44731]
Reported in 2.6.8

**Repro steps:**

    deployed rancher-monitoring
    updated the values.yaml to add the drop for the metric like below and continue with the deployment
    run the count and if it is dropped then it should not increase

cAdvisorMetricRelabelings: - action: drop regex: container_blkio_device_usage_total sourceLabels: - _name_

SURE-7124

**Comment by dharmit** [comment]
I tried this on rancher v2.8.4. After creating an RKE2 downstream cluster, I installed monitoring on it and added the following to `values.yaml` before creation:
```yaml
cAdvisorMetricRelabelings:
    - action: drop
      regex: container_blkio_device_usage_total
      sourceLabels:
      - __name__
```

* After successful installation, I clicked on "Prometheus Rules" in the following page and searched for the metric.
  ![image](https://github.com/rancher/rancher/assets/713521/919cafe7-182b-4e61-89d3-cb81da97be13)

* The `container_blkio_device_usage_total` doesn't show up, as can be seen below:
  ![image](https://github.com/rancher/rancher/assets/713521/c9e2915e-ff41-4e48-87f8-f7128ee8e252)

* After removing the aforementioned "drop" rule, I do see the `container_blkio_device_usage_total` in suggestions:
  ![image](https://github.com/rancher/rancher/assets/713521/86205318-db63-4576-80ca-052b92610407)

@joshmeranda @alexandreLamarre can one of you validate if I'm looking at this correctly?

**Comment by dharmit** [comment]
`drop`'ing the metric again still shows it when trying to query. But the value isn't increasing (as mentioned in the original issue).

**Comment by alexandreLamarre** [comment]
Looks like the cAdvisor relabellings only apply to the kubelet service monitor, which is disabled in k3s. So this issue is likely specific to other distributions, like RKE2.

**Comment by alexandreLamarre** [comment]
Works as expected in `103.1.1+up45.31.1`

with:
```yaml

kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings:
      // ....
      - action: drop
      regex: container_blkio_device_usage_total
      sourceLabels:
      - __name__
```



![image](https://github.com/rancher/rancher/assets/56211853/51172d7e-bbc9-421c-b98c-6a2987bacba2)

![image](https://github.com/rancher/rancher/assets/56211853/65758713-7b5e-4528-a90e-daaec4c7773c)
