### ISSUE TITLE
Local k3s cluster version not in sync with rancher

### ISSUE THREAD

**Issue by migs35323** [rancher/rancher#44849]
**Setup**
- Rancher version: v2.8.2

**Describe the bug**
I have a k3s deployment wich i installed rancher's helm chart
i did upgrade k3s following it's automated upgrades documentation in k3s documentation
Rancher management is out of sync and when i attempt to do some operations like adding changing some cluster info like adding a badge, it fails due to failing to apply the older version due to newer one

here's my cluster api resource
```
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    management.cattle.io/current-cluster-controllers-version: 1.27.10+k3s2
  name: local
spec:
  internal: true
  k3sConfig:
    k3supgradeStrategy:
      serverConcurrency: 1
      workerConcurrency: 1
    kubernetesVersion: v1.24.12+k3s1
status:
  driver: k3s
  version:
    gitVersion: v1.27.11+k3s1
    goVersion: go1.21.7
    major: '1'
    minor: '27'
    platform: linux/amd64

```

I tried to change the version but this attempt triggers rancher to upgrade the cluster which is not desired.
I'd like to propose that there should be an annotation (or use an already existent one, like being a local cluster) to control if rancher is the one responsible or not for managing the cluster's version.
