### ISSUE TITLE
[BUG] Cluster Role Templates can be set with projectCreatorDefault: true

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44860]
If roletemplates with the context: cluster are incorrectly configured with projectCreatorDefault: true then when a project is created it spams the logs with error syncing messages. There should be a validating webhook to capture this when the roletemplate is being created to fail if context: cluster and projectCreatorDefault: true are both there.

**Repro steps:**

Create a RoleTemplate with context: cluster and projectCreatorDefault: true
Create a Project
Follow Rancher Pod Logs

**Workaround:**
Is workararound available and implemented? yes
What is the workaround: remove bad roletemplate from authz annotation

**Actual behavior:**
RoleTemplate with incorrect setting can be created

**Expected behavior:**
RoleTemplate would fail a validation webhook like the projectroletemplatebindings do.

**Comment by samjustus** [comment]
sure-7635

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

Validation was introduced that prevents the combination of `.context: cluster` and `.projectCreatorDefault: true` which means they'll be rejected by the admission-control webhook.

## Areas or cases that should be tested

- Create a `RoleTemplate` with `.context: cluster` and `.projectCreatorDefault: true` this should now be rejected, previously the service would log out errors saying that it wasn't allowed after it had been applied to the cluster.

## What areas could experience regressions

- Existing `RoleTemplates` with this combination will fail to be applied to the cluster.

## Are the repro steps accurate/minimal?

Yes.

**Comment by brudnak** [comment]
<a name="top"></a>

## 🧪 Test Cases

| \#  | Priority | Description & Link                                        | PASS/FAIL        |
| --- | -------- | --------------------------------------------------------- | ---------------- |
| 1   | P0       | [Basic Validation Test](#test-1)                          | ⏸️ NOT TESTED YET |
| 2   | P0       | [Valid Combinations Test](#test-2)                        | ⏸️ NOT TESTED YET |
| 3   | P1       | [Empty Context](#test-3)                                  | ⏸️ NOT TESTED YET |
| 4   | P1       | [Update Rejection Test](#test-4)                          | ⏸️ NOT TESTED YET |
| 5   | P1       | [Valid Update](#test-5)                                   | ⏸️ NOT TESTED YET |
| 6   | P1       | [Upgrade: Existing Invalid RoleTemplates Update](#test-6) | ⏸️ NOT TESTED YET |
| 7   | P1       | [Upgrade](#test-7)                                        | ⏸️ NOT TESTED YET |

<details>
    <summary>🚨 7 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Basic Validation Test Status: ⏸️ NOT TESTED YET

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

  1. Attempt to create a new RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: invalid-roletemplate.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: invalid-cluster-project-creator
     context: cluster
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML using `kubectl apply -f invalid-roletemplate.yaml`
  3. Verify that the creation is rejected by the admission-control webhook.

**✅ Expected Outcome**

Role template creation to be rejected by the webhook

**✅ Actual Outcome**


</details>

<hr>

# 2 / Valid Combinations Test Status: ⏸️ NOT TESTED YET

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

  1. Create a RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: valid-rt1.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: valid-project-creator
     context: project
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Create another RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: valid-rt2.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: valid-cluster-role
     context: cluster
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["namespaces"]
         verbs: ["get", "list", "watch"]
     ```

  3. Apply both YAMLs and verify that both creations are successful.
     1. `kubectl apply -f valid-rt1.yaml`
     2. `kubectl apply -f valid-rt2.yaml`

**✅ Expected Outcome**

For the valid role templates to be successfully created

**✅ Actual Outcome**


</details>

<hr>

# 3 / Empty Context Status: ⏸️ NOT TESTED YET

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

  1. Attempt to create a RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: empty-context-role
     context: ""
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML and verify it's rejected.

**✅ Expected Outcome**

Should be rejected by the webhook

**✅ Actual Outcome**


</details>

<hr>

# 4 / Update Rejection Test Status: ⏸️ NOT TESTED YET

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

  1. Create a valid RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: initially-valid-cluster-role
     context: cluster
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML, then attempt to update it to have `projectCreatorDefault: true` using `kubectl edit roletemplate initially-valid-cluster-role`
  3. Verify that the update is rejected.

**✅ Expected Outcome**

The update should be blocked by the webhook

**✅ Actual Outcome**


</details>

<hr>

# 5 / Valid Update Status: ⏸️ NOT TESTED YET

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

 1. Create a RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: updatable-project-role
     context: project
     projectCreatorDefault: false
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list"]
     ```

  2. Apply the YAML, then update it to have `projectCreatorDefault: true` and add "watch" to verbs using `kubectl edit roletemplate updatable-project-role`
  3. Verify the update is successful.

**✅ Expected Outcome**

Able to update the role template

**✅ Actual Outcome**


</details>

<hr>

# 6 / Upgrade: Existing Invalid RoleTemplates Update Status: ⏸️ NOT TESTED YET

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

> Verify that existing invalid RoleTemplates cannot be updated without correcting the invalid combination.

1. Start with Rancher on a version without the fix
2. Create this role template on that version of Rancher

     ```yaml
     # FILE NAME: legacy-invalid-combination-rt.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: legacy-invalid-combination
     context: cluster
     projectCreatorDefault: true
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

3. `kubectl apply -f legacy-invalid-combination-rt.yaml`
4. Upgrade Rancher to a version with the fix
5. Try to update the role template by adding `resources: ["pods", "services"]`
6. Verify that the update is rejected if the invalid combination is not corrected.
7. Attempt to update the same RoleTemplate, changing `context` to "project":

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: legacy-invalid-combination
     context: project
     projectCreatorDefault: true
     clusterCreatorDefault: false
     rules:
       - apiGroups: [""]
         resources: ["pods", "services"]
         verbs: ["get", "list", "watch"]
     ```

8. Verify that this valid update is accepted.

**✅ Expected Outcome**

Updating an invalid role template from an older version of Rancher should be successful

**✅ Actual Outcome**


</details>

<hr>

# 7 / Upgrade Status: ⏸️ NOT TESTED YET

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a version of Rancher without the fix
2. Upgrade to a version of Rancher with the fix
3. Repeat applicable test cases (1, 2, 3, 4, 5)

**✅ Expected Outcome**

Test cases should still pass when coming from an older version of Rancher 

**✅ Actual Outcome**


</details>

<hr>

</details>

**Comment by brudnak** [comment]
## Validation Environment




| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head |
| Installation option              | Helm (high availability)                           |
| If Helm Chart k8s cluster        | v1.28.10                                           |
| Cert Details                     | external tls `aws acm`                             |
| Docker version                   | 20.10.7, build f0df350                             |
| Helm version                     | v2.16.8-rancher2                                   |
| Downstream cluster type          | Linode k3s                                         |
| Downstream K8s version           | v1.29.6+k3s2                                       |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |
| Dashboard                        | master 2fdd3be                                     |
| Webhook version                  | rancher/rancher-webhook:v0.5.0-rc14                |

<details>
    <summary>🏗️ Rancher Installation Details... CLICK TO EXPAND! ⬅️</summary>

```sh
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set tls=external \
  --set rancherImageTag=v2.9-head \
  --set global.cattle.psp.enabled=false
```

</details>

<a name="top"></a>

## 🧪 Test Cases

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | [Basic Validation Test](#test-1)                          | ✅ PASS    |
| 2   | P0       | [Valid Combinations Test](#test-2)                        | ✅ PASS    |
| 3   | P1       | [Empty Context](#test-3)                                  | ✅ PASS    |
| 4   | P1       | [Update Rejection Test](#test-4)                          | ✅ PASS    |
| 5   | P1       | [Valid Update](#test-5)                                   | ✅ PASS    |
| 6   | P1       | [Upgrade: Existing Invalid RoleTemplates Update](#test-6) | ✅ PASS    |
| 7   | P1       | [Upgrade](#test-7)                                        | ✅ PASS    |

<details>
    <summary>🚨 7 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Basic Validation Test Status: ✅ PASS 

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

  1. Attempt to create a new RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: invalid-roletemplate.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: invalid-cluster-project-creator
     context: cluster
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML using `kubectl apply -f invalid-roletemplate.yaml`
  3. Verify that the creation is rejected by the admission-control webhook.

**✅ Expected Outcome**

Role template creation to be rejected by the webhook

**✅ Actual Outcome**

Rejected by the webhook as expected:

```log
Error from server (BadRequest): error when creating "test1.yaml": admission webhook "rancher.cattle.io.roletemplates.management.cattle.io" denied the request: roletemplate.context: Forbidden: RoleTemplate context must be project when projectCreatorDefault=true
```

</details>

<hr>

# 2 / Valid Combinations Test Status: ✅ PASS 

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

  1. Create a RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: valid-rt1.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: valid-project-creator
     context: project
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Create another RoleTemplate with the following YAML:

     ```yaml
     # FILE NAME: valid-rt2.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: valid-cluster-role
     context: cluster
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["namespaces"]
         verbs: ["get", "list", "watch"]
     ```

  3. Apply both YAMLs and verify that both creations are successful.
     1. `kubectl apply -f valid-rt1.yaml`
     2. `kubectl apply -f valid-rt2.yaml`

**✅ Expected Outcome**

For the valid role templates to be successfully created

**✅ Actual Outcome**

Able to successfully create these roles

```shell
kubectl apply -f valid-rt1.yaml 
roletemplate.management.cattle.io/valid-project-creator created

kubectl apply -f valid-rt2.yaml  
roletemplate.management.cattle.io/valid-cluster-role created
```

</details>

<hr>

# 3 / Empty Context Status: ✅ PASS 

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

  1. Attempt to create a RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: empty-context-role
     context: ""
     projectCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML and verify it's rejected.

**✅ Expected Outcome**

Should be rejected by the webhook

**✅ Actual Outcome**

Rejected by webhook as expected:

```log
Error from server (BadRequest): error when creating "empty.yaml": admission webhook "rancher.cattle.io.roletemplates.management.cattle.io" denied the request: roletemplate.context: Forbidden: RoleTemplate context must be project when projectCreatorDefault=true
```

</details>

<hr>

# 4 / Update Rejection Test Status: ✅ PASS 

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

  1. Create a valid RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: initially-valid-cluster-role
     context: cluster
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

  2. Apply the YAML, then attempt to update it to have `projectCreatorDefault: true` using `kubectl edit roletemplate initially-valid-cluster-role`
  3. Verify that the update is rejected.

**✅ Expected Outcome**

The update should be blocked by the webhook

**✅ Actual Outcome**

Rejected by webhook as expected:

```log
error: roletemplates.management.cattle.io "initially-valid-cluster-role" could not be patched: admission webhook "rancher.cattle.io.roletemplates.management.cattle.io" denied the request: roletemplate.context: Forbidden: RoleTemplate context must be project when projectCreatorDefault=true
```

</details>

<hr>

# 5 / Valid Update Status: ✅ PASS 

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

 1. Create a RoleTemplate with the following YAML:

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: updatable-project-role
     context: project
     projectCreatorDefault: false
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list"]
     ```

  2. Apply the YAML, then update it to have `projectCreatorDefault: true` and add "watch" to verbs using `kubectl edit roletemplate updatable-project-role`
  3. Verify the update is successful.

**✅ Expected Outcome**

Able to update the role template

**✅ Actual Outcome**

Update was successful

</details>

<hr>

# 6 / Upgrade: Existing Invalid RoleTemplates Update Status: ✅ PASS 

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

> Verify that existing invalid RoleTemplates cannot be updated without correcting the invalid combination.

1. Start with Rancher on a version without the fix
2. Create this role template on that version of Rancher

     ```yaml
     # FILE NAME: legacy-invalid-combination-rt.yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: legacy-invalid-combination
     context: cluster
     projectCreatorDefault: true
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods"]
         verbs: ["get", "list", "watch"]
     ```

3. `kubectl apply -f legacy-invalid-combination-rt.yaml`
4. Upgrade Rancher to a version with the fix
5. Try to update the role template by adding `resources: ["pods", "services"]`
6. Verify that the update is rejected if the invalid combination is not corrected.
7. Attempt to update the same RoleTemplate, changing `context` to "project":

     ```yaml
     apiVersion: management.cattle.io/v3
     kind: RoleTemplate
     metadata:
       name: legacy-invalid-combination
     context: project
     projectCreatorDefault: false
     clusterCreatorDefault: true
     rules:
       - apiGroups: [""]
         resources: ["pods", "services"]
         verbs: ["get", "list", "watch"]
     ```

8. Verify that this valid update is accepted.

**✅ Expected Outcome**

Updating an invalid role template from an older version of Rancher should be successful

**✅ Actual Outcome**

Able to update the role template as expected and get it into a valid state

</details>

<hr>

# 7 / Upgrade Status: ✅ PASS   

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a version of Rancher without the fix
2. Upgrade to a version of Rancher with the fix
3. Repeat applicable test cases (1, 2, 3, 4, 5)

**✅ Expected Outcome**

Test cases should still pass when coming from an older version of Rancher 

**✅ Actual Outcome**

Same passing results on all cases from an upgraded setup

</details>

<hr>

</details>
