### ISSUE TITLE
Not able to delete service/Replication controller/pod.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4515]
Rancher Version: Build from master

Docker Version: 1.10.3

Steps to Reproduce: 

Create a kubernetes environment with few hosts.
Create service/Replication controller/pod using the following command:

./kubectl create -f nginx.yml

nginx.yml:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: testnginx
spec:
  replicas: 2
  selector:
    name: testnginx
  template:
    metadata:
      labels:
        name: testnginx
    spec:
      containers:
        - name: testnginx
          image: nginx
          ports:
            - containerPort: 80

---            

apiVersion: v1
kind: Service
metadata:
  name: testnginx
  labels:
    name: testnginx
    type: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: testnginx
```

Delete service/Replication controller/pod using "delete" option in UI.

Deletion fails for service/Replication controller/pod with the following error message:

```
Request URL:http://<ip-address>:8080/v1/projects/1a5/r/kubernetes/api/v1/namespaces/default/replicationcontrollers/testnginx
Request Method:DELETE
Status Code:404 Not Found
```
