### ISSUE TITLE
[rancher-compose] How to pass multiline values as answers with CLI

### ISSUE THREAD

**Issue by michaellopez** [rancher/rancher#4518]
Rancher Version: v1.0.0

Docker Version: Docker version 1.11.0, build 4dc5990

OS: Mac OS X 10.10.5

Steps to Reproduce: Create a `docker-compose.yml` and `rancher-compose.yml`. In the `rancher-compose.yml` add a question:

``` yml
.catalog:
  name: Name
  version: version
  description: |
    Description
  questions:
    - variable: multi
      type: multiline
      label: Multiline
      description: |
        A multiline test
```

`rancher-compose up -d` asks interactively in the CLI for an answer for `multi` variable. I am trying to figure out how to enter a multiline value, or rather paste a multiline value. I've tried all the usual methods with `\` `"` and `'`

Results:  First newline char acts as "enter" on the CLI confirming only the first line as the value. Making the rest of the pasted lines error out as bad bash commands or similar.

Expected: A way to pass multiline values.
