### ISSUE TITLE
Ports are not mapping and when they do it doesn't work as expected. 

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#4540]
**Rancher Version:** 1.0.1

**Docker Version:** 1.10 and 1.11

**OS:** centos7

**Steps to Reproduce:** 
_docker-compose.yml_
```
logio:
  image: blacklabelops/logio:latest
  container_name: logio
  restart: always
  hostname: "logger.domain.com"
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: logioserver=true
  expose:
    - 28778:28778
    - 28777:28777
  ports:
    - 28778:28778
    - 28777:28777
  environment:
    TERM: xterm-256color
    LOGIO_ADMIN_USER: ${LOGIO_ADMIN_USER}
    LOGIO_ADMIN_PASSWORD: ${LOGIO_ADMIN_PASSWORD}
    LOGIO_CERTIFICATE_DNAME: ${LOGIO_CERTIFICATE_DNAME}
  volumes:
    - /opt/server
```

_rancher-compose.yml_
```
.catalog:
  name: Log.io
  description: |
     Log.io server for collecting and display real-time text streams.
  version: v0.0.1
  category: Logging
  minimum_rancher_version: v0.90.0
  
  questions:

    - variable: LOGIO_ADMIN_USER
      description: "HTTP Auth username for web interface"
      label: "Web Username"
      required: false
      type: "string"

    - variable: LOGIO_ADMIN_PASSWORD
      description: "HTTP Auth password for web interface"
      label: "Web Password"
      required: false
      type: "string"

    - variable: LOGIO_CERTIFICATE_DNAME
      description: "Certificat DName"
      label: "Certificate DName"
      required: false
      type: "string
```

**Results:**
Couple errors:

1. Ports don't get properly mapped. Before creating this stack I exposed 28777 and 28778 fully in firewalld, after install - ports - ports are closed for public access

2. IP address that is specified is not binding and the port is showing that it is open globally (in my case it's an issue because port is Jared across multiple services that run on same port and its not able to bind globally since it is already used on a couple of other ips on same host) but when I move my mouse over it is showing that it is associated with ip 172.17.0.1 and if fact it remains block from outer access

3. When I Try to edit ports and add IP: in front of the port, only first number of the up address gets stripped off, i.e. 5.9.9.9:27017 as source [ip:]port it will keep only number 5 after I save the form and no matter what I try to do it won't work. 

Reproducible every time with any other docker-compose that I tried

**Expected:**
Expected same as docker standard behavior when it exposes ports or publishes them as specified in docker. 

And for edit port mapping to save changes properly without dropping everything after the first . (Period)
