### ISSUE TITLE
[SURE-8656] [RFE] Support Creating a Cluster with a Service Account

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#45591]
**Is your feature request related to a problem? Please describe.**
When importing CAPI-provisioned clusters via [Turtles](https://github.com/rancher/turtles), the Rancher cluster resource are generated and there are errors related to `creatorId`, like the following:
```
[ERROR] error syncing 'c-m-fl56rrkb/creator-cluster-owner': handler mgmt-auth-crtb-controller: users.management.cattle.io "system:serviceaccount:rancher-turtles-system:rancher-turtles-manager" not found, requeuing
```

When importing the same cluster via the "standard" Rancher way, the `creatorId` annotation is populated with a valid `users.management.cattle.io` and the error is gone.

The issue is that Turtles (as part of it's operation) creates a mgmt cluster. There is functionality which gives the user who creates this CRD default bindings (usually to cluster-owner). However, in the turtles case, this user is a service account, and our RBAC doesn't work for service accounts. So we get error logs as our handlers spin and can't process the user.

**Describe the solution you'd like**
Provide a method for users to bypass the default bindings, possibly by adding an annotation to the cluster.

**Describe alternatives you've considered**
Instead of explicitly adding an annotation to the cluster, the default bindings could be bypassed based on the user type when importing a cluster. Generally, RBAC rules and bindings are preferred to be explicit. Otherwise that implicit logic if not well maintained can lead to CVEs.

Perhaps another solution would be to have RBAC work with Service Accounts. This needs more research if it's even feasible as it may not be supported by Kubernetes.

**Reproduction**
1. Install turtles on rancher ([guide here](https://turtles.docs.rancher.com/getting-started/install-rancher-turtles/using_rancher_dashboard/))
2. Provision a downstream cluster ([guide here](https://turtles.docs.rancher.com/getting-started/create-first-cluster/using_kubectl/))
3. Once the cluster is imported, the Rancher logs will begin to produce the above RBAC error

**Comment by JonCrowther** [comment]
SURE-8656

**Comment by JonCrowther** [comment]
There is now an annotation `field.cattle.io/no-creator-rbac` that when applied to clusters, prevents any ClusterOwner or ProjectOwner roles to be created, thus allowing a service account to create the cluster.

**Comment by JonCrowther** [comment]
## Validation Template
## What was fixed, or what change has occurred

For things like CAPI and Turtles, cluster provisioning is done by a service account. When a cluster is provisioned, it provides RBAC to the creator to designate it as a `cluster-owner`. The problem is that RBAC can't be assigned to a service account, so the logs get filled with errors as it repeatedly tries to assign `cluster-owner` to a service account.

To fix this, we've added a check for the annotation `field.cattle.io/no-creator-rbac`. When applied to a cluster (via yaml) the RBAC controllers will not attempt to create RBAC for the service account.

## Areas or cases that should be tested

Since this is only a change in the logs a user is seeing, the impact is fairly minimal. Attempt to provision a cluster with a service account and watch the logs for the following error:
```
[ERROR] error syncing 'c-m-fl56rrkb/creator-cluster-owner': handler mgmt-auth-crtb-controller: users.management.cattle.io "system:serviceaccount:rancher-turtles-system:rancher-turtles-manager" not found, requeuing
```

## What areas could experience regressions

Make sure that provisioning a cluster normally (ie not with a service account) creates the `cluster-owner` RBAC.

Since the RBAC path for provisioning is the same for all cloud providers, there should be no regressions across providers. Provisioning an RKE cluster and an AKS cluster look the same as far as RBAC goes, so there should be no differences.

## Are the repro steps accurate/minimal?

Because the fix requires additional steps from Turtles and CAPI to add the annotation, the easiest way to test the changes is as follows:

1. Create a service account
```
kubectl create sa $SA_NAME -n $NAMESPACE
```
2. Give the service account admin access in the local cluster
```
kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=$NAMESPACE:$SA_NAME
```
3. Create a token for the service account
```
kubectl create token $SA_NAME -n $NAMESPACE
```
4. Create a kubeconfig for the service account ([source](https://stackoverflow.com/questions/47770676/how-to-create-a-kubectl-config-file-for-serviceaccount))
```
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    server: $RANCHER_URL
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: $NAMESPACE
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: $TOKEN
```
5. Get a digital ocean cluster yaml to apply. 
   a. In the UI, provision a digital ocean (or provider of choice) RKE cluster
   b. Find the `DigitalOceanConfig` yaml that was created
   c. Find the `Cluster` yaml that was created
   d. Copy those yamls, and add the annotation `field.cattle.io/noCreatorRBAC: "true"` to both
   e. Give both new names and apply the yamls using your service account config
6. Watch the logs for the error

<details>
<summary>Example digital ocean yaml</summary>

```
accessToken: ""
apiVersion: rke-machine-config.cattle.io/v1
backups: false
image: ubuntu-20-04-x64
ipv6: false
kind: DigitaloceanConfig
metadata:
  annotations:
    field.cattle.io/noCreatorRBAC: "true"
  name: nc-test-cluster-pool1-srqfr
  namespace: fleet-default
monitoring: false
privateNetworking: false
region: sfo3
size: s-2vcpu-4gb
sshKeyContents: ""
sshKeyFingerprint: ""
sshPort: "22"
sshUser: root
tags: ""
userdata: ""

---

apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/noCreatorRBAC: "true"
  name: test-cluster
  namespace: fleet-default
spec:
  cloudCredentialSecretName: cattle-global-data:cc-7pqbc
  kubernetesVersion: v1.31.0+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    dataDirectories: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machinePools:
    - controlPlaneRole: true
      drainBeforeDelete: true
      dynamicSchemaSpec: '{"resourceFields":{"accessToken":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital
        Ocean access token"},"backups":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
        backups for droplet"},"image":{"type":"string","default":{"stringValue":"ubuntu-20-04-x64","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital
        Ocean Image"},"ipv6":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
        ipv6 for droplet"},"monitoring":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
        monitoring for droplet"},"privateNetworking":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"enable
        private networking for droplet"},"region":{"type":"string","default":{"stringValue":"nyc3","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital
        Ocean region"},"size":{"type":"string","default":{"stringValue":"s-1vcpu-1gb","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Digital
        Ocean size"},"sshKeyContents":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File
        contents for sshKeyContents"},"sshKeyFingerprint":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
        key fingerprint"},"sshPort":{"type":"string","default":{"stringValue":"22","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
        port"},"sshUser":{"type":"string","default":{"stringValue":"root","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"SSH
        username"},"tags":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"comma-separated
        list of tags to apply to the Droplet"},"userdata":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File
        contents for userdata"}}}'
      etcdRole: true
      machineConfigRef:
        kind: DigitaloceanConfig
        name: nc-test-cluster-pool1-srqfr
      name: pool1
      quantity: 1
      unhealthyNodeTimeout: 0s
      workerRole: true
    machineSelectorConfig:
    - config:
        protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: "1"
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: "1"
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120

```

</details>
