### ISSUE TITLE
How to set up mysql with data volume

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#4559]
How can I set up a mysql server as a rancher service while storing the mysql data inside a volume? Do you have a tutorial for this?

**Comment by Frintrop** [comment]
Maybe have a look here:
http://rancher.com/using-convoy-to-backup-and-recover-a-wordpress-mysql-database-with-docker/

**Comment by galal-hussein** [comment]
@opichon The article describes how to create mysql database as a service in Rancher with Convoy volume driver, However if you are looking for a simple host backend volume, you can use something like the following docker-compose.yml file:
```
mysql:
  ports:
  - 3306:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: mysql-root-pw
  labels:
    io.rancher.container.pull_image: always
  image: mysql:5.6
  volumes:
  - /var/lib/mysql:/var/lib/mysql
```

You can run the previous file using rancher-compose or use the UI directly.
