### ISSUE TITLE
[BUG] inheritedClusterRoles cause local cluster to not appear in UI

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#45708]
**Rancher Server Setup**
- Rancher version: 2.8.2 (also seen in 2.9-latest)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Both
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): I used k3s

**Describe the bug**
When a user is given a global role that has both `rules` and `inheritedClusterRoles`, that user doesn't see the local cluster in the UI when they log in.

**To Reproduce**
_Need a downstream cluster to reproduce_

1. Create the following global role:

```
apiVersion: management.cattle.io/v3
inheritedClusterRoles:
- nodes-view
kind: GlobalRole
metadata:
  name: test-global-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
```

2. Create a new user and give it that global role + user base
3. Log in as that user

**Result**
The user can only see the downstream cluster and not the upstream cluster.

**Expected Result**
Both the upstream and downstream cluster should be visible. The user should see `clusters` and `pods` in the upstream, and be able to see `nodes`, `nodepools`, and everything else given by roletemplate `nodes-view` in the downstream cluster.

**Additional context**
If you create the same global role without the `inheritedClusterRoles`, the user is able to see the local cluster and view the `pods` and `clusters`.
