### ISSUE TITLE
Not able to start a service using "up" command because of validation failures on certain fields.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4600]
./rancher-compose -p test168303rancher -f docker-compose.yml -r rancher-compose.yml up -d
[u'time="2016-04-29T01:03:38Z" level=error msg="Could not parse config for project test168303rancher : Service \'test499436\' configuration key \'command\' contains 9000, which is an invalid type, it should be a string\nService \'test499436\' configuration key \'cpuset\' contains an invalid type, it should be a string." \n', u'time="2016-04-29T01:03:38Z" level=fatal msg="Failed to read project: Service \'test499436\' configuration key \'command\' contains 9000, which is an invalid type, it should be a string\nService \'test499436\' configuration key \'cpuset\' contains an invalid type, it should be a string." \n']

Contents of rancher-compsoe.yml and docker-compose.yml

```
test499436:
  image: ibuildthecloud/helloworld:latest
  cap_drop:
  - KILL
  stdin_open: true
  volumes:
  - /test/container:/test/vol1:ro
  dns:
  - 1.2.3.4
  domainname: rancher.io
  cpuset: '0'
  command:
  - sleep
  - '9000'
  labels:
    io.rancher.scheduler.affinity:container_label: c1=vol
  privileged: true
  mem_limit: 8000000
  cap_add:
  - CHOWN
  hostname: test
  environment:
    TEST_FILE: /etc/testpath.conf
  dns_search:
  - 1.2.3.4
  tty: true
  user: root
  cpu_shares: 400
```

`
test499436:
  scale: 1
`
