### ISSUE TITLE
[BUG] Status of clusterRoleExists is `completed` even when it is deleted

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46065]
**Rancher Server Setup**
- Rancher version: v2.9-head `1c2b815c8dd`

**Information about the Cluster**
- Kubernetes version: `v1.30.1+k3s1`
- Cluster Type (Local/Downstream): Local
 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Global role status fields is not updating summary for `ClusterRoleExists` even when we delete the backing cluster role.

**To Reproduce**
1. Create a global role with the following yaml: 
```
apiVersion: management.cattle.io/v3
builtin: false
displayName: grole1
kind: GlobalRole
metadata:
  name: grole1
  finalizers:
    - foo
rules:
  - cattle-global-datae:
    - apiGroups:
        - management.cattle.io
      resources:
        - preferences
      verbs:
        - '*'
```
2. Verify a backing cluster role `cattle-globalrole-grole2` is created.
3. Verified the status is completed too.
4. Delete the cluster role. 
5. Observe the status.conditions.message in the status field of the global role and the lastTransitionTime and lastUpdateTime 

**Result**
Message is not changed on the global role status field.
the lastTransitionTime and lastUpdateTime are not changed as well.

**Expected Result**
Expected the message is updated for the global role status field as there is a change in the backing cluster role.

**Screenshots**
<img width="500" alt="2024-07-08_16-19-11" src="https://github.com/rancher/rancher/assets/38144301/85e79bc0-eff6-4cb2-842f-39ac64efdf61">
