### ISSUE TITLE
[BUG]lastTransitionTime and lastUpdateTime are same across all resources for Global role status fields 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46064]
**Rancher Server Setup**
- Rancher version: v2.9-head `1c2b815c8dd`

**Information about the Cluster**
- Kubernetes version: `v1.30.1+k3s1`
- Cluster Type (Local/Downstream): Local
 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Global role status fields for namespaced rules and cluster role exists have the same last transition time and last updated time, even when the namespaced rules resource is updated.

**To Reproduce**
1. Create a global role with the following yaml: 
```
apiVersion: management.cattle.io/v3
builtin: false
displayName: grole1
kind: GlobalRole
metadata:
  name: grole1
  finalizers:
    - foo
namespacedRules:
  - cattle-global-datae:
    - apiGroups:
        - management.cattle.io
      resources:
        - preferences
      verbs:
        - '*'
```
2. The status field shows error as the namespace does not exist but for ClusterRoleExists, status is completed.
3. Edit the yaml and update the namespace name to `cattle-global-data`
4. Notice the error is resolved
5. Notice the lastTransitionTime and lastUpdateTime for both namespaced rules and cluster role exists.

**Result**
lastTransitionTime and lastUpdateTime are same even and is updated for cluster roles as well when there is no change to the cluster role.

**Expected Result**
Expected lastTransitionTime and lastUpdateTime to be different for both of the resources as there was a change only to the namespace rules.

**Screenshots**
<img width="400" alt="2024-07-08_16-08-32" src="https://github.com/rancher/rancher/assets/38144301/83ca75aa-32f6-4fb1-8e3f-1cd7930317b4">
