### ISSUE TITLE
[BUG] Members of nested groups in Azure AD do not inherit the same permissions as those in the parent group

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46169]
**Rancher Server Setup**
- Rancher version: v2.9-head `3c4ccdc` and upgrade from 2.8.5 to 2.9-head
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: Local 
- Cluster Type (Local/Downstream): `v1.30.2+k3s2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When a group is added in Azure AD with specific permissions, members of nested groups do not receive the same permissions. After upgrading from version 2.8.5 to 2.9-head, nested group members who previously had access in 2.8.5 lose their access post Rancher upgrade.

**To Reproduce**
1. Create a rancher server v2.8.5
2. Enable azure AD with default settings - do not add any filter.
3. Navigate to Users and auth >> role template, create a global role as follows:
```
apiVersion: management.cattle.io/v3
displayName: inheritedrole1
inheritedClusterRoles:
  - cluster-owner
kind: GlobalRole
metadata:
  name: role1
```
4. Create a downstream node provider k3s cluster.
5. Navigate to Users and auth >> groups >> Add a user group with the role created above. >> group1
6. Login as a user1 from the group nested in the parent group >> group2
7. Verify the user has permissions to the downstream cluster.
8. Upgrade rancher server to v2.9-head.

**Result**
Notice the user1 do not have the permissions that were previously seen pre upgrade.

**Expected Result**
Expected nested users to have permissions added for the parent group.

**Additional context**

- This is only seen on azure AD auth providers. Tried the same use case with Active directory and noticed no change in the permissions.
- User attributes post upgrade do not have the parent group listed..
F.e:
### 2.8.5 user attributes:
```
 azuread:
    Items:
    - displayName: anugroup
      memberOf: true
      metadata:
        creationTimestamp: null
        name: azuread_group://bf<redacted>
      principalType: group
      provider: azuread
    - displayName: anunestedgroup1
      memberOf: true
      metadata:
        creationTimestamp: null
        name: azuread_group://95<redacted>
      principalType: group
      provider: azuread
```

### 2.9-head user attributes:
```
  azuread:
    Items:
    - displayName: anunestedgroup1
      memberOf: true
      metadata:
        creationTimestamp: null
        name: azuread_group://95<redacted>
      principalType: group
      provider: azuread
```

Group structure:
```
anugroup
|__ anuuser1
|__ anunestedgroup1
      |__ anunesteduser1
```
