### ISSUE TITLE
[2.9.0][BUG][Steve] Steve server will panic if the cluster hosted NonStructuralSchema crds

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#46213]
**Rancher Server Setup**
- Rancher version: v2.9-head
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details: N/A

**Cluster version**: 
- `v1.26.3-aliyun.1`

Related Steve version: https://github.com/rancher/steve/tree/47871606146c436849dabf0a7ed7cd9dd3356817

As title, the steve server will panic with following errors:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x60dd9f5]

goroutine 907 [running]:
github.com/rancher/steve/pkg/schema/definitions.listGVKModels({0x6b9c288, 0xc001d6b228}, 0xc00244cf80, {0x4ec7dae8, 0xc0002eb380})
        /Users/dengyuxing/gopath/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:226 +0x5b5
github.com/rancher/steve/pkg/schema/definitions.(*SchemaDefinitionHandler).Refresh(0xc000866240)
        /Users/dengyuxing/gopath/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:107 +0x17a
github.com/rancher/steve/pkg/debounce.(*DebounceableRefresher).RefreshAfter.func1()
        /Users/dengyuxing/gopath/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/debounce/refresher.go:49 +0x106
created by github.com/rancher/steve/pkg/debounce.(*DebounceableRefresher).RefreshAfter in goroutine 962
        /Users/dengyuxing/gopath/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/debounce/refresher.go:38 +0x13b
exit status 2
``` 

The crd is not validated because it's created in 1.20.x via API group `apiextensions.k8s.io/v1beta1` which didn't require `spec.validation` back in the days. And the cluster got upgraded to v1.26.* but the crd remains.

The panic code is here https://github.com/rancher/steve/blob/master/pkg/schema/definitions/handler.go#L226, which might need to check for condition `NonStructuralSchema` is true or `versions[].schema` is nil.

Related crds:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2022-02-07T06:04:24Z"
  generation: 1
  name: globaljobs.jobs.aliyun.com
  resourceVersion: "6696734787"
  uid: ba580245-14a1-41bd-ac8c-6a13c1cd5f30
spec:
  conversion:
    strategy: None
  group: jobs.aliyun.com
  names:
    kind: GlobalJob
    listKind: GlobalJobList
    plural: globaljobs
    shortNames:
    - globaljob
    singular: globaljob
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: GlobalJob
    listKind: GlobalJobList
    plural: globaljobs
    shortNames:
    - globaljob
    singular: globaljob
  conditions:
  - lastTransitionTime: "2022-02-07T06:04:24Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-02-07T06:04:24Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2022-02-07T06:12:29Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  storedVersions:
  - v1alpha1
```

**Comment by flostru** [comment]
Found some aswell preventing 2.9.0 from updating cluster agents in 1.26 rke1 downstream clusters.

I know < 1.27 is unsupported in rancher 2.9.0, but maybe it helps somebody to find CRDs that cause trouble in legacy clusters.

just kubectl edit following CRDs

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteruserattributes.cluster.cattle.io
spec:
  conversion:
    strategy: None
  group: cluster.cattle.io
  names:
    kind: ClusterUserAttribute
    listKind: ClusterUserAttributeList
    plural: clusteruserattributes
    singular: clusteruserattribute
  # preserveUnknownFields: true # remove this
  scope: Namespaced
  versions:
  - name: v3
    # add this
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterauthtokens.cluster.cattle.io
spec:
  conversion:
    strategy: None
  group: cluster.cattle.io
  names:
    kind: ClusterAuthToken
    listKind: ClusterAuthTokenList
    plural: clusterauthtokens
    singular: clusterauthtoken
  # preserveUnknownFields: true # remove this
  scope: Namespaced
  versions:
  - name: v3
    # add this
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
```

**Comment by andrew-landsverk-win** [comment]
I'm having a similar issue in one of our older downstream clusters. The cluster in question has been upgraded from older versions and is on a currently supported version (1.28). I looked at the 3 CRDs mentioned so far in this issue and I don't have any of them on my clsuter. Does anyone have a good way to determine which CRD is causing the issue for me? Thanks in advance!

**Comment by andrew-landsverk-win** [comment]
Following up on my previous comment, I had to alter the CRDs for several rancher provided CRDs:

authconfigs.management.cattle.io
groupmembers.management.cattle.io
groups.management.cattle.io
tokens.management.cattle.io
userattributes.management.cattle.io
users.management.cattle.io

To remove `preserveUnknownFields` and to replace the contents of `versions` with the following:

```yaml
  - name: v3
    # add this
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```

Once I did that my child cluster connected back to Rancher.

**Comment by braunsonm** [comment]
Thanks @andrew-landsverk-win Similar story here.

Question for rancher folks, why is this happening for older upstream or downstream clusters even if they have been updated to the latest supported version? In our case this happed from an upgrade from 2.8.5 to 2.9.0 and our Kubernetes version is the latest RKE2 available. Aren't these CRDs being upgraded? Or is this a problem on new clusters too?

**Comment by andrew-landsverk-win** [comment]
@braunsonm it looks like they were updated in the Rancher cluster, but Rancher CRDs in the downstream clusters do not appear to be updated at all?

**Comment by braunsonm** [comment]
For further context, our Rancher Cluster from 2021 has 52 Rancher (cattle.io) CRDs with this problem, whereas our cluster from 2022 has none.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

Steve did not check if a CRD's version had a schema before attempting to access the OpenAPIV3 member field of the schema. This produced a panic in CRDs like the one identified in the issue. 

## What was fixed, or what change have occurred

Steve now checks to see if the version has a schema. If not, no information derived from the CRD is added to the Schema Definition. However, it will no longer Panic in the cases where no information is present.

## Areas or cases that should be tested

The original case. This can likely be reproduced by:
1. Install Rancher on v1.21 or earlier.
2. Create a CRD with no schema specified in the version. Example below taken from [this issue](https://github.com/kubernetes/kubernetes/issues/87231):
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  version: v1
  scope: ""
```
3. Upgrade to rancher/rancher:v2.9.0.
4. Observe panics in the log (before the patch, but not after the patch).

## What areas could experience regressions

Calculation of schema definitions on CRDs which have values set. See this [validation template](https://github.com/rancher/rancher/issues/45157#issuecomment-2208882016) for more information onwhich CRDs this effects.

## Are the repro steps accurate/minimal?

The steps are not very minimal, but they are included above, and require upgrading Rancher to test.

**Comment by ericpromislow** [comment]
To repro I did the followign running Rancher 2.5 on k8s 1.20:

Two files:

badcrd.yaml:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globaljobs.jobs.aliyun.com
spec:
  conversion:
    strategy: None
  group: jobs.aliyun.com
  names:
    kind: GlobalJob
    listKind: GlobalJobList
    plural: globaljobs
    shortNames:
    - globaljob
    singular: globaljob
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
```

badcrd-instance01.yaml:
```
apiVersion: jobs.aliyun.com/v1alpha1
kind: GlobalJob
metadata:
  name: example-global-job01
spec:
  data:
    key1: someValue
    anotherKey:
      key2: 15
```

```
$ kubectl apply -f badcrd.yaml
$ kubectl apply -f badcrd-instance01.yaml:
```

I then ran the folllowing script (using Rancher Desktop with the rdctl utility):
```
#!/bin/bash

set -exu

wait_for_k8s() {
    sleep 90
    while true; do
        if kubectl get --raw /readyz &>/dev/null; then
          break
        fi
        sleep 5
    done
    while true; do
        if [[ $(kubectl get node -o jsonpath="{.items[0].status.conditions[?(@.type=='Ready')].status}") == "True" ]] ; then
            break
        fi
        sleep 1
    done
    while true; do
        zob=$(kubectl get crd globaljobs.jobs.aliyun.com -o json| jq '.status.conditions[] | select(.type == "NonStructuralSchema") | .status')
        case $zob in
            "True") break ;;
        esac
        echo "Got $zob"
        sleep 1
    done
}


rdctl set --kubernetes.version=v1.21.14
wait_for_k8s
rdctl set --kubernetes.version=v1.22.17
wait_for_k8s
rdctl set --kubernetes.version=v1.23.17
wait_for_k8s
rdctl set --kubernetes.version=v1.24.17
wait_for_k8s
rdctl set --kubernetes.version=v1.25.16
wait_for_k8s
rdctl set --kubernetes.version=v1.26.15
wait_for_k8s
rdctl set --kubernetes.version=v1.27.15
wait_for_k8s
rdctl set --kubernetes.version=v1.28.11
wait_for_k8s
echo "Continue when watching the rancher logs"
read ok
rdctl set --kubernetes.version=v1.29.6
wait_for_k8s
```

Run the webhook logs when moving to k8s 1.29.6.  You should see a panic at startup in the rancher log files without this fix, and no logs with the fix.

**Comment by brudnak** [comment]
| Component                        | Version / Type                 |
| -------------------------------- | ------------------------------ |
| Rancher version starting         | v2.5.13                        |
| Rancher version upgraded         | v2.9.1-rc1                     |
| Installation option              | Helm (high availability)       |
| RKE binary version used          | `v1.2.19` --> ` v1.5.10`       |
| If Helm Chart k8s cluster        | `v1.28.10 `                    |
| Cert Details                     | external tls `aws acm`         |
| Docker version                   | 20.10.7, build f0df350         |
| Helm version                     | v2.16.8-rancher2               |
| Downstream cluster type          | not applicable                 |
| Downstream K8s version           | not applicable                 |
| Authentication providers enabled | local                          |
| Logged in user role              | admin                          |
| Browser type                     | Firefox Developer Edition      |
| Browser version                  | 130.0b4 (64-bit)               |
| Dashboard                        | v2.9.1-alpha1                  |
| Webhook version                  | rancher/rancher-webhook:v0.5.0 |

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                           | PASS/FAIL |
| --- | -------- | ------------------------------------------------------------ | --------- |
| 1   | P0       | [k8s Upgrade Then Install Rancher](#test-1)                  | ✅ PASS    |
| 2   | P0       | [Rancher upgrade](#test-2)                                   | ✅ PASS    |
| 3   | P0       | [Type Validation for rkeConfig field](#test-3)               | ✅ PASS    |
| 4   | P0       | [Steve Schemas performance (regression automation)](#test-4) | ✅ PASS    |



<details>
    <summary>🚨 4 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / k8s Upgrade Then Install Rancher Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Create k8s cluster with `rke up` using version: `v1.2.19` / `v1.20.15-rancher1-2`
2. Create the following CRD:

    ```yaml
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: examples.cluster.cattle.io
    spec:
      conversion:
        strategy: None
      group: cluster.cattle.io
      names:
        kind: Example 
        listKind: ExampleList
        plural: examples
        singular: example 
      preserveUnknownFields: true 
      scope: Namespaced
      versions:
      - name: v3
        served: true
        storage: true
    ```

3. Update using `rke up` with `rke` version: `v1.5.10` 
4. In the `cluster.yml` set the k8s version: `v1.28.10-rancher1-1`

    ```yaml
    kubernetes_version: "v1.28.10-rancher1-1"
    ```

5. Now install Rancher onto this setup with a version of Rancher with the fix
6. Rancher should come up active with no panic

**✅ Expected Outcome**

Rancher to be available for use, without a panic in the logs

**✅ Actual Outcome**

Rancher comes up active without a panic in the logs

</details>

<hr>

# 2 / Rancher upgrade Status: ✅ PASS   

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with rke `v1.2.19`
2. Start with Rancher `2.5.13`
3. Install this crd onto the cluster

    ```yaml
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: examples.cluster.cattle.io
    spec:
      conversion:
        strategy: None
      group: cluster.cattle.io
      names:
        kind: Example 
        listKind: ExampleList
        plural: examples
        singular: example 
      preserveUnknownFields: true 
      scope: Namespaced
      versions:
      - name: v3
        served: true
        storage: true
    ```

4. Start upgrading Rancher to to `v2.9.1-rc1`
5. Start upgrading k8s to `v1.28.10-rancher1-1`
6. Check the Rancher logs for the known panic

**✅ Expected Outcome**

To **not** receive the following panic:

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26586b5]
```

**✅ Actual Outcome**

Test was successful did not receive a panic


</details>

<hr>

# 3 / Type Validation for rkeConfig field Status: ✅ PASS  

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Access the `schemadefinitions` endpoint for "provisioning.cattle.io.cluster"
   - https://Rancher_URL/v1/schemadefinitions/provisioning.cattle.io.cluster
2. Verify that the type of the rkeConfig field under io.cattle.provisioning.v1.Cluster.spec is io.cattle.provisioning.v1.Cluster.spec.rkeConfig and has the subfields defined

**✅ Expected Outcome**

the type of the rkeConfig field under io.cattle.provisioning.v1.Cluster.spec is io.cattle.provisioning.v1.Cluster.spec.rkeConfig

**✅ Actual Outcome**

the type of the rkeConfig field under io.cattle.provisioning.v1.Cluster.spec is io.cattle.provisioning.v1.Cluster.spec.rkeConfig


</details>

<hr>

# 4 / Steve Schemas performance (regression automation) Status: ✅ PASS  

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated schemas automation to check for regressions: https://github.com/rancher/rancher/tree/main/tests/v2/validation/schemas

**✅ Expected Outcome**

No errors in the automated tests

**✅ Actual Outcome**

No errors were found when running the automated tests


</details>

<hr>

</details>

**Comment by kirby0025** [comment]
Just as a guide for people getting here from searching as this can be a little hard to piece it together : 
* A quick way to identify if you are probably affected by this issue is to run the command from this reply https://github.com/kubernetes/kubernetes/issues/87231#issuecomment-575177656 . It will give you something like this : 
```
kubectl get crd.v1.apiextensions.k8s.io -o yaml | kubectl create -f - 2>&1 | grep -v AlreadyExists

Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-kubernetes-preserve-unknown-fields to true in spec.versions[*].schema instead]
```
* Run "kubectl edit crd <each CRD you have in error>" (I had 61 to correct) and follow the instructions in this reply : https://github.com/rancher/rancher/issues/46213#issuecomment-2263423523 which are :

1. Remove "preserveUnknownFields" line.
2. Add this block if it's not already there in the version subsection :

```    
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```
