### ISSUE TITLE
Adding resources requests and limits to the pods panel

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4622]
Rancher Version:
1.0.1
Docker Version:
1.10.1

There is no way to check for the resource requests and limits specified in the Pod specs, for example:

```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
```

The panel doesn't show the amount of RAM or CPU this pod requested, also when the request exceed the Node's limit, the panel doesn't show any helpful message and it show only that the status is Pending however the `kubectl describe pods/frontend` shows the following:

```
Name:       frontend
Namespace:  default
Node:       /
Labels:     <none>
Status:     Pending
IP:     
Controllers:    <none>
Containers:
  db:
    Image:  mysql
    Port:   
    QoS Tier:
      memory:   Burstable
      cpu:  Burstable
    Limits:
      cpu:  500m
      memory:   2Gi
    Requests:
      memory:   1Gi
      cpu:  250m
    Environment Variables:
  wp:
    Image:  wordpress
    Port:   
    QoS Tier:
      cpu:  Burstable
      memory:   Burstable
    Limits:
      cpu:  500m
      memory:   2Gi
    Requests:
      cpu:  250m
      memory:   1Gi
    Environment Variables:
No volumes.
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        ReasonMessage
  --------- --------    -----   ----            -------------   --------    -------------
  3m        16s     15  {default-scheduler }            Warning     FailedScheduling    pod (frontend) failed to fit in any node
fit failure on node (node-02): Node didn't have enough resource: Memory, requested: 2147483648, used: 0, capacity: 2099134464
```
