### ISSUE TITLE
[BUG] Backing role in local cluster is not deleted upon deleting corresponding cluster roletemplate

### ISSUE THREAD

**Issue by joesims22** [rancher/rancher#46235]
**Rancher Server Setup**
- Rancher version: v2.8.5 / v2.9-head
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: v1.30.2+k3s2
- Cluster Type (Local/Downstream): node provisioned downstream k3s

**Describe the bug**
When deleting a cluster roletemplate the backing role in the local cluster is not deleted. 

<details open>
  <summary>clusterRT.yaml</summary>
  
```
apiVersion: management.cattle.io/v3
builtin: false
clusterCreatorDefault: false
context: cluster
description: test
displayName: rt-testcluster
external: false
hidden: false
kind: RoleTemplate
locked: false
metadata:
  name: rt-testcluster
projectCreatorDefault: false
roleTemplateNames: []
rules:
- apiGroups:  # not included in clusterManagementPlaneResources
  - "apps"
  resources:
  - 'deployments'
  verbs:
  - 'create'
  - 'get'
- apiGroups:  # included in clusterManagementPlaneResources
  - "management.cattle.io"
  resources:
  - "clusterscans"
  verbs:
  - 'get'
``` 
</details>

**To Reproduce**
1. Deploy Rancher on `v2.8.5` or `v2.9-head`
2. Create a downstream rke2/k3s cluster
3. Create a cluster roletemplate using yaml provided above
4. Create a user and add them to a cluster/project with the role created in previous step
5. Verify the backing role is created in the local cluster
6. Delete the cluster roletemplate
7. Observe the backing role is still present in the local cluster 
**Expected Result**
Since this backing role is created when we create the roletemplate then as a user I would expect it's deleted when we delete the roletemplate.
