### ISSUE TITLE
[BUG]: Admin user: UserAttributes cleanup is not happening properly after disabling Auth

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#46252]
**Rancher Server Setup**
- Rancher version: v2.9-head & v2.8.2

**Information about the Cluster**

**User Information**
- Auth provider (okat/ azure, etc)

**Describe the bug**
After disabling the Auth, the principalID is not cleaned up properly on UserAttributes. Auth related principalID and UserName are still present after Auth disablement. 

**To Reproduce**
1. Provision rancher v2.9-head / v2.8.2
2. Connect to Azure/ okta app
3. Check for the user attributes for the admin user `kubectl describe userattributes user-abc`
4. Disable the Auth
5. Check for the user attributes for the admin user `kubectl describe userattributes user-abc`

**Result**
1. User attributes(Principalid & UserName) related to the connected auth are not deleted for the admin user
2. All the other Auth users userattributes are deleted after the disable
3. Logs did not printed for admin user clean up

**Expected Result**
1. As soon as the the rancher disable the Auth, the userattributes should clean up properly, no information related to Auth should exist in userAttributes & Logs should reflect the same

**Screenshots**

**Additional context**

1. This is happening on v2.9-head and v2.82
2. Not a new issues, existing issue
3. Fetch userattributes output as below after disable the Auth :

```
kubectl describe userattributes user-abc
Name:         user-abc
Namespace:
Labels:       cattle.io/creator=norman
Annotations:  <none>
Extra By Provider:
  Azuread:
    Principalid:
      azuread_user://aaaaaaaaaaaaaaaaaa
    Username:
      testuser1@aaaaaa.onmicrosoft.com
  Local:
    Principalid:
      local://user-abc
    Username:
      admin
  Okta:
    Principalid:
      okta_user://test@okta.com
    Username:
     test@okta.com
Group Principals:
  Activedirectory:
    Items:  <nil>
  Adfs:
    Items:  <nil>
```
