### ISSUE TITLE
Add a timeout when waiting for cache sync to complete

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#46267]
# Context

During startup, Rancher starts many controllers - some are always registered, some are only registered once the Rancher pod becomes leader. When registered within [StartWithTransaction](https://github.com/rancher/rancher/blob/2ee1647393c5354d40b4369e9b5464d5fce9cc1b/pkg/wrangler/context.go#L179-L194), controllers follow this process:

1. The callback function is run (which essentially register caches); controllers (handlers) are NOT registered yet
2. Caches are started (List+Watch with informer/reflector)
3. We block until ALL registered caches have successfully synced with kube-apiserver.
4. Controllers (handlers) are registered & start processing

# Issue

If some caches never finish syncing (eg: CRD not being served by the apiserver), Rancher will be blocked, possibly forever, and controllers won't start. There will be no obvious log message to notify the user about this problem. This makes it very difficult to troubleshoot these kind of failures.

# Discussed solution

We'll add a big timeout (5-10 minutes) on the `context.Context` passed to [WaitForCacheSync](https://github.com/rancher/rancher/blob/2ee1647393c5354d40b4369e9b5464d5fce9cc1b/pkg/wrangler/context.go#L191). This will prevent blocking forever. 

Once the call returns, we'll verify that all caches have finished syncing (WaitForCacheSync returns a `map[schema.GroupVersionKind]bool`, where the `bool` is whether the cache has synced). We can then log an error message for all caches that haven't synced. We can also check for "known" problems at that time, for example verifying that the CRD exist and verifying that it is served by kube-apiserver.

The timeout will be configurable through an environment variable, in case it needs to be upped for a very big cluster. Ideally though users wouldn't need to change it.

**Comment by joshmeranda** [comment]
# QA Template

1. Before installing rancher onto your k8s cluster, run the following command:

```
kubectl apply -f -<<EOF
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authconfigs.management.cattle.io
spec:
  conversion:
    strategy: None
  group: management.cattle.io
  names:
    kind: AuthConfig
    listKind: AuthConfigList
    plural: authconfigs
    singular: authconfig
  scope: Cluster
  versions:
    - name: v3
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: false
      storage: true
EOF
```

1. Install rancher via helm with the `--set cacheSyncTimeout=30s` (not necessary but will shorten how long you will need to wait to see the expected changes)
2. After some time you should see an error like below:
```
2025/09/03 20:34:31 [ERROR] found issues for gvk 'management.cattle.io/v3, Kind=AuthConfig': failed to get crd for gvk: customresourcedefinitions.apiextensions.k8s.io "AuthConfig.management.cattle.io" not found
```
