### ISSUE TITLE
[BUG] ClusterRoleBinding in Imported Cluster Registraton Manifest erroneously define the `metadata.namespace`

### ISSUE THREAD

**Issue by VltraHeaven** [rancher/rancher#46305]
**Rancher Server Setup**
- Rancher version: v2.8.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.27.11
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.27.11 
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**

I'm working on writing some Terraform that creates and imports a downstream cluster and just noticed the registration manifest being generated has an issue. The cattle-admin-binding ClusterRoleBinding manifest defines a namespace at metadata.namespace where it shouldn't:

``` 
      ---
        
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: cattle-admin-binding
          namespace: cattle-system
          labels:
            cattle.io/creator: "norman"
        subjects:
        - kind: ServiceAccount
          name: cattle
          namespace: cattle-system
        roleRef:
          kind: ClusterRole
          name: cattle-admin
          apiGroup: rbac.authorization.k8s.io
        
        ---
```

 ClusterRoleBindings aren't a namespaced resource. Applying the manifest with kubectl apply seems to remove the namespace field, but this breaks the kubernetes_manifest Terraform resource when used to apply this manifest to the downstream cluster. 

Removing this line of code will alleviate the issue - https://github.com/rancher/rancher/blob/d566ccfd6aad22159282745ac2e6b2f1d06f47bd/pkg/systemtemplate/template.go#L51

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**
