### ISSUE TITLE
Kubernetes Jobs doesn't appear in UI

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4647]
Rancher Version:
v1.1.0-dev1-rc2
Docker Version:
1.10.3

Steps to Reproduce: 
Create a sample job in kubernetes using the following yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

kubectl create -f job.yml

The job is created successfully and pod is terminated as expected but there is no indication in Rancher UI that shows that the pod is a part of a job, however you can see that the pod created is a part of a job using kubectl:

```
$ kubectl describe jobs
Name:       pi
Namespace:  default
Image(s):   perl
Selector:   controller-uid=b8a69a88-10a4-11e6-983e-02dffdf7cbbc
Parallelism:    1
Completions:    1
Start Time: Mon, 02 May 2016 22:30:34 +0200
Labels:     controller-uid=b8a69a88-10a4-11e6-983e-02dffdf7cbbc,job-name=pi
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason          Message
  --------- --------    -----   ----            -------------   --------    ------          -------
  6m        6m      1   {job-controller }           Normal      SuccessfulCreate    Created pod: pi-48p5q
```
