### ISSUE TITLE
[BUG] Rancher 2.9.0 ExternalAuth ADFS to JumpCloud Generic SAML Assign Global Group to Role not working.

### ISSUE THREAD

**Issue by btaylor-ag** [rancher/rancher#46577]
**Rancher Server Setup**
- Rancher version: 2.9.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm on EKS.
- Proxy/Cert Details: valid 

**Information about the Cluster**
- Kubernetes version: v1.28.5-eks-5e0fdde
- Cluster Type (Local/Downstream): Hosted AWS EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Enabling ADFS from admin, and then trying to login with an SSO user.

**Describe the bug**
Rancher 2.9.0 ExternalAuth ADFS to JumpCloud Generic SAML Assign Global Group to Role not working.
I can login when adding users to groups assigned to the Generic SAML app in JumpCloud, SAML Tracer shows memberOf passing the group, but when I configure Global Roles to the JumpCloud group, users are still admin, and no seperate user is provisioned under Users & Authentication -> Users. The Admin user when looking at Related Resources, UserAttribute is constantly updated to be Default Admin. That is: no matter what ADFS SSO user I login as it's Default Admin.

```
ExtraByProvider:
  adfs:
    principalid:
      - adfs_user://
    username:
      - rancher.test-user
  local:
    principalid:
      - local://user-hctl5
    username:
      - admin
GroupPrincipals:
  activedirectory:
    Items: null
  adfs:
    Items:
      - displayName: engineering
        memberOf: true
        metadata:
          creationTimestamp: null
          name: adfs_group://engineering
        principalType: group
        provider: adfs
```

Found issues relating to groups not being supported in SAML?  Is this just the case? Is it on the roadmap for any level of support? 
https://github.com/rancher/rancher/issues/20175
https://github.com/rancher/rancher/issues/26309

**To Reproduce**
Using the Okta and Rancher JC App resulted in 403. 
https://ranchermanager.docs.rancher.com/v2.5/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/about-authentication/authentication-config/configure-okta-saml

**Result**

ADFS to JumpCloud Generic SAML: No Group Role Mapping, users are not JIT provisioned
Okta Provider to JumpCloud Rancher APP: 403 

**Expected Result**
Users to be associated with correct Group from JumpCloud to roles in Rancher.
