### ISSUE TITLE
[BUG] Etcd Restore Does Not Respect spec.answers on RKE1 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#46730]
**Rancher Server Setup**
- Rancher version: reported on 2.7.11, reproduced on v2.9-head 
- Installation option (Docker install/Helm Chart): any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.27.16-rancher1-1 
- Cluster Type (Local/Downstream): Downstream, node-driver/ custom 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

In the case of restoring the etcd backup to roll back the cluster's Kubernetes version, the value of `.spec.answers.values[rancherKubernetesEngineConfig.kubernetesVersion]` is not reset to the previous value, which makes it impossible to upgrade the cluster's k8s version anymore. 
A workaround exists though. 

**To Reproduce**

Notes: The steps are based on v2.7.11

1) Creaete RKE1 Template. set the default Kubernetes version is 1.27 and it is editable.
2) Create a custom Kubernetes 1.26 cluster with the RKE1 Template.
After the cluster was created, yaml showed the following value.

```
spec:
  answers:
    values:
      rancherKubernetesEngineConfig.kubernetesVersion: v1.26.15-rancher1-1
  questions:
    - default: v1.27.16-rancher1-1
      type: string
      variable: rancherKubernetesEngineConfig.kubernetesVersion 
```

3) Take a snapshot

4) Upgrade to 1.27.16
After the cluster was upgraded, yaml showed the following value.

```spec:
  answers:
    values:
      rancherKubernetesEngineConfig.kubernetesVersion: v1.27.16-rancher1-1
  questions:
    - default: v1.27.16-rancher1-1
      type: string
      variable: rancherKubernetesEngineConfig.kubernetesVersion 
```

5) Restore to v1.26 (From Rancher UI, "Cluster config, Kubernetes version and etcd")
Restored successfully, but `answers.values.rancherKubernetesEngineConfig.kubernetesVersion` is still v1.27.

```
spec:
  answers:
    values:
      rancherKubernetesEngineConfig.kubernetesVersion: v1.27.16-rancher1-1 <<== XXX
  questions:
    - default: v1.27.16-rancher1-1
      type: string
      variable: rancherKubernetesEngineConfig.kubernetesVersion 
```

6) Upgrade to 1.27.16

**Result**

NO upgrade runs.

**Expected Result**

The upgrading should be trigged and the cluster should be upgraded to 1.27.16 successfully 

**Screenshots**

**Additional context**

**Workaround:** 
7) Edit `spec.answers` and modified to `v1.26.15-rancher1-1`.
```
$ k edit clusters.management.cattle.io <cluster id>
spec:
  answers:
    values:
      rancherKubernetesEngineConfig.kubernetesVersion: v1.26.15-rancher1-1 
```

8) Upgrade to 1.27.16
Success fully upgraded to 1.27.16.

SURE-8847
