### ISSUE TITLE
disable-embedded-helm-controller doesn't seem to be working

### ISSUE THREAD

**Issue by vistasunil** [rancher/rancher#46764]
**Cluster Setup**
- Kubernetes version: 1.28
- Type of Cluster (RKE1, RKE2, k3s, EKS, GKE, AKS, OKE, etc): RKE2
- Installation option (Helm Chart / Custom Installation): Helm Chart
   - If Helm Chart, did you supply any non-default values? If so, what values did you supply:
   - If Custom Installation, how did you install it (kustomize, k8s manifest, etc.):
   
**Describe the bug**
We are installing Prometheus-federator chart and that install helm-project-operator along with it. Since we are using RKE2 cluster, there already exists a CRD Helm chart and project-operator tries to overrides that one. In the documentation we found that adding below will disable HelmChart CRD install and project-operator by enabling argument `--disable-embedded-helm-controller`:

```
  helmController:
    # Note: should be disabled for RKE2 clusters since they already run Helm Controller to manage internal Kubernetes components
    enabled: true
```

But doing so did not help either and we are still getting our RKE2 cluster messed up due to this. 

**To Reproduce**
Try installing prometheus-federator with above setting. It will still install helm-project-operator and override your HelmChart CRD in RKE2.

**Result**

**Expected Result**
When HelmController flag is disabled, it should not install helm-project-operator and HelmChart CRD on RKE2 clusters.

**Screenshots**

**Additional context**

**Comment by MKlimuszka** [comment]
It is under development, so it will be in an upcoming version barring any discovered disasters.

**Comment by mallardduck** [comment]
## Helpful context for QA efforts:

The CRDs related to this project (prometheus-federator) are:

- helmchartconfigs.helm.cattle.io - Provided via `helm-controller`
- helmcharts.helm.cattle.io - Provided via `helm-controller`
- helmreleases.helm.cattle.io - Provided via `helm-locker`
- projecthelmcharts.helm.cattle.io - Provided via `helm-project-operator`

Note that when a customer is on k3s/RKE2 the `helm-controller` is built-in and as such the CRDs for those should generally be managed by the cluster distro itself. There are flags for the controller that will skip CRDs which users could use with their Cluster setup and opt to have PromFed manage the CRDs. However that should likely be avoided in favor of disabling PromFed's management of CRDs.

---

New Values fields based on CRD management:
```yaml
# Configure how the operator will manage the CustomResourceDefinitions (CRDs) it needs to function.
crdManagement:
  # Enable or disable automatic updates of CRDs during startup.
  # When true, all CRDs will be udpated to the version the operator provides.
  # When false, only missing CRDs will be installed, and existing ones will not be updated.
  update: true
  # Specify whether the operator should detect K3s and RKE2 clusters and exclude `helm-controller` CRDs from management.
  # When true, `helm-controller` CRDs will not be managed by the operator in these environments, as K3s/RKE2 handle them internally.
  # When false, the operator will manage `helm-controller` CRDs regardless of the runtime environment.
  detectK3sRke2: false
```

In a following comment I will document a basic table of some option combinations and environments that could be good to QA test on. I will also include some basic expectations of results for each scenario I document in that table.

**Comment by pankajsqe** [comment]
Fix for this issue has been validated and working as expected. When HelmController flag is disabled, it is not installing helm-project-operator and HelmChart CRD on RKE2 clusters.

Details
Rancher : V2.11-head
PromFed : 105.1.0-rc.1+up0.4.5-rc.1
Cluster : v1.31.1+rke2r1

```
RKE2 Scenario 1
crdManagement:
   	 detectK3sRke2: false
    	 update: true
  helmController:
    	enabled: false
```
Result : The PromFed controller will create HelmChart resources with prometheus-federator set as managed by annotation.


```
RKE2 Scenario 2
 crdManagement:
   	 detectK3sRke2: false
    	 update: false
  helmController:
    	enabled: false   
```
Result : CRDs will only install if missing, user will need to take manual steps to update CRDs. Even helm-controller CRDs will be managed by PromFed.


```
RKE2 Scenario 3
 crdManagement:
   	 detectK3sRke2: true
    	 update: true
  helmController:
    	enabled: false
```
Result : CRDs will be fully managed. The k3s/rke2 detection feature will be enabled, which will skip management of CRDs from helm-controller


Before
<img width="1410" alt="Image" src="https://github.com/user-attachments/assets/e86a6365-3ded-44c7-a095-7890ef3268c4" />

After
<img width="1724" alt="Image" src="https://github.com/user-attachments/assets/df276400-1292-4e5c-b7ba-fcafface3b57" />
