### ISSUE TITLE
[BUG] Rancher-Logging v104.1.0+up4.8.0 breaks GELF Output!

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#46862]
**Rancher Server Setup**
- Rancher version: 2.9.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.11
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

We are using Rancher-Logging since the cluster exists with GrayLog GELF Output.
Now since v104.1.0+up4.8.0 the rancher-logging-root-fluentd-configcheck pod fails whit this error:
```
[error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="this plugin 'Fluent::GELFOutput' cannot handle arguments for <buffer ...> section"
```

**To Reproduce**

1. install Rancher-Logging
2. setup a output:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: graylog-prod-edm
  namespace: edm
spec:
  gelf:
    host: 172.27.130.101
    port: 12201
    protocol: tcp
    tls_options: {}
```
3. setup a flow:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: edm
  namespace: edm
spec:
  globalOutputRefs: []
  localOutputRefs:
    - graylog-prod-edm
```

**Result**
the rancher-logging-root-fluentd-configcheck pod fails whit this error:
```
[error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="this plugin 'Fluent::GELFOutput' cannot handle arguments for <buffer ...> section"
```

**Expected Result**

the rancher-logging-root-fluentd-configcheck pod should exit successfully like in the previous version v104.0.0+up4.4.0
