### ISSUE TITLE
[BUG] PrometheusRule is missing from the logging stack feature

### ISSUE THREAD

**Issue by pankajsqe** [rancher/rancher#46878]
**Rancher Server Setup**
- Rancher version: 2.9.X and above
- Installation option (Docker install/Helm Chart): Both

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
PrometheusRule is missing from the logging stack feature.
[RFE] Monitor the logging stack[#46591](https://github.com/rancher/rancher/issues/46591)”

Details
Rancher : v2.9-head
cluster : v1.30.2+k3s2
Monitoring : 105.0.0-rc1+up57.0.3
Logging : 105.0.0-rc1+up4.8.0

fluentd-alert.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: central-logging-alerts
  namespace: cattle-monitoring-system 
```

**To Reproduce**

- Install monitoring chart with loggingMonitors.fluentd  and loggingMonitors.fluentbit enabled.
- Install logging chart with metrics.serviceMonitor   enabled.
- Once it is successfully installed two grafana dashboard with be generated.
- However Prometheus rule under cattle-monitoring-system missing.

**Expected Result**
Prometheus  Rule should be present under cattle monitoring system.

**Additional context**
[Rancher-Central-Logging-FluentD-Grafana-Dashboard.json](https://github.com/user-attachments/files/16795005/Rancher-Central-Logging-FluentD-Grafana-Dashboard.json)
