### ISSUE TITLE
[RFE] Move bcrypt password hash off of the user object.

### ISSUE THREAD

**Issue by vtrenton** [rancher/rancher#46946]
Native Kubernetes patterns typically facilitate the control of sensative infromation such as password hashes to secrets. Using the secret pattern also allows users to leverage gitops patterns for changing and setting user passwords. This request is to ask to move the user password (for local user accounts) off of the `users.management.cattle.io` object and instead rely on a referenced secret.

## **example**

```
apiVersion: management.cattle.io/v3
description: ""
displayName: Default Admin
kind: User
metadata:
    name: user-admin
    uid: 111111
password: PASSWORD HASH IS HERE!!!!
principalIds:
  - local://user-admin
```

Instead it would be a lot safer to create a  secret that the Users Object can reference like this:

```
apiVersion: management.cattle.io/v3
description: ""
displayName: Default Admin
kind: User
metadata:
    name: user-admin
    uid: 111111
password-secret:
    name: creds-local-admin
    key: userhash
principalIds:
  - local://user-admin
  ---
apiVersion: v1 
kind: Secret
metadata:
  name: creds-local-admin
  namespace: cattle-system
type: Opaque
data:
  userhash: SSdtIGZhciB0b28gbGF6eSB0byBoYXNoIHRoaXMgLSBidXQgdGhpcyB3b3VsZCBiZSBiY3J5cHQg
b2YgeW91ciB1c2VyIHBhc3N3b3JkCg==
 ```
 
 Using this method will put us in line with kubernetes best practices: https://kubernetes.io/docs/concepts/security/secrets-good-practices/ and better protect users from potential privelege escallation attacks (if applicable)
