### ISSUE TITLE
Start the extension API server when `imperative-api-extension` is enabled

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#47035]
# Context

**Parent issue:** https://github.com/rancher/rancher/issues/47010

As part of the Imperative API, we want to be able to use Rancher as an extension API server. This requires Rancher to implement specific HTTP handlers and point kube-apiserver to it.

# Summary

In rancher/rancher, add the new feature `imperative-api-extension` as defined by the RFC. This new feature will be off by default and will control whether kube-apiserver must reach Rancher for custom resources (eg: `ext.cattle.io`).

When the feature is on, Rancher must:
1. Start a new HTTPS server with dynamiclistener. The CA cert will be used later. The handler will be Steve's extension API server handler but not at `/ext`, instead directly at `/`. The listening address should be `0.0.0.0:6666`. There should be an authentication middleware that validates the request is coming from kube-apiserver (see POC).

2. Create a Service `imperative-api-extension` that points to Rancher's port `6666` and must create the following APIservice:

```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.ext.cattle.io
spec:
  group: ext.cattle.io
  groupPriorityMinimum: 100
  caBundle: <CA_BUNDLE>
  service:
    name: imperative-api-extension
    namespace: cattle-system
    port: 6666
  version: v1
  versionPriority: 100
```

The `CA_BUNDLE` must be the CA cert from dynamiclistener. This will make kube-apiserver trusts our extension API server.

When the feature is off, we should not be listening on port 6666 and we should clean up the `Service` / `APIService` resources.

**Note:** This is a temporary step to get going, another issue will change where this service points to.

**Comment by brudnak** [comment]
moved to `Reopened` awaiting QA template - Please move into `To Test` once added, thanks!

**Comment by tomleb** [comment]
## QA Testing

Note, testing the following depends on RDP to be included (for better test coverage). This means https://github.com/rancher/rancher/pull/49182/ must be merged.

### Root cause

N/A

### What was fixed, or what changes have occurred

We're adding a new feature `imperative-api-extension` that will be off by default.

When turned on:
- A new HTTPS server is started listening on port `localhost:6666`
- This server should be reachable by Kubernetes either directly (when `IMPERATIVE_API_DIRECT=true`) or indirectly otherwise.
- RemoteDialerProxy is deployed when `IMPERATIVE_API_DIRECT` is not set to true. This happens when Rancher is started either with the binary or with docker directly. When deploying Rancher with `helm`, then RemoteDialer is not deployed.
- A APIService for ext.cattle.io should be deployed. (We're still deploying one even though we don't have any store.. It's fine..)


### Areas or cases that should be tested

### What areas could experience regressions?

Rancher startup sequence when the feature is on, both with or without `IMPERATIVE_API_DIRECT=true`. This is because we're adding new CustomResources to Kubernetes, which may or may not be available right away based (especially true if we're waiting for RDP to be deployed).

### Steps


#### Feature is off

- Test that Rancher doesn't listen on `localhost:6666`. 
- When `IMPERATIVE_API_DIRECT` is true, verify that RemoteDialerProxy is not deployed. (`kubectl -n cattle-system get deployments api-extension` returns not found)
- `kubectl get apiservice v1.ext.cattle.io` returns not found in both cases
- Still able to access `https://<rancher url>/ext/apis` (make sure you set a valid rancher token in `Authorization: Bearer <token>` header. This should give you a 200.

#### Feature is on

- Test that Rancher listens on `localhost:6666`
- When `IMPERATIVE_API_DIRECT` is not true:
  - verify that the service `api-extension` in `cattle-system` points to the deployments `api-extension` in `cattle-system`
  - verify that RemoteDialerProxy is deployed. (`kubectl -n cattle-system get deployments api-extension` returns something)
-  When `IMPERATIVE_API_DIRECT` is true:
  - verify that the service `api-extension` in `cattle-system` points to Rancher
  - verify that RemoteDialerProxy is not deployed. (`kubectl -n cattle-system get deployments api-extension` returns not found)
- `kubectl get apiservice v1.ext.cattle.io` returns something in both cases (unfortunately, due to having no store, we expect the apiservice to have a status like so (404):
```
status:
  conditions:
  - lastTransitionTime: "2025-02-24T19:26:45Z"
    message: 'failing or missing response from https://10.42.0.53:6666/apis/ext.cattle.io/v1:
      bad status from https://10.42.0.53:6666/apis/ext.cattle.io/v1: 404'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```
