### ISSUE TITLE
Port conflicts after scale web service

### ISSUE THREAD

**Issue by aisensiy** [rancher/rancher#4706]
In rancher UI I tried the wordpress stack and followed the document to leave an empty port for public port in order to get a random public port. But after I scaling the wordpress it use the generated port and still get a conflict. Why can't rancher to generate a random port for each scaled container with blank public port?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`Disabled`|
|Route|`authenticated.project.help`|

**Comment by deniseschannon** [comment]
Do you only have 1 host? All the containers in the same service will use the same random public port assigned. This is the design of how port mapping is used for services in Rancher.

**Comment by aisensiy** [comment]
Yes, I have only one host. And when I use `rancher-compose command tool` everything works well...

**Comment by deniseschannon** [comment]
Can you provide the docker-compose.yml file that you use with rancher-compose?

**Comment by aisensiy** [comment]
```
mywordpress:
  tty: true
  image: wordpress
  links:
    - database:mysql
  stdin_open: true
wordpresslb:
  ports:
    - 3080:80
  tty: true
  image: rancher/load-balancer-service
  links:
    - mywordpress:mywordpress
  stdin_open: true
database:
  environment:
    MYSQL_ROOT_PASSWORD: pass1
  tty: true
  image: mysql
  stdin_open: true
```

It is an example in docs.
