### ISSUE TITLE
Use RemoteDialerProxy for extension API server in Rancher

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#47091]
# Context

**Parent issue:** https://github.com/rancher/rancher/issues/47010

As part of the Imperative API, when the extension API server is enabled, kube-apiserver needs to be able to communicate with Rancher's extension API server. This is configured through an [APIService object](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/api-service-v1/) which points to a `Service` which itself then points to `Pods`.

Rancher does not always run as Pods and instead sometimes runs as a Docker container (eg: for testing puposes) or even as a binary (for development). We want to make the extension API server work in those cases as well.

# Summary

In https://github.com/rancher/rancher/issues/47037, we created a RDP server and client. In https://github.com/rancher/rancher/issues/49003, we're pusing the RDP server container image to a registry.

It is time to integrate the RDP with Rancher.

For this, we need three things:
1. Add the environment variable `IMPERATIVE_API_DIRECT` in the `Deployment` manifest of Rancher. 
2. Create a new charts and deploy it on startup
3. Start the proxy client

# `IMPERATIVE_API_DIRECT` environment variable

This will be hardcoded to `true` in the deployment manifest so we can determine whether Rancher is deployed with Helm or not. When this is true, Rancher will NOT deploy RDP but instead it will just create the apiservice (and other resources). When this is false, it will deploy the RDP.

# Create the charts and deploy it on startup

Rancher must deploy these additional resources when extension API server is enabled. (Only the leader should attempt deploying the resources).

**Deployment**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-extension
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-extension
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-extension
    spec:
      containers:
      - image: <RDP image>
        name: api-extension
        ports:
        - containerPort: 5555
          protocol: TCP
        - containerPort: 6666
          protocol: TCP
        env:
        - name: CERT_CA_NAME
          value: "api-extension-ca"
        - name: CERT_CA_NAMESPACE
          value: "cattle-system"
        - name: SECRET
          value: "api-extension"
        - name: HTTPS_PORT
          value: "5555"
        - name: PROXY_PORT
          value: "6666"
        - name: PEER_PORT
          value: "6666"
      serviceAccountName: api-extension

```

**ServiceAccount**

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-extension
  namespace: cattle-system
```

**Role**

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-extension
  namespace: cattle-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["api-extension"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["api-extension-ca"]
  verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
```

**RoleBinding**

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-extension
  namespace: cattle-system
subjects:
  - kind: ServiceAccount
    name: api-extension
    namespace: cattle-system
roleRef:
  kind: Role
  name: api-extension
  apiGroup: rbac.authorization.k8s.io
```

The Service `api-extension` should be updated to point to RDP's `6666` port instead of directly to Rancher.

Rancher must generate a random secret and store it in the `Secret` named `api-extension`. This secret will be used to authenticate with the RDP.

Once the charts is in rancher/charts, we can deploy it by adding a chart definition here: https://github.com/rancher/rancher/blob/37b99eef43096c288c498f431155c331cd9eaaa7/pkg/controllers/dashboard/systemcharts/controller.go#L154. Simply follow how it's done for webhook and that should work.

Make sure to only deploy RDP on the local cluster and not downstream. This probably means having some kind of check in the Enabled() func, something like:

```go                                                                                                                                                                                                                           
          if features.MCMAgent.Enabled() {
                 // In downstream, don't deploy RDP                                         
                  return false                                          
          } 
```

# Start the proxy client

The client built in https://github.com/rancher/rancher/issues/47037 must be started.
