### ISSUE TITLE
Reduce `webhook`'s dependency on RKE1 type changes

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47200]
**Is your feature request related to a problem? Please describe.**
This issue is a remediation to the root cause of https://github.com/rancher/rancher/issues/44980
The TLDR of that issue is if new fields are added to RKE1 and reference to `github.com/rancher/rke/types` or `http://github.com/rancher/rancher/pkg/apis` is not updated in https://github.com/rancher/webhook 's `go.mod`, any values populated in these fields are dropped. This happens because webhook mutators that act on `cluster.management.cattle.io/v3` resources generate Patch request that includes dropping these unknown fields (e.g. https://github.com/rancher/webhook/blob/f98e238f5ba59fba0603eb3c0b3d6d7dc1a4cb3d/pkg/resources/management.cattle.io/v3/cluster/mutator.go#L54). The root cause of that is the fact that we first unmarshal Cluster object from `request.Object.Raw` JSON and in case the Cluster type is not up to date, these new fields are then missing. We then proceed to determine if any mutations are needed for the Cluster object; however, the patch is generated by comparing `request.Object.Raw` with re-marshaled Cluster object which generates instructions to drop values from these newly introduced fields (e.g. see https://github.com/rancher/webhook/blob/6b74a9a9006ccb27e74146a91899a02dd03a7d3b/pkg/resources/management.cattle.io/v3/cluster/mutator.go#L97)

While there is no issue to update `github.com/rancher/rke/types`, because we generally don't want to have non-release versions referenced in `go.mod`, it creates dependency for our release process where RKE1 must be released first to have release tag, then update webhook's `go.mod` before it can be released.

**Describe the solution you'd like**
To make webhook more resilient to Cluster type changes, it's proposed to update implementation of any webhook mutators that generate Patch for `cluster.management.cattle.io/v3` object to calculate it based on re-marshaled Cluster object (created immediately after it was marshaled from `request.Object.Raw`) instead of `request.Object.Raw` JSON. This way instructions to drop values of any unknown fields are not generated.
This way we can keep reference for `github.com/rancher/rke/types` to point to (potentially old) released (non-RC) RKE1 tag without having to update it (unless newly introduced fields are in fact needed in webhook's logic - which is very unlikely).

**Describe alternatives you've considered**
The alternative (and likely more correct) way of addressing this issue is to split off Rancher type definitions in its own repo that can be released independently so webhook release then depends on having types released (which can and should be done before RKE1 and Rancher release). This is tracked as SURE-8422.

**Additional context**
Please note it will be hard to validate this fix until new fields are actually introduced and webhook's type references are NOT updated therefore setting this as `QA/RunRegression` label.

**Comment by Josh-Diamond** [comment]
Ticket #47200 - Test Results - ❌ 
---

Verified on Rancher `v2.10-8decbf6fd040b5b2168430f1e72ccc484d59b6e0-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Set unknown cluster field in RKE1 custom cluster and ensure field is accurately set | ❌ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.10-head`
2. Create a downstream RKE1 custom cluster object w/ the following set for Network configurations in the cluster yaml:
```yaml
  network:
    aci_network_provider:
      toleration_seconds: '111'
      opflex_agent_reset_wait_delay: 'test'
    plugin: aci
```
3. Save cluster, no need to register nodes, and verify `opflex_agent_reset_wait_delay: 'test'` persists in YAML
4. Veri-FAILED: custom field was removed from YAML network configurations:
```yaml
    network:
      aciNetworkProvider:
        apicRefreshTime: '1200'
        tolerationSeconds: '111'
      plugin: aci
```

**Comment by Josh-Diamond** [comment]
Ticket #47200 - Test Results - ✅ 
---

Verified on Rancher `v2.10-6e85a811efd6b831c3d49a7336a6d4b3e96c1a93-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Set unknown cluster field in RKE1 custom cluster and ensure field is accurately set | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.10-head`
2. Create a downstream RKE1 custom cluster object w/ the following set for Network configurations in the cluster yaml:
```yaml
  network:
    aci_network_provider:
      toleration_seconds: '111'
      opflex_agent_reset_wait_delay: 'test'
    plugin: aci
```
3. Save cluster, no need to register nodes, and verify `opflex_agent_reset_wait_delay: 'test'` persists in YAML
4. Verified: custom field persists in YAML network configurations, as expected:
```yaml
    network:
      aciNetworkProvider:
        apicRefreshTime: '1200'
        opflexAgentResetWaitDelay: test
        tolerationSeconds: '111'
```
