### ISSUE TITLE
[Backport v2.9] Reduce `webhook`'s dependency on RKE1 type changes

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47201]
Backport of https://github.com/rancher/rancher/issues/47200 to v2.9.x line of releases (webhook v0.5.x)

**Comment by kinarashah** [comment]
Following fields were added with ACI 6.1.1.1, which are present in Rancher v2.9-head (via RKE `v1.6.3-rc.2`) but are not present in webhook `104.0.3+up0.5.3-rc.1` (webhook uses RKE `v1.6.2`) 
```
EnableHppDirect                      string              `yaml:"enable_hpp_direct,omitempty" json:"enableHppDirect,omitempty"`
OpflexAgentResetWaitDelay            string              `yaml:"opflex_agent_reset_wait_delay,omitempty" json:"opflexAgentResetWaitDelay,omitempty"`
```

**Steps to test:** 
- Create RKE1 custom cluster
- Under Edit as Yaml replace the network section with
```
  network:
    aci_network_provider:
      toleration_seconds: '111'
      opflex_agent_reset_wait_delay: 'test'
    plugin: aci
```
- Save the cluster, no need to actually add nodes
- Field `opflex_agent_reset_wait_delay` should not disappear from the config

**Comment by Josh-Diamond** [comment]
Ticket #47201 - Test Results - ✅ 
---

Verified on Rancher `v2.9.3-alpha7`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Set unknown cluster field in RKE1 custom cluster and ensure field is accurately set | ✅  |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9.3-alpha7`
2. Create a downstream RKE1 custom cluster object w/ the following set for Network configurations in the cluster yaml:
```yaml
  network:
    aci_network_provider:
      toleration_seconds: '111'
      opflex_agent_reset_wait_delay: 'test'
    plugin: aci
```
3. Save cluster, no need to register nodes, and verify `opflex_agent_reset_wait_delay: 'test'` persists in YAML
4. Verified: custom field persists in YAML network configurations, as expected:
```yaml
    network:
      aciNetworkProvider:
        apicRefreshTime: '1200'
        opflexAgentResetWaitDelay: test
        tolerationSeconds: '111'
      plugin: aci
```
