### ISSUE TITLE
[BUG] Missing Permissions not logged when creating NS without managed-namespaces

### ISSUE THREAD

**Issue by inichols** [rancher/rancher#47585]
**Rancher Server Setup**
- Rancher version: 2.8.5
- Installation option (Docker install/Helm Chart): Helm/RKE2
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28.11
- Cluster Type (Local/Downstream): Local or Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Custom role to replicate
```
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
  - updatepsa
  ```
**Describe the bug**

**To Reproduce**
Create a Namespace within a Project either via UI or create it via kubectl

**Result**
`admission webhook "rancher.cattle.io.namespaces.create-non-kubesystem" denied the request: Unauthorized`
**Expected Result**

I would expect something along the lines of what is documented here: https://github.com/rancher/webhook/issues/272. I would like the error to say what permissions were missing for the user to be able to create the namespace.

**Comment by crobby** [comment]
I see the same results against v2.8.5.  @inichols are there any other details you can provide that may help me reproduce this issue?

**Comment by crobby** [comment]
> I see I missed clarifying that this was a custom Cluster Role and not Project role.
> 
> So this is a custom Cluster Role not a Project role. So its the idea that this user is a limited cluster admin that is just there to make namespaces for any project. If using the same rules for a Project role it works.

Ah, thank you for the clarification!

**Comment by brudnak** [comment]
Verified: on `v2.11.0-rc7`
Webhook: `rancher/rancher-webhook:v0.7.0-rc.10`

```yaml
apiVersion: management.cattle.io/v3
kind: RoleTemplate
metadata:
  name: insufficient-namespace-creator
  labels:
    cattle.io/creator: "norman"
displayName: Insufficient Namespace Creator
description: "Role that will trigger the permission error when trying to create namespaces"
context: cluster
builtin: false
external: false
hidden: false
locked: false
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - management.cattle.io
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
      - updatepsa
```

Error msg:
```log
admission webhook "rancher.cattle.io.namespaces.create-non-kubesystem" denied the request: User "u-d5z9n" does not have permission "manage-namespaces" on project "p-gcgcn"
```

1. Create user with `User-Base` permission
2. Use the above yaml file to create a role template
3. Assign the test user with `User-Base` the role template `insufficient-namespace-creator` on a downstream cluster
4. Login as that user, attempt to create a namespace, and get the updated error messsage
