### ISSUE TITLE
[1.x.x] Using rancher/load-balancer-service locally with compose

### ISSUE THREAD

**Issue by andrewmclagan** [rancher/rancher#4760]
We would like to use the same docker-compose files for local development as we do for remote environments with Rancher AKA staging and production.

Both staging and production are extended via the rancher-compose file. 

Therefore it would make sense to be able to use the `rancher/load-balancer-service` HAProxy load balancer locally as well. Currently it seems that his is not possible as its some kind of "special" Rancher service. Is my assumption correct? 

**thanks!**
(congrats on the recent round 2 funding!)

---------

For the present we are using the extends feature of docker compose and using the `dockercloud/haproxy` image as such:

docker-compose -f docker-compose.yml -f docker-compose-development.yml up -d

And extending our load-balancer service to use this image for development. Not optimal but it works..

**Comment by vincent99** [comment]
The "real" image is `rancher/agent-instance`, but it is just vanilla Ubuntu with haproxy (and some other stuff) installed.  The `rancher/server` manages the balancer instances by pushing the config into it, so when running just docker locally there is no server and therefore nothing to configure them.

I haven't tried this lately but I think you can do this because docker-compose doesn't care about rancher-compose.yml and rancher-compose internally merges the 2 files together into one map:

```bash
#docker-compose.yml
lb:
  image: dockercloud/haproxy
  ...
```

```bash
#rancher-compose.yml
lb:
  image: rancher/load-balancer-service
  scale: 3
  ...
```

**Comment by andrewmclagan** [comment]
yeah +1 that was the solution i ended up going for.

**Comment by cnadeau** [comment]
@vincent99 

dockercloud/haproxy has FORCE_SSL, VIRTUAL_HOST and VIRTUAL_HOST_WEIGHT en var which helps a lot to force ssl endpoint and route traffic as follow using wildcards:

```yaml
# docker-compose.yml

# routes all non specific traffic to web1 service
web1:
  ...
  environment:
    VIRTUAL_HOST: '*, https://*'
    FORCE_SSL: 'true'

# routes all specific traffic to web2 service 
# (higher priority than web1 which is a fallback service)
web2:
  ...
  environment:
    VIRTUAL_HOST: '*/specific/*, https://*/specific/*'
    VIRTUAL_HOST_WEIGHT: 10
    FORCE_SSL: 'true'
```

Is this possible to configure it as easily with rancher-compose?

I've found [1.0 doc regarding labels](https://docs.rancher.com/rancher/v1.0/en/labels/ ) and [syntax for those labels](https://docs.rancher.com/rancher/v1.0/en/rancher-compose/rancher-services/#syntax-of-the-combination-of-all-optional-fields)

I ended up creating a rancher-compose.yml with something similar to 

```yaml
lb:
    image: rancher/load-balancer-service
    lb_config:
      certs: []
     # manual HAProxy configuration to redirect
     # from : https://github.com/rancher/rancher/issues/3505
      config: |-
           frontend 80
            redirect scheme https code 302 if  !lepath !{ ssl_fc }
      port_rules:
      # all https traffic to /specific to web2 service (I'm not sure that this routes /specific/*)
      - path: /specific
        priority: 1
        protocol: https
        service: web2
        source_port: 443
        target_port: 3000
     # all https traffic to web1 service
      - priority: 2
        protocol: https
        service: web1
        source_port: 443
        target_port: 3000
```
But I'm not even sure the /specific also targets /specific/* and I can't find any doc on that.

I would really like a single way of configuring local and staging/prod load balancer to be able to get the exact same behaviour locally and remotely.

Any advice?

Thank you very much for your time!
