### ISSUE TITLE
Cleanup via script: clusterrole has to few permissions

### ISSUE THREAD

**Issue by BBQigniter** [rancher/rancher#47683]
As documented here https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes#removing-rancher-components-from-registered-clusters I tried to cleanup a generic imported cluster manually via script. But there are some permissions missing in:

https://github.com/rancher/rancher/blob/bd75b096ba9e9736c82faadd7f08a4c73f6cdd2a/cleanup/user-cluster.yml#L62-L95

instead it should be:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cattle-cleanup-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - get
  - delete
- apiGroups:
  - ""
  resourceNames:
  - rancher
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - rancher.cattle.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - delete
```

Deleting an imported generic cluster via UI works but some cleanup-related stuff keeps to stick around (like for example `clusterrole cattle-cleanup-....`)
