### ISSUE TITLE
Log driver is not being set correctly on the container, but is set correctly in API using rancher-compose 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4773]
**Rancher Version:** v1.1.0-dev1

**OS and where are the hosts located? (cloud, bare metal, etc):** , Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** : Cattle

**Steps to Reproduce:**
1. Create a stack and service using rancher compose. Provide a log_driver setting as syslog.
```
test3:
  log_driver: syslog
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  cpu_shares: 256
  privileged: true
  stdin_open: true
  mem_limit: 104857600
```

**Results:** 
The api sets the logConfig correctly as 
```
logConfig": {
"driver": "syslog",
}
```
But the docker inspect on the container shows 
```            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },```

**Comment by deniseschannon** [comment]
After speaking with @joshwget, this is not a rancher-compose issue as rancher-compose is passing in the correct log configuration to Rancher.

**Comment by deniseschannon** [comment]
Verified with master and v0.8.4-rc2 of rancher-compose

```
test:
  tty: true
  stdin_open: true
  image: ubuntu:14.04.3
  log_driver: syslog
```

Inspect container

```
 "LogConfig": {
                "Type": "syslog",
                "Config": {
                    "max-file": "2",
                    "max-size": "25m"
                }
            },
```
