### ISSUE TITLE
[BUG] Azure cloud provider config fails to apply on RKE2 cluster.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#47824]
**Rancher Server Setup**
- Rancher version: v2.10-head
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.31.1+rke2r1
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
While provisioning the RKE2 cluster with External cloud provider enabled, the cloud provider config doesn't get applied on cluster.

**To Reproduce**
1. Create a rancher server v2.10-head
2. Follow the steps to create an RKE2 Azure node driver cluster with external cloud provider enabled.
    -   Follow these [steps](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure#using-the-out-of-tree-azure-cloud-provider).
3. Click on create to submit the form and create cluster.

**Result**
Cluster fails to provision successfully, cluster shows: `waiting for cluster agent to connect`

**Expected Result**
Cluster provisions successfully.

**Screenshots**
![Screenshot from 2024-10-31 10-40-09](https://github.com/user-attachments/assets/c78c35b2-e51e-49fe-bfde-02979d613d0e)

**Additional context**
The issue was observed during functional checks for k8s [v1.31 support](https://github.com/rancher/rancher/issues/46197) testing.

**Comment by kinarashah** [comment]
@vivek-shilimkar Moving the issue to test, please refer to the linked docs PR to set the manifest for cloud controller manager.

**Comment by kinarashah** [comment]
@vivek-shilimkar Also use the following toleration if using node with both etcd and control plane role. Default docs have tolerations only for control plane node. 

```
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          value: 'true'
        - effect: NoSchedule
          key: node-role.kubernetes.io/etcd
          value: 'true'             
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: 'true'
```
