### ISSUE TITLE
Named volume creation through rancher-compose CLI is broken

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4786]
**Rancher Version:**V1.1.0-dev1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a stack and service using rancher compose CLI as below:
./rancher-compose -f dc5.yml -r rc5.yml -p newstack up -d

dc5.yml is as below:
```
st2:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  volumes:
  - abcvol:/home/soumya
```

rc5.yml  is as below

```
st2:
  scale: 3
```
**Results**
Named volume is not created. "docker volume ls" does not show the volume 'abcvol'

Also the docker inspect on a container shows the entire local directory path:
```
HostConfig": {
            "Binds": [
                "/Users/soumya/Downloads/rancher-compose-v0.8.0/abcvol:/home/soumya:rw"
            ],
```
