### ISSUE TITLE
[BUG] Issue installing Rancher when pre-populating bootstrap password secret

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47964]
**Rancher Server Setup**
- Rancher version: 2.9.x

This is to track: SURE-9210

**Describe the bug**
If a customer creates the secret which stores the Rancher admin bootstrap password manually. Either via kubectl, terraform, etc. Then when they go to install Rancher chart it will attempt to fetch this value to use it - however it currently incorrectly fetches the value resulting in the expected password not working.

**To Reproduce**

1. Create the `cattle-system` namespace,
2. Create the `bootstrap-secret` secret,
3. Observe the base64 value of the secret,
4. Install rancher via chart w/o setting bootstrap secret,
5. Observe that after Rancher starts the secret value changes.

**Result**
The starting admin PW is no longer matching the user provided input based on the secret they created.

**Expected Result**
If the secret already exists before Rancher chart installed, then Rancher will properly read the secret to use the user-input.

**Comment by mallardduck** [comment]
While I have created an initial PR attempt to fix this, much of that attempt was because I had already spent time familiarizing myself with the new code areas. So I wanted to leave myself stronger and more clear breadcrumbs to follow later than simple notes that will be obscured with the distance of time.

Currently the PR fixed the issue with the secret changing values. However still poses an issue with the actual password working or not to login.

**Comment by mallardduck** [comment]
Note for QA/testing:

To test a "failure" scenario - one where the user creates the secret incorrectly - you should expect to get a generated bootstrap password. It will show an error in the Rancher pod logs citing that the secret wasn't correctly structured.

Then it will gracefully fail and generate a random PW that the user can look up. They will still be able to login and use Rancher, just not with the Password they provided as the initial admin PW.

**Comment by pankajsqe** [comment]
I am still able to reproduce it. Below are the steps I followed to reproduce the issue:

**details**
rancher : v2.10-head
cluster : Rke2

**Steps to Reproduce:**
1.Create the cattle-system namespace.
2. Created a bootstrap-secret using below yaml.
```
secret.yaml
apiVersion: v1
data:
  bootstrapPassword: YnJlYWtpdHRvbWFrZWl0
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-jfvwj
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '-5'
    helm.sh/resource-policy: keep
  name: bootstrap-secret
  namespace: cattle-system
type: Opaque
```

![Image](https://github.com/user-attachments/assets/9b8e3667-1ec2-490e-98cd-1cef9af4c321)


3. Installed rancher without bootstrap password.
```
helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system \
  --set hostname=rancher.18.216.95.220.sslip.io \
  --set replicas=1 \
  --set global.cattle.psp.enabled=false \
  --set rancherImageTag=v2.10-head \
  --devel
```

![Image](https://github.com/user-attachments/assets/fc2d9995-bb53-430a-9c04-a62fa27e11f2)

4. Once it is successfully deployed. I tried to fetch the secret and I observed that bootstrap password got changed.
`kubectl get secret -n cattle-system bootstrap-secret -o yaml`
![Image](https://github.com/user-attachments/assets/51bc2e24-69ce-4ca9-9bbf-9460434284e1)



expected : Bootstrap password should  YnJlYWtpdHRvbWFrZWl0
actual : Bootstrap password should  NzJOdHo0N3NnbWRxCzQONG1qZ2hxbmhqZ2Q2ND1jNDU5Mmh2 am56N3dgemg 2N2N40Wdkdmc4

**Comment by pankajsqe** [comment]
Ticket has been verified and now bootstrap-secret password is same after deploying rancher.

details
rancher :v2.11-966420b3cc6c6efe8a862491da0a160bd8989828-head
cluster : Rke2

Steps to Reproduce:
1.Create the cattle-system namespace.
2. Created a bootstrap-secret using below yaml.

secret.yaml
```
apiVersion: v1
data:
  bootstrapPassword: YnJlYWtpdHRvbWFrZWl0
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-jfvwj
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '-5'
    helm.sh/resource-policy: keep
  name: bootstrap-secret
  namespace: cattle-system
type: Opaque
![Image](https://github.com/user-attachments/assets/4ac03c5f-c1de-478b-aaf0-bc419eb3e06d)
```


Installed rancher without bootstrap password.
`helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system   --set hostname=rancher.3.17.16.244.sslip.io   --set replicas=1   --set global.cattle.psp.enabled=false   --set rancherImageTag=v2.11-966420b3cc6c6efe8a862491da0a160bd8989828-head   --devel`
![Image](https://github.com/user-attachments/assets/5b72b77d-066f-4107-bbb7-2384bb976a05)



Once it is successfully deployed. I tried to fetch the secret and I observed that bootstrap password got changed.
`kubectl get secret -n cattle-system bootstrap-secret -o yaml`

![Image](https://github.com/user-attachments/assets/ecaaf2b7-3ce9-4b53-b6bb-04766ed6ae88)


expected : Bootstrap password should YnJlYWtpdHRvbWFrZWl0
actual : Bootstrap password should YnJlYWtpdHRvbWFrZWl0
