### ISSUE TITLE
[BUG] rancher-logging - unknown field "spec.security.seLinuxOptions"

### ISSUE THREAD

**Issue by Ijokoedih** [rancher/rancher#48049]
**Rancher Server Setup**
- Rancher version: 2.9.1

**Information about the Cluster**
- Kubernetes version: 1.30.X
- Cluster Type : Local - RKE2

**User Information**
Install the logging "cluster-tool" with the values : 
```
global:
  seLinux:
    enabled: true
additionalLoggingSources:
  rke2:
    enabled: true
```

**Describe the bug**
Helm is showing a warning message but the helm install is not failling : 
```W1113 14:56:07.665238   92315 warnings.go:70] unknown field "spec.security.seLinuxOptions"```
If SELinux is enabled on nodes, the fluentbit daemonset will fail access to /var/log/containers/*.log .

**To Reproduce**
See user information

**Result**
Fluentbit cannot read containers log.

**Expected Result**
Fluentbit shoult be able to read the containers logs

**Screenshots**

**Additional context**
