### ISSUE TITLE
[RFE] Adding a way to auto assign role templates by cluster name.

### ISSUE THREAD

**Issue by gasalomo-github** [rancher/rancher#48090]
**Describe the solution you'd like**
We are looking for a way to have rancher automatically assign role templates and groups to a cluster depending on the cluster name.
For example:
If a cluster is registered in rancher with "prod" in the name - the following assignments will take place:
dev group - custom read only dev cluster role template
infra group - custom read only infra cluster role template

But if it is registered with "dev" in the name then:
dev group - custom read/write role 
infra group - custom read only infra cluster role template
etc.

**Describe alternatives you've considered**

We considered automating the process during the cluster registration. 
But on occasion we need to create new roles.
In addition, it will be hard to keep assignment "rules" up to date and documented as it will be a part of the cluster creation pipeline which includes other services beside rancher.

**Comment by bigkevmcd** [comment]
@gasalomo-github Can you expand on what you think this might look like?

**Comment by gasalomo-github** [comment]
> @gasalomo-github Can you expand on what you think this might look like?

Something like clusterCreatorDefault in roletemplate, but with the ability to specify which clusters it would apply to, as well as run it on existing clusters.

For Example:

```yaml
apiVersion: management.cattle.io/v3
kind: RoleTemplate
builtin: false
context: cluster
displayName: readonly-custom
...
clusterBindingDefault:
    rules:
    - groupId: <group id> 
      clusters: ["*-prod"] # regex for the cluster displayName
    - userId: <user id>
      clusters: ["*-prod"]
    - groupPrincipalId: <group principal id>
      clusters: ["*-prod"]
```
so if I have an existing cluster with the name "us-prod" or if I create one called "eu-prod"
rancher will create a role bindings on the clusters for each of those rules  

but it will not apply to "us-dev"
