### ISSUE TITLE
[BUG] spurious networkpolicy controller error

### ISSUE THREAD

**Issue by xhejtman** [rancher/rancher#48133]
**Rancher Server Setup**
- Rancher version: 2.10.0
- Installation option (Docker install/Helm Chart): helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2 1.30.5
- Proxy/Cert Details: no proxy, cert manager

**Information about the Cluster**
- Kubernetes version: rke2 1.30.5
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported rke2 1.30.5

**Describe the bug**
Downstream cluster uses Calico CNI (rke2 version). However, it is configured without VXLan. In this case, if networkpolicy isolation for cluster is enabled, it produces tons of:
```
[ERROR] netpolMgr: handleHostNetwork: calico: couldn't get tunnel address for node kub-cs1.priv.cerit-sc.cz err=<nil>
```

because there is no vxlan setup.

**To Reproduce**

enable cluster network policy for cluster, that uses Calico cni without ipip and vxlans.

**Result**
Error message printed.

**Expected Result**

no message printed if fallback works.

**Comment by Josh-Diamond** [comment]
@xhejtman could you elaborate on the reproduction steps and provide the exact steps you executed to get your standalone rke2 cluster with `enabled cluster network policy for cluster, that uses Calico cni without ipip and vxlans` before you imported it into Rancher? 

those details would be very helpful in triaging this issue and further looking into this.  Thanks!

**Comment by xhejtman** [comment]
But the code seems to be obvious:
https://github.com/rancher/rancher/blob/d801b492431179a9b648eb6b9062c234cf494be1/pkg/controllers/managementuser/networkpolicy/netpol.go#L205

In case of calico, it wants to obtain tunel address and if there is none, it prints error. Am I wrong?

Thanks for testing this. 

This is from rke config:
```
disable:
  - rke2-canal

cni: multus,calico

profile: cis
```

it is dualstack node.

calico configuration:
```
installation:
      calicoNetwork:
        bgp: Enabled
        ipPools:
        - blockSize: 24
          cidr: 10.42.0.0/16
          encapsulation: None
          natOutgoing: Enabled
        - blockSize: 116
          cidr: xxx:42bf:8:2::/96
          encapsulation: None
          natOutgoing: Enabled
    felixConfiguration:
      featureDetectOverride: ""
      failsafeInboundHostPorts: []
      failsafeOutboundHostPorts: []
```

With defined host endpoints, bgp peers, and global network policy (the calico one). Is something from this relevant?
