### ISSUE TITLE
[BUG] Restart of the prometheus-federator pod triggers project monitors reinstallation

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48175]
**Describe the bug**
When the Prometheus Federator pod is deleted, an install helm job is triggered and the project monitor is recreated. As a consequence the user loses data. 

**Additional context**
SURE-9039

**Comment by deepakpunia-suse** [comment]
**Bug Verification Details:**

* **Rancher:** v2.11-head
* **RKE2:** v1.31.7+rke2r1
* **Prometheus Federator:** 106.0.1-rc.1+up3.0.1-rc.2

This bug is difficult to reproduce. A hotfix has been successfully deployed in the customer's environment.

**Quick Sanity Check:**

1.  Install Prometheus Federator and verify the following parameters in `values.yaml`:

    ```yaml
    namespaceRegistration:
      retryMax: 10
      retryWaitMilliseconds: 5000
      workers: 2
    ```

2.  Create a namespace within the project monitor and observe.

![Image](https://github.com/user-attachments/assets/8adac838-9e0f-400e-8c67-bb9d14dbde68)

![Image](https://github.com/user-attachments/assets/4c06aaff-e1d9-4b52-9585-d78792b8ab69)
