### ISSUE TITLE
[BUG] rancher-logging Update fails due to lack of reference to Internal Image Registry/private registry

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#48218]
**Rancher Server Setup**
- Rancher version: 2.9.4 Prime
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

When the `logging.enabled = true` setting is enabled during the update of the Rancher Logging deployment, subsequent deployments attempt to pull images from an external image registry, which fails due to the lack of internet access. The deployment should reference the internal image registry instead, as per the expected configuration.

**To Reproduce**

1. Install rancher latest
2. Install lognhorn for pv,pvc
3. Install latest logging chart
4. set `logging.enabled: true` in values.yaml 

**Result**

**Expected Result**

images should be from system-default-registry 

**Screenshots**

![screenshoteasy](https://github.com/user-attachments/assets/f281b925-635a-42f1-a114-5b1c36108f9b)

**Additional context**

**Comment by jbiers** [comment]
Adding this comment to make it clear that this can already be configured like in the example below:
```
logging:
  enabled: true
  fluentbit:
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: a.b.c
  fluentd:
    image:
      repository: rancher/mirrored-kube-logging-fluentd
      tag: x.y.z
```
IMO, the question to be answered here is whether we should have this set as default in our charts for custom logging components.
