### ISSUE TITLE
Templates cannot put boolean variable in top-level settings

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4822]
**Rancher Version:**
1.1.0-dev1
**Docker Version:**
1.9.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS stable under vmware
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create a new catalog template with a Boolean-type variable in the rancher-config

```
  questions:
    - variable: "TEST"
      label: "Test"
      description: "test"
      default: false
      required: true
      type: "boolean"
```

In the docker-config, use this variable to populate both a label, and the 'tty' setting.

```
test:
  image: busybox:latest
  labels:
    test: ${TEST}
  tty: ${TEST}
```

Attempt to deploy a new stack from this template.     

**Results:** 
The stack will deploy empty, with the error message:

```
Activating (Service 'test' configuration key 'tty' contains an invalid type, it should be a boolean.)
```

Note that there is no complaint about the use in labels.  The same error will appear multiple times if the variable is used to configure tty, stdin_open or privileged.

**Expected:**
Stack should deploy with the 'tty' setting being taken from the TEST variable.

It appears that the syntax check is performed BEFORE the variable substitution.  This worked in prior versions of Rancher.

See the "Janitor" community template for one which worked previously but is now broken in 1.1.0-dev1 by this bug.
