### ISSUE TITLE
[BUG] Fleet does not work with bitnami charts anymore

### ISSUE THREAD

**Issue by bpedersen2** [rancher/rancher#48297]
**Rancher Server Setup**
- Rancher version: 2.9.3
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: 1.30.6 (k3s and rke2)
- Cluster Type (Local/Downstream):
  - downstream, harvester provisioned or  cusotm

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Installing/Updating bitnami charts via fleet is broken.
The fleet process fails with 
```time="2024-12-04T15:01:51Z" level=fatal msg="helm chart download: invalid_reference: invalid tag"```

if only the requested chart version is bumped in the  fleet.yaml file 
(e.g. 

```
defaultNamespace: cert-manager
helm:
  repo: https://charts.bitnami.com/bitnami
  chart: cert-manager
  version: 1.3.24 
 ```

The version is listed as  available in the rancher gui ( and can be updated manually if one ignores the warnings, but that leaves the fleet bundle in an error state of course)

**Additional context**

related to #48211
