### ISSUE TITLE
Creating an ingress with rules having two paths and two services does not get created correctly 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4832]
**Rancher Version:**v1.1.0-dev2-rc3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a two services
2. Create an ingress with two paths and two services as below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customingress2
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /service3.html
        backend:
          serviceName: k8test 
          servicePort: 81
      - path: /name.html
        backend:
          serviceName: k8test1 
          servicePort: 80
```

**Results:** 
The rules specified with path:/name.html and service: k8test1 is not reflected in the haproxy.cfg
