### ISSUE TITLE
[BUG] Unable to configure loggings individually

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48364]
Customer wants to be able to define settings for each pre-defined logging resource individually without it affecting others. Especially the number of fluentd replicas and the resources dedicated to them.

**Additional context**
SURE-9146

**Comment by jbiers** [comment]
QA notes

This PR should allow users to configure the following fields when setting additionalLoggingSources for aks, eks, gke, kubeAudit and k3s+openrc:

Logging CR:
- loggingRef
- fluentd.scaling.replicas
- fluentd.resources

FluentBitAgent CR:
- loggingRef
- resources

As well as these fields when setting additionalLoggingSources for rke, rke2 and k3s+systemd:
Daemonset CR:
- containers[0].resources

In order to configure these, add the information under the corresponding additionalLoggingSources field. Example:
```
additionalLoggingSources:
  gke:
    enabled: true
    loggingRef: test
    fluentd:
      scaling
        replicas: 3
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    fluentbit:
      loggingRef: test
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
```
Example for rke:
```
additionalLoggingSources:
  rke:
    enabled: true
    fluentbit:
      log_level: "info"
      mem_buffer_limit: "5MB"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
```

**Comment by prachidamle** [comment]
@jbiers After upgrading to 2.10.2 chart will these values become available to configura, if we fix these values?

**Comment by jbiers** [comment]
Yes @prachidamle, exactly

**Comment by gregsidelinger** [comment]
I've been doing some testing of https://github.com/rancher/charts/pull/4907.  I've noticed two things.  You can not override stuff for the root logger using additionalLoggingSources.root.  Looks like the root logger needs the individualValues changes applied to it.

Also in my testing if I tried to bump the resources for fluentd but not set a scaling replicas helm would return an error.  Not a big deal and easy to work around but something I noticed.

```shell
executing "logging-operator.individualFluentd" at <.fluentd.scaling.replicas>: nil pointer evaluating interface {}.replicas
```
Here is a basic values I was using when getting the issue.
```yaml
additionalLoggingSources:
  eks:
    enabled: true
    fluentd:
      # scaling:
      #   replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 800M
        requests:
          cpu: "1"
          memory: 800M
```

**Comment by jbiers** [comment]
@gregsidelinger Thanks for taking a look at the PR. 

Not setting individual values for the root logging resource was intentional, notice how it actually doesn't have any value set to it individually unlike all others (EKS, AKS, K3s, etc). This being the default logging means it can be controlled via the fluentd.resources, fluentd.replicas and fluentbit.resources fields. This will, of course, change the values of all loggings which do not have an individual value set to them, so then you need to overwrite the values of other loggings individually as needed.

As for the bug when not setting the scaling replicas, good catch. I ended up accidentally reverting the change which fixed it during development and will add it back in :D

**Comment by pankajsqe** [comment]
After the fix in new PR, I have verified Greg's issue on both GKE and EKS clusters. when I tried to bump the resources for fluentd but not set a scaling replicas, helm did not returned any error.

Details
rancher v2.10-head
logging : 105.2.0-rc.1+up4.10.0
cluster : EKS and GKE

EKS
```
eks:
    enabled: true
    fluentd:
      # scaling:
      #   replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 800M
        requests:
          cpu: "1"
          memory: 800M
```


<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/e4c91c33-e3a2-495d-b3f0-5ab59454e2e7" />

----------------------

GKE
```
gke:
    enabled: true
    fluentd:
      # scaling:
      #   replicas: 3
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 200m
          memory: 128Mi
    loggingRef: test
```
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/49266194-2ccd-45f9-8d76-f427d55d7a3d" />

cc: @jbiers , @gregsidelinger
