### ISSUE TITLE
[BUG] Track CRD Ownership 

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#48393]
**Describe the bug**
Currently there is not a consistent way to identify what component (in a cluster) owns a given CRD. Or in other words, what component is the origin of the CustomResoruceDefinition (CRD) for the cluster being interacted with. One might assume that the "owner" of a CRD would be the component responsible for future updates to that CRD.

This issue affects Rancher framework created CRDs, so it applies to things like `prometheus-federator` and `k3s/helm-controller`. And likely others as well unless those projects have taken additional steps to produce different results.

Currently if one needs to "identify a CRD's owner", if you try to directly check the CRD you will find a recursive reference. For instance, here is the information on who owns the `Setting` CRD:
```yaml
    objectset.rio.cattle.io/owner-gvk: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition
    objectset.rio.cattle.io/owner-name: settings.management.cattle.io
    objectset.rio.cattle.io/owner-namespace: ""
```

So the owner of this CRD is identified as itself rather than the component/controller/chart origin. 

**To Reproduce**

**Result**

**Expected Result**
Compared to a non-Rancher CRD (in this case metallb crds), we can find something like:

```yaml
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: metallb-crds
    objectset.rio.cattle.io/owner-namespace: kube-system
```

That's a bit of an improvement than seeing the CRD cite it's own name as the owner. It seems these annotations are coming from rke2 as part of the cluster construction. We can see that because the [manifest I apply](https://github.com/metallb/metallb/blob/main/config/manifests/metallb-native.yaml) to install it doesn't (and wouldn't) contain these Rancher specific annotations.

While the above example is better than nothing (or the current circular reference), the best solution would include the ability to track non-resource based owners. In other words, the current annotations shown must represent a k8s resource as the owner - a robust solution should allow to identify an operator/controller as the owner as well.

**Additional context**
This has become a recent concern as O&B team seeks to improve Prometheus Federator. The PromFed project is ultimately relying on the `k3s/helm-controller` for much of the core helm functionality. And as such it relies on it as the "upstream" for some of the CRDs it uses.

When the cluster is not RKE2/k3s, then PromFed will simply install the CRDs at start up and work as expected. However on RKE2/k3s that behaviour may cause undesired results as the same `helm-controller` already exists. Both instances already know how to properly delegate the management of these resources the CRDs are based off - however neither know which one really owns the CRD itself.
