### ISSUE TITLE
Icons of  `Helm` charts are not loaded from custom repository

### ISSUE THREAD

**Issue by mguggi** [rancher/rancher#48468]
**Rancher Server Setup**
- Rancher version: `v2.8.5`

**Describe the bug**
Once you access the Apps > Charts via the UI, the icons are not loading in the catalog of helm charts. The console shows for each chart the error 500.

**To Reproduce**
I have my catalog in a Git Repository and access the icon via `file://`

```yaml
apiVersion: v2
name: test
description: A Helm chart for the test app
version: 1.0.0
type: application
icon: file://../test.png
```

**Result**
<img width="1845" alt="Screenshot 2024-12-18 at 08 48 01" src="https://github.com/user-attachments/assets/819f0abd-50c3-4704-b079-52dd1ac1230b" />

**Expected Result**
The UI should load the icons for the charts.
