### ISSUE TITLE
[BUG] node driver has incorrect id when created via rancher user interface

### ISSUE THREAD

**Issue by sudomateo** [rancher/rancher#48527]
**Rancher Server Setup**
- Rancher version: v2.10
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.31.1+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): N/A

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions: N/A

**Describe the bug**
I maintain the Oxide Rancher machine driver at https://github.com/oxidecomputer/rancher-machine-driver-oxide. When I configure this node driver using the Rancher user interface and give it my binary location and checksum it creates a random ID (e.g., `nd-nsxrx`) for the node driver. Then when I go to use the node driver to create a Kubernetes cluster it hangs because there's no node driver with the ID `oxide`. I instead have to create the node driver using the following Kubernetes manifest so the ID is correctly set as `oxide`.

```yaml
---
apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  name: oxide
  annotations:
    privateCredentialFields: token
    publicCredentialFields: host,project
  finalizers:
  - controller.cattle.io/node-driver-controller
spec:
  active: true
  addCloudCredential: true
  builtin: false
  checksum: <SHA256SUM_OF_BINARY>
  description: "Oxide Rancher node driver."
  displayName: oxide
  externalId: ""
  uiUrl: ""
  url: "https://example.com/docker-machine-driver-oxide"
```

**To Reproduce**
1. Create a node driver via the Rancher user interface.
2. Observe its ID is randomly generated (e.g., `nd-nsxrx`) using `kubectl get nodedriver`.

**Result**

```sh
> kubectl get nodedriver
NAME            AGE
aliyunecs       23d
amazonec2       23d
azure           23d
...
nd-nsxrx        30s  # This should be `oxide` or whatever the node driver is supposed to be named.
...
rackspace       23d
softlayer       23d
vmwarevsphere   23d
```

**Expected Result**

```sh
> kubectl get nodedriver
NAME            AGE
aliyunecs       23d
amazonec2       23d
azure           23d
...
oxide           30s  # Much better!
...
rackspace       23d
softlayer       23d
vmwarevsphere   23d
```

**Screenshots**
N/A

**Additional context**

```
> kubectl describe nodedriver nd-nsxrx
Name:         nd-nsxrx
Namespace:
Labels:       cattle.io/creator=norman
Annotations:  field.cattle.io/creatorId: user-49778
              lifecycle.cattle.io/create.node-driver-controller: true
API Version:  management.cattle.io/v3
Kind:         NodeDriver
Metadata:
  Creation Timestamp:  2024-12-20T03:50:11Z
  Finalizers:
    controller.cattle.io/node-driver-controller
  Generate Name:     nd-
  Generation:        5
  Resource Version:  8319113
  UID:               10410013-c17d-47ab-9adb-debf27e3a703
Spec:
  Active:                true
  Add Cloud Credential:  false
  Builtin:               false
  Checksum:              3c6428515925128d6b8089e947c883c7f4e7f66bff1631f6e177474ca9f85c28
  Description:
  Display Name:          oxide
  External Id:
  Ui URL:
  URL:                   http://example.com/docker-machine-driver-oxide
```

```
> kubectl describe nodedriver oxide
Name:         oxide
Namespace:
Labels:       <none>
Annotations:  field.cattle.io/description: http://example.com/docker-machine-driver-oxide
              lifecycle.cattle.io/create.node-driver-controller: true
              privateCredentialFields: token
              publicCredentialFields: host,project
API Version:  management.cattle.io/v3
Kind:         NodeDriver
Metadata:
  Creation Timestamp:  2024-12-19T23:37:09Z
  Finalizers:
    controller.cattle.io/node-driver-controller
  Generation:        11
  Resource Version:  8296486
  UID:               1268db90-a2a5-4413-a662-fc9bfaef808c
Spec:
  Active:                true
  Add Cloud Credential:  true
  Builtin:               false
  Checksum:              3c6428515925128d6b8089e947c883c7f4e7f66bff1631f6e177474ca9f85c28
  Description:           Oxide Rancher node driver.
  Display Name:          oxide
  External Id:
  Ui URL:
  URL:                   http://example.com/docker-machine-driver-oxide
```
