### ISSUE TITLE
ingress with only backend specified does not get programmed correctly

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4853]
**Rancher Version:**Master

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a kubernetes environment
2. Create a service k8test with port 81 and ingress as below:
soumyas-MacBook-Pro:kubernetes soumya$ cat ingresscustom.yml 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customingress 
spec:
   backend:
     serviceName: k8test
     servicePort: 81
````
**Results:** 
The following is programmed in /etc/haproxy/haproxy.cfg (port 80 is programmed although we provided port 81 as the service port)
```
frontend 402ce9d9-43f5-4588-8b31-cb72b9562f56_80_frontend
        bind *:80
        mode http

        default_backend 402ce9d9-43f5-4588-8b31-cb72b9562f56_80_0_backend

backend 402ce9d9-43f5-4588-8b31-cb72b9562f56_80_0_backend
        mode http
        server 21f62c53-f06d-4cd1-80a3-6a063ad443b2 10.42.159.88:80
        server f616994a-6cdf-44dc-8250-84f4dede1486 10.42.126.50:80
```
