### ISSUE TITLE
[v2.11] [Forwardport] [BUG] Unable to configure loggings individually

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48629]
Issue created to track the forwardport of https://github.com/rancher/rancher/issues/48364 to Rancher v2.11

**Comment by jbiers** [comment]
When forwardporting this issue, be mindful of a typo accidentally inserted in the file templates/loggings/k3s/fluentbitagent.yaml. In line 3 it says `{{- $individualValues := .Values.additionalLoggingSources.kes.fluentbit -}}` while it should be `{{- $individualValues := .Values.additionalLoggingSources.k3s.fluentbit -}}. I'll go back and add a fix to the 2.10 version when code freeze is over ;)

**Comment by apoorvajagtap** [comment]
Hi @jbiers with the merging of https://github.com/rancher/charts/pull/5050, are we comfortable with closing this?

**Comment by jbiers** [comment]
> Hi [@jbiers](https://github.com/jbiers) with the merging of [rancher/charts#5050](https://github.com/rancher/charts/pull/5050), are we comfortable with closing this?

Not yet. It’s status should be moved to “To Test” so that it can go through the QA team and only then be closed by them.

**Comment by pankajsqe** [comment]
I have verified above issue on both GKE and EKS clusters. User is able to configure rancher-logging individually. There was an error scenario as well  when I tried to bump the resources for fluentd but not set a scaling replicas, helm did not returned any error.

Details
rancher v2.11.0-alpha4
logging : v1.31.5-eks-8cce635
cluster : EKS and GKE

EKS positive scenario
```
eks:
    enabled: true
    fluentd:
      scaling:
        replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 800M
        requests:
          cpu: "1"
          memory: 800M

```

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/da7413ec-272d-49f5-ab8d-3ab9f878ed03" />
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/7afa7c83-4ec2-4635-9d85-3a5c16330a6a" />
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/7940b993-ff96-4b07-aca9-065e5c7e261c" />

_____________________________________________________________________________________________________

EKS Failure Scenario
```
eks:
    enabled: true
    fluentd:
      # scaling:
      #   replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 800M
        requests:
          cpu: "1"
          memory: 800M
```

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/a7c749af-c6b9-467f-8674-bcb53af082d3" />
<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/5904f087-557a-4b51-8301-fb43a9ad658e" />
