### ISSUE TITLE
[BUG] Rancher does not list the charts with versions which include `+` in OCI based helm repositories

### ISSUE THREAD

**Issue by jtomasek** [rancher/rancher#48746]
**Rancher Server Setup**
- Rancher version: 2.10.1
- Installation option (Docker install/Helm Chart): Helm Chart, RKE2

**Information about the Cluster**
- Kubernetes version: v1.31.3+rke2r1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
As [described in the HELM documentation](https://helm.sh/docs/topics/registries/#oci-feature-deprecation-and-behavior-changes-with-v380)  and [HELM codebase](https://github.com/helm/helm/blob/7f83ea5e5ecee756bbc62783bd6ad2ea1e2dc6bf/pkg/registry/client.go#L49-L52) the OCI registries don't support `+` as a tag character. Helm adopts the convention of changing plus (+) to an underscore (_) in chart version tags when pushing to a registry and back to a plus (+) when pulling from a registry.

Since the `+` is stored as `_` in the registry, when Rancher lists the charts from the OCI repository, it hits the tag with underscore, identifies it as non SemVer and the chart does not get listed.

We should adopt the same approach as HELM and replace the underscores in tags with `+` before checking if it is valid SemVer and listing the OCI repository index.

**To Reproduce**
1. Add `oci://registry.opensuse.org/isv/suse/edge/factory/totest/charts/metallb-chart` clusterrepo as 'metallb-obs-totest'
2. List the chart using HELM
```
helm show chart oci://registry.opensuse.org/isv/suse/edge/factory/totest/charts/metallb-chart
Pulled: registry.opensuse.org/isv/suse/edge/factory/totest/charts/metallb-chart:999.0.0_up0.14.9
Digest: sha256:5a0fc615bd9c875179512befd60cc32fe3d327314683df4c2ad24d516883f980
registry.opensuse.org/isv/suse/edge/factory/totest/charts/metallb-chart:999.0.0_up0.14.9 contains an underscore.

OCI artifact references (e.g. tags) do not support the plus sign (+). To support
storing semantic versions, Helm adopts the convention of changing plus (+) to
an underscore (_) in chart version tags when pushing to a registry and back to
a plus (+) when pulling from a registry.
apiVersion: v2
appVersion: v0.14.3
dependencies:
- condition: frrk8s.enabled
  name: frr-k8s
  repository: file://./charts/frr-k8s
  version: 0.0.15
- condition: crds.enabled
  name: metallb-crds
  repository: file://./charts/metallb-crds
  version: 0.14.8
description: A network load-balancer implementation for Kubernetes using standard
  routing protocols
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
kubeVersion: '>= 1.19.0-0'
name: metallb
sources:
- https://github.com/metallb/metallb
type: application
version: 999.0.0+up0.14.9
```
3. List the repo index using Rancher API (or see the browser console 'Network' tab when using UI)
```
curl 'https://<RANCHER_API>/v1/catalog.cattle.io.clusterrepos/metallb-obs-totest?link=index' -H 'Accept: application/json' -H 'Cookie: R_SESS=token-<token>' --insecure
{"apiVersion":"v1","generated":"2025-01-16T15:45:59.07928819Z","entries":{}}
```

**Result**
No entries returned even though there is one (step 2.).

**Expected Result**
`entries` in the response contains 1 chart.

**Screenshots**
<img width="918" alt="Image" src="https://github.com/user-attachments/assets/a9ca50ad-6faf-495d-ae3e-af90fa193e43" />
