### ISSUE TITLE
[BUG] New custom cluster stuck in "Non-ready bootstrap machine(s) custom-abcdef123456 and join url to be available on bootstrap node"

### ISSUE THREAD

**Issue by maxnitze** [rancher/rancher#48783]
**Rancher Server Setup**
- Rancher version: 2.9.3
- Installation option (Docker install/Helm Chart): Docker
   ```yaml
   services:
     rancher:
       image: my-registry.company.com/rancher/rancher:v2.9.3
       container_name: "rancher"
       ports:
       - 80:80
       - 443:443
       restart: unless-stopped
       privileged: true
       command: "--no-cacerts"
       extra_hosts:
       - # some extra hosts
       volumes:
       - /var/lib/rancher:/var/lib/rancher
       - /opt/rancher/compose/ssl/secret.crt:/etc/rancher/ssl/cert.pem
       - /opt/rancher/compose/ssl/secret.key:/etc/rancher/ssl/key.pem
       - /etc/pki/ca-trust/source/anchors/companyRootCA.crt:/etc/rancher/ssl/ca-additional.pem
       - /etc/pki/ca-trust/source/anchors/companyRootCA.crt:/etc/pki/trust/anchors/ca-additional.pem
   ```
- Proxy/Cert Details: %

**Information about the Cluster**
- Kubernetes version: v1.30.7+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions: %

**Describe the bug**

My new custom cluster with one control-plane,etcd and three worker nodes gets stuck in "Provisioning" (or "Updating", if I edit something on it) with message "Non-ready bootstrap machine(s) custom-abcdef123456 and join url to be available on bootstrap node". All nodes are in state "Waiting for Node Ref" with message "This resource is currently in a transitioning state, but there isn't a detailed message available."

The control-plane seems to start up okay. I can query the API server from the control-plane node. But no worker node joins.

```
[root@my-cluster-control-plane-1 ~]# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml version
Client Version: v1.30.7+rke2r1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.7+rke2r1
[root@my-cluster-control-plane-1 ~]# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
NAME                         STATUS   ROLES                       AGE   VERSION
my-cluster-control-plane-1   Ready    control-plane,etcd,master   93m   v1.30.7+rke2r1
[root@my-cluster-control-plane-1 ~]# 
```

**To Reproduce**

* have four VMs as nodes
   * all VMs run Oracle Linux Server 9.4
* disable firewalld
* configure NetworkManager
   * https://docs.rke2.io/known_issues#networkmanager
* create a new custom RKE2 cluster from the Rancher UI
   * Kubernetes Version v1.30.7+rke2r1
   * Cloud Provider: Default
   * Container Network: Calico
* join all the nodes using the join command from the "Registration" tab

We don't have DNS resolution for Rancher in the network the VMs run in. So I need to configure the nodes and CoreDNS to know about Rancher:
* on all nodes
   ```
   [root@my-cluster-control-plane-1 ~]#  cat /etc/hosts
   # ...
   10.20.30.40  rancher.my-domain.com 
   # ...
   [root@my-cluster-control-plane-1 ~]# 
   ```
* in the "Additional Manifests" section in the cluster config
   ```yaml
   apiVersion: helm.cattle.io/v1
   kind: HelmChartConfig
   metadata: 
     name: rke2-coredns
     namespace: kube-system
   spec: 
     valuesContent: |-
       zoneFiles: 
         - filename: my-domain.com.db
           domain: my-domain.com
           contents: |
             $ORIGIN my-domain.com.
             @         3600 IN SOA   [ ... ]
             rancher   3600 IN A     10.20.30.40
         - filename: my-domain.conf
           domain: my-domain.com
           contents: |
             my-domain.com {
                 file /etc/coredns/my-domain.com.db
             }
       extraConfig: 
         import: 
           parameters: /etc/coredns/*.conf
   ```

**Result**

The control-plane node is immediately going to "Waiting for Node Ref". It does not do anything until the first worker node joins, which already seems odd to me. Once the first worker node joins, the initial plan is executed on the control plane. Everything comes up successfully until "Non-ready bootstrap machine(s) ...". Then nothing happens anymore:

```
7:44:23 pm   [INFO ] waiting for at least one control plane, etcd, and worker node to be registered
7:45:39 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for agent to check in and apply initial plan
7:45:43 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
7:46:23 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler
7:46:29 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for probes: calico, kube-apiserver, kube-controller-manager, kube-scheduler
7:46:59 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for probes: calico
7:47:55 pm   [INFO ] configuring bootstrap node(s) custom-b01ff73cf294: waiting for cluster agent to connect
7:48:49 pm   [INFO ] non-ready bootstrap machine(s) custom-b01ff73cf294 and join url to be available on bootstrap node
```

All nodes stuck in "Waiting for Node Ref", cluster in state "Provisioning" with message "Non-ready bootstrap machine(s) custom-abcdef123456 and join url to be available on bootstrap node".

**Expected Result**

The control-plane comes up running and the worker nodes join as well.

**Additional context**

I tested A LOT of ideas and setups and read through A LOT of issues on GitHub.

**helm-operations are pending**

I have the issue, that the `helm-operations` are stuck in pending state, because they have the wrong tolerations for k3s/rke2.

I could fix this by adding the following block to my cluster yaml:

```yaml
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  labels:
  name: my-cluster
  namespace: fleet-default
spec:
  clusterAgentDeploymentCustomization:
    appendTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  fleetAgentDeploymentCustomization:
    appendTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/etcd
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  # ...
```

And then changing the taints on my control plane node from

```yaml
taints:                                                                                                 
- effect: NoSchedule                                                                                    
  key: node-role.kubernetes.io/control-plane                                                                                                                                                                       
- effect: NoExecute                                                                                                                                                                                                
  key: node-role.kubernetes.io/etcd
```

to

```yaml
taints:                                                                                                 
- effect: NoSchedule                                                                                    
  key: node-role.kubernetes.io/controlplane                                                                                                                                                                       
  value: "true"
- effect: NoExecute                                                                                                                                                                                                
  key: node-role.kubernetes.io/etcd
  value: "true"
```

(remove the dash in `control-plane` and add the `value: "true"` to both)

This way the `helm-operations` pods as well as the cluster agent pod is working.

Here are some of the issues on this:
* https://github.com/rancher/rancher/issues/43237
* https://github.com/rancher/rancher/pull/47305
* https://github.com/rancher/rancher/issues/48541
* https://github.com/rancher/rancher/issues/48130

This does not really help though, since it only enables to install the `rancher-webhook` that then needs a worker node to run.

**Machine-Plan Secret is Empty**

When I look into the `rancher-system-agent` systemd service logs (with debug enabled), I see, that it reads its machine-plan secret every five seconds.

```
Jan 20 20:00:02 my-cluster-node-1 rancher-system-agent[16623]: time="2025-01-20T20:00:02+01:00" level=debug msg="[K8s] Processing secret custom-582d6b8e9abf-machine-plan in namespace fleet-default at generation 0 with resource version 728476987"
Jan 20 20:00:07 my-cluster-node-1 rancher-system-agent[16623]: time="2025-01-20T20:00:07+01:00" level=debug msg="[K8s] Processing secret custom-582d6b8e9abf-machine-plan in namespace fleet-default at generation 0 with resource version 728476987"
Jan 20 20:00:12 my-cluster-node-1 rancher-system-agent[16623]: time="2025-01-20T20:00:12+01:00" level=debug msg="[K8s] Processing secret custom-582d6b8e9abf-machine-plan in namespace fleet-default at generation 0 with resource version 728476987"
```

When I look into that secret in the rancher local cluster, I see, that it is empty. I also found an issue for that, but no real solutions there as well: https://github.com/rancher/fleet/issues/2053

I tried the ideas in the thread (start node and control-plane "in quick succession", or join a node before the control-plane), but nothing worked for me.

**Add node with all three roles**

I also tried to add the control-plane node with all three roles, but that resulted in the same state ("Waiting for Node Ref" and "non-ready bootstrap machine(s)").

**Add multiple control-plane nodes**

I also tried to add one or two of the worker nodes as control-plane nodes as well. This also did not change anything.

Any help is very welcome!
