### ISSUE TITLE
[BUG] Remove remote fields from GRB Status for non-admin global roles

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#48790]
**Rancher Server Setup**
- Rancher version: v2.11-05a12b2b913325def4805dee2b83d18ba94ef426-head
- Installation option (Docker install/Helm Chart): Helm chart 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)

**Describe the bug**
The GRB status includes observedGenerationRemote, summaryRemote for non-admin GlobalRoles which are intended only for admin GlobalRoles. 
Note: This issue was observed while testing https://github.com/rancher/rancher/issues/44668

**To Reproduce**
1. Create a custom global role: grole1 
3. Create a user with the global role "grole1": testuser1.
4. Verify global role binding was created for the user on the local cluster: kubectl get globalrolebinding <grb-name> -o yaml
5. Verify that the status field exists in the output YAML and ensure the following fields are NOT present:
  - remoteConditions
  - summaryRemote
  - observedGenerationRemote

**Result**
The summaryRemote and observedGenerationRemote fields were displayed in the GRB status for a non-admin global role:
```
status:
 lastUpdateTime: "2025-01-20T21:15:47Z"
 localConditions:
 - lastTransitionTime: "2025-01-20T21:15:47Z"
  message: ""
  reason: ClusterPermissionsReconciled
  status: "True"
  type: ClusterPermissionsReconciled
 - lastTransitionTime: "2025-01-20T21:15:47Z"
  message: ""
  reason: GlobalRoleBindingReconciled
  status: "True"
  type: GlobalRoleBindingReconciled
 - lastTransitionTime: "2025-01-20T21:15:47Z"
  message: ""
  reason: NamespacedRoleBindingReconciled
  status: "True"
  type: NamespacedRoleBindingReconciled
 observedGenerationLocal: 1
 observedGenerationRemote: 1
 summary: Completed
 summaryLocal: Completed
 summaryRemote: Completed
```
**Expected Result**
Since `RemoteConditions` field is ONLY for the admin GlobalRole, observedGenerationRemote and summaryRemote should not be displayed in the GRB status field for non-admin global roles

**Comment by Priyashetty17** [comment]
Validated with `v2.11-a1bda936c809e0394520c9d40d2998529223401e-head` that the remote fields are not present in the GRB status with non-admin global roles.

```
status:
  lastUpdateTime: "2025-01-28T20:08:29Z"
  localConditions:
  - lastTransitionTime: "2025-01-28T20:08:29Z"
    message: ""
    reason: ClusterPermissionsReconciled
    status: "True"
    type: ClusterPermissionsReconciled
  - lastTransitionTime: "2025-01-28T20:08:29Z"
    message: ""
    reason: GlobalRoleBindingReconciled
    status: "True"
    type: GlobalRoleBindingReconciled
  - lastTransitionTime: "2025-01-28T20:08:29Z"
    message: ""
    reason: NamespacedRoleBindingReconciled
    status: "True"
    type: NamespacedRoleBindingReconciled
  observedGenerationLocal: 1
  summary: Completed
  summaryLocal: Completed
```

GRB status with admin global roles:
```
status:
  lastUpdateTime: "2025-01-28T20:14:59Z"
  localConditions:
  - lastTransitionTime: "2025-01-28T20:14:59Z"
    message: ""
    reason: ClusterPermissionsReconciled
    status: "True"
    type: ClusterPermissionsReconciled
  - lastTransitionTime: "2025-01-28T20:14:59Z"
    message: ""
    reason: GlobalRoleBindingReconciled
    status: "True"
    type: GlobalRoleBindingReconciled
  - lastTransitionTime: "2025-01-28T20:14:59Z"
    message: ""
    reason: NamespacedRoleBindingReconciled
    status: "True"
    type: NamespacedRoleBindingReconciled
  observedGenerationLocal: 1
  observedGenerationRemote: 1
  remoteConditions:
  - lastTransitionTime: "2025-01-28T20:14:59Z"
    message: ""
    reason: ClusterAdminRoleExists
    status: "True"
    type: ClusterAdminRoleExists
  summary: Completed
  summaryLocal: Completed
  summaryRemote: Completed
```
