### ISSUE TITLE
[BUG] Rancher Server Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by RoybertParada** [rancher/rancher#48792]
**Rancher Server Setup**
- Rancher version: 2.10.1
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: 1.29
- Cluster Type (Local/Downstream): EKS
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

I am trying to deploy Rancher on my EKS Kubernetes cluster using the Helm chart. My use case is to have Rancher running on one cluster and then add the other EKS clusters I have in AWS, allowing me to access all of them from a single interface using SSO for login and managing the set of permissions directly from Rancher.

The problem arises when I try to install and configure it so that TLS termination happens at the AWS Network Load Balancer (NLB) that is provisioned using the AWS Load Balancer Ingress Controller.

When I configure the Helm chart as follows:
```yaml
agentTLSMode: "system-store"
ingress:
  enabled: false

service:
  type: "LoadBalancer"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: '60'
    service.beta.kubernetes.io/aws-load-balancer-name: "rancher"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:x:certificate/2430e303-4077-47e0-a73e-826aa9a3f7c9"

tls: external
```

I get the error: "Client sent an HTTP request to an HTTPS server." I don’t fully understand what’s going wrong. Then, when I configure the listener on port 443 of the load balancer to forward requests to port 80 of the service instead of 444, and I try to access my domain, I encounter the error: "Too many redirects."

If someone can help me understand what I need to do differently or additionally to make this work, I’d appreciate it. I’ve read the documentation on [SSL termination](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#external-tls-termination) and [NLB configuration](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/infrastructure-setup/amazon-elb-load-balancer), and everything seems fine according to what the documentation states.

**To Reproduce**

Deploy rancher with rancher helm chart and the above helm chart values

**Expected Result**

Browser https access to rancher dashboard
