### ISSUE TITLE
[BUG] lastTransitionTime shouldn't update for conditions that remain unchanged

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#48809]
**Rancher Server Setup**
- Rancher version: v2.11-05a12b2b913325def4805dee2b83d18ba94ef426-head
- Installation option (Docker install/Helm Chart): Helm chart 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
The lastTransitionTime for the GlobalRoleBindingReconciled condition is being updated even though its status remains "True". 
Note: This issue was observed while testing https://github.com/rancher/rancher/issues/44668

**To Reproduce**
1. Create a global role: grole1 
3. Create a user with the global role "grole1": testuser1.
4. Verify global role binding was created for the user on the local cluster: kubectl get globalrolebinding <grb-name> -o yaml
5. Add a dummy finalizer to the GRB.
6. Delete the global role grole1 to simulate an error condition in the GRB status for ClusterPermissionsReconciled and NamespacedRoleBindingReconciled.
7. Verify that the Error status is reflected for ClusterPermissionsReconciled and NamespacedRoleBindingReconciled.
8. Verify that the lastTransitionTime gets updated ONLY for ClusterPermissionsReconciled and NamespacedRoleBindingReconciled and not for GlobalRoleBindingReconciled.

**Result**
The lastTransitionTime gets updated for all 3 conditions under localConditions.
**BEFORE DELETING GLOBAL ROLE:**
```
status:
  lastUpdateTime: "2025-01-21T20:59:48Z"
  localConditions:
  - lastTransitionTime: "2025-01-21T20:59:48Z"
    message: ""
    reason: ClusterPermissionsReconciled
    status: "True"
    type: ClusterPermissionsReconciled
  - lastTransitionTime: "2025-01-21T20:59:48Z"
    message: ""
    reason: GlobalRoleBindingReconciled
    status: "True"
    type: GlobalRoleBindingReconciled
  - lastTransitionTime: "2025-01-21T20:59:48Z"
    message: ""
    reason: NamespacedRoleBindingReconciled
    status: "True"
    type: NamespacedRoleBindingReconciled
  observedGenerationLocal: 1
  observedGenerationRemote: 1
  summary: Completed
  summaryLocal: Completed
  summaryRemote: Completed
userName: u-tdsgc
```
AFTER DELETING GLOBAL ROLE:
```
status:
  lastUpdateTime: "2025-01-21T21:00:55Z"
  localConditions:
  - lastTransitionTime: "2025-01-21T21:00:55Z"
    message: globalroles.management.cattle.io "grole1" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: ClusterPermissionsReconciled
  - lastTransitionTime: "2025-01-21T21:00:55Z"
    message: ""
    reason: GlobalRoleBindingReconciled
    status: "True"
    type: GlobalRoleBindingReconciled
  - lastTransitionTime: "2025-01-21T21:00:55Z"
    message: globalroles.management.cattle.io "grole1" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: NamespacedRoleBindingReconciled
  - lastTransitionTime: "2025-01-21T21:00:55Z"
    message: globalroles.management.cattle.io "grole1" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: FleetWorkspacePermissionReconciled
  observedGenerationLocal: 1
  observedGenerationRemote: 1
  summary: Error
  summaryLocal: Error
  summaryRemote: Completed
userName: u-tdsgc
```

**Expected Result**
The lastTransitionTime should be updated only for ClusterPermissionsReconciled and NamespacedRoleBindingReconciled, and should not be updated for GlobalRoleBindingReconciled

**Comment by Priyashetty17** [comment]
Validated with `v2.11-a1bda936c809e0394520c9d40d2998529223401e-head` that the lastTransitionTime doesn't update for conditions that are unchanged.

```
status:
  lastUpdateTime: "2025-01-28T20:04:39Z"
  localConditions:
  - lastTransitionTime: "2025-01-28T20:04:39Z"
    message: globalroles.management.cattle.io "auto-testgr-kaxot" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: ClusterPermissionsReconciled
  - lastTransitionTime: "2025-01-28T20:03:29Z"
    message: ""
    reason: GlobalRoleBindingReconciled
    status: "True"
    type: GlobalRoleBindingReconciled
  - lastTransitionTime: "2025-01-28T20:04:39Z"
    message: globalroles.management.cattle.io "auto-testgr-kaxot" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: NamespacedRoleBindingReconciled
  - lastTransitionTime: "2025-01-28T20:04:39Z"
    message: globalroles.management.cattle.io "auto-testgr-kaxot" not found
    reason: FailedToGetGlobalRole
    status: "False"
    type: FleetWorkspacePermissionReconciled
  observedGenerationLocal: 1
  summary: Error
  summaryLocal: Error
```
