### ISSUE TITLE
[v2.9] [Backport] [BUG] Unable to configure loggings individually

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48870]
Issue created to track the backport of https://github.com/rancher/rancher/issues/48364 to Rancher v2.9

**Comment by deepakpunia-suse** [comment]
Details
rancher v2.9-head
logging : 104.2.0-rc.1+up4.8.0
cluster : EKS and GKE

GKE
```
gke:
    enabled: true
    fluentd:
       #scaling:
        # replicas: 3
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 200m
          memory: 128Mi
    loggingRef: test

```

![Image](https://github.com/user-attachments/assets/c65ac87b-4e48-411e-ad3b-f6e9f2d2895e)


EKS
```
eks:
    enabled: true
    fluentd:
      # scaling:
      #   replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: 800M
        requests:
          cpu: "1"
          memory: 800M
```

![Image](https://github.com/user-attachments/assets/ea7931b4-0621-4032-b124-990ea3bed6d3)
