### ISSUE TITLE
[BUG] Istio ztunnel image not properly referenced when ambient mode is enabled

### ISSUE THREAD

**Issue by ian659** [rancher/rancher#48924]
**Rancher Server Setup**
- Rancher version: v2.10.1
- Installation option (Docker install/Helm Chart): rancher-istio 105.5.0+up1.24.1 helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.31
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

When enabling istio ambient mode the [ztunnel](https://hub.docker.com/r/istio/ztunnel) image is set to just `ztunnel` rather than something like `<docker repo>/istio/ztunnel`. Also there does not appear to be a rancher mirrored version of ztunnel.

**To Reproduce**

In the istio helm values submit an `overlayFile` with `spec.profile = ambient`

```
overlayFile: |
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  spec:
    profile: ambient
```

Deploy the istio helm chart.

**Result**

The ztunnel image cannot be pulled because the default address is not a container image repo.

**Expected Result**

The default should be something functional. Either the istio container image repo or a mirrored repo.

**Screenshots**

**Additional context**

In the helm values we can change the default container repo like this:

```
overlayFile: |
  apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  spec:
    hub: <repo address>
```

The ambient mode functionally would seem to reduce compute costs and solves troublesome edge cases such as trouble with jobs running with istio proxies, prometheus scraps in strict mtls mode and so on. It would be nice if the ambient mode configuration could be as smooth as possible.
