### ISSUE TITLE
Audit logging controller

### ISSUE THREAD

**Issue by joshmeranda** [rancher/rancher#48941]
# Problem
As it currently exists, the rancher audit log collects all logs all the time. This leaves the user with log storage being filled with many logs which may or may not be useful to them. Users should have the ability to configure which logs are collected and which are not.

The audit log also redacts some information according to hard coded non-user-configurable logic. If a user finds we have missed some important fields, they can report the issue but until a fix can be released they are stuck with exposed information. Users should be able to update the redaction system as patch until it can be incorporated into rancher.

# Solution
Rancher should provide support for audit log configuration to allow for filtering audit logs and configuring additional redactions.

# Requirements

- [x] Support for log filtering
- [x] Support for redaction filtering
- [x] UI support for configuration options
- [x] No regressions in existing redactions
- [x] Update webhook to validate `AuditPolicy` resources
- [x] Document the new functionality

**Comment by joshmeranda** [comment]
Closing in favor ofhttps://github.com/rancher/rancher/pull/49521#pullrequestreview-2703664068

**Comment by joshmeranda** [comment]
# QA Template

## Helm Tests

### Enable / Disable

When installing rancher via helm, it can be disabled by controlling the `auditLog.enabled` value.

1. When installing rancher with `helm upgrade --install --create-namespace --namespace cattle-system rancher <chart> --set auditLog.enabled=true`, you should see an additional container called `rancher-audit-log`. When interacting with the rancher api (ex navigating the UI or making requests directly to the api) you should see log entries in that `rancher-audit-log` container.
2. Upgrading the chart with `--set auditLog.enabled=false` should remove the container from rancher pods

### Log Level

1. Install rancher with the flags `--set auditLog.enabled=true --set auditLog.level=0`
2. Verify that the logs found in the `rancher-audit-log` only contain log metedata
3. Upgrade the rancher installation to bump the level to `1`
4. Verify that logs now also include `responseHeaders` and `requestHeaders` but do not include `requestBody` or `responseBody`
5. Upgrade the rancher installation to bump the level to `2`
6. Verify that logs now also include `responseHeaders`, `requestHeaders`, and `requestBody`, but does not include `responseBody`
7. Upgrade the rancher installation to bump the level to `3`
8. Verify that logs now also include `responseHeaders`, `requestHeaders`, `requestBody`, and `responseBody`

**Note: not all logs will have a response or request body even at level 3, as long as there are logs that contain all those fields that can count as a `PASS`. Easiest way to get this info is by logging in via the UI.

## Controller / CRD

### Enabled

1. Install rancher with `--set auditLog.enabled=true`
2. Create the `AuditPolicy`
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: enabled
spec:
  enabled: true
EOF
```
3. Verify that the `Active` status of the `AuditPolicy` is `true`
4. Disable the policy with
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: enabled
spec:
  enabled: true
EOF
```
5. Verify that the `Active` status of the `AuditPolicy` is `false`

### Verbosity

1. Install rancher with `--set auditLog.enabled=true`
2. Create the `AuditPolicy`
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: increase-verbosity
spec:
  enabled: true
  verbosity:
    level: 3
EOF
```
3. Login to rancher and verify that you see `requestHeader`, `requestBody`, `responseHeader`, `responseBody` in the rancher audit logs

### Filters

1. Install rancher with `--set auditLog.enabled=true`
2. Create the `AuditPolicy`
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: filters
spec:
  enabled: true
  filters:
    - action: deny
      requestUri: ".*"
    - action: allow
      requestUri: ".*login.*"
EOF
```
3. Login to rancher
4. Send a request to `https://<rancher hostname>/version`
5. Verify that only the login requests were added to the audit log

### Redactions

1. Install rancher with `--set auditLog.enabled=true`
2. Create the `AuditPolicy`
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: redactions
spec:
  enabled: true
  additionalRedactions:
    - paths:
      - "$.gitCommit"
EOF
```
3. Verify that in the associated audit log that the `responseBody.gitCommit` field is `[redacted]`

### Invalid Policies

Each of the following `AuditPolicies` should be rejected by `rancher-webhook`:

#### Invalid filter action
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: bad.filter.action
spec:
  enabled: true
  filters:
    - action: "do not allow"
      requestURI: ".*"
EOF
```

#### Invalid filter `requestURI` Regex
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: invalid.requesturi.regex
spec:
  enabled: true
  filters:
    - action: allow
      requestURI: "*"
EOF
```

#### Invalid Redaction Header Regex
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: invalid.redaction.header.regex
spec:
  enabled: true
  additionalRedactions:
    - headers:
      - "*"
EOF
```

#### Invalid Redaction JSONPath
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: invalid.redaction.jsonpath
spec:
  enabled: true
  additionalRedactions:
    - paths:
      - "..gitCommit"
EOF
```

#### Invalid Policy Log Levels
```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: too.low.log.level
spec:
  enabled: true
  verbosity:
    level: -1
EOF
```

```
kubectl apply -f -<<EOF
apiVersion: auditlog.cattle.io/v1
kind: AuditPolicy
metadata:
  name: too.high.log.level
spec:
  enabled: true
  verbosity:
    level: 4
EOF
```
