### ISSUE TITLE
Setting up KeycloakOIDC API: summarize scopes must be space delimited

### ISSUE THREAD

**Issue by manofftoday** [rancher/rancher#48963]
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions: N/A
- Browser type & version: N/A

**Describe the bug**
When attempting to configure **KeycloakOIDC** as an authentication provider via **API automation**, the `testAndApply` endpoint (using a **POST** request) always returns the following error:

```shell
scopes are invalid:  scopes must be space delimited and openid is a required scope. ", "status": 500, "type": "error"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "strict_transport_security": "max-age=31536000;
```  

While I'm able to configure **KeycloakOIDC** using a **PUT** request, it does not create the associated objects (e.g., **users** and **clusterRoleBindings**).  
However, when configuring via the **Rancher web interface**, everything works as expected: the login screen appears, and the system asks for a **Keycloak user** to create the necessary objects.

I also tried performing a **PUT** before the **POST**, but the issue persists.

**To Reproduce**

1. Attempt to configure KeycloakOIDC using the following Ansible playbook:
```yaml
  - name: Configure Keycloak Authentication
    ansible.builtin.uri:
      url: "https://{{ ansible_fqdn }}/v3/keyCloakOIDCConfigs/keycloakoidc?action=testAndApply"
      method: POST
      headers:
        Authorization: "Bearer {{ rancher_api_token }}"
        Content-Type: "application/json"
      body:
        accessMode: "unrestricted"
        enabled: true
        allowedPrincipalIds:
          - "keycloakoidc_group://rke2admin"
        clientId: "rancher"
        clientSecret: "QzkGBXod9B6LSbRdFH5HT6dr7b0FPyIT"
        authEndpoint: "https:/test-1:8443/realms/master/protocol/openid-connect/auth"
        issuer: "https://test-1:8443/realms/master"
        rancherUrl: "https://rancher.gre2.com/verify-auth"
        scope: "openid profile email"
        logoutAllSupported: false
        groupSearchEnabled: true
      body_format: json
      validate_certs: no
    register: response
```
**Result**
```shell
scopes are invalid: scopes must be space delimited and openid is a required scope.", "status": 500, "type": "error"}, "msg": "Status code was 500 and not [200]: HTTP Error 500: Internal Server Error", "redirected": false, "status": 500, "strict_transport_security": "max-age=31536000;
```

Even when using a **PUT** request to configure KeycloakOIDC, **no associated objects** (such as users or roles) are created.

**Expected Result**

- The API should correctly configure Keycloak OIDC and create the associated **users** and **clusterRoleBindings**, just as it does via the Rancher web interface.
- The `allowedPrincipalIds` field should work properly when using a **PUT** request.
- If additional credentials are needed to create the associated objects, this should be **clearly documented**.

**Screenshots**

![Image](https://github.com/user-attachments/assets/46f3cb24-81d5-4eb0-a50c-0b904c95afe4)

**Additional context**

- The **Rancher API documentation** does not provide clear guidance on how to correctly configure KeycloakOIDC via API.
- There are no API fields documented that allow sending **Keycloak user credentials** for mapping.
- Even though a **PUT** request successfully configures the authentication provider, the related objects (**users, clusterRoleBindings**) are **not created automatically**.
- Could someone confirm if this is a **bug** or clarify the correct API configuration process?
- Using PUT, scopes are correctly configured so it seems not to be a syntax issue.
- Using PUT and then logging in via OIDC to RANCHER creates an associated usermap, but the Default Admin is missing

**Comment by manofftoday** [comment]
I was able to deal with the request:


```
  - name: Configure Keycloak Authentication
    ansible.builtin.uri:
      url: "https://{{ ansible_fqdn }}/v3/keyCloakOIDCConfigs/keycloakoidc?action=configureTest"
      method: POST
      headers:
        Authorization: "Bearer {{ rancher_api_token }}"
        Content-Type: "application/json"
      body:
        accessMode: "unrestricted"
        enabled: false
        type: "keyCloakOIDCConfig"
        uuid: "fe651219-adbc-427a-bf1f-ac1f8257fce1"
        clientId: "rancher"
        clientSecret: "QzkGBXod9B6LSbRdFH5HT6dr7b0FPyIT"
        authEndpoint: "https://test-1:8443/realms/master/protocol/openid-connect/auth"
        tokenEndpoint: "https://test-1:8443/realms/master/protocol/openid-connect/token"
        issuer: "https://test-1:8443/realms/master"
        rancherUrl: "https://rancher.gre2.com/verify-auth"
        scope: "openid profile email"
      body_format: json
      validate_certs: no
    register: response

  - name: Enable Keycloak
    ansible.builtin.uri:
      url: "https://{{ ansible_fqdn }}/v3/keyCloakOIDCConfigs/keycloakoidc?action=testAndApply"
      method: POST
      headers:
        Authorization: "Bearer {{ rancher_api_token }}"
        Content-Type: "application/json"
      body_format: json
      body:
        enabled: true
        oidcConfig:
          tokenEndpoint: "https://test-1:8443/realms/master/protocol/openid-connect/token"
          accessMode: "unrestricted"
          groupSearchEnabled: true
          groupsClaim: "groups"
          enabled: true
          baseType: "authConfig"
          type: "keyCloakOIDCConfig"
          logoutAllSupported: false
          id: "keycloakoidc"
          clientId: "rancher"
          uuid: "fe651219-adbc-427a-bf1f-ac1f8257fce1"
          clientSecret: "QzkGBXod9B6LSbRdFH5HT6dr7b0FPyIT"
          scope: "openid profile email"
          authEndpoint: "https://test-1:8443/realms/master/protocol/openid-connect/auth"
          issuer: "https://test-1:8443/realms/master"
      validate_certs: no
    register: response
```

So the original bug reported was a malformed body request.


Using inspector, in the testAndApply POST request, it sends a code obtained via interactive logon with a keycloak user.
There is a tokenEndpoint configuration but it seems it does not work as expected.
Is there a way to configure keycloak entirely via API?

Otherwise I obtain:

`"message": "[generic oidc]: server error while authenticating: oauth2: \"invalid_grant\" \"Code not valid\"",`
