### ISSUE TITLE
[RFE] SQLite backed cache: Enhance sort capabilities

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#48967]
**Is your feature request related to a problem? Please describe.**
- pre vai-cache world the ui could sort on more complex concepts like duration (1h, 2m, 3s, etc - like job duration) and cron schedule (like cronjobs schedule)
- post cache world we would like to continue support sort on these
  - a full list will be provided in https://github.com/rancher/dashboard/issues/12815

**Describe the solution you'd like**
- there might be a way to intelligible determine the type to apply a different style of sort, however that could be bug prone
- there could instead be a way to provide a specific sort mechanism as option when providing the sort column?
- could the columns be typed to allow native sorting?

**Comment by ericpromislow** [comment]
At a first guess, it's all possible but we need to explicitly add the fields we want to filter or sort on, and write translations for things like <NUM><TIME UNIT> so they sort correctly.

**Comment by richard-cox** [comment]
That sounds like the best plan for the one's we explicitly index (there should be some nice db sorting if the type is correctly defined?).

We would need to think about how to handle generically indexed fields
- labels
- schema attribute.columns (almost always resource metadata.fields array) i think mostly come with a type already, that might contain enough detail to translate to db type?

**Comment by ericpromislow** [comment]
I think the problem is due to confusion over representation vs. display. Durations should be stored as timestamps (with the value being creation time), not as human-friendly forms like "4h". Then sorting should just work™ . The human-friendly form should only be used for display.

**Comment by richard-cox** [comment]
Unfortunately we don't have control of the fields that report as durations (they're native to kube)

**Comment by ericpromislow** [comment]
See https://github.com/rancher/dashboard/issues/12815#issuecomment-3137268071 - sorting on duration fields works if they're explicitly indexed, because those fields are stored as Datetime objects in the database, and those sort naturally

**Comment by ericpromislow** [comment]
Could you be more specific on what you mean by `Cron Schedule` sorting?  

1. Which resources and which fields?

2. How are they supposed to be sorted?

    I assume that this refers to the typical 5-part at-time in a cron listing (like `20 16 * * mon,tue,wed,thu,fri`) but what's the sort order on something like this?

It's implementable in VAI using the same kind of custom function I wrote to sort IP addresses, so the client-side
notation could be something like

```
curl ... https://DOMAIN:PORT/v1/RESOURCE?sort=cron(FIELD)
```

**Comment by richard-cox** [comment]
I think something has been lost over the different issues.

It's CronJob Last Schedule/Success (status.lastScheduleTime, status.lastSuccessfulTime) that were missing, rather than the Cronjob Schedule (spec.schedule). Apologies for the confusion.

lastScheduleTime and lastSuccessfulTime are datetime strings (e.g `2025-08-07T00:05:00Z`), sorting by those should already work right?

**Comment by ericpromislow** [comment]
Sorting by `lastScheduleTime` and `lastSuccessfulTime` is just a matter of adding those fields to the `typeSpecificIndexedFields` in `pkg/stores/sqlproxy/proxy_store.go` - I'll add the QA template next.

**Comment by ericpromislow** [comment]
# QA Template

1. I've created four different cronjob templates, that schedule on different prime-number-second intervals so there's always something happening, but at different times:

cron01.json:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crontest01
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crontest01
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date -u -Iseconds; echo Hello from crontest01
          restartPolicy: OnFailure
```

cron02.json:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  # Deliberately swapping file name and object name just because
  name: crontest03 
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crontest03
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date -u -Iseconds; echo Hello from crontest03
          restartPolicy: OnFailure
```

cron03.json:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crontest02
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crontest02
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date -u -Iseconds; echo Hello from crontest02
          restartPolicy: OnFailure
```

cron04.json:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crontest04
spec:
  schedule: "*/7 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crontest04
            image: busybox:1.27
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date -u -Iseconds; echo Hello from crontest04
          restartPolicy: OnFailure
```

Note that `cron04.json` uses a different image, for sort-testing purposes...

Now load them:
```
$ for x in *.json ; do kubectl -f apply $x ; done
```

Run `kubectl get pods -w | grep cronjob`

When there are a few PODs with recent ages, run the following curl commands:
```
$ curl -skgL https://$DOMAIN/v1/batch.cronjobs'?filter=metadata.name~crontest&sort=status.lastScheduleTime,metadata.namespace,metadata.name' | jq '.data[] | [.id, .status.lastScheduleTime]'
[
  "default/crontest02",
  "2025-08-07T19:55:00Z"
]
[
  "default/crontest03",
  "2025-08-07T19:57:00Z"
]
[
  "default/crontest01",
  "2025-08-07T19:58:00Z"
]
[
  "default/crontest04",
  "2025-08-07T19:58:00Z"
]

$ 
```
curl -skgL https://$DOMAIN/v1/batch.cronjobs'?filter=metadata.name~crontest&sort=status.lastSuccessfulTime,metadata.namespace,metadata.name' | jq '.data[] | [.id, .status.lastScheduleTime]'
[
  "default/crontest02",
  "2025-08-07T19:55:00Z"
]
[
  "default/crontest03",
  "2025-08-07T19:57:00Z"
]
[
  "default/crontest01",
  "2025-08-07T19:58:00Z"
]
[
  "default/crontest04",
  "2025-08-07T19:58:00Z"
]
```

Also verify that sorting by images works (just for fun):
```
$ curl -skgL https://$DOMAIN/v1/batch.cronjobs'?filter=metadata.name~crontest&sort=spec.jobTemplate.spec.template.spec.containers.image' | jq '.data[] | [.id, .spec.jobTemplate.spec.template.spec.containers[0].image]'
[
  "default/crontest04",
  "busybox:1.27"
]
[
  "default/crontest02",
  "busybox:1.28"
]
[
  "default/crontest01",
  "busybox:1.28"
]
[
  "default/crontest03",
  "busybox:1.28"
]
```

**Comment by ericpromislow** [comment]
# QA Template with YAMLScript template

## Prerec

Install yamlscript: See https://yamlscript.org/doc/install/ - `brew is available`

## Create a template:
```
!YS-v0:
apiVersion: batch/v1
kind: CronJob
metadata:
  name:: "$(ENV.CRON_NAME)"
spec:
  schedule:: "*/$(ENV.MINUTES) * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name:: "$(ENV.CRON_NAME)"
            image:: "busybox:$(ENV.BOXNUM)"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - ! "date -u -Iseconds; echo Hello from $(ENV.CRON_NAME)"
          restartPolicy: OnFailure
```

Then create different cronjob objects by setting the busybox number to `1.xx` (looks like `xx` can be as high as 36 of this date), giving the object a unique name at `CRON_NAME`, and set `MINUTES` to the interval you want the job to run at, like so:
```
$ BOXNUM=1.27 CRON_NAME=ct10bb27t7 MINUTES=7 ys -Y cron.template | k apply -f-
$ BOXNUM=1.27 CRON_NAME=ct11bb27t5 MINUTES=5 ys -Y cron.template | k apply -f-
$ BOXNUM=1.26 CRON_NAME=ct12bb26t2 MINUTES=2 ys -Y cron.template | k apply -f-
$ BOXNUM=1.30 CRON_NAME=ct13bb30t1 MINUTES=1 ys -Y cron.template | k apply -f-
```

and then use the various sorting options from the previous section. I assume that I should be able to
use yamlscript to parse `$CRON_NAME` to calculate the values for the busybox version and
minutes interval, but I'll leave that for later.
