### ISSUE TITLE
[BUG] RKE1 downstream cluster uses the first registry in the list regardless of the is_default flag

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#48994]
**Rancher Server Setup**
- Rancher version: 2.9.3 , 2.10.1
- Installation option (Docker install/Helm Chart): any 
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any 

**User Information**
- What is the role of the user logged in? admin 

**Describe the bug**

In the RKE1 downstream cluster, multiple registry entries can be configured by editing the cluster as YAML. However, if two entries are added to the list and the second one is set as the default, Rancher will still pull images from the first registry in the list.

**To Reproduce**

- Create a node-driver RKE1 cluster, enable the private registry, and set the URL to docker.io. Notice that the following values are put in the mgmt v3 cluster object 
```
  private_registries:
    - ecr_credential_plugin: {}
      is_default: true
      url: docker.io
```
- Wait for the cluster to be active 
- Confirm that all images are pulled from the docker.io registry 
- Edit the cluster to add a 2nd registry and set it to the default 
```
  private_registries:
    - ecr_credential_plugin: {}
      is_default: false
      url: docker.io
    - ecr_credential_plugin: {}
      is_default: true
      url: registry.hub.docker.com
```
- Wait for the cluster to be active 

**Result**

All images are still pulled from the docker.io registry  

**Expected Result**

Images should be pulled from the  registry.hub.docker.com registry 

**Screenshots**

<img width="461" alt="Image" src="https://github.com/user-attachments/assets/c0573495-7915-4781-88df-0ef3b794bcdc" />

<img width="1394" alt="Image" src="https://github.com/user-attachments/assets/f6550e94-880d-49d1-9ac9-bb4fb11372b7" />

**Additional context**

- If we switch the order of the entries, all images are pulled from registry.hub.docker.com. 
- https://github.com/rancher/rancher/blob/main/pkg/cluster/private_registry.go#L48-L54 

 
SURE-9673
