### ISSUE TITLE
[BUG] Incorrect Calculation of usedLimit in Project Resource Quota

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#49041]
**Rancher Server Setup**
- Rancher version: 2.10.2
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.30
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
There are two problems here: 

1. Rancher incorrectly calculates the usedLimit in project resource quotas. The computed values under ResourceQuota.usedLimits: `limitsCpu` and `requestsCpu` are unexpectedly large. 
Rancher's controllers may modify the resourceQuota.usedLimit field on the project, increasing the value, so that later the webhook notices that the used limit is too high relative to the specified quota and issues an error. The reason Rancher increases the used value may be due to namespaces' overrides of the quota. This override, which may ask for too much of some resource, may drive up the used value of the project.

2. String values for CPU fields or without any units (limitsCpu & requestsCpu) in `usedLimit` are accepted and added to the quota, even when no namespaces exist in the project and later webhook denies it.

**To Reproduce**

Apply this Project.yaml
~~~
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: displ
  namespace: local
spec:
  clusterName: local
  containerDefaultResourceLimit: {}
  displayName: display
  namespaceDefaultResourceQuota:
    limit:
      limitsCpu: 100m
      limitsMemory: 1024Mi
      requestsCpu: 1000m
      requestsMemory: 1024Mi
  resourceQuota:
    limit:
      limitsCpu: 200m
      limitsMemory: 2048Mi
      requestsCpu: 2000m
      requestsMemory: 2048Mi
    usedLimit:
      limitsCpu: '20000000000000000'
      limitsMemory: 2048Mi
      requestsCpu: 2000m
      requestsMemory: 2048Mi

~~~

**Result**
- Rancher incorrectly calculates the usedLimit in project resource quota
- UsedLimits calculated incorrectly for new project

**Expected Result**

- usedLimit should not exceed the project resource quota
- Drop UsedLimit if project is new and has no namespaces

**Screenshots**

```
spec:
  clusterName: c-m-xxxxxx
  containerDefaultResourceLimit: {}
  displayName: xxxxxxxx
  namespaceDefaultResourceQuota:
    limit:
      limitsCpu: 1000m
      limitsMemory: 1024Mi
      requestsCpu: 1000m
      requestsMemory: 1024Mi
  resourceQuota:
    limit:
      limitsCpu: 56127m
      limitsMemory: 88495Mi
      requestsCpu: 51025m
      requestsMemory: 80450Mi
    usedLimit:
      limitsCpu: '4915000028'
      limitsMemory: '73586616768'
      requestsCpu: 1228000008628m
      requestsMemory: '17480007232'
status:
  conditions:
    - lastUpdateTime: '2024-10-28T12:17:43Z'
      status: 'True'
      type: BackingNamespaceCreated
```

**Additional context**

SURE-9711
