### ISSUE TITLE
[BUG] node driver provisioning: the tls-ca-additional secret is not appended to the generated machine-certs node drivers provisioning job

### ISSUE THREAD

**Issue by one-horned-flying** [rancher/rancher#49045]
**Rancher Server Setup**
- Rancher version: v2.10.2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): SLE Micro 6.1 base OS

**Information about the Cluster**

base cluster built with: edge-image-builder

```yaml
apiVersion: 1.1
image:
  arch: x86_64
  imageType: raw
  baseImage: SL-Micro.x86_64-6.1-Base-GM.raw
  outputImageName: k8s-mgmt.raw
kubernetes:
  version: v1.31.3+rke2r1
  network:
    apiVIP: 192.168.224.48
  nodes:
  - hostname: mgmt-node-0
    type: server
  - hostname: mgmt-node-1
    type: server
  - hostname: mgmt-node-2
    type: server
  helm:
    charts:
      - name: cert-manager
        repositoryName: jetstack
        version: v1.17.0
        targetNamespace: cert-manager-system
        createNamespace: true
        valuesFile: cert-manager.yaml
    repositories:
      - name: jetstack
        url: https://charts.jetstack.io/
operatingSystem:
  rawConfiguration:
    diskSize: 4G
  packages:
    packageList:
      - cloud-init
    sccRegistrationCode: <redacted>
```

rancher values.yaml:

```yaml
hostname: 10.10.10.10.sslip.io
additionalTrustedCAs: true
```

**User Information**
- What is the role of the user logged in? Cluster Admin

**Describe the bug**
I am using a built node driver, the `tls-ca-additional` are not appended to the `machine-certs-xxxxxxxxx...` secret created as it's passed to the node drivers provisioning job `cluster-name-pool-<rand>-machine-provision`

**To Reproduce**

**Result**
```
    Error creating machine: Error in driver during machine creation: error
    sending request: Post
    "https://stack.internal/api/call": tls: failed to
    verify certificate: x509: certificate signed by unknown authority
```

**Expected Result**
provisioning of the node with the driver success

**Screenshots**

**Additional context**

**Comment by one-horned-flying** [comment]
As a work around, when I add my internal CA certs to the end of the `tls-rancher-internal-ca` secrets `tls.crt` field in the `cattle-system` namespace the provisioning succeeds.

**Comment by one-horned-flying** [comment]
If I add:
```
ingress:
  tls:
    source: secret
privateCA: true
```
and push up a signed cert, everything works as intended. I think this only happens when there is no trusted private ca.. 
I'm assuming the `tls-ca-additional` appending to the `machine-certs-xxx` would fix the issue.
