### ISSUE TITLE
Auto Chart Bumps for Improving Rancher `vsphere-charts` Maintenance

### ISSUE THREAD

**Issue by pratikjagrut** [rancher/rancher#49086]
## **Description**  
Assess whether the recently implemented **Auto Chart Bumps** feature in the `rancher/charts` repository can help streamline the maintenance of the [rancher/vsphere-charts](https://github.com/rancher/vsphere-charts) charts.  

## **Required Changes**  
The Auto Chart Bumps feature has specific requirements that the respective Helm chart repositories must meet.  

### **Updates Needed in `rancher/vsphere-charts` Repository**  
- Create and maintain three branches corresponding to the three active Rancher releases >= v2.10.  
- The branch mappings should follow this structure:  
  ```
  Vsphere-charts Branch -> Charts Branch -> Rancher Release  
  release-v2.10 -> dev-v2.10 -> release/v2.10
  ```  
- These branches must be actively maintained, and all future updates should be made in the respective release branch.

### **Updates Needed in `charts` repo** 
- Ensure that only `package.yaml` exists in this directory—no other files should be present.
- Update `package.yaml` to match the format defined in the [Auto Chart Bumps documentation](https://github.com/rancher/charts/wiki/6%E2%80%90Auto-Chart-Bumps#packages).
- `charts/packages/rancher-vsphere/rancher-vsphere-cpi`  
 For example, `package.yaml` in the `dev-v2.10` branch should look like:  
  ```yaml
  auto: true
  url: https://github.com/rancher/vsphere-charts.git
  chartRepoBranch: release-v2.10
  subdirectory: charts/rancher-vsphere-cpi
  ```
- `charts/packages/rancher-vsphere/rancher-vsphere-csi`
   ```yaml
   auto: true
  url: https://github.com/rancher/vsphere-charts
  chartRepoBranch:release-v2.10
  subdirectory: charts/rancher-vsphere-csi
   ```
- The `chartRepoBranch` field should be updated based on branch tracking.
