### ISSUE TITLE
Epic: migrate image mirroring from bash + python + skopeo to regsync + go

### ISSUE THREAD

**Issue by adamkpickering** [rancher/rancher#49146]
I have detailed the implementation plan for this below. Note that aspects of the plan may change as development proceeds - I will do my best to keep this description updated.

There will be a file called `config.yaml` that will be used to generate `regsync` config (`regsync.yaml`). `regsync.yaml` should never be modified directly. `config.yaml` may be modified directly, or by scripts. `config.yaml` will look like this:
```yaml
Repositories:
  - BaseUrl: repo1.com/containers
    Registry: repo1.com
    Username: '{{ env "REPO1_USERNAME" }}'
    Password: '{{ env "REPO1_PASSWORD" }}'
  - BaseUrl: repo2.com/conainers
    Target: true
    Registry: repo2.com
    Username: '{{ env "REPO2_USERNAME" }}'
    Password: '{{ env "REPO2_PASSWORD" }}'
Images:
- SourceImage: directxman12/k8s-prometheus-adapter
  Tags:
  - v0.8.3
  - v0.8.4
  TargetImageName: mirrored-directxman12-k8s-prometheus-adapter
- SourceImage: grafana/grafana
  Tags:
  - 7.1.5
  - 7.2.1
  TargetImageName: grafana-grafana
```
`Repositories` specifies metadata for repositories that we will either source images from, or that we will copy images to. `Images` specifies the images that we want to mirror.

There are several reasons for using `config.yaml`:
 * It allows us to reduce duplication by generating an entry in `regsync.yaml` for each target registry for each element of `Images`.
 * It allows us to specify metadata about each image if desired in the future, such as the image origin, or which versions of Rancher use the image, or whether to include the image in mirroring (useful for if we are simply tracking images that are used by Rancher).

Next, another file, `autoupdate.yaml`, will be introduced. The purpose of this file is the same as `retrieve-image-tags/config.json`. In fact, it may be possible to reuse `retrieve-image-tags/config.json`. Either way, the purpose of this file is to describe ways to discover images/tags that must be added to `config.yaml`. This information will be used by scripts to automatically create PRs to update `config.yaml`, and thus `regsync.yaml`. Note that the current scripts do this. However, the logic is scattered over python, shell scripts and shell scripts in github actions, which is hard to maintain. Also, we want to be able to extend this easily: for example, we should be able to fetch all of the tags and images that `rancher/charts` needs and ensure that they are present in `config.yaml`.

I have planned out a zero-downtime migration from the current setup to the setup described above, and written it down in the sub-tasks of this issue.

For those wondering why I chose `regsync`: I did an investigation of `regsync` and its alternatives, and chose it for the following reasons:
* It's already used by `rancher/kontainer-driver-metadata` and `rancher/charts` (and maybe more), so at least some others in the Rancher organization understand it.
* It's mature and established.
* It's purpose-built for mirroring images, which allows for some potentially very helpful features.
* It is an external project that appears to be well-maintained, so it takes much of the work of maintaining image mirroring scripts off our plate.
