### ISSUE TITLE
[BUG] When a namespace is moved between projects, it doesn't show up in the UI

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#49259]
**Rancher Server Setup**
- Rancher version: 2.11.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: NA

**Information about the Cluster**
- Kubernetes version: NA
- Cluster Type (Local/Downstream): both
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Project member, project owner or any PRTB with namespace edit permissions.
  - If custom, define the set of permissions:

**Describe the bug**
When a namespace is moved from one project to another project, the `namespaces-edit` ClusterRole doesn't get updated right away with the right namespaces. It causes users such as `project-member` and `project-owner` to not see the namespaces in the UI.

After a while, the role seems to be reconciled and fixed, but it's not very consistent or predictable.

**To Reproduce**
1. Create a project (`project-A`)
3. Create another project (`project-B`)
4. Create a namespace in `project-A` (`ns-A`)
5. Create a namespace in `project-B` (`ns-B`)
6. Create a user
7. Give the user `project-member` to project-B
8. In the UI, move `ns-A` to `project-B`
9. Log in as the user

**Result**
They can only see `ns-B` and not `ns-A`

The `read-only` ClusterRole gets properly updated, so if you do the above, but instead give the user the role `Read-Only` to a project, they can see both `ns-A` and `ns-B`

NOTE: The controller sometimes eventually runs and reconciles this issue and will fix the ClusterRole. In my experience the controller doesn't run very often.

**Expected Result**
The `project-member` should see both `ns-A` and `ns-B` instantly.

**Additional context**

Moving a namespace just involves replacing the label and annotation referencing the project-ID with the new project. So if project-A's ID is `p-abc123` and project-B's ID is `p-xyz789`, you can move them via kubectl by changing the annotation `field.cattle.io/projectId: local:p-abc123` and the label `field.cattle.io/projectId: p-abc123` to use `p-xyz789` instead.

Pretty confident the issue is somewhere within the function `reconcileNamespaceProjectClusterRole`. Either the function itself is wrong, it's not being queued properly, or something is wrong with the caching.
https://github.com/rancher/rancher/blob/ce89133fc84b3c18beda3f4f86dc71c208e8fb5c/pkg/controllers/managementuser/rbac/namespace_handler.go#L326

The 2 ClusterRoles that get created for each project are `p-abc123-namespaces-edit` and `p-abc123-namespaces-readonly`. When the bug occurs, the `namespaces-edit` ClusterRole is missing namespaces in the rules. It should always match the list of namespaces as `namespaces-readonly`.

The rules for namespaces-edit:
```
rules:
- apiGroups:
  - management.cattle.io
  resourceNames:
  - p-jngts
  resources:
  - projects
  verbs:
  - manage-namespaces
- apiGroups:
  - ""
  resourceNames:
  - ns1
  - ns2
  - ns3
  resources:
  - namespaces
  verbs:
  - '*'
```

The rules for namespaces-get:
```
rules:
- apiGroups:
  - ""
  resourceNames:
  - ns1
  - ns2
  - ns3
  resources:
  - namespaces
  verbs:
  - get
```
