### ISSUE TITLE
[BUG] CiliumLocalRedirectPolicy CRD not installed with cilium cni

### ISSUE THREAD

**Issue by todeb** [rancher/rancher#49331]
**Rancher Server Setup**
- Rancher version: v2.8.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v2.16.8-rancher2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.15+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

cluster specs:
```
spec:
  enableNetworkPolicy: false
  kubernetesVersion: v1.28.15+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-cilium:
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        k8sServiceHost: 127.0.0.1
        k8sServicePort: 6443
        kubeProxyReplacement: true
        loadBalancer:
          enabled: true
          mode: eBPF
        localRedirectPolicy: true
      rke2-coredns:
        nodelocal:
          enabled: true
          use_cilium_lrp: true
```

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : Admin
  - If custom, define the set of permissions:

**Describe the bug**

CiliumLocalRedirectPolicy CRD is missing when using cni: cilium

**To Reproduce**

create rke2 cluster with cni: cilium 
and config:
```
rke_config {
    chart_values = <<-EOT
        rke2-cilium: #https://documentation.suse.com/cloudnative/rke2/latest/en/networking/networking_services.html
          kubeProxyReplacement: true
          k8sServiceHost: "127.0.0.1"
          k8sServicePort: 6443
          localRedirectPolicy: true
        rke2-coredns:
          nodelocal:
            enabled: true
            use_cilium_lrp: true
    EOT
```

**Result**

output from job: helm-install-rke2-coredns
```
+ echo 'Upgrading helm chart'
Upgrading rke2-coredns
+ echo 'Upgrading rke2-coredns'
+ shift 1
+ helm upgrade --set-string global.clusterCIDR=10.42.0.0/16 --set-string global.clusterCIDRv4=10.42.0.0/16 --set-string global.clusterDNS=10.43.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.43.0.0/16 --set-string global.systemDefaultIngressClass=ingress-nginx rke2-coredns /tmp/rke2-coredns.tgz --values /config/values-10_HelmChartConfig.yaml
Error: UPGRADE FAILED: resource mapping not found for name: "lrp-nodelocal" namespace: "" from "": no matches for kind "CiliumLocalRedirectPolicy" in version "cilium.io/v2"
ensure CRDs are installed first
```
```
kubectl get crd -A | grep cilium
ciliumcidrgroups.cilium.io                                        2025-03-04T15:36:44Z
ciliumclusterwidenetworkpolicies.cilium.io                        2025-03-04T15:36:45Z
ciliumendpoints.cilium.io                                         2025-03-04T15:36:44Z
ciliumexternalworkloads.cilium.io                                 2025-03-04T15:36:44Z
ciliumidentities.cilium.io                                        2025-03-04T15:36:43Z
ciliuml2announcementpolicies.cilium.io                            2025-03-04T15:36:43Z
ciliumloadbalancerippools.cilium.io                               2025-03-04T15:36:43Z
ciliumnetworkpolicies.cilium.io                                   2025-03-04T15:36:45Z
ciliumnodeconfigs.cilium.io                                       2025-03-04T15:36:43Z
ciliumnodes.cilium.io                                             2025-03-04T15:36:44Z
ciliumpodippools.cilium.io                                        2025-03-04T15:36:43Z
```

**Expected Result**

crd CiliumLocalRedirectPolicy should be installed.
