### ISSUE TITLE
[BUG] rancher-logging - newer helm charts' fluentd.security.podSecurityContext defaults to null

### ISSUE THREAD

**Issue by christianshub** [rancher/rancher#49381]
### **Rancher Server Setup**

- **Rancher version:** v2.10.1
- **Installation option:** Helm Chart (105.1.0+up4.10.0)
- **Kubernetes Cluster and version:** v1.30.7+rke2r1
- **Proxy/Cert Details:** custom certs

---

### **Information about the Cluster**

- **Kubernetes version:** v1.30.7
- **Cluster Type:** On-premises (RKE2)

---

### **User Information**

- **Role of the user logged in:** Admin

---

### **Describe the bug**

The `spec.fluentd.security.podSecurityContext` configuration in the newer rancher-logging helm charts (105.0.0+up4.8.0 and up) does not behave as expected. Whether `spec.fluentd.security.podSecurityContext` is set or not, it defaults to `null`. This has potential sideeffects such as causing Flux (with `driftdetection` enabled) to detect this as an null error:

The following is the result of running `kubectl get helmrelease -n cattle-logging-system`:

```bash
NAMESPACE               NAME                  AGE   READY   STATUS
cattle-logging-system   rancher-logging       24h   False   Could not determine release state: unable to determine cluster state: Logging/cattle-logging-system/rancher-logging-root dry-run failed (Invalid): Logging.logging.banzaicloud.io "rancher-logging-root" is invalid: spec.fluentd.security.podSecurityContext: Invalid value: "null": spec.fluentd.security.podSecurityContext in body must be of type object: "null"
```

This is due to the setting in [\_generic_logging.yaml](https://github.com/rancher/charts/blob/dev-v2.10/charts/rancher-logging/105.1.0%2Bup4.10.0/templates/_generic_logging.yaml#L29) line 29:

```yaml
{{- define "logging-operator.logging.tpl" -}}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentd:
    # omitted
    security:
      podSecurityContext:
    {{- if .Values.global.cattle.psp.enabled }}
    # omitted
```

Notice that `spec.fluentd.security.podSecurityContext` has no use or effect here.

---

### **To Reproduce**

1. Ensure you have Flux deploying the helm chart through a HelmRelease like so:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  driftDetection:
    mode: enabled
  dependsOn:
    - name: rancher-logging-crd
      namespace: cattle-logging-system
  chart:
    spec:
      chart: rancher-logging
      version: "105.1.0+up4.10.0"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
```

2. Install the Rancher Logging Helm chart. I am using version `105.1.0+up4.10.0`. But I see the issue started from `105.0.0+up4.8.0`.
3. Deploy the chart
4. Check the status of the rancher-logging-system helmrelease: `kubectl get helmrelease -n cattle-logging-system`

---

### **Result**

When `spec.fluentd.security.podSecurityContext` is not set in values.yaml, the rancher-logging helm chart renders it null instead of omitting the field or setting it as an empty object {}.

As a result, Flux drift detection fails due to an invalid `null` value, leading to an error like:

```bash
spec.fluentd.security.podSecurityContext: Invalid value: "null": spec.fluentd.security.podSecurityContext in body must be of type object: "null"
```

The setting of `spec.fluentd.security.podSecurityContext` in [\_generic_logging.yaml](https://github.com/rancher/charts/blob/dev-v2.10/charts/rancher-logging/105.1.0%2Bup4.10.0/templates/_generic_logging.yaml#L29) may result in unintended or unclear configurations. Furthermore, users implementing GitOps with Flux and DriftDetection enabled will no longer be able to deploy the rancher-logging helm chart successfully.

### **Expected Result**

`spec.fluentd.security.podSecurityContext` is not causing an object: "null" error if leveraging GitOps and Flux with DriftDetection.

### **Proposed correction**

`spec.fluentd.security.podSecurityContext` at [\_generic_logging.yaml L29](https://github.com/rancher/charts/blob/dev-v2.10/charts/rancher-logging/105.1.0%2Bup4.10.0/templates/_generic_logging.yaml#L29) is changed from

```yaml
fluentd:
  security:
    podSecurityContext:
```

to

```yaml
fluentd:
  security:
    podSecurityContext: {{- if .Values.fluentd.podSecurityContext }}{{ toYaml .Values.fluentd.podSecurityContext | nindent 6 }}{{- else }}{}{{- end }}
```

Alternatively, `fluentd.security.podSecurityContext` is omitted entirely, which may be the cleanest approach since it is not being used.

---

### **Screenshots**

N/A

### **References**

- Flux [Drift Detection](https://fluxcd.io/flux/components/helm/helmreleases/#drift-detection) is a feature that continuously checks whether the actual state of Kubernetes resources deviates from the desired state defined in Git. If a drift is detected (e.g., unexpected changes in a HelmRelease), Flux reports it and can optionally reconcile the state back to match Git.
