### ISSUE TITLE
Network issues with native containers

### ISSUE THREAD

**Issue by trivoallan** [rancher/rancher#4938]
**Rancher Version:** 

v1.1.0-dev2

**Docker Version:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**OS and where are the hosts located? (cloud, bare metal, etc):** : 

Ubuntu 16.04 in the cloud (gandi.net)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** : 

Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** : 

Cattle

**Steps to Reproduce:**

Add a custom host with existing containers created using the following docker-compose.yml : 

```
version: '2'

volumes:
  plesk-var-lib-mysql: ~
  plesk-var-www: ~
  plesk-etc-psa: ~
  plesk-etc-sw: ~
  plesk-etc-nginx: ~
  plesk-opt-psa: ~
  plesk-etc-apache2: ~
  plesk-var-lib-plesk: ~
  plesk-var-lib-psa: ~
  plesk-var-parallels: ~

services:
  plesk:
    #build: .
    image: plesk/plesk
    privileged: true
    ports:
     - "80:80"
     - "443:443"
     - "21:21"
     - "8880:8880"
     - "8443:8443"
    volumes:
      - "plesk-var-www:/var/www"
      - "plesk-var-lib-plesk:/var/lib/plesk"
      - "plesk-var-lib-psa:/var/lib/psa"
      - "plesk-var-lib-mysql:/var/lib/mysql"
      - "plesk-etc-psa:/etc/psa"
      - "plesk-etc-sw:/etc/sw"
      - "plesk-etc-nginx:/etc/nginx"
      - "plesk-opt-psa:/opt/psa"
      - "plesk-etc-apache2:/etc/apache2"
      - "plesk-var-parallels:/var/parallels"
    links:
      - mysql:mysql.1

  mysql:
    image: percona
    volumes:
      - "/opt/docker/volumes/mysql.1:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=XXX"
```

**Results:** 

There is no IP displayed on the UI for the native containers and it's impossible to add links to other services : http://i.imgur.com/FNavDPj.png

**Expected:**

I need to link the Solr service to the Plesk service (see screenshot).

Thanks in advance for your help !
