### ISSUE TITLE
[BUG] Steve AccessStore doesn't consider ServiceAccount privileges

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#49404]
**Describe the bug**

Steve caches privileges of users to avoid making SAR request to kube-apiserver. It makes privilege check available via the [AccessSetLookup](https://github.com/rancher/steve/blob/f48690210021f1d5be996593caea9a6e476e8d46/pkg/accesscontrol/access_store.go#L17) (ASL) interface. That's used in Steve and it's now also [used in the extension API server](https://github.com/rancher/rancher/blob/af56e7fa886d35cb2f464422389c4a57e2f65a17/pkg/ext/extension_apiserver.go#L222-L244) (and given to the stores).

Debugging showed that the ASL doesn't see this cluster-admin being bound to this service account. The issue is that we're not constructing the correct full name of the service account [here](https://github.com/rancher/steve/blob/f48690210021f1d5be996593caea9a6e476e8d46/pkg/accesscontrol/policy_rule_index.go#L75). So when doing the lookup, we check for system:serviceaccount:cattle-system:rancher but when populating this ASL we add an index for serviceaccount:cattle-system:rancher. Those don't match so cluster-admin does not get added to this SA's privileges.

Maybe we have the same issue with groups for serviceaccounts.. Need to investigate that more as part of this issue.

**To Reproduce**

Might be harder to reproduce without the tokens feature but something like the following should reproduce the issue:

1. Start Rancher
2. `kubectl create sa test`
3. `kubectl create clusterrole test --verb=get --resource=useractivities.ext.cattle.io`
4. `kubectl create clusterrolebinding test --serviceaccount=default:test --clusterrole=test`

**Result**

The service account is not allowed to list useractivities:

```sh
$ kubectl --as=system:serviceaccount:default:test --as-group=system:authenticated get useractivity foo
Error from server (Forbidden): useractivities.ext.cattle.io "foo" is forbidden: User "system:serviceaccount:default:test" cannot get resource "useractivities" in API group "ext.cattle.io" at the cluster scope
```

**Expected Result**

The service account is allowed to list useractivities. (Note: This command still fails because the token `foo` is not valid, but that's expected)

```sh
$ kubectl get useractivities foo
Error from server (Forbidden): useractivities.ext.cattle.io is forbidden: user system:admin is not a Rancher user
```

**Screenshots**

**Additional context**

Fixing this will fix https://github.com/rancher/rancher/issues/49342 which is bound to come back once the `tokens` work from collie is merged again.

We already have tested a fix here https://github.com/rancher/steve/pull/539 (which has been reverted because we no longer need it since tokens is being reverted). The fix has been confirmed to be working and solving that GH issue and the slow UI startup problem.

**Comment by tomleb** [comment]
## QA Testing

### Root cause

Steve uses an in-memory store for making privilege check instead of using SubjectAccessRequest (SAR) requests to kubernetes. 

The check did not account correctly for privileges (rules) bound to service accounts because we would associate the rules to subject named `serviceaccount:<namespace of service account>:<name of service account>` instead of `system:serviceaccount:<namespace of service account>:<name of service account>`.

The result of this is Steve would not find all the rules for service accounts, so service account wouldn't be able to access resources they should be able to.

Here's an example ServiceAccount / ClusterRole / ClusterRoleBinding that wouldn't work correctly before:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

### What was fixed, or what changes have occurred

We now properly compute the full name of a service account (`system:serviceaccount:<namespace of service account>:<name of service account>`) so the service account should now have the rules bound to it.

### Areas or cases that should be tested

- Making sure a RoleBinding binding a service account (subject kind == ServiceAccount) correctly apply privilege rules to that user for Steve
- Making sure a ClusterRoleBinding binding a service account (subject kind == ServiceAccount) correctly apply privilege rules to that user for Steve

### What areas could experience regressions?

I don't think it's possible for a service account to ever have the full name without the `system:` prefix, but it'd be worth having a second pair of eye to make sure we haven't made a regression by changing that name computation.

In general, anything to do with Steve's authorization check could experience regressions.
