### ISSUE TITLE
Automatically Created Network Policies for NodePort Services

### ISSUE THREAD

**Issue by jcambronero** [rancher/rancher#49430]
Hi,
We are encountering an issue with Rancher where network policies are automatically created for NodePort services when project network isolation is enabled. We would like to understand the rationale behind this behavior and explore options for customization. Specifically, we are seeking clarification and potential solutions for the following:

**Purpose of Automatically Created Network Policies:**
We can see that the automatic creation of these network policies was introduced by: https://github.com/rancher/rancher/pull/11932
Could you please explain why Rancher automatically creates network policies for NodePort services? Understanding the intended purpose and benefits of these policies will help us assess their impact on our cluster's security and functionality.

**Disabling Automatic Network Policy Creation:**
Is there a configuration setting or method to disable the automatic creation of these NodePort network policies? If not, are there any plans to introduce such a feature in future releases?

**Customizing Automatically Created Network Policies:**
We have observed that the current network policies allow traffic across namespaces in different projects, which conflicts with our requirement to restrict traffic between namespaces in different projects. Is there a way to modify the default behavior of these policies to maintain namespace isolation?

Current Configuration:
Rancher Version: 2.9.3
Kubernetes Version: 1.30.8
Network Provider: Calico
Impact: The automatic NodePort network policies are affecting our ability to enforce strict namespace isolation between projects, which is a critical security requirement for our environment.

Steps to Reproduce:
- Enable Project Network isolation.
- Create a new project. A network policy similar to this will be created to restrict traffic only from namespaces in the same project or the System project:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-default
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          field.cattle.io/projectId: p-hzjmf
    - namespaceSelector:
        matchLabels:
          field.cattle.io/projectId: p-8bth6
  podSelector: {}
  policyTypes:
  - Ingress
```
- Deploy a sample app and a NodePort service. A network policy similar to this will be created:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-api-server
  namespace: my-namespace
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: api-server
  policyTypes:
  - Ingress
```

- Note the this new policy will open traffic from any namespace as long as the incoming traffic is on port 8080.

**Expected Behavior**: We expect to have control over network policy creation to ensure that our security requirements are met, specifically maintaining strict traffic restrictions between namespaces in different projects.

Please let me know if there's any additional information that we can provide.
Thanks.
