### ISSUE TITLE
rancher-compose for windows modifies bind mount path

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#4947]
**OS and where are the hosts located? (cloud, bare metal, etc):**
- Windows workstation running Windows 7 - Rancher Compose v0.8.2 

**Steps to Reproduce:**
- Run rancher-compose up using docker-compose on the widows host.
- Ran docker-compose config, on the same windows host, using the same docker-compose file. No path modifications observed in the output.

**docker-compose.yml Stack config in Rancher:** 
```
test:
  image: microsoft/aspnet
  volumes:
  - C:\Users\dummy\vagrant:/vagrant
```

**docker-compose.yml:**
```
test:
  image: microsoft/aspnet 
  volumes:
  - /vagrant:/vagrant
```
