### ISSUE TITLE
support docker-compose version 2

### ISSUE THREAD

**Issue by Pedramrn** [rancher/rancher#4948]
This is my docker-compose.yml

```yml
version: '2'
services:
  app:
    image: pedramrn/webapp:0.1.1
    container_name: app
    ports:
      - "80:8080"
      - "5005:5005"
    networks:
      - main
    environment:
      - GRADLE_VERSION=2.10
    depends_on:
      - db-postgresql
      - db-mongo

  db-postgresql:
    image: postgres:9.5
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    networks:
      - main
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres

  db-mongo:
    image: mongo:3.2
    container_name: db-mongo
    ports:
      - "27017:27017"
    volumes:
      - data-mongo:/data/db
    networks:
      - main
    restart: always

volumes:
  data-mongo:

  data-postgresql:

networks:
  main:
```
Adding it from *add stack ui* causes this error:
`Activating (Unknown resolution for '2' using <config.RawService Value> at line 0, column 9)     `

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev3` Cattle: `v0.161.5` UI: `v1.1.3` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`environment.index`|
