### ISSUE TITLE
[2.11][chart] Add new options for Rancher default service hardening

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#49666]
## Issue: SURE-9797
This is to track some chart changes that will improve the ability to apply the workaround for certain security requirements.

This issue is for main and tracks this PR: https://github.com/rancher/rancher/pull/49537
The issue for main is here: https://github.com/rancher/rancher/issues/49665

**Comment by mallardduck** [comment]
Provided by @apoorvajagtap on the PRs, here are steps for Manual Testing.

> Assumptions:
> 
> 1. Customize the following fields in chart/values.yaml:
>    - service.disableHTTP: true
>    - ingress.servciePort: 443
>    - If ingress.servciePort is set to 443: then an annotation for nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" is included by the chart (not needed manually by user)
>    - If ingressClass is `traefik`: ingress.extraAnnotatios: {traefik.ingress.kubernetes.io/router.tls.passthrough: "true"}
>  
> 2. Install rancher using the above mentioned values.yaml:
> ```
> $ helm install rancher rancher-stable/rancher  --namespace cattle-system --create-namespace --set replicas=1 -f chart/values.yaml
> ```
> 
> 3. Ensure the following:
> - The rancher service does not have port 80 (http) block specified, only has port 443 (https-internal). (As the backend protocol is also expected to be HTTPS).
> - Ensure that backend.port.number is set to 443 in the rancher ingress. 
> - Ensure that rancher is able to establish HTTPS communication externally as well as internally.

As this is a charts change the testing will need to be done after RCs/alpha/etc is produced that includes a new chart.

**Comment by deepakpunia-suse** [comment]
**Bug Verification Details:**

* **Rancher:** v2.11.1-rc2
* **RKE2:** v1.31.8-rc1+rke2r1

1.  Customized the following fields in `values.yaml`:

    ```yaml
    service:
      disableHTTP: true
    ```

    ```
    # grep -ir -A6 'service:' rancher/values.yaml
    service:
      type: ""
      annotations: {}
      # An optional security setting to disables the HTTP port of the rancher service
      # When set true, you must also set `ingress.servicePort` to 443 and the appropriate ingress annotation to use HTTPS
      disableHTTP: true
    ```

    ```yaml
    ingress:
      servicePort: 443
    ```

    ```
    # grep -ir -B5 'servicePort' rancher/values.yaml
      # Certain ingress controllers will require the pathType or path to be set to a different value.
      pathType: ImplementationSpecific
      path: "/"
      # Backend port number; should use either: 80, or 443.
      # Must use 443 when `service.disableHTTP` is set to true.
      servicePort: 443
    ```

2.  Installed Rancher using the above mentioned `values.yaml`:

    ```
    # helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher...<snip>... --set replicas=1 --version 2.11.1-rc2 --set global.cattle.psp.enabled=false --set rancherImageTag=v2.11.1-rc2 --wait --timeout=10m --create-namespace --devel -f rancher/values.yaml
    NAME: rancher
    LAST DEPLOYED: Thu Apr 24 06:18:14 2025
    NAMESPACE: cattle-system
    STATUS: deployed
    REVISION: 1
    TEST SUITE: None
    NOTES:
    Rancher Server has been installed.
    ```

3.  Checked the following verification points:

    Checked annotation for `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` is included by the chart:

    ```
    # k get ingress -n cattle-system rancher -o yaml | grep 'nginx.ingress.kubernetes.io/backend-protocol'
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    ```

    The Rancher service does not have port 80 (http) block specified and only has port 443 (https-internal), as the backend protocol is also expected to be HTTPS.

    ```
    # k get svc -n cattle-system rancher
    NAME      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
    rancher   ClusterIP   10.43.14.4   <none>        443/TCP   8m21s
    ```

    Ensured that `backend.port.number` is set to `443` in the Rancher ingress.

    ```
    # k get ingress -n cattle-system rancher -o yaml | grep -A10 rules
      rules:
      - host: rancher.18.117.230.21.sslip.io
        http:
          paths:
          - backend:
              service:
                name: rancher
                port:
                  number: 443
              path: /
              pathType: ImplementationSpecific
    ```

    Ensured that Rancher is able to establish HTTPS communication externally as well as internally.
