### ISSUE TITLE
Custom port specified for an ingress is not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4967]
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes Environment
2. Create an ingress with a http port  and a secret 'foo' as below

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: customingresscert 
  annotations:
    scale: "2"
    https.port: "99"
spec:
   tls:
     - secretName: foo
   backend:
     serviceName: k8test1
     servicePort: 80
```

**Results:** 
The ingress lb is not accessible at the custom port 99
