### ISSUE TITLE
[Logging] Rancher logging RKE2 fluentbit pods don't get scheduled on control-plane nodes

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#49719]
By default, when installing the chart no fluentbit pods get scheduled on control-plane nodes, despite the fact that there is a toleration block for it in the chart.

This is caused by the toleration testing for a "true" value in the taint where it should actually test if it exists.

SURE-10000

**Comment by mallardduck** [comment]
The logging version this is fixed in at OB-team-charts isn't synced into Rancher charts yet.

**Comment by deepakpunia-suse** [comment]
**Bug Verification Details:**

* **Rancher:** v2.11-head
* **RKE2:** v1.31.7+rke2r1
* **Logging:** 106.0.1-rc.1+up4.10.0-rancher.4

1.  Install the Logging chart and verify the following `fluentbit` tolerations in `values.yaml`:

    ```yaml
    fluentbit:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
    ```

2.  After chart installation, confirm that the `fluentbit` pod has the specified tolerations with `operator: Exists`.

![Image](https://github.com/user-attachments/assets/a4364c13-0bad-43d2-afeb-429bd30ca83c)
