### ISSUE TITLE
On Rancher UI v2.9 most of the Cluster Tools are not shown on the Cluster Tools tab

### ISSUE THREAD

**Issue by dantalian-pv** [rancher/rancher#49743]
**Setup**
- Rancher version: v2.9.2
- Rancher UI Extensions: none
- Browser type & version: Microsoft Edge 133.0.3065.82 

**Describe the bug**
On Rancher Dashboard v2.9 most of the Cluster Tools are not shown in the list of Cluster Tools tab.

**To Reproduce**
Connect App's repositories:

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-charts
spec:
  gitBranch: release-v2.9
  gitRepo: https://git.rancher.io/charts
```
and

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-partner-charts
spec:
  gitBranch: main
  gitRepo: https://git.rancher.io/partner-charts
```

**Result**

It shows only a couple of available Cluster Tools, there is no Logging or Monitoring Tools, for example.

**Expected Result**

Should show other tools, like Logging or Monitoring.

**Screenshots**

![Image](https://github.com/user-attachments/assets/5d9a1d0b-22c0-43ba-a6d7-05cf3dc4069c)

**Additional context**

As far as I understand, the problem is in restriction of Chart.yaml.
For example, in NeuVector tool (See: https://github.com/rancher/charts/blob/release-v2.9/charts/neuvector/104.0.4%2Bup2.8.4/Chart.yaml#L5C54-L5C55) the Kubernetes server version is defined as `catalog.cattle.io/kube-version: '>=1.18.0-0 < 1.33.0-0'`, on the other hand in Rancher Logging tool (See: https://github.com/rancher/charts/blob/release-v2.9/charts/rancher-logging/104.2.0%2Bup4.8.0/Chart.yaml#L6) it is defined as `catalog.cattle.io/kube-version: '>= 1.26.0-0 < 1.31.0-0'`.

I have:
```
kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.6+rke2r1
```

Which means the tools are not shown, because they do not cover patch version, maybe it is better to change the restriction to something like `catalog.cattle.io/kube-version: '>= 1.26.0-0 < 1.32.0-0'`, because from semantic versioning definition patch version should have backward compatibility with minor version.
