### ISSUE TITLE
Cannot resolve container DNS when container is set to net host 

### ISSUE THREAD

**Issue by samattridge** [rancher/rancher#4975]
**Rancher Version:1.1.0-dev2**

**Docker Version:1.11.1**

**OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu 14.04.2 (Microsoft Azure VM)**

**Setup Details: single node rancher, internal DB**

**Environment Type: Cattle**

**Steps to Reproduce: Create two stacks: devtest1 and int1-monitoring.  In devtest1, provision a simple service running busybox or such like called 'test'.  In int1-monitoring, provision a sysdig-agent container as recommended based on the following docker compose snippet:

```
sysdig-agent:
  environment:
    ACCESS_KEY: 1234
  labels:
    io.rancher.container.dns: 'true'
    io.rancher.scheduler.affinity:host_label_ne: sysdig.exclude_sysdigcloud=true
  image: sysdig/agent:latest
  privileged: true
  volumes:
  - /var/run/docker.sock:/host/var/run/docker.sock
  - /dev:/host/dev
  - /proc:/host/proc:ro
  - /boot:/host/boot:ro
  - /lib/modules:/host/lib/modules:ro
  - /usr:/host/usr:ro
  net: host
```

(Note, use of "io.rancher.container.dns: 'true'")

Shell to the sysdig-agent container and attempt to ping test.devtest1.
**

**Results: Host does not resolve. Doing the same on a container that is not set to 'net: host' works as expected. ** 

**Expected: Expect to receive ping result. My understanding is that the DNS should at least resolve. **
