### ISSUE TITLE
When checking ssl, add in `ssl` to each backend to allow `ssl verify none`to work in global section

### ISSUE THREAD

**Issue by juandavidgc** [rancher/rancher#4977]
**Rancher Version: 1.0.2**

**Docker Version: 1.11.1**

**OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 14.04, AWS**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single node rancher**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle**

Right now I've configured a Load Balancer for a Service that has SSL:

ssl => load balancer => ssl => service

When I try to access the load balancer, the browser shows "502 Bad Gateway. The server returned an invalid or incomplete response."

I've exposed the ports of the service and it's working fine.

_docker-compose.yml_

```
lb-test:
  ports:
  - 9000:9443
  labels:
    io.rancher.loadbalancer.ssl.ports: '9000'
  tty: true
  image: rancher/load-balancer-service
  links:
  - apim-gateway:apim-gateway
  stdin_open: true
```

_rancher-compose.yml_

```
lb-test:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: Autosign
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```
