### ISSUE TITLE
[BUG] Ingress is created even with flag ingress.enabled: false

### ISSUE THREAD

**Issue by ildoc** [rancher/rancher#49855]
**Rancher Server Setup**
- Rancher version: 2.10.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): kubeadm v1.31.7
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.31.7
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

I deplyed Rancher through ArgoCD with a super simple application

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    chart: rancher
    targetRevision: 2.10.3
    helm:
      valuesObject: 
        ingress.enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      prune: true
      selfHeal: true
```

and I've noticed that the Ingress manifest is deployed even if the flag is set to false.

I'm using an HTTPRoute with the Gateway APIs to reach the ui and I don't need the ingress, so I didn't configured it.

So ArgoCD fails to sync it

**To Reproduce**

- create a test.yaml with `ingress.enabled: false`
- check the generated ingress template with
 ```
helm template rancher rancher-stable/rancher \
  --version 2.10.3 \
  --values test.yaml
```

**Result**

**Expected Result**

the ingress manifest is not generated if the flag is false (https://github.com/rancher/rancher/blob/main/chart/templates/ingress.yaml#L1)

**Screenshots**

![Image](https://github.com/user-attachments/assets/ec75b4e6-980e-4ccb-b3fc-15498e2d5131)

**Additional context**

I'm pretty noob at this, so maybe I'm doing something wrong
