### ISSUE TITLE
[RFE] Configure Storage Class based on Resource Quotas on Rancher Projects

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#49863]
**Request description:**
Configure a storage class based on resource quotas on Rancher Projects.

**Actual behavior:**
It is currently not possible to configure a storage class based on resource quotas on projects. Managing storage quotas at a namespace-level proves to be cumbersome.

**Expected behavior:**
Limit allocation/consumption of storage resources based on an associated storage class at project-level.

**Customer use-case story example**
Currently, it is possible to set a general storage quota at project-level; if a user tries to create a PVC, it is rejected.
 
Customer would like to achieve the same outcome on a quota specific to a storage class.
For example, say there are two (2) storage classes - A and B. A given user should be able to request 10GB and 20GB on storage classes A and B, respectively.
 
Now, consider a user attempting to provision a persistent volume requesting 12GB of storage using storage class A.
Rancher should generate a message indicating that the generation of this persistent volume is NOT permitted because of an exceeding quota when using storage class A.
 
If the user attempts to create the same PV via storage class B, then the request should succeed because of the 20GB quota, unless other persistent volumes exist with more than 8GB of requested storage.
 
Currently, this is only possible at namespace-level, per the official Kubernetes documentation (https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota).

**Comment by samjustus** [comment]
https://github.com/rancher/dashboard/issues/14797

**Comment by Priyashetty17** [comment]
Test scenarios for storage class specific quotas in the extended field have been validated with `v2.14-b80e630f3408512249ce27605981179c086060b1-head`

✅ Project with extended field for storageClass-specific quotas – PVC count
1. Created StorageClasses sc-a and sc-b
2. Created a Project with storageClass-specific quotas (PVC count). Verified that the Project spec reflects correct quota information
```
  resourceQuota:
    limit:
      extended:
        persistentvolumeclaims: "10"
  namespaceDefaultResourceQuota:
    limit:
      extended:
        persistentvolumeclaims: "1"
```
3. Created a namespace in the project. Verified namespace resource quota (kubectl describe ns)
4. Verified ResourceQuota in the namespace: kubectl get resourcequota
5. Created a PVC and verified it was created successfully. Verified ResourceQuota usage is accurate
6. Created another PVC in the same namespace. Verified it fails with exceeded quota error

✅Project with extended field for storageClass-specific quotas – Storage (requests.storage) (P1)
1. Created StorageClasses sc-a and sc-b
2. Created a Project with storageClass-specific quotas (requests.storage). Verified that the Project spec reflects correct quota information
```
  resourceQuota:
    limit:
      extended:
        sc-a.storageclass.storage.k8s.io/requests.storage: "100Gi"
        sc-b.storageclass.storage.k8s.io/requests.storage: "200Gi"
  namespaceDefaultResourceQuota:
    limit:
      extended:
        sc-a.storageclass.storage.k8s.io/requests.storage: "10Gi"
        sc-b.storageclass.storage.k8s.io/requests.storage: "20Gi"
```
3. Created a namespace in the project. Verified namespace resource quota (kubectl describe ns)
4. Verified ResourceQuota in the namespace: kubectl get resourcequota
5. Verified usedLimit in the Project spec is accurate
6. Created PVC on sc-a requesting 12Gi. Verified it fails with exceeded quota error
7. Created PVC on sc-b requesting 12Gi. Verify it is created successfully
8. Verified ResourceQuota usage is accurate
