### ISSUE TITLE
kube-apiserver audit events are not emitted when viewing secrets in cluster explorer

### ISSUE THREAD

**Issue by brownz11** [rancher/rancher#49899]
**Versions**
Rancher: v2.6.7
RKE2: v1.23.10+rke2r1
OS: RHEL 8.4
Kernel: 4.18.0-372.26.1.el8_6.x86_64

**Cluster Layout**
3 node HA RKE2 Cluster hosting Rancher (with 2 downstream clusters)

**Issue Description**
When Viewing Secrets in the local cluster in the Rancher Dashboard, the kube-apiserver does not emit an audit event. Viewing the secret yaml via the Cluster Explorer or doing a `kubectl get secret xyz` does emit an audit event

**Reproduction**
1. Given a Rancher v2.6.7 server
2. Ensure kube-apiserver auditing is configured to audit secret events
3. View an existing Secret via the cluster explorer on the `local` cluster (In my case I've been picking any of the default-token-abc123 secrets)
4. Observe none of the kube-apiservers emitted an audit event

**Additional Information**
A kubectl get secret will emit an audit event
View the Secret YAML via the Explorer will emit an event
Restarting all the rancher server's doesn't change the behavior
I have not tested this on downstream clusters, all config/testing has been limited to just the `local` cluster

`/etc/rancher/rke2/audit-policy.yaml` for the local cluster contains the following rule
```
- level: Metadata
    resources:
      - group: "" # core
        resources: ["secrets", "configmaps", "serviceaccounts/token"]
      - group: authentication.k8s.io
        resources: ["tokenreviews"]
```
