### ISSUE TITLE
[rancher-compose] 0.8.0 change in empty environment variables handling

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#4990]
**Rancher Version:** 1.0.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** bare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

docker-compose.yml
```yaml
service:
    image: alpine
    command: sh -c 'while true; do sleep 60; done'
    environment:
        EMPTY:
```

```sh
unset EMPTY
# download rancher-compose 0.7.4
rancher-compose up -d
# download rancher-compose 0.8.0
rancher-compose up -d
```

**Results:** 

```
time="2016-06-02T14:01:29+02:00" level=warning msg="Service service is out of sync with local configuration file" 
```
`<nil>` values instead of empty values in configuration view of service

UI stack config:
```yaml
service:
  environment:
    EMPTY: <nil>
  command:
  - sh
  - -c
  - while true; do sleep 60; done
  image: debian:jessie
```

**Expected:**

No warning.
Same behaviour as 0.7.4 (and versions before).

UI stack config:
```yaml
service:
  command:
  - sh
  - -c
  - while true; do sleep 60; done
  image: debian:jessie
```

**Comment by andyshinn** [comment]
I'd just like to point out that even when the environment variable is set on the local shell (so that it gets passed through to the container when running `rancher-compose` the values are `<nil>` as well. I expect them to be the environment variables from the shell.

**Comment by janeczku** [comment]
See https://github.com/docker/libcompose/issues/296

**Comment by deniseschannon** [comment]
Verified that it's working with v0.8.3-rc2.

```
service:
    image: alpine
    command: sh -c 'while true; do sleep 60; done'
    environment:
        EMPTY:
```
UI exported view
```
service:
  command:
  - sh
  - -c
  - while true; do sleep 60; done
  image: alpine
```

**Comment by andyshinn** [comment]
So, is https://github.com/docker/libcompose/issues/296 different than this issue?

**Comment by joshwget** [comment]
They're the same issue. The problem was in libcompose, which Rancher Compose uses.

**Comment by andyshinn** [comment]
Ah, I didn't notice it was merged in https://github.com/docker/libcompose/pull/297. Thanks!

**Comment by beatcracker** [comment]
So, how does one set an empty environment variable in using `rancher-compose`? 

I've tried:

* `docker-compose.yml`
```
environment:
    EMPTY1:
    EMPTY2: ""
    EMPTY3: ''
    EMPTY4: null
    EMPTY5:  ~
```
But it doesn't create empty variables.

It's possible to do so via UI. Adding empty variable resultsare visible in API and container:

```json
"launchConfig": {
  "environment": {
    "EMPTY1": '',
    "EMPTY2": '',
    "EMPTY3": '',
    "EMPTY4": '',
    "EMPTY5": '',
  }
```
```bash
/ # env
HOSTNAME=ba962f043e17
SHLVL=2
HOME=/root
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
EMPTY1=
EMPTY1=
EMPTY1=

```
