### ISSUE TITLE
[RFE] Access Rancher WebUI via Ingress while using BYO Certificate automated with CertManager

### ISSUE THREAD

**Issue by sam-sre** [rancher/rancher#49937]
**Is your feature request related to a problem? Please describe.**
Currently if you want to access Rancher WebUI via HTTPS and ingress, there are 3 methods for the SSL configuration as stated in below snapshot:

![Image](https://github.com/user-attachments/assets/4b88fe2a-eb60-4335-bf35-5b2d6c3c7bc0)

I'm wondering why the 3rd option `Bring your own certificate` does not support using CertManager to automate the LCM (Life Cycle Management) of the generated certificates?

**Describe the solution you'd like**
`Bring your own certificate` is an important option for isolated (AirGapped) environments where neither using Let's Encrypt nor Rancher Generated Certificates are options.
Yet, the way I understand the documentation, the `Bring your own certificate` option means creating certificates manually like it is described [here](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/add-tls-secrets) which hinders automating those certificate LCM.

CertManager can be used to create and manage a certificate. This certificate will be stored in a secret, and this secret can be passed to Rancher via the option `ingress.tls.source=secret` 
Note that this option provides flexibility for testing within AirGapped environment using selfsigned certificates for example, but more important is to test with a real private CA

**Comment by bpedersen2** [comment]
You can still use certmanager or cert-bot or... to manage the certificate, but you need a further to step so sync the secret.
One approach is using hashicorp vault + externalsecrets to deploy the cert.

**Comment by sam-sre** [comment]
@bpedersen2 Thanks for your answer..
I'm not sure why would I need the extra step?

Cert Manager will Issue the certificate and put it in a secret .. for testing I'm keeping this secret locally in etcd (no Vault)
I tried to pass this secret to Rancher WebUI via `ingress.tls.source=secret` but it did not pick it up
Am I missing something?
Below are the related resources

ClusterIssuer (Selfsigned for testing)
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
```

Certificate for Rancher WebUI
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
  namespace: cattle-system
spec:
  secretName: rancher-tls   #Secret passed to Rancher Ingress
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: rancher.local
  dnsNames:
  - rancher.local
```

Rancher WebUI Ingress 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: cattle-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: rancher.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher
                port:
                  number: 80
  tls:
  - hosts:
    - rancher.local
    secretName: rancher-tls   #Secret Created by Cert-Manager
```


BR
Sam
