### ISSUE TITLE
[BUG] kubectl with Rancher kubeconfig fails in CI/CD pipeline: system:unauthenticated or localhost:8080 fallback

### ISSUE THREAD

**Issue by hericlessssss** [rancher/rancher#49996]
## Rancher Server Setup

- **Rancher version**: v2.10.1
- **Installation option**: Helm Chart  
  - **Cluster type/version**: RKE2 v1.31.5+rke2r1
- **Proxy/Cert Details**:
  - No proxy
  - Internal certificate with custom CA (working on bastion nodes)

---

## Information about the Cluster

- **Kubernetes version**: v1.31.5+rke2r1
- **Cluster type**: Downstream
  - **Provisioning method**: Rancher with Infrastructure Provider (vSphere via node driver)

---

## User Information

- **Role**: Admin (full permissions)

---

## Describe the bug

When deploying applications using `kubectl` within a GitLab CI/CD pipeline (outside the Rancher UI), we consistently experience authentication or resolution issues when referencing the Rancher-generated kubeconfig file.

---

## To Reproduce

1. Use Rancher to generate a kubeconfig for a downstream cluster (`c-m-sfc75dww`).
2. Encode it as base64 and pass to GitLab CI via `KUBECONFIG_PROD` variable.
3. In the CI job, decode into `temp_kubeconfig`:
   ```bash
   echo "$KUBECONFIG_PROD" | base64 -d > temp_kubeconfig
   ```
4. Attempt to apply any resource using:
   ```bash
   KUBECONFIG=temp_kubeconfig kubectl apply -f ns.yaml
   ```
5. Observe one of two errors depending on the context.

---

## Result

```bash
error: error validating "STDIN": error validating data: failed to download openapi: 
{"Code":{"Code":"Forbidden","Status":403},
"Message":"clusters.management.cattle.io \"c-m-sfc75dww\" is forbidden: 
User \"system:unauthenticated\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope"}
```

or:

```bash
couldn't get current server API group list: 
Get "http://localhost:8080/api?timeout=32s": 
dial tcp [::1]:8080: connect: connection refused
```

---

## Expected Result

The decoded kubeconfig should allow `kubectl` to authenticate and connect to the correct Rancher-managed cluster from within the CI pipeline — as it does when used manually from a bastion host or local environment.

---

## Screenshots / Debug Output

```bash
$ ls -lah temp_kubeconfig
-rw-r--r-- 1 root root 3.5K Apr 23 01:58 temp_kubeconfig

$ cat temp_kubeconfig | head -n 5
apiVersion: v1
kind: Config
clusters:
- name: "producao"
  cluster:
    server: "https://rancher.memora.com.br/k8s/clusters/c-m-sfc75dww"

$ KUBECONFIG=temp_kubeconfig kubectl config get-contexts
CURRENT   NAME          CLUSTER         AUTHINFO        NAMESPACE
*         producao      producao        producao
```

---

## Additional context

We created a ServiceAccount and ClusterRoleBinding to ensure full cluster access:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: rancher
    namespace: cattle-system
```

This did not resolve the issue.

We’ve verified the kubeconfig content is valid, and it works correctly via CLI on our bastion server. But in GitLab CI runners, it consistently results in either 403 errors or fallback to localhost:8080.

---

Any help or insights would be greatly appreciated 🙏
