### ISSUE TITLE
"Start before stopping" not a zero downtime deploy

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#5000]
When upgrading a service's image and selecting "Start before stopping" I'm running into issues where my site is going offline - turning into a 502 Bad Gateway.  The point at which it shows a bad gateway, the fpm container shows 2 stopped and 2 Running containers.  To resolve this, I have to restart my nginx container.

**docker-compose**
```
nginx:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: namespace/project:nginx.91c82cc1
  links:
  - 'fpm:'
  stdin_open: true
load-balancer:
  ports:
  - 443:80
  - 80:2443
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.scheduler.affinity:host_label: domain=my-domain.com
  tty: true
  image: rancher/load-balancer-service
  links:
  - nginx:nginx
  stdin_open: true
fpm:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: namespace/project:fpm.974d73a9
  links:
  - 'database:'
  - 'redis:'
  stdin_open: true
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environment.code`|
