### ISSUE TITLE
Container for a global service failed to start in one of the host after the hosts were rebooted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5005]
Rancher Version: Build from master

Set up - 3 ROS host.

Had health check enabled global service  - driver with following definition:

```
storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  command:
  - launch-driver
  - storagepool
  image: cjellick/longhorn:dev-7022b12
driver:
  environment:
    RANCHER_CLIENT_DEBUG: 'true'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  command:
  - launch-driver
  - volumedriver
  image: cjellick/longhorn:dev-7022b12
  privileged: true
  volumes:
  - /lib/modules:/lib/modules:ro
  - /proc:/host/proc
  - /var/run:/host/var/run
  - /dev:/host/dev
  - /etc/docker/plugins:/etc/docker/plugins
  - /var/lib/rancher/longhorn:/var/lib/rancher/longhorn
```
```
storagepool:
  scale: 1
  health_check:
    port: 10241
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET /healthcheck HTTP/1.0
    healthy_threshold: 2
driver:
  health_check:
    port: 10241
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET /healthcheck HTTP/1.0
    healthy_threshold: 2
  metadata:
    VOLUME_STACK_IMAGE: cjellick/longhorn:dev-7022b12
```

All hosts had "driver" container running.

Rebooted all the 3 hosts ( not at the the same time ..but staggered by 5 minutes).
All 3 hosts got from active->reconnecting-> active as expected. But driver container failed to start in one of the hosts.
Also the service is not in Degraded state.

```
mysql> select id,name,state,created,removed, health_state from instance where name like "%driver%";
+-----+---------------------+---------+---------------------+---------------------+--------------+
| id  | name                | state   | created             | removed             | health_state |
+-----+---------------------+---------+---------------------+---------------------+--------------+
|   2 | longhorn_driver_1   | purged  | 2016-06-02 00:40:40 | 2016-06-02 16:42:32 | unhealthy    |
|   3 | longhorn_driver_2   | purged  | 2016-06-02 00:40:40 | 2016-06-02 17:02:27 | healthy      |
|   4 | longhorn_driver_3   | purged  | 2016-06-02 00:40:40 | 2016-06-02 16:41:46 | unhealthy    |
| 147 | longhorn_driver_4   | purged  | 2016-06-02 05:19:38 | 2016-06-02 16:55:40 | healthy      |
| 152 | longhorn_driver_5   | purged  | 2016-06-02 05:20:23 | 2016-06-02 05:21:44 | healthy      |
| 177 | r-longhorn_driver_2 | purged  | 2016-06-02 05:20:38 | 2016-06-02 05:21:44 | NULL         |
| 186 | longhorn_driver_5   | purged  | 2016-06-02 05:23:20 | 2016-06-02 16:50:02 | healthy      |
| 280 | longhorn_driver_3   | purged  | 2016-06-02 16:40:51 | 2016-06-02 16:41:34 | NULL         |
| 290 | longhorn_driver_1   | purged  | 2016-06-02 16:43:57 | 2016-06-02 17:02:28 | healthy      |
| 295 | r-longhorn_driver_3 | purged  | 2016-06-02 16:43:58 | 2016-06-02 16:44:32 | NULL         |
| 312 | longhorn_driver_3   | purged  | 2016-06-02 16:45:07 | 2016-06-02 17:02:27 | healthy      |
| 336 | longhorn_driver_1   | purged  | 2016-06-02 17:04:43 | 2016-06-03 05:00:15 | unhealthy    |
| 337 | longhorn_driver_2   | purged  | 2016-06-02 17:04:43 | 2016-06-02 23:09:10 | unhealthy    |
| 338 | longhorn_driver_3   | purged  | 2016-06-02 17:04:43 | 2016-06-02 18:46:40 | unhealthy    |
| 388 | longhorn_driver_3   | purged  | 2016-06-02 18:46:15 | 2016-06-02 23:09:09 | unhealthy    |
| 463 | longhorn_driver_3   | purged  | 2016-06-02 23:08:19 | 2016-06-02 23:08:50 | NULL         |
| 480 | longhorn_driver_2   | purged  | 2016-06-02 23:10:59 | 2016-06-03 16:34:32 | unhealthy    |
| 485 | r-longhorn_driver_2 | purged  | 2016-06-02 23:11:07 | 2016-06-02 23:11:18 | NULL         |
| 498 | longhorn_driver_3   | purged  | 2016-06-02 23:11:43 | 2016-06-03 16:39:47 | unhealthy    |
| 650 | longhorn_driver_1   | purged  | 2016-06-03 05:02:10 | 2016-06-03 16:39:20 | unhealthy    |
| 651 | longhorn_driver_2   | purged  | 2016-06-03 16:33:35 | 2016-06-03 16:34:27 | NULL         |
| 673 | longhorn_driver_2   | running | 2016-06-03 16:35:11 | NULL                | healthy      |
| 682 | longhorn_driver_1   | purged  | 2016-06-03 16:38:18 | 2016-06-03 16:39:07 | NULL         |
| 710 | longhorn_driver_1   | purged  | 2016-06-03 16:39:30 | 2016-06-03 16:41:28 | NULL         |
| 718 | longhorn_driver_1   | running | 2016-06-03 16:40:12 | NULL                | healthy      |
+-----+---------------------+---------+---------------------+---------------------+--------------+
25 rows in set (0.01 sec)
```
```
| 53 | driver |          5 | service | 5f2c8f89-506f-4c18-9dc2-5407de782ae6 | NULL        | active  | 2016-06-02 17:04:43 | NULL                | NULL                | {"fields":{"scale":1,"launchConfig":{"command":["launch-driver","volumedriver"],"dataVolumes":["/lib/modules:/lib/modules:ro","/proc:/host/proc","/var/run:/host/var/run","/dev:/host/dev","/etc/docker/plugins:/etc/docker/plugins","/var/lib/rancher/longhorn:/var/lib/rancher/longhorn"],"environment":{"RANCHER_CLIENT_DEBUG":"true"},"healthCheck":{"healthyThreshold":2,"interval":2000,"port":10241,"requestLine":"GET /healthcheck HTTP/1.0","responseTimeout":2000,"unhealthyThreshold":3,"strategy":"recreate"},"imageUuid":"docker:cjellick/longhorn:dev-7022b12","labels":{"io.rancher.container.agent.role":"environment","io.rancher.container.create_agent":"true","io.rancher.scheduler.global":"true","io.rancher.service.hash":"f7319460980f805a319af8026f70d74d4abd7f88"},"logConfig":{},"networkMode":"managed","pidMode":"host","privileged":true,"startOnCreate":true,"kind":"container","publishAllPorts":false,"readOnly":false,"stdinOpen":false,"tty":false,"version":"0","vcpu":1},"startOnCreate":false,"assignServiceIpAddress":false,"metadata":{"VOLUME_STACK_IMAGE":"cjellick/longhorn:dev-7022b12","io.rancher.service.hash":"9fd2f82bfe6ce48f88f57e41f0bc3467fb9ee994"},"secondaryLaunchConfigs":[],"token":"6GtFNDctzio5UcziVyBRx4sjwCkyAWFWqudbP2U4","transitioningProgress":50}} |             30 | NULL |           13 | NULL          | NULL               | NULL        | healthy      |
```
