### ISSUE TITLE
Mixed content error when behind a TLS proxy

### ISSUE THREAD

**Issue by marcaurele** [rancher/rancher#5016]
Rancher Version: v1.0.2
Docker Version: 1.10.3, build 20f81dd
OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 16.04 LTS on the cloud
Setup Details: single node rancher, internal DB
Environment Type: Cattle

**Steps to Reproduce:**
Use this docker-compose file content and try to access the UI over HTTPS.
```
version: '2'
services:
  nginx:
    image: smashwilson/lets-nginx
    environment:
      EMAIL: "<youremail>"
      DOMAIN: "<your_domain>"
      UPSTREAM: "rancher:8080"
    ports:
      - "80:80"
      - "443:443"
    links:
      - rancher
  rancher:
    image: rancher/server:v1.0.2
    ports:
      - "8080:8080"
```
The port 8080 is also exposed just to be able to check the state of the UI without TLS.

**Results:** 
The UI is blinking, and looking at the console you can see a mixed content error on a URL request over http only, which is blocked by the browser.

**Expected:**
Everything should be loaded over HTTPS
