### ISSUE TITLE
[BUG] serviceAccount impersonation by other serviceAccount through rancher proxy is not working

### ISSUE THREAD

**Issue by enneitex** [rancher/rancher#50211]
**Rancher Server Setup**
- Rancher version: v2.11.1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm

**Describe the bug**

Thanks to JWT Authentication, It is possible to interact with downstream cluster using ServiceAccount through Rancher Proxy
Thanks to https://github.com/rancher/rancher/pull/47110, It is also possible to impersonate ServiceAccount but It only works for user, It is not possible to combine the two features: A serviceAccount cannot impersonate another serviceAccount with rancher proxy.
However it works well when using the ACE of the downstream cluster

**To Reproduce**

Run Rancher with a downstream cluster where ACE is defined and JWT Authentication is enabled

Create two SA on the downstream cluster, one impersonator and one with basic rbac:
```bash
kubectl create ns demo

kubectl create serviceaccount demo-sa-impersonate -n demo
kubectl create clusterrole demo-sa-impersonate --verb=impersonate --resource=serviceaccounts
kubectl create clusterrolebinding demo-sa-impersonate --clusterrole=demo-sa-impersonate --serviceaccount=demo:demo-sa-impersonate
kubectl create token -n demo demo-sa-impersonate

kubectl create serviceaccount demo-sa -n demo
kubectl create role demo-sa -n demo --verb=list,get,watch --resource=secrets
kubectl create rolebinding demo-sa -n demo --role=demo-sa --serviceaccount=demo:demo-sa
```
Get a kubeconfig for the impersonator, in my case:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <>
    server: https://rancher.dev.local/k8s/clusters/c-8tklh
  name: kind-downstream
- cluster:
    certificate-authority-data: <>
    server: https://api.kind-downstream.dev.local
  name: kind-downstream-fqdn
contexts:
- context:
    cluster: kind-downstream
    user: kind-downstream
  name: kind-downstream
- context:
    cluster: kind-downstream-fqdn
    user: kind-downstream
  name: kind-downstream-fqdn
current-context: kind-downstream-fqdn
kind: Config
preferences: {}
users:
- name: kind-downstream
  user:
    token: <>
```

Try to impersonate demo-sa:
```bash
k --kubeconfig kubeconfig-sa-impersonator.yml config get-contexts
CURRENT   NAME                   CLUSTER                AUTHINFO          NAMESPACE
          kind-downstream        kind-downstream        kind-downstream   
*         kind-downstream-fqdn   kind-downstream-fqdn   kind-downstream     

# impersonation through ACE
kc --kubeconfig kubeconfig-sa-impersonator.yml get secret -n demo --as system:serviceaccount:demo:demo-sa
NAME          TYPE     DATA   AGE
demo-secret   Opaque   1      19m

# switch context
# impersonation through Rancher proxy
kc --kubeconfig kubeconfig-sa-impersonator.yml config use-context kind-downstream
kc --kubeconfig kubeconfig-sa-impersonator.yml get secret -n demo --as system:serviceaccount:demo:demo-sa
Error from server (Forbidden): {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-8tklh\" is forbidden: User \"system:serviceaccount:demo:demo-sa\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get secrets)
```

**Result**

**Expected Result**

same output in both case, no 403 error trying to get clusters.management.cattle.io

**Screenshots**

**Additional context**
