### ISSUE TITLE
[forwardport v2.12] [BUG] When User update values.yaml file then rancher-monitoring chart upgrade is failing with error.

### ISSUE THREAD

**Issue by rancherbot** [rancher/rancher#50291]
This is a forwardport issue for #50239, automatically created via [GitHub Actions workflow](https://github.com/rancher/rancher/actions/runs/15031376626) initiated by @rak-phillip

Original issue body:

**Rancher Server Setup**
- Rancher version: v2.11-head
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.32.1+rke2r1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**
When user tries to upgrade values of rancher monitoring 106.1.0-rc.2+up69.8.2-rancher.4 chart  via values.yaml. Chart upgrade is failing with error message

`Error: UPGRADE FAILED: template: rancher-monitoring/templates/prometheus/servicemonitor.yaml:37:36: executing “rancher-monitoring/templates/prometheus/servicemonitor.yaml” at <.Values.prometheus.prometheusSpec.routePrefix>: wrong type for value; expected string; got interface {}
`

Values.yaml
```
grafana.ini:    
  server: 
    domain: grafana.<public-ip>.sslip.io
    root_url: "%(protocol)s://%(domain)s/"
    serve_from_sub_path: true
ingress:    
  annotations: {}
  enabled: true
  hosts:
  - grafana.<public-ip>.sslip.io
  labels: {}
  path: /
  tls: []    
  ingressClassName: nginx  

```
**To Reproduce**

**Result**
rancher monitoring chart upgrade is failing.

**Expected Result**
rancher monitoring chart upgrade should be successful.

**Screenshots**

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/70c21e96-e569-4224-995e-861e721fcd2d" />
