### ISSUE TITLE
`global.fleet`, `global.cattle` and their source are not explained in the docs

### ISSUE THREAD

**Issue by nnlkcncff** [rancher/rancher#50353]
# 1

I haven't found `global.fleet` object structure complete explanation, it's only barely mentioned here:
  - https://fleet.rancher.io/ref-fleet-yaml (section `helm.values`)

It can be used in Helm values to get cluster label value using `global.cattle.clusterLabels.<label name>` syntax, but it's not mentioned if it's only for labels.

# 2

Templates (https://fleet.rancher.io/ref-fleet-yaml#templating) and `global.fleet.clusterLabels.<label name>` only fetch cluster data from `Cluster` object in `fleet.cattle.io` API, but it's not mentioned anywhere; there are other APIs with object `Cluster` such as `provisioning.cattle.io` and `management.cattle.io` which although don't contain these labels, but it's still misleading not to mention the right API.

# 3

Helm values section `global.cattle` is not explained anywhere in the docs or Rancher Charts `README.md`'s, but it make the diference in that case, so it's VERY important:
  - https://github.com/rancher/rancher/issues/41562#issuecomment-1747036459
```yaml
global:
  cattle:
    clusterId: global.fleet.clusterLabels.management.cattle.io/cluster-name
    clusterName: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
```
---

Please, reflect this information in the docs.
