### ISSUE TITLE
Unknown log opt 'gelf-compression-level' for gelf log driver

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#5046]
**Rancher Version:**  `v1.1.0-dev4`

**Docker Version:**  `1.10.3`

**OS and where are the hosts located? (cloud, bare metal, etc):** `CoreOS 1068 on Virtualbox`

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Vagrant setup for local testing

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Create a new container using the following options for logging:

![image](https://cloud.githubusercontent.com/assets/1039098/15910781/62646506-2d81-11e6-8c88-47268f2789db.png)

**Results:** 

Seeing the following log entry on the client container:

```
APIError: 500 Server Error: Internal Server Error ("unknown log opt 'gelf-compression-type' for gelf log driver")
```

**Expected:**

I have tested this configuration with docker-compose locally so I know it works.  Here is what the working definition looks like:

```
    logging:
        driver: gelf
        options:
          gelf-address: "udp://1.2.3.4:12201"
          gelf-compression-type: "gzip"
          gelf-compression-level: "1"
```

I have tried using quotes and without on the Rancher side of things but it doesn't seem to help.

**Comment by deniseschannon** [comment]
This is the v2 format of logging, which Rancher/rancher-compose doesn't support yet. https://github.com/rancher/rancher/issues/3973

We currently only support v1, which would be 

```
log_driver: gelf
log_opt:
  gelf-address: "udp://1.2.3.4:12201"
  gelf-compression-type: "gzip"
  gelf-compression-level: "1"
```
