### ISSUE TITLE
Monitoring Apps - different behaviour between Helm and Apps Install

### ISSUE THREAD

**Issue by seb-835** [rancher/rancher#50634]
Hi,

- when i install the Monitoring apps throught Rancher Management UI :
 all goes fine,   i reach  Grafana  trough Monitoring-> Grafana  and i got to the home dashboard. 

- when i install using helm : 
```
helm repo add rancher-charts https://charts.rancher.io
helm install rancher-monitoring-crd rancher-charts/rancher-monitoring-crd --version 105.2.0+up66.7.1-rancher.10 -n cattle-monitoring-system
helm install rancher-monitoring rancher-charts/rancher-monitoring --version 105.2.0+up66.7.1-rancher.10 -n cattle-monitoring-system --values=monitoring.yaml

note : monitoring.yaml is the same as the one use by apps for installation
```

Monitoring-> Grafana  bring me to the Grafana Page not found  with message :
 _We're looking but can't seem to find this page. Try returning home or seeking help on the community site._
If i click the "home link" on this page  then i get the wanted home dashboard.

What i see :

from Rancher Management UI the  grafana link is : https://rancher-xxxx/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/

while the home link proposed by the grafana page is :  https://rancher-xxxx/k8s/clusters//api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1

What can cause this behaviour ?

**Comment by seb-835** [comment]
When using Helm, 
do not forget to set those values in helm  :

```
global:
  cattle:
    clusterId:    your_cluster_Id_here
    clusterName:  your_cluster_name_here

grafana:
  grafana.ini:
    auth.anonymous:
      org_role: Admin
  sidecar:
    dashboards:
      searchNamespace: ALL
rke2ControllerManager:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx:
  enabled: true
rke2Proxy:
  enabled: true
rke2Scheduler:
  enabled: true
```
