### ISSUE TITLE
Images added via `GithubLatestRelease` update strategy do not respect `TargetImageName`

### ISSUE THREAD

**Issue by adamkpickering** [rancher/rancher#50781]
While looking at https://github.com/rancher/image-mirror/pull/985 I noticed that it created the following new entry in `config.yaml`:
```yaml
- SourceImage: registry.k8s.io/csi-vsphere/driver
  Tags:
  - v3.4.0
```
This doesn't seem right, because there is the existing entry:
```yaml
- SourceImage: registry.k8s.io/csi-vsphere/driver
  Tags:
  - v3.3.1
  - v3.4.0
  TargetImageName: mirrored-cloud-provider-vsphere-csi-release-driver
```
I did some investigation, and it turns out that this is a bug. We create `config.Image`s without ever considering if the current entry in `config.yaml` has `TargetImageName` set. We need to fix this.

I think that the way I'd approach this would be to allow the user to configure `TargetImageName` for each image in `GithubLatestRelease` in `autoupdate.yaml`. But that might change with more thought. It is important to consider how this will look for the update strategies that we have not yet migrated.
