### ISSUE TITLE
K8S Namespace does not allow same name objects 

### ISSUE THREAD

**Issue by vishal-biyani** [rancher/rancher#5079]
**Rancher Version:**
v1.1.0-dev4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Digital Ocean droplets

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

1) Create a service let's say "srv1" in "default" namespace
2) In another namespace "n2" create a service by same name "srv1"

**Results:** 
It gives an error: 
```
Error from server: error when creating "STDIN": services "frontend" already exists
```
**Expected:**

It should be able to create service by same name in different namespace.

**Comment by deniseschannon** [comment]
Verified using v1.1.0-dev4

Steps to Reproduce:
1. Create k8s environment
2. Launch `nginx-service.yml` into default namespace
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 90
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```
3. Create a new namespace, download and save the new k8s config for the new namespace
4. Try to launch `nginx-service.yml` again. 

The replication controller has no issue being created, but the service throws an error. 

```
replicationcontroller "nginx-service" created
Error from server: error when creating "nginx-service.yml": services "nginx-service" already exists
```
