### ISSUE TITLE
[BUG] Docker in Docker image cannot access api.nuget.org

### ISSUE THREAD

**Issue by sjacquier-coexya** [rancher/rancher#50828]
**Rancher Server Setup**
- Rancher version: 2.11
- Installation option (Docker install/Helm Chart): I don't know
- Proxy/Cert Details: No proxy

**Information about the Cluster**
- Kubernetes version: 1.32.4
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
- I have all the rights inside my namespaces. I can't access anything outside of my namespaces, but my issue is 100% contained inside one of my namespaces.

**Describe the bug**
Today we installed Docker in Docker in a Kubernetes Cluster v1.32.4, operated witch Rancher 2.11 (calico).
The issue has been reproduced with docker:28.2.2-dind and docker:20.10-dind pods.

We create a container inside this dind. The issue I will describe has been reproduced on mcr.microsoft.com/dotnet/sdk:8.0 and on alpine/alpine:latest containers. 

Inside this countainer, we simply try different curl commands :
- curl https://www.google.com : works without any issue.
- curl https://www.nuget.org : works too
- curl https://api.nuget.org : timeout error after 100000ms :

```
root@55891c3b3336:/testrestore# curl -v https://api.nuget.org/v3/index.json
*   Trying 13.107.253.61:443...
* Connected to api.nuget.org (13.107.253.61) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to api.nuget.org:443
* Closing connection 0
curl: (35) Recv failure: Connection reset by peer
```

This cannot be a certificate nor a cipher issue, as www.nuget.org and api.nuget.org have the same certificates and accept the same ciphers.

curl https://api.nuget.org does work on any pod of the cluster, and also in dind, but not in any container created inside of dind.
And like I said, all the other websites works, there is no TLS issue... We have no idea what it would happen.

One of our few guesses would be that a middle agent does not forward the Server Hello response to the container, for a security or configuration issue. 

**To Reproduce**
1. Deploy this : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind-docker
  template:
    metadata:
      labels:
        app: dind-docker
    spec:
      containers:
        - name: dind-docker
          image: docker:28.2.2-dind
          command:
            - "dockerd"
            - "--host=unix:///var/run/docker.sock"
            - "--host=tcp://0.0.0.0:2376"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
            limits:
              cpu: "4000m"
              memory: "16Gi"
          ports:
            - containerPort: 2376
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}
```
2. Connect to the pod and run these commands : 
```
docker run --rm -it alpine
curl -v https://api.nuget.org/v3/index.json
```

**Result**

```
*   Trying 13.107.253.61:443...
* Connected to api.nuget.org (13.107.253.61) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Recv failure: Connection reset by peer
* OpenSSL SSL_connect: Connection reset by peer in connection to api.nuget.org:443
* Closing connection 0
curl: (35) Recv failure: Connection reset by peer

```

**Expected Result**

```
* Host api.nuget.org:443 was resolved.
* IPv6: 2620:1ec:29:1::61
* IPv4: 13.107.253.42
*   Trying [2620:1ec:29:1::61]:443...
* Immediate connect fail for 2620:1ec:29:1::61: Network unreachable
*   Trying 13.107.253.42:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1): 
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / secp256r1 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=*.nuget.org     
*  start date: Jun 17 15:13:42 2025 GMT
*  expire date: Dec 14 15:13:42 2025 GMT
*  subjectAltName: host "api.nuget.org" matched cert's "*.nuget.org"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 03
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha384WithRSAEncryption
*   Certificate level 1: Public key type RSA (4096/152 Bits/secBits), signed using sha384WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to api.nuget.org (13.107.253.42) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://api.nuget.org/v3/index.json
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: api.nuget.org]
* [HTTP/2] [1] [:path: /v3/index.json]
* [HTTP/2] [1] [user-agent: curl/8.14.1]
* [HTTP/2] [1] [accept: */*]
> GET /v3/index.json HTTP/2
> Host: api.nuget.org
> User-Agent: curl/8.14.1
> Accept: */*
>
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 200
< date: Wed, 25 Jun 2025 19:01:41 GMT
< content-type: application/json
< content-length: 9272
[.......]
```

**Additional context**
Actually, this worked a week ago, but an electrical outage forced us to reinstall and reconfigure some things in the cluster and today it does not work anymore.
We observed some weird changes to the Network Policies but I saw nothing that should conflict with this.

Have a good day and thanks for your help !
