### ISSUE TITLE
[BUG] Kubeconfig API fails with pem error for ACE clusters: creation fails with FQDN, usage fails without FQDN

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#50855]
**Rancher Server Setup**
- Rancher version: `v2.12-45db8e5baaff593ffbd40e6a8c8a40b59faabb7c-head` 
- Installation option (Docker install/Helm Chart): any

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): local and downstream

**User Information**
- What is the role of the user logged in? Admin

NOTE: This issue was observed during the validation of **Imperative Kubeconfigs API**

**Describe the bug**
For ACE clusters, the kubeconfig generated via the Kubeconfig API fails to work due to certificate issues

**To Reproduce**
1. Create a Rancher instance with v2.12-head.
2. Create two ACE downstream clusters - aceCluster1 (without FQDN), aceCluster2 (with FQDN).
3. As an admin, create a kubeconfig for aceCluster1 (without FQDN):
    ```
    kubectl create -o jsonpath='{.status.value}' -f -<<EOF > ace_ds_config.yaml
    apiVersion: ext.cattle.io/v1
    kind: Kubeconfig
    metadata:
      name: ace-downstream-kubeconfig
    spec:
       clusters: ["c-m-ace1"]  # Replace with actual ACE cluster ID
       description: "Create kubeconfig - ACE downstream"
    EOF
    ```
4. Verify that the file ace_ds_config.yaml is not empty.
5. Validate Kubeconfig content. 
    - Includes apiVersion, clusters, users, contexts
    - server URL is of the format: https://<control-plane-node-IP>:6443
    - status.summary is "Complete"
    - status.tokens contains one token
    - metadata.ownerReferences points to the backing token
 6. Verify Backing Token is created
 7. Verify Backing ConfigMap is created in the cattle-tokens namespace
 8. Attempt to list pods using the generated kubeconfig: kubectl get pods -A --kubeconfig=ace_ds_config.yaml

**Expected result:** 
The output should list all pods from all namespaces in the downstream ACE cluster.

**Actual result:** 
Fails with an error:
```
$ k get pods -A --kubeconfig=ace_ds_config.yaml
error: unable to load root certificates: unable to parse bytes as PEM block
```

**Note:** 
 - For the other ACE cluster "aceCluster2" (with FQDN configured but no certs provided), I get the same certificate parsing error ^^ but this time while creating the kubeconfig yaml:
```
$ kubectl create -o jsonpath='{.status.value}' -f -<<EOF > ace2_ds_config.yaml
> apiVersion: ext.cattle.io/v1
> kind: Kubeconfig
> metadata:
>   name: ace2-downstream-kubeconfig 
> spec:
>   clusters: ["c-m-jvvvzj9q"]
>   description: "Create kubeconfig - ACE downstream2"
> EOF
error: unable to load root certificates: unable to parse bytes as PEM block
```

 - I downloaded the kubeconfig for both the ACE clusters using the UI and was able to use those kubeconfigs to list pods successfully.
 - This issue does not occur with non-ACE downstream clusters - kubeconfig YAMLs work as expected.
