### ISSUE TITLE
loadbalancer not working properly and generating wrong ha config

### ISSUE THREAD

**Issue by ionutalexandruisac** [rancher/rancher#5131]
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
1.11.1 and 1.10.3 (2 hosts)

**OS and where are the hosts located? (cloud, bare metal, etc):**
2 hosts, both bare metal, one running Ubuntu 16.04 and the other Ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher & external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (v0.161.5)

**Steps to Reproduce:**
Trying to create 1 loadbalancer on 2 hosts for 3 services (database, redis and rabbitmq) running again on both hosts.
Database running on port 3306, redis on port 6379 and rabbitmq on port 5672.
The loadbalancer should take requests coming from an "app" container running on both hosts and forward them to the database, redis or rabbitmq containers based on the port used by the request.
![lb](https://cloud.githubusercontent.com/assets/16538993/16073849/c30ce38e-32df-11e6-888b-54f15bbcb202.png)

**Results:** 
Doesn't work. The docker-compose seems to be alright, but the haconfig seems to be very wrong(instead of mapping each port to the corresponding service which runs on 2 hosts - so 2 containers-, it maps each port to each service and each container.)

**docker-compose**
```
lb-services:
  expose:
  - 3306:3306/tcp
  - 5672:5672/tcp
  - 6379:6379/tcp
  labels:
    io.rancher.loadbalancer.target.database: 3306=3306
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.rabbitmq: 5672=5672
    io.rancher.scheduler.affinity:host_label: app.api=true
    io.rancher.loadbalancer.target.redis: 6379=6379
  tty: true
  image: rancher/load-balancer-service
  links:
  - database:database
  - redis:redis
  - rabbitmq:rabbitmq
  stdin_open: true

```

**ha config**
```
global
    log 127.0.0.1 local0
        log 127.0.0.1 local1 notice
        maxconn 4096
        maxpipes 1024
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log    global
    mode    tcp
    option    tcplog
        option  dontlognull
        option  redispatch
        option http-server-close
        option forwardfor
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend c228acd3-a969-4823-9234-c1f180983e1c_5672_frontend
        bind *:5672 
        mode tcp

        default_backend c228acd3-a969-4823-9234-c1f180983e1c_5672_0_backend

backend c228acd3-a969-4823-9234-c1f180983e1c_5672_0_backend
        mode tcp
        server 8d27b362-ad44-40af-8acd-3a2a75480e6e 10.42.177.51:5672
        server 79ee21c1-d19a-437f-8654-42cd1d11a8d4 10.42.100.132:5672
        server 0845d20f-688b-47c6-b1d6-c52d636e166e 10.42.16.240:5672
        server 81381ba3-6b53-4048-a94b-19d4082506ff 10.42.254.140:5672
        server 3053cf2c-1454-4a95-a5a3-917bf06f0ec5 10.42.216.146:5672
        server 7b981b0e-a37a-45a3-82c2-b917633c8244 10.42.252.80:5672

frontend c228acd3-a969-4823-9234-c1f180983e1c_6379_frontend
        bind *:6379 
        mode tcp

        default_backend c228acd3-a969-4823-9234-c1f180983e1c_6379_0_backend

backend c228acd3-a969-4823-9234-c1f180983e1c_6379_0_backend
        mode tcp
        server 8d27b362-ad44-40af-8acd-3a2a75480e6e 10.42.177.51:6379
        server 79ee21c1-d19a-437f-8654-42cd1d11a8d4 10.42.100.132:6379
        server 0845d20f-688b-47c6-b1d6-c52d636e166e 10.42.16.240:6379
        server 81381ba3-6b53-4048-a94b-19d4082506ff 10.42.254.140:6379
        server 3053cf2c-1454-4a95-a5a3-917bf06f0ec5 10.42.216.146:6379
        server 7b981b0e-a37a-45a3-82c2-b917633c8244 10.42.252.80:6379

frontend c228acd3-a969-4823-9234-c1f180983e1c_3306_frontend
        bind *:3306 
        mode tcp

        default_backend c228acd3-a969-4823-9234-c1f180983e1c_3306_0_backend

backend c228acd3-a969-4823-9234-c1f180983e1c_3306_0_backend
        mode tcp
        server 8d27b362-ad44-40af-8acd-3a2a75480e6e 10.42.177.51:3306
        server 79ee21c1-d19a-437f-8654-42cd1d11a8d4 10.42.100.132:3306
        server 0845d20f-688b-47c6-b1d6-c52d636e166e 10.42.16.240:3306
        server 81381ba3-6b53-4048-a94b-19d4082506ff 10.42.254.140:3306
        server 3053cf2c-1454-4a95-a5a3-917bf06f0ec5 10.42.216.146:3306
        server 7b981b0e-a37a-45a3-82c2-b917633c8244 10.42.252.80:3306


listen default
    bind *:42
```

**
