### ISSUE TITLE
Upgrade Create/Stack from CI server?

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5190]
**Rancher Version:** v1.1.0-dev1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've setup my Gitlab CI to create a docker image of a project and push it to a private registry.
The next step would be deploying the image in the form of a Rancher stack or upgrading an existing one.

`rancher-compose` is not available on my CI runner as its just a docker-container.

How would I do this from the CI server?

**Comment by dj-hedgehog** [comment]
I found out I can use any Docker image in my CI for the various built-steps so I'm using an image which contains `rancher-compose` for deployment.

The CI-definition looks like this:
```
deploy_test:
  stage: deploy
  image: monostream/rancher-compose:latest
  script:
    - rancher-compose --url "http://rancher.example.com:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --project-name test --file ci/docker-compose.yml --verbose up --upgrade --pull
```


The only issue is that Rancher can't pull from my private registry. I opened a new issue for that: https://github.com/rancher/rancher/issues/5198
