### ISSUE TITLE
LoadBalancer with https port redirecting to wrong service

### ISSUE THREAD

**Issue by MaxNoe** [rancher/rancher#5207]
**Rancher Version:**
1.1.0-dev3
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
4 BareMetal Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Master / internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Run More than one webservice using https with a loadbalancer listenting on port 443
**Results:** 
The loadbalancer sometimes redirects to the wrong service. 
**Expected:**
Correct routing.

We have a custom gitlab, a catalog registry (without the loadbalancer, because we have the global one) and another webservice.

The loadbalancer definition is:
```
loadbalancer-https:
  ports:
  - 443:443/tcp
  external_links:
  - git/gitlab:gitlab
  - fact-aux/auxservice:auxservice
  - registry/sslproxy:sslproxy
  labels:
    io.rancher.loadbalancer.target.git/gitlab: git.e5.physik.tu-dortmund.de:443=443
    io.rancher.scheduler.affinity:host_label: role=master
    io.rancher.loadbalancer.target.fact-aux/auxservice: auxdb.app.tu-dortmund.de:443=443
    io.rancher.loadbalancer.target.registry/sslproxy: registry.e5.physik.tu-dortmund.de:443=443
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```

Any idea why this is happening? It also seems to just affect the loadbalancer on port 443.
