### ISSUE TITLE
/var/run/docker.sock not mounted correctly in docker 1.11.2

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5209]
**Rancher Version:** 1.1.0 dev 1
**Docker Version:** 1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**single node, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

This `docker-compose.yml`:

```
gitlab-runner:
  log_driver: ''
  labels:
    io.rancher.sidekicks: gitlab-runner-data
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: system=test
  log_opt: {}
  image: gitlab/gitlab-runner:alpine
gitlab-runner-data:
  log_driver: ''
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: system=test
  entrypoint:
  - /bin/true
  log_opt: {}
  image: gitlab/gitlab-runner:alpine
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /srv/gitlab-runner/config:/etc/gitlab-runner
```

**Results:** 

When building with the CI-runner:
`Get http://unix.sock/v1.18/version: dial unix /var/run/docker.sock: connect: no such file or directory`
The file isn't mounted properly inside the container.
This worked with docker 1.9.1 on the host.

**Expected:**

`/var/run/docker.sock` being accessible from the container.
I need to mount the docker socket because the build runner is using Docker-in-Docker.
