### ISSUE TITLE
Stacks could not create success

### ISSUE THREAD

**Issue by MadeInChina** [rancher/rancher#5212]
**Rancher Version:**
     v1.1.0-dev5
**Docker Version:**
   Docker version 1.11.1, build 5604cbe

**OS and where are the hosts located? (cloud, bare metal, etc):**
    Mac
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
    1.dao pull rancher/server
    2.docker run -d --restart=always -p 8888:8080 --name rancher-server rancher/server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
    Cattle
**Steps to Reproduce:**
    1.dao pull rancher/server
    2.docker run -d --restart=always -p 8888:8080 --name rancher-server rancher/server

    3.create stack with name es with yml:
     

```
elasticsearch_master:
    image: slamhan/elasticsearch:latest
    command: "elasticsearch -Des.cluster.name=es-cluster -Des.node.master=true -Des.node.data=false"
    environment:
       - ES_HEAP_SIZE=512m
    ports:
      - "9200:9200"
      - "9300:9300"

elasticsearch1:
    image: slamhan/elasticsearch:latest
    command: "elasticsearch -Des.cluster.name=es-cluster -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master"
    links:
      - elasticsearch_master
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m
elasticsearch2:
    image: slamhan/elasticsearch:latest
    command: "elasticsearch -Des.cluster.name=es-cluster -Des.discovery.zen.ping.unicast.hosts=elasticsearch_master"
    links:
      - elasticsearch_master
    volumes:
      - "/opt/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m
```

**Results:** 
Activating (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, fieldName=name] from [http://localhost:8080/v1/projects/1a5/services])

http://192.168.99.100:8888/v1/projects/1a5/services could access but not http://localhost:8080/v1/projects/1a5/services i thought this is the issue.
**Expected:**
Create stack success without error
