### ISSUE TITLE
IP address fails to be injected for the ingress when it is created in a namespace that has "-"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5213]
Rancher Version: v1.1.0-dev5

Steps to reproduce the problem:

Create a namespace - "ingress-test" ( with "-" in it)
Created 2 services and ingress rule in this namespace.
Ingress gets created successfully and i also see the lb-ingress instance being programmed for the rules. But IP inject on the ingress object fails

<img width="462" alt="screen shot 2016-06-21 at 9 44 06 am" src="https://cloud.githubusercontent.com/assets/4266958/16238319/f797c452-3794-11e6-95cc-905a85bdd0e4.png">

ingress-controller logs:
```
6/21/2016 9:41:51 AMtime="2016-06-21T16:41:51Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"ingress-test\", Name:\"ingress1\", UID:\"0ded6334-37cf-11e6-9fbe-020842bc4153\", APIVersion:\"extensions\", ResourceVersion:\"17637\", FieldPath:\"\"}): type: 'Normal' reason: 'CREATE' ingress-test/ingress1"
6/21/2016 9:41:51 AMtime="2016-06-21T16:41:51Z" level=info msg="LB [ingress-test-ingress1] is not ready yet, skipping endpoint update"
```

controller-manager.logs
```
6/21/2016 9:41:35 AMI0621 16:41:35.967148       1 rancher.go:107] GetLoadBalancer [lb-a04c8989237cf11e69fbe020842bc415] [Region1]
6/21/2016 9:41:36 AMI0621 16:41:36.473839       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"ingress-test", Name:"k8testrc1", UID:"04deea8e-37cf-11e6-9fbe-020842bc4153", APIVersion:"v1", ResourceVersion:"17581", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc1-5s4pd
6/21/2016 9:41:36 AMI0621 16:41:36.562793       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"ingress-test", Name:"k8testrc1", UID:"04deea8e-37cf-11e6-9fbe-020842bc4153", APIVersion:"v1", ResourceVersion:"17581", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc1-q8kec
6/21/2016 9:41:45 AMI0621 16:41:45.799788       1 rancher.go:107] GetLoadBalancer [lb-a0a9f83e437cf11e69fbe020842bc415] [Region1]
6/21/2016 9:41:45 AMI0621 16:41:45.888499       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"ingress-test", Name:"k8testrc2", UID:"0ab11629-37cf-11e6-9fbe-020842bc4153", APIVersion:"v1", ResourceVersion:"17611", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc2-yl72z
6/21/2016 9:41:45 AMI0621 16:41:45.892203       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"ingress-test", Name:"k8testrc2", UID:"0ab11629-37cf-11e6-9fbe-020842bc4153", APIVersion:"v1", ResourceVersion:"17611", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc2-gmgz5
6/21/2016 9:43:47 AMI0621 16:43:47.089384       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/21/2016 9:43:47 AMI0621 16:43:47.093599       1 servicecontroller.go:298] LB doesn't need update for service ingress-test/k8test1
6/21/2016 9:43:47 AMI0621 16:43:47.145147       1 servicecontroller.go:298] LB doesn't need update for service ingress-test/k8test2
```

```
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat service2_ingress.yml
apiVersion: v1
kind: Service
metadata:
 name: k8test2
 labels:
   k8s-app: k8test2-service
spec:
 ports:
 - port: 80
   targetPort: 80
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test2-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc2
spec:
 replicas: 2
 selector:
   k8s-app: k8test2-service
 template:
   metadata:
     labels:
       k8s-app: k8test2-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 80
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat service1_ingress.yml
apiVersion: v1
kind: Service
metadata:
 name: k8test1
 labels:
   k8s-app: k8test1-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test1-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc1
spec:
 replicas: 2
 selector:
   k8s-app: k8test1-service
 template:
   metadata:
     labels:
       k8s-app: k8test1-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat ingress_1.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress1
spec:
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /service3.html
       backend:
         serviceName: k8test1
         servicePort: 81
     - path: /name.html
       backend:
         serviceName: k8test2
         servicePort: 80
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ 
```
