### ISSUE TITLE
Is there a way to create global LB with kubernetes ingress?

### ISSUE THREAD

**Issue by qkos** [rancher/rancher#5240]
At the moment you can scale the LB for kubernetes ingress via the `scale` annotation. I have a use case where I am using an autoscaling group for my kubernetes environment and I have an ELB attached to it. The UI allows creating LB with global scale that spins up a container on each host.

It seems like currently the [ingress-controller](https://github.com/rancher/ingress-controller) does not support this.

At the moment I am using the ingress-controller independently on the stable rancher build. Any chance this can be included in 1.1.0?

@alena1108 would you be able to comment on this perhaps?

**Comment by deniseschannon** [comment]
@mechatama We have already released 1.1, but I've changed this as an enhancement request. If others are interested in this concept, we can look into prioritizing it.

**Comment by LoicMahieu** [comment]
@deniseschannon I think some people, including me, is really interested on more control of the `ingress-controller.
See:
 - https://github.com/rancher/rancher/issues/6344
 - https://github.com/rancher/rancher/issues/5999

**Comment by omegarus** [comment]
+1

**Comment by qamalbcgdv** [comment]
👍

**Comment by wlan0** [comment]
This feature has been added since v1.4.0-rancher release of kubernetes

Ensure that you have more than one host added to rancher

Steps to test:

1. create the reference RC and Service shown below.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```

2. Using this reference ingress definition, create the ingress controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.scheduler.global: "true"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

This will create the lb service globally. Check that the lb-service container gets launched on every host by checking the host view in rancher UI.
