### ISSUE TITLE
Rancher doesn't resolve hostnames of other containers in the same stack

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5247]
**Rancher Version:** v1.1.0-dev5
**Docker Version:** 1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've got a Node application which tries to connect to the host `db`. It works when started using `docker-compose` but not in Rancher. There the host `db` resolves to `db.<hostname>.com`. Hostname is the name of the host the containers are running on as reported by the OS.

**How can I solve this problem?**

Here's the `docker-compose.yml` I use.
```
backend:
  image: my.registry.com/node-backend:latest
  links:
    - 'db:db'
  ports:
    - 1337:1337/tcp
  labels:
    io.rancher.sidekicks: db
    io.rancher.container.pull_image: always

db:
  image: postgres:latest
  environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=1234abcd
```

For some reason the `links` keyword is stripped from the `docker-compose.yml` which is deployed. This is the one I see when I go to the stack and `view config`

```
db:
  environment:
    POSTGRES_PASSWORD: 1234abcd
    POSTGRES_USER: myuser
  image: postgres:latest
backend:
  ports:
  - 1337:1337/tcp
  labels:
    io.rancher.sidekicks: db
    io.rancher.container.pull_image: always
  image: my.registry.com/node-backend:latest
```

**Comment by deniseschannon** [comment]
How are you deploying the services? Using rancher-compose? Adding the docker-compose.yml into when you create a new stack? Individually creating services?

**Comment by dj-hedgehog** [comment]
I'm deploying via my CI server with this command:

```
rancher-compose --url "http://rancher.storyx.company:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --project-name my-test --file ci/docker-compose.yml --verbose up -d --upgrade
```

I also tried doing it manually via the UI (both services at once but the result was the same.
For now I'm using `retain_ip: true` on the db container but this isn't really a solution.

Oh, this is my `rancher-compose.yml`
```
db:
  scale: 1
  retain_ip: true
backend:
  scale: 1
  retain_ip: true
```
