### ISSUE TITLE
kubectl created ConfigMaps do not receive specified keys/values

### ISSUE THREAD

**Issue by nrvale0** [rancher/rancher#5293]
**Rancher Version:**
v1.1.0-dev5

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 on Digital Ocean. All latest patches.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Feed the following k8s manifest to Rancher via both local kubectl and via kubectl console in Rancher console.

https://github.com/nrvale0/rancher-k8s-puppet/blob/c689816316ec60ac9d38341f7fd196c825a79436/kubernetes-templates/puppet-standalone/0/cm-puppetserver-standalone.yml

```YAML
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-puppetserver-standalone
  namespace: default
data:
  controlrepo.git.uri: "from cm-puppetserver-standalone.yml"
```

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Feed this manifest to Rancher via local kubectl.
2. Note that the ConfigMap with specified key/value is present
3. Delete the ConfigMap
4. Feed this manifest via the kubectl in Rancher Console
5. Note that ConfigMap is present but specified key/value is *not* present.

Note that the last behavior can be reproduced by attempting to create the ConfigMap via a Kubernetes Catalog entry

**Results:** 
See above.

**Expected:**
In all scenarios, expect the ConfigMap to be created with the specified key(s)/value(s).
