### ISSUE TITLE
K8's Replication Controller Tabs Positioning Off

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#5307]
The tabs in the K8's replication controller page are positioned incorrectly. I've included a screen shot and a sample RC yaml file for you @lvuch 

<img width="1355" alt="screenshot 2016-06-30 15 53 05" src="https://cloud.githubusercontent.com/assets/858614/16506963/f6decb26-3eda-11e6-826e-577361a52096.png">

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: nginx
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
