### ISSUE TITLE
Rancher doesn't resolve container hostnames on CentOS 7 hosts

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5351]
**Rancher Version:** v.1.1.0dev5
**Docker Version:** 1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS 7 on vServer
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher with internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 

- Create a stack with multiple containers
- execute `getent hosts othercontainername` inside a container

**Results:** 
`46.45.233.210   containername.megasrv.de`

**Expected:**
`10.42.79.247    containername.stackname.stackname.rancher.internal`

This problem occurs only on CentOS 7 hosts which I set up freshly. Two other Ubuntu hosts don't show this behaviour.
I also restarted the agents with `CATTLE_AGENT_IP="public IP" but it still doesn't work.

Could this be related to https://github.com/rancher/rancher/issues/5303 ? I'm seeing the same issue as described in the bug for the hosts which can't resolve hostnames.

**Comment by vincent99** [comment]
This is a combination of several things...

- Your host has a search path of `megasrv.de` set
- `megasrv.de` returns an answer no matter what you ask for
- We apply that search path to containers, putting yours before ours (`rancher.internal, <servicename>.rancher.internal, <stackname>.rancher.internal`).
- When you ask for an unqualified name in CentOS (e.g. `containername` vs a fully-qualified name ending in a dot like `containername.`), it tries the search paths **first**, before trying the unqualified name as-given.

The net result is the first DNS question sent to us is for `containername.megasrv.de`, that's not our domain so we recurse it up to the resolver configured on the host, and it returns an answer so we're done.

Other OSes generally send the original question as-asked first (`containername.`), which we would find an answer for.  Or if `megasrv.de` didn't have a wildcard and answer for any name it would fail and then move on to the next search path.  But the combination of all these means the answers are always wrong.

To fix you can:
 - Remove `megasrv.de` from the search path on the host
 - Make `*.megasrv.de` not be a wildcard, if it's your domain
 - Always ask qualified questions (`containername.`, or `containername.stackname.rancher.internal`)
 - Or possibly muck with nsswitch.conf to change the handling of search paths

Or we could put the rancher search paths before the user ones, but that causes other issues...

**Comment by dj-hedgehog** [comment]
Thanks for pointing this out.
How can I modify the search path on the host? I removed the `megasrv.de` entry from `/etc/hosts` but that doesn't suffice.

**Comment by vincent99** [comment]
There are docker daemon command line or config options depending on the OS (https://docs.docker.com/engine/reference/commandline/dockerd/) for DNS resolver and search path.  When not specified the host's /etc/resolv.conf is used, but editing it doesn't affect currently running containers so you'd have to restart them.

**Comment by dj-hedgehog** [comment]
I restarted them all after removing the search-domain so it must be something different. I noticed one strange thing.

I've got a stack which contains a `frontend` and a `backend` container (the latter one with a DB sidekick). When I execute `getent hosts backend` in the **frontend**-container it resolves to the container IP.
When I execute `getent hosts frontend` in the **backend**-container it resolves to the search-domains IP.
This is the full `docker-compose.yml` I use:

```
db:
  environment:
    POSTGRES_PASSWORD: 1234abcd
    POSTGRES_USER: myuser
  image: postgres:latest
backend:
  ports:
  - 1337:1337/tcp
  environment:
    NODE_ENV: production
  labels:
    io.rancher.sidekicks: db
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: system=test
  image: myregistry.com/project/backend:latest
frontend:
  environment:
    API_HOST: backend
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: system=test
  tty: true
  image: myregistry.com/project/client:latest
  stdin_open: true
```

What may be the cause of this unexpected behaviour?
