### ISSUE TITLE
Rancher-Compose stack update doesn't respect docker-compose.yml changes

### ISSUE THREAD

**Issue by wayneconnolly** [rancher/rancher#5360]
**Rancher Version:**
Component	Version
Rancher	v1.1.0-dev1
Cattle	v0.160.3
User Interface	v1.0.7
Rancher Compose	v0.8.0

**Docker Version:**
Docker version 1.11.1, build 5604cbe

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.3
Vultr.com VPS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
Persistent Cattle MySQL DB
Private Docker Registry:2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

1. Deploy a stack with any image (postgres in example)
2. Update the docker-compose.yml to some simple change. Like change the host port from 5432 to 5433

```
postgres:
  ports:
  - 5433:5432/tcp
  environment:
    DB_NAME: piel_production
    DB_PASS: pielio1234
    DB_USER: piel
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: sub_domain=assets
  image: sameersbn/postgresql
  volumes:
  - /data/piel/postgresql:/var/lib/postgresql
```

3. Perform a stack update 

```
/usr/local/bin/rancher-compose \
 --url http://domain.com/v1 \
 --access-key ABCD1234 \
 --secret-key ABCD1234 \
 -f docker-compose.yml -r rancher-compose.yml \
 --verbose -p test-pg up -p
```

Note: Pull image is set in the 
rancher-compose via "-p" and in the docker-compose.yml

```
labels:

   # Pull all containers again  

   io.rancher.container.pull_image: always
```

**Results:** 
The exposed host is still 5432. 

**Expected:**
The exposed host port is now 5433. 

**Suggestion**
Maybe include in the rancher-compose a log entry that shows us that the compose files have a diff and that the stack will now be updated to respect the diff and if this is successful or not.
