### ISSUE TITLE
Rancher load-balancer, route only to local containers

### ISSUE THREAD

**Issue by SimonR** [rancher/rancher#5363]
**Rancher Version:** 1.0.1
**Docker Version:** 1.10+
**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS on AWS
**Setup Details:** Single node with external (AWS RDS) database
**Environment Type:** Cattle

**Enhancement Request:**
I am using Rancher in an AWS setting which is scaled up/down using scheduled AWS _auto-scaling_ groups. Load is distributed across instances using an ELB and within an instance to a _web_ container using a Rancher load balancer. Instances are configured with cloud-config such that they automatically register with the Rancher server which deploys the correct containers. 

The aim of the Rancher load balancer is to reduce user-facing HTTP errors associated with container deployments. The Rancher upgrade process provisions new containers along-side the running containers and can switches them out quickly. This process happens more quickly than the ELB polling interval and provides a method for fast roll-back.

The implication of the load balancer is that they distribute load across all containers with the stack which means that failure scenarios are more complex and latency is increased.
1) if a request is routed via the ELB instance to _availability zone 1a_ the Rancher load balancer may route the request to another availability zone over the internal IPSec network adding additional latency
2) If an server instance degrades (server or container issue) in some way traffic may still be routed to the _failed_ instance and re-routed using the load-balancer
3) Troubleshooting is made more difficult as the path that a request takes can no longer be predicted making it difficult to identify/analyse availability zone specific problems.  

Would it be possible to add a load balancer configuration option such that requests are only routed to local containers hosted on the same server as the load balancer. Network traffic should be traverse the  local docker network as opposed to the IPSec network.

**Comment by wlan0** [comment]
We need to test 4 different scenarios:

1. ingress points to all backend containers available for service
2. ingress points to local only
3. ingress points to prefer-local (local is available)
4. ingress points to prefer-local (local container is not available)

Ensure that you have more than one host added to rancher, label the hosts in rancher with names like

```
host=host1
host=host2
...
```

Steps to test:

Reference rc and service:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```

Reference ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.lb_service.target: "only-local"
    io.rancher.scheduler.affinity.host_label: "host=host1"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

Testing scenario 1:
================

From the reference service and rc shown above, set the rc's replicas to 3 (assuming you have 3 hosts), and then create it.

From the reference ingress, remove the two rancher labels ( io.rancher.lb_service.target: "only-local", 
    io.rancher.scheduler.affinity.host_label: "host=host1") and then create it.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there are as many entries of the server parameter as there are replicas. 

For eg. if the replicas config was set to 2, then you should see 2 entries starting with the `server` identifier
```
mode http
server cf286eb55658612617e38d857cdd5741d65dca1b 10.42.242.91:80
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```


Testing scenario 2:
================

Before you start, delete the rc, service, and ingress from scenario 1.

From the reference service and rc shown above, set the rc's replicas to 3 (assuming you have 3 hosts), and then create it.

Note down the hosts on which the pod for the above service is launched. Let's say it was launched on hosts with labels `host=host1`, `host=host2` and `host=host3`.

From the reference ingress, set the host label to one of the above noted down host. for eg.

```
set     io.rancher.scheduler.affinity.host_label: "host=host1"
```
 and then create it.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there is only one entry of the server parameter. Ensure that the ip address of the entry is the same as the ip address of the pod on the same host.

```
mode http
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```

Testing scenario 3:
================

Leave the rc, and service from scenario 2, but delete the ingress.

Keep the Note of the hosts on which the pod for the above service is launched. Let's say it was launched on hosts with labels `host=host1`, `host=host2` and `host=host3`.

From the reference ingress, set the host label to one of the above noted down host. for eg.

```
set     io.rancher.scheduler.affinity.host_label: "host=host1"
```

and set the lb_service target label to "prefer-local"

```
    io.rancher.lb_service.target: "prefer-local"
```
 and then create it.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there is only one entry of the server parameter. Ensure that the ip address of the entry is the same as the ip address of the pod on the same host.

```
mode http
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```

Testing scenario 4:
================

Leave the rc, and service from scenario 3, but delete the ingress.

Keep the Note of the hosts on which the pod for the above service is launched. Let's say it was launched on hosts with labels `host=host1`, `host=host2` and `host=host3`.

From the reference ingress, set the host label to a host that does not have the pod for the service. i.e. It should be none of the above noted down host. for eg.

```
set     io.rancher.scheduler.affinity.host_label: "host=host5"
```

and set the lb_service target label to "prefer-local"

```
    io.rancher.lb_service.target: "prefer-local"
```
 and then create it.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there are as many entries of the server parameter as there are replicas. 

```
mode http
server cf286eb55658612617e38d857cdd5741d65dca1b 10.42.242.91:80
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```

**Comment by galal-hussein** [comment]
I tested all the scenarios with Rancher version `1.4.0-rc2` and kubernetes `rancher/k8s:v1.5.2-rancher1-2`

All the scenarios worked and verified.

**Comment by alena1108** [comment]
We should test for LB created with Cattle as well.

**Comment by galal-hussein** [comment]
To test the 4 scenarios on Cattle as well, I used the following docker-compose.yml and rancher-compose.yml files:

docker-compose.yml
```
version: '2'
services:
  nginx:
    image: nginx
  lb:
    image: rancher/lb-service-haproxy:v0.5.5
    labels:
      config: "defaults\n balance source\nglobal\nmaxconnrate 60"
      io.rancher.lb_service.target: "only-local"
      io.rancher.scheduler.affinity:host_label: "host=host1"
    links:
    - nginx:nginx
    ports:
    - 80:80
```
rancher-compose.yml
```
version: '2'
services:
  nginx:
    scale: 3
  lb:
   scale: 1
   lb_config:
     port_rules:
     - source_port: 80
       target_port: 80
       service: nginx
```

# Testing scenario 1:

From the reference rancher-compose.yml shown above, set the scale to 3 (assuming you have 3 hosts).

From the lb section in docker-compose.yml, remove the two rancher labels ( io.rancher.lb_service.target: "only-local",
io.rancher.scheduler.affinity.host_label: "host=host1") and then create the stack.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there are as many entries of the server parameter as there are replicas.

For eg. if the replicas config was set to 2, then you should see 2 entries starting with the server identifier
```
mode http
server cf286eb55658612617e38d857cdd5741d65dca1b 10.42.242.91:80
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```
# Testing scenario 2:

Before you start, delete the stack from scenario 1.

From the reference rancher-compose.yml shown above, set the scale to 3 (assuming you have 3 hosts).

Note down the hosts on which the nginx is launched. Let's say it was launched on hosts with labels host=host1, host=host2 and host=host3.

From the lb section in docker-compose.yml,, set the host label to one of the above noted down host. for eg.

`io.rancher.scheduler.affinity.host_label: "host=host1"`
and then create the stack.

Once it is created, login into the lb container that is created and execute this command
cat /etc/haproxy/haproxy.cfg

ensure that at the end of the file, there is only one entry of the server parameter. Ensure that the ip address of the entry is the same as the ip address of the container on the same host.
```
mode http
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```

# Testing scenario 3:

Before you start delete the stack from scenario 2

Assuming you have 3 hosts, Add the following label to the nginx service in docker compose:
```
labels:
      io.rancher.scheduler.global: 'true'
```
This will ensure that nginx will run on each host.

From the lb section in docker-compose, set the host label to one of the hosts where nginx will be launched, Let's say it will be launched on hosts with labels host=host1, host=host2, host=host3 for eg.

set     `io.rancher.scheduler.affinity.host_label: "host=host1"`
and set the lb_service target label to "prefer-local"

   `io.rancher.lb_service.target: "prefer-local"`

Create the stack, once it is created, login into the lb container that is created and execute this command

`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there is only one entry of the server parameter. Ensure that the ip address of the entry is the same as the ip address of the container on the same host.
```
mode http
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```
# Testing scenario 4:

Before you start delete the stack from scenario 3.

Keep the Note of the hosts on which the nginx container is launched. Let's say it was launched on hosts with labels host=host1, host=host2 and host=host3.

From the lb section in docker-compose, set the host label to a host that does not have the nginx container. i.e. It should be none of the above noted down host. for eg.

set     io.rancher.scheduler.affinity.host_label: "host=host5"
and set the lb_service target label to "prefer-local"

    io.rancher.lb_service.target: "prefer-local"
and then create it.

Once it is created, login into the lb container that is created and execute this command
`cat /etc/haproxy/haproxy.cfg`

ensure that at the end of the file, there are as many entries of the server parameter as there are replicas.
```
mode http
server cf286eb55658612617e38d857cdd5741d65dca1b 10.42.242.91:80
server 2933de06d51882d3e44a82fafc349c62a63b4a16 10.42.158.153:80
```

All scenarios tested and verified.
