### ISSUE TITLE
Rancher Host view not showing container IPs

### ISSUE THREAD

**Issue by averri** [rancher/rancher#5364]
The Rancher host view is not showing the container IPs, as showed in the following image:

![image](https://cloud.githubusercontent.com/assets/1898447/16686332/47a7eed2-4509-11e6-9c18-4097c5bfc9a3.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`host.containers`|

**Comment by tfiduccia** [comment]
Can you share your compose.yml file.

**Comment by averri** [comment]
**Important**: I created the containers using `docker-compose up -d`, and not using the Rancher UI. 

Here is the `docker-compose.yml`:

```
version: '2'
services:

  database:
    image: averri/app:codex-db
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD=thePassword
    ports:
     - 3306:3306

  reports:
    image: averri/app:giacoop-reports

  giacoop:
    image: averri/app:giacoop
    restart: unless-stopped
    ports:
     - 8080:8080
     - 7070:7070
    volumes_from:
     - reports

  emanager:
    image: averri/app:emanager
    restart: unless-stopped
    ports:
     - 8081:8080
    volumes:
     - /var/www/html/wp-content/themes/ocbrj/emanager:/emanager

  ocbweb:
    image: averri/app:ocbweb
    restart: unless-stopped
    ports:
     - 80:80
    volumes:
     - /var/www/html/wp-content/themes/ocbrj/emanager:/var/www/html/wp-content/themes/ocbrj/emanager
    extra_hosts:
     - "localhost.localdomain:127.0.0.1"
```
