### ISSUE TITLE
Sidekick service using networkFrom option, is not dns resolvable

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5372]
Steps to reproduce:

1) Create a service foo with a sidekick bar. Make bar to use network from foo
2) From bar container, try to ping foo. It works. 
3) From foo container, try to ping bar. It fails.

The failure happens as the dns record is missing for bar container as the bar container doesn't have nic/ip address assigned to it.

**Comment by sangeethah** [comment]
Tested with v1.1.1

Created stack with following compose file:

```
slave1:
  command:
  - sleep
  - '100000'
  image: ubuntu
  net: container:master
master:
  labels:
    io.rancher.sidekicks: slave1
  image: sangeetha/testclient
```

From containers of master , able to ping slave1.
From container of slave1 , able to ping master.
