### ISSUE TITLE
Accessing certificate store from container

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#5397]
**Rancher Version:**
1.1.0

Since the rancher load balancer is quite limited in a lot of ways, i've built my own which does service discovery for stack routing.

I would like to access the certificates in the same way as the rancher load balancer service.
It seems this is purposely blocked. if i add the rancher-compose.yml config the same way that a loadbalancer has:
```
SomeLoadBalancer:
   load_balancer_config:
    haproxy_config:
      defaults: option forwardfor header X-Real-IP
  default_cert: '*.dev.datarepublic.com.au'
```
When i create the stack it removes those keys from the resulting stack.

How does the rancher lb get an exception for this?
