### ISSUE TITLE
Error deploying services that use the same convoy-nfs container

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5404]
**Rancher Version:**
1.1.0.

**Docker Version:**
1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
1. Make sure you have a correctly deployed convoy-nfs stack.
2. Create a new stack and use this `docker-compose.yml`:

```yml
nginx:
  image: nginx:latest
  volumes:
    - myvol:/foobar
  volume_driver: convoy-nfs

hello:
  image: tutumcloud/hello-world
  labels:
    io.rancher.container.start_once: 'true'
  volumes:
    - myvol:/foobar
    - anothervol:/foobiz
  volume_driver: convoy-nfs
```

If you'll notice above, both services use the same `myvol` volume.

**Results:** 

The containers will never start up and will be stuck in "Starting..." state. Here's what the volume page looks like:

<img width="1343" alt="screen shot 2016-07-12 at 14 28 22" src="https://cloud.githubusercontent.com/assets/92085/16769138/42b085ea-483f-11e6-8f6a-8cb304ec307e.png">

If I navigate to "Admin" -> "Processes", there is an error: "Volume already exists 'myvol'" (paraphrasing as I do not have it in front of me).

**Expected:**

Both containers should start up and use the same convoy-nfs volume without issue.
