### ISSUE TITLE
Load balancer listen by host header and port / path

### ISSUE THREAD

**Issue by ca0abinary** [rancher/rancher#544]
I would like to supply a host header value per http listener so one load balancer can support multiple web sites on the same port. With HAProxy this is accomplished by having multiple backends and ACLs as described [here](http://stackoverflow.com/questions/18572222/how-to-balance-to-a-specific-server-if-hostname-matches-x-domaine-com-haproxy/18700791#18700791).

**Comment by vincent99** [comment]
This seems like it would be useful for things like shared hosting where you want to conserve the public IPv4 addresses required.  The host port 80 (and 443, with SNI) can really be 'shared' across multiple balancers.

Varying targets depending on the listener the request hits would be a significant change to the API though, as the targets are mapped directly to the balancer.

**Comment by ca0abinary** [comment]
@vincent99 So the recommended pattern would be to create one load balancer per HA application? Then have that collection of load balancers behind a top level load balancer which could provide routing based on host header?

**Comment by ibuildthecloud** [comment]
The semantics of our Load Balancer are really based around ELB concepts.  ELB was obviously created for VMs.  In this new world of containers I think it makes sense that we look at adding more L7 concepts like HTTP host and path routing.

**Comment by vincent99** [comment]
It's not really ideal to actually have every request go through 2 separate haproxies, though you could create a regular container and configure it to do host-header-based balancing to different rancher balancer IPs today.

I was more just thinking out loud about how to represent something like this in our API.  We'd definitely need to put some thought into the best way to do it.  One possible way of thinking about it (and my first thought) is that ports used for http/tls can be "shared" instead to of being dedicated to a single container.

Something like you create multiple logically separate balancer resources (one for each site/VirtualHost) with their own targets (presumably differing for each site, or you could just do VHosts in the container with a single normal balancer).  Then you somehow configure that they use a shared listening port on the host(s), and we physically create just one LB Agent container (per host) with the appropriate config for all of the logical VHosts.

**Comment by bscott** [comment]
+ 1 on Host header routing

**Comment by blackjid** [comment]
:+1:

**Comment by adamkdean** [comment]
Any update on this @vincent99? At the moment without this, Rancher is not the complete solution. There still needs to be an an additional load balancing service to map hostnames to ports and this adds on an additional hop which isn't ideal.

**Comment by vincent99** [comment]
We haven't designed it out quite yet but will be working on this soon.  It is one of the things that has to be in before we can call it a 1.0:  https://github.com/rancherio/rancher/milestones/Release%201.0%20Features

**Comment by adamkdean** [comment]
Ok that's great to know. Do we know when 1.0 might land? Any target date?

**Comment by teamon** [comment]
Hostname-based routing seems like the only thing missing for me, I must say I'm pretty impressed by the rancher project overall. Keep up the great work!

In the meantime, do you have any tips how could one "hack" a hostname based LB using custom service connected to other LBs? Are there any API docs you could point me to?

**Comment by moimael** [comment]
For me it is really top priority feature to have. Without it rancher is close to useless in our development/test environment (I'm not criticizing the really good work the rancher team is doing, just emphasizing the importance of this feature).

**Comment by moimael** [comment]
I just updated rancher and it seems the feature is finally here :) One thing to note though, I can't specify where the load balancer must be (and stay). That's kind of problematic since my DNS point on one specific ip, and I can't predict where the lb-agent will launch and if it will stay here.

**Comment by adamkdean** [comment]
Is there no chance of having an external load balancer which points to your X rancher servers?

**Comment by moimael** [comment]
You mean having a load balancer in front, and spawning lb-agent on every rancher server which will then redirect to the correct container ?

**Comment by adamkdean** [comment]
Yeah, exactly. It means having an extra machine but otherwise how are you going to reliably deal traffic to all three servers? You could point to a single server in the cluster but then if that goes down, you'll have to change your DNS and that'll be a slower recovery from failure.

**Comment by willseward** [comment]
You could add a lb in front of your cluster and spawn a lb-agent on every host. That would ensure you never have a lb config/agent mismatch. You would need inter-service lb capabilities though. I think that is in the works as we speak.

**Comment by moimael** [comment]
Yes that makes perfect sense. Indeed i need inter-service lb capabilities. I'll setup my front lb and wait and see :)

**Comment by moimael** [comment]
Ok my lb setup is functionnal. Is there a place (bug number) where inter-service lb capabilities progress is tracked ?

Thanks ! Rancher is almost functional for me :) Better volume management / distributed storage / backup is the next thing i'll miss :)

**Comment by deniseschannon** [comment]
@moimael Here's the issue: https://github.com/rancher/rancher/issues/1433 and it should be out in the next release.

**Comment by nixelsolutions** [comment]
There is any chance we can set up Host headers & URI rules with Rancher CLI (rancher compose)?

**Comment by blackjid** [comment]
In the docs there is an example with this `rancher-compose.yml`

```yaml
lb:
  image: rancher/load-balancer-service
  ports:
  # Load Balancer should listen on public port 80
  - 80
  # Load Balancer public port 82 and by default forward private port 81 using HTTP
  - 82:81
  # Load Balancer public port 9999 using TCP and not HTTP
  - 9999/tcp
  labels:
    # Put load balancer containers on hosts with label lb=true
    - "io.rancher.scheduler.affinity:host_label=lb=true"
    # Requests to http://app.example.com/foo should be routed to web over port 8000
    - "io.rancher.loadbalancer.target.web=8000:app.example.com/foo"
    # Requests to http://app.example.com should be routed to web2 over port 8000
    - "io.rancher.loadbalancer.target.web2=8000:app.example.com"
    # Requests routed to web2 should go to port 8000, overriding the default configuration
    # of 80:81
    - "io.rancher.loadbalancer.target.web3=80"
```
Is the `io.rancher.loadbalancer.target.web` label the option we need to use for what @nixelsolutions is proposing????
