### ISSUE TITLE
syslog-address not working in overlay networks

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#5442]
**Rancher Version:**
v1.1.0-dev5

**Docker Version:**
1.10.3

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

When we add 

```
log_opt:
    syslog-address: "udp:/karaf-logstash.logstash:5000"
    tag: "my-service/{{.Name}}"
log_driver: syslog
```

to our services in docker-compose we can't reach the logstash server by service name because of syslog-address not working in overlay networks.

I'm wondering if you have any workaround for this that aren't to complex?
