### ISSUE TITLE
Rancher Catalog or API is not honoring quoted numeric strings.

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#5458]
*Describe your issue here*

At some point rancher is treating my quoted numeric strings in docker/rancher-compose.yml as integers and eating leading zeros. This happens in environment, labels and metadata.

docker-compose.yml
```yaml
volume:
  image: leankit/rancher-azurefile-volume
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    VOLUME_NAME: ${name}
    VOLUME_GID: '${gid}'
    VOLUME_UID: '${uid}'
    VOLUME_FILEMODE: '${filemode}'
    VOLUME_DIRMODE: '${dirmode}'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
```
rancher-compose.yml
```
.catalog:
  name: "AzureFile Volume"
  version: "v0.0.1"
  description: Create an Azure File Share Volume.
  uuid: azurefile-volume:v0.0.1
  questions:
    - variable: name
      label: Volume Name
      type: string
      required: true
    - variable: uid
      label: UID
      type: string
      description: UID for owner of mounted files.
      required: true
      default: '0'
    - variable: gid
      label: GID
      type: string
      description: GID for owner of mounted files.
      required: true
      default: '0'
    - variable: filemode
      label: File Mode
      type: string
      description: Mode for mounted files.
      required: true
      default: '0644'
    - variable: dirmode
      label: Directory Mode
      type: string
      description: Mode for directories (executable is important).
      required: true
      default: '0755'
```

My dirmode/filemode variables end getting set as 644 and 755 instead of 0644 and 0755.

launch config from service api view 
```json
"launchConfig": {
  "dataVolumes": [
    "/var/run/docker.sock:/var/run/docker.sock",
  ],
  "environment": {
    "VOLUME_DIRMODE": "755",
    "VOLUME_FILEMODE": "644",
    "VOLUME_GID": "999",
    "VOLUME_NAME": "rabbitmq",
    "VOLUME_UID": "999",
  },
  "imageUuid": "docker:leankit/rancher-azurefile-volume",
  "kind": "container",
  "labels": {
    "io.rancher.container.hostname_override": "container_name",
    "io.rancher.container.pull_image": "always",
    "io.rancher.container.start_once": "true",
    "io.rancher.scheduler.global": "true",
    "io.rancher.service.hash": "c63db665ca265e47450a8f82416d6449415be228",
  },
  "logConfig": { },
  "networkMode": "managed",
  "privileged": false,
  "publishAllPorts": false,
  "readOnly": false,
  "startOnCreate": true,
  "stdinOpen": false,
  "tty": false,
  "version": "0",
  "vcpu": 1,
  }
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|
