### ISSUE TITLE
Rancher Load Balancer Healthchecks causing a lot of (104: Connection reset by peer)

### ISSUE THREAD

**Issue by suizman** [rancher/rancher#5464]
**Rancher Version:**
v1.1.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS Red Hat Enterprise Linux Server release 7.2 (Maipo)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Non HA Rancher server + AWS Aurora db + 40~ AWS autoscale group nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Run some app with docker nginx:1.10.0 create rancher LB on top of it.

Nginx config: 

```
user root root;
worker_processes  1;

pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /var/www;
            index  index.html index.htm;
        }
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log  info;

        error_page  404     /index.html;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /var/www;
        }

    }

}
```

**Results:** 

```
18/7/2016 17:14:4210.42.89.204 - - [18/Jul/2016:15:14:42 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:422016/07/18 15:14:42 [info] 8#8: *3240 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.89.204, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:4210.42.12.39 - - [18/Jul/2016:15:14:42 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4310.42.226.193 - - [18/Jul/2016:15:14:43 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:432016/07/18 15:14:43 [info] 8#8: *3242 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.226.193, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:442016/07/18 15:14:44 [info] 8#8: *3243 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.224.205, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:4410.42.224.205 - - [18/Jul/2016:15:14:44 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:442016/07/18 15:14:44 [info] 8#8: *3244 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.89.204, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:4410.42.89.204 - - [18/Jul/2016:15:14:44 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4410.42.12.39 - - [18/Jul/2016:15:14:44 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:452016/07/18 15:14:45 [info] 8#8: *3246 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.226.193, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:4510.42.226.193 - - [18/Jul/2016:15:14:45 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4610.42.224.205 - - [18/Jul/2016:15:14:46 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4610.42.89.204 - - [18/Jul/2016:15:14:46 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4610.42.12.39 - - [18/Jul/2016:15:14:46 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:4710.42.226.193 - - [18/Jul/2016:15:14:47 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:482016/07/18 15:14:48 [info] 8#8: *3251 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.224.205, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
18/7/2016 17:14:4810.42.224.205 - - [18/Jul/2016:15:14:48 +0000] "GET /api/heartbeat HTTP/1.0" 200 38 "-" "-"
18/7/2016 17:14:482016/07/18 15:14:48 [info] 8#8: *3252 recv() failed (104: Connection reset by peer) while sending response to client, client: 10.42.89.204, server: localhost, request: "GET /api/heartbeat HTTP/1.0"
```

**Expected:**

200 OK

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml and rancher-compose.yml of your service and your load balancer so I can try to recreate correctly?

I was unable to reproduce what I thought you were doing in v1.2.0-pre2

```
nginx:
  tty: true
  image: nginx:1.10.0
lbnginxtest:
  ports:
  - 80:80
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - nginx:nginx
  stdin_open: true
```

rancher-compose.yml

```
nginx:
  scale: 8
lbnginxtest:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

**Comment by suizman** [comment]
I'm using rancher server v1.1.0 not v1.2.0-pre2. Anyways my compose look like this

**docker-compose.yml**

```
nginx:
  image: my-nginx-with-custom-statics:1.10.0
lb:
  expose:
  - 80:80
  labels:
    io.rancher.scheduler.global: 'true'
  image: rancher/load-balancer-service
  links:
  - nginx:nginx
```

**rancher-compose.yml**
```

nginx:
  scale: 2
lb:
  scale: 2
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

On top of that I have external proxies pointing to the nginx service load balancers with public DNS..

I'm unable to reproduce the error in local it seams to be related when rancher server is under heavy load. I've detected that the network-agents are degradated and it coauses some serious conectivity issues with the services conected with links,rancher dns even if i try to ping the containers by IP.

Maybe the problems are more related with connectivity than haproxy and nginx itself ....
