### ISSUE TITLE
External IPs service is not working as expected in K8S 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5495]
**Rancher Version:**
rancher/server:v1.2.0-pre1-rc1 
**Kubernetes Version**
1.2.4
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu - cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Create any nginx pod and then create the following service:

```
---

apiVersion: v1
kind: Service
metadata:
  name: external-nginx
  labels:
    name: external-nginx
spec:
  type: NodePort
  externalIPs: ['first-ip', 'second-ip']
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    name: nginx
```

This should create a service with two external ips that will expose port 30003 on each node. 

**Results:** 

The nginx container is not accessible on the IP of the server that it **doesn't** resides.

**Expected:**

Nginx should be accessible on both IPs
