### ISSUE TITLE
Kubernetes loadbalancer issues warning "UpdateFailed Error updating load balancer with new hosts"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5529]
**Rancher Version:**: v1.2.0-pre1-rc4

**Docker Version:**:1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment using https://github.com/ibuildthecloud/rancher-catalog 
2. Create a loadbalancer using the below yml file

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: sangeetha/testnewhostrouting
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: lbnginx
  labels:
    name: lbnginx
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 80
  selector:
    name: nginx
```
- Upgrade to Kubernetes1.3

**Results:** 
Load balancer issues a warning 

```
> kubectl describe service lbnginx 
Labels:                 name=lbnginx                                                                                    
Selector:               name=nginx                                                                                      
Type:                   LoadBalancer                                                                                    
IP:                     10.43.40.20                                                                                     
LoadBalancer Ingress:   104.197.231.176                                                                                 
Port:                   <unset> 8888/TCP                                                                                
NodePort:               <unset> 31313/TCP                                                                               
Endpoints:              10.42.247.7:80,10.42.85.10:80                                                                   
Session Affinity:       None                                                                                            
Events:                                                                                                                 
 FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason                 M
essage                                                                                                                  
 ---------     --------        -----   ----                    -------------   --------        ------                 -
------                                                                                                                  
 17m           17m             1       {service-controller }                   Normal          CreatingLoadBalancer   C
reating load balancer                                                                                                   
 17m           17m             1       {service-controller }                   Normal          CreatedLoadBalancer    C
reated load balancer                                                                                                    
 13m           13m             1       {service-controller }                   Normal          CreatingLoadBalancer   C
reating load balancer                                                                                                   
 13m           13m             1       {service-controller }                   Normal          CreatedLoadBalancer    C
reated load balancer                                                                                                    
 12m           12m             1       {service-controller }                   Warning         LoadBalancerUpdateFaileE
rror updating load balancer with new hosts [soumyapre1rc4testing-10acre-1 soumyapre1rc4testing-10acre-2 soumyapre1rc4tes
ting-10acre-3]: Couldn't call activate on external service 1s35 for LB lb-a469020d150f811e6b422025c9ec587f              
 12m           12m             1       {service-controller }                   Normal          UpdatedLoadBalancer    U
pdated load balancer with new hosts
```

Load balancer is functional but has the above warning.
