### ISSUE TITLE
Kubernetes Ingress not working initially

### ISSUE THREAD

**Issue by jondubois** [rancher/rancher#5559]
For some reason I was struggling to get the ingress feature to work today...
I would deploy my service and then shortly afterwards, I would deploy the ingress but when I tried accessing my service through the browser, I kept getting 503 from the Rancher load balancer.

Then after trying a lot of things (none of which worked), I ended up deleting the ingress using `kubectl delete ingress loadbalancer` and then I re-launched it using `kubectl create -f myingress.yaml` and it started working!

I guess this could be one of those hard-to-reproduce bugs but I thought I should mention it here in case it helps.

**Rancher Version:**
1.1.2

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu, EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher is running on its own node and a new host was added using the UI by clicking on the 'Add Host' button and then selecting 'Amazon EC2' as the machine driver, providing my access keys, selecting availability zone, then a VPC (same availability zone and VPC as my rancher/server), etc...

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

- Create a new Kubernetes environment and switch to that environment
- Add a new host on EC2 by going through the UI and providing the AWS access keys (see Setup Details above).
- Once Kubernetes is ready, use `kubectl create -f myfrontend.yaml` to deploy a service to it, then use `kubectl create -f myingress.yaml` to deploy the ingress.

**Results:** 

I get a 503 error (probably coming from the Rancher load balancer kubernetes-ingress-lbs_default-loadbalancer_1) which tells me that the service is not reachable.

Here are the .yaml files which I'm using (the image socketcluster/socketcluster:v4.7.1 is open source so feel free to use it).
 
myfrontend.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: socketcluster
  labels:
    app: socketcluster
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: socketcluster-port
  selector:
    app: socketcluster

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: socketcluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: socketcluster
    spec:
      containers:
      - name: socketcluster
        image: socketcluster/socketcluster:v4.7.1
        ports:
        - containerPort: 8000
```

myingress.yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loadbalancer
spec:
  backend:
    serviceName: socketcluster
    servicePort: 8000
```

**Expected:**

When I navigate to my node's IP address on port 80, I expect to see a dummy project page with some text and links.

Note that I was able to resolve the issue by eventually deleting the ingress using `kubectl delete ingress loadbalancer` and then launching it again with `kubectl create -f myingress.yaml`.

While I was debugging, I had tried to delete just the container `kubernetes-ingress-lbs_default-loadbalancer_1` earlier but that didn't work - I had to delete the whole ingress via kubectl.
