### ISSUE TITLE
Kubernetes Ingress doesn't support WebSockets ws:// and wss://

### ISSUE THREAD

**Issue by jondubois** [rancher/rancher#5560]
**Rancher Version:**
1.1.2

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu, EC2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

It looks like Rancher's load balancer (via Ingress) doesn't support WebSocket traffic. For example requests starting with `ws://` fail with a 404 Not Found when run behind the Ingress (but it works if I use NodePort).

**Comment by jondubois** [comment]
I think this is likely a Kubernetes issue https://github.com/kubernetes/kubernetes/issues/25126

**Comment by jondubois** [comment]
Or maybe not... Apparently the nginx ingress does support WebSockets https://github.com/kubernetes/kubernetes/issues/24745#issuecomment-226906208 - It could be that Rancher's ingress lb doesn't

**Comment by jondubois** [comment]
Here is the yaml configs which I'm using to deploy my service and ingress (I'm using `kubectl create -f websocketservice.yaml` and `kubectl create -f ingress.yaml`):

websocketservice.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: websocketservice
  labels:
    app: websocketservice
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: websocketservice

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websocketservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: websocketservice
    spec:
      containers:
      - name: socketcluster
        image: socketcluster/socketcluster:v4.7.1
        ports:
        - containerPort: 8000
```

ingress.yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loadbalancer
spec:
  backend:
    serviceName: websocketservice
    servicePort: 8000

```

For testing purposes, I have setup my websocketservice to handle both WebSockets AND HTTP traffic from port 8000 (in the container). When I access the service via the browser, the HTTP gets served correctly but `ws://` connections gets blocked with a 404 (both go through the same connection - It works fine when I run the service standalone on Docker).

---

Another approach I tried (for testing purposes) was to expose my service directly to outside without using a proxy (using a `DaemonSet` and setting a `hostPort` property).

Here is the yaml file I used:

```
apiVersion: v1
kind: Service
metadata:
  name: websocketservice
  labels:
    app: websocketservice
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: websocketservice

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: websocketservice
  # namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: websocketservice
    spec:
      containers:
      - name: socketcluster
        image: socketcluster/socketcluster:v4.7.1
        ports:
        - containerPort: 8000
          hostPort: 80
```

Surprisingly, with this approach, I ran into the exact same problem as before (using the ingress) - HTTP traffic is fine but WS traffic gets 404.

---

At this point I thought that maybe it's Kubernetes itself which can't handle WebSockets.
So then I tried using `NodePort` as the service `type`:

```
apiVersion: v1
kind: Service
metadata:
  name: websocketservice
  labels:
    app: websocketservice
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    app: websocketservice

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: websocketservice
  # namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: websocketservice
    spec:
      containers:
      - name: socketcluster
        image: socketcluster/socketcluster:v4.7.1
        ports:
        - containerPort: 8000

```

When I access my service in the browser using `http://<my-host-address>:30080` it works completely - Both the HTTP AND WebSocket connections work perfectly.
