### ISSUE TITLE
pods fails to get created in k8s v1.2 environment with error "no API token found for service account"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5562]
Rancher Version: v1.2.0-pre1-rc7

Set up with 3 hosts added to "cattle" Default environment.
Updated "cattle" to "Kubernetes" environment.
Once K8s system stack was created, used the following yml to create service/rc/pods.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: testnginx
spec:
  replicas: 2
  selector:
    name: testnginx
  template:
    metadata:
      labels:
        name: testnginx
    spec:
      containers:
        - name: testnginx
          image: sangeetha/testnewhostrouting
          ports:
            - containerPort: 80

---            

apiVersion: v1
kind: Service
metadata:
  name: testnginx
  labels:
    name: testnginx
    type: ui
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    name: testnginx
```

services and rcs gets created as expected.
But pods are not getting created.
Following error is seen when we describe the replication controller:

```
Events:                                                                                                                 
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason         M
essage                                                                                                                  
  ---------     --------        -----   ----                            -------------   --------        ------         -
------                                                                                                                  
  19m           7s              84      {replication-controller }                       Warning         FailedCreate   E
rror creating: pods "testnginx-" is forbidden: no API token found for service account default/default, retry after the t
oken is automatically created and added to the service account   
```
