### ISSUE TITLE
LoadBalancer not mapping ports correctly

### ISSUE THREAD

**Issue by taormania** [rancher/rancher#5570]
**Rancher Version:**
1.1.0-dev1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu EC2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
docker-compose.yml:

```
SwaggerEditorLb:
  ports:
  - 5000:8080
  labels:
    io.rancher.scheduler.affinity:host_label: host_type=internal_apps
  tty: true
  image: rancher/load-balancer-service
  links:
  - Editor:Editor
  stdin_open: true
Editor:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: swaggerapi/swagger-editor
  stdin_open: true
```
rancher-compose.yml:

```
Editor:
  scale: 1
SwaggerEditorLb:
  scale: 1
```

**Results:** 
Port 5000 to mapped to port 5000 in container over tcp
**Expected:**
Port 5000 to be mapped to port 8080 in container

![screen shot 2016-07-27 at 4 55 19 pm](https://cloud.githubusercontent.com/assets/3212434/17192083/fa9e290a-541a-11e6-87a6-554e327b2656.png)
