### ISSUE TITLE
Heapster can't gather nodes information on Kubernetes 1.3

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5594]
**Rancher Version:**
v1.2.0-pre1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.3
**Steps to Reproduce:**
Run the following yaml file against Rancher kubernets environment:
```
apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-grafana
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30804
    targetPort: 3000
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-influxdb
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30805
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://$KUBERNETES_SERVICE_HOST?inClusterConfig=false&insecure=true
        - --sink=influxdb:http://monitoring-influxdb:8086

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: influxdb-grafana
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v2.6.0-2
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
```
**Results:** 
All pods are up and running but Heapster pod can't gather information about the nodes:
```
7/29/2016 9:08:12 PME0729 19:08:12.666216       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:12 PME0729 19:08:12.667410       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:12 PME0729 19:08:12.797839       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:12 PME0729 19:08:12.799263       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:13 PME0729 19:08:13.669723       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:13 PME0729 19:08:13.671048       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:13 PME0729 19:08:13.801783       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:13 PME0729 19:08:13.803596       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:14 PME0729 19:08:14.674533       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:14 PME0729 19:08:14.675598       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:14 PME0729 19:08:14.804962       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:14 PME0729 19:08:14.806454       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:15 PME0729 19:08:15.679040       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:15 PME0729 19:08:15.681176       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:15 PME0729 19:08:15.810444       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:15 PME0729 19:08:15.812157       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:16 PME0729 19:08:16.687073       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:16 PME0729 19:08:16.689462       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:16 PME0729 19:08:16.814825       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:16 PME0729 19:08:16.815679       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:17 PME0729 19:08:17.691271       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:17 PME0729 19:08:17.695341       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:17 PME0729 19:08:17.822528       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:17 PME0729 19:08:17.824120       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:18 PME0729 19:08:18.694087       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:18 PME0729 19:08:18.697698       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:18 PME0729 19:08:18.826310       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:18 PME0729 19:08:18.827887       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:19 PME0729 19:08:19.699437       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:19 PME0729 19:08:19.701160       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:19 PME0729 19:08:19.831430       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:19 PME0729 19:08:19.832557       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:20 PME0729 19:08:20.706416       1 reflector.go:205] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:92: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
7/29/2016 9:08:20 PME0729 19:08:20.707589       1 reflector.go:205] k8s.io/heapster/metrics/heapster.go:236: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
7/29/2016 9:08:20 PME0729 19:08:20.834242       1 reflector.go:205] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
7/29/2016 9:08:20 PME0729 19:08:20.836123       1 reflector.go:205] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
```

**Comment by wlan0** [comment]
@galal-hussein You need to replace the $KUBERNETES_SERVICE_HOST with the kube-apiserver container's IP:PORT, and set inClusterConfig=true to get it working.

inClusterConfig should be true if heapster is running within the cluster. The rest of the options should be as they are. I have added a kubernetes fix that is required to get it working - https://github.com/rancher/kubernetes/pull/42. Once it is merged and released, heapster will work with rancher kubernetes.

**Comment by bonifaido** [comment]
@wlan0 Which version of heapster did you try with kubernetes v.1.3.4-rancher ?
I could only get it to work with 1.1.0-beta2 since the PodMetric object has changed (in canary build) compared to the one in the Rancher Kubernetes fork.

**Comment by wlan0** [comment]
@bonifaido I tried `heapster:canary` with rancher kubernetes v1.3.4-rancher1

@galal-hussein  The template I’m using for *launching kubernetes* is in this repository - `https://github.com/rancher/rancher-catalog/tree/qa` , the branch is qa branch.

The Kubernetes version in the image is `v1.3.4-rancher1` and rancher version can be any of v1.2.0-pre1 , v1.2.0-pre2, or v1.2.0-pre3

This is the kubernetes template I use for *launching heapster*
```
apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-grafana
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30804
    targetPort: 3000
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-influxdb
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30805
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://Kubernetes.kubernetes:6443?inClusterConfig=true&insecure=true
        - --sink=influxdb:http://monitoring-influxdb:8086

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: influxdb-grafana
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v2.6.0-2
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
```
