### ISSUE TITLE
Petset Can't start with NFS persistent volumes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5607]
**Rancher Version:**
v1.2.0-pre1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu - cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.3
**Steps to Reproduce:**
Create two NFS persistent volumes:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xx.xx.xx.xx
    path: "/nfs1"
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xx.xx.xx.xx
    path: "/nfs2"
```

Run the following petset.yaml file:

```
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nfs1
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nfs1
      annotations:
        volume.alpha.kubernetes/io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
   - port: 80
     name: web
  clusterIP: None
  selector:
    app: nginx
```

**Results:** 

The petset can't generate the pv claims, and it throw the following error:

```
$ kubectl describe petset
Name:           web
Namespace:      default
Image(s):       gcr.io/google_containers/nginx-slim:0.8
Selector:       app=nginx
Labels:         app=nginx
Replicas:       0 current / 2 desired
Annotations:        <none>
CreationTimestamp:  Mon, 01 Aug 2016 22:04:47 +0200
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen LastSeen    Count   From        SubobjectPath   Type        Reason      Message
  --------- --------    -----   ----        -------------   --------    ------      -------
  14m       <invalid>   2238    {petset }           Warning     FailedCreate    pvc: nfs1-web-0, error: persistentvolumeclaims "nfs1-web-0" not found
  14m       <invalid>   2238    {petset }           Warning     FailedCreate    pvc: nfs1-web-1, error: persistentvolumeclaims "nfs1-web-1" not found

```
