### ISSUE TITLE
Feature: LoadBalancer Sidekicks

### ISSUE THREAD

**Issue by jhmartin** [rancher/rancher#5610]
It would be useful to be able to specify a sidekick for LoadBalancer instaces, which could be used to add glue for external loadbalancing tools such as ELBs.

**Comment by edaubert** [comment]
+1 for this.

Here is one usecase for us:

We want to define some sidekicks to integrate [goreplay](https://goreplay.org/) which allow us to duplicate production data to our pre-production environment.

Here is an example of a simplified catalog definition for a load balancer, a sidekick with goreplay and nginx as backend service:

**docker-compose:**
```yaml
version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.sidekicks: gor-archive
  gor-archive:
    image: edaubert/goreplay:0.16.1
    command: ['/goreplay', '--input-raw :80 --output-stdout']
    stdin_open: true
    tty: true
    network_mode: container:lb
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  nginx:
    image: nginx
```
**rancher-compose:**
```yaml
version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        defaults
          mode http
      port_rules:
        - backend_name: nginx
          priority: 1
          protocol: http
          service: nginx
          source_port: 80
          target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```
