### ISSUE TITLE
Deploying services stuck at initializing state

### ISSUE THREAD

**Issue by boshido** [rancher/rancher#5630]
**Rancher Version:**
v1.1.2

**Docker Version:**
1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS: centos7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher -> external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**First scenarios**
1. I setup rancher agent host private subnet
2. I add rancher agent host to rancher server by using private ip 
3. I tried deploying my service and restrict them only be deployed to host in private subnet
**Results:** 
All of service changed to running state
**Expected:**
All of service must change to running state

**Second scenarios**
1. I place AWS External ELB linked to rancher server
2. I setup new rancher agent host private subnet again
3. I setup Host Registration URL at /admin/settings page to use my domain name instead of ip
4. I add rancher agent host to rancher server by using domain name 
5. I tried deploying my service and restrict them only be deployed to new host in private subnet.

**Results:** 
All of service that had been deployed were stuck in initializing state
**Expected:**
All of service must change to running state

**Third scenarios**
(After I finished doing first scenarios and second scenarios)
1. I try deploying my service to first scenarios agent host again
**Results:** 
All of service changed to running state
**Expected:**
All of service must change to running state

**FYI: I setup rancher server host inside AWS VPC private subnet**
My hierarchy is a bit like this
![image](https://cloud.githubusercontent.com/assets/3489862/17398753/8a7b6db4-5a68-11e6-995b-07335d5b4f49.png)

This is my docker-compose.yml
```
load-balancer:
  restart: always
  image: rancher/load-balancer-service
  expose:
  - 80:80
  labels:
    io.rancher.scheduler.affinity:host_label: access_mode=private
    load-balancer: private
  links:
  - api:api
  stdin_open: true
  tty: true
api:
  restart: always
  image: abcdefg.xyz/sendit/2stage-api:devel
  labels:
    io.rancher.scheduler.affinity:host_label: access_mode=private
    io.rancher.scheduler.affinity:host_label: stricted_service=sendit-2stage-api
    io.rancher.container.pull_image: always
```

And this is my rancher-compose.yml
```
load-balancer:
  upgrade_strategy:
    start_first: true
  scale: 2
  load_balancer_config:
    name: load-balancer
  default_cert: dev-2stage-api-th
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
    strategy: recreate
api:
  upgrade_strategy:
    start_first: true
  scale: 4
  health_check:
    port: 80
    request_line: GET /th/2stage/system/health HTTP/1.0
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
    strategy: recreate

```

This is my current infrastructures
![screen shot 2559-08-04 at 4 49 01 pm](https://cloud.githubusercontent.com/assets/3489862/17397752/bba7a1d2-5a63-11e6-9784-f7558b9fb9da.png)

**Note**
I looked at the logs from my service and I found that everything seemly worked fine, so the api service already started but it might stuck from health check could not reach to them
