### ISSUE TITLE
Containers don't get marked unhealthy when hosts go down

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#5644]
**Foreword: All of my containers have health checks set up on them.**

**Rancher Version:** 1.1.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS RancherOS 0.4.5

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

I have about 17 hosts currently running on a single environment. The servers are spanned across several AWS Regions. We run several servers through a spot instance launch configuration/auto scaler, so we occasionally see a server or two get killed until the spot pricing goes below our pricing limit. I saw about 3 of my servers in one region get killed last night due to spot request pricing.

I use Route53 Manager with a dedicated custom load balancing service to go to my containerized application. Both the load balancer and the application have health checks set up on them (load balancer is Layer 4, application is Layer 7). The setup goes like this:
- Route53 managed loadbalancer-service.stack.zone.com DNS points to the A records of the healthy service
- Load Balancers on this service direct traffic through Rancher's IPSec/internals to the application, usually found on the same cluster as the load balancers

**Results:** 

When the hosts were killed, I found that the services under them were not being marked correctly as unhealthy, but rather "green" (I had already marked them as Inactive before taking the screenshot):

![screen shot 2016-08-05 at 2 53 40 pm](https://cloud.githubusercontent.com/assets/12628715/17447795/8ebe08b2-5b1e-11e6-8e8f-33922d487584.png)

**Expected:**

Dead services with the health checks enabled on them should be going down as unhealthy so that Route53 updates the DNS correctly. Maybe it's the luck of the draw and Rancher picked the 3 hosts doing the health check that ended up going down? This is the second time I've seen this happen, and multiple services are still showing as healthy, even though I can prove the whole host is entirely down.

**Comment by schuylr** [comment]
I tested again by intentionally killing one of my instances this time (instead of several) and I'm still having issues with either service not being marked as unhealthy or degraded:

![screen shot 2016-08-05 at 3 36 13 pm](https://cloud.githubusercontent.com/assets/12628715/17448482/7bb2a4e0-5b22-11e6-94fe-30d4b3e9a814.png)

```
Schuylers-Work-Computer:jewlr4 sjagr$ dig www.jewlr.ca

; <<>> DiG 9.8.3-P1 <<>> www.jewlr.ca
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52313
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.jewlr.ca.			IN	A

;; ANSWER SECTION:
www.jewlr.ca.		47	IN	A	54.234.209.91
www.jewlr.ca.		47	IN	A	54.175.48.152
www.jewlr.ca.		47	IN	A	54.84.65.175
www.jewlr.ca.		47	IN	A	54.196.36.82
www.jewlr.ca.		47	IN	A	54.234.223.208
```

**Comment by schuylr** [comment]
I just added a Layer7 health check for my load balancers, to see if the type mattered, and ran another test by killing a host. It seems it's still not working out in my favour:

![screen shot 2016-08-08 at 10 00 58 am](https://cloud.githubusercontent.com/assets/12628715/17482283/0f5169c4-5d4f-11e6-927b-752ed0cfce76.png)

This is somewhat urgent to me since we depend on the Route53 manager to correctly reflect the list of healthy load balancers.

**Comment by deniseschannon** [comment]
Do these services have healthchecks on them? These look like your own load balancers versus Rancher's load balancers.

If your services do not have health checks, then Rancher assumes that the containers are still running on the host until the host is removed from the Rancher environment. A host in `reconnecting` or `inactive` state will not reschedule containers to other hosts as it assumes that the containers are still running.

If you add a health check to your services/custom load balancers, these will automatically be launched on another host when a host is in reconnecting or inactive state. 

http://docs.rancher.com/rancher/v1.2/en/cattle/health-checks/

**Comment by schuylr** [comment]
@deniseschannon Yes, as stated. Every one of my services have health checks on them, including the load balancers. I even made sure that it was a Layer7 health check instead of just a TCP port check.

**Comment by deniseschannon** [comment]
@schuylr Sorry, I missed the foreword! I thought I had seen that when I had initially read your issue in email but when I came back to it today, I couldn't find that part. :)

Can you share a docker-compose.yml and rancher-compose.yml of one of your stacks?

**Comment by schuylr** [comment]
@deniseschannon It's also my bad, I edited a foreword in since I didn't seem to make it very clear in the rest of my description :)

Here's a stack configuration, some secrets edited out:

docker-compose.yml:
```
productionau:
  ports:
  - 30001:30001/tcp
  dns_search:
  - ec2.internal
  environment: (edited for security)
    RAILS_ENV: production
  external_links:
  - elasticsearch/elasticsearch-au:elasticsearch
  - 'etcd-ha/etcd:'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: cluster=au-host
    io.rancher.container.hostname_override: container_name
  tty: true
  dns:
  - 169.254.169.253
  image: quay.io/jewlr/jewlr4:stable
  volumes:
  - /var/www/assets:/var/www/apps/jewlr4/shared/public/assets
  - /var/www/products:/var/www/apps/jewlr4/shared/public/products
  - /var/www/tmp:/var/www/apps/jewlr4/shared/tmp
  - /var/www/log:/var/www/apps/jewlr4/shared/log
  stdin_open: true
loadbalancer-au:
  ports:
  - 80:80/tcp
  - 8080:8080/tcp
  - 443:443/tcp
  environment:
    SERVICE_NAME: productionau
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: cluster=au-host
    io.rancher.container.hostname_override: container_name
  tty: true
  image: quay.io/jewlr/haproxy
  privileged: true
  stdin_open: true
```

rancher-compose.yml:
```
productionau:
  health_check:
    port: 80
    interval: 30000
    initializing_timeout: 600000
    unhealthy_threshold: 10
    strategy: recreate
    response_timeout: 10000
    request_line: GET "/health" "HTTP/1.0"
    healthy_threshold: 2
loadbalancer-au:
  health_check:
    port: 8888
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/health" "HTTP/1.0"
    healthy_threshold: 2
```

I believe I left my load balancer as a public image so you can pull and examine how it works as well.
