### ISSUE TITLE
Rancher internal DNS not immediately available on container startup

### ISSUE THREAD

**Issue by francoishill** [rancher/rancher#5652]
**Rancher Version:** 1.1.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 3 CoreOS droplets on DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node Rancher with Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle environment

**Steps to Reproduce:**
- Create a shared-dbs stack which contains a Mysql service with one container
- Create another stack with a service that uses `external_links` in the docker-compose.yml file to link to that shared Mysql service. They are in different stacks. For instance if we have the external link as `shared-dbs/mysql:external-mysql`.
- This other service must try to connect on startup to that DNS `external-mysql` with its normal Mysql connection string. This will fail with error `dial tcp 10.42.148.235:3306: getsockopt: no route to host`

**Results:** 

If the other service has requirement to be able to connect to Mysql on startup, the container fails to start.

**Expected:**

The "route" must be accessible from startup of the container.

**Comment by vincent99** [comment]
Check that cross-host networking is working in general?  http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#cross-host-communication

Networking, Metadata, and DNS entries are available at the time the entrypoint is run:
 ```yaml
#stack-1-docker-compose.yml
mysql:
  environment:
    MYSQL_ROOT_PASSWORD: foobar
  image: mysql
```

```yaml
#stack2-docker-compose.yml
test:
  external_links:
  - stack1/mysql:external-mysql
  tty: true
  entrypoint:
  - mysql
  - -u
  - root
  - -pfoobar
  - -h
  - external-mysql
  image: mysql
```

![image](https://cloud.githubusercontent.com/assets/753917/17535531/f6947dd6-5e43-11e6-8660-8b9e4e5a63fb.png)
