### ISSUE TITLE
./rancher export to a file or stdout has extra digits appended and is not formatted correctly

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5672]
**Rancher Version:**Master

**Docker Version:**1.10.3, 1.12.0

Rancher CLI version: v0.0.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a rancher-cli set up and create stacks, services 
2.  Try the ./rancher export command:
./rancher export mystack
```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher export mystack
docker-compose.yml0000644000000000000000000000021000000000000014363 ustar00rootroot00000000000000soumyaserv1:
  image: nginx
myservice:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
rancher-compose.yml0000644000000000000000000000006200000000000014543 ustar00rootroot00000000000000soumyaserv1:
  scale: 1
myservice:
  scale: 3

```
