### ISSUE TITLE
official rancher-compose docker image

### ISSUE THREAD

**Issue by matbaj** [rancher/rancher#5695]
**Rancher Version:**
N/A
**Docker Version:**
N/A
**OS and where are the hosts located? (cloud, bare metal, etc):**
Everything
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher hosting + dev workspace / ci workspace
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Docker 
**Steps to Reproduce:**
N/A
**Results:** 
N/A
**Expected:**

Docker images which provides rancher-compose tool for deploying projects to rancher.
Simple image where there is rancher-compose binary in PATH.
There is already existing image: https://hub.docker.com/r/monostream/rancher-compose/ but it is not official and has only one release.

Example usage is deploy stage for gitlab ci
Sample .gitlab-ci.yml 

```
deploy to staging:
  image: rancher/rancher-compose
  environment: staging
  before_script:
    - export TAG=$CONTAINER_BUILD_TAG
    - echo "deploying $TAG"
  stage: deploy
  script: rancher-compose -f docker-compose.yml -f docker-compose.stage.yml -p fancyproject-staging up -p -u -d
  only:
    - master
```

for fixed version you can use docker image tag for example: rancher/rancher-compose:v0.8.6
