### ISSUE TITLE
When fetching metadata with chinese characters , it shows up as "???? 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5701]
Rancher server version - v1.2.0-pre2-rc1
Rancher compose version v0.9.1-rc2

Use the following compose files to create service which has chinese characters in metadata field.

```
Sangeethas-MacBook-Pro:rancher-compose-v0.9.1-rc2 sangeethahariharan1$ cat docker-compose.yml 
testnow123:
  environment:
    A: :A
    B: :B
    C: 'contains: colon'
    D: 'contains: colon'
    E: œ∑˙ß®∫ƒ˜†∂˜老版本没问题
  image: sangeetha/testclient
Sangeethas-MacBook-Pro:rancher-compose-v0.9.1-rc2 sangeethahariharan1$ cat rancher-compose.yml 
testnow123:
  scale: 1
  metadata:
    test1: œ∑˙ß®∫ƒ˜†∂˜老版本没问题
Sangeethas-MacBook-Pro:rancher-compose-v0.9.1-rc2 sangeethahariharan1$ 
```

Exec into the container (of the service) and fetch metadata. It appears as "?????".
But the environment variable "E" that had chinese characters in it , showsup fine.

```
root@4476bb14d573:/# curl -H 'Accept:application/json' http://rancher-metadata/latest/services/testnow123/metadata/test1 -o metadata1.out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0    713      0 --:--:-- --:--:-- --:--:--   730
root@4476bb14d573:/# hexdump -x metadata1.out
0000000    3f22    3f3f    3f3f    3f3f    3f3f    3f3f    3f3f    3f3f
0000010    3f3f    0022                                                
0000013
root@4476bb14d573:/# curl -H 'Accept:application/json' http://rancher-metadata/latest/self/service/metadata/test1 -o metadataself.out    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0    462      0 --:--:-- --:--:-- --:--:--   475
root@4476bb14d573:/# hexdump -x metadataself.out                                                                                     
0000000    3f22    3f3f    3f3f    3f3f    3f3f    3f3f    3f3f    3f3f
0000010    3f3f    0022                                                
0000013
root@4476bb14d573:/# env | grep ^E=   
E=œ∑˙ß®∫ƒ˜†∂˜老版本没问题
root@4476bb14d573:/# env | grep ^E= | hexdump -x
0000000    3d45    93c5    88e2    cb91    c399    c29f    e2ae    ab88
0000010    92c6    9ccb    80e2    e2a0    8288    9ccb    80e8    e781
0000020    8889    9ce6    e6ac    a1b2    97e9    e9ae    98a2    000a
000002f
root@4476bb14d573:/# 
```
