### ISSUE TITLE
Prompted multiple times for some questions.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5756]
rancher-compose version v0.9.2-rc1

When trying to use rancher-compose up with the following yml files , I am prompted to enter "Hosted Zone ID ROUTE53_ZONE_ID" multiple times (3 times)

```
Sangeethas-MacBook-Pro:rancher-compose-v0.9.2-rc1 sangeethahariharan1$ cat dc-route53.yml
route53:
  image: rancher/external-dns:v0.5.0
  expose: 
   - 1000
  environment:
    AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    AWS_REGION: ${AWS_REGION}
    ROOT_DOMAIN: ${ROOT_DOMAIN}
    ROUTE53_ZONE_ID: ${ROUTE53_ZONE_ID}
    TTL: ${TTL}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-dns"
Sangeethas-MacBook-Pro:rancher-compose-v0.9.2-rc1 sangeethahariharan1$ cat rc-route53.yml
.catalog:
  name: "Route53 DNS"
  version: "v0.5.0-rancher1"
  description: "Rancher External DNS service powered by Amazon Route53. Requires Rancher version 0.44.0"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: "AWS_ACCESS_KEY"
      label: "AWS Access Key ID"
      description: "Access key ID for your AWS account"
      type: "string"
      required: true
    - variable: "AWS_SECRET_KEY"
      label: "AWS Secret Access Key"
      description: "Secret access key for your AWS account"
      type: "string"
      required: true
    - variable: "AWS_REGION"
      label: "AWS Region"
      description: "AWS region name"
      type: "string"
      default: "us-west-2"
      required: true
    - variable: "TTL"
      label: "TTL"
      description: "The resource record cache time to live (TTL), in seconds"
      type: "int"
      default: 60
      required: false
    - variable: "ROOT_DOMAIN"
      label: "Hosted Zone Name"
      description: "Route53 hosted zone name (zone has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>"
      type: "string"
      required: true
    - variable: "ROUTE53_ZONE_ID"
      label: "Hosted Zone ID"
      description: "If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use."
      type: "string"
      required: false
    - variable: "HEALTH_CHECK_INTERVAL"
      label: "Health Check Interval"
      description: "The health check interval in seconds. Raise this value if the global number of requests from your account exceed the Route53 API rate limits."
      type: "int"
      min: 2
      max: 999
      default: 15
      required: false

route53:
  health_check:
    port: 1000
    interval: ${HEALTH_CHECK_INTERVAL}000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 5000

Sangeethas-MacBook-Pro:rancher-compose-v0.9.2-rc1 sangeethahariharan1$ 
```

```
Sangeethas-MacBook-Pro:rancher-compose-v0.9.2-rc1 sangeethahariharan1$ ./rancher-compose -p testnew -f dc-route53.yml -r rc-route53.yml up
INFO[0000] Creating stack testnew                       
AWS region name
AWS Region AWS_REGION[us-west-2]: 
Route53 hosted zone name (zone has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>
Hosted Zone Name ROOT_DOMAIN[]: 
WARN[0010] The ROOT_DOMAIN variable is not set. Substituting a blank string. 
If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use.
Hosted Zone ID ROUTE53_ZONE_ID[]: ^C
Sangeethas-MacBook-Pro:rancher-compose-v0.9.2-rc1 sangeethahariharan1$ ./rancher-compose -p testnew123 -f dc-route53.yml -r rc-route53.yml up
INFO[0000] Creating stack testnew123                    
Route53 hosted zone name (zone has to be pre-created). DNS entries will be created for <service>.<stack>.<environment>.<hosted zone>
Hosted Zone Name ROOT_DOMAIN[]: sangee-test.com
If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use.
Hosted Zone ID ROUTE53_ZONE_ID[]: 
WARN[0068] The ROUTE53_ZONE_ID variable is not set. Substituting a blank string. 
The resource record cache time to live (TTL), in seconds
TTL TTL[60]: 
Access key ID for your AWS account
AWS Access Key ID AWS_ACCESS_KEY[]:  ************
Secret access key for your AWS account
AWS Secret Access Key AWS_SECRET_KEY[]: ****************
AWS region name
AWS Region AWS_REGION[us-west-2]: 
The health check interval in seconds. Raise this value if the global number of requests from your account exceed the Route53 API rate limits.
Health Check Interval HEALTH_CHECK_INTERVAL[15]: 
If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use.
Hosted Zone ID ROUTE53_ZONE_ID[]: 
INFO[0112] [0/1] [route53]: Creating                    
INFO[0112] Creating service route53                     
INFO[0113] [0/1] [route53]: Created                     
If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use.
Hosted Zone ID ROUTE53_ZONE_ID[]: 
INFO[0150] [0/1] [route53]: Starting                    
INFO[0154] [1/1] [route53]: Started                     
If there are multiple zones with the same name, then you must additionally specify the ID of the hosted zone to use.
Hosted Zone ID ROUTE53_ZONE_ID[]: 
route53_1 | 2016-08-17T21:09:59.279771400Z time="2016-08-17T21:09:59Z" level=info msg="Starting Rancher External DNS service" 
route53_1 | 2016-08-17T21:09:59.536163493Z time="2016-08-17T21:09:59Z" level=info msg="Configured Route 53 with hosted zone 'sangee-test.com.' in region 'us-west-2' " 
route53_1 | 2016-08-17T21:09:59.536746842Z time="2016-08-17T21:09:59Z" level=info msg="Healthcheck handler is listening on :1000" 
^C
```
