### ISSUE TITLE
[rancher-compose] creating a new stack with a default_cert fails to actually set the certificate

### ISSUE THREAD

**Issue by cmeury** [rancher/rancher#5805]
**Rancher Version:** v1.1.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** EC2 Arch Linux

**Setup Details:** Single node, external AWS RDS MySQL

**Environment Type:** Cattle

**Steps to Reproduce:** 

**docker-compose.yml**

``` yaml
star-xyz-abc-lb:
  ports:
  - 443:64000
  external_links:
  - app-dev/app-service:app-service
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.app-dev/app-service: app.xyz.abc=5000
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```

**rancher-compose.yml**

``` yaml
star-xyz-abc-lb:
  load_balancer_config:
    haproxy_config: {}
  default_cert: star.xyz.abc
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

Command: 

``` bash
rancher-compose --project-name public-lb --env-file env.ini up -d
```

**Results:** Stack and service created, but certificate was not set. After editing the service and setting the certificate manually, everything works as expected.

**Expected:** Default certificate is used.
