### ISSUE TITLE
environment variables showing up as nil

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5806]
**Rancher Version:**
v1.2.0-pre2
rancher-compose v0.9.2

**Steps to Reproduce:**

1. set an environment variable `export MYSQL_ROOT_PASSWORD=test`
2. start a service using rancher-compose

```
dbtest:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 
```

**Results:** 
In the API, the environment variable is `<nil>`.

**Expected:**
The environment variable should be `test`.
