### ISSUE TITLE
Customisation of Rancher ingress/haproxy configuration

### ISSUE THREAD

**Issue by rsuniev** [rancher/rancher#5823]
**Rancher Version: v.1.1.3**
**Environment Type: Kubernetes**

Currently, there is no way to customise rancher ingress configuration.

Add support for customisation of some HAProxy parameters, such as timeouts, client_max_body_size and others via ConfigMaps

Add the ability to redefine those parameters per Ingress Resource. 

There is work already done in kubernetes. Please check the example on how to customise NGINX: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/customization

**Comment by alena1108** [comment]
for 1.1.4 release, we are going to add support for global/default sections customization. Once we release refactored LB (1.2), we will switch ingress to program against it, and there support for frontends/backends customization will be in place.

**Comment by alena1108** [comment]
This issue should be fixed for both 1.2 and 1.3 k8s templates

**Comment by alena1108** [comment]
Global/Defaults can be configured via ingress annotations. Nginx supports 2 ways of custom configuration - via annotations or via configMaps - but we will go with annotations approach as we use it for a bunch of other customizable parameters. 

The format/example of the custom config:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\nbalance source\ntimeout server 70000\nglobal\nmaxconnrate 60"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80

```

In the config:

* defaults/global keywords identify the customizable sections
* every new parameter should be followed by the new line

The same format will be used for frontends/backends sections as we add support for it. Basically the entire haproxy custom config would be passed as a single parameter (see the comments on the custom config format on the Rancher side in one of the comments to https://github.com/rancher/rancher/issues/2179)
