### ISSUE TITLE
Load balancer taking 5+ seconds to load

### ISSUE THREAD

**Issue by OmgImAlexis** [rancher/rancher#5831]
**Rancher Version:** v1.1.3

**Docker Version:**  1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal

**Setup Details:** 2 node rancher with internal DB

**Environment Type:** Swam

**Steps to Reproduce:** 

docker-compose.yml

```
hostname-test:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  entrypoint:
  - sh
  - -c
  - wget -q http://pastebin.com/raw/M9LB9jdQ -O app.js && npm install express && node app.js
  image: asakaguchi/node:onbuild
  working_dir: /usr/local/src/app
  stdin_open: true
test-load-balancer:
  ports:
  - 443:3000
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
  tty: true
  image: rancher/load-balancer-service
  links:
  - hostname-test:hostname-test
  stdin_open: true
```

rancher-compose.yml

```
hostname-test:
  scale: 50
mongodb:
  scale: 1
test-load-balancer:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: test-cert
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

If I run `curl -o /dev/null -s -w %{time_total}\\n https://192.168.1.90 --insecure` I get 5 seconds where as running the same command on the docker containers indevidially gives me less than 2ms so there's something going on between the load balancer and the docker containers.
