### ISSUE TITLE
Kubernetes hostPort is not working

### ISSUE THREAD

**Issue by bonifaido** [rancher/rancher#5857]
**Rancher Version:**
1.2.0-pre2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with 3 agents in the Kubernetes environment
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes (1.3.0-rancher3)
**Steps to Reproduce:**
Create a pod with a hostPort defined:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
```

**Results:** 
You can't access the pod from outside the cluster on the hostPort
**Expected:**
The opposite.
