### ISSUE TITLE
[rancher-compose] ENV variables are not correctly set for secondary containers

### ISSUE THREAD

**Issue by waysidekoi** [rancher/rancher#5876]
**Rancher Version:**
v1.1.3
**Rancher-Compose Version:**
rancher-compose version v0.9.2
**Docker Version:**
1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.1.1503 (Core), AWS ec2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
`HELLO=myfriend rancher-compose up`

```
test:
  tty: true
  image: ubuntu:14.04.2
  stdin_open: true
  volumes_from:
  - test-data
  labels:
    io.rancher.sidekicks: test-data
  environment:
    - HELLO

test-data:
  tty: true
  command:
  - cat
  image: ubuntu:14.04.2
  stdin_open: true
  volumes:
    - /tmp
  environment:
    - HELLO
```

**Results:** 

``` json
{
  "launchConfig": {
    "environment": {
      "HELLO": "myfriend"
    }
  },
  "secondaryLaunchConfigs":{
    "environment": {
      "HELLO": ""
    }
  }
}
```

**Expected:**
Expected both the primary and secondary containers to have the same environment variables

**Comment by waysidekoi** [comment]
Workaround:
```yaml
test:
  tty: true
  image: ubuntu:14.04.2
  stdin_open: true
  volumes_from:
  - test-data
  labels:
    io.rancher.sidekicks: test-data
  environment:
    - HELLO

test-data:
  tty: true
  command:
  - cat
  image: ubuntu:14.04.2
  stdin_open: true
  volumes:
    - /tmp
  environment:
    - HELLO=$HELLO
```
