### ISSUE TITLE
A problem occurred when rancher-compose convert the 'extends' field

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#5913]
**Rancher Version:** v1.2.0-pre2

**Docker Version:** 1.10.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Add this docker-compose file by Rancher UI, we use 'extends' field.
Attention: vp0.CORE_PEER_ID=vp0   vp1.CORE_PEER_ID=vp1  vp2.CORE_PEER_ID=vp2  

```
vp0:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
    - CORE_LOGGING_LEVEL=INFO
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    - CORE_PBFT_GENERAL_MODE=batch
  command: peer node start
vp1:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  links:
    - vp0
vp2:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  links:
    - vp0
```

Finally we get the following file.

```
vp1:
  environment:
    CORE_LOGGING_LEVEL: INFO
    CORE_PBFT_GENERAL_MODE: batch
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_DISCOVERY_ROOTNODE: vp0:7051
    CORE_PEER_ID: vp2
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_VM_ENDPOINT: http://172.17.0.1:4243
  command:
  - peer
  - node
  - start
  image: hyperledger/fabric-peer
  links:
  - vp0:vp0
vp0:
  environment:
    CORE_LOGGING_LEVEL: INFO
    CORE_PBFT_GENERAL_MODE: batch
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_ID: vp0
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_VM_ENDPOINT: http://172.17.0.1:4243
  command:
  - peer
  - node
  - start
  image: hyperledger/fabric-peer
vp2:
  environment:
    CORE_LOGGING_LEVEL: INFO
    CORE_PBFT_GENERAL_MODE: batch
    CORE_PEER_ADDRESSAUTODETECT: 'true'
    CORE_PEER_DISCOVERY_ROOTNODE: vp0:7051
    CORE_PEER_ID: vp2
    CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN: pbft
    CORE_VM_ENDPOINT: http://172.17.0.1:4243
  command:
  - peer
  - node
  - start
  image: hyperledger/fabric-peer
  links:
  - vp0:vp0
```

Attention: vp0.CORE_PEER_ID=vp0   **vp1.CORE_PEER_ID=vp2**  vp2.CORE_PEER_ID=vp2  

Maybe a problem occurred when rancher-compose convert the 'extends' field.

**Comment by joshwget** [comment]
It seems like libcompose doesn't have the same problem. Smaller reproducible example:
```
vp0:
  command: env
  image: busybox
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
vp1:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp1
vp2:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp2
```
