### ISSUE TITLE
No access to the internet from container inside Managed Network

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#5920]
**Rancher Version:** 1.1.3

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** 2 hosts Linux Ubuntu 16.04.1, one of them runs Rancher server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher server, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Create stack using the following docker-compose.yml:
```
other:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: busybox
  links:
  - 'busy:'
  stdin_open: true
busy:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: busybox
  stdin_open: true
```

Navigate to container running other
Execute `ping busy.rancher.internal`
Execute `ping google.com`

**Results:** 
PING busy.rancher.internal (10.42.158.227): 56 data bytes
64 bytes from 10.42.158.227: seq=0 ttl=64 time=0.106 ms
...

**ping: bad address 'google.com'**

**Expected:**
Both pings run successfully.

I tried switching containers to Host network mode, in that case they start pinging google.com, but after that they stop seeing each other (ping busy.rancher.internal)

The contents of my /var/lib/cattle/etc/cattle/dns/answers.json from my Network Agent:
```
{
	"default": {
		"search": ["rancher.internal"],
		"recurse": ["8.8.8.8",
		"8.8.4.4"],
		"authoritative": ["rancher.internal"],
		"a": {
			"test_busy_1.rancher.internal.": {
				"answer": ["10.42.158.227"]
			},
			"rancher-metadata.rancher.internal.": {
				"answer": ["169.254.169.250"]
			},
			"test_other_1.rancher.internal.": {
				"answer": ["10.42.186.215"]
			},
			"other.test.rancher.internal.": {
				"answer": ["10.42.186.215"]
			},
			"busy.test.rancher.internal.": {
				"answer": ["10.42.158.227"]
			},
		},
		"cname": {
			
		}
	},
	"10.42.158.227": {
		"search": ["test.rancher.internal",
		"busy.test.rancher.internal",
		"rancher.internal"],
		"recurse": [],
		"authoritative": [],
		"a": {
			
		},
		"cname": {
			
		}
	},
	"10.42.186.215": {
		"search": ["test.rancher.internal",
		"other.test.rancher.internal",
		"rancher.internal"],
		"recurse": [],
		"authoritative": [],
		"a": {
			"busy.rancher.internal.": {
				"answer": ["10.42.158.227"]
			},
			"busy.test.rancher.internal.": {
				"answer": ["10.42.158.227"]
			}
		},
		"cname": {
			
		}
	}
}
```

The contents of /etc/resolv.conf from other container:
```
/ # cat /etc/resolv.conf
search internal.corp test.rancher.internal other.test.rancher.internal rancher.i
nternal
nameserver 169.254.169.250
```

The contents of /etc/resolv.conf from the host:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search internal.corp
```

`ping google.com` works on the host successfully.

I need both container to reside within the same managed network and at the same time one of them needs to be able to access the external internet service.

**Comment by gerich-home** [comment]
I believe my issue is probably the duplicate of https://github.com/rancher/rancher/issues/4291

However I resolved it differently.
As I was using Ubuntu I tried to collect the list of DNS addresses (http://askubuntu.com/questions/152593/command-line-to-list-dns-servers-used-by-my-system)
First I have run ifconfig to collect the list of network interfaces on my host.
Then I run the command nmcli device show <interfacename> | grep IP4.DNS for each of the intefaces I found.
Using these command I have collected 3 DNS server ips.

Then I changed my stack's config to the following:
```
other:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 192.168.32.13
  - 192.168.32.16
  - 192.168.32.54
  image: busybox
  links:
  - 'busy:'
  stdin_open: true
busy:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  dns:
  - 192.168.32.13
  - 192.168.32.16
  - 192.168.32.54
  image: busybox
  stdin_open: true
```

And they started working!

However the potential problem is that these ips can be specific to the host (not my case) and you have to manually specify all of them for each service you have
