### ISSUE TITLE
[rancher-compose] Can't create empty environment variable

### ISSUE THREAD

**Issue by beatcracker** [rancher/rancher#5935]
### Details
- Rancher Version: **v1.1.1**
- Rancher Compose version: **v0.8.6**
- Docker Version: **version 1.11.2, build b9f10c9**
- OS and where are the hosts located: **CentOS Linux 7 (4.6.4-1.el7.elrepo.x86_64) in Hyper-V VM**
- Setup Details: **single rancher node with one host**
- Environment Type: **Cattle**
### Steps to Reproduce

Create new service configuration:
- `docker-compose.yml`

```
alpine:
  environment:
    EMPTY1:
    EMPTY2: ""
    EMPTY3: ''
    EMPTY4: null
    EMPTY5:  ~
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - cat
  image: alpine:latest
  stdin_open: true
```
- `rancher-compose.yml`

```
alpine:
  scale: 1
```

Push it to the Rancher host using `rancher-compose`:

``` bash
rancher-compose -p alpine up
```

Access container via shell and run `env` command.
### Results

Empty environment variables specified in `docker-compose.yml` are not created:

``` bash
/ # env
HOSTNAME=18a158c41d55
SHLVL=2
HOME=/root
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
```
### Expected

If the same service is created via Rancher UI, empty environment variables are visible in the API and in the container:

![Rancher UI](https://cloud.githubusercontent.com/assets/7583050/18384222/12520140-7692-11e6-8da0-e988c832edb8.png)

``` json
"launchConfig": {
  "environment": {
    "EMPTY1": '',
    "EMPTY2": '',
    "EMPTY3": '',
    "EMPTY4": '',
    "EMPTY5": '',
  }
```

``` bash
/ # env
HOSTNAME=ba962f043e17
SHLVL=2
HOME=/root
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
EMPTY1=
EMPTY2=
EMPTY3=
EMPTY4=
EMPTY5=
```
