### ISSUE TITLE
Loadbalancer SSL handshake failure

### ISSUE THREAD

**Issue by maximegaillard** [rancher/rancher#5936]
**Rancher Version:**

1.2.0-pre2 (also tested on v1.1.3)

**Docker Version:**

1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

Cloud (Openstack instance)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I'm trying to access a postgresql cluster from outside through the `rancher/load-balancer-service` over SSL. The certificate is provided by the Let's Encrypt community plugin (https://github.com/janeczku/rancher-letsencrypt).

docker-compose.yml

```
lb:
  image: rancher/load-balancer-service
  tty: true
  stdin_open: true
  links:
    - dbnode:dbnode
  ports:
    - ${PUBLIC_PORT}:5432/tcp
    - 1111:5432/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.ssl.ports: '${PUBLIC_PORT}'
    io.rancher.container.pull_image: always
    io.rancher.loadbalancer.target.dbnode: ${DOMAIN}:${PUBLIC_PORT}=5432 # tested with or without this line
  health_check:
    port: 8008
    request_line: GET / HTTP/1.0
    interval: 2000
    healthy_threshold: 2
    unhealthy_threshold: 3
    response_timeout: 2000
```

rancher-compose.yml
```
lb:
  scale: 1
  load_balancer_config:
    description: 'lb'
    name: lb config
  default_cert: ${CERT_NAME}
```

**Results:** 

I can access Postgresql through the no-ssl port (1111), but through the SSL port I can't : my `psql` command ends up stalling.

According to the HAProxy logs, the issue is an `SSL Handshake failure` :
`Sep  9 09:39:37 localhost haproxy[1132]: xx.xx.xx.xx:55815 [09/Sep/2016:09:39:17.275] e54cf7f6-9f4a-4487-87a3-aa3adb340ad2_5432_frontend/1: SSL handshake failure`

The strange thing is, I can access it with openssl

```
openssl s_client -connect FQDN:5432
CONNECTED(00000003)
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=FQDN
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
XXX
-----END CERTIFICATE-----
subject=/CN=FQDN
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
---
SSL handshake has read 3442 bytes and written 456 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: 3D637AAFDBA43D1021A9F083AAE54E8940F048E6210AC4DE313A5FA031DA38C6
    Session-ID-ctx:
    Master-Key: EABBC21601CC27E6259678A03B30E882E3AA182C12D71B47C8FD8AE69DA039F020B7FD19EF18DF85E5FAEDA96C29842B
    Key-Arg   : None
    Start Time: 1473407829
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```
