### ISSUE TITLE
Intermediate Error when rolling back - "Rolling-Back (Failed to allocate instance [container:1i1809]: volumeFrom instance is not running : Dependencies readiness error)"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5941]
Server version -  v1.2.0-pre3-rc1

Steps to reproduce the problem:

Perform the following action using rancher-compose:

Create service with volume mounts.
Upgrade this service.
Once in upgraded state , rollback.

service is still in "rolling-back" state when we expect it to be in "active" state.

In UI , we see the following error for the service - "Rolling-Back (Failed to allocate instance [container:1i1809]: volumeFrom instance is not running : Dependencies readiness error)"

After few seconds , we see the roll back proceed and succeed.

```
admin_client = <cattle.Client object at 0x7f0442ac3fd0>
client = <cattle.Client object at 0x7f0442805890>
rancher_compose_container = None, socat_containers = None

    @if_compose_data_files
    def test_rancher_compose_inservice_upgrade_volume_mount_sidekick2_rollback(
            admin_client, client, rancher_compose_container, socat_containers):
    
        env_name = random_str().replace("-", "")
    
        # Create an environment using up
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice3_1.yml", env_name,
            "up -d", "Creating stack", "rc_inservice3_1.yml")
    
        env, service = get_env_service_by_name(client, env_name, "test1")
    
        assert service.state == "active"
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk1",
            {"testsk1": "value1"}, 1, primary=False)
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk2",
            {"testsk2": "value1"}, 1, primary=False)
        primary_containers = get_service_containers_with_name(
            admin_client, service, env_name+"_test1", 1)
    
        # Upgrade environment using up --upgrade
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice3_4.yml", env_name,
            "up --upgrade -d", "Upgrading")
        service = client.reload(service)
        assert service.state == "upgraded"
    
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1",
            {"test1": "value1"}, 0)
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1",
            {"test1": "value1"}, 1)
    
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk1",
            {"testsk1": "value1"}, 0)
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk1",
            {"testsk1": "value1"}, 1, primary=False)
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk2",
            {"testsk2": "value1"}, 0)
        check_config_for_service_sidekick(
            admin_client, service, env_name+"_test1_sk2",
            {"testsk2": "value2"}, 1, primary=False)
        check_container_state(client, primary_containers, "stopped")
    
        # Rollback upgrade
    
        launch_rancher_compose_from_file(
            client, INSERVICE_SUBDIR, "dc_inservice3_4.yml", env_name,
            "up --rollback -d", "Started")
        service = client.reload(service)
>       assert service.state == "active"
E       assert 'rolling-back' == 'active'
E         - rolling-back
E         + active
```

**Comment by sangeethah** [comment]
```
Sangeethas-MacBook-Pro:inservicedc sangeethahariharan1$ cat dc_inservice3_4.yml
sk1:
  image: sangeetha/testnewhostrouting
  volumes_from:
  - sk2
  labels:
    testsk1: value1
test1:
  labels:
    io.rancher.sidekicks: sk1,sk2
    test1: value1
  image: sangeetha/testclient
  volumes_from:
  - sk1
sk2:
  image: sangeetha/testlbsd:latest
  labels:
    testsk2: value2
Sangeethas-MacBook-Pro:inservicedc sangeethahariharan1$ cat dc_inservice3_1.yml
sk1:
  image: sangeetha/testnewhostrouting
  volumes_from:
  - sk2
  labels:
    testsk1: value1
test1:
  labels:
    io.rancher.sidekicks: sk1,sk2
    test1: value1
  image: sangeetha/testclient
  volumes_from:
  - sk1
sk2:
  image: sangeetha/testlbsd:latest
  labels:
    testsk2: value1
Sangeethas-MacBook-Pro:inservicedc sangeethahariharan1$ cat rc_inservice3_1.yml
test1:
  scale: 3
```
