### ISSUE TITLE
LB service is not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5963]
Rancher Version:v1.2.0-pre3-rc2 

Steps to reproduce the problem:
Create K8s environments.

Create LB service using the following yml

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxlb
spec:
  replicas: 2
  selector:
    name: nginxlb
  template:
    metadata:
      labels:
        name: nginxlb
    spec:
      containers:
        - name: nginxlb
          image: sangeetha/testnewhostrouting
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: lbnginx
  labels:
    name: lbnginx
spec:
  type: LoadBalancer
  ports:
  - port: 8889
    targetPort: 80
  selector:
    name: nginxlb
```

Once Lb service get created , wait for the IP to be available for the LB service.

```
> kubectl get servoce
the server doesn't have a resource type "service"
> kubectl get service
NAME         CLUSTER-IP      EXTERNAL-IP      PORT(S)    AGE
kubernetes   10.43.0.1       <none>           443/TCP    5h
lbnginx      10.43.232.148   104.198.253.78   8889/TCP   11m
>
```

Lb IP is not reachable.

No backends are being added to the LB service.

<img width="869" alt="screen shot 2016-09-13 at 1 48 09 pm" src="https://cloud.githubusercontent.com/assets/4266958/18490876/c3574396-79b8-11e6-928d-d4d3a0daf211.png">
