### ISSUE TITLE
Rancher load balancer service as sidekick

### ISSUE THREAD

**Issue by mckn** [rancher/rancher#5980]
**Rancher Version:**
Rancher: v1.1.3
Cattle: v0.165.8.1

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS (4.4.0-34-generic) on a cloud provider

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
```yml
web-gateway:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: web-lb
      io.rancher.scheduler.affinity:host_label: server=gw
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/ssl:/etc/nginx/certs:ro

  web-lb:
    image: rancher/load-balancer-service
    environment:
      - VIRTUAL_HOST=*.webs.com
      - VIRTUAL_PORT=80
    external_links:
      - webs/web:web
    expose:
      - 80:80
    stdin_open: true
    tty: true
    labels:
      io.rancher.loadbalancer.target.webs/web: 80=80
```
**Results:** 
 Error (Image [rancher/load-balancer-service:latest] failed to pull: Error: image rancher/load-balancer-service:latest not found)

**Expected:**
I would like to run a rancher loadbalancer as a side kick for our nginx proxy that handles SSL etc. So I only want to use the rancher loadbalancer to balance load between different subdomains and to different applications.
