### ISSUE TITLE
Rancher Compose attributes can't be included in docker-compose.yml

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#5987]
In Rancher Compose, attributes from a rancher-compose.yml file can also be included in the docker-compose.yml file. This isn't currently working in the new Rancher CLI.

**Comment by soumyalj** [comment]
Tested with Rancher version v1.2.0-pre4-rc4 and rancher cli version v0.3.0-rc3. Rancher compose attributes can be included in docker compose files and stacks/services can be created successfully. Example below includes rancher compose attributes such as scale, load_balancer_config, health_check in the docker-compose.yml file
docker-compose.yml 
```
lb:
  image: rancher/load-balancer-service
  ports:
  # Listen on public port 80 and direct traffic to private port 80 of the service
  - 80:80
  labels:
    # Put load balancer containers on hosts with label lb=true
    io.rancher.scheduler.affinity:host_label: lb=true
  scale: 1
  load_balancer_config:
    name: lb config
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```
