### ISSUE TITLE
Containers can't find Convoy-EFS volume after Host restart

### ISSUE THREAD

**Issue by Joeasaurus** [rancher/rancher#5995]
**Rancher Version:** 1.1.3

**Docker Version:**  1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS 0.6.1. Hosted on AWS EC2, added to default Environment via "Custom" Host addition. Boot managed via an AutoScaling Group & Cloud-Config.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB):** Single Node with External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos):** Cattle

**Steps to Reproduce:**
I configured the EC2 hosts to boot with a `rancher/server` instance that connects to my external DB. I then manually add the same host via the "Custom" method, so it is a Host in the Environment. 

When I kill that machine and another is booted in it's place, it connects to the DB and gets all it's config back. I "Custom" add it again and it's available in the Environment again. Cool, this external DB stuff works.

I added a `convoy-efs` Service to it (from the Catalog), added some volumes and kill the machine again. It comes back and gets the settings from the DB again, this time including the `convoy-efs` Service. When I "Custom" add the Host again, the convoy Service starts again on that host and the volumes are available again.

I then add a GitLab Service, which uses the `convoy-efs` volumes to store it's data. Here is it's `docker-compose.yml` (it's behind an LB usually, ignore the odd port mappings):

``` yaml
GitLab-Server:
  ports:
  - 22/tcp
  - 80/tcp
  hostname: git.domain.com
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gitlab/gitlab-ce:latest
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://git.domain.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 2222
      nginx['listen_port'] = 80
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = {
        "X-Forwarded-Proto" => "https",
        "X-Forwarded-Ssl" => "on"
      }
    GITLAB_HOST: "https://git.domain.com"
    GITLAB_EMAIL_FROM: "gitlab@domain.com"
  volumes:
  - gitlab-etc:/etc/gitlab
  - gitlab-logs:/var/log/gitlab
  - gitlab-opt:/var/opt/gitlab
  volume_driver: convoy-efs
```

**Results:** The GitLab Service never becomes active. The containers spin because they can't see the data they expected. Here's the error message: 

```
404 Client Error: Not Found ("open /var/lib/rancher/convoy/convoy-efs-245b4976-c778-42a9-972f-347ed08b0ba7/mnt/gitlab-logs: no such file or directory"
```

**Expected:** The new `convoy-efs` Service on the freshly added Host should "tell Rancher" that it's path name has changed so other Services can use it as they expect to. 

I'm not sure "tell Rancher" is the exact fix, as I'm not quite sure what causes this issue, but I checked on the Host and the `convoy-efs` volumes are all definitely mounted, they're just in a different directory:

```
[rancher@ip-172-31-3-46 ~]$ ls /var/lib/rancher/convoy/convoy-efs-f23b27c2-9c21-407c-abd9-2ea6b65dd4ae/mnt/
config  gitlab-etc  gitlab-logs  gitlab-opt  gitlab-runner-etc
[rancher@ip-172-31-3-46 ~]$ ls /var/lib/rancher/convoy/convoy-efs-f23b27c2-9c21-407c-abd9-2ea6b65dd4ae/mnt/gitlab-etc/
gitlab.rb            ssh_host_ecdsa_key      ssh_host_ed25519_key      ssh_host_rsa_key      trusted-certs
gitlab-secrets.json  ssh_host_ecdsa_key.pub  ssh_host_ed25519_key.pub  ssh_host_rsa_key.pub
```

Thanks in advance!
