### ISSUE TITLE
scale_policy causes cattle to try to deploy containers forever

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6007]
Steps to reproduce:
1. create an environment with two hosts
2. Try to run this compose:
```
one:
    image: ubuntu
    tty: true
    stdin_open: true
    scale_policy:
    labels:
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
        io.rancher.sidekicks: data
    volumes_from:
    - data
    scale_policy:
        increment: 1
        max: 3
        min: 1

data:
    image: ubuntu
    tty: true
    stdin_open: true
```
