### ISSUE TITLE
Kubernetes LoadBalancer service type creates "k8s service" instead of "Load Balancer"

### ISSUE THREAD

**Issue by tehdeadone** [rancher/rancher#6060]
**Rancher Version:** 1.2.0-pre2 and 1.2.0-pre3

**Environment Type:** Kubernetes

**Steps to Reproduce:**

Spin up a kubernetes service with type LoadBalancer.

Example yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: apigateway
  type: LoadBalancer
```

**Results:** 

In kubernetes-load-balancers, a "K8s Service" is created. The service can only be accessed at it's randomly assigned nodePort

**Expected:**

Prior to upgrading to v1.2.0-pre2, when we created a service of this type, a "Load Balancer" was created in kubernetes-load-balancers and it opened the port 443 using tcp as it's protocol. We could also increase the Scale which is not possible with the current "K8s Service".
