### ISSUE TITLE
Access a container's web UI

### ISSUE THREAD

**Issue by AmitKumarDas** [rancher/rancher#6064]
*Not able to access the Concourse CI 's web portal which has been installed in Rancher*

Not sure which IP address to follow ?
I want to access the Concourse CI's web from my laptop which can communicate the Rancher box.
In other words I am able to access the Rancher Web UI from my laptop.

**Steps followed:**
- Go through the concourse install steps w.r.t 
 - docker-compose and 
 - key generation w.r.t concourse web & concourse worker
 - refer [link](https://concourse.ci/docker-repository.html)

- Open Rancher (this is installed on Ubuntu trusty) web ui
- Add stack & import docker-compose.yml file for concourse ci
 - NOTE - Provide full path of the concourse keys
 - NOTE - If Rancher is running on a separate machine, 
  - generate the keys inside Rancher machine & 
  - provide the path relative to Rancher box.

**Details of the image, & various commands run after creating Concourse CI container**

```shell
echo $CONCOURSE_EXTERNAL_URL
http://20.10.112.151:8181
```

- cat docker-compose.yml
```yml
concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database

concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  ports: ["8181:8181"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: admin
    CONCOURSE_BASIC_AUTH_PASSWORD: test
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web
```

```shell
docker-compose ps
            Name                          Command               State    Ports
------------------------------------------------------------------------------
concourse_concourse-db_1       /docker-entrypoint.sh postgres   Exit 0
concourse_concourse-web_1      /usr/local/bin/dumb-init / ...   Exit 0
concourse_concourse-worker_1   /usr/local/bin/dumb-init / ...   Exit 0
```

```shell
iptables -L -n --line-numbers -t nat

Chain CATTLE_PREROUTING (1 references)
num  target     prot opt source               destination
1    MARK       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:8181 MARK set 0x668a0
2    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL tcp dpt:8181 to:10.42.227.22:8181

# The user-defined container in which the user mapped host port 8181 to container port 8181. 
# The ip 10.42.227.22 is the IP the Rancher assigned to the container. 
```

```shell
lsof -i tcp:8181
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 18533 root    4u  IPv6  56755      0t0  TCP *:8181 (LISTEN)
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`container.labels`|

**Comment by aemneina** [comment]
@AmitKumarDas is port 8181 accessible on the host your concourse web container resides on? Are there firewalls/security groups in the way? Can you curl localhost:8181, while on the host and get a result?

**Comment by AmitKumarDas** [comment]
I have been trying a few options in between. 
I tried to check if the web app container was listening to 8181.
I could find that the web app container was registering 8080 as its tcp listener.

I did 2 things to access the web ui from my laptop:

- NATed a IP (which I can access from my laptop's network) to rancher host's network interface i.e. eth0
- I modified my compose file, thinking that the web app was unable to use 8181 as its tcp listener.

Below is the modified snippet of my compose file (*the ports value was changed*)

```yml
concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  network_mode: "host"
  ports: ["20.10.113.2:8181:8180"]
  volumes: ["/home/concourse/keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: admin
    CONCOURSE_BASIC_AUTH_PASSWORD: test
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable
```

However, I used docker daemon just to negate the variable factors.
I guess Rancher will work out seamlessly.

I have posted the details in the following link:
https://github.com/AmitKumarDas/amitkumardas.github.io/blob/master/_posts/2016-09-28-connect-a-docker-container-from-a-local-network-part-1.md
