### ISSUE TITLE
Allow rancher-compose variables in Load Balancer

### ISSUE THREAD

**Issue by dalareo** [rancher/rancher#6075]
It is not possible to set rancher-compose variables in Load Balancer. I am creating a load balancer template for my custom catalog and I would like to let users customize it from the UI with rancher-compose variables. Example:

```
  lb:
  ports:
  - 80:80
  image: rancher/load-balancer-service
  external_links:
     - {$stack_5}/{$service_5}:{$service_5}
  labels:
  # Put load balancer containers only on hosts without label availability=temporal
     io.rancher.scheduler.affinity:host_label_ne: availability=temporal
  # Requests to http://app.example.com/foo:80 should be routed to web1 over port 8000
     io.rancher.loadbalancer.target.{$stack_5}/{$service_5}: {$subdomain_5}.educaas.io:80={$port_5}
```

**Rancher Version:** 
1.14

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu with DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:** 

**Expected:**
