### ISSUE TITLE
Metabase container not working on Rancher

### ISSUE THREAD

**Issue by cgarciae** [rancher/rancher#6082]
**Rancher Version:**
1.1.3
**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Linode

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a stack based on this `docker-compose.yml`

```
metabase:
  image: metabase/metabase:v0.19.3
  ports:
    - "3000:3000"
  links:
  - postgres
postgres:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_PASSWORD: asdfghjkl
    POSTGRES_USER: someuser
  image: postgres:9.5
  volumes:
  - metabase:/var/lib/postgresql/data/pgdata
```

and go to `http://RANCHER_IP:3000` on your browser.

**Results:** 
Can't connect to the server.

**Expected:**
If you instead of running the stack with Rancher, you locally start the containers using 

```
docker-compose up -d
```

and go to `http://localhost:3000` on your browser, you will see metabase welcome page.

**Notes**
It takes about a minute for the metabase container to configure itself before it starts serving on port 3000.
