### ISSUE TITLE
docker-compose "command" section doesn't work for multi commands

### ISSUE THREAD

**Issue by maZahaca** [rancher/rancher#6096]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12.1

**OS and where are the hosts located?:** Ubuntu 14.04, DigitalOcean

**Setup Details:** One node - rancher, another node - services

**Environment Type:** Cattle

**Steps to Reproduce:**
1. Run docker-compose.yml from CLI

``` yml
test:
  image: php
  restart: always
  command: "echo '1' && tail -f /dev/null"
```

**Results:** 
Created container executes only first command and fails.
If you do `docker inspect` you'll see the reason of that.
&& - escaped

``` json
{
        "Path": "echo",
        "Args": [
            "1",
            "\u0026\u0026",
            "tail",
            "-f",
            "/dev/null"
        ],
}
```

**Expected:**
Script executes as expected and as it does in local docker-compose
