### ISSUE TITLE
Host not showing up in storage page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6097]
**Rancher Version:** master with perf build for UI

**Steps to Reproduce:**
1.  Setup storage using convoy-nfs
2.  Create a service using convoy-nfs
3.  Go to storage page and refresh it

**Results:** Notice that the Volumes information is showing up, but the Hosts section is completely blanks.
![image](https://cloud.githubusercontent.com/assets/11514927/19009418/9862fc66-8728-11e6-8654-08ba5cdaec18.png)

**Expected:** Should show hosts

**Comment by deniseschannon** [comment]
Verified with v1.2.0-pre4-rc9. 

Started Rancher-NFS. 
Created a service using rancher-nfs. 
```
version: '2'
services:
  foo:
    image: busybox
    volumes:
    - bar:/var/lib/storage
volumes:
  bar:
    driver: rancher-nfs
```
Go to storage page. Hosts shown. 
<img width="385" alt="screen shot 2016-11-19 at 7 24 45 am" src="https://cloud.githubusercontent.com/assets/11410997/20456304/4d22a666-ae29-11e6-9d4f-e409ad511931.png">
