### ISSUE TITLE
Not able to create service with external volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6141]
Rancher Server version - Build from master

Rancher server - Latest build from master
rancher-compose version v0.11.0-rc1

Steps to reproduce the problem:
Have convoy-nfs volume driver set up for the environment.
Create a volume - test1 (from UI)  so that it is in "requested" state.

Use the following yml to create a service with this volume test1 mounted as "/data1".

rancher compose complains that volume could not be found.

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ cat test-env.yml
version: '2'
services:
  nginx5:
    image: nginx
    volumes:
    - test1:/data1

volumes:
  test1:
    external: true
Sangeethas-MacBook-

Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ ./rancher-compose -p newext  -f test-env.yml up
INFO[0000] Creating stack newext                        
INFO[0000] [0/1] [nginx5]: Creating                     
INFO[0000] Creating service nginx5                      
INFO[0001] [0/1] [nginx5]: Created                      
FATA[0001] Volume test1 declared as external, but could not be found. Please create the volume manually and try again. 
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ 
```

**Comment by sangeethah** [comment]
This issue is still reproducible when testing with rancher-compose-v0.11.0-rc4.

**Comment by sangeethah** [comment]
Tested with latest build from master.
Able to create service with external volumes successfully

**Comment by giovannicandido** [comment]
I'm having this same problem.

When using docker-compose.yml rancher rise the message:

>  Error (Volume postgres-atlassian declared as external, but could not be found. Please create the volume manually and try again.)

But the volume is created manually.

To workaround, I manually create a container in the rancher interface mapping the volume, it doesn't matter what image or volume path, then deleted the service and when creating the stack again with docker compose it works.

**Comment by giovannicandido** [comment]
Rancher v1.2.2

**Comment by deniseschannon** [comment]
@giovannicandido How is your volume created manually? Can you share your docker-compose.yml? 

What you are describing is expected behavior if you are trying to use an environment scoped volume.

**Comment by giovannicandido** [comment]
hi @deniseschannon the actual docker compose is a little complex and I give up after a week trying to reproduce the env in rancher and other schedules. Also tried https://kontena.io with no luck. 
Current I'm using docker-compose alone in production, until I can reproduce the env in any scheduler.
With that said, I can share with you the compose file.
I will let two files: the complex one and a simplified version, so you get more quick to the point.

```
version: '2'
services:
  postgresql-atlassian:
    image: postgres:9.4-alpine
    volumes:
      - postgres-atlassian:/var/lib/postgresql/data
    networks:
      - default
      - service-proxy
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=bla
      - POSTGRES_USER=postgres
    labels:
      description: "Postgresql Database"
      service: "postgresql"
  jira:
    image: atende/jira
    ports:
    - "8080:8080"
    - "8081:8081"
    volumes:
      - jira-home:/opt/jira-home
    environment:
      - VIRTUAL_HOST=projects.domain.local
      - VIRTUAL_PORT=8080
      - CATALINA_OPTS= -Xms256m -Xmx1g
      - PROXY_SCHEME=https
      - PROXY_PORT=443
      - PROXY_SECURED=true
      - LETSENCRYPT_HOST=projects.domain.local
      - LETSENCRYPT_EMAIL=infraestrutura@domain.local
      - CROWD_URL=https://auth.domain.local
      - CROWD_APPLICATION_NAME=jira
      - CROWD_PASSWORD=bla
    labels:
      description: "Atlassian Jira"
      service: "jira"
    links:
      - postgresql-atlassian:db
    networks:
      - default
      - service-proxy
  crowd:
    image: atende/crowd:2.8.0
    volumes:
      - crowd-home:/opt/crowd-home
    ports:
      - "8095:8095"
    links:
      - postgresql-atlassian:db
    environment:
      - VIRTUAL_HOST=auth.domain.local
      - LETSENCRYPT_HOST=auth.domain.local
      - PROXY_SCHEME=https
      - PROXY_PORT=443
      - PROXY_SECURED=true
    networks:
      - default
      - service-proxy
    labels:
      description: "Atlassian Crowd"
      service: "crowd"
  confluence:
    image: atende/confluence
    links:
      - postgresql-atlassian:db
    ports:
      - "8091:8091"
      - "8090:8090"
    volumes:
      - confluence-home:/opt/confluence-home
    environment:
      - VIRTUAL_HOST=wiki.domain.local
      - VIRTUAL_PORT=8090
      - SECONDARY_NO_SSL_PORT=8091
      - PROXY_SCHEME=https
      - PROXY_PORT=443
      - PROXY_SECURED=true
      - LETSENCRYPT_HOST=wiki.domain.local
      - LETSENCRYPT_EMAIL=infraestrutura@domain.local
      - CROWD_URL=https://auth.domain.local
      - CROWD_APPLICATION_NAME=confluence
      - CROWD_PASSWORD=bla
    networks:
      - default
      - service-proxy
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/opt/volumes/proxy/certs:/etc/nginx/certs:ro,Z"
    networks:
      - default
      - service-proxy
    labels:
      io.rancher.sidekicks: nginx-gen, letsencrypt-nginx-proxy-companion
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:Z"
      - "/opt/volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,Z"
    volumes_from:
      - nginx
    networks:
      - default
      - service-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:Z"
      - "/opt/volumes/proxy/certs:/etc/nginx/certs:rw,Z"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - LETSENCRYPT_TEST=true
    networks:
      - default
      - service-proxy
networks:
  service-proxy:
    external: true

volumes:
  jira-home:
    external: true
  confluence-home:
    external: true
  crowd-home:
    external: true
  postgres-atlassian:
    external: true
```

Note, the **networks** section is a workaround the bug https://github.com/jwilder/nginx-proxy/issues/622

```
version: '2'
services:
  postgresql-atlassian:
    image: alpine
    volumes:
      - external-volume:/bla
    labels:
      description: "Alpine"
      service: "alpine"

volumes:
  external-volume:
    external: true
```

To create the volumes, I use convoy, not sure if the problem is exclusive to that volume-driver:

```
convoy create external-volume
convoy create jira-home
convoy create confluence-home
convoy create crowd-home
convoy create postgres-atlassian
```

Steps to reproduce: 
1 - Create the external volumes
2 - Create the env with docker-compose.yml
3 - Error will occour
4 - Create a service in rancher ui with the volumes
5 - Delete and recreate the env with docker-compose.yml

**Comment by ebreton** [comment]
Hello, 

rancher-compose version:  v0.12.2-rc1
docker-compose version: 1.9.0, build 2585387

I have a similar issue:
```
$ rancher-compose up
FATA[0000] Volume dbdata declared as external, but could not be found. Please create the volume manually and try again. 
```
The message remains the same although I do create the volume manually:
```
$ docker volume create --name dbdata
$ docker volume ls
DRIVER              VOLUME NAME
...
local               dbdata
...
$ rancher-compose up
FATA[0000] Volume dbdata declared as external, but could not be found. Please create the volume manually and try again. 
```

my docker-compose.yml is as follow:
```
version: '2'

volumes:
  dbdata:
    external:
      name: dbdata

services:
  db-shared:
    image: mariadb
    restart: always
    container_name: db-shared
    env_file:
      - ./etc/db.env
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db-shared:db
    env_file:
      - ./etc/db.env
```

Any idea? :)
