### ISSUE TITLE
Error out when per_container: true and external: true is specified for a volume.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6146]
Rancher Version: Build form master
Rancher compose Version: rancher-compose-v0.11.0-rc1

Steps to reproduce the problem:
Create a service with volume at container level using the following yml:

```
version: '2'
services:
  nginxnew:
    image: nginx
    volumes:
    - conw:/tmp

volumes:
  conw:
    driver: convoy-nfs
    per_container: true
    external: true
```

In this case , external-true takes precedence.

Instead of this , we should provide user an error message stating that both per_container and external cannot be set to true.
