### ISSUE TITLE
Not able to deploy "Rancher NFS" catalog

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6158]
Rancher Version: v1.2.0-pre4-rc1

Steps to reproduce the problem:
Try to deploy "Rancher NFS" catalog from "Infrastructure Stacks".

docker-compose.yml has references to AWS keys instead of NFS configurations.

```
nfs-driver:
  privileged: true
  image: rancher/storage-nfs:v0.0.1
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  metadata:
    storage_driver:
      name: rancher-nfs
      scope: environment
      volumeAccessMode: multiHostR
```
