### ISSUE TITLE
Load balancer do not remove links, leaving description broken

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#6168]
**Rancher Version:**
1.2.0-pre4-rc1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1) add couple of services/containers for using behind LBA
2) add load balancer
3) add two targets for LBA created in pt. 1
4) remove one of containers behind LBA

**Results:** 
You will see container with name "/" in description

**Expected:**
Entry should be completely gone

I tried adding new services, removing existing, etc - no luck.
The entry is actually gone from haproxy.cfg and LBA settings, but still exists somewhere in (?) cattle/rancher

**Comment by alena1108** [comment]
@rlex Could you please share exported config of your problematic stack? taken at step3 and step4. Also can you elaborate on "You will see container with name "/" in description". In the UI description? on the API? screen shot would be helpful

**Comment by rlex** [comment]
Sorry, forgot to attach screenshot. Looks like this (from my prev ticket): 
https://cloud.githubusercontent.com/assets/84462/19152945/13b63f3c-8bdd-11e6-83ef-ca7d0b3bfafd.png

As for example, i'll post it a bit later.

**Comment by rlex** [comment]
```
version: '2'
services:
  playground-balancer:
    ports:
    - 443:443
    - 80:80
    external_links:
    - huginn/huginn:huginn
    labels:
      io.rancher.loadbalancer.ssl.ports: '443'
      io.rancher.loadbalancer.target.huginn/huginn: huginn.pg.example.tld=3000
    tty: true
    image: rancher/load-balancer-service
    stdin_open: true
```

```
version: '2'
services:
  playground-balancer:
    scale: 2
    load_balancer_config:
      haproxy_config: {}
    default_cert: SSG *.pg.example.tld
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```
