### ISSUE TITLE
Recreate from health check does not re-create links

### ISSUE THREAD

**Issue by guyspronck** [rancher/rancher#6169]
**Rancher Version:**
v1.1.4

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Three hosts on three different physical servers with internal DB. (No HA setup yet)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Setup a stack with two or more linked containers. For example: database which is linked in a website.
2. Setup health checks for both services. Make sure Recreate is selected. (TCP)
3. When the containers are running on different hosts, kill the host on which the database is running.
4. Health check should automatically recreate the database.
5. The link between the website and database is not recreating, leaving the website without a database whilst it is actually recovered.

**Results:** 
Have a recreated database which is not linked to the website container, causing the website container to not have a database connection anymore.

**Expected:**
The link should be recovered after recreation.

**Comment by aemneina** [comment]
hey @guyspronck can you share your docker/rancher-compose file for this?

**Comment by guyspronck** [comment]
@aemneina Sure, I was using a Rocket.Chat stack to test this, here is my config.

docker-compose.yml
```yaml
mongo:
  image: mongo
  volume_driver: volume1
  volumes:
     - volume1:/data/db
     - volume1:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=https://rocket.chat.lan/
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=password
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-giphy,hubot-http-status
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
```

rancher-compose.yml
```yaml
.catalog:
  name: RocketChat # Name of the versioned template of the Catalog Entry
  version: v3 # Version of the versioned template of the Catalog Entry
  description: "Slack-like clone but free." # Description of the versioned template of the Catalog Entry
  uuid: rocket.chat-3 # Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: v0.51.0 # The minimum version of Rancher that supports the template
  questions: #Used to request user input for configuration options

rocketchat:
  scale: 1
  health_check:
    # Which port to perform the check against 
    port: 3000
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000

mongo:
  scale: 1
  health_check:
    # Which port to perform the check against 
    port: 27017
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000

hubot:
  scale: 1
  health_check:
    # Which port to perform the check against 
    port: 8080
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000
```
