### ISSUE TITLE
Add cloudProvider as an option (enum) to the k8s template

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6172]
Today we default cloud provider to Rancher for our k8s template. But as might need to register a provider as an original one - AWS, GCE - in order to exercise certain features like PVs, ELG, so we'd have to enable it as an option. It should be enum (list of all providers supported by k8s, Rancher as a default one)

**Comment by galal-hussein** [comment]
AWS provider works correctly, I was able to test Persistent volumes and ELB features:

- PV

First i created storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
```
Then i created a persistent volume claim to use this storage class to **Dynamically** create persistent volumes and bound it to the claim:
```
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "annotations": {
      "volume.beta.kubernetes.io/storage-class": "slow"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "3Gi"
      }
    }
  }
}
```

And as expected a PV created on AWS dynamically and got bounded to the claim:
```
$ kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
claim1    Bound     pvc-60836d27-9fa4-11e6-a412-020aa43d8984   3Gi        RWO           12s
$ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM            REASON    AGE
pvc-60836d27-9fa4-11e6-a412-020aa43d8984   3Gi        RWO           Delete          Bound     default/claim1             20s
```
Finally i created a pod to mount this pv:
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    name: frontendhttp
spec:
  containers:
    - name: myfrontend
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
       claimName: claim1
```
To make sure that the pv is mounted inside the pod:
```
$ kubectl exec -it mypod /bin/bash
root@mypod:/# lsblk                                                                                                                                                                          
NAME    MAJ:MIN   RM SIZE RO TYPE MOUNTPOINT
xvda    202:0      0   8G  0 disk 
`-xvda1 202:1      0   8G  0 part /etc/hosts
xvdba   202:13312  0   3G  0 disk /usr/share/nginx/html
```

- ELB

On the same setup i created a service with type: Loadbalancer
```
{
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "example-elb"
      },
      "spec": {
        "ports": [{
          "port": 80,
          "targetPort": 80
        }],
        "selector": {
          "name": "frontendhttp"
        },
        "type": "LoadBalancer"
      }
}
```
A load balancer automatically created on AWS with the two hosts registered:

![aws-elb](https://cloud.githubusercontent.com/assets/3309968/19869982/36b1edcc-9fb7-11e6-8460-2b2b81db84db.png)
