### ISSUE TITLE
[rancher-compose] Error to parse docker-compose v2 format

### ISSUE THREAD

**Issue by baptistedonaux** [rancher/rancher#6188]
**Rancher Version:** v1.2.0-pre4-rc1

**Rancher-compose Version:** v0.11.0-rc2

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Debian 8 into VM

**Setup Details:** external DB

**Environment Type:** Cattle

**Steps to Reproduce:**

```yaml
version: "2"

services:
  …
```

```bash
$ rancher-compose up
```

**Results:** 
```bash
FATA[0000] Failed to read project: yaml: unmarshal errors:
  line 1: cannot unmarshal !!int `2` into map[string]interface {}
```

**Expected:**

Docker compose format V2 supported.

**Comment by joshwget** [comment]
I'm unable to reproduce this with v0.11.0-rc2 and this simple Docker Compose file.

```
version: "2"
services:
  test:
    image: busybox
    command: "sleep 1000"
```

Can you post your full Docker Compose file?
