### ISSUE TITLE
automated LetsEncrypt, kubernetes and ingress controllers seem to conflict with Rancher's ingress loadbalancer

### ISSUE THREAD

**Issue by T-Grave** [rancher/rancher#6208]
**Rancher Version:**
1.1.3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Node 1: seperate single node rancher with internal DB
Node 2: Host added to rancher to schedule containers
Node 3: Host added to rancher to schedule containers
Node 4: Host added to rancher to schedule containers

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Setup the nginx-ingress-controller within the cluster and add an ingress resource.

**Results:** 
The service I'm routing to with ingress **is actually externally available** (so that's good).

But, it looks like the HA lb of rancher is in some sort of conflict with the nginx-ingress-controller I've setup. When I go to ```Kubernetes -> System``` I can see the ingress rule being added, but it keeps saying "activating" and is creating containers that have the label Error in front of them.

When I go to the detailed view it says this in the upper right corner: ``` Activating (Failed to allocate instance [1607]: Object [instance:1607] failed to satisfy predicate [15000] millis)```

**My goal**
What I am trying to achieve in general, is having a NodeJS powered webservice running in Kubernetes using Rancher, available to the outside world, with LetsEncrypt certificates that renew themselves automatically.

I'm somewhat new to K8s and rancher so maybe there is a better solution for this without using the nginx ingress controller and purely relying on the rancher ingress loadbalancer, but the kube-lego page states it only supports the GCE ingress controller and nginx ingress controller, so I went with nginx naturally.

Currently I'm trying to get this to work using:
- [nginx-ingress-controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx)
- [kube-lego](https://github.com/jetstack/kube-lego)
- a nodejs server running my app
- an ingress resource to link everything up
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: storefront
  namespace: bazaar
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - storefront.moonkin.space
    secretName: storefront-tls
  rules:
  - host: storefront.moonkin.space
    http:
      paths:
      - path: /
        backend:
          serviceName: storefront
          servicePort: 80
```

**Comment by alena1108** [comment]
@T-Grave by default, k8s provides 2 entry points for the ingress: port 80 and port 443. Those are the ports that are being published to the host. If there is any other service listening on this very same port, the port config error will prevent ingress LB from launching. So looks like something else is listening on port 80 when your ingress gets created. So you have 2 ways of solving it:

1) Override http port in ingress via annotations:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scaledlb
  annotations:
    http.port: "99"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```
2) if you still want your ingress to use port 80 for access, add more hosts to your environment

Note that storefront service behind ingress doesn't have to be of a NodePort type; it can be simple ClusterIp . Rancher Ingress balances traffic between pods that are behind "storefront"

Let me know if it helps
