### ISSUE TITLE
Failed to unmarshall: Invalid integer. mem_limit breaks custom catalog upgrade when set on a sidekick.

### ISSUE THREAD

**Issue by jdel** [rancher/rancher#6241]
**Rancher Version:**
v1.1.2, cattle v0.165.8, rancher-compose v0.8.6

**Docker Version:**
v1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Virtual vCloud machines running ROS 0.4.5

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Make a custom catalog entry that has some containers and a sidekick, set mem_limit to at least 157286400 on both.
2. Deploy that stack
3. Make a new version of the catalog template, refresh catalog and upgrade from orange button in the Rancher UI.

**Results:** 
The stack is stuck in Upgrading, upgrade will never complete, and ultimately I will never have a chance to "Finish Upgrade".

**Expected:**
Upgrade successful

---

To give a bit of context, in my case the issue arose on my ELK stack.
While stuck, the stack displays the message "logstash-indexer does not have a sidekick named logstash-indexer-config"

Digging a bit deeper in the cattle logs I found this:

```
time="2016-10-11T12:59:20Z" level=error msg="Failed to unmarshall: Invalid integer: '1.572864e+08' at line 10, column 8
dataVolumes:
- /data/logstash-config:/etc/logstash

imageUuid: docker:rancher/logstash-config:v0.2.0
kind: container
labels:
  io.rancher.container.hostname_override: container_name
  io.rancher.container.pull_image: always
  io.rancher.scheduler.affinity:host_label: hostLogs=yes
  io.rancher.service.hash: 9316e3b8a55f2f9b5126543632d8e054c8d69afc
logConfig: {}
memory: 1.572864e+08
name: logstash-indexer-config
networkMode: managed
privileged: false
publishAllPorts: false
readOnly: false
startOnCreate: true
stdinOpen: false
tty: false
vcpu: 1
```

The mem_limit value are converted into scientific notation for some reason I ignore, making it impossible to spawn the container.
Out of the 6 mem_limited containers in the stack, only this one has the issue.

In order to be able to upgrade my stack, I had to go cancel the stuck upgrade, then upgrade the sidekick container, remove the mem_limit, and then upgrade the stack again. This time I was able to "Finish Upgrade".

This workaround fixed the problem on both my staging and production environments that were experiencing the issue.
