### ISSUE TITLE
Routing to the same service twice from different domains / same paths breaks Ingress loadbalancer 

### ISSUE THREAD

**Issue by T-Grave** [rancher/rancher#6244]
**Rancher Version:**
1.1.4
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 - cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
4 nodes, 1 dedicated rancher node, 3 host nodes for kubernetes
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Problem**

In my previous issue (#6208) I describe how I wasn't able to setup automated LetsEncrypt certificates for my kubernetes cloud.

As I need this in production asap, I'm trying a different approach where I'm using Rancher's built-in Ingress support (instead of the Nginx Controller I stated in the other issue). I'm running one LetsEncrypt renewal container(just a simple nginx back-end with the LetsEncrypt certbot in it and some bash scripts to automate the process) in a kubernetes namespace together with two web services I'm trying to expose.

I can expose a single webservice and have it renew it's certificate using the following Ingress resource:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb
  namespace: staging
spec:
  rules:
  - host: svc1.example.com
    http:
      paths:
      - backend:
          serviceName: svc1
          servicePort: 80
      - path: /.well-known/acme-challenge/
        backend:
          serviceName: letsencrypt
          servicePort: 80
```

Now, I have a second web service (the admin panel for the other service) that should be routed using the **same Ingress resource**.

This is where I hit a wall. When I update the Ingress resource to expose the second service and setup routing to that same LetsEncrypt service for the second domain and I try to apply/create it using kubectl, it creates the LoadBalancer container, but the links/targets are broken. (Rancher UI shows up empty where it should show the targets). Also, when I browse to [lb-IP]:80 it gives a connection error instead of a 503 or something. (so the port is not even actually opened on the lb node)

This is what the "broken" Ingress resource looks like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb
  namespace: staging
spec:
  rules:
  - host: svc1.example.com
    http:
      paths:
      - backend:
          serviceName: svc1
          servicePort: 80
      - path: /.well-known/acme-challenge/
        backend:
          serviceName: letsencrypt
          servicePort: 80
  - host: svc2.example.com
    http:
      paths:
      - backend:
          serviceName: svc2
          servicePort: 80
      - path: /.well-known/acme-challenge/
        backend:
          serviceName: letsencrypt
          servicePort: 80
```

When I remove the second LetsEncrypt back-end path, the Ingress starts working again and the links are fine, but of course, my LetsEncrypt renewal process won't work for the second domain.

**I'm not sure if this is a bug or expected behavior (if it is expected, I don't see why) but it seems like referring to the same service more than once for two different domains breaks the Ingress Resource (without properly notifying the user of it).**

If there is a way to define the path defined service only once and make it work for all domains, that would be even better, as my current tried approach requires a lot of duplicate definitions on the path level.

Notes:

- I could use two Ingress resources, but I'd rather not since it would use two IP addresses, one for each service and I'll be hosting a lot more services once I get the renewal process up and running.

- Another workaround would be to create a second LetsEncrypt service and point it to the same pod and create such a service for every domain I define in my Ingress resource.

**Comment by T-Grave** [comment]
While playing around with different configurations I noticed the following:

kube-lego (the cert renewal container I used in #6208) is not aware it's running in a Rancher environment (neither do they support Rancher), yet somehow when it creates the k8s certificate secret, **Rancher picks it up and adds it very neatly to it's Certificates store, making them available throughout rancher loadbalancers etc**. As I can not use kube-lego because of #6208 I am using a different container that doesn't rely on the Nginx Ingress Controller. I was wondering if anyone knows how to achieve the same effect when adding k8s secrets. When I add them from the custom container, they appear as valid k8s secrets, but not as Rancher Certificates in the UI, which results in rendering them useless within Rancher's environment of loadblancers and ingress.

For now I will try and add them using Rancher's API, but it would be easier to use k8s for such tasks, as you can add secrets to k8s without the need to supply the container with API keys/secrets and a rancher URL.

**Comment by alena1108** [comment]
@T-Grave 

> Also, I was wondering, if I update a certificate using the Rancher API, will it propagate to the loadbalancers?

Yes, it will get updated for the all the lbs using this certificate. Also there are 2 ways of uploading certs that is supported for Rancher ingress: you can either specify it via secrets, and they will be uploaded to rancher/lb, or you can create them via Rancher, and reference it by name from your ingress resource.

Regarding the first configuration, I'll try to reproduce it using your config, and will update the bug with the findings.

**Comment by T-Grave** [comment]
Oh, in that case I'll try adding them as secrets agian, but this did not upload them to rancher. Is there a certain specification they should follow to be working? And when is the upload triggered, when applying these secrets to the Ingress, or when the secrets are created?

Might be a good idea to update the documentation to reflect this information, currently it says you should create a Rancher certificate in order to use Ingress TLS.

Thanks for your quick response btw!

**Comment by alena1108** [comment]
@T-Grave 
> Oh, in that case I'll try adding them as secrets again, but this did not upload them to rancher previously.

Have you updated the corresponding? or removed/recreated? I believe removing/recreating should work. Need to double check on update.

As an alternative solution, you can just upload certificates to Rancher, omitting the k8s secrets. In Rancher UI, chose Infrastructure-> certificates, and upload your cert with the name = the name you gonna reference it by in your ingress.

You can find some instructions on how to test TLS with ingress by following this link: https://github.com/rancher/rancher/issues/4892

@deniseschannon do we have a documentation on how certificates part of Ingress is being done by Rancher? If not, we should add some.

**Comment by T-Grave** [comment]
@alena1108 

After fixing a bug in my container (it was adding empty secrets) I was able to use them as secrets in my Ingress resource. **The certificate upload to rancher happened as soon as I applied the Ingress configuration** (that should save you on the double checking)

**Comment by alena1108** [comment]
@T-Grave original bug is good one: same service referenced by 2 host names should be supported. I'm going to work on a fix for ingress service

**Comment by alena1108** [comment]
@soumyalj the image with the fix was merged to rancher-catalog (same folder, 12). We should also include this test case to our automation run.

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc4 with https://github.com/rancher/infra-catalog (qa branch), Kubernetes 1.4. The ingress described above is functional and targets are reached successfully. Here is an example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingresslb
spec:
  rules:
  - host: svc1.example.com
    http:
      paths:
      - backend:
          serviceName: k8test1
          servicePort: 81
      - path: /name.html
        backend:
          serviceName: k8test3
          servicePort: 80
  - host: svc2.example.com
    http:
      paths:
      - backend:
          serviceName: k8test2
          servicePort: 81
      - path: /name.html
        backend:
          serviceName: k8test3
          servicePort: 80                                         
```
