### ISSUE TITLE
private/public network connection issue 

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#6274]
**Rancher Version:**
V1.1.4
**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher / internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Our haproxy load-balances cannot contact nodes on the private network

We have a bare metal cluster with several head nodes attached to the internet and a private network and many worker nodes living only on the private  10.0.X.X network. 

I have configured our rancher load balancers to deploy only to internet nodes by using  host labels (in the case   with io.rancher.scheduler.affinity:host_label: visible=internet)

Our applications are placed only on internal worker nodes (10.0.X.X) and are assigned
by rancher another internet address such as 10.42.X.X   I can see the internal address in rancher UI

**Results:** 

Opening a console on the load-balancer I can ping the node on 10.0.X.X address but cannot on 10.42.X.X.

/# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.17.0.1      0.0.0.0         UG    0      0        0 eth0
10.42.0.0       *               255.255.0.0     U     0      0        0 eth0
169.254.169.250 *               255.255.255.255 UH    0      0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 eth0

root@cf47e1753ddd:/# ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=63 time=0.307 ms
64 bytes from 10.0.0.1: icmp_seq=2 ttl=63 time=0.192 ms
^C
--- 10.0.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.192/0.249/0.307/0.059 ms
root@cf47e1753ddd:/# ping 10.42.39.66
PING 10.42.39.66 (10.42.39.66) 56(84) bytes of data.
^C
--- 10.42.39.66 ping statistics ---
775 packets transmitted, 0 received, 100% packet loss, time 773999ms

load-balancer cannot communicate with nodes on internal 10.0.X.X. network.

**Expected:**

**Comment by kkvilekval** [comment]
Another piece of the puzzle.

. on the internet facing machines the, in the load-balancer the /etc/resolv.conf appears to be taken verbatim from host

:/# cat /etc/resolv.conf
domain ece.ucsb.edu
search ece.ucsb.edu
nameserver 128.111.56.36
nameserver 128.111.56.123
nameserver 128.111.1.2



While on the worker hosts:

~# cat /etc/resolv.conf
search ece.ucsb.edu testing.rancher.internal websvc.testing.rancher.internal ran
cher.internal
nameserver 169.254.169.250

**Comment by kkvilekval** [comment]
I did get this working and  want to close this issue with a comment for future reference:

1.   Ensure that all rancher worker  are initializing with the private  IP address even those nodes that may have Public IPs.   
2.  initialze with CATTLE_AGENT_IP= Private IP of worker 
3.  You will still be able to connect to ports available on nodes with a public IP address unless you have a firewall somewhere.

4.   I use ansible to reboot rancher on  nodes and needed to add the following while starting rancher-agent.

 ```
docker: 
        docker_api_version: 1.21
        image: "rancher/agent:v1.0.2"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/rancher:/var/lib/rancher
        privileged: true
        env:
          CATTLE_AGENT_IP: "{{ansible_all_ipv4_addresses | ipaddr('10.0.0.0/16') | first}}"
        command:  <The connection string from your rancher UI> 
        detach: true
        state: running
```
