### ISSUE TITLE
Exporting yaml for stacks uses v1 format for "logging" key

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6277]
**Rancher Version:**Master

**Docker Version:**1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack "Stack1" using the below yaml file:

```
version: '2'
services:
  test:
    image: busybox
    command: "sleep 1000"
    logging:
      driver: syslog
```

Stack1 is created with service 'test'. 
2. Export the yaml file for the stack created above. The docker-compose created for export still has log_driver(which is v1 format)

```
version: '2'
services:
  test:
    log_driver: syslog
    command:
    - sleep
    - '1000'
    image: busybox:latest


```

**Comment by deniseschannon** [comment]
Note: when there is no log driver/log options chosen, it's still exporting something. 

```
  web:
    tty: true
    image: nginx:latest
    logging: {}
    stdin_open: true
```

@soumyalj Can you test when there are log drivers and log opts for correct exporting before re-opening and assigning to @alena1108 for the issue of printing out when nothing is set.

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc5. The yml was generated correctly for the "logging key" after exporting as below:
```
version: '2'
services:
  test:
    command:
    - sleep
    - '1000'
    image: busybox:latest
    logging:
      driver: syslog
```
@deniseschannon : Did not see the issue you mentioned
@prachidamle : The logs did not have the errors mentioned above

**Comment by deniseschannon** [comment]
In rc6, I am still seeing the issue. No log driver is set and this is what is in the exported yml. 

```
version: '2'
services:
  test:
    tty: true
    image: ubuntu:14.04.3
    logging: {}
    stdin_open: true
```

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. The service created through UI or through docker-compose (with no logging key set) generated the exported yml correctly.
```
version: '2'
services:
  defaultservice1:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: ubuntu:14.04.3
    stdin_open: true
```
