### ISSUE TITLE
[rancher-dns] environment names with space cause dns update requests to fail 

### ISSUE THREAD

**Issue by dutronlabs** [rancher/rancher#6304]
**Rancher Version:**
- 1.1.4 

**Docker Version:**
- 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
- centOS 7, virtualized (ESXi), hosts are on-premise

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- 6 node rancher, internal DB 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
 - Cattle only

**Steps to Reproduce:**
docker-compose.yml for dnsupdate-rfc2136
```
rfc2136dns:
  environment:
    RFC2136_HOST: 192.168.20.232
    RFC2136_PORT: '53'
    RFC2136_TSIG_KEYNAME: ielab.local.
    RFC2136_TSIG_SECRET: **redacted**
    ROOT_DOMAIN: ielab.local
    TTL: '299'
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: external-dns
  command:
  - -provider
  - rfc2136
  image: rancher/external-dns:v0.5.0
```

rancher-compose.yml for dnsupdate-rfc2136
```
rfc2136dns:
  scale: 1
  health_check:
    port: 1000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
```

For purposes of testing, I used ```IE Lab``` as my environment name. 

rancher-dns service appeared to be up OK, so I went to the catalog in Rancher and provision a load balancer to my jenkins-ci stack to test the update. Example is shown below.

**Results:** 
```
10/17/2016 4:52:00 PMtime="2016-10-17T20:52:00Z" level=info msg="Adding dns record: {jenkinslb.jenkins.ie lab.ielab.local. [192.168.10.244] A 299}"
10/17/2016 4:52:00 PMtime="2016-10-17T20:52:00Z" level=error msg="Failed to add DNS record to provider {jenkinslb.jenkins.ie lab.ielab.local. [192.168.10.244] A 299}: Failed to build RR: dns: not a TTL: \"lab.ielab.local.\" at line: 1:38"
```

What I believe happens is that external-dns creates a record based off this spec - 
```
<service_name>.<stack_name>.<environment_name>.<root_domain> {record set}
```

Since there was a space in the <environment_name> variable, it led to a parsing error in the RR.

**Expected:**
When I changed my environment name to ```westeros```, the update request worked.

edit: clear up reproduction steps
