### ISSUE TITLE
Health check for sidekicks having networkFrom primary service

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6305]
We should add support for defining health check for the sidekicks using network from main container.

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.8-rc1 with rancher/healthcheck:v0.3.2.

Deployed services having health check enabled for sidekick containers (with networkFrom primary service).

When the sidekick containers become unhealthy (In my case , I made the health check url become unavailable so that the health check url gets "404" ) , they continue to be in "healthy" state.

Sidekick containers are being monitored for health by only 1 host , when the primary container is monitored by 2 hosts.

The host that was monitoring the container's health has reported the container as being "DOWN". But container continues to be in "healthy" state.

```

mysql> select * from service_event where instance_id = 204;
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
| id   | name | account_id | kind         | uuid                                 | description | state   | created             | removed | remove_time | data | host_id | healthcheck_uuid                                                            | instance_id | healthcheck_instance_id | reported_health | external_timestamp |
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
| 1898 | NULL |          5 | serviceEvent | 62086294-ddfe-4f96-ba55-a01436f8a8c6 | NULL        | created | 2017-08-14 20:27:43 | NULL    | NULL        | {}   |       1 | 2c874d5b-d7de-46b5-bb27-a004c9bb6e9f_1d41aec2-2df1-4fae-a2ab-38c5b1c209c9_1 |         204 |                      97 | INIT            |         1502742463 |
| 1899 | NULL |          5 | serviceEvent | a1063ed2-2be2-42f2-bd7c-63e6cb959ea9 | NULL        | created | 2017-08-14 20:27:45 | NULL    | NULL        | {}   |       1 | 2c874d5b-d7de-46b5-bb27-a004c9bb6e9f_1d41aec2-2df1-4fae-a2ab-38c5b1c209c9_1 |         204 |                      97 | UP              |         1502742465 |
| 1900 | NULL |          5 | serviceEvent | a2e547ad-fae9-4a5a-86a9-7e1a78478251 | NULL        | created | 2017-08-14 20:41:44 | NULL    | NULL        | {}   |       1 | 2c874d5b-d7de-46b5-bb27-a004c9bb6e9f_1d41aec2-2df1-4fae-a2ab-38c5b1c209c9_1 |         204 |                      97 | DOWN            |         1502743304 |
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
3 rows in set (0.00 sec)

mysql> select * from service_event where instance_id = 203;
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
| id   | name | account_id | kind         | uuid                                 | description | state   | created             | removed | remove_time | data | host_id | healthcheck_uuid                                                            | instance_id | healthcheck_instance_id | reported_health | external_timestamp |
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
| 1892 | NULL |          5 | serviceEvent | 1c8de67d-e305-482b-afa0-f5be1654932c | NULL        | created | 2017-08-14 20:27:38 | NULL    | NULL        | {}   |       3 | ba3d2403-e729-49c9-bc2a-59ed8b4c11d2_cb4b4fa2-9018-4a1e-8062-d93840a07c59_1 |         203 |                      96 | INIT            |         1502742458 |
| 1893 | NULL |          5 | serviceEvent | c1a43c8d-54c5-402e-be5a-74e0557077a9 | NULL        | created | 2017-08-14 20:27:39 | NULL    | NULL        | {}   |       1 | 2c874d5b-d7de-46b5-bb27-a004c9bb6e9f_cb4b4fa2-9018-4a1e-8062-d93840a07c59_1 |         203 |                      96 | INIT            |         1502742459 |
| 1895 | NULL |          5 | serviceEvent | ac1b55bb-eca5-4fde-9011-6008bc311cd3 | NULL        | created | 2017-08-14 20:27:40 | NULL    | NULL        | {}   |       3 | ba3d2403-e729-49c9-bc2a-59ed8b4c11d2_cb4b4fa2-9018-4a1e-8062-d93840a07c59_1 |         203 |                      96 | UP              |         1502742460 |
| 1897 | NULL |          5 | serviceEvent | c19d525b-e6b0-4884-8037-f9a6b91a1030 | NULL        | created | 2017-08-14 20:27:41 | NULL    | NULL        | {}   |       1 | 2c874d5b-d7de-46b5-bb27-a004c9bb6e9f_cb4b4fa2-9018-4a1e-8062-d93840a07c59_1 |         203 |                      96 | UP              |         1502742461 |
+------+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+-----------------------------------------------------------------------------+-------------+-------------------------+-----------------+--------------------+
4 rows in set (0.00 sec)

```

**Comment by sangeethah** [comment]
When health check is enabled only in sidekick containers , then sidekick containers are stuck in "Initializing" state forever.

```
version: '2'
services:
  test2:
    image: sangeetha/testclient
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: test3
  test3:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    network_mode: container:test2
    tty: true
```

```
version: '2'
services:
  test2:
    scale: 1
    start_on_create: true
  test3:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 81
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/service3.html" "HTTP/1.0"
      reinitializing_timeout: 60000
```

No hosts monitor the health of the sidekick containers in this case.
