### ISSUE TITLE
Unable to use custom volume driver in docker-compose v2 (1.2.0)

### ISSUE THREAD

**Issue by lnattrass** [rancher/rancher#6310]
I've been trying everything to get a custom volume driver working on rancher for a while now...

Rancher Version:1.2.0-pre3
Docker Version:1.12.1
CentOS 7.1 and also CoreOS 1122.2 on local ESXi 
Setup Details: single node rancher, internal database
Environment Type: Cattle

**Steps to Reproduce:**
Create a volume in rancher with a custom driver:

```
version: '2'

volumes:
  data:
    driver: nfs
    driver_opts:
      share: nas:/mnt/tank/data

services:
  test:
    image: alpine
    labels:
      io.rancher.scheduler.affinity:host_label_soft: dev=true
    volumes:
      - data:/data
    command: sh
    tty: true
```

**Results:**

```
[root@dev01 ~]# docker volume ls
DRIVER              VOLUME NAME
local               dcedc9309e31932468c7ea814ceb0d5f223e9fdb268b0e4acd4bcc5476f70a49
local               tststack_data
[root@dev01 ~]#
```

**Expected:**

```
[root@dev01 ~]# docker volume ls
DRIVER              VOLUME NAME
local               dcedc9309e31932468c7ea814ceb0d5f223e9fdb268b0e4acd4bcc5476f70a49
nfs                  tststack_data
[root@dev01 ~]#
```

The docker-compose above works okay when I use docker-compose, but doesn't work when I use rancher UI or rancher-compose on v1.2.0.

In this instance, I am using the netshare driver for NFSv3 http://netshare.containx.io/
