### ISSUE TITLE
Containers using networkFrom other container are missing from metadata

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6326]
Steps to reproduce:

1) Create service foo with sidekick bar using networkFrom foo
2) list rancher-metadata/latest/containers

Bug: bar container is missing from the list

That will impact dns resolution once it is moved to a microservice, as the microservice relies on container presence in the metadata.

**Comment by alena1108** [comment]
https://github.com/rancher/rancher-dns/pull/35/commits/4644b757f8dee067555f599e7b49ecb336588f5b

**Comment by alena1108** [comment]
containers using networkFrom, should be in the metadata now. They have empty primary_ip field, and field network_from_container_uuid set to the uuid of its primary container.

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc7

Create a stack using the following yml to have a service with sicekick which has network from its primary container:

```
test-sk1:
  image: sangeetha/testclient
  net: "container:test-primary"
test-primary:
  image: sangeetha/testnewhostrouting
  ports:
    - 80:7001
  labels:
    io.rancher.sidekicks: test-sk1
```
wget  http://rancher-metadata/latest/containers/ shows 2 entries for this sidekick container:

33=hello-test-primary-test-sk1-1
56=hello-test-primary-test-sk1-1


Expected Behavior:
We should have only 1 entry for every container.
