### ISSUE TITLE
Validate Azure volume plugin 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6352]

**Comment by galal-hussein** [comment]
Here are my steps:

- Register an azure virtual machine with kubernetes cluster on Rancher.
- Attach a new disk to the azure virtual machine of size 1GB.
- Label the azure virtual machine on kubernetes with label (provider=azure), to be used later with node selector to make sure the pod will get created on the azure machine.
```
kubectl label nodes testvol-k8s provider=azure
```
- Run the pod, which should mount the disk on azure machine:
```
apiVersion: v1
kind: Pod
metadata:
 name: azure
spec:
 containers:
  - image: kubernetes/pause
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 nodeSelector:
   provider: azure
 volumes:
      - name: azure
        azureDisk:
          diskName: newvol-test                    
          diskURI: xxxxxxxxxxxxxxxxxx
```

**Results**
```
$  kubectl describe pods
Name:		azure
Namespace:	default
Node:		testvol-k8s/13.93.200.151
Start Time:	Thu, 20 Oct 2016 22:42:10 +0200
Labels:		<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  azure:
    Container ID:	
    Image:		kubernetes/pause
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /mnt/azure from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zs7xu (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  azure:
    Type:		AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)
    DiskName:		newvol-test
    DiskURI:		https://k8sdiag342.blob.core.windows.net/bootdiagnostics-testvolk8-4718c42b-863d-4bc7-a77c-e1717c00337f/newvol-test.vhd
    FSType:		ext4
    CachingMode:	None
    ReadOnly:		false
  default-token-zs7xu:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-zs7xu
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  20s		20s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned azure to testvol-k8s
  20s		4s		6	{kubelet testvol-k8s}			Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/azure-disk/ac82b7bf-9705-11e6-8614-025d5b72cb19-azure" (spec.Name: "azure") pod "ac82b7bf-9705-11e6-8614-025d5b72cb19" (UID: "ac82b7bf-9705-11e6-8614-025d5b72cb19") with: mount failed: exit status 32
Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/newvol-test /var/lib/kubelet/pods/ac82b7bf-9705-11e6-8614-025d5b72cb19/volumes/kubernetes.io~azure-disk/azure  [bind]
Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/newvol-test does not exist
```
