### ISSUE TITLE
"STARTUP FAILED" with simple external database compose

### ISSUE THREAD

**Issue by seanhoughton** [rancher/rancher#6368]
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Stock Ubuntu 16 on AWS

The following compose file results in a dead rancher container with the error. I would have expected this simple setup to work. It follows the instructions posted at http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/

> Error creating bean with name 'liquibase-core' defined in URL [jar:file:/usr/share/cattle/58488b81592773dcae114770406e3e1b/WEB-INF/lib/cattle-app-config-0.5.0-SNAPSHOT.jar!/META-INF/cattle/system/spring-system-context.xml]: Invocation of init method failed; nested exception is java.lang.ClassCastException: [B cannot be cast to java.lang.String

```
version: '2'

services:
    rancher:
      image: rancher/server:v1.1.4
      environment:
        - 'CATTLE_DB_CATTLE_MYSQL_HOST=db'
        - 'CATTLE_DB_CATTLE_MYSQL_PORT=3306'
        - 'CATTLE_DB_CATTLE_MYSQL_NAME=rancher'
        - 'CATTLE_DB_CATTLE_USERNAME=rancher'
        - 'CATTLE_DB_CATTLE_PASSWORD=rancher'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - cattle:/var/lib/cattle
      networks:
        - back
    db:
      image: mysql:8.0.0
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=rancher
        - MYSQL_USER=rancher
        - MYSQL_PASSWORD=rancher
      volumes:
        - db:/var/lib/mysql
      networks:
        - back
volumes:
  cattle:
  db:
networks:
  back:
```
