### ISSUE TITLE
Do not include empty entry for blkio_weight_device and change ipc_mode to ipc in generated config.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6404]
Rancher server version  - v1.2.0-pre4-rc5

Create a service with following fields set in launch config:
```
    launch_config = {"imageUuid": TEST_SERVICE_OPT_IMAGE_UUID,
                     "extraHosts": extraHosts,
                     "privileged": True,
                     "cpuShares": cpu_shares,
                     "blkioWeight": blkio_weight,
                     "blkioDeviceOptions": dev_opts,
                     "cgroup": cgroup,
                     "cgroupParent": cgroup_parent,
                     "cpuShares": cpu_shares,
                     "cpuPeriod": cpu_period,
                     "cpuQuota": cpu_quota,
                     "cpuSet": cpu_set,
                     "cpuSetMems": cpu_setmems,
                     "dnsOpt": dns_opt,
                     "groupAdd": group_add,
                     "kernelMemory": kernel_memory,
                     "memoryReservation": memory_reservation,
                     "memorySwap": memory_swap,
                     "memorySwappiness": memory_swappiness,
                     "oomKillDisable": oom_killdisable,
                     "oomScoreAdj": oom_scoreadj,
                     "readOnly": read_only,
                     "securityOpt": security_opt,
                     "shmSize": shm_size,
                     "stopSignal": stop_signal,
                     "sysctls": sysctls,
                     "tmpfs": tmp_fs,
                     "ulimits": [ulimit],
                     "ipcMode": ipcMode,
                     "uts": uts,
                     "requestedHostId": hosts[0].id
                     }
```

In the generated yaml for this stack ,  do not include empty entry for blkio_weight_device and change ipc_mode to ipc in generated config.
```
version: '2'
services:
  test274421:
    device_write_bps:
      /dev/null: 200
    device_write_iops:
      /dev/sda: 3000
    cpu_quota: 20000
    read_only: true
    ipc_mode: host
    memswap_limit: -1
    oom_score_adj: 100
    cpu_shares: 400
    shm_size: 1024
    cgroup_parent: xyz
    security_opt:
    - label=user:USER
    - label=role:ROLE
    device_read_bps:
      /dev/null: 4000
    tmpfs:
    - /tmp:rw
    group_add:
    - root
    blkio_weight_device: {}
    blkio_weight: 1000
    stop_signal: SIGTERM
    dns_opt:
    - abc
    cgroup: abc
    ulimits:
      cpu:
        hard: 1024
        soft: 1024
    extra_hosts:
    - host1:10.1.1.1
    - host2:10.2.2.2
    cpu_period: 10000
    cpuset: '0'
    image: ibuildthecloud/helloworld:latest
    mem_reservation: 5000000
    device_read_iops:
      /dev/sda: 2000
    mem_swappiness: 100
    oom_kill_disable: true
    uts: host
    privileged: true
```
