### ISSUE TITLE
[question] SSL redirection and LetsEncrypt

### ISSUE THREAD

**Issue by T-Grave** [rancher/rancher#6409]
**Problem**
I have an Ingress resource that looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lb
  namespace: production
spec:
  tls:
    - hosts:
      - example.com
      secretName: example-tls
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: storefront
          servicePort: 80
      - path: /.well-known/acme-challenge
        backend:
          serviceName: letsencrypt-storefront
          servicePort: 80
```

My service is available using `https://example.com` and my renewal process for the certificate seems to work as well.

I would however like all http traffic to be redirected to https. Currently when I visit `http://example.com` it doesn't redirect the user to the `https` version.

I know I could redirect all traffic on port 80 to a small service container returning 302 reponses(as described in #3505), but this would break my letsencrypt renewal service. Also, I'm not to sure it's possible to configure Ingress in a way it would only listen to the 443 port as described in before mentioned issue.

Any ideas on how I can solve this in my Rancher Kubernetes environment?

@alena1108 : Seeing as you do most of the lb work, you might have an idea on how to solve this?

Thanks in advance!
