### ISSUE TITLE
Volume Only Container degraded and restarting all the time

### ISSUE THREAD

**Issue by apertureless** [rancher/rancher#6415]
**Rancher Version:** 1.1.2

**Environment Type:** Cattle
---

I have two containers. One running mysql and a sidekick for the volume. 

_docker-compose.yml_

``` yaml
dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

db:
  image: mysql:5.6
  volumes_from:
  - dbdata
  labels:
    io.rancher.sidekicks: dbdata
  ports:
    - 3306:3306
```

However the dbdata container keeps getting degraded all the time and then stopping and starting again. In docker compose on my local machine it seems working fine.
