### ISSUE TITLE
Support for dynamic question type in catalog

### ISSUE THREAD

**Issue by abeMedia** [rancher/rancher#6420]
I have a use case where I created a catalog entry for an API gateway which needs to be linked to a dynamic amount of other services, with a few configuration parameters for each one. Currently the only way to do this is with a multiline field containing JSON, YAML or similar, however this is not very intuitive.

It would be awesome if the catalog supported a new type which rendered exactly how the `Listening Ports` and `Targets` fields do in the load balancer and could be configured along these lines:

``` yaml
.catalog:
  name: "My API Gateway"
  ...
  questions:
    - variable: "API_ENDPOINTS"
      label: "API Endpoints"
      type: "question_table"
      questions:
        - variable: "api"
          label: "API Service"
          type: "service"
        - variable: "listen_path"
          label: "Listen path"
          type: "string"
       ...
```

Resulting in `$API_ENDPOINTS` returning something like:

``` json
[{"api": "foo", "listen_path": "/foo"}, {"api": "bar", "listen_path": "/bar"}]
```
