### ISSUE TITLE
Unsupported config option - uts/cgroup

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6434]
Rancher server version - v1.2.0-pre4-rc6
Rancher compose version - rancher-compose-v0.11.0-rc6

Not able to create a service using up command with the following yml files. 
I get - "Unsupported config option - uts/cgroup" error and also "service: dependency \'mem_limit\' is not satisfied" message.

```
version: '2'
services:
  test88536:
    device_write_bps:
      /dev/null: 200
    device_write_iops:
      /dev/sda: 3000
    cpu_quota: 20000
    read_only: true
    memswap_limit: -1
    oom_score_adj: 100
    cpu_shares: 400
    shm_size: 1024
    cgroup_parent: xyz
    security_opt:
    - label=user:USER
    - label=role:ROLE
    device_read_bps:
      /dev/null: 4000
    tmpfs:
    - /tmp:rw
    group_add:
    - root
    blkio_weight: 1000
    stop_signal: SIGTERM
    dns_opt:
    - abc
    cgroup: abc
    ulimits:
      cpu:
        hard: 1024
        soft: 1024
    extra_hosts:
    - host1:10.1.1.1
    - host2:10.2.2.2
    cpu_period: 10000
    cpuset: '0'
    image: ibuildthecloud/helloworld:latest
    mem_reservation: 5000000
    device_read_iops:
      /dev/sda: 2000
    mem_swappiness: 100
    ipc: host
    oom_kill_disable: true
    uts: host
    privileged: true
```

```
version: '2'
services:
  test88536:
    scale: 2
```

```
./rancher-compose -p test883351rancher -f test883351rancher-docker-compose.yml -r test883351rancher-rancher-compose.yml up -d

Obtained Response: [u'time="2016-10-28T21:09:12Z" level=error msg="Could not parse config for project test883351rancher : Invalid configuration for \'test88536\' service: dependency \'mem_limit\' is not satisfied\\nUnsupported config option for uts service: \'cgroup\'\\nUnsupported config option for test88536 service: \'uts\'" \n', u'time="2016-10-28T21:09:12Z" level=fatal msg="Failed to read project: Invalid configuration for \'test88536\' service: dependency \'mem_limit\' is not satisfied\\nUnsupported config option for uts service: \'cgroup\'\\nUnsupported config option for test88536 service: \'uts\'" \n']
```
