### ISSUE TITLE
Error: occurred while checking if volume exists: EOF

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#6436]
**Rancher Version:**
v1.1.4

**Docker Version:**
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**
OS: ros version v0.7.0
Cloud: Amazon Web Services - EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
My environment was built with a single node rancher running ros version v0.7.0 with external DB + single host running ros version v0.7.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
You will need an Amazon web services account.
- Create an S3 bucket at Amazon Web Services. For this example, I'll use mybucket.
- Create an IAM user with the following policy:

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket",
                "arn:aws:s3:::mybucket/*"
            ]
        }
    ]
}
```
- Build the following image and name it _sb-baseimage_. You need to download some packages first and put them into the same folder of the Dockerfile:

``` bash
wget https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz
wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
wget https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64 ; gzip -9 confd-0.11.0-linux-amd64
```

``` Dockerfile
FROM alpine:3.4

#------------------------------
# EVIRONMENT VARIABLES
#------------------------------

ENV S6_FILE=s6-overlay-amd64.tar.gz \
    DOCKERIZE_FILE=dockerize-linux-amd64-v0.2.0.tar.gz \
    CONFD_FILE=confd-0.11.0-linux-amd64.gz \
    BIN_PATH=/usr/local/bin

#------------------------------
# INSTRUCTIONS
#------------------------------

RUN apk --update add \
    tar

COPY root /

RUN cd /tmp \
    && tar -xzf ${S6_FILE} -C / \ 
    && tar -zxf ${DOCKERIZE_FILE} -C ${BIN_PATH}/ \
    && gunzip -c ${CONFD_FILE} > ${BIN_PATH}/confd \
    && chown root. ${BIN_PATH}/* \
    && chmod 0700 ${BIN_PATH}/* \
    && mkdir -p /etc/confd/conf.d \
    && mkdir -p /etc/confd/templates \
    && rm -rf /tmp/* \
    && apk del --purge tar \
    && rm -rf /var/cache/apk/* \
    && chmod 1777 /tmp

ENTRYPOINT ["/init"]
```
- Execute the following commands on the registered host to enable kernel-headers (it is necessary to make possible run a nfsserver in a container)

``` bash
sudo ros service enable kernel-headers
sudo ros service up -d kernel-headers
```
- Build the following image: https://forums.rancher.com/t/nfs-server-no-support-in-current-kernel/4343/24?u=bruno.galindro and name it _sb-s3nfs_.
- Add a stack called convoy-nfs using the docker-compose and rancher-compose from the above link. Don't forget to put the AMI Access Key into AWSACCESSKEYID and AWSSECRETACCESSKEY environment variables on the docker-compose.yml. The URL variable must meet your S3 region. See [this documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for more details.

``` yaml
# docker-compose.yml
s3nfs:
  image: sb-s3nfs
  environment:
    AWSACCESSKEYID: <put_here>
    AWSSECRETACCESSKEY: <put_here>
    URL: <S3 url>
  cap_add:
    - SYS_ADMIN
  tty: true
  privileged: true
  stdin_open: true

convoy-nfs:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /run:/host/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: rancher/convoy-agent:v0.9.0
  command: volume-agent-nfs
  links:
    - s3nfs:s3nfs

convoy-nfs-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  image: rancher/convoy-agent:v0.9.0
  volumes:
    - /var/run:/host/var/run
    - /run:/host/run
  command: storagepool-agent
  links:
    - s3nfs:s3nfs
```

``` yaml
# rancher-compose.yml
s3nfs:
  scale: 1

convoy-nfs:
    metadata:
        nfs_server: "s3nfs"
        mount_dir: "/"
        mount_opts: "proto=tcp,nfsvers=4"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

convoy-nfs-storagepool:
    metadata:
        nfs_server: "s3nfs"
        mount_dir: "/"
        mount_opts: "proto=tcp,nfsvers=4"
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
```
- Wait for the stack to be fully deployed:

![image](https://cloud.githubusercontent.com/assets/4622097/19823149/e359a07a-9d45-11e6-8f9f-aca47eb16f47.png)
- Go to Infrastructure > Storage and Add a new Volume. You need to refresh the page to make the volume visible (this problem was reported before here: https://github.com/rancher/rancher/issues/3312 and it still occurs with 1.1.4 version @deniseschannon. I'm very sorry about not giving a feedback to you...)

![image](https://cloud.githubusercontent.com/assets/4622097/19822996/13699924-9d45-11e6-8c10-a806bd0082f9.png)
- Now add a stack (nfstest) with the following docker-compose and rancher-compose files:

``` yaml
# docker-compose.yml
nfsclient:
  tty: true
  entrypoint:
  - /bin/sh
  image: alpine
  volumes:
  - s3fs:/data
  stdin_open: true
  volume_driver: convoy-nfs
```

``` yaml
# rancher-compose.yml
nfsclient:
  scale: 1
```

**Results:** 
After the nfstest stack is created, the following error is displayed:

![image](https://cloud.githubusercontent.com/assets/4622097/19822094/8514f55a-9d40-11e6-91e8-1c5ed9c70532.png)

I can confirm that on the S3 bucket, some files was created after I have launched the nfstest stack:

``` bash
s3fs                                          # this is a directory
config/vfs_volume_s3fs.json   # this file has 0 bytes
```

**Expected:**
I expect to mount the nfs exported directory into a new container inside a different stack.
