### ISSUE TITLE
v2 key "tmpfs" is not used while creating services

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6437]
Rancher Version:v1.2.0-pre4-rc5

Docker Version:1.12.2

OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu, Cloud

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)Single node

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)Cattle

Steps to Reproduce:
1. Create a stack "Stack1" using the below yaml file:
```
version: '2'
services:
  web:
    image: sangeetha/testnewhostrouting
    command: "sleep 1000"
    logging:
      driver: syslog
    network_mode: "bridge"
    tmpfs:
      - /run
```
**Results:** 
The service created does not have "tmpfs" set in the API. 
The exported file also does not have "tmpfs"
