### ISSUE TITLE
Rancher catalog: "invalid character '\x00' in string literal" for large catalog entries (>3k)

### ISSUE THREAD

**Issue by rezonant** [rancher/rancher#6447]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu / cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Multi-node, internal-DB, no-HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create a custom catalog entry which contains enough content in its set of files (ie rancher-compose.yml, service.yaml, deployment.yaml) such that the buffer sent to `/r/projects/1a5/kubectld:8091/v1-kubectl/catalog?defaultNamespace=production` is over 3096 characters.

I was testing with this adminMongo catalog entry which also contained a fairly lengthy `deployment.yaml` and `service.yaml`:

``` yaml
.catalog: 
  description: "A user interface for managing MongoDB"
  name: adminMongo
  version: 1.0
  questions: 
    - description: "Domain to deploy the service to"
      label: "Domain name to deploy on"
      required: true
      type: string
      variable: domain
    - description: "A secret containing 'realm' name and 'users' file (htpasswd format) for basic authentication"
      label: "Basic-Auth Secret"
      required: false
      type: string
      variable: basicauth_secret
    - default: MongoDB
      description: "A user-readable name to attach to the default MongoDB connection"
      label: "Name of default MongoDB connection"
      required: false
      type: string
      variable: conn_name
    - default: mongo
      description: "Mongo host to connect to"
      label: "MongoDB host"
      required: false
      type: string
      variable: mongo_host
    - default: "27017"
      description: "Mongo port to connect to"
      label: "MongoDB port"
      required: false
      type: string
      variable: mongo_port
    - default: ""
      description: "Username to use to connect to MongoDB"
      label: "MongoDB user"
      required: false
      type: string
      variable: mongo_user
    - default: ""
      description: "Password to use to connect to MongoDB"
      label: "MongoDB password"
      required: false
      type: string
      variable: mongo_pass
    - default: "true"
      description: "Whether to run monitoring at regular intervals"
      label: "Monitoring"
      required: true
      type: string
      variable: monitoring
```

Note that this is not over 3096 characters so I don't think it will trigger the bug. 
However, because this is purely a file length limitation, you can trigger it with the following:

```
.catalog: 
  description: "A user interface for managing MongoDB"
  name: adminMongo
  version: 1.0
  questions: 
    - description: "Domain to deploy the service to ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    "
      label: "Domain name to deploy on"
      required: true
      type: string
      variable: domain
```

Now, attempt to start the service from the catalog entry, providing whatever values you want for the questions.

**Results:** 

This error is shown with no additional information as to where:
`invalid character '\x00' in string literal`

In the browser's inspector, there is slightly more information provided in the response to `POST /r/projects/1a5/kubectld:8091/v1-kubectl/catalog?defaultNamespace=production`:

```
{"exitCode":-1,"stdOut":"","stdErr":"invalid character '\\x00' in string literal","error":{"Offset":3096}}
```

From this, it's clear that the limit being hit is 3096 characters. I'm not sure if the content is truncated before being processed, or if this is a buffer overflow.

**Expected:**
Rancher should spin up the service, and provide more information when failures like this occur. Or, if the maximum length of a rancher-compose file is 3096 characters, then the frontend should indicate that the file is too long.
