### ISSUE TITLE
Support GCE as a cloud provider for kubernetes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6457]
**Rancher Version:**
v1.2.0-pre4-rc6
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4.4
**Steps to Reproduce:**
use branch (1.2) to provision k8s 1.4 with provider set to gce.
try to create the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
**Results:** 
The pod stuck in pending state with the following error:

```
-----	----			-------------	--------	------			-------
  2m		1m		7	{default-scheduler }			Warning		FailedScheduling	no nodes available to schedule pod
```
