### ISSUE TITLE
stickiness policy gets set for LB when no stickiness policy is set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6458]
Rancher server version - Build from master
rancher-compose version v0.11.0-rc7

Steps to reproduce the problem:
Create LB service using the following docker-compose/rancher-compose files.

When Lb service gets created , stickiness policy gets set to "cookie" type.

```
"stickinessPolicy": {
"type": "loadBalancerCookieStickinessPolicy",
"mode": "insert",
},
```
```
version: '2'
services:
  test825722:
    image: sangeetha/testnewhostrouting:latest
  test271590:
    image: sangeetha/testnewhostrouting:latest
  LB-test890396:
    ports:
    - 900:900/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:latest
  test11504:
    image: sangeetha/testnewhostrouting:latest
  test939972:
    image: sangeetha/testnewhostrouting:latest
```

```
version: '2'
services:
  test825722:
    scale: 2
  test271590:
    scale: 2
  LB-test890396:
    scale: 1
    lb_config:
      certs: []
      config: null
      default_cert: null
      port_rules:
      - backend_name: null
        hostname: www.abc1.com
        path: /service1.html
        priority: null
        protocol: http
        selector: null
        service:test271590
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc2.com
        path: /service2.html
        priority: null
        protocol: http
        selector: null
        service:test271590
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc1.com
        path: /service1.html
        priority: null
        protocol: http
        selector: null
        service: test939972
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc2.com
        path: /service2.html
        priority: null
        protocol: http
        selector: null
        service: test939972
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc3.com
        path: /service1.html
        priority: null
        protocol: http
        selector: null
        service: test784419/test825722
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc4.com
        path: /service2.html
        priority: null
        protocol: http
        selector: null
        service: test784419/test825722
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc3.com
        path: /service1.html
        priority: null
        protocol: http
        selector: null
        service: test11504
        source_port: 900
        target_port: 80
      - backend_name: null
        hostname: www.abc4.com
        path: /service2.html
        priority: null
        protocol: http
        selector: null
        service: test784419/test11504
        source_port: 900
        target_port: 80
      stickiness_policy: null
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  test11504:
    scale: 2
  test939972:
    scale: 2
```
