### ISSUE TITLE
Exported yaml file has extra colon when using the tmps key

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6461]
**Rancher Version:**1.2.0-pre4-rc6

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a stack using the yaml file below:
```
version: '2'
services:
  web:
    image: sangeetha/testnewhostrouting
    command: "sleep 1000"
    logging:
      driver: syslog
    tmpfs:
      - /run
      - /tmp
```
After the stack is created, the exported file is below which has colon after the directory:

```
version: '2'
services:
  web:
    tmpfs:
    - '/run:'
    - '/tmp:'
    command:
    - sleep
    - '1000'
    image: sangeetha/testnewhostrouting:latest
    logging:
      driver: syslog

```

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. Created a stack using the yaml given above. The exported file (without colons) is below:
```
version: '2'
services:
  web:
    tmpfs:
    - /run
    - /tmp
    command:
    - sleep
    - '1000'
    image: sangeetha/testnewhostrouting
    logging:
      driver: syslog
```
