### ISSUE TITLE
Exported yaml file does not have the key depends_on set after creating the stack

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6462]
**Rancher Version:**1.2.0-pre4-rc6

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a stack "Stack1" with depends_on key using the below yaml file:
```
version: '2'
services:
  web:
    image: busybox
    command: "sleep 1000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```
The stack is created with all the 3 services. But the exported yaml file does not have depends_on key which was used while creating the stack. Exported file below:
```
version: '2'
services:
  db:
    image: postgres:latest
  redis:
    image: redis:latest
  web:
    command:
    - sleep
    - '1000'
    image: busybox:latest
```
