### ISSUE TITLE
Kubernetes ingress targets are not served in a round robin fashion

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6463]
**Rancher Version:**Master

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
This test fails while running our automation tests.
The following steps have been used in our automation:
Create service/rc/pods using the yaml file below:
```
apiVersion: v1
kind: Service
metadata:
  name: k8test13
  labels:
    k8s-app: k8test13-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: k8test13-service

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8testrc13
spec:
  replicas: 1
  selector:
    k8s-app: k8test13-service
  template:
    metadata:
      labels:
        k8s-app: k8test13-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: testcontainer
        image: sangeetha/testnewhostrouting
        ports:
        - containerPort: 80
        tty: true
```
Create an ingress using the following yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress13
 annotations:
   http.port: "96"

spec:
  backend:
    serviceName: k8test13
    servicePort: 80
```
Increment the pod scale by replacing the replication controller using the following yaml file:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8testrc13
spec:
  replicas: 3
  selector:
    k8s-app: k8test13-service
  template:
    metadata:
      labels:
        k8s-app: k8test13-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: testcontainer
        image: sangeetha/testnewhostrouting
        ports:
        - containerPort: 80
        tty: true
```
**Results:** 
The services/rc/pods/ingress are created successfully. 
The targets are not hit in a round robin fashion always

**Expected:**
The targets should be served in a round robin fashion
