### ISSUE TITLE
Ingress with ssl listener is not functional.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6464]
Server version - Build from master

Steps to reproduce the problem:

Create Ingress with ssl listener using the following yml files:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress12
  annotations:
   http.port: "95"
spec:
  tls:
   - secretName: certificate
  backend:
    serviceName: k8test12
    servicePort: 80

```

```
apiVersion: v1
kind: Service
metadata:
  name: k8test12
  labels:
    k8s-app: k8test12-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: k8test12-service

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8testrc12
spec:
  replicas: 2
  selector:
    k8s-app: k8test12-service
  template:
    metadata:
      labels:
        k8s-app: k8test12-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: testcontainer
        image: sangeetha/testnewhostrouting
        ports:
        - containerPort: 80
        tty: true
```

lb ip  is not functional.

haproxy.conf indicates that http mode is used:

```
listen default
bind *:42

frontend 95
bind *:95
mode http
default_backend 95_

backend 95_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_prot
o
mode http
server 10.42.96.227 10.42.96.227:80
server 10.42.111.55 10.42.111.55:80
root@bc45bfc836a6:/#
```
