### ISSUE TITLE
[rancher-compose] unsupported config option upgrade_strategy

### ISSUE THREAD

**Issue by jensendw** [rancher/rancher#6477]
**Rancher Version: v1.1.0

**Docker Version:1.10.3

**OS and where are the hosts located? :AWS, ubuntu 14.04

**Setup Details: single node, external DB

**Environment Type: Cattle

**Steps to Reproduce:

Using rancher-compose 0.8.5 I get this, but using rancher-compose 0.7.4 it works
Running the following against any rancher-compose.yml file that contains upgrade_strategy.
```
/usr/local/bin/rancher-compose --url https://rancher.something.com -f "rancher-compose.yml" --access-key $RANCHER_ACCESS_KEY --s
ecret-key $RANCHER_SECRET_KEY --project-name sensu up --upgrade -d -c
```
```
cat rancher-compose.yml

sensu-server :
  scale: 2
  tty: false
  upgrade_strategy:
    start_first: true
    batch_size: 1
  labels:
    io.rancher.scheduler.affinity:host_label: asg_name=rancher-operations-o1
    io.rancher.container.pull_image: always
  image: my.private.repo/operations/sensu-server:1.11
```

**Results:** 
```
ERRO[0000] Could not parse config for project sensu : Unsupported config option for sensu-server service: 'upgrade_strategy'
FATA[0000] Failed to read project: Unsupported config option for sensu-server service: 'upgrade_strategy'
make: *** [deploy] Error 1
```
**Expected:**

Standard upgrade should happen, at least it does with rancher-compose v0.7.4, I looked at the new rancher-compose documentation here https://docs.rancher.com/rancher/v1.2/en/cattle/upgrading/  it doesn't look like the syntax has changed.  With v0.7.4 I get this:

```
WARN[0001] A newer version of rancher-compose is available: 0.8.5
INFO[0001] Project [sensu]: Starting project
INFO[0001] [0/1] [sensu-server]: Starting
INFO[0002] Upgrading sensu-server
INFO[0053] [1/1] [sensu-server]: Started
```
