### ISSUE TITLE
Suppress io.rancher.container.create_agent and  io.rancher.container.agent.role in generated config for LB services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6519]
Rancher server version - Build from master

Steps to reproduce the problem:
Create an Lb service and get the generated config using "View config" option on the stack.

Generated config has the following 2 labels , which can be suppressed.

```
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
```
```
docker-compose.yml 
version: '2'
services:
  test969759:
    image: sangeetha/testlbsd:latest
  LB-test669803:
    ports:
    - 18901:18901/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:latest
```
