### ISSUE TITLE
Unsupported load balancer affinity: ClientIP

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#6525]
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc6
**Docker Version:**
Docker version 1.12.1, build 23cf638
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.0 on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
K8s 1.4
**Steps to Reproduce:**
create a service with service.spec.sessionAffinity to ClientIP:
```
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    name: nodejs
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
  selector:
    name: nodejs
```
**Results:** 
Error creating load balancer (will retry): Failed to create load balancer for service default/nodejs: Unsupported load balancer affinity: ClientIP
**Expected:**
No error
