### ISSUE TITLE
Heapster container throws errors and cannot gather node information in Kubernetes 1.4.4

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6547]
**Rancher Version:**Master

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

Steps to Reproduce:

1.Create a 3 host Kubernetes set up. Ensure ipsec, metadata, dns, healthcheck, scheduler, networkmanager microservices are enabled.
2. Create a heapster service using the below yaml:
```
apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-grafana
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30804
    targetPort: 3000
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: heapster
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster

---

apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-influxdb
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30805
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    name: influxGrafana

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://$KUBERNETES_SERVICE_HOST?inClusterConfig=false&insecure=true
        - --sink=influxdb:http://monitoring-influxdb:8086

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: influxdb-grafana
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v2.6.0-2
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://monitoring-influxdb:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
```
All containers are running, but the following errors show up in the logs:
```
11/7/2016 4:07:44 PME1108 00:07:44.329026       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:44 PME1108 00:07:44.331813       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:44 PME1108 00:07:44.332393       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:44 PME1108 00:07:44.333074       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:44 PME1108 00:07:44.335678       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:313: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
11/7/2016 4:07:45 PME1108 00:07:45.331040       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:45 PME1108 00:07:45.332808       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:45 PME1108 00:07:45.333882       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:45 PME1108 00:07:45.334698       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:45 PME1108 00:07:45.337014       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:313: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
11/7/2016 4:07:46 PME1108 00:07:46.332943       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:46 PME1108 00:07:46.334516       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:46 PME1108 00:07:46.335604       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:46 PME1108 00:07:46.337216       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:46 PME1108 00:07:46.338282       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:313: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
11/7/2016 4:07:47 PME1108 00:07:47.334824       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:47 PME1108 00:07:47.336393       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:47 PME1108 00:07:47.337259       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:47 PME1108 00:07:47.338379       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:47 PME1108 00:07:47.339372       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:313: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
11/7/2016 4:07:48 PME1108 00:07:48.336765       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:48 PME1108 00:07:48.338540       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:48 PME1108 00:07:48.338957       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:48 PME1108 00:07:48.340884       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:48 PME1108 00:07:48.341741       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:313: Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
11/7/2016 4:07:49 PME1108 00:07:49.338682       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: the server has asked for the client to provide credentials (get namespaces)
11/7/2016 4:07:49 PME1108 00:07:49.340509       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:49 PME1108 00:07:49.340962       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:321: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
11/7/2016 4:07:49 PME1108 00:07:49.342035       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)



```
