### ISSUE TITLE
DNS resolution does not work for sidekick containers that have network from primary containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6555]
Rancher Version: v1.2.0-pre4-rc7

Steps to reproduce the problem:
Create  a service with sidekick containers that have network from primary containers using the following docker-compose.yml:

```
version: '2'
services:
  sk:
    network_mode: container:primary
    image: sangeetha/testclient
  primary:
    ports:
    - 80:7001/tcp
    labels:
      io.rancher.sidekicks: sk
    image: sangeetha/testnewhostrouting
```
DNS resolution does not work for sidekick containers:

```
root@1ce05b92f2ed:/# dig primary.test4  +short
10.42.60.225
root@1ce05b92f2ed:/# dig sk.primary.test4  +short
;; Warning: Message parser reports malformed message packet.
```

Also I see the hostname on the sidekick container set to primary containers docker id. 
Is this is as expected ?
