### ISSUE TITLE
rancher-compose doesn't replace environment variables on upgrade

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#6560]
I'm refering an old closed issue #3574. 

**Rancher Version:**
1.1.4

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
export variable_name="jjjj"
rancher up --force deploy
export variable_name="cccc"
rancher up --force deploy

**Results:** 
varibale_name (should be used in docker-compose) will not be updated
**Expected:**
varibale_name is updated (interpolated)

I did some tests and I think upper case varibale names could help (VARIABLE_NAME="jjjj")

**Comment by deniseschannon** [comment]
do you have a docker-compose file that i could test with?

**Comment by pschrammel** [comment]
I think I have sth reproducable:
```
cat docker-compose.yml 
test:
  image: ruby:2.1.5-slim
  environment:
    - UPPER_CASE_VAR=$UPPER_CASE_VAR
    - LOWER_CASE_VAR=$lower_case_var
  labels:
    io.rancher.container.start_once: 'true'
  command: env

cat rancher-compose.yml 
.catalog:
  name: "Rancher Test"
  version: 0
  description: |
    Metoda Account
  uuid: account-0
  questions:
    - variable: "UPPER_CASE_VAR"
      label: "Upper"
      default: "UPPER"
      required: true
      type: "string"
    - variable: "lower_case_var"
      label: "Lower"
      default: "lower"
      required: true
      type: "string"

cat vars.sh 
export UPPER_CASE_VAR="YEAH UPPER - new3"
export lower_case_var="yeah lower - new6"
```

To reproduce:

-  create a catalog (rancher-test) with the docker- and rancher-compose files
- install from catalog
- upgrade the envs through UI. 
- run sth like "source vars.sh && rancher-compose -p rancher-test up --force-upgrade"
- see how your variables in vars.sh will be ignored

If you do not change vars through UI rancher-compose will override the vars.
