### ISSUE TITLE
storage_driver definitions in docker-compose.yml aren't creating storageDriverService in rancher

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#6564]
**Rancher Version:** master

**Docker Version:** n/a

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** n/a

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** n/a

**Steps to Reproduce:**
Run [nfs](https://github.com/rancher/rancher-catalog/tree/1.2/infra-templates/nfs/0) system template via CLI `rancher stack create --system` or via UI

**Results:** storage_driver definition is not present in service "data" field

**Expected:** storage_driver definition is present in service "data" field

network_driver definitions should also be passed in cattle API requests when specified in docker-compose.yml

**Comment by deniseschannon** [comment]
@LLParse I'm not sure what you mean by service `data` field.

Using rancher-compose v0.11.0-rc9
Using master from nov 8

I used the following ymls

```
nfs-driver:
  privileged: true
  image: rancher/storage-nfs:v0.1.1
  pid: host
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
```

rancher-compose.yml

```
nfs-driver:
  storage_driver:
    name: rancher-nfs
    scope: environment
    volume_access_mode: multiHostRW
```

Launching in rancher-compose CLI,  I can see the service and in the API, I see the storage_driver definition

![screen shot 2016-11-09 at 4 39 54 pm](https://cloud.githubusercontent.com/assets/11410997/20160361/2c609b30-a69b-11e6-99f6-728563ba9c2e.png)


Can you look again? I am wondering if you had an older version of cattle or rancher-compose.

**Comment by LLParse** [comment]
@deniseschannon It was the opinion of @ibuildthecloud that the storageDriver definition should be put int the docker-compose.yml file. It is understood by the team that it functions when defined in rancher-compose.yml.

**Comment by joshwget** [comment]
It should be supported in both, but are we going to put it in `docker-compose.yml` by default? Do we put other Rancher specific items in `docker-compose.yml` in the catalog?

**Comment by LLParse** [comment]
I don't think we put any of the rancher-specific stuff in `docker-compose.yml` today. Since the definition works in `rancher-compose.yml`, I don't see this as a high priority item.

**Comment by ibuildthecloud** [comment]
@joshuacox @LLParse The idea is that rancher-compose.yml should be optional.  (with the exception of the .catalog key, that's a different story).  So `storage_driver` should work if I put it in the docker-compose.yml or rancher-compose.yml as a field of the service.  In v1 or v2 format.

**Comment by deniseschannon** [comment]
Regardless of where it is, I believe that the driver is setting storage driver correctly in the API. 

@LLParse If you have any more issues, please re-open.

**Comment by LLParse** [comment]
@deniseschannon I tested this and it does not work in `docker-compose.yml`, the definition does not appear in the API and the storage handler can't do its thing. It does appear in the API when placed in `rancher-compose.yml`.

**Comment by deniseschannon** [comment]
Determined the issue

When `storage_driver` is in rancher-compose.yml, it correctly creates a storageDriverService in Rancher as expected, but when it's in docker-compose.yml, it creates a service. 

updated the templates so that `storage_driver` is in rancher-compose.yml so that it works, but need a fix in rancher-compose.

**Comment by deniseschannon** [comment]
Validated in v1.6.0-rc1. The following docker-compose.yml produces a storage service:

```
nfs-driver:
    nfs-driver:
    storage_driver:
      name: rancher-nfs
      scope: environment
      volumeAccessMode: multiHostRW
    start_on_create: true
    privileged: true
    image: rancher/storage-nfs:v0.1.1
    pid: host
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
```
