### ISSUE TITLE
Question : Variable substitution as a partial json object

### ISSUE THREAD

**Issue by ogdabou** [rancher/rancher#6577]
Hi everyone,

**Rancher Version:** v1.1.3

**Docker Version:** v1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Debian 8 (64bits)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher, external DB (mounted volume)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**  Cattle

**Steps to Reproduce:** 
1- Create a custom rancher catalog
2- In `doker-compose.yml`, write reference for variable substitution this way  
```yaml
my-example:
  image: whatever_spring_boot_application_image
  ports:
    - 80825:8082
  environment:
    - json_property='{ "my.json.prop" : { ${MY_JSON_PARTIAL} }'
```
3- Define varialbe in rancher-compose.yml
```yaml
.catalog:
  ...
  questions: #Used to request user input for configuration options
    - variable: "MY_JSON_PARTIAL"
      description: "inner json to complete"
      label: "Json conf"
      required: true
      default: '"variable.one" : "value.one", "variable.two": "value.two"'
      type: "string"
```

**Results:** 
```yaml
'''{"my.json.prop": {'"variable.one" : "value.one", "variable.two": "value.two"'}}'''
```  
As we can see, simple quotes are added when injecting the variable, and I don't know why but 3 appears on the side.  

**Expected:**
```yaml
'{"my.json.prop":{"variable.one" : "value.one", "variable.two": "value.two"}}'
```  
  
**Why doing this:**  
Maybe my approach is wrong, but here is what I intend to do :  
Have a master application running on Rancher, which will starts workers with a Rancher client.  
So  `"my.json.prop"` is actually the default env variables to be passed to the worker, its not fixed.
Of course I can put the whole json object into the `rancher-compose.yaml` but it's very messy to edit.  
  
Have you got any ideas ? workaround ? Is this even possible ?
Maybe I missed something important, maybe I'm completly dumb as I am not using `yaml` very often.
  
Thank you for your help, thank you for your work <3.
