### ISSUE TITLE
Rancher Compose: Isolation key is not set in the service api 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6587]
**Rancher Version:**v1.2.0-pre4-rc7

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack with "isolation" key set using the yml file below:
```
version: '2'
services:
  test554094:
    device_write_bps:
      /dev/null: 200
    device_write_iops:
      /dev/vda: 3000
    cpu_quota: 20000
    read_only: true
    memswap_limit: 2000000000
    oom_score_adj: 100
    cpu_shares: 400
    shm_size: 1024
    cgroup_parent: abcd
    mem_limit: 1000000000
    security_opt:
    - label:user:USER
    - label:role:ROLE
    tmpfs:
    - /run
    device_read_bps:
      /dev/null: 4000
    group_add:
    - root
    blkio_weight: 1000
    stop_signal: SIGTERM
    dns_opt:
    - abc
    extra_hosts:
    - h1:162.242.195.82
    - h2:162.241.195.82
    cpu_period: 10000
    cpuset: '0'
    image: ibuildthecloud/helloworld:latest
    mem_reservation: 5000000
    device_read_iops:
      /dev/vda: 2000
    dns_search:
    - abc
    mem_swappiness: 100
    oom_kill_disable: true
    ipc: host
    isolation: default
```
**Results**
isolation key is not set in service api
The exported yml file does not have the isolation key:
```
version: '2'
services:
  test554094:
    device_write_bps:
      /dev/null: 200
    device_write_iops:
      /dev/vda: 3000
    cpu_quota: 20000
    read_only: true
    memswap_limit: 2000000000
    oom_score_adj: 100
    cpu_shares: 400
    shm_size: 1024
    cgroup_parent: abcd
    mem_limit: 1000000000
    security_opt:
    - label:user:USER
    - label:role:ROLE
    tmpfs:
    - /run
    device_read_bps:
      /dev/null: 4000
    group_add:
    - root
    blkio_weight: 1000
    stop_signal: SIGTERM
    dns_opt:
    - abc
    extra_hosts:
    - h1:162.242.195.82
    - h2:162.241.195.82
    cpu_period: 10000
    cpuset: '0'
    image: ibuildthecloud/helloworld:latest
    mem_reservation: 5000000
    device_read_iops:
      /dev/vda: 2000
    dns_search:
    - abc
    mem_swappiness: 100
    oom_kill_disable: true
    ipc: host
```

**Comment by joshwget** [comment]
@StrongMonkey Isolation is being dropped in the `/scripts/transform` API.

**Comment by StrongMonkey** [comment]
@alena1108 Could you please take a look? I have test cases that already covered `isolation`, but i doubt this is beyond the logic i wrote in cattle. Is there any java classed that does this transformation?

**Comment by StrongMonkey** [comment]
I think `ServiceDiscoveryConfigItem.java` is only responsible for transforming `launch_config` into yml files.

**Comment by alena1108** [comment]
@StrongMonkey this is the class responsible for fields transformation on the instance (and launch config): 

./code/implementation/docker/api/src/main/java/io/cattle/platform/docker/api/transform/TransformInspect.java

And when rancher-compose invokes /scripts/transform API path, this is the cattle code that is being hit. And by some reason, "isolation" field is being stripped.

Try debugging by putting a break point here to figure out if the field is even coming with the request. If yes, and then it is being dropped, check how this field is any different from the rest of the fields you've added.

**Comment by soumyalj** [comment]
Will test with windows OS in 1.3.0

**Comment by ibuildthecloud** [comment]
windowsOS, like macOS but with more powershell :)

**Comment by StrongMonkey** [comment]
lol

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.3.0-rc1

When a stack is created with the following yml file , service that gets created has isolation saved at the api level.

```
version: '2'
services:
  testhyper:
    image: microsoft/iis
    stdin_open: true
    network_mode: nat
    tty: true
    isolation: hyperv
    ports:
    - 9081:80/tcp
    labels:
      io.rancher.container.pull_image: always
```

Exported config of this service also has " isolation: hyperv" set in it.
