### ISSUE TITLE
When yml compose files with certs for LB in v1 version  is used to create stack , LB is stuck in "Initializing" state forever. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6594]
Rancher server version - Build from master

Steps to reproduce the problem:
Create 2 certs "test1" and "test2".
Use the following yml compose files to create stack.

LB gets stuck in "Initializing" state forever with following error message seen:
```
11/11/2016 10:30:06 AMtime="2016-11-11T18:30:06Z" level=error msg="Failed to get lb config: Coudln't get certificate by name [test1]. Error: Unknown schema type [certificate]"
```

ymls used:

```
test536846:
  image: sangeetha/testnewhostrouting:latest
LB-test972684:
  ports:
  - 4061:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '4061'
    io.rancher.loadbalancer.target.test950163: www.abc2.com/service2.html
    io.rancher.loadbalancer.target.test536846: www.abc1.com/service1.html
  image: rancher/load-balancer-service
  links:
  - test536846:test536846
  - test950163:test950163
test950163:
  image: sangeetha/testnewhostrouting:latest
Sangeethas-MacBook-Pro:ssl sangeethahariharan1$ cat rc.yml 
test536846:
  scale: 2
LB-test972684:
  scale: 1
  certs:
  - test1
  default_cert: test2
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
test950163:
  scale: 2
```
