### ISSUE TITLE
When yml compose files with target port override for LB in v1 version is used to create stack , LB is missing port rules.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6598]
Rancher Version: Build form master

Steps to reproduce the problem:
Use the following yml compose files to create stack.
```
Sangeethas-MacBook-Pro:hostrouting sangeethahariharan1$ cat dc.yml 
test678500:
  image: sangeetha/testnewhostrouting:latest
LB-test154262:
  ports:
  - 1008:80
  - 1009:81
  labels:
    io.rancher.loadbalancer.target.test936526: www.abc1.com:1008/service1.html,www.abc1.com:1009/service3.html
    io.rancher.loadbalancer.target.test956454: /service1.html=80,/service3.html=81
    io.rancher.loadbalancer.target.test678500: www.abc1.com
  image: rancher/load-balancer-service
  links:
  - test936526:test936526
  - test956454:test956454
  - test678500:test678500
  - test398531:test398531
test398531:
  image: sangeetha/testnewhostrouting:latest
test936526:
  image: sangeetha/testnewhostrouting:latest
test946778:
  image: sangeetha/testnewhostrouting:latest
test956454:
  image: sangeetha/testnewhostrouting:latest

Sangeethas-MacBook-Pro:hostrouting sangeethahariharan1$ cat  rc.yml 
test678500:
  scale: 2
LB-test154262:
  scale: 1
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
test398531:
  scale: 2
test936526:
  scale: 2
test946778:
  scale: 2
test956454:
  scale: 2
Sangeethas-MacBook-Pro:hostrouting sangeethahariharan1$ 
```
Target test956454 has 2 port rules  relating to ```/service3.html=80``` for both ports - 1008 and 1009.
as expected.

Missing  port rules relating relating to  1008 and 1009 for port ```/service1.html=80```
