### ISSUE TITLE
DNS support for k8s Pods

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6599]
**Rancher Version:**
master build (11 Nov)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4.5

- Create kubernetes environment
- run the following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

The DNS should resolve (POD-IP.my_namespace.pod.cluster.local), but it doesn't:
```
root@nginx-mapa0:/# nslookup 10.42.81.11.default.pod.cluster.local                                                                                                                           
Server:		169.254.169.250
Address:	169.254.169.250#53

** server can't find 10.42.81.11.default.pod.cluster.local: NXDOMAIN
```
