### ISSUE TITLE
DNS support for "hostname" and "subdomain" Pod Specs

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6600]
**Rancher Version:**
master build (11 Nov)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4.5

**Steps to Reproduce:**
- Create kubernetes stack
- Run the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx
spec:
  hostname: foo
  subdomain: bar
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
The DNS should resolve (**foo.bar.default.svc.cluster.local**) to the pod's IP.

```
root@nginx-mapa0:/# nslookup foo.bar.default.svc.cluster.local
Server:		169.254.169.250
Address:	169.254.169.250#53

** server can't find foo.bar.default.svc.cluster.local: NXDOMAIN
```
