### ISSUE TITLE
Cannot setup Rancher HA v1.2.0-pre4-rc7

### ISSUE THREAD

**Issue by jdel** [rancher/rancher#6611]
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc7

**Docker Version:**
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.0-rc7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA with Galera Cluster

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a galera cluster (3 nodes), setup Rancher HA

**Results:** 
```bash
time="2016-11-14T10:05:31Z" level=info msg="Waiting for server to be available" component=cert
time="2016-11-14T10:05:31Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
```

**Expected:**
I expect Rancher HA to start

To clarify, I am setting up a sandbox environment to test Rancher 1.2 and Rancher OS 0.7.
I setup everything with VirtualBox 5.1.4 on my Mac, installed RancherOS from iso with basic cloud-config as below:

```yml
#cloud-config
ssh_authorized_keys:
  - ssh-rsa xxx
hostname: rancher-server-01
rancher:
  network:
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 10.0.2.11/24
        gateway: 10.0.2.2
      eth1:
        address: 192.168.99.11/24
    dns:
      nameservers:
        - 192.168.99.21
        - 192.168.99.22
        - 192.168.99.23
```

My virtual machines have two network interfaces, eth0 configured as NAT (to be able to do pulls), eth1 setup as host-only network for me to ssh to the machines.

I have already tried adding CATTLE_AGENT_IP=172.17.0.2 in rancher-ha.sh but it seems to be completely ignored as it still tries to connect to 172.17.0.1

I can provide more logs if required.
