### ISSUE TITLE
Rancher load balancer does not auto-migrate when host goes down

### ISSUE THREAD

**Issue by renaudholcombe** [rancher/rancher#6612]
Rancher Version: 1.1.2

Docker Version: 1.10.3

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 14.04.5 hosted in Amazon EC2

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB): HA Rancher, external DB, 3 host machines.

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create stack with 1 rancher load balancer and N service containers
2. Shut down host that is running the rancher load balancer

Results:
Host shows as "Reconnecting" and rancher load balancer is still marked as healthy so it is not migrated to a healthy host.

Expected:
Rancher load balancer would be migrated to a healthy host.

**Comment by deniseschannon** [comment]
Are you sure the load balancer did not get migrated? Typically, it should get re-deployed on another host, but the one on the "reconnecting" host will still show up as that was the last known state on the host. 

So from the host view, there might be 2 load balancers, but in the services, there will be 1 active and woking LB.

**Comment by renaudholcombe** [comment]
Yes, I verified with another test that the load balancer is not being migrated. Are there some logs that would help shed light on what might be happening?

**Comment by renaudholcombe** [comment]
Any idea's on this? We've had to resort to striping load balancers across all hosts in order to mitigate this issue.

**Comment by renaudholcombe** [comment]
@deniseschannon, any ideas on this? Seems like it might be falling through the cracks.

**Comment by deniseschannon** [comment]
@renaudholcombe Could you share your docker-compose.yml and rancher-compose.yml for the LB definition that you have? How many hosts do you have? How many LBs? Did you make them through the UI?

**Comment by renaudholcombe** [comment]
Sure, we have 3 hosts and when replicating the issue we use a single load balancer; all containers/load balancers are created via docker/rancher compose. Docker-compose is below:
`node-service:
  ports:
  - "33305"
  image: "$node-servicetag"
  mem_limit: 2147483648
  environment:
    - API_URL=${API_URL}
  external_links:
    - routing/consul-agent:consul-agent
lb:
  ports:
  - "33306:33305"
  labels:
    io.rancher.loadbalancer.target.node-platformweb-server: /=33306
  image: rancher/load-balancer-service
  links:
  - node-service:node-service`

Rancher compose is below:
`.catalog:
  name: "node-service-stack"
  version: "$stack_version"
  description: "Node service stack"
  uuid: $uuid
  questions:
    - variable: API_URL
      description: "Consul agent port"
      label: "Consul agent port"
      type: string
      required: true
      default: "http://consul-agent:8001"
node-service:
  scale: 3
lb:
  scale: 1`

**Comment by renaudholcombe** [comment]
@deniseschannon, any ideas or next steps?

**Comment by renaudholcombe** [comment]
Reviving the thread; @deniseschannon, what are the next steps for troubleshooting this issue? It's still occurring for us.

**Comment by deniseschannon** [comment]
@renaudholcombe Your load balancer doesn't have a health check on it in the rancher-compose.yml, which is why it's not migrating. I had initially thought that you had created the load balancer through the UI, which automatically has a health check created with it.

You'll need the health check in order for services to be migrated to a different host when a host goes to reconnecting.

```
 .catalog:
  name: "node-service-stack"
  version: "$stack_version"
  description: "Node service stack"
  uuid: $uuid
  questions:
    - variable: API_URL
      description: "Consul agent port"
      label: "Consul agent port"
      type: string
      required: true
      default: "http://consul-agent:8001"
node-service:
  scale: 3
lb:
  scale: 1
  health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```
