### ISSUE TITLE
ulimit parameters not being set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6614]
Rancher Version: Build from master

rancher-compose.yml used for creating service with ulimit params - hard,soft and name provided.

```
services:
  test303196:
    device_write_bps:
      /dev/null: 200
    device_write_iops:
      /dev/sda: 3000
    cpu_quota: 20000
    read_only: true
    memswap_limit: -1
    oom_score_adj: 100
    cpu_shares: 400
    shm_size: 1024
    cgroup_parent: xyz
    mem_limit: 8000000
    security_opt:
    - label=user:USER
    - label=role:ROLE
    device_read_bps:
      /dev/null: 4000
    tmpfs:
    - /tmp:rw
    group_add:
    - root
    blkio_weight: 1000
    stop_signal: SIGTERM
    dns_opt:
    - abc
    ulimits:
      cpu:
        hard: 1024
        soft: 1024
    extra_hosts:
    - host1:10.1.1.1
    - host2:10.2.2.2
    cpu_period: 10000
    cpuset: '0'
    image: ibuildthecloud/helloworld:latest
    mem_reservation: 5000000
    device_read_iops:
      /dev/sda: 2000
    mem_swappiness: 100
    oom_kill_disable: true
    ipc: host
    uts: host
    privileged: true
```

When service is started , container fails to start with following exception - ```Error (Error response from daemon: invalid header field value "oci runtime error: Wrong rlimit value: RLIMIT_\n")```

In the service that gets created , u limit is missing  params - hard,soft and name  that was provided in yml.

```
"ulimits": [
{
"type": "ulimit",
},
],
```
