### ISSUE TITLE
"Unable to establish SSL connection." error seen often when trying to access LB ip which have port rules with SNI protocol.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6620]
Rancher Version: Build from master

Steps to reproduce problem:
Have target service s1 listening on port  443 with certificates for test1.com
Have target service s2 listening on port  443 with certificates for test2.com

Create LB service with port rules having "sni" protocol using the following definition:

```
version: '2'
services:
  test546137:
    image: sangeetha/ssllbtarget2:latest
  LB-test497531:
    ports:
    - 20001:20001/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:latest
  test211211:
    image: sangeetha/ssllbtarget1:latest
```
```
version: '2'
services:
  test546137:
    scale: 2
  LB-test497531:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - hostname: test1.com
        protocol: sni
        service: test511837/test211211
        source_port: 20001
        target_port: 443
      - hostname: test2.com
        protocol: sni
        service: test511837/test546137
        source_port: 20001
        target_port: 443
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  test211211:
    scale: 2
```

When LB ip is accessed with test1.com/test2.com, they get directed to containers are service s1/s2 respectively. But lot of times , we get the following error when trying to access the LB ip:

```
Sangeethas-MacBook-Pro:sslcerts sangeethahariharan1$ wget --timeout=20 --tries=1 --ca-certificate=test2.com.crt  https://test2.com:20001/name.html
--2016-11-14 13:44:57--  https://test2.com:20001/name.html
Resolving test2.com... 104.197.244.142
Connecting to test2.com|104.197.244.142|:20001... connected.
Unable to establish SSL connection.
```
