### ISSUE TITLE
All instances of a service that has volumes from rancher-nfs volumedriver land on the same host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6660]
Rancher Version: Build from master

Steps to reproduce the problem:
Add "Rancher-Nfs" stack to "Cattle" environment.

Create service with scale =1 having volumes from rancher-nfs volumedriver with following yml:
```
version: '2'
services:
  nginx1:
    image: nginx
    volumes:
    - foo1:/tmp
  nginx2:
    image: nginx
    volumes:
    - foo2:/mydata1

volumes:
  foo1:
    driver: rancher-nfs
    external: false
  foo2:
    driver: rancher-nfs
    external: false
```

once the service is started successfully , scale up the service.
Notice that all the instances of the service land on the same host.
