### ISSUE TITLE
K8 environment fails to start when using route53 private dns name for server

### ISSUE THREAD

**Issue by sundeer** [rancher/rancher#6664]
**Rancher Version:**
v1.1.4

**Docker Version:**
v1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
- AWS
- RancherOS v0.7.0
- ami-c62170b5/eu-west-1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- Single server, internal DB
- Using terraform for starting all server/hosts
- Server user_data:
```yaml
#cloud-config
rancher:
  services:
    rancher-server:
      image: rancher/server:latest
      restart: always
      name: rancher-server
      ports:
        - 8080:8080
```
- Host user_data template:
```yaml
#cloud-config
rancher:
  services:
    rancher-agent-boot:
      image: rancher/agent:v1.0.2
      command: ${agent_registration_url}
      detatch: true
      privileged: true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
K8

**Steps to Reproduce:**
If the host user_data template variable ```${agent_registration_url}```is rendered with the EC2 server private ip, k8 works fine:
```http://10.79.37.201:8080/v1/projects/1a8/scripts/36FC84018F4648ED3A02:1479477600000:RyTzI1E8y73q05AVMoJzG719WI```

Same result if rendered with private dns:
```http://ip-10-79-37-201.eu-west-1.compute.internal:8080/v1/projects/1a8/scripts/36FC84018F4648ED3A02:1479477600000:RyTzI1E8y73q05AVMoJzG719WI```

However k8 fails to start if I create a route53 private hosted zone like ```rancher.local.``` with an A record like```server.rancher.local. => 10.79.37.201``` and use it in the hosts user_data like:
```http://server.rancher.local:8080/v1/projects/1a8/scripts/36FC84018F4648ED3A02:1479477600000:RyTzI1E8y73q05AVMoJzG719WI```

**Results:** 
 rancher-ingress-controller_1 errors:
```time="2016-11-18T15:14:44Z" level=fatal msg="Failed to create Rancher client Get http://server.rancher.local:8080/v1: dial tcp: lookup server.rancher.local: no such host"```

 rancher-kubernetes-agent_1 keeps restarting

all other k8 containers are start up just fine

**Expected:**
I can ssh into hosts and ping server via private ip, private dns, and 'server.rancher.local' so I would expect the k8 containers to be able to resolve 'server.rancher.local' as well.
