### ISSUE TITLE
mount information not shown in "storage Driver" view for volumes that are in "active" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6677]
Rancher Version: Build from master

Server version - Build from master
rancher/storage-nfs:v0.2.0

Steps to reproduce the problem:
Create a service using volumes from rancher-nfs volume driver with the following yml
```
version: '2'
services:
  nginx1:
    image: nginx
    volumes:
    - foo1:/tmp
  nginx2:
    image: nginx
    volumes:
    - foo2:/mydata1

volumes:
  foo1:
    driver: rancher-nfs
    external: false
  foo2:
    driver: rancher-nfs
    external: false
```
once the service is started , goto Infrastructure->storage view to see all the volumes created.

Volume is shown in "active" state but no "Mounts" are listed.
<img width="1240" alt="screen shot 2016-11-18 at 8 16 06 pm" src="https://cloud.githubusercontent.com/assets/4266958/20452997/db9cc0a0-adcc-11e6-8318-b974eccd7a0e.png">
