### ISSUE TITLE
Catalogs that are not valid in the current Rancher version are not correctly looking up available versions

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6704]
**Rancher Version:**
v1.1.4 upgraded to v1.2.0-pre4-rc10

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
1. Launch a kubernetes environment in Ranchr 1.1.4. Current default template is 1.2.4-rancher10
```
.catalog:
  name: Kubernetes
  version: v1.2.4-rancher10
  description: Rancher Kubernetes service
  minimum_rancher_version: v1.1.4
  maximum_rancher_version: v1.1.99
```

2. Upgrade Rancher server to 1.2.0-pre4-rc10. Upgrade the k8s environment

**Results:** 
 Kubernetes stack doesn't show upgrade available. 

**Expected:**
Kuberenetes shows upgrade available for 1.4.6 template. 

Note: If I set `maximum_rancher_version` so that it would be valid for v1.2.0-pre4-rc10, upgrade available appears.
