### ISSUE TITLE
Deletion of EBS volume , results in only 1 of the volume(out of the 2) to be deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6714]
Rancher Version: v1.2.0-pre4-rc10

Steps to reproduce the problem:
Deploy rancher-ebs.
Create a volume with name say "abc"
Create a service with  this volume in volume driver "rancher-ebs" with scale=2.
There are 2 EBS volumes with name "abc" that gets created in AWS EBS.

Delete this service. 
volume gets to "detached" state. 
Delete this volume.

Only one of the instance of the volume get deleted from  AWS EBS.
The other instance of the volume continues to be there.

**Comment by LLParse** [comment]
@sangeethah Did you use the UI to create this service? We need to know [what scope](https://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/) the volume(s) had, because it may be the case that only one volume should be created in the first place.

**Comment by LLParse** [comment]
Reproduced by using environment (default) scope. The 2nd docker create request doesn't look for existing volumes with the same AWS Name tag.

**Comment by LLParse** [comment]
@StrongMonkey TL;DR At https://github.com/rancher/storage/blob/v0.7.0/package/ebs/rancher-ebs#L128 we need to search for existing volumes with the desired name tag. Something like this:
```
aws ec2 describe-volumes --filters Name=tag-key,Values="Name" Name=tag-value,Values="test" --query 'Volumes[*].{ID:VolumeId,Tag:Tags}'
```

**Comment by StrongMonkey** [comment]
I can not reproduce it with rancher 1.5.1 and storage-ebs v0.6.5. It seems to be fixed by this commit https://github.com/rancher/storage/commit/a55a88716c505edb9ae4a9d93c94d8ac031c7af4

**Comment by StrongMonkey** [comment]
@sangeethah I follow the same steps in the issue and didn't reproduce it. I have three containers using the volume but only one volume was created in AWS ebs. Can you re-test to see if you can reproduce it now?

**Comment by LLParse** [comment]
@StrongMonkey I've successfully reproduced on rancher 1.5.1 with ebs 0.6.5

First, install rancher CLI and make a folder somewhere. Add these files:
docker-compose.yml
```
version: '2'

services:
    etcd:
        image: rancher/etcd:v2.3.7-11
        labels:
            io.rancher.scheduler.affinity:host_label_soft: etcd=true
        environment:
            RANCHER_DEBUG: 'true'
            EMBEDDED_BACKUPS: 'true'
            BACKUP_PERIOD: 1s
            BACKUP_RETENTION: 10m
        volumes:
        - /pdata
        - bar:/data-backup

volumes:
    bar:
        driver: rancher-ebs
        external: true
```
rancher-compose.yml
```
etcd:
  scale: 3
```

Steps:
1. Create an env with 3+ AWS hosts in the same AZ
2. Start rancher-ebs
3. Create volume 'bar' in UI
4. Run `rancher stack create` from the folder you created

Result:
etcd starts on _different_ hosts, 3 volumes of name `bar` are created.

Expected:
etcd starts on same host, 1 volume of name `bar` is created.
