### ISSUE TITLE
volumes in UI need to export using v2 syntax volume format. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6726]
With the move to v2 syntax support for compose files, the old volume logic should export in v2 format. Since volumes without a volumeTemplate are environment scoped, we should convert to the environment scoped volume.

Current Format in v1.2.0-pre4-rc11
```
version: '2'
services:
  testexistingvol:
    tty: true
    image: ubuntu:14.04.3
    volumes:
    - testvolume:/testing
    stdin_open: true
    volume_driver: rancher-nfs
```

Expected Version:

```
version: '2'
services:
  testexistingvol:
    tty: true
    image: ubuntu:14.04.3
    volumes:
    - testvolume:/testing
    stdin_open: true
volumes:
   testvolume: # This is the name of the volume from the API
     driver: rancher-nfs
     external: true  
```

**Comment by soumyalj** [comment]
Tested with v1.2.1-rc1. After export we see the V2 syntax for volumes:
```
version: '2'
volumes:
  testvolume:
    external: true
    driver: local
services:
  testexistingvol:
    image: ubuntu:14.04.3
    stdin_open: true
    volumes:
    - testvolume:/testing
    tty: true
```
