### ISSUE TITLE
Loadbalancer: cant set SourceIP / Port anymore

### ISSUE THREAD

**Issue by toughIQ** [rancher/rancher#6727]
**Rancher Version:**
v1.2.0-pre4-rc11
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2 (VMware)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, external MariaDB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Upgrading from rc6 to rc11. It told that Loadbalancers have to be upgraded.
**Results:** 
Upgrade Failed.
**Expected:**
Smooth LB upgrade.

I suspect: I had a LB setting, where I added a dedicated IP to bind to. I tried to clone my old LB and configure my requirements with the new one. I couldnt find any option/possibility to add a __SourceIP/Port__ setting. Seems this whole section, which is there in v1.1.4, is missing from v1.2.

Am I missing something?

**Comment by deniseschannon** [comment]
Upgrades will only be supported from 1.1.4 to 1.2.0 and 1.2.0-pre3 to 1.2.0. We've gone from v1 Load balancer to a v2 load balancers and in 1.2.0, we will be converting old v1 LBs to the new v2 LBs. 

There is an extensive documentation update regarding the new Load balancers that will be coming with 1.2.0. 

Can you share your docker-compose.yml of your old LB?

**Comment by toughIQ** [comment]
I am sorry, but I nuked my old dev environment with this upgrade, so I dont have the old compose file anymore. Here is the current one, which doesnt start.
(IP address and domains randomized) 
```
  loadbalancer:
    ports:
    - 123.123.12.12:443:443/tcp
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.loadbalancer.ssl.ports: '443'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.loadbalancer.target.portus: portus.mydomain.at:443=3000
      io.rancher.loadbalancer.target.registry: registry.mydomain.at:443=5000
    tty: true
    image: rancher/lb-service-haproxy:v0.4.1
    links:
    - portus:portus
    - registry:registry
    stdin_open: true
```
But even if the automatic upgrade doesnt work, I cant recreate my old config using the new interface. There seems to be no place to put the IP to listen to.
