### ISSUE TITLE
Updating LB source port does not check if the port is available on the host and will take over port

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6765]
**Rancher Version:**
1.2.0-pre4-rc14

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a nginx container with global scale and export port 80 (to occupy port 80 on all hosts)
2. Create a ghost container (ghost)
3. Create a LB using source port 81 pointing to the ghost container pointing to 2368. 
4. Update/Edit the LB to change the source port to 80. 

**Results:** 
No error is thrown, the LB is updated and starts to point the traffic to the ghost container instead of the nginx container.

**Expected:**
Error to show that the port is already in use and not allow the LB to update to the new port and start having all new traffic direct to the new service. 

Docker-compose.yml to start steps 1-3.

```
 version: '2'
services:
  nginx:
    ports:
    - 80:80/tcp
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: nginx
    stdin_open: true
  ghostlb:
    ports:
    - 81:81/tcp
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
    image: rancher/lb-service-haproxy:v0.4.2
  ghost:
    tty: true
    image: ghost
    stdin_open: true
```

Rancher-compose.yml

```
version: '2'
services:
  ghostlb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: testrepro/ghost
        source_port: 81
        target_port: 2368
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      response_timeout: 2000
      healthy_threshold: 2
  ghost:
    scale: 1
```
