### ISSUE TITLE
Migrated Lbs have io.rancher.loadbalancer.target.<target-name> labels which can be supressed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6780]
Rancher-server version - v1.2.0-pre4-rc15

Steps to reproduce the problem:

Fresh install of Rancher-server version - v1.1.4.
Create Lb service which has some hostname routing rules.
Example yml file
```
test678500:
  image: sangeetha/testnewhostrouting:latest
LB-test154262:
  ports:
  - 1008:80
  - 1009:81
  labels:
    io.rancher.loadbalancer.target.test936526: www.abc1.com:1008/service1.html,www.abc1.com:1009/service3.html
    io.rancher.loadbalancer.target.test956454: /service1.html=80,/service3.html=81
    io.rancher.loadbalancer.target.test678500: www.abc1.com
  image: rancher/load-balancer-service
  links:
  - test936526:test936526
  - test956454:test956454
  - test678500:test678500
  - test398531:test398531
test398531:
  image: sangeetha/testnewhostrouting:latest
test936526:
  image: sangeetha/testnewhostrouting:latest
test946778:
  image: sangeetha/testnewhostrouting:latest
test956454:
  image: sangeetha/testnewhostrouting:latest
test678500:
  image: sangeetha/testnewhostrouting:latest
LB-test154262:
  ports:
  - 1008:80
  - 1009:81
  labels:
    io.rancher.loadbalancer.target.test936526: www.abc1.com:1008/service1.html,www.abc1.com:1009/service3.html
    io.rancher.loadbalancer.target.test956454: /service1.html=80,/service3.html=81
    io.rancher.loadbalancer.target.test678500: www.abc1.com
  image: rancher/load-balancer-service
  links:
  - test936526:test936526
  - test956454:test956454
  - test678500:test678500
  - test398531:test398531
test398531:
  image: sangeetha/testnewhostrouting:latest
test936526:
  image: sangeetha/testnewhostrouting:latest
test946778:
  image: sangeetha/testnewhostrouting:latest
test956454:
  image: sangeetha/testnewhostrouting:latest
```
```
test678500:
  scale: 2
LB-test154262:
  scale: 1
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
test398531:
  scale: 2
test936526:
  scale: 2
test946778:
  scale: 2
test956454:
  scale: 2
```

Upgrade to v1.2.0-pre4-rc15.
Upgrade environment.

Lb that gets upgraded, has ``` io.rancher.loadbalancer.target.*``` labels that can be suppressed:

<img width="1104" alt="screen shot 2016-11-26 at 6 55 34 pm" src="https://cloud.githubusercontent.com/assets/4266958/20645156/f71cada2-b409-11e6-8de7-d7818afaeb90.png">

Similar to this issue - https://github.com/rancher/rancher/issues/6597
