### ISSUE TITLE
It starts, stops and restarts continuously a container

### ISSUE THREAD

**Issue by bitliner** [rancher/rancher#6783]
**Rancher Version:**

rancher/agent:v1.0.2
rancher/agent-instance:v0.8.3

**Docker Version:**

Docker version 1.11.1, build 5604cbe

**OS and where are the hosts located? (cloud, bare metal, etc):**

bare metal, Linux Ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1. Add a new stack using a docker-compose yml file
2. Start stack

**Results:** 

The stack in docker-compose file is composed by a database, API e frontend. Locally it works fine. On Rancher, the front-end gets continuously restarting.

No errors in the log of the agent and agent instance.

The image is from a private account on docker hub, but the registry is properly specified.

The AuditLogs shows that many times Rancher is 

```
Service reconcile - "waiting for [instance:stageAppHelloCo_appStageFrontend_1]. Instance status: null
```

**Expected:**

The frontend should start without getting restarted every time and continuously.

**Comment by bitliner** [comment]
If I delete the service of the stack, and add it manually and start it manually, then everything works fine

**Comment by bitliner** [comment]
After I removed the service and added it manually, I tried also to delete the stack and recreate it from scratch.

And now also the stack works fine.

**Comment by vincent99** [comment]
Closing due to inactivity, please reopen with a specific reproducible compose file if you still have an issue on current releases.

**Comment by devfelipereis** [comment]
I have exactly the same issue. And I fix as @bitliner said.
The only container that keeps restarting is my application container(framework files, assets, etc).

My compose is something like this:

```
application:
    image: MYAPPIMAGE
    restart: "no"
    volumes:
      - application:/var/app
      - app-storage:/app-storage
    labels:
      - io.rancher.container.pull_image=always

...

volumes:
  application:
    driver: "rancher-nfs"
  database-data:
    driver: "rancher-nfs"
  app-storage:
    driver: "rancher-nfs"

```

Other services are nginx, php-fpm and mariadb(it's a laravel app).

All starts good but the application service after some seconds starts to restarting.

If I set "io.rancher.container.start_once=true" in compose file, it also works.
