### ISSUE TITLE
rancher-compose do not honor docker-compose container_name

### ISSUE THREAD

**Issue by fenchu** [rancher/rancher#6791]
I'm unable to get the proper name on my container resulting in links not working

I can use r-<project_name>_<container_name>_1 but how do I maintain compatibility with
docker-compose? and it will add extra checks to autoparse all config for proper linking.

Is this fixed in newer version of rancher? I can get the ops-guys to upgrade

--
Thanks
Morten Bjoernsvik, Oslo, Norway

**Rancher Version:**
Rancher 	v1.0.0
Cattle 	v0.159.2
User Interface 	v0.100.3
Rancher Compose 	v0.7.3

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04LTS all servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Enclosed docker-compose.yml

```
cat docker-compose.yml 
sslfactory:
  container_name: sslfactory
  ports:
  - 8802:8802/tcp
  - 38802:38802/tcp
  image: vmbld07it.intra.buypass.no:5001/sslfactory:latest
  links:
  - productapi:8653
  - tlscheck:9000
  stdin_open: true
  labels:
    io.rancher.container.name: sslfactory
    io.rancher.container.hostname_override: sslfactory
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: env=test12
tlsdetect:
  container_name: tlsdetect
  ports:
  - 9100:9100/tcp
  log_driver: ''
  image: vmbld07it.intra.buypass.no:5001/tls-detect-cert-service-server:latest
  labels:
    io.rancher.container.name: tlsdetect
    io.rancher.container.hostname_override: tlsdetect
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: env=test12
tlscheck:
  container_name: tlscheck
  ports:
  - 9000:9000/tcp
  image: vmbld07it.intra.buypass.no:5001/tls-checker-api-server:latest
  links:
  - tlsdetect:9100
  labels:
    io.rancher.container.name: tlscheck
    io.rancher.container.hostname_override: tlscheck
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: env=test12
productapi:
  container_name: productapi
  ports:
  - 8653:8653/tcp
  image: vmbld07it.intra.buypass.no:5001/product-api:latest
  labels:
    io.rancher.container.name: productapi
    io.rancher.container.hostname_override: tlscheck
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: env=test12
```

**Results:** 

```
$ docker ps
CONTAINER ID        IMAGE                                                                   COMMAND                  CREATED             STATUS              PORTS
              NAMES
f3febd3c4315        vmbld07it.intra.buypass.no:5001/sslfactory:latest                       "/bin/sh -c '/usr/loc"   25 minutes ago      Up 25 minutes       0.0.0.0:8802->8802/tcp, 0.0.0.0:38802->38802/tcp   r-sslfactory_sslfactory_1
a9a12eb7cda5        vmbld07it.intra.buypass.no:5001/tls-checker-api-server:latest           "su-exec buypassuser "   25 minutes ago      Up 25 minutes       0.0.0.0:9000->9000/tcp
              r-sslfactory_tlscheck_1
d42e5bacd3df        vmbld07it.intra.buypass.no:5001/tls-detect-cert-service-server:latest   "su-exec buypassuser "   25 minutes ago      Up 25 minutes       0.0.0.0:9100->9100/tcp
              r-sslfactory_tlsdetect_1
196887857cd1        vmbld07it.intra.buypass.no:5001/product-api:latest                      "su-exec buypassuser "   25 minutes ago      Up 25 minutes       0.0.0.0:8653->8653/tcp
              r-sslfactory_productapi_1
```

**Expected:**
Same docker-compose.yml with "docker-compose up -d" has correct names:

```
$ docker ps
CONTAINER ID        IMAGE                                                                   COMMAND                  CREATED             STATUS              PORTS                                              NAMES
bcf6b4c7b801        vmbld07it.intra.buypass.no:5001/sslfactory:latest                       "/bin/sh -c '/usr/loc"   2 minutes ago       Up 4 seconds        0.0.0.0:8802->8802/tcp, 0.0.0.0:38802->38802/tcp   sslfactory
7b65be54da57        vmbld07it.intra.buypass.no:5001/tls-checker-api-server:latest           "su-exec buypassuser "   2 minutes ago       Up 5 seconds        0.0.0.0:9000->9000/tcp                             tlscheck
2db8a2241967        vmbld07it.intra.buypass.no:5001/product-api:latest                      "su-exec buypassuser "   2 minutes ago       Up 5 seconds        0.0.0.0:8653->8653/tcp                             productapi
0b83c51908f4        vmbld07it.intra.buypass.no:5001/tls-detect-cert-service-server:latest   "su-exec buypassuser "   2 minutes ago       Up 5 seconds        0.0.0.0:9100->9100/tcp                             tlsdetect

```
