### ISSUE TITLE
Importing docker-compose/rancher-compose that has lb pointing to a service in the same stack using stackname/service name fails to come up

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6828]
**Rancher Version:**
v1.2.0-rc1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Use following docker-compose.yml/ rancher-compose.yml to create a stack with name `testing2`.  Notice how the port rule in rancher-compose.yml uses `testing2/nginx`. 

docker-compose.yml
```
version: '2'
services:
  nginx:
    image: nginx
    stdin_open: true
    tty: true
  lb:
    image: rancher/lb-service-haproxy:v0.4.2
    ports:
    - 90:90/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

rancher-compose.yml
```
version: '2'
services:
  nginx:
    scale: 1
  lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: testing2/nginx
        source_port: 90
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```

**Results:** 
When creating the stack, it errors with
```
Error (Failed to find existing service: testing/nginx)
```

**Expected:**

Stack to come up with no issues as the service is in the same stack.

> **Note:** when using the same compose file, but removing the stack name, the services come up as expected.
