### ISSUE TITLE
Exporting load balancer service shows stack name in port rules for services in same stack

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6829]
**Rancher Version:**
1.2.0-rc1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a `nginx` service and then a load balancer targeting `nginx`. 
2. Export the yaml. 

**Results:** 
rancher-compose.yml
```
version: '2'
services:
  nginx:
    scale: 1
  lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: testing2/nginx
        source_port: 90
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate

```

The port rule contains the service name. If I export the stack and re-import, my load balancer will be pointing to the service in the original stack and not within my stack (like I would have expected). This is a behavioral change from the old LB use case. 

**Expected:**

I would expect the stack name to not be included as I am referencing a service in my own stack. 

Use case: I export the stack and re-import, I would expect the setup to have my LB point to the service within my same stack. 

rancher-compose.yml
```
version: '2'
services:
  nginx:
    scale: 1
  lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
#notice how there is no stack name
        service: nginx
        source_port: 90
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```
