### ISSUE TITLE
[rancher-dns] dns lookup slow and unstable

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#6843]
**Rancher Version: v1.1.4**
**Cattle Version: v0.165.8.4**
**Docker Version: 1.11.2**

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal, hetzner

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create redis rc and service.
Connect to any other container in same kubernetes cluster and same namespace. 
Run redis-benchmark  -c 10 -n 100000 -q -h gitlab-redis
 Result: Writing to socket: Connection timed out

Add ip of gitlab-redis to hosts file. 
redis-benchmark  -c 10 -n 100000 -q -h gitlab-redis                                                             
PING_INLINE: 99304.87 requests per second
PING_BULK: 100704.94 requests per second
SET: 86132.64 requests per second
...

```
apiVersion: v1
kind: Service
metadata: 
  labels:
    name: gitlab-redis
  name: gitlab-redis
  namespace: default 
spec: 
  ports:
  - name: gitlab-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: gitlab-redis 

apiVersion: v1
kind: Pod
metadata: 
  labels:
    name: gitlab-redis
  name: gitlab-redis 
  namespace: default 
spec:
  containers:
  - image: sameersbn/redis
    imagePullPolicy: Always
    name: gitlab-redis
    ports:
    - containerPort: 6379
      name: gitlab-redis
      protocol: TCP 
    image: sameersbn/redis 
```
**Results:** 
I get timeouts from the benchmark.

**Expected:**
No timeouts.
