### ISSUE TITLE
Running docker-compose up with Rancher load balancers

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6879]
Would it be possible to use the exported docker-compose.yml with load balancers from Rancher to run a stack locally using just `docker-compose up`? Currently the load balancer service dies upon start up.

```
 lb:
    image: rancher/lb-service-haproxy:v0.4.2
    expose:
    - 8080:8080/tcp
    - 8082:8082/tcp
    - 5432:5432/tcp
    - 27017:27017/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```
