### ISSUE TITLE
hostname/path/port from service's port_rules and not used for Load balancer targets.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6892]
Rancher Version: v1.2.0-rc4

Steps to reproduce the problem:

Create a service with following lb_config port_rules and with label test1=value1:

```
    port_rules = {
        "targetPort": "80",
        "hostname": "www.abc.com",
        "path": "name.html"}

```

Create an Lb service with selector links that resolve to the above created service by providing the following selector rule:
```
services:
  lb-testlink:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 2
        protocol: http
        selector: test1=value1
        source_port: 8082
        target_port: 8082
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

When Lb is created , hostname/path/port from service's port_rules and not used for Load balancer targets.

```
frontend 8082
bind *:8082
mode http
default_backend 8082_

backend 8082_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_prot
o
mode http
server 10.42.215.21 10.42.215.21:8082

```

**Comment by sangeethah** [comment]
When Lb service is created with selector rule by providing only source port , no frontend/backends get created on the haproxy config.

```
version: '2'
services:
  lb-testlink:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - priority: 2
        protocol: http
        selector: test1=value1
        source_port: 8082
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```

**Comment by sangeethah** [comment]
metadata for target services does not include lb_config detaisl. Following metadata call to fetch lb_config is empty -  ```http://rancher-metadata/latest/services/test73073/lb_config```

**Comment by sangeethah** [comment]
Tested the same use case with  rancher-server version - v1.2.1-rc1

lb service keeps restarting with the following exception seen in logs:

```
12/13/2016 1:31:46 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
12/13/2016 1:31:48 PMtime="2016-12-13T21:31:48Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
12/13/2016 1:31:48 PMtime="2016-12-13T21:31:48Z" level=info msg="Starting Rancher LB service"
12/13/2016 1:31:49 PMtime="2016-12-13T21:31:49Z" level=info msg="LB controller: rancher"
12/13/2016 1:31:49 PMtime="2016-12-13T21:31:49Z" level=info msg="LB provider: haproxy"
12/13/2016 1:31:49 PMtime="2016-12-13T21:31:49Z" level=info msg="starting rancher controller"
12/13/2016 1:31:49 PMtime="2016-12-13T21:31:49Z" level=info msg="Healthcheck handler is listening on :10241"
12/13/2016 1:31:49 PMpanic: runtime error: index out of range
12/13/2016 1:31:49 PM
12/13/2016 1:31:49 PMgoroutine 29 [running]:
12/13/2016 1:31:49 PMpanic(0x2203b00, 0xc820016050)
12/13/2016 1:31:49 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).BuildConfigFromMetadata(0xc82044b440, 0xc8200d8720, 0x14, 0xc8202b2960, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:201 +0x1f0e
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).GetLBConfigs(0xc82044b440, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:314 +0x1a4
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).sync(0xc82044b440, 0x2532460, 0x7)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:551 +0x93
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).(github.com/rancher/lb-controller/controller/rancher.sync)-fm(0x2532460, 0x7)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:539 +0x34
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc82042ee60)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8204c5f60)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8204c5f60, 0x3b9aca00, 0x0, 0x1, 0xc82044b3e0)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc8204c5f60, 0x3b9aca00, 0xc82044b3e0)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
12/13/2016 1:31:49 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc82042ee60, 0x3b9aca00, 0xc82044b3e0)
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
12/13/2016 1:31:49 PMcreated by github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run
12/13/2016 1:31:49 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
12/13/2016 1:31:56 PMtime="2016-12-13T21:31:56Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
12/13/2016 1:31:57 PMtime="2016-12-13T21:31:57Z" level=info msg="Starting Rancher LB service"
12/13/2016 1:31:57 PMtime="2016-12-13T21:31:57Z" level=info msg="LB controller: rancher"
12/13/2016 1:31:57 PMtime="2016-12-13T21:31:57Z" level=info msg="LB provider: haproxy"
12/13/2016 1:31:57 PMtime="2016-12-13T21:31:57Z" level=info msg="starting rancher controller"
12/13/2016 1:31:57 PMtime="2016-12-13T21:31:57Z" level=info msg="Healthcheck handler is listening on :10241"
12/13/2016 1:31:57 PMpanic: runtime error: index out of range
12/13/2016 1:31:57 PM
12/13/2016 1:31:57 PMgoroutine 29 [running]:
12/13/2016 1:31:57 PMpanic(0x2203b00, 0xc820016050)
12/13/2016 1:31:57 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).BuildConfigFromMetadata(0xc82044b440, 0xc8202e2f00, 0x14, 0xc8202b2960, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:201 +0x1f0e
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).GetLBConfigs(0xc82044b440, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:314 +0x1a4
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).sync(0xc82044b440, 0x2532460, 0x7)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:551 +0x93
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).(github.com/rancher/lb-controller/controller/rancher.sync)-fm(0x2532460, 0x7)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:539 +0x34
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc820430e20)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8204b7f60)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8204b7f60, 0x3b9aca00, 0x0, 0x1, 0xc82044b3e0)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc8204b7f60, 0x3b9aca00, 0xc82044b3e0)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
12/13/2016 1:31:57 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc820430e20, 0x3b9aca00, 0xc82044b3e0)
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
12/13/2016 1:31:57 PMcreated by github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run
12/13/2016 1:31:57 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
12/13/2016 1:32:01 PMtime="2016-12-13T21:32:01Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
12/13/2016 1:32:02 PMtime="2016-12-13T21:32:02Z" level=info msg="Starting Rancher LB service"
12/13/2016 1:32:02 PMtime="2016-12-13T21:32:02Z" level=info msg="LB controller: rancher"
12/13/2016 1:32:02 PMtime="2016-12-13T21:32:02Z" level=info msg="LB provider: haproxy"
12/13/2016 1:32:02 PMtime="2016-12-13T21:32:02Z" level=info msg="starting rancher controller"
12/13/2016 1:32:02 PMtime="2016-12-13T21:32:02Z" level=info msg="Healthcheck handler is listening on :10241"
12/13/2016 1:32:02 PMpanic: runtime error: index out of range
12/13/2016 1:32:02 PM
12/13/2016 1:32:02 PMgoroutine 29 [running]:
12/13/2016 1:32:02 PMpanic(0x2203b00, 0xc820016050)
12/13/2016 1:32:02 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).BuildConfigFromMetadata(0xc820449500, 0xc820661800, 0x14, 0xc8202b4a00, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:201 +0x1f0e
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).GetLBConfigs(0xc820449500, 0x0, 0x0, 0x0, 0x0, 0x0)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:314 +0x1a4
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).sync(0xc820449500, 0x2532460, 0x7)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:551 +0x93
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).(github.com/rancher/lb-controller/controller/rancher.sync)-fm(0x2532460, 0x7)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:539 +0x34
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc82042ee80)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc8201ddf60)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc8201ddf60, 0x3b9aca00, 0x0, 0x1, 0xc8204494a0)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc8201ddf60, 0x3b9aca00, 0xc8204494a0)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
12/13/2016 1:32:02 PMgithub.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc82042ee80, 0x3b9aca00, 0xc8204494a0)
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
12/13/2016 1:32:02 PMcreated by github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run
12/13/2016 1:32:02 PM	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
```

**Comment by sangeethah** [comment]
For service:
```
version: '2'
services:
  test526351:
    image: sangeetha/testnewhostrouting:latest
    labels:
      test1: value1
  test778818:
    image: sangeetha/testnewhostrouting:latest
    labels:
      test1: value1
```
```
version: '2'
services:
  test526351:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: www.abc.com
        path: name.html
        target_port: 80
  test778818:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: www.abc1.com
        path: service1.html
        target_port: 80
```

For lb:
```
version: '2'
services:
  lb-withselectorlinks:
    image: rancher/lb-service-haproxy:v0.4.5
    ports:
    - 20001:20001/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'

```
```
version: '2'
services:
  lb-withselectorlinks:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        selector: test1=value1
        source_port: 20001
      - protocol: http
        selector: test1=value1
        source_port: 20001
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

**Comment by sangeethah** [comment]
Tested the same use case with rancher-server version - v1.2.1-rc2.

hostname/path/port from service's port_rules are used for Load balancer targets as expected.

**Comment by martinbaillie** [comment]
Hi guys,

I'm playing around with an http lb as a global service and trying to use selectors to configure stack lb rules, but running into the same error.

I believe I'm up-to-date:
- Rancher version: v1.3.0
- Rancher LB version: v0.4.5

#### Test LB
##### docker-compose.yml
```yaml
version: '2'
services:
  test-lb:
    image: rancher/lb-service-haproxy:v0.4.5
    tty: true
    stdin_open: true
    ports:
      - 9000:9000
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

##### rancher-compose.yml
```yaml
version: '2'
services:
  test-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
       - selector: test-lb-stack.test-lb=test-endpoints
         source_port: 9000
         protocol: http
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```

#### Test Service

martinbaillie/fake-endpoint is a very simple scratch binary that listens on port 3000 serving endpoints from the command args, e.g. /argv1 /argv2 etc.

##### docker-compose.yml
```yaml
version: '2'
services:
  test-endpoints:
    image: martinbaillie/fake-endpoint
    tty: true
    stdin_open: true
    labels:
      test-lb-stack.test-lb: test-endpoints
```

##### rancher-compose.yml
```yaml
version: '2'
services:
  test-endpoints:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /foo
        target_port: 3000
```

#### Reproduction

1. deploy `test-lb-stack` first and have it sitting idle
2. deploy `test-endpoints-stack`
3. observe `test-lb-stack` transition to crash/red as test-endpoints-stack becomes ready/green

#### LB Container Errors

##### UI
test-lb (Failed to acquire lock [SERVICE.80])

##### LB Console
```
0/01/2017 10:33:55INFO[0000] Healthcheck handler is listening on :10241
10/01/2017 10:33:55panic: runtime error: index out of range
10/01/2017 10:33:55
10/01/2017 10:33:55goroutine 68 [running]:
10/01/2017 10:33:55panic(0x2203b00, 0xc820010030)
10/01/2017 10:33:55	/usr/local/go/src/runtime/panic.go:481 +0x3e6
10/01/2017 10:33:55github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).BuildConfigFromMetadata(0xc8203ba180, 0xc820548128, 0x7, 0xc820118be0, 0x0, 0x0, 0x0, 0x0, 0x0)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:201 +0x1f0e
10/01/2017 10:33:55github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).GetLBConfigs(0xc8203ba180, 0x0, 0x0, 0x0, 0x0, 0x0)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:314 +0x1a4
10/01/2017 10:33:55github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).sync(0xc8203ba180, 0x2532460, 0x7)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:551 +0x93
10/01/2017 10:33:55github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).(github.com/rancher/lb-controller/controller/rancher.sync)-fm(0x2532460, 0x7)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:539 +0x34
10/01/2017 10:33:55github.com/rancher/lb-controller/utils.(*TaskQueue).worker(0xc82045f520)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/utils/utils.go:64 +0x138
10/01/2017 10:33:55github.com/rancher/lb-controller/utils.(*TaskQueue).(github.com/rancher/lb-controller/utils.worker)-fm()
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x20
10/01/2017 10:33:55github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc82071bf60)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
10/01/2017 10:33:55github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc82071bf60, 0x3b9aca00, 0x0, 0x1, 0xc8203ba120)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
10/01/2017 10:33:55github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc82071bf60, 0x3b9aca00, 0xc8203ba120)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
10/01/2017 10:33:55github.com/rancher/lb-controller/utils.(*TaskQueue).Run(0xc82045f520, 0x3b9aca00, 0xc8203ba120)
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/utils/utils.go:33 +0x48
10/01/2017 10:33:55created by github.com/rancher/lb-controller/controller/rancher.(*loadBalancerController).Run
10/01/2017 10:33:55	/go/src/github.com/rancher/lb-controller/controller/rancher/rancher.go:105 +0x19c
```

**Comment by aemneina** [comment]
hey @martinbaillie I made a few modifcations to your yaml files... this should get make your example operational


Load balancer service definition:

```
version: '2'
services:
  test-lb:
    image: rancher/lb-service-haproxy:v0.4.5
    tty: true
    stdin_open: true
    ports:
      - 9000:9000
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

The only change here is the target port for the backend containers...
```
version: '2'
services:
  test-lb:
    start_on_create: true
    lb_config:
      port_rules:
       - selector: test-lb-stack.test-lb=test-endpoints
         source_port: 9000
         target_port: 80
         protocol: http
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```

Backend service definition
```
version: '2'
services:
  test-endpoints:
    image: sangeetha/testnewhostrouting
    tty: true
    stdin_open: true
    labels:
      test-lb-stack.test-lb: test-endpoints
```

I removed the path here. I'm going with the most simple configuration here, as the container doesnt deal with paths other than /

```
version: '2'
services:
  test-endpoints:
    scale: 1
    start_on_create: true
```
