### ISSUE TITLE
Compose doesn't replace variables in volumes section

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#6936]
Environment variables are not looked for and replaced in the `volumes` section of a v2 compose file.

**Comment by sangeethah** [comment]
Tested with rancher-compose-v0.12.1-rc2

Variable substitution works in volume section:

When the following yml was used , Variable substitution worked for driver and driver_options for volumes:

```
version: '2'
services:
  nginxtest:
    image: nginx
    volumes:
    - foo1:/tmp

volumes:
  foo1:
    driver: $driver
    external: false
    driver_opts: 
      test: $TEST_OPT
```
