### ISSUE TITLE
Environment Variables and External Links different behavior from 1.11.x

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#6996]
**Rancher Version:**
v1.12
Rancher Compose: v0.12.0

**Docker Version:**
v1.12.3
Docker Compose: v1.9.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
boot2docker, local vm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher; same host for rancher and user containers

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Deploy service with external variables and uses an external service using Rancher Compose...like:

```
db-client:
equipment-query:
    ports:
    - 8080
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.container.hostname_override: container_name
    external_links:
    - foo/mongo:mongo
    environment:
      MONGO_PORT: '27017'
```

**Results:** 

MONGO_PORT variable set to "tcp://mongo:27017"

**Expected:**

MONGO_PORT variable set to "27017" (as in Rancher 1.11.x)

**Notes:**

I used both Docker Compose file versions 1 and 2 and got same result.  For version, I was expect the issue to be solved as the environment variables for links are no longer supposed to be populated (https://docs.docker.com/compose/link-env-deprecated/)...what gives?
