### ISSUE TITLE
Could not create stack with Load Balancer

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#7032]
**Rancher Version:** 1.2

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Create stack (a71 in my case) via docker and rancher composes with service and load balancer configured to serve this service

**Results:** 
 Error (Failed to find existing service: a71/mongo)

**Expected:**
Stack successfully created

*docker-compose.yml*
```yml
api:
  environment: {COMMIT_HASH: 147e1006029a584c7df932ff4c8dfeebf407108c, DB_MONGO_DB: dddb,
    DB_MONGO_HOST: mongo, DB_MONGO_PASSWORD: '123456', DB_MONGO_PORT: '27017',
    DB_MONGO_USER: user, DB_POSTGRES_DB: dddb, DB_POSTGRES_HOST: postgres, DB_POSTGRES_PASSWORD: '123456',
    DB_POSTGRES_PORT: '5432', DB_POSTGRES_USER: postres, GIT_BRANCH: master}
  external_links: ['postgres/postgres:postgres']
  image: docker-registry:5000/api
  labels: {io.rancher.container.pull_image: always, 'io.rancher.scheduler.affinity:host_label': purpose=ci}
  links: ['mongo:']
  log_driver: ''
  log_opt: {}
  stdin_open: true
  tty: true
mongo:
  environment: {DB_MONGO_PORT: '27017'}
  image: docker-registry:5000/mongo
  labels: {io.rancher.container.pull_image: always}
  log_driver: ''
  log_opt: {}
  stdin_open: true
  tty: true
mongo-balancer:
  image: rancher/lb-service-haproxy:v0.4.2
  labels: {io.rancher.container.agent.role: environmentAdmin, io.rancher.container.create_agent: 'true',
    'io.rancher.scheduler.affinity:host_label': balancer=true}
  ports: ['60000:60000/tcp']
site:
  environment: {API_URL: 'http://api.XXX', CLOUD_STORAGE_URL: 'http://api.XXX/resources'}
  image: docker-registry:5000/site
  labels: {io.rancher.container.pull_image: always, 'io.rancher.scheduler.affinity:host_label': purpose=ci}
  links: ['api:']
  log_driver: ''
  log_opt: {}
  stdin_open: true
  tty: true
```

*rancher-compose.yml*
```yml
api:
  health_check: {healthy_threshold: 2, initializing_timeout: 360000, interval: 2000,
    port: 5099, response_timeout: 5000, strategy: none, unhealthy_threshold: 3}
  scale: 1
mongo: {scale: 1}
mongo-balancer:
  health_check: {healthy_threshold: 2, interval: 2000, port: 42, response_timeout: 2000,
    unhealthy_threshold: 3}
  lb_config:
    certs: []
    config: timeout tunnel        15m
    port_rules:
    - {priority: '1', protocol: tcp, service: a71/mongo, source_port: '60000', target_port: '27017'}
  scale: 1
site:
  health_check: {healthy_threshold: 2, initializing_timeout: 360000, interval: 2000,
    port: 3000, request_line: GET "/healthcheck" "HTTP/1.0", response_timeout: 2000,
    strategy: recreate, unhealthy_threshold: 10}
  scale: 1
```

It seems load balancer should not try to resolve targets until all other services created. Or it should be more smart check strategy. And I believe it possible, because all necessary information given to rancher.

And you can see what all services are up, but balancer not created
![image](https://cloud.githubusercontent.com/assets/1079535/21151670/ea9a480c-c195-11e6-9476-fcd9ab1881e8.png)
