### ISSUE TITLE
Rancher server starts new kubernetes-ingress-lb instance, for each ingress resource being added.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#7054]
**Rancher Version:**
Server v1.2.0 Agent v1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu14.04 VMware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with two hosts
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kuberenetes
**Steps to Reproduce:**
Create few namespaces. For example: test1, test2, test3
Add ingress resource to each namespace like this one:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-name
spec:
  rules:
  - host: ${HOSTNAME}
    http:
      paths:
      - path: /ws
        backend:
          serviceName: ws
          servicePort: 7000
      - path: /store
        backend:
          serviceName: store
          servicePort: 6000
      - backend:
          serviceName: front
          servicePort: 8080
```
**Results:** 
Rancher will start new kubernetes-ingress-lb instance for each Ingress resource being added.
Each of my hosts ended running instance of kubernetes-ingress-lb. Then i tried to add ingress resource to third name space i end up with this error:
```
 (Failed to allocate instance [container:1i629]: Bad instance [container:1i629] in state [error]: Scheduling failed: host needs ports 80/tcp available)
```
**Expected:**
I expect from rancher to update configuration of exiting kubernetes-ingress-lb instances and not start new one. Like [Nginx Ingress Controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx) for example.
