### ISSUE TITLE
Log driver in docker-compose not added to service in environment.

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#7056]
**Rancher Version:**
1.2.0-1

**Docker Version:**
1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher external Galera DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Deploy the service below ( Removed image etc )
```
version: "2"
services:
  myapp:
    image: "...."
    ports:
      - "8181"
    environment:
      - SERVICE_8181_NAME=myapp
    restart: unless-stopped
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:1330"
        tag: "myapp/{{.Name}}"
    labels:
      io.rancher.container.hostname_override: container_name
```

I've also tried docker-compose v1 but it didn't work either.
I deploy the service with Rancher-compose 0.12.0.
The logging in docker-compose v1 worked before we upgraded to Rancher 1.2.0-1 from 1.1.3

**Results:** 
Logging is still sent to stdout and can be viewed in Rancher UI and when I look in the config view I can't see anything about logging in the docker-compose.yml

**Expected:**
That syslog driver is added and used for the service.
