### ISSUE TITLE
Validate new features supported in kubernetes version 1.5

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7069]

**Comment by galal-hussein** [comment]
- [x]  Beta support for the OpenAPI spec, and tested the first [non-go client](https://github.com/kubernetes-incubator/client-python) that based on it.

**Comment by galal-hussein** [comment]
- [x] Report underlying reason about failed deployments/RS via the API

Was able to verify using a failed deployment and to see the reason:

```
$ kubectl describe deployments                
Name:			nginx-deployment
Namespace:		default
CreationTimestamp:	Mon, 09 Jan 2017 21:38:06 +0200
Labels:			app=nginx
Selector:		app=nginx
Replicas:		3 updated | 3 total | 0 available | 3 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	False	MinimumReplicasUnavailable
  Progressing 	False	ProgressDeadlineExceeded
```

```
$ kubectl rollout status deployment/nginx-deployment
error: deployment "nginx-deployment" exceeded its progress deadline
```

**Comment by galal-hussein** [comment]
- [x] Kubectl apply is now able to delete resources you no longer need with --prune

Was able to validate this feature using remote and UI kubectl client.

**Comment by galal-hussein** [comment]
- [x] StatefulSets, steps to validate:

- Spin up 3 hosts on AWS with role that enable them access on EBS volumes
- Install kubernetes with AWS as a provider
- Create storage class for AWS:
```
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1d
``` 
- run the following Statefulset manifest:
```
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
