### ISSUE TITLE
Not able to start service with the generated config of a service with host mount points.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7070]
Steps to reproduce the problem:
Create a service with host mount point as follows:

```
"dataVolumes": [
"/test/container:/test/vol1:ro"
],
```
Service starts up successfully.

Not able to use the exported config for this service . Following error is seen -
``Volume /test/container declared as external, but could not be found. Please create the volume manually and try again.```

docker-compose.yml generated for this service:

```
version: '2'
volumes:
  /test/container:
    external: true
    driver: 'null'
services:
  test914757:
    image: ibuildthecloud/helloworld:latest
    cap_drop:
    - KILL
    stdin_open: true
    volumes:
    - /test/container:/test/vol1:ro
    dns:
    - 1.2.3.4
    domainname: rancher.io
    cpuset: '0'
    command:
    - sleep
    - '9000'
    labels:
      io.rancher.scheduler.affinity:container_label: c1=vol
    privileged: true
    mem_limit: 8000000
    cap_add:
    - CHOWN
    hostname: test
    environment:
      TEST_FILE: /etc/testpath.conf
    dns_search:
    - 1.2.3.4
    tty: true
    user: root
    cpu_shares: 400
```

**Comment by sangeethah** [comment]
Tested with v1.2.1-rc3

When service is created with host mounts, generated config does not use v2 volume format for it.
```
"dataVolumes": [
"/test/container:/test/vol1:ro"
]
```
Able to start service successfully with this generated config.
```
version: '2'
services:
  test345829:
    image: ibuildthecloud/helloworld:latest
    cap_drop:
    - KILL
    stdin_open: true
    volumes:
    - /test/container:/test/vol1:ro
    dns:
    - 1.2.3.4
    domainname: rancher.io
    cpuset: '0'
    command:
    - sleep
    - '9000'
    labels:
      io.rancher.scheduler.affinity:container_label: c1=vol
    privileged: true
    mem_limit: 8000000
    cap_add:
    - CHOWN
    hostname: test
    environment:
      TEST_FILE: /etc/testpath.conf
    dns_search:
    - 1.2.3.4
    tty: true
    user: root
    cpu_shares: 400
```
