### ISSUE TITLE
[rancher-compose] Don't pass empty question responses to docker-compose as variables

### ISSUE THREAD

**Issue by InAnimaTe** [rancher/rancher#7074]
This request relates to the awesome racher-compose handling of questions for catalog entries. Right now, you define your variables in the `docker-compose.yml` file like:

```
    environment:
      ROUTER: ${ROUTER}
      PASSWORD: ${PASSWORD}
```

and then in your `rancher-compose.yml`:

```
  questions:
    - variable: ROUTER
      required: true
      default: route-me-yay
      type: string
    - variable: PASSWORD
      required: false
      type: string
```

If you were to keep the password field blank, a variable in your container environment of `PASSWORD=` would exist. If your application is a python program which already has a default password, for instance in your `settings.py` (while utilizing `os.environ` to pull in any environment variables), you would effectively be clearing the actual program default, which should not happen (or at least be configurable).

With the current setup, users have to maintain defaults in two places, including ensuring documentation is up to date etc.. I think providing a configurable option saying "only pass non-empty" question variables needs to be implemented.

PS: If there is already a way to do this, please let me know. I didn't see anything in the docs or other examples.
