### ISSUE TITLE
rancher-compose replaces environment variables instead of merging them

### ISSUE THREAD

**Issue by mathuin** [rancher/rancher#7100]
**Rancher Version:** 1.2.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** CoreOS at DO

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node Rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a `docker-compose.yml` file with the following content:
```
version: '2'
services:
  test:
    image: busybox
    environment:
      VAR1: 'hello'
      VAR2: 'world'
```

2.  Create a `docker-compose.override.yml` file with the following content:
```
version: '2'
services:
  test:
    environment:
      VAR1: 'goodbye'
```

3.  Create a zero-byte `rancher-compose.yml` file.

4. Run `rancher-compose create` with the appropriate environment variables pointing to a Rancher server.

**Results:** 

Look at the stack config, specifically the `docker-compose.yml` portion.  You will see output not unlike this:
```
version: '2'
services:
  test:
    image: busybox
    environment:
      VAR1: goodbye
```

**Expected:**

I expected something closer to the output of `docker-compose config`, shown below.

```
networks: {}
services:
  test:
    environment:
      VAR1: goodbye
      VAR2: world
    image: busybox
version: '2.0'
volumes: {}
```

https://docs.docker.com/compose/extends/#/adding-and-overriding-configuration describes the behavior of `docker-compose` in this area.  It is reasonable to expect `rancher-compose` to work this way.
