### ISSUE TITLE
Docker-compose goes corrupted after creating a Cattle Stack

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#7161]
1.2.1

After creating a stack with rancher-nfs the Docker-Compose.yaml file is in wrong order, and can't be used to recreate that stack.

Original dockercompose.yml file:

```
version: '2'
services:
  Jira-DB:
    image: postgres:9.5.4
    environment:
      PGDATA: /var/lib/postgresql/data/jira-data
      POSTGRES_DB: jira
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - ${db_volume}:/var/lib/postgresql/data/jira-data
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
  Jira-Server:
    image: cptactionhank/atlassian-jira-software:latest
    environment:
      X_PROXY_NAME: ${domain_name}
      X_PROXY_PORT: '443'
      X_PROXY_SCHEME: https
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - ${data_volume}:/var/atlassian/jira
    tty: true
    links:
    - Jira-DB:postgres
    ports:
    - ${public_port}:8080/tcp
    labels:
      io.rancher.container.pull_image: always
```

Docker-Compose from view config:

`version: '2'
**volumes:
  Jira-Progress-test:
    external: true
    driver: rancher-nfs
  Jiratest-data:
    external: true
    driver: rancher-nfs**
services:
  Jira-DB:
    image: postgres:9.5.4
    environment:
      PGDATA: /var/lib/postgresql/data/jira-data
      POSTGRES_DB: jira
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    stdin_open: true
    volumes:
    - Jira-Progress-test:/var/lib/postgresql/data/jira-data
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
  Jira-Server:
    image: cptactionhank/atlassian-jira-software:latest
    environment:
      X_PROXY_NAME: jiratest.pax.ch
      X_PROXY_PORT: '443'
      X_PROXY_SCHEME: https
    stdin_open: true
    volumes:
    - Jiratest-data:/var/atlassian/jira
    tty: true
    links:
    - Jira-DB:postgres
    ports:
    - 8099:8080/tcp
    labels:
      io.rancher.container.pull_image: always`
