### ISSUE TITLE
LB ingress are not functional since no target instances are programmed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7183]
Rancher Version:v1.2.2-rc2

Steps to reproduce the problem:

Create services and ingress withe following yml files:

```
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat ingress_1.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress1
 annotations:
   http.port: "83"
spec:
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /service3.html
       backend:
         serviceName: k8test1
         servicePort: 81
     - path: /name.html
       backend:
         serviceName: k8test2
         servicePort: 80
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat service1_ingress.yml
apiVersion: v1
kind: Service
metadata:
 name: k8test1
 labels:
   k8s-app: k8test1-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test1-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc1
spec:
 replicas: 2
 selector:
   k8s-app: k8test1-service
 template:
   metadata:
     labels:
       k8s-app: k8test1-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ cat service2_ingress.yml
apiVersion: v1
kind: Service
metadata:
 name: k8test2
 labels:
   k8s-app: k8test2-service
spec:
 ports:
 - port: 80
   targetPort: 80
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test2-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc2
spec:
 replicas: 2
 selector:
   k8s-app: k8test2-service
 template:
   metadata:
     labels:
       k8s-app: k8test2-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 80
Sangeethas-MacBook-Pro:k8s sangeethahariharan1$ 
```

When ingress is created , there are no target instances programmed for any of the backends.

When accessing LB with correct host headers and path names , we get "503 service Unavaiable"
