### ISSUE TITLE
Helm operations stuck on Rancher self signed certificate kubernetes setup

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7234]
**Rancher Version:**
v1.3.0-rc2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes rancher/k8s:v1.5.1-rancher1-7
**Steps to Reproduce:**
- Install Rancher server with self signed certificate ssl
- Run kubernetes v1.5.1
- Navigate to kubectl tab and try to use helm operations like:
`helm ls`
`helm install stable/nginx`

**Results:** 
The helm commands hung forever without any results, tiller is not generating any errors.

**Comment by wlan0** [comment]
nginx proxy (that we use for ssl termination) does not support http/ 2.0, and helm client uses this to create a grpc connection to helm server. @cloudnautique and @LLParse can we look into using a TCP proxy instead of HTTPS proxy.

**Comment by wlan0** [comment]
@galal-hussein Can you test this with nginx-1.9.5 and check if it works pls?

**Comment by deniseschannon** [comment]
@galal-hussein I've assigned to you. Please reassign to sid if it's still broken.

**Comment by wlan0** [comment]
@deniseschannon I've confirmed that its not fixed yet. I'm working on it. Going to re-assign it to myself.

**Comment by galal-hussein** [comment]
Rancher version: v1.3.3
kubernetes version: rancher/k8s:v1.5.1-rancher1-7

steps to test:

- Start rancher server with self signed cerificate:
`docker run -d -p 8080:8080 -v /path/to/self/signed/cert:/var/lib/rancher/etc/ssl/ca.crt rancher/server:v1.3.3`
- Install nginx and add the following configuration:
```
upstream rancher {
    server 127.0.0.1:8080;
}

server {
    listen 443 ssl spdy;
    server_name example;
    ssl_certificate <path-to-ssl-crt>;
    ssl_certificate_key <path-to-ssl-key>;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name example;
    return 301 https://$server_name$request_uri;
}
```
- Register few agents with Rancher server
- Install kubernetes stack
- Copy the kubectl configuration to the remote client:
```
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: "https://xxxx/r/projects/1a5/kubernetes"
    certificate-authority-data: "<certificate-here>"
    insecure-skip-tls-verify: false
  name: "Default"
contexts:
- context:
    cluster: "Default"
    user: "Default"
  name: "Default"
current-context: "Default"
users:
- name: "Default"
  user:
    username: "xxxx"
    password: "xxxxx"
```
- Run helm operation like install/delete/ls...

Helm is working without problems.
