### ISSUE TITLE
Creating an LB with an empty port mapping causes UI to crash

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7238]
**Rancher Version:**
1.2.2

When launching an LB service with a simple configuration, the UI "upgrade" screen crashes because there are no port rules defined.

```
# rancher-compose.yml
version: '2'
services:
  haproxy:
    lb_config:
      certs: []
      port_rules: []
```
