### ISSUE TITLE
Rancher service rollback after failed upgrade initiates another upgrade with container recreation loop

### ISSUE THREAD

**Issue by larsrya8** [rancher/rancher#7242]
**Rancher Version:**

```
Rancher: v1.2.2
Cattle: v0.174.13
UI: v1.2.40
```

**Docker Version:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-59.el7.centos.x86_64
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```

**OS and where are the hosts located? (cloud, bare metal, etc):**

CentOS 7 VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node master, internal DB.  Two Docker nodes for scheduling containers.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1. Create a stack scheduled to run on multiple hosts with the following docker-compose.yml and rancher-compose.yml:

docker-compose.yml
```
version: '2'
services:
  top:
    image: centos:7
    command: top
    environment:
    - TERM=xterm-256color
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    network_mode: bridge
    tty: true
```
rancher-compose.yml
```
version: '2'
services:
  top:
    start_on_create: true
```

2. Wait for "top" service to become Active

3. Click "Upgrade" button for "top", change Command to "topp" (to simulate a container that fails to start), and initiate upgrade

4. Wait for upgrade to fail

5. Click "Rollback" button

6. Wait for service to rollback

**Results:** 

Within a minute after the rollback completes, Rancher changes state back to "Upgrading" and continually recreates the container running "top".  Click "Rollback" again resolves the issue.

If the service was scheduled on only a single node, then the container is recreated just once, and I'm asked to "Finish Upgrade".

**Expected:**

Rancher does not initiate an upgrade with the "rolled back" configuration or recreate containers after a rollback, continually or just once.

I'm able to reproduce this behavior with the Rancher UI, rancher-compose, and the Rancher CLI.

Please let me know if there's any more information I can provide.
