### ISSUE TITLE
Convert v1 selector based LB to v2

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7269]
If selector is defined on LB service level in v1, it should be transformed to the selector on the port rule in v2. 

@deniseschannon we've decided to fix it on the rancher compose side

**Comment by lukewhiting** [comment]
This is currently malfunctioning on Rancher 1.2.2 (Compose v0.12.1).

When running `rancer-compose up` on a Docker compose file written from Rancher <1.2 it partially converts the label based LB targets to the newer load balancer but incorrectly sets them to type TCP so the path is ignored causing apps that rely on path routing to fail.

It seems the paths are being read and set. For example an old style LB with a label of `    io.rancher.loadbalancer.target.twitter-profile-service: /twitter=8082` created an entry in the new LB config screen targeting twitter-profile-service on port 8082 and once you change the type from TCP to HTTP the path shows correctly in the UI.

Currently for operational reasons we must keep backwards compatibility in our docker-compose & rancher-compose files so this is unfortunately blocking us from upgrading to 1.2.

If you need any more info please don't hesitate to ask.

**Comment by lukewhiting** [comment]
@joshwget Sure thing

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.4.0-rc3
Created a stack with following yml where Lb is v1 selector based .
```
lb-1:
  ports:
  - 4001:80
  labels:
    io.rancher.service.selector.link: test2=bar
  image: rancher/load-balancer-service
test-752736:
  labels:
    test2: bar
  image: sangeetha/testlbsd:latest
test-479268:
  labels:
    test2: bar
  image: sangeetha/testlbsd:latest
```
```
lb-1:
  scale: 1
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

When Lb gets created with selector based Port Rule as expected.
Lb is functional and directs traffic to all the containers that have the specified label.
<img width="1169" alt="screen shot 2017-01-27 at 6 40 05 pm" src="https://cloud.githubusercontent.com/assets/4266958/22393675/33206050-e4c0-11e6-8986-9f141d2a7cfc.png">
