### ISSUE TITLE
Conversion of path based V1 load balancers in docker-compose.yaml to V2 fails

### ISSUE THREAD

**Issue by lukewhiting** [rancher/rancher#7301]
When running rancer-compose up on a Docker compose file written from Rancher <1.2 it partially converts the label based LB targets to the newer load balancer but incorrectly sets them to type TCP so the path is ignored causing apps that rely on path routing to fail.

It seems the paths are being read and set. For example an old style LB with a label of `io.rancher.loadbalancer.target.twitter-profile-service: /twitter=8082` created an entry in the new LB config screen targeting twitter-profile-service on port 8082 and once you change the type from TCP to HTTP the path shows correctly in the UI.

Currently for operational reasons we must keep backwards compatibility in our docker-compose & rancher-compose files so this is unfortunately blocking us from upgrading to 1.2.

If you need any more info please don't hesitate to ask.

---

Rancher Version: 1.2.2

Docker Version: 1.10.3

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 16.04.1 LTS on AWS

Setup Details (single node rancher vs. HA rancher, internal DB vs. external DB): Single node External DB (MySQL Via RDS)

Environment Type (Cattle/Kubernetes/Swarm/Mesos): Cattle

**Comment by lukewhiting** [comment]
Sure. Here you go:

```
audiences-rest-api:
  expose:
    - 80:80
  labels:
    io.rancher.loadbalancer.target.geolocation-service: /locations=8081
    io.rancher.loadbalancer.target.twitter-profile-service: /twitter=8082
    io.rancher.loadbalancer.target.segmentation-service: /segment=9101
    io.rancher.loadbalancer.target.thing-service: /things=8080,/otherthings=8080,/projects=8080,/users=8080,/morethings=8080,/authentication=8080,/content=8080
    io.rancher.loadbalancer.target.thing-rest-api-service: /api/v1=8087
    io.rancher.loadbalancer.target.favicon-service: /icon=8080,/lettericons=8080
    io.rancher.scheduler.affinity:host_label_ne: vpn=true
  tty: true
  image: rancher/load-balancer-service
  links:
    - thing-service:thing-service
    - twitter-profile-service:twitter-profile-service
    - geolocation-service:geolocation-service
    - thing-rest-api-service:thing-rest-api-service
    - segmentation-service:segmentation-service-server
    - favicon-service:favicon-service
  stdin_open: true
  log_driver: json-file
  log_opt:
    max-size: 1g
```

**Comment by deniseschannon** [comment]
What version of rancher-compose are you using? 

By using `expose`, you aren't exposing any ports to the host. Are you intentionally making this an internal load balancer? If not, you should be using `ports` instead of `expose` to have the ports exposed on the host. 

I tested with the following compose file with Rancher 1.2.2 and 1.3, which uses Rancher-Compose v0.12.1. The only difference is the image tag for the LB. 

```
audiences-rest-api:
  expose:
    - 80:80
  labels:
    io.rancher.loadbalancer.target.twitter-profile-service: /twitter=8082
    io.rancher.scheduler.affinity:host_label_ne: vpn=true
  tty: true
  image: rancher/load-balancer-service
  links:
    - twitter-profile-service:twitter-profile-service
  stdin_open: true
  log_driver: json-file
  log_opt:
    max-size: 1g
twitter-profile-service:
  image: nginx
```

And it converted the path correctly. In the UI, I see:
<img width="837" alt="screen shot 2017-01-05 at 7 32 54 am" src="https://cloud.githubusercontent.com/assets/11410997/21686148/36304bf6-d319-11e6-951a-ce681043ac27.png">

And the new docker-compose/rancher-compose files show that the protocol is using `http`. 

docker-compose.yml
```
version: '2'
services:
  twitter-profile-service:
    image: nginx
  audiences-rest-api:
    image: rancher/lb-service-haproxy:v0.4.9
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 1g
    links:
    - twitter-profile-service:twitter-profile-service
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label_ne: vpn=true
```

rancher-compose.yml
```
version: '2'
services:
  twitter-profile-service:
    scale: 1
    start_on_create: true
  audiences-rest-api:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /twitter
        protocol: http
        service: twitter-profile-service
        source_port: 80
        target_port: 8082
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

**Comment by lukewhiting** [comment]
> What version of rancher-compose are you using?

V0.12.1

> Are you intentionally making this an internal load balancer?

Yes that's correct. This LB is used to collate several microservices that our used by our frontend.

> I tested with the following compose file with Rancher 1.2.2 and 1.3, which uses Rancher-Compose v0.12.1. The only difference is the image tag for the LB.

In our config we also have multiple paths on a single label (See thing-service). Might that cause this?

Also if it makes any difference we are running on a brand new, fresh install of 1.2.2 with a clean DB.

**Comment by deniseschannon** [comment]
Even with multiple paths, I still see http. 

I put in
```
audiences-rest-api:
  expose:
    - 80:80
  labels:
    io.rancher.loadbalancer.target.geolocation-service: /locations=8081
    io.rancher.loadbalancer.target.twitter-profile-service: /twitter=8082
    io.rancher.loadbalancer.target.segmentation-service: /segment=9101
    io.rancher.loadbalancer.target.thing-service: /things=8080,/otherthings=8080,/projects=8080,/users=8080,/morethings=8080,/authentication=8080,/content=8080
    io.rancher.loadbalancer.target.thing-rest-api-service: /api/v1=8087
    io.rancher.loadbalancer.target.favicon-service: /icon=8080,/lettericons=8080
    io.rancher.scheduler.affinity:host_label_ne: vpn=true
  tty: true
  image: rancher/load-balancer-service
  links:
    - thing-service:thing-service
    - twitter-profile-service:twitter-profile-service
    - geolocation-service:geolocation-service
    - thing-rest-api-service:thing-rest-api-service
    - segmentation-service:segmentation-service-server
    - favicon-service:favicon-service
  stdin_open: true
  log_driver: json-file
  log_opt:
    max-size: 1g
thing-service:
  image: nginx
twitter-profile-service:
  image: nginx
geolocation-service:
  image: nginx
thing-rest-api-service:
  image: nginx
segmentation-service:
  image: nginx
favicon-service:
  image: nginx
```

All of them are showing up with `http` in the UI. 

Can you send me a screenshot of where you are seeing `tcp`?
