### ISSUE TITLE
ports for services are being swapped

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7326]
**Rancher Versions:**
Server: 1.2.2
healthcheck: v0.2.0
ipsec: v0.0.2
network-services: v0.0.8
scheduler: v0.2.0

**Docker Version:**
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 / AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deployed 2 load balancers as services with different port mappings. The ports are getting swapped when services are deployed.

**Expected:**
ports mapped correctly to corresponding services

docker-compose.yml
```
version: '2'
services:
  haproxy-primary:
    image: rancher/lb-service-haproxy:v0.4.6
    ports:
    - 443:443/tcp
    labels:
      primary_lb: true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'

  haproxy-secondary:
    image: rancher/lb-service-haproxy:v0.4.6
    ports:
    - 443:9000/tcp
    labels:
      include_in_primary_lb: true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

rancher-compose.yml
```
version: '2'
services:
  haproxy-primary:
    # launched on 10.42.5.243
    lb_config:
      port_rules:
        # forward TCP traffic from public port 443 to port 443 on the secondary
        # but actually results in an haproxy config wtih the following backend rule:
        #
        # backend lb_primary
        #    server 10.42.X.X 10.42.X.X:9000  check port 443 inter 1000 rise 2 fall 1
        #
      - protocol: tcp
        source_port: 443
        target_port: 443
        selector: include_in_primary_lb=true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000

  haproxy-secondary:
    # launched on 10.42.24.18
    lb_config:
      default_cert: user.example.com
      port_rules:
        # proxy https://HOST/lb/primary to haproxy-primary:9000  (via selector)
        # but actually results in an haproxy config wtih the following backend rule:
        #
        # backend 443_
        #  server 10.42.X.X 10.42.X.X:443  check port 42 inter 2000 rise 2 fall 3
        #
      - backend_name: lb_primary
        hostname: 
        path: /lb/primary
        protocol: https
        # service: lb-test/primary-haproxy
        selector: primary_lb=true
        source_port: 443
        target_port: 9000

    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 443
      unhealthy_threshold: 1
      interval: 1000
```
