### ISSUE TITLE
Not able to start services with stack scoped volumes in rancher-nfs

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7334]
Rancher Versions: Build from master

Environment - cattle with rancher-nfs - rancher/storage-nfs:v0.6.0
Create a stack using the following yml:
```
version: '2'
services:
  nginx3:
    image: nginx
    volumes:
    - foo3:/tmp

volumes:
  foo3:
    driver: rancher-nfs
    external: false
``` 
Sangeethas-MacBook-Pro:rancher-compose-v0.12.1 sangeethahariharan1$ ./rancher-compose -p new1 -f test1.yml up
INFO[0000] Creating volume template foo3                
INFO[0000] [0/1] [nginx3]: Creating                     
INFO[0000] Creating service nginx3                      
INFO[0000] [0/1] [nginx3]: Created                      
INFO[0000] Existing volume template found for foo3      
INFO[0000] [0/1] [nginx3]: Starting                     
INFO[0005] [1/1] [nginx3]: Started                      
ERRO[0006] Failed to get logs for new1-nginx3-1: Failed to find action: logs 

Stack scoped Volume gets created - ```new1_foo3_82c63``` but it in "Dactched" state.
Containers fail to start with the following  exception:
``` Activating (Expected state running but got error: Error response from daemon: chown /var/lib/rancher/volumes/rancher-nfs/new1_foo_3e06f: operation not permitted```
