### ISSUE TITLE
Unable to stop a stack

### ISSUE THREAD

**Issue by pierredavidbelanger** [rancher/rancher#7396]
**Rancher Versions:**
Server: `rancher/server:stable` I see `v1.2.2` in the UI
healthcheck: `rancher/healthcheck:v0.2.0`
ipsec: `rancher/net:holder`
network-services: `rancher/metadata:v0.7.0` and `rancher/network-manager:v0.4.0`
scheduler: `rancher/scheduler:v0.5.0`

**Docker Version:**

On the host where the server is:

```sh
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**OS and where are the hosts located? (cloud, bare metal, etc):**

The RancherOS AMI on AWS

```sh
$ uname -a
Linux ip-*whatever*.us-east-2.compute.internal 4.4.24-rancher #1 SMP Fri Nov 11 03:20:22 UTC 2016 x86_64 GNU/Linux
```

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

The server cloud config:

```yaml
#cloud-config
write_files:
  - path: /mnt/efs/this_is_just_to_make_the_dir.txt
    owner: root:root
    permissions: "0644"
mounts:
  - ["fs-*whatever*.efs.us-east-2.amazonaws.com:/", "/mnt/efs", "nfs4", "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"]
rancher:
  services:
    rancher-server:
      image: rancher/server:stable
      restart: unless-stopped
      ports:
        - 8080:8080
      volumes:
        - /mnt/efs/rancher-server/var/lib/mysql:/var/lib/mysql
```

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

```
Rancher	v1.2.2
Cattle	v0.174.13
User Interface	v1.2.40
Rancher Compose	v0.12.1
```

**Steps to Reproduce:**

Create a stack in the UI with this docker-compose file (that uses an invalid image):

```yaml
version: '2'
services:
  hello:
    image: nouser/invalidimage
    labels:
      io.rancher.scheduler.global: true
    ports:
      - '80:80'
```

Try to stop the service from always retrying to start without deleting the stack.

**Results:** 

No matter what, you will see this sequence repeated in loop:

![rancher](https://cloud.githubusercontent.com/assets/1076726/21898250/3f1b5570-d8ba-11e6-8c63-0b04e9cd93e6.png)

**Expected:**

Being able to stop this unhealty stack ,  have some time to fix the issue, and start it again.
