### ISSUE TITLE
"Process delayed" message on a upgrade rollback 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7431]
**Rancher Versions:**
Server:v1.4.0-rc2

**Docker Version:**v1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Signlenode

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack with services/sidekicks using the docker-compose file below:
```
sk2:
  restart: always
  tty: true
  image: sangeetha/testnewhostrouting
  stdin_open: true
  labels:
    testsk2: value1
sk1:
  restart: always
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true
  labels:
    testsk1: value1
test1:
  restart: always
  labels:
    io.rancher.sidekicks: sk1,sk2
    test1: value1
  tty: true
  image: sangeetha/testlbsd
  stdin_open: true

```
2. Upgrade and rollback
3. The rollback is delayed with the message below:

<img width="1357" alt="screen shot 2017-01-16 at 11 15 06 am" src="https://cloud.githubusercontent.com/assets/18536626/21995857/0652b0ec-dbdc-11e6-92e9-f658781ab984.png">

The rollback is delayed for around 3 minutes and completes eventually
