### ISSUE TITLE
Cant start vault in rancher

### ISSUE THREAD

**Issue by boskiv** [rancher/rancher#7459]
Starting vault failed
```
18.01.2017 14:19:46Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK
18.01.2017 14:19:46error: exec failed: text file busy
18.01.2017 14:19:48Vault v0.6.4 ('f4adc7fa960ed8e828f94bc6785bcdbae8d1b263')
18.01.2017 14:19:48At least one config path must be specified with -config
18.01.2017 14:19:48Usage: vault server [options]
18.01.2017 14:19:48
18.01.2017 14:19:48  Start a Vault server.
18.01.2017 14:19:48
18.01.2017 14:19:48  This command starts a Vault server that responds to API requests.
18.01.2017 14:19:48  Vault will start in a "sealed" state. The Vault must be unsealed
18.01.2017 14:19:48  with "vault unseal" or the API before this server can respond to requests.
18.01.2017 14:19:48  This must be done for every server.
18.01.2017 14:19:48
18.01.2017 14:19:48  If the server is being started against a storage backend that has
18.01.2017 14:19:48  brand new (no existing Vault data in it), it must be initialized with
18.01.2017 14:19:48  "vault init" or the API first.
18.01.2017 14:19:48
18.01.2017 14:19:48
18.01.2017 14:19:48General Options:
18.01.2017 14:19:48
18.01.2017 14:19:48  -config=<path>          Path to the configuration file or directory. This can
18.01.2017 14:19:48                          be specified multiple times. If it is a directory,
18.01.2017 14:19:48                          all files with a ".hcl" or ".json" suffix will be
18.01.2017 14:19:48                          loaded.
18.01.2017 14:19:48
18.01.2017 14:19:48  -dev                    Enables Dev mode. In this mode, Vault is completely
18.01.2017 14:19:48                          in-memory and unsealed. Do not run the Dev server in
18.01.2017 14:19:48                          production!
18.01.2017 14:19:48
18.01.2017 14:19:48  -dev-root-token-id=""   If set, the root token returned in Dev mode will have
18.01.2017 14:19:48                          the given ID. This *only* has an effect when running
18.01.2017 14:19:48                          in Dev mode. Can also be specified with the
18.01.2017 14:19:48                          VAULT_DEV_ROOT_TOKEN_ID environment variable.
18.01.2017 14:19:48
18.01.2017 14:19:48  -dev-listen-address=""  If set, this overrides the normal Dev mode listen
18.01.2017 14:19:48                          address of "127.0.0.1:8200". Can also be specified
18.01.2017 14:19:48                          with the VAULT_DEV_LISTEN_ADDRESS environment
18.01.2017 14:19:48                          variable.
18.01.2017 14:19:48
18.01.2017 14:19:48  -log-level=info         Log verbosity. Defaults to "info", will be output to
18.01.2017 14:19:48                          stderr. Supported values: "trace", "debug", "info",
18.01.2017 14:19:48                          "warn", "err"
```

Here is screen shots and exported configs

docker-compose.yml
```
version: '2'
services:
  vault:
    cap_add:
    - IPC_LOCK
    image: registry.exness.io/dockerhub/vault:latest
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl":
        "168h", "max_lease_ttl": "720h"}'
    stdin_open: true
    tty: true
    command:
    - vault
    - server
    labels:
      io.rancher.container.pull_image: always

```

rancher-compose.yml
```
version: '2'
services:
  vault:
    scale: 1
    start_on_create: true

```

![2017-01-18 14 19 35](https://cloud.githubusercontent.com/assets/1939783/22063798/6d7fd0ca-dd89-11e6-8e2f-9fb1e3525e9b.png)

![2017-01-18 14 19 41](https://cloud.githubusercontent.com/assets/1939783/22063801/721b70c6-dd89-11e6-843b-d5012ae22b6d.png)

![2017-01-18 14 19 51](https://cloud.githubusercontent.com/assets/1939783/22063802/74955f92-dd89-11e6-9a93-40b3ff5ee1db.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.0` Cattle: `v0.175.2` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by boskiv** [comment]
Running same config manually without problem


```
➜  ~ docker run --cap-add=IPC_LOCK -e 'VAULT_LOCAL_CONFIG={"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}' vault server
Unable to find image 'vault:latest' locally
latest: Pulling from library/vault

b7f33cc0b48e: Pull complete
299f3e567563: Pull complete
f34115770a8e: Pull complete
02d201e1e6b3: Pull complete
5eccd8c8e1c2: Pull complete
Digest: sha256:b513e9d7f79282311145ccd5464a35ef7b293257ae610bab1ec07dc03faeb983
Status: Downloaded newer image for vault:latest
Vault v0.6.4 ('f4adc7fa960ed8e828f94bc6785bcdbae8d1b263')
==> Vault server configuration:

                 Backend: file
                     Cgo: disabled
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Version: Vault v0.6.4
             Version Sha: f4adc7fa960ed8e828f94bc6785bcdbae8d1b263

==> Vault server started! Log data will stream in below:
```

**Comment by tfiduccia** [comment]
@boskiv - in the UI, in your command section, you have "vault server".  But your manual command vault is actually the image, and server is the only command.

**Comment by boskiv** [comment]
Yeah, But Secret Bridge is about link between existing vault server and rancher. I need clean Vault server in my environment.

**Comment by janeczku** [comment]
@boskiv as @tfiduccia noted you have a typo in your UI service definition. The command should be `server` and not `vault server`. I verified with this docker-compose that the container will start successfully:

```
version: '2'
services:
  vault:
    cap_add:
    - IPC_LOCK
    image: vault:latest
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl":
        "168h", "max_lease_ttl": "720h"}'
    stdin_open: true
    tty: true
    command:
    - server
    labels:
      io.rancher.container.pull_image: always
```
