### ISSUE TITLE
External service links not working

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#7460]
I have a cron container that connects to a database in the same stack as well as a database container in another stack.  The external service link to the wordpress database is not resolvable.  This was functional in Rancher v1.1.4 but since then I've rebuilt my Rancher cluster on v1.3.1.  I've tried upgrading the image and restarting the container with no luck.

What steps can I take to debug why this isn't available?  

```
/var/www/html # ping database
PING database (10.42.45.211): 56 data bytes
64 bytes from 10.42.45.211: seq=0 ttl=64 time=0.376 ms
64 bytes from 10.42.45.211: seq=1 ttl=64 time=0.141 ms
^C
--- database ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.141/0.258/0.376 ms
/var/www/html # ping wordpress_database
ping: bad address 'wordpress_database'
```

**docker-compose**

```
  cron:
    image: namespace/project:cli.c37fd39b
    environment:
      APP_ENV: production
    stdin_open: true
    external_links:
    - wordpress-site/database:wordpress_database
    tty: true
    links:
    - database:database
    command:
    - crond
    - -f
    - -d
    - '8'
    labels:
      io.rancher.container.pull_image: always
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.1` Cattle: `v0.175.6` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.new`|
