### ISSUE TITLE
Kubectl config doesn't work if Access Control is activated

### ISSUE THREAD

**Issue by rebhisaid** [rancher/rancher#7463]
**Rancher Versions:**
Server: v1.3.1
healthcheck: v0.2.0
ipsec:rancher/net:holder
network-services: network-manager:v0.4.0
scheduler:
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7
etcd version: rancher/etcd:v2.3.7-11

**Docker Version:**  
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** 
- CentOS7
- bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Activate access control with Local authentication (username and password)
- Generate from UI the kubectl config
- Copy/paste it in my ~/.kube/config
- I got an error message 
```
Error from server: an error on the server ("Service Unavailable") has prevented the request from succeeding
```

**Results:** 
It should work and access the cluster

**Comment by galal-hussein** [comment]
@rebhisaid I can't reproduce the issue, i used the following steps to reproduce:

- Run Rancher v1.3.1 with kubernetes k8s:v1.5.1-rancher1-7
- Activate access control with local authentication.
- Login with admin user and normal user.
- Generate and copy kubectl config from UI
- Try to run different kubectl commands
```
kubectl version 
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.1-rancher1", GitCommit:"24adf52d6f18be9071dc3194b4dca4a0d4e35bb9", GitTreeState:"clean", BuildDate:"2016-12-15T05:28:48Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rebhisaid** [comment]
@galal-hussein I tried many kubectl commands and I have the same error message:
```
Error from server (InternalError): an error on the server ("Service Unavailable") has prevented the request from succeeding (get pods)
```

This is the generated config:
```
apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    insecure-skip-tls-verify: true
    server: "https://x.y.z.t:8080/r/projects/1a163/kubernetes"
  name: "dev"
contexts:
- context:
    cluster: "dev"
    user: "dev"
  name: "dev"
current-context: "dev"
users:
- name: "dev"
  user:
    username: "YYYYYYYYYYYYYYYYYYYYYYYYYYY"
    password: "XXXXXXXXXXXXXXXXXXXXXXX"
```

Why it is "https"? I didn't enabled https in rancher.
I removed the 's' so I use http but I got the error above.
