### ISSUE TITLE
Add sticky session support for ingress

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#7467]
With a kubernetes ingress we need to be able to support sticky sessions

**Comment by wlan0** [comment]
In v1.5.0-dev we have added the ability to configure StickinessPolicy for ingresses

Create a kubernetes rc, service.
Create an ingress for the service with the following annotation

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.stickiness.policy: "name: testname\n cookie: cookie123\ndomain: test.domain"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

Open the API UI for loadbalancerservices and ensure that the lb created corresponding to this ingress contains the StickinessPolicy field populated with the values mentioned above.

Then edit one of the values in the above stickiness policy config in the ingress and then replace the ingress, and check that the value is updated in the rancher API

Then, remove the stickiness policy config in the ingress and replace the ingress (kubectl replace -f $file_name), and check that the StickinessPolicy field is removed from the rancher API.
