### ISSUE TITLE
Add "how to schedule ingress LB on a particular host(s)" to the doc 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7517]
@wlan0 we have to put a small writeup on how to configure scheduling labels for k8s ingress (also covering global scale)

@deniseschannon

**Comment by wlan0** [comment]
These are the steps for scheduling ingress LB on particular hosts -

This feature has been added since v1.4.0-rancher release of kubernetes

Ensure that you have more than one host added to rancher, label the hosts in rancher with names like

```
host=host1
host=host2
```

Steps to test:

1. create the reference RC and Service shown below.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```

2. Using this reference ingress definition, create the ingress controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.scheduler.affinity.host_label: "host=host1"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

Note the annotation in the ingress config yaml. This will create the lb service on the host with label host=host1. Check that the lb-service container gets launched on this particular host by checking the host view in rancher UI.

The following are the steps to create a global service

This feature has been added since v1.4.0-rancher release of kubernetes

Ensure that you have more than one host added to rancher

Steps to test:

1. create the reference RC and Service shown below.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
  template:
    metadata:
      labels:
        k8s-app: nginx-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx-service
        image: nginx:latest
        ports:
        - containerPort: 80
```

2. Using this reference ingress definition, create the ingress controller:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    config: "defaults\n balance source\nglobal\nmaxconnrate 60"
    io.rancher.scheduler.global: "true"
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

This will create the lb service globally. Check that the lb-service container gets launched on every host by checking the host view in rancher UI.
