### ISSUE TITLE
Unclear error message from invalid docker-compose

### ISSUE THREAD

**Issue by trondhindenes** [rancher/rancher#7558]
**Rancher Versions:**
Server: 1.3.2

**Docker Version: 1.12.6

**Steps to Reproduce:**
I'm getting some errors from rancher based on an invalid docker-compose:
`ERRO[0000] Failed Creating celery_redis : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, fieldName=name, baseType=error]`
Based on this, its pretty hard to track down where the actual error is, especially in a large compose file. It would be great if rancher would output better errors, for instance the value of the field it chokes on.
**Results:**

**Comment by pkaramol** [comment]
Why was this issue closed?
The error message is extremly vague and not providing any feedback about potential mitigating actions.
Why such a generic unhelpful message?

**Comment by phynias** [comment]
i get the same error, no idea what it is referring to or if it is even a problem.

```
---
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    mem_limit: 2147483648
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - /home/test/utilities/test-on-prem/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: logstash
    mem_limit: 536870912
    environment:
      - 'xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}'
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    volumes:
      - /home/test/utilities/test-on-prem/logstash:/etc/logstash
    depends_on:
      - elasticsearch
      - db
    command: ['-f', '/etc/logstash/logstash.conf']

  redis:
    image: redis
    mem_limit: 1073741824
    command: ["redis-server"]
    volumes:
      - redisdata1:/data

  cassandra:
    mem_limit: 2147483648
    image: cassandra
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    volumes:
      - cassandradata1:/var/lib/cassandra:rw

  db:
    image: mysql
    mem_limit: 3221225472
    container_name: db
    command: mysqld --user=root --verbose
    volumes:
      - /home/test/utilities/test-on-prem/sql:/docker-entrypoint-initdb.d
      - dbdata1:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test_dev
      MYSQL_PASSWORD: test_dev
      MYSQL_ROOT_PASSWORD: root

  minio:
    image: minio/minio
    mem_limit: 3221225472
    volumes:
      - miniodata1:/data
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${PARTNER_ACCESS}
      MINIO_SECRET_KEY: ${PARTNER_SECRET}

  api:
    image: testvision/api:${TAG}
    mem_limit: 1073741824
    environment:
      ENV: ${ENV}
    ports:
      - "3737:3737"
      - "4747:4747"
      - "8080:8080"

  console:
    image: testvision/console:${TAG}
    mem_limit: 1073741824
    environment:
      ENV: ${ENV}
    ports:
      - "8000:8000"

  tasks_light:
    image: testvision/tasks_light:gpu-${TAG}
    mem_limit: 1073741824
    environment:
      ENV: ${ENV}
      PARTNER_ACCESS: ${PARTNER_ACCESS}
      PARTNER_SECRET: ${PARTNER_SECRET}
      API_KEY: ${API_KEY}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES}

volumes:
  esdata1:
    driver: local
  redisdata1:
    driver: local
  dbdata1:
    driver: local
  miniodata1:
    driver: local
  cassandradata1:
    driver: local
```

```

version: '2'
services:
  db:
    scale: 1
  api:
    scale: 1
  console:
    scale: 1
  tasks_light:
    scale: 1
  cassandra:
    scale: 1
  elasticsearch:
    scale: 1
  redis:
    scale: 1
  logstash:
    scale: 1
  minio:
    scale: 1
```
