### ISSUE TITLE
Not able to start containers with new EBS volume.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7589]
Rancher Server version  - v1.4.0-rc4  and rancher/storage-ebs:v0.6.5

Steps to reproduce the problem:
Create an environment with hosts in AWS.
Deploy rancher-ebs using the same aws credentials as what was used for host deployments.

Create a service with a new volume in rancher-ebs driver using the following yml:
```
version: '2'
volumes:
  testvol1:
    driver_opts:
      size: '1'
    driver: rancher-ebs
services:
  test1:
    image: ubuntu
    volumes:
    - testvol1:/mydata1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

Volume gets created successfully.
But containers fails to start and gets to stopped state.

Following errors seen in  ebs-ebs-driver logs:

```
1/28/2017 6:45:20 PMtime="2017-01-29T02:45:20Z" level=info msg=attach.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=attach.response
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=mount.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg="mytest1_testvol1_e4f97 already mounted on /var/lib/rancher/volumes/rancher-ebs/mytest1_testvol1_e4f97"
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-ebs/mytest1_testvol1_e4f97"
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=unmount.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=unmount.response
1/28/2017 6:45:21 PMtime="2017-01-29T02:45:21Z" level=info msg=attach.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg=attach.response
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg=mount.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg="mytest1_testvol1_e4f97 already mounted on /var/lib/rancher/volumes/rancher-ebs/mytest1_testvol1_e4f97"
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-ebs/mytest1_testvol1_e4f97"
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg=unmount.request name="mytest1_testvol1_e4f97"
1/28/2017 6:45:22 PMtime="2017-01-29T02:45:22Z" level=info msg=unmount.response
```

**Comment by yasker** [comment]
In fact, we didn't specify TTY or stdin in compose file so it started then stopped.

Assign back to @sangeethah

**Comment by sangeethah** [comment]
This issue is still reproducible.

**Comment by sangeethah** [comment]
Tested with following yml including the  stdin_open: true and tty: true:

```
version: '2'
volumes:
  testvol1:
    driver_opts:
      size: '1'
    driver: rancher-ebs
services:
  test1:
    image: ubuntu
    volumes:
    - testvol1:/mydata1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

Service is able to start successfully with volumes in EBS.
