### ISSUE TITLE
Volume deletion for EBS volumes fails

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7590]
Rancher Server version - v1.4.0-rc4 and rancher/storage-ebs:v0.6.5

Steps to reproduce the problem:
Create an environment with hosts in AWS.
Deploy rancher-ebs using the same aws credentials as what was used for host deployments.

Create a service with a new volume in rancher-ebs driver using the following yml:

```
version: '2'
volumes:
  testvol1:
    driver_opts:
      size: '1'
    driver: rancher-ebs
services:
  test1:
    image: ubuntu
    volumes:
    - testvol1:/mydata1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
Volume gets created successfully.
But containers fails to start and gets to stopped state. This is tracked in https://github.com/rancher/rancher/issues/7589.

Delete the stack.
Volume gets removed from the rancher-side ( It is not listed in the storage volume list anymore).

But the volume is still present in AWS.

```
1/28/2017 10:39:54 PMtime="2017-01-29T06:39:54Z" level=info msg=mount.request name="hello_testvol1_45117"
1/28/2017 10:39:54 PMtime="2017-01-29T06:39:54Z" level=info msg="hello_testvol1_45117 already mounted on /var/lib/rancher/volumes/rancher-ebs/hello_testvol1_45117"
1/28/2017 10:39:54 PMtime="2017-01-29T06:39:54Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-ebs/hello_testvol1_45117"
1/28/2017 10:39:55 PMtime="2017-01-29T06:39:55Z" level=info msg=unmount.request name="hello_testvol1_45117"
1/28/2017 10:39:55 PMtime="2017-01-29T06:39:55Z" level=info msg=unmount.response
1/28/2017 10:40:03 PMtime="2017-01-29T06:40:03Z" level=info msg="container 80d10b53de94c37ac4be30da60dd1a49e2faefe4b6e2653966889d96dcf95450 destroyed"
1/28/2017 10:40:05 PMtime="2017-01-29T06:40:05Z" level=info msg=remove.request name="hello_testvol1_45117"
1/28/2017 10:40:05 PMtime="2017-01-29T06:40:05Z" level=error msg=remove.response error="Failed to delete volume vol-0ce3ac3b1ccabbc9e, current state: in-use is not available"
1/28/2017 10:40:05 PMtime="2017-01-29T06:40:05Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-ebs/hello_testvol1_45117"
1/28/2017 10:40:06 PMtime="2017-01-29T06:40:06Z" level=info msg=remove.request name="hello_testvol1_45117"
1/28/2017 10:40:07 PMtime="2017-01-29T06:40:07Z" level=error msg=remove.response error="Failed to delete volume vol-0ce3ac3b1ccabbc9e, current state: in-use is not available"
```

<img width="1126" alt="screen shot 2017-01-28 at 10 49 21 pm" src="https://cloud.githubusercontent.com/assets/4266958/22402450/1c11ff62-e5ac-11e6-946a-714d509e81c0.png">

**Comment by yasker** [comment]
Assign back to @sangeethah due to the same issue of #7589

**Comment by sangeethah** [comment]
This issue is still reproducible.

Create a service with a new volume in rancher-ebs driver using the following yml:
```
version: '2'
volumes:
  testvol1:
    driver_opts:
      size: '1'
    driver: rancher-ebs
services:
  test1:
    image: ubuntu
    volumes:
    - testvol1:/mydata1
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

Once service is created successfully, delete the stack.
Volume gets removed from the rancher-side ( It is not listed in the storage volume list anymore).

But the volume is still present in AWS.
