### ISSUE TITLE
Creation of webhooks to scale a service with no image should not be allowed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7636]
**Rancher Versions:**
Server:v1.4.0-rc6

**Docker Version:**v1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a service with no image and encompassing containers with a specific label [ Using the key io.rancher.service.selector.container]

docker-compose.yml
```
version: '2'
services:
  test92633:
    image: rancher/none
    labels:
      io.rancher.service.selector.container: test=none
```
rancher-compose.yml
```
version: '2'
services:
  test92633:
    scale: 0
    start_on_create: true

```
2. Create a webhook to scale up for this service with no image. 

Webhook should not be created for this service
