### ISSUE TITLE
Can't run service with docker-compose v2 defined volume on different nodes

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#7646]
**Rancher Versions:**
Server: v1.3.3
healthcheck: v0.2.0
ipsec: v0.0.2
network-services: v0.0.8
scheduler: v0.3.0

**Docker Version:**
v1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS on Openstack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a stack with this docker-compose.yml:
```yaml
version: '2'
services:
  hello:
    image: tutum/hello-world
    labels:
      io.rancher.scheduler.global: 'true'
    volumes:
      - test:/test
volumes:
  test: {}
```

**Results:** 
The service starts on one node and fails to start on all the other nodes with:
`
Failed to allocate instance [container:1i514421]: Bad instance [container:1i514421] in state [error]: Scheduling failed: valid host(s) [2], volume [509390] must have exactly these pool(s): [3]
`
