### ISSUE TITLE
container_label_ne not working properly

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7704]
**Rancher Versions:**
scheduler: 0.5.1

**Docker Version:** 1.12.5

**Setup Details: HA rancher**

**Environment Type: Cattle**

**Problem:**

I've deployed 3 containers that have the label `io.rancher.stack_service.name` with a value of `consul/consul-server`

I have another set of containers that I want to schedule globally EXCEPT on servers that have `io.rancher.stack_service.name=consul/consul-server`

Rancher ignores the affinity constraint. I have the label set as follows ...

```
io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=consul/consul-server
```

**Steps to Reproduce:**

The following docker-compose nets be 3 consul servers because I have 3 servers with the host label of managers, but when the agent runs it spins up containers on all servers including the servers that already have an instance of consul-server running on it.

```
consul-server:
  image: ekristen/consul-rancher:latest
  command: server
  net: host
  uts: host
  tty: true
  stdin_open: true
  ports:
    - 8300:8300/tcp
    - 8301:8301/tcp
    - 8301:8301/udp
    - 8302:8302/tcp
    - 8302:8302/udp
    - 8400:8400/tcp
    - 8500:8500/tcp
    - 8600:8600/udp
  labels:
    io.rancher.container.dns: true
    io.rancher.container.network: true
    io.rancher.scheduler.global: true
    io.rancher.scheduler.affinity:host_label: group=managers
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=consul/consul-server
  volumes:
    - /var/lib/consul:/consul/data
    - /etc/consul/:/consul/config

consul-agent:
  image: ekristen/consul-rancher:latest
  command: agent
  net: host
  uts: host
  tty: true
  stdin_open: true
  labels:
    io.rancher.container.dns: true
    io.rancher.scheduler.global: true
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=consul/consul-server
  links:
    - consul:consul
  volumes:
    - /var/lib/consul:/consul/data
    - /etc/consul:/consul/config
```

**Results:** 

Rancher spins up instances on servers it should not by ignoring the container_label_ne affinity label.
