### ISSUE TITLE
Cannot launch services using Secrets v1.4.0

### ISSUE THREAD

**Issue by jsalva** [rancher/rancher#7707]
**Rancher Versions:**
Server: 1.4.0
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: v0.4.5
scheduler: v0.6.3
kubernetes (if applicable):

**Docker Version:**
Docker version 1.12.6, build 7392c3b/1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon Linux (AWS)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, RDS DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Launch rancher secrets from Catalogue
- Create a secret
- Create Empty Stack
- Launch any service (e.g. ubuntu) in empty stack with the secret created in previous step

**Results:** 
```
Activating (Expected state running but got error: Error response from daemon: create 6b89278348bf3b0e919a5b4cc8acef7988efe1e1fb2cfb6af58af1dbb11f5896: create 6b89278348bf3b0e919a5b4cc8acef7988efe1e1fb2cfb6af58af1dbb11f5896: Error looking up volume plugin rancher-secrets: plugin not found)
```

Here are my configs for the secrets stack:

```yml
#docker-compose.yml
version: '2'
services:
  secrets-driver:
    privileged: true
    image: rancher/storage-secrets:v0.6.7
    environment:
      RANCHER_DEBUG: 'true'
    network_mode: host
    volumes:
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    labels:
      io.rancher.container.agent.role: environment,agent
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
```

```yml
#rancher-compose.yml
version: '2'
services:
  secrets-driver:
    storage_driver:
      volumeAccessMode: singleHostRW
      description: A tmpfs driver for secrets
      name: rancher-secrets
      volumeCapabilities:
      - secrets
      scope: local
      blockDevicePath: null
    start_on_create: true
```

I upgraded all of my infrastructure stacks (some were not yet upgraded). Upgrades went fine.

Secrets is running and reporting healthy on all hosts, with the following sample logs:

```
2/6/2017 1:57:24 PMtime="2017-02-06T18:57:24Z" level=info msg=Running
2/6/2017 1:57:24 PMtime="2017-02-06T18:57:24Z" level=info msg=Starting
2/6/2017 1:58:46 PMtime="2017-02-06T18:58:46Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 1:59:14 PMtime="2017-02-06T18:59:14Z" level=info msg=Running
2/6/2017 1:59:14 PMtime="2017-02-06T18:59:14Z" level=info msg=Starting
2/6/2017 2:00:35 PMtime="2017-02-06T19:00:35Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:00:37 PMtime="2017-02-06T19:00:37Z" level=info msg=Running
2/6/2017 2:00:37 PMtime="2017-02-06T19:00:37Z" level=info msg=Starting
2/6/2017 2:01:58 PMtime="2017-02-06T19:01:58Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:02:00 PMtime="2017-02-06T19:02:00Z" level=info msg=Running
2/6/2017 2:02:00 PMtime="2017-02-06T19:02:00Z" level=info msg=Starting
2/6/2017 2:03:21 PMtime="2017-02-06T19:03:21Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:03:23 PMtime="2017-02-06T19:03:23Z" level=info msg=Running
2/6/2017 2:03:23 PMtime="2017-02-06T19:03:23Z" level=info msg=Starting
2/6/2017 2:04:44 PMtime="2017-02-06T19:04:44Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:04:46 PMtime="2017-02-06T19:04:46Z" level=info msg=Running
2/6/2017 2:04:46 PMtime="2017-02-06T19:04:46Z" level=info msg=Starting
2/6/2017 2:06:07 PMtime="2017-02-06T19:06:07Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:06:09 PMtime="2017-02-06T19:06:09Z" level=info msg=Running
2/6/2017 2:06:09 PMtime="2017-02-06T19:06:09Z" level=info msg=Starting
2/6/2017 2:07:30 PMtime="2017-02-06T19:07:30Z" level=fatal msg="getting host ID: initializing metadata: Get http://169.254.169.250/2015-12-19/version: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
2/6/2017 2:07:32 PMtime="2017-02-06T19:07:32Z" level=info msg=Running
2/6/2017 2:07:32 PMtime="2017-02-06T19:07:32Z" level=info msg=Starting
2/6/2017 2:08:09 PMtime="2017-02-06T19:08:09Z" level=info msg="Running on host ip-10-0-2-152.us-west-1.compute.internal(1h27) with driver rancher-secrets(1sd1)"
2/6/2017 2:08:09 PMtime="2017-02-06T19:08:09Z" level=info msg="Starting plugin for rancher-secrets"
2/6/2017 2:09:01 PMtime="2017-02-06T19:09:01Z" level=info msg="container 1e3c8cb08fea684dcb466daaf831ff1c4a08a4e57047d43480a4db89c87dca46 destroyed"
2/6/2017 2:11:59 PMtime="2017-02-06T19:11:59Z" level=info msg="container c69a08d97b815e30b00e3fe211b26a7b8be38d420cbbce68d3fe87ae31fcd03b destroyed"
```
