### ISSUE TITLE
Automate pre Upgrade and Post upgrade steps for Upgrade testing

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7725]
Current manual upgrade testing (from version v1 to v2) can be broken down into following steps:

1. Fresh install of version v1.
2. In cattle environment, Create the following set of services.
```
1. Create LB service
2. Create DNS service
3. Create External service
4. Create a service with link to another service. Ensure it is functional.
5. Create a new environment.
6. Create services in this environment.
7. Create health check enabled services
8. Create health check enabled global services
9. Create LB services with health check enabled targets
10. Create global LB service with global health check enabled targets
11. Add 2 DO/EC2 machines and have few containers running on them.
12. Create new stack and have some services deployed. 
13. Create LB services to have targets from a different stack. 
14. Create a service with link to service in the other stack. Ensure it is functional
```
3. Validate the services created in step 2.
```
1. Make sure all services created are functional (LB/DNS and External services work as expected).
2. Ensure services can be accessed by their name from containers of other services: dig servicename dig servicename.stackname
```
4. Upgrade rancher-server to version v2.
5. Repeat step 3
6. Repeat step2 and step3 by creating them on new stacks.
7. On the stacks that were created on pre upgrade steup , perform the following validations:
```
1. Scale up/scale down instances and make sure that LB/DNS and External services continue to work as expected and able to resolve to older (pre upgrade) and new instances (post upgrade).
2. Ensure machine config downloads for existing machines (DO/EC2) are successful.Able to delete existing machines.
```

K8s upgrade pretty much follows the same steps , except that we have K8s related objects created and validated in steps 2, 3 and 7.

As a first step towards getting to a fully automated upgrade testing , we would want steps 2 , 3 and 7 to be automated fully. 
Creation of stacks will be driven by pre defined docker and rancher compose files.

**Comment by galal-hussein** [comment]
@sangeethah In k8s, step 2 will create the following resources:

upgrade_testing.yml
```
# Pod
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

# RC
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: husseingalal/nginx-curl
          ports:
            - containerPort: 80

# service LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    name: nginx-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 80
  selector:
    name: nginx

# service external
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  labels:
    name: nginx-external
spec:
  type: NodePort
  externalIPs: ['placeholder-1']
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    name: nginx

# service cluster ip
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  labels:
    name: nginx-clusterip
spec:
  sessionAffinity: ClientIP
  type: ClusterIP
  clusterIP: 10.43.0.50
  ports:
  - port: 8000
    targetPort: 80
  selector:
    name: nginx

# Ingress testing
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress1
 annotations:
   http.port: "83"
spec:
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /service3.html
       backend:
         serviceName: k8test1
         servicePort: 81
     - path: /name.html
       backend:
         serviceName: k8test2
         servicePort: 80

---

apiVersion: v1
kind: Service
metadata:
 name: k8test1
 labels:
   k8s-app: k8test1-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test1-service

---

apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc1
spec:
 replicas: 2
 selector:
   k8s-app: k8test1-service
 template:
   metadata:
     labels:
       k8s-app: k8test1-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81

---

apiVersion: v1
kind: Service
metadata:
 name: k8test2
 labels:
   k8s-app: k8test2-service
spec:
 ports:
 - port: 80
   targetPort: 80
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test2-service

---

apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc2
spec:
 replicas: 2
 selector:
   k8s-app: k8test2-service
 template:
   metadata:
     labels:
       k8s-app: k8test2-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 80
```

The testing will include the following:

- Make sure the Pod "nginx-pod" is up and running.
- Test service "nginx-lb" and make sure it sends traffic to rc's pod "nginx"
- Test service "nginx-external" and make sure it sends traffic to  rc's pod "nginx"
- Test service "nginx-clusterip" and make sure it sends traffic to  rc's pod "nginx"
- Test ingress with host header "foo.bar.com" on port "83"
   - Test /name.html and make sure it sends traffic to "k8test2" service on port 80
   - Test /service3.html and make sure it sends traffic to "k8test1" service on port 81
