### ISSUE TITLE
Unable to ping other services from sidekick containers

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#7738]
## Steps to reproduce the problem:
1. Deploy the test1 stack
2. Wait until the status changes to active
3. Deploy the test2 stack
4. Wait until the status changes to active
5. Upgrade the service1 service.
6. Try to ping service1 from the sidekick container of service2

## Result
Unable to ping "unknown host service1"
## Expected
Should be able to ping from both primary and sidekick containers.

I've also check the file "/etc/rancher-dns/answers.json" in the network-services-metadata-dns container,
it does contain service1 information as follows,
"a":{"service1.rancher.internal.":{"answer":["10.42.83.18"]},"service1.test1.rancher.internal.":{"answer":["10.42.83.18"]}}

## The test1 stack
```

Docker compose

version: '2'
services:
  service1:
    image: ubuntu:14.04
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      
      
Rancher compose

version: '2'
services:
  service1:
    scale: 1
    start_on_create: true
```
The test2 stack
```

Docker compose
version: '2'
services:
  sidekick:
    image: ubuntu:14.04
    stdin_open: true
    external_links:
    - test1/service1:service1
    tty: true
    labels:
      io.rancher.container.pull_image: always
  service2:
    image: ubuntu:14.04
    stdin_open: true
    external_links:
    - test1/service1:service1
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: sidekick

Rancher compose
version: '2'
services:
  sidekick:
    scale: 1
    start_on_create: true
  service2:
    scale: 1
    start_on_create: true
```
--
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.4` Cattle: `v0.175.10` UI: `v1.3.6` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|
