### ISSUE TITLE
Created a load balancer with port rules as null in lbconfig 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7767]
**Rancher Versions:**
Server: v1.4.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1.  Using kubectl create these 2 files.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---            

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
    type: ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: nginx
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  backend:
    serviceName: nginx-service
    servicePort: 80
```

Results: 

UI no longer loads because a load balancer is created cause port rules is null instead of an empty array.
