### ISSUE TITLE
Mixed content loaded over HTTPS with HAProxy

### ISSUE THREAD

**Issue by occasl** [rancher/rancher#7804]
**Rancher Versions:**
```
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=localhost
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v0.4.1
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.2
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v1.4.0
CATTLE_USE_LOCAL_ARTIFACTS=true
```
**Docker Version:**
1.2.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.3.1611 (Core) on VMWare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Run: 
`sudo docker run -d --restart=unless-stopped --name=rancher-server -v /data/rancher:/var/lib/rancher -p 127.0.0.1:8080:8080 rancher/server`

Open web console and configure LDAP connectivity successfully

Install HA-Proxy version 1.5.18 2016/05/10

Update haproxy.cfg to allow SSL:
```
global
  maxconn 4096
  ssl-server-verify none

defaults
  mode http
  balance roundrobin
  option redispatch
  option forwardfor

  timeout connect 5s
  timeout queue 5s
  timeout client 36000s
  timeout server 36000s

frontend http-in
  mode tcp
  bind *:443 ssl crt /etc/haproxy/rancher-cert.pem
  default_backend rancher_servers

  acl is_websocket hdr(Upgrade) -i WebSocket
  acl is_websocket hdr_beg(Host) -i ws
  use_backend rancher_servers if is_websocket

backend rancher_servers
  server websrv1 127.0.0.1:8080 weight 1 maxconn 1024
```

Restart haproxy and attempt to login again.

**Results:** 

```
Mixed Content: The page at 'https://rancher.abc.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://rancher.abc.com/v2-beta/identities?limit=-1&sort=name'. This request has been blocked; the content must be served over HTTPS.
```

I've tried multiple things to workaround this. Any ideas why this is happening in this release? It appears that this was address in older versions.

**Comment by evanrich** [comment]
I have the same issue with gitlab behind haproxy.  Haproxy serves as SSL endpoint, but when I try to load a page, I get a very similar message

**Comment by occasl** [comment]
I had to abandon HAProxy and use NGINX for SSL termination.

**Comment by cusspvz** [comment]
@occasl I'm using (nginx-proxy)[https://github.com/jwilder/nginx-proxy] for SSL termination with enforcing. Could you please share your nginx configurations? The same you've experienced is happening on my setup. Thanks

**Comment by bezzers** [comment]
Same issue here. I can put HAProxy in front of Rancher running under http, but under https it fails to login because the v2-beta/identities?limit=-1&sort=name endpoint is requested over http. This is running in single server mode, and happens under both v1.4.1 and v1.3.4. 

Letting Chrome accept mixed content just means that we get 301 redirections from http to https from HAProxy, but the browser doesn't try the https version.

**Comment by cusspvz** [comment]
FYI, before giving up and configuring our rancher back again to `http`, I've got into the point that `identities` request is being requested over `http` because `api` internal endpoint responses are pointing to `http` inspite you got `https` on your rancher url setup.

ping @ibuildthecloud @cloudnautique

**Comment by bezzers** [comment]
Yes, I agree that is what is happening. I was having a quick look through the code to see where that request was being made from to figure out why but I haven't tracked it down yet.

**Comment by bezzers** [comment]
Some progress tracking this down: There is a difference in the way that we call for the failing identities request and other successful requests that use https properly.

In the /assets/ember-api-store/services/store.js module, the successful calls got through line 157 and the unsuccessful one through line 162.

The relevant section of code is:

```
      // If URL is explicitly given, go straight to making the request.  Do not pass go, do not collect $200.
      // This is used for bootstraping to load the schema initially, and shouldn't be used for much else.
      if (opt.url) {
        return this._findWithUrl(opt.url, type, opt);
      } else {
        // Otherwise lookup the schema for the type and generate the URL based on it.
        return this.find('schema', type, { url: 'schemas/' + encodeURIComponent(type) }).then(function (schema) {
          var url = schema.linkFor('collection') + (id ? '/' + encodeURIComponent(id) : '');
          return _this._findWithUrl(url, type, opt);
        });
      }
```

So the generation of the URL from the schema isn't working in this case.

**Comment by cusspvz** [comment]
@bezzers Thats what I've mentioned, internal endpoint responses (which includes schema for further requests) are pointing to `http` instead of `https`, event when rancher's base url is set to `https`. That's the issue.

**Comment by bezzers** [comment]
Right @cusspvz . So two questions I'm looking into here:
1. Why does the schema lock us in to http and where is that set?
2. Why is the identities request uniquely looking up its address from the schema rather than having it passed into the store directly like everything else?

**Comment by vincent99** [comment]
The API returns responses with absolute URLs in them, and the UI follows them.  The first few initial requests on load do not go through that path to make it load faster/in parallel since we realistically know they're not going to move unexpectedly.

The UI requesting things wrong is just a symptom of the server returning incorrect URLs in teh response.  Any proxy or TLS termination between the client and server container needs to pass down enough information to reconstruct the original request URI, either through PROXY protocol or `X-Forwarded-*` + `Host` headers.

**Comment by cusspvz** [comment]
@vincent99 This happened me when using [nginx-proxy](https://github.com/jwilder/nginx-proxy).

Here are the [headers that are passed](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L64-L68).

URLs were all following the protocol as it should, except the `identities` call.

Could it be because of  [`x-api-request-url`](https://github.com/rancher/v2-api/blob/097a723c797f1bbb096576b74cbea04f2f90abd2/vendor/github.com/rancher/go-rancher/api/url.go#L139)?

**Comment by cusspvz** [comment]
Here's a replicable docker-compose:

```yaml
rancher:
  restart: always
  image: rancher/server:v1.4.1
  environment:
    VIRTUAL_HOST: rancher.test.com
    VIRTUAL_PORT: 8080
    HTTPS_METHOD: redirect
    LETSENCRYPT_HOST: rancher.test.com
    LETSENCRYPT_EMAIL: youremail@test.com

nginx-proxy:
  restart: always
  image: jwilder/nginx-proxy:0.5.0
  volumes:
  - /tmp/proxy/certs:/etc/nginx/certs:ro
  - /etc/nginx/vhost.d
  - /usr/share/nginx/html
  - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
  - 80:80/tcp
  - 443:443/tcp

ssl-generator:
  restart: always
  image: jrcs/letsencrypt-nginx-proxy-companion:latest
  volumes:
  - /tmp/proxy/certs:/etc/nginx/certs:rw
  - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
  - nginx-proxy
```

**Comment by vincent99** [comment]
```
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
```

Have you looked at what's actually coming out and being received by the server?  I don't think most of these make sense.  [Our example](http://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration) shows 

```
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass http://rancher;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
# This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
proxy_read_timeout 900s;
```

**Comment by vincent99** [comment]
And identities is just the first thing that is actually following a link; in current versions all the initial load is manually set.  There are plenty of other places you'll run into later if you keep clicking around that will eb wrong too.

**Comment by mikemoate** [comment]
I've just been looking at this with @bezzers and the [example config given for HAProxy](https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/#example-haproxy-configuration) would seem to result in most of those headers being unset (Only X-Forwarded-For will be set).

Should the example be specifying something like `send-proxy` for the backend server?

**Comment by bezzers** [comment]
I seem to have cracked it. I added the line `reqadd X-Forwarded-Proto:\ https if { ssl_fc }` to my HAProxy configuration and now the schema returns properly and everything seems to load.

**Comment by vincent99** [comment]
[$scheme](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_scheme), [$server_port](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_port), and [$proxy_add_x_forwarded_for](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#variables) are all defined variables.  As far as I can tell "proxy_x_forwarded_proto" and others @cusspvz had in his example are not actual things.

@bezzers alternate way of setting `X-Forwarded-Proto` should work too, but I think produces the same result as just using `$scheme`.

**Comment by cusspvz** [comment]
> As far as I can tell "proxy_x_forwarded_proto" and others @cusspvz had in his example are not actual things.

Those "undefined" variables are actually mapped [here](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L22-L45). What I've understood so far, is that they mapped those to allow overriding from parent proxies.

Since @bezzers has solved his problem, I think it is better to change the approach I'm using (give up on nginx-proxy) and configure it manually.

@vincent99 thank you very much for your time mate!!

Inspite all this, gonna give a last try on `nginx-proxy` just in case something is missing me.

**Comment by cusspvz** [comment]
Solved. I've replaced the variables `nginx-proxy` uses by a custom `proxy.conf`.
Thanks once again @vincent99 !

For those who may need it

```yaml
# docker-compose.yaml

# Don't forgot to mount volumes on rancher to prevent data-loss
rancher:
  restart: always
  image: rancher/server:v1.4.1
  environment:
    VIRTUAL_HOST: rancher.test.com
    VIRTUAL_PORT: 8080
    HTTPS_METHOD: redirect
    LETSENCRYPT_HOST: rancher.test.com
    LETSENCRYPT_EMAIL: youremail@test.com

nginx-proxy:
  restart: always
  build: ./nginx-proxy
  volumes:
  - /tmp/proxy/certs:/etc/nginx/certs:ro
  - /etc/nginx/vhost.d
  - /usr/share/nginx/html
  - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
  - 80:80/tcp
  - 443:443/tcp

ssl-generator:
  restart: always
  image: jrcs/letsencrypt-nginx-proxy-companion:latest
  volumes:
  - /tmp/proxy/certs:/etc/nginx/certs:rw
  - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
  - nginx-proxy

```

```Dockerfile
# nginx-proxy/Dockerfile
FROM jwilder/nginx-proxy:0.5.0
ADD proxy.conf /etc/nginx/proxy.conf
```

```nginx
# nginx-proxy/proxy.conf

# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering on;
proxy_buffers 16 16k;
proxy_buffer_size 16k;
proxy_max_temp_file_size 0;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Port $server_port;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";

server_tokens off;
client_max_body_size 10m;
client_body_buffer_size 10m;

```
