### ISSUE TITLE
CLI rancher-compose:  Unsupported config option secrets

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#7809]
I know that secrets backend is experimental,  but rancher-compose should support stack/service configuration right ?  Not creation of secrets, just use of them.

**Rancher Versions:**
Server: 1.4.0
rancher-compose version v0.12.2 / v0.12.2-rc1

**Steps to Reproduce:**
create some app, via Rancher UI assign secret, get resulted docker/rancher-compose files in UI and test them via CLI

```
    environment:
      PASSWORD_FILE: /run/secrets/password
    secrets:
    - uid: '0'
      gid: '0'
      mode: '444'
      name: password
      secretId: 24
```

**Results:** 

ERRO[0000] Could not parse config for project Stack : Unsupported config option for app service: 'secrets'
FATA[0000] Failed to read project: Unsupported config option for app service: 'secrets'

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/22950400/b7f9057e-f2c2-11e6-98e5-90d53ee34f26.png)

**Comment by VAdamec** [comment]
I know that's experimental, but documentation mention only secrets creation, not usage
https://docs.rancher.com/rancher/v1.4/en/cattle/secrets/ so can you update documentation which declare whats possible in actual version (only testing via UI) ?

**Comment by deniseschannon** [comment]
@VAdamec I believe the docs clearly note that creating and using secrets is not supported in the CLI. There is a note in the creation and the using secrets section.

**Comment by swartel-fa** [comment]
@VAdamec +1 with your comment
To my mind, there is no interest to just provide this experimental feature to be used exclusively via UI :/
A little feedback, it's less readable and not convenient to map correctly secret by using id so that  could it be possible to allow mapping with secret name ?

@deniseschannon Hi Denise, I have a demo next friday and hope I will be able to integrate secrets in docker-compose.yml in our custom catalog. Please, just let us know about its availability ;)

**Comment by vincent99** [comment]
Usage is documented here: https://docs.rancher.com/rancher/v1.4/en/cattle/secrets/#adding-secrets-to-servicescontainers .  When compose support is added, usage of it will be added there too. And it will be by name, not ID.

We have clearly let you know: it is not available and will be in a future release.  [Non-patch] Releases are monthly so that is not going to change by Friday. The functionality that exists today provides a way to define and use secrets.  If it not being your favorite way means you have "no interest", then sorry,  pretend it doesn't exist at all, but that doesn't mean it's not useful to other people.

**Comment by swartel-fa** [comment]
@vincent99 Many thanks for your answer 👍 

Just to let you know I lost half a day while using the same document yesterday due to a typo:
https://github.com/rancher/rancher/issues/7650#issuecomment-280925322

So even if it is an experimental feature, please make an effort on documentation or wait until the next monthly release to publish :)

**Comment by vincent99** [comment]
Denise already changed it.  Again I'm sorry but experimental things by definition are going to have rough edges; that's why they're labeled.

PRs are accepted for all repos and the docs are probably the easiest to contribute to.  Please have some perspective and realize mistakes happen and you're using the product of >100,000 person-hours of our work for €0.

**Comment by swartel-fa** [comment]
Of course I know what open source meant and its different business models as well. Be sure I should contribute to Rancher with great pleasure quite soon.
For the moment, I am not using it but exploring its great features as a way to provide multi-tenant application stacks for our development teams. So I try to keep in touch as possible to demonstrate Rancher is the right solution we are looking for.
And many thanks to the Rancher team and contributors for your hard work on the project well appreciated 👍

**Comment by raphink** [comment]
I see that catalogs can take fiels with a `secret` type in `.catalog`, and it effectively renders as a selector with existing secrets. Is there a way to inject that into the `docker-compose.yml` of the catalog template?

**Comment by vincent99** [comment]
@raphink Still not supported in compose, but that is the idea with that question type.  The output is the name of a secret, which you will eventually be able to substitute in and use in the compose file.

**Comment by raphink** [comment]
@vincent99 so currently, there is no way to do this programmatically at all, even with the Cattle API? How does the UI do it?

**Comment by vincent99** [comment]
API yes, compose no.  The UI only interacts with the API.

**Comment by raphink** [comment]
Do I need to create the service through the API then.

**Comment by vincent99** [comment]
Yes, you can add `secrets` to the `launchConfig` with an array of [secretReferences](http://docs.rancher.com/rancher/v1.5/en/api/v2-beta/api-resources/secretReference/).

```
{
  type: 'service',
  launchConfig: {
    imageUuid: '...',
    secrets: [
      {name: 'foo', secretId: '1s42', uid: "0", gid: "0", mode: "666"},
      ...
    ]
  }
}
```

**Comment by dsteegen** [comment]
Hi,

Is this feature still not working? When using the latest version of rancher-compose (0.12.5) I am not able to spin up a docker if the compose file contains secrets configuration.

Example config:

```
version: '2'
services:
  config:
    image: xxx
    env_file: bootstrap-config.env
    secrets:
    - GIT_CONFIG_REPO_USERNAME
    - GIT_CONFIG_REPO_PASSWORD
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: "/run/secrets/GIT_CONFIG_REPO_USERNAME"
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: "/run/secrets/GIT_CONFIG_REPO_PASSWORD"
    labels:
      io.rancher.container.pull_image: always
secrets:
  GIT_CONFIG_REPO_USERNAME:
    external: true
  GIT_CONFIG_REPO_PASSWORD:
    external: true
```

The error I get is: 

```
time="2018-03-01T08:49:20+01:00" level=error msg="Could not parse config for project rancher-v0.6.3 : Unsupported config option for config service: 'secrets'"
time="2018-03-01T08:49:20+01:00" level=fatal msg="Failed to read project: Unsupported config option for config service: 'secrets'"
```

We are using rancher version 1.6.6. The documentation clearly states that it should be possible. Is this feature still experimental? Or should I be using the rancher-cli instead? :)
