### ISSUE TITLE
Service links for lb targets are in "removed" state when Lb and target services are created using compose file.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7815]
Rancher Versions: Build from master

Steps to reproduce the problem:
Create a stack with Lb and target service using the following yml files:

```
version: '2'
services:
  hello1:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  hello2:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    links:
    - hello1:hello1
    labels:
      io.rancher.container.pull_image: always
  lblb:
    image: rancher/lb-service-haproxy:v0.5.9
    ports:
    - 1001:1001/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```
```
version: '2'
services:
  hello1:
    scale: 2
    start_on_create: true
  hello2:
    scale: 1
    start_on_create: true
  lblb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: foo.com
        priority: 1
        protocol: http
        service: hello1
        source_port: 1001
        target_port: 1001
      - priority: 2
        protocol: http
        service: hello2
        source_port: 1001
        target_port: 1002
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

Once the Lb is created , "linkedServices" for this service is null.

Expected Behavior:
"linkedServices" for the LB service should have all target services from targetPort of LB.
