### ISSUE TITLE
Service with uppercase/mixedcase name is not listed under latest/stacks/stackname/services

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7831]
Steps to reproduce:

1) Create a stack using following compose files:

````
version: '2'
services:
  WEB1:
    image: rancher/dns-service
    external_links:
    - test612432/test631753:test631753
    - test103067/test812486:test812486
  test337474:
    image: sangeetha/testclient:latest
    links:
    - WEB1:WEB1
    ports:
    - 32222:22/tcp
````

```
version: '2'
services:
  test337474:
    scale: 2
    start_on_create: true
```

2) Fetch rancher-metadata/latest/stacks/stackname/services. Service alias web1 is not listed. It is present in the latest/services list though
