### ISSUE TITLE
Need UUID for "links" in metadata

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7869]
One of the problems of using all lower case names in metadata. 

Scenario:
In the UI, the user created something like this:
```
stackONE:
  etcd:
  xyz:

stackone:
  etcd:
  lmn:

stackFOO: 
  bar: in the UI the user has picked a linked service from stackONE/etcd.
```

Now in the metadata, when I do:
```
curl -H "Accept: application/json" rancher-metadata/latest/services/bar/links
{"stackone/etcd":"etcd"}
```

Now any microservice working on the links wouldn't be able to figure what the stack the user is actually referring to.

So can we have `rancher-metadata/latest/services/bar/links_by_uuid` in metadata?
