### ISSUE TITLE
LB rule with selector removed when any labelled service removed

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#7892]
**Rancher Versions:**
Server: 1.4.1
 - Rancher/lb-service-haproxy:v0.5.9

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
openstack, centos7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA with external DB (galera)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
 - Balancer is used like global service (not deployed for specific stack/service)
 - LB service -> Add Selector Rule -> https,443 and target: loadbalancer.https=true
start two services with label 'loadbalancer.https: true' add lb_config

```
    lb_config:
      port_rules:
      - hostname: first.example.com
        target_port: 8080
```

```
    lb_config:
      port_rules:
      - hostname: second.example.com
        target_port: 8080
```

remove one of services, check rules on LB.

**Results:** 
Selector rule is removed with service, expected is that this rule will stay here (at least until all services with this label not removed).

**Comment by tcdev0** [comment]
+1 same here

**Comment by mhdev90** [comment]
+1 same issue.

Rancher Version:
* Server: 1.4.2
* rancher/lb-service-haproxy:v0.5.9

Docker Version:
* 1.12.6

**Comment by VAdamec** [comment]
Same for 1.5.1 and rancher/lb-service-haproxy:v0.6.2, Docker v1.13.1

**Comment by deniseschannon** [comment]
@VAdamec It would help me if you could put your full compose files for the load balancers and services to it'd be easier to reproduce and ensure we're doing the same steps. 

Could anyone give more details on how you are adding/removing services? Was it through the UI or compose? How are you checking the rules?

Are there additional rules or just 1 selector rule on the LB?

I assume your 2 services were started using CLI/rancher-compose as there is no UI support for adding in port rules to services being targeted by selectors.

I removed the service through the UI. 

I am unable to reproduce in v1.5.3 using `lb-service-haproxy:v0.6.2`

Steps I did:

1. I started a load balancer using selector rules with 2 services being picked up by doing "Add Stack and inputting the following compose"

docker-compose.yml

``` 
version: '2'
services:
  lb1:
    image: rancher/lb-service-haproxy:<version>
    ports:
    - 81
  web1:
    image: nginx
    labels:
      foo: bar
  web2:
    image: nginx
    labels:
        foo: bar
```

rancher-compose.yml
```
version: '2'
services:
  lb1:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 81
        # Target any service that has foo=bar as a label
        selector: foo=bar
        protocol: http
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  # web1 and web2 are targeted with the same source port but with the different hostname and path rules
  web1:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 80
        hostname: test.com
  web2:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 80
        hostname: example.com/test     
```

2. From the UI, I can see the load balancer and 2 services. I check the yaml of the stack by clicking on "View Config" from the dropdown of the stack. I also check the LB that the HAProxy is programmed correctly for both services by execing into the LB container and viewing `/etc/haproxy/haproxy.cfg`

3. From the UI, I delete one of the services. I re-check the yaml of the stack and the

```
selector: foo=bar
``` 

part of the lb_config is still in.

I check the HAProxy and confirm that there is still 1 service being targetted.

I tried these steps with a load balancer with a specific scale as well a load balacner with a global scale. Both times, after deleting one of 2 services, the port rules on the load balancer still remained.
