### ISSUE TITLE
docker-compose: docker-compose yaml is modified by Rancher on ingest, so export config differs from original yaml

### ISSUE THREAD

**Issue by waarg** [rancher/rancher#7895]
**Rancher Versions:**
Server: 1.3.2
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): NA

**Docker Version:**
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
RedHat 7, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 node HA + external (RDS) database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create a stack from dockercompose.yml, with several labels in alphabetical order:

```
version: '2'
services:
  nginx:
    image: nginx
    labels:
      a_key: "a_value"
      b_key: "b_value"
      c_key: "c_value"
      d_key: "d_value"
      e_key: "e_value"
      f_key: "f_value"
      g_key: "g_value"
```

2. Once created, view the stack in compose view in Rancher, or Export config.
3. Compare the docker-compose.yml output here, to the original docker-compose.yml
4. Observe ordering of labels
4. Perform an upgrade, adding another label
5. Again, observe ordering of labels

**Results:** 

The ordering of the labels changes. We have also observed similar changes in ordering at each yaml indent level.

This interferes with third-party tools such as Terraform that use export config to maintain state.
