### ISSUE TITLE
rancher-nfs custom NFS server driver_opts don't create subfolders

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7906]
**Rancher Versions:**
storage-nfs: v0.6.5

**Steps to Reproduce:**
1. Create and mount an NFS volume using custom `host` and `export` driver_opts. For example:
```
volumes:
  vol1:
    driver: rancher-nfs
    driver_opts:
      host: 1.2.3.4
      export: /data
```

**Expected:** A subfolder is created on the NFS server and is mounted

**Actual:** The root export path is mounted

We want to preserve the ability to mount the root export for advanced users, so add a new driver_opt `no_subfolder` that, when set to `true`, will mount the root export path like it currently does.

**Comment by LLParse** [comment]
Ready for testing in master

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.0-rc4 and nfs-driver version - rancher/storage-nfs:v0.8.2

Create service with volumes in nfs-driver using driver_opts (export and host) using the following yml:

```
volumes:
  yello11:
    driver_opts:
      export: /var/nfs
      host: ****
    driver: rancher-nfs
services:
  nginx1:
    image: nginx
    volumes:
    - yello11:/data1
```

Volume name ( in this case <stack_name>_<vol_name>_xxx) gets created as directory under the <export-directory> in rancher server host specified in host field.
