### ISSUE TITLE
Internal Rancher DNS does not work with host network

### ISSUE THREAD

**Issue by kamrar** [rancher/rancher#7945]
I am planning to upgrade my rancher version from v.1.1.1 to one of the newest releases.
During my simple tests I noticed this problem. It was tested on many different environments with different rancher versions v1.2.0+ (v1.5.0-alpha1,v1.4.1,v1.3.4,v1.3.0).

**Rancher Versions:**
Server: v1.5.0-alpha1
healthcheck: v0.2.3
ipsec: 0.0.4
network-services: v0.0.15
scheduler: v0.5.0

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Tested on multiple environment , Bare metal - Ubuntu16 , Cloud - Centos7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Tested on multiple environment
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Use this docker-compose to create test stack
```
version: '2'
services:
  test:
    image: alpine
    hostname: alpine
    stdin_open: true
    network_mode: host
    tty: true
    command:
    - /bin/sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
```
2. Try to run `ping alpine` inside the container
![zaznaczenie_037](https://cloud.githubusercontent.com/assets/5478883/23283697/c494c46e-fa27-11e6-80bc-654639164780.png)

**Results:** 
Ping is not working with selected hostname.
This test case is working with rancher below version 1.2.
Switching to managed network is fixing the problem but with my current environment I can't use it.

Is it possible to ping the container by using only selected hostname with internal dns and host network ?
