### ISSUE TITLE
Selector service containers should appear in the stack box on the Hosts page

### ISSUE THREAD

**Issue by imikushin** [rancher/rancher#7992]
**Rancher Versions:**
All (as of v1.5.0)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create `mystack` stack in the UI and put the following as docker-compose.yml:
```yaml
version: '2'
services:
  myservice:
    image: rancher/none
    labels:
      io.rancher.service.selector.container: my.selector=foo
```

2. Run `my-container` container with the selector label: Key: `my.selector`, Value: `foo`

**Results:** 
On the User Stacks page, `myservice` shows it has 1 container, and if you click the service link, you'll see `my-container` listed in the Containers tab on the Service page. 

But! On the Hosts page, `my-container` is shown as a standalone container, and `mystack` is shown as it has no containers.
