### ISSUE TITLE
Add an option to request to remove services in a stack when upgrading using a compose file

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7993]
Example:
 
Stack A contains service A and B.
Upgrade stack, remove service A from both docker-compose and rancher-compose. Made some changes in service B. Upgrade stack.
Service B is upgraded. But service A is not removed even after clicking finish upgrade.

Currently, as expected service A would not be removed as we only remove services based on explicit removal.

Enhancement: Add in new option that would remove all other services in the stack except for the ones remaining in the compose file.

**Comment by deniseschannon** [comment]
Need to add `--prune` so that you can do `rancher up --prune` so that any services that are in the existing stack that are not in the compose file woudl be removed.

**Comment by carolynhu** [comment]
Example of this issue. Say, user has a docker compose file as follows
Compose1.yml
```
services:
	serviceA:
	serviceB:
	serviceC:
```
when he run ```rancher up```,  it will create service A, B, and C in a stack.
After a while, the user modifies his compose file to Compose2.yml
Compose2.yml
```
services:
	serviceA:
	serviceB:
	serviceD:
```
when he run ```rancher up --prune```,  our CLI should not only creating a new serviceD successfully, but also should delete serviceC, which does not exist in current compose file anymore.

My idea for solving this issue is as follows:
In rancher-compose-executor, cliMain() code path, 
1. Add ```prune``` flag in for cli.Flag
2. Before rancher.NewProject(context) being called, setting rancher.context.prune = cli.context.Bool("prune")
3. NewProject() function will call open() and parse() function to process current compose file. Try to find an appropriate place for getting all services' name of the old stack. Then, save this info into a new context field, for example, existingServiceName. 
or get this existingServiceName info at any appropriate place before creating new services based on current compose file (Compose2.yml in this case).
4. After creating new services based on current compose file. Check if cli.context.Bool("prune") == true, if so, need to call delete() function, and it will do the two things
(4-1) compare with existingServiceName, pick up those old services do not appear in current compose file 
(4-2) delete those extra services

**Comment by carolynhu** [comment]
Manually tested:
1.Create a stack with name "myStack" with serviceA, B, and C in UI, then run ```rancher up -s myStack --prune``` with new compose file contains service A, B, and D. Check whether service C being deleted, service D being created, and service A and B keep alive.
2.```rancher up``` with compose file contains serviceA, B, and C, then ```rancher up --prune``` with new modified compose file contains A, B, and D. Check whether service C being deleted, service D being created, and service A and B keep alive.

**Comment by cjellick** [comment]
@sangeethah when you (or whoever) qa this, can you review and merge the validataion test pr as well?

**Comment by sangeethah** [comment]
@cjellick sure.Will do.

**Comment by soumyalj** [comment]
Tested with rancher v1.6.11-rc1 using CLI 0.6.5-rc1. Created stack "mystack" in UI with the test.yml file below:
```
version: '2'
services:
  service1:
    image: nginx
    stdin_open: true
    tty: true
  service2:
    image: nginx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
Used --prune in CLI with test1.yml as below:
```
./rancher up -d --prune --stack mystack --file test1.yml

```
```
version: '2'
services:
  service2:
    image: nginx
    stdin_open: true
    tty: true
  service3:
    image: nginx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

service1 was successfully deleted from the stack and service3 was added to the stack
The above steps were repeated by creating a stack through CLI to start with.
