### ISSUE TITLE
K8s Ingress Controller not updating on service name change in ingress

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8010]
**Rancher Versions:**
Server:
rancher/server:v1.5.0-rc1

kubernetes (if applicable):
1.5.2-rancher1-3

**Docker Version:**
v1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher OS KVM

Testing Blue/Green Deployments in 1.5.0-rc1

Yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: blue
    spec:
      containers:
        - image: cloudnautique/hello-world:light
          name: webserver-hello
          ports:
            - containerPort: 80
              name: http-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: green
    spec:
      containers:
        - image: cloudnautique/hello-world:dark
          name: webserver-hello
          ports:
            - containerPort: 80
              name: http-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
spec:
  backend:
    serviceName: webserver-blue
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-blue
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    type: webserver
    color: blue
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-green
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    type: webserver
    color: green
```

Editing the ingress controller like:
`kubectl edit ingress webapp` to point to the webserver-green service does not reroute traffic.

Likewise, using a single service, and updating the service selector using:
`kubectl edit svc webserver` and pointing to green.
