### ISSUE TITLE
K8s updating service selectors doesn't update ingress controller

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8011]
**Rancher Versions:**
Server: rancher/server:v1.5.0

kubernetes (if applicable):
1.5.2-rancher1-3

Testing Blue Green Deployments with service selectors: 

Yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: blue
    spec:
      containers:
        - image: cloudnautique/hello-world:light
          name: webserver-hello
          ports:
            - containerPort: 80
              name: http-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: green
    spec:
      containers:
        - image: cloudnautique/hello-world:dark
          name: webserver-hello
          ports:
            - containerPort: 80
              name: http-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
spec:
  backend:
    serviceName: webserver
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    type: webserver
    color: blue
```

performing `kubectl edit svc webserver` and chaging color to green doesn't result in an update to the ingress controller.
