### ISSUE TITLE
Rancher cli can't create a service with secret specified in docker-compose

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8025]
**Rancher Versions:**
Server: v1.5.0-rc3

Rancher-cli: v0.5.0-rc1

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

- Deploy the secret catalog volume driver
- Create a new secret and get its id
- Try to run the following docker-compose file with rancher cli:

```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
    - uid: '0'
      gid: '0'
      mode: '444'
      name: foo
      secretId: 3
    labels:
      io.rancher.container.pull_image: always
```
```
rancher up -f docker-compose.yml
```
**Results:** 
```
ERRO[0001] Could not parse config for project catalogs : Unsupported config option for test service: 'secrets' 
FATA[0001] Failed to read project: Unsupported config option for test service: 'secrets'
```

**Comment by soumyalj** [comment]
Tested with master having rancher-compose executor using rancher-cli version vtest and v0.6.0-rc2.
Creation of service with secret specified using docker-compose file is successful. Tested with both long format and short format for secrets. Example docker-compose file:
```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
      - source: mylongsecret
        target: mylongsecretincontainer
        uid: '104'
        gid: '103'
        mode: 444
secrets:
  mylongsecret:
    file: ./secretvalue
soumyas-MacBook-Pro:rancher-vtest soumya$ cat secret_short_file_specified.yml
version: '2' 
services:
  test:
    image: nginx
    secrets:
      - mytestsecret
secrets:
  mytestsecret:
    file: ./secretvalue
```
