### ISSUE TITLE
If a variable used in catalog templating is not defined , we should error out.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8026]
Tested with v1.5.0-rc3 version and rancher cli version - v0.5.0-rc1

If a service is started with the following docker-compose yml without defining the variable PORT , service gets created with no ports definition.

```
version: '2'
services:
  web:
    image: sangeetha/testnewhostrouting
    {{- if eq .Values.PORT "standard" }}
    ports:
    - 8000:80
    {{- else }}
    ports:
    - 8000:81
    {{- end }}
```

Expected behavior:

We should either error out in this case or if there is a catch all block (like the else part i the yml above) we should execute that logic.
