### ISSUE TITLE
Rancher Server 1.5 - Catalog Variables 'Not Defined' On Stack Launch

### ISSUE THREAD

**Issue by gromit6891** [rancher/rancher#8051]
**Rancher Versions:**
Server: 1.5
healthcheck: latest
ipsec: latest
network-services: latest
scheduler: latest
kubernetes (if applicable):

**Docker Version:**
1.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Xenial - VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create catalog using variables
Example docker compose file beginning:
```
version: '2'
services:

  myservice:
    build: https://github.com/mycontainer.git#master
    environment:
      MY_VNAME: ${MY_VNAME}
      MY_SNAME: othername
```
**Results:** 
  (template: template:57: function "MY_VNAME" not defined)

**Comment by deniseschannon** [comment]
Do you have a corresponding rancher-compose.yml with it?

**Comment by joshwget** [comment]
@gromit6891 Can you also provide a little more information on how you launched this? Was this through the catalog, Rancher CLI, or Rancher Compose CLI?

**Comment by gromit6891** [comment]
This was launched via the catalog.
The corresponding rancher-compose file begins:
```
.catalog:
  version: 1
  questions:
    - variable: MY_VNAME
      description: Specify the name of the site.
      label: Site domain name
      required: true
      default: mysite.com
type: string
```
This worked fine with version 1.4.1. I see in the release notes about template variable interpolation, that the variable declarations are surrounded by quotes:
```
# bracketed name
    command: "${COMMAND}"
```
I'll give that a try.
