### ISSUE TITLE
Impossible to start the Rancher Server on macOS

### ISSUE THREAD

**Issue by mytototo** [rancher/rancher#8056]
**Rancher Versions:** server:stable

**Docker Version:** 17.03.0-ce, build 60ccb22

**OS and where are the hosts located? (cloud, bare metal, etc):** Docker for macOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Docker-compose.yml

```yml
version: '2'

services:
  rancher_mysql:
    build: ./containers/rancher_mysql
    restart: always

  rancher_server:
    build: ./containers/rancher_server
    restart: always
    depends_on:
      - rancher_mysql
```

MySQL Dockerfile:

```dockerfile
FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD = qwerty
ENV MYSQL_DATABASE = cattle
ENV MYSQL_USER = cattle
ENV MYSQL_PASSWORD = qwerty
```

Rancher Server Dockerfile:

```dockerfile
FROM rancher/server:stable

ENV CATTLE_DB_CATTLE_MYSQL_NAME = cattle
ENV CATTLE_DB_CATTLE_USERNAME = cattle
ENV CATTLE_DB_CATTLE_PASSWORD = qwerty
```

**Results:** 

Error from the Rancher Server:

```bash
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= cattle COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8'' at line 1
```
