### ISSUE TITLE
Scheduler violates hard anti-affinity constraint when sidekick present

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#8070]
**Rancher Versions:**
Server: v1.4.1
scheduler: v0.6.3

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single internal

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Add 7 hosts to a cattle environment
2. Create a 7-node etcd from community catalog
3. Power cycle 3 hosts

**Results:** 
2 etcd land on same host, violating `io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}` constraint

![image](http://i.imgur.com/ydh2lm5.png)

EDIT: Removing the sidekick data container appears to have fixed this, so it is a distinct possibility that only services with sidekicks are afflicted.

**Comment by LLParse** [comment]
This is particularly dangerous because these 2 containers end up consuming the same named volume, potentially corrupting the data.

**Comment by LLParse** [comment]
I just reproduced this with a _fresh_ deployment of etcd, which leads me to believe this is a regression.

![fresh install](http://i.imgur.com/ylLR401.png)

**Comment by schuylr** [comment]
Can confirm the issues above. I have a theory concerning the data containers as I was running a modified version of your latest etcd image without them, I'm going to try a modified service and see if it helps.

**Comment by schuylr** [comment]
@LLParse Here's the docker and rancher compose that I'm running as a modified service. Basically I have removed the data sidekick containers.

docker-compose.yml:
```
etcd:
    image: rancher/etcd:v2.3.7-11
    labels:
        io.rancher.scheduler.affinity:host_label_soft: etcd=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
        RANCHER_DEBUG: 'true'
        EMBEDDED_BACKUPS: 'true'
        BACKUP_PERIOD: '15m'
        BACKUP_RETENTION: '24h'
    volumes:
    - /var/etcd-test:/data-backup
```

rancher-compose.yml:
```
etcd:
  scale: 7
  retain_ip: true
  health_check:
    port: 2378
    request_line: /health
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
```

I don't see any affinity issues yet. I think the data containers (or something with the way Cattle handles sidekick or started-once containers) triggers the problem but I'm not sure. Since you have a much quicker way to reproduce the problem (I don't have 7 test machines spun up right now) - would you like to try this one out?
