### ISSUE TITLE
Top level keys for various existing service types

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8093]
Support top level keys for various service types that were previously just under the `services` key.

For example, load balancers should change in the following way.

```
services:
  lb:
    image: ...
    lb_config:
      port_rules:
      - ...
```
->
```
load_balancers:
  lb:
    image: ...
    port_rules:
    - ...
```

The fields in `lb_config` are now directly part of the service. `storage_drivers` and `network_drivers` are the other keys that should be top level in this way.

```
version: '2'
storage_drivers:
  test:
    image: nginx
    storage_driver:
      name: rancher-efs
      scope: environment
      volume_access_mode: multiHostRW
```

```
version: '2'
network_drivers:
  test-driver:
    image: nginx
    network_driver:
      name: Rancher VXLAN
      default_network:
        name: vxlan
```
