### ISSUE TITLE
Dependencies in a Compose file

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8094]
Compose files should support dependencies on existing catalog templates.

```
stacks:
  database:
    template: community:mysql

services:
  wordpress:
    ...
    external_links:
    - database/mysql:db
```

(`dependencies` might be a better key for this`)

Services within a dependency should be referenced as if they were part of another stack with the name of the dependency (`database` in this case). The actual stack name should probably be prefixed to avoid naming collisions when launching two stacks with the same dependency.

All dependent stacks should be successfully started before starting services in the current stack.

An optional `version` key is probably necessary.

```
stacks:
  database:
    template: community:mysql
    version: v3.2-rancher2
```

Questions for dependent stacks likely need to bubble up to the current stack, though this is still to be determined.
