### ISSUE TITLE
API metadata JSON depth removed with service upgrade

### ISSUE THREAD

**Issue by jri-sp** [rancher/rancher#8100]
**Rancher Versions:**
Server: 1.5.1

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** VM with CoreOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external Galera DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add long JSON (more than 8 level I think) in metadata field of rancher API:
Example:
```
{
	"es": {
		"indexes": {
			"isari": {
				"settings": {
					"analysis": {
						"analyzer": {
							"default": {
								"type": "custom",
								"tokenizer": "standard",
								"filter": [
									"lowercase",
									"asciifolding"
								]
							}
						}
					}
				}
			}
		}
	}
}
```
Or in my rancher-compose.yml:
```
  myapp:
    metadata: 
      config:
        es:
          indexes:
            isari:
              settings:
                analysis:
                  analyzer:
                    default:
                      type: custom
                      tokenizer: standard
                      filter:
                      - lowercase
                      - asciifolding
```

Screenshot when put config:  https://i.imgur.com/kvkC5SV.png

Screenshot when applied (which is good): https://i.imgur.com/vNpSf1o.png

and **upgrade** the service concerned.

**Results:** 

The fields at the end of JSON tree are replaced by "null".

Screenshot of the mess: https://i.imgur.com/fNPLidE.png

So I had to cut my JSON in different branch to reduce it and join them with a script (which suppose a new sidekick container to do that), which is not really as easiest as just put it in API and read it in my application.

Ask me for details if needed.
