### ISSUE TITLE
Path-based routing Ingress not working

### ISSUE THREAD

**Issue by jamelseagraves** [rancher/rancher#8125]
**Rancher Versions:**
Server: 1.5.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04; AWS EC2 instance

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

I am running a Kubernetes cluster (which has the default rancher-ingress-controller) and trying to use an ingress with path-based routing. I first run some service/deployment (i.e. nginx-svc) and then create an ingress as follows:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: nginx-svc
          servicePort: 80
```
Then I make a request to the host ip address with a path i.e. `curl -i http://1.2.3.4/foo`

**Results:** 
I get the following response:
```
HTTP/1.1 404 Not Found
Date: Thu, 09 Mar 2017 02:13:49 GMT
X-FRAME-OPTIONS: SAMEORIGIN
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 280
Server: Jetty(9.2.13.v20150730)
...
```
However, if I change the path in the ingress config file to just "/" such that the yaml looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
```
then run `curl -i http://1.2.3.4/`, everything works fine; I get a valid response:
```
HTTP/1.1 200 OK
Date: Wed, 08 Mar 2017 17:58:17 GMT
X-FRAME-OPTIONS: SAMEORIGIN
Content-Type: text/html
Content-Length: 6047
Server: Jetty(9.2.13.v20150730)
```

Thanks in advance for any help!
