### ISSUE TITLE
side kick container never gets into started state.

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8142]
**Rancher Versions:**
Server: 1.4.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04.1 - AWS

**Steps to Reproduce:**
a side kick container containing a large filesystem 

**Results:** 
When starting a container with a lot of data docker takes a while to copy that data.  that happens during "start" so rancher sends the start call,  but times out waiting for the start to finish. We end up trying some 15 seconds later, but in the mean time the container started and then stops...  so the stop event gets sent to cattle and we stop it and cancel the start.  so the container goes to stopped state but we never technically saw it running.  so the startCount is 0 and the state is considered bad.  Rancher doesn't start the container again, which @ibuildthecloud states 'seems like a problem'.

Reach out for repro image and stack yaml

**Comment by cjellick** [comment]
Testing with:
```
test:
  tty: true
  image: debian
  command:
  - bash
  stdin_open: true
  labels:
    io.rancher.sidekicks: test-data
test-data:
  tty: true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /big
  command:
  - echo
  - hi
  image: cjellick/big:11g
  stdin_open: true
```

**Comment by cjellick** [comment]
available on master

**Comment by sangeethah** [comment]
Tested with latest build from master:

Created a stack with following yml:
```
  tty: true
  image: debian
  command:
  - bash
  stdin_open: true
  labels:
    io.rancher.sidekicks: test-data
test-data:
  tty: true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /big
  command:
  - echo
  - hi
  image: cjellick/big:11g
  stdin_open: true
```

Sidekick container is "starting" state for a long time until docker copies data from the image to a volume. Once this is done container gets to "stopped" state as expected with green status -checkered pattern circle -  in UI since it is “start_once” and “startCount”: 1 .

Also all  existing automation test cases relating to stopping container from host and waiting for reconcile to get triggered work as expected.
