### ISSUE TITLE
log_driver settings is not working.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8156]
Rancher server version - Build from master

Steps to reproduce the problem:
Create a service with following yml files where log_driver is set to  syslog.
This setting does not take effect for the containers of the service.
log_driver is set to json-file - inspect["HostConfig"]["LogConfig"]["Type"] shows 'json-file'

```
Sangeethas-MBP:rccmds sangeethahariharan1$ cat dc3.yml 
test3:
  cap_drop:
  - BLOCK_SUSPEND
  - CHOWN
  log_driver: syslog
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: rancherhost
  pid: host
  log_opt: {}
  image: ubuntu:14.04.3
  cpu_shares: 256
  privileged: true
  stdin_open: true
  mem_limit: 104857600
  cap_add:
  - AUDIT_CONTROL
  - AUDIT_WRITE
Sangeethas-MBP:rccmds sangeethahariharan1$ cat rc3.yml 
test3:
  scale: 3
Sangeethas-MBP:rccmds sangeethahariharan1$ 
```
