### ISSUE TITLE
Creation of stacks with invalid keys in docker-compose file does not error out

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8169]
**Rancher Versions:**
Server:Master 

**Docker Version:** 17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack with invalid key for services/loadbalancers in the docker-compose yml file as below :
```
version: '2'
servicesabc:
  service2:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
loadbalancersabc:
  lb1:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 8010:8010/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    scale: 1
    start_on_create: true
    certs: []
    port_rules:
     - priority: 1
       protocol: http
       service: service2
       source_port: 8010
       target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
```

**Results:** 
The stack gets created without any service/loadbalancer. 

Expected:
It should give out an error that the keys used in the yml file are invalid and stack creation should fail
