### ISSUE TITLE
Feature Request: Use secret names instead of secretId in rancher-compose

### ISSUE THREAD

**Issue by siosphere** [rancher/rancher#8184]
Allow specifying the secret name instead of the secretId in rancher-compose.yml files. Right now you have to initially make the stack in the RancherUI in order to get the secretIds that are used. Otherwise you have to view the secrets in the API in order to get the ID for use in the compose file, which is annoying.

Change secretId to secretName
```
secrets:
    - gid: '0'
      mode: '444'
      name: ''
      secretName: 'mysecret.Name'
      uid: '0'
```
