### ISSUE TITLE
Panic when launching a stack having service with secrets using an invalid yaml file 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8195]
**Rancher Versions:**
Server:Master with rancher executor

**Rancher CLI version**:  vtest

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a secret through Rancher UI
2. Using Rancher CLI launch a stack having service with secrets using an invalid yaml file 
```
./rancher up -d -f secretsdc.yml
```
Ex: docker compose file
```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
    - uid: '0'
      gid: '0'
      mode: '444'
      name: mysecret
      secretId: 1
    labels:
      io.rancher.container.pull_image: always

```
**Results:** 
The up command fails with a panic. No useful message to user is provided
```
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
panic(0x634c80, 0xc42036dc40)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc4204c6968)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0x634c80, 0xc42036dc40)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.parseValidTypesFromSchema(0xc4203862d0, 0xc42042fb40, 0x15, 0x0, 0xc42042fb40, 0x15)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/schema_helpers.go:72 +0x6e5
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.oneOfMessage(0xc4203a4720, 0xc4203862d0, 0xa2e340, 0xc42036da00, 0xa2ddc0, 0xc42036d9c0, 0x5ac000, 0xc42048def0)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:162 +0x5d5
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.generateErrorMessages(0xc4203a4720, 0xc4203862d0, 0xc42042f280, 0xc420393b40, 0xc42042f280)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:258 +0x10f4
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.validateV2(0xc420386120, 0xc4203862a0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/validation.go:222 +0x127
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.MergeServicesV2(0xc420315f80, 0xa24e60, 0xc420315f40, 0xa24ea0, 0xa6da68, 0x7fff5fbffce0, 0xd, 0xc420386120, 0x0, 0xc41ffe7645, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/merge_v2.go:13 +0x43
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config.Merge(0xc420315f80, 0xa24e60, 0xc420315f40, 0xa24ea0, 0xa6da68, 0x7fff5fbffce0, 0xd, 0xc42037c000, 0xf1, 0x2f1, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/config/merge.go:154 +0xe52
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project.(*Project).load(0xc4200f0a50, 0x7fff5fbffce0, 0xd, 0xc42037c000, 0xf1, 0x2f1, 0xc4201ae1b8, 0x12ac8)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project/project.go:178 +0xc6
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project.(*Project).Parse(0xc4200f0a50, 0xc4200f0a50, 0x5)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/project/project.go:113 +0x15a
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/rancher.NewProject(0xc42032c300, 0x70813c, 0x4, 0x300)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/rancher/project.go:35 +0x246
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app.(*RancherProjectFactory).Create(0xc4204c63c0, 0xc42033ef00, 0x4, 0x7fff5fbffce0, 0xd)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app/app.go:66 +0x6b2
github.com/rancher/cli/cmd.(*projectFactory).Create(0xa6da68, 0xc42033ef00, 0x8, 0xc420315de0, 0xc420315e00)
	/go/src/github.com/rancher/cli/cmd/up.go:63 +0x390
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app.WithProject.func1(0xc42033ef00, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose-executor/app/app.go:104 +0x4e
reflect.Value.call(0x5ed4e0, 0xc420314c20, 0x13, 0x707a78, 0x4, 0xc4204c6908, 0x1, 0x1, 0x9ee38, 0x6ee4a0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x5ed4e0, 0xc420314c20, 0x13, 0xc4204c6908, 0x1, 0x1, 0x55, 0x140, 0x140)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x5ed4e0, 0xc420314c20, 0xc42033ef00, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0x707231, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x715fa5, 0x15, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc42032c180, 0xc42007c080, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.mainErr(0x0, 0xc420354750)
	/go/src/github.com/rancher/cli/main.go:150 +0x20e6
main.main()
	/go/src/github.com/rancher/cli/main.go:37 +0x26


```

**Comment by besishblia** [comment]
Same bug in 1.6.0
I found, if mode value not in quotas, i get another error
time="2017-05-31T13:48:56+03:00" level=error msg="Failed Creating btl-postgres : Failed to find secret " 
time="2017-05-31T13:48:56+03:00" level=error msg="Failed to start: btl-postgres : Failed to find secret " 
time="2017-05-31T13:48:56+03:00" level=fatal msg="Failed to find secret "

My yaml: 
secrets:
    - name: POSTGRES_PASSWORD
      secretId: 21
      mode: 444
      uid: '0'
      gid: '0'

**Comment by joshwget** [comment]
@besishblia Secrets are currently exported with the incorrect syntax. Please checkout the [docs on secrets](https://docs.rancher.com/rancher/v1.6/en/cattle/secrets/) for the proper syntax.

**Comment by ivan-exness** [comment]
@joshwget And how it help us ? Can we fix it ourself ?

**Comment by ivan-exness** [comment]
I have fix my catalog yml files.
Now it dont fail. But secrets node are not present in stack after deploy.

**docker-compose from preview section before deploy**
```
  private-backend:
    image: registry.exness.io/site/py:master
    environment:
      CONFIG_TOKEN: ${CONFIG_TOKEN}
      ENV: ${CONFIG_ENV}
      MIGRATE_DB: ${MIGRATE_DB}
      SERVER_NAME: ${SERVER_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      SENTRY_PRIVATE_DSN: ${SENTRY_PRIVATE_DSN}
    stdin_open: true
    secrets:
    - config-token
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    - private-locale
    - private-templates
    - private-pages
    labels:
      io.rancher.container.pull_image: always
  private-nginx:
    image: registry.exness.io/dockerhub/nginx:exness-custom
    environment:
      UPSTREAM: private-backend:8000
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: private-pages,private-backend,private-static,private-frontendsource,private-locale,private-templates
secrets:
  config-token:
    external: true
```
**docker-compose file after deploy**
```
  private-backend:
    image: registry.exness.io/site/py:master
    environment:
      CONFIG_TOKEN: config-token
      ENV: qa-server
      MIGRATE_DB: 'false'
      SENTRY_PRIVATE_DSN: https://4a9ce600aebc48809144c9d43c850bb4:007a1a117cde48a4bddf3eab3e46c514@sentry.test.env/11
      SERVER_NAME: dev-v2-01
      WEB_CONCURRENCY: '3'
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    - private-locale
    - private-templates
    - private-pages
    labels:
      io.rancher.container.pull_image: always
```
