### ISSUE TITLE
ipsec: disable icmp redirects

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8203]
Currently in the ipsec container, the control for sending redirects is enabled. Need to disable that.

```
root@a961dbd70b43:/# echo 0 > /proc/sys/net/ipv4/conf/all/send_redirects
bash: /proc/sys/net/ipv4/conf/all/send_redirects: Read-only file system
root@a961dbd70b43:/#
```

**Comment by leodotcloud** [comment]
Blocked by: https://github.com/rancher/rancher/issues/8243

**Comment by leodotcloud** [comment]
Tried setting the following in `docker-compose.yml`:
```
      net.ipv4.conf.all.send_redirects: '0'
      net.ipv4.conf.default.send_redirects: '0'
```

But these settings are not being set on newly created interfaces.
```
root@39543f9b5e7c:/# sysctl -a | grep send_redirects
sysctl: reading key "kernel.unprivileged_userns_apparmor_policy"
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.eth0.send_redirects = 1
net.ipv4.conf.lo.send_redirects = 1
```

Tried setting each of them individually, but didn't work.

Reference: http://marc.info/?l=linux-kernel&m=123606366021995&w=2

The behavior seems to be different inside the containers. Need to investigate further if this needs to be handled in the CNI plugin.

**Comment by leodotcloud** [comment]
```
    sysctls:
      net.ipv4.conf.all.send_redirects: '0'
      net.ipv4.conf.default.send_redirects: '0'
      net.ipv4.conf.eth0.send_redirects: '0'
```

This works.
