### ISSUE TITLE
Creating a stack (through UI) having secrets with file specified in the yaml should error out that file does not exist

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8219]
Rancher Versions:
Server: Master with rancher-compose executor

**Docker Version:**1.12.6

Rancher CLI version: vtest

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

Steps to Reproduce:

1. Create a cattle setup and install secrets driver from catalogs
2. Create a secret "mysecret" through UI
3. Create a stack with service using secrets through rancher CLI. Specify a file "secretvalue" Example yaml file below:
```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
      - source: mylongsecret
        target: mysecretincontainer
        uid: '104'
        gid: '103'
        mode: 444
secrets:
  mylongsecret:
    file: ./secretvalue
```
Results:
The stack creation is successful and it does not error out that the file ```secretvalue``` does not exist. Looks like it finds the secret "mysecret" and ignores other specifications in the yaml file

**Expected**
It should error out that the file does not exist.
