### ISSUE TITLE
load balancer container clobbers > 1 custom backend

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#8226]
Many sites require customization to haproxy. For example, Seafile needs to have `/seafhttp` stripped from the path and sent to a different listener. This requires two backends in haproxy. Another example would be using haproxy to route to a host or service outside of Rancher (and thus not appearing in the dropdown). 

It's easy to add multiple backends into the custom section, but when adding more than one backend that isn't already defined in the services list above, only the last one is added to the config.

**Rancher Versions:**
Server: 1.4.1

**Steps to Reproduce:**

* create a service with a load balancer
* in the custom config section, add two backends
* commit the change

**Results:** 
* check the compiled configuration and see that only the last one appears

**Comment by oskapt** [comment]
This is still present in v0.6.2 of `lb-service-haproxy`. My workaround is to take anything that needs multiple backends or custom backend configuration and send it from a main ingress LB to a stack-focused LB where so far I've only needed one additional backend.

**Comment by janeczku** [comment]
Reproduced on Rancher v1.6.2 with rancher/lb-service-haproxy:v0.7.5

**Steps to reproduce**

Create a loadbalancer with the following configurations:

1. docker-compose

```yaml
version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

2. rancher-compose

```yaml
version: '2'
services:
  test:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        backend foo
        mode http

        backend bar
        mode http
      port_rules:
      - priority: 1
        protocol: http
        service: hello-world
        source_port: 9074
        target_port: 80
```

**Expected**

haproxy configuration includes `backend foo` and `backend bar`

**Actual**

haproxy configuration includes only `backend bar`

**Comment by alena1108** [comment]
Can be tested with haproxy v0.7.9

**Comment by sangeethah** [comment]
Tested with rancher-server version v1.6.8-rc1

When having multiple entries in the custom haproxy.cfg (these are new entries that does not exist in the haproxy config) , all entries get appended to the haproxy config as expected.

Tested with the following config:
```
version: '2'
services:
  hello1:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  hello2:
    image: sangeetha/testnewhostrouting
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  testme123:
    image: rancher/lb-service-haproxy:v0.7.8
    ports:
    - 8989:8989/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

```
version: '2'
services:
  hello1:
    scale: 1
    start_on_create: true
  hello2:
    scale: 1
    start_on_create: true
  testme123:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend 80
                  bind *:80
                  mode http
                  redirect scheme https code 301 if !{ ssl_fc }

                listen stats
                  bind *:9000
                  mode http
                  stats enable
                  stats hide-version
                  stats realm Haproxy\ Statistics
                  stats uri /haproxy_stats
      port_rules:
      - priority: 1
        protocol: http
        service: hello1
        source_port: 8989
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```


In this case ,  ```frontend 80``` and ```listen stats``` get added to the haproxy configuration as expected.

```
frontend 80
              bind *:80
              mode http
              redirect scheme https code 301 if !{ ssl_fc }
listen stats
              bind *:9000
              mode http
              stats enable
              stats hide-version
              stats realm Haproxy\ Statistics
              stats uri /haproxy_stats

```
