### ISSUE TITLE
resolving service alias with periods (DNS)

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#8232]
refactored from #7970.
---
We have a service alias, and link to it from another service using an alias for a fqdn. In 1.1.4 the aliased link resolves to the address of the service alias, where as in 1.4.1 it returns the address found on external DNS for the fqdn.

```
  nginx:
    image: xxx:nnn/nginx/master:latest
    external_links:
    - global/api:api.www.7943.xxx.se
    volumes_from:
    - dddd
    labels:
      io.rancher.sidekicks: dddd
      io.rancher.container.hostname_override: container_name
```

in the nginx service, `api.www.7943.xxx.se` does not resolve to the address of `global/api`, as it does in 1.1.4.

The rancher dns service has records like this, both on our 1.1.4 and 1.4.1 systems, for the nginx service:

```
  "10.42.248.210": {
    "search": [
      "7921-dddd.rancher.internal",
      "zzz.7921-dddd.rancher.internal",
      "rancher.internal"
    ],
    "recurse": [],
    "authorative": [],
    "a": {
      "api.www.7921.dddd.mr.xxxxx.se.global.rancher.internal.": {
        "answer": [
          "10.42.100.102"
        ]
      },
      "api.www.7921.trinidad.mr.ocean.svenskaspel.se.rancher.internal.": {
        "answer": [
          "10.42.100.102"
        ]
      },
      "qqqq.7921-dddd.rancher.internal.": {
        "answer": [
          "10.42.15.145"
        ]
      },
      "qqqq.rancher.internal.": {
        "answer": [
          "10.42.15.145"
        ]
      }
    },
    "cname": {}
  },
```

When looking up `api.www.7921.dddd.mr.xxxxx.se` on 1.1.4 we get the data from `answers.json` but on 1.4.1 we get the data from our dns servers.
