### ISSUE TITLE
Rancher healthcheck restarting containers / load balancer

### ISSUE THREAD

**Issue by georgesvachulay** [rancher/rancher#8234]
**Rancher Versions:**
Server: 1.4.0-1.5.2
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.17
scheduler: 0.4.0
kubernetes (if applicable): n/a

**Docker Version:**
Docker 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.0 with all updates installed (except for docker)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Server: Rancher Server + MySQL sidekick on a server docker host
Hosts:
- 2 Load Balancer hosts (tagged, scheduling keeps additional containers off them 2GB RAM, 2 cores)
- 2 Rancher hosts (tagged, scheduling keeps containers on these, 4GB RAM, 4 cores, devicemapper)
- TCP 22 for sshd was changed to run on TCP 200 to have 22 open
- SeLinux disabled on the hosts (but same results with that enabled too)
- Data persisted over NFSv3 on a FreeNAS host
- Hosts directly connected over a single subnet

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) Create the 4+1 node cluster, using rancher versions between 1.4.0 - 1.5.2
2) Tag two instances with loadbalanced=true and set container stacks to must have hostlabel and backend=true
3) Tag two other instances with backend=true. Create a couple user stacks.
4) Create a rancher load balancer and schedule it to hostlabel loadbalanced=true. Set the load balancer stack to run a container on each host. Set up 3 forwardings, HTTP, HTTPS and TCP 22. 
5) Create a stack that has a rancher health check configured (e.g. sentry). Add it to the load balancer too.
6) Monitor the state of the Health Check stack. It should start showing invalid entries in a short while, saying it needs to restart to reconcile, etc.
7) The restart of the HC container will be only 1 out of the 4 and happens on a random host each time in no particular order. Whenever it happens on a host, the containers from that host become inaccessible. This affects both the load balancer and the actual stacks too.
8) Removing the HC stack completely resolves the issue, but Health Checks don't work afterwards (obviously).

**Results:**
- Load balancers have service interruptions in about 5-10 min intervals, whenever the HC container restart happens on a host that runs the LB too.
- Regular containers get interrupted too, until the HC recovers
- Throughout the error period, the HC container (1 out of 4) is yellow, 'Initializing'
- Logs on the HC container say:

3/20/2017 9:32:30 AMtime="2017-03-20T09:32:30Z" level=info msg="Starting haproxy listener"
3/20/2017 9:32:31 AMtime="2017-03-20T09:32:31Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
3/20/2017 9:32:31 AMtime="2017-03-20T09:32:31Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:32 AMtime="2017-03-20T09:32:32Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for backend 'cattle-eb9cc1d7-4052-4412-a41d-b22e9b2b452b_e76cd500-e47c-44a7-b3d9-6cf61e4b79da_1' as it requires HTTP mode.\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for backend 'cattle-eb9cc1d7-4052-4412-a41d-b22e9b2b452b_bbc3e2ce-117e-4097-b685-8e7774b50727_1' as it requires HTTP mode.\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for backend 'cattle-eb9cc1d7-4052-4412-a41d-b22e9b2b452b_69470efc-932b-408f-84df-0db57c80a026_1' as it requires HTTP mode.\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for backend 'cattle-eb9cc1d7-4052-4412-a41d-b22e9b2b452b_39f969cf-cae1-4ca9-ab48-da362460f953_1' as it requires HTTP mode.\n[WARNING] 078/093232 (35) : config : 'option forwardfor' ignored for backend 'cattle-eb9cc1d7-4052-4412-a41d-b22e9b2b452b_035ca491-09b4-4551-acb8-155a0fae949b_1' as it requires HTTP mode.\n"
3/20/2017 9:32:32 AMtime="2017-03-20T09:32:32Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:32 AMtime="2017-03-20T09:32:32Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:33 AMtime="2017-03-20T09:32:33Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:33 AMtime="2017-03-20T09:32:33Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:33 AMtime="2017-03-20T09:32:33Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:33 AMtime="2017-03-20T09:32:33Z" level=info msg="Monitoring 6 backends"
3/20/2017 9:32:34 AMtime="2017-03-20T09:32:34Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:34 AMtime="2017-03-20T09:32:34Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:34 AMtime="2017-03-20T09:32:34Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:34 AMtime="2017-03-20T09:32:34Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:35 AMtime="2017-03-20T09:32:35Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:35 AMtime="2017-03-20T09:32:35Z" level=info msg="Scheduling apply config"
3/20/2017 9:32:35 AMtime="2017-03-20T09:32:35Z" level=info msg="healthCheck -- no changes in haproxy config\n"
3/20/2017 9:32:35 AMtime="2017-03-20T09:32:35Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_e76cd500-e47c-44a7-b3d9-6cf61e4b79da_1=DOWN"
3/20/2017 9:32:35 AMtime="2017-03-20T09:32:35Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_bd4c567d-4cd9-4fc1-879a-63e642f560a3_1=DOWN"
3/20/2017 9:32:36 AMtime="2017-03-20T09:32:36Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_bbc3e2ce-117e-4097-b685-8e7774b50727_1=DOWN"
3/20/2017 9:32:36 AMtime="2017-03-20T09:32:36Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_69470efc-932b-408f-84df-0db57c80a026_1=DOWN"
3/20/2017 9:32:36 AMtime="2017-03-20T09:32:36Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_39f969cf-cae1-4ca9-ab48-da362460f953_1=DOWN"
3/20/2017 9:32:36 AMtime="2017-03-20T09:32:36Z" level=info msg="eb9cc1d7-4052-4412-a41d-b22e9b2b452b_035ca491-09b4-4551-acb8-155a0fae949b_1=DOWN"

- Logs on interrupted containers don't show any errors
- Logs on interrupted load balancer don't show any errors in particular (generic warnings still appear for HAproxy, but it remains fully operational without HC running)
- Looking up log container IDs yields only dead API entries (they don't exist anymore)

Please advise. For the time being, we are keeping the Healthcheck stack disabled and removed Healthchecks from the stacks too, so they don't restart. We've tried upgrading / downgrading, didn't help. We've tried adjusting / disabling the container health checks, didn't help.

**Comment by joshuacox** [comment]
Can you post the template?  Or at least the healthcheck?  https://github.com/rancher/rancher/issues/7969 I've run into much of the same sort of issue and am having trouble discerning what the difference is between a working healthcheck and a broken.  Something fishy is going on.

**Comment by opsforge** [comment]
docker-compose.yml

```
smtp:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  environment:
    maildomain: ${mail_domain}
    smtp_user: sentry:PASSWORD
  image: catatnight/postfix
sentry-postgres:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  environment:
    PGDATA: /var/lib/postgresql/data
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: sentry
  image: postgres:9.5.3
  volumes:
  - /mnt/stacks/sentry/${db_stor_path}:/var/lib/postgresql/data
sentry-worker:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  environment:
    SENTRY_EMAIL_HOST: email
    SENTRY_EMAIL_PASSWORD: PASSWORD
    SENTRY_EMAIL_USER: sentry@${mail_domain}
    SENTRY_SECRET_KEY: ${secret_key}
    SENTRY_SERVER_EMAIL: sentry@${mail_domain}
    SENTRY_LDAP_SERVER: ${ldap_server}
    SENTRY_LDAP_SERVICE_DN: ${ldap_service_account_dn}
    SENTRY_LDAP_BIND_PASSWORD: ${ldap_password}
    SENTRY_LDAP_BASE_DN: ${ldap_base_dn}
  command:
  - run
  - worker
  image: allistera/sentry:8.13.0
  links:
  - sentry-redis:redis
  - smtp:email
  - sentry-postgres:postgres
sentry-redis:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  image: redis:3.2.4-alpine
sentry:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  environment:
    SENTRY_EMAIL_HOST: email
    SENTRY_EMAIL_PASSWORD: PASSWORD
    SENTRY_EMAIL_USER: sentry@${mail_domain}
    SENTRY_SECRET_KEY: ${secret_key}
    SENTRY_SERVER_EMAIL: sentry@${mail_domain}
    SENTRY_LDAP_SERVER: ${ldap_server}
    SENTRY_LDAP_SERVICE_DN: ${ldap_service_account_dn}
    SENTRY_LDAP_BIND_PASSWORD: ${ldap_password}
    SENTRY_LDAP_BASE_DN: ${ldap_base_dn}
  command:
  - /bin/bash
  - -c
  - sentry upgrade --noinput && /entrypoint.sh run web || /entrypoint.sh run web
  image: allistera/sentry:8.13.0
  links:
  - sentry-redis:redis
  - smtp:email
  - sentry-postgres:postgres
sentry-cron:
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_label}=true
  environment:
    SENTRY_EMAIL_HOST: email
    SENTRY_EMAIL_PASSWORD: PASSWORD
    SENTRY_EMAIL_USER: sentry@${mail_domain}
    SENTRY_SECRET_KEY: ${secret_key}
    SENTRY_SERVER_EMAIL: sentry@${mail_domain}
    SENTRY_LDAP_SERVER: ${ldap_server}
    SENTRY_LDAP_SERVICE_DN: ${ldap_service_account_dn}
    SENTRY_LDAP_BIND_PASSWORD: ${ldap_password}
    SENTRY_LDAP_BASE_DN: ${ldap_base_dn}
  command:
  - run
  - cron
  image: allistera/sentry:8.13.0
  links:
  - sentry-redis:redis
  - smtp:email
  - sentry-postgres:postgres
```
rancher-compose.yml

```
.catalog:
    name: "Sentry"
    version: "v8.10.0.23"
    description: "Sentry Server With LDAP Enabled."
    questions:
      - variable: secret_key
        description: "Random Secret Key"
        label: "Secret Key"
        required: true
        type: "string"
        default: "BLAH"
      - variable: ldap_server
        description: "LDAP Server Address"
        label: "LDAP Server"
        required: true
        type: "string"
        default: "something.net"
      - variable: ldap_service_account_dn
        description: "LDAP Service Account DN"
        label: "Service Account DN"
        required: true
        type: "string"
        default: "DC=Something,DC=net"
      - variable: ldap_password
        description: "LDAP Service Account Password"
        label: "Service Account Password"
        required: true
        type: "string"
        default: "blah"
      - variable: ldap_base_dn
        description: "LDAP Base DN"
        label: "Base DN"
        required: true
        type: "string"
        default: "DC=Something,DC=net"
      - variable: "mail_domain"
        description: "Domain Email is From"
        label: "Email Domain"
        required: true
        default: "something.net"
        type: "string"
      - variable: db_stor_path
        description: "suffix to the mount path only, / not needed :"
        label: "Database storage"
        required: true
        default: "sentry_db"
        type: "string"
      - variable: host_label
        description: "Used to schedule to stack to a specific host"
        label: "Host label"
        required: true
        default: "sentry"
        type: "string"
sentry:
  scale: 1
  health_check:
    port: 9000
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000
```

HC on the bottom. However even after removing this, the symptoms persisted. I tried without / with HCs, I even tried removing the HCs of the HC stack (ridiculous I know). Same thing, stayed.

I was thinking possible causes:
- Labeled scheduling?
- TCP 42 something to do with selinux
- HC caching invalid results

Still unsure...

**Comment by opsforge** [comment]
Oh yeah and I can't see similar symptoms when I only have 2 or less hosts in an Env. Maybe that will shed some light on it.

**Comment by joshuacox** [comment]
I have something wrong with one of my environments.  I have another env under the same rancher server that seem to be fine now.  If you can, try your templates on a completely new rancher setup and see if everything starts working correctly.  I am not even certain what is wrong with my broken env, but now even the healthcheck containers exhibit the 'initializing' constantly yellow behavior.  I am evacuating and killing this one off ASAP

**Comment by joshuacox** [comment]
@SvenDowideit  this is a weird issue that deserves attention, I've seen more than one get 'poisoned'. A good fix in my case is to spawn new rancer VMs and replace the entire environment.  I'm not certain what is wrong but @opsforge  may be onto something with his healthcheck debugging

**Comment by mempapeur** [comment]
Had the same issue, HCs and LBs were detected as DOWN every 5-10mns and then recreated by rancher. 

No logs available on the HC/LB as it was deleted by rancher, but on the others HC logs showing that all HCs detected it as down at same time (whereas it wasn't).

Seems the issue wasn't related to rancher, but rather to HAproxy (used by HC to check other HCs/LBs).

On my env, i had 4 hosts, so each HC/LB was checked by the HCs of the 3 other hosts, so as the default value of the check interval is 2000ms, there was 3 tcp checks every 2s.
I upgrade the check interval of HCs and LBs to 6000ms. This can be done using rancher UI for the HCs (Stack > Infrastructure: Upgrade button on HealthCheck service), but not for the LBs, the "Healtcheck" tab is missing on the UI. So i added it using rancher-compose.yml (did have to delete/create the stack) : 
```
LB:  
    start_on_create: true  
 [...]  
    health_check:  
      healthy_threshold: 2  
      response_timeout: 2000  
      port: 42  
      unhealthy_threshold: 3  
      interval: 6000  
      strategy: recreate
```



These changes fixed the issue on my env.

I'm not quite sure about how this fix the issue. 
As mentionned on HAproxy doc (https://www.haproxy.com/doc/aloha/7.0/haproxy/healthchecks.html#checking-a-mysql-service) in the case "timeout check" is set (as it is in the HCs haproxy.cfg), check timeout is based on min of "timeout check"/'interv", and i only changed the interv on my HCs/LBs : timeout check is still set to default value -> 2000ms.

But as i mentioned, before this change HCs/LBs were recreated every 5-10mins and since then HCs/LBs weren't recreated!

**Comment by opsforge** [comment]
Upgraded to server 1.5.6 (with agent 1.2.2), upgraded docker engine to latest too (not supported by rancher, shows up as untested), and followed @mempapeur 's instructions to increase the interval for HC from 2000ms to 6000ms. The load balancer haproxy image got upgraded as part of the 1.5.6 upgrade. I didn't create a custom config for the elb, so the interval is the same on that.

So far it seems to be holding up ok, I did not see a restart since. HC log says 'already reconciled' which is not what it was saying before, so it seems to be good. Will update here if anything changes / thanks for the help, all!

**Comment by pboos** [comment]
Experiencing the same update after update to 1.5.6.
Would be nice to get a way to solve this problem without having to delete and recreate the stack.

**Comment by qixinyun** [comment]
The same issue, Upgraded to server 1.5.6 and followed @mempapeur 's instructions to increase the interval for both HC and LB. it seems solved. thx guys.

**Comment by williamheinz** [comment]
Experiencing this issue as well, Rancher v1.6.2 running on RancherOS v1.0.3.

All healthcheck instances besides the primary are stuck in "Initializing" and load balancers don't work at all (fails on rancher-metadata) and are repeatedly restarted by health checks.

**Comment by xaka** [comment]
Same problem with Rancher v1.6.2 running on RancherOS v1.0.3.

I simply created nginx service based on nginx image and added HTTP check, and service is still in initializing state. I exec-ed into healthcheck container and was able to ping and curl nginx container.

**Comment by xaka** [comment]
What looks off to me is haproxy configuration:

```
backend cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_eab88149-f31d-4b2d-8523-40e087e04b47_2
mode http
balance roundrobin
option httpchk GET /healthcheck HTTP/1.0
timeout check 2000
server cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_eab88149-f31d-4b2d-8523-40e087e04b47_2 10.42.200.105:80 check port 80 inter 2000 rise 2 fall 3

backend cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_acbc0bf1-f556-4bac-9b42-5d19053611e3_2
mode tcp
balance roundrobin
timeout check 2000
server cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_acbc0bf1-f556-4bac-9b42-5d19053611e3_2 10.42.61.120:42 check port 42 inter 2000 rise 2 fall 3

backend cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_884ead93-c410-41f4-b321-c242be0a4d77_1
mode tcp
balance roundrobin
timeout check 2000
server cattle-0159f5e8-1b0c-45f2-a2af-92fff34beee4_884ead93-c410-41f4-b321-c242be0a4d77_1 10.42.160.101:42 check port 42 inter 2000 rise 2 fall 3
```

and nothing matches to healthcheck configuration:

```
version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000
```

nor to container IP:

```
10.42.69.18
```
