### ISSUE TITLE
awslogs driver doesn't support tag option

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#8235]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: net:holder
network-services: 0.8.11
scheduler: 0.7.4

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
aws, ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
configure log driver to awslogs
set awslogs-group=mongo
set tag=mongo-{{.ID}}

```
version: '2'
services:
  mongo:
    image: mongo:3.2
    logging:
      driver: awslogs
      options:
        awslogs-group: mongo
        tag: mongo-{{.ID}}
    labels:
      io.rancher.container.pull_image: always
```
**Results:** 
mongo (Expected state running but got error: Error response from daemon: unknown log opt 'tag' for awslogs log driver) 

How do I setup awslogs driver to prefix container id with a name?

I've also tried `awslogs-stream=mongo-{{.ID}}` it's not working

Links:
https://docs.docker.com/engine/admin/logging/awslogs/#usage

https://docs.docker.com/engine/admin/logging/log_tags/
