### ISSUE TITLE
Unable to create new stack with LB setup - MissingRequired

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#8237]
**Rancher Versions:**
Server: 1.5.1
healthcheck: up2date
ipsec: up2date
network-services: up2date
scheduler: up2date

**Rancher compose:**
Tested versions from v0.12.3 to last RC (v0.12.4-rc1)

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher + ext DB (Galera)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup and create new stack with lb_config, for example:

- docker-compose.yml

```
version: '2'
services:
  collector:
    image: wordpress
    labels:
      loadbalancer.https: true
```

- rancher-compose.yml

```
version: '2'
services:
  wordpress:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: test-1.example.com
        source_port: 443
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```

**Results:** 

```
rancher-compose  --verbose up -d --force-upgrade
...
time="2017-03-20T14:21:18Z" level=debug msg="Creating service collector with hash: digest.ServiceHash{Service:\"2a605fea5e743xxxxx721bdf434ba65d7c978\", LaunchConfig:\"99ce2594540f92e256e2xxxxxx394c8\", SecondaryLaunchConfigs:map[string]string(nil)}" 
time="2017-03-20T14:21:18Z" level=error msg="Failed Creating collector : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=serviceId, baseType=error] from [https://xxxxxxx/v2-beta/loadbalancerservices]" 
time="2017-03-20T14:21:18Z" level=error msg="Failed to start: collector : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=serviceId, baseType=error] from [https://xxxxxxx/v2-beta/loadbalancerservices]" 
time="2017-03-20T14:21:18Z" level=fatal msg="Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=serviceId, baseType=error] from [https://xxxxxxx/v2-beta/loadbalancerservices]" 
```

If I remove LB setup from rancher-compose, create new stack, stop stack and after that make upgrade it's ok.

**Comment by tfiduccia** [comment]
In your docker-compose you are just creating a single regular service called collector, not a load balancer.  You need to add the load balancer to the docker-compose file

example:
docker-compose:

```
version: '2'
services:
  wordpress:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  collector:
    image: wordpress
    labels:
      loadbalancer.https: 'true'
```

rancher-compose:

```version: '2'
services:
  wordpress:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: collector
        source_port: 443
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  collector:
    scale: 1
    start_on_create: true
```

**Comment by VAdamec** [comment]
Well we use balancers as a separate stack (even on separate hosts, because of firewall rules and strict security policy), I don't want to create balancer for every new service.

**Comment by VAdamec** [comment]
Well it exists, but as a different stack/service. Also I can create such service but in two steps, first without this configuration and than with lb_config. And it works. If this is not correct way, how to setup service which will use different balancer ? How to setup parameters in service for LB ?

LB is setup to use selector 'loadbalancer.https: true' but there need to be some setup specific for service which contain info about domain (Request Host). So maybe I'm just missing some label or so. Like Traefic, it use labels (like traefik.alias, traefik.domain, ...)

**Comment by tfiduccia** [comment]
![image](https://cloud.githubusercontent.com/assets/11514927/24394068/5fc6262c-134f-11e7-99b4-72dce23a3b5f.png)

**Comment by VAdamec** [comment]
Via compose? In UI it's clear

**Comment by tfiduccia** [comment]
Okay I went through it all again.  The rule you create for the load balancer through the service is not shown in the UI (there is already a issue about this logged).  But I did get it work.  You can't define lb certs through the service, and since you have that in there, it thinks it's trying to create a new load balancer.  Just simply take out the cert: [] from your yaml.

Sorry about misunderstanding your problem from the get go.

**Comment by VAdamec** [comment]
Maybe with HAProxy balancer we cannot use it like this (and I should use Traefic instead) or just take this behaviour as feature, not bug ;-)

**Comment by tfiduccia** [comment]
Did you see my comment on removing the cert: [] from your yaml.  After I did that the service was fine.  Although you can't see the rule through the UI, you can go to the shell in the load balancer container and go to 'cat /etc/haproxy/haproxy.cfg' to see the list of rules there.

**Comment by VAdamec** [comment]
Ah ok, I missed that.

**Comment by tfiduccia** [comment]
You will also have to remove the source_port: 443, cause you can't have a different source port than the one you put the label on.

**Comment by VAdamec** [comment]
Hm removing cert doesn't help

```
version: '2'
services:
  example:
    start_on_create: true
    lb_config:
      port_rules:
      - hostname: ${DOMAIN}
        source_port: 443
        target_port: 8080
```

```
version: '2'
services:
  example:
    image: registry.example.com:5000/example:${VERSION}
    stdin_open: true
    tty: true
    labels:
      loadbalancer.https: 'true'
```

Bad response statusCode [422]. Status [422 status code 422]. Body: [baseType=error, fieldName=serviceId, code=MissingRequired]

1. removing LB setup, deploy = OK
2. adding back LB and run upgrade pass = infinite upgrade loop
3. stop service before upgrade, deploy = OK
