### ISSUE TITLE
loadbalancer gets recreated after delete, get cert sends create after delete event

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8254]
**Rancher Versions:**
Server: 1.4.1

kubernetes (if applicable):
1.5.2-rancher1-4

**Docker Version:**
1.12.6

**Steps to Reproduce:**
- create an lb listening on 443, without cert being present in name space
- delete ingress
- in ingress controller manager you'll see the delete event, and then a create event because of cert application (thread that gets cert never ends and recreates ingress)

**Results:** 
kubectl doesnt show the ingress, but it shows up in rancher.

**Comment by kinarashah** [comment]
I'm not able to reproduce this behavior. Let me know if I'm missing something. Thanks! 

**Rancher Version** : rancher/server:v1.6.6
**Kubernetes** : rancher/k8s:v1.7.2-rancher5

Created lb at 443 using,  
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simplelb
spec:
  backend:
    serviceName: nginx-service
    servicePort: 443
```
My nginx-service looks like, 
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-service
spec:
  replicas: 1
  selector:
    k8s-app: nginx-service
```

On deleting ingress, these are the events in the ingress controller manager - 
```
8/4/2017 1:00:41 PMtime="2017-08-04T20:00:41Z" level=info msg="Creating lb service"
8/4/2017 1:00:45 PMtime="2017-08-04T20:00:45Z" level=info msg="Updating Rancher LB with the new lbConfig [&{{  map[] map[]} []   [{{  map[] map[]}    %!s(int64=0) http  1s40 %!s(int64=80) %!s(int64=80)}] %!s(*client.LoadBalancerCookieStickinessPolicy=<nil>)}] "
8/4/2017 1:01:04 PMtime="2017-08-04T20:01:04Z" level=info msg="Updating ingress default/simplelb with IP 35.192.87.96"
8/4/2017 1:01:04 PMtime="2017-08-04T20:01:04Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"default\", Name:\"simplelb\", UID:\"973de23a-794f-11e7-a5ea-024ff9e6028d\", APIVersion:\"extensions\", ResourceVersion:\"161305\", FieldPath:\"\"}): type: 'Normal' reason: 'CREATE' ip: 35.192.87.96"
8/4/2017 1:01:04 PMtime="2017-08-04T20:01:04Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"default\", Name:\"simplelb\", UID:\"973de23a-794f-11e7-a5ea-024ff9e6028d\", APIVersion:\"extensions\", ResourceVersion:\"161348\", FieldPath:\"\"}): type: 'Normal' reason: 'UPDATE' default/simplelb"
8/4/2017 1:06:33 PMtime="2017-08-04T20:06:33Z" level=info msg="Event(api.ObjectReference{Kind:\"Ingress\", Namespace:\"default\", Name:\"simplelb\", UID:\"973de23a-794f-11e7-a5ea-024ff9e6028d\", APIVersion:\"extensions\", ResourceVersion:\"161348\", FieldPath:\"\"}): type: 'Normal' reason: 'DELETE' default/simplelb"
8/4/2017 1:06:33 PMtime="2017-08-04T20:06:33Z" level=info msg="Deleting lb service [default-rancherlb-simplelb]"
```

No events after DELETE get logged.
