### ISSUE TITLE
Exported config file should include scale min/max/increment set for global services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8255]
Rancher Versions: Build from wagyu

Steps to reproduce the problem:
Create a global service with scale min/max/increment set.
```
"scaleIncrement": 2,
"scaleMax": 4,
"scaleMin": 2,
```
Exported config file for this service does not include scale min/max/increments set for global services.

**Comment by deniseschannon** [comment]
Fixed in wagyu branch

**Comment by sangeethah** [comment]
Tested with rancher-server build from master - 07/07
Exported config files for global services now include scale min/max/increments.

```
version: '2'
services:
  test-839890:
    scale_increment: 2
    start_on_create: true
    scale_max: 4
    scale_min: 2
```
