### ISSUE TITLE
Adding single/multiple hosts dedicated to a stack using hosts key in docker-compose file adds 3 hosts to the environment

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8273]
**Rancher Versions:**
Server: master, wagyu branch

**Docker Version:**17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Add single/multiple hosts dedicated to a stack in UI through docker-compose file. Example files below:
```
version: '2'
services:
  a:
    image: nginx
hosts:
  testh1:
    count: 1
    digitalocean_config:
      access_token: ...
```
```
version: '2'
services:
  a:
    image: nginx
hosts:
  soumyah1:
    count: 10
    digitalocean_config:
      access_token: ...

```

**Results:** 
Three hosts are added to the environment, irrespective of the count specified in the yaml file
<img width="851" alt="screen shot 2017-03-22 at 2 14 55 pm" src="https://cloud.githubusercontent.com/assets/18536626/24221061/0b41d2c0-0f0a-11e7-8e04-473f751c3302.png">
