### ISSUE TITLE
kubernetes runasuser blocked by k8s service policy SecurityContextDeny

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8287]
**Rancher Versions:**
Server: 1.5.1
kubernetes (if applicable):
1.5.2

**Docker Version:**
1.12.6

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
default runasuser security context is blocked. 
looking to validate k8s setup with this enabled

**Comment by aemneina** [comment]
Example yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 41
```

**Comment by janeczku** [comment]
we hit this today and it blocked us from successfully deploying the socks shop micro-service demo application

**Comment by joshwget** [comment]
This was changed in rancher/rancher-catalog#679. The `SecurityContextDeny` admission controller isn't enabled anymore.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.2
Kubernetes: 1.6.4

I ran the following yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 101
    command: ["sleep","1000"]
```

Then
```
$ kubectl exec -it nginx -- whoami
nginx
```
