### ISSUE TITLE
Deploying load balancer to the random free port from Rancher CLI

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#8291]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1

**Docker Version:** 1.12.6 on agents, 17.03.0-ce on the server 

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.2 LTS (with KVM) (4.4.0), cloud, DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Our application has a web-server + load balancer, only load balancer is exposed to a public port.
In order to test different versions of the application simultaneously in our CD pipeline we deploy it to random ports, then retrieve the port it was deployed to and run e2e tests against this port.

We have been doing so by not specifing host port mapping (it looked like `ports: -80`) in `docker-compose.yml` file for load balancer service.
So when we did a deployment Rancher CLI has been choosing a random port (say 43165) where the application became accessible.

After migrating from bare metal setup to cloud setup and in the same time upgrading from Rancher 1.2 to 1.5 this behavior stopped working.
Now the port is not selected randomly, but instead Rancher sets port 80.

So steps to reproduce are:
1. Deploy the app using Rancher CLI:

docker-compose.yml:
```
version: '2.0'
services:
  load-balancer:
    image: rancher/lb-service-haproxy:v0.6.2
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
    ports:
    - 80
  web:
    image: some-image
```

rancher-compose.yml:
```
version: '2'
services:
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 3333
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  web:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3333
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
      request_line: GET / HTTP/1.0
```

2. Check the port that Rancher chooses for load balancer service

**Actual Results:** 
The load balancer is deployed to port 80 of any available host. If no free hosts are left then deployment fails.

**Expected Results:** 
The load balancer is deployed to any free port of any available host.
In the environment having 3 hosts it should be possible to deploy 10 instances of application without having to generate a random port number (read: guess what of them is free) inside deployment script.

Please note that this issue is not about creating LB from UI (like  https://github.com/rancher/rancher/issues/3547 or https://github.com/rancher/rancher/issues/3103)
