### ISSUE TITLE
Dynamic EBS provisioning with Storage Class fails on Kubernetes

### ISSUE THREAD

**Issue by harshal-shah** [rancher/rancher#8300]
**Rancher Versions:**
Server: v1.5.3
healthcheck: 0.2.3
ipsec: 0.9.4
network-services: v0.5.3
scheduler: v1.5.4-rancher1-3
kubernetes (if applicable): client v1.5.5 server v1.5.4-rancher1

**Docker Version:** 
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu14.04 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 node kubernetes cluster on rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

Create storage class with following definition: 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow-ap
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: ap-southeast-1
  iopsPerGB: "10"
```
Create a PVC with following definition: 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-ap
  labels:
  name: my-test3-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

**Results:** 
The PVC will not get bound and will show following error: 

```
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  19s           2s              3       {persistentvolume-controller }                  Warning         ProvisioningFailed      no volume plugin matched
```

It seems kubernetes controller manager needs to be started with --cloud-provider=aws for dynamic storage provisioning to work. Is there any other way around this to make it work with Rancher ?

https://github.com/kubernetes/kubernetes/issues/16585#issuecomment-153928223
