### ISSUE TITLE
[cli] Cannot map host directories if deploying from Windows command line

### ISSUE THREAD

**Issue by agavrilov** [rancher/rancher#8311]
**Rancher Versions:**
Server: 1.5.3
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1
rancher cli: 0.5.1

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.10 bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher server, internal DB with a data directory mapped to a host

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* Set up Rancher server
* Add Linux host to Rancher server
* Set up Rancher CLI on Windows 10 machine to connect a Rancher server above
* Unpack the attached [docker-compose.zip](https://github.com/rancher/rancher/files/873028/docker-compose.zip) into a separate directory on Windows machine
* Open Windows command prompt and go to the directory where the attached file was unpacked
* Issue the following command: **rancher up --stack test** 

**Results:** 
The stack creation is error out with the following message:
Activating (Expected state running but got error: Error response from daemon: create C: volume name is too short, names should be at least two alphanumeric characters)

**Comment by agavrilov** [comment]
The original file docker-compose.yml is
```yml
cadvisor:
  labels:
    io.rancher.scheduler.global: 'true'
  image: google/cadvisor:latest
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
```

but when I open View Config in Rancher UI, I see the following config:
```yml
version: '2'
volumes:
  C:
    external: true
    driver: 'null'
services:
  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - C:/rootfs:ro
    - C:/var/run:rw
    - C:/sys:ro
    - C:/var/lib/docker:ro
    labels:
      io.rancher.scheduler.global: 'true'
```
