### ISSUE TITLE
race condition bug for volume create

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8357]
For EBS volume(this might apply to other volume driver), there is a possible race condition. When creating a per_container volume in template, cattle will try to create the instance and volume at the same time. Then during the creation of instance agent will call docker volume plugin to create volume and at the same time volume will go through the rancher lifecycle. But during volume.create in rancher lifecycle, because the volume already has a hostID appended to it(because it is a per_container volume and container is already allocated), it will be considered as already created volume and then volume.deactivate process will be chained to detach the volume. So this could happen before agent call the docker volume plugin to create volume so it will never succeed since it is already in detached state. Then volume.attach will never succeed cause the plugin will never try to re-create the volume.

**Comment by StrongMonkey** [comment]
To test this, just make sure we are able to launched containers using stack-scoped and container-scoped volume.

**Comment by soumyalj** [comment]
Tested with 1.6.0-rc5. Created stack scoped and container scoped volumes successfully.
Stack scoped volume example below:

```
version: '2'
services:
  foo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - testvol:/mydata
volumes:
  testvol:
    external: false
    driver: rancher-ebs
    driver_opts:
      size: '10'
```

Container scoped volume example below:
```
version: '2'
services:
  yoo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - percontvolume:/mydata
volumes:
  percontvolume:
    per_container: true
    driver: rancher-ebs
    driver_opts:
      size: '5'
```
