### ISSUE TITLE
Rancher-compose file not updated with new answers on catalog upgrade

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#8378]
**Rancher Versions:**
Server: 1.5.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Use [this repository](https://github.com/mattdodge/bad_rancher_upgrade) as a custom catalog. It basically has a template for an nginx service that relies on the port_rules for load balancers in the rancher-compose.yml file.

**rancher-compose.yml from template**
```yml
.catalog:
   name: "Catalog Test"
   version: "0.1.0" 
   description: "Testing catalog thingy"
   questions:
     - variable: "host_alias"
       description: |
         The instance's alias or host name. This is how the container will be accessed as a URL
       label: "Host Alias"
       type: "string"
       required: true
     - variable: "host_root"
       description: |
         The root domain of the host
       label: "Host Domain"
       type: "string"
       required: true

webby:
  scale: 1 
  lb_config:
    port_rules:
      - target_port: 80
        hostname: ${host_alias}.${host_root}
```

Specifically, when launching the stack you can specify (through questions/answers) what hostname you would like to bind to on the load balancer. 

**If you update the stack and change your answer, the load balancer rules are not changed.**

Example below:
Launch a stack from the catalog with alias `alias_here` and domain `domain.here.com`
<img width="1244" alt="screenshot 2017-03-31 13 56 58" src="https://cloud.githubusercontent.com/assets/797259/24569206/f771c7e8-1619-11e7-93e7-8ac9ef0c5038.png">

After launching, viewing the config of the stack shows that the host alias and domain were replaced in both the docker compose and rancher compose files properly:
<img width="1257" alt="screenshot 2017-03-31 13 58 02" src="https://cloud.githubusercontent.com/assets/797259/24569232/12795cae-161a-11e7-8987-0df317a20d4a.png">

Now, update the stack and change the answer for host_alias to `new_host_alias`. Expected behavior would have it substitute the new answer for that question in both the rancher-compose and docker-compose files, but the substitution only occurs in the docker-compose file:
<img width="1268" alt="screenshot 2017-03-31 13 58 56" src="https://cloud.githubusercontent.com/assets/797259/24569282/44ace1d2-161a-11e7-93b0-fe632d13e492.png">
