### ISSUE TITLE
A compatibility issue  between rancher-compose and go-template 

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8418]
**Rancher Versions:**
Server: v1.5.3

Create a stack with this compose file.
```
  consul00:
    image: consul
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    command:
    - 'agent'
    - '-server'
    - '-node=node0'
    - '-bootstrap-expect=1'
    - '-bind={{GetInterfaceIP "eth0"}}'
    - '-client={{GetInterfaceIP "eth0"}}'
    - '-ui'
```

![image](https://cloud.githubusercontent.com/assets/998984/24702100/e5515f50-1a2f-11e7-9fde-d706ef4d4f54.png)

The consul image  need use {{GetInterfaceIP "eth0"}}, but rancher-compose read it as go-template synax.
