### ISSUE TITLE
Ingress scale up by editing the ingress scale is not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8450]
**Rancher Versions:**
Server:v1.4.1

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with 3 hosts
2. Create service/pods and an ingress with scale 1. Ensure the ingress is functional and targets are reachable
3. Edit the ingress and increase the scale to 3. 

Results
The ingress doesn't scale up to 3

Example Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress10
 annotations:
   scale: "2"
   http.port: "93"
spec:
  backend:
    serviceName: k8test10
    servicePort: 80

```
Editing the http port along with increasing the scale will scale up the ingress. But just increasing the scale does not update the ingress.
