### ISSUE TITLE
Load Balancer can point to itself when defined in the GUI, cannot when defined in rancher-compose.yml

### ISSUE THREAD

**Issue by MartinLeedotOrg** [rancher/rancher#8464]
In order to get metrics out of the HAProxy Load Balancer, I'm doing this:

```
    lb_config:
      certs: []
      config: |-
        frontend monitoring
          mode http
          bind *:9805
          no log
          stats uri /
          stats enable
          stats show-desc
```
...
```
      - hostname: ''
        priority: 4
        protocol: http
        service: front-end
        source_port: 9805
        target_port: 9805
```

The GUI let me do this without warning or complaint.

When replicating the stack using the exported rancher-compose.yml file, I get the following error:
```Cycle detected in path front-end->front-end```

I can understand the reason for the error, but it does seem odd that a rule defined in the GUI isn't accepted when used through rancher-compose.yml.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.code`|

**Comment by unitymind** [comment]
Exactly, very annoying restriction still actual in Rancher v1.6.1.

I want to use only one LB, which handle internal load-balancing and point public host and/or port to internal LB rule. And, yes, it's possible and working like a charm through UI, but arise error as described.

Only two workarounds:

1) Use different LB services.
2) Add desired behaviour using Rancher UI (not usable with private catalog automation).

Any thoughts? Will be categorised as bug? )

**Comment by unitymind** [comment]
And just found third workaround and it's works via rancher-compose.yml

Use Service alias to lb and refer in lb conf by alias. Try to create via Rancher UI and see exported docker-compose.yml and rancher-compose.yml

**Comment by pasikarkkainen** [comment]
Just noticed this bug with rancher v1.6.2.

One has to define some "service" when exposing the haproxy stats page, so it's annoying it's not allowed to be the LB itself.. especially when the rancher GUI is totally happy with that, and it works OK.

**Comment by failedguidedog** [comment]
It is very annoying, but I've found a workaround using selector targeting (using a lable to select the target for the loadbalancer rule):

Add a label to the loadbalancer service in `docker-compose.yml`:

```yml
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.1
    ports:
    - 6668:6668/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
      loadbalancer: stats
```

Then use the label as a selector in `port_rules` in `rancher-compose.yml`:

```yml
services:
  lb:
    start_on_create: true
    lb_config:
      port_rules:
      - backend_name: stats
        path: /stats
        priority: 3
        protocol: http
        selector:  loadbalancer=stats
        source_port: 6668
        target_port: 6668
```

This works as expected and a loop is not detected. I hope this helps anyone.
