### ISSUE TITLE
Firefox always showing scheduling rule as "must" on upgrade/clone

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#8494]
**Rancher Versions:**
Server: 1.5.3
scheduler: 0.7.5

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a service with a schedule rule, for example "host should not have a service with the name {service name}. Click upgrade. Once upgrade is complete, click approve. Then go into the upgrade menu again. Click into the schedule rules, and the rule you just added does not show up. Some rule shows up, but its not the right one.

**Results:** 
the rule you just added does not show up. Some rule shows up, but its not the right one. I havent tested it, but this could potentially override an existing scheduling rule on accident.

**Comment by aemneina** [comment]
@nhumrich is that the exact use case you ran through? I tried this on rancher v1.5.5 + scheduler v0.7.5 and wasn't able to reproduce. Can you try it on 1.5.5?

**Comment by nhumrich** [comment]
Just tried it on 1.5.5, no difference:
If I go look at the docker-compose yaml from rancher I get the following:

```
version: '2'
services:
  java-all-projects:
    image: canopytax/java-service:xxxxxx
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=java-all-projects
      service: java-all
```

But when I go into the UI it shows:

![selection_069](https://cloud.githubusercontent.com/assets/4661889/25157039/f9c1a04a-245b-11e7-9958-f342d8362f39.png)

The scheduling rule is incorrect.
