### ISSUE TITLE
Nodeport service doesn't work on all the Rancher agents

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8506]
**Rancher Versions:**
Server: v1.5.4
kubernetes (if applicable): 1.5.4

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
GCE - ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Start a 3 node Rancher setup
- Install kubernetes
- Run the following yaml:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: husseingalal/nginx-curl
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: external-nginx
  labels:
    name: external-nginx
spec:
  type: NodePort
  externalIPs: ['node-1', 'node-2']
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    name: nginx
```
Change the node-1 and node-2 with the public ips of the first and second agents

- curl the first and second host with the nodeport

**Results:** 
```
$ curl -IL node-1:30003
HTTP/1.1 200 OK
Server: nginx/1.9.15
Date: Thu, 13 Apr 2017 22:36:42 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 19 Apr 2016 17:27:46 GMT
Connection: keep-alive
ETag: "57166a92-264"
Accept-Ranges: bytes

$ curl -IL node-2:30003

```
