### ISSUE TITLE
hostPID spec is not working as expected in kubernetes 1.6

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8531]
**Rancher Versions:**
Server: master build
kubernetes (if applicable): 1.6

**Steps to Reproduce:**
- Start kubernetes 1.6.1
- Run the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  hostPID: true
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
- Run the following command to exec and check the container's processes.
```
kubectl exec nginx -- ps aux         
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  31876  5240 ?        Ss   00:08   0:00 nginx: master process nginx -g daemon off;
nginx        6  0.0  0.0  32264  3016 ?        S    00:08   0:00 nginx: worker process
root        25  0.0  0.0  17500  2184 ?        Rs   00:22   0:00 ps aux
```
**Results:** 
The running pod doesn't share the same PID namespace with the host.
