### ISSUE TITLE
rancher-catalog-service does not resolve the database name the same way as cattle

### ISSUE THREAD

**Issue by dabelenda** [rancher/rancher#8539]
**Rancher Versions:**
Server:  1.5.5 (regression in branch 1.5 with regards to 1.3 and 1.4)
healthcheck: v0.2.3
ipsec: v0.11.2
network-services: v0.9.1
scheduler: v0.7.5
kubernetes (if applicable): N/A

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node external mysql DB (5.7) run using docker-compose

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:** using the following docker-compose.yml (make sure that **used-name** exists in `hostname -d` or any domain configured as search in /etc/resolv.conf

composition has IP range 172.18.0.0/16, used-name in the composition becomes 172.18.0.3 while used-name.`hostname -d` has IP 10.10.10.10

```
version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: cattle
      MYSQL_USER: cattle
      MYSQL_PASSWORD: cattle
    volumes:
      - /var/opt/rancher/mysql-data/:/var/lib/mysql

  rancher-server:
    image: rancher/server:v1.5.5
    ports:
    - 8080:8080
    environment:
      CATTLE_DB_CATTLE_MYSQL_HOST: used-name
      CATTLE_DB_CATTLE_MYSQL_PORT: 3306
      CATTLE_DB_CATTLE_MYSQL_NAME: cattle
      CATTLE_DB_CATTLE_USERNAME: cattle
      CATTLE_DB_CATTLE_PASSWORD: cattle
    links:
      - mysql:used-name
    restart: always
```

**Results:** cattle will correctly connect to the mysql service in the composition (IP 172.18.0.3 ), but rancher-catalog-service will exit the composition network and connect to the external name **used-name**.`hostname -d` (IP 10.10.10.10).

Note: _getent hosts used-name_ returns the IP of the external alias (10.10.10.10) for all tested rancher-server versions.
