### ISSUE TITLE
milli_cpu_reservation is not honored by rancher-cli and rancher-compose

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#8545]
**Rancher Versions:**
Server: 1.5.3

**Docker Version:** 1.12.6

**Rancher-CLI Version:** 0.5.1

**Rancher-Compose Version:** 0.12.4

**Steps to Reproduce:**
Create a docker-compose.yml with a "web" service and a rancher-compose.yml with
```
version: '2'
services:
  web:
    milli_cpu_reservation: 100
    scale: 1
    start_on_create: true
```

**Results:** 
 - Looking at the "Security" tab of the container the reservation is not set
 - Looking at the config of the stack in the rancher-compose.yml file  the milli_cpu_reservation doesn't show up
 - The docu claims this should be possible (https://docs.rancher.com/rancher/v1.5/en/rancher-services/scheduler/) from the rancher-compose.yml file.

**Comment by tfiduccia** [comment]
Version - v1.5.5
This is indeed a bug and when I try to use catalog or import yaml the mili_cpu_reservation is being ignored.

**Comment by borntorock** [comment]
Is this still an bug in rancher v1.6.0. We're currently using Rancher v1.6.0 and have mentioned `milli_cpu_reservation` in rancher-compose.yml file but looks this param is not being picked and shown under Security tab on rancher UI.

**Comment by soumyalj** [comment]
Tested with rancher v1.6.8-rc4. Creation of stack using UI providing the dockercompose.yml file below was successful
```
version: '2'
services:
  web:
    image: nginx
    milli_cpu_reservation: 100
    scale: 1
    start_on_create: true
```
milli_cpu_reservation was seen in the exported config file. It was set correctly in the security tab.
Also, created a stack using CLI version v0.6.4-rc1. milli_cpu_reservation is supported and the stack is created successfully.

**Comment by samvdb** [comment]
I am currently running on 1.6.10 and can confirm this issue is not fixed. 
Can this ticket be reopened?

Using rancher-compose 0.12.5 on OSX with the following rancher-compose.yml

```yml
  nginx:
      scale: 1
      milli_cpu_reservation: 5
```
