### ISSUE TITLE
Not able to resolve rancher-metadata.rancher.internal with alpine:3.4 image does not work.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8588]
Rancher Versions: v1.5.5

Create a K8s env with 3 hosts.

Steps to reproduce the problem:
Deploy pod with - alpine:3.4 image  with command - 

```	
command: [ping]
args: [rancher-metadata.rancher.internal]
```

Container fails to start with error - ```ping: bad address 'rancher-metadata.rancher.internal'```

yml used to deploy the pod:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: mytest1
spec:
  replicas: 1
  selector:
    name: mytest1
  template:
    metadata:
      labels:
        name: mytest1
    spec:
      containers:
        - name: mytest1
          image: alpine:3.4
          command: ["ping"]
          args: ["rancher-metadata.rancher.internal"]
```
