### ISSUE TITLE
Question: how to open the grafana page in Kubernetes?

### ISSUE THREAD

**Issue by meggarr** [rancher/rancher#8594]
Just wondering how to open the grafana page in Rancher/K8s setup? Thanks!

**Rancher Versions:**
Server: 1.5.6
healthcheck:
ipsec: yes

**Comment by meggarr** [comment]
The composed URL `https://<rancher-server>/r/projects/1a6776/monitoring-grafana:80/#` does not work, while the `https://<rancher-server>/r/projects/1a6776/kubernetes-dashboard:9090/` works for the dashboard

**Comment by meggarr** [comment]
Ok, I managed open grafana by exporting the service from rancher-lb

**Comment by rbq** [comment]
Could you provide details what you did exactly? I have a fresh cluster and can't access Grafana or Heapster. The K8 Dashboard doesn't show any metrics. There is a pre-installed service:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-09-14T21:43:18Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
  resourceVersion: "86"
  selfLink: /api/v1/namespaces/kube-system/services/monitoring-grafana
  uid: b896cc5e-9995-11e7-be82-025d6ce38c5f
spec:
  clusterIP: 10.43.147.128
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by rbq** [comment]
Oops, had to open port range 30000 to 32767 on the nodes. Now I get some graphs on the dashboard, but still none of the URLs provided by `kubectl cluster-info` works.

**Comment by Parth6288** [comment]
I am also facing the similar issue. Unable to access the grafana dashboard. while accessing the URL provided in the cluster-info i can as below.

![rancherdashboard](https://user-images.githubusercontent.com/16204776/30534243-fec5e924-9c7a-11e7-9ed1-654b509e4bf1.JPG)

**Comment by meggarr** [comment]
I am simply creating a Ingress resource, so that the LB will be created automatically by Rancher on the host of orchestration.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: monitoring-grafana
  annotations:
    config: "defaults\ntimeout client 10m\ntimeout server 10m\n"
    io.rancher.scheduler.affinity.host_label: "orchestration=true"
spec:
  backend:
    serviceName: monitoring-grafana
    servicePort: 80
```
