### ISSUE TITLE
When upgrading k8s stacks using rancher-cli using  "--confirm-upgrade" , rancher-ingress-controller/rancher-kubernetes-agent continue to be in "upgraded" state

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8598]
Rancher Versions: v1.5.6

K8s environment with 3 hosts.

Steps to reproduce the problem:

Force upgrade K8s stack using rancher cli , using command ```rancher up --stack kubernetes --force-upgrade -d --confirm-upgrade```

Even after waiting for 20 mts , rancher-ingress-controller/rancher-kubernetes-agent continues to be in "upgraded" state. All other services get to "active" state as expected.

**Comment by ecliptik** [comment]
Something similar is also happening with Cattle. I've been unable to reproduce it on-demand, but it crops up occasionally with a variety of different stacks in different cattle environments and masters.

Rancher: v1.5.6 and v1.5.2 (happening on two seperate masters) (HA mode with a single IP)
rancher-compose: v0.12.4
Docker: v1.12.6
OS: Ubuntu 16.04

Stacks that half upgrade and require a manual completion. We recently moved to Rancher 1.5.x and updated Rancher compose to 0.12.4 and this started happening in the last month. Before stacks would fully completely withou manual intervention.

<img width="471" alt="screen shot 2017-04-20 at 4 31 47 pm" src="https://cloud.githubusercontent.com/assets/1261742/25452877/f62be64a-2a7b-11e7-9e1e-bc915716fd73.png">

example `docker-compose.yml`

```
version: '2'
services:
  api-admin:
    ports:
      - 25230:9292
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: cluster-type=default
      io.rancher.stack.name: "demandbase/api-admin:${DOCKER_TAG}"
      org.label-schema.build-date: "$BUILD_DATE"
      org.label-schema.version: "$GIT_TAG"
      org.label-schema.vcs-url: "$GIT_URL"
      org.label-schema.vcs-ref: "$GIT_COMMIT"
      org.label-schema.name: "$PROJECT_NAME"
      org.label-schema.vendor: "$VENDOR"
      com.demandbase.build-url: "$BUILD_URL"
      com.demandbase.job-name: "$JOB_NAME"
      com.demandbase.job-url: "$JOB_URL"
      com.demandbase.build-number: "$BUILD_NUMBER"
      com.demandbase.product: "api-admin"
      com.demandbase.environment: "$ENVIRONMENT"
    env_file:
      - .env.export
    image: "demandbase/api-admin:${DOCKER_TAG}"
    logging:
      options:
        labels: "api-admin-${ENVIRONMENT}"
    stdin_open: true
    volumes:
      - data:/db/files
  upload-worker:
    command: [ "exec", "sidekiq", "-q", "list_upload", "-q", "batch_upload", "-c", "2" ]
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: cluster-type=default
      io.rancher.stack.name: "demandbase/api-admin:${DOCKER_TAG}"
      org.label-schema.build-date: "$BUILD_DATE"
      org.label-schema.version: "$GIT_TAG"
      org.label-schema.vcs-url: "$GIT_URL"
      org.label-schema.vcs-ref: "$GIT_COMMIT"
      org.label-schema.name: "$PROJECT_NAME-upload_worker"
      org.label-schema.vendor: "$VENDOR"
      com.demandbase.build-url: "$BUILD_URL"
      com.demandbase.job-name: "$JOB_NAME"
      com.demandbase.job-url: "$JOB_URL"
      com.demandbase.build-number: "$BUILD_NUMBER"
      com.demandbase.product: "api-admin"
      com.demandbase.environment: "$ENVIRONMENT"
    env_file:
      - .env.export
    environment:
      NEW_RELIC_AGENT_ENABLED: false
    image: "demandbase/api-admin:${DOCKER_TAG}"
    logging:
      options:
        labels: "api-admin-upload-worker-${ENVIRONMENT}"
    stdin_open: true
    volumes:
      - data:/db/files
  gooddata-worker:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: cluster-type=default
      io.rancher.stack.name: "demandbase/api-admin:${DOCKER_TAG}"
      org.label-schema.build-date: "$BUILD_DATE"
      org.label-schema.version: "$GIT_TAG"
      org.label-schema.vcs-url: "$GIT_URL"
      org.label-schema.vcs-ref: "$GIT_COMMIT"
      org.label-schema.name: "$PROJECT_NAME-gooddata_worker"
      org.label-schema.vendor: "$VENDOR"
      com.demandbase.build-url: "$BUILD_URL"
      com.demandbase.job-name: "$JOB_NAME"
      com.demandbase.job-url: "$JOB_URL"
      com.demandbase.build-number: "$BUILD_NUMBER"
      com.demandbase.environment: "$ENVIRONMENT"
    env_file:
      - .env.export
    environment:
      NEW_RELIC_AGENT_ENABLED: false
    image: "demandbase/api-admin:${DOCKER_TAG}"
    logging:
      options:
        labels: "api-admin-gooddata-worker-${ENVIRONMENT}"
    stdin_open: true
    command: [ "exec", "sidekiq", "-q", "gooddata", "-c", "2" ]
    volumes:
      - data:/db/files
volumes:
  data:
    driver: local
```

corresponding `rancher-compose.yml`

```
version: '2'
services:
  api-admin:
    scale: 1
  upload-worker:
    scale: 1
  gooddata-worker:
    scale: 1
```

`rancher-compose` command to deploy to Cattle environment

```
rancher-compose --file docker-compose-rancher.yml \
                --env-file .env.export \
                --project-name api-admin \
                up \
                --force-upgrade \
                --confirm-upgrade \
                --pull \
                -d
```
