### ISSUE TITLE
Unable to run global services with local volume driver

### ISSUE THREAD

**Issue by ket4yii** [rancher/rancher#8604]
**Rancher Versions:**
Server: 1.5.5

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

RancherOS on parallels6 vm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I used this compose file:

```
version: '2'
volumes:
  consul-data:
    external: false
services:
  agent:
    image: consul
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 'true'
      SERVICE_IGNORE: 'true'
    network_mode: host
    volumes:
    - consul-data:/consul/data
    - /etc/config.d/consul:/etc/consul.d
    logging:
      driver: json-file
    command:
    - agent
    - -config-dir
    - /etc/consul.d
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: role=system
      io.rancher.scheduler.global: 'true'

```

**Results:** 

And got this: 

```
(Failed to allocate instance [container:1i2576]: Bad instance [container:1i2576] in state [error]: Allocation failed: volume [3277] must have exactly these pool(s): [13], valid host(s) [11])
```

Moreover one service ran on a host and created volume(I tried to do it more than once, so there is more than one volume for service):

```
docker volume ls

local               071f63b1a53e70738274efc75940050f20df1945b9b7794e0ca8ab8beaef173d
local               0999fbc06da37532badfeae382e4b11a43fb37691ea8d66d07bbd66b2114a849
local               5ef4ecac1eb1c841c154006b6530182e41bc52feddaaf13d68f81efe9becb663
local               Consul_consul-data_11edd
local               Consul_consul-data_27b41
local               Consul_consul-data_37a81
local               Consul_consul-data_ad998
local               Consul_consul-data_eaf9b
local               a453661bd0761a012f9d7eb139f164278c6c32e8f0784f383b367ee27690594a
local               cabd372720d01667c298ba6a2ff500502c18f5e04df39169c202557cf1e38c10
local               rancher-agent-state
local               rancher-cni
local               rancher-cni-driver
```

**Comment by ket4yii** [comment]
Maybe it can help. When I view generated config volumes configuration's change to:
```
volumes:
  consul-data:
    external: true
    driver: 'null'
```
