### ISSUE TITLE
Rancher affinity label not deploying correctly

### ISSUE THREAD

**Issue by dahendel** [rancher/rancher#8615]
*Describe your issue here*
I am trying to schedule containers 1 per host, but I have to services that make up the stack. consul-masters at a scale of 3, and a global container consul-clients. I am trying to schedule the clients n all hosts that do not have a consul-masters container on them. Below are my docker/rancher-compose files:

```
version: '2'
services:
  consul-masters:
    image: dahendel/consul
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - SERVER=true
    expose:
      - "8301"
      - "8500"
    links:
      - "consul-masters:consul-masters"
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.system: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack.name=consul

  consul-clients:
    image: dahendel/consul
    network_mode: host
    stdin_open: true
    tty: true
    depends_on:
      - consul-masters
    links:
      - "consul-masters:consul-masters"
    expose:
      - "8500"
      - "8301"
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack.name=consul
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.container.system: 'true'
```
**Rancher compose:**
```
version: '2'

services:
  consul-clients:
    start_on_create: true

  consul-masters:
    scale: 3
    start_on_create: true
```

The consul-masters deploy correctly however the io.rancher.scheduler.global: 'true' label on the consul-clients containers overrides the scheduler affinity and still deploys the client containers on hosts with consul-masters. If I deploy without the global label It deploys correctly if I set the scale to n - hostsWithoutMasters, but once the scale is bigger than the number of hosts without consul-masters it still deploys to the hosts with master containers. 

Deployed Services
![services deployed](https://cloud.githubusercontent.com/assets/11720061/25544535/889ed820-2c20-11e7-9d5c-868372f104ed.png)

Verified the scheduler labels were applied
![verifiedscheduling](https://cloud.githubusercontent.com/assets/11720061/25544540/8da0397c-2c20-11e7-9e47-f3108983c402.png)

I know I can solve this problem with just adding host labels, but I am wanting to make this an infrastructure app for a environment template. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.6` Cattle: `v0.178.4` UI: `v1.5.9` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|
