### ISSUE TITLE
Health check with strategy 'none' recreates container on unhealthy

### ISSUE THREAD

**Issue by davidmav** [rancher/rancher#8616]
Health check with strategy 'none' recreates container on unhealthy

My health check configuration:
```
  frontend:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 7780
      unhealthy_threshold: 10
      initializing_timeout: 200000
      interval: 2000
      strategy: none
      request_line: GET "/MyApp" "HTTP/1.0"
      reinitializing_timeout: 150000
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.6` Cattle: `v0.178.4` UI: `v1.5.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`container.healthcheck`|
