### ISSUE TITLE
Rancher-EBS options

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8618]
Need to make sure the following options work for EBS:
```     size: '10' # specify the size for EBS volume. This is required.
       volumeType: gp2 # specify the volume type
       iops: 1000 # specify the iops
       encrypted: true # specify whether the volume should be encrypted
       kmsKeyId: id # the full ARN of the AWS Key Management Service (AWS KMS) customer master key (CMK) to use when creating the encrypted volume
       snapshotID: id # the snapshot from which to create the volume.
```

**Comment by soumyalj** [comment]
Tested with rc4 and rc5. Example ymls below:
```
version: '2'
services:
  foo:
    image: ubuntu 
    stdin_open: true
    volumes:
    - bartest:/mydata
volumes:
  bartest:
    driver: rancher-ebs
    driver_opts:
      size: '10' # specify the size for EBS volume. This is required.
      volumeType: 'gp2' # specify the volume type
      iops: '1000' # specify the iops
      snapshotID: 'snap-089f42c78be76fbca'
```
```
version: '2'
services:
  foo:
    image: ubuntu 
    stdin_open: true
    volumes:
    - barabc1:/mydata
volumes:
  barabc1:
    driver: rancher-ebs
    driver_opts:
      size: '10' # specify the size for EBS volume. This is required.
      volumeType: 'gp2' # specify the volume type
      iops: '1000' # specify the iops
      encrypted: true
      kmsKeyId: 'arn:aws:kms:us-west-2:605812595337:key/df565821-b83b-486b-a3d4-0026af7ee9f4'
```

**Comment by StrongMonkey** [comment]
This is documented in this https://github.com/rancher/rancher.github.io/pull/750.

**Comment by soumyalj** [comment]
Example of using KMS key Id specifying the zone
```
version: '2'
services:
  foo1:
    image: ubuntu 
    stdin_open: true
    volumes:
    - barabc:/mydata
volumes:
  barabc:
    driver: rancher-ebs
    driver_opts:
      size: '10' # specify the size for EBS volume. This is required.
      volumeType: 'gp2' # specify the volume type
      ec2_az: 'us-west-2a'
      iops: '1000' # specify the iops
      encrypted: true
      kmsKeyId: 'arn:aws:kms:us-west-2:605812595337:key/df565821-b83b-486b-a3d4-0026af7ee9f4'

```
