### ISSUE TITLE
Creating a new service specifying an existing volume by volume id fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8628]
**Rancher Versions:**
Server:1.6.0-rc2

**Docker Version:**: 17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Deploy rancher-ebs catalog on a setup with AWS hosts
2. Add a volume volume1 through UI
3. Create a service to use volume1 and ensure you can access the volume for read and write
4. Create another service by specifying the volume id of volume1 using the yaml file below:
```
version: '2'
services:
  coo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - newvolume:/mydata
volumes:
  newvolume:
    driver: rancher-ebs
    driver_opts:
      volumeID: 'vol-03d9b99c199b16b67' 
```
**Results:** 
Creation of the new service fails as below:
```
Expected state running but got error: /VolumeDriver.Attach 'myvolidtest1_newvolume_fa3f3' (driver 'rancher-ebs') returned status 500: 500 Internal Server Error
```
EBS Driver logs:
```
5/1/2017 11:36:48 AMtime="2017-05-01T18:36:48Z" level=info msg=attach.request name="myvolidtest1_newvolume_fa3f3"
5/1/2017 11:36:48 AMtime="2017-05-01T18:36:48Z" level=error msg=attach.response error="No such volume"
5/1/2017 11:36:49 AMtime="2017-05-01T18:36:49Z" level=info msg=attach.request name="myvolidtest1_newvolume_fa3f3"
5/1/2017 11:36:49 AMtime="2017-05-01T18:36:49Z" level=error msg=attach.response error="No such volume"
5/1/2017 11:36:49 AMtime="2017-05-01T18:36:49Z" level=info msg=attach.request name="myvolidtest1_newvolume_fa3f3"
5/1/2017 11:36:49 AMtime="2017-05-01T18:36:49Z" level=error msg=attach.response error="No such volume"

```
