### ISSUE TITLE
Docker compose export displays volume driver as NULL when a service is created with existing volume specifying external:true

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8629]
Rancher Versions:
Server:1.6.0-rc2

Docker Version:: 17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

Steps to Reproduce:

1. Deploy rancher-ebs catalog on a setup with AWS hosts
2. Add a volume volume1 through UI
3. Create a stack using external:true specifying the existing volume volume1

```
version: '2'
services:
  roo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - volume1:/mydata
volumes:
  volume1:
    external: true
    driver: rancher-ebs
```
**Results:** 
The service is created successfully, but the docker-compose export displays driver as "NULL"
```
version: '2'
volumes:
  volume1:
    external: true
    driver: 'null'
services:
  too:
    image: ubuntu
    stdin_open: true
    volumes:
    - volume1:/mydata

```
Also the containers display the volumeDriver as NULL in the API
```
uuid": "1e7da15b-fd93-4064-bc85-58e580824bfe",
"version": "0",
"volumeDriver": null,
"workingDir": null

```

**Comment by soumyalj** [comment]
Tested with v1.6.0-rc4. The issue is not completely fixed. The first time when the volume is inactive, and we create a service using the volume, the driver is displayed correctly as "rancher-ebs" in export
```
version: '2'
volumes:
  drivernullvolume:
    external: true
    driver: rancher-ebs
services:
  roo:
    image: ubuntu
    stdin_open: true
    volumes:
    - drivernullvolume:/mydata

```
When we create more services using the same volume after it is active, the driver is displayed as "NULL" in export
```
version: '2'
volumes:
  drivernullvolume:
    external: true
    driver: 'null'
services:
  roo:
    image: ubuntu
    stdin_open: true
    volumes:
    - drivernullvolume:/mydata
```
