### ISSUE TITLE
Networking fails after 12 hours

### ISSUE THREAD

**Issue by stoehrm5** [rancher/rancher#8645]
We have installed rancherOS on two (baremetal) machines. After 12 hours a simple stack, which consists of containers pinging each other will no longer be functional. The network connection between the two rancherOS machines is breaking down. We have seen this issue also in a VM environment and reproduced it for at least 10 times.

# Versions:
- Rancher  v1.5.6  
- Cattle:  v0.178.4  
- UI:  v1.5.9  
- Access| Disabled | |Orchestration| Cattle | |Route| hosts.index

# Steps done:

- initialize rancher server on machine 1: 

`sudo docker run -d --restart=unless-stopped --name=rancher-server -p 8080:8080 rancher/server`

- add rancher agents according to webinterface
- add stack:

## Container 
Dockerfile:

```
FROM centos:7.2.1511
MAINTAINER xxx
RUN yum -y update
ADD start.sh /
CMD ["/bin/bash", "/start.sh"]
```

start.sh:

```
if [ -z "${PINGTEST2_PORT_20000_TCP_ADDR+x}" ]; then
        echo doing nothing
        while [ 1 ]; 
        do
                sleep 100
        done
else
        while [ 1 ]; 
        do
                ts=`date +"%Y-%m-%d_%H:%M:%S"`
                echo -n "$ts "  >> /tmp/ping.log
                ping -c 4  $PINGTEST2_PORT_20000_TCP_ADDR |grep loss >> /tmp/ping.log
        done
fi
```

## Stackconfig
docker-compose.yml 

```
version: '2'

services:
   pingtest:
     image: pingtest
     restart: always
     links:
       - pingtest2
     ports: 
        - 20000
   pingtest2:
     image: pingtest
     restart: always
     ports: 
       - 20000
```

rancher-compose.yml 

```
version: '2'
services:
  pingtest:
      scale: 2
  pingtest2:
    scale: 1
```
