### ISSUE TITLE
Escape {{ }} in docker-compose for go template

### ISSUE THREAD

**Issue by dirosden** [rancher/rancher#8652]
**Rancher Versions:**
Server: 1.4.3 | 1.5.8

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux coreos-vm 4.9.24-coreos #1 x86_64 Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz GenuineIntel GNU/Linux

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
docker-compose with similar environment variables:
```
  logagent:
    image: dirosden/caplogagent:dev
    restart: always
    ports:
      - 8000:80
    environment:
      KAFKA_TEMPLATE_JSON: 1
      KAFKA_TEMPLATE_1: "time=\"{{.Time}}\" container_name=\"{{.Container.Name}}\" source=\"{{.Source}}\" data=\"{{.Data}}\""
      KAFKA_TEMPLATE_2: "time=\"{{`{{.Time}}`}}\" container_name=\"{{`{{.Container.Name}}`}}\" source=\"{{`{{.Source}}`}}\" data=\"{{`{{.Data}}`}}\""
      KAFKA_COMPRESSION_CODEC: snappy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.global: 'true'
```

**Results:** 
 KAFKA_TEMPLATE_1 will work properly in Rancher Server version 1.4.3
 KAFKA_TEMPLATE_2 will work properly in Rancher Server version 1.5.8

Need a way to get the template escaped properly so that we get this in the environment:
KAFKA_TEMPLATE=time="{{.Time}}" container_name="{{.Container.Name}}" source="{{.Source}}" data="{{.Data}}"
