### ISSUE TITLE
Support appending to a line of Haproxy config to faciliate mutual SSL

### ISSUE THREAD

**Issue by dxxxxxg** [rancher/rancher#8655]
this parameter needs to be on the line in haproxy that starts with "bind".

Rancher allows you to define the custom config it merges it with ranchers haproxy config which causes a duplicate bind lines which is a syntax error.

Here is the file: "/etc/haproxy/haproxy.cfg"

**Comment by wjimenez5271** [comment]
An example of the bind line that we would need to append to. Say we have the following section in our haproxy config:

```
frontend myfrontend
    bind *:443 ssl crt /etc/haproxy/mycert.pem 
    mode http
    default_backend nodes
```

We need to be able to append something to the second line in the above (`bind *:443 ssl crt /etc/haproxy/mycert.pem`), so the result is:

```
frontend myfrontend
    bind *:443 ssl crt /etc/haproxy/mycert.pem ca-file /etc/haproxy/ca.crt verify required
    mode http
    default_backend nodes
```

**Comment by stszap** [comment]
Hit this problem while trying to setup amazon api gateway with client-side certificate and rancher lb as a backend. We removed "bind" keyword in frontend section of /etc/haproxy/haproxy_template.cfg  inside lb container and used this configuration (this is simplified version):
  
```
lb_config:
  certs:
  - <our cert>
  default_cert: <our cert>
  config: |-
    frontend 3000
      bind *:3000 ssl crt <path to default cert> ssl crt /etc/haproxy/certs/current verify required ca-file <path to ca for client cert>
```

We are using custom image, so all changes are persistent, but I think it can be done with standart lb image and volumes. We would like "normal" option to configure bind settings too.
