### ISSUE TITLE
driver_opts set for external volumes in rancher compose gets ingnored without amy indication to the user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8657]
Rancher Versions: v1.6.0-rc4

Steps to reproduce the issue:
Create a service with the following yml having volume - yello1 created in UI without any driver_opts.

```
version: '2'
volumes:
  yello11:
    external: true
    driver_opts:
      export: /var/nfs
      host: *****
    driver: rancher-nfs
  nginx1:
    image: nginx
    volumes:
    - yello11:/data1
```

Volumes get created in the nfs server configured during the rancher-nfs deployment and the driver_opts settings for this volume is ignored.

In such cases , instead of silently ignoring the settings , error message should be provided to the user.
