### ISSUE TITLE
Containers should get deployed to the right zone when creating service with volume using KmsKeyId and VolumeID

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8666]
Rancher Versions:

Server: 1.6.0-rc5

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Cloud

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB): Single node

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle

Steps to Reproduce:
1. Deploy rancher-ebs catalog on a setup with AWS-hosts
2. Create an encrypted key in east zone. Create a service with volume using this key in a setup with hosts in west zone and east zone. Service creation fails as the keys are from east zone.
```
version: '2'
services:
  foo:
    image: ubuntu 
    stdin_open: true
    volumes:
    - bartestabc:/mydata
volumes:
  bartestabc:
    driver: rancher-ebs
    driver_opts:
      size: '10' # specify the size for EBS volume. This is required.
      volumeType: 'gp2' # specify the volume type
      iops: '1000' # specify the iops
      encrypted: true
      kmsKeyId: 'arn:aws:kms:us-east-1:605812595337:key/654f82eb-5ba7-4f40-92ba-81b8639e0f2f'
```
3. A volume ID from east zone cannot be used with hosts in west zone
```
version: '2'
services:
  coo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - soumyanewawsvolume:/mydata
volumes:
  soumyanewawsvolume:
    driver: rancher-ebs
    driver_opts:
      volumeID: 'vol-0e9f109d2dc24ca29'
```
Note:
Using ```ec2_az: zone``` in driver options will schedule the containers to the appropriate zone currently
