### ISSUE TITLE
Layer-2 Flat networking support in Rancher cattle

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8673]
I have updated network-manager, it can be able to support other CNI drivers. So Flat network support can be achieved. #8535 

**How does Flat work?**
![image](https://cloud.githubusercontent.com/assets/998984/25739860/58a357c2-31b6-11e7-8bec-1a1b3198f2b8.png)
Notice:
1. Container network and eth0 in the same network
2. Move eth0 IP setting to flat-br, eth0 needs to be bound on the bridge flat-br. This part will be executed automatically

**For network-manager version requirements:**
As previously mentioned, make sure that the version you are using includes this commit https://github.com/rancher/plugin-manager/commit/6512bf77f38f3ed6751644aca8165e311634881b
Test image: **niusmallnan/network-manager:dev**

**For catalog item:**
There is a catalog item that is being tested.
Repo: https://github.com/niusmallnan/flatnet-catalog.git
Branch: master

**For rancher-cni-flat:**
Basically, it is based on rancher-cni-bridge. I just add a flag named isFlat and some logic.
I'm not sure if this needs to be merged into rancher-cni-bridge.
Repo: https://github.com/niusmallnan/rancher-cni-bridge
Branch: flat

Ensure that the Rancher server version is v1.6.0+

**Comment by leodotcloud** [comment]
> Move eth0 IP setting to flat-br, eth0 needs to be bound on the bridge flat-br. This part will be executed automatically

@niusmallnan Did you mean this has to be done outside of Rancher manually by a System admin?

**Comment by niusmallnan** [comment]
Use the following cni configuration:
```
'10-rancher-flat.conf':
          name: rancher-cni-network
          type: rancher-bridge
          bridge: ${FLAT_BRIDGE}
          bridgeSubnet: ${SUBNET}
          bridgeIP: '__host_interface__: ${FLAT_BRIDGE}'
          logToFile: /var/log/rancher-cni.log
          isDebugLevel: ${RANCHER_DEBUG}
          hairpinMode: {{ .Values.RANCHER_HAIRPIN_MODE }}
          promiscMode: {{ .Values.RANCHER_PROMISCUOUS_MODE }}
          hostNat: {{ .Values.HOST_NAT }}
          mtu: ${MTU}
          ipam:
            type: rancher-cni-ipam
            logToFile: /var/log/rancher-cni.log
            isDebugLevel: ${RANCHER_DEBUG}
            subnetPrefixSize: /${SUBNET_PREFIX_SIZE}
            routes:
            - dst: 0.0.0.0/0
              gw: ${GATEWAY}
            - dst: 169.254.169.250/32
              gw: '__host_interface__: ${FLAT_BRIDGE}'
```
Replace the `__host_interface__` value in the plugin-manager.
