### ISSUE TITLE
Secrets aren't exported correctly

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8680]
Creating a simple service using secrets will result in the following export.

```
version: '2'
services:
  test:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    secrets:
    - uid: '0'
      gid: '0'
      mode: '444'
      name: ''
      secretId: 1
    labels:
      io.rancher.container.pull_image: always
```
