### ISSUE TITLE
Per_container scoped volume

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8683]
Steps to reproduce:
1 . Create a service using the following yaml file.
```
sion: '2'
volumes:
  daishan-re:
    driver_opts:
      size: '10'
    driver: rancher-ebs
    per_container: true
services:
  coo:
    image: ubuntu
    stdin_open: true
    volumes:
    - daishan-re:/mydata
    labels:
      io.rancher.sidekicks: test-data
  test-data:
    image: ubuntu:14.04.2
    stdin_open: true
    volumes:
    - daishan-re:/mydata
    tty: true
    command:
    - cat
```
2. Upgrade service, by specifying an invalid option to it.(Example: logger_driver: 123). This will cause service failed to upgrade.
3. The existing volume will be deleted. A new volume( with the new DeploymentUUID name) will be created. User will lose data from the previous volume.

This is reproducible very consistently with container_scoped volume. Seems like the container_scoped volume is specifically bind to a deploymentUUID. Once the deployementUUID is changed during the upgrade, the volume will be deleted, which is not desired.
