### ISSUE TITLE
Ceph RBD support in Rancher storage

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8722]
Some users expect to use RBD storage under Cattle. **Jewel** is the latest LTS version, so I will give priority to support it and test it well. Here are some usage information.

Rancher RBD catalog item:
Repo: https://github.com/niusmallnan/rancher-rbd-catalog
Use this repo to deploy the rancher-rbd driver.

You can use the following compose files to test.
**Stack Scoped**:
```
version: '2'
services:
  foo:
    image: nginx
    volumes:
    - bar:/var/lib/storage
volumes:
  bar:
    driver: rancher-rbd
    driver_opts:
      size: 2G
      pool: rbd
```
For stack scoped: The containers for any service using the RBD volume will automatically be scheduled onto the same host as where the RBD volume is attached to.

As we all know, Ceph's configuration file is very complex, so it is difficult to automatically generate it. You need to manually synchronize the configuration file in the /etc/ceph directory on all rancher-agent nodes, rancher-rbd will mount this directory.

If you do not have a Ceph setup, you can use [ceph-docker](https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/16.04/demo) to quickly build your setup.
```
docker run -d --net=host -v /etc/ceph:/etc/ceph -e MON_IP=192.168.0.20 -e CEPH_PUBLIC_NETWORK=192.168.0.0/24 ceph/demo:tag-build-master-jewel-ubuntu-16.04
```

Due to librbd compatibility with the kernel, it is recommended to use ubuntu16.04.
It is recommended to use Rancher v1.6.0+ .
