### ISSUE TITLE
rancher and rancher-compose not update lb_config

### ISSUE THREAD

**Issue by davidnussio** [rancher/rancher#8724]
**Rancher Versions:**
Server: v1.5.6
healthcheck: v0.2.3
ipsec: v0.11.2
network-services: v0.9.1
scheduler: v0.7.5

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
 Ubuntu 16.04.2 LTS (4.4.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create service with **rancher up** (v0.5.1) or **rancher-compose up** (v0.12.4)
```
# docker-compose.yml
version: '2'
services:
  web2:
    image: httpd
    labels:
      proxy: me
  web1:
    image: nginx
    labels:
      proxy: me
```
```
# rancher-compose.yml
version: '2'
services:
  web2:
    scale: 1
  web1:
    scale: 1
```
2. Add lb_config port_rules and redeploy configuration **rancher up --force-upgrade**
```
# rancher-compose.yml
version: '2'
services:
  web2:
    scale: 1
    lb_config:
      port_rules:
        - target_port: 80
        hostname: httpd.localhost
  web1:
    scale: 1
    lb_config:
      port_rules:
        - target_port: 80
        hostname: nginx.localhost
```

**Results:** 
lb_config section still missing and selector rule in the balancer does't work

![selection_031](https://cloud.githubusercontent.com/assets/324371/25893002/8af72fc8-3576-11e7-816a-426e47f04bbc.png)

If remove (**rancher rm**) the stack and recreate (**rancher up**) the port_rules appear and everything works.
