### ISSUE TITLE
rancher-compose healthcheck shows up null

### ISSUE THREAD

**Issue by michaelsobota-charter** [rancher/rancher#8737]
When deploying a service with rancher-compose the health_check statement is not honored. Service starts as expected but with a null health_check. This is only happening to a few services, not all and the rancher-compose setups are identical besides the ports and service names being different. The health_check comes up fine on all those other services.

```
version: '2'
services:
  my-service:
    image: my-service:latest
    health_check:
      port: 9000
      request_line: GET / HTTP/1.0
      interval: 10000
      healthy_threshold: 2
      unhealthy_threshold: 3
      response_timeout: 10000
```

Verbose rancher-compose API logging shows healthCheck as null when making a POST to the Rancher API:
`"healthCheck":null,"healthCmd":null,"healthInterval":null,"healthRetries":null,"healthState":null,"healthTimeout":null,`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.1` Cattle: `v0.174.8` UI: `v1.2.39` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|
