### ISSUE TITLE
Host affinity rules are ignored when creating a service using EBS volume

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8762]
**Rancher versions:**
rancher/server:v1.6.0

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS/digital ocean

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a setup with 2 AWS hosts in west zone and deploy EBS catalog
2. Add a digital ocean host with label foo=bar
3. Create a service using EBS volume and host affinity label foo=bar as below:
```
version: '2'
volumes:
  bar1234:
    driver_opts:
      ec2_az: us-west-2a
      size: '10'
    driver: rancher-ebs
services:
  foo:
    image: nginx
    volumes:
    - bar1234:/var/lib/storage
    labels:
      io.rancher.scheduler.affinity:host_label: foo=bar

```
**Results:**
The service gets scheduled on a host in west-zone without the label foo=bar. The host affinity rule is ignored

Expected
Service creation should fail as there is no host in west zone with label foo=bar
