### ISSUE TITLE
support for waiting for service to pass health check before continuing deploy

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#8778]
Currently we wait for a service to be started before proceeding in a stack deploy when the `depends_on` key is used in the `docker-compose.yml`. However the container is only started and the process inside the container may not be ready until sometime later. This issue is a feature request to support waiting for a service to transition to a `healthy` state before proceeding with a deploy.

**Comment by wjimenez5271** [comment]
https://github.com/rancher/rancher-compose-executor/pull/47

**Comment by deniseschannon** [comment]
@wjimenez5271 Can you provide some instructions on how to use this feature and how QA can test it? 

Also, add some docs? :)

**Comment by wjimenez5271** [comment]
To use, set the label `io.rancher.service.wait_for_healthcheck` in your docker-compose.yml for the stack on each service you want Rancher to wait for the the health state to be "healthy" before marking it as deployed. This means any services depending on this service will not deploy until it transitions into a healthy state as defined by the requirements for its health check.

**Comment by deniseschannon** [comment]
@galal-hussein This is in cattle master and will be in v1.6.1-rc9 for catalogs/add stack in the UI. For now, can you test with CLI v0.6.1-rc2, which is available here: https://github.com/rancher/cli/releases on Rancher v1.6.1-rc8?

**Comment by galal-hussein** [comment]
Rancher server: v1.6.1-rc8
Rancher cli: v0.6.1-rc2

I used the following docker-compose and rancher-compose files to validate the feature:

docker-compose.yml
```
version: '2'
services:
  wordpress:
    image: wordpress
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 80:80
  
  db:
    image: mariadb
    labels:
      io.rancher.service.wait_for_healthcheck: true
    environment:
      MYSQL_ROOT_PASSWORD: example
```

rancher-compose.yml
```
wordpress:

db:
  scale: 1
  start_on_create: true
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 3306
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000
```

I can see that wordpress container won't start until the db container is in healthy state and the healthcheck verified that port 3306 is open.
