### ISSUE TITLE
environmentAdmin role does not work

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#8783]
**Rancher versions:**
rancher/server: 1.5.9

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Create a stack with:

```yaml
version: '2'
services:
  hello:
    image: tutum/hello-world
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

Log in to the container and use the `CATTLE_AGENT_INSTANCE_AUTH`:

```
$ curl -s -H "Authorization: ${CATTLE_AGENT_INSTANCE_AUTH}" "${CATTLE_CONFIG_U
RL}/certificates"
```

**Results:**

The API returns "not found":

```
{"id":"eb303c48-70c1-4928-8241-47b706b76a05","type":"error","links":{},"actions"
:{},"status":404,"code":"Not Found","message":"Not Found","detail":null,"baseTyp
e":"error"}
```
