### ISSUE TITLE
have rancher-compose or cli environment aware

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8791]
Currently conditionals are evaluated in docker-compose files. Asking for a conditional in docker-compose that I wanted to impact something in rancher compose (i.e. scale). 

Example case would be:
If environment == qa: scale 1 elseif env == prod: scale 10

**Comment by deniseschannon** [comment]
As of 1.6, you can have any item in rancher-compose.yml moved to docker-compose.yml and have templating work on the fields that were typically in rancher-compose.yml.

**Comment by joshwget** [comment]
I guess there were two things in here, `If environment == qa` isn't something that's currently possible.

**Comment by aemneina** [comment]
Rancher CLI is environment aware... it would be good to have an environment environment variable (sorry that sounds confusing, but what I'm looking for).

**Comment by soumyalj** [comment]
@carolynhu : Can you please provide an example for the above feature ?

**Comment by carolynhu** [comment]
This issue is similar to what we've solved for {{ .Stack.Name }} support here https://github.com/rancher/rancher/issues/3393
and its docs is here for reference: http://rancher.com/docs/rancher/v1.6/en/cli/variable-interpolation/#stack-name-interpolation
Same usage as {{ .Stack.Name }} by replacing it with {{ .Environment.Name }}

**Comment by soumyalj** [comment]
Tested with master using the UI. Created a stack from UI using the {{ .Environment.Name }} as part of volume mount path: Example for creating a stack "testvol" in environment "Default":
```
version: '2'
volumes:
  foo3:
    driver: rancher-nfs
services:
  nginxstack:
    image: nginx
    volumes:
    - foo3:/{{ .Environment.Name }}/{{ .Stack.Name }}/mydata
```
The service created had a volume mount in Default/testvol/mydata as expected

Also, tested with CLI version v0.6.4-rc1 and stack creation with a service using {{ .Environment.Name }} was successful.
```
version: '2'
services:
  web:
    image:  nginx
    labels:  
      test: {{ .Environment.Name }}
```
The service created had a label with key:value as test: Default
