### ISSUE TITLE
Host losing network connectivity after been restarted.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#8852]
**Rancher versions:**
rancher/server:v1.5.9
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.2.3
ipsec:v0.0.7
network-services:v0.1.2
scheduler:v0.5.1
kubernetes (if applicable):v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
```#docker info
Containers: 13
Running: 11
Paused: 0
Stopped: 2
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 69
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: host2
ID: GJ37:EDR5:XSCJ:HXFA:4A3Z:JEKQ:AMIX:5NAJ:553P:CTLO:BKJQ:MHG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
127.0.0.0/8
# docker version
Client:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
 
Server:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
#cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
#uname -r
3.19.0-77-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server + 2 hosts
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Add two hosts to rancher server and wait to kubernetes stack been installed. Then deploy traefik ingress controller as DaemonSet:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8081
        securityContext:
          privileged: true
        args:
        - -d
        - --web
        - --web.address=:8081
        - --kubernetes
```
Now restart on of the hosts. 
**Results:**
One of the hosts (sometimes two) loosing network connectivity after restart. 

I tried to flush iptables to default state with this commands: 
```
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
```
Tried to remove all containers and restart docker-engine, tried to flush routing tables and then ifdown/ifup eth0. Nothing helped. Only restart of host vm helped.
With rancher 1.4.1 i don't have this problem.
