### ISSUE TITLE
docker-compose.yml / environment section

### ISSUE THREAD

**Issue by rodislav** [rancher/rancher#8956]
*Describe your issue here*

Hello, while creating a stack I've added this piece of docker-compose.yml file: ``

```yml
activemq:
  image: webcenter/activemq
  ports:
    - 61616:61616
    - 8161:8161
  restart: always
  environment:
    - ACTIVEMQ_ADMIN_LOGIN
    - ACTIVEMQ_ADMIN_PASSWORD
```

and for some reason when I go to "View config"
2 sections are not present: restart and environment
yet, if I use the API then the content of the initial docker-compose.yml is correct

as well, it seems the variables are not considered while running the images

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.code`|

**Comment by rodislav** [comment]
I've changed variables in environment to this: 

```yml
activemq:
  image: webcenter/activemq
  ports:
    - 61616:61616
    - 8161:8161
  restart: always
  environment:
    ACTIVEMQ_ADMIN_LOGIN: ${ACTIVEMQ_ADMIN_LOGIN}
    ACTIVEMQ_ADMIN_PASSWORD: ${ACTIVEMQ_ADMIN_PASSWORD}
```
now the section is there, yet the values are not taken from environment
