### ISSUE TITLE
[RFE] Specify source port on service side when using selector based load balancer

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8994]
**Rancher versions:**
rancher/server: 1.6.0
cattle

When working with selector based Load Balancers we currently have to specify the source port when configuring the selector rule in the load balancer.
Instead we would like to be able to configure the source port on the service side. For example:

docker-compose
```
version: '2'
services:
  loadbalancer:
    image: rancher/lb-service-haproxy:<version>
    ports:
    - 80, 8080
  web-service:
    image: nginx
    labels:
      foo: bar
```
rancher-compose
```
version: '2'
services:
  loadbalancer:
    scale: 1
    lb_config:
      port_rules:
      - selector: foo=bar
        protocol: http
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  web-service:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
         target_port: 81
         hostname: test.com
```
