### ISSUE TITLE
service from rancher-catalog not updated upon change

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#8997]
**Rancher versions:**
rancher/server: 1.6.0

**Docker version: (`docker version`,`docker info` preferred)**

docker 17.03

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

When creating a application in a rancher-catalog  with a  docker-compose.yml such as:

```
{{- if eq .Values.DB "true" }}
  mongo:
    image: mongo:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
{{- end }}
```
If we set **DB=true** when instantiating the application from the catalog, mongo will be deployed correctly 
If I then click up to date button on the stack I will get the catalog form, then I change **DB to false** and hit upgrade.

**Then the mongo service is not removed.**

It should be removed because that's what I asked and my service is in an inconsitent state as it's not the state that the catalog describes.

**Results:**
The stack should match the description in the catalog, if DB is switched to false, it must be removed
