### ISSUE TITLE
Volumes not defined in top level volumes section show up there when stack is exported as compose

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9000]
When you add a service with no driver specified in the UI, the export shows that the driver is `null`. ~~Since no driver assumes `local`, we should export `driver: local`.~~ `EDIT: If the volume was not defined originally as a top level volume, it should not show up there when exported~~ -Craig` 

```
version: '2'
volumes:
  foo2:
    external: true
    driver: 'null'
```

**Comment by StrongMonkey** [comment]
fixed in https://github.com/rancher/cattle/pull/2746.

**Comment by ket4yii** [comment]
And related issue #8604. The same thing with global services, but only the first one creates volume. Other services just can't create local volumes.

**Comment by cjellick** [comment]
@deniseschannon adding an entry to the volume section at all is wrong. The exported config should simply look like:
```
version: v2
services:
  volumes:
  - foo2:/whatever
```
This ensures that stacks can be "roundtripped", meaning that you can export the config and then use it to create a new stack (even in a new environment).

**Comment by soumyalj** [comment]
Tested with 1.6 master and 1.6.3-rc1. 
1)Created a stack with no top level volumes. The export config did not have top level volume section. Created another stack with the exported config and it was functional.
Stack Input file
```
version: '2'
services:
  test:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    volumes:
      - foo2:/data
```
Exported file
```
version: '2'
services:
  test:
    image: ubuntu:14.04.3
    stdin_open: true
    volumes:
    - foo2:/data
    tty: true

```
2) Created a stack with volume section but no driver opts using the below file:
```
version: '2'
volumes:
  foo2:
    external: false
services:
  test2:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    volumes:
      - foo2:/data
```
Exported file:
```
version: '2'
volumes:
  foo2: {}
services:
  test2:
    image: ubuntu:14.04.3
    stdin_open: true
    volumes:
    - foo2:/data
    tty: true
```
Created another stack using the exported file and it was functional.
