### ISSUE TITLE
Creating stack with exported config results in errors

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9010]
**Rancher versions:**
rancher/server:Master

**Docker version: (`docker version`,`docker info` preferred)**17.05.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack using the below config:
    launch_config = {"imageUuid": TEST_SERVICE_OPT_IMAGE_UUID,
                     "command": command,
                     "dataVolumes": [docker_vol_value],
                     "environment": env_var,
                     "capAdd": cap_add,
                     "capDrop": cap_drop,
                     "dnsSearch": dns_search,
                     "dns": dns_name,
                     "privileged": True,
                     "domainName": domain_name,
                     "stdinOpen": True,
                     "tty": True,
                     "memory": memory,
                     "cpuSet": cpu_set,
                     "cpuShares": cpu_shares,
                     "restartPolicy": restart_policy,
                     "directory": "/",
                     "hostname": host_name,
                     "user": user,
                     "labels":
                         {"io.rancher.scheduler.affinity:container_label":
                          "c1=vol"}
                     }

    service, stack = create_env_and_svc(client, launch_config,
                                      scale)
2. Obtain the exported configs using stack.exportconfig() 
3. Creating a stack using rancher cli with the above exported config fails.

Exported docker compose file:

```
version: '2'
services:
  test892756:
    image: ibuildthecloud/helloworld:latest
    restart:
      maximumRetryCount: 10
      name: on-failure
    cap_drop:
    - KILL
    stdin_open: true
    volumes:
    - /test/container:/test/vol1:ro
    dns:
    - 1.2.3.4
    domainname: rancher.io
    cpuset: '0'
    command:
    - sleep
    - '9000'
    labels:
      io.rancher.scheduler.affinity:container_label: c1=vol
    privileged: true
    mem_limit: 8000000
    cap_add:
    - CHOWN
    hostname: test
    environment:
      TEST_FILE: /etc/testpath.conf
    dns_search:
    - 1.2.3.4
    tty: true
    user: root
    cpu_shares: 400
```
Error below:

```Obtained Response: [u'time="2017-06-08T22:30:51Z" level=error msg="Could not parse config for project test698247rancher : Service \'test892756\' configuration key \'restart\' contains an invalid type, it should be a string." \n', u'time="2017-06-08T22:30:51Z" level=fatal msg="Failed to read project: Service \'test892756\' configuration key \'restart\' contains an invalid type, it should be a string." \n']```
