### ISSUE TITLE
Raise error for empty volumes section in compose v2 syntax

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9020]
While this is valid:
```
version: '2'
volumes: {}
services:
  foo:
  volumes:
  - vol-foo:/zzz
```
its behavior is ambiguous. Some users expect that to be sufficient to cause all inline volumes defined within a service to become stack scoped. To avoid this ambiguity, we should raise an error if a user explicitly defines an empty volumes section.
