### ISSUE TITLE
Stack scoped local volumes are not deleted when stack is deleted.

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9038]
**Rancher versions:**
rancher/server: v1.5.x, 1.6.x

**Docker version: (`docker version`,`docker info` preferred)**
Any

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Any

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Any

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Any

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Using compose, create a stack scoped local volume:
  ```
  version: '2'
  volumes:
    foo: {}
  services:
    sv1:
      image: nginx
      volumes:
      - foo:/test
  ```
2. Wait for stack to become active and then delete.

**Results:**
Expected:
On the host, the volume <stackname>_foo_<random> should be deleted.

Actual:
Its not deleted.

**Notes:**
This is caused by how we create local volumes from volume templates. There's a few internal fields we aren't setting correctly.
