### ISSUE TITLE
422 Error on using volumes-from with attachment data container

### ISSUE THREAD

**Issue by forktheweb** [rancher/rancher#9056]
**Rancher versions:**
rancher/server: 1.5.10

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce
Cattle environment

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Rancher OS 0.7.1

**Steps to Reproduce:**

When running a docker-compose with 'volumes-from', rancher gives an error #422.... a "not so nice" error. 
This is resolved when running a side-kick container, but I think this could be better documented and better error'd.

![422error](https://user-images.githubusercontent.com/16281585/27105942-6a1c4032-505f-11e7-852c-c923408df4b3.png)

Sample docker-compose:

```
version: '2'
services:
  web-service:
    image: pierrezemb/gostatic
    volumes:
      - website:/srv/http
    command:
    - '-'
    - '--forceHTTP'
  helper-sidekick:
    image: some-volume-image:latest
    labels:
       io.rancher.container.start_once: true
  primary-service:
    image: alpine:3.5
    entrypoint: /somedir/entrypoint.sh
    volumes:
      - website:/srv/http
    volumes_from:
      - helper-sidekick
```
**Results:**

Also interesting to note that Rancher mangles the docker-compose and removes the service that uses "volumes-from" entirely.  I'm guessing that should not be the behavior.

Screenshot provided.

Thanks guys!

**Comment by janeczku** [comment]
I think we need to document specifically that "volumes_from" are not supported unless you use a sidekick relationship (if thats not in our docs somewhere already). This is v1/v2 docker-compose stuff that users will expect to work unless documented otherwise. And yes the error message does not indicate that stack creation failed due to referencing a non-sidekick service in the`volumes_from` key, so that should be improved as well.

**Comment by carolynhu** [comment]
The error msg being enhanced to:
```
Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=InvalidReference, fieldName=From LaunchConfig primary-service to LaunchConfig helper-sidekick, baseType=error] from [http://xxxx/v2-beta/services] 
```

**Comment by soumyalj** [comment]
Reproduced the issue in v1.6.11-rc5.
Tested with rancher v1.6.11-rc6. Created a stack with the yaml below:
```
version: '2'
services:
  web-service:
    image: pierrezemb/gostatic
    volumes:
      - website:/srv/http
    command:
    - '-'
    - '--forceHTTP'
  helper-sidekick:
    image: ubuntu:latest
    labels:
       io.rancher.container.start_once: true
  primary-service:
    image: alpine:3.5
    volumes:
      - website:/srv/http
    volumes_from:
      - helper-sidekick
```
The error message is updated as below:
<img width="1250" alt="screen shot 2017-11-01 at 3 14 23 pm" src="https://user-images.githubusercontent.com/18536626/32300577-6b75285a-bf17-11e7-8820-7d62b6b84bf1.png">

**Comment by jambajaar** [comment]
@carolynhu @soumyalj @will-chan 

Could you change the error message to something more user-friendly such as the following?

volumes_from of the primary service <service_name> is referencing a container that is not labeled as a sidekick.  To fix this, please add the label io.rancher.sidekick: <sidekick_service name>

**Comment by carolynhu** [comment]
A correct docker-compose.yml should be:
```
version: '2'
services:
  web-service:
    image: pierrezemb/gostatic
    volumes:
      - website:/srv/http
    command:
    - '-'
    - '--forceHTTP'
  helper-sidekick:
    image: nginx:latest
    labels:
       io.rancher.container.start_once: true
  primary-service:
    image: alpine:3.5
    entrypoint: /somedir/entrypoint.sh
    labels:
        io.rancher.sidekicks: helper-sidekick
    volumes:
      - website:/srv/http
    volumes_from:
      - helper-sidekick
```
