### ISSUE TITLE
depends_on only working when links is in yaml file

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#9071]
Does Rancher/libcompose support depends_on parameter of docker-compose? 

If not, is there any way to strictly control service startup order in Rancher? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deniseschannon** [comment]
Yes, `depends_on` works in Rancher and Rancher Compose, but it is not exported in the UI. https://github.com/rancher/rancher/issues/6462 We plan to fix the export in Rancher 2.0. 

Note: When using `depends_on`, it will only wait for a service to be `active`. If you need to depend on a certain healthcheck, you would want to use this new label introduced as fo Rancher 1.6.1, CLI v0.6.1. It is not in rancher-compose. 

http://docs.rancher.com/rancher/v1.6/en/cattle/labels/ 

Scroll down to read about `io.rancher.service.wait_for_healthcheck: true`

**Comment by pengjiang80** [comment]
@deniseschannon I tested with depends_on parameter in Rancher and it doesn't work. The step is as below. Just used the following compose file to create a stack, web service started even db and redis are not in active status. The version I tried is v1.6.2 

version: '2'
services:
  web:
    image: busybox
    command: "sleep 1000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres

**Comment by maslennikov** [comment]
Hi @deniseschannon 

I found this topic as having a more appropriate title as #4337 where we exchanged on a similar issue.

I made some tests today, with the latest setup, working via CLI:
```
Component        Version
Rancher          v1.6.2
Cattle           v0.181.4
User Interface   v1.6.5
Rancher CLI      v0.6.1
Rancher Compose	 v0.12.5
```

My samlpe docker-compose.yml:
```yaml
version: '2'
services:
  postgres:
    image: postgres:9.6
    tty: true
    stdin_open: true
    # labels:
      # io.rancher.service.wait_for_healthcheck: 'true'

  migrator:
    image: ${MIGRATOR__IMAGE_VERSION}
    # depends_on:
      # - postgres
    links:
      - postgres
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    environment:
      NET_DB_URL: postgres://postgres@postgres
```
rancher-compose.yml:
```yaml
version: '2'
services:
  postgres:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
      initializing_timeout: 10000

  migrator:
    scale: 1
```

I performed tests removing all user stacks from rancher and then executing a single command `cli up --pull --upgrade -d` providing composefiles with different variations of commented-out blocks in docker-compose, and it seems that only `links` key has any effect on container startup sequence.

In general, when no `links` present, regardless of `depends_on`, cli output looks something like:
```
time="2017-06-16T10:15:18Z" level=info msg="Creating stack ppt-db"
time="2017-06-16T10:15:18Z" level=info msg="[postgres]: Creating "
time="2017-06-16T10:15:18Z" level=info msg="[migrator]: Creating "
time="2017-06-16T10:15:18Z" level=info msg="Creating service migrator"
time="2017-06-16T10:15:18Z" level=info msg="Creating service postgres"
time="2017-06-16T10:15:18Z" level=info msg="[migrator]: Created "
time="2017-06-16T10:15:18Z" level=info msg="[postgres]: Created "
time="2017-06-16T10:15:18Z" level=info msg="[migrator]: Starting "
time="2017-06-16T10:15:18Z" level=info msg="[postgres]: Starting "
time="2017-06-16T10:15:20Z" level=info msg="[migrator]: Started "
time="2017-06-16T10:15:31Z" level=info msg="[postgres]: Started "
```

With `links` key, it starts syncing:
```
time="2017-06-16T10:27:39Z" level=info msg="Creating stack ppt-db"
time="2017-06-16T10:27:39Z" level=info msg="[postgres]: Creating "
time="2017-06-16T10:27:39Z" level=info msg="Creating service postgres"
time="2017-06-16T10:27:40Z" level=info msg="[postgres]: Created "
time="2017-06-16T10:27:40Z" level=info msg="[migrator]: Creating "
time="2017-06-16T10:27:40Z" level=info msg="Creating service migrator"
time="2017-06-16T10:27:40Z" level=info msg="[migrator]: Created "
time="2017-06-16T10:27:40Z" level=info msg="[postgres]: Starting "
time="2017-06-16T10:27:43Z" level=info msg="[postgres]: Started "
time="2017-06-16T10:27:43Z" level=info msg="[migrator]: Starting "
time="2017-06-16T10:27:45Z" level=info msg="[migrator]: Started "
```

I haven't noticed any effect neither of label `io.rancher.service.wait_for_healthcheck`, nor of the `depends_on` key. I even tried setting the `wait_for_healthcheck` label on the migrator service.

Right now the `links` effect solves my use-case but in general the behavior seems a bit misleading.

**Comment by deniseschannon** [comment]
`depends_on` does not work in 1.6, only `links` works on startup ordering in v1.6.

We will introduce `depends_on` support in v2.0.

**Comment by deniseschannon** [comment]
@StrongMonkey I believe we now have support for `depends_on` now. Can you look into getting this working with compose files? And without requiring `links`?

**Comment by StrongMonkey** [comment]
@deniseschannon i briefly tested it and it is working for 2.0. (even without links)

**Comment by tfiduccia** [comment]
Version - 2.0 master 11/07
Depends_on is working but it's not exporting or showing up in the config
Imported yaml:
```
version: '2'
services:
  web:
    image: nginx
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```

Exported config:
```
version: "2"
services:
  db:
    image: postgres
    stop_signal: SIGTERM
  redis:
    image: redis
    stop_signal: SIGTERM
  web:
    image: nginx
    stop_signal: SIGTERM
```

**Comment by StrongMonkey** [comment]
I am not sure where this ends up going to in 2.0, but it should be fixed in this [pr](https://github.com/rancher/rancher-compose-executor/pull/130) :)

**Comment by yasker** [comment]
@deniseschannon Can we get this for 1.6? One potential customer is using this.

**Comment by flaccid** [comment]
@deniseschannon regarding:

> http://docs.rancher.com/rancher/v1.6/en/cattle/labels/
> Scroll down to read about `io.rancher.service.wait_for_healthcheck: true`

I can't seem to find that label on the docs page there. Is this still available and supported?

**Comment by deniseschannon** [comment]
@flaccid no, that label was removed as it had issues and isn't officially supported. 

`depends_on` only works if you have `links`

**Comment by kingsd041** [comment]
@pengjiang80 
1. If you set depends_on only in docker-compose.yaml, Rancher does not give priority to starting redis and db.
```
version: '2'
services:
  web:
    image: busybox
    command: "sleep 1000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```
2. If you set links and depend_ons in docker-compose.yaml, Rancher will give priority to starting redis and db. But when using a wrong image(Ex: postgres:test1), web service will still start.
```
version: '2'
services:
  web:
    image: busybox
    links:
    - db:db
    - redis:redis
    command:
    - sleep
    - '1000'
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```

3. If you set only links, the result is the same as in step 2
```
version: '2'
services:
  web:
    image: busybox
    links:
    - db:db
    - redis:redis
    command:
    - sleep
    - '1000'
  redis:
    image: redis
  db:
    image: postgres
```
