### ISSUE TITLE
Stack export config has driver: 'null' after deleting a service with volume having "driver:null" and creating another service with volume

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9080]
**Rancher versions:**
rancher/server:Master from v1.6 branch

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a service ser1 with a volume and specify driver = NULL
2. Delete the service ser1 
3. Create another service ser2 with volume and no driver specified in the SAME STACK

**Results:**
The export config has driver : 'null'
```
version: '2'
volumes:
  testvol:
    driver: 'null'
services:
  ser1:
    image: ubuntu:14.04.3
    stdin_open: true
    volumes:
    - myvol:/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
