### ISSUE TITLE
Removing service defined in external_links change configuration

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#9085]
*I have simple service (for simplicity UI) which use as ext. link another service, when I remove this ext service (for example during new version deployment), rancher modified docker-compose cfg of UI and remove ext service. So it never start works when DB is up again*

# Expected behaviour
- removing external service should not modify another stack configuration.

# Sample docker-compose

```
version: '2'
services:
  phpipam:
    image: sample.registry.com:5000/ui:1
    environment:
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: xxxxx
    stdin_open: true
    external_links:
    - mariadb/haproxy:mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
      loadbalancer.https: 'true'
```

After removing mariadb/haproxy:mysql (upgrade) resulted docker-compose for UI is:

```
version: '2'
services:
  phpipam:
    image: sample.registry.com:5000/ui:1
    environment:
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: xxxxx
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      loadbalancer.https: 'true'
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|
