### ISSUE TITLE
LB created from catalog has http mode instead of tcp

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#9124]
Apologies if there is an existing issue for this, I couldn't quite find one exact.

**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Steps to Reproduce:**
Launch from catalog https://github.com/flaccid/rancher-catalog/tree/master/templates/mysql or postgres from community catalog.

**Results:**
All is configured correctly except the mode of the load balancer/rule. `http` instead of `tcp`. A simple switch back via edit of the LB remedies the issue.

Preview of the services in `rancher-compose.yml` before launch from catalog:

```
version: '2'
services:
  mysql-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: mysql
        source_port: ${lb_port}
        target_port: 3306
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql-data:
    scale: 1
    start_on_create: true
```

After launch:

```
version: '2'
services:
  mysql-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: mysql
        source_port: 3306
        target_port: 3306
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  mysql-data:
    scale: 1
    start_on_create: true
```
