### ISSUE TITLE
Rancher Compose & CLI doesn't update external-service external_ips or hostname

### ISSUE THREAD

**Issue by azuretek** [rancher/rancher#9147]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.0
network-services: 0.2.1
scheduler: 0.6.0

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 15
 Running: 13
 Paused: 0
 Stopped: 2
Images: 19
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.15-rancher
Operating System: RancherOS v0.9.0
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: rancher-abi133-0
ID: WOK5:R2GP:S33M:ZY3T:NIZT:I44Z:CW7M:VN6P:XUVY:W73C:IGWP:W3FT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v0.9.0
ID=rancheros
ID_LIKE=
VERSION_ID=v0.9.0
PRETTY_NAME="RancherOS v0.9.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.9.15-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
**docker-compose.yml**
```
version: '2'
services:
  test-external:
    image: rancher/external-service
  test-external2:
    image: rancher/external-service
```
**rancher-compose.yml**
```
version: '2'
services:
  test-external:
    hostname: google.com
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  test-external2:
    external_ips:
    - 1.1.1.1
    - 2.2.2.2
    start_on_create: true
```
**Command used**
```
rancher --debug \
--url http://<rancher_host> \
--access-key <access_key> \
--secret-key <secret_key> \
-f ./docker-compose.yml \
--rancher-file ./rancher-compose.yml \
up -d \
--force-upgrade \
--stack mystack
```

**Results:**

When I use these compose files with rancher cli it creates the stack just fine, when I try to update the external_ips or hostname for these external services using rancher cli (or rancher-compose) nothing happens and there is no change.
