### ISSUE TITLE
Scope-Stack volumes not working with 1.6.2?

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#9158]
Rancher versions:
rancher/server:
1.6.2
rancher/agent:
latest

Infrastructure Stack versions:
healthcheck: latest (upgraded max)
ipsec: latest (upgraded max)
network-services: latest (upgraded max)
scheduler:latest (upgraded max)

Docker version: (docker version,docker info preferred)
Server Version: 17.03.1-ce

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
rancheros 1.0.1-LTS

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Baremetal under KVM (proxmox)

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
no HA, internal DB

Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

Steps to Reproduce:
no idea

When creating a  new stack from catalog with a volume defintion like this

```
version: "2"

services:
  drupal:
    image: someimage
    volumes:
      - volumefiles:/mnt/data
  db:
    image: percona:5.5
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=someuser
      - MYSQL_USER=someuser
      - MYSQL_PASSWORD=somepw
    volumes:
      - volumedb:/var/lib/mysql
  httpd:
    image: nginx
    volumes_from:
     - drupal
    labels:
      io.rancher.sidekicks: drupal
```

the volumes are created without any stack scope, they are just named "volumedb"
