### ISSUE TITLE
Rancher-ebs external volume losing data when moving container from one host to another 

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#9201]
**Rancher versions:**
rancher/server: 1.6.2
CATTLE 0.181.4

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec:
network-services: 0.7.1
scheduler: 0.8.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 and rancher OS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS ec2
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA external db
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default Cattle
**Steps to Reproduce:**
Create 2 hosts on aws

Create a Rancher-ebs volume in aws, size=1, volumeType=gp2
Add a container (mongo for example) mount the volume to /data/db
when the container starts it correctly uses the volume to store the database.
Schedule the container to run on the other host
The volume seems to be linked but it's empty, mongo will re-init the database.

```
volumes:
  mongo:
    external: true
    driver_opts:
      size: '100'
      volumeType: gp2
    driver: rancher-ebs
services:
  mongo-db:
    image: mongo:latest
    volumes:
    - mongo:/var/db/
    labels:
      io.rancher.scheduler.affinity:host_label: type=database
      io.rancher.service.selector.container: mongo-db
      io.rancher.container.pull_image: always
```

**Results:**
Data are lost

I though mounting volumes to store data was the safe way to persist data, and easily reschedule containers across hosts
