### ISSUE TITLE
Issue with nesting of the load balancers

### ISSUE THREAD

**Issue by jakubsacha** [rancher/rancher#9216]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec:
network-services:
scheduler:
kubernetes (if applicable): -

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-62-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vps (ovh)
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Main load balancer:

```
version: '2'

services:
  lb:
    image: "rancher/lb-service-haproxy:v0.7.5"
    ports:
      - "80:80"
      - "443:443"

```
```
version: '2'
services:
  lb:
    scale: 1
    lb_config:
      port_rules:
      ## xxx.pl
      - source_port: 80
        target_port: 80
        selector: xxx=true
        hostname: "xxx.pl"
      - source_port: 80
        target_port: 80
        selector: xxx=true
        hostname: "www.xxx.pl"
      ## stage zzz.im
      - source_port: 80
        target_port: 80
        selector: zzz_lb=stage
        hostname: "stage.zzz.im"
      - source_port: 80
        target_port: 80
        selector: zzz_lb=stage
        hostname: "*.stage.zzz.im"
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```

zzz:
```
version: '2'

services:
  app1:
    image: "registry.gitlab.com/xxx/pg/app1:latest"

  app2:
    image: "bkimminich/juice-shop:latest"

  lb1:
    image: "rancher/lb-service-haproxy:v0.7.5"
```

```
version: '2'
services:
  app1:
    scale: 2
  app2:
    scale: 2
  lb1:
    labels:
      jagim_lb: stage
    scale: 2
    lb_config:
      port_rules:
      - source_port: 80
        target_port: 3000
        service: app2
        path: /shop/
      - source_port: 80
        target_port: 80
        service: app1
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```

**Results:**
Main load balancer contains entries from the internal one. part /shop/ should not be there. haproxy.cnf from the main lb:

```
listen default
bind *:42

frontend 80
bind *:80
mode http
acl 80_stage_zzz_im_shop__host hdr(host) -i stage.zzz.im
acl 80_stage_zzz_im_shop__host hdr(host) -i stage.zzz.im:80
acl 80_stage_zzz_im_shop__path path_beg -i /shop/
use_backend 80_stage_zzz_im_shop_ if 80_stage_zzz_im_shop__host 80_stage_zzz_im_shop__path
acl 80_xxx_pl__host hdr(host) -i xxx.pl
acl 80_xxx_pl__host hdr(host) -i xxx.pl:80
use_backend 80_xxx_pl_ if 80_xxx_pl__host
acl 80_www_xxx_pl__host hdr(host) -i www.xxx.pl
acl 80_www_xxx_pl__host hdr(host) -i www.xxx.pl:80
use_backend 80_www_xxx_pl_ if 80_www_xxx_pl__host
acl 80_stage_zzz_im__host hdr(host) -i stage.zzz.im
acl 80_stage_zzz_im__host hdr(host) -i stage.zzz.im:80
use_backend 80_stage_zzz_im_ if 80_stage_zzz_im__host
```
