### ISSUE TITLE
Don't get nginx access logs

### ISSUE THREAD

**Issue by mc388** [rancher/rancher#9241]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: Up to date
ipsec: Up to date
network-services: Up to date
scheduler: Up to date

**Docker version: (`docker version`,`docker info` preferred)**

Docker version 17.05.0-ce, build 89658be

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

**Type/provider of hosts: (Bare-metal)**

**Setup details: (single node rancher, internal DB)**

**Environment Template: (Cattle)**

**Steps to Reproduce:**

- start nginx container behind rancher lb
- visit website
- check logs from rancher ui

**Results:**

- i just see the nginx error logs but not the access logs

**nginx.conf**
```
daemon off;

user www-data;
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  log_format          main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

  access_log          stdout main;
  error_log           stderr warn;

  sendfile            off;
  keepalive_timeout   65;

  server {
    listen       80;

    client_max_body_size	100M;

    root /var/www/html/web;
    index index.html index.php;

    charset utf-8;

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|pdf|txt|tar|wav|bmp|rtf|js|flv|swf)$ {
      root /var/www/html/web;
    }

    location ~ [^/]\.php(/|$) {
      fastcgi_split_path_info ^(.+?\.php)(/.*)$;
      if (!-f $document_root$fastcgi_script_name) {
          return 404;
      }

      fastcgi_pass php:9000;
      fastcgi_index index.php;
      include conf.d/fastcgi_params;
      fastcgi_read_timeout 900;
    }

    gzip                on;
    gzip_min_length     1000;
    gzip_proxied        any;
    gzip_types          text/plain
                        application/xml
                        text/css
                        text/js
                        application/javascript
                        application/x-javascript;
  }
}

```

**docker-compose**
```
version: '2'

services:
  web:
    image: myNginxImage:latest
    volumes_from:
      - php
    command: nginx -c /etc/nginx/nginx.conf
    logging:
      options:
        max-size: "25m"
        max-file: "4"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: php
...
```
