### ISSUE TITLE
Rancher-nfs fails with Internal Server Error is the volume is named 'int'

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#9242]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: 0.1.0
network-services: v0.2.1
scheduler: v0.6.0
nfs: 0.3.0

**Docker version: (`docker version`,`docker info` preferred)**

1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Ubuntu 16.04

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

```yaml
version: '2'
volumes:
  prod:
    external: true
    driver: rancher-nfs
  dev:
    external: true
    driver: rancher-nfs
  int:
    external: true
    driver: rancher-nfs
services:
  prod:
    image: tutum/hello-world
    volumes:
    - prod:/mnt/prod:ro
  dev:
    image: tutum/hello-world
    volumes:
    - dev:/mnt/dev:ro
  int:
    image: tutum/hello-world
    volumes:
    - int:/mnt/int:ro
```

**Results:**

Services `dev` and `prod` works, but `int` fails with:

    Expected state running but got error: /VolumeDriver.Attach 'int' (driver 'rancher-nfs') returned status 500: 500 Internal Server Error

FYI: directories `dev`, `int` and `prod` exists on the NFS server.

In the logs of the nfs-driver container I can see:

```
05/07/2017 15:25:02time="2017-07-05T13:25:02Z" level=info msg=attach.request name=int
05/07/2017 15:25:02time="2017-07-05T13:25:02Z" level=error msg=attach.response error="No such volume"
```
