### ISSUE TITLE
rancher compose v0.12.5 could not find expected ':'

### ISSUE THREAD

**Issue by ppiccolo** [rancher/rancher#9243]
**Rancher versions:**
rancher/server: v1.6.2

Unable to use **templating** with `rancher-compose v0.12.5`, raise an error `could not find expected ':'`

Step to reproduce:

**rancher-compose.yml**
```
.catalog:
  name: "test"
  version: "1"
  description: "test"
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "SOME_VARIABLE"
      label: "Label :"
      description: |
        description
      default: false
      required: true
      type: enum
      options:
        - false
        - true
```

**docker-compose.yml**
```
version: "2"
services:
  test:
    image: rancher/external-service
  {{- if eq .Values.SOME_VARIABLE "true" }}
  test-if:
    image: rancher/external-service
  {{- end }}
```
running the following command :

`rancher-compose -p test --url <rancher_url> --access-key <key>  --secret-key <secret> create`

return this :

```
ERRO[0000] Could not parse config for project test : yaml: line 7: could not find expected ':' 
FATA[0000] Failed to read project: yaml: line 7: could not find expected ':' 
```
