### ISSUE TITLE
LB updated with unhealthy instance on service upgrade

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#9287]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.0
network-services: v0.2.2
scheduler: v0.6.1

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create this stack containing a web service and a LB:

docker-compose:
```YAML
version: '2'
services:
  hello-world-svc:
    image: janeczku/hello-world:health-check-8080
    stdin_open: true
    tty: true
  hello-world-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
```

rancher-compose:
```YAML
version: '2'
services:
  hello-world-svc:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 15000
      interval: 2000
      strategy: none
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 15000
  hello-world-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: hello-world-svc
        source_port: 8080
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
```

2. Upgrade the hello-world-svc by checking the option "Start before stopping" and replacing with the image that does not expose health check on port 8080 (simulating unhealthy instance): `janeczku/hello-world:health-check-off`

3. As soon as the new instance state changes to initializing, do curl check against the load balancer public port 8080
4. Check /etc/haproxy/haproxy.cfg in the load balancer container

**Results:**
- curl command returns error 502 - no backends available
- previous instance is still running and healthy but removed from haproxy.cfg
- new instance is still initializing (not healthy) but added to haproxy.cfg

**Exepected Results:**
- curl command should succeed since there is still a healthy running instance of the service
- the previous instance should not be removed from haproxy.cfg until the upgraded instance becomes healthy.

https://github.com/rancher/rancher/issues/5826 implemented waiting for upgraded instance to become healthy before stopping the previous container. The same should be true with regards to removing the previous container from the load balancer.
