### ISSUE TITLE
Application creates stack-scoped local volume

### ISSUE THREAD

**Issue by sorenroug** [rancher/rancher#9293]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent:

We recreated a container last Friday. Afterwards, the local volume was ignored and a new empty stack-scoped _local_ volume was created. The original /var/lib/docker/volumes/webforms-eionet-mysql volume is still there.
```
        "Mounts": [
            {
                "Name": "webforms-eionet_webforms-eionet-mysql_db55f",
                "Source": "/var/lib/docker/volumes/webforms-eionet_webforms-eionet-mysql_db55f/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "rancher-cni",
                "Source": "/var/lib/docker/volumes/rancher-cni/_data",
                "Destination": "/.r",
                "Driver": "local",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```
The docker-compose file looks like this:
```
version: '2'

volumes:
  webforms-eionet-config:
    driver: rancher-nfs
    external: true

  webforms-eionet-mysql:
    driver: local

services:

  webqproddb:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXX
      MYSQL_DATABASE: XXXXXXX
      MYSQL_USER: XXXXXXX
      MYSQL_PASSWORD: XXXXXXX
    command: mysqld --max_allowed_packet=30M
    mem_reservation: 419430400 # = 400 MB
    volumes:
    - webforms-eionet-mysql:/var/lib/mysql
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=eionet-cph-06
```

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.10.3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**
