### ISSUE TITLE
[per-host-subnet]Get richer context data in scheduler when scheduling retain_ip containers

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9317]
The following is the current scheduler to get the context data:
```
## Received event: Name: scheduler.prioritize, Event Id: 7d2ee590-d6a4-4b6c-b3f7-97a24397dd25, ResourceId : 1i274
## Filter context:
Fields: {
	ServiceIndex: 3 ImageUUID: docker: ubuntu: 14.04 .3 DataVolumeMounts: {}
	AllocatedIPAddress: < nil > PublishAllPorts: false StartOnCreate: true 
        Labels: map[
		io.rancher.project.name: bbb 
		io.rancher.project_service.name: bbb / bb 
		io.rancher.stack.name: bbb
		io.rancher.service.deployment.unit: 54d7bdaa-078d-4065-bbcd-ee3b21d6f351 
		io.rancher.stack_service.name: bbb / bb 
		io.rancher.service.launch.config: 
		io.rancher.service.primary.launch.config] 
        NetworkMode: managed DNS: [169.254.169.250] 
        DNSSearch: [bbb.rancher.internal bb.bbb.rancher.internal rancher.internal] 
        StdinOpen: true Vcpu: 1 Ports: [] ReadOnly: false 
        DataVolumesFromLaunchConfigs: [] 
        Secrets: [] DataVolumesFrom: [] 
        CapAdd: [] Tty: true CapDrop: [] DataVolumes: [] Privileged: false 
        LogConfig: {
		Driver: Config: {}
	}
	Devices: [] NetworkIds: [15] TransitioningMessage: Scheduling TransitioningProgress: 32
}
```

But when we set the retain_ip for the service, there is no richer presentation in context data.
Sometimes we need to do some special logic for retain_ip.

This [issue-9153](https://github.com/rancher/rancher/issues/9153) should need this feature.
Then we can use this retain_ip information to calculate the hosts. We do not just need the retain_ip boolean value, and also need to include allocated ip address.
So a rough algo in scheduler:
```
subnet, ok := lpool.(*LabelPool).Labels[vpcSubnetLabel]
...
_, ipnet, err := net.ParseCIDR(subnet)
...
for _, con := range context {
        if !con.retainIp {
               ...
               continue
        }
	retainIPStr := con.AllocatedIPAddress
	if retainIPStr == "" {
		...
		continue
	} 
	if ipnet.Contains(net.ParseIP(retainIPStr)) {
		...
		// choose the host
	}
}
```
In addition, if we do not use rancher-ipam, the `AllocatedIPAddress` value is always null.
