### ISSUE TITLE
Replacing Ingress doesn't update haproxy configuration in k8s 1.7

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9349]
**Rancher versions:**
rancher/server: v1.6.3
kubernetes (if applicable): rancher/k8s:v1.7.0-rancher3
rancher/lb-service-haproxy: v0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12, 1.10
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04, 14.04, RHEL
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Deploy the following RCs:
```
apiVersion: v1
kind: Service
metadata:
 name: k8test21-one
 labels:
   k8s-app: k8test21-one-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test21-one-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc21-one
spec:
 replicas: 2
 selector:
   k8s-app: k8test21-one-service
 template:
   metadata:
     labels:
       k8s-app: k8test21-one-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81
```
```
apiVersion: v1
kind: Service
metadata:
 name: k8test21-two
 labels:
   k8s-app: k8test21-two-service
spec:
 ports:
 - port: 81
   targetPort: 81
   protocol: TCP
   name: http
 selector:
   k8s-app: k8test21-two-service
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: k8testrc21-two
spec:
 replicas: 2
 selector:
   k8s-app: k8test21-two-service
 template:
   metadata:
     labels:
       k8s-app: k8test21-two-service
   spec:
     terminationGracePeriodSeconds: 60
     containers:
     - name: testcontainer
       image: sangeetha/testnewhostrouting
       ports:
       - containerPort: 81
```
Then deploy ingress resource to point to the the `k8stest21-one-service`
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress21
 annotations:
   http.port: "105"
spec:
  backend:
    serviceName: k8test21-one
    servicePort: 81
```
Then try to access the ingress on port 105 with path service3.html
```
➜  curl http://x.x.x.x:105/service3.html
k8testrc21-one-psll1
➜ curl http://x.x.x.x:105/service3.html
k8testrc21-one-6p2dh
```
Replace the ingress with new ingress that points to the second service
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress21
 annotations:
   http.port: "105"
spec:
  backend:
    serviceName: k8test21-two
    servicePort: 81
```
- now try to access the the service again:

**Results:**
```
➜  curl http://x.x.x.x:105/service3.html
k8testrc21-one-psll1
➜ curl http://x.x.x.x:105/service3.html
k8testrc21-one-6p2dh
```

The ingress still points to the old service, and the haproxy configuration still points to the ips of the old pods.

**Note**: After deleting the ingress lb, the new lb created is pointing to the correct service.

**Comment by galal-hussein** [comment]
@alena1108 Other uses cases related to updating the ingress also has the same behavior:

1- scaling the pods in the backend.
2- Upgrading the ingress to change the host header.

**Comment by alena1108** [comment]
@galal-hussein can we put steps to reproduce for each use case, to this bug? As the root case might be different depending on the steps

**Comment by galal-hussein** [comment]
use case 1:

- Add a new rc and service:
```
apiVersion: v1
kind: Service
metadata:
  name: k8test14
  labels:
    k8s-app: k8test14-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: k8test14-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8testrc14
spec:
  replicas: 3
  selector:
    k8s-app: k8test14-service
  template:
    metadata:
      labels:
        k8s-app: k8test14-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: testcontainer
        image: sangeetha/testnewhostrouting
        ports:
        - containerPort: 80
        tty: true
```
- deploy a new ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress14
 annotations:
   http.port: "97"
spec:
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /name.html
       backend:
         serviceName: k8test14
         servicePort: 80
```
- check the ingress endpoint:
```
curl http://x.x.x.x:97/name.html
pod-1
curl http://x.x.x.x:97/name.html
pod-2
curl http://x.x.x.x:97/name.html
pod-3
```
- replace the rc with a new one (only one replica)
`kubectl replace -f new-rc.yaml`
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: k8testrc14
spec:
  replicas: 1
  selector:
    k8s-app: k8test14-service
  template:
    metadata:
      labels:
        k8s-app: k8test14-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: testcontainer
        image: sangeetha/testnewhostrouting
        ports:
        - containerPort: 80
        tty: true
```
- check the ingress again, it should report one pod:
```
curl http://x.x.x.x:97/name.html
pod-1
curl http://x.x.x.x:97/name.html
pod-2
curl http://x.x.x.x:97/name.html
pod-3
```
