### ISSUE TITLE
Rancher panic after deploy stack from catalog with secret linked

### ISSUE THREAD

**Issue by ivan-exness** [rancher/rancher#9358]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.1
network-services: 0.2.2
scheduler: 0.6.2
secrets: 0.0.2

**Docker version: (`docker version`,`docker info` preferred)**
```
exness@dev-v2-01:~$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```
exness@dev-v2-01:~$ docker info
Containers: 17
 Running: 16
 Paused: 0
 Stopped: 1
Images: 36
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 203
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: dev-v2-01
ID: GUJM:CQWD:X24B:KMNR:BERG:QHMS:PAE3:ZZXR:BAVC:YXZW:7W4N:5JHQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
exness@server:~/projects/rancher$ uname -r
4.4.0-79-generic
exness@server:~/projects/rancher$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
* add secret
* setup rancher sercret-driver
* create item in catalog with question type secret
**rancher-compose.yml**
```
version: '2'
catalog:
  name: WebSite Stack
  version: master
  description: Personal Info thrift service
  questions:
    - variable: CONFIG_TOKEN
      label: "GitLab API Token"
      description: |
        GitLab API Token to get boot up configs from git
      type: secret
      required: true
    - variable: CONFIG_ENV
      label: "Config environments"
      description: |
        Choose what configs to use `production`, `testenv`, `qa-sever`
      type: string
      default: 'qa-server'
      required: true
    - variable: WEB_CONCURRENCY
      label: "Gunicorn workers count (33 if empty)"
      description: |
        Gunicorn workers count (if empty = 33)
      type: int
      default: 3
      required: false
    - variable: SERVER_NAME
      label: "Server name to use in *.test.env"
      description: |
        Server name to use in *.test.env. E.G. `dev-v2-01`
      type: string
      required: true
    - variable: SENTRY_PUBLIC_DSN
      label: "Sentry public DSN"
      description: |
        Public DSN for Sentry error collector
      type: string
      required: true
    - variable: SENTRY_PRIVATE_DSN
      label: "Sentry private DSN"
      description: |
        Private DSN for Sentry error collector
      type: string
      required: true
    - variable: MIGRATE_DB
      label: "Migrate Database on start"
      description: |
        Run alembic migrations before service start
      type: boolean
      required: false
  services:
    public-locale:
      scale: 1
      start_on_create: true
    private-static:
      scale: 1
      start_on_create: true
    public-static:
      scale: 1
      start_on_create: true
    private-frontendsource:
      scale: 1
      start_on_create: true
    private-locale:
      scale: 1
      start_on_create: true
    private-templates:
      scale: 1
      start_on_create: true
    public-templates:
      scale: 1
      start_on_create: true
    public-frontendsource:
      scale: 1
      start_on_create: true
    public-backend:
      scale: 1
      start_on_create: true
    public-nginx:
      scale: 1
      start_on_create: true
    private-pages:
      scale: 1
      start_on_create: true
    private-backend:
      scale: 1
      start_on_create: true
    private-nginx:
      scale: 1
      start_on_create: true
```
**docker-compose.yml**
```
version: '2'
services:
  public-locale:
    image: registry.exness.io/public-site/locale:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  private-static:
    image: registry.exness.io/site/static_member:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  public-static:
    image: registry.exness.io/public-site/static:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  private-frontendsource:
    image: registry.exness.io/site/frontendsource:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  private-locale:
    image: registry.exness.io/site/locale:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  private-templates:
    image: registry.exness.io/site/templates:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  public-templates:
    image: registry.exness.io/public-site/templates:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  public-frontendsource:
    image: registry.exness.io/site/frontendsource:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  public-backend:
    image: registry.exness.io/public-site/backend:master
    environment:
      CONFIG_TOKEN: ${CONFIG_TOKEN}
      ENV: ${CONFIG_ENV}
      MIGRATE_DB: ${MIGRATE_DB}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      SERVER_NAME: ${SERVER_NAME}
      SENTRY_PUBLIC_DSN: ${SENTRY_PUBLIC_DSN}
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - public-locale
    - public-static
    - public-templates
    - public-frontendsource
    labels:
      io.rancher.container.pull_image: always
  public-nginx:
    image: registry.exness.io/dockerhub/nginx:exness-custom
    environment:
      UPSTREAM: public-backend:8000
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - public-static
    - public-frontendsource
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: public-backend,public-locale,public-static,public-templates,public-frontendsource
  private-pages:
    image: registry.exness.io/site/pages:master
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  private-backend:
    image: registry.exness.io/site/py:master
    environment:
      CONFIG_TOKEN: ${CONFIG_TOKEN}
      ENV: ${CONFIG_ENV}
      MIGRATE_DB: ${MIGRATE_DB}
      SERVER_NAME: ${SERVER_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      SENTRY_PRIVATE_DSN: ${SENTRY_PRIVATE_DSN}
    stdin_open: true
    secrets:
    - gid: '0'
      mode: '444'
      name: config_token
      secretId: ${CONFIG_TOKEN}
      uid: '1007'
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    - private-locale
    - private-templates
    - private-pages
    labels:
      io.rancher.container.pull_image: always
  private-nginx:
    image: registry.exness.io/dockerhub/nginx:exness-custom
    environment:
      UPSTREAM: private-backend:8000
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: private-pages,private-backend,private-static,private-frontendsource,private-locale,private-templates
```

* deploy item from catalog and choose secret from dropdown list

**Results:**
```
time="2017-07-17T09:27:22Z" level=info msg="Stack Create Event Received" eventId=3cebbd77-0eeb-42e5-a034-17d0bef3283e resourceId=1st229
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 75 [running]:
github.com/rancher/rancher-compose-executor/config.parseValidTypesFromSchema(0xc4201285d0, 0xc42000a3e0, 0x20, 0x0, 0xc42000a3e0, 0x20)
	/go/src/github.com/rancher/rancher-compose-executor/config/schema_helpers.go:72 +0x73e
github.com/rancher/rancher-compose-executor/config.oneOfMessage(0xc4201e7ef0, 0xc4201285d0, 0xd3f8e0, 0xc4201da240, 0xd3f360, 0xc4201da200, 0x0, 0x4f28bf)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:162 +0x5d6
github.com/rancher/rancher-compose-executor/config.generateErrorMessages(0xc4201e7ef0, 0xc4201285d0, 0xc42016c3e0, 0xc4201bfb60, 0xc42016c3e0)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:258 +0x1069
github.com/rancher/rancher-compose-executor/config.validateV2(0xc4202aac60, 0x0, 0xc4201285a0)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:222 +0x13f
github.com/rancher/rancher-compose-executor/config.MergeServicesV2(0xc420147940, 0xd36420, 0xc42000c0e8, 0xd363e0, 0xd8d988, 0x0, 0x0, 0xc4202aac60, 0xc4205a3000, 0xe52, ...)
	/go/src/github.com/rancher/rancher-compose-executor/config/merge_v2.go:13 +0x43
github.com/rancher/rancher-compose-executor/config.Merge(0xc420147940, 0xd36420, 0xc42000c0e8, 0xd363e0, 0xd8d988, 0xc4202697a0, 0x6, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/rancher-compose-executor/config/merge.go:167 +0x1173
github.com/rancher/rancher-compose-executor/project.(*Project).load(0xc42059c000, 0x0, 0x0, 0xc420477000, 0xe52, 0x1000, 0xc42059bbc0, 0xc4201d5ad0)
	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:165 +0xe3
github.com/rancher/rancher-compose-executor/project.(*Project).Parse(0xc42059c000, 0xc42059c000, 0x30)
	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:97 +0x15b
github.com/rancher/rancher-compose-executor/rancher.NewProject(0xc4204b0d00, 0xc4201d58c0, 0xc42047fa38, 0x2)
	/go/src/github.com/rancher/rancher-compose-executor/rancher/project.go:35 +0x26d
github.com/rancher/rancher-compose-executor/executor/handlers.constructProject(0xc42053f700, 0xc4200a0000, 0xc420223f40, 0x1d, 0xc420016012, 0x14, 0xc420018092, 0x28, 0xc4204ae420, 0xc4200f8180, ...)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/project.go:91 +0x4d2
github.com/rancher/rancher-compose-executor/executor/handlers.createStack(0xc42053f700, 0xc4204a1c70, 0xc42032e000, 0x1, 0xc42035ad50)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:46 +0x166
github.com/rancher/rancher-compose-executor/executor/handlers.CreateStack(0xc4204a1c70, 0xc42032e000, 0xc4204a0101, 0xc42004cde8)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:22 +0x269
github.com/rancher/rancher-compose-executor/executor/handlers.WithTimeout.func1(0xc4204a1c70, 0xc42032e000, 0xc42035ac00, 0x2d)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/common.go:54 +0x46
github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.doWork(0xc4204a1c70, 0xc420355ec0, 0xc42032e000, 0xd33560, 0xc4202f1a90)
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x28d
github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc420531f60, 0xb, 0xc4204a1c70, 0xc420355ec0, 0xc42032e000)
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
created by github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x18d
time="2017-07-17T09:27:24Z" level=info msg="Starting rancher-compose-executor" version=v0.14.10
time="2017-07-17T09:27:25Z" level=info msg="Initializing event router" workerCount=250
time="2017-07-17T09:27:25Z" level=info msg="Connection established"
time="2017-07-17T09:27:25Z" level=info msg="Starting websocket pings"
```

**Comment by ivan-exness** [comment]
Possible duplicate: https://github.com/rancher/rancher/issues/8195

**Comment by ivan-exness** [comment]
I have fix my catalog yml files.
Now it don't fail. But secrets node are not present in stack after deploy.

**docker-compose from preview section before deploy**
```
  private-backend:
    image: registry.exness.io/site/py:master
    environment:
      CONFIG_TOKEN: ${CONFIG_TOKEN}
      ENV: ${CONFIG_ENV}
      MIGRATE_DB: ${MIGRATE_DB}
      SERVER_NAME: ${SERVER_NAME}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      SENTRY_PRIVATE_DSN: ${SENTRY_PRIVATE_DSN}
    stdin_open: true
    secrets:
    - config-token
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    - private-locale
    - private-templates
    - private-pages
    labels:
      io.rancher.container.pull_image: always
  private-nginx:
    image: registry.exness.io/dockerhub/nginx:exness-custom
    environment:
      UPSTREAM: private-backend:8000
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: private-pages,private-backend,private-static,private-frontendsource,private-locale,private-templates
secrets:
  config-token:
    external: true
```
**docker-compose file after deploy**
```
  private-backend:
    image: registry.exness.io/site/py:master
    environment:
      CONFIG_TOKEN: config-token
      ENV: qa-server
      MIGRATE_DB: 'false'
      SENTRY_PRIVATE_DSN: https://4a9ce600aebc48809144c9d43c850bb4:007a1a117cde48a4bddf3eab3e46c514@sentry.test.env/11
      SERVER_NAME: dev-v2-01
      WEB_CONCURRENCY: '3'
    stdin_open: true
    volumes:
    - /glusterfs:/glusterfs
    tty: true
    volumes_from:
    - private-static
    - private-frontendsource
    - private-locale
    - private-templates
    - private-pages
    labels:
      io.rancher.container.pull_image: always
```
