### ISSUE TITLE
Compose: Non-unique services are silently stripped instead of raising validation error

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#9424]
**Rancher versions:**
rancher/server: 1.6.2
Cattle | v0.181.4
User Interface | v1.6.5
Rancher CLI | v0.6.1
Rancher Compose | v0.12.5

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create a new stack in the UI from the following docker-compose.yml:

```yaml
version: '2'
services:
  foo:
    image: ubuntu
    command: cat
  foo:
    image: alpine
    command: cat
```

**Expected:**

Validation fails and error is thrown (Non-unique service name)

**Actual:***

Stack is created with just the second service. No error.
