### ISSUE TITLE
rancher cli: handle compose file type mismatch gracefully 

### ISSUE THREAD

**Issue by amy** [rancher/rancher#9483]
Investigate whether type mismatch in other fields causes a go panic.
Make sure type mismatch doesn't cause panics and either converts the type or returns a useful error.

See issue: https://github.com/rancher/rancher/issues/9094

**Comment by amy** [comment]
Update: Issue occurs because `parseValidTypesFromSchema` in `rancher-compose-executor/config/schema_helpers.go` does not handle nested fields.

Upcoming fix will prevent panics from happening, and return appropriate type mismatch errors for nested fields.

**Comment by cjellick** [comment]
Initial review done; asked for tests

**Comment by amy** [comment]
available on `v1.6.8-rc5`

**Comment by amy** [comment]
For testing, the following `docker-compose.yml` files can be used. Flip the fields from string to int and vice versa to make sure the type mismatch won't cause a panic.

```
version: '2'
services:
  test:
    image: nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: '20000'
        hard: 40000
``` 
```
version: '2'
services:
  test:
    image: nginx
    secrets:
    - gid: '1'
      mode: '111'
      name: test_config.cfg
      secretId: 1
      uid: '1'
```

**Comment by soumyalj** [comment]
Tested with rancher v1.6.8-rc6 using CLI v0.6.4-rc3. Tested with the above examples. With a type mismatch there is no panic and the command exits gracefully with a relevant message.
Example below:
testpanic1.yml
```
version: '2'
services:
  test:
    image: nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: '20000'
        hard: 40000
```
```
rancher-v0.6.4-rc3 soumya$ ./rancher up -d -f testpanic1.yml -s mypanicclitest1
INFO[0000] Creating stack mypanicclitest1               
ERRO[0000] Could not parse config for project mypanicclitest1 : Service 'test' configuration key 'nofile' contains an invalid type, it should be an integer or object
Service 'nofile' configuration key nofile value Property "nofile" does not match pattern "^[a-z]+$" 
FATA[0000] Failed to read project: Service 'test' configuration key 'nofile' contains an invalid type, it should be an integer or object
Service 'nofile' configuration key nofile value Property "nofile" does not match pattern "^[a-z]+$" 
```
