### ISSUE TITLE
Rancher generating invalid docker-compose file when using a volume driver

### ISSUE THREAD

**Issue by Ramblurr** [rancher/rancher#9485]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: rancher/net:v0.11.3
network-services: rancher/dns:v0.15.1
scheduler: v0.8.2
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:22 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:16:12 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
Debian 9 Stretch
4.9.0-3-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

`bare metal`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

`single node rancher host bound mysql volume`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

`cattle`

**Steps to Reproduce:**

This issue is related to #7894, however it deals with the exported docker-compose files generated by rancher.

1. Create a convoy volume (though is probably isn't specific to convoy, its just a convenient driver to use)
2. Using the rancher UI, create a stack and a service with a volume, here's my actual case (using the sonatype/nexus3 image)
![rancher](https://user-images.githubusercontent.com/14830/28626266-d26a865e-721e-11e7-9b8d-69668642d2b3.png)
3. Create the service
4. View the docker compose config generated by rancher:

**Results:**

```yaml
version: '2'
volumes:
  data-nexus3:
    external: true
    driver: convoy-hdd
services:
  nexus3:
    image: sonatype/nexus3
    stdin_open: true
    network_mode: bridge
    volumes:
    - data-nexus3:/nexus-data
    tty: true
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.container.pull_image: always
```

Notice the `external: true` under the main `volumes` section, that is not allowed [according to the docker compose docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#/external).

This means the docker compose generated by rancher is invalid, and can't be used elsewhere.

When you try to launch a service with an external volume, rancher hangs in the starting state forever.

![rancher](https://user-images.githubusercontent.com/14830/28671878-6f7a70de-72de-11e7-9234-df2aa9b0da3a.png)
![rancher](https://user-images.githubusercontent.com/14830/28671897-7ec57ff2-72de-11e7-83b2-43f48c5d65cd.png)
