### ISSUE TITLE
Stack export for secrets in long syntax is not successful

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9501]
**Rancher versions:**
rancher/server:v1.6.6-rc4

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a stack using CLI with secrets in long syntax as below. File secretvalue should contain the secret
```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
      - source: mylongsecret
        target: mylongsecretincontainer
        uid: '104'
        gid: '103'
        mode: 444
secrets:
  mylongsecret:
    file: ./secretvalue
```
OR Precreate a secret in UI and use it in the yml file to create a new stack. Example below:
```
version: '2'
services:
  newtest:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
      - source: mysecret
        target: mysecretincontainer
        uid: '0'
        gid: '0'
        mode: 444
        name: mysecret
        secretId: 1
secrets:
  mysecret:
    external: true
```

2. After the stack creation succeeds,  create another stack using the exported config
Exported config below:
docker-compose.yml

```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
    - mode: '444'
      uid: '104'
      gid: '103'
      source: mylongsecret
      target: mylongsecretincontainer
secrets:
  mylongsecret:
    external: 'true'
```
Rancher-compose.yml
```
version: '2'
services:
  test:
    scale: 1
    start_on_create: true

```
3. Stack creation using the exported config fails. Logs from the server below:
```
time="2017-07-27T22:46:08Z" level=info msg="Starting rancher-compose-executor" version=v0.14.12 
time="2017-07-27T22:46:09Z" level=info msg="Initializing event router" workerCount=250 
time="2017-07-27T22:46:09Z" level=info msg="Connection established" 
time="2017-07-27T22:46:09Z" level=info msg="Starting websocket pings" 
time="2017-07-27T22:47:21Z" level=info msg="Stack Create Event Received" eventId=8073c77e-f1a7-415e-973b-c4f69388bc39 resourceId=1st11 
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 49 [running]:
github.com/rancher/rancher-compose-executor/config.parseValidTypesFromSchema(0xc4204b0c90, 0xc42000a4c0, 0x15, 0x0, 0xc42000a4c0, 0x15)
	/go/src/github.com/rancher/rancher-compose-executor/config/schema_helpers.go:72 +0x73e
github.com/rancher/rancher-compose-executor/config.oneOfMessage(0xc4201a3950, 0xc4204b0c90, 0xd3dea0, 0xc42046cfc0, 0xd3d920, 0xc42046cf80, 0x0, 0x4f28bf)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:162 +0x5d6
github.com/rancher/rancher-compose-executor/config.generateErrorMessages(0xc4201a3950, 0xc4204b0c90, 0xc4204a9960, 0xc420101d90, 0xc4204a9960)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:258 +0x1069
github.com/rancher/rancher-compose-executor/config.validateV2(0xc4204b0b10, 0x0, 0xc4204b0c60)
	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:222 +0x13f
github.com/rancher/rancher-compose-executor/config.MergeServicesV2(0xc4204dede0, 0xd34420, 0xc42000c308, 0xd343e0, 0xd8b908, 0x0, 0x0, 0xc4204b0b10, 0xc, 0xc4204b0240, ...)
	/go/src/github.com/rancher/rancher-compose-executor/config/merge_v2.go:13 +0x43
github.com/rancher/rancher-compose-executor/config.Merge(0xc4204dede0, 0xd34420, 0xc42000c308, 0xd343e0, 0xd8b908, 0x0, 0x0, 0x0, 0x0, 0xc4204c9f20, ...)
	/go/src/github.com/rancher/rancher-compose-executor/config/merge.go:167 +0x116b
github.com/rancher/rancher-compose-executor/project.(*Project).load(0xc4201be2d0, 0x0, 0x0, 0xc4204d38c0, 0x102, 0x120, 0xc420014ba0, 0xc4204b01e0)
	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:166 +0x156
github.com/rancher/rancher-compose-executor/project.(*Project).Parse(0xc4201be2d0, 0xc4201be2d0, 0x30)
	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:97 +0x15b
github.com/rancher/rancher-compose-executor/rancher.NewProject(0xc4204dda00, 0xc4204b0060, 0xc420395a38, 0x2)
	/go/src/github.com/rancher/rancher-compose-executor/rancher/project.go:35 +0x26d
github.com/rancher/rancher-compose-executor/executor/handlers.constructProject(0xc4200185c0, 0xc42007c000, 0xc4201eff60, 0x1d, 0xc420016012, 0x14, 0xc420018092, 0x28, 0xc4204de5c0, 0xc4200c80c0, ...)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/project.go:91 +0x4d2
github.com/rancher/rancher-compose-executor/executor/handlers.createStack(0xc4200185c0, 0xc4204d9e10, 0xc4202fa000, 0x1, 0xc4204d52f0)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:46 +0x166
github.com/rancher/rancher-compose-executor/executor/handlers.CreateStack(0xc4204d9e10, 0xc4202fa000, 0xc4204d0101, 0xc420045de8)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:22 +0x269
github.com/rancher/rancher-compose-executor/executor/handlers.WithTimeout.func1(0xc4204d9e10, 0xc4202fa000, 0xc4204d5050, 0x2d)
	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/common.go:54 +0x46
github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.doWork(0xc4204d9e10, 0xc420355b00, 0xc4202fa000, 0xd31560, 0xc4204c87d0)
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x28d
github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc42037b330, 0xe, 0xc4204d9e10, 0xc420355b00, 0xc4202fa000)
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
created by github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x18d



```

**Comment by deniseschannon** [comment]
In master, but not RC5. It will be in RC6.

**Comment by soumyalj** [comment]
Tested with rancher v1.6.6-rc6. Created stacks with secret in long format. Stack creation using the exported config was successful. The secret in the container was verified in /run/secrets directory.
Exported config example:
```
version: '2'
services:
  test:
    image: nginx
    stdin_open: true
    tty: true
    secrets:
    - mode: 444
      uid: '104'
      gid: '103'
      source: mylongsecret
      target: mylongsecretincontainer
secrets:
  mylongsecret:
    external: 'true'

```

```
version: '2'
services:
  test:
    scale: 1
    start_on_create: true

```
