### ISSUE TITLE
Rancher ingress for kubernetes routes to service on http, but fails on https

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#9514]
**Rancher versions:**
rancher/server: v1.6.3
rancher/agent: rancher/agent:v1.2.5

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1
ipsec: 0.1.1
network-services: v0.2.2
scheduler: rancher/k8s:v1.6.6-rancher1-4
kubernetes (if applicable): rancher/k8s:v1.6.6-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Ubuntu 16.04.2 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with RDS db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
kubernetes 

**Steps to Reproduce:**
Apply this ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    io.rancher.scheduler.global: "true"
spec:
  backend:
    serviceName: nginx
    servicePort: 80
  rules:
  - host: alertmanager-qa.yourdomain.com
    http:
      paths:
      - backend:
          serviceName: k8s-alertmanager
          servicePort: 9093
```

**Results:**
Navigating to `https://alertmanager-qa.yourdomain.com` routes to default backend service `nginx`.  Navigating to `http://alertmanager-qa.yourdomain.com` routes to correct service.
