### ISSUE TITLE
Volume driver external option can't use variables from Rancher-Compose questions

### ISSUE THREAD

**Issue by emcniece** [rancher/rancher#9536]
**Rancher versions:**
rancher/server: `1.6.0`
rancher/agent: `1.2.2`

**Infrastructure Stack versions:**
healthcheck: `v0.3.1`
ipsec: `rancher/net:v0.11.2`
network-services: `rancher/dns:v0.15.0`
scheduler: `v0.7.5`

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 50
 Running: 34
 Paused: 0
 Stopped: 16
Images: 55
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.24-rancher
Operating System: RancherOS v1.0.1
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.68 GiB
Name: emc2-dev-beast
ID: X5N3:JNKC:PEI3:WNLK:N3BE:25P2:GSAX:XZDM:TNF3:U3T4:ZOBX:KJCB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.9.24-rancher

```
NAME="RancherOS"
VERSION=v1.0.1
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.1
PRETTY_NAME="RancherOS v1.0.1"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Create an environment-level volume (named "files") via UI, then create a catalog item with a variable in the external property of a volume driver. [Sample item here](https://github.com/emcniece/rancher-catalog/tree/feat/wp-fpm-upgrade/templates/wp-php7-mysql/0). Attempt to start the stack through the Catalog UI.

docker-compose.yml:

```
version: '2'
services:
  ubuntu:
    image: ubuntu
    volumes:
    - files:/test
volumes:
  files:
    driver: rancher-nfs
    external: ${STORAGE_REMOTE}
```

rancher-compose.yml:

```
version: '2'
catalog:
  name: Test Ubuntu item
  version: 0.0.1
  questions:
    - variable: "STORAGE_REMOTE"
      description: "Determines storage scope. Stack=false, Environment=true"
      label: "External Remote Storage"
      required: true
      type: "boolean"
      default: false
services:
  ubuntu:
    scale: 1
```

**Expected Results:**

Stack gets created 🎉 

**Actual Results:**

Rancher displays an error: 

```
Error (yaml: unmarshal errors: line 3: cannot unmarshal !!str 'true' into struct { Name string })
```

**Other Notes:**

- Variable types tried: `boolean`, `enum`, `string`
- Works fine via CLI `docker-compose up` and `rancher-compose up`
- Works fine by pre-filling and pasting into manual stack creation input boxes

**Comment by genuss** [comment]
Try this:
```
volumes:
  files:
    driver: rancher-nfs
    external: '${STORAGE_REMOTE}'
```
Notice the `'` signs. It's yaml issue not rancher.
