### ISSUE TITLE
[rancher-dns]  POD  loosing its DNS record after it is assigned to a service

### ISSUE THREAD

**Issue by hristovpln** [rancher/rancher#9543]
**Rancher versions:**
rancher/server: v1.6.4
rancher/agent: v0.181.13

**Infrastructure Stack versions:**
healthcheck: 
ipsec: 
network-services: 
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (3.10.0) 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
After deploying microservices with:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: true
        microservice: cloud-config
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: cloud
        image: localhost:5000/cloud-config:9
        ports:
        - containerPort: 8888
          protocol: TCP
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: true
        microservice: eureka
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: eureka
        image: localhost:5000/discovery:9
        ports:
        - containerPort: 8761
          protocol: TCP
```

Each created POD is able to resolve the other. Trying with ping and nslookup to resolve the opposite pod. 

After deploying a service in front of each, they loose resolvability .
Deploying services with:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: true
    microservice: eureka
  name: eureka-svc
#  namespace: ms-second
spec:
  ports:
  - name: discovery-port
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    run: true
    microservice: eureka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: true
    microservice: cloud-config
  name: cloud-svc
spec:
  ports:
  - name: cloud-port
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: true
    microservice: cloud-config
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Results:**

After assigning a service in front the pod it looses its rancher.internal DNS record and you can no longer ping it from a test POD whether or not it is in the same namespace.
