### ISSUE TITLE
Allocation error does not include resource constraints (regression #8636)

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#9554]
**Rancher versions:**
Rancher | v1.6.5
Cattle | v0.182.1
User Interface | v1.6.9
Rancher CLI | v0.6.2
Rancher Compose | v0.12.5
Scheduler v0.8.2
Cattle

**Steps to Reproduce:**
See test case https://github.com/rancher/rancher/issues/8636#issuecomment-305037229

On a setup with one host. h1 has label foo=true set.
Created a service test1 with exposed host port 80.
Then created another stack as below:

```
version: '2'
services:
  test:
    image: ubuntu:14.04
    tty: true
    ports:
    - 8086:8086/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: foo=true
```

Same problem when no host label constraint is used:

```
version: '2'
services:
  test:
    image: ubuntu:14.04
    tty: true
    ports:
    - 80:80/tcp
```

**Results:**

The error message does not include the constraints:

`Allocation failed: No healthy hosts with sufficient resources available)`

**Expected Result:**

Error message includes the constraints (See test case https://github.com/rancher/rancher/issues/8636#issuecomment-305037229).

` (Failed to allocate instance [container:1i82]: Bad instance [container:1i82] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [80:80/tcp portReservation, 1 instanceReservation])`

<img width="900" alt="allocation-error" src="https://user-images.githubusercontent.com/3813921/28873969-2b2c3cd0-7790-11e7-83fb-bfbb585f2dd7.png">

**Comment by soumyalj** [comment]
Tested with v1.6.8-rc1. This issue happens on a setup with one active host and another inactive host. Error message does not include all the constraints
<img width="1232" alt="screen shot 2017-08-09 at 1 39 08 pm" src="https://user-images.githubusercontent.com/18536626/29142899-31be2e5a-7d08-11e7-8dcd-858cfafec8e9.png">

**Comment by cjellick** [comment]
available on v1.6-development. will be in rc5

**Comment by soumyalj** [comment]
Tested with v1.6-development.
1. Create a two host setup and set one host label as foo=true. Make the other host inactive
2. Create a service with host port setting to 8086 container port 80 and label foo=true
3. Create another service stack as below:
```
version: '2'
services:
  test:
    image: ubuntu:14.04
    tty: true
    ports:
    - 8086:8086/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: foo=true
``` 
Container creation fails and the error message includes all the constraints:
<img width="1311" alt="screen shot 2017-08-22 at 5 15 32 pm" src="https://user-images.githubusercontent.com/18536626/29593287-54b9869c-875e-11e7-88c7-e302b5e59dc4.png">
