### ISSUE TITLE
gitlab-multi-runner from catalog very high I/O disk wait

### ISSUE THREAD

**Issue by Beenhakker** [rancher/rancher#9620]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 
network-services: 0.11.3
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.05CE

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.0.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Run Gitlab CI server, than run a gitlab-multi-runner from the catalog. Use a Docker build template (I even added the "DOCKER_DRIVER: overlay" option (speeds it up).

**Results:**
 Often the initial build is quick, but after that you get gigantic I/O disk waits, for unknown reason. The agent the container runs on disconnects, and the whole environment goes down.

**Comparison**
I set up a single Gitlab-runner (gitlab/gitlab-runner:alpine) and register the node. Now my builds are running fine.

**Comment by boTux** [comment]
I reproduced it on my environment.
Rancher version 
on Container Linux by CoreOS 1465.7.0 (Ladybug)
with latest version of gitlab.

The problem came when I added in one of my gitlab-ci.yml the "DOCKER_DRIVER: overlay" .

```yml
test:codequality:
  image: docker:latest
  stage: test
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]
```

docker events logs : [log-docker-events-crash.txt](https://github.com/rancher/rancher/files/1317582/log-docker-events-crash.txt)

Other jobs without overlay drivers works fine.

Any idias ?
