### ISSUE TITLE
docker-compose variable interpolation doesn't support defaults

### ISSUE THREAD

**Issue by frankh** [rancher/rancher#9648]
**Rancher versions:**
rancher/server: v1.6.6
rancher/agent: v1.2.5
rancher/cli: v0.6.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.3 (4.9.34)

**Steps to Reproduce:**

Use rancher cli to create a stack from a docker-compose file, with something like:

```
version: "2"
services:
  test:
    image: ubuntu:${VERSION:-xenial}
```

**Results:**

Rancher cli fails with error message:

```Failed to read project: Invalid interpolation format for key \"image\": \"ubuntu:${VERSION:-xenial}\"```

I would expect it to sub in the VERSION env variable, or use the default "xenial" if not provided.

See: https://docs.docker.com/compose/compose-file/#variable-substitution

**Comment by joshwget** [comment]
You can use [templating](http://rancher.com/docs/rancher/v1.6/en/cli/variable-interpolation/#templating) to accomplish the same thing in the meantime.

**Comment by stefanlasiewski** [comment]
Any update on this? It seems like an important missing element for Compose files:

```
version: '2'
services:
  web:
    image: nginx
    ports:
    - "${PUBLIC_PORT:-60000}:8080"
```

```
$ export PUBLIC_PORT=60000
$ rancher up --render 
ERRO[0000] Could not parse config for project variables-test : Invalid interpolation format for key "ports": "${PUBLIC_PORT:-8080}:8080" 
FATA[0000] Failed to read project: Invalid interpolation format for key "ports": "${PUBLIC_PORT:-8080}:8080" 
```

Docker Compose v2.1 will support this, but I need to specify `version: '2.1'` instead of just `version: '2'`.

```
version: '2.1'
services:
  web:
    image: nginx
    ports:
      - "${PUBLIC_PORT:-60000}:8080"
```

```
$ export PUBLIC_PORT=8080
$ docker-compose config 
services:
  web:
    image: nginx
    ports:
    - 8080:8080/tcp
version: '2.1'
```
