### ISSUE TITLE
Networking Issues in Kubernetes Immediately Following Upgrades

### ISSUE THREAD

**Issue by Joeskyyy** [rancher/rancher#9678]
This is an issue requested from @leodotcloud concerning networking issues and kubernetes we've observed in our environments.

Issues seen:
* Ingress controllers are unable to be communicated with. There appears to be a "macsync" issue which is often remedied with a reboot, but not 100% of the time.
* Occasional ARP cache issues where network communicates do not transmit properly, which has caused a catastrophic etcd failure in dev.

Steps to Reproduce:

* Create a new rancher stack, (e.g. 1.6.4) and install kubernetes (In my example, 1.6)
* Be sure to disable the rancher ingress controller, otherwise it gets in the way.
* After the cluster is created create a traefik ingress daemonset
* Once the traefik ingress is working and responding appropriately, perform an upgrade to rancher and kubernetes (in my example 1.6.5 and its upgrades caused a failure, as well as a test from 1.6.5 to 1.6.6 and k8s 1.7)
* Ingress controllers will stop working (sometimes a select few, sometimes all, but always at least one). The container will be running, and listening on port 80, but not doing anything. You cannot netcat, curl, etc, to it.
* Network manager container on the host for which the ingress controller will have error messages similar to the following:

```
8/14/2017 3:54:09 PMtime="2017-08-14T22:54:09Z" level=error msg="macsync: for container: {traefik-ingress-controller-7g72s 192.168.249.66 02:ae:9c:da:8d:76 [192.168.249.66] [0.0.0.0:80:80/tcp 0.0.0.0:8080:8080/tcp]    map[io.rancher.container.display_name:traefik-ingress-controller-7g72s io.rancher.container.network:true io.rancher.stack.name:kube-system pod-template-generation:1 controller-revision-hash:546381873 io.kubernetes.container.name:POD io.kubernetes.pod.namespace:kube-system k8s-app:traefik-ingress-lb annotation.kubernetes.io/config.seen:2017-08-09T17:02:35.572280667Z annotation.kubernetes.io/config.source:api io.kubernetes.pod.name:traefik-ingress-controller-7g72s io.kubernetes.pod.uid:8a986fdf-7d24-11e7-a9de-02ae9cca6e8d io.rancher.service.launch.config:io.rancher.service.primary.launch.config name:traefik-ingress-lb annotation.kubernetes.io/created-by:{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"DaemonSet\",\"namespace\":\"kube-system\",\"name\":\"traefik-ingress-controller\",\"uid\":\"a8116811-7c67-11e7-b5f0-02ae9c26e2c6\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"355234\"}}\n io.kubernetes.docker.type:podsandbox io.rancher.service.deployment.unit:8a986fdf-7d24-11e7-a9de-02ae9cca6e8d] 0 1ab57e95-b7d7-4ad1-a7a5-3dabf8cff02d 3128ecf0-3e08-4345-b463-7bb4bf625ee7 running  af3d191aa9bf463be2601ae0076dbd756556f9c71f3e403a9b40a9395279fed2 1 0 0 [169.254.169.250] [rancher.internal] []  f80bce3a-404a-418d-abbc-a10b66f4cbe3 map[] false 26fc4bd1-8a7b-4950-8eef-b1fbd5cfa090 {0 0 0  0 0}}, could not lookup interface: Link not found"
8/14/2017 3:54:09 PMtime="2017-08-14T22:54:09Z" level=error msg="macsync: error syncing MAC addresses for the first tiime: in name ns for container af3d191aa9bf463be2601ae0076dbd756556f9c71f3e403a9b40a9395279fed2: Link not found"

```

Traefik yaml:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: traefik-ingress-lb
  name: traefik-ingress-controller
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      containers:
      - args:
        - -d
        - --web
        - --kubernetes
        image: traefik
        imagePullPolicy: Always
        name: traefik-ingress-lb
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: admin
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
```

**Comment by leodotcloud** [comment]
Assigning the issue to you as requested @alena1108 

Summary:

```
apiVersion: v1
kind: Pod
metadata:
  name: full
spec:
  containers:
    - name: full
      image: nginx
  hostNetwork: true
```

The above yaml file will launch a pod in host network, but in the UI/metadata you can see this container is registered on the managed network. Since it's on the managed network, we try to do macsync, etc and doing those incorrectly on a container which doesn't belong to managed network can have random side effects.

**Comment by alena1108** [comment]
@leodotcloud I'll add the missing logic to not place k8s hostNetwork=true container on the managed network, but I am curious how it even worked before? This bug in k8s pods sync has been in rancher for a long time, yet it somehow worked? Did anything got changed in macsync logic on the network manager side?

**Comment by deniseschannon** [comment]
Available with `rancher/server:v1.6.8-rc4` and kubernetes `v1.7.4-rancher1-etcdv2` using image `rancher/kubernetes-agent:v0.6.5`

**Comment by sangeethah** [comment]
@galal-hussein Can you also add the validation to check connectivity for the existing K8s host network test case?

**Comment by omegarus** [comment]
With rancher 1.6.7 installed from scratch I have similar issue but without observing errro in network manager container. ```netstat -tulpn``` on host shows: 
```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      18957/traefik
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      18957/traefik
```
But if you try connect to host:80 you will get icmp with "Host ureachable" error.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.8-rc5

Fresh installation of kubernetes on this rancher version and deploying host networked pod didn't reveal any issues and i can see that the pod didn't get a 10.42.x.x ip and not in the Rancher managed network.

However when upgrading from v1.6.7 to v1.6.8-rc5 i can see that the old pod still got the 10.42.x.x ip and  its networking seems to be broken, pod used:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: sangeetha/testnewhostrouting
    ports:
    - containerPort: 80
```

i can't connect to the host's ip anymore.
