### ISSUE TITLE
[rancher-abs] Cannot select disk category and disk size through "add service" page.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9808]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: VPC

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Add stack.
3. Add server.
4. Set volume and volume driver.

**Results:**
1. User only can set the abs volume driver image, volume name and volume path.
2. But they can't select disk category and disk size. 

**expectation**
1. We will give out the disk category and disk size options according to user's Region and Zone and let users to select them.

@yasker  @thxCode 
#9194

**Comment by thxCode** [comment]
The user can add a custom volume by accessing **"INFRASTRUCTURE" - "Storage" - "Add Volume"** on the console. You can config the driver options:
``` yaml
[...]
volumes:
 <volume name>:
    driver: rancher-abs
    driver_opts:
      diskName: <a name for disk>
      size: <20 default>
      diskCategory: <cloud_ssd default>
      snapshot_id: <disk snapshot id>
```
