### ISSUE TITLE
Healthcheck params have no defaults, produce broken config if not set

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#9840]
rancher/server: v1.6.8 (not new, but apparently worked in 1.1/1.2 timeframe)

The 6 health check interval, threshold, and timeout fields have no default values.. If a service is created with a `health_check` that doesn't specify them, the resulting config gets `inter 0` on the server lines, which is invalid and makes haproxy fail to start.

The fields should have appropriate minimums and defaults so that you can't create this situation.

**Steps to Reproduce:**
Add a service as below, then add it as the target of a balancer:

```
version: '2'
services:
  foo:
    image: nginx
    scale: 1
    start_on_create: true
    health_check:
      port: 80
      strategy: none
      request_line: GET "/" "HTTP/1.0"
```

**Results:**
haproxy.cfg:
```
backend 90_
...
server af6f9200a038f4b9ef06e42530a1e2e093c21b14 10.42.71.135:80  check port 80 i
nter 0 rise 0 fall 0
```
Startup error:

```
time="2017-09-07T06:14:03Z" level=error msg="Failed to apply lb config on provider: error reloading  -- reloading haproxy config with the new config changes
 * Reloading haproxy haproxy\n[ALERT] 249/061403 (50) : parsing [/etc/haproxy/haproxy.cfg:50]: invalid value 0 for argument 'inter' of server 
```
