### ISSUE TITLE
rancher-compose.yml does not apply LB config to stack when using rancher-compose CLI

### ISSUE THREAD

**Issue by DoingItNow** [rancher/rancher#9874]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec:
network-services:
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS Linux 7 (Core) 3.10.0-514.26.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher web server, 4 nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Refer to a sample docker-compose.yml and rancher-compose.yml below
docker-compose.yml
```
version: '2'
services:
  nginx:
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
      io.rancher.container.pull_image: always
    image: nginx
    command: nginx -g 'daemon off;'
  
  lb:
    image: rancher/load-balancer-service
    # internal load balancer
    ports:
      - 443
      - 80
```

rancher-compose.yml
```
version: '2'
services:
  nginx:
    scale: 2
    start_on_create: true
  lb:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: nginx
        source_port: 443
        target_port: 80
      - protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```
run a rancher-compose up command

**Results:**
Stack is created with the nginx service with 2 nginx containers but the LB service did not create any balancing rules. The rancher-compose.yml generated by rancher can be seen below

```
version: '2'
services:
  nginx:
    scale: 2
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules: []
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
```
