### ISSUE TITLE
Unable to access the grafana Dashboard installed during the k8s cluster setup using Rancher

### ISSUE THREAD

**Issue by Parth6288** [rancher/rancher#9898]
**Rancher versions:**
rancher/server:  latest release
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.11.9
network-services: v0.7.8
scheduler: v0.8.2
kubernetes (if applicable): v1.7.4-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 38
 Running: 37
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.359 GiB
Name: Host1
ID: MH52:YS7X:TNT2:ZQU2:FSMI:74BB:5IWV:P5HT:EUS4:24DD:4BIY:K3LX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure/Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher, internalDB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Just install the rancher server and add hosts to it. Try accessing the grafana-dashboard using the url found using the kubectl cluster-info command.
**Results:**
The Dashboard is not available and just give the screen as attached screenshot. 
![rancherdashboard](https://user-images.githubusercontent.com/16204776/30534130-62ac5d0c-9c7a-11e7-992d-367371fb290d.JPG)

Thanks.

**Comment by KevinMaschke** [comment]
Same issue here :(

**Comment by cjellick** [comment]
This is a known issue. There is a work around that involves modifying some service. @aemneina do you have that work around handy?

**Comment by aemneina** [comment]
This should do the trick on a vanilla setup:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-system
spec:
  rules:
    - host: yourdomain.example.com
      http:
        paths:
          - backend:
              serviceName: monitoring-grafana
              servicePort: 80
            path: /
```
