### ISSUE TITLE
Importing exported stack compose.yml fails on v2 preview

### ISSUE THREAD

**Issue by ianmjones** [rancher/rancher#9979]
**Steps:**
1. Create a stack with 2 services, both using global 1 container per host scale.
1. Export stack to file (or copy to clipboard).
1. Delete existing stack.
1. Go to Containers menu and click "import compose.yml".
1. Set name for new stack, pick or copy in compose.yml from 2nd step.
1. Click "Create".

**Expected:**
Nice shiny new stack.

**Actual:**
Error "Could not parse config: Unsupported config option for goalmonitor service: 'scale_increment' Unsupported config option for goalmonitor-lb service: 'scale_increment'".

No service or load balancer created, just an empty stack.

It's also impossible to "Delete" this new stack, get confirmation to do so but it never actually goes away.

**Example compose.yml:**
```
version: "2"
services:
  goalmonitor:
    image: registry.gitlab.com/goalmonitor/goalmonitor-server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: "true"
    stop_signal: SIGTERM
    restart: always
    stdin_open: true
    tty: true
    scale_increment: 1
  goalmonitor-lb:
    image: rancher/lb-service-haproxy:v0.8.1
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: "true"
      io.rancher.scheduler.global: "true"
    ports:
    - 8888:8888/tcp
    stop_signal: SIGTERM
    restart: always
    lb_config:
      port_rules:
      - source_port: 8888
        protocol: http
        service: goalmonitor
        target_port: 8888
        priority: 1
    health_check:
      healthy_threshold: 2
      initializing_timeout: 60000
      interval: 2000
      port: 42
      response_timeout: 2000
      unhealthy_threshold: 3
    scale_increment: 1
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha7` Cattle: `v0.184.8` UI: `v2.0.8` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`stack.index`|
